// Ngân hàng câu VIẾT TAY — phần CƠ HỌC (Vật lí 8 · KHTN 8, KNTT)
// Mỗi phần tử: [chương, text, [đáp án đúng, nhiễu 1, nhiễu 2, nhiễu 3], why]
// Chương: klr (khối lượng riêng) · apr (áp suất bề mặt) · apl (áp suất chất lỏng)
//         akq (áp suất khí quyển) · arc (lực đẩy Archimedes) · mom (moment lực – đòn bẩy)
export const CO = [
/* ───────── KHỐI LƯỢNG RIÊNG ───────── */
['klr', 'Khối lượng riêng của một chất cho ta biết điều gì?',
 ['Khối lượng của một đơn vị thể tích (1 m<sup>3</sup>) chất đó', 'Trọng lượng của toàn bộ vật làm bằng chất đó', 'Thể tích của 1 kg chất đó', 'Khối lượng của vật khi cân trong không khí'],
 'Khối lượng riêng D = m/V là khối lượng của một đơn vị thể tích chất đó, ví dụ 1 m<sup>3</sup> nước có khối lượng 1000 kg.'],
['klr', 'Đơn vị đo khối lượng riêng trong hệ SI là',
 ['kg/m<sup>3</sup>', 'N/m<sup>3</sup>', 'kg·m<sup>3</sup>', 'kg/m<sup>2</sup>'],
 'D = m/V nên đơn vị là kg/m<sup>3</sup> (hoặc g/cm<sup>3</sup>, g/mL). N/m<sup>3</sup> là đơn vị của trọng lượng riêng.'],
['klr', '1 g/cm<sup>3</sup> bằng bao nhiêu kg/m<sup>3</sup>?',
 ['1000 kg/m<sup>3</sup>', '1 kg/m<sup>3</sup>', '100 kg/m<sup>3</sup>', '0,001 kg/m<sup>3</sup>'],
 '1 g = 0,001 kg; 1 cm<sup>3</sup> = 0,000001 m<sup>3</sup>. Vậy 1 g/cm<sup>3</sup> = 0,001 : 0,000001 = 1000 kg/m<sup>3</sup>.'],
['klr', 'Công thức tính khối lượng riêng là',
 ['D = m/V', 'D = m·V', 'D = V/m', 'D = P/V'],
 'Khối lượng riêng bằng khối lượng chia cho thể tích: D = m/V. P/V là trọng lượng riêng d.'],
['klr', 'Nói "khối lượng riêng của nước là 1000 kg/m<sup>3</sup>" có nghĩa là',
 ['1 m<sup>3</sup> nước có khối lượng 1000 kg', '1 lít nước có khối lượng 1000 kg', '1 kg nước có thể tích 1000 m<sup>3</sup>', '1 m<sup>3</sup> nước có trọng lượng 1000 N'],
 'D = 1000 kg/m<sup>3</sup>: mỗi mét khối nước có khối lượng 1000 kg (tức 1 lít nước nặng 1 kg).'],
['klr', 'Hai vật đặc có cùng thể tích, vật 1 bằng sắt (D = 7800 kg/m<sup>3</sup>), vật 2 bằng nhôm (D = 2700 kg/m<sup>3</sup>). Khối lượng vật 1 so với vật 2',
 ['lớn hơn, khoảng 2,9 lần', 'nhỏ hơn, khoảng 2,9 lần', 'bằng nhau vì cùng thể tích', 'lớn hơn 5100 lần'],
 'm = D·V, cùng V nên m<sub>1</sub>/m<sub>2</sub> = D<sub>1</sub>/D<sub>2</sub> = 7800/2700 ≈ 2,9.'],
['klr', 'Hai vật đặc có cùng khối lượng, một bằng chì (11 300 kg/m<sup>3</sup>), một bằng nhôm (2700 kg/m<sup>3</sup>). Nhận xét nào đúng?',
 ['Vật nhôm có thể tích lớn hơn vật chì', 'Vật chì có thể tích lớn hơn vật nhôm', 'Hai vật có thể tích bằng nhau', 'Không so sánh được vì chưa biết hình dạng'],
 'V = m/D, cùng m nên chất có D nhỏ hơn (nhôm) chiếm thể tích lớn hơn.'],
['klr', 'Cắt một thanh đồng đồng chất thành hai phần bằng nhau. Khối lượng riêng của mỗi phần',
 ['không thay đổi so với thanh ban đầu', 'giảm đi một nửa', 'tăng gấp đôi', 'không xác định được'],
 'Khối lượng riêng là đặc trưng của chất, không phụ thuộc kích thước vật. Khối lượng và thể tích đều giảm nửa nên D = m/V không đổi.'],
['klr', 'Để xác định khối lượng riêng của một hòn đá nhỏ, cần dùng bộ dụng cụ nào?',
 ['Cân và bình chia độ', 'Thước và cân', 'Bình chia độ và nhiệt kế', 'Lực kế và thước'],
 'Cân đo khối lượng m, bình chia độ đo thể tích V (bằng phần nước dâng lên), rồi tính D = m/V.'],
['klr', 'Thứ tự các bước đúng khi đo khối lượng riêng của một viên sỏi bằng cân và bình chia độ là',
 ['Cân sỏi → đổ nước, đọc V<sub>1</sub> → thả sỏi, đọc V<sub>2</sub> → tính D = m/(V<sub>2</sub> − V<sub>1</sub>)', 'Đổ nước, đọc V<sub>1</sub> → tính D = m/V<sub>1</sub> → cân sỏi', 'Thả sỏi vào bình → đọc V<sub>2</sub> → tính D = m/V<sub>2</sub>', 'Cân sỏi → đo chiều dài sỏi bằng thước → D = m/l'],
 'Thể tích sỏi bằng phần nước dâng lên V<sub>2</sub> − V<sub>1</sub>; sau đó D = m/(V<sub>2</sub> − V<sub>1</sub>).'],
['klr', 'Khi đo khối lượng riêng của một chất lỏng bằng cân và bình chia độ, vì sao phải cân bình rỗng trước?',
 ['Để trừ khối lượng bình, lấy đúng khối lượng chất lỏng', 'Để kiểm tra cân có chính xác không', 'Để biết thể tích của bình', 'Không cần cân bình rỗng'],
 'Khối lượng chất lỏng = khối lượng (bình + chất lỏng) − khối lượng bình rỗng.'],
['klr', 'Sắp xếp theo khối lượng riêng tăng dần: nước (1000), dầu ăn (800), sắt (7800), nhôm (2700) (đơn vị kg/m<sup>3</sup>).',
 ['Dầu ăn < nước < nhôm < sắt', 'Nước < dầu ăn < nhôm < sắt', 'Dầu ăn < nước < sắt < nhôm', 'Sắt < nhôm < nước < dầu ăn'],
 'So sánh số: 800 < 1000 < 2700 < 7800.'],
['klr', 'Khối lượng riêng của một vật đặc KHÔNG phụ thuộc vào',
 ['hình dạng và kích thước của vật', 'chất cấu tạo nên vật', 'nhiệt độ của vật', 'trạng thái (rắn, lỏng, khí) của chất'],
 'D là đặc trưng của chất ở một điều kiện; vật to hay nhỏ, tròn hay vuông không làm D thay đổi.'],
['klr', 'Nước đá nổi trên mặt nước vì',
 ['khối lượng riêng của nước đá nhỏ hơn của nước', 'nước đá nhẹ hơn mọi vật khác', 'nước đá không thấm nước', 'khối lượng riêng của nước đá lớn hơn của nước'],
 'D nước đá ≈ 900 kg/m<sup>3</sup> < 1000 kg/m<sup>3</sup> nên nước đá nổi.'],
['klr', 'Hộp sữa ghi "1 lít", cân được khối lượng sữa là 1,03 kg. Khối lượng riêng của sữa là',
 ['1030 kg/m<sup>3</sup>', '1,03 kg/m<sup>3</sup>', '103 kg/m<sup>3</sup>', '10 300 kg/m<sup>3</sup>'],
 '1 lít = 0,001 m<sup>3</sup>; D = 1,03 : 0,001 = 1030 kg/m<sup>3</sup>.'],
['klr', 'Kim loại nào sau đây có khối lượng riêng lớn nhất?',
 ['Vàng (19 300 kg/m<sup>3</sup>)', 'Chì (11 300 kg/m<sup>3</sup>)', 'Bạc (10 500 kg/m<sup>3</sup>)', 'Đồng (8900 kg/m<sup>3</sup>)'],
 'Trong các kim loại đã cho, vàng có D lớn nhất, 19 300 kg/m<sup>3</sup>.'],
['klr', 'Một lít dầu ăn và một lít nước, cái nào có khối lượng lớn hơn?',
 ['Nước, vì khối lượng riêng của nước lớn hơn', 'Dầu, vì dầu đặc hơn', 'Bằng nhau vì cùng thể tích', 'Không so sánh được'],
 'Cùng V = 1 lít, m = D·V; D nước (1000) > D dầu (≈ 800) nên nước nặng hơn.'],
['klr', 'Khẳng định nào sau đây đúng?',
 ['Khối lượng riêng của một chất không phụ thuộc khối lượng của vật', 'Vật có khối lượng lớn hơn thì khối lượng riêng lớn hơn', 'Vật có thể tích lớn hơn thì khối lượng riêng nhỏ hơn', 'Hai vật cùng khối lượng thì cùng khối lượng riêng'],
 'D chỉ phụ thuộc chất và điều kiện (nhiệt độ). Vật to nhỏ khác nhau nhưng cùng chất thì cùng D.'],
['klr', 'Khối lượng riêng của không khí khoảng 1,29 kg/m<sup>3</sup>. Khối lượng không khí trong căn phòng 5 m × 4 m × 3 m là',
 ['77,4 kg', '7,74 kg', '774 kg', '46,5 kg'],
 'V = 5 × 4 × 3 = 60 m<sup>3</sup>; m = D·V = 1,29 × 60 = 77,4 kg.'],
['klr', 'Một quả cầu sắt có khối lượng 3,9 kg và thể tích 1 dm<sup>3</sup>. Biết D<sub>sắt</sub> = 7800 kg/m<sup>3</sup>. Kết luận nào đúng?',
 ['Quả cầu rỗng, phần rỗng có thể tích 0,5 dm<sup>3</sup>', 'Quả cầu đặc', 'Quả cầu rỗng, phần rỗng có thể tích 0,25 dm<sup>3</sup>', 'Quả cầu rỗng, phần rỗng có thể tích 1 dm<sup>3</sup>'],
 'Thể tích sắt thực: 3,9 : 7800 = 0,0005 m<sup>3</sup> = 0,5 dm<sup>3</sup> < 1 dm<sup>3</sup> nên rỗng; phần rỗng 1 − 0,5 = 0,5 dm<sup>3</sup>.'],
['klr', 'Hòn đá có khối lượng 260 g. Bình chia độ đựng 50 cm<sup>3</sup> nước, thả hòn đá vào thì mực nước lên 150 cm<sup>3</sup>. Khối lượng riêng của đá là',
 ['2,6 g/cm<sup>3</sup>', '1,73 g/cm<sup>3</sup>', '5,2 g/cm<sup>3</sup>', '26 g/cm<sup>3</sup>'],
 'V = 150 − 50 = 100 cm<sup>3</sup>; D = 260 : 100 = 2,6 g/cm<sup>3</sup>.'],
['klr', 'Đồng có khối lượng riêng 8,9 g/cm<sup>3</sup>. Đổi ra kg/m<sup>3</sup> ta được',
 ['8900 kg/m<sup>3</sup>', '89 kg/m<sup>3</sup>', '0,0089 kg/m<sup>3</sup>', '890 kg/m<sup>3</sup>'],
 '1 g/cm<sup>3</sup> = 1000 kg/m<sup>3</sup> nên 8,9 g/cm<sup>3</sup> = 8900 kg/m<sup>3</sup>.'],
['klr', 'Đặt 1 kg bông và 1 kg sắt lên hai đĩa cân, cân thăng bằng. Nhận xét nào đúng?',
 ['Khối lượng bằng nhau nhưng thể tích bông lớn hơn nhiều', 'Sắt nặng hơn bông', 'Thể tích hai vật bằng nhau', 'Khối lượng riêng hai vật bằng nhau'],
 'Cùng m = 1 kg; D bông rất nhỏ nên V = m/D của bông lớn hơn nhiều.'],
['klr', 'Trộn 1 lít rượu (D = 800 kg/m<sup>3</sup>) với 1 lít nước (D = 1000 kg/m<sup>3</sup>), coi thể tích không đổi. Khối lượng riêng của hỗn hợp là',
 ['900 kg/m<sup>3</sup>', '1800 kg/m<sup>3</sup>', '800 kg/m<sup>3</sup>', '1000 kg/m<sup>3</sup>'],
 'm = 0,8 + 1 = 1,8 kg; V = 2 lít = 0,002 m<sup>3</sup>; D = 1,8 : 0,002 = 900 kg/m<sup>3</sup>.'],
['klr', 'Một chiếc vòng "vàng" có khối lượng 38,6 g, thể tích 4 cm<sup>3</sup>. Biết vàng nguyên chất có D = 19,3 g/cm<sup>3</sup>. Kết luận?',
 ['Không phải vàng nguyên chất vì D ≈ 9,65 g/cm<sup>3</sup>', 'Là vàng nguyên chất vì D = 19,3 g/cm<sup>3</sup>', 'Là vàng nguyên chất vì khối lượng đúng 38,6 g', 'Không kết luận được'],
 'D = 38,6 : 4 = 9,65 g/cm<sup>3</sup>, chỉ bằng nửa D của vàng nên đây là hợp kim hoặc vàng pha.'],
['klr', 'Đun nóng một lượng nước (chưa sôi), khối lượng riêng của nước sẽ',
 ['giảm vì thể tích tăng, khối lượng không đổi', 'tăng vì nước nóng hơn', 'không đổi vì khối lượng không đổi', 'tăng vì thể tích giảm'],
 'Nước nở ra khi nóng: V tăng, m không đổi nên D = m/V giảm.'],
['klr', 'Bình chia độ có 100 cm<sup>3</sup> nước. Thả 5 viên bi giống nhau vào thì mực nước là 120 cm<sup>3</sup>. Cân 5 viên bi được 156 g. Khối lượng riêng của bi là',
 ['7,8 g/cm<sup>3</sup>', '1,3 g/cm<sup>3</sup>', '31,2 g/cm<sup>3</sup>', '0,78 g/cm<sup>3</sup>'],
 'V của 5 bi = 20 cm<sup>3</sup>; D = 156 : 20 = 7,8 g/cm<sup>3</sup> (bi bằng sắt/thép).'],
['klr', 'Muốn đo thể tích của một vật rắn không bỏ lọt bình chia độ, ta dùng',
 ['bình tràn kết hợp bình chứa và bình chia độ', 'thước kẻ', 'cân đồng hồ', 'lực kế'],
 'Thả vật vào bình tràn đầy nước, nước tràn ra được hứng và đo bằng bình chia độ, đó chính là thể tích vật.'],
['klr', 'Khi đọc thể tích chất lỏng trong bình chia độ, phải đặt mắt',
 ['ngang với mực chất lỏng', 'cao hơn mực chất lỏng và nhìn xuống', 'thấp hơn mực chất lỏng và nhìn lên', 'ở vị trí bất kì'],
 'Đặt mắt ngang mực chất lỏng để tránh sai số do nhìn xiên.'],
['klr', 'Khối gỗ có khối lượng 2 kg, khối lượng riêng 800 kg/m<sup>3</sup>. Thể tích khối gỗ là',
 ['2,5 dm<sup>3</sup>', '1600 dm<sup>3</sup>', '0,4 dm<sup>3</sup>', '25 dm<sup>3</sup>'],
 'V = m/D = 2 : 800 = 0,0025 m<sup>3</sup> = 2,5 dm<sup>3</sup>.'],
['klr', 'Một vật đặc bằng nhôm và một vật đặc bằng sắt có cùng khối lượng riêng hay không?',
 ['Không, vì mỗi chất có khối lượng riêng riêng', 'Có, nếu hai vật cùng thể tích', 'Có, nếu hai vật cùng khối lượng', 'Có, nếu hai vật cùng hình dạng'],
 'Khối lượng riêng là đặc trưng của chất: nhôm 2700, sắt 7800 kg/m<sup>3</sup>, không phụ thuộc kích thước, hình dạng vật.'],
['klr', 'Một bình đựng đầy 500 g nước. Thay nước bằng dầu ăn (D = 0,8 g/cm<sup>3</sup>) đổ đầy bình, khối lượng dầu là',
 ['400 g', '500 g', '625 g', '800 g'],
 'V bình = 500 cm<sup>3</sup> (nước D = 1 g/cm<sup>3</sup>); m dầu = 0,8 × 500 = 400 g.'],

/* ───────── ÁP SUẤT TRÊN MỘT BỀ MẶT ───────── */
['apr', 'Áp lực là',
 ['lực ép có phương vuông góc với mặt bị ép', 'lực ép theo phương bất kì lên mặt bị ép', 'trọng lượng của vật', 'lực ma sát giữa vật và mặt tiếp xúc'],
 'Áp lực là lực ép vuông góc với mặt bị ép. Vật đặt trên mặt ngang thì áp lực bằng trọng lượng.'],
['apr', 'Công thức tính áp suất trên một bề mặt là',
 ['p = F/S', 'p = F·S', 'p = S/F', 'p = d·h'],
 'Áp suất bằng áp lực chia cho diện tích bị ép: p = F/S; đơn vị N/m<sup>2</sup> (Pa).'],
['apr', '1 kPa bằng',
 ['1000 Pa', '100 Pa', '10 Pa', '0,001 Pa'],
 'k (kilô) = 1000, nên 1 kPa = 1000 Pa = 1000 N/m<sup>2</sup>.'],
['apr', 'Cách nào sau đây KHÔNG làm tăng áp suất của vật lên mặt bị ép?',
 ['Tăng diện tích mặt bị ép, giữ nguyên áp lực', 'Tăng áp lực, giữ nguyên diện tích', 'Giảm diện tích mặt bị ép, giữ nguyên áp lực', 'Vừa tăng áp lực vừa giảm diện tích'],
 'p = F/S: tăng S thì p giảm.'],
['apr', 'Lưỡi dao, lưỡi kéo được mài mỏng để',
 ['giảm diện tích tiếp xúc, tăng áp suất', 'giảm áp lực cần dùng', 'tăng diện tích tiếp xúc', 'giảm ma sát'],
 'Cùng một lực tay, diện tích lưỡi càng nhỏ thì áp suất lên vật cắt càng lớn.'],
['apr', 'Xe tăng có bản xích rộng nhằm',
 ['tăng diện tích tiếp xúc để giảm áp suất, không bị lún', 'tăng áp suất lên mặt đất', 'chạy nhanh hơn', 'giảm trọng lượng xe'],
 'Xe rất nặng; bản xích rộng làm S lớn nên p = F/S nhỏ, xe không lún sâu.'],
['apr', 'Đinh có đầu nhọn dễ đóng vào gỗ vì',
 ['diện tích mũi đinh rất nhỏ nên áp suất rất lớn', 'đinh nhọn thì nhẹ hơn', 'đinh nhọn có lực ma sát lớn', 'mũi đinh chịu áp lực nhỏ'],
 'Cùng lực búa, S mũi đinh rất nhỏ → p = F/S rất lớn, đủ xuyên vào gỗ.'],
['apr', 'Một người đứng bằng một chân thì áp suất lên mặt đất so với khi đứng bằng hai chân sẽ',
 ['gấp đôi', 'giảm một nửa', 'không thay đổi', 'gấp bốn'],
 'Áp lực (trọng lượng) không đổi, diện tích giảm nửa → áp suất gấp đôi.'],
['apr', 'Một khối gỗ đặt trên mặt bàn nằm ngang. Áp lực của khối gỗ lên mặt bàn',
 ['bằng trọng lượng của khối gỗ', 'lớn hơn trọng lượng của khối gỗ', 'nhỏ hơn trọng lượng của khối gỗ', 'bằng khối lượng của khối gỗ'],
 'Trên mặt ngang, lực ép vuông góc chính là trọng lượng P = 10m.'],
['apr', 'Cùng một viên gạch đặt trên bàn theo ba cách (nằm, nghiêng, dựng). Nhận xét nào đúng?',
 ['Áp lực như nhau, áp suất lớn nhất khi diện tích tiếp xúc nhỏ nhất', 'Áp lực và áp suất đều như nhau', 'Áp lực thay đổi, áp suất không đổi', 'Áp suất lớn nhất khi diện tích tiếp xúc lớn nhất'],
 'Áp lực luôn bằng trọng lượng gạch; p = F/S nên mặt nhỏ nhất cho áp suất lớn nhất.'],
['apr', 'Một người có khối lượng 60 kg, diện tích tiếp xúc của hai bàn chân với đất là 300 cm<sup>2</sup>. Áp suất người đó lên mặt đất khi đứng hai chân là',
 ['20 000 Pa', '2 Pa', '200 Pa', '180 000 Pa'],
 'F = 600 N; S = 300 cm<sup>2</sup> = 0,03 m<sup>2</sup>; p = 600 : 0,03 = 20 000 Pa.'],
['apr', 'Trường hợp 1: lực 20 N ép lên 4 cm<sup>2</sup>. Trường hợp 2: lực 100 N ép lên 0,01 m<sup>2</sup>. So sánh áp suất:',
 ['p<sub>1</sub> = 5p<sub>2</sub>', 'p<sub>2</sub> = 5p<sub>1</sub>', 'p<sub>1</sub> = p<sub>2</sub>', 'p<sub>2</sub> = 25p<sub>1</sub>'],
 'p<sub>1</sub> = 20 : 0,0004 = 50 000 Pa; p<sub>2</sub> = 100 : 0,01 = 10 000 Pa. Vậy p<sub>1</sub> = 5p<sub>2</sub>.'],
['apr', 'Chiếc tủ có khối lượng 100 kg đứng trên 4 chân, mỗi chân tiếp xúc với sàn 25 cm<sup>2</sup>. Áp suất của tủ lên sàn là',
 ['100 000 Pa', '25 000 Pa', '400 000 Pa', '10 000 Pa'],
 'F = 1000 N; S = 4 × 25 = 100 cm<sup>2</sup> = 0,01 m<sup>2</sup>; p = 1000 : 0,01 = 100 000 Pa.'],
['apr', 'Móng nhà thường được xây rộng hơn tường vì',
 ['để giảm áp suất lên nền đất, tránh lún', 'để tăng áp suất lên nền đất', 'để tiết kiệm vật liệu', 'để tường nhẹ hơn'],
 'Tăng diện tích tiếp xúc S → áp suất p = F/S giảm, nhà không bị lún, nghiêng.'],
['apr', 'Đi trên tuyết người ta dùng ván trượt hoặc giày bản rộng để',
 ['giảm áp suất lên tuyết nên không bị lún', 'tăng ma sát', 'tăng áp suất xuống tuyết', 'giữ ấm chân'],
 'Diện tích tiếp xúc lớn → áp suất nhỏ → không lún sâu.'],
['apr', 'Hai khối lập phương đặc bằng sắt, cạnh 10 cm và 20 cm, đặt trên mặt bàn nằm ngang. Áp suất của khối lớn so với khối nhỏ',
 ['gấp 2 lần', 'gấp 4 lần', 'gấp 8 lần', 'bằng nhau'],
 'p = P/S = 10·D·a<sup>3</sup>/a<sup>2</sup> = 10·D·a, tỉ lệ với cạnh a. Cạnh gấp đôi → áp suất gấp đôi.'],
['apr', 'Hình hộp chữ nhật 20 cm × 10 cm × 5 cm, khối lượng 4 kg. Áp suất LỚN NHẤT hộp có thể gây lên mặt bàn là',
 ['8000 Pa', '2000 Pa', '4000 Pa', '800 Pa'],
 'F = 40 N. Áp suất lớn nhất khi đặt mặt nhỏ nhất 10 × 5 = 50 cm<sup>2</sup> = 0,005 m<sup>2</sup>: p = 40 : 0,005 = 8000 Pa.'],
['apr', 'Ô tô có khối lượng 2 tấn, 4 bánh, mỗi bánh tiếp xúc với đường 100 cm<sup>2</sup>. Áp suất xe lên mặt đường là',
 ['500 000 Pa', '50 000 Pa', '2 000 000 Pa', '5000 Pa'],
 'F = 20 000 N; S = 400 cm<sup>2</sup> = 0,04 m<sup>2</sup>; p = 20 000 : 0,04 = 500 000 Pa.'],
['apr', '1 N/cm<sup>2</sup> bằng bao nhiêu Pa?',
 ['10 000 Pa', '100 Pa', '1 Pa', '0,0001 Pa'],
 '1 cm<sup>2</sup> = 0,0001 m<sup>2</sup>, nên 1 N/cm<sup>2</sup> = 1 : 0,0001 = 10 000 N/m<sup>2</sup> = 10 000 Pa.'],
['apr', 'Mũi kim tiêm, đầu ống hút được làm nhọn/vát để',
 ['tăng áp suất khi đâm/chọc', 'giảm áp suất', 'tăng diện tích tiếp xúc', 'giảm áp lực tác dụng'],
 'Diện tích đầu nhọn rất nhỏ nên chỉ cần lực nhỏ đã tạo áp suất lớn, dễ đâm xuyên.'],
['apr', 'Xe tải chở hàng nặng thường có nhiều bánh (nhiều cầu) nhằm',
 ['tăng diện tích tiếp xúc để giảm áp suất lên mặt đường', 'tăng áp suất lên đường', 'chạy nhanh hơn', 'tiết kiệm nhiên liệu'],
 'Trọng lượng chia cho diện tích lớn hơn → áp suất nhỏ, bảo vệ mặt đường và xe.'],
['apr', 'Khi bị sa vào bãi lầy, cách xử lí đúng là',
 ['nằm sấp, dang tay chân và trườn để tăng diện tích tiếp xúc', 'đứng thẳng và bước nhanh', 'nhảy lên để thoát', 'co một chân lên'],
 'Tăng diện tích tiếp xúc làm giảm áp suất lên bùn, cơ thể ít bị lún hơn.'],
['apr', 'Áp suất do một vật đặt trên mặt bàn nằm ngang gây ra phụ thuộc vào',
 ['trọng lượng của vật và diện tích mặt tiếp xúc', 'chỉ trọng lượng của vật', 'chỉ diện tích mặt tiếp xúc', 'màu sắc và chất liệu của vật'],
 'p = F/S với F là trọng lượng và S là diện tích tiếp xúc.'],
['apr', 'Vật A có khối lượng 5 kg đặt trên bàn, diện tích tiếp xúc 0,01 m<sup>2</sup>. Đặt thêm vật B cũng 5 kg chồng lên A. Áp suất lên mặt bàn lúc này là',
 ['10 000 Pa', '5000 Pa', '2500 Pa', '1000 Pa'],
 'Áp lực = 100 N, S vẫn 0,01 m<sup>2</sup> → p = 100 : 0,01 = 10 000 Pa (gấp đôi lúc đầu).'],
['apr', 'Một người 50 kg, diện tích một bàn chân 125 cm<sup>2</sup>. Khi đi bộ (mỗi lúc chỉ một chân chạm đất), áp suất lên đất là',
 ['40 000 Pa', '20 000 Pa', '4000 Pa', '400 Pa'],
 'F = 500 N; S = 125 cm<sup>2</sup> = 0,0125 m<sup>2</sup>; p = 500 : 0,0125 = 40 000 Pa.'],
['apr', 'Áp suất 2000 Pa tác dụng lên mặt sàn có diện tích 0,5 m<sup>2</sup>. Áp lực lên sàn là',
 ['1000 N', '4000 N', '2000 N', '100 N'],
 'F = p·S = 2000 × 0,5 = 1000 N.'],

/* ───────── ÁP SUẤT CHẤT LỎNG ───────── */
['apl', 'Chất lỏng đựng trong bình gây áp suất lên',
 ['đáy bình, thành bình và các vật ở trong lòng nó', 'chỉ đáy bình', 'chỉ thành bình', 'chỉ các vật nhúng trong nó'],
 'Khác chất rắn, chất lỏng gây áp suất theo mọi phương: lên đáy, thành bình và vật nhúng trong nó.'],
['apl', 'Trong công thức p = d·h của áp suất chất lỏng, h là',
 ['độ sâu từ mặt thoáng chất lỏng đến điểm xét', 'chiều cao của bình chứa', 'khoảng cách từ đáy bình đến điểm xét', 'chiều cao của cột chất lỏng trong bình'],
 'h là độ sâu tính từ mặt thoáng xuống điểm đang xét; d là trọng lượng riêng (N/m<sup>3</sup>).'],
['apl', 'Trọng lượng riêng d của nước là 10 000 N/m<sup>3</sup>. Liên hệ với khối lượng riêng D là',
 ['d = 10·D', 'd = D/10', 'd = D', 'd = 100·D'],
 'd = P/V = 10m/V = 10·D. Nước: D = 1000 kg/m<sup>3</sup> → d = 10 000 N/m<sup>3</sup>.'],
['apl', 'Bình trụ có đáy và các lỗ bên thành bịt màng cao su. Đổ nước vào, các màng đều phồng ra. Thí nghiệm chứng tỏ',
 ['chất lỏng gây áp suất lên cả đáy và thành bình', 'chất lỏng chỉ gây áp suất lên đáy', 'màng cao su tự phồng khi ướt', 'chất lỏng không gây áp suất lên thành'],
 'Màng ở đáy và ở thành đều phồng → chất lỏng gây áp suất theo mọi phương.'],
['apl', 'Thợ lặn phải mặc áo lặn chịu áp suất cao vì',
 ['càng xuống sâu áp suất chất lỏng càng lớn', 'nước biển mặn', 'dưới sâu nước rất lạnh', 'dưới sâu không có ánh sáng'],
 'p = d·h tăng theo độ sâu; ở vài chục mét áp suất đã gấp nhiều lần trên bờ.'],
['apl', 'Trong bình thông nhau chứa cùng một chất lỏng đứng yên, các mặt thoáng ở các nhánh',
 ['ở cùng một độ cao', 'cao hơn ở nhánh to', 'cao hơn ở nhánh nhỏ', 'cao thấp tuỳ hình dạng nhánh'],
 'Cùng một chất lỏng đứng yên → áp suất tại cùng độ cao bằng nhau → mặt thoáng ngang nhau.'],
['apl', 'Trong một chất lỏng đứng yên, hai điểm có cùng độ sâu thì',
 ['áp suất bằng nhau, không phụ thuộc hình dạng bình', 'điểm ở giữa bình có áp suất lớn hơn', 'điểm gần thành bình có áp suất lớn hơn', 'áp suất phụ thuộc lượng chất lỏng trong bình'],
 'p = d·h chỉ phụ thuộc d và h. Cùng h → cùng p.'],
['apl', 'Ba bình có hình dạng khác nhau đựng cùng một chất lỏng tới cùng một độ cao. Áp suất tại đáy các bình',
 ['bằng nhau', 'lớn nhất ở bình chứa nhiều chất lỏng nhất', 'lớn nhất ở bình có đáy nhỏ nhất', 'lớn nhất ở bình có đáy rộng nhất'],
 'p = d·h, cùng d và cùng h → áp suất đáy bằng nhau dù lượng chất lỏng khác nhau.'],
['apl', 'Ấm trà có vòi cao ngang miệng ấm là ứng dụng của',
 ['bình thông nhau', 'máy nén thuỷ lực', 'áp suất khí quyển', 'lực đẩy Archimedes'],
 'Vòi và thân ấm là bình thông nhau; vòi cao ngang miệng để rót đầy mà nước không tràn qua vòi.'],
['apl', 'Áp suất của nước ở độ sâu 2 m (d = 10 000 N/m<sup>3</sup>) là',
 ['20 000 Pa', '5000 Pa', '2000 Pa', '200 000 Pa'],
 'p = d·h = 10 000 × 2 = 20 000 Pa.'],
['apl', 'Bình cao 1,2 m đựng đầy nước. Điểm A cách đáy 30 cm. Áp suất của nước tại A là',
 ['9000 Pa', '3000 Pa', '12 000 Pa', '15 000 Pa'],
 'Độ sâu của A: h = 1,2 − 0,3 = 0,9 m; p = 10 000 × 0,9 = 9000 Pa.'],
['apl', 'Thùng đựng dầu (d = 8000 N/m<sup>3</sup>) cao 1,5 m, đầy dầu. Áp suất dầu tác dụng lên đáy thùng là',
 ['12 000 Pa', '15 000 Pa', '1200 Pa', '9500 Pa'],
 'p = d·h = 8000 × 1,5 = 12 000 Pa.'],
['apl', 'Máy nén thuỷ lực hoạt động dựa trên nguyên lí',
 ['áp suất tác dụng lên chất lỏng trong bình kín được truyền nguyên vẹn tới mọi điểm', 'chất lỏng có thể nén được dễ dàng', 'lực đẩy Archimedes', 'bình thông nhau có mặt thoáng ngang nhau'],
 'Nguyên lí Pascal: p = f/s = F/S, nên F/f = S/s — pit-tông lớn hơn cho lực lớn hơn.'],
['apl', 'Máy nén thuỷ lực có pit-tông nhỏ 2 cm<sup>2</sup>, pit-tông lớn 200 cm<sup>2</sup>. Tác dụng lực 50 N lên pit-tông nhỏ, lực nâng ở pit-tông lớn là',
 ['5000 N', '500 N', '0,5 N', '50 000 N'],
 'F = f·S/s = 50 × 200/2 = 5000 N.'],
['apl', 'Bình thông nhau chứa nước. Đổ vào nhánh trái một cột dầu cao 20 cm (d<sub>dầu</sub> = 8000 N/m<sup>3</sup>, d<sub>nước</sub> = 10 000 N/m<sup>3</sup>). Khi cân bằng, mặt thoáng dầu so với mặt thoáng nước ở nhánh phải',
 ['cao hơn 4 cm', 'thấp hơn 4 cm', 'ngang bằng', 'cao hơn 20 cm'],
 'Tại mặt phân cách: 8000 × 0,2 = 10 000 × h → h = 0,16 m = 16 cm nước cân với 20 cm dầu; mặt dầu cao hơn mặt nước 20 − 16 = 4 cm.'],
['apl', 'Khi tàu ngầm nổi dần lên mặt nước, áp suất nước tác dụng lên vỏ tàu',
 ['giảm dần', 'tăng dần', 'không thay đổi', 'lúc tăng lúc giảm'],
 'Độ sâu h giảm nên p = d·h giảm.'],
['apl', 'Đập thuỷ điện được xây dày ở chân đập, mỏng ở đỉnh vì',
 ['áp suất nước càng sâu càng lớn', 'chân đập dễ bị nước cuốn trôi', 'để tiết kiệm bê tông ở đỉnh', 'nước ở đáy hồ lạnh hơn'],
 'p = d·h lớn nhất ở đáy hồ nên chân đập phải chịu lực lớn nhất.'],
['apl', 'Rót thêm nước vào một nhánh của bình thông nhau. Khi nước đứng yên trở lại thì',
 ['mực nước hai nhánh lại ngang nhau', 'nhánh được rót cao hơn', 'nhánh được rót thấp hơn', 'nước không chuyển sang nhánh kia'],
 'Nước chảy sang nhánh kia đến khi áp suất ở đáy hai nhánh bằng nhau, tức mặt thoáng ngang nhau.'],
['apl', 'Trong nước, điểm A ở độ sâu 0,5 m và điểm B ở độ sâu 1,5 m. Áp suất tại B lớn hơn tại A một lượng',
 ['10 000 Pa', '5000 Pa', '15 000 Pa', '20 000 Pa'],
 'Δp = d·(h<sub>B</sub> − h<sub>A</sub>) = 10 000 × 1 = 10 000 Pa.'],
['apl', 'Áp suất do chất lỏng gây ra tại một điểm KHÔNG phụ thuộc vào',
 ['thể tích chất lỏng và diện tích đáy bình', 'độ sâu của điểm đó', 'trọng lượng riêng của chất lỏng', 'loại chất lỏng'],
 'p = d·h chỉ phụ thuộc d và h; bình to hay nhỏ, nhiều hay ít chất lỏng không ảnh hưởng.'],
['apl', 'Thùng cao 1 m đựng đầy nước. Áp suất tại điểm ở chính giữa chiều cao thùng là',
 ['5000 Pa', '10 000 Pa', '500 Pa', '2500 Pa'],
 'h = 0,5 m; p = 10 000 × 0,5 = 5000 Pa.'],
['apl', 'Tàu ngầm ở độ sâu 100 m trong nước biển (d = 10 300 N/m<sup>3</sup>). Áp lực nước lên cửa sổ tàu có diện tích 0,1 m<sup>2</sup> là',
 ['103 000 N', '10 300 N', '1 030 000 N', '1030 N'],
 'p = 10 300 × 100 = 1 030 000 Pa; F = p·S = 1 030 000 × 0,1 = 103 000 N.'],
['apl', 'Máy nén thuỷ lực có S/s = 10. Khi pit-tông nhỏ đi xuống 10 cm thì pit-tông lớn đi lên',
 ['1 cm', '10 cm', '100 cm', '0,1 cm'],
 'Thể tích chất lỏng chuyển từ xi-lanh nhỏ sang lớn bằng nhau: s·h<sub>1</sub> = S·h<sub>2</sub> → h<sub>2</sub> = 10/10 = 1 cm. Lợi 10 lần về lực thì thiệt 10 lần về đường đi.'],
['apl', 'Bình A miệng loe, bình B miệng thắt, cùng đựng nước đến độ cao 40 cm. So sánh áp suất tại đáy:',
 ['bằng nhau', 'A lớn hơn vì chứa nhiều nước hơn', 'B lớn hơn vì miệng hẹp', 'không so sánh được'],
 'Cùng độ cao cột nước h = 0,4 m → p = d·h bằng nhau, không phụ thuộc hình dạng bình.'],
['apl', 'Phanh dầu (phanh thuỷ lực) của ô tô, xe máy hoạt động dựa trên',
 ['sự truyền nguyên vẹn áp suất trong chất lỏng (máy nén thuỷ lực)', 'bình thông nhau', 'lực đẩy Archimedes', 'áp suất khí quyển'],
 'Lực nhỏ ở bàn đạp tạo áp suất truyền qua dầu tới pit-tông lớn ở bánh xe, tạo lực phanh lớn.'],
['apl', 'Trong toà nhà nhiều tầng dùng chung một bể nước trên mái, vòi nước ở tầng nào chảy mạnh nhất?',
 ['Tầng thấp nhất, vì độ sâu so với mặt nước bể lớn nhất', 'Tầng cao nhất, vì gần bể', 'Các tầng chảy như nhau', 'Tầng giữa'],
 'Áp suất nước tại vòi p = d·h với h là độ cao từ vòi lên mặt nước bể; tầng thấp có h lớn nhất.'],
['apl', 'Trong chất lỏng đứng yên, tại một độ sâu, áp suất lên thành bình so với áp suất lên đáy bình ở cùng độ sâu đó',
 ['bằng nhau', 'nhỏ hơn', 'lớn hơn', 'bằng 0'],
 'Áp suất chất lỏng tại một điểm có giá trị như nhau theo mọi phương.'],
['apl', 'Bình thông nhau chứa thuỷ ngân (d = 136 000 N/m<sup>3</sup>). Đổ vào nhánh trái cột nước cao 27,2 cm. Mặt thuỷ ngân ở nhánh phải cao hơn mặt phân cách ở nhánh trái',
 ['2 cm', '27,2 cm', '13,6 cm', '0,2 cm'],
 '10 000 × 0,272 = 136 000 × h → h = 0,02 m = 2 cm.'],
['apl', 'Bình đựng hai chất lỏng không hoà tan: dầu (d<sub>1</sub>) cao h<sub>1</sub> nổi trên nước (d<sub>2</sub>) cao h<sub>2</sub>. Áp suất tại đáy bình là',
 ['d<sub>1</sub>h<sub>1</sub> + d<sub>2</sub>h<sub>2</sub>', 'd<sub>2</sub>(h<sub>1</sub> + h<sub>2</sub>)', 'd<sub>1</sub>(h<sub>1</sub> + h<sub>2</sub>)', '(d<sub>1</sub> + d<sub>2</sub>)(h<sub>1</sub> + h<sub>2</sub>)'],
 'Áp suất tại đáy bằng tổng áp suất do từng lớp chất lỏng gây ra: p = d<sub>1</sub>h<sub>1</sub> + d<sub>2</sub>h<sub>2</sub>.'],
['apl', 'Bình thông nhau có nhánh trái to gấp 3 lần nhánh phải, chứa nước đứng yên. Mực nước ở hai nhánh',
 ['ngang nhau', 'nhánh to cao hơn', 'nhánh nhỏ cao hơn', 'nhánh to cao gấp 3'],
 'Mặt thoáng của cùng một chất lỏng trong bình thông nhau luôn ngang nhau, không phụ thuộc tiết diện.'],

/* ───────── ÁP SUẤT KHÍ QUYỂN ───────── */
['akq', 'Nguyên nhân gây ra áp suất khí quyển là',
 ['không khí có trọng lượng và bao quanh Trái Đất', 'không khí chuyển động thành gió', 'Mặt Trời làm nóng không khí', 'không khí có màu trong suốt'],
 'Lớp khí quyển dày hàng chục km có trọng lượng, ép lên mọi vật trên Trái Đất theo mọi phương.'],
['akq', 'Áp suất khí quyển tác dụng lên vật theo',
 ['mọi phương', 'chỉ phương thẳng đứng từ trên xuống', 'chỉ phương nằm ngang', 'chỉ phương thẳng đứng từ dưới lên'],
 'Không khí bao quanh vật và gây áp suất theo mọi hướng, giống chất lỏng.'],
['akq', 'Trong thí nghiệm Torricelli, cột thuỷ ngân trong ống còn lại cao 76 cm. Điều này cho biết',
 ['áp suất khí quyển bằng áp suất của cột thuỷ ngân cao 76 cm', 'thuỷ ngân không thể chảy hết ra', 'ống thuỷ tinh dài 76 cm', 'áp suất khí quyển bằng 0'],
 'Áp suất khí quyển cân bằng với áp suất cột Hg 76 cm: p ≈ 136 000 × 0,76 ≈ 103 360 Pa.'],
['akq', 'Khi hút sữa bằng ống hút, sữa lên miệng ta vì',
 ['áp suất trong ống giảm, áp suất khí quyển đẩy sữa lên', 'miệng hút sữa lên trực tiếp', 'sữa tự chảy lên', 'trọng lực đẩy sữa lên'],
 'Ta hút làm áp suất khí trong ống nhỏ hơn áp suất khí quyển bên ngoài; chênh lệch áp suất đẩy sữa lên.'],
['akq', 'Muốn rót sữa đặc ra khỏi hộp dễ dàng, ta thường đục hai lỗ trên nắp hộp vì',
 ['lỗ thứ hai cho không khí vào, áp suất trong hộp cân bằng với bên ngoài', 'sữa chảy ra cả hai lỗ', 'hộp nhẹ hơn', 'sữa loãng hơn'],
 'Nếu chỉ một lỗ, sữa chảy ra làm áp suất trong hộp giảm, khí quyển bên ngoài ép lại cản sữa.'],
['akq', 'Thí nghiệm bán cầu Magdeburg: hai bán cầu ghép kín, hút hết không khí bên trong, 16 con ngựa kéo không tách được. Thí nghiệm chứng tỏ',
 ['áp suất khí quyển rất lớn', 'ngựa yếu', 'bán cầu bị dính keo', 'không khí không có trọng lượng'],
 'Bên trong gần như chân không, chỉ còn áp suất khí quyển bên ngoài ép hai bán cầu vào nhau với lực rất lớn.'],
['akq', 'Càng lên cao, áp suất khí quyển',
 ['càng giảm', 'càng tăng', 'không thay đổi', 'tăng rồi giảm'],
 'Lên cao lớp không khí phía trên mỏng hơn, loãng hơn nên áp suất giảm.'],
['akq', 'Nhúng ống thuỷ tinh hở hai đầu vào nước, bịt ngón tay đầu trên rồi nhấc ra, nước không chảy ra vì',
 ['áp suất khí quyển tác dụng lên đáy cột nước lớn hơn áp suất của cột nước', 'nước dính vào ống', 'ngón tay hút nước', 'ống quá nhỏ'],
 'Bên trên bị bịt, không khí không vào được; áp suất khí quyển từ dưới đẩy lên giữ cột nước.'],
['akq', 'Dụng cụ dùng đo áp suất khí quyển là',
 ['áp kế (khí áp kế)', 'nhiệt kế', 'lực kế', 'ẩm kế'],
 'Khí áp kế đo áp suất khí quyển, thường có thang đo bằng mmHg hoặc hPa.'],
['akq', 'Giá trị áp suất khí quyển chuẩn ở mực nước biển gần bằng',
 ['101 325 Pa ≈ 760 mmHg', '1000 Pa', '76 Pa', '10 000 Pa'],
 '1 atm ≈ 101 325 Pa ≈ 760 mmHg = 76 cmHg.'],
['akq', 'Khi lên núi cao, ta thấy ù tai vì',
 ['áp suất khí quyển bên ngoài giảm, chênh lệch với áp suất trong tai', 'không khí lạnh hơn', 'trên núi nhiều gió', 'độ ẩm cao'],
 'Áp suất bên ngoài giảm nhanh hơn áp suất trong tai giữa, màng nhĩ bị đẩy ra tạo cảm giác ù.'],
['akq', 'Đổ đầy nước vào cốc, đậy tờ giấy rồi lộn ngược cốc, nước không đổ ra vì',
 ['áp suất khí quyển đẩy tờ giấy từ dưới lên', 'tờ giấy dính chặt vào cốc', 'nước nhẹ hơn giấy', 'trọng lực không tác dụng lên nước'],
 'Áp suất khí quyển đẩy lên tờ giấy lớn hơn áp suất cột nước trong cốc ép xuống.'],
['akq', 'Bầu giác (giác hơi) dính chặt vào da người vì',
 ['không khí trong bầu bị hút bớt hoặc làm nóng, áp suất trong bầu nhỏ hơn khí quyển', 'da người có chất dính', 'bầu giác có nam châm', 'bầu giác quá nặng'],
 'Áp suất trong bầu nhỏ hơn bên ngoài, khí quyển ép bầu vào da.'],
['akq', 'Móc dán tường (giác mút) bám chặt vào tường nhờ',
 ['áp suất khí quyển ép giác mút khi không khí bên trong bị đẩy ra', 'keo dính', 'lực từ', 'lực đẩy Archimedes'],
 'Ép giác mút đẩy không khí ra, áp suất bên trong nhỏ hơn khí quyển nên bị ép chặt vào tường.'],
['akq', 'Với d<sub>Hg</sub> = 136 000 N/m<sup>3</sup>, áp suất khí quyển 76 cmHg tương ứng',
 ['103 360 Pa', '10 336 Pa', '1 033 600 Pa', '76 000 Pa'],
 'p = d·h = 136 000 × 0,76 = 103 360 Pa.'],
['akq', 'Không dùng nước thay thuỷ ngân trong ống Torricelli vì',
 ['cột nước cân bằng với khí quyển phải cao khoảng 10,3 m', 'nước bay hơi hết', 'nước không có trọng lượng', 'nước quá nặng'],
 'h = p/d = 103 360 : 10 000 ≈ 10,3 m, ống quá dài không thực tế.'],
['akq', 'Gói bánh snack mang lên núi cao thì phồng to hơn vì',
 ['áp suất khí quyển bên ngoài giảm, khí trong gói nở ra', 'bánh nở khi lạnh', 'khí trong gói tăng thêm', 'trên núi độ ẩm cao'],
 'Áp suất bên ngoài giảm, khí trong gói kín (áp suất giữ nguyên) đẩy phồng vỏ.'],
['akq', 'Cabin máy bay bay ở độ cao 10 km phải được điều áp vì',
 ['áp suất khí quyển ở đó rất thấp, không đủ để người hô hấp bình thường', 'trên cao nhiều tia nắng', 'để máy bay bay nhanh hơn', 'để giữ nhiệt độ'],
 'Ở 10 km, áp suất chỉ khoảng 1/4 áp suất mặt đất; cabin được bơm khí để duy trì áp suất phù hợp.'],
['akq', 'Áp suất khí quyển ép lên mặt bàn 1 m<sup>2</sup> một lực khoảng 100 000 N nhưng bàn không sập vì',
 ['không khí ép từ mọi phía, kể cả từ dưới lên, các lực cân bằng nhau', 'mặt bàn rất cứng', 'không khí không có trọng lượng', 'áp suất chỉ tác dụng lên vật nhẹ'],
 'Không khí ở dưới mặt bàn cũng ép lên với áp suất như vậy nên hợp lực bằng 0.'],
['akq', 'Cứ lên cao 12 m thì áp suất khí quyển giảm khoảng 1 mmHg. Ở đỉnh toà nhà cao 120 m, áp suất khí quyển khoảng (biết tại mặt đất 760 mmHg)',
 ['750 mmHg', '770 mmHg', '640 mmHg', '748 mmHg'],
 'Giảm 120 : 12 = 10 mmHg → 760 − 10 = 750 mmHg.'],
['akq', 'Khi kéo pit-tông của ống tiêm (đầu kim nhúng trong thuốc), thuốc đi vào ống vì',
 ['áp suất trong ống giảm, áp suất khí quyển đẩy thuốc vào', 'pit-tông hút thuốc', 'thuốc tự chảy', 'kim tiêm có lực từ'],
 'Kéo pit-tông làm thể tích tăng, áp suất trong ống nhỏ hơn khí quyển tác dụng lên mặt thuốc.'],
['akq', 'Vì sao không tính áp suất khí quyển bằng công thức p = d·h như chất lỏng?',
 ['Trọng lượng riêng của không khí thay đổi theo độ cao và không xác định được độ cao lớp khí quyển', 'Không khí không có trọng lượng', 'Khí quyển quá mỏng', 'Không khí không gây áp suất'],
 'd của không khí giảm dần theo độ cao và không có "mặt thoáng" rõ ràng của khí quyển.'],
['akq', 'Khí áp kế được dùng trong dự báo thời tiết vì',
 ['áp suất khí quyển thay đổi báo hiệu thời tiết thay đổi', 'nó đo được nhiệt độ', 'nó đo được lượng mưa', 'nó đo được gió'],
 'Áp suất giảm thường báo mưa bão, tăng thường báo trời quang.'],
['akq', 'Nắp phích nước, ấm điện thường có một lỗ nhỏ để',
 ['không khí vào cân bằng áp suất, rót nước dễ dàng', 'thoát hơi nước làm nguội', 'trang trí', 'giảm trọng lượng'],
 'Nếu kín hoàn toàn, khi rót áp suất trong bình giảm, khí quyển bên ngoài cản nước chảy ra.'],
['akq', 'Bình kín đựng nước có một lỗ nhỏ ở đáy. Khi đậy kín nắp, nước hầu như không chảy; mở nắp, nước chảy ra. Giải thích:',
 ['Mở nắp, không khí vào tạo áp suất khí quyển lên mặt nước đẩy nước chảy ra', 'Nắp giữ nước bằng lực hút', 'Mở nắp nước nóng lên', 'Nắp làm nước đặc hơn'],
 'Khi đóng nắp, áp suất khí quyển ở lỗ đáy giữ nước; mở nắp, khí quyển ép cả từ trên xuống nên nước chảy.'],
['akq', 'Ở mực nước biển áp suất khí quyển khoảng 760 mmHg. Đỉnh Fansipan cao 3143 m có áp suất khí quyển khoảng',
 ['nhỏ hơn 760 mmHg đáng kể (khoảng 520 mmHg)', 'lớn hơn 760 mmHg', 'đúng 760 mmHg', 'bằng 0'],
 'Lên cao áp suất giảm; ở hơn 3000 m áp suất chỉ còn khoảng 2/3 so với mặt biển.'],

/* ───────── LỰC ĐẨY ARCHIMEDES ───────── */
['arc', 'Lực đẩy Archimedes tác dụng lên vật nhúng trong chất lỏng có',
 ['phương thẳng đứng, chiều từ dưới lên', 'phương thẳng đứng, chiều từ trên xuống', 'phương nằm ngang', 'phương bất kì'],
 'Lực đẩy Archimedes luôn hướng thẳng đứng lên trên, ngược chiều trọng lực.'],
['arc', 'Trong công thức F<sub>A</sub> = d·V, V là',
 ['thể tích phần chất lỏng bị vật chiếm chỗ (phần vật chìm)', 'thể tích toàn bộ vật', 'thể tích chất lỏng trong bình', 'thể tích bình chứa'],
 'V là thể tích phần vật ngập trong chất lỏng; vật chìm hoàn toàn thì V bằng thể tích vật.'],
['arc', 'Lực đẩy Archimedes tác dụng lên vật chìm hoàn toàn trong chất lỏng KHÔNG phụ thuộc vào',
 ['độ sâu của vật và chất làm vật', 'thể tích của vật', 'trọng lượng riêng của chất lỏng', 'loại chất lỏng'],
 'F<sub>A</sub> = d·V chỉ phụ thuộc d chất lỏng và V phần chìm, không phụ thuộc độ sâu hay khối lượng vật.'],
['arc', 'Ba vật đặc bằng sắt, nhôm, gỗ có cùng thể tích, nhúng chìm hoàn toàn trong nước. Lực đẩy Archimedes lên chúng',
 ['bằng nhau', 'lớn nhất lên vật sắt', 'lớn nhất lên vật gỗ', 'lớn nhất lên vật nhôm'],
 'Cùng d nước và cùng V → F<sub>A</sub> = d·V bằng nhau.'],
['arc', 'Cùng một vật nhúng chìm hoàn toàn lần lượt trong nước (d = 10 000 N/m<sup>3</sup>) và trong dầu (d = 8000 N/m<sup>3</sup>). Lực đẩy Archimedes',
 ['trong nước lớn hơn trong dầu', 'trong dầu lớn hơn trong nước', 'bằng nhau', 'không so sánh được'],
 'Cùng V, F<sub>A</sub> tỉ lệ với d chất lỏng; d nước > d dầu.'],
['arc', 'Vật nhúng trong chất lỏng sẽ nổi lên khi',
 ['P < F<sub>A</sub> (khối lượng riêng vật nhỏ hơn chất lỏng)', 'P > F<sub>A</sub>', 'P = F<sub>A</sub>', 'vật có khối lượng nhỏ'],
 'Nổi lên khi lực đẩy lớn hơn trọng lượng, tương ứng D<sub>vật</sub> < D<sub>lỏng</sub>.'],
['arc', 'Khi một vật nổi cân bằng trên mặt nước thì',
 ['F<sub>A</sub> = P', 'F<sub>A</sub> > P', 'F<sub>A</sub> < P', 'F<sub>A</sub> = 0'],
 'Vật nằm yên → hai lực cân bằng: lực đẩy Archimedes bằng trọng lượng của vật.'],
['arc', 'Treo vật vào lực kế: trong không khí chỉ 5 N, nhúng chìm trong nước chỉ 3 N. Lực đẩy Archimedes lên vật là',
 ['2 N', '8 N', '5 N', '3 N'],
 'F<sub>A</sub> = P − P<sub>nước</sub> = 5 − 3 = 2 N.'],
['arc', 'Treo vật vào lực kế: trong không khí chỉ 5 N, nhúng chìm hoàn toàn trong nước chỉ 3 N. Thể tích của vật là',
 ['200 cm<sup>3</sup>', '500 cm<sup>3</sup>', '300 cm<sup>3</sup>', '20 cm<sup>3</sup>'],
 'F<sub>A</sub> = 2 N → V = F<sub>A</sub>/d = 2 : 10 000 = 0,0002 m<sup>3</sup> = 200 cm<sup>3</sup>.'],
['arc', 'Treo vật vào lực kế: trong không khí chỉ 5 N, nhúng chìm hoàn toàn trong nước chỉ 3 N. Khối lượng riêng của vật là',
 ['2500 kg/m<sup>3</sup>', '1500 kg/m<sup>3</sup>', '5000 kg/m<sup>3</sup>', '1000 kg/m<sup>3</sup>'],
 'V = 0,0002 m<sup>3</sup>; m = 0,5 kg; D = 0,5 : 0,0002 = 2500 kg/m<sup>3</sup>.'],
['arc', 'Tàu bằng thép (D<sub>thép</sub> ≈ 7800 kg/m<sup>3</sup>) vẫn nổi trên nước vì',
 ['tàu có nhiều khoang rỗng nên khối lượng riêng trung bình nhỏ hơn nước', 'thép nhẹ hơn nước', 'nước biển rất mặn', 'tàu chạy nhanh'],
 'Thể tích tàu rất lớn so với khối lượng, D trung bình < 1000 kg/m<sup>3</sup>, F<sub>A</sub> đủ cân bằng trọng lượng.'],
['arc', 'Một chiếc kim khâu chìm trong nước nhưng chiếc tàu hàng ngàn tấn lại nổi. Yếu tố quyết định là',
 ['so sánh khối lượng riêng trung bình của vật với khối lượng riêng của nước', 'khối lượng của vật', 'hình dạng nhọn hay tròn', 'màu sắc của vật'],
 'Vật nổi hay chìm phụ thuộc D<sub>vật</sub> so với D<sub>nước</sub>, không phụ thuộc vật nặng hay nhẹ.'],
['arc', 'Quả trứng chìm trong nước ngọt nhưng nổi trong nước muối đặc vì',
 ['trọng lượng riêng nước muối lớn hơn trọng lượng riêng của trứng', 'trứng nhẹ đi khi gặp muối', 'muối làm trứng nở to', 'nước muối nóng hơn'],
 'F<sub>A</sub> = d·V; nước muối có d lớn hơn nên lực đẩy đủ lớn để trứng nổi.'],
['arc', 'Khinh khí cầu bay lên được là do',
 ['lực đẩy Archimedes của không khí lớn hơn trọng lượng của khí cầu', 'gió thổi lên', 'khí cầu không có trọng lượng', 'khí cầu được kéo bằng dây'],
 'Chất khí cũng gây lực đẩy Archimedes; khí nóng hoặc khí nhẹ trong cầu làm trọng lượng tổng nhỏ hơn F<sub>A</sub>.'],
['arc', 'Khối gỗ có D = 600 kg/m<sup>3</sup> nổi trên nước. Phần thể tích chìm trong nước chiếm',
 ['60% thể tích khối gỗ', '40% thể tích khối gỗ', '100% thể tích khối gỗ', '6% thể tích khối gỗ'],
 'Nổi: 10·D<sub>gỗ</sub>·V = 10·D<sub>nước</sub>·V<sub>chìm</sub> → V<sub>chìm</sub>/V = 600/1000 = 60%.'],
['arc', 'Vật hình hộp có thể tích 2 dm<sup>3</sup> chìm hoàn toàn trong nước. Lực đẩy Archimedes lên vật là',
 ['20 N', '2 N', '200 N', '0,2 N'],
 'V = 0,002 m<sup>3</sup>; F<sub>A</sub> = 10 000 × 0,002 = 20 N.'],
['arc', 'Người tắm ở Biển Chết có thể nằm nổi dễ dàng vì',
 ['nước ở đó rất mặn, trọng lượng riêng lớn nên lực đẩy lớn', 'nước ở đó rất nóng', 'người nhẹ hơn', 'biển không có sóng'],
 'Nước Biển Chết có D ≈ 1240 kg/m<sup>3</sup>, lớn hơn D trung bình của cơ thể người nhiều.'],
['arc', 'Thả viên bi sắt (D = 7800 kg/m<sup>3</sup>) vào thuỷ ngân (D = 13 600 kg/m<sup>3</sup>), viên bi sẽ',
 ['nổi', 'chìm', 'lơ lửng', 'tan ra'],
 'D<sub>sắt</sub> < D<sub>thuỷ ngân</sub> → bi nổi trên thuỷ ngân.'],
['arc', 'Tàu ngầm lặn xuống hoặc nổi lên bằng cách',
 ['bơm nước vào hoặc ra khỏi các khoang để thay đổi trọng lượng', 'thay đổi thể tích thân tàu', 'đổi hướng chân vịt', 'thay đổi nhiệt độ nước'],
 'Thể tích tàu không đổi nên F<sub>A</sub> không đổi; bơm nước vào làm P > F<sub>A</sub> → lặn, bơm ra → nổi.'],
['arc', 'Nhiều loài cá nổi lên, chìm xuống được nhờ',
 ['thay đổi thể tích bong bóng khí trong bụng', 'bơi nhanh hơn', 'thay đổi màu da', 'ăn nhiều hay ít'],
 'Bong bóng phồng lên làm thể tích cá tăng → F<sub>A</sub> tăng → nổi lên; ngược lại thì chìm.'],
['arc', 'Quả cầu có khối lượng 0,5 kg nổi trên mặt nước. Lực đẩy Archimedes tác dụng lên quả cầu là',
 ['5 N', '0,5 N', '50 N', 'chưa đủ dữ liệu vì không biết thể tích'],
 'Vật nổi cân bằng: F<sub>A</sub> = P = 10 × 0,5 = 5 N.'],
['arc', 'Quả cầu có khối lượng 0,5 kg nổi trên mặt nước. Thể tích phần chìm trong nước là',
 ['500 cm<sup>3</sup>', '50 cm<sup>3</sup>', '5000 cm<sup>3</sup>', '5 cm<sup>3</sup>'],
 'F<sub>A</sub> = P = 5 N → V<sub>chìm</sub> = 5 : 10 000 = 0,0005 m<sup>3</sup> = 500 cm<sup>3</sup>.'],
['arc', 'Một vật lơ lửng (đứng yên ở giữa) trong nước. Khối lượng riêng của vật',
 ['bằng 1000 kg/m<sup>3</sup>', 'lớn hơn 1000 kg/m<sup>3</sup>', 'nhỏ hơn 1000 kg/m<sup>3</sup>', 'bằng 0'],
 'Lơ lửng: P = F<sub>A</sub> với vật chìm hoàn toàn → D<sub>vật</sub> = D<sub>nước</sub>.'],
['arc', 'Thả cùng một khối gỗ vào nước và vào dầu (gỗ nổi trong cả hai). So sánh lực đẩy Archimedes và phần chìm:',
 ['F<sub>A</sub> bằng nhau; phần chìm trong dầu lớn hơn', 'F<sub>A</sub> trong nước lớn hơn; phần chìm bằng nhau', 'F<sub>A</sub> trong dầu lớn hơn', 'F<sub>A</sub> bằng nhau; phần chìm trong nước lớn hơn'],
 'Vật nổi nên F<sub>A</sub> = P trong cả hai trường hợp; dầu có d nhỏ hơn nên cần V<sub>chìm</sub> lớn hơn.'],
['arc', 'Nhấn từ từ một khối gỗ xuống nước cho đến khi chìm hẳn rồi nhấn tiếp xuống sâu hơn. Lực đẩy Archimedes',
 ['tăng dần rồi không đổi khi đã chìm hẳn', 'tăng liên tục theo độ sâu', 'không đổi từ đầu', 'giảm dần'],
 'Khi phần chìm tăng thì F<sub>A</sub> = d·V<sub>chìm</sub> tăng; chìm hẳn rồi V không đổi nên F<sub>A</sub> không đổi.'],
['arc', 'Vật có trọng lượng 10 N, thể tích 0,5 dm<sup>3</sup>. Thả vào nước, vật sẽ',
 ['chìm, vì F<sub>A</sub> tối đa chỉ 5 N < 10 N', 'nổi, vì F<sub>A</sub> = 10 N', 'lơ lửng', 'nổi một nửa'],
 'F<sub>A</sub> lớn nhất khi chìm hẳn: 10 000 × 0,0005 = 5 N < P = 10 N → vật chìm.'],
['arc', 'Cách đo lực đẩy Archimedes bằng lực kế là',
 ['đo trọng lượng P trong không khí, đo P<sub>1</sub> khi nhúng trong chất lỏng, F<sub>A</sub> = P − P<sub>1</sub>', 'đo P rồi nhân với thể tích', 'đo P<sub>1</sub> khi nhúng, đó là F<sub>A</sub>', 'đo P rồi chia cho 10'],
 'Lực kế chỉ giảm đi đúng bằng lực đẩy Archimedes: F<sub>A</sub> = P − P<sub>1</sub>.'],
['arc', 'Hai vật A và B có cùng khối lượng, D<sub>A</sub> > D<sub>B</sub>, nhúng chìm cả hai trong nước. Lực đẩy Archimedes lên vật nào lớn hơn?',
 ['Lên B, vì B có thể tích lớn hơn', 'Lên A, vì A nặng hơn', 'Bằng nhau vì cùng khối lượng', 'Lên A, vì A đặc hơn'],
 'Cùng m, V = m/D → B có V lớn hơn → F<sub>A</sub> = d·V lớn hơn.'],
['arc', 'Cốc đầy nước có cục nước đá nổi. Khi nước đá tan hết thì',
 ['nước không tràn ra, mực nước không đổi', 'nước tràn ra ngoài', 'mực nước hạ xuống', 'không xác định được'],
 'Khối lượng nước đá = khối lượng nước tan ra; thể tích nước tan ra đúng bằng phần chìm của nước đá.'],
['arc', 'Chiếc bè gỗ nổi trên sông, khi chất thêm hàng lên bè thì',
 ['bè chìm sâu hơn, lực đẩy Archimedes tăng', 'bè nổi cao hơn', 'lực đẩy Archimedes không đổi', 'lực đẩy Archimedes giảm'],
 'Trọng lượng tăng → cần F<sub>A</sub> lớn hơn → phần chìm phải tăng.'],
['arc', 'Hai quả cầu đặc cùng thể tích, một bằng đồng và một bằng sắt, treo vào hai lực kế và nhúng chìm trong nước. Nhận xét đúng:',
 ['Lực đẩy Archimedes bằng nhau, số chỉ lực kế khác nhau', 'Lực đẩy Archimedes lên quả đồng lớn hơn', 'Số chỉ hai lực kế bằng nhau', 'Lực đẩy Archimedes lên quả sắt lớn hơn'],
 'Cùng V nên F<sub>A</sub> bằng nhau; trọng lượng khác nhau nên số chỉ (P − F<sub>A</sub>) khác nhau.'],

/* ───────── MOMENT LỰC – ĐÒN BẨY ───────── */
['mom', 'Tác dụng làm quay của một lực lên vật có trục quay phụ thuộc vào',
 ['độ lớn của lực và khoảng cách từ trục quay đến giá của lực', 'chỉ độ lớn của lực', 'chỉ khối lượng của vật', 'màu sắc và chất liệu của vật'],
 'Moment lực M = F·d: lực càng lớn, cánh tay đòn d càng dài thì tác dụng làm quay càng mạnh.'],
['mom', 'Moment lực được tính bằng công thức và có đơn vị',
 ['M = F·d, đơn vị N·m', 'M = F/d, đơn vị N/m', 'M = F + d, đơn vị N', 'M = F·d, đơn vị J'],
 'Moment lực bằng lực nhân với cánh tay đòn; đơn vị niutơn mét (N·m).'],
['mom', 'Một lực có giá đi qua trục quay của vật thì',
 ['không làm vật quay vì cánh tay đòn bằng 0', 'làm vật quay mạnh nhất', 'làm vật quay ngược chiều kim đồng hồ', 'làm vật quay cùng chiều kim đồng hồ'],
 'd = 0 → M = 0. Ví dụ đẩy cánh cửa ngay tại bản lề thì cửa không quay.'],
['mom', 'Vật có trục quay cố định ở trạng thái cân bằng khi',
 ['tổng moment làm quay theo chiều kim đồng hồ bằng tổng moment làm quay ngược chiều', 'chỉ có một lực tác dụng', 'các lực đều hướng lên trên', 'tổng các lực bằng 0'],
 'Điều kiện cân bằng của vật có trục quay: các moment quay ngược chiều nhau cân bằng nhau (F<sub>1</sub>d<sub>1</sub> = F<sub>2</sub>d<sub>2</sub>).'],
['mom', 'Đòn bẩy cho lợi về lực (F<sub>2</sub> < F<sub>1</sub>) khi',
 ['khoảng cách từ điểm tựa đến điểm tác dụng lực lớn hơn khoảng cách từ điểm tựa đến vật', 'hai khoảng cách bằng nhau', 'khoảng cách từ điểm tựa đến lực nhỏ hơn đến vật', 'đòn bẩy làm bằng kim loại'],
 'F<sub>1</sub>d<sub>1</sub> = F<sub>2</sub>d<sub>2</sub>: d<sub>2</sub> > d<sub>1</sub> thì F<sub>2</sub> < F<sub>1</sub>.'],
['mom', 'Kéo cắt kim loại có tay cầm dài, lưỡi ngắn nhằm',
 ['lợi về lực để cắt vật cứng', 'lợi về đường đi để cắt nhanh', 'cho đẹp', 'giảm khối lượng kéo'],
 'Cánh tay đòn của tay lớn hơn của lưỡi nhiều lần nên lực cắt lớn hơn lực tay.'],
['mom', 'Kéo cắt giấy có lưỡi dài, tay cầm ngắn nhằm',
 ['lợi về đường đi, cắt được đường dài trong một nhát', 'lợi về lực', 'tăng lực cắt', 'giảm ma sát'],
 'Giấy dễ cắt, không cần lợi lực; lưỡi dài giúp mỗi nhát cắt được xa hơn.'],
['mom', 'Dụng cụ nào sau đây có điểm tựa nằm GIỮA điểm đặt lực và vật?',
 ['Cái bập bênh', 'Xe cút kít', 'Cái kẹp gắp than', 'Cần câu cá'],
 'Bập bênh: trục ở giữa, hai người ở hai đầu. Xe cút kít có điểm tựa ở bánh (một đầu).'],
['mom', 'Xe cút kít (xe rùa) là đòn bẩy có',
 ['điểm tựa ở bánh xe, vật ở giữa, lực nâng ở tay cầm', 'điểm tựa ở tay cầm', 'điểm tựa ở giữa thùng xe', 'không phải đòn bẩy'],
 'Trục bánh xe là điểm tựa; hàng gần điểm tựa hơn tay cầm nên lực nâng nhỏ hơn trọng lượng hàng.'],
['mom', 'Cân Robecvan (cân đòn) hoạt động dựa trên',
 ['điều kiện cân bằng của đòn bẩy có hai cánh tay đòn bằng nhau', 'lực đẩy Archimedes', 'áp suất chất lỏng', 'lực ma sát'],
 'Hai cánh tay đòn bằng nhau nên khi cân thăng bằng, trọng lượng (khối lượng) hai bên bằng nhau.'],
['mom', 'Tay nắm cửa được đặt xa bản lề vì',
 ['tăng cánh tay đòn nên chỉ cần lực nhỏ để mở cửa', 'để cửa đẹp hơn', 'để giảm khối lượng cửa', 'tay nắm gần bản lề dễ bị kẹt'],
 'M = F·d, d lớn thì cùng moment cần F nhỏ hơn.'],
['mom', 'Dùng cờ lê cán dài mở ốc dễ hơn cờ lê cán ngắn vì',
 ['cánh tay đòn lớn hơn nên moment lực lớn hơn với cùng lực tay', 'cờ lê dài nặng hơn', 'cờ lê dài cứng hơn', 'ma sát nhỏ hơn'],
 'M = F·d tăng theo d, đủ thắng moment ma sát giữ ốc.'],
['mom', 'Thanh AB dài 1 m, trục quay O ở chính giữa. Treo vật 20 N tại A. Để thanh cân bằng, tại điểm cách O 25 cm về phía B phải treo vật',
 ['40 N', '20 N', '10 N', '80 N'],
 '20 × 0,5 = F × 0,25 → F = 40 N.'],
['mom', 'Trên bập bênh, bé An 20 kg ngồi cách trục 1,5 m. Bé Bình 30 kg phải ngồi cách trục bao nhiêu để cân bằng?',
 ['1 m', '2,25 m', '1,5 m', '0,5 m'],
 '200 × 1,5 = 300 × d → d = 1 m.'],
['mom', 'Dùng xà beng nâng tảng đá 1000 N. Khoảng cách từ điểm tựa đến đá 20 cm, đến tay cầm 1 m. Lực tối thiểu cần dùng là',
 ['200 N', '500 N', '5000 N', '1000 N'],
 'F × 1 = 1000 × 0,2 → F = 200 N.'],
['mom', 'Đòn gánh dài 1,5 m, hai đầu treo thúng 20 kg và 30 kg. Để đòn cân bằng, vai phải đặt cách thúng 30 kg',
 ['0,6 m', '0,9 m', '0,75 m', '0,5 m'],
 'Gọi x là khoảng cách đến thúng 30 kg: 300x = 200(1,5 − x) → 500x = 300 → x = 0,6 m.'],
['mom', 'Đòn bẩy AB dài 2 m. Đầu A treo vật 600 N, điểm tựa O cách A 0,5 m. Lực cần tác dụng vuông góc tại B để cân bằng là',
 ['200 N', '150 N', '600 N', '2400 N'],
 'OB = 1,5 m; F × 1,5 = 600 × 0,5 → F = 200 N.'],
['mom', 'Lực 50 N tác dụng vuông góc vào cờ lê tại điểm cách trục ốc 20 cm. Moment của lực đối với trục ốc là',
 ['10 N·m', '1000 N·m', '2,5 N·m', '70 N·m'],
 'M = F·d = 50 × 0,2 = 10 N·m.'],
['mom', 'Đẩy cửa với lực 5 N tại điểm cách bản lề 80 cm, hoặc lực 10 N tại điểm cách bản lề 40 cm (đều vuông góc cửa). So sánh tác dụng làm quay:',
 ['bằng nhau vì hai moment đều bằng 4 N·m', 'lực 10 N làm quay mạnh hơn', 'lực 5 N làm quay mạnh hơn', 'không so sánh được'],
 '5 × 0,8 = 4 N·m và 10 × 0,4 = 4 N·m → moment bằng nhau.'],
['mom', 'Tác dụng lực vào cánh cửa theo phương song song với mặt cửa (hướng về bản lề). Kết quả là',
 ['cửa không quay vì giá của lực đi qua trục quay', 'cửa quay nhanh', 'cửa quay chậm', 'cửa bị gãy'],
 'Giá của lực cắt trục quay → cánh tay đòn bằng 0 → moment bằng 0.'],
['mom', 'Thanh nhẹ có trục quay O. Bên trái treo 10 N cách O 30 cm và 20 N cách O 60 cm. Để cân bằng cần treo ở bên phải, cách O 50 cm, một vật',
 ['30 N', '15 N', '60 N', '20 N'],
 'Moment trái: 10 × 0,3 + 20 × 0,6 = 15 N·m; F × 0,5 = 15 → F = 30 N.'],
['mom', 'Thanh nhẹ có trục O. Bên trái treo 30 N cách O 40 cm. Bên phải treo 20 N cách O 30 cm và vật x cách O 60 cm. Thanh cân bằng khi x bằng',
 ['10 N', '20 N', '30 N', '5 N'],
 '30 × 40 = 20 × 30 + x × 60 → 1200 = 600 + 60x → x = 10 N.'],
['mom', 'Tuốc-nơ-vít có cán to giúp',
 ['tăng cánh tay đòn quanh trục cán nên vặn vít dễ hơn', 'giảm ma sát với vít', 'giảm khối lượng dụng cụ', 'tăng độ dài mũi'],
 'Tay tác dụng lực ở mép cán; cán to → d lớn → moment lớn hơn với cùng lực tay.'],
['mom', 'Vô lăng ô tô có đường kính lớn để',
 ['tăng cánh tay đòn, người lái cần lực nhỏ hơn', 'người lái dễ nhìn', 'giảm khối lượng xe', 'tăng tốc độ xe'],
 'Cùng moment cần để quay trục lái, d lớn → F nhỏ.'],
['mom', 'Khi cân bằng cân Robecvan, đĩa trái đặt vật, đĩa phải đặt quả cân 200 g. Kết luận:',
 ['khối lượng vật là 200 g vì hai cánh tay đòn bằng nhau', 'khối lượng vật lớn hơn 200 g', 'khối lượng vật nhỏ hơn 200 g', 'không kết luận được'],
 'd<sub>1</sub> = d<sub>2</sub> nên cân bằng khi P<sub>1</sub> = P<sub>2</sub>, tức m<sub>vật</sub> = 200 g.'],
['mom', 'Đòn bẩy KHÔNG cho lợi về lực khi',
 ['cánh tay đòn của lực bằng cánh tay đòn của vật', 'cánh tay đòn của lực lớn hơn của vật', 'điểm tựa nằm gần vật', 'đòn dài'],
 'F<sub>1</sub>d<sub>1</sub> = F<sub>2</sub>d<sub>2</sub>, d<sub>1</sub> = d<sub>2</sub> → F<sub>2</sub> = F<sub>1</sub>, không lợi cũng không thiệt.'],
['mom', 'Muốn nhổ một chiếc đinh bằng xà beng nhẹ nhàng hơn, ta nên',
 ['cầm xa đầu nhổ đinh (tăng cánh tay đòn của lực tay)', 'cầm gần đầu nhổ đinh', 'dùng xà beng ngắn hơn', 'dùng xà beng nặng hơn'],
 'Cánh tay đòn của tay càng dài thì lực cần thiết càng nhỏ.'],
['mom', 'Cái kìm là đòn bẩy có',
 ['điểm tựa ở chốt kìm, lực tay ở cán, vật ở mỏ kìm', 'điểm tựa ở mỏ kìm', 'điểm tựa ở cán', 'không phải đòn bẩy'],
 'Chốt kìm là trục quay; cán dài hơn mỏ nên lực kẹp lớn hơn lực tay.'],
['mom', 'Người có trọng lượng 500 N ngồi cách trục bập bênh 1,2 m. Để cân bằng, vật 400 N phải đặt ở phía bên kia cách trục',
 ['1,5 m', '0,96 m', '1,2 m', '2 m'],
 '500 × 1,2 = 400 × d → d = 1,5 m.'],
['mom', 'Cánh tay đòn của lực là',
 ['khoảng cách từ trục quay đến giá (đường thẳng chứa) của lực', 'khoảng cách từ trục quay đến điểm đặt lực', 'độ dài của đòn bẩy', 'chiều dài của vectơ lực'],
 'Khi lực không vuông góc với đòn, cánh tay đòn là đoạn vuông góc hạ từ trục quay xuống giá của lực.'],
['mom', 'Tại sao dùng cùng một lực, kéo xe cút kít nâng vật nặng ở gần bánh xe lại nhẹ hơn ở gần tay cầm?',
 ['Vật gần điểm tựa hơn nên moment của trọng lượng nhỏ hơn', 'Vật gần bánh nên ma sát nhỏ hơn', 'Bánh xe nâng vật lên', 'Không có sự khác biệt'],
 'Moment của trọng lượng vật = P·d<sub>1</sub>; d<sub>1</sub> nhỏ → cần lực nâng F = P·d<sub>1</sub>/d<sub>2</sub> nhỏ hơn.'],
];
