// Ngân hàng câu VIẾT TAY — phần ĐIỆN (Vật lí 8 · KHTN 8, KNTT)
// Chương: dt (nhiễm điện – điện tích – dòng điện – nguồn điện) · mach (sơ đồ mạch điện – tác dụng dòng điện)
//         iu (cường độ dòng điện – hiệu điện thế – đo I, U) · ntss (mạch nối tiếp – song song)
export const DIEN = [
/* ───────── NHIỄM ĐIỆN – ĐIỆN TÍCH – DÒNG ĐIỆN – NGUỒN ĐIỆN ───────── */
['dt', 'Cọ xát thước nhựa vào vải khô rồi đưa lại gần các vụn giấy, thước hút vụn giấy. Kết luận:',
 ['thước nhựa đã bị nhiễm điện do cọ xát', 'thước nhựa trở thành nam châm', 'vụn giấy bị nóng lên', 'thước nhựa nặng hơn'],
 'Vật nhiễm điện có khả năng hút các vật nhẹ khác như vụn giấy, sợi bông.'],
['dt', 'Có mấy loại điện tích và chúng tương tác với nhau như thế nào?',
 ['Hai loại (dương, âm); cùng loại đẩy nhau, khác loại hút nhau', 'Hai loại; cùng loại hút nhau, khác loại đẩy nhau', 'Một loại; luôn hút nhau', 'Ba loại; luôn đẩy nhau'],
 'Quy ước: điện tích dương và âm; các điện tích cùng loại đẩy nhau, khác loại hút nhau.'],
['dt', 'Theo quy ước, thanh thuỷ tinh cọ xát vào lụa và thanh nhựa sẫm màu cọ xát vào vải khô lần lượt nhiễm điện',
 ['dương và âm', 'âm và dương', 'đều dương', 'đều âm'],
 'Quy ước: thuỷ tinh cọ xát lụa mang điện dương (+); nhựa sẫm cọ xát vải khô mang điện âm (−).'],
['dt', 'Một vật nhiễm điện âm khi',
 ['nhận thêm electron', 'mất bớt electron', 'mất bớt hạt nhân', 'không có electron'],
 'Electron mang điện âm; vật nhận thêm electron thì thừa điện tích âm → nhiễm điện âm; mất electron → nhiễm điện dương.'],
['dt', 'Khi cọ xát hai vật trung hoà với nhau, sau đó',
 ['hai vật nhiễm điện trái dấu vì electron chuyển từ vật này sang vật kia', 'hai vật nhiễm điện cùng dấu', 'chỉ một vật nhiễm điện', 'điện tích mới được sinh ra ở cả hai vật'],
 'Electron dịch chuyển từ vật này sang vật kia: vật mất electron nhiễm dương, vật nhận electron nhiễm âm.'],
['dt', 'Hai quả cầu nhẹ treo bằng sợi chỉ, đưa lại gần nhau thì đẩy nhau. Kết luận:',
 ['hai quả cầu nhiễm điện cùng loại', 'hai quả cầu nhiễm điện khác loại', 'chỉ một quả cầu nhiễm điện', 'cả hai không nhiễm điện'],
 'Chỉ có các điện tích cùng loại mới đẩy nhau.'],
['dt', 'Hai quả cầu nhẹ hút nhau. Nhận xét nào chắc chắn đúng?',
 ['Ít nhất một quả cầu nhiễm điện', 'Cả hai nhiễm điện trái dấu', 'Cả hai nhiễm điện cùng dấu', 'Cả hai không nhiễm điện'],
 'Hút nhau xảy ra khi hai vật trái dấu hoặc khi một vật nhiễm điện hút vật trung hoà. Chắc chắn có vật nhiễm điện.'],
['dt', 'Sấm sét là',
 ['hiện tượng phóng điện giữa các đám mây nhiễm điện hoặc giữa mây và mặt đất', 'tiếng động do gió mạnh', 'ánh sáng Mặt Trời phản chiếu', 'hiện tượng nở vì nhiệt của không khí'],
 'Mây nhiễm điện do cọ xát với không khí; khi điện tích đủ lớn xảy ra phóng điện tạo tia sét và tiếng sấm.'],
['dt', 'Mùa đông cởi áo len trong tối nghe tiếng lách tách và thấy chớp sáng nhỏ vì',
 ['áo len và áo trong cọ xát nhiễm điện, phóng điện gây tiếng nổ nhỏ', 'áo len bị rách', 'cơ thể nóng lên', 'áo len phát sáng tự nhiên'],
 'Đây là hiện tượng nhiễm điện do cọ xát rồi phóng điện qua không khí, giống tia sét thu nhỏ.'],
['dt', 'Chải tóc khô bằng lược nhựa, tóc bị lược hút và dựng lên vì',
 ['lược và tóc cọ xát, nhiễm điện trái dấu nên hút nhau', 'lược có nam châm', 'tóc bị nóng lên', 'lược làm tóc khô'],
 'Cọ xát làm lược và tóc nhiễm điện trái dấu → hút nhau; các sợi tóc cùng dấu còn đẩy nhau dựng lên.'],
['dt', 'Cánh quạt điện quay lâu ngày bám nhiều bụi hơn các vật đứng yên vì',
 ['cánh quạt cọ xát với không khí, nhiễm điện nên hút bụi', 'cánh quạt có keo', 'gió thổi bụi vào cánh quạt', 'bụi nặng hơn không khí'],
 'Cọ xát với không khí làm cánh quạt nhiễm điện, hút các hạt bụi nhẹ; mép cánh cọ xát nhiều nên bám bụi nhiều.'],
['dt', 'Xe bồn chở xăng dầu thường có dây xích sắt kéo lê trên mặt đường để',
 ['truyền điện tích do cọ xát xuống đất, tránh phóng điện gây cháy', 'giảm tốc độ xe', 'tăng ma sát khi phanh', 'làm xe cân bằng'],
 'Xăng cọ xát với bồn khi xe chạy gây nhiễm điện; dây xích dẫn điện tích xuống đất để không tích tụ gây tia lửa.'],
['dt', 'Vật nhiễm điện có khả năng',
 ['hút các vật nhẹ và làm sáng bóng đèn bút thử điện', 'chỉ đẩy các vật khác', 'hút mọi vật kể cả vật rất nặng', 'tự phát ra ánh sáng liên tục'],
 'Vật nhiễm điện hút vụn giấy, sợi bông... và có thể làm sáng bóng đèn bút thử điện khi chạm vào.'],
['dt', 'Trong nguyên tử, hạt nào mang điện tích âm và có thể dịch chuyển từ nguyên tử này sang nguyên tử khác?',
 ['Electron', 'Hạt nhân', 'Proton', 'Nguyên tử'],
 'Electron mang điện âm, chuyển động quanh hạt nhân và có thể rời khỏi nguyên tử; hạt nhân mang điện dương và hầu như cố định.'],
['dt', 'Bình thường nguyên tử trung hoà về điện vì',
 ['tổng điện tích âm của các electron bằng điện tích dương của hạt nhân', 'nguyên tử không có điện tích', 'electron đứng yên', 'hạt nhân không mang điện'],
 'Số điện tích âm (electron) cân bằng với điện tích dương của hạt nhân nên nguyên tử trung hoà.'],
['dt', 'Thanh A hút thanh B, thanh B đẩy thanh C, thanh C nhiễm điện âm. Kết luận nào đúng?',
 ['B nhiễm điện âm; A nhiễm điện dương hoặc không nhiễm điện', 'A nhiễm điện âm; B nhiễm điện dương', 'A và B đều nhiễm điện âm', 'B không nhiễm điện'],
 'B đẩy C nên B cùng dấu với C (âm). A hút B nên A dương hoặc trung hoà.'],
['dt', 'Sau khi cọ xát thanh nhựa sẫm màu với mảnh vải khô, mảnh vải',
 ['nhiễm điện dương vì mất electron sang thanh nhựa', 'nhiễm điện âm', 'không nhiễm điện', 'nhiễm điện cùng dấu với thanh nhựa'],
 'Thanh nhựa nhận electron (âm) thì mảnh vải mất electron nên mang điện dương.'],
['dt', 'Cầm thanh kim loại bằng tay rồi cọ xát vào vải khô, thanh hầu như không nhiễm điện vì',
 ['kim loại dẫn điện, điện tích truyền qua tay xuống đất', 'kim loại không có electron', 'vải không cọ xát được kim loại', 'kim loại quá cứng'],
 'Kim loại và cơ thể người đều dẫn điện, điện tích không tích tụ được trên thanh. Cầm bằng cán cách điện thì thanh sẽ nhiễm điện.'],
['dt', 'Vì sao các thí nghiệm nhiễm điện do cọ xát dễ thành công vào ngày hanh khô hơn ngày ẩm ướt?',
 ['Không khí ẩm dẫn điện tốt hơn, điện tích trên vật nhanh chóng bị truyền đi', 'Ngày khô vật nặng hơn', 'Ngày ẩm không cọ xát được', 'Ngày khô có nhiều ánh sáng'],
 'Hơi nước trong không khí ẩm làm điện tích tích tụ trên vật dễ tiêu tán.'],
['dt', 'Dòng điện là',
 ['dòng các hạt mang điện dịch chuyển có hướng', 'dòng các nguyên tử chuyển động', 'sự chuyển động hỗn loạn của electron', 'dòng nước chảy trong dây dẫn'],
 'Định nghĩa: dòng điện là dòng chuyển dời có hướng của các hạt mang điện (electron, ion).'],
['dt', 'Trong dây dẫn kim loại, dòng điện là dòng dịch chuyển có hướng của',
 ['các electron tự do', 'các hạt nhân nguyên tử', 'các nguyên tử kim loại', 'các ion dương'],
 'Kim loại có các electron tự do; khi có nguồn điện chúng dịch chuyển có hướng tạo thành dòng điện.'],
['dt', 'Nguồn điện có đặc điểm nào sau đây?',
 ['Có hai cực (dương và âm) và có khả năng cung cấp, duy trì dòng điện', 'Chỉ có một cực', 'Tiêu thụ điện năng', 'Chỉ hoạt động khi đã bị nhiễm điện'],
 'Mọi nguồn điện đều có cực dương (+) và cực âm (−), tạo ra và duy trì dòng điện trong mạch kín.'],
['dt', 'Thiết bị nào sau đây KHÔNG phải là nguồn điện?',
 ['Bóng đèn', 'Pin', 'Acquy', 'Máy phát điện'],
 'Bóng đèn là thiết bị tiêu thụ điện; pin, acquy, máy phát điện cung cấp dòng điện.'],
['dt', 'Chiều dòng điện theo quy ước là',
 ['từ cực dương qua dây dẫn và thiết bị điện tới cực âm của nguồn', 'từ cực âm qua dây dẫn tới cực dương của nguồn', 'chiều dịch chuyển của electron', 'không xác định'],
 'Quy ước: dòng điện chạy từ cực + qua các thiết bị về cực − của nguồn (ở mạch ngoài).'],
['dt', 'Trong kim loại, chiều dịch chuyển của các electron tự do so với chiều dòng điện quy ước là',
 ['ngược chiều', 'cùng chiều', 'vuông góc', 'lúc cùng lúc ngược'],
 'Electron mang điện âm nên đi từ cực − về cực +, ngược với chiều quy ước của dòng điện.'],
['dt', 'Nhóm vật liệu nào sau đây đều là chất dẫn điện?',
 ['Đồng, nhôm, dung dịch muối, than chì', 'Nhựa, gỗ khô, sứ, cao su', 'Thuỷ tinh, đồng, nhựa, gỗ', 'Không khí khô, nhôm, sứ, bạc'],
 'Kim loại, than chì và các dung dịch muối, axit dẫn điện; nhựa, gỗ khô, sứ, cao su, thuỷ tinh là chất cách điện.'],
['dt', 'Dây điện có lõi bằng đồng và vỏ bằng nhựa vì',
 ['đồng dẫn điện tốt, nhựa cách điện bảo vệ an toàn', 'đồng nhẹ, nhựa nặng', 'đồng cách điện, nhựa dẫn điện', 'nhựa dẫn nhiệt tốt'],
 'Lõi đồng dẫn điện; vỏ nhựa cách điện, ngăn dòng điện truyền ra ngoài gây giật hoặc chập.'],
['dt', 'Không nên dùng tay ướt chạm vào thiết bị điện vì',
 ['nước thường (có tạp chất) dẫn điện, dễ gây điện giật', 'nước làm hỏng thiết bị', 'tay ướt trơn', 'nước cách điện'],
 'Nước máy, nước sinh hoạt chứa muối khoáng nên dẫn điện, làm dòng điện dễ đi qua cơ thể.'],
['dt', 'Bóng đèn trong mạch chỉ sáng khi',
 ['mạch điện kín: nguồn, dây dẫn và đèn nối liền thành vòng', 'chỉ cần có nguồn điện', 'chỉ cần nối một đầu đèn với nguồn', 'mạch hở'],
 'Dòng điện chỉ chạy được trong mạch kín liên tục từ cực + qua đèn về cực −.'],
['dt', 'Pin và acquy khi hoạt động biến đổi dạng năng lượng nào thành điện năng?',
 ['Hoá năng', 'Cơ năng', 'Quang năng', 'Nhiệt năng'],
 'Trong pin, acquy xảy ra phản ứng hoá học tạo ra dòng điện: hoá năng → điện năng.'],
['dt', 'Trên pin tròn, đầu có núm nhô lên là',
 ['cực dương', 'cực âm', 'không phải cực', 'cực dương hoặc âm tuỳ pin'],
 'Đầu núm nhô là cực (+); mặt đáy phẳng là cực (−).'],
['dt', 'Điểm khác cơ bản giữa acquy và pin thường là',
 ['acquy có thể nạp lại điện để dùng nhiều lần', 'acquy không có cực', 'acquy không cung cấp dòng điện', 'pin có điện áp lớn hơn'],
 'Acquy có thể nạp (sạc) lại nhiều lần; pin thường dùng hết thì bỏ.'],
['dt', 'Pin mặt trời (tấm quang điện) biến đổi',
 ['năng lượng ánh sáng thành điện năng', 'nhiệt năng thành điện năng', 'điện năng thành ánh sáng', 'hoá năng thành điện năng'],
 'Ánh sáng chiếu vào tấm quang điện tạo ra dòng điện: quang năng → điện năng.'],
['dt', 'Đinamô xe đạp là nguồn điện biến đổi',
 ['cơ năng thành điện năng', 'điện năng thành cơ năng', 'hoá năng thành điện năng', 'nhiệt năng thành điện năng'],
 'Bánh xe quay làm quay đinamô (một máy phát điện nhỏ) tạo ra dòng điện thắp đèn.'],
['dt', 'Chạm bút thử điện vào vật nhiễm điện mạnh, đèn bút loé sáng chứng tỏ',
 ['điện tích dịch chuyển qua bút tạo dòng điện ngắn', 'vật là nguồn điện lâu dài', 'bút thử điện có pin', 'vật nóng lên'],
 'Điện tích trên vật dịch chuyển qua đèn bút thử điện trong thời gian rất ngắn tạo thành dòng điện làm đèn loé sáng.'],
['dt', 'Khi cọ xát hai vật, tổng điện tích của hai vật',
 ['không thay đổi, điện tích chỉ chuyển từ vật này sang vật kia', 'tăng lên', 'giảm đi', 'bằng 0 ở mỗi vật'],
 'Cọ xát không tạo ra điện tích mới; electron chỉ chuyển từ vật này sang vật kia.'],
['dt', 'Trong chiếc đèn pin, bộ phận nào là nguồn điện?',
 ['Pin', 'Bóng đèn', 'Công tắc', 'Vỏ đèn'],
 'Pin cung cấp dòng điện; bóng đèn tiêu thụ điện; công tắc đóng ngắt mạch.'],
['dt', 'Đưa thước nhựa đã nhiễm điện lại gần dòng nước nhỏ chảy từ vòi, dòng nước',
 ['bị hút lệch về phía thước', 'bị đẩy ra xa thước', 'ngừng chảy', 'chảy nhanh hơn'],
 'Vật nhiễm điện hút các vật nhẹ, dòng nước nhỏ cũng bị hút cong về phía thước.'],
['dt', 'Trong thanh kim loại nối giữa hai cực của pin, các electron tự do dịch chuyển',
 ['từ cực âm sang cực dương của pin (ở mạch ngoài)', 'từ cực dương sang cực âm của pin', 'hỗn loạn không có hướng', 'không dịch chuyển'],
 'Electron mang điện âm bị cực âm đẩy và cực dương hút.'],
['dt', 'Màng bọc thực phẩm sau khi kéo ra khỏi cuộn thường dính vào tay, vào bát vì',
 ['màng bị nhiễm điện do cọ xát khi kéo', 'màng có keo', 'màng ướt', 'màng nóng'],
 'Kéo màng làm nó cọ xát và nhiễm điện, hút vào các vật khác.'],

/* ───────── SƠ ĐỒ MẠCH ĐIỆN – TÁC DỤNG CỦA DÒNG ĐIỆN ───────── */
['mach', 'Trong sơ đồ mạch điện, kí hiệu hai đoạn thẳng song song, một dài một ngắn biểu thị',
 ['nguồn điện (pin), vạch dài là cực dương', 'công tắc', 'bóng đèn', 'ampe kế'],
 'Kí hiệu nguồn điện: vạch dài (mảnh) là cực +, vạch ngắn (đậm) là cực −.'],
['mach', 'Sơ đồ mạch điện là',
 ['hình vẽ dùng các kí hiệu quy ước để mô tả cách mắc các bộ phận của mạch', 'ảnh chụp mạch điện', 'bản vẽ kích thước thật', 'bảng liệt kê các thiết bị'],
 'Sơ đồ giúp mô tả và lắp mạch đúng cách mà không cần vẽ hình dạng thật của thiết bị.'],
['mach', 'Kí hiệu vòng tròn có dấu chéo (×) ở trong dùng để biểu thị',
 ['bóng đèn', 'nguồn điện', 'công tắc mở', 'dây dẫn'],
 'Bóng đèn được kí hiệu bằng vòng tròn có dấu chéo bên trong.'],
['mach', 'Khi công tắc trong mạch mở thì',
 ['mạch hở, không có dòng điện, đèn không sáng', 'mạch kín, đèn sáng', 'đèn sáng yếu', 'dòng điện chạy ngược'],
 'Công tắc mở làm mạch bị ngắt (hở), dòng điện không thể chạy.'],
['mach', 'Mạch điện kín là mạch',
 ['dòng điện có thể chạy liên tục từ cực này qua các thiết bị về cực kia của nguồn', 'không có công tắc', 'có nhiều bóng đèn', 'chỉ có nguồn điện'],
 'Mạch kín: các bộ phận được nối liền thành vòng khép kín với nguồn điện.'],
['mach', 'Cầu chì bảo vệ mạch điện dựa vào tác dụng nào của dòng điện?',
 ['Tác dụng nhiệt: dây chì nóng chảy khi dòng điện quá lớn', 'Tác dụng từ', 'Tác dụng hoá học', 'Tác dụng phát sáng'],
 'Dòng quá lớn làm dây chì (nhiệt độ nóng chảy thấp) chảy đứt, ngắt mạch.'],
['mach', 'Dòng điện có các tác dụng nào?',
 ['Nhiệt, phát sáng, từ, hoá học, sinh lí', 'Chỉ nhiệt và phát sáng', 'Chỉ từ và hoá học', 'Chỉ sinh lí'],
 'Dòng điện có năm tác dụng: nhiệt, phát sáng, từ, hoá học và sinh lí.'],
['mach', 'Bàn là, bếp điện, nồi cơm điện hoạt động chủ yếu dựa trên',
 ['tác dụng nhiệt của dòng điện', 'tác dụng từ', 'tác dụng hoá học', 'tác dụng sinh lí'],
 'Dòng điện qua dây đốt (dây điện trở) làm dây nóng lên.'],
['mach', 'Dây tóc bóng đèn sợi đốt làm bằng vonfram vì',
 ['vonfram có nhiệt độ nóng chảy rất cao, chịu được nhiệt độ hàng nghìn độ', 'vonfram rẻ', 'vonfram cách điện', 'vonfram dẫn điện kém'],
 'Dây tóc phải nóng đến khoảng 2500 °C để phát sáng; vonfram nóng chảy ở khoảng 3400 °C.'],
['mach', 'Bóng đèn sợi đốt phát sáng là do',
 ['dây tóc bị dòng điện nung nóng tới nhiệt độ cao', 'khí trong bóng phát sáng', 'thuỷ tinh phát sáng', 'dây tóc có chất phát quang'],
 'Tác dụng nhiệt làm dây tóc nóng sáng; đây là lí do đèn sợi đốt toả nhiều nhiệt, kém tiết kiệm.'],
['mach', 'Đèn LED (đi-ốt phát quang) có đặc điểm',
 ['chỉ cho dòng điện đi qua theo một chiều nhất định', 'cho dòng điện đi qua theo cả hai chiều', 'phát sáng nhờ dây tóc nóng', 'chỉ sáng với dòng điện rất lớn'],
 'LED chỉ sáng khi mắc đúng chiều (bản cực nhỏ nối cực +, bản cực lớn nối cực −).'],
['mach', 'Bóng đèn của bút thử điện sáng nhờ',
 ['chất khí trong bóng phát sáng khi có dòng điện chạy qua', 'dây tóc nóng sáng', 'thuỷ tinh nóng lên', 'nam châm nhỏ bên trong'],
 'Đèn bút thử điện là đèn khí (neon), sáng dù dòng điện rất nhỏ, không nóng.'],
['mach', 'Nam châm điện gồm cuộn dây quấn quanh lõi sắt non. Khi ngắt dòng điện thì',
 ['lõi sắt mất từ tính, không hút sắt nữa', 'lõi sắt vẫn hút sắt như cũ', 'lõi sắt hút mạnh hơn', 'cuộn dây nóng lên'],
 'Từ tính của nam châm điện chỉ có khi có dòng điện chạy trong cuộn dây; sắt non không giữ từ tính lâu.'],
['mach', 'Chuông điện, rơle điện từ, cần cẩu điện nâng sắt vụn hoạt động dựa vào',
 ['tác dụng từ của dòng điện', 'tác dụng nhiệt', 'tác dụng hoá học', 'tác dụng sinh lí'],
 'Dòng điện qua cuộn dây tạo nam châm điện hút các vật bằng sắt, thép.'],
['mach', 'Trong thí nghiệm mạ đồng (dung dịch muối đồng sunfat), vật cần mạ được nối với',
 ['cực âm của nguồn', 'cực dương của nguồn', 'cả hai cực', 'không nối với nguồn'],
 'Tác dụng hoá học: đồng tách ra khỏi dung dịch và bám vào thỏi than (vật) nối cực âm.'],
['mach', 'Dòng điện đi qua cơ thể người gây co giật cơ, tim ngừng đập... Đó là',
 ['tác dụng sinh lí', 'tác dụng nhiệt', 'tác dụng từ', 'tác dụng hoá học'],
 'Tác dụng sinh lí có thể gây nguy hiểm, nhưng được ứng dụng trong châm cứu điện, máy kích tim.'],
['mach', 'Biện pháp nào sau đây KHÔNG an toàn khi sử dụng điện?',
 ['Dùng dây đồng thay cho dây chì trong cầu chì để không bị đứt', 'Ngắt cầu dao trước khi sửa điện', 'Không chạm vào dây điện bị hở', 'Dùng dụng cụ có tay cầm cách điện'],
 'Dây đồng có nhiệt độ nóng chảy cao, không đứt khi dòng quá lớn → mất tác dụng bảo vệ, dễ cháy.'],
['mach', 'Khi dòng điện chạy qua bất kì dây dẫn nào thì dây dẫn đều',
 ['nóng lên (tác dụng nhiệt)', 'phát sáng', 'trở thành nam châm vĩnh cửu', 'bị ăn mòn'],
 'Tác dụng nhiệt xuất hiện ở mọi vật dẫn có dòng điện chạy qua, dù nhiều hay ít.'],
['mach', 'Quạt điện, máy bơm nước, động cơ điện hoạt động chủ yếu dựa vào',
 ['tác dụng từ của dòng điện', 'tác dụng nhiệt', 'tác dụng hoá học', 'tác dụng phát sáng'],
 'Động cơ điện quay nhờ lực từ giữa nam châm và cuộn dây có dòng điện.'],
['mach', 'Mạch có hai bóng đèn mắc nối tiếp với một công tắc. Khi ngắt công tắc thì',
 ['cả hai đèn đều tắt', 'chỉ đèn gần công tắc tắt', 'chỉ đèn xa công tắc tắt', 'cả hai vẫn sáng'],
 'Công tắc ngắt làm mạch hở, không còn dòng điện qua đèn nào.'],
['mach', 'Muốn hai bóng đèn trong phòng có thể tắt mở độc lập với nhau, phải mắc',
 ['hai đèn song song, mỗi đèn có công tắc riêng ở nhánh của nó', 'hai đèn nối tiếp với một công tắc chung', 'hai đèn nối tiếp với hai công tắc', 'hai đèn song song với một công tắc ở mạch chính'],
 'Mỗi nhánh song song có công tắc riêng nên tắt một đèn không ảnh hưởng đèn kia.'],
['mach', 'Đèn LED tiết kiệm điện hơn đèn sợi đốt vì',
 ['phần lớn điện năng biến thành ánh sáng, ít toả nhiệt', 'LED nhỏ hơn', 'LED có màu đẹp hơn', 'LED không cần nguồn điện'],
 'Đèn sợi đốt biến hơn 90% điện năng thành nhiệt vô ích; LED phát sáng hiệu quả hơn nhiều.'],
['mach', 'Nồi cơm điện có bộ phận chính là',
 ['dây đốt (dây điện trở) toả nhiệt khi có dòng điện', 'nam châm điện', 'bóng đèn', 'pin'],
 'Dây đốt nóng lên nhờ tác dụng nhiệt của dòng điện để nấu chín cơm.'],
['mach', 'Mắc đèn LED vào mạch nhưng đèn không sáng dù mạch kín và nguồn tốt. Nguyên nhân có thể là',
 ['mắc LED ngược chiều', 'LED không cần nguồn', 'dây dẫn quá dài', 'công tắc đang đóng'],
 'LED chỉ cho dòng điện đi qua theo một chiều; đảo hai chân LED đèn sẽ sáng.'],
['mach', 'Bóng đèn trong mạch kín không sáng. Nguyên nhân nào sau đây KHÔNG thể là lí do?',
 ['Công tắc đang ở vị trí đóng', 'Dây tóc bóng đèn bị đứt', 'Pin đã hết điện', 'Dây nối tiếp xúc kém với chốt đèn'],
 'Công tắc đóng là điều kiện để mạch kín, không phải nguyên nhân làm đèn tắt.'],
['mach', 'Trên sơ đồ mạch điện, chiều dòng điện được biểu diễn bằng mũi tên',
 ['đi ra từ cực dương của nguồn, qua thiết bị, về cực âm', 'đi ra từ cực âm của nguồn', 'hướng vào bóng đèn từ cả hai phía', 'vẽ tuỳ ý'],
 'Chiều quy ước của dòng điện ở mạch ngoài là từ cực + về cực −.'],
['mach', 'Aptomat (cầu dao tự động) trong nhà tự ngắt khi quá tải hoặc chập mạch, dựa trên',
 ['tác dụng nhiệt và tác dụng từ của dòng điện', 'tác dụng hoá học', 'tác dụng sinh lí', 'tác dụng phát sáng'],
 'Dòng quá lớn làm băng kép nóng cong hoặc nam châm điện hút lẫy → ngắt mạch.'],
['mach', 'Dùng mạch điện gồm pin, bóng đèn, dây dẫn có hai đầu kẹp để kiểm tra vật. Kẹp vật vào, đèn sáng thì vật là',
 ['chất dẫn điện', 'chất cách điện', 'nguồn điện', 'nam châm'],
 'Đèn sáng chứng tỏ dòng điện đi qua vật → vật dẫn điện.'],
['mach', 'Trong mạch gồm pin, công tắc, bóng đèn, thiết bị tiêu thụ điện năng là',
 ['bóng đèn', 'pin', 'công tắc', 'dây dẫn'],
 'Bóng đèn biến điện năng thành nhiệt và ánh sáng; pin cung cấp điện; công tắc điều khiển.'],
['mach', 'Máy sấy tóc hoạt động dựa trên các tác dụng nào của dòng điện?',
 ['Tác dụng nhiệt (dây đốt) và tác dụng từ (động cơ quạt)', 'Chỉ tác dụng nhiệt', 'Tác dụng hoá học và sinh lí', 'Chỉ tác dụng từ'],
 'Dây đốt nóng nhờ tác dụng nhiệt; quạt thổi gió quay nhờ động cơ điện (tác dụng từ).'],
['mach', 'Nam châm điện hút được vật sắt mạnh hơn khi',
 ['tăng cường độ dòng điện hoặc tăng số vòng dây', 'giảm cường độ dòng điện', 'bỏ lõi sắt ra', 'dùng dây dài hơn nhưng ít vòng'],
 'Lực từ của nam châm điện tăng khi dòng điện lớn hơn hoặc số vòng dây nhiều hơn.'],
['mach', 'Cho dòng điện qua dung dịch đồng sunfat với hai thỏi than, sau một thời gian thỏi than nối cực âm được phủ lớp màu đỏ nhạt. Đó là biểu hiện của',
 ['tác dụng hoá học', 'tác dụng nhiệt', 'tác dụng từ', 'tác dụng phát sáng'],
 'Dòng điện tách đồng ra khỏi dung dịch và đồng bám lên thỏi than nối cực âm.'],
['mach', 'Khi sạc (nạp) pin điện thoại, điện năng được biến đổi thành',
 ['hoá năng (tác dụng hoá học của dòng điện)', 'cơ năng', 'quang năng', 'nhiệt năng hoàn toàn'],
 'Nạp pin là quá trình ngược của phóng điện: điện năng → hoá năng tích trong pin.'],
['mach', 'Khi dùng bút thử điện, phải chạm ngón tay vào đầu kim loại phía trên bút để',
 ['tạo mạch kín cho dòng điện rất nhỏ đi qua người xuống đất làm đèn sáng', 'giữ bút không rơi', 'làm bút nóng lên', 'ngắt dòng điện'],
 'Bút có điện trở lớn nên dòng qua người rất nhỏ, an toàn; không chạm tay thì mạch hở, đèn không sáng.'],
['mach', 'Dây tóc bóng đèn được làm rất mảnh và cuộn xoắn để',
 ['nóng lên nhiều và tập trung, dễ đạt nhiệt độ phát sáng', 'tiết kiệm vonfram', 'cho đẹp', 'dẫn điện tốt hơn'],
 'Dây mảnh nóng nhanh hơn; cuộn xoắn tập trung nhiệt tại vùng nhỏ, đạt nhiệt độ cao để sáng.'],
['mach', 'Người ta mạ vàng, mạ bạc lên đồ trang sức nhờ',
 ['tác dụng hoá học của dòng điện', 'tác dụng nhiệt', 'tác dụng từ', 'tác dụng sinh lí'],
 'Vật cần mạ nối cực âm, nhúng trong dung dịch muối của kim loại mạ; dòng điện làm kim loại bám lên vật.'],
['mach', 'Hai pin 1,5 V được mắc nối tiếp (cực âm pin này nối cực dương pin kia) làm nguồn. Trên sơ đồ, nguồn này được vẽ',
 ['hai kí hiệu pin liền nhau, vạch dài nối vạch ngắn', 'một kí hiệu pin', 'hai kí hiệu pin cách xa nhau bằng bóng đèn', 'hai vạch dài đối nhau'],
 'Bộ nguồn nối tiếp vẽ bằng các kí hiệu pin ghép liên tiếp, cho hiệu điện thế 3 V.'],
['mach', 'Rơle nhiệt trong bàn là tự ngắt điện khi quá nóng nhờ',
 ['băng kép nóng lên bị cong, tách khỏi tiếp điểm', 'cầu chì đứt', 'nam châm hút', 'nước sôi'],
 'Băng kép gồm hai kim loại nở khác nhau; nóng lên thì cong, ngắt tiếp điểm.'],
['mach', 'Khi vẽ sơ đồ mạch điện, dây dẫn được biểu diễn bằng',
 ['các đoạn thẳng nối các kí hiệu thiết bị', 'các đường cong lượn sóng', 'mũi tên', 'hình chữ nhật'],
 'Dây dẫn được vẽ bằng đoạn thẳng; các chỗ nối vẽ chấm.'],
['mach', 'Điện giật là do dòng điện qua cơ thể. Hiệu điện thế được xem là an toàn với người trong điều kiện bình thường là dưới',
 ['40 V', '220 V', '110 V', '1000 V'],
 'Với người, hiệu điện thế dưới 40 V thường được coi là an toàn; 220 V ở nhà rất nguy hiểm.'],

/* ───────── CƯỜNG ĐỘ DÒNG ĐIỆN – HIỆU ĐIỆN THẾ ───────── */
['iu', 'Cường độ dòng điện cho biết',
 ['mức độ mạnh yếu của dòng điện', 'chiều của dòng điện', 'thời gian dòng điện chạy', 'nhiệt độ của dây dẫn'],
 'Dòng điện càng mạnh thì cường độ dòng điện càng lớn; đơn vị ampe (A), đo bằng ampe kế.'],
['iu', 'Đơn vị đo hiệu điện thế và dụng cụ đo hiệu điện thế là',
 ['vôn (V) và vôn kế', 'ampe (A) và ampe kế', 'oát (W) và oát kế', 'ôm (Ω) và ôm kế'],
 'Hiệu điện thế kí hiệu U, đơn vị vôn, đo bằng vôn kế mắc song song với hai đầu thiết bị.'],
['iu', 'Chọn cách đổi đơn vị ĐÚNG:',
 ['1 A = 1000 mA', '1 A = 100 mA', '1 mA = 1000 A', '1 kV = 100 V'],
 '1 A = 1000 mA; 1 kV = 1000 V; 1 mV = 0,001 V.'],
['iu', 'Cách mắc ampe kế để đo cường độ dòng điện qua bóng đèn là',
 ['mắc nối tiếp với đèn, chốt (+) nối về phía cực dương của nguồn', 'mắc song song với đèn', 'mắc trực tiếp vào hai cực của nguồn', 'mắc nối tiếp, chốt (+) về phía cực âm'],
 'Ampe kế phải nằm trên đường đi của dòng điện (nối tiếp) và đúng chiều chốt.'],
['iu', 'Cách mắc vôn kế để đo hiệu điện thế giữa hai đầu bóng đèn là',
 ['mắc song song với đèn, chốt (+) về phía cực dương của nguồn', 'mắc nối tiếp với đèn', 'mắc nối tiếp với nguồn', 'mắc song song, chốt (+) về phía cực âm'],
 'Vôn kế mắc vào hai đầu (song song) thiết bị cần đo, đúng chiều chốt.'],
['iu', 'Một nguồn điện chưa được nối vào mạch nào. Nhận xét đúng:',
 ['giữa hai cực nguồn vẫn có hiệu điện thế nhưng chưa có dòng điện', 'không có hiệu điện thế', 'có dòng điện chạy trong nguồn', 'hiệu điện thế bằng 0 và dòng điện bằng 0'],
 'Nguồn luôn có hiệu điện thế giữa hai cực; dòng điện chỉ xuất hiện khi mạch kín.'],
['iu', 'Số 1,5 V ghi trên viên pin cho biết',
 ['hiệu điện thế giữa hai cực của pin khi chưa mắc vào mạch', 'cường độ dòng điện pin tạo ra', 'pin dùng được 1,5 giờ', 'khối lượng pin'],
 'Đó là hiệu điện thế định danh giữa hai cực khi mạch hở.'],
['iu', 'Số 6 V ghi trên bóng đèn cho biết',
 ['hiệu điện thế định mức để đèn sáng bình thường', 'hiệu điện thế nhỏ nhất để đèn sáng', 'cường độ dòng điện qua đèn', 'đèn có 6 dây tóc'],
 'Mắc đèn vào đúng 6 V thì đèn sáng bình thường; cao hơn nhiều có thể cháy dây tóc.'],
['iu', 'Bóng đèn ghi 6 V được mắc vào nguồn 3 V. Đèn sẽ',
 ['sáng yếu hơn bình thường', 'sáng bình thường', 'cháy ngay', 'không sáng vì sai hiệu điện thế'],
 'Hiệu điện thế nhỏ hơn định mức → dòng điện qua đèn nhỏ hơn → đèn sáng yếu.'],
['iu', 'Bóng đèn ghi 6 V được mắc vào nguồn 12 V. Kết quả có thể là',
 ['đèn sáng rất mạnh rồi cháy dây tóc', 'đèn sáng bình thường', 'đèn sáng yếu', 'đèn không sáng'],
 'Hiệu điện thế gấp đôi định mức làm dòng điện quá lớn, dây tóc quá nóng và đứt.'],
['iu', 'Cần đo dòng điện khoảng 0,35 A. Nên chọn ampe kế có giới hạn đo (GHĐ)',
 ['0,5 A', '20 mA', '5 A', '100 mA'],
 'GHĐ phải lớn hơn giá trị cần đo nhưng không quá lớn để đọc chính xác: 0,5 A là phù hợp; 20 mA và 100 mA sẽ hỏng ampe kế.'],
['iu', 'Đo hiệu điện thế của một viên pin 1,5 V, nên dùng vôn kế có GHĐ',
 ['3 V', '1 V', '100 V', '250 V'],
 'GHĐ 3 V lớn hơn 1,5 V vừa đủ, cho kết quả chính xác. GHĐ 1 V quá nhỏ, 100 V và 250 V quá lớn.'],
['iu', 'Đồng hồ đo điện đa năng (vạn năng) có thể',
 ['đo cả cường độ dòng điện và hiệu điện thế khi chọn đúng chức năng', 'chỉ đo cường độ dòng điện', 'chỉ đo hiệu điện thế', 'chỉ đo nhiệt độ'],
 'Đồng hồ vạn năng có núm xoay chọn thang đo: DCV, ACV, DCA, Ω...'],
['iu', 'Mắc ampe kế trực tiếp vào hai cực của nguồn điện (không qua thiết bị) là',
 ['nguy hiểm, có thể làm hỏng ampe kế và nguồn vì dòng điện rất lớn', 'cách đo cường độ dòng điện của nguồn', 'cách đo hiệu điện thế của nguồn', 'an toàn vì ampe kế có điện trở lớn'],
 'Ampe kế có điện trở rất nhỏ, mắc thẳng vào nguồn tương đương chập mạch.'],
['iu', 'Trong mạch nối tiếp gồm nguồn, công tắc và một bóng đèn, ampe kế có thể đặt',
 ['ở bất kì vị trí nào trong mạch, số chỉ như nhau', 'chỉ ở trước bóng đèn', 'chỉ ở sau bóng đèn', 'chỉ ở cạnh nguồn'],
 'Trong mạch nối tiếp cường độ dòng điện tại mọi điểm bằng nhau.'],
['iu', 'Kim của ampe kế quay ngược (về phía trái vạch 0). Nguyên nhân là',
 ['mắc nhầm chốt (+) và chốt (−)', 'dòng điện quá nhỏ', 'ampe kế hết pin', 'mắc ampe kế song song'],
 'Chốt (+) phải nối về phía cực dương của nguồn; mắc ngược kim sẽ quay ngược.'],
['iu', 'Cùng một bóng đèn, khi cường độ dòng điện qua đèn tăng thì',
 ['đèn sáng mạnh hơn', 'đèn sáng yếu hơn', 'độ sáng không đổi', 'đèn tắt'],
 'Dòng điện càng mạnh, dây tóc càng nóng, đèn càng sáng.'],
['iu', 'Với cùng một bóng đèn, khi hiệu điện thế giữa hai đầu đèn tăng thì cường độ dòng điện qua đèn',
 ['tăng', 'giảm', 'không đổi', 'bằng 0'],
 'Hiệu điện thế lớn hơn tạo dòng điện mạnh hơn qua cùng một thiết bị.'],
['iu', 'Hiệu điện thế của mạng điện gia đình ở Việt Nam là',
 ['220 V', '110 V', '12 V', '1,5 V'],
 'Mạng điện sinh hoạt Việt Nam dùng 220 V; đây là hiệu điện thế nguy hiểm với người.'],
['iu', 'Ampe kế có GHĐ 3 A, từ vạch 0 đến vạch 3 A có 15 khoảng chia. Độ chia nhỏ nhất (ĐCNN) của ampe kế là',
 ['0,2 A', '0,5 A', '0,1 A', '5 A'],
 'ĐCNN = 3 : 15 = 0,2 A.'],
['iu', 'Đèn LED nhỏ hoạt động với dòng điện khoảng 20 mA, tức là',
 ['0,02 A', '0,2 A', '2 A', '0,002 A'],
 '20 mA = 20 : 1000 = 0,02 A.'],
['iu', 'Trên mặt dụng cụ đo có ghi chữ A hoặc mA, đó là',
 ['ampe kế hoặc miliampe kế, dùng đo cường độ dòng điện', 'vôn kế', 'oát kế', 'nhiệt kế'],
 'Chữ A: ampe kế; mA: miliampe kế đo dòng nhỏ; chữ V: vôn kế.'],
['iu', 'Khi công tắc trong mạch mở, ampe kế mắc nối tiếp với đèn chỉ',
 ['0 A', 'giá trị lớn nhất', 'giá trị bằng số ghi trên đèn', 'giá trị âm'],
 'Mạch hở → không có dòng điện → I = 0.'],
['iu', 'Mạch gồm pin, công tắc đang mở và bóng đèn. Vôn kế V<sub>1</sub> mắc vào hai đầu đèn, vôn kế V<sub>2</sub> mắc vào hai cực pin. Số chỉ:',
 ['V<sub>1</sub> = 0, V<sub>2</sub> khác 0', 'V<sub>1</sub> khác 0, V<sub>2</sub> = 0', 'cả hai đều bằng 0', 'cả hai đều khác 0 và bằng nhau'],
 'Mạch hở: không có dòng qua đèn nên U giữa hai đầu đèn = 0; nhưng hai cực pin vẫn có hiệu điện thế.'],
['iu', 'Trong mạch nối tiếp, cường độ dòng điện ở đầu ra của đèn so với đầu vào',
 ['bằng nhau, dòng điện không bị "hao" khi qua đèn', 'nhỏ hơn vì đèn tiêu thụ', 'lớn hơn', 'bằng 0'],
 'Điện tích không mất đi khi đi qua đèn; đèn tiêu thụ năng lượng, không tiêu thụ dòng điện.'],
['iu', '0,25 A bằng',
 ['250 mA', '25 mA', '2500 mA', '0,25 mA'],
 '0,25 × 1000 = 250 mA.'],
['iu', 'Hai pin 1,5 V mắc nối tiếp (cực âm pin này nối cực dương pin kia) tạo thành nguồn có hiệu điện thế',
 ['3 V', '1,5 V', '0,75 V', '2,25 V'],
 'Nối tiếp: U = 1,5 + 1,5 = 3 V.'],
['iu', 'Số chỉ của vôn kế mắc vào hai cực của pin khi mạch kín (đèn sáng) so với khi mạch hở thường',
 ['nhỏ hơn hoặc gần bằng', 'lớn hơn', 'bằng 0', 'gấp đôi'],
 'Khi có dòng điện, một phần hiệu điện thế "rơi" bên trong pin nên số chỉ hơi giảm.'],
['iu', 'Dùng ampe kế có GHĐ nhỏ hơn cường độ dòng điện cần đo thì',
 ['ampe kế có thể bị hỏng', 'kết quả chính xác hơn', 'kim chỉ đúng vạch cuối', 'không sao'],
 'Dòng điện vượt GHĐ làm kim đập mạnh vào vạch cuối, cuộn dây có thể cháy.'],
['iu', 'Hiệu điện thế 220 V nguy hiểm với người, hiệu điện thế 1,5 V của pin không gây hại. Kết luận chung:',
 ['hiệu điện thế càng lớn thì dòng điện qua cơ thể càng lớn, càng nguy hiểm', 'pin không có hiệu điện thế', 'mọi hiệu điện thế đều an toàn', 'chỉ điện xoay chiều nguy hiểm'],
 'Với cùng cơ thể người, hiệu điện thế lớn tạo dòng điện lớn qua người.'],

/* ───────── MẠCH NỐI TIẾP – SONG SONG ───────── */
['ntss', 'Trong mạch điện gồm hai bóng đèn mắc nối tiếp, cường độ dòng điện',
 ['tại mọi điểm đều bằng nhau: I = I<sub>1</sub> = I<sub>2</sub>', 'qua đèn gần nguồn lớn hơn', 'bằng tổng cường độ qua hai đèn', 'qua đèn sau bằng 0'],
 'Mạch nối tiếp chỉ có một đường đi cho dòng điện nên I ở mọi điểm bằng nhau.'],
['ntss', 'Trong mạch hai đèn mắc nối tiếp, hiệu điện thế giữa hai đầu đoạn mạch',
 ['bằng tổng hiệu điện thế hai đèn: U = U<sub>1</sub> + U<sub>2</sub>', 'bằng hiệu điện thế mỗi đèn', 'bằng hiệu U<sub>1</sub> − U<sub>2</sub>', 'bằng 0'],
 'Nối tiếp: U = U<sub>1</sub> + U<sub>2</sub>.'],
['ntss', 'Trong mạch hai đèn mắc song song, hiệu điện thế',
 ['giữa hai đầu mỗi đèn bằng nhau và bằng hiệu điện thế mạch: U<sub>1</sub> = U<sub>2</sub> = U', 'chia đều mỗi đèn nửa U', 'đèn gần nguồn lớn hơn', 'bằng tổng U<sub>1</sub> + U<sub>2</sub>'],
 'Hai đèn song song có chung hai điểm nối nên chung hiệu điện thế.'],
['ntss', 'Trong mạch hai đèn mắc song song, cường độ dòng điện mạch chính',
 ['bằng tổng cường độ các mạch rẽ: I = I<sub>1</sub> + I<sub>2</sub>', 'bằng cường độ mỗi nhánh', 'bằng hiệu I<sub>1</sub> − I<sub>2</sub>', 'nhỏ hơn mỗi nhánh'],
 'Dòng điện mạch chính tách thành hai nhánh rồi hợp lại: I = I<sub>1</sub> + I<sub>2</sub>.'],
['ntss', 'Hai đèn mắc nối tiếp, một đèn bị cháy dây tóc. Đèn còn lại',
 ['tắt vì mạch hở', 'vẫn sáng như cũ', 'sáng hơn', 'sáng yếu hơn'],
 'Dây tóc đứt làm mạch nối tiếp bị hở, không còn dòng điện.'],
['ntss', 'Hai đèn mắc song song, một đèn bị cháy. Đèn còn lại',
 ['vẫn sáng bình thường', 'tắt', 'sáng yếu hơn nhiều', 'cháy theo'],
 'Nhánh còn lại vẫn kín và vẫn nhận hiệu điện thế của nguồn.'],
['ntss', 'Các thiết bị điện trong gia đình được mắc song song để',
 ['dùng độc lập với nhau và đều nhận đúng hiệu điện thế 220 V', 'tiết kiệm dây', 'tăng cường độ dòng điện qua mỗi thiết bị', 'giảm hiệu điện thế'],
 'Song song: tắt/bật một thiết bị không ảnh hưởng cái khác, mọi thiết bị đều có U = 220 V.'],
['ntss', 'Dây đèn trang trí kiểu cũ có hàng chục bóng nhỏ, hỏng một bóng thì cả dây tắt. Các bóng được mắc',
 ['nối tiếp', 'song song', 'hỗn hợp', 'không theo quy tắc'],
 'Nối tiếp: hở một chỗ là cả mạch mất dòng điện. Vì thế mỗi bóng chỉ chịu một phần nhỏ của 220 V.'],
['ntss', 'Hai đèn nối tiếp với nguồn 6 V. Hiệu điện thế hai đầu đèn 1 là 2,5 V. Hiệu điện thế hai đầu đèn 2 là',
 ['3,5 V', '2,5 V', '6 V', '8,5 V'],
 'U<sub>2</sub> = U − U<sub>1</sub> = 6 − 2,5 = 3,5 V.'],
['ntss', 'Hai đèn song song, cường độ dòng điện qua đèn 1 là 0,3 A, qua đèn 2 là 0,2 A. Cường độ dòng điện mạch chính là',
 ['0,5 A', '0,1 A', '0,3 A', '0,25 A'],
 'I = I<sub>1</sub> + I<sub>2</sub> = 0,3 + 0,2 = 0,5 A.'],
['ntss', 'Hai đèn giống nhau mắc nối tiếp vào nguồn 12 V. Hiệu điện thế hai đầu mỗi đèn là',
 ['6 V', '12 V', '24 V', '3 V'],
 'Hai đèn giống nhau chia đều hiệu điện thế: 12 : 2 = 6 V.'],
['ntss', 'Hai đèn mắc song song vào nguồn 6 V. Hiệu điện thế hai đầu mỗi đèn là',
 ['6 V', '3 V', '12 V', '0 V'],
 'Song song: mỗi đèn nhận đủ hiệu điện thế của nguồn, 6 V.'],
['ntss', 'Mạch hai đèn song song. Ampe kế mạch chính chỉ 0,7 A; ampe kế ở nhánh đèn 1 chỉ 0,4 A. Cường độ dòng điện qua đèn 2 là',
 ['0,3 A', '1,1 A', '0,7 A', '0,4 A'],
 'I<sub>2</sub> = I − I<sub>1</sub> = 0,7 − 0,4 = 0,3 A.'],
['ntss', 'Ba đèn mắc nối tiếp vào nguồn 9 V, U<sub>1</sub> = 2 V, U<sub>2</sub> = 3 V. Hiệu điện thế hai đầu đèn 3 là',
 ['4 V', '5 V', '9 V', '14 V'],
 'U<sub>3</sub> = 9 − 2 − 3 = 4 V.'],
['ntss', 'Dấu hiệu nhận biết hai đèn mắc song song trên sơ đồ là',
 ['hai đèn có chung hai điểm nối (điểm vào và điểm ra)', 'hai đèn nằm trên một đường dây', 'hai đèn vẽ cạnh nhau', 'có hai công tắc'],
 'Song song: hai đầu mỗi đèn đều được nối vào cùng hai điểm chung của mạch.'],
['ntss', 'Điểm khác nhau cơ bản của mạch nối tiếp và song song là',
 ['mạch nối tiếp chỉ có một đường đi cho dòng điện, mạch song song có nhiều nhánh', 'mạch nối tiếp không cần nguồn', 'mạch song song không có công tắc', 'mạch nối tiếp có nhiều đèn hơn'],
 'Nối tiếp: một đường duy nhất; song song: dòng điện tách ra các nhánh rồi hợp lại.'],
['ntss', 'Trong mạch hai đèn song song, tháo bớt một đèn thì',
 ['cường độ dòng điện mạch chính giảm, hiệu điện thế đèn còn lại không đổi', 'đèn còn lại tắt', 'hiệu điện thế đèn còn lại tăng gấp đôi', 'cường độ dòng điện mạch chính tăng'],
 'Mất một nhánh nên I mạch chính giảm; đèn còn lại vẫn nhận U của nguồn.'],
['ntss', 'Trong mạch hai đèn nối tiếp, tháo một đèn ra khỏi đế thì',
 ['mạch hở, đèn còn lại tắt', 'đèn còn lại sáng hơn', 'đèn còn lại sáng như cũ', 'đèn còn lại sáng yếu hơn'],
 'Tháo đèn làm mạch nối tiếp bị hở tại vị trí đó.'],
['ntss', 'Trong mạch hai đèn song song, ampe kế đặt ở mạch chính đo',
 ['tổng cường độ dòng điện qua cả hai đèn', 'cường độ dòng điện qua đèn 1', 'cường độ dòng điện qua đèn 2', 'hiệu điện thế của nguồn'],
 'Mạch chính là nơi dòng điện chưa tách hoặc đã hợp lại: I = I<sub>1</sub> + I<sub>2</sub>.'],
['ntss', 'Trong mạch hai đèn nối tiếp, vôn kế mắc song song với đèn 1 đo',
 ['hiệu điện thế giữa hai đầu đèn 1', 'hiệu điện thế của nguồn', 'hiệu điện thế hai đầu đèn 2', 'cường độ dòng điện qua đèn 1'],
 'Vôn kế đo hiệu điện thế giữa hai điểm nó được mắc vào, ở đây là hai đầu đèn 1.'],
['ntss', 'Mạch hai đèn nối tiếp. Vôn kế mắc vào hai cực nguồn chỉ 9 V, vôn kế mắc vào hai đầu đèn 2 chỉ 4 V. Hiệu điện thế hai đầu đèn 1 là',
 ['5 V', '13 V', '4 V', '9 V'],
 'U<sub>1</sub> = U − U<sub>2</sub> = 9 − 4 = 5 V.'],
['ntss', 'Hai đèn giống nhau và một nguồn 3 V. Cách mắc nào làm hai đèn sáng hơn?',
 ['Mắc song song, vì mỗi đèn nhận 3 V', 'Mắc nối tiếp, vì mỗi đèn nhận 3 V', 'Mắc nối tiếp, vì dòng điện qua cả hai', 'Hai cách sáng như nhau'],
 'Nối tiếp mỗi đèn chỉ nhận 1,5 V; song song mỗi đèn nhận 3 V nên sáng hơn.'],
['ntss', 'Hai đèn khác nhau mắc nối tiếp, đèn 1 sáng hơn đèn 2. Nhận xét đúng:',
 ['cường độ dòng điện qua hai đèn bằng nhau, hiệu điện thế đèn 1 lớn hơn', 'cường độ dòng điện qua đèn 1 lớn hơn', 'hiệu điện thế hai đèn bằng nhau', 'đèn 2 không có dòng điện'],
 'Nối tiếp thì I bằng nhau; đèn sáng hơn là đèn có hiệu điện thế hai đầu lớn hơn.'],
['ntss', 'Hai đèn song song, cường độ dòng điện qua đèn 1 gấp đôi đèn 2, mạch chính 0,6 A. Cường độ dòng điện qua đèn 1 là',
 ['0,4 A', '0,2 A', '0,3 A', '1,2 A'],
 'I<sub>1</sub> + I<sub>2</sub> = 3I<sub>2</sub> = 0,6 → I<sub>2</sub> = 0,2 A, I<sub>1</sub> = 0,4 A.'],
['ntss', 'Hai đèn nối tiếp vào nguồn 9 V, hiệu điện thế đèn 1 gấp đôi đèn 2. Hiệu điện thế hai đầu đèn 1 là',
 ['6 V', '3 V', '4,5 V', '9 V'],
 'U<sub>1</sub> + U<sub>2</sub> = 3U<sub>2</sub> = 9 → U<sub>2</sub> = 3 V, U<sub>1</sub> = 6 V.'],
['ntss', 'Mạch hai đèn song song có công tắc K ở mạch chính và công tắc K<sub>1</sub> ở nhánh đèn 1. Đóng K, mở K<sub>1</sub> thì',
 ['chỉ đèn 2 sáng', 'cả hai đèn sáng', 'chỉ đèn 1 sáng', 'cả hai đèn tắt'],
 'K<sub>1</sub> mở làm nhánh đèn 1 hở; nhánh đèn 2 vẫn kín qua K.'],
['ntss', 'Mắc thêm một bóng đèn nối tiếp vào mạch đang có hai đèn nối tiếp (nguồn không đổi). Các đèn sẽ',
 ['sáng yếu hơn vì hiệu điện thế mỗi đèn giảm', 'sáng hơn', 'sáng như cũ', 'tắt hết'],
 'U nguồn chia cho ba đèn thay vì hai, mỗi đèn nhận ít hơn nên dòng điện nhỏ hơn.'],
['ntss', 'Hai pin 1,5 V mắc song song (cực dương nối cực dương, âm nối âm) cho hiệu điện thế',
 ['1,5 V, nhưng dùng được lâu hơn một pin', '3 V', '0,75 V', '0 V'],
 'Song song không cộng hiệu điện thế; hai pin cùng chia sẻ dòng điện nên bền hơn.'],
['ntss', 'Mạch hai đèn nối tiếp, ampe kế đặt giữa hai đèn chỉ 0,25 A. Cường độ dòng điện qua đèn 1 và đèn 2 lần lượt là',
 ['0,25 A và 0,25 A', '0,5 A và 0,25 A', '0,125 A và 0,125 A', '0,25 A và 0'],
 'Nối tiếp: I bằng nhau tại mọi điểm.'],
];
