// Ngân hàng câu VIẾT TAY — phần NHIỆT (Vật lí 8 · KHTN 8, KNTT)
// Chương: nhiet (năng lượng nhiệt – nội năng – nhiệt lượng Q = m·c·Δt) · truyen (dẫn nhiệt – đối lưu – bức xạ)
//         no (sự nở vì nhiệt và ứng dụng)
export const NHIET = [
/* ───────── NĂNG LƯỢNG NHIỆT – NỘI NĂNG – NHIỆT LƯỢNG ───────── */
['nhiet', 'Năng lượng nhiệt của một vật là',
 ['năng lượng vật có được do chuyển động hỗn loạn (chuyển động nhiệt) của các phân tử cấu tạo nên vật', 'năng lượng do vật ở trên cao', 'năng lượng do vật chuyển động', 'nhiệt độ của vật'],
 'Các phân tử luôn chuyển động hỗn loạn không ngừng; tổng động năng của chúng là năng lượng nhiệt của vật.'],
['nhiet', 'Khi nhiệt độ của vật tăng thì',
 ['các phân tử chuyển động nhanh hơn, năng lượng nhiệt của vật tăng', 'các phân tử chuyển động chậm hơn', 'năng lượng nhiệt của vật giảm', 'các phân tử ngừng chuyển động'],
 'Nhiệt độ càng cao, chuyển động nhiệt càng nhanh, năng lượng nhiệt càng lớn.'],
['nhiet', 'Có mấy cách làm thay đổi nội năng (năng lượng nhiệt) của một vật?',
 ['Hai cách: thực hiện công và truyền nhiệt', 'Một cách: đun nóng', 'Ba cách: đun, làm lạnh, cọ xát', 'Không thể thay đổi'],
 'Nội năng thay đổi bằng thực hiện công (cọ xát, nén) hoặc truyền nhiệt (tiếp xúc vật nóng/lạnh).'],
['nhiet', 'Cọ xát miếng đồng lên mặt bàn, miếng đồng nóng lên. Nội năng của miếng đồng tăng do',
 ['thực hiện công', 'truyền nhiệt', 'bức xạ nhiệt', 'đối lưu'],
 'Lực ma sát thực hiện công làm phân tử đồng chuyển động nhanh hơn.'],
['nhiet', 'Thả miếng đồng vào cốc nước nóng, miếng đồng nóng lên. Nội năng của miếng đồng tăng do',
 ['truyền nhiệt', 'thực hiện công', 'ma sát', 'đối lưu trong đồng'],
 'Nước nóng truyền năng lượng nhiệt cho miếng đồng lạnh hơn.'],
['nhiet', 'Nhiệt lượng là',
 ['phần năng lượng nhiệt mà vật nhận thêm hoặc mất đi trong quá trình truyền nhiệt', 'toàn bộ năng lượng của vật', 'nhiệt độ của vật', 'khối lượng của vật nóng'],
 'Nhiệt lượng kí hiệu Q, đơn vị jun (J), là phần năng lượng trao đổi khi truyền nhiệt.'],
['nhiet', 'Nhiệt lượng vật thu vào để nóng lên được tính bằng',
 ['Q = m·c·Δt', 'Q = m·c/Δt', 'Q = m·Δt', 'Q = c·Δt/m'],
 'Q phụ thuộc khối lượng m, nhiệt dung riêng c của chất và độ tăng nhiệt độ Δt.'],
['nhiet', 'Nói nhiệt dung riêng của nước là 4200 J/(kg·K) có nghĩa là',
 ['để 1 kg nước tăng thêm 1 °C cần cung cấp 4200 J', 'để 1 kg nước sôi cần 4200 J', '1 kg nước chứa 4200 J', 'nước có nhiệt độ 4200 K'],
 'c là nhiệt lượng cần để 1 kg chất tăng 1 °C (1 K).'],
['nhiet', 'Dụng cụ dùng để đo trực tiếp năng lượng nhiệt (nhiệt lượng) do dây đốt cung cấp cho nước trong thí nghiệm là',
 ['joulemeter (jun kế)', 'nhiệt kế', 'ampe kế', 'cân'],
 'Joulemeter đo năng lượng điện chuyển thành nhiệt trên dây đốt, hiển thị bằng jun.'],
['nhiet', 'Nhiệt lượng cần cung cấp để 2 kg nước tăng từ 20 °C lên 100 °C (c = 4200 J/(kg·K)) là',
 ['672 000 J', '840 000 J', '168 000 J', '67 200 J'],
 'Q = 2 × 4200 × 80 = 672 000 J.'],
['nhiet', 'Hai vật có cùng khối lượng, nhận cùng một nhiệt lượng. Vật có nhiệt dung riêng nhỏ hơn sẽ',
 ['tăng nhiệt độ nhiều hơn', 'tăng nhiệt độ ít hơn', 'không thay đổi nhiệt độ', 'tăng nhiệt độ như vật kia'],
 'Δt = Q/(m·c): c nhỏ → Δt lớn.'],
['nhiet', 'Nước được dùng làm chất làm mát động cơ, chất tải nhiệt trong lò sưởi vì',
 ['nước có nhiệt dung riêng lớn, thu hoặc toả được nhiều nhiệt', 'nước rẻ và dễ bay hơi', 'nước dẫn nhiệt rất tốt', 'nước có nhiệt dung riêng nhỏ'],
 'c nước = 4200 J/(kg·K) rất lớn nên với cùng Δt nước thu/toả nhiều nhiệt hơn các chất khác.'],
['nhiet', 'Nhiệt lượng một vật toả ra khi nguội từ t<sub>1</sub> xuống t<sub>2</sub> là',
 ['Q = m·c·(t<sub>1</sub> − t<sub>2</sub>)', 'Q = m·c·(t<sub>2</sub> − t<sub>1</sub>)', 'Q = m·c·t<sub>1</sub>', 'Q = m·(t<sub>1</sub> − t<sub>2</sub>)'],
 'Độ giảm nhiệt độ Δt = t<sub>1</sub> − t<sub>2</sub> > 0.'],
['nhiet', 'Đường tan trong nước nóng nhanh hơn trong nước lạnh vì',
 ['ở nhiệt độ cao các phân tử chuyển động nhanh hơn, khuếch tán nhanh hơn', 'nước nóng nhẹ hơn', 'đường tan chảy do nóng', 'nước nóng có nhiều nước hơn'],
 'Chuyển động nhiệt nhanh hơn làm phân tử đường và nước xen vào nhau nhanh hơn.'],
['nhiet', 'Cho hai vật có nhiệt độ khác nhau tiếp xúc, sự truyền nhiệt dừng lại khi',
 ['nhiệt độ hai vật bằng nhau', 'vật nóng nguội hết', 'vật lạnh nóng bằng vật nóng ban đầu', 'khối lượng hai vật bằng nhau'],
 'Nhiệt truyền từ vật nóng sang vật lạnh cho đến khi cân bằng nhiệt.'],
['nhiet', 'Khi hai vật trao đổi nhiệt với nhau (bỏ qua hao phí ra môi trường), nhiệt lượng vật nóng toả ra',
 ['bằng nhiệt lượng vật lạnh thu vào', 'lớn hơn nhiệt lượng vật lạnh thu vào', 'nhỏ hơn nhiệt lượng vật lạnh thu vào', 'bằng 0'],
 'Phương trình cân bằng nhiệt: Q<sub>toả</sub> = Q<sub>thu</sub>.'],
['nhiet', 'Phát biểu nào ĐÚNG?',
 ['Nhiệt độ cho biết mức độ nóng lạnh, còn nhiệt lượng là phần năng lượng nhiệt được trao đổi', 'Nhiệt độ và nhiệt lượng là một', 'Vật có nhiệt độ cao thì luôn có nhiều nhiệt lượng', 'Nhiệt lượng có đơn vị là °C'],
 'Nhiệt độ (°C) khác nhiệt lượng (J). Một cốc nước sôi có nhiệt độ cao hơn nhưng năng lượng nhiệt ít hơn một hồ nước ấm.'],
['nhiet', 'Hai cốc nước ở cùng nhiệt độ 50 °C, một cốc chứa 200 g, một cốc chứa 400 g. Năng lượng nhiệt của cốc nào lớn hơn?',
 ['Cốc 400 g, vì có nhiều phân tử hơn', 'Cốc 200 g', 'Bằng nhau vì cùng nhiệt độ', 'Không so sánh được'],
 'Cùng nhiệt độ (cùng động năng trung bình mỗi phân tử) nhưng nhiều phân tử hơn thì tổng năng lượng nhiệt lớn hơn.'],
['nhiet', 'Xoa hai bàn tay vào nhau thấy ấm lên. Đây là cách làm tăng nội năng bằng',
 ['thực hiện công', 'truyền nhiệt', 'bức xạ', 'đối lưu'],
 'Ma sát giữa hai tay thực hiện công làm nội năng tăng, không có vật nóng nào truyền nhiệt.'],
['nhiet', 'Bơm xe đạp một lúc thì thân bơm nóng lên vì',
 ['pit-tông nén không khí và ma sát với thân bơm, thực hiện công làm nội năng tăng', 'không khí bên ngoài truyền nhiệt vào', 'bơm hấp thụ ánh sáng', 'xe đạp nóng truyền sang bơm'],
 'Thực hiện công lên khí và ma sát chuyển hoá thành năng lượng nhiệt.'],
['nhiet', 'Nồi nấu bằng kim loại nóng lên nhanh hơn nước trong nồi vì',
 ['kim loại có nhiệt dung riêng nhỏ hơn nước nhiều lần', 'kim loại nặng hơn nước', 'kim loại có nhiệt dung riêng lớn hơn', 'nước cách nhiệt'],
 'Ví dụ c nhôm = 880, c đồng = 380 J/(kg·K), nhỏ hơn nhiều so với c nước = 4200.'],
['nhiet', 'Nhiệt lượng để đun 1,5 lít nước từ 25 °C đến sôi (100 °C) là (c = 4200 J/(kg·K))',
 ['472 500 J', '630 000 J', '157 500 J', '47 250 J'],
 'm = 1,5 kg; Q = 1,5 × 4200 × 75 = 472 500 J.'],
['nhiet', 'Trộn 1 kg nước ở 20 °C với 1 kg nước ở 60 °C (bỏ qua hao phí). Nhiệt độ khi cân bằng là',
 ['40 °C', '80 °C', '30 °C', '50 °C'],
 'Cùng khối lượng, cùng chất → nhiệt độ cân bằng là trung bình: (20 + 60) : 2 = 40 °C.'],
['nhiet', 'Trộn 2 kg nước ở 10 °C với 1 kg nước ở 70 °C (bỏ qua hao phí). Nhiệt độ khi cân bằng là',
 ['30 °C', '40 °C', '35 °C', '50 °C'],
 '2(t − 10) = 1(70 − t) → 3t = 90 → t = 30 °C.'],
['nhiet', 'Miếng nhôm 0,5 kg ở 100 °C thả vào nước, khi cân bằng nhôm còn 30 °C. Nhiệt lượng nhôm toả ra là (c<sub>nhôm</sub> = 880 J/(kg·K))',
 ['30 800 J', '44 000 J', '13 200 J', '3080 J'],
 'Q = 0,5 × 880 × (100 − 30) = 30 800 J.'],
['nhiet', 'Vật ở 0 °C',
 ['vẫn có năng lượng nhiệt vì các phân tử vẫn chuyển động', 'không có năng lượng nhiệt', 'có năng lượng nhiệt âm', 'các phân tử ngừng chuyển động'],
 '0 °C chỉ là mốc nhiệt độ nước đóng băng; phân tử vẫn chuyển động nhiệt.'],
['nhiet', 'Đổi đơn vị: 1 kJ và 1 cal lần lượt bằng',
 ['1000 J và khoảng 4,2 J', '100 J và 42 J', '1000 J và 420 J', '10 J và 4,2 J'],
 '1 kJ = 1000 J; 1 calo ≈ 4,2 J (nhiệt lượng làm 1 g nước tăng 1 °C).'],
['nhiet', 'Hai vật A và B cùng khối lượng, c<sub>A</sub> = 2c<sub>B</sub>. Cung cấp cùng nhiệt lượng, độ tăng nhiệt độ của A so với B',
 ['bằng một nửa', 'gấp đôi', 'bằng nhau', 'gấp bốn'],
 'Δt = Q/(m·c) tỉ lệ nghịch với c → Δt<sub>A</sub> = Δt<sub>B</sub>/2.'],
['nhiet', 'Nhỏ một giọt mực vào cốc nước nóng và một giọt vào cốc nước lạnh. Mực loang nhanh hơn trong',
 ['nước nóng, vì phân tử chuyển động nhanh hơn', 'nước lạnh', 'hai cốc như nhau', 'không loang ở cốc nào'],
 'Hiện tượng khuếch tán xảy ra nhanh hơn khi nhiệt độ cao hơn.'],
['nhiet', 'Nhiệt lượng 84 000 J làm 2 kg nước tăng thêm bao nhiêu độ?',
 ['10 °C', '20 °C', '40 °C', '5 °C'],
 'Δt = Q/(m·c) = 84 000 : (2 × 4200) = 10 °C.'],
['nhiet', 'Trong quá trình truyền nhiệt giữa hai vật, năng lượng',
 ['được bảo toàn: vật này mất bao nhiêu thì vật kia nhận bấy nhiêu (bỏ qua hao phí)', 'tự sinh ra ở vật lạnh', 'mất đi ở vật nóng mà không đi đâu', 'chỉ truyền từ vật lạnh sang vật nóng'],
 'Định luật bảo toàn năng lượng áp dụng cho truyền nhiệt.'],

/* ───────── DẪN NHIỆT – ĐỐI LƯU – BỨC XẠ NHIỆT ───────── */
['truyen', 'Dẫn nhiệt là',
 ['sự truyền năng lượng nhiệt từ phần này sang phần khác của vật hoặc từ vật này sang vật khác khi tiếp xúc', 'sự truyền nhiệt bằng các dòng chất lỏng', 'sự truyền nhiệt bằng tia nhiệt', 'sự nở ra của vật khi nóng'],
 'Dẫn nhiệt là hình thức truyền nhiệt chủ yếu của chất rắn.'],
['truyen', 'Đối lưu là hình thức truyền nhiệt',
 ['bằng các dòng chất lỏng hoặc chất khí, là hình thức chủ yếu ở chất lỏng và khí', 'bằng tia nhiệt', 'trong chất rắn', 'chỉ xảy ra trong chân không'],
 'Phần chất lỏng/khí nóng nở ra, nhẹ hơn nên đi lên; phần lạnh chìm xuống, tạo dòng đối lưu.'],
['truyen', 'Bức xạ nhiệt là hình thức truyền nhiệt',
 ['bằng các tia nhiệt đi thẳng, có thể xảy ra cả trong chân không', 'cần có vật trung gian tiếp xúc', 'bằng dòng chất khí', 'chỉ xảy ra trong chất rắn'],
 'Tia nhiệt truyền không cần môi trường vật chất, ví dụ từ Mặt Trời tới Trái Đất.'],
['truyen', 'Năng lượng từ Mặt Trời truyền đến Trái Đất bằng hình thức',
 ['bức xạ nhiệt', 'dẫn nhiệt', 'đối lưu', 'cả dẫn nhiệt và đối lưu'],
 'Giữa Mặt Trời và Trái Đất là khoảng chân không, chỉ bức xạ mới truyền được.'],
['truyen', 'Nhóm chất nào dẫn nhiệt tốt?',
 ['Đồng, nhôm, bạc', 'Gỗ, bông, không khí', 'Nhựa, len, thuỷ tinh', 'Nước, không khí, cao su'],
 'Kim loại dẫn nhiệt tốt nhất; gỗ, bông, không khí dẫn nhiệt kém (chất cách nhiệt).'],
['truyen', 'Gắn các đinh bằng sáp dọc theo thanh đồng, đun nóng một đầu thanh, các đinh rơi lần lượt từ gần nguồn nhiệt ra xa. Thí nghiệm chứng tỏ',
 ['nhiệt được dẫn dần từ đầu nóng sang đầu lạnh của thanh đồng', 'sáp tự chảy', 'đồng nở ra', 'thanh đồng bức xạ nhiệt'],
 'Đây là thí nghiệm minh hoạ sự dẫn nhiệt trong chất rắn.'],
['truyen', 'Khi đun nước, ta đun từ phía dưới đáy ấm vì',
 ['nước nóng ở dưới nở ra, nhẹ hơn đi lên, nước lạnh đi xuống tạo dòng đối lưu làm nước nóng đều', 'đáy ấm dày hơn', 'nước dẫn nhiệt tốt', 'để nước bức xạ nhiệt'],
 'Đun từ trên xuống thì lớp nước nóng ở trên không đi xuống, nước dưới lâu nóng.'],
['truyen', 'Nồi, chảo làm bằng kim loại nhưng cán làm bằng gỗ hoặc nhựa vì',
 ['kim loại dẫn nhiệt tốt để nấu nhanh, gỗ/nhựa dẫn nhiệt kém để cầm không nóng', 'gỗ nhẹ hơn kim loại', 'kim loại đắt hơn', 'gỗ dẫn nhiệt tốt hơn'],
 'Kết hợp vật liệu dẫn nhiệt tốt (thân) và cách nhiệt (cán).'],
['truyen', 'Mặc áo bông giữ ấm cơ thể vì',
 ['không khí giữa các sợi bông dẫn nhiệt kém, ngăn nhiệt từ cơ thể truyền ra ngoài', 'bông toả nhiệt', 'bông truyền nhiệt vào cơ thể', 'bông hấp thụ ánh sáng'],
 'Áo bông không sinh nhiệt; nó cách nhiệt để cơ thể ít mất nhiệt.'],
['truyen', 'Mùa đông chim thường xù lông để',
 ['tạo lớp không khí dày giữa các lông, cách nhiệt tốt hơn', 'bay nhanh hơn', 'hấp thụ ánh sáng', 'toả nhiệt nhanh hơn'],
 'Lớp không khí bị giữ lại dẫn nhiệt kém giúp chim giữ ấm.'],
['truyen', 'Cửa kính hai lớp có lớp không khí (hoặc chân không) ở giữa nhằm',
 ['cách nhiệt, hạn chế dẫn nhiệt qua cửa', 'cho ánh sáng đi qua nhiều hơn', 'làm cửa nặng hơn', 'chống trầy xước'],
 'Không khí dẫn nhiệt kém hơn kính rất nhiều; chân không thì không dẫn nhiệt và không đối lưu.'],
['truyen', 'Sờ tay vào thanh kim loại và miếng gỗ cùng ở nhiệt độ phòng, ta thấy kim loại lạnh hơn vì',
 ['kim loại dẫn nhiệt tốt, lấy nhiệt từ tay nhanh hơn', 'kim loại có nhiệt độ thấp hơn', 'gỗ nóng hơn', 'kim loại nặng hơn'],
 'Hai vật cùng nhiệt độ; cảm giác lạnh do tay mất nhiệt nhanh vào kim loại.'],
['truyen', 'Vật có bề mặt màu đen, sần so với vật màu trắng, bóng thì',
 ['hấp thụ bức xạ nhiệt tốt hơn và cũng toả bức xạ nhiệt tốt hơn', 'hấp thụ bức xạ nhiệt kém hơn', 'phản xạ tia nhiệt tốt hơn', 'không hấp thụ bức xạ'],
 'Bề mặt tối, sần hấp thụ và phát bức xạ nhiệt mạnh; bề mặt sáng, bóng phản xạ tốt.'],
['truyen', 'Mùa hè nên mặc áo sáng màu vì',
 ['áo sáng màu hấp thụ ít bức xạ nhiệt từ Mặt Trời', 'áo sáng màu mỏng hơn', 'áo sáng màu dẫn nhiệt tốt', 'áo sáng màu toả nhiệt nhiều'],
 'Màu sáng phản xạ phần lớn tia nhiệt, cơ thể ít bị nóng.'],
['truyen', 'Ống hấp thụ của bình nước nóng năng lượng mặt trời được sơn đen để',
 ['hấp thụ bức xạ nhiệt tốt nhất', 'chống gỉ', 'trang trí', 'phản xạ ánh sáng'],
 'Màu đen hấp thụ hầu hết tia nhiệt chiếu tới, làm nước nóng nhanh.'],
['truyen', 'Phích nước có hai lớp thuỷ tinh, giữa là chân không, mặt trong tráng bạc. Lớp chân không có tác dụng',
 ['ngăn dẫn nhiệt và đối lưu', 'ngăn bức xạ nhiệt', 'làm phích nhẹ hơn', 'giữ nước sạch'],
 'Chân không không có vật chất nên không dẫn nhiệt, không đối lưu; lớp bạc phản xạ tia nhiệt ngăn bức xạ.'],
['truyen', 'Máy điều hoà (dàn lạnh) thường lắp trên cao, lò sưởi đặt dưới thấp vì',
 ['không khí lạnh nặng đi xuống, không khí nóng nhẹ đi lên, tạo đối lưu làm mát/ấm cả phòng', 'để tiết kiệm chỗ', 'trên cao ít bụi', 'lò sưởi nặng'],
 'Vị trí lắp đặt tận dụng dòng đối lưu của không khí.'],
['truyen', 'Ống khói nhà máy, bếp lò hoạt động dựa trên',
 ['đối lưu: khí nóng nhẹ bay lên kéo theo khói', 'dẫn nhiệt', 'bức xạ nhiệt', 'áp suất chất lỏng'],
 'Khí nóng trong ống nhẹ hơn không khí ngoài nên bay lên, hút không khí mới vào lò.'],
['truyen', 'Trong chân không, hình thức truyền nhiệt duy nhất có thể xảy ra là',
 ['bức xạ nhiệt', 'dẫn nhiệt', 'đối lưu', 'không có hình thức nào'],
 'Dẫn nhiệt và đối lưu cần vật chất; bức xạ thì không.'],
['truyen', 'Đun nóng phần giữa ống nghiệm chứa nước có cục sáp ở đáy. Nước phía trên sôi mà sáp ở đáy không chảy. Thí nghiệm chứng tỏ',
 ['nước dẫn nhiệt kém', 'sáp không chảy khi nóng', 'nước không truyền nhiệt', 'thuỷ tinh cách nhiệt hoàn toàn'],
 'Nhiệt chỉ truyền lên trên bằng đối lưu; xuống dưới chỉ có dẫn nhiệt rất kém nên sáp không chảy.'],
['truyen', 'Đặt nhiệt kế bên cạnh bếp điện (không chạm), nhiệt kế nóng lên; đặt tấm bìa chắn giữa bếp và nhiệt kế thì nhiệt độ ngừng tăng. Thí nghiệm chứng tỏ',
 ['bếp truyền nhiệt bằng bức xạ, tia nhiệt đi thẳng và bị tấm bìa chắn lại', 'bếp truyền nhiệt bằng dẫn nhiệt qua không khí', 'tấm bìa làm lạnh không khí', 'nhiệt kế hỏng'],
 'Tia nhiệt đi thẳng như ánh sáng, bị vật cản chắn.'],
['truyen', 'Xoong nồi tốt thường có đáy dày, làm bằng đồng hoặc nhôm để',
 ['dẫn nhiệt nhanh và đều khắp đáy, thức ăn không bị cháy cục bộ', 'nồi nặng hơn, khó đổ', 'cách nhiệt tốt', 'chịu áp suất'],
 'Kim loại dẫn nhiệt tốt phân bố nhiệt đều trên toàn đáy.'],
['truyen', 'Ban đêm ở sa mạc rất lạnh dù ban ngày rất nóng vì',
 ['không khí khô, ít mây; cát bức xạ nhiệt ra không gian rất nhanh', 'ban đêm có tuyết', 'cát dẫn nhiệt vào lòng đất', 'gió biển thổi vào'],
 'Không có hơi nước và mây giữ nhiệt, mặt đất mất nhiệt bằng bức xạ rất nhanh.'],
['truyen', 'Nhà kính trồng cây giữ được ấm vì',
 ['ánh sáng Mặt Trời vào được, nhưng bức xạ nhiệt từ đất và cây khó thoát qua kính, đồng thời kính chặn đối lưu với bên ngoài', 'kính dẫn nhiệt tốt', 'kính phát ra nhiệt', 'cây toả nhiệt'],
 'Đây là hiệu ứng nhà kính: nhiệt bị "nhốt" lại bên trong.'],
['truyen', 'Thổi vào bát canh nóng làm canh nguội nhanh hơn vì',
 ['tăng đối lưu không khí và bay hơi ở mặt canh, mang nhiệt đi nhanh hơn', 'hơi thở lạnh', 'canh dẫn nhiệt tốt hơn', 'canh bức xạ nhiều hơn'],
 'Lớp không khí nóng ẩm trên mặt canh bị thổi đi, thay bằng không khí mát.'],
['truyen', 'Ngăn đá của tủ lạnh kiểu cũ thường đặt ở trên cùng vì',
 ['không khí lạnh nặng hơn chìm xuống, làm lạnh các ngăn dưới nhờ đối lưu', 'trên cao ít bụi', 'để dễ lấy đá', 'không khí lạnh bay lên'],
 'Đối lưu: khí lạnh từ ngăn đá đi xuống, khí ấm ở dưới đi lên được làm lạnh.'],
['truyen', 'Bồn chứa xăng dầu thường sơn màu trắng hoặc nhũ bạc để',
 ['phản xạ bức xạ nhiệt, hạn chế xăng nóng lên và bay hơi', 'dễ nhìn', 'chống gỉ', 'hấp thụ nhiệt'],
 'Màu sáng, bóng hấp thụ ít tia nhiệt từ Mặt Trời.'],
['truyen', 'Hình thức truyền nhiệt chủ yếu của chất rắn, chất lỏng và chất khí lần lượt là',
 ['dẫn nhiệt, đối lưu, đối lưu', 'đối lưu, dẫn nhiệt, bức xạ', 'bức xạ, đối lưu, dẫn nhiệt', 'dẫn nhiệt, dẫn nhiệt, bức xạ'],
 'Chất rắn: dẫn nhiệt; chất lỏng và khí: đối lưu (vì các phần tử dễ dịch chuyển).'],
['truyen', 'Tuyết rơi phủ lên mặt đất lại giúp cây trồng bên dưới ít bị chết rét vì',
 ['tuyết xốp chứa nhiều không khí, cách nhiệt, ngăn đất mất nhiệt', 'tuyết toả nhiệt', 'tuyết dẫn nhiệt tốt', 'tuyết hấp thụ ánh sáng'],
 'Lớp tuyết xốp cách nhiệt như chiếc chăn.'],
['truyen', 'Khi cầm cốc nước nóng, ta lót thêm khăn hoặc bìa giấy vì',
 ['giấy, khăn dẫn nhiệt kém nên tay ít bị nóng', 'giấy hấp thụ nhiệt', 'giấy làm nước nguội', 'giấy bức xạ nhiệt'],
 'Vật liệu cách nhiệt làm chậm sự dẫn nhiệt từ cốc ra tay.'],
['truyen', 'Không nên che kín các khe thoát nhiệt của tủ lạnh, máy tính vì',
 ['cản trở đối lưu không khí, thiết bị không tản nhiệt được', 'bụi vào máy', 'máy chạy nhanh hơn', 'máy ồn hơn'],
 'Thiết bị tản nhiệt bằng đối lưu không khí qua các khe.'],
['truyen', 'Cốc thuỷ tinh dày dễ nứt hơn cốc mỏng khi rót nước sôi vào vì',
 ['thuỷ tinh dẫn nhiệt kém, lớp trong nóng nở ra trước trong khi lớp ngoài chưa kịp nở', 'cốc dày nặng hơn', 'cốc dày dẫn nhiệt tốt', 'nước sôi nặng hơn'],
 'Sự nở không đều giữa lớp trong và lớp ngoài tạo lực làm cốc nứt.'],
['truyen', 'Đứng gần đống lửa ta thấy nóng mặt chủ yếu do',
 ['bức xạ nhiệt', 'dẫn nhiệt qua không khí', 'đối lưu', 'không khí nóng bay ngang'],
 'Khí nóng bay lên trên; nhiệt đến mặt ta theo phương ngang chủ yếu bằng tia nhiệt.'],
['truyen', 'Thìa kim loại nhúng trong cốc nước nóng, cán thìa nóng lên. Hình thức truyền nhiệt trong thìa là',
 ['dẫn nhiệt', 'đối lưu', 'bức xạ nhiệt', 'nở vì nhiệt'],
 'Nhiệt truyền dọc theo chất rắn từ phần nhúng nước tới cán.'],
['truyen', 'Nước trong ấm được làm nóng đều là nhờ',
 ['đối lưu', 'dẫn nhiệt trong nước', 'bức xạ nhiệt', 'nước nở ra'],
 'Nước dẫn nhiệt kém; các dòng đối lưu mang nước nóng lên và nước lạnh xuống.'],
['truyen', 'Mặt trong của phích nước được tráng lớp bạc sáng bóng để',
 ['phản xạ tia nhiệt, ngăn truyền nhiệt bằng bức xạ', 'chống dẫn nhiệt', 'ngăn đối lưu', 'giữ nước sạch'],
 'Lớp gương phản xạ bức xạ nhiệt trở lại, nước giữ nóng lâu.'],
['truyen', 'Gạch xây tường thường có các lỗ rỗng để',
 ['chứa không khí giúp cách nhiệt tốt hơn và gạch nhẹ hơn', 'dẫn nhiệt tốt hơn', 'tiết kiệm vữa', 'chống thấm nước'],
 'Không khí trong lỗ dẫn nhiệt kém giúp nhà mát về hè, ấm về đông.'],
['truyen', 'Ban ngày gió thường thổi từ biển vào đất liền vì',
 ['đất nóng nhanh hơn nước, không khí trên đất nóng bay lên, không khí mát từ biển tràn vào thay thế', 'biển nóng hơn đất', 'nước biển bốc hơi', 'gió luôn thổi từ biển'],
 'Đây là dòng đối lưu quy mô lớn của không khí.'],
['truyen', 'Áo phao, chăn bông, mũ len giữ ấm đều dựa trên nguyên tắc',
 ['giữ lớp không khí dẫn nhiệt kém sát cơ thể', 'toả nhiệt cho cơ thể', 'hấp thụ bức xạ Mặt Trời', 'dẫn nhiệt tốt'],
 'Vật liệu xốp giữ không khí; không khí cách nhiệt tốt.'],
['truyen', 'Vì sao mái nhà lợp tôn nóng hơn mái ngói vào buổi trưa?',
 ['Tôn kim loại dẫn nhiệt tốt và mỏng, nhiệt truyền nhanh vào nhà; ngói dày, dẫn nhiệt kém', 'Tôn hấp thụ ít bức xạ', 'Ngói không bị nắng chiếu', 'Tôn nặng hơn ngói'],
 'Kim loại dẫn nhiệt tốt gấp nhiều lần vật liệu đất nung.'],

/* ───────── SỰ NỞ VÌ NHIỆT ───────── */
['no', 'Chất rắn',
 ['nở ra khi nóng lên, co lại khi lạnh đi; các chất rắn khác nhau nở vì nhiệt khác nhau', 'co lại khi nóng lên', 'không thay đổi kích thước theo nhiệt độ', 'nở vì nhiệt giống nhau với mọi chất'],
 'Ví dụ cùng chiều dài, cùng tăng nhiệt độ, nhôm nở nhiều hơn đồng, đồng nhiều hơn sắt.'],
['no', 'So sánh sự nở vì nhiệt của các chất:',
 ['chất khí nở nhiều nhất, rồi đến chất lỏng, chất rắn nở ít nhất', 'chất rắn nở nhiều nhất', 'chất lỏng nở ít nhất', 'ba chất nở như nhau'],
 'Khí > lỏng > rắn. Các chất khí khác nhau nở vì nhiệt giống nhau.'],
['no', 'Quả cầu kim loại lọt qua vòng kim loại khi nguội. Hơ nóng quả cầu thì quả cầu không lọt qua vòng nữa vì',
 ['quả cầu nở ra khi nóng lên', 'vòng co lại', 'quả cầu nặng hơn', 'vòng nở ra'],
 'Thể tích quả cầu tăng khi nhiệt độ tăng. Nếu hơ nóng cả vòng thì cầu lại lọt.'],
['no', 'Băng kép (đồng – thép) khi bị đốt nóng sẽ',
 ['cong về phía thanh thép vì đồng nở dài nhiều hơn thép', 'cong về phía thanh đồng', 'thẳng ra', 'gãy đôi'],
 'Đồng dài hơn nên nằm ngoài (phía lồi), thép nằm trong: băng kép cong về phía thép.'],
['no', 'Băng kép được ứng dụng để',
 ['tự động đóng ngắt mạch điện theo nhiệt độ (rơle nhiệt trong bàn là, ấm điện)', 'đo khối lượng', 'làm dây dẫn điện', 'dẫn nhiệt tốt hơn'],
 'Nóng lên băng kép cong, tách tiếp điểm → ngắt điện; nguội lại thẳng → đóng điện.'],
['no', 'Giữa các thanh ray đường sắt thường để khe hở vì',
 ['khi nóng thanh ray nở dài, không có khe sẽ bị cong, gãy', 'để tiết kiệm sắt', 'để tàu chạy êm', 'để thoát nước'],
 'Sự nở vì nhiệt bị ngăn cản sinh ra lực rất lớn có thể làm cong ray.'],
['no', 'Một đầu cầu thép được đặt trên các con lăn để',
 ['cầu có thể nở dài, co ngắn theo nhiệt độ mà không bị hỏng', 'cầu di chuyển được', 'giảm ma sát cho xe', 'cầu nhẹ hơn'],
 'Cầu dài hàng trăm mét có thể giãn ra vài chục cm khi nóng.'],
['no', 'Tháp Eiffel bằng thép cao khoảng 300 m. Vào mùa hè, tháp',
 ['cao hơn mùa đông vài chục cm do thép nở ra', 'thấp hơn mùa đông', 'không thay đổi chiều cao', 'nghiêng đi'],
 'Thép nở dài khi nóng; chiều cao tháp thay đổi khoảng 10–17 cm giữa mùa hè và mùa đông.'],
['no', 'Nhiệt kế thuỷ ngân, nhiệt kế rượu hoạt động dựa trên',
 ['sự nở vì nhiệt của chất lỏng', 'sự nở vì nhiệt của chất rắn', 'sự nở vì nhiệt của chất khí', 'sự bay hơi'],
 'Chất lỏng trong bầu nở ra khi nóng, dâng lên trong ống mao dẫn.'],
['no', 'Nước ngọt, nước khoáng đóng chai không được đổ quá đầy vì',
 ['chất lỏng nở ra khi nóng có thể làm bật nắp hoặc vỡ chai', 'để nhẹ hơn', 'để tiết kiệm', 'để nhìn đẹp'],
 'Chất lỏng nở nhiều hơn chai (rắn); không có khoảng trống thì sinh lực rất lớn.'],
['no', 'Quả bóng bàn bị bẹp, nhúng vào nước nóng lại phồng lên vì',
 ['không khí trong bóng nóng lên, nở ra, đẩy vỏ bóng phồng lên', 'vỏ bóng nở ra', 'nước ngấm vào bóng', 'bóng nhẹ hơn'],
 'Chất khí nở vì nhiệt rất mạnh; điều kiện: bóng không bị thủng.'],
['no', 'Để quả bóng bay bơm căng ngoài trời nắng, bóng có thể nổ vì',
 ['không khí trong bóng nóng lên nở ra làm vỏ căng quá mức', 'vỏ bóng co lại', 'ánh sáng làm vỏ mỏng đi', 'bóng bay lên cao'],
 'Chất khí nở vì nhiệt nhiều nên thể tích tăng đáng kể khi bị nắng.'],
['no', 'Lọ thuỷ tinh có nắp kim loại bị kẹt, khó mở. Cách làm đúng là',
 ['hơ nóng nắp: nắp kim loại nở nhiều hơn miệng lọ thuỷ tinh nên lỏng ra', 'làm lạnh nắp', 'hơ nóng đáy lọ', 'đổ nước vào lọ'],
 'Kim loại nở vì nhiệt nhiều hơn thuỷ tinh nên nắp rộng ra.'],
['no', 'Rót nước sôi vào cốc thuỷ tinh dày, cốc có thể nứt vì',
 ['lớp trong nóng nở nhanh, lớp ngoài chưa nở, sự nở không đều tạo lực làm nứt', 'thuỷ tinh tan trong nước nóng', 'nước sôi quá nặng', 'cốc dày dẫn nhiệt tốt'],
 'Để tránh, tráng cốc bằng nước ấm trước hoặc dùng cốc mỏng, thuỷ tinh chịu nhiệt.'],
['no', 'Đun ấm nước đầy, khi nước nóng lên thì nước tràn ra ngoài dù chưa sôi vì',
 ['nước nở ra khi nóng lên, thể tích tăng', 'ấm co lại', 'nước bay hơi', 'không khí đẩy nước'],
 'Chất lỏng nở vì nhiệt nhiều hơn chất rắn nên nước tràn dù ấm cũng nở một ít.'],
['no', 'Khi một vật nóng lên (không đổi trạng thái), khối lượng, thể tích và khối lượng riêng của nó thay đổi thế nào?',
 ['Khối lượng không đổi, thể tích tăng, khối lượng riêng giảm', 'Khối lượng tăng, thể tích tăng, khối lượng riêng không đổi', 'Khối lượng không đổi, thể tích giảm, khối lượng riêng tăng', 'Cả ba đều tăng'],
 'Số phân tử không đổi nên m không đổi; V tăng nên D = m/V giảm.'],
['no', 'Tấm tôn lợp mái có dạng lượn sóng vì',
 ['để tôn co giãn vì nhiệt mà không bị cong vênh, đứt đinh', 'để đẹp', 'để nhẹ hơn', 'để thoát nước nhanh'],
 'Dạng sóng cho phép tôn giãn ra, co lại theo nhiệt độ trong ngày.'],
['no', 'Khinh khí cầu dùng khí nóng bay lên vì',
 ['khí nóng nở ra, khối lượng riêng giảm, nhẹ hơn không khí lạnh xung quanh', 'khí nóng nặng hơn', 'lửa đẩy khí cầu lên', 'khí nóng bám vào vỏ'],
 'Không khí nóng trong cầu nhẹ hơn không khí ngoài → lực đẩy Archimedes lớn hơn trọng lượng.'],
['no', 'Điều đặc biệt trong sự nở vì nhiệt của nước là',
 ['từ 0 °C đến 4 °C nước co lại khi nóng lên; khối lượng riêng lớn nhất ở 4 °C', 'nước không nở vì nhiệt', 'nước nở đều ở mọi nhiệt độ', 'nước co lại khi nóng lên ở mọi nhiệt độ'],
 'Vì vậy mùa đông nước ở đáy hồ vẫn khoảng 4 °C, cá sống được dưới lớp băng.'],
['no', 'Dây điện trên cột điện vào mùa hè bị chùng xuống nhiều hơn mùa đông vì',
 ['dây nở dài khi nóng lên', 'dây nặng hơn khi nóng', 'cột điện lùn xuống', 'gió mùa hè mạnh'],
 'Chiều dài dây tăng khi nhiệt độ tăng nên dây võng nhiều hơn. Khi lắp không được kéo quá căng.'],
['no', 'Hai thanh sắt và đồng cùng chiều dài ban đầu, nung nóng cùng độ tăng nhiệt độ. Kết quả',
 ['thanh đồng dài hơn thanh sắt', 'thanh sắt dài hơn thanh đồng', 'hai thanh vẫn dài bằng nhau', 'hai thanh đều ngắn lại'],
 'Đồng nở dài vì nhiệt nhiều hơn sắt (khoảng 1,5 lần).'],
['no', 'Trong ống thuỷ tinh cắm qua nút của bình cầu chứa không khí có một giọt nước màu. Áp hai bàn tay vào bình, giọt nước dịch chuyển ra phía ngoài. Thí nghiệm chứng tỏ',
 ['không khí nở ra khi nóng lên', 'nước bay hơi', 'thuỷ tinh nở ra', 'giọt nước nặng hơn'],
 'Hơi ấm từ tay làm không khí trong bình nóng lên, nở ra, đẩy giọt nước đi.'],
['no', 'Nhiệt kế y tế có chỗ thắt nhỏ ở gần bầu để',
 ['giữ thuỷ ngân không tụt về bầu khi lấy nhiệt kế ra khỏi cơ thể, đọc được kết quả', 'thuỷ ngân nở nhanh hơn', 'trang trí', 'chứa thêm thuỷ ngân'],
 'Khi nguội, cột thuỷ ngân bị đứt tại chỗ thắt và giữ nguyên mức đã đo.'],
['no', 'Bê tông được kết hợp với cốt thép vì (về mặt nở vì nhiệt)',
 ['bê tông và thép nở vì nhiệt gần như nhau nên không bị tách, nứt khi thay đổi nhiệt độ', 'thép không nở vì nhiệt', 'bê tông nở nhiều hơn thép', 'thép cách nhiệt'],
 'Nếu hai vật liệu nở khác nhau nhiều, khi nóng lạnh công trình sẽ rạn nứt.'],
['no', 'Xe đạp để ngoài trời nắng gắt lâu, bánh xe bơm căng có thể bị nổ vì',
 ['không khí trong săm nóng lên, nở ra, áp suất tăng quá mức', 'săm co lại', 'lốp mềm ra', 'xe nặng hơn'],
 'Chất khí nở vì nhiệt mạnh; săm không giãn kịp nên áp suất tăng.'],
['no', 'Nhiệt kế rượu thích hợp đo nhiệt độ rất thấp (vùng cực) hơn nhiệt kế thuỷ ngân vì',
 ['rượu đông đặc ở khoảng −117 °C, thấp hơn nhiều so với thuỷ ngân (−39 °C)', 'rượu nở ít hơn', 'rượu có màu', 'rượu rẻ hơn'],
 'Thuỷ ngân đông đặc ở −39 °C nên không đo được nhiệt độ thấp hơn.'],
['no', 'Dụng cụ nấu bằng thuỷ tinh chịu nhiệt không bị nứt khi nóng vì',
 ['thuỷ tinh chịu nhiệt nở vì nhiệt rất ít', 'thuỷ tinh chịu nhiệt dẫn nhiệt tốt', 'thuỷ tinh chịu nhiệt rất mỏng', 'thuỷ tinh chịu nhiệt không nóng'],
 'Nở ít nên sự nở không đều giữa các lớp không tạo ra lực lớn.'],
['no', 'Khi sự nở vì nhiệt bị ngăn cản thì',
 ['sinh ra lực rất lớn có thể làm cong, gãy, nứt vật', 'vật không nở nữa mà không sao', 'vật bị mất nhiệt', 'vật co lại'],
 'Ví dụ ray bị cong, tường nứt, chai nước đầy bị vỡ.'],
['no', 'Khi lát gạch nền, người thợ để mạch (khe) nhỏ giữa các viên gạch để',
 ['gạch có chỗ giãn nở khi nóng, không bị bong, vỡ', 'dễ lát hơn', 'tiết kiệm gạch', 'thoát nước'],
 'Gạch nở ra khi nắng nóng; khe hở tránh các viên chèn ép lên nhau.'],
['no', 'Bàn là điện quá nóng thì tự ngắt vì',
 ['băng kép trong bàn là nóng lên bị cong, tách khỏi tiếp điểm làm hở mạch', 'cầu chì đứt', 'dây đốt đứt', 'nam châm hút'],
 'Đây là ứng dụng của băng kép làm rơle nhiệt.'],
['no', 'Tấm kính lớn lắp trong khung kim loại cần có đệm cao su vì',
 ['kim loại và kính nở vì nhiệt khác nhau, đệm cao su tránh kính bị ép nứt', 'để cách âm', 'để đẹp', 'để kính không rơi'],
 'Khung nở nhiều hơn kính; không có đệm, kính bị ép khi nóng hoặc lỏng khi lạnh.'],
['no', 'Không nên đổ xăng thật đầy bình khi trời nóng vì',
 ['xăng nở ra khi nóng, có thể trào ra ngoài gây lãng phí và nguy hiểm', 'xăng nặng hơn', 'bình xăng co lại', 'xăng bay hơi nhanh hơn khi đầy'],
 'Chất lỏng nở vì nhiệt nhiều hơn bình chứa (rắn).'],
['no', 'Sắp xếp theo mức độ nở dài vì nhiệt tăng dần (cùng chiều dài, cùng tăng nhiệt độ): sắt, đồng, nhôm.',
 ['Sắt < đồng < nhôm', 'Nhôm < đồng < sắt', 'Đồng < sắt < nhôm', 'Sắt < nhôm < đồng'],
 'Nhôm nở dài nhiều nhất, sắt (thép) nở ít nhất trong ba kim loại này.'],
['no', 'Bình cầu thuỷ tinh đựng đầy nước màu, ống thuỷ tinh cắm qua nút. Nhúng bình vào nước nóng, mực nước trong ống lúc đầu hạ xuống một chút rồi mới dâng cao vì',
 ['bình thuỷ tinh nóng trước, nở ra trước; sau đó nước nóng lên và nở nhiều hơn bình', 'nước co lại khi nóng', 'nước bay hơi', 'ống bị tắc'],
 'Nhiệt truyền tới thuỷ tinh trước; nước nở vì nhiệt nhiều hơn thuỷ tinh nên cuối cùng dâng lên.'],
['no', 'Chất khí trong bình kín (thể tích không đổi) khi bị nung nóng thì',
 ['áp suất khí tăng lên', 'thể tích khí tăng lên', 'khối lượng khí tăng', 'không có gì thay đổi'],
 'Không nở ra được về thể tích, khí nóng va đập vào thành bình mạnh hơn nên áp suất tăng; đó là lí do bình kín có thể nổ.'],
['no', 'Nhiệt kế kim loại dùng trong lò nướng hoạt động dựa trên',
 ['sự nở vì nhiệt của băng kép (thanh kim loại kép) làm kim quay', 'sự nở vì nhiệt của chất lỏng', 'sự nở vì nhiệt của chất khí', 'sự bay hơi'],
 'Băng kép xoắn cong theo nhiệt độ, kéo kim chỉ thị.'],
];
