/* vatli7-bank-a.mjs — ngân hàng câu VIẾT TAY cho Vật lí 7 (KHTN 7, KNTT)
   Phần A: chương TỐC ĐỘ và chương ÂM THANH.
   Mỗi câu: [text, đáp án ĐÚNG, nhiễu 1, nhiễu 2, nhiễu 3, giải thích]
   (phương án đúng luôn đứng đầu — script sinh sẽ xáo vị trí A/B/C/D). */

export const TOC = [
['Tốc độ của một vật cho ta biết điều gì?',
 'Mức độ nhanh hay chậm của chuyển động', 'Quãng đường vật đã đi được', 'Thời gian vật đã chuyển động', 'Hướng chuyển động của vật',
 'Tốc độ đặc trưng cho sự nhanh, chậm của chuyển động: v = s/t.'],
['Công thức tính tốc độ là',
 'v = s/t', 'v = s × t', 'v = t/s', 'v = s + t',
 'Tốc độ bằng quãng đường đi được chia cho thời gian đi hết quãng đường đó.'],
['Đơn vị đo tốc độ trong hệ đơn vị SI là',
 'm/s', 'km/h', 'km/s', 'm/phút',
 'Trong SI, quãng đường đo bằng mét, thời gian đo bằng giây nên tốc độ đo bằng m/s. km/h là đơn vị thường dùng nhưng không phải đơn vị SI.'],
['1 m/s bằng bao nhiêu km/h?',
 '3,6 km/h', '0,36 km/h', '36 km/h', '60 km/h',
 '1 m/s = 1 m trong 1 s = 3600 m trong 1 h = 3,6 km/h.'],
['1 km/h xấp xỉ bằng',
 '0,28 m/s', '3,6 m/s', '1000 m/s', '0,6 m/s',
 '1 km/h = 1000 m / 3600 s ≈ 0,28 m/s.'],
['Dụng cụ báo tốc độ tức thời trên ô tô, xe máy gọi là',
 'Tốc kế (đồng hồ đo tốc độ)', 'Nhiệt kế', 'Lực kế', 'Áp kế',
 'Tốc kế trên bảng đồng hồ xe cho biết tốc độ của xe tại từng thời điểm.'],
['Để xác định tốc độ của một vật chuyển động, cần đo trực tiếp hai đại lượng nào?',
 'Quãng đường đi được và thời gian đi hết quãng đường đó', 'Khối lượng và thời gian', 'Quãng đường và khối lượng', 'Lực kéo và quãng đường',
 'Từ s và t đo được, tính v = s/t.'],
['Trong thí nghiệm đo tốc độ bằng cổng quang điện, đồng hồ đo thời gian hiện số bắt đầu đếm khi nào?',
 'Khi tấm chắn sáng gắn trên xe đi qua (che) cổng quang điện thứ nhất', 'Khi người làm thí nghiệm bấm nút bằng tay', 'Khi xe bắt đầu được thả ở đầu máng', 'Khi xe đi qua cổng quang điện thứ hai',
 'Tấm chắn sáng che tia hồng ngoại của cổng quang thứ nhất → đồng hồ bắt đầu đếm; che cổng thứ hai → đồng hồ dừng.'],
['Ưu điểm nổi bật của việc dùng cổng quang điện kết hợp đồng hồ đo thời gian hiện số so với đồng hồ bấm giây là',
 'Loại bỏ sai số do phản ứng của người bấm, đo được khoảng thời gian rất ngắn', 'Không cần đo quãng đường nữa', 'Đo được quãng đường dài hơn', 'Đo được cả khối lượng của vật',
 'Đồng hồ tự động bật/tắt khi vật che cổng quang nên không phụ thuộc phản xạ tay của người đo.'],
['Khi đo thời gian bằng đồng hồ bấm giây, sai số chủ yếu đến từ',
 'Thời gian phản ứng của người bấm nút', 'Đồng hồ chạy ngược', 'Quãng đường bị thay đổi', 'Vật chuyển động quá nặng',
 'Người bấm luôn chậm hơn thời điểm thực một chút (khoảng 0,1 – 0,3 s), gây sai số.'],
['Trong đồ thị quãng đường – thời gian, trục nằm ngang (trục hoành) thường biểu diễn',
 'Thời gian t', 'Quãng đường s', 'Tốc độ v', 'Khối lượng m',
 'Quy ước: trục hoành là thời gian, trục tung là quãng đường.'],
['Đồ thị quãng đường – thời gian của một vật chuyển động với tốc độ không đổi, xuất phát từ gốc, có dạng',
 'Đường thẳng xiên đi lên, qua gốc toạ độ', 'Đường thẳng nằm ngang', 'Đường cong đi lên', 'Đường thẳng thẳng đứng',
 'Quãng đường tỉ lệ thuận với thời gian nên đồ thị là đường thẳng qua gốc toạ độ.'],
['Trên đồ thị quãng đường – thời gian, đoạn đồ thị nằm ngang (song song trục thời gian) cho biết',
 'Vật đang đứng yên', 'Vật chuyển động đều', 'Vật chuyển động nhanh dần', 'Vật đang quay về chỗ cũ',
 'Thời gian trôi nhưng quãng đường không tăng → vật không di chuyển.'],
['Trên cùng một đồ thị quãng đường – thời gian, đường nào <b>dốc hơn</b> thì ứng với',
 'Tốc độ lớn hơn', 'Tốc độ nhỏ hơn', 'Thời gian đi lâu hơn', 'Quãng đường đi ngắn hơn',
 'Độ dốc của đồ thị s – t chính là tốc độ: cùng thời gian đi được quãng đường lớn hơn.'],
['Hai xe cùng xuất phát từ một vị trí, đồ thị s – t là hai đường thẳng qua gốc toạ độ, đường của xe A nằm phía trên đường của xe B. Kết luận nào đúng?',
 'Xe A có tốc độ lớn hơn xe B', 'Xe B có tốc độ lớn hơn xe A', 'Hai xe cùng tốc độ', 'Xe A xuất phát trước xe B',
 'Ở cùng một thời điểm, xe A đi được quãng đường lớn hơn → nhanh hơn.'],
['"Khoảng cách an toàn" giữa hai xe khi tham gia giao thông là khoảng cách',
 'Đủ để người lái xe sau kịp xử lí, phanh dừng khi xe trước dừng đột ngột', 'Bằng đúng chiều dài của xe', 'Tối đa mà hai xe được phép cách nhau', 'Do người lái tự chọn, không phụ thuộc tốc độ',
 'Khoảng cách an toàn phụ thuộc tốc độ; càng nhanh càng phải giữ xa hơn.'],
['Tốc độ của xe càng lớn thì khoảng cách an toàn tối thiểu với xe phía trước',
 'Càng lớn', 'Càng nhỏ', 'Không thay đổi', 'Bằng 0 khi xe đi trên đường cao tốc',
 'Xe nhanh cần quãng đường phanh dài hơn nên phải giữ khoảng cách lớn hơn.'],
['Theo quy định hiện hành ở Việt Nam, xe chạy với tốc độ trên 60 km/h đến 80 km/h phải giữ khoảng cách an toàn tối thiểu là',
 '55 m', '35 m', '70 m', '100 m',
 'Bảng quy định: 60–80 km/h: 55 m; 80–100 km/h: 70 m; 100–120 km/h: 100 m; dưới 60 km/h: 35 m (trở lên).'],
['Xe chạy trên đường cao tốc với tốc độ trên 100 km/h đến 120 km/h, khoảng cách an toàn tối thiểu là',
 '100 m', '70 m', '55 m', '35 m',
 'Theo bảng khoảng cách an toàn: 100–120 km/h → 100 m.'],
['Quy tắc "3 giây" giữ khoảng cách an toàn được thực hiện như thế nào?',
 'Chọn một mốc cố định bên đường; xe mình phải đi qua mốc đó sau xe trước ít nhất 3 giây', 'Đếm 3 giây rồi tăng tốc vượt xe trước', 'Chạy sau xe trước đúng 3 m', 'Bật đèn xin đường 3 giây trước khi phanh',
 'Khoảng cách tương ứng với 3 giây chuyển động đủ để người lái phản ứng và phanh.'],
['Khi đường trơn ướt do mưa, khoảng cách an toàn giữa hai xe nên',
 'Tăng lên so với khi đường khô', 'Giảm xuống cho đỡ tắc đường', 'Giữ nguyên như đường khô', 'Không cần quan tâm',
 'Đường trơn làm quãng đường phanh dài hơn, cần khoảng cách lớn hơn.'],
['Camera bắn tốc độ kiểu "hai vạch mốc" xác định tốc độ của xe bằng cách',
 'Ghi thời gian xe đi hết quãng đường giữa hai vạch mốc rồi tính v = s/t', 'Đo khối lượng của xe', 'Đếm số bánh xe quay', 'Chụp ảnh biển số rồi tra cứu',
 'Thiết bị biết khoảng cách hai vạch, đo thời gian xe đi qua → tính tốc độ.'],
['Biển báo hình tròn, viền đỏ, nền trắng ghi số 50 có ý nghĩa gì?',
 'Tốc độ tối đa cho phép là 50 km/h', 'Tốc độ tối thiểu là 50 km/h', 'Còn 50 km nữa tới đích', 'Đường dài 50 km',
 'Biển tròn viền đỏ là biển cấm/hạn chế: cấm chạy quá 50 km/h.'],
['Biển báo hình tròn nền xanh ghi số 60 (không có gạch chéo) đặt trên đường cao tốc có ý nghĩa',
 'Tốc độ tối thiểu cho phép là 60 km/h', 'Tốc độ tối đa cho phép là 60 km/h', 'Đoạn đường dài 60 km', 'Cấm xe chạy 60 km/h',
 'Biển tròn nền xanh ghi số là biển hiệu lệnh tốc độ tối thiểu.'],
['Tốc độ trung bình của một vật trên cả quãng đường được tính bằng',
 'Tổng quãng đường đi được chia cho tổng thời gian đi', 'Trung bình cộng các tốc độ trên từng đoạn', 'Tốc độ lớn nhất trừ tốc độ nhỏ nhất', 'Tốc độ trên đoạn đường dài nhất',
 'v<sub>tb</sub> = (s<sub>1</sub> + s<sub>2</sub> + …)/(t<sub>1</sub> + t<sub>2</sub> + …). Chỉ khi các đoạn có thời gian bằng nhau thì trung bình cộng mới đúng.'],
['Đơn vị nào sau đây <b>không</b> phải là đơn vị của tốc độ?',
 'kg/m', 'm/s', 'km/h', 'cm/s',
 'Tốc độ = quãng đường/thời gian, nên đơn vị phải là (đơn vị độ dài)/(đơn vị thời gian).'],
['Tốc độ đi bộ bình thường của một người vào khoảng',
 '1,5 m/s (khoảng 5 km/h)', '15 m/s', '0,15 m/s', '150 m/s',
 'Người đi bộ mỗi giờ được khoảng 4 – 6 km, tức 1 – 1,7 m/s.'],
['Tốc độ của xe đạp học sinh đi bình thường vào khoảng',
 '15 km/h', '1,5 km/h', '150 km/h', '15 m/s',
 '15 km/h ≈ 4 m/s là tốc độ đạp xe thong thả; 15 m/s = 54 km/h thì quá nhanh với xe đạp.'],
['Kim tốc kế của ô tô chỉ 60 km/h. Điều đó có nghĩa',
 'Nếu giữ nguyên tốc độ này thì trong 1 giờ xe đi được 60 km', 'Xe đã đi được 60 km', 'Xe đã chạy 1 giờ', 'Xe còn phải đi 60 km nữa',
 'Tốc độ 60 km/h nói lên mỗi giờ đi được 60 km, không nói xe đã đi bao lâu hay bao xa.'],
['Nam và Hà cùng đi từ nhà đến trường trên cùng quãng đường. Nam đi hết 10 phút, Hà đi hết 15 phút. Tốc độ của Nam so với Hà',
 'Gấp 1,5 lần', 'Bằng nhau', 'Bằng 2/3', 'Gấp 2 lần',
 'Cùng s, tốc độ tỉ lệ nghịch với thời gian: v<sub>N</sub>/v<sub>H</sub> = 15/10 = 1,5.'],
['Hai vật chuyển động trong cùng một khoảng thời gian. Vật nào đi được quãng đường dài hơn thì',
 'Có tốc độ lớn hơn', 'Có tốc độ nhỏ hơn', 'Có khối lượng lớn hơn', 'Không kết luận được',
 'Cùng t, s lớn hơn thì v = s/t lớn hơn.'],
['Một ô tô đi 60 km trong 2 giờ đầu, dừng nghỉ 1 giờ, rồi đi tiếp 30 km trong 1 giờ. Tốc độ trung bình trên cả hành trình là',
 '22,5 km/h', '30 km/h', '45 km/h', '90 km/h',
 'Tổng quãng đường 90 km, tổng thời gian (kể cả nghỉ) 4 h → 90/4 = 22,5 km/h.'],
['Nếu quãng đường đi được tăng gấp đôi trong khi thời gian không đổi thì tốc độ',
 'Tăng gấp đôi', 'Giảm một nửa', 'Không đổi', 'Tăng gấp bốn',
 'v = s/t, s tăng 2 lần → v tăng 2 lần.'],
['Nếu cả quãng đường và thời gian đều tăng gấp ba thì tốc độ',
 'Không thay đổi', 'Tăng gấp ba', 'Giảm ba lần', 'Tăng gấp chín',
 'v = 3s/3t = s/t.'],
['Tốc độ hiển thị trên tốc kế của xe tại một thời điểm gọi là',
 'Tốc độ tức thời', 'Tốc độ trung bình', 'Tốc độ tối đa', 'Tốc độ trung bình cộng',
 'Tốc kế cho biết xe đang chạy nhanh hay chậm tại chính lúc đó.'],
['Tốc độ ánh sáng trong không khí xấp xỉ',
 '300 000 km/s', '340 m/s', '3000 km/h', '300 km/s',
 'Ánh sáng đi khoảng 300 000 km mỗi giây — vì thế ta thấy chớp trước khi nghe sấm.'],
['Trên đồ thị quãng đường – thời gian của hai xe, hai đường biểu diễn cắt nhau tại một điểm. Điểm đó cho biết',
 'Hai xe gặp nhau (cùng vị trí ở cùng thời điểm)', 'Hai xe cùng tốc độ', 'Hai xe dừng lại', 'Hai xe đổi chiều',
 'Cùng một t, cùng một s → hai xe ở cùng chỗ.'],
['Trên đồ thị quãng đường – thời gian (s tính từ điểm xuất phát), đoạn đồ thị đi xuống và về giá trị 0 cho biết',
 'Vật quay trở lại vị trí xuất phát', 'Vật chuyển động nhanh hơn', 'Vật đứng yên', 'Vật đi tiếp theo hướng cũ',
 'Khoảng cách tới điểm xuất phát giảm dần về 0 → vật đã quay về nơi bắt đầu.'],
['Súng bắn tốc độ cầm tay của cảnh sát giao thông hoạt động dựa trên nguyên tắc',
 'Phát sóng (radar/laser) tới xe và thu sóng phản xạ để tính tốc độ', 'Đo khối lượng của xe', 'Đếm vòng quay bánh xe', 'Đọc chỉ số trên tốc kế của xe',
 'Thiết bị dựa vào thời gian/tần số sóng phản xạ từ xe để tính tốc độ ngay lập tức.'],
['Khi tốc độ xe tăng gấp đôi thì quãng đường xe trượt trên đường từ lúc phanh đến lúc dừng tăng khoảng',
 '4 lần', '2 lần', 'Không đổi', '1,5 lần',
 'Quãng đường phanh tỉ lệ với bình phương tốc độ: (2v)<sup>2</sup> = 4v<sup>2</sup>. Đây là lí do phải giảm tốc độ khi đường đông.'],
['Để đo tốc độ của một chiếc xe đồ chơi lăn trên sàn, tối thiểu cần các dụng cụ',
 'Thước đo độ dài và đồng hồ bấm giây', 'Cân và nhiệt kế', 'Lực kế và thước', 'Đồng hồ và cân',
 'Đo s bằng thước, t bằng đồng hồ rồi tính v = s/t.'],
['Ba lần đo thời gian một viên bi lăn hết máng nghiêng cho kết quả 2,1 s; 2,3 s; 2,2 s. Giá trị thời gian nên lấy là',
 '2,2 s (giá trị trung bình)', '2,1 s (giá trị nhỏ nhất)', '2,3 s (giá trị lớn nhất)', '6,6 s (tổng ba lần)',
 'Lấy trung bình cộng nhiều lần đo để giảm sai số: (2,1 + 2,3 + 2,2)/3 = 2,2 s.'],
['15 phút đổi ra giờ là',
 '0,25 h', '0,15 h', '1,5 h', '0,5 h',
 '15/60 = 0,25 h.'],
['Vật A chuyển động với tốc độ 5 m/s, vật B với tốc độ 18 km/h. So sánh tốc độ hai vật',
 'Bằng nhau', 'A nhanh hơn B', 'B nhanh hơn A', 'Không so sánh được',
 '18 km/h = 18/3,6 = 5 m/s.'],
['Bảng số liệu của một vật: t (s): 0; 1; 2; 3 — s (m): 0; 4; 8; 12. Kết luận nào đúng?',
 'Vật chuyển động với tốc độ không đổi 4 m/s', 'Vật chuyển động nhanh dần', 'Vật đứng yên', 'Tốc độ của vật là 12 m/s',
 'Mỗi giây quãng đường tăng thêm 4 m → v = 4 m/s không đổi.'],
['Một xe đi 30 km hết 45 phút. Tốc độ của xe là',
 '40 km/h', '30 km/h', '45 km/h', '67,5 km/h',
 '45 phút = 0,75 h; v = 30/0,75 = 40 km/h.'],
['Một vật chuyển động với tốc độ 15 m/s. Trong 1 phút vật đi được',
 '900 m', '15 m', '60 m', '150 m',
 's = v·t = 15 × 60 = 900 m.'],
['Trong thí nghiệm đo tốc độ trên máng, người ta gắn tấm chắn sáng lên xe nhằm',
 'Che tia sáng của cổng quang điện để đồng hồ tự bật/tắt', 'Cho xe nặng hơn', 'Giảm ma sát cho xe', 'Trang trí cho đẹp',
 'Cổng quang điện chỉ "nhận biết" xe khi có vật che tia hồng ngoại giữa hai nhánh của cổng.'],
['Khi s đo bằng km và t đo bằng giờ thì tốc độ có đơn vị',
 'km/h', 'm/s', 'km/s', 'h/km',
 'Đơn vị tốc độ bằng đơn vị quãng đường chia cho đơn vị thời gian.'],
['Xe A đi 3 km trong 6 phút, xe B đi 5 km trong 12 phút. Xe nào nhanh hơn?',
 'Xe A nhanh hơn (30 km/h so với 25 km/h)', 'Xe B nhanh hơn', 'Hai xe nhanh bằng nhau', 'Không đủ dữ liệu để so sánh',
 'v<sub>A</sub> = 3/0,1 = 30 km/h; v<sub>B</sub> = 5/0,2 = 25 km/h.'],
['Xe ô tô chạy với tốc độ 20 m/s. Người lái mất 1 s để nhận ra nguy hiểm và đạp phanh. Trong 1 s đó xe đã đi được',
 '20 m', '2 m', '72 m', '0 m',
 'Trong thời gian phản ứng xe vẫn chạy: s = 20 × 1 = 20 m. Đây gọi là quãng đường phản ứng.'],
['Hai vật xuất phát cùng lúc từ hai vị trí khác nhau, chuyển động cùng hướng với tốc độ bằng nhau. Đồ thị s – t của chúng là',
 'Hai đường thẳng song song', 'Hai đường thẳng cắt nhau', 'Hai đường trùng nhau', 'Hai đường thẳng nằm ngang',
 'Cùng tốc độ → cùng độ dốc → song song; khác vị trí đầu → không trùng nhau.'],
['Trong hàng hải, tốc độ tàu thường được đo bằng đơn vị "hải lí/giờ" (knot). Đây là',
 'Một đơn vị tốc độ', 'Một đơn vị quãng đường', 'Một đơn vị thời gian', 'Một đơn vị khối lượng',
 '1 hải lí ≈ 1,852 km; hải lí/giờ là quãng đường/thời gian → đơn vị tốc độ.'],
['Dụng cụ dùng để đo tốc độ gió là',
 'Máy đo gió (phong tốc kế)', 'Nhiệt kế', 'Ẩm kế', 'Vũ lượng kế',
 'Máy đo gió có các cánh quay, tốc độ quay tỉ lệ với tốc độ gió.'],
['Một vật đi được 1 km trong 1 phút. Tốc độ của vật là',
 '60 km/h', '1 km/h', '6 km/h', '600 km/h',
 '1 phút = 1/60 h → v = 1 : (1/60) = 60 km/h.'],
['Trên đường cao tốc có cột biển báo: biển trên ghi 120 (viền đỏ), biển dưới ghi 60 (nền xanh). Ý nghĩa là',
 'Tốc độ tối đa 120 km/h, tối thiểu 60 km/h', 'Tốc độ tối đa 60 km/h, tối thiểu 120 km/h', 'Chỉ được chạy đúng 120 km/h hoặc 60 km/h', 'Đường dài 120 km, còn 60 km nữa',
 'Biển tròn viền đỏ: tốc độ tối đa; biển tròn nền xanh: tốc độ tối thiểu.'],
['Người lái xe buồn ngủ hoặc dùng điện thoại khi lái sẽ nguy hiểm vì',
 'Thời gian phản ứng dài hơn nên quãng đường xe đi trước khi phanh tăng lên', 'Tốc độ của xe tự tăng lên', 'Động cơ xe nóng hơn', 'Tốc kế bị sai',
 'Phản ứng chậm → xe chạy thêm quãng đường lớn trước khi bắt đầu phanh.'],
['Xe khách chạy 45 km/h muốn đi hết quãng đường 90 km thì cần thời gian',
 '2 giờ', '4 giờ', '45 phút', '1 giờ 30 phút',
 't = s/v = 90/45 = 2 h.'],
['Con báo săn có thể chạy 30 m/s, tức là khoảng',
 '108 km/h', '30 km/h', '8,3 km/h', '1800 km/h',
 '30 × 3,6 = 108 km/h.'],
['Xe thứ nhất đi 100 m trong 10 s, xe thứ hai đi 500 m trong 100 s. Kết luận nào đúng?',
 'Xe thứ nhất nhanh hơn xe thứ hai', 'Xe thứ hai nhanh hơn vì đi xa hơn', 'Hai xe nhanh bằng nhau', 'Xe thứ hai nhanh hơn vì đi lâu hơn',
 'v<sub>1</sub> = 10 m/s; v<sub>2</sub> = 5 m/s.'],
['Một xe đi nửa quãng đường đầu với tốc độ 30 km/h, nửa quãng đường sau với tốc độ 60 km/h. Tốc độ trung bình trên cả quãng đường là',
 '40 km/h', '45 km/h', '90 km/h', '30 km/h',
 'Gọi cả đường là 2s: t = s/30 + s/60 = s/20 → v<sub>tb</sub> = 2s : (s/20) = 40 km/h. Không phải trung bình cộng!'],
['Một xe đi với tốc độ 30 km/h trong nửa thời gian đầu và 60 km/h trong nửa thời gian sau. Tốc độ trung bình của xe là',
 '45 km/h', '40 km/h', '90 km/h', '50 km/h',
 'Hai khoảng thời gian bằng nhau (mỗi khoảng t): s = 30t + 60t = 90t → v<sub>tb</sub> = 90t/2t = 45 km/h.'],
['Bảng số liệu: t (s): 0; 1; 2; 3; 4 — s (m): 0; 5; 10; 10; 10. Vật đứng yên trong khoảng thời gian',
 'Từ giây thứ 2 đến giây thứ 4', 'Từ giây 0 đến giây thứ 2', 'Từ giây thứ 1 đến giây thứ 2', 'Vật không đứng yên lúc nào',
 'Từ t = 2 s trở đi quãng đường giữ nguyên 10 m → vật không di chuyển.'],
['Một học sinh chạy 60 m hết 12 s. Tốc độ của bạn ấy là',
 '5 m/s', '720 m/s', '0,2 m/s', '72 m/s',
 'v = 60/12 = 5 m/s.'],
['Người đi bộ với tốc độ 5 km/h đi hết quãng đường 2,5 km trong',
 '30 phút', '2 giờ', '12,5 phút', '50 phút',
 't = 2,5/5 = 0,5 h = 30 phút.'],
['Một vật đi 40 m trong 8 s rồi quay ngược lại đúng 40 m trong 4 s. Tốc độ trung bình của vật trong cả quá trình là',
 'Khoảng 6,7 m/s', '0 m/s', '10 m/s', '5 m/s',
 'Tổng quãng đường 80 m, tổng thời gian 12 s → 80/12 ≈ 6,7 m/s.'],
['Đơn vị mm/s thích hợp để mô tả tốc độ của',
 'Ốc sên đang bò', 'Máy bay phản lực', 'Ô tô trên cao tốc', 'Tàu cao tốc',
 'Ốc sên bò chỉ vài mm mỗi giây; các vật kia đi hàng chục mét mỗi giây.'],
['Quãng đường phanh của ô tô <b>không</b> phụ thuộc vào',
 'Màu sơn của xe', 'Tốc độ của xe', 'Tình trạng mặt đường (khô, ướt)', 'Chất lượng phanh và lốp xe',
 'Màu xe không liên quan tới chuyển động; các yếu tố còn lại đều ảnh hưởng đến quãng đường phanh.'],
['Phát biểu nào sau đây về an toàn giao thông là <b>sai</b>?',
 'Chạy càng nhanh càng dễ dừng xe kịp thời', 'Đi càng nhanh thì càng phải giữ khoảng cách xa xe trước', 'Trời mưa nên giảm tốc độ', 'Không vượt xe khi tầm nhìn bị hạn chế',
 'Tốc độ càng lớn thì quãng đường phanh càng dài, càng khó dừng kịp.'],
['Nếu đồ thị quãng đường – thời gian là đường cong đi lên và ngày càng dốc thì vật',
 'Chuyển động ngày càng nhanh', 'Chuyển động ngày càng chậm', 'Đứng yên', 'Chuyển động đều',
 'Độ dốc tăng dần → tốc độ tăng dần.'],
['Tốc độ âm thanh trong không khí 340 m/s tương đương khoảng',
 '1224 km/h', '340 km/h', '94 km/h', '12 240 km/h',
 '340 × 3,6 = 1224 km/h.'],
['Muốn so sánh tốc độ của hai vật cho bằng đơn vị khác nhau (m/s và km/h), trước hết phải',
 'Đổi về cùng một đơn vị', 'So sánh trực tiếp các con số', 'Cộng hai tốc độ lại', 'Đo lại quãng đường',
 'Chỉ so sánh được các số đo cùng đơn vị.'],
['Trong công thức v = s/t, nếu s đo bằng cm và t đo bằng giây thì v có đơn vị',
 'cm/s', 'm/s', 'cm', 's/cm',
 'Tốc độ = đơn vị độ dài / đơn vị thời gian = cm/s.'],
['Xe máy chạy 40 km/h, ô tô chạy 15 m/s. Xe nào nhanh hơn?',
 'Ô tô (15 m/s = 54 km/h)', 'Xe máy', 'Bằng nhau', 'Không so sánh được',
 '15 × 3,6 = 54 km/h > 40 km/h.'],
['Một tàu hoả chạy với tốc độ 20 m/s. Tốc độ này bằng',
 '72 km/h', '20 km/h', '7,2 km/h', '200 km/h',
 '20 × 3,6 = 72 km/h.'],
['Ô tô chạy 108 km/h, đổi ra m/s là',
 '30 m/s', '388,8 m/s', '3 m/s', '1,8 m/s',
 '108 : 3,6 = 30 m/s.'],
['Trong thí nghiệm với hai cổng quang điện cách nhau 0,5 m, đồng hồ hiện số chỉ 0,250 s. Tốc độ xe là',
 '2 m/s', '0,125 m/s', '0,5 m/s', '20 m/s',
 'v = 0,5/0,25 = 2 m/s.'],
['Chọn phát biểu <b>đúng</b>.',
 'Cùng một quãng đường, vật nào đi ít thời gian hơn thì tốc độ lớn hơn', 'Vật nào đi lâu hơn thì luôn nhanh hơn', 'Tốc độ có đơn vị là mét', 'Vật đi quãng đường dài hơn thì luôn nhanh hơn',
 'v = s/t: s bằng nhau, t nhỏ → v lớn. Các phát biểu khác thiếu điều kiện.'],
['Trên đồ thị s – t, tại thời điểm t = 3 h vật ở cách điểm xuất phát 120 km; đồ thị là đường thẳng qua gốc. Tốc độ của vật là',
 '40 km/h', '120 km/h', '360 km/h', '30 km/h',
 'v = 120/3 = 40 km/h.'],
['Hai người đi xe đạp xuất phát cùng lúc từ hai điểm cách nhau 30 km, đi ngược chiều để gặp nhau với tốc độ 12 km/h và 18 km/h. Họ gặp nhau sau',
 '1 giờ', '2 giờ', '30 phút', '5 giờ',
 'Mỗi giờ khoảng cách giảm 12 + 18 = 30 km → gặp nhau sau 30/30 = 1 h.'],
['Xe A chạy 60 km/h đuổi theo xe B chạy 40 km/h ở phía trước 50 km. Xe A đuổi kịp xe B sau',
 '2,5 giờ', '0,5 giờ', '1 giờ', '5 giờ',
 'Mỗi giờ A rút ngắn khoảng cách 60 − 40 = 20 km → 50/20 = 2,5 h.'],
['Một người đi bộ 1,5 km trong 20 phút rồi chạy 2,5 km trong 10 phút. Tốc độ trung bình trên cả đoạn đường là',
 '8 km/h', '4,5 km/h', '9,75 km/h', '4 km/h',
 'Tổng s = 4 km, tổng t = 30 phút = 0,5 h → 8 km/h.'],
['Vật nào dưới đây có tốc độ lớn nhất?',
 'Máy bay: 250 m/s', 'Ô tô: 120 km/h', 'Tàu cao tốc: 300 km/h', 'Xe máy: 20 m/s',
 '250 m/s = 900 km/h, lớn hơn cả 300 km/h.'],
['Một xe chạy 72 km/h. Trong 10 giây xe đi được',
 '200 m', '720 m', '72 m', '20 m',
 '72 km/h = 20 m/s → s = 20 × 10 = 200 m.'],
['Nói xe chuyển động với tốc độ 50 km/h nghĩa là',
 'Nếu chuyển động đều thì cứ 1 giờ xe đi được 50 km', 'Xe đã đi 50 km', 'Xe đã đi trong 1 giờ', 'Xe nhất định sẽ đi được 50 km',
 'Đó là ý nghĩa của số đo tốc độ.'],
['Tại một cổng trường, biển báo tốc độ tối đa là 30 km/h. Xe máy chạy với tốc độ 10 m/s tại đây thì',
 'Vi phạm, vì 10 m/s = 36 km/h > 30 km/h', 'Không vi phạm, vì 10 < 30', 'Không vi phạm, vì 10 m/s = 27 km/h', 'Không xác định được',
 '10 m/s = 36 km/h, vượt mức cho phép.'],
['Đồ thị s – t của xe gồm: đoạn OA xiên lên (0 → 2 h, s tăng 0 → 80 km), đoạn AB nằm ngang (2 h → 3 h), đoạn BC xiên lên (3 h → 4 h, s tăng 80 → 120 km). Tốc độ trên đoạn BC là',
 '40 km/h', '120 km/h', '30 km/h', '80 km/h',
 'Đoạn BC: quãng đường thêm 40 km trong 1 h → 40 km/h.'],
['Đồ thị s – t của xe gồm: đoạn OA xiên lên (0 → 2 h, s tăng 0 → 80 km), đoạn AB nằm ngang (2 h → 3 h), đoạn BC xiên lên (3 h → 4 h, s tăng 80 → 120 km). Tốc độ trung bình cả hành trình là',
 '30 km/h', '40 km/h', '60 km/h', '35 km/h',
 'Tổng 120 km trong 4 h (kể cả 1 h dừng) → 30 km/h.'],
['Một đoàn tàu dài 200 m chạy với tốc độ 20 m/s. Thời gian để cả đoàn tàu chạy qua một cột điện là',
 '10 s', '20 s', '40 s', '4000 s',
 'Tàu phải đi hết chiều dài chính nó: t = 200/20 = 10 s.'],
['Một đoàn tàu dài 100 m chạy 15 m/s đi qua một cây cầu dài 200 m. Thời gian từ lúc đầu tàu lên cầu đến lúc đuôi tàu rời cầu là',
 '20 s', '13,3 s', '6,7 s', '30 s',
 'Tàu phải đi 200 + 100 = 300 m → 300/15 = 20 s.'],
['Đi từ nhà đến trường, Lan đi 5 phút đầu được 600 m, 5 phút sau được 400 m. Kết luận nào đúng?',
 '5 phút đầu Lan đi nhanh hơn 5 phút sau', '5 phút sau Lan đi nhanh hơn', 'Tốc độ hai đoạn bằng nhau', 'Tốc độ trung bình là 1000 m/phút',
 'Cùng 5 phút, đoạn đầu đi xa hơn → nhanh hơn (2 m/s so với 1,33 m/s).'],
['Tốc độ trung bình của một vận động viên chạy marathon 42 km trong 3 giờ là',
 '14 km/h', '126 km/h', '3,9 km/h', '42 km/h',
 '42/3 = 14 km/h (≈ 3,9 m/s).'],
['Vì sao trong thí nghiệm đo tốc độ ta cần đo quãng đường giữa hai cổng quang chứ không đo từ chỗ thả xe?',
 'Vì đồng hồ chỉ đo thời gian xe đi giữa hai cổng quang', 'Vì quãng đường từ chỗ thả xe không đo được', 'Vì xe không chuyển động trước cổng quang thứ nhất', 'Vì đồng hồ đo cả thời gian trước khi thả xe',
 'Phải lấy quãng đường tương ứng với khoảng thời gian đồng hồ đã đo.'],
['Một ô tô đi 2 giờ với tốc độ 50 km/h rồi đi 1 giờ với tốc độ 80 km/h. Tốc độ trung bình của ô tô là',
 '60 km/h', '65 km/h', '130 km/h', '55 km/h',
 's = 100 + 80 = 180 km; t = 3 h → 60 km/h.'],
['Khoảng cách từ Trái Đất đến Mặt Trăng khoảng 384 000 km. Ánh sáng (300 000 km/s) đi từ Mặt Trăng đến Trái Đất mất khoảng',
 '1,3 s', '13 s', '0,13 s', '78 s',
 't = 384 000/300 000 ≈ 1,28 s.'],
['Một người đi xe đạp với tốc độ không đổi 12 km/h. Sau 25 phút người đó đi được',
 '5 km', '300 km', '3 km', '12 km',
 '25 phút = 25/60 h; s = 12 × 25/60 = 5 km.'],
['Thiết bị nào sau đây <b>không</b> dùng để đo tốc độ?',
 'Cân điện tử', 'Tốc kế trên xe máy', 'Súng bắn tốc độ', 'Bộ cổng quang điện và đồng hồ hiện số',
 'Cân đo khối lượng, không liên quan đến tốc độ.'],
['Một xe đang chạy 90 km/h trên cao tốc. Trong 3 giây xe đi được khoảng',
 '75 m', '270 m', '30 m', '25 m',
 '90 km/h = 25 m/s → 3 s đi 75 m. Đó chính là khoảng cách theo "quy tắc 3 giây".'],
['Khi tính tốc độ trung bình của cả chuyến đi, thời gian dừng nghỉ giữa đường',
 'Phải được tính vào tổng thời gian', 'Không được tính', 'Chỉ tính một nửa', 'Được cộng vào quãng đường',
 'Tốc độ trung bình = tổng quãng đường / tổng thời gian chuyển động thực tế kể cả lúc dừng.'],
['Trong hình đồ thị s – t, đường biểu diễn của xe X dốc gấp đôi đường của xe Y (cả hai qua gốc toạ độ). Kết luận nào đúng?',
 'Tốc độ của X gấp đôi tốc độ của Y', 'Tốc độ của Y gấp đôi tốc độ của X', 'X đi lâu gấp đôi Y', 'Hai xe cùng tốc độ',
 'Độ dốc đồ thị s – t chính là tốc độ.'],
];

export const AM = [
['Nguồn âm là',
 'Vật phát ra âm thanh', 'Vật nghe được âm thanh', 'Vật truyền âm thanh', 'Vật hấp thụ âm thanh',
 'Vật phát ra âm gọi là nguồn âm, ví dụ dây đàn đang rung, mặt trống đang được gõ.'],
['Đặc điểm chung của mọi nguồn âm là',
 'Đều dao động', 'Đều làm bằng kim loại', 'Đều rất to', 'Đều đứng yên',
 'Mọi vật phát ra âm đều dao động (rung động), dù có khi mắt ta không thấy.'],
['Dao động là',
 'Chuyển động qua lại quanh một vị trí cân bằng', 'Chuyển động thẳng đều', 'Chuyển động rơi tự do', 'Chuyển động tròn quanh một tâm',
 'Ví dụ: dây đàn rung, quả lắc đồng hồ, mặt trống lên xuống.'],
['Khi gõ vào mặt trống, bộ phận nào dao động phát ra âm?',
 'Mặt trống', 'Dùi trống', 'Tang trống (thân gỗ)', 'Không khí trong phòng',
 'Mặt trống rung lên, làm không khí xung quanh dao động và truyền âm đến tai.'],
['Khi ta nói, bộ phận nào của cơ thể dao động phát ra âm?',
 'Dây thanh trong thanh quản', 'Lưỡi', 'Răng', 'Môi',
 'Không khí từ phổi đi qua làm dây thanh rung → phát ra âm; miệng, lưỡi chỉ điều chỉnh âm.'],
['Ở đàn ghi-ta, bộ phận dao động phát ra âm là',
 'Dây đàn', 'Cần đàn', 'Ngón tay người gảy', 'Dây đeo đàn',
 'Gảy dây → dây dao động → phát âm; hộp đàn làm âm to hơn.'],
['Khi thổi sáo, âm phát ra do',
 'Cột không khí trong ống sáo dao động', 'Ống sáo đang chuyển động', 'Ngón tay dao động', 'Môi người thổi dao động rất mạnh',
 'Cột không khí bên trong ống là nguồn âm của các nhạc cụ hơi.'],
['Âm thanh có thể truyền được trong các môi trường',
 'Rắn, lỏng, khí', 'Chỉ trong không khí', 'Chỉ trong chất rắn', 'Rắn, lỏng, khí và chân không',
 'Âm cần môi trường vật chất để truyền; không truyền được trong chân không.'],
['Hai nhà du hành đứng cạnh nhau trên Mặt Trăng không nói chuyện trực tiếp được vì',
 'Trên Mặt Trăng không có không khí để truyền âm', 'Trên Mặt Trăng quá lạnh', 'Mũ bảo hiểm quá dày', 'Trên Mặt Trăng trọng lực nhỏ',
 'Mặt Trăng gần như chân không → âm không truyền được; họ phải dùng sóng vô tuyến.'],
['Sắp xếp tốc độ truyền âm trong các môi trường theo thứ tự giảm dần',
 'Chất rắn > chất lỏng > chất khí', 'Chất khí > chất lỏng > chất rắn', 'Chất lỏng > chất rắn > chất khí', 'Chất khí > chất rắn > chất lỏng',
 'Ví dụ: thép ≈ 6100 m/s, nước ≈ 1500 m/s, không khí ≈ 340 m/s.'],
['Tốc độ truyền âm trong không khí ở điều kiện thường xấp xỉ',
 '340 m/s', '1500 m/s', '6100 m/s', '300 000 km/s',
 'Âm trong không khí khoảng 340 m/s (ở 20°C khoảng 343 m/s).'],
['Tốc độ truyền âm trong nước xấp xỉ',
 '1500 m/s', '340 m/s', '6100 m/s', '150 m/s',
 'Trong nước, âm truyền nhanh hơn trong không khí khoảng 4 lần.'],
['Tốc độ truyền âm trong thép xấp xỉ',
 '6100 m/s', '1500 m/s', '340 m/s', '610 m/s',
 'Trong chất rắn như thép, âm truyền nhanh nhất.'],
['Ngày xưa, người ta áp tai xuống đường ray để biết tàu đang tới từ xa vì',
 'Âm truyền trong thép nhanh và ít bị yếu đi hơn trong không khí', 'Đường ray phát ra ánh sáng', 'Tàu chỉ phát âm qua đường ray', 'Không khí không truyền được âm',
 'Ray thép truyền âm tốt nên nghe được tiếng tàu trước khi nghe qua không khí.'],
['Cá trong ao nghe được tiếng bước chân người trên bờ chứng tỏ',
 'Âm truyền được qua chất rắn (đất) và chất lỏng (nước)', 'Cá có tai rất to', 'Âm chỉ truyền trong nước', 'Âm không truyền trong không khí',
 'Âm từ bước chân truyền qua đất → nước → tới cá.'],
['Trong thí nghiệm đặt chuông điện trong bình thuỷ tinh rồi hút dần không khí ra, ta thấy',
 'Tiếng chuông nhỏ dần rồi gần như không nghe thấy dù chuông vẫn rung', 'Tiếng chuông to dần', 'Chuông ngừng rung', 'Tiếng chuông không thay đổi',
 'Càng ít không khí, âm càng khó truyền → chứng tỏ âm cần môi trường vật chất.'],
['Khi âm truyền từ không khí vào nước, tốc độ truyền âm',
 'Tăng lên', 'Giảm đi', 'Không thay đổi', 'Bằng 0',
 'Tốc độ âm trong nước (≈1500 m/s) lớn hơn trong không khí (≈340 m/s).'],
['Độ to của âm phụ thuộc vào',
 'Biên độ dao động của nguồn âm', 'Tần số dao động', 'Khối lượng của nguồn âm', 'Màu sắc của nguồn âm',
 'Biên độ càng lớn thì âm càng to.'],
['Biên độ dao động là',
 'Độ lệch lớn nhất của vật so với vị trí cân bằng', 'Số dao động trong 1 giây', 'Thời gian thực hiện 1 dao động', 'Quãng đường vật đi trong 1 giây',
 'Ví dụ: gảy dây đàn càng mạnh, dây lệch khỏi vị trí cân bằng càng nhiều → biên độ lớn.'],
['Đơn vị đo độ to của âm là',
 'Đêxiben (dB)', 'Héc (Hz)', 'Mét trên giây (m/s)', 'Niutơn (N)',
 'Độ to đo bằng dB; tần số mới đo bằng Hz.'],
['Độ cao của âm (âm bổng hay trầm) phụ thuộc vào',
 'Tần số dao động của nguồn âm', 'Biên độ dao động', 'Khoảng cách tới nguồn', 'Kích thước của tai người nghe',
 'Tần số lớn → âm cao (bổng); tần số nhỏ → âm thấp (trầm).'],
['Tần số dao động là',
 'Số dao động vật thực hiện được trong 1 giây', 'Độ lệch lớn nhất khỏi vị trí cân bằng', 'Thời gian để đi hết một quãng đường', 'Số lần gõ trong 1 phút',
 'Đơn vị của tần số là héc (Hz): 1 Hz = 1 dao động/giây.'],
['Vật dao động càng nhanh (tần số càng lớn) thì âm phát ra',
 'Càng cao (bổng)', 'Càng trầm', 'Càng to', 'Càng nhỏ',
 'Độ cao của âm gắn với tần số, không phải độ to.'],
['Âm trầm là âm có',
 'Tần số nhỏ', 'Tần số lớn', 'Biên độ lớn', 'Biên độ nhỏ',
 'Trầm/bổng do tần số quyết định.'],
['Tai người bình thường nghe được âm có tần số trong khoảng',
 '20 Hz đến 20 000 Hz', '2 Hz đến 200 Hz', '200 Hz đến 2000 Hz', '20 000 Hz đến 200 000 Hz',
 'Dưới 20 Hz là hạ âm, trên 20 000 Hz là siêu âm — tai người không nghe được.'],
['Âm có tần số lớn hơn 20 000 Hz được gọi là',
 'Siêu âm', 'Hạ âm', 'Âm trầm', 'Tạp âm',
 'Siêu âm được dơi, cá heo sử dụng và ứng dụng trong y học.'],
['Âm có tần số nhỏ hơn 20 Hz gọi là',
 'Hạ âm', 'Siêu âm', 'Âm bổng', 'Âm to',
 'Hạ âm tai người không nghe được; một số loài như voi có thể cảm nhận.'],
['Loài vật nào sau đây phát và nghe được siêu âm để định hướng?',
 'Dơi', 'Chó', 'Gà', 'Voi',
 'Dơi phát siêu âm, thu âm phản xạ để định vị con mồi trong đêm.'],
['Gảy dây đàn mạnh hơn (vẫn cùng dây, cùng độ căng) thì âm phát ra',
 'To hơn nhưng độ cao không đổi', 'Cao hơn nhưng độ to không đổi', 'Vừa to hơn vừa cao hơn', 'Không thay đổi',
 'Gảy mạnh → biên độ lớn → to hơn; tần số của dây không đổi nên độ cao giữ nguyên.'],
['Vặn khoá đàn để dây căng hơn thì âm phát ra khi gảy sẽ',
 'Cao hơn', 'Trầm hơn', 'To hơn', 'Nhỏ hơn',
 'Dây căng hơn dao động nhanh hơn → tần số tăng → âm cao hơn.'],
['Khi bấm phím đàn ghi-ta để làm phần dây dao động ngắn hơn, âm phát ra',
 'Cao hơn', 'Trầm hơn', 'To hơn', 'Không thay đổi',
 'Dây ngắn dao động nhanh hơn → tần số cao hơn.'],
['Trong bộ dây đàn ghi-ta, dây to và nặng nhất phát ra âm',
 'Trầm nhất', 'Cao nhất', 'To nhất', 'Nhỏ nhất',
 'Dây nặng dao động chậm → tần số thấp → âm trầm.'],
['Khi thổi sáo, bịt thêm các lỗ trên ống sáo làm cột không khí dao động dài hơn nên âm',
 'Trầm hơn', 'Cao hơn', 'To hơn', 'Nhỏ hơn',
 'Cột không khí dài dao động chậm → tần số nhỏ → âm trầm.'],
['Xếp các chai thuỷ tinh giống nhau chứa lượng nước khác nhau rồi <b>gõ</b> vào thân chai. Chai nào phát ra âm trầm nhất?',
 'Chai chứa nhiều nước nhất', 'Chai chứa ít nước nhất', 'Chai rỗng', 'Các chai phát âm giống nhau',
 'Khi gõ, chai và nước cùng dao động; càng nhiều nước dao động càng chậm → âm trầm.'],
['Xếp các chai giống nhau chứa lượng nước khác nhau rồi <b>thổi</b> ngang miệng chai. Chai nào phát ra âm cao nhất?',
 'Chai chứa nhiều nước nhất (cột không khí ngắn nhất)', 'Chai rỗng', 'Chai chứa ít nước nhất', 'Các chai phát âm giống nhau',
 'Khi thổi, cột không khí trong chai dao động; cột ngắn dao động nhanh → âm cao.'],
['Trên màn dao động kí, so với âm thứ nhất, âm thứ hai có đỉnh sóng cao hơn nhưng số đỉnh trên cùng khoảng thời gian bằng nhau. Kết luận',
 'Âm thứ hai to hơn, cùng độ cao', 'Âm thứ hai cao hơn, cùng độ to', 'Âm thứ hai trầm hơn', 'Hai âm hoàn toàn giống nhau',
 'Đỉnh cao → biên độ lớn → to hơn; cùng số đỉnh → cùng tần số.'],
['Trên màn dao động kí, âm B có các đỉnh sóng sít nhau hơn âm A (cùng độ cao đỉnh). Kết luận',
 'Âm B cao hơn âm A, cùng độ to', 'Âm B to hơn âm A', 'Âm B trầm hơn âm A', 'Âm B nhỏ hơn âm A',
 'Đỉnh sít → nhiều dao động hơn trong cùng thời gian → tần số lớn → cao hơn.'],
['Phản xạ âm là hiện tượng',
 'Âm dội lại khi gặp mặt chắn', 'Âm bị hấp thụ hoàn toàn', 'Âm truyền xuyên qua vật', 'Âm bị tắt dần trong không khí',
 'Âm gặp vật cản (tường, vách núi…) sẽ bị phản xạ trở lại.'],
['Vật nào sau đây phản xạ âm tốt?',
 'Tấm kim loại phẳng, nhẵn', 'Miếng xốp', 'Tấm vải nhung dày', 'Bức tường sần sùi phủ rêu',
 'Vật cứng, phẳng, nhẵn phản xạ âm tốt; vật mềm, xốp, gồ ghề phản xạ kém.'],
['Vật nào sau đây phản xạ âm kém (hấp thụ âm tốt)?',
 'Rèm cửa bằng vải dày', 'Mặt gương', 'Mặt đá hoa cương nhẵn', 'Tấm kính phẳng',
 'Vật mềm, xốp như rèm, thảm hấp thụ phần lớn âm.'],
['Tiếng vang là',
 'Âm phản xạ nghe được cách âm truyền trực tiếp ít nhất 1/15 giây', 'Mọi âm phản xạ', 'Âm phát ra từ nguồn thứ hai', 'Âm to hơn âm bình thường',
 'Tai chỉ phân biệt hai âm cách nhau từ 1/15 s trở lên; khi đó âm phản xạ nghe rõ thành tiếng vang.'],
['Trong phòng học nhỏ, ta không nghe thấy tiếng vang vì',
 'Âm phản xạ đến tai gần như cùng lúc với âm trực tiếp nên tai không phân biệt được', 'Tường lớp học không phản xạ âm', 'Không khí trong phòng không truyền âm', 'Âm bị hấp thụ hết',
 'Khoảng cách nhỏ → thời gian chênh lệch nhỏ hơn 1/15 s; âm phản xạ chỉ làm âm nghe to hơn.'],
['Để nghe được tiếng vang của tiếng nói mình trong không khí, người nói phải cách vật phản xạ tối thiểu khoảng',
 '11,3 m', '340 m', '22,6 m', '1,5 m',
 'Âm đi và về 2d trong ít nhất 1/15 s: 2d = 340/15 ≈ 22,7 m → d ≈ 11,3 m.'],
['Vì sao trong hang động lớn ta nghe được tiếng vang?',
 'Vách hang xa, cứng, phản xạ âm và âm phản xạ tới tai chậm hơn âm trực tiếp trên 1/15 s', 'Trong hang không khí lạnh nên truyền âm chậm', 'Hang có nhiều dơi', 'Vách hang phát ra âm',
 'Điều kiện tiếng vang: khoảng cách đủ lớn và vật phản xạ tốt.'],
['Tường của phòng hoà nhạc, rạp hát thường làm sần sùi hoặc treo rèm nhung để',
 'Giảm âm phản xạ, tránh tiếng vang làm âm bị rối', 'Trang trí cho đẹp', 'Tăng âm phản xạ cho to hơn', 'Giảm nhiệt độ phòng',
 'Bề mặt sần, mềm hấp thụ âm nên âm nghe rõ, không bị lẫn với âm phản xạ.'],
['Sóng siêu âm dùng để đo độ sâu đáy biển dựa trên nguyên tắc',
 'Đo thời gian từ khi phát siêu âm đến khi nhận được âm phản xạ từ đáy', 'Đo độ to của âm phản xạ', 'Đo tần số âm phản xạ', 'Đo nhiệt độ nước biển',
 'Độ sâu = (tốc độ âm trong nước × thời gian)/2.'],
['Ô nhiễm tiếng ồn xảy ra khi',
 'Tiếng ồn to, kéo dài, ảnh hưởng xấu đến sức khoẻ và hoạt động của con người', 'Có bất kì âm thanh nào', 'Có tiếng nhạc du dương', 'Trời có sấm sét',
 'Ba dấu hiệu: to, kéo dài, gây ảnh hưởng xấu.'],
['Trường hợp nào sau đây là ô nhiễm tiếng ồn?',
 'Tiếng máy khoan bê tông hoạt động liên tục cả ngày cạnh lớp học', 'Tiếng sấm trong cơn mưa', 'Tiếng cô giáo giảng bài', 'Tiếng chim hót buổi sáng',
 'Máy khoan to, kéo dài, cản trở việc học → ô nhiễm tiếng ồn.'],
['Trồng nhiều cây xanh quanh trường học, bệnh viện có tác dụng chống ô nhiễm tiếng ồn theo cách',
 'Phân tán và hấp thụ âm trên đường truyền', 'Làm giảm âm tại nguồn', 'Làm âm truyền nhanh hơn', 'Không có tác dụng gì với tiếng ồn',
 'Tán lá làm âm bị phản xạ tán loạn và hấp thụ nên tiếng ồn giảm.'],
['Biện pháp nào sau đây là <b>giảm tiếng ồn tại nguồn</b>?',
 'Lắp ống giảm thanh (bô) cho xe máy', 'Xây tường bao quanh nhà', 'Treo rèm dày trong phòng', 'Đeo chụp tai chống ồn',
 'Ống giảm thanh làm tiếng động cơ nhỏ đi ngay từ nơi phát ra.'],
['Biện pháp nào sau đây là <b>ngăn chặn đường truyền âm</b>?',
 'Đóng kín cửa, lắp cửa kính hai lớp', 'Tắt bớt loa đài', 'Nhắc nhở mọi người nói nhỏ', 'Yêu cầu nhà máy đổi máy móc',
 'Cửa kín, kính hai lớp có lớp không khí ở giữa làm âm khó truyền vào phòng.'],
['Bảng "Cấm bóp còi" gần bệnh viện nhằm',
 'Giảm tiếng ồn ngay tại nguồn phát', 'Ngăn đường truyền âm', 'Hấp thụ âm', 'Tăng tốc độ giao thông',
 'Không bóp còi → không phát ra tiếng ồn.'],
['Tiếng ồn quá mức kéo dài có thể gây',
 'Giảm thính lực, mất ngủ, căng thẳng', 'Tăng chiều cao', 'Cải thiện thị lực', 'Tăng khả năng tập trung',
 'Tác hại của ô nhiễm tiếng ồn tới sức khoẻ.'],
['Nghe nhạc bằng tai nghe với âm lượng lớn trong thời gian dài có thể',
 'Làm tổn thương tai, giảm khả năng nghe', 'Làm tai nghe tốt hơn', 'Không ảnh hưởng gì', 'Làm tăng tần số nghe được',
 'Âm to kéo dài làm hỏng tế bào thính giác.'],
['Phát biểu nào sau đây <b>đúng</b>?',
 'Âm không truyền được trong chân không', 'Âm truyền trong không khí nhanh hơn trong nước', 'Âm to là âm có tần số lớn', 'Mọi âm phản xạ đều là tiếng vang',
 'Âm cần môi trường vật chất; các câu còn lại đều sai.'],
['Trong thí nghiệm hút không khí khỏi bình có chuông điện, ta vẫn thấy búa chuông gõ nhưng gần như không nghe tiếng. Điều đó chứng tỏ',
 'Nguồn âm vẫn dao động nhưng thiếu môi trường truyền âm', 'Chuông đã hỏng', 'Âm bị bình thuỷ tinh hút hết', 'Chuông chỉ rung mà không phát âm',
 'Chuông vẫn là nguồn âm, nhưng âm không truyền qua chân không đến tai.'],
['Ta thường thấy chớp trước rồi mới nghe tiếng sấm vì',
 'Ánh sáng truyền nhanh hơn âm thanh rất nhiều', 'Sấm xảy ra sau chớp', 'Mắt nhạy hơn tai', 'Âm thanh không truyền trong mưa',
 'Ánh sáng đi 300 000 km/s, âm chỉ 340 m/s.'],
['Thấy chớp rồi 3 giây sau nghe sấm. Nơi sét đánh cách ta khoảng',
 '1020 m', '510 m', '113 m', '3000 m',
 's = 340 × 3 = 1020 m (ánh sáng đến gần như tức thời nên không chia đôi).'],
['Trò chơi "điện thoại dây" với hai cốc giấy nối bằng sợi dây căng cho thấy',
 'Âm truyền được qua chất rắn (sợi dây)', 'Âm chỉ truyền qua không khí', 'Cốc giấy phát ra âm', 'Âm truyền qua chân không',
 'Đáy cốc dao động → sợi dây truyền dao động → đáy cốc kia dao động → nghe được.'],
['Đặt ngọn nến đang cháy trước loa đang phát âm to, ngọn lửa lay động. Hiện tượng này chứng tỏ',
 'Màng loa dao động làm không khí dao động và truyền đi', 'Loa toả nhiệt', 'Loa thổi gió', 'Ngọn nến phát ra âm',
 'Không khí dao động theo màng loa, đẩy ngọn lửa qua lại.'],
['Đặt hai trống gần nhau, trên mặt trống thứ hai rải vài hạt gạo. Gõ trống thứ nhất, hạt gạo nảy lên. Điều này chứng tỏ',
 'Âm truyền qua không khí làm mặt trống thứ hai dao động', 'Gạo bị gió thổi', 'Trống thứ hai tự phát âm', 'Dùi trống chạm vào trống thứ hai',
 'Dao động của mặt trống 1 → không khí → mặt trống 2 dao động → gạo nảy.'],
['Âm có tần số 1000 Hz so với âm 500 Hz thì',
 'Cao hơn', 'Trầm hơn', 'To hơn', 'Nhỏ hơn',
 'Tần số lớn hơn → cao hơn (độ to không được nói tới).'],
['Con lắc thực hiện 60 dao động trong 2 phút. Tần số của nó là',
 '0,5 Hz', '30 Hz', '120 Hz', '2 Hz',
 'f = 60/120 s = 0,5 Hz → là hạ âm, tai không nghe được.'],
['Cánh muỗi dao động khoảng 600 lần mỗi giây. Tần số này',
 'Là 600 Hz, tai người nghe được (tiếng vo ve)', 'Là 600 Hz, tai người không nghe được', 'Là 60 Hz', 'Là 6000 Hz',
 '600 Hz nằm trong khoảng 20 – 20 000 Hz.'],
['Đàn bầu chỉ có một dây nhưng chơi được nhiều nốt vì người chơi',
 'Thay đổi độ căng của dây bằng cần đàn và điểm chạm tay trên dây', 'Thay dây liên tục', 'Gảy mạnh nhẹ khác nhau', 'Đổi loại que gảy',
 'Độ căng và chiều dài phần dây dao động thay đổi → tần số thay đổi.'],
['Gõ âm thoa rồi nhúng nhanh vào cốc nước, nước bắn tung. Thí nghiệm này chứng tỏ',
 'Âm thoa đang dao động khi phát âm', 'Âm thoa nóng lên', 'Nước phát ra âm', 'Âm thoa hút nước',
 'Dù mắt không thấy rõ, âm thoa phát âm luôn dao động.'],
['Kẹp một đầu thước thép vào mép bàn, gảy đầu kia. Khi phần thước nhô ra dài quá, ta thấy thước rung nhưng không nghe âm vì',
 'Tần số dao động quá nhỏ (dưới 20 Hz)', 'Biên độ quá lớn', 'Thước không dao động', 'Âm bị bàn hấp thụ',
 'Thước dài dao động chậm → hạ âm → tai không nghe được.'],
['Càng xa nguồn âm ta nghe càng nhỏ vì',
 'Năng lượng âm lan ra vùng rộng hơn, biên độ dao động không khí tại tai giảm', 'Tần số âm giảm', 'Âm đổi hướng', 'Không khí ở xa không truyền âm',
 'Độ to giảm theo khoảng cách do biên độ giảm, tần số không đổi.'],
['Ứng dụng nào sau đây <b>không</b> dựa trên phản xạ âm?',
 'Đèn pin chiếu sáng trong đêm', 'Máy siêu âm trong y học', 'Sonar đo độ sâu biển', 'Dơi bắt mồi trong đêm',
 'Đèn pin liên quan đến ánh sáng, không phải phản xạ âm.'],
['Tần số dao động của một vật giảm thì âm nó phát ra',
 'Trầm hơn', 'Cao hơn', 'To hơn', 'Nhỏ hơn',
 'Tần số nhỏ → âm thấp/trầm.'],
['Khi gõ vào các thanh của đàn xylophone, thanh ngắn phát ra âm',
 'Cao hơn thanh dài', 'Trầm hơn thanh dài', 'To hơn thanh dài', 'Nhỏ hơn thanh dài',
 'Thanh ngắn dao động nhanh → tần số lớn → cao hơn.'],
['Micro có nhiệm vụ',
 'Biến dao động âm thành tín hiệu điện', 'Biến tín hiệu điện thành âm', 'Phản xạ âm', 'Hấp thụ âm',
 'Màng micro dao động theo âm và tạo ra tín hiệu điện; loa làm ngược lại.'],
['Bấm còi xe trong hầm đường bộ nghe to và vang hơn ngoài đường vì',
 'Vách hầm cứng phản xạ âm nhiều lần, âm phản xạ cộng thêm vào âm trực tiếp', 'Trong hầm không khí đặc hơn', 'Còi xe kêu to hơn trong hầm', 'Trong hầm tốc độ âm lớn hơn',
 'Không gian kín có nhiều mặt phản xạ tốt.'],
['Người thợ sửa máy áp một đầu thanh gỗ vào động cơ, tai áp đầu kia để nghe tiếng bên trong máy vì',
 'Chất rắn truyền âm tốt hơn không khí', 'Gỗ khuếch đại âm', 'Không khí không truyền âm', 'Thanh gỗ phát âm',
 'Âm truyền trong chất rắn nhanh và ít suy giảm.'],
['Phát biểu nào sau đây <b>sai</b>?',
 'Tốc độ truyền âm trong không khí lớn hơn trong nước', 'Âm truyền được trong chất rắn', 'Âm không truyền trong chân không', 'Tốc độ âm trong thép lớn hơn trong nước',
 'Thực tế âm trong nước (1500 m/s) nhanh hơn trong không khí (340 m/s).'],
['Hai âm có cùng độ cao nhưng khác độ to thì chúng có',
 'Cùng tần số, khác biên độ', 'Cùng biên độ, khác tần số', 'Khác cả tần số và biên độ', 'Cùng cả tần số và biên độ',
 'Độ cao ↔ tần số; độ to ↔ biên độ.'],
['Nhân viên làm việc gần đường băng sân bay phải',
 'Đeo chụp tai chống ồn để bảo vệ tai', 'Mở to nhạc để át tiếng máy bay', 'Đứng gần máy bay hơn', 'Không cần bảo hộ gì',
 'Tiếng động cơ phản lực rất to (trên 120 dB), gây hại tai nếu không bảo hộ.'],
['Cửa kính hai lớp có lớp không khí ở giữa cách âm tốt vì',
 'Âm phải truyền qua nhiều lớp môi trường khác nhau, bị phản xạ và yếu đi', 'Kính hấp thụ hoàn toàn âm', 'Không khí giữa hai lớp là chân không', 'Kính phát ra âm ngược chiều',
 'Mỗi lần đổi môi trường (kính – khí – kính) một phần âm bị phản xạ ngược.'],
['Dao động kí (máy hiện sóng) cho biết những đặc điểm nào của âm?',
 'Biên độ và tần số dao động', 'Chỉ độ to', 'Chỉ tốc độ truyền âm', 'Màu của âm',
 'Trên màn ta đọc được chiều cao đỉnh (biên độ) và số dao động trong một khoảng thời gian (tần số).'],
['Một vật dao động 40 lần trong 10 giây. Tần số dao động là',
 '4 Hz', '400 Hz', '0,25 Hz', '40 Hz',
 'f = 40/10 = 4 Hz (là hạ âm).'],
['Hát trong phòng tắm lát gạch men nghe "hay" và vang hơn vì',
 'Gạch men cứng, nhẵn phản xạ âm tốt, âm phản xạ hoà cùng âm trực tiếp', 'Không khí ẩm truyền âm nhanh hơn', 'Phòng tắm có nước', 'Giọng hát tự tốt lên',
 'Bề mặt cứng, nhẵn phản xạ tốt tạo cảm giác vang.'],
['Khi tuyết rơi dày, không gian trở nên rất yên tĩnh vì',
 'Tuyết xốp, hấp thụ âm tốt', 'Trời lạnh làm âm không truyền được', 'Mọi vật ngừng dao động', 'Tuyết phản xạ âm lên trời',
 'Lớp tuyết mềm, xốp phản xạ âm kém, hút mất phần lớn âm.'],
['Chụp siêu âm thai trong y học dựa trên hiện tượng',
 'Phản xạ của siêu âm tại các mô trong cơ thể', 'Hấp thụ ánh sáng', 'Truyền điện', 'Dao động của dây thanh',
 'Máy phát siêu âm, thu âm phản xạ để dựng hình ảnh.'],
['Giọng nam trưởng thành thường trầm hơn giọng nữ vì',
 'Dây thanh của nam dài và dày hơn nên dao động với tần số nhỏ hơn', 'Nam nói to hơn', 'Nam có phổi lớn hơn', 'Nam nói chậm hơn',
 'Dây thanh dài, dày → tần số thấp → âm trầm.'],
['Cặp đại lượng nào sau đây gắn với nhau <b>đúng</b>?',
 'Độ to – biên độ – đêxiben; độ cao – tần số – héc', 'Độ to – tần số – héc', 'Độ cao – biên độ – đêxiben', 'Độ to – tốc độ – m/s',
 'Độ to ↔ biên độ (dB); độ cao ↔ tần số (Hz).'],
['Cho đồng hồ báo thức đang reo vào túi nhựa kín rồi nhúng vào chậu nước, ta',
 'Vẫn nghe được tiếng reo vì âm truyền qua nước và túi', 'Không nghe được vì nước không truyền âm', 'Không nghe được vì túi nhựa chặn hết âm', 'Nghe to hơn nhiều lần',
 'Âm truyền qua chất rắn (túi) và chất lỏng (nước) rồi ra không khí.'],
['Muốn một chiếc chuông đang kêu tắt tiếng ngay lập tức, cách hiệu quả nhất là',
 'Dùng tay giữ chặt chuông để nó ngừng dao động', 'Bịt tai lại', 'Thổi vào chuông', 'Đứng ra xa',
 'Nguồn âm ngừng dao động thì âm dừng ngay.'],
['Đứng giữa sân trường rộng hô to, ta nghe được tiếng vang từ dãy nhà đối diện khi dãy nhà cách ta',
 'Từ khoảng 11,3 m trở lên', 'Dưới 5 m', 'Dưới 11,3 m', 'Bất kì khoảng cách nào',
 'Cần 2d/340 ≥ 1/15 s → d ≥ 11,3 m.'],
['Loa phát ra âm to hơn khi',
 'Màng loa dao động với biên độ lớn hơn', 'Màng loa dao động nhanh hơn', 'Loa được đặt xa hơn', 'Loa đặt trong chân không',
 'Độ to gắn với biên độ.'],
['Ống nghe của bác sĩ hoạt động dựa trên',
 'Truyền âm từ ngực bệnh nhân qua ống dẫn (chất rắn, khí) tới tai, hạn chế âm tản ra', 'Khuếch đại điện tử', 'Phản xạ ánh sáng', 'Siêu âm',
 'Âm được dẫn trong ống kín nên tới tai rõ hơn.'],
['Trẻ nhỏ nghe được âm tần số cao tới 20 000 Hz, người cao tuổi thường chỉ nghe tới khoảng 12 000 Hz. Điều này cho thấy',
 'Khả năng nghe âm cao giảm dần theo tuổi', 'Người già nghe tốt hơn trẻ nhỏ', 'Âm cao không tồn tại với người già', 'Tần số âm thay đổi theo tuổi người nghe',
 'Ngưỡng nghe tần số cao giảm khi tuổi tăng.'],
['Một âm có tần số 50 Hz. Trong 1 phút nguồn âm thực hiện',
 '3000 dao động', '50 dao động', '300 dao động', '0,83 dao động',
 '50 × 60 = 3000 dao động.'],
['Một cái giếng sâu 34 m. Thời gian để âm thanh truyền từ mặt nước dưới giếng lên tới miệng giếng là',
 '0,1 s', '0,2 s', '1 s', '10 s',
 't = s/v = 34/340 = 0,1 s.'],
['Chọn câu <b>sai</b> về tiếng vang.',
 'Trong phòng nhỏ ta luôn nghe được tiếng vang rõ ràng', 'Tiếng vang là âm phản xạ nghe được tách biệt với âm trực tiếp', 'Vách núi xa có thể tạo tiếng vang', 'Phòng nhỏ có âm phản xạ nhưng không tạo tiếng vang',
 'Phòng nhỏ: âm phản xạ tới tai gần như cùng lúc → không tách thành tiếng vang.'],
['Một cái trống và một cái sáo cùng phát ra âm to bằng nhau nhưng tiếng sáo cao hơn. Vậy so với trống, nguồn âm của sáo có',
 'Tần số lớn hơn, biên độ (tại tai) tương đương', 'Biên độ lớn hơn', 'Tần số nhỏ hơn', 'Tốc độ truyền âm lớn hơn',
 'Cao hơn → tần số lớn hơn; cùng độ to → biên độ tương đương.'],
['Trong thí nghiệm đo tốc độ truyền âm ngoài trời, hai bạn cách nhau 340 m; một bạn gõ trống, bạn kia bấm đồng hồ khi thấy dùi chạm trống và dừng khi nghe tiếng. Đồng hồ chỉ khoảng',
 '1 s', '2 s', '0,5 s', '0,1 s',
 't = 340/340 = 1 s (thời gian ánh sáng truyền coi như bằng 0).'],
['Rèm cửa, thảm trải sàn, tấm xốp tiêu âm trong phòng thu âm có tác dụng chung là',
 'Hấp thụ âm, giảm phản xạ', 'Tăng tần số âm', 'Làm âm truyền nhanh hơn', 'Phát ra âm',
 'Vật mềm, xốp phản xạ âm kém.'],
['Nói "âm thanh của tiếng đàn to 60 dB" thì 60 dB là số đo của',
 'Độ to', 'Độ cao', 'Tần số', 'Tốc độ truyền âm',
 'dB là đơn vị độ to.'],
['Nghe nhạc ở mức 85 dB liên tục nhiều giờ mỗi ngày là',
 'Nguy hiểm cho tai về lâu dài', 'Hoàn toàn an toàn', 'Tốt cho thính giác', 'Không gây hậu quả nào',
 'Từ 85 dB trở lên, tiếp xúc lâu gây tổn thương thính giác.'],
['Trong các vật sau, vật nào là nguồn âm khi đang hoạt động?',
 'Chiếc loa đang phát nhạc', 'Chiếc loa tắt', 'Tờ giấy nằm trên bàn', 'Chiếc gương treo tường',
 'Màng loa dao động phát ra âm.'],
['Khi nhiệt độ không khí tăng lên, tốc độ truyền âm trong không khí',
 'Tăng lên một ít', 'Giảm mạnh', 'Không đổi tuyệt đối', 'Bằng 0',
 'Ở 0°C khoảng 331 m/s, ở 20°C khoảng 343 m/s: tăng khoảng 0,6 m/s mỗi độ.'],
['Đơn vị héc (Hz) được đặt theo tên nhà vật lí',
 'Heinrich Hertz', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei',
 'Hertz là nhà vật lí người Đức, người phát hiện sóng điện từ.'],
];
