/* vatli7-bank-b.mjs — ngân hàng câu VIẾT TAY cho Vật lí 7 (KHTN 7, KNTT)
   Phần B: chương ÁNH SÁNG và chương TỪ.
   Mỗi câu: [text, đáp án ĐÚNG, nhiễu 1, nhiễu 2, nhiễu 3, giải thích] */

export const AS = [
['Vật nào sau đây là nguồn sáng?',
 'Ngọn nến đang cháy', 'Mặt Trăng', 'Tấm gương', 'Quyển sách đặt dưới đèn',
 'Nguồn sáng là vật tự phát ra ánh sáng. Mặt Trăng, gương, sách chỉ hắt lại ánh sáng.'],
['Ánh sáng là một dạng',
 'Năng lượng', 'Vật chất rắn', 'Chất lỏng', 'Âm thanh',
 'Ánh sáng mang năng lượng: làm nóng vật, tạo điện trong pin mặt trời.'],
['Bằng chứng nào cho thấy ánh sáng mang năng lượng?',
 'Pin mặt trời tạo ra điện khi được chiếu sáng', 'Ánh sáng truyền theo đường thẳng', 'Ánh sáng phản xạ trên gương', 'Ánh sáng có nhiều màu',
 'Năng lượng ánh sáng chuyển hoá thành điện năng trong pin mặt trời, thành nhiệt khi làm vật nóng lên.'],
['Ta nhìn thấy một vật khi',
 'Có ánh sáng từ vật đó truyền vào mắt ta', 'Vật đó được chiếu sáng, dù ta quay lưng lại', 'Mắt ta phát ra ánh sáng chiếu vào vật', 'Vật đó ở gần mắt',
 'Điều kiện nhìn thấy vật: ánh sáng từ vật (tự phát hoặc hắt lại) đi vào mắt.'],
['Trong phòng tối hoàn toàn, ta không nhìn thấy các vật vì',
 'Không có ánh sáng từ vật truyền vào mắt', 'Mắt bị mỏi', 'Các vật biến mất', 'Không khí trong phòng cản ánh sáng',
 'Không có nguồn sáng → không có ánh sáng hắt lại từ vật → không nhìn thấy.'],
['Tia sáng được biểu diễn bằng',
 'Một đường thẳng có mũi tên chỉ hướng truyền', 'Một đường cong', 'Một đoạn thẳng không có mũi tên', 'Một hình tròn',
 'Quy ước: đường thẳng có mũi tên là đường truyền của ánh sáng.'],
['Chùm sáng song song là chùm gồm các tia sáng',
 'Không giao nhau trên đường truyền', 'Giao nhau tại một điểm', 'Loe rộng ra', 'Cong dần',
 'Chùm tia laser, chùm ánh sáng Mặt Trời tới Trái Đất được coi là song song.'],
['Chùm sáng hội tụ là chùm gồm các tia sáng',
 'Giao nhau tại một điểm trên đường truyền', 'Song song với nhau', 'Loe rộng ra', 'Vuông góc với nhau',
 'Các tia chụm lại một điểm — ví dụ chùm sáng qua kính lúp hội tụ tại một điểm nóng.'],
['Chùm sáng phát ra từ bóng đèn pin (bỏ pha) hoặc ngọn nến là chùm',
 'Phân kì', 'Hội tụ', 'Song song', 'Tròn',
 'Từ nguồn điểm, các tia loe rộng ra xa nhau — chùm phân kì.'],
['Trong môi trường trong suốt và đồng tính (như không khí sạch), ánh sáng truyền theo',
 'Đường thẳng', 'Đường cong', 'Đường gấp khúc', 'Đường tròn',
 'Định luật truyền thẳng của ánh sáng.'],
['Trong thí nghiệm, người ta thường dùng đèn laser để tạo tia sáng vì laser',
 'Cho chùm sáng rất hẹp và gần như song song', 'Có màu đỏ đẹp', 'Rất rẻ', 'Không mang năng lượng',
 'Chùm laser hẹp nên có thể coi như một tia sáng.'],
['Vùng tối là vùng',
 'Phía sau vật cản, không nhận được ánh sáng từ nguồn sáng', 'Nhận được một phần ánh sáng từ nguồn', 'Được chiếu sáng đầy đủ', 'Ở phía trước vật cản',
 'Vật cản không cho ánh sáng đi qua nên phía sau nó có vùng không có ánh sáng.'],
['Vùng nửa tối là vùng',
 'Chỉ nhận được ánh sáng từ một phần của nguồn sáng', 'Không nhận được ánh sáng nào', 'Nhận được toàn bộ ánh sáng từ nguồn', 'Phía trước vật cản',
 'Vùng nửa tối xuất hiện khi nguồn sáng rộng: một phần nguồn bị che, một phần không.'],
['Với nguồn sáng rất nhỏ (nguồn điểm), phía sau vật cản chỉ có',
 'Vùng tối, ranh giới rõ nét', 'Vùng nửa tối', 'Cả vùng tối và vùng nửa tối rộng', 'Không có vùng tối',
 'Nguồn điểm → chỉ có vùng tối; nguồn rộng → có thêm vùng nửa tối.'],
['Bóng của quả bóng trên tường khi chiếu bằng đèn ống dài có viền mờ vì',
 'Đèn ống là nguồn sáng rộng nên tạo vùng nửa tối quanh vùng tối', 'Quả bóng trong suốt', 'Tường phản xạ ánh sáng', 'Đèn ống quá yếu',
 'Nguồn sáng rộng → vùng nửa tối ở rìa làm bóng mờ dần.'],
['Hiện tượng nhật thực xảy ra khi',
 'Mặt Trăng nằm giữa Mặt Trời và Trái Đất, che ánh sáng Mặt Trời tới một vùng trên Trái Đất', 'Trái Đất nằm giữa Mặt Trời và Mặt Trăng', 'Mặt Trời nằm giữa Trái Đất và Mặt Trăng', 'Mặt Trăng bị mây che',
 'Nơi nằm trong vùng tối của Mặt Trăng thấy nhật thực toàn phần, trong vùng nửa tối thấy nhật thực một phần.'],
['Trong hiện tượng nhật thực, người đứng ở vùng nửa tối do Mặt Trăng tạo ra sẽ thấy',
 'Nhật thực một phần', 'Nhật thực toàn phần', 'Nguyệt thực', 'Không thấy gì khác thường',
 'Vùng nửa tối chỉ bị che một phần Mặt Trời.'],
['Hiện tượng nguyệt thực xảy ra khi',
 'Trái Đất nằm giữa Mặt Trời và Mặt Trăng, Mặt Trăng đi vào vùng tối của Trái Đất', 'Mặt Trăng nằm giữa Mặt Trời và Trái Đất', 'Mặt Trăng tắt sáng', 'Mặt Trời bị Mặt Trăng che',
 'Mặt Trăng không nhận được ánh sáng Mặt Trời vì bị Trái Đất che.'],
['Với nguồn sáng điểm cố định và màn cố định, đưa vật cản lại gần nguồn sáng thì vùng tối trên màn',
 'Lớn hơn', 'Nhỏ hơn', 'Không đổi', 'Biến mất',
 'Vật gần nguồn chắn được góc rộng hơn nên bóng trên màn lớn hơn.'],
['Với nguồn sáng điểm cố định, đưa vật cản lại gần màn thì vùng tối trên màn',
 'Nhỏ dần, tiến tới bằng kích thước vật', 'Lớn dần vô hạn', 'Không đổi', 'Chuyển thành vùng nửa tối',
 'Vật càng gần màn, bóng càng gần kích thước thật của vật.'],
['Nội dung định luật phản xạ ánh sáng: tia phản xạ nằm trong mặt phẳng chứa tia tới và pháp tuyến tại điểm tới; và',
 'Góc phản xạ bằng góc tới', 'Góc phản xạ lớn hơn góc tới', 'Góc phản xạ nhỏ hơn góc tới', 'Góc phản xạ bằng hai lần góc tới',
 'i′ = i.'],
['Pháp tuyến tại điểm tới là',
 'Đường thẳng vuông góc với mặt gương tại điểm tới', 'Đường thẳng song song với mặt gương', 'Tia tới kéo dài', 'Đường thẳng nằm trên mặt gương',
 'Góc tới và góc phản xạ đều đo so với pháp tuyến.'],
['Góc tới là góc tạo bởi',
 'Tia tới và pháp tuyến tại điểm tới', 'Tia tới và mặt gương', 'Tia tới và tia phản xạ', 'Tia phản xạ và mặt gương',
 'Định nghĩa góc tới.'],
['Chiếu tia sáng vuông góc với mặt gương phẳng. Khi đó',
 'Góc tới bằng 0°, tia phản xạ đi ngược lại trùng với tia tới', 'Góc tới bằng 90°', 'Không có tia phản xạ', 'Tia phản xạ đi dọc theo mặt gương',
 'Tia tới trùng pháp tuyến → i = 0° → i′ = 0°.'],
['Tia sáng tới hợp với mặt gương phẳng một góc 30°. Góc tới bằng',
 '60°', '30°', '90°', '120°',
 'Góc tới đo với pháp tuyến: 90° − 30° = 60°.'],
['Phản xạ khuếch tán xảy ra khi ánh sáng chiếu tới',
 'Bề mặt gồ ghề, các tia phản xạ đi theo nhiều hướng khác nhau', 'Bề mặt nhẵn bóng, các tia phản xạ song song', 'Chân không', 'Mặt gương phẳng',
 'Bề mặt không nhẵn làm các tia phản xạ tán ra mọi phía, nên ta nhìn được vật từ nhiều hướng.'],
['Ánh sáng chiếu tới mặt nhẵn bóng (gương, mặt nước lặng) cho các tia phản xạ theo một hướng xác định. Đó là hiện tượng',
 'Phản xạ (phản xạ gương)', 'Phản xạ khuếch tán', 'Hấp thụ ánh sáng', 'Truyền thẳng',
 'Phản xạ gương tạo ảnh rõ nét của vật.'],
['Ta nhìn thấy trang sách từ mọi hướng dưới ánh đèn nhờ hiện tượng',
 'Phản xạ khuếch tán trên mặt giấy', 'Phản xạ gương', 'Trang sách tự phát sáng', 'Ánh sáng xuyên qua giấy',
 'Mặt giấy gồ ghề (ở mức nhỏ) tán ánh sáng ra mọi hướng.'],
['Mặt hồ lặng cho ảnh rõ của hàng cây; khi gió làm mặt nước gợn sóng, ảnh bị vỡ, mờ vì',
 'Mặt nước gợn sóng gây phản xạ khuếch tán', 'Nước bị đục', 'Ánh sáng không tới được mặt nước', 'Hàng cây di chuyển',
 'Mặt phẳng nhẵn cho phản xạ gương; mặt gợn sóng cho phản xạ khuếch tán.'],
['Phát biểu nào <b>đúng</b> về phản xạ khuếch tán?',
 'Tại mỗi điểm nhỏ trên bề mặt gồ ghề, định luật phản xạ vẫn đúng', 'Định luật phản xạ không còn đúng', 'Ánh sáng bị hấp thụ hoàn toàn', 'Chỉ xảy ra với ánh sáng laser',
 'Vì bề mặt gồ ghề, pháp tuyến tại các điểm khác nhau hướng khác nhau nên tia phản xạ tán ra nhiều hướng, dù mỗi tia vẫn tuân theo định luật.'],
['Ảnh của một vật tạo bởi gương phẳng có tính chất',
 'Là ảnh ảo, lớn bằng vật, cách gương một khoảng bằng khoảng cách từ vật đến gương', 'Là ảnh thật, hứng được trên màn', 'Nhỏ hơn vật', 'Lớn hơn vật',
 'Ảnh và vật đối xứng nhau qua mặt gương.'],
['Ảnh ảo là ảnh',
 'Không hứng được trên màn chắn', 'Hứng được trên màn chắn', 'Luôn nhỏ hơn vật', 'Chỉ có với vật phát sáng',
 'Ảnh ảo được tạo bởi đường kéo dài của các tia phản xạ nên không hứng được trên màn.'],
['Một vật đặt cách gương phẳng 2 m. Khoảng cách từ ảnh của vật đến vật là',
 '4 m', '2 m', '1 m', '8 m',
 'Ảnh cách gương 2 m ở phía sau gương → ảnh cách vật 2 + 2 = 4 m.'],
['Chữ "AMBULANCE" (xe cứu thương) thường được viết ngược ở đầu xe để',
 'Người lái xe phía trước nhìn qua gương chiếu hậu thấy chữ đúng chiều', 'Trang trí cho lạ mắt', 'Người đi bộ đọc được từ xa', 'Tiết kiệm sơn',
 'Ảnh qua gương phẳng bị đảo trái – phải; viết ngược sẵn thì qua gương thấy đúng.'],
['Một người tiến lại gần gương phẳng thêm 1 m. Khi đó',
 'Ảnh tiến lại gần gương 1 m, ảnh và người gần nhau thêm 2 m', 'Ảnh lùi xa gương 1 m', 'Ảnh đứng yên', 'Ảnh tiến lại gần gương 2 m',
 'Ảnh luôn đối xứng với người qua gương.'],
['Cách dựng ảnh của điểm sáng S qua gương phẳng là',
 'Lấy S′ đối xứng với S qua mặt gương', 'Lấy S′ trùng S', 'Lấy S′ trên mặt gương', 'Lấy S′ cách gương gấp đôi S',
 'Dựa vào tính chất ảnh đối xứng với vật qua gương.'],
['Tia phản xạ trên gương phẳng của tia tới xuất phát từ điểm sáng S có đặc điểm',
 'Đường kéo dài của nó đi qua ảnh S′', 'Đi qua S', 'Song song với tia tới', 'Vuông góc với gương',
 'Mọi tia phản xạ đều có đường kéo dài hội tụ tại ảnh ảo S′.'],
['Một người cao 1,6 m đứng trước gương phẳng treo thẳng đứng. Chiều cao tối thiểu của gương để người đó thấy toàn thân mình là',
 '0,8 m', '1,6 m', '3,2 m', '0,4 m',
 'Gương chỉ cần cao bằng nửa người (bất kể đứng xa hay gần).'],
['Bạn Nam đứng trước gương phẳng và giơ tay phải lên. Ảnh của Nam trong gương',
 'Giơ tay bên trái (theo cách nhìn của ảnh)', 'Giơ tay bên phải', 'Giơ cả hai tay', 'Không giơ tay',
 'Ảnh qua gương đối xứng, đảo trái – phải.'],
['Đặt một vật giữa hai gương phẳng song song, đối diện nhau. Số ảnh của vật là',
 'Vô số', '2', '3', '4',
 'Ảnh của gương này lại là vật đối với gương kia → ảnh tạo mãi.'],
['Đặt một vật giữa hai gương phẳng vuông góc với nhau. Số ảnh của vật là',
 '3', '2', '4', 'Vô số',
 'Công thức: 360°/90° − 1 = 3 ảnh.'],
['Muốn biến tia sáng chiếu thẳng đứng từ trên xuống thành tia nằm ngang, phải đặt gương phẳng nghiêng với phương ngang một góc',
 '45°', '90°', '30°', '60°',
 'Tia tới và tia phản xạ vuông góc → góc tới 45° → gương nghiêng 45°.'],
['Kính tiềm vọng đơn giản gồm',
 'Hai gương phẳng đặt song song, cùng nghiêng 45° so với ống kính', 'Hai gương phẳng vuông góc nhau', 'Một gương phẳng nằm ngang', 'Hai gương cầu lồi',
 'Ánh sáng phản xạ hai lần và ra mắt theo hướng song song với hướng tới.'],
['Ứng dụng nào sau đây <b>không</b> phải của gương phẳng?',
 'Kính lúp phóng to chữ', 'Kính tiềm vọng', 'Gương soi', 'Gắn gương ở tiệm cắt tóc để thấy phía sau đầu',
 'Kính lúp là thấu kính, không phải gương phẳng.'],
['Chữ nào sau đây khi soi vào gương phẳng đặt thẳng đứng (phía bên phải chữ) vẫn nhìn giống hệt như chữ gốc?',
 'A', 'B', 'F', 'R',
 'Chữ A đối xứng qua trục thẳng đứng nên ảnh đảo trái – phải vẫn là A.'],
['Kích thước ảnh của một vật qua gương phẳng khi vật ở xa gương so với khi ở gần gương',
 'Bằng nhau (luôn bằng vật)', 'Nhỏ hơn', 'Lớn hơn', 'Bằng nửa',
 'Ảnh luôn bằng vật; ở xa ta thấy ảnh "nhỏ" chỉ vì góc nhìn nhỏ.'],
['Hộp tối có lỗ nhỏ (camera obscura) cho ảnh ngược của vật trên vách trong. Hiện tượng này được giải thích bằng',
 'Sự truyền thẳng của ánh sáng', 'Phản xạ ánh sáng', 'Phản xạ khuếch tán', 'Hấp thụ ánh sáng',
 'Tia sáng từ đỉnh vật đi thẳng qua lỗ xuống dưới, từ chân vật đi lên trên → ảnh ngược.'],
['Bóng của một cái cây dưới ánh nắng dài nhất vào lúc',
 'Sáng sớm hoặc chiều muộn', 'Giữa trưa', 'Bất kì lúc nào cũng dài như nhau', 'Đêm khuya',
 'Mặt Trời càng thấp, tia sáng càng xiên → bóng càng dài.'],
['Đồng hồ Mặt Trời xác định giờ dựa trên',
 'Vị trí và độ dài bóng của một thanh thẳng do ánh sáng truyền thẳng tạo ra', 'Sự phản xạ ánh sáng trên gương', 'Nhiệt độ của ánh nắng', 'Màu sắc của bầu trời',
 'Bóng đổi vị trí khi Mặt Trời di chuyển trên bầu trời.'],
['Chiếu một chùm sáng song song vào gương phẳng, chùm phản xạ là chùm',
 'Song song', 'Hội tụ', 'Phân kì', 'Bị tắt',
 'Các tia tới song song có cùng góc tới → cùng góc phản xạ → vẫn song song.'],
['Chiếu chùm sáng phân kì từ nguồn điểm vào gương phẳng, chùm phản xạ là chùm',
 'Phân kì, dường như xuất phát từ ảnh của nguồn', 'Hội tụ tại một điểm trước gương', 'Song song', 'Vuông góc với gương',
 'Đường kéo dài của các tia phản xạ đi qua ảnh ảo S′.'],
['Ta thấy Mặt Trăng sáng vào ban đêm vì',
 'Mặt Trăng hắt lại ánh sáng từ Mặt Trời', 'Mặt Trăng tự phát sáng', 'Mặt Trăng nóng đỏ', 'Ánh sáng của Trái Đất chiếu lên',
 'Mặt Trăng không phải nguồn sáng; nó phản xạ ánh sáng Mặt Trời.'],
['Xoay gương phẳng một góc 10° quanh trục đi qua điểm tới và vuông góc với tia tới, tia tới giữ cố định. Tia phản xạ quay một góc',
 '20°', '10°', '5°', '40°',
 'Gương quay α thì pháp tuyến quay α, góc tới và góc phản xạ cùng đổi α → tia phản xạ quay 2α.'],
['Góc giữa tia tới và tia phản xạ trên gương phẳng là 90°. Góc tới bằng',
 '45°', '90°', '30°', '60°',
 'Góc giữa hai tia = i + i′ = 2i = 90° → i = 45°.'],
['Chiếu tia laser sát mặt bàn có rắc bột phấn, ta thấy rõ "vệt sáng" của tia vì',
 'Các hạt bột phấn tán xạ (phản xạ khuếch tán) ánh sáng vào mắt', 'Không khí phát sáng', 'Laser tự sáng trong không khí sạch', 'Bàn phát sáng',
 'Trong không khí sạch ta không thấy đường đi của tia vì không có gì hắt ánh sáng về mắt.'],
['Đêm sương mù, ta thấy rõ "cột sáng" của đèn pha vì',
 'Các hạt nước nhỏ tán xạ ánh sáng đèn về mắt ta', 'Sương mù phát sáng', 'Đèn pha mạnh hơn khi trời lạnh', 'Ánh sáng truyền theo đường cong',
 'Tương tự bột phấn: có hạt nhỏ hắt ánh sáng thì thấy được đường truyền.'],
['Một mũi tên AB đặt song song với gương phẳng. Ảnh A′B′ của nó',
 'Song song với gương, cùng chiều và bằng AB', 'Vuông góc với gương', 'Ngược chiều với AB', 'Dài gấp đôi AB',
 'Mỗi điểm lấy đối xứng qua gương → ảnh song song, bằng vật, cùng chiều.'],
['Một mũi tên AB đặt vuông góc với gương phẳng (A gần gương). Ảnh A′B′',
 'Nằm trên đường thẳng AB kéo dài, ngược chiều với AB, bằng AB', 'Song song với gương', 'Cùng chiều với AB', 'Ngắn hơn AB',
 'A′ gần gương, B′ xa hơn ở phía sau gương → ảnh "quay đầu" so với vật.'],
['Dù ảnh ảo không hứng được trên màn, ta vẫn nhìn thấy nó vì',
 'Các tia phản xạ đi vào mắt có đường kéo dài qua ảnh nên mắt "cảm thấy" ánh sáng từ ảnh tới', 'Ảnh tự phát sáng', 'Mắt phát ra ánh sáng chiếu vào ảnh', 'Gương phát sáng',
 'Mắt nhận các tia phản xạ như thể chúng phát ra từ ảnh S′.'],
['Để nhìn thấy ảnh S′ của điểm sáng S qua gương phẳng, mắt phải đặt ở vị trí',
 'Đón được các tia phản xạ từ gương (trước gương)', 'Sau gương', 'Trên mặt gương', 'Bất kì đâu trong phòng',
 'Phải có tia phản xạ vào mắt thì mới thấy ảnh.'],
['Đứng dưới đèn đường vào ban đêm, bóng của bạn ngắn nhất khi bạn',
 'Đứng ngay dưới chân đèn', 'Đi ra xa đèn', 'Đứng cách đèn 10 m', 'Ngồi xuống xa đèn',
 'Ngay dưới đèn, ánh sáng chiếu gần thẳng xuống nên bóng rất ngắn.'],
['Ánh sáng từ Mặt Trời tới Trái Đất mất khoảng',
 '8 phút', '8 giây', '8 giờ', '8 ngày',
 'Khoảng cách 150 triệu km, tốc độ 300 000 km/s → ≈ 500 s ≈ 8 phút.'],
['Vật màu đen được nhìn thấy trong phòng sáng vì',
 'Nó hấp thụ hầu hết ánh sáng nên hiện lên tối hơn các vật sáng xung quanh', 'Nó phản xạ nhiều ánh sáng', 'Nó tự phát sáng', 'Mắt phát ra ánh sáng',
 'Ta nhận ra vật đen nhờ sự tương phản với nền sáng xung quanh.'],
['Nếu Mặt Trăng ở gần Trái Đất hơn hiện nay thì vùng tối do nó tạo ra trên Trái Đất khi nhật thực sẽ',
 'Lớn hơn', 'Nhỏ hơn', 'Không đổi', 'Không tồn tại',
 'Vùng tối phía sau Mặt Trăng có dạng hình nón thu nhỏ dần; Trái Đất ở gần Mặt Trăng hơn sẽ cắt hình nón ở chỗ rộng hơn nên vùng tối lớn hơn.'],
['Khi hai gương phẳng đặt vuông góc, tia sáng phản xạ lần lượt trên cả hai gương sẽ đi ra',
 'Song song và ngược chiều với tia tới', 'Vuông góc với tia tới', 'Trùng với tia tới', 'Theo hướng bất kì',
 'Tính chất nổi tiếng của cặp gương vuông góc — dùng trong gương phản quang.'],
['Trong bản vẽ quang học, ảnh ảo được vẽ bằng',
 'Nét đứt', 'Nét liền đậm', 'Mũi tên hai đầu', 'Đường lượn sóng',
 'Quy ước: ảnh ảo và đường kéo dài của tia sáng vẽ bằng nét đứt.'],
['Một vật cách gương phẳng 50 cm. Dịch gương ra xa vật thêm 10 cm thì ảnh',
 'Dịch xa vật thêm 20 cm', 'Dịch xa vật thêm 10 cm', 'Đứng yên', 'Lại gần vật 10 cm',
 'Khoảng cách ảnh – vật = 2 lần khoảng cách vật – gương: 2 × 60 − 2 × 50 = 20 cm.'],
['Ứng dụng của định luật truyền thẳng ánh sáng trong đời sống là',
 'Ngắm thẳng hàng khi xếp hàng, trồng cây, xây tường', 'Soi gương', 'Làm kính tiềm vọng', 'Chống ô nhiễm tiếng ồn',
 'Khi ba vật thẳng hàng, vật sau bị vật trước che khuất — nhờ ánh sáng đi thẳng.'],
['Vật nào sau đây phản xạ ánh sáng tốt nhất?',
 'Tấm kim loại đánh bóng', 'Tấm vải đen', 'Tấm bìa cứng', 'Bức tường xây thô',
 'Mặt nhẵn, sáng bóng phản xạ mạnh và theo một hướng.'],
['Ban đêm khi trời mưa, người lái xe khó nhìn vạch kẻ đường vì',
 'Mặt đường ướt phản xạ như gương, ánh đèn hắt đi hướng khác thay vì khuếch tán về mắt người lái', 'Nước làm vạch sơn trôi', 'Trời tối hơn khi mưa', 'Đèn xe yếu đi khi trời mưa',
 'Mặt đường khô có phản xạ khuếch tán nên thấy vạch; ướt thì phản xạ gương.'],
['Tia tới hợp với pháp tuyến góc 40°. Góc giữa tia phản xạ và mặt gương là',
 '50°', '40°', '80°', '90°',
 'Góc phản xạ 40° → góc với mặt gương = 90° − 40° = 50°.'],
['Chiếu tia sáng vuông góc vào gương phẳng. Muốn tia phản xạ lệch 60° so với phương tia tới, phải quay gương một góc',
 '30°', '60°', '120°', '15°',
 'Gương quay α → tia phản xạ quay 2α = 60° → α = 30°.'],
['Soi gương trong phòng chỉ có một bóng đèn ở phía sau lưng, ta thấy mặt mình tối vì',
 'Mặt không được chiếu sáng nên ít ánh sáng từ mặt tới gương rồi tới mắt', 'Gương hấp thụ ánh sáng', 'Ánh sáng bị mặt hấp thụ hết', 'Đèn quá yếu',
 'Cần ánh sáng chiếu vào mặt thì gương mới hắt lại đủ ánh sáng.'],
['Biển báo giao thông có lớp phản quang giúp',
 'Hắt ánh sáng đèn xe trở lại phía người lái nên nhìn rõ ban đêm', 'Biển tự phát sáng', 'Hấp thụ ánh sáng đèn xe', 'Biển nóng lên',
 'Lớp phản quang chứa các hạt gương nhỏ phản xạ ánh sáng ngược về nguồn.'],
['Trong kính tiềm vọng, hai gương phẳng phải đặt nghiêng',
 '45° so với phương của tia sáng tới', '90°', '30°', '60°',
 'Mỗi lần phản xạ tia đổi hướng 90°, hai lần → song song với hướng ban đầu.'],
['Gương nhỏ của bác sĩ nha khoa dùng để',
 'Nhìn thấy mặt sau của răng nhờ phản xạ ánh sáng', 'Chiếu sáng miệng bệnh nhân', 'Phóng to răng nhiều lần', 'Đo nhiệt độ răng',
 'Gương phẳng cho ảnh của phần răng bị khuất.'],
['Tại sao ta không nhìn thấy đường đi của tia sáng trong không khí sạch?',
 'Không có hạt nào hắt ánh sáng từ tia sáng vào mắt ta', 'Ánh sáng trong không khí là vô hình tuyệt đối', 'Tia sáng chuyển động quá nhanh', 'Không khí hấp thụ hết ánh sáng',
 'Ta chỉ thấy ánh sáng khi nó đi vào mắt; tia không hướng vào mắt thì không thấy.'],
['Cho điểm sáng S, gương phẳng và điểm M trước gương. Để vẽ tia sáng từ S phản xạ trên gương đi qua M, ta',
 'Dựng ảnh S′, nối S′M cắt gương tại I; tia cần vẽ là SI rồi IM', 'Nối thẳng S với M', 'Vẽ tia từ S vuông góc với gương', 'Nối S với chân đường vuông góc hạ từ M',
 'Tia phản xạ có đường kéo dài qua S′ nên điểm tới I nằm trên S′M.'],
['Đặt bóng đèn sau hai tấm bìa có lỗ nhỏ. Mắt chỉ nhìn thấy đèn khi',
 'Hai lỗ và bóng đèn cùng nằm trên một đường thẳng với mắt', 'Hai lỗ lệch nhau', 'Tấm bìa gần đèn được che kín', 'Đèn tắt',
 'Ánh sáng truyền thẳng nên phải thẳng hàng mới đi được qua cả hai lỗ.'],
['Nhìn qua ống thẳng thấy ngọn đèn, nhưng qua ống cong không thấy. Thí nghiệm này chứng tỏ',
 'Ánh sáng truyền theo đường thẳng', 'Ánh sáng truyền theo đường cong', 'Ống cong hấp thụ ánh sáng', 'Ánh sáng chỉ truyền trong ống',
 'Ánh sáng không "bẻ cong" theo ống cong.'],
['Chóa (pha) phản xạ trong đèn pin có tác dụng',
 'Hướng các tia sáng của bóng đèn về phía trước thành chùm sáng hẹp, đi xa', 'Làm đèn sáng hơn về công suất', 'Giảm nhiệt cho bóng', 'Đổi màu ánh sáng',
 'Chóa gom các tia toả ra nhiều hướng thành chùm gần song song.'],
['Ảnh của một điểm sáng S qua gương phẳng nằm',
 'Phía sau gương, trên đường vuông góc hạ từ S xuống gương, cách gương bằng khoảng cách từ S đến gương', 'Phía trước gương, trùng với S', 'Trên mặt gương', 'Phía sau gương, cách gương gấp đôi S',
 'Đây là cách dựng ảnh bằng tính chất đối xứng.'],
['Vùng tối trên màn có dạng giống hình dạng của',
 'Vật cản', 'Nguồn sáng', 'Màn chắn', 'Mắt người quan sát',
 'Bóng của vật có hình chiếu của vật lên màn.'],
['Trong nhật thực toàn phần, người quan sát đứng ở',
 'Vùng tối của Mặt Trăng trên Trái Đất', 'Vùng nửa tối của Mặt Trăng', 'Vùng tối của Trái Đất', 'Phía Trái Đất đang là ban đêm',
 'Ở vùng tối, toàn bộ Mặt Trời bị Mặt Trăng che khuất.'],
['Phát biểu nào sau đây <b>sai</b> về ảnh qua gương phẳng?',
 'Ảnh có thể hứng được trên màn đặt sau gương', 'Ảnh lớn bằng vật', 'Ảnh đối xứng với vật qua gương', 'Ảnh là ảnh ảo',
 'Ảnh ảo không hứng được trên màn.'],
['Trò chơi "trốn tìm": bạn A đứng khuất sau cột, bạn B không thấy A vì',
 'Ánh sáng từ A không truyền thẳng được tới mắt B do cột che', 'A không phát ra ánh sáng', 'Cột hút hết ánh sáng', 'Ánh sáng chỉ truyền qua vật trong suốt',
 'Ánh sáng truyền thẳng, bị cột chắn.'],
['Trong bức ảnh chụp bóng của một người dưới nắng, bóng có viền mờ ở rìa. Lí do là',
 'Mặt Trời là nguồn sáng rộng tạo ra vùng nửa tối ở rìa bóng', 'Máy ảnh bị rung', 'Người đang chuyển động', 'Mặt đất không phẳng',
 'Nguồn sáng có kích thước → có vùng nửa tối.'],
['Cho tia tới SI và tia phản xạ IR trên gương phẳng, góc giữa hai tia là 120°. Góc tới và góc hợp bởi tia tới với mặt gương lần lượt là',
 '60° và 30°', '120° và 60°', '30° và 60°', '60° và 60°',
 'i = 120°/2 = 60°; góc với gương = 90° − 60° = 30°.'],
['Hai người đứng ở hai phía của một gương phẳng nhỏ treo trên tường (gương giữa hai người). Người này thấy được ảnh của người kia khi',
 'Có tia sáng từ người kia phản xạ trên gương đi vào mắt người này', 'Hai người đứng thật gần gương', 'Gương thật lớn', 'Không bao giờ thấy được',
 'Điều kiện chung để thấy ảnh: tia phản xạ đi vào mắt.'],
['Kích thước ảnh của bạn trong gương phẳng khi bạn lùi xa gương',
 'Không thay đổi', 'Nhỏ dần', 'Lớn dần', 'Biến mất',
 'Ảnh luôn bằng vật.'],
['Điểm khác nhau cơ bản giữa phản xạ gương và phản xạ khuếch tán là',
 'Hướng của các tia phản xạ: theo một hướng xác định hay tán ra nhiều hướng', 'Góc phản xạ có bằng góc tới hay không', 'Ánh sáng có bị hấp thụ hay không', 'Tốc độ ánh sáng thay đổi hay không',
 'Cả hai đều tuân theo định luật phản xạ tại từng điểm; khác ở độ nhẵn bề mặt.'],
['Bóng của cột cờ dài 6 m khi bóng của cây gậy cao 1 m dài 1,5 m (cùng thời điểm). Cột cờ cao',
 '4 m', '9 m', '6 m', '3 m',
 'Tia nắng song song → tỉ lệ chiều cao/bóng bằng nhau: h = 1 × 6/1,5 = 4 m.'],
['Nguồn sáng điểm S cách màn 3 m. Đặt tấm bìa tròn đường kính 20 cm cách S 1 m (song song màn). Vùng tối trên màn có đường kính',
 '60 cm', '20 cm', '40 cm', '30 cm',
 'Tam giác đồng dạng: D = 20 × 3/1 = 60 cm.'],
['Tia sáng chiếu tới gương phẳng theo phương nằm ngang, muốn tia phản xạ hướng thẳng lên trên thì gương phải',
 'Nghiêng 45° so với phương ngang', 'Đặt thẳng đứng', 'Đặt nằm ngang', 'Nghiêng 30°',
 'Tia tới và tia phản xạ vuông góc → i = 45°.'],
['Chọn câu <b>đúng</b>.',
 'Ta nhìn thấy bông hoa màu đỏ vì ánh sáng đỏ từ hoa hắt lại đi vào mắt', 'Bông hoa tự phát ra ánh sáng đỏ', 'Mắt ta phát ra ánh sáng đỏ chiếu vào hoa', 'Hoa đỏ vì hấp thụ ánh sáng đỏ',
 'Hoa hắt lại (phản xạ khuếch tán) ánh sáng màu đỏ và hấp thụ các màu khác.'],
['Một điểm sáng S đặt trước gương phẳng. Có bao nhiêu tia sáng từ S tới gương cho tia phản xạ vào mắt người quan sát đặt tại một vị trí cố định?',
 'Chỉ có một tia', 'Vô số tia', 'Hai tia', 'Không có tia nào',
 'Với mỗi vị trí mắt, chỉ có đúng một điểm tới I trên gương (giao của S′M với gương) cho tia phản xạ vào mắt.'],
['Đặt ngọn nến trước gương phẳng rồi đặt tờ giấy trắng ở phía sau gương đúng vị trí ảnh. Trên tờ giấy',
 'Không có ảnh ngọn nến vì ảnh qua gương phẳng là ảnh ảo', 'Có ảnh ngọn nến rõ nét', 'Có ảnh ngọn nến bị ngược', 'Có ảnh ngọn nến nhỏ hơn',
 'Ảnh ảo không hứng được trên màn.'],
['Tia sáng tới gương phẳng có góc tới 0°. Góc giữa tia tới và tia phản xạ bằng',
 '0°', '90°', '180°', '45°',
 'Tia phản xạ trùng với tia tới nhưng ngược chiều → góc giữa hai tia bằng 0°.'],
['Một bóng đèn nhỏ chiếu vào quả cầu, tạo bóng trên tường. Để bóng của quả cầu <b>lớn hơn</b> mà không dịch tường, ta',
 'Đưa quả cầu lại gần bóng đèn', 'Đưa quả cầu lại gần tường', 'Thay đèn bằng đèn sáng hơn', 'Sơn quả cầu màu đen',
 'Vật cản càng gần nguồn điểm, vùng tối trên màn càng lớn.'],
['Mắt ta không thể nhìn thấy ánh sáng laser đi ngang qua trước mặt trong không khí sạch, nhưng khi có khói thì thấy rõ. Điều đó cho thấy',
 'Ta chỉ nhìn thấy ánh sáng khi có ánh sáng đi vào mắt (khói tán xạ ánh sáng về mắt)', 'Khói phát ra ánh sáng', 'Laser chỉ sáng trong khói', 'Ánh sáng bị khói bẻ cong về mắt',
 'Hạt khói phản xạ khuếch tán ánh sáng đến mắt ta.'],
['Bạn Mai đứng cách gương phẳng 1,5 m, bạn Hoa đứng cách gương 2,5 m (cùng phía, cùng đường vuông góc). Ảnh của Hoa cách Mai',
 '4 m', '1 m', '2,5 m', '5 m',
 'Ảnh của Hoa cách gương 2,5 m ở phía sau → cách Mai 2,5 + 1,5 = 4 m.'],
['Một vật chuyển động lại gần gương phẳng với tốc độ 2 m/s. Ảnh của vật chuyển động lại gần vật với tốc độ',
 '4 m/s', '2 m/s', '1 m/s', '0 m/s',
 'Vật lại gần gương 2 m/s, ảnh cũng lại gần gương 2 m/s từ phía đối diện → hai bên tiến lại nhau 4 m/s.'],
['Trong hiện tượng phản xạ ánh sáng trên gương phẳng, nếu tăng góc tới thêm 15° thì góc giữa tia tới và tia phản xạ',
 'Tăng thêm 30°', 'Tăng thêm 15°', 'Không đổi', 'Giảm 15°',
 'Góc giữa hai tia = 2i, i tăng 15° → 2i tăng 30°.'],
];

export const TU = [
['Nam châm hút được các vật làm bằng',
 'Sắt, thép, niken, coban', 'Mọi kim loại', 'Đồng và nhôm', 'Gỗ và nhựa',
 'Chỉ một số vật liệu (gọi là vật liệu từ) bị nam châm hút; đồng, nhôm không bị hút.'],
['Vật nào sau đây <b>không</b> bị nam châm hút?',
 'Thanh nhôm', 'Đinh sắt', 'Viên bi thép', 'Đồng xu có niken',
 'Nhôm không phải vật liệu từ.'],
['Mỗi thanh nam châm luôn có',
 'Hai cực: cực Bắc (N) và cực Nam (S)', 'Một cực duy nhất', 'Ba cực', 'Cực dương và cực âm',
 'Không thể tách riêng một cực từ.'],
['Trên nam châm thẳng, chỗ hút vật liệu từ mạnh nhất là',
 'Hai đầu (hai cực)', 'Chính giữa thanh', 'Mọi chỗ như nhau', 'Cách hai đầu 1/3 chiều dài',
 'Từ trường mạnh nhất ở hai cực, yếu nhất ở giữa.'],
['Đưa hai cực cùng tên của hai nam châm lại gần nhau, chúng',
 'Đẩy nhau', 'Hút nhau', 'Không tương tác', 'Lúc hút lúc đẩy',
 'Cùng cực đẩy nhau, khác cực hút nhau.'],
['Một kim nam châm được treo tự do khi cân bằng sẽ nằm theo hướng',
 'Bắc – Nam địa lí (cực Bắc của kim chỉ hướng Bắc)', 'Đông – Tây', 'Bất kì', 'Thẳng đứng',
 'Do tác dụng của từ trường Trái Đất.'],
['Bẻ đôi một thanh nam châm thẳng, ta được',
 'Hai nam châm, mỗi nam châm đủ hai cực', 'Một mảnh chỉ có cực Bắc, một mảnh chỉ có cực Nam', 'Hai mảnh sắt thường không có từ tính', 'Một nam châm và một mảnh sắt',
 'Mỗi phần của nam châm vẫn là nam châm có hai cực.'],
['Nam châm vĩnh cửu có thể bị giảm hoặc mất từ tính khi',
 'Bị nung nóng hoặc va đập mạnh', 'Để trong tủ lạnh', 'Đặt cạnh gỗ', 'Bôi dầu',
 'Nhiệt độ cao và va đập làm xáo trộn sự sắp xếp từ bên trong.'],
['Từ trường là',
 'Vùng không gian xung quanh nam châm (hoặc dòng điện) có tác dụng lực từ lên vật liệu từ, kim nam châm', 'Khu vực có nhiệt độ cao', 'Vùng không khí bị hút vào nam châm', 'Bề mặt của nam châm',
 'Từ trường tồn tại xung quanh nam châm và dây dẫn có dòng điện.'],
['Cách đơn giản nhất để nhận biết tại một điểm có từ trường hay không là',
 'Đặt một kim nam châm nhỏ tại đó, xem nó có bị lệch hướng không', 'Đo nhiệt độ', 'Dùng thước đo', 'Nhìn bằng mắt thường',
 'Kim nam châm là dụng cụ phát hiện từ trường.'],
['Từ phổ là',
 'Hình ảnh các đường mạt sắt sắp xếp xung quanh nam châm', 'Bảng màu của nam châm', 'Tên gọi khác của la bàn', 'Dụng cụ đo từ trường',
 'Rắc mạt sắt lên tấm bìa đặt trên nam châm, gõ nhẹ → mạt sắt xếp thành các đường cong.'],
['Bên ngoài thanh nam châm, đường sức từ có chiều',
 'Đi ra từ cực Bắc, đi vào cực Nam', 'Đi ra từ cực Nam, đi vào cực Bắc', 'Song song với thanh, không có chiều', 'Từ giữa thanh toả ra hai đầu',
 'Quy ước chiều đường sức từ theo hướng cực Bắc kim nam châm thử.'],
['Phát biểu nào <b>sai</b> về đường sức từ?',
 'Các đường sức từ có thể cắt nhau', 'Đường sức từ càng dày (sít) thì từ trường càng mạnh', 'Bên ngoài nam châm, đường sức đi ra từ cực N, vào cực S', 'Đường sức từ là những đường cong khép kín',
 'Tại mỗi điểm chỉ có một hướng từ trường nên đường sức không cắt nhau.'],
['Kim nam châm thử đặt trên một đường sức từ sẽ',
 'Định hướng dọc theo đường sức, cực Bắc chỉ theo chiều đường sức', 'Đặt vuông góc với đường sức', 'Quay tròn liên tục', 'Không bị ảnh hưởng',
 'Đây là cách xác định chiều đường sức từ bằng kim nam châm.'],
['Đặt hai cực khác tên của hai thanh nam châm đối diện, gần nhau. Đường sức từ ở khoảng giữa hai cực',
 'Gần như thẳng, song song, đi từ cực N sang cực S', 'Vòng tròn khép kín', 'Không có đường sức', 'Đi từ S sang N',
 'Đường sức nối từ cực Bắc của thanh này sang cực Nam của thanh kia.'],
['Trái Đất có từ trường, biểu hiện là',
 'Kim la bàn luôn định hướng Bắc – Nam', 'Trái Đất hút mọi vật', 'Trái Đất quay quanh Mặt Trời', 'Trái Đất có ngày và đêm',
 'Trái Đất giống một nam châm khổng lồ tác dụng lên kim nam châm.'],
['Cực Bắc của kim la bàn bị hút về phía cực Bắc địa lí. Điều đó chứng tỏ gần cực Bắc địa lí là',
 'Cực từ Nam của "nam châm Trái Đất"', 'Cực từ Bắc của "nam châm Trái Đất"', 'Không có cực từ', 'Cả hai cực từ',
 'Khác cực thì hút: cực N của kim bị hút → nơi đó là cực từ Nam. Vì thế cực Bắc địa lí và cực Bắc địa từ không trùng nhau.'],
['La bàn là dụng cụ dùng để',
 'Xác định hướng', 'Đo tốc độ', 'Đo nhiệt độ', 'Đo độ cao',
 'Kim nam châm của la bàn luôn chỉ hướng Bắc – Nam.'],
['Bộ phận chính của la bàn là',
 'Kim nam châm quay tự do trên trục và mặt chia độ', 'Lò xo và kim chỉ', 'Bóng đèn nhỏ', 'Thước đo góc',
 'Kim nam châm định hướng theo từ trường Trái Đất; mặt chia độ ghi các hướng.'],
['Khi dùng la bàn xác định hướng, thao tác nào <b>đúng</b>?',
 'Đặt la bàn nằm ngang, xa nam châm và vật bằng sắt, chờ kim đứng yên', 'Đặt la bàn dựng thẳng đứng', 'Để la bàn cạnh điện thoại, loa', 'Lắc mạnh la bàn liên tục',
 'Vật sắt, nam châm, loa điện thoại làm kim la bàn chỉ sai.'],
['Đặt la bàn gần một thanh nam châm hoặc cục sắt lớn thì',
 'Kim la bàn chỉ sai hướng Bắc', 'Kim la bàn chỉ chính xác hơn', 'Kim la bàn quay tròn không ngừng', 'La bàn bị hỏng vĩnh viễn',
 'Từ trường của vật gần mạnh hơn từ trường Trái Đất làm kim bị lệch.'],
['Trên mặt chia độ của la bàn, hướng Đông ứng với góc',
 '90°', '0°', '180°', '270°',
 'Bắc 0°, Đông 90°, Nam 180°, Tây 270°.'],
['Nam châm điện gồm',
 'Ống dây dẫn có lõi sắt non, có dòng điện chạy qua', 'Thanh sắt được cọ xát', 'Thanh nam châm vĩnh cửu nối pin', 'Cuộn dây đồng không có điện',
 'Khi có dòng điện, lõi sắt non nhiễm từ và ống dây trở thành nam châm.'],
['Để tăng lực từ của nam châm điện, ta có thể',
 'Tăng số vòng dây hoặc tăng cường độ dòng điện qua ống dây', 'Giảm số vòng dây', 'Bỏ lõi sắt non', 'Dùng dây dài hơn nhưng không quấn',
 'Từ trường của ống dây mạnh hơn khi nhiều vòng và dòng điện lớn hơn.'],
['Khi ngắt dòng điện, nam châm điện có lõi sắt non',
 'Mất từ tính gần như ngay lập tức', 'Vẫn giữ từ tính lâu dài', 'Mạnh lên', 'Đổi cực',
 'Sắt non nhiễm từ nhanh nhưng cũng khử từ nhanh — đó là ưu điểm của nam châm điện.'],
['Đổi chiều dòng điện chạy qua ống dây của nam châm điện thì',
 'Hai cực từ của nam châm điện đổi chỗ cho nhau', 'Nam châm điện mất từ tính', 'Lực từ mạnh gấp đôi', 'Không có gì thay đổi',
 'Chiều đường sức từ của ống dây phụ thuộc chiều dòng điện.'],
['Không nên dùng lõi thép thay lõi sắt non trong nam châm điện vì',
 'Thép giữ từ tính lâu sau khi ngắt điện nên không "tắt" được nam châm', 'Thép không nhiễm từ', 'Thép quá nhẹ', 'Thép dẫn điện quá tốt',
 'Lõi thép sẽ thành nam châm vĩnh cửu; lõi sắt non mới cho phép bật/tắt.'],
['Thiết bị nào sau đây sử dụng nam châm điện?',
 'Chuông điện', 'Bếp ga', 'Kính lúp', 'Đồng hồ cát',
 'Chuông điện, rơ-le, cần cẩu điện, loa… đều dùng nam châm điện.'],
['Trong chuông điện, khi nhấn nút chuông thì',
 'Nam châm điện hút cần gõ vào chuông, đồng thời làm mạch bị ngắt, cần bật lại, quá trình lặp lại liên tục', 'Nam châm vĩnh cửu quay tròn', 'Chuông tự rung vì dòng điện đốt nóng', 'Lá thép bị đẩy ra xa mãi',
 'Cơ chế "hút – ngắt – nhả – đóng" lặp lại nhanh tạo tiếng kêu liên hồi.'],
['Cần cẩu dùng nam châm điện để bốc phế liệu sắt. Muốn thả phế liệu xuống, người điều khiển',
 'Ngắt dòng điện qua nam châm', 'Tăng dòng điện', 'Đổi chiều dòng điện', 'Lắc mạnh cần cẩu',
 'Ngắt điện → nam châm điện mất từ tính → thả vật.'],
['Không thể dùng cần cẩu nam châm điện để bốc các thùng nhôm vì',
 'Nhôm không bị nam châm hút', 'Nhôm quá nặng', 'Nhôm dẫn điện tốt', 'Nhôm bị nóng chảy',
 'Nhôm không phải vật liệu từ.'],
['Đặt kim nam châm gần dây dẫn thẳng. Khi cho dòng điện chạy qua dây, kim bị lệch. Thí nghiệm này (Ơ-xtét) chứng tỏ',
 'Xung quanh dòng điện có từ trường', 'Dây dẫn bị nóng', 'Kim nam châm bị hút bởi đồng', 'Dòng điện làm kim nhẹ đi',
 'Từ trường không chỉ có quanh nam châm mà cả quanh dòng điện.'],
['Trong thí nghiệm từ phổ, sau khi rắc mạt sắt lên tấm bìa đặt trên nam châm, ta gõ nhẹ tấm bìa để',
 'Mạt sắt dễ xoay và sắp xếp theo đường sức từ', 'Mạt sắt rơi khỏi tấm bìa', 'Nam châm mạnh lên', 'Tấm bìa nóng lên',
 'Gõ nhẹ làm giảm ma sát, mạt sắt định hướng theo từ trường.'],
['Thanh sắt non đặt gần nam châm trở thành nam châm (bị nhiễm từ). Khi đưa ra xa nam châm, thanh sắt non',
 'Mất từ tính gần như ngay', 'Giữ từ tính lâu dài', 'Mạnh hơn nam châm ban đầu', 'Đổi cực',
 'Sắt non không giữ được từ tính.'],
['Có hai thanh giống hệt nhau, một là nam châm, một là sắt thường. Đặt đầu thanh X vào chính giữa thanh Y: nếu chúng hút nhau thì',
 'X là nam châm', 'Y là nam châm', 'Cả hai là nam châm', 'Không kết luận được',
 'Nếu Y là nam châm thì giữa Y hầu như không hút; hút được nghĩa là X là nam châm hút sắt Y.'],
['Đưa hai thanh kim loại lại gần nhau thấy chúng đẩy nhau. Kết luận',
 'Cả hai thanh đều là nam châm', 'Chỉ một thanh là nam châm', 'Cả hai đều là sắt thường', 'Một thanh là đồng',
 'Lực đẩy chỉ xuất hiện giữa hai cực cùng tên của hai nam châm; nam châm với sắt thường chỉ hút.'],
['Ở nam châm hình chữ U, từ trường mạnh nhất ở',
 'Khoảng giữa hai cực (hai đầu chữ U)', 'Đáy chữ U', 'Ngoài xa nam châm', 'Mọi nơi như nhau',
 'Hai cực gần nhau tạo vùng từ trường mạnh, gần đều.'],
['Cửa tủ lạnh tự khép chặt vào khung vì',
 'Gioăng cửa có nam châm hút vào khung tủ bằng sắt', 'Cửa nặng nên rơi xuống', 'Khung tủ có lò xo', 'Không khí trong tủ hút cửa',
 'Ứng dụng của nam châm trong đời sống.'],
['Hai kim nam châm đặt gần nhau, tự do, khi cân bằng sẽ',
 'Hướng các cực khác tên về phía nhau', 'Hướng các cực cùng tên về phía nhau', 'Vuông góc với nhau', 'Quay liên tục',
 'Khác cực hút nhau nên ổn định ở vị trí cực N gần cực S.'],
['Từ trường Trái Đất giúp',
 'La bàn định hướng và nhiều loài chim, cá di cư tìm đường', 'Trái Đất giữ được không khí', 'Cây cối quang hợp', 'Nước biển có vị mặn',
 'Nhiều sinh vật cảm nhận được từ trường Trái Đất để định hướng.'],
['So với nam châm vĩnh cửu, nam châm điện có ưu điểm',
 'Có thể bật/tắt, thay đổi độ mạnh và đổi cực dễ dàng', 'Không cần điện', 'Luôn nhẹ hơn', 'Không bao giờ mất từ tính',
 'Điều khiển bằng dòng điện.'],
['Nam châm điện A có 100 vòng dây, nam châm điện B có 200 vòng dây, cùng lõi và cùng dòng điện. Kết luận',
 'B hút mạnh hơn A', 'A hút mạnh hơn B', 'Hai nam châm hút bằng nhau', 'Không so sánh được',
 'Nhiều vòng hơn → từ trường mạnh hơn.'],
['Nam châm hút được đinh sắt qua tấm bìa mỏng. Điều này cho thấy',
 'Từ trường xuyên qua được tấm bìa', 'Tấm bìa là vật liệu từ', 'Tấm bìa dẫn điện', 'Đinh sắt là nam châm',
 'Từ trường tồn tại trong không gian, bìa không chắn được từ trường.'],
['Cực Bắc địa lí và cực Bắc địa từ của Trái Đất',
 'Không trùng nhau', 'Trùng nhau hoàn toàn', 'Cách nhau đúng nửa vòng Trái Đất', 'Đổi chỗ mỗi ngày',
 'Cực địa từ lệch so với cực địa lí, nên kim la bàn chỉ lệch một góc nhỏ so với hướng Bắc thật.'],
['Khoáng vật có từ tính tự nhiên, được người xưa dùng làm nam châm và la bàn là',
 'Đá nam châm (magnetit)', 'Thạch anh', 'Đá vôi', 'Than đá',
 'Từ chữ "magnet" — tên vùng Magnesia ở Hy Lạp có nhiều loại đá này.'],
['Lõi của nam châm điện làm bằng sắt non vì sắt non',
 'Nhiễm từ mạnh khi có điện và mất từ tính ngay khi ngắt điện', 'Rất cứng', 'Không nhiễm từ', 'Nhẹ hơn thép',
 'Cần vật liệu nhiễm từ nhanh nhưng không giữ từ.'],
['Không nên để nam châm gần',
 'Thẻ ngân hàng có dải từ, đồng hồ cơ, màn hình cũ', 'Cốc thuỷ tinh', 'Quyển sách', 'Chai nước',
 'Từ trường mạnh làm hỏng dữ liệu trên dải từ, làm sai lệch cơ cấu đồng hồ.'],
['Lực từ là',
 'Lực mà nam châm (hay từ trường) tác dụng lên vật liệu từ hoặc nam châm khác', 'Lực hút của Trái Đất lên mọi vật', 'Lực đẩy của không khí', 'Lực ma sát giữa hai nam châm',
 'Lực hút, đẩy giữa các nam châm và vật liệu từ là lực từ.'],
['Cách chế tạo nam châm điện đơn giản ở nhà là',
 'Quấn nhiều vòng dây đồng có vỏ cách điện quanh chiếc đinh sắt rồi nối hai đầu dây với pin', 'Cọ xát đinh sắt vào tóc', 'Nhúng đinh vào nước muối', 'Đốt nóng đinh sắt',
 'Đinh sắt là lõi, dây quấn tạo ống dây, pin cung cấp dòng điện.'],
['Dây quấn nam châm điện phải có vỏ cách điện để',
 'Dòng điện chạy dọc theo từng vòng dây, không nối tắt qua các vòng kề nhau hoặc lõi', 'Dây đẹp hơn', 'Dây không bị gãy', 'Tăng khối lượng',
 'Nếu không cách điện, dòng điện đi tắt, ống dây không tạo từ trường đúng.'],
['Mạt sắt xếp thành các đường cong trên tấm bìa đặt trên nam châm vì',
 'Mỗi mạt sắt bị nhiễm từ thành nam châm nhỏ và định hướng theo từ trường', 'Mạt sắt bị gió thổi', 'Tấm bìa có rãnh', 'Mạt sắt bị tĩnh điện',
 'Các nam châm nhỏ nối đuôi nhau tạo hình đường sức từ.'],
['Ứng dụng của nam châm điện trong công nghiệp tái chế là',
 'Tách phế liệu sắt, thép ra khỏi rác', 'Nung chảy kim loại', 'Sơn phủ kim loại', 'Cắt kim loại',
 'Băng chuyền có nam châm điện hút riêng đồ sắt.'],
['Cần cẩu điện cần nâng vật sắt nặng hơn thì có thể',
 'Tăng cường độ dòng điện qua nam châm điện', 'Giảm số vòng dây', 'Ngắt điện rồi đóng lại', 'Thay lõi sắt bằng lõi nhựa',
 'Dòng điện lớn hơn → từ trường mạnh hơn → lực hút lớn hơn.'],
['Tàu điện đệm từ (maglev) chạy êm và rất nhanh vì',
 'Dùng lực từ giữa các nam châm điện để nâng tàu lên khỏi đường ray, gần như không ma sát', 'Dùng bánh xe rất tròn', 'Đường ray rất dài', 'Tàu rất nhẹ',
 'Lực đẩy/hút từ giữ tàu lơ lửng và đẩy tàu tiến.'],
['Rơ-le điện từ là thiết bị',
 'Dùng nam châm điện để tự động đóng, ngắt một mạch điện khác', 'Đo cường độ dòng điện', 'Phát sáng khi có điện', 'Tạo ra dòng điện',
 'Khi cuộn dây có điện, nam châm điện hút lá thép làm đóng/mở tiếp điểm.'],
['Thép được dùng để chế tạo nam châm vĩnh cửu vì thép',
 'Giữ được từ tính lâu dài sau khi nhiễm từ', 'Không nhiễm từ', 'Rất nhẹ', 'Dẫn điện tốt nhất',
 'Trái với sắt non, thép "nhớ" từ tính.'],
['Phát biểu nào sau đây <b>đúng</b>?',
 'Xung quanh dây dẫn có dòng điện có từ trường', 'Chỉ nam châm mới có từ trường', 'Từ trường nhìn thấy được bằng mắt thường', 'Nam châm hút mọi kim loại',
 'Thí nghiệm Ơ-xtét chứng minh dòng điện tạo ra từ trường.'],
['Trong thí nghiệm Ơ-xtét, ban đầu dây dẫn được đặt',
 'Song song với kim nam châm (dọc theo hướng Bắc – Nam)', 'Vuông góc với kim nam châm', 'Thẳng đứng', 'Cách kim nam châm rất xa',
 'Đặt song song để dễ quan sát kim lệch khi có dòng điện.'],
['Hai thanh nam châm đặt gần nhau thì đẩy nhau. Vậy hai đầu gần nhau của chúng là',
 'Hai cực cùng tên', 'Hai cực khác tên', 'Một cực và phần giữa', 'Hai phần giữa',
 'Cùng tên → đẩy.'],
['Một thanh nam châm bị mất kí hiệu cực. Đưa một đầu thanh lại gần cực Bắc của kim la bàn, thấy hút. Đầu đó là',
 'Cực Nam', 'Cực Bắc', 'Không phải cực từ', 'Cả hai cực',
 'Hút cực Bắc → là cực khác tên → cực Nam.'],
['Tai nghe, loa điện thoại có chứa',
 'Nam châm nhỏ (nam châm vĩnh cửu) và cuộn dây', 'Pin nhiệt', 'Gương phẳng', 'Bóng đèn nhỏ',
 'Loa hoạt động nhờ tương tác giữa cuộn dây có dòng điện và nam châm.'],
['Từ trường Trái Đất mạnh nhất ở',
 'Gần hai cực từ', 'Xích đạo', 'Trên đỉnh núi cao', 'Dưới đáy biển',
 'Đường sức từ tập trung dày ở gần các cực từ.'],
['Trong từ phổ, chỗ mạt sắt sắp xếp dày (sít nhau) là nơi',
 'Từ trường mạnh', 'Từ trường yếu', 'Không có từ trường', 'Nam châm bị hỏng',
 'Mạt sắt dày ở hai cực nam châm — nơi từ trường mạnh nhất.'],
['Kim nam châm đang cân bằng chỉ hướng Bắc – Nam, ta xoay lệch đi rồi thả ra. Kim sẽ',
 'Dao động rồi quay về hướng Bắc – Nam cũ', 'Đứng yên ở hướng mới', 'Quay tròn mãi', 'Chỉ hướng Đông – Tây',
 'Từ trường Trái Đất luôn kéo kim về hướng Bắc – Nam.'],
['Khi đóng công tắc chuông điện, bộ phận trực tiếp hút cần gõ là',
 'Nam châm điện', 'Nam châm vĩnh cửu', 'Lò xo', 'Bóng đèn',
 'Nam châm điện hút lá thép mang búa gõ vào chuông.'],
['Hai cực từ của ống dây có dòng điện nằm ở',
 'Hai đầu ống dây', 'Chính giữa ống dây', 'Trên từng vòng dây', 'Ngoài ống dây rất xa',
 'Ống dây có dòng điện giống một nam châm thẳng với hai cực ở hai đầu.'],
['Nguy cơ khi dùng cần cẩu nam châm điện là',
 'Mất điện đột ngột làm vật sắt rơi xuống', 'Nam châm hút cả người', 'Nam châm quá nhẹ', 'Nam châm không hút được thép',
 'Cần cẩu điện phải có nguồn dự phòng hoặc không đưa vật qua đầu người.'],
['Nam châm vĩnh cửu hiện đại rất mạnh thường được làm từ hợp kim chứa',
 'Neodymi (nam châm đất hiếm) hoặc ferit', 'Đồng', 'Nhôm nguyên chất', 'Kẽm',
 'Nam châm neodymi (NdFeB) mạnh gấp nhiều lần nam châm ferit.'],
['Để xác định các cực của một nam châm điện đang hoạt động, ta',
 'Đưa kim la bàn lại gần: đầu hút cực N của kim là cực S của nam châm điện', 'Nhìn màu của ống dây', 'Đo nhiệt độ hai đầu', 'Đếm số vòng dây',
 'Dùng tương tác hút/đẩy với kim nam châm đã biết cực.'],
['Treo một đinh sắt vào nam châm; đưa đinh thứ hai chạm vào đầu đinh thứ nhất, nó cũng bị giữ lại vì',
 'Đinh thứ nhất bị nhiễm từ, trở thành nam châm tạm thời', 'Đinh thứ hai dính keo', 'Hai đinh cùng dẫn điện', 'Nam châm quá lớn',
 'Vật liệu từ đặt trong từ trường bị nhiễm từ.'],
['Cách nào sau đây <b>không</b> làm tăng lực từ của nam châm điện?',
 'Thay lõi sắt non bằng lõi nhựa', 'Tăng số vòng dây', 'Tăng cường độ dòng điện', 'Thêm lõi sắt non vào ống dây rỗng',
 'Lõi nhựa không nhiễm từ nên nam châm yếu đi rất nhiều.'],
['Điểm khác biệt quan trọng giữa nam châm điện và nam châm vĩnh cửu là nam châm điện',
 'Chỉ có từ tính khi có dòng điện chạy qua', 'Luôn yếu hơn', 'Không có cực', 'Không hút sắt',
 'Ngắt điện là hết từ tính (với lõi sắt non).'],
['Biển cảnh báo trong phòng chụp cộng hưởng từ (MRI) yêu cầu không mang đồ sắt thép vào vì',
 'Máy có từ trường rất mạnh hút vật sắt thép, gây nguy hiểm', 'Máy phát ra tia lửa', 'Phòng rất nóng', 'Sắt thép làm máy tắt',
 'Vật sắt bị hút với lực rất lớn có thể gây tai nạn.'],
['Nhiều loài chim di cư hàng nghìn km vẫn tìm đúng đường một phần nhờ',
 'Cảm nhận được từ trường Trái Đất', 'Nghe tiếng sóng biển', 'Nhìn thấy các thành phố', 'Ngửi mùi thức ăn',
 'Một số sinh vật có "la bàn sinh học".'],
['Để la bàn trên điện thoại (hoặc cạnh loa), kim bị lệch vì',
 'Trong loa điện thoại có nam châm tạo từ trường mạnh hơn từ trường Trái Đất tại đó', 'Điện thoại toả nhiệt', 'Màn hình phát sáng', 'Điện thoại rung',
 'Từ trường của nam châm gần át từ trường Trái Đất.'],
['Nam châm chữ U giữ được vật sắt tốt nhất khi vật',
 'Chạm vào cả hai cực', 'Chạm vào đáy chữ U', 'Đặt xa hai cực', 'Chạm một cạnh bên',
 'Từ trường mạnh nhất ở hai cực; vật nối hai cực được hút mạnh nhất.'],
['Phát biểu nào sau đây <b>sai</b>?',
 'Nam châm hút được mọi kim loại', 'Nam châm có hai cực', 'Cùng cực thì đẩy nhau', 'Nam châm hút được niken',
 'Nam châm không hút đồng, nhôm, vàng, bạc…'],
['Để bảo quản nam châm chữ U lâu ngày, người ta',
 'Đặt một miếng sắt non nối liền hai cực', 'Để hai cực hở ra ngoài', 'Ngâm trong nước', 'Nung nóng định kì',
 'Miếng sắt "khép kín" đường sức, giúp nam châm ít bị mất từ tính.'],
['Để bảo quản hai thanh nam châm thẳng, người ta đặt chúng',
 'Song song, cực khác tên cạnh nhau, có miếng sắt non ở hai đầu', 'Nối đuôi cùng chiều', 'Cực cùng tên cạnh nhau', 'Cách xa nhau trong tủ',
 'Cách này khép kín đường sức từ, giữ từ tính lâu.'],
['Hiện tượng cực quang ở vùng gần hai cực Trái Đất liên quan đến',
 'Từ trường Trái Đất hướng các hạt mang điện từ Mặt Trời về phía hai cực', 'Núi lửa phun', 'Băng tan', 'Ánh sáng Mặt Trăng',
 'Hạt mang điện bị từ trường dẫn về cực, va chạm với khí quyển phát sáng.'],
['Thí nghiệm nào chứng tỏ từ trường tồn tại ở khoảng không gian quanh nam châm chứ không chỉ khi tiếp xúc?',
 'Kim nam châm bị lệch dù chưa chạm vào thanh nam châm', 'Nam châm hút đinh khi chạm vào', 'Nam châm nặng hơn sắt', 'Nam châm có màu đỏ, xanh',
 'Tác dụng lực từ xa chứng tỏ có từ trường trong không gian.'],
['Trong đời sống, vật nào sau đây <b>có</b> sử dụng nam châm?',
 'Nắp hộp bút tự đóng, cửa tủ lạnh, loa', 'Thước kẻ nhựa', 'Cốc thuỷ tinh', 'Bút chì',
 'Nam châm nhỏ được dùng ở rất nhiều đồ vật quen thuộc.'],
['Từ trường của một nam châm điện có 500 vòng dây so với chính nó khi chỉ còn 250 vòng (cùng dòng điện, cùng lõi) sẽ',
 'Mạnh hơn', 'Yếu hơn', 'Bằng nhau', 'Không có từ trường',
 'Số vòng tăng → từ trường mạnh hơn.'],
['Cho dòng điện chạy qua ống dây không có lõi, sau đó đưa lõi sắt non vào trong ống. Lực hút của ống dây lên đinh sắt',
 'Tăng lên rõ rệt', 'Giảm đi', 'Không đổi', 'Bằng 0',
 'Lõi sắt non bị nhiễm từ làm từ trường tổng cộng mạnh lên nhiều lần.'],
['Trên la bàn, để đọc hướng ta cần xoay mặt la bàn sao cho',
 'Vạch 0° (chữ N) trùng với đầu cực Bắc của kim', 'Vạch 90° trùng với kim', 'Kim nằm thẳng đứng', 'Kim chỉ vào chữ S',
 'Sau đó các hướng khác trên mặt chia độ là đúng.'],
['Một bạn đi theo hướng kim la bàn chỉ chữ N thì bạn đó đang đi về hướng',
 'Bắc', 'Nam', 'Đông', 'Tây',
 'N (North) là Bắc.'],
['Kim nam châm nhỏ đặt gần cực Bắc của thanh nam châm sẽ có',
 'Cực Nam của kim hướng về cực Bắc của thanh', 'Cực Bắc của kim hướng về cực Bắc của thanh', 'Kim vuông góc với thanh', 'Kim không bị ảnh hưởng',
 'Khác cực hút nhau.'],
['Khi cho dòng điện chạy qua ống dây, bên trong ống dây có từ trường. Đường sức từ trong lòng ống dây',
 'Gần như song song và cách đều nhau', 'Vòng tròn quanh trục ống', 'Không có', 'Cắt nhau tại tâm',
 'Trong lòng ống dây dài, từ trường gần đều.'],
['Đưa cực Nam của thanh nam châm A lại gần cực Nam của thanh nam châm B, chúng',
 'Đẩy nhau', 'Hút nhau', 'Không tương tác', 'Quay tròn',
 'Cùng tên → đẩy.'],
['Chọn câu <b>đúng</b> về la bàn.',
 'Kim la bàn là một nam châm nhỏ', 'Kim la bàn làm bằng đồng', 'La bàn hoạt động nhờ điện', 'La bàn chỉ dùng được ban ngày',
 'Kim la bàn là kim nam châm định hướng theo từ trường Trái Đất, dùng được cả ngày đêm.'],
['Nếu Trái Đất không có từ trường thì',
 'La bàn không còn định hướng được', 'Không còn ngày đêm', 'Nam châm không hút sắt nữa', 'Không có trọng lực',
 'La bàn dựa vào từ trường Trái Đất.'],
['Từ trường được biểu diễn trực quan bằng',
 'Các đường sức từ', 'Các mũi tên lực hấp dẫn', 'Các tia sáng', 'Các đường đồng mức',
 'Đường sức từ mô tả hướng và độ mạnh của từ trường.'],
['Cho 3 thanh: thép, sắt non và đồng, hình dạng giống nhau. Đưa nam châm lại gần thì',
 'Thép và sắt non bị hút, đồng không bị hút', 'Cả ba bị hút', 'Chỉ thép bị hút', 'Không thanh nào bị hút',
 'Đồng không phải vật liệu từ.'],
['Nam châm điện trong khoá cửa điện tử hoạt động như sau: khi có điện, nam châm điện',
 'Hút chốt sắt để giữ hoặc mở cửa; mất điện thì nhả', 'Phát sáng báo hiệu', 'Làm nóng chốt', 'Tự đổi cực liên tục',
 'Ứng dụng của nam châm điện: điều khiển bằng dòng điện.'],
['Ống dây có dòng điện chạy qua hút được đinh sắt nhỏ. Nếu tăng dòng điện lên gấp đôi thì',
 'Lực hút lên đinh tăng lên', 'Lực hút giảm đi', 'Ống dây mất từ tính', 'Không có gì thay đổi',
 'Cường độ dòng điện tăng → từ trường mạnh hơn.'],
['Thanh nam châm đặt nằm ngang trên mặt bàn, một kim nam châm đặt ở điểm chính giữa phía trên thanh (song song với thanh). Kim sẽ',
 'Nằm song song với thanh, cực Bắc của kim hướng về cực Nam của thanh', 'Vuông góc với thanh', 'Nằm dọc Bắc – Nam địa lí', 'Quay liên tục',
 'Ở phía trên chính giữa thanh, đường sức từ đi từ N sang S song song với thanh.'],
['Trước khi có la bàn, người đi biển định hướng chủ yếu dựa vào',
 'Mặt Trời và các ngôi sao', 'Nhiệt độ nước biển', 'Tiếng sóng', 'Màu nước',
 'La bàn từ ra đời (Trung Quốc cổ) giúp đi biển cả khi mây mù.'],
['Trong máy phát điện xe đạp (đi-na-mô) có',
 'Nam châm quay gần cuộn dây', 'Bóng đèn quay', 'Pin nhỏ', 'Gương phản xạ',
 'Nam châm quay làm từ trường qua cuộn dây biến đổi, tạo ra dòng điện.'],
['Sắp xếp độ mạnh từ trường tại các vị trí trên thanh nam châm thẳng: cực Bắc (1), điểm giữa (2), điểm cách cực Bắc 1/4 chiều dài (3). Thứ tự giảm dần là',
 '1 > 3 > 2', '2 > 3 > 1', '3 > 1 > 2', '1 > 2 > 3',
 'Càng gần cực từ trường càng mạnh; giữa thanh yếu nhất.'],
['Nam châm điện dùng trong loa, rơ-le có đặc điểm nào khiến nó được ưa chuộng hơn nam châm vĩnh cửu?',
 'Có thể thay đổi từ trường nhanh theo dòng điện', 'Rẻ hơn mọi trường hợp', 'Không cần dây dẫn', 'Không bao giờ nóng',
 'Từ trường thay đổi theo tín hiệu điện là cơ sở hoạt động của loa, rơ-le.'],
['Phát biểu nào <b>đúng</b> khi nói về cực từ của Trái Đất?',
 'Cực từ Bắc của Trái Đất nằm gần cực Nam địa lí', 'Cực từ Bắc của Trái Đất trùng với cực Bắc địa lí', 'Trái Đất chỉ có một cực từ', 'Trái Đất không có cực từ',
 'Cực Bắc của kim la bàn bị hút về phía Bắc, nghĩa là nơi đó là cực từ Nam; ngược lại cực từ Bắc nằm gần cực Nam địa lí.'],
];
