// ĐẠO ĐỨC — LỚP 3 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// Các chủ đề bám chương trình GDPT 2018:
//   - Em yêu Tổ quốc Việt Nam: Quốc kì, Quốc ca, Bác Hồ, tự hào dân tộc
//   - Quan tâm hàng xóm láng giềng
//   - Ham học hỏi
//   - Giữ lời hứa
//   - Tích cực hoàn thành nhiệm vụ (ở nhà, ở trường)
//   - Xử lí bất hoà với bạn bè
//   - Tuân thủ quy tắc an toàn (giao thông, ở nhà, nơi công cộng)

const DAODUC3_EXAMS = [

/* ═══════════ ĐỀ 1 — EM YÊU TỔ QUỐC VIỆT NAM ═══════════ */
{
  id: 9201, title: 'Đề 1 · Em yêu Tổ quốc Việt Nam', time: 20,
  questions: [
    { sec: 'Yêu Tổ quốc', name: 'Câu 1', pts: 1,
      text: 'Quốc kì của nước ta có đặc điểm gì?',
      opts: o4('Nền đỏ, ở giữa có ngôi sao vàng năm cánh', 'Nền xanh, có hình mặt trời', 'Nền trắng, có ba sọc', 'Nền vàng, có ngôi sao đỏ'), ans: 'A',
      why: 'Quốc kì Việt Nam nền đỏ, chính giữa là ngôi sao vàng năm cánh.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 2', pts: 1,
      text: 'Khi chào cờ và hát Quốc ca, em cần có thái độ thế nào?',
      opts: o4('Nói chuyện riêng', 'Nghiêm trang, mắt hướng về Quốc kì', 'Cười đùa với bạn', 'Đứng dựa vào tường'), ans: 'B',
      why: 'Chào cờ, hát Quốc ca phải đứng nghiêm trang, mắt hướng về Quốc kì để bày tỏ lòng tôn kính.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 3', pts: 1,
      text: 'Bài hát được cất lên trang trọng trong lễ chào cờ gọi là gì?',
      opts: o4('Bài hát ru', 'Bài đồng dao', 'Quốc ca', 'Bài hát vui chơi'), ans: 'C',
      why: 'Quốc ca là bài hát chính thức của Tổ quốc, được hát trang trọng khi chào cờ.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 4', pts: 1,
      text: 'Vị lãnh tụ kính yêu đọc Tuyên ngôn Độc lập, khai sinh nước Việt Nam là ai?',
      opts: o4('Bác Hồ (Hồ Chí Minh)', 'Một nhà vua thời xưa', 'Một vị tướng nước ngoài', 'Một nhà thơ'), ans: 'A',
      why: 'Bác Hồ đọc Tuyên ngôn Độc lập ngày 2/9/1945, khai sinh nước Việt Nam Dân chủ Cộng hoà.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 5', pts: 1,
      text: 'Việc làm nào thể hiện tình yêu Tổ quốc của học sinh?',
      opts: o4('Chê bai đất nước mình', 'Vứt rác nơi công cộng', 'Chăm học, giữ gìn của công, yêu quê hương', 'Không quan tâm gì đến quê hương'), ans: 'C',
      why: 'Chăm học, giữ gìn của công và yêu quê hương là biểu hiện tình yêu Tổ quốc của học sinh.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 6', pts: 1,
      text: 'Khi thấy Quốc kì bị rơi xuống đất, em nên làm gì?',
      opts: o4('Nhặt lên, phủi sạch và treo lại cẩn thận', 'Bước qua rồi bỏ đi', 'Giẫm lên cho vui', 'Mặc kệ không quan tâm'), ans: 'A',
      why: 'Cần trân trọng nhặt Quốc kì lên, làm sạch và treo lại vì đó là biểu tượng thiêng liêng của Tổ quốc.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 7', pts: 1,
      text: 'Ngày 2 tháng 9 hằng năm là ngày gì của nước ta?',
      opts: o4('Ngày Nhà giáo', 'Ngày Quốc khánh', 'Ngày Quốc tế Thiếu nhi', 'Ngày Phụ nữ'), ans: 'B',
      why: 'Ngày 2/9 là Quốc khánh — kỉ niệm ngày Bác Hồ đọc Tuyên ngôn Độc lập.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 8', pts: 1,
      text: 'Điều gì khiến em tự hào về dân tộc Việt Nam?',
      opts: o4('Truyền thống yêu nước, đoàn kết, cần cù', 'Thói quen xả rác bừa bãi', 'Sự lười biếng', 'Việc chia rẽ nhau'), ans: 'A',
      why: 'Dân tộc ta có truyền thống yêu nước, đoàn kết, cần cù lao động — rất đáng tự hào.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 9', pts: 1,
      text: 'Khi khách nước ngoài đến thăm quê hương, em nên làm gì?',
      opts: o4('Trốn tránh, không chào', 'Chỉ trỏ, cười chê', 'Vui vẻ, lịch sự chào hỏi và giúp đỡ', 'Xin tiền của khách'), ans: 'C',
      why: 'Vui vẻ, lịch sự chào hỏi và giúp đỡ khách thể hiện nét đẹp của người Việt Nam.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 10', pts: 1,
      text: 'Học tập theo lời dạy của Bác Hồ, học sinh cần làm gì?',
      opts: o4('Chăm ngoan, học giỏi, đoàn kết, giữ vệ sinh', 'Nói dối thầy cô', 'Bỏ bê học hành', 'Gây gổ với bạn'), ans: 'A',
      why: 'Bác Hồ dạy thiếu nhi phải chăm ngoan, học giỏi, đoàn kết và giữ gìn vệ sinh.' },
  ],
},

/* ═══════════ ĐỀ 2 — QUAN TÂM HÀNG XÓM LÁNG GIỀNG ═══════════ */
{
  id: 9202, title: 'Đề 2 · Quan tâm hàng xóm láng giềng', time: 20,
  questions: [
    { sec: 'Hàng xóm', name: 'Câu 1', pts: 1,
      text: 'Gặp bác hàng xóm đi ngang qua, em nên làm gì?',
      opts: o4('Lễ phép chào hỏi bác', 'Quay mặt đi', 'Giả vờ không thấy', 'Trêu chọc bác'), ans: 'A',
      why: 'Lễ phép chào hỏi hàng xóm là cách cư xử ngoan ngoãn, thân thiện.' },
    { sec: 'Hàng xóm', name: 'Câu 2', pts: 1,
      text: 'Nhà bên cạnh có cụ già sống một mình, thỉnh thoảng em nên làm gì?',
      opts: o4('Làm ồn cho cụ khó chịu', 'Sang hỏi thăm, giúp cụ việc nhỏ', 'Không bao giờ để ý', 'Ném rác sang nhà cụ'), ans: 'B',
      why: 'Sang hỏi thăm, giúp cụ những việc nhỏ thể hiện sự quan tâm với hàng xóm.' },
    { sec: 'Hàng xóm', name: 'Câu 3', pts: 1,
      text: 'Khi vui chơi ở gần nhà vào buổi trưa, em nên thế nào?',
      opts: o4('Hò hét thật to', 'Bật nhạc thật lớn', 'Chơi vừa phải, giữ yên tĩnh cho mọi người nghỉ', 'Đập cửa nhà hàng xóm'), ans: 'C',
      why: 'Giữ yên tĩnh giờ nghỉ trưa là biết tôn trọng và quan tâm đến hàng xóm.' },
    { sec: 'Hàng xóm', name: 'Câu 4', pts: 1,
      text: 'Nhà hàng xóm đang phơi quần áo mà trời bất chợt đổ mưa, người lớn đi vắng. Em nên làm gì?',
      opts: o4('Mặc kệ cho ướt', 'Cười vì thấy vui', 'Chạy đi chơi chỗ khác', 'Báo người lớn hoặc giúp thu quần áo vào'), ans: 'D',
      why: 'Giúp thu quần áo hoặc báo người lớn là hành động quan tâm, giúp đỡ hàng xóm.' },
    { sec: 'Hàng xóm', name: 'Câu 5', pts: 1,
      text: 'Em bé nhà bên bị ngã khóc mà không có ai ở gần. Em nên làm gì?',
      opts: o4('Đỡ em dậy, dỗ em và gọi người lớn', 'Cười nhạo em bé', 'Bỏ đi chỗ khác', 'Trêu cho em khóc to hơn'), ans: 'A',
      why: 'Đỡ em dậy, dỗ dành và gọi người lớn là cách cư xử tử tế với hàng xóm.' },
    { sec: 'Hàng xóm', name: 'Câu 6', pts: 1,
      text: 'Vì sao cần sống hoà thuận với hàng xóm láng giềng?',
      opts: o4('Để khoe khoang', 'Để mọi người giúp đỡ, yêu thương nhau khi cần', 'Để tranh giành đồ', 'Không có lí do gì'), ans: 'B',
      why: 'Hàng xóm hoà thuận thì lúc khó khăn, hoạn nạn mới giúp đỡ, đùm bọc lẫn nhau.' },
    { sec: 'Hàng xóm', name: 'Câu 7', pts: 1,
      text: 'Hành vi nào làm mất lòng hàng xóm?',
      opts: o4('Chào hỏi lễ phép', 'Giúp đỡ khi cần', 'Vứt rác sang sân nhà người khác', 'Giữ trật tự chung'), ans: 'C',
      why: 'Vứt rác sang nhà người khác gây phiền hà, làm mất tình cảm hàng xóm.' },
    { sec: 'Hàng xóm', name: 'Câu 8', pts: 1,
      text: 'Khi hàng xóm có việc vui (đám cưới, mừng nhà mới), em nên thế nào?',
      opts: o4('Nói chung vui, chúc mừng lịch sự', 'Ghen tị, nói xấu', 'Phá đám', 'Làm ngơ'), ans: 'A',
      why: 'Chia sẻ niềm vui, chúc mừng lịch sự giúp tình làng nghĩa xóm thêm gắn bó.' },
    { sec: 'Hàng xóm', name: 'Câu 9', pts: 1,
      text: 'Bạn hàng xóm nhờ em chỉ giúp một bài toán mà em biết cách làm. Em nên làm gì?',
      opts: o4('Từ chối cho bõ ghét', 'Đòi tiền mới chỉ', 'Vui vẻ hướng dẫn bạn cùng hiểu', 'Làm hộ để bạn chép'), ans: 'C',
      why: 'Vui vẻ hướng dẫn để bạn tự hiểu vừa giúp bạn vừa thể hiện tình thân ái với hàng xóm.' },
    { sec: 'Hàng xóm', name: 'Câu 10', pts: 1,
      text: 'Câu tục ngữ nào nói về tình nghĩa hàng xóm?',
      opts: o4('Ăn quả nhớ kẻ trồng cây', 'Bán anh em xa, mua láng giềng gần', 'Có công mài sắt, có ngày nên kim', 'Đi một ngày đàng, học một sàng khôn'), ans: 'B',
      why: '"Bán anh em xa, mua láng giềng gần" nhắc ta quý trọng, gắn bó với hàng xóm.' },
  ],
},

/* ═══════════ ĐỀ 3 — HAM HỌC HỎI ═══════════ */
{
  id: 9203, title: 'Đề 3 · Ham học hỏi', time: 20,
  questions: [
    { sec: 'Ham học hỏi', name: 'Câu 1', pts: 1,
      text: 'Gặp một điều chưa biết trong bài học, em nên làm gì?',
      opts: o4('Mạnh dạn hỏi thầy cô, bạn bè hoặc tra sách', 'Bỏ qua luôn', 'Đoán bừa cho xong', 'Chép của bạn'), ans: 'A',
      why: 'Chủ động hỏi và tìm hiểu điều chưa biết là biểu hiện của tinh thần ham học hỏi.' },
    { sec: 'Ham học hỏi', name: 'Câu 2', pts: 1,
      text: 'Ham học hỏi mang lại lợi ích gì?',
      opts: o4('Làm ta mệt mỏi', 'Giúp hiểu biết ngày càng nhiều, tiến bộ hơn', 'Khiến ta chậm chạp', 'Không có ích gì'), ans: 'B',
      why: 'Ham học hỏi giúp ta hiểu biết nhiều hơn, ngày càng tiến bộ và giỏi giang.' },
    { sec: 'Ham học hỏi', name: 'Câu 3', pts: 1,
      text: 'Hành vi nào thể hiện sự ham học hỏi?',
      opts: o4('Ngủ gật trong lớp', 'Không làm bài tập', 'Đọc sách, quan sát, tìm hiểu điều mới', 'Trốn học đi chơi'), ans: 'C',
      why: 'Đọc sách, quan sát và tìm hiểu điều mới là những biểu hiện của người ham học hỏi.' },
    { sec: 'Ham học hỏi', name: 'Câu 4', pts: 1,
      text: 'Khi xem một chương trình khoa học thú vị, em nên làm gì?',
      opts: o4('Chê nhàm chán rồi tắt đi', 'Vừa xem vừa nghịch điện thoại', 'Xem qua loa rồi quên ngay', 'Chú ý xem và ghi nhớ điều mới học được'), ans: 'D',
      why: 'Chú ý và ghi nhớ điều bổ ích cho thấy em biết tận dụng cơ hội học hỏi.' },
    { sec: 'Ham học hỏi', name: 'Câu 5', pts: 1,
      text: 'Bạn hỏi em một câu mà em chưa biết. Cách ứng xử ham học hỏi là gì?',
      opts: o4('Nói bừa cho xong', 'Cùng bạn tìm hiểu để biết câu trả lời', 'Mắng bạn hỏi nhiều', 'Giả vờ đã biết'), ans: 'B',
      why: 'Cùng nhau tìm hiểu điều chưa biết vừa giúp bạn vừa giúp mình mở mang kiến thức.' },
    { sec: 'Ham học hỏi', name: 'Câu 6', pts: 1,
      text: 'Câu tục ngữ nào khuyên ta chăm học hỏi?',
      opts: o4('Đi một ngày đàng, học một sàng khôn', 'Nước chảy đá mòn', 'Gần mực thì đen', 'Chậm như rùa'), ans: 'A',
      why: '"Đi một ngày đàng, học một sàng khôn" nhắc ta đi nhiều, học nhiều thì hiểu biết thêm.' },
    { sec: 'Ham học hỏi', name: 'Câu 7', pts: 1,
      text: 'Khi làm sai một bài, người ham học hỏi sẽ làm gì?',
      opts: o4('Giấu đi không cho ai biết', 'Bỏ mặc, không sửa', 'Xem lại chỗ sai để rút kinh nghiệm', 'Xé vở đi'), ans: 'C',
      why: 'Xem lại lỗi sai để hiểu và không mắc lại là cách học tập tiến bộ.' },
    { sec: 'Ham học hỏi', name: 'Câu 8', pts: 1,
      text: 'Để ham học hỏi, em nên có thói quen nào?',
      opts: o4('Chỉ chơi game cả ngày', 'Đọc sách, đặt câu hỏi, quan sát xung quanh', 'Ngại hỏi vì sợ quê', 'Chờ người khác học hộ'), ans: 'B',
      why: 'Đọc sách, hay đặt câu hỏi và quan sát giúp em học hỏi được nhiều điều bổ ích.' },
    { sec: 'Ham học hỏi', name: 'Câu 9', pts: 1,
      text: 'Vì sao không nên xấu hổ khi hỏi điều mình chưa biết?',
      opts: o4('Vì hỏi là dại dột', 'Vì hỏi mới hiểu, không hỏi mãi không biết', 'Vì hỏi làm phiền người khác', 'Vì hỏi là kém cỏi'), ans: 'B',
      why: 'Không biết mà hỏi thì sẽ hiểu; giấu dốt không hỏi thì mãi không biết.' },
    { sec: 'Ham học hỏi', name: 'Câu 10', pts: 1,
      text: 'Bạn Lan luôn tìm tòi, hay đọc sách và hỏi thầy cô. Bạn Lan là người thế nào?',
      opts: o4('Lười biếng', 'Ham chơi', 'Ham học hỏi, đáng khen', 'Kiêu ngạo'), ans: 'C',
      why: 'Tìm tòi, đọc sách và hay hỏi là biểu hiện của người ham học hỏi, rất đáng khen.' },
  ],
},

/* ═══════════ ĐỀ 4 — GIỮ LỜI HỨA ═══════════ */
{
  id: 9204, title: 'Đề 4 · Giữ lời hứa', time: 20,
  questions: [
    { sec: 'Giữ lời hứa', name: 'Câu 1', pts: 1,
      text: 'Giữ lời hứa nghĩa là gì?',
      opts: o4('Nói rồi quên ngay', 'Làm đúng điều mình đã hứa', 'Hứa cho vui', 'Hứa nhưng không làm'), ans: 'B',
      why: 'Giữ lời hứa là thực hiện đúng điều mình đã nói, đã hứa với người khác.' },
    { sec: 'Giữ lời hứa', name: 'Câu 2', pts: 1,
      text: 'Người biết giữ lời hứa sẽ được mọi người thế nào?',
      opts: o4('Tin tưởng và quý mến', 'Xa lánh', 'Coi thường', 'Chê cười'), ans: 'A',
      why: 'Giữ lời hứa khiến mọi người tin tưởng, quý mến và tôn trọng em.' },
    { sec: 'Giữ lời hứa', name: 'Câu 3', pts: 1,
      text: 'Em hứa với mẹ sẽ học bài xong trước khi xem tivi. Em nên làm gì?',
      opts: o4('Xem tivi trước đã', 'Không học nữa', 'Chỉ học một chút rồi thôi', 'Học bài xong rồi mới xem tivi'), ans: 'D',
      why: 'Học bài xong trước rồi mới xem tivi là giữ đúng lời đã hứa với mẹ.' },
    { sec: 'Giữ lời hứa', name: 'Câu 4', pts: 1,
      text: 'Trước khi hứa điều gì, em nên làm gì?',
      opts: o4('Suy nghĩ xem mình có làm được không rồi mới hứa', 'Hứa đại cho xong', 'Hứa thật nhiều để lấy lòng', 'Hứa rồi tính sau'), ans: 'A',
      why: 'Chỉ nên hứa điều mình có thể làm được, tránh hứa suông không thực hiện.' },
    { sec: 'Giữ lời hứa', name: 'Câu 5', pts: 1,
      text: 'Em hứa cho bạn mượn truyện ngày mai. Đến hẹn em nên làm gì?',
      opts: o4('Quên luôn', 'Mang truyện đến đưa bạn như đã hứa', 'Nói dối là để quên ở nhà', 'Đổi ý không cho mượn nữa'), ans: 'B',
      why: 'Mang truyện đến cho bạn đúng hẹn là giữ lời hứa và giữ được lòng tin của bạn.' },
    { sec: 'Giữ lời hứa', name: 'Câu 6', pts: 1,
      text: 'Nếu vì lí do bất ngờ mà không thực hiện được lời hứa, em nên làm gì?',
      opts: o4('Im lặng luôn', 'Trốn tránh bạn', 'Đổ lỗi cho người khác', 'Xin lỗi, giải thích và hẹn dịp khác'), ans: 'D',
      why: 'Khi không giữ được lời hứa, cần xin lỗi chân thành, giải thích rõ và tìm cách bù lại.' },
    { sec: 'Giữ lời hứa', name: 'Câu 7', pts: 1,
      text: 'Bạn Nam hứa giúp bạn trực nhật nhưng lại bỏ về sớm đi chơi. Việc làm của Nam là gì?',
      opts: o4('Không giữ lời hứa, đáng chê', 'Rất tốt', 'Bình thường', 'Đáng khen'), ans: 'A',
      why: 'Hứa rồi bỏ đi chơi là thất hứa, làm bạn thất vọng và mất lòng tin.' },
    { sec: 'Giữ lời hứa', name: 'Câu 8', pts: 1,
      text: 'Giữ lời hứa giúp em rèn luyện đức tính gì?',
      opts: o4('Ích kỉ', 'Trung thực, có trách nhiệm', 'Lười biếng', 'Kiêu căng'), ans: 'B',
      why: 'Biết giữ lời hứa giúp em trở thành người trung thực và có trách nhiệm.' },
    { sec: 'Giữ lời hứa', name: 'Câu 9', pts: 1,
      text: 'Em nên hứa như thế nào là đúng?',
      opts: o4('Hứa thật nhiều điều dù không làm được', 'Hứa để người khác vui lòng thôi', 'Chỉ hứa điều đúng đắn và làm được', 'Hứa rồi quên'), ans: 'C',
      why: 'Chỉ nên hứa những điều đúng đắn, phù hợp và bản thân có thể thực hiện.' },
    { sec: 'Giữ lời hứa', name: 'Câu 10', pts: 1,
      text: 'Vì sao thất hứa nhiều lần là điều không tốt?',
      opts: o4('Vì sẽ mất lòng tin của mọi người', 'Vì tốn thời gian', 'Vì làm ta vui', 'Vì không sao cả'), ans: 'A',
      why: 'Thất hứa nhiều lần khiến mọi người không còn tin tưởng và xa lánh em.' },
  ],
},

/* ═══════════ ĐỀ 5 — TÍCH CỰC HOÀN THÀNH NHIỆM VỤ ═══════════ */
{
  id: 9205, title: 'Đề 5 · Tích cực hoàn thành nhiệm vụ', time: 20,
  questions: [
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 1', pts: 1,
      text: 'Được cô giao làm tổ trưởng nhắc bạn giữ trật tự, em nên thế nào?',
      opts: o4('Cố gắng làm tốt nhiệm vụ được giao', 'Bỏ mặc không nhắc ai', 'Chỉ lo chơi', 'Nhờ bạn khác làm hộ'), ans: 'A',
      why: 'Tích cực, có trách nhiệm hoàn thành nhiệm vụ được giao là điều đáng khen.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 2', pts: 1,
      text: 'Đến phiên em trực nhật lớp, em nên làm gì?',
      opts: o4('Đến muộn cho bạn làm hết', 'Đến sớm quét lớp, lau bảng sạch sẽ', 'Trốn không trực', 'Làm qua loa'), ans: 'B',
      why: 'Đến sớm và làm sạch lớp là hoàn thành tốt nhiệm vụ trực nhật của mình.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 3', pts: 1,
      text: 'Ở nhà, việc nào phù hợp để em giúp đỡ bố mẹ?',
      opts: o4('Làm hỏng đồ đạc', 'Chỉ ngồi xem tivi', 'Quét nhà, gấp quần áo, tưới cây', 'Bày bừa đồ chơi'), ans: 'C',
      why: 'Quét nhà, gấp quần áo, tưới cây là những việc nhỏ vừa sức giúp đỡ bố mẹ.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 4', pts: 1,
      text: 'Cô giao bài tập về nhà, em nên làm gì?',
      opts: o4('Chờ đến lớp chép của bạn', 'Không làm', 'Làm dở rồi bỏ', 'Tự giác làm đầy đủ, đúng hạn'), ans: 'D',
      why: 'Tự giác làm bài đầy đủ và đúng hạn là hoàn thành tốt nhiệm vụ học tập.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 5', pts: 1,
      text: 'Khi làm việc nhóm, mỗi bạn nên thế nào?',
      opts: o4('Làm tốt phần việc của mình, giúp đỡ nhau', 'Ỷ lại cho bạn khác', 'Chỉ ngồi chơi', 'Tranh cãi không làm'), ans: 'A',
      why: 'Mỗi người hoàn thành phần việc của mình và hỗ trợ nhau thì cả nhóm mới thành công.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 6', pts: 1,
      text: 'Việc được giao còn dang dở nhưng đến giờ đi chơi, em nên làm gì?',
      opts: o4('Bỏ đó đi chơi ngay', 'Nhờ người khác làm nốt', 'Cố gắng làm xong rồi mới đi chơi', 'Để đấy mai làm'), ans: 'C',
      why: 'Hoàn thành công việc rồi mới nghỉ ngơi, vui chơi là biểu hiện của sự trách nhiệm.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 7', pts: 1,
      text: 'Tích cực hoàn thành nhiệm vụ giúp em điều gì?',
      opts: o4('Bị mọi người chê', 'Được tin tưởng, tiến bộ và tự tin hơn', 'Mất thời gian vô ích', 'Trở nên lười biếng'), ans: 'B',
      why: 'Hoàn thành tốt nhiệm vụ giúp em được tin tưởng, tiến bộ và thêm tự tin.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 8', pts: 1,
      text: 'Bạn nhờ em làm chung bài nhóm nhưng em chỉ ngồi chơi để bạn làm hết. Việc đó là gì?',
      opts: o4('Ỷ lại, thiếu trách nhiệm', 'Rất khéo léo', 'Đáng khen', 'Thông minh'), ans: 'A',
      why: 'Để bạn làm hết còn mình ngồi chơi là ỷ lại, thiếu trách nhiệm với công việc chung.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 9', pts: 1,
      text: 'Gặp việc khó khi làm nhiệm vụ, em nên làm gì?',
      opts: o4('Bỏ cuộc ngay', 'Khóc lóc', 'Kiên trì cố gắng, nhờ người lớn hướng dẫn', 'Đổ lỗi cho người khác'), ans: 'C',
      why: 'Kiên trì cố gắng và biết nhờ chỉ dẫn giúp em vượt khó, hoàn thành nhiệm vụ.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 10', pts: 1,
      text: 'Sau khi hoàn thành tốt việc được giao, em cảm thấy thế nào?',
      opts: o4('Vui vẻ, tự hào về bản thân', 'Buồn chán', 'Hối hận', 'Mệt mỏi và tiếc nuối'), ans: 'A',
      why: 'Hoàn thành tốt nhiệm vụ đem lại niềm vui và sự tự hào chính đáng về bản thân.' },
  ],
},

/* ═══════════ ĐỀ 6 — XỬ LÍ BẤT HOÀ VỚI BẠN BÈ ═══════════ */
{
  id: 9206, title: 'Đề 6 · Xử lí bất hoà với bạn bè', time: 20,
  questions: [
    { sec: 'Xử lí bất hoà', name: 'Câu 1', pts: 1,
      text: 'Khi giận nhau với bạn, cách xử lí nào là tốt nhất?',
      opts: o4('Bình tĩnh nói chuyện, giải thích để hiểu nhau', 'Đánh nhau', 'Chửi mắng bạn', 'Rủ bạn khác cô lập bạn ấy'), ans: 'A',
      why: 'Bình tĩnh nói chuyện, giải thích rõ ràng giúp hai bên hiểu nhau và làm hoà.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 2', pts: 1,
      text: 'Nếu em nhận ra mình sai trong lúc cãi nhau với bạn, em nên làm gì?',
      opts: o4('Vẫn cãi cho thắng', 'Chủ động xin lỗi bạn', 'Giận luôn không nói chuyện', 'Đổ lỗi cho bạn'), ans: 'B',
      why: 'Nhận ra mình sai thì nên chủ động xin lỗi để hàn gắn tình bạn.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 3', pts: 1,
      text: 'Hai bạn trong lớp cãi nhau, em nên làm gì?',
      opts: o4('Cổ vũ cho hai bạn đánh nhau', 'Đứng xem cho vui', 'Can ngăn, khuyên hai bạn bình tĩnh làm hoà', 'Kể lại cho cả lớp cười'), ans: 'C',
      why: 'Can ngăn và khuyên hai bạn bình tĩnh làm hoà là cách ứng xử đúng đắn.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 4', pts: 1,
      text: 'Bạn vô tình làm rơi hộp bút của em xuống đất. Em nên làm gì?',
      opts: o4('Mắng bạn thậm tệ', 'Đẩy ngã bạn', 'Giận không thèm nói chuyện', 'Nhắc nhẹ nhàng và cùng bạn nhặt lên'), ans: 'D',
      why: 'Bạn chỉ vô tình, nên nhắc nhẹ nhàng và cùng nhặt lên thay vì nổi giận.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 5', pts: 1,
      text: 'Khi có bất hoà mà không tự giải quyết được, em nên làm gì?',
      opts: o4('Nhờ thầy cô hoặc người lớn giúp đỡ', 'Rủ người ngoài đến đánh bạn', 'Giữ trong lòng rồi thù ghét', 'Nói xấu bạn khắp nơi'), ans: 'A',
      why: 'Nhờ thầy cô, người lớn giúp đỡ là cách giải quyết mâu thuẫn an toàn, đúng đắn.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 6', pts: 1,
      text: 'Vì sao nên làm hoà sau khi cãi nhau với bạn?',
      opts: o4('Để bạn sợ mình', 'Để giữ tình bạn và vui vẻ trở lại', 'Để khoe với người khác', 'Không cần làm hoà'), ans: 'B',
      why: 'Làm hoà giúp giữ gìn tình bạn và mọi người lại vui vẻ, gắn bó với nhau.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 7', pts: 1,
      text: 'Cách nào KHÔNG nên dùng khi có bất hoà với bạn?',
      opts: o4('Nói chuyện nhẹ nhàng', 'Nhờ người lớn hoà giải', 'Dùng nắm đấm để giải quyết', 'Cùng nhau nhận lỗi'), ans: 'C',
      why: 'Dùng bạo lực để giải quyết mâu thuẫn là sai, có thể gây thương tích và mất tình bạn.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 8', pts: 1,
      text: 'Bạn hiểu lầm và giận em. Em nên làm gì?',
      opts: o4('Giận lại cho bõ', 'Mặc kệ bạn', 'Bình tĩnh giải thích để bạn hiểu đúng', 'Nói xấu bạn'), ans: 'C',
      why: 'Bình tĩnh giải thích giúp bạn hiểu đúng sự việc và xoá bỏ hiểu lầm.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 9', pts: 1,
      text: 'Khi đang tức giận, em nên làm gì trước khi nói với bạn?',
      opts: o4('Hét thật to', 'Hít thở sâu, bình tĩnh lại rồi mới nói', 'Ném đồ đạc', 'Bỏ chạy'), ans: 'B',
      why: 'Bình tĩnh lại trước khi nói giúp tránh những lời nói, hành động làm tổn thương bạn.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 10', pts: 1,
      text: 'Tình bạn đẹp được xây dựng dựa trên điều gì?',
      opts: o4('Tôn trọng, tha thứ và cảm thông cho nhau', 'Hơn thua, ganh ghét', 'Nói xấu sau lưng', 'Tranh giành đồ chơi'), ans: 'A',
      why: 'Tôn trọng, biết tha thứ và cảm thông là nền tảng của một tình bạn đẹp và bền lâu.' },
  ],
},

/* ═══════════ ĐỀ 7 — AN TOÀN GIAO THÔNG ═══════════ */
{
  id: 9207, title: 'Đề 7 · Tuân thủ quy tắc an toàn giao thông', time: 20,
  questions: [
    { sec: 'An toàn giao thông', name: 'Câu 1', pts: 1,
      text: 'Khi đi bộ trên đường có vỉa hè, em nên đi ở đâu?',
      opts: o4('Đi trên vỉa hè', 'Đi giữa lòng đường', 'Đi sát giữa đường', 'Đi hàng ba, hàng bốn dưới lòng đường'), ans: 'A',
      why: 'Người đi bộ phải đi trên vỉa hè để bảo đảm an toàn.' },
    { sec: 'An toàn giao thông', name: 'Câu 2', pts: 1,
      text: 'Đèn tín hiệu giao thông màu đỏ báo hiệu điều gì?',
      opts: o4('Được đi', 'Dừng lại', 'Đi thật nhanh', 'Chuẩn bị đi'), ans: 'B',
      why: 'Đèn đỏ báo hiệu các phương tiện và người đi bộ phải dừng lại.' },
    { sec: 'An toàn giao thông', name: 'Câu 3', pts: 1,
      text: 'Khi muốn qua đường, em nên đi ở đâu?',
      opts: o4('Trèo qua dải phân cách', 'Chạy băng qua bất cứ chỗ nào', 'Qua đúng vạch kẻ dành cho người đi bộ', 'Qua giữa dòng xe'), ans: 'C',
      why: 'Qua đường đúng vạch kẻ dành cho người đi bộ (và khi có đèn xanh) là an toàn nhất.' },
    { sec: 'An toàn giao thông', name: 'Câu 4', pts: 1,
      text: 'Khi ngồi trên xe máy, để an toàn em cần làm gì?',
      opts: o4('Không cần gì cả', 'Đứng lên cho vui', 'Thò tay ra ngoài', 'Đội mũ bảo hiểm và ngồi ngay ngắn'), ans: 'D',
      why: 'Đội mũ bảo hiểm và ngồi ngay ngắn giúp bảo vệ em khi ngồi trên xe máy.' },
    { sec: 'An toàn giao thông', name: 'Câu 5', pts: 1,
      text: 'Hành vi nào là KHÔNG an toàn khi tham gia giao thông?',
      opts: o4('Đá bóng, chơi đùa dưới lòng đường', 'Đi bộ trên vỉa hè', 'Qua đường khi đèn xanh', 'Đội mũ bảo hiểm'), ans: 'A',
      why: 'Chơi đùa dưới lòng đường rất nguy hiểm, dễ bị xe đâm phải.' },
    { sec: 'An toàn giao thông', name: 'Câu 6', pts: 1,
      text: 'Trên đường không có vỉa hè, người đi bộ nên đi thế nào?',
      opts: o4('Đi giữa đường', 'Đi sát mép đường bên phải', 'Đi thành hàng ngang', 'Vừa đi vừa nô đùa'), ans: 'B',
      why: 'Nơi không có vỉa hè, người đi bộ phải đi sát mép đường bên phải để tránh xe cộ.' },
    { sec: 'An toàn giao thông', name: 'Câu 7', pts: 1,
      text: 'Thấy bạn định chạy qua đường lúc đèn đỏ, em nên làm gì?',
      opts: o4('Chạy theo bạn', 'Cổ vũ bạn', 'Cười chê bạn nhát', 'Ngăn bạn lại và nhắc chờ đèn xanh'), ans: 'D',
      why: 'Ngăn bạn và nhắc chờ đèn xanh là biết bảo vệ an toàn cho bạn và mọi người.' },
    { sec: 'An toàn giao thông', name: 'Câu 8', pts: 1,
      text: 'Vì sao phải tuân thủ quy tắc giao thông?',
      opts: o4('Để bảo vệ an toàn cho mình và mọi người', 'Để đi nhanh hơn', 'Để được khen', 'Không có lí do gì'), ans: 'A',
      why: 'Tuân thủ luật giao thông giúp tránh tai nạn, bảo vệ an toàn cho mình và người khác.' },
    { sec: 'An toàn giao thông', name: 'Câu 9', pts: 1,
      text: 'Khi đi xe đạp trên đường, em nên thế nào?',
      opts: o4('Buông cả hai tay', 'Đi hàng đôi, hàng ba', 'Đi đúng phần đường, không lạng lách', 'Đua xe với bạn'), ans: 'C',
      why: 'Đi đúng phần đường, không lạng lách hay buông tay giúp em đi xe đạp an toàn.' },
    { sec: 'An toàn giao thông', name: 'Câu 10', pts: 1,
      text: 'Đèn tín hiệu màu xanh cho phép em làm gì?',
      opts: o4('Được đi', 'Dừng lại', 'Chờ đợi', 'Quay đầu lại'), ans: 'A',
      why: 'Đèn xanh báo hiệu được phép đi, nhưng vẫn phải quan sát cẩn thận.' },
  ],
},

/* ═══════════ ĐỀ 8 — AN TOÀN Ở NHÀ VÀ NƠI CÔNG CỘNG ═══════════ */
{
  id: 9208, title: 'Đề 8 · An toàn ở nhà và nơi công cộng', time: 20,
  questions: [
    { sec: 'An toàn ở nhà', name: 'Câu 1', pts: 1,
      text: 'Thấy ổ điện trong tầm tay, em nên làm gì?',
      opts: o4('Không thọc tay, không cắm vật lạ vào ổ điện', 'Thọc que sắt vào cho vui', 'Nghịch dây điện', 'Cắm nhiều đồ vào một ổ'), ans: 'A',
      why: 'Không thọc tay hay vật lạ vào ổ điện để tránh bị điện giật nguy hiểm.' },
    { sec: 'An toàn ở nhà', name: 'Câu 2', pts: 1,
      text: 'Với dao, kéo, vật sắc nhọn ở nhà, em nên thế nào?',
      opts: o4('Dùng để đùa nghịch', 'Cẩn thận khi dùng, cất đúng nơi quy định', 'Ném cho nhau bắt', 'Để bừa trên sàn'), ans: 'B',
      why: 'Dao, kéo cần dùng cẩn thận và cất gọn đúng chỗ để tránh bị đứt tay, gây tai nạn.' },
    { sec: 'An toàn ở nhà', name: 'Câu 3', pts: 1,
      text: 'Khi ở nhà một mình, người lạ gõ cửa đòi vào, em nên làm gì?',
      opts: o4('Mở cửa cho vào ngay', 'Mời người lạ vào nhà chơi', 'Không mở cửa, gọi điện báo bố mẹ', 'Đi theo người lạ'), ans: 'C',
      why: 'Không mở cửa cho người lạ và báo ngay cho bố mẹ để giữ an toàn cho bản thân.' },
    { sec: 'An toàn ở nhà', name: 'Câu 4', pts: 1,
      text: 'Với nồi nước, ấm nước đang sôi trên bếp, em nên thế nào?',
      opts: o4('Sờ vào xem có nóng không', 'Bê chạy quanh nhà', 'Nghịch nắp nồi', 'Tránh xa, không lại gần để khỏi bị bỏng'), ans: 'D',
      why: 'Tránh xa nồi, ấm đang sôi để không bị nước sôi hay hơi nóng làm bỏng.' },
    { sec: 'Nơi công cộng', name: 'Câu 5', pts: 1,
      text: 'Ở nơi công cộng (công viên, siêu thị), em nên cư xử thế nào?',
      opts: o4('Giữ trật tự, không chen lấn, xô đẩy', 'Chạy nhảy la hét', 'Chen lấn giành chỗ', 'Vứt rác bừa bãi'), ans: 'A',
      why: 'Giữ trật tự, không chen lấn xô đẩy là cách cư xử văn minh nơi công cộng.' },
    { sec: 'Nơi công cộng', name: 'Câu 6', pts: 1,
      text: 'Khi đi bơi ở hồ, bể bơi, để an toàn em cần làm gì?',
      opts: o4('Bơi ra chỗ nước sâu một mình', 'Chỉ bơi khi có người lớn trông và ở khu vực an toàn', 'Xô bạn xuống nước', 'Lặn thật lâu để thử sức'), ans: 'B',
      why: 'Chỉ bơi khi có người lớn trông coi và ở nơi an toàn để tránh đuối nước.' },
    { sec: 'Nơi công cộng', name: 'Câu 7', pts: 1,
      text: 'Nếu bị lạc bố mẹ ở nơi đông người, em nên làm gì?',
      opts: o4('Khóc và chạy lung tung tìm', 'Đi theo một người lạ bất kì', 'Đứng yên hoặc tìm chú bảo vệ, cô bán hàng nhờ giúp', 'Trốn vào góc khuất'), ans: 'C',
      why: 'Đứng yên tại chỗ hoặc nhờ bảo vệ, nhân viên giúp là cách an toàn khi bị lạc.' },
    { sec: 'An toàn ở nhà', name: 'Câu 8', pts: 1,
      text: 'Thấy em nhỏ định cho hạt, đồ chơi nhỏ vào miệng, em nên làm gì?',
      opts: o4('Kệ em', 'Cho em thêm nhiều hạt hơn', 'Cười cho vui', 'Ngăn lại và lấy ra vì dễ bị hóc, nghẹn'), ans: 'D',
      why: 'Vật nhỏ dễ làm trẻ bị hóc, nghẹn rất nguy hiểm nên phải ngăn lại kịp thời.' },
    { sec: 'Nơi công cộng', name: 'Câu 9', pts: 1,
      text: 'Khi đi thang cuốn ở siêu thị, em nên thế nào?',
      opts: o4('Đứng vững, bám tay vịn, không đùa nghịch', 'Nhảy nhót trên bậc thang', 'Ngồi lên bậc thang', 'Chạy ngược chiều'), ans: 'A',
      why: 'Đứng vững và bám tay vịn, không đùa nghịch giúp tránh té ngã trên thang cuốn.' },
    { sec: 'An toàn ở nhà', name: 'Câu 10', pts: 1,
      text: 'Vì sao cần tuân thủ các quy tắc an toàn?',
      opts: o4('Để phòng tránh tai nạn, bảo vệ bản thân và mọi người', 'Để bị người khác chê', 'Để mất thời gian', 'Không cần thiết'), ans: 'A',
      why: 'Tuân thủ quy tắc an toàn giúp phòng tránh tai nạn, bảo vệ bản thân và mọi người.' },
  ],
},

/* ═══════════ ĐỀ 9 — TỔNG HỢP CÁC CHỦ ĐỀ (1) ═══════════ */
{
  id: 9209, title: 'Đề 9 · Ôn tập tổng hợp (1)', time: 20,
  questions: [
    { sec: 'Yêu Tổ quốc', name: 'Câu 1', pts: 1,
      text: 'Việc làm nào thể hiện lòng yêu quê hương, đất nước?',
      opts: o4('Giữ gìn cảnh đẹp, bảo vệ môi trường quê hương', 'Vẽ bậy lên di tích', 'Vứt rác xuống sông', 'Bẻ cây, hái hoa nơi công cộng'), ans: 'A',
      why: 'Giữ gìn cảnh đẹp và bảo vệ môi trường quê hương là biểu hiện của tình yêu đất nước.' },
    { sec: 'Hàng xóm', name: 'Câu 2', pts: 1,
      text: 'Bác hàng xóm xách đồ nặng, em nên làm gì?',
      opts: o4('Đứng nhìn', 'Chạy đi chỗ khác', 'Lễ phép hỏi và giúp bác xách đỡ', 'Trêu bác'), ans: 'C',
      why: 'Giúp bác hàng xóm xách đồ là hành động lễ phép, biết quan tâm người xung quanh.' },
    { sec: 'Ham học hỏi', name: 'Câu 3', pts: 1,
      text: 'Người ham học hỏi thường có biểu hiện nào?',
      opts: o4('Lười đọc sách', 'Ngại hỏi han', 'Sợ điều mới lạ', 'Thích tìm tòi, khám phá điều mới'), ans: 'D',
      why: 'Thích tìm tòi, khám phá điều mới là biểu hiện rõ nhất của người ham học hỏi.' },
    { sec: 'Giữ lời hứa', name: 'Câu 4', pts: 1,
      text: 'Người luôn giữ lời hứa là người thế nào?',
      opts: o4('Đáng tin cậy', 'Hay nói dối', 'Thiếu trách nhiệm', 'Ba hoa'), ans: 'A',
      why: 'Người biết giữ lời hứa là người đáng tin cậy, được mọi người quý mến.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 5', pts: 1,
      text: 'Được phân công tưới cây ở lớp, em nên làm gì?',
      opts: o4('Quên luôn', 'Nhờ bạn làm hộ', 'Tự giác tưới cây đều đặn mỗi ngày', 'Chỉ làm khi cô nhắc'), ans: 'C',
      why: 'Tự giác hoàn thành việc được giao đều đặn là biết có trách nhiệm.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 6', pts: 1,
      text: 'Cách tốt nhất để giữ tình bạn khi có mâu thuẫn là gì?',
      opts: o4('Im lặng thù ghét', 'Đánh nhau', 'Nói xấu bạn', 'Bình tĩnh nói chuyện và cùng làm hoà'), ans: 'D',
      why: 'Bình tĩnh trò chuyện và cùng làm hoà giúp giữ gìn tình bạn tốt đẹp.' },
    { sec: 'An toàn giao thông', name: 'Câu 7', pts: 1,
      text: 'Khi qua đường, ngoài đi đúng vạch, em cần làm gì?',
      opts: o4('Quan sát cẩn thận cả hai phía trước khi qua', 'Nhắm mắt chạy qua', 'Vừa đi vừa xem điện thoại', 'Chạy thật nhanh không nhìn'), ans: 'A',
      why: 'Quan sát cẩn thận hai phía trước khi qua đường giúp tránh tai nạn giao thông.' },
    { sec: 'An toàn ở nhà', name: 'Câu 8', pts: 1,
      text: 'Ở nhà một mình, nếu ngửi thấy mùi khí ga, em nên làm gì?',
      opts: o4('Bật quạt điện lên', 'Bật bếp thử xem', 'Khoá van ga, mở cửa cho thoáng và báo người lớn', 'Đóng kín cửa lại'), ans: 'C',
      why: 'Khoá van ga, mở cửa cho thoáng và báo người lớn (không bật điện) để tránh cháy nổ.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 9', pts: 1,
      text: 'Khi hát Quốc ca, giọng hát của em nên thế nào?',
      opts: o4('Hát to, rõ ràng, trang nghiêm', 'Hát nhại cho vui', 'Hát nhỏ như không hát', 'Không hát, chỉ đứng chơi'), ans: 'A',
      why: 'Hát Quốc ca to, rõ, trang nghiêm thể hiện lòng tôn kính với Tổ quốc.' },
    { sec: 'Hàng xóm', name: 'Câu 10', pts: 1,
      text: 'Tình cảm tốt đẹp giữa những người hàng xóm với nhau gọi là gì?',
      opts: o4('Sự ganh ghét', 'Tình làng nghĩa xóm', 'Sự xa cách', 'Sự thờ ơ'), ans: 'B',
      why: 'Tình cảm gắn bó, giúp đỡ nhau giữa hàng xóm được gọi là tình làng nghĩa xóm.' },
  ],
},

/* ═══════════ ĐỀ 10 — TỔNG HỢP CÁC CHỦ ĐỀ (2) ═══════════ */
{
  id: 9210, title: 'Đề 10 · Ôn tập tổng hợp (2)', time: 20,
  questions: [
    { sec: 'Ham học hỏi', name: 'Câu 1', pts: 1,
      text: 'Câu nào đúng về việc học hỏi?',
      opts: o4('Học ở trường, học ở sách và học từ cuộc sống', 'Chỉ cần học ở trường là đủ', 'Không cần học gì cả', 'Học một lần là biết hết'), ans: 'A',
      why: 'Ta có thể học hỏi ở khắp nơi: trường lớp, sách vở và từ cuộc sống hằng ngày.' },
    { sec: 'Giữ lời hứa', name: 'Câu 2', pts: 1,
      text: 'Hứa với thầy cô sẽ sửa lỗi, em cần làm gì?',
      opts: o4('Hứa cho xong', 'Quên đi', 'Thực sự cố gắng sửa lỗi đã hứa', 'Tái phạm nhiều lần'), ans: 'C',
      why: 'Đã hứa sửa lỗi thì phải thực sự cố gắng thực hiện, đó là giữ lời hứa.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 3', pts: 1,
      text: 'Việc học tập chăm chỉ mỗi ngày là nhiệm vụ của ai?',
      opts: o4('Của thầy cô', 'Của bố mẹ', 'Của người lớn', 'Của chính mỗi học sinh'), ans: 'D',
      why: 'Học tập chăm chỉ là nhiệm vụ chính của mỗi học sinh, cần tự giác thực hiện.' },
    { sec: 'Xử lí bất hoà', name: 'Câu 4', pts: 1,
      text: 'Khi bạn xin lỗi vì đã trót làm em buồn, em nên làm gì?',
      opts: o4('Vui vẻ tha thứ và làm hoà với bạn', 'Vẫn giận mãi', 'Đòi bạn phải đền', 'Mách khắp nơi'), ans: 'A',
      why: 'Biết tha thứ khi bạn đã xin lỗi giúp tình bạn thêm gắn bó, tốt đẹp.' },
    { sec: 'An toàn giao thông', name: 'Câu 5', pts: 1,
      text: 'Nơi nào là an toàn để chơi đùa, chạy nhảy?',
      opts: o4('Trên lòng đường', 'Sân chơi, sân trường, công viên', 'Đường ray xe lửa', 'Gần ao hồ sâu'), ans: 'B',
      why: 'Sân chơi, sân trường, công viên là những nơi an toàn để vui chơi.' },
    { sec: 'An toàn ở nhà', name: 'Câu 6', pts: 1,
      text: 'Người lạ cho em quà bánh và rủ đi chơi, em nên làm gì?',
      opts: o4('Nhận quà và đi ngay', 'Đi theo vì tò mò', 'Từ chối, không đi theo và báo người lớn', 'Rủ thêm bạn cùng đi'), ans: 'C',
      why: 'Không nhận quà, không đi theo người lạ và báo người lớn để giữ an toàn cho bản thân.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 7', pts: 1,
      text: 'Học sinh thể hiện lòng biết ơn các anh hùng liệt sĩ bằng cách nào?',
      opts: o4('Chăm học, viếng nghĩa trang liệt sĩ, giữ gìn đất nước', 'Quên lãng công ơn', 'Phá hoại tượng đài', 'Không quan tâm'), ans: 'A',
      why: 'Chăm học và tưởng nhớ, viếng nghĩa trang liệt sĩ là cách bày tỏ lòng biết ơn người có công.' },
    { sec: 'Hàng xóm', name: 'Câu 8', pts: 1,
      text: 'Việc làm nào giúp tình hàng xóm thêm gắn bó?',
      opts: o4('Tranh giành với hàng xóm', 'Chào hỏi, giúp đỡ và chia sẻ với nhau', 'Cãi vã, to tiếng', 'Đóng cửa không giao lưu'), ans: 'B',
      why: 'Chào hỏi, giúp đỡ và chia sẻ khiến tình cảm hàng xóm ngày càng gắn bó.' },
    { sec: 'Ham học hỏi', name: 'Câu 9', pts: 1,
      text: 'Bạn không biết mà giả vờ đã biết, không chịu hỏi. Đó là biểu hiện gì?',
      opts: o4('Ham học hỏi', 'Khiêm tốn', 'Giấu dốt, không ham học hỏi', 'Thông minh'), ans: 'C',
      why: 'Giấu dốt, không chịu hỏi khiến ta mãi không hiểu biết — đó là điều nên tránh.' },
    { sec: 'Hoàn thành nhiệm vụ', name: 'Câu 10', pts: 1,
      text: 'Là một người con ngoan, trò giỏi, em cần rèn luyện điều gì?',
      opts: o4('Chăm học, chăm làm, thật thà, có trách nhiệm', 'Lười biếng, ham chơi', 'Nói dối, ỷ lại', 'Bỏ bê việc nhà, việc học'), ans: 'A',
      why: 'Chăm học, chăm làm, thật thà và có trách nhiệm giúp em trở thành con ngoan, trò giỏi.' },
  ],
},

];

SUBJECTS.push({ id:'daoduc3', name:'Đạo đức', short:'Đạo đức 3', icon:'❤️', grade:3, exams:DAODUC3_EXAMS, ready:true, heroTitle:'Đạo đức lớp 3 — yêu Tổ quốc, quan tâm hàng xóm, ham học hỏi, giữ lời hứa và xử lí bất hoà', heroMeta:'📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018' });
