// FMO / TOÁN TƯ DUY LỚP 2 — BẢN HẠ ĐỘ KHÓ
// 15 chuyên đề × 15 câu = 225 câu. Mỗi đề: Phần A 10 câu × 0,6đ = 6đ · Phần B 5 câu × 0,8đ = 4đ.
// Thang 10 — 40 phút mỗi đề — 5 lựa chọn A–E theo thể lệ FMO/AMO.
//
// NGUỒN & CÁCH BIÊN SOẠN
//  Bộ đề gốc tham khảo: tuyển tập ôn thi khối 2 gồm FMO (Fermat Mathematical Olympiad —
//  Fermat Education), AMO Vietnam, ASMO, Math IQ, Magic Square/Sudoku và Toán 2 nâng cao
//  (biên soạn: Thầy Đặng Việt Hùng). Toàn bộ câu hỏi ở đây được VIẾT LẠI, không sao chép đề gốc.
//
//  ĐÃ HẠ ĐỘ KHÓ so với đề gốc theo bốn hướng:
//   1. Bỏ hẳn các dạng vượt lớp 2: xoay/lật mảnh ghép pentomino, ma trận IQ 3×3,
//      suy luận lịch nhiều tầng, cryptarithm (phép tính chữ thay số).
//   2. Rút số bước tính: mỗi câu tối đa 2–3 phép tính thay vì 4–6 như đề gốc.
//   3. Việt hoá hoàn toàn — đề gốc AMO/FMO nhiều phần chỉ có tiếng Anh.
//   4. Giữ số trong phạm vi 1 000, chỉ dùng bảng nhân chia 2–5 theo chương trình lớp 2.
//
//  Mức nhắm tới: HSG cấp trường / cấp quận — làm quen dạng bài thi tư duy quốc tế,
//  KHÔNG phải mức vòng chung kết. Hình vẽ lại bằng SVG trong assets/fmo2/.

const FM = 'assets/fmo2/';
const FM5 = (a, b, c, d, e) => [{ k: 'A', t: a }, { k: 'B', t: b }, { k: 'C', t: c }, { k: 'D', t: d }, { k: 'E', t: e }];
const FA = 'Phần A — Khởi động (6 điểm)';
const FB = 'Phần B — Tăng tốc (4 điểm)';

const FMO2_EXAMS = [

/* ═══════════ ĐỀ 1 — CÂN THĂNG BẰNG ═══════════ */
{
  id: 1001, title: 'CĐ 1 · Bài toán cân thăng bằng', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f1q1.svg',
      text: 'Cân thăng bằng. Ba quả cam nặng bằng một quả dưa 900 g. Hỏi mỗi quả cam nặng bao nhiêu gam?',
      opts: FM5('200 g', '450 g', '300 g', '600 g', '900 g'), ans: 'C',
      why: 'Ba quả cam cùng nặng và tổng bằng 900 g nên mỗi quả cam nặng: 900 : 3 = 300 (g).' },
    { sec: FA, name: 'Câu 2', pts: 0.6, img: FM + 'f1q2.svg',
      text: 'Cân thăng bằng cho biết 2 hình tròn nặng bằng 3 hình tam giác. Hỏi 4 hình tròn nặng bằng mấy hình tam giác?',
      opts: FM5('6 hình', '4 hình', '5 hình', '7 hình', '8 hình'), ans: 'A',
      why: '4 hình tròn gấp đôi 2 hình tròn nên cũng phải gấp đôi số tam giác: 3 × 2 = 6 (hình tam giác).' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Một hộp bút nặng bằng 5 viên bi. Hỏi 3 hộp bút như thế nặng bằng bao nhiêu viên bi?',
      opts: FM5('8 viên', '10 viên', '12 viên', '20 viên', '15 viên'), ans: 'E',
      why: 'Mỗi hộp bút đổi được 5 viên bi nên 3 hộp đổi được: 5 × 3 = 15 (viên bi).' },
    { sec: FA, name: 'Câu 4', pts: 0.6, img: FM + 'f1q4.svg',
      text: 'Quan sát cân. Con nào nặng hơn?',
      opts: FM5('Con mèo', 'Con chó', 'Hai con nặng bằng nhau', 'Con mèo nặng gấp đôi con chó', 'Không xác định được'), ans: 'B',
      why: 'Đĩa cân bên nào hạ thấp xuống thì bên đó nặng hơn. Đĩa có con chó hạ xuống nên con chó nặng hơn con mèo.' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Hai túi gạo loại A nặng bằng một túi gạo loại B. Túi loại B nặng 18 kg. Hỏi mỗi túi loại A nặng bao nhiêu ki-lô-gam?',
      opts: FM5('6 kg', '12 kg', '20 kg', '9 kg', '36 kg'), ans: 'D',
      why: 'Hai túi A cùng nặng và tổng bằng 18 kg nên mỗi túi A nặng: 18 : 2 = 9 (kg).' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: '5 quả táo nặng bằng 2 quả bưởi. Mỗi quả bưởi nặng 500 g. Hỏi mỗi quả táo nặng bao nhiêu gam?',
      opts: FM5('200 g', '100 g', '150 g', '250 g', '400 g'), ans: 'A',
      why: 'Hai quả bưởi nặng: 500 × 2 = 1 000 (g). Đó cũng là cân nặng của 5 quả táo, nên mỗi quả táo nặng: 1 000 : 5 = 200 (g).' },
    { sec: FA, name: 'Câu 7', pts: 0.6, img: FM + 'f1q7.svg',
      text: 'Hai cân đều thăng bằng. Hỏi 1 hình vuông nặng bằng mấy hình tam giác?',
      opts: FM5('2 hình', '3 hình', '5 hình', '4 hình', '6 hình'), ans: 'D',
      why: 'Cân thứ nhất: 1 vuông = 2 tròn. Cân thứ hai: 1 tròn = 2 tam giác. Vậy 1 vuông = 2 tròn = 2 × 2 = 4 (hình tam giác).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Một con vịt nặng bằng 2 con gà. Hỏi 3 con vịt nặng bằng mấy con gà?',
      opts: FM5('3 con', '4 con', '6 con', '5 con', '8 con'), ans: 'C',
      why: 'Mỗi con vịt đổi được 2 con gà nên 3 con vịt đổi được: 2 × 3 = 6 (con gà).' },
    { sec: FA, name: 'Câu 9', pts: 0.6, img: FM + 'f1q9.svg',
      text: 'Bốn khối vuông giống nhau nặng tất cả 12 kg. Hỏi mỗi khối vuông nặng bao nhiêu ki-lô-gam?',
      opts: FM5('2 kg', '3 kg', '4 kg', '6 kg', '8 kg'), ans: 'B',
      why: 'Bốn khối nặng như nhau nên mỗi khối nặng: 12 : 4 = 3 (kg).' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Cân thăng bằng: đĩa bên trái có 3 gói kẹo, mỗi gói nặng 200 g; đĩa bên phải chỉ có 1 gói bánh. Hỏi gói bánh nặng bao nhiêu gam?',
      opts: FM5('200 g', '400 g', '500 g', '800 g', '600 g'), ans: 'E',
      why: 'Ba gói kẹo nặng: 200 × 3 = 600 (g). Cân thăng bằng nên gói bánh cũng nặng 600 g.' },

    { sec: FB, name: 'Câu 11', pts: 0.8, img: FM + 'f1q11.svg',
      text: 'Hai cân đều thăng bằng. Hỏi hình tròn nặng bao nhiêu ki-lô-gam?',
      opts: FM5('6 kg', '12 kg', '9 kg', '10 kg', '14 kg'), ans: 'B',
      why: 'Cân thứ hai cho biết 1 tròn = 2 tam giác. Thay vào cân thứ nhất: 1 tròn + 1 tam giác = 2 tam giác + 1 tam giác = 3 tam giác = 18 kg. Vậy mỗi tam giác nặng 18 : 3 = 6 (kg) và hình tròn nặng 6 × 2 = 12 (kg).' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: '2 thùng hàng nặng bằng 3 hộp hàng. Mỗi hộp nặng 4 kg. Hỏi mỗi thùng nặng bao nhiêu ki-lô-gam?',
      opts: FM5('4 kg', '5 kg', '8 kg', '6 kg', '12 kg'), ans: 'D',
      why: 'Ba hộp nặng: 4 × 3 = 12 (kg). Đó là cân nặng của 2 thùng nên mỗi thùng nặng: 12 : 2 = 6 (kg).' },
    { sec: FB, name: 'Câu 13', pts: 0.8,
      text: '3 quyển vở nặng bằng 2 quyển sách. Hỏi 6 quyển vở nặng bằng mấy quyển sách?',
      opts: FM5('4 quyển', '3 quyển', '5 quyển', '6 quyển', '9 quyển'), ans: 'A',
      why: '6 quyển vở gấp đôi 3 quyển vở nên số sách cũng gấp đôi: 2 × 2 = 4 (quyển sách).' },
    { sec: FB, name: 'Câu 14', pts: 0.8, img: FM + 'f1q14.svg',
      text: 'Hai cân đều thăng bằng. Hỏi 1 quả dưa hấu nặng bằng mấy quả táo?',
      opts: FM5('2 quả', '3 quả', '4 quả', '6 quả', '8 quả'), ans: 'C',
      why: 'Cân thứ nhất: 2 táo = 1 lê. Cân thứ hai: 2 lê = 1 dưa hấu. Mà 2 lê đổi được 2 × 2 = 4 quả táo, nên 1 quả dưa hấu nặng bằng 4 quả táo.' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: 'Cân thăng bằng: đĩa trái có 1 quả dưa và một quả cân 2 kg; đĩa phải có 3 quả dưa giống hệt nhau. Hỏi mỗi quả dưa nặng bao nhiêu ki-lô-gam?',
      opts: FM5('2 kg', '3 kg', '4 kg', '6 kg', '1 kg'), ans: 'E',
      why: 'Bỏ bớt 1 quả dưa ở mỗi đĩa thì cân vẫn thăng bằng: quả cân 2 kg nặng bằng 2 quả dưa. Vậy mỗi quả dưa nặng: 2 : 2 = 1 (kg).' },
  ],
},

/* ═══════════ ĐỀ 2 — NGÀY THỨ VÀ LỊCH ═══════════ */
{
  id: 1002, title: 'CĐ 2 · Bài toán ngày thứ và lịch', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6,
      text: 'Hôm nay là thứ Ba. Hỏi 5 ngày nữa là thứ mấy?',
      opts: FM5('Thứ Sáu', 'Thứ Bảy', 'Thứ Hai', 'Chủ nhật', 'Thứ Năm'), ans: 'D',
      why: 'Đếm tiếp từ thứ Ba: Tư (1), Năm (2), Sáu (3), Bảy (4), Chủ nhật (5). Vậy 5 ngày nữa là Chủ nhật.' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: 'Hôm qua là thứ Sáu. Hỏi hôm nay là thứ mấy?',
      opts: FM5('Thứ Năm', 'Thứ Bảy', 'Thứ Sáu', 'Chủ nhật', 'Thứ Hai'), ans: 'B',
      why: 'Ngày liền sau thứ Sáu là thứ Bảy.' },
    { sec: FA, name: 'Câu 3', pts: 0.6, img: FM + 'f2q3.svg',
      text: 'Quan sát tờ lịch tháng 3. Hỏi ngày 10 tháng 3 là thứ mấy?',
      opts: FM5('Thứ Hai', 'Thứ Ba', 'Thứ Năm', 'Thứ Sáu', 'Thứ Tư'), ans: 'E',
      why: 'Tìm ô ghi số 10 trên lịch rồi nhìn lên hàng tên thứ ở phía trên: ô đó nằm ở cột "Tư". Vậy ngày 10 tháng 3 là thứ Tư.' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Một tuần lễ có 7 ngày. Hỏi 3 tuần lễ và 2 ngày có tất cả bao nhiêu ngày?',
      opts: FM5('23 ngày', '21 ngày', '22 ngày', '24 ngày', '32 ngày'), ans: 'A',
      why: '3 tuần có: 7 × 3 = 21 (ngày). Thêm 2 ngày nữa là: 21 + 2 = 23 (ngày).' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Hôm nay là thứ Hai. Hỏi đúng 7 ngày nữa là thứ mấy?',
      opts: FM5('Thứ Ba', 'Chủ nhật', 'Thứ Hai', 'Thứ Bảy', 'Thứ Tư'), ans: 'C',
      why: 'Cứ đúng 7 ngày (một tuần lễ) thì lại lặp lại thứ cũ. Vậy 7 ngày nữa vẫn là thứ Hai.' },
    { sec: FA, name: 'Câu 6', pts: 0.6, img: FM + 'f2q6.svg',
      text: 'Quan sát tờ lịch tháng 5. Hỏi ngày 20 tháng 5 (ô được tô vàng) là thứ mấy?',
      opts: FM5('Thứ Hai', 'Thứ Tư', 'Thứ Ba', 'Thứ Năm', 'Thứ Bảy'), ans: 'C',
      why: 'Ô số 20 nằm ở cột "Ba" trên tờ lịch. Vậy ngày 20 tháng 5 là thứ Ba.' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Ngày mai là thứ Năm. Hỏi hôm qua là thứ mấy?',
      opts: FM5('Thứ Ba', 'Thứ Hai', 'Thứ Tư', 'Thứ Sáu', 'Thứ Bảy'), ans: 'A',
      why: 'Ngày mai là thứ Năm nên hôm nay là thứ Tư, và hôm qua là thứ Ba.' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Trong một năm có bao nhiêu tháng có 31 ngày?',
      opts: FM5('4 tháng', '5 tháng', '6 tháng', '8 tháng', '7 tháng'), ans: 'E',
      why: 'Các tháng có 31 ngày là tháng 1; 3; 5; 7; 8; 10; 12 — tất cả 7 tháng.' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: 'Sinh nhật của Lan là ngày 15 tháng 6, đúng vào thứ Bảy. Hỏi ngày 22 tháng 6 là thứ mấy?',
      opts: FM5('Thứ Sáu', 'Thứ Bảy', 'Chủ nhật', 'Thứ Hai', 'Thứ Ba'), ans: 'B',
      why: 'Từ ngày 15 đến ngày 22 cách nhau 7 ngày, đúng một tuần lễ, nên ngày 22 tháng 6 cũng là thứ Bảy.' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Các bạn học sinh đi học từ thứ Hai đến hết thứ Sáu. Hỏi mỗi tuần các bạn đi học bao nhiêu ngày?',
      opts: FM5('4 ngày', '6 ngày', '7 ngày', '5 ngày', '3 ngày'), ans: 'D',
      why: 'Đếm: Hai, Ba, Tư, Năm, Sáu — tất cả 5 ngày.' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: 'Hôm nay là thứ Tư. Hỏi 15 ngày nữa là thứ mấy?',
      opts: FM5('Thứ Năm', 'Thứ Ba', 'Thứ Tư', 'Thứ Sáu', 'Thứ Bảy'), ans: 'A',
      why: 'Ta có 15 : 7 = 2 (dư 1). Sau 14 ngày (2 tuần) vẫn là thứ Tư, thêm 1 ngày nữa là thứ Năm.' },
    { sec: FB, name: 'Câu 12', pts: 0.8, img: FM + 'f2q12.svg',
      text: 'Quan sát tờ lịch tháng 9. Hỏi ngày cuối cùng của tháng 9 (ô được tô vàng) là thứ mấy?',
      opts: FM5('Thứ Hai', 'Thứ Tư', 'Thứ Năm', 'Thứ Ba', 'Chủ nhật'), ans: 'D',
      why: 'Tháng 9 có 30 ngày và trên lịch ô số 30 nằm ở cột "Ba". Vậy ngày cuối cùng của tháng 9 là thứ Ba.' },
    { sec: FB, name: 'Câu 13', pts: 0.8,
      text: 'Buổi học bơi đầu tiên của Nam vào thứ Hai, cứ cách 4 ngày lại có một buổi. Hỏi buổi học bơi <b>thứ ba</b> của Nam vào thứ mấy?',
      opts: FM5('Thứ Hai', 'Thứ Sáu', 'Thứ Ba', 'Thứ Bảy', 'Chủ nhật'), ans: 'C',
      why: 'Buổi 1 là thứ Hai. Buổi 2 sau đó 4 ngày là thứ Sáu. Buổi 3 sau buổi 2 thêm 4 ngày nữa, tức là 8 ngày kể từ thứ Hai. Vì 8 : 7 = 1 (dư 1) nên buổi 3 rơi vào thứ Ba.' },
    { sec: FB, name: 'Câu 14', pts: 0.8, img: FM + 'f2q14.svg',
      text: 'Quan sát tờ lịch tháng 3 dưới đây (tháng 3 có 31 ngày). Hỏi tháng đó có bao nhiêu ngày thứ Sáu?',
      opts: FM5('3 ngày', '5 ngày', '4 ngày', '6 ngày', '7 ngày'), ans: 'B',
      why: 'Trên lịch, các ngày thứ Sáu là 1; 8; 15; 22 và 29 (mỗi ngày cách nhau 7 ngày, đều không quá 31). Vậy tháng đó có 5 ngày thứ Sáu.' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: 'Hôm kia là thứ Bảy. Hỏi ngày mai là thứ mấy?',
      opts: FM5('Chủ nhật', 'Thứ Hai', 'Thứ Tư', 'Thứ Sáu', 'Thứ Ba'), ans: 'E',
      why: 'Hôm kia là thứ Bảy nên hôm qua là Chủ nhật, hôm nay là thứ Hai, và ngày mai là thứ Ba.' },
  ],
},

/* ═══════════ ĐỀ 3 — XẾP HÀNG VÀ THỨ TỰ ═══════════ */
{
  id: 1003, title: 'CĐ 3 · Bài toán xếp hàng và thứ tự', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6,
      text: 'Trong một hàng, bạn Nam đứng thứ 4 tính từ bên trái và thứ 3 tính từ bên phải. Hỏi hàng đó có bao nhiêu bạn?',
      opts: FM5('5 bạn', '6 bạn', '7 bạn', '8 bạn', '12 bạn'), ans: 'B',
      why: 'Nếu cộng 4 + 3 = 7 thì bạn Nam bị đếm hai lần. Số bạn trong hàng là: 4 + 3 − 1 = 6 (bạn).' },
    { sec: FA, name: 'Câu 2', pts: 0.6, img: FM + 'f3q2.svg',
      text: 'Bảy bạn xếp thành một hàng như hình. Bạn Lan đứng thứ 3 tính từ bên trái. Hỏi Lan đứng thứ mấy tính từ bên phải?',
      opts: FM5('3', '4', '6', '5', '7'), ans: 'D',
      why: 'Bên phải Lan còn 7 − 3 = 4 (bạn). Tính cả Lan thì Lan đứng thứ 4 + 1 = 5 từ bên phải.' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Một hàng có 10 bạn, bạn An đứng cuối hàng. Hỏi An đứng thứ mấy tính từ đầu hàng?',
      opts: FM5('10', '1', '5', '9', '11'), ans: 'A',
      why: 'Bạn cuối hàng chính là bạn thứ 10 nếu đếm từ đầu hàng.' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Trong một hàng, bạn An đứng thứ 2. Giữa An và Bình có đúng 3 bạn (Bình đứng sau An). Hỏi Bình đứng thứ mấy?',
      opts: FM5('4', '5', '6', '7', '8'), ans: 'C',
      why: 'Sau An (thứ 2) là 3 bạn ở giữa, tức các vị trí thứ 3; 4; 5. Bình đứng ngay sau đó nên Bình thứ 6.' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Một hàng có 12 bạn. Bạn An đứng thứ 5 tính từ bên trái. Hỏi phía sau An còn bao nhiêu bạn?',
      opts: FM5('5 bạn', '6 bạn', '8 bạn', '11 bạn', '7 bạn'), ans: 'E',
      why: 'Số bạn phía sau An là: 12 − 5 = 7 (bạn).' },
    { sec: FA, name: 'Câu 6', pts: 0.6, img: FM + 'f3q6.svg',
      text: 'Các xe xếp thành hàng như hình. Xe màu đỏ đứng thứ 3, xe màu xanh đứng thứ 6. Hỏi giữa hai xe đó có bao nhiêu xe?',
      opts: FM5('1 xe', '3 xe', '4 xe', '2 xe', '5 xe'), ans: 'D',
      why: 'Giữa vị trí thứ 3 và thứ 6 là các vị trí thứ 4 và thứ 5. Số xe ở giữa là: 6 − 3 − 1 = 2 (xe).' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: '8 bạn xếp thành một hàng dọc, hai bạn liền nhau cách nhau 2 m. Hỏi hàng đó dài bao nhiêu mét?',
      opts: FM5('10 m', '14 m', '12 m', '16 m', '18 m'), ans: 'B',
      why: '8 bạn thì có 8 − 1 = 7 (khoảng cách). Hàng dài: 2 × 7 = 14 (m).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Một hàng có 15 bạn, bạn Mai đứng đúng chính giữa hàng. Hỏi Mai đứng thứ mấy?',
      opts: FM5('7', '9', '10', '15', '8'), ans: 'E',
      why: 'Mai đứng chính giữa nên hai bên có số bạn bằng nhau: (15 − 1) : 2 = 7 (bạn mỗi bên). Vậy Mai đứng thứ 7 + 1 = 8.' },
    { sec: FA, name: 'Câu 9', pts: 0.6, img: FM + 'f3q9.svg',
      text: 'Tám chú gà con xếp thành một hàng như hình. Chú gà đứng thứ 3 tính từ bên phải là chú gà thứ mấy tính từ bên trái?',
      opts: FM5('6', '3', '4', '5', '7'), ans: 'A',
      why: 'Bên phải chú gà đó còn 2 chú. Tính từ bên trái, chú gà đó đứng thứ: 8 − 2 = 6.' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Một bạn đứng thứ 6 tính từ bên trái và cũng thứ 6 tính từ bên phải. Hỏi hàng đó có bao nhiêu bạn?',
      opts: FM5('10 bạn', '12 bạn', '11 bạn', '13 bạn', '6 bạn'), ans: 'C',
      why: 'Số bạn trong hàng là: 6 + 6 − 1 = 11 (bạn), vì bạn đó bị đếm hai lần.' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: 'Một hàng có 20 bạn. Nam đứng thứ 8 tính từ bên trái, Bắc đứng thứ 9 tính từ bên phải. Hỏi giữa Nam và Bắc có bao nhiêu bạn?',
      opts: FM5('2 bạn', '4 bạn', '3 bạn', '5 bạn', '6 bạn'), ans: 'C',
      why: 'Tính từ bên trái, Bắc đứng thứ: 20 − 9 + 1 = 12. Giữa vị trí thứ 8 và thứ 12 có: 12 − 8 − 1 = 3 (bạn).' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Các bạn xếp thành 4 hàng, mỗi hàng 6 bạn. Hỏi có tất cả bao nhiêu bạn?',
      opts: FM5('24 bạn', '10 bạn', '18 bạn', '20 bạn', '30 bạn'), ans: 'A',
      why: 'Tổng số bạn: 6 × 4 = 24 (bạn).' },
    { sec: FB, name: 'Câu 13', pts: 0.8,
      text: 'Cô giáo phát kẹo theo hàng: bạn thứ nhất được 1 cái, bạn thứ hai được 2 cái, bạn thứ ba được 3 cái… Hỏi 5 bạn đầu hàng được tất cả bao nhiêu cái kẹo?',
      opts: FM5('10 cái', '12 cái', '20 cái', '25 cái', '15 cái'), ans: 'E',
      why: 'Tổng số kẹo: 1 + 2 + 3 + 4 + 5 = 15 (cái kẹo).' },
    { sec: FB, name: 'Câu 14', pts: 0.8, img: FM + 'f3q14.svg',
      text: 'Năm quyển sách vở được xếp chồng lên nhau như hình. Hỏi phía trên quyển "Sách Toán" có bao nhiêu quyển?',
      opts: FM5('1 quyển', '2 quyển', '3 quyển', '4 quyển', '0 quyển'), ans: 'B',
      why: 'Đọc từ trên xuống: Vở Mĩ thuật, Sách Tiếng Việt, rồi mới đến Sách Toán. Vậy phía trên Sách Toán có 2 quyển.' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: 'Một hàng dọc có 9 bạn. Bạn đứng đầu hàng và bạn đứng cuối hàng đổi chỗ cho nhau. Hỏi bạn vốn đứng thứ nhất bây giờ đứng thứ mấy?',
      opts: FM5('1', '2', '8', '9', '5'), ans: 'D',
      why: 'Bạn đứng đầu chuyển xuống vị trí cuối hàng, mà hàng có 9 bạn nên vị trí cuối là thứ 9.' },
  ],
},

/* ═══════════ ĐỀ 4 — QUY LUẬT SỐ VÀ HÌNH ═══════════ */
{
  id: 1004, title: 'CĐ 4 · Quy luật số và hình', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f4q1.svg',
      text: 'Tìm số thích hợp thay cho dấu hỏi chấm.',
      opts: FM5('9', '8', '10', '11', '13'), ans: 'A',
      why: 'Mỗi số hơn số liền trước 2 đơn vị (1; 3; 5; 7). Số tiếp theo là: 7 + 2 = 9.' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: 'Số thích hợp điền tiếp vào dãy <b>2; 4; 6; 8; …</b> là:',
      opts: FM5('9', '11', '12', '10', '16'), ans: 'D',
      why: 'Đây là dãy số chẵn, mỗi số hơn số trước 2 đơn vị: 8 + 2 = 10.' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Số thích hợp điền tiếp vào dãy <b>10; 20; 30; …</b> là:',
      opts: FM5('31', '35', '40', '50', '60'), ans: 'C',
      why: 'Mỗi số hơn số trước 10 đơn vị: 30 + 10 = 40.' },
    { sec: FA, name: 'Câu 4', pts: 0.6, img: FM + 'f4q4.svg',
      text: 'Tìm số thích hợp thay cho dấu hỏi chấm.',
      opts: FM5('18', '32', '20', '24', '64'), ans: 'B',
      why: 'Mỗi số gấp đôi số liền trước: 2; 4; 8; 16. Số tiếp theo là: 16 × 2 = 32.' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Số thích hợp điền tiếp vào dãy <b>100; 90; 80; …</b> là:',
      opts: FM5('60', '75', '79', '85', '70'), ans: 'E',
      why: 'Mỗi số kém số trước 10 đơn vị: 80 − 10 = 70.' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: 'Số thích hợp điền tiếp vào dãy <b>3; 6; 9; 12; …</b> là:',
      opts: FM5('13', '15', '14', '16', '18'), ans: 'B',
      why: 'Mỗi số hơn số trước 3 đơn vị: 12 + 3 = 15.' },
    { sec: FA, name: 'Câu 7', pts: 0.6, img: FM + 'f4q7.svg',
      text: 'Các hình tròn màu được xếp lặp lại theo quy luật. Hỏi hình thứ 7 (dấu hỏi chấm) có màu gì?',
      opts: FM5('Màu xanh dương', 'Màu vàng', 'Màu xanh lá', 'Màu đỏ', 'Màu tím'), ans: 'D',
      why: 'Quy luật lặp lại theo nhóm 3 màu: đỏ – xanh dương – vàng. Ta có 7 : 3 = 2 (dư 1) nên hình thứ 7 giống hình thứ nhất của nhóm, tức là màu đỏ.' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Số thích hợp điền tiếp vào dãy <b>1; 2; 4; 7; 11; …</b> là:',
      opts: FM5('16', '14', '15', '18', '22'), ans: 'A',
      why: 'Khoảng cách tăng dần: +1; +2; +3; +4. Tiếp theo phải cộng 5: 11 + 5 = 16.' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: 'Cho dãy số <b>5; 10; 15; 20; …</b> Hỏi số hạng thứ 10 của dãy là số nào?',
      opts: FM5('40', '45', '50', '55', '60'), ans: 'C',
      why: 'Các số trong dãy lần lượt là 5 × 1; 5 × 2; 5 × 3; … nên số hạng thứ 10 là 5 × 10 = 50.' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Số thích hợp điền tiếp vào dãy <b>1; 1; 2; 3; 5; 8; …</b> là:',
      opts: FM5('10', '11', '12', '16', '13'), ans: 'E',
      why: 'Mỗi số bằng tổng hai số đứng ngay trước nó: 1 + 1 = 2; 1 + 2 = 3; 2 + 3 = 5; 3 + 5 = 8. Số tiếp theo là 5 + 8 = 13.' },

    { sec: FB, name: 'Câu 11', pts: 0.8, img: FM + 'f4q11.svg',
      text: 'Tìm số thích hợp thay cho dấu hỏi chấm.',
      opts: FM5('20', '24', '30', '25', '36'), ans: 'D',
      why: 'Các số lần lượt là 1 × 1; 2 × 2; 3 × 3; 4 × 4. Số tiếp theo là 5 × 5 = 25.' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Cho dãy số <b>2; 5; 8; 11; …</b> Hỏi số hạng thứ 8 của dãy là số nào?',
      opts: FM5('20', '23', '21', '24', '26'), ans: 'B',
      why: 'Mỗi số hơn số trước 3 đơn vị. Từ số thứ nhất đến số thứ 8 phải cộng thêm 7 lần số 3: 2 + 3 × 7 = 2 + 21 = 23.' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f4q13.svg',
      text: 'Bạn Eddy sơn các tấm ván hàng rào lặp lại theo thứ tự: <b>đỏ – xanh dương – vàng – xanh lá</b>. Hàng rào có 19 tấm ván. Hỏi tấm ván cuối cùng có màu gì?',
      opts: FM5('Màu đỏ', 'Màu xanh dương', 'Màu xanh lá', 'Không xác định được', 'Màu vàng'), ans: 'E',
      why: 'Quy luật lặp theo nhóm 4 màu. Ta có 19 : 4 = 4 (dư 3) nên tấm thứ 19 giống tấm thứ 3 của nhóm, tức là màu vàng.' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Số thích hợp điền tiếp vào dãy <b>1; 3; 6; 10; 15; …</b> là:',
      opts: FM5('21', '18', '20', '24', '25'), ans: 'A',
      why: 'Khoảng cách tăng dần: +2; +3; +4; +5. Tiếp theo phải cộng 6: 15 + 6 = 21.' },
    { sec: FB, name: 'Câu 15', pts: 0.8, img: FM + 'f4q15.svg',
      text: 'Tìm số thích hợp thay cho dấu hỏi chấm.',
      opts: FM5('12', '13', '14', '15', '16'), ans: 'C',
      why: 'Mỗi số kém số liền trước 4 đơn vị: 30; 26; 22; 18. Số tiếp theo là: 18 − 4 = 14.' },
  ],
},

/* ═══════════ ĐỀ 5 — ĐẾM HÌNH ═══════════ */
{
  id: 1005, title: 'CĐ 5 · Kỹ thuật đếm hình', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f5q1.svg',
      text: 'Trên đường thẳng có 5 điểm A, B, C, D, E như hình. Hỏi có tất cả bao nhiêu đoạn thẳng?',
      opts: FM5('5 đoạn', '8 đoạn', '10 đoạn', '15 đoạn', '20 đoạn'), ans: 'C',
      why: 'Từ điểm A nối được 4 đoạn; từ B nối thêm 3 đoạn mới; từ C thêm 2; từ D thêm 1. Tổng: 4 + 3 + 2 + 1 = 10 (đoạn thẳng).' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: 'Trên một đường thẳng lấy 4 điểm phân biệt. Hỏi có tất cả bao nhiêu đoạn thẳng?',
      opts: FM5('6 đoạn', '4 đoạn', '5 đoạn', '8 đoạn', '12 đoạn'), ans: 'A',
      why: 'Tổng số đoạn thẳng: 3 + 2 + 1 = 6 (đoạn).' },
    { sec: FA, name: 'Câu 3', pts: 0.6, img: FM + 'f5q3.svg',
      text: 'Hình chữ nhật dưới đây được chia bởi 2 đoạn thẳng thành 3 phần. Hỏi trên hình có tất cả bao nhiêu hình chữ nhật?',
      opts: FM5('3 hình', '4 hình', '5 hình', '9 hình', '6 hình'), ans: 'E',
      why: 'Có 3 hình chữ nhật nhỏ; ghép 2 hình liền nhau được 2 hình; ghép cả 3 được 1 hình lớn. Tổng: 3 + 2 + 1 = 6 (hình chữ nhật).' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Một hình chữ nhật được chia đôi bởi một đoạn thẳng. Hỏi trên hình có tất cả bao nhiêu hình chữ nhật?',
      opts: FM5('1 hình', '3 hình', '2 hình', '4 hình', '5 hình'), ans: 'B',
      why: 'Có 2 hình chữ nhật nhỏ và 1 hình chữ nhật lớn ban đầu. Tổng: 2 + 1 = 3 (hình).' },
    { sec: FA, name: 'Câu 5', pts: 0.6, img: FM + 'f5q5.svg',
      text: 'Hỏi trên hình có tất cả bao nhiêu <b>hình vuông</b>?',
      opts: FM5('4 hình', '6 hình', '8 hình', '5 hình', '9 hình'), ans: 'D',
      why: 'Hình vuông nhỏ (cỡ 1 ô): 4 hình. Hình vuông lớn (cỡ 2 × 2 ô): 1 hình. Tổng: 4 + 1 = 5 (hình vuông).' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: 'Vẽ một đoạn thẳng từ một đỉnh của hình tam giác xuống cạnh đối diện. Hỏi trên hình có tất cả bao nhiêu hình tam giác?',
      opts: FM5('3 hình', '1 hình', '2 hình', '4 hình', '6 hình'), ans: 'A',
      why: 'Có 2 hình tam giác nhỏ và 1 hình tam giác lớn ban đầu. Tổng: 2 + 1 = 3 (hình tam giác).' },
    { sec: FA, name: 'Câu 7', pts: 0.6, img: FM + 'f5q7.svg',
      text: 'Từ một đỉnh của tam giác, người ta kẻ 2 đoạn thẳng xuống cạnh đối diện như hình. Hỏi có tất cả bao nhiêu hình tam giác?',
      opts: FM5('3 hình', '4 hình', '5 hình', '6 hình', '9 hình'), ans: 'D',
      why: 'Có 3 tam giác nhỏ; ghép 2 tam giác liền nhau được 2 hình; ghép cả 3 được tam giác lớn. Tổng: 3 + 2 + 1 = 6 (hình tam giác).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Một hình vuông được chia thành lưới 2 × 2 ô. Hỏi có tất cả bao nhiêu <b>hình chữ nhật</b> (tính cả hình vuông)?',
      opts: FM5('4 hình', '5 hình', '9 hình', '6 hình', '8 hình'), ans: 'C',
      why: 'Theo chiều ngang có 3 cách chọn (ô trái, ô phải, cả hai ô); theo chiều dọc cũng 3 cách. Tổng: 3 × 3 = 9 (hình chữ nhật).' },
    { sec: FA, name: 'Câu 9', pts: 0.6, img: FM + 'f5q9.svg',
      text: 'Trên đường thẳng có 6 điểm như hình. Hỏi có tất cả bao nhiêu đoạn thẳng?',
      opts: FM5('10 đoạn', '15 đoạn', '12 đoạn', '18 đoạn', '21 đoạn'), ans: 'B',
      why: 'Tổng số đoạn thẳng: 5 + 4 + 3 + 2 + 1 = 15 (đoạn).' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Một hình chữ nhật được chia bởi 3 đoạn thẳng thẳng đứng thành 4 phần. Hỏi có tất cả bao nhiêu hình chữ nhật?',
      opts: FM5('4 hình', '6 hình', '8 hình', '12 hình', '10 hình'), ans: 'E',
      why: 'Tổng: 4 + 3 + 2 + 1 = 10 (hình chữ nhật).' },

    { sec: FB, name: 'Câu 11', pts: 0.8, img: FM + 'f5q11.svg',
      text: 'Hỏi trên hình có tất cả bao nhiêu <b>hình vuông</b>?',
      opts: FM5('9 hình', '14 hình', '10 hình', '13 hình', '16 hình'), ans: 'B',
      why: 'Hình vuông cỡ 1 ô: 9 hình. Cỡ 2 × 2 ô: 4 hình. Cỡ 3 × 3 ô (cả hình lớn): 1 hình. Tổng: 9 + 4 + 1 = 14 (hình vuông).' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Một hình vuông được chia thành lưới 3 × 3 ô. Hỏi có tất cả bao nhiêu <b>hình chữ nhật</b> (tính cả hình vuông)?',
      opts: FM5('14 hình', '18 hình', '24 hình', '36 hình', '30 hình'), ans: 'D',
      why: 'Theo chiều ngang có 3 + 2 + 1 = 6 cách chọn; theo chiều dọc cũng 6 cách. Tổng: 6 × 6 = 36 (hình chữ nhật).' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f5q13.svg',
      text: 'Hình dưới đây là lưới 2 hàng × 3 cột. Hỏi có tất cả bao nhiêu <b>hình chữ nhật</b>?',
      opts: FM5('18 hình', '6 hình', '9 hình', '12 hình', '24 hình'), ans: 'A',
      why: 'Theo chiều ngang (3 cột) có 3 + 2 + 1 = 6 cách chọn; theo chiều dọc (2 hàng) có 2 + 1 = 3 cách. Tổng: 6 × 3 = 18 (hình chữ nhật).' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Một hình vuông được chia thành lưới 4 × 4 ô. Hỏi có tất cả bao nhiêu <b>hình vuông</b>?',
      opts: FM5('16 hình', '20 hình', '30 hình', '25 hình', '36 hình'), ans: 'C',
      why: 'Cỡ 1 ô: 16 hình; cỡ 2 × 2: 9 hình; cỡ 3 × 3: 4 hình; cỡ 4 × 4: 1 hình. Tổng: 16 + 9 + 4 + 1 = 30 (hình vuông).' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: 'Trên một đường thẳng lấy 8 điểm phân biệt. Hỏi có tất cả bao nhiêu đoạn thẳng?',
      opts: FM5('21 đoạn', '24 đoạn', '32 đoạn', '36 đoạn', '28 đoạn'), ans: 'E',
      why: 'Tổng: 7 + 6 + 5 + 4 + 3 + 2 + 1 = 28 (đoạn thẳng).' },
  ],
},

/* ═══════════ ĐỀ 6 — SỐ ẨN TRONG HÌNH ═══════════ */
{
  id: 1006, title: 'CĐ 6 · Số ẩn trong hình – ma phương', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6,
      text: 'Điền số thích hợp vào hình tròn: <b>4 + ◯ = 11</b>',
      opts: FM5('5', '6', '8', '7', '15'), ans: 'D',
      why: 'Muốn tìm số hạng chưa biết ta lấy tổng trừ số hạng kia: 11 − 4 = 7.' },
    { sec: FA, name: 'Câu 2', pts: 0.6, img: FM + 'f6q2.svg',
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng 15. Hỏi số điền vào ô dấu hỏi chấm là số nào?',
      opts: FM5('5', '8', '6', '7', '9'), ans: 'B',
      why: 'Xét hàng cuối: 4 + 3 + ? = 15, suy ra ? = 15 − 7 = 8. Kiểm tra cột cuối: 6 + 1 + 8 = 15, đúng.' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Người ta xếp các số từ 1 đến 9 vào bảng 3 × 3 sao cho tổng ba số ở mỗi hàng đều bằng nhau. Hỏi tổng đó bằng bao nhiêu?',
      opts: FM5('12', '18', '20', '45', '15'), ans: 'E',
      why: 'Tổng cả 9 số là 1 + 2 + … + 9 = 45. Bảng có 3 hàng với tổng bằng nhau nên mỗi hàng có tổng: 45 : 3 = 15.' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Biết <b>◯ + ◯ + ◯ = 21</b>. Hỏi hình tròn thay cho số nào?',
      opts: FM5('7', '3', '5', '6', '9'), ans: 'A',
      why: 'Ba hình tròn giống nhau có tổng 21 nên mỗi hình tròn là: 21 : 3 = 7.' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Biết <b>△ + 5 = 12</b> và <b>□ − △ = 3</b>. Hỏi hình vuông thay cho số nào?',
      opts: FM5('7', '8', '10', '9', '12'), ans: 'C',
      why: 'Từ △ + 5 = 12 suy ra △ = 7. Từ □ − 7 = 3 suy ra □ = 3 + 7 = 10.' },
    { sec: FA, name: 'Câu 6', pts: 0.6, img: FM + 'f6q6.svg',
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng 15. Hỏi số điền vào ô dấu hỏi chấm là số nào?',
      opts: FM5('2', '4', '3', '6', '9'), ans: 'C',
      why: 'Xét hàng giữa: ? + 5 + 7 = 15, suy ra ? = 15 − 12 = 3. Kiểm tra cột đầu: 8 + 3 + 4 = 15, đúng.' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Biết <b>🍎 + 🍎 = 10</b> và <b>🍎 + 🍌 = 12</b>. Hỏi quả chuối 🍌 thay cho số nào?',
      opts: FM5('7', '2', '5', '6', '8'), ans: 'A',
      why: 'Từ 🍎 + 🍎 = 10 suy ra 🍎 = 5. Thay vào: 5 + 🍌 = 12 nên 🍌 = 12 − 5 = 7.' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Biết <b>◯ × 3 = 18</b>. Hỏi hình tròn thay cho số nào?',
      opts: FM5('3', '5', '9', '15', '6'), ans: 'E',
      why: 'Muốn tìm thừa số chưa biết ta lấy tích chia cho thừa số kia: 18 : 3 = 6.' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: 'Ba số tự nhiên liên tiếp có tổng bằng 12. Hỏi số ở giữa là số nào?',
      opts: FM5('3', '4', '5', '6', '7'), ans: 'B',
      why: 'Số đứng trước kém số giữa 1 đơn vị, số đứng sau hơn số giữa 1 đơn vị nên tổng bằng 3 lần số giữa. Số giữa là: 12 : 3 = 4 (ba số là 3; 4; 5).' },
    { sec: FA, name: 'Câu 10', pts: 0.6, img: FM + 'f6q10.svg',
      text: 'Trong tháp số, mỗi ô bằng tổng hai ô ngay dưới nó. Hỏi số điền vào ô dấu hỏi chấm là số nào?',
      opts: FM5('1', '11', '12', '13', '42'), ans: 'D',
      why: 'Ô trên cùng bằng tổng hai ô dưới: 7 + 6 = 13.' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: 'Biết <b>🐱 + 🐱 + 🐶 = 20</b> và <b>🐱 = 6</b>. Hỏi con chó 🐶 thay cho số nào?',
      opts: FM5('8', '6', '7', '10', '14'), ans: 'A',
      why: 'Hai con mèo là: 6 × 2 = 12. Vậy 🐶 = 20 − 12 = 8.' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Biết <b>⭐ + ⭐ + ⭐ + ⭐ = 24</b> và <b>⭐ + ♥ = 11</b>. Hỏi trái tim ♥ thay cho số nào?',
      opts: FM5('3', '4', '6', '5', '7'), ans: 'D',
      why: 'Bốn ngôi sao có tổng 24 nên mỗi ngôi sao là: 24 : 4 = 6. Thay vào: 6 + ♥ = 11 nên ♥ = 5.' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f6q13.svg',
      text: 'Trong tháp số, mỗi ô bằng tổng hai ô ngay dưới nó. Hỏi số điền vào ô dấu hỏi chấm là số nào?',
      opts: FM5('10', '13', '15', '17', '20'), ans: 'C',
      why: 'Ô trên cùng bằng tổng hai ô ở hàng giữa: 8 + 7 = 15. (Kiểm tra hàng giữa: 3 + 5 = 8 và 5 + 2 = 7, đúng.)' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Biết <b>🔺 = 🔵 + 2</b> và <b>🔵 = 5</b>. Hỏi <b>🔺 + 🔵</b> bằng bao nhiêu?',
      opts: FM5('7', '12', '10', '14', '17'), ans: 'B',
      why: 'Ta có 🔺 = 5 + 2 = 7. Vậy 🔺 + 🔵 = 7 + 5 = 12.' },
    { sec: FB, name: 'Câu 15', pts: 0.8, img: FM + 'f6q15.svg',
      text: 'Trong tháp số, mỗi ô bằng tổng hai ô ngay dưới nó. Hỏi số điền vào ô dấu hỏi chấm là số nào?',
      opts: FM5('7', '8', '10', '11', '9'), ans: 'E',
      why: 'Ô dấu hỏi nằm ở hàng giữa, phía trên hai ô 4 và 5 nên bằng 4 + 5 = 9. (Kiểm tra: ô trên cùng 9 + 11 = 20, đúng.)' },
  ],
},

/* ═══════════ ĐỀ 7 — BÀI TOÁN TÍNH TIỀN ═══════════ */
{
  id: 1007, title: 'CĐ 7 · Bài toán tính tiền', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f7q1.svg',
      text: 'Dựa vào bảng giá, mua 1 cây bút chì và 1 quyển vở hết bao nhiêu tiền?',
      opts: FM5('9 000 đồng', '13 000 đồng', '12 000 đồng', '15 000 đồng', '18 000 đồng'), ans: 'B',
      why: 'Bút chì 5 000 đồng, quyển vở 8 000 đồng. Tổng: 5 000 + 8 000 = 13 000 (đồng).' },
    { sec: FA, name: 'Câu 2', pts: 0.6, img: FM + 'f7q1.svg',
      text: 'Dựa vào bảng giá trên, mua 2 quyển vở hết bao nhiêu tiền?',
      opts: FM5('10 000 đồng', '13 000 đồng', '18 000 đồng', '16 000 đồng', '24 000 đồng'), ans: 'D',
      why: 'Mỗi quyển vở 8 000 đồng nên 2 quyển hết: 8 000 × 2 = 16 000 (đồng).' },
    { sec: FA, name: 'Câu 3', pts: 0.6, img: FM + 'f7q1.svg',
      text: 'Dựa vào bảng giá trên, mua 1 cái thước kẻ và 1 cục tẩy hết bao nhiêu tiền?',
      opts: FM5('7 000 đồng', '4 000 đồng', '8 000 đồng', '9 000 đồng', '12 000 đồng'), ans: 'A',
      why: 'Thước kẻ 4 000 đồng, cục tẩy 3 000 đồng. Tổng: 4 000 + 3 000 = 7 000 (đồng).' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Bạn Nam có 20 000 đồng, mua một quyển vở giá 8 000 đồng. Hỏi Nam còn lại bao nhiêu tiền?',
      opts: FM5('8 000 đồng', '10 000 đồng', '12 000 đồng', '14 000 đồng', '28 000 đồng'), ans: 'C',
      why: 'Số tiền còn lại: 20 000 − 8 000 = 12 000 (đồng).' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Mua 3 cây bút, mỗi cây giá 5 000 đồng. Hỏi phải trả bao nhiêu tiền?',
      opts: FM5('8 000 đồng', '10 000 đồng', '12 000 đồng', '20 000 đồng', '15 000 đồng'), ans: 'E',
      why: 'Số tiền phải trả: 5 000 × 3 = 15 000 (đồng).' },
    { sec: FA, name: 'Câu 6', pts: 0.6, img: FM + 'f7q6.svg',
      text: 'Dựa vào bảng giá, mua 1 ổ bánh mì và 1 hộp sữa hết bao nhiêu tiền?',
      opts: FM5('21 000 đồng', '27 000 đồng', '30 000 đồng', '24 000 đồng', '36 000 đồng'), ans: 'D',
      why: 'Bánh mì 15 000 đồng, hộp sữa 9 000 đồng. Tổng: 15 000 + 9 000 = 24 000 (đồng).' },
    { sec: FA, name: 'Câu 7', pts: 0.6, img: FM + 'f7q6.svg',
      text: 'Dựa vào bảng giá trên, bạn Lan có 50 000 đồng và mua 2 hộp sữa. Hỏi Lan còn lại bao nhiêu tiền?',
      opts: FM5('18 000 đồng', '32 000 đồng', '27 000 đồng', '41 000 đồng', '35 000 đồng'), ans: 'B',
      why: 'Tiền mua sữa: 9 000 × 2 = 18 000 (đồng). Số tiền còn lại: 50 000 − 18 000 = 32 000 (đồng).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Một tờ tiền 20 000 đồng đổi được bao nhiêu tờ tiền 5 000 đồng?',
      opts: FM5('2 tờ', '3 tờ', '5 tờ', '10 tờ', '4 tờ'), ans: 'E',
      why: 'Số tờ đổi được: 20 000 : 5 000 = 4 (tờ).' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: 'Mẹ đưa cô bán hàng 100 000 đồng để mua hàng hết 65 000 đồng. Hỏi cô bán hàng phải trả lại mẹ bao nhiêu tiền?',
      opts: FM5('35 000 đồng', '25 000 đồng', '45 000 đồng', '55 000 đồng', '165 000 đồng'), ans: 'A',
      why: 'Tiền trả lại: 100 000 − 65 000 = 35 000 (đồng).' },
    { sec: FA, name: 'Câu 10', pts: 0.6, img: FM + 'f7q6.svg',
      text: 'Dựa vào bảng giá trên, mua 2 quả táo hết bao nhiêu tiền?',
      opts: FM5('12 000 đồng', '18 000 đồng', '24 000 đồng', '21 000 đồng', '30 000 đồng'), ans: 'C',
      why: 'Mỗi quả táo 12 000 đồng nên 2 quả hết: 12 000 × 2 = 24 000 (đồng).' },

    { sec: FB, name: 'Câu 11', pts: 0.8, img: FM + 'f7q11.svg',
      text: 'Dựa vào bảng giá, mua 1 vé xem phim và 1 hộp bắp rang hết bao nhiêu tiền?',
      opts: FM5('52 000 đồng', '60 000 đồng', '70 000 đồng', '65 000 đồng', '77 000 đồng'), ans: 'C',
      why: 'Vé xem phim 45 000 đồng, bắp rang 25 000 đồng. Tổng: 45 000 + 25 000 = 70 000 (đồng).' },
    { sec: FB, name: 'Câu 12', pts: 0.8, img: FM + 'f7q11.svg',
      text: 'Bạn An có 100 000 đồng, mua 1 vé xem phim và 1 hộp bắp rang. Hỏi An còn lại bao nhiêu tiền?',
      opts: FM5('30 000 đồng', '20 000 đồng', '25 000 đồng', '35 000 đồng', '55 000 đồng'), ans: 'A',
      why: 'Tiền đã tiêu: 45 000 + 25 000 = 70 000 (đồng). Số tiền còn lại: 100 000 − 70 000 = 30 000 (đồng).' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f7q1.svg',
      text: 'Bạn Bình có 30 000 đồng. Dựa vào bảng giá, Bình mua được nhiều nhất mấy quyển vở và còn thừa bao nhiêu tiền?',
      opts: FM5('3 quyển, thừa 2 000 đồng', '4 quyển, thừa 2 000 đồng', '2 quyển, thừa 14 000 đồng', '4 quyển, vừa hết tiền', '3 quyển, thừa 6 000 đồng'), ans: 'E',
      why: 'Mỗi quyển vở 8 000 đồng. Ta có 8 000 × 3 = 24 000 (đồng) còn 8 000 × 4 = 32 000 (đồng) — nhiều hơn số tiền có. Vậy mua được 3 quyển và còn thừa 30 000 − 24 000 = 6 000 (đồng).' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Mua 4 cái bánh, mỗi cái giá 6 000 đồng, và đưa cô bán hàng một tờ 50 000 đồng. Hỏi cô bán hàng trả lại bao nhiêu tiền?',
      opts: FM5('16 000 đồng', '26 000 đồng', '20 000 đồng', '24 000 đồng', '34 000 đồng'), ans: 'B',
      why: 'Tiền mua bánh: 6 000 × 4 = 24 000 (đồng). Tiền trả lại: 50 000 − 24 000 = 26 000 (đồng).' },
    { sec: FB, name: 'Câu 15', pts: 0.8, img: FM + 'f7q11.svg',
      text: 'Dựa vào bảng giá, bạn Hoa đi xe buýt 2 lượt rồi mua 1 vé xem phim. Hỏi Hoa tiêu hết bao nhiêu tiền?',
      opts: FM5('52 000 đồng', '55 000 đồng', '63 000 đồng', '59 000 đồng', '70 000 đồng'), ans: 'D',
      why: 'Tiền xe buýt: 7 000 × 2 = 14 000 (đồng). Cộng với vé xem phim: 14 000 + 45 000 = 59 000 (đồng).' },
  ],
},

/* ═══════════ ĐỀ 8 — THỜI GIAN VÀ ĐỒNG HỒ ═══════════ */
{
  id: 1008, title: 'CĐ 8 · Bài toán thời gian và đồng hồ', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f8q1.svg',
      text: 'Đồng hồ bên chỉ mấy giờ?',
      opts: FM5('3 giờ 15 phút', '3 giờ', '3 giờ 30 phút', '4 giờ 15 phút', '15 giờ 3 phút'), ans: 'A',
      why: 'Kim ngắn (kim giờ) vừa qua số 3, kim dài (kim phút) chỉ số 3 tức là 15 phút. Vậy đồng hồ chỉ 3 giờ 15 phút.' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: 'Một giờ có 60 phút. Vậy nửa giờ có bao nhiêu phút?',
      opts: FM5('15 phút', '20 phút', '45 phút', '30 phút', '120 phút'), ans: 'D',
      why: 'Nửa giờ là một nửa của 60 phút: 60 : 2 = 30 (phút).' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Từ 8 giờ đến 11 giờ là bao lâu?',
      opts: FM5('2 giờ', '4 giờ', '3 giờ', '19 giờ', '30 phút'), ans: 'C',
      why: 'Đếm từ 8 giờ: 9 (1 giờ), 10 (2 giờ), 11 (3 giờ). Vậy là 3 giờ.' },
    { sec: FA, name: 'Câu 4', pts: 0.6, img: FM + 'f8q4.svg',
      text: 'Đồng hồ bên chỉ mấy giờ?',
      opts: FM5('7 giờ 9 phút', '7 giờ 45 phút', '9 giờ 35 phút', '8 giờ 45 phút', '7 giờ 15 phút'), ans: 'B',
      why: 'Kim ngắn ở khoảng giữa số 7 và số 8 (chưa tới 8), kim dài chỉ số 9 tức là 45 phút. Vậy đồng hồ chỉ 7 giờ 45 phút, còn đọc là 8 giờ kém 15 phút.' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: '<b>2 giờ = … phút</b>. Số thích hợp điền vào chỗ chấm là:',
      opts: FM5('60', '90', '100', '200', '120'), ans: 'E',
      why: '1 giờ = 60 phút nên 2 giờ = 60 × 2 = 120 (phút).' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: 'Từ 9 giờ đến 9 giờ 40 phút là bao lâu?',
      opts: FM5('20 phút', '40 phút', '30 phút', '1 giờ', '9 phút'), ans: 'B',
      why: 'Cùng trong giờ thứ 9 nên chỉ cần lấy 40 − 0 = 40 (phút).' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Một ngày có bao nhiêu giờ?',
      opts: FM5('12 giờ', '30 giờ', '60 giờ', '24 giờ', '7 giờ'), ans: 'D',
      why: 'Một ngày (một ngày đêm) có 24 giờ.' },
    { sec: FA, name: 'Câu 8', pts: 0.6, img: FM + 'f8q8.svg',
      text: 'Hai đồng hồ cho biết lúc bắt đầu và lúc kết thúc một buổi tập. Hỏi buổi tập kéo dài bao lâu?',
      opts: FM5('1 giờ 30 phút', '1 giờ', '2 giờ', '2 giờ 30 phút', '30 phút'), ans: 'A',
      why: 'Bắt đầu lúc 8 giờ, kết thúc lúc 9 giờ 30 phút. Từ 8 giờ đến 9 giờ là 1 giờ, thêm 30 phút nữa. Vậy buổi tập kéo dài 1 giờ 30 phút.' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: '<b>90 phút = … giờ … phút</b>. Kết quả đúng là:',
      opts: FM5('9 giờ', '1 giờ 3 phút', '1 giờ 30 phút', '2 giờ 30 phút', '1 giờ 90 phút'), ans: 'C',
      why: '90 − 60 = 30 nên 90 phút = 1 giờ 30 phút.' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Buổi học bắt đầu lúc 7 giờ 30 phút và kéo dài 45 phút. Hỏi buổi học kết thúc lúc mấy giờ?',
      opts: FM5('8 giờ', '8 giờ 30 phút', '8 giờ 45 phút', '7 giờ 75 phút', '8 giờ 15 phút'), ans: 'E',
      why: 'Từ 7 giờ 30 phút thêm 30 phút được 8 giờ, còn dư 15 phút nữa. Vậy kết thúc lúc 8 giờ 15 phút.' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: 'Một bộ phim bắt đầu lúc 19 giờ 15 phút và kéo dài 1 giờ 20 phút. Hỏi phim kết thúc lúc mấy giờ?',
      opts: FM5('20 giờ 25 phút', '20 giờ 45 phút', '21 giờ 35 phút', '20 giờ 35 phút', '19 giờ 35 phút'), ans: 'D',
      why: '19 giờ 15 phút + 1 giờ = 20 giờ 15 phút; thêm 20 phút nữa là 20 giờ 35 phút.' },
    { sec: FB, name: 'Câu 12', pts: 0.8, img: FM + 'f8q12.svg',
      text: 'Đồng hồ bên đang chỉ giờ hiện tại. Hỏi sau 25 phút nữa là mấy giờ?',
      opts: FM5('9 giờ 35 phút', '9 giờ 45 phút', '9 giờ 55 phút', '10 giờ 20 phút', '10 giờ 45 phút'), ans: 'B',
      why: 'Đồng hồ chỉ 9 giờ 20 phút. Sau 25 phút nữa: 20 + 25 = 45, tức là 9 giờ 45 phút.' },
    { sec: FB, name: 'Câu 13', pts: 0.8,
      text: 'Nam bắt đầu làm bài lúc 8 giờ 10 phút và làm xong lúc 8 giờ 55 phút. Hỏi Nam làm bài hết bao lâu?',
      opts: FM5('35 phút', '40 phút', '50 phút', '1 giờ 5 phút', '45 phút'), ans: 'E',
      why: 'Hai mốc cùng trong giờ thứ 8 nên lấy: 55 − 10 = 45 (phút).' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Một chuyến tàu khởi hành lúc 6 giờ 45 phút và đi hết 2 giờ 30 phút. Hỏi tàu đến nơi lúc mấy giờ?',
      opts: FM5('9 giờ 15 phút', '8 giờ 15 phút', '8 giờ 45 phút', '9 giờ 30 phút', '9 giờ 45 phút'), ans: 'A',
      why: '6 giờ 45 phút + 2 giờ = 8 giờ 45 phút; thêm 30 phút nữa là 9 giờ 15 phút.' },
    { sec: FB, name: 'Câu 15', pts: 0.8, img: FM + 'f8q15.svg',
      text: 'Đồng hồ bên đang chỉ giờ hiện tại. Hỏi còn bao nhiêu phút nữa thì đến 11 giờ?',
      opts: FM5('10 phút', '15 phút', '20 phút', '25 phút', '40 phút'), ans: 'C',
      why: 'Đồng hồ chỉ 10 giờ 40 phút. Từ đó đến 11 giờ còn: 60 − 40 = 20 (phút).' },
  ],
},

/* ═══════════ ĐỀ 9 — THỐNG KÊ, BIỂU ĐỒ ═══════════ */
{
  id: 1009, title: 'CĐ 9 · Thống kê và biểu đồ', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f9q1.svg',
      text: 'Dựa vào biểu đồ, lớp nào trồng được nhiều cây nhất?',
      opts: FM5('Lớp 2A', 'Lớp 2B', 'Lớp 2C', 'Lớp 2D', 'Hai lớp bằng nhau'), ans: 'C',
      why: 'Cột của lớp 2C cao nhất (21 cây), cao hơn 2A (18 cây), 2D (15 cây) và 2B (12 cây).' },
    { sec: FA, name: 'Câu 2', pts: 0.6, img: FM + 'f9q1.svg',
      text: 'Cũng theo biểu đồ trên, lớp 2A trồng được bao nhiêu cây?',
      opts: FM5('18 cây', '12 cây', '15 cây', '20 cây', '21 cây'), ans: 'A',
      why: 'Đọc chiều cao cột của lớp 2A trên trục số bên trái: 18 cây.' },
    { sec: FA, name: 'Câu 3', pts: 0.6, img: FM + 'f9q1.svg',
      text: 'Cũng theo biểu đồ trên, lớp 2C trồng được nhiều hơn lớp 2B bao nhiêu cây?',
      opts: FM5('3 cây', '6 cây', '12 cây', '33 cây', '9 cây'), ans: 'E',
      why: 'Lớp 2C trồng 21 cây, lớp 2B trồng 12 cây. Nhiều hơn: 21 − 12 = 9 (cây).' },
    { sec: FA, name: 'Câu 4', pts: 0.6, img: FM + 'f9q1.svg',
      text: 'Cũng theo biểu đồ trên, cả bốn lớp trồng được tất cả bao nhiêu cây?',
      opts: FM5('60 cây', '66 cây', '64 cây', '68 cây', '70 cây'), ans: 'B',
      why: 'Cộng số cây của bốn lớp: 18 + 12 + 21 + 15 = 66 (cây).' },
    { sec: FA, name: 'Câu 5', pts: 0.6, img: FM + 'f9q5.svg',
      text: 'Dựa vào biểu đồ tranh, ngày nào lớp 2A được nhiều điểm mười nhất?',
      opts: FM5('Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu'), ans: 'D',
      why: 'Hàng thứ Năm có nhiều ngôi sao nhất — 7 ngôi sao, tức 7 điểm mười.' },
    { sec: FA, name: 'Câu 6', pts: 0.6, img: FM + 'f9q5.svg',
      text: 'Cũng theo biểu đồ trên, thứ Ba lớp 2A được bao nhiêu điểm mười?',
      opts: FM5('6 điểm', '3 điểm', '4 điểm', '5 điểm', '7 điểm'), ans: 'A',
      why: 'Đếm số ngôi sao ở hàng thứ Ba: 6 ngôi sao, mỗi ngôi sao là 1 điểm mười.' },
    { sec: FA, name: 'Câu 7', pts: 0.6, img: FM + 'f9q5.svg',
      text: 'Cũng theo biểu đồ trên, cả bốn ngày lớp 2A được tất cả bao nhiêu điểm mười?',
      opts: FM5('16 điểm', '18 điểm', '22 điểm', '20 điểm', '24 điểm'), ans: 'D',
      why: 'Cộng số ngôi sao bốn hàng: 4 + 6 + 3 + 7 = 20 (điểm mười).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Bảng ghi số nhãn vở của ba bạn: <b>An 5 cái · Bình 8 cái · Cường 7 cái</b>. Hỏi cả ba bạn có bao nhiêu cái nhãn vở?',
      opts: FM5('15 cái', '18 cái', '20 cái', '22 cái', '25 cái'), ans: 'C',
      why: 'Tổng số nhãn vở: 5 + 8 + 7 = 20 (cái).' },
    { sec: FA, name: 'Câu 9', pts: 0.6, img: FM + 'f9q9.svg',
      text: 'Dựa vào biểu đồ, loại quả nào có ít bạn thích nhất?',
      opts: FM5('Táo', 'Lê', 'Cam', 'Nho', 'Táo và Lê bằng nhau'), ans: 'B',
      why: 'Cột của quả Lê thấp nhất — chỉ 6 bạn, ít hơn Táo (8 bạn), Nho (10 bạn) và Cam (14 bạn).' },
    { sec: FA, name: 'Câu 10', pts: 0.6, img: FM + 'f9q9.svg',
      text: 'Cũng theo biểu đồ trên, số bạn thích quả Cam nhiều hơn số bạn thích quả Táo bao nhiêu?',
      opts: FM5('4 bạn', '5 bạn', '8 bạn', '22 bạn', '6 bạn'), ans: 'E',
      why: 'Cam có 14 bạn thích, Táo có 8 bạn thích. Nhiều hơn: 14 − 8 = 6 (bạn).' },

    { sec: FB, name: 'Câu 11', pts: 0.8, img: FM + 'f9q9.svg',
      text: 'Cũng theo biểu đồ trên, cả bốn loại quả có tất cả bao nhiêu bạn thích?',
      opts: FM5('32 bạn', '38 bạn', '34 bạn', '36 bạn', '40 bạn'), ans: 'B',
      why: 'Cộng bốn cột: 8 + 14 + 6 + 10 = 38 (bạn).' },
    { sec: FB, name: 'Câu 12', pts: 0.8, img: FM + 'f9q13.svg',
      text: 'Dựa vào biểu đồ tranh (mỗi quyển sách 📗 tượng trưng cho 2 quyển sách), hỏi bạn An đã đọc bao nhiêu quyển sách?',
      opts: FM5('5 quyển', '6 quyển', '8 quyển', '10 quyển', '12 quyển'), ans: 'D',
      why: 'Hàng của An có 5 hình sách, mỗi hình là 2 quyển. Vậy An đọc: 2 × 5 = 10 (quyển sách).' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f9q13.svg',
      text: 'Cũng theo biểu đồ trên, bạn Cường đọc nhiều hơn bạn Bình bao nhiêu quyển sách?',
      opts: FM5('6 quyển', '3 quyển', '4 quyển', '9 quyển', '12 quyển'), ans: 'A',
      why: 'Cường có 6 hình, Bình có 3 hình, hơn nhau 3 hình. Mỗi hình là 2 quyển nên hơn: 2 × 3 = 6 (quyển sách).' },
    { sec: FB, name: 'Câu 14', pts: 0.8, img: FM + 'f9q13.svg',
      text: 'Cũng theo biểu đồ trên, cả ba bạn đọc được tất cả bao nhiêu quyển sách?',
      opts: FM5('14 quyển', '20 quyển', '28 quyển', '24 quyển', '32 quyển'), ans: 'C',
      why: 'Tổng số hình sách: 5 + 3 + 6 = 14 (hình). Mỗi hình là 2 quyển nên tất cả: 2 × 14 = 28 (quyển sách).' },
    { sec: FB, name: 'Câu 15', pts: 0.8, img: FM + 'f9q1.svg',
      text: 'Trở lại biểu đồ số cây. Nếu mỗi lớp trồng thêm 5 cây nữa thì cả bốn lớp trồng được tất cả bao nhiêu cây?',
      opts: FM5('71 cây', '76 cây', '81 cây', '91 cây', '86 cây'), ans: 'E',
      why: 'Bốn lớp trồng thêm: 5 × 4 = 20 (cây). Tổng mới: 66 + 20 = 86 (cây).' },
  ],
},

/* ═══════════ ĐỀ 10 — TÍNH NGƯỢC TỪ CUỐI ═══════════ */
{
  id: 1010, title: 'CĐ 10 · Tính ngược từ cuối', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f10q1.svg',
      text: 'Các phép tính được thực hiện theo chiều mũi tên. Hãy tính ngược lại để tìm số ban đầu (ô dấu hỏi chấm).',
      opts: FM5('4', '8', '14', '10', '20'), ans: 'D',
      why: 'Tính ngược từ cuối: 12 + 3 = 15; 15 − 5 = 10. Thử lại: 10 + 5 = 15; 15 − 3 = 12, đúng.' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: 'Một số cộng thêm 8 thì được 20. Hỏi số đó là số nào?',
      opts: FM5('10', '12', '14', '16', '28'), ans: 'B',
      why: 'Tính ngược: 20 − 8 = 12.' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Một số trừ đi 7 thì được 15. Hỏi số đó là số nào?',
      opts: FM5('8', '18', '20', '25', '22'), ans: 'E',
      why: 'Tính ngược: 15 + 7 = 22.' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Một số nhân với 4 thì được 24. Hỏi số đó là số nào?',
      opts: FM5('6', '4', '5', '8', '20'), ans: 'A',
      why: 'Tính ngược: 24 : 4 = 6.' },
    { sec: FA, name: 'Câu 5', pts: 0.6, img: FM + 'f10q5.svg',
      text: 'Các phép tính được thực hiện theo chiều mũi tên. Hãy tìm số ban đầu (ô dấu hỏi chấm).',
      opts: FM5('5', '10', '7', '13', '14'), ans: 'C',
      why: 'Tính ngược từ cuối: 20 − 6 = 14; 14 : 2 = 7. Thử lại: 7 × 2 = 14; 14 + 6 = 20, đúng.' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: 'Một số chia cho 5 thì được 8. Hỏi số đó là số nào?',
      opts: FM5('13', '30', '40', '35', '45'), ans: 'C',
      why: 'Tính ngược: 8 × 5 = 40.' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Tôi nghĩ ra một số, gấp số đó lên 3 lần rồi bớt đi 4 thì được 20. Hỏi tôi đã nghĩ ra số nào?',
      opts: FM5('8', '5', '6', '7', '9'), ans: 'A',
      why: 'Tính ngược: 20 + 4 = 24; 24 : 3 = 8. Thử lại: 8 × 3 = 24; 24 − 4 = 20, đúng.' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Tìm <b>x</b>, biết: <b>x + 15 = 40</b>',
      opts: FM5('15', '20', '30', '55', '25'), ans: 'E',
      why: 'x = 40 − 15 = 25.' },
    { sec: FA, name: 'Câu 9', pts: 0.6, img: FM + 'f10q9.svg',
      text: 'Các phép tính được thực hiện theo chiều mũi tên. Hãy tìm số ban đầu (ô dấu hỏi chấm).',
      opts: FM5('11', '15', '13', '18', '21'), ans: 'B',
      why: 'Tính ngược từ cuối: 18 + 2 = 20; 20 − 9 = 11; 11 + 4 = 15. Thử lại: 15 − 4 = 11; 11 + 9 = 20; 20 − 2 = 18, đúng.' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Số nào cộng với chính nó thì được 18?',
      opts: FM5('6', '8', '12', '9', '36'), ans: 'D',
      why: 'Số đó gấp đôi lên được 18 nên số đó là: 18 : 2 = 9.' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: 'Một số bớt đi 6 rồi gấp kết quả lên 5 lần thì được 40. Hỏi số đó là số nào?',
      opts: FM5('14', '8', '10', '12', '16'), ans: 'A',
      why: 'Tính ngược: 40 : 5 = 8; 8 + 6 = 14. Thử lại: 14 − 6 = 8; 8 × 5 = 40, đúng.' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Lan cho bạn 5 cái kẹo, sau đó được mẹ cho thêm 8 cái nữa thì Lan có 20 cái. Hỏi lúc đầu Lan có bao nhiêu cái kẹo?',
      opts: FM5('12 cái', '15 cái', '23 cái', '17 cái', '33 cái'), ans: 'D',
      why: 'Tính ngược: 20 − 8 = 12 (trước khi mẹ cho); 12 + 5 = 17 (trước khi cho bạn). Vậy lúc đầu Lan có 17 cái kẹo.' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f10q13.svg',
      text: 'Các phép tính được thực hiện theo chiều mũi tên. Hãy tìm số ban đầu (ô dấu hỏi chấm).',
      opts: FM5('2', '5', '3', '10', '17'), ans: 'C',
      why: 'Tính ngược từ cuối: 30 : 3 = 10; 10 − 7 = 3. Thử lại: 3 + 7 = 10; 10 × 3 = 30, đúng.' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Trong một phép chia, số bị chia là 45 và thương là 9. Hỏi số chia là số nào?',
      opts: FM5('4', '5', '6', '9', '405'), ans: 'B',
      why: 'Muốn tìm số chia ta lấy số bị chia chia cho thương: 45 : 9 = 5.' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: 'Một người bán đi 12 quả trứng thì số trứng còn lại đúng bằng một nửa số trứng lúc đầu. Hỏi lúc đầu người đó có bao nhiêu quả trứng?',
      opts: FM5('18 quả', '20 quả', '30 quả', '36 quả', '24 quả'), ans: 'E',
      why: 'Bán đi một nửa thì còn một nửa, nên 12 quả đã bán chính là một nửa số trứng lúc đầu. Lúc đầu có: 12 × 2 = 24 (quả trứng).' },
  ],
},

/* ═══════════ ĐỀ 11 — SUY LUẬN LOGIC ═══════════ */
{
  id: 1011, title: 'CĐ 11 · Suy luận logic', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6,
      text: 'Ba bạn An, Bình, Cường mỗi bạn thích một môn: Toán, Nhạc hoặc Vẽ. Biết An <b>không</b> thích Toán và <b>không</b> thích Nhạc; Bình <b>không</b> thích Toán. Hỏi bạn nào thích môn Toán?',
      opts: FM5('An', 'Cường', 'Bình', 'An hoặc Bình', 'Không xác định được'), ans: 'B',
      why: 'An không thích Toán, Bình cũng không thích Toán, nên chỉ còn Cường thích môn Toán. (An thích Vẽ, Bình thích Nhạc.)' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: 'Trong hộp có 4 viên bi đỏ và 3 viên bi xanh. Không nhìn vào hộp, phải lấy ra <b>ít nhất</b> bao nhiêu viên để chắc chắn có 2 viên <b>cùng màu</b>?',
      opts: FM5('2 viên', '4 viên', '5 viên', '3 viên', '7 viên'), ans: 'D',
      why: 'Lấy 2 viên vẫn có thể được 1 đỏ 1 xanh. Lấy 3 viên mà chỉ có 2 màu thì chắc chắn phải có 2 viên trùng màu.' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Vẫn hộp có 4 viên bi đỏ và 3 viên bi xanh. Phải lấy ra <b>ít nhất</b> bao nhiêu viên để chắc chắn có 1 viên bi <b>xanh</b>?',
      opts: FM5('5 viên', '2 viên', '3 viên', '4 viên', '7 viên'), ans: 'A',
      why: 'Trường hợp xấu nhất là lấy phải cả 4 viên bi đỏ trước. Khi đó viên thứ 5 chắc chắn là bi xanh.' },
    { sec: FA, name: 'Câu 4', pts: 0.6, img: FM + 'f11q4.svg',
      text: 'Ba chiếc hộp được xếp chồng lên nhau như hình. Hỏi hộp nào nằm <b>dưới cùng</b>?',
      opts: FM5('Hộp Xanh', 'Hộp Đỏ', 'Hộp Vàng', 'Hộp Xanh hoặc Đỏ', 'Không xác định được'), ans: 'C',
      why: 'Đọc từ trên xuống: hộp Xanh, hộp Đỏ, hộp Vàng. Vậy hộp Vàng nằm dưới cùng.' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'An cao hơn Bình, Bình cao hơn Cường. Hỏi bạn nào <b>thấp nhất</b>?',
      opts: FM5('An', 'Bình', 'An và Bình bằng nhau', 'Không xác định được', 'Cường'), ans: 'E',
      why: 'Sắp thứ tự từ cao xuống thấp: An — Bình — Cường. Vậy Cường thấp nhất.' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: 'Trong sân có 6 con vừa gà vừa thỏ, đếm được tất cả 16 cái chân. Hỏi có bao nhiêu con thỏ?',
      opts: FM5('1 con', '3 con', '4 con', '2 con', '5 con'), ans: 'D',
      why: 'Giả sử cả 6 con đều là gà thì có 2 × 6 = 12 (chân), thiếu 16 − 12 = 4 (chân). Mỗi lần đổi 1 con gà thành 1 con thỏ thì thêm 2 chân, nên số thỏ là 4 : 2 = 2 (con).' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Ba bạn Nam, Bắc, Trung thi chạy, không có ai bằng nhau. Biết Nam <b>không</b> về nhất và <b>không</b> về cuối; Bắc <b>không</b> về nhất. Hỏi ai về nhất?',
      opts: FM5('Nam', 'Trung', 'Bắc', 'Nam hoặc Bắc', 'Không xác định được'), ans: 'B',
      why: 'Nam không nhất, Bắc không nhất nên người về nhất chỉ có thể là Trung. (Nam về nhì, Bắc về cuối.)' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Có 3 chiếc chìa khoá và 3 chiếc ổ khoá, mỗi chìa chỉ mở được đúng một ổ. Hỏi phải thử <b>nhiều nhất</b> mấy lần để chắc chắn tìm được chìa mở ổ khoá thứ nhất?',
      opts: FM5('1 lần', '3 lần', '4 lần', '6 lần', '2 lần'), ans: 'E',
      why: 'Thử chìa thứ nhất, nếu không được thì thử chìa thứ hai. Nếu cả hai đều không mở được thì chắc chắn chìa còn lại là chìa đúng, không cần thử nữa. Vậy nhiều nhất 2 lần.' },
    { sec: FA, name: 'Câu 9', pts: 0.6, img: FM + 'f11q9.svg',
      text: 'Ba bạn về đích: An về trước Bình, Bình về trước Cường. Hỏi bạn nào được huy chương vàng 🥇?',
      opts: FM5('An', 'Bình', 'Cường', 'An và Bình', 'Không xác định được'), ans: 'A',
      why: 'Thứ tự về đích là An — Bình — Cường nên An về nhất và nhận huy chương vàng.' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Mai có nhiều hơn Lan 4 cái kẹo. Nếu Mai cho Lan 2 cái kẹo thì lúc đó hai bạn thế nào?',
      opts: FM5('Mai nhiều hơn Lan 2 cái', 'Lan nhiều hơn Mai 2 cái', 'Hai bạn có số kẹo bằng nhau', 'Mai nhiều hơn Lan 4 cái', 'Lan nhiều hơn Mai 4 cái'), ans: 'C',
      why: 'Mai bớt 2 cái, Lan thêm 2 cái nên khoảng cách giảm 2 + 2 = 4 (cái). Ban đầu Mai hơn đúng 4 cái nên bây giờ hai bạn bằng nhau.' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: 'Trong hộp có 5 bút xanh, 4 bút đỏ và 3 bút đen. Không nhìn vào hộp, phải lấy ra <b>ít nhất</b> bao nhiêu chiếc để chắc chắn có đủ cả 3 màu?',
      opts: FM5('3 chiếc', '6 chiếc', '10 chiếc', '9 chiếc', '12 chiếc'), ans: 'C',
      why: 'Trường hợp xấu nhất là lấy hết 5 bút xanh và 4 bút đỏ trước — tất cả 9 chiếc mà vẫn thiếu màu đen. Chiếc thứ 10 bắt buộc là bút đen. Vậy ít nhất 10 chiếc.' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Bốn bạn gặp nhau, mỗi bạn bắt tay với tất cả các bạn còn lại đúng một lần. Hỏi có bao nhiêu cái bắt tay?',
      opts: FM5('6 cái', '4 cái', '8 cái', '10 cái', '12 cái'), ans: 'A',
      why: 'Bạn thứ nhất bắt tay 3 bạn, bạn thứ hai bắt thêm 2 cái mới, bạn thứ ba thêm 1 cái. Tổng: 3 + 2 + 1 = 6 (cái bắt tay).' },
    { sec: FB, name: 'Câu 13', pts: 0.8,
      text: 'Trong sân có 10 con vừa gà vừa chó, đếm được tất cả 26 cái chân. Hỏi có bao nhiêu con gà?',
      opts: FM5('3 con', '5 con', '6 con', '8 con', '7 con'), ans: 'E',
      why: 'Giả sử cả 10 con đều là gà thì có 2 × 10 = 20 (chân), thiếu 26 − 20 = 6 (chân). Số chó là 6 : 2 = 3 (con), nên số gà là 10 − 3 = 7 (con).' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Ba bạn Lan, Huệ, Cúc mặc áo màu hồng, xanh hoặc vàng (không trùng nhau). Biết Lan <b>không</b> mặc áo hồng và <b>không</b> mặc áo xanh; Huệ <b>không</b> mặc áo xanh. Hỏi Cúc mặc áo màu gì?',
      opts: FM5('Màu hồng', 'Màu xanh', 'Màu vàng', 'Màu hồng hoặc vàng', 'Không xác định được'), ans: 'B',
      why: 'Lan không hồng, không xanh nên Lan mặc áo vàng. Huệ không xanh, cũng không thể vàng (Lan mặc rồi) nên Huệ mặc áo hồng. Còn lại, Cúc mặc áo xanh.' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: 'Có 3 chiếc hộp, chỉ 1 hộp đựng viên bi. Trên hộp A ghi “Bi ở trong hộp này”, hộp B ghi “Bi không ở trong hộp này”, hộp C ghi “Bi không ở trong hộp A”. Biết <b>chỉ có đúng một dòng chữ đúng</b>. Hỏi viên bi ở trong hộp nào?',
      opts: FM5('Hộp A', 'Hộp C', 'Không hộp nào', 'Hộp B', 'Không xác định được'), ans: 'D',
      why: 'Thử từng trường hợp. Nếu bi ở hộp A: dòng A đúng và dòng B cũng đúng — có 2 dòng đúng, loại. Nếu bi ở hộp C: dòng B và dòng C đều đúng — 2 dòng đúng, loại. Nếu bi ở hộp B: dòng A sai, dòng B sai, chỉ dòng C đúng — đúng 1 dòng, thoả mãn. Vậy bi ở hộp B.' },
  ],
},

/* ═══════════ ĐỀ 12 — ĐẾM KHỐI LẬP PHƯƠNG ═══════════ */
{
  id: 1012, title: 'CĐ 12 · Đếm khối lập phương', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f12q1.svg',
      text: 'Hình bên được xếp từ các khối lập phương nhỏ bằng nhau. Hỏi có tất cả bao nhiêu khối?',
      opts: FM5('8 khối', '4 khối', '6 khối', '10 khối', '12 khối'), ans: 'A',
      why: 'Hình gồm 2 tầng, mỗi tầng có 2 × 2 = 4 (khối). Tất cả: 4 × 2 = 8 (khối).' },
    { sec: FA, name: 'Câu 2', pts: 0.6, img: FM + 'f12q4.svg',
      text: 'Hình bên được xếp từ các khối lập phương nhỏ bằng nhau. Hỏi có tất cả bao nhiêu khối?',
      opts: FM5('4 khối', '5 khối', '8 khối', '6 khối', '9 khối'), ans: 'D',
      why: 'Hình chỉ có 1 tầng, gồm 2 hàng, mỗi hàng 3 khối. Tất cả: 3 × 2 = 6 (khối).' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Khối lập phương có bao nhiêu <b>mặt</b>?',
      opts: FM5('4 mặt', '5 mặt', '6 mặt', '8 mặt', '12 mặt'), ans: 'C',
      why: 'Khối lập phương có 6 mặt, mỗi mặt là một hình vuông bằng nhau (giống con xúc xắc).' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Khối hộp chữ nhật có bao nhiêu <b>đỉnh</b>?',
      opts: FM5('4 đỉnh', '8 đỉnh', '6 đỉnh', '10 đỉnh', '12 đỉnh'), ans: 'B',
      why: 'Khối hộp chữ nhật có 8 đỉnh: 4 đỉnh ở mặt trên và 4 đỉnh ở mặt dưới.' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Khối lập phương có bao nhiêu <b>cạnh</b>?',
      opts: FM5('6 cạnh', '8 cạnh', '10 cạnh', '16 cạnh', '12 cạnh'), ans: 'E',
      why: 'Khối lập phương có 12 cạnh: 4 cạnh mặt trên, 4 cạnh mặt dưới và 4 cạnh đứng nối hai mặt.' },
    { sec: FA, name: 'Câu 6', pts: 0.6, img: FM + 'f12q7.svg',
      text: 'Hình bên được xếp từ các khối lập phương nhỏ bằng nhau thành hình bậc thang. Hỏi có tất cả bao nhiêu khối?',
      opts: FM5('3 khối', '6 khối', '4 khối', '5 khối', '9 khối'), ans: 'B',
      why: 'Ba cột lần lượt cao 3 khối, 2 khối và 1 khối. Tất cả: 3 + 2 + 1 = 6 (khối).' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Xếp một hình khối gồm 2 tầng, mỗi tầng 4 khối lập phương nhỏ. Hỏi có tất cả bao nhiêu khối?',
      opts: FM5('4 khối', '6 khối', '10 khối', '8 khối', '16 khối'), ans: 'D',
      why: 'Tất cả: 4 × 2 = 8 (khối).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Hình khối nào dưới đây <b>lăn được</b> theo mọi hướng?',
      opts: FM5('Khối cầu', 'Khối lập phương', 'Khối hộp chữ nhật', 'Hình vuông', 'Hình tam giác'), ans: 'A',
      why: 'Khối cầu (như quả bóng) có bề mặt cong đều nên lăn được theo mọi hướng; các khối có mặt phẳng thì chỉ trượt hoặc lật.' },
    { sec: FA, name: 'Câu 9', pts: 0.6, img: FM + 'f12q10.svg',
      text: 'Hình bên được xếp từ các khối lập phương nhỏ bằng nhau. Hỏi có tất cả bao nhiêu khối?',
      opts: FM5('9 khối', '12 khối', '18 khối', '15 khối', '27 khối'), ans: 'C',
      why: 'Hình gồm 2 tầng, mỗi tầng có 3 × 3 = 9 (khối). Tất cả: 9 × 2 = 18 (khối).' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Xếp 27 khối lập phương nhỏ bằng nhau thành một khối lập phương lớn. Hỏi mỗi cạnh của khối lớn gồm mấy khối nhỏ?',
      opts: FM5('2 khối', '4 khối', '6 khối', '9 khối', '3 khối'), ans: 'E',
      why: 'Khối lớn gồm 3 tầng, mỗi tầng 3 × 3 = 9 khối, tất cả 9 × 3 = 27 khối. Vậy mỗi cạnh gồm 3 khối nhỏ.' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: 'Một khối lập phương lớn ghép từ 27 khối nhỏ (3 × 3 × 3) được sơn đỏ toàn bộ mặt ngoài. Hỏi có bao nhiêu khối nhỏ được sơn <b>đúng 3 mặt</b>?',
      opts: FM5('4 khối', '6 khối', '9 khối', '8 khối', '12 khối'), ans: 'D',
      why: 'Khối được sơn 3 mặt là các khối nằm ở góc của khối lớn. Một khối lập phương có 8 góc nên có 8 khối như thế.' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Vẫn khối lập phương 3 × 3 × 3 được sơn đỏ mặt ngoài ở trên. Hỏi có bao nhiêu khối nhỏ <b>không được sơn mặt nào</b>?',
      opts: FM5('0 khối', '1 khối', '3 khối', '6 khối', '8 khối'), ans: 'B',
      why: 'Chỉ khối nằm chính giữa khối lớn là bị bao kín hoàn toàn, không lộ ra mặt ngoài nào. Vậy có đúng 1 khối.' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f12q13.svg',
      text: 'Hình bên được xếp từ các khối lập phương nhỏ bằng nhau. Hỏi có tất cả bao nhiêu khối?',
      opts: FM5('6 khối', '7 khối', '8 khối', '12 khối', '9 khối'), ans: 'E',
      why: 'Hàng phía sau có ba cột cao lần lượt 1; 2; 3 khối — tất cả 6 khối. Hàng phía trước có ba cột, mỗi cột 1 khối — 3 khối. Tổng: 6 + 3 = 9 (khối).' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Một khối lập phương ghép từ 8 khối nhỏ (2 × 2 × 2) được sơn đỏ toàn bộ mặt ngoài. Hỏi có bao nhiêu khối nhỏ được sơn <b>đúng 3 mặt</b>?',
      opts: FM5('8 khối', '0 khối', '2 khối', '4 khối', '6 khối'), ans: 'A',
      why: 'Khối 2 × 2 × 2 chỉ gồm toàn các khối ở góc, không có khối nào nằm khuất bên trong. Vì vậy cả 8 khối đều được sơn đúng 3 mặt.' },
    { sec: FB, name: 'Câu 15', pts: 0.8, img: FM + 'f12q15.svg',
      text: 'Hình bên là một khối lập phương lớn xếp từ các khối lập phương nhỏ bằng nhau. Hỏi có tất cả bao nhiêu khối nhỏ?',
      opts: FM5('9 khối', '18 khối', '27 khối', '24 khối', '36 khối'), ans: 'C',
      why: 'Khối lớn gồm 3 tầng, mỗi tầng 3 × 3 = 9 (khối). Tất cả: 9 × 3 = 27 (khối).' },
  ],
},

/* ═══════════ ĐỀ 13 — BÀI TOÁN TÍNH TUỔI ═══════════ */
{
  id: 1013, title: 'CĐ 13 · Bài toán tính tuổi', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f13q1.svg',
      text: 'Dựa vào cuộc trò chuyện, hỏi em Nam năm nay bao nhiêu tuổi?',
      opts: FM5('6 tuổi', '8 tuổi', '9 tuổi', '11 tuổi', '21 tuổi'), ans: 'C',
      why: 'Chị Mai 15 tuổi, em kém chị 6 tuổi nên em: 15 − 6 = 9 (tuổi).' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: 'Anh 12 tuổi, em 8 tuổi. Hỏi anh hơn em bao nhiêu tuổi?',
      opts: FM5('4 tuổi', '2 tuổi', '3 tuổi', '5 tuổi', '20 tuổi'), ans: 'A',
      why: 'Anh hơn em: 12 − 8 = 4 (tuổi).' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Bố 35 tuổi, con 7 tuổi. Hỏi bố hơn con bao nhiêu tuổi?',
      opts: FM5('5 tuổi', '25 tuổi', '27 tuổi', '42 tuổi', '28 tuổi'), ans: 'E',
      why: 'Bố hơn con: 35 − 7 = 28 (tuổi).' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Mẹ hơn con 25 tuổi, con năm nay 5 tuổi. Hỏi mẹ bao nhiêu tuổi?',
      opts: FM5('20 tuổi', '30 tuổi', '25 tuổi', '28 tuổi', '35 tuổi'), ans: 'B',
      why: 'Tuổi mẹ: 5 + 25 = 30 (tuổi).' },
    { sec: FA, name: 'Câu 5', pts: 0.6,
      text: 'Hai năm nữa bạn An sẽ tròn 10 tuổi. Hỏi năm nay An bao nhiêu tuổi?',
      opts: FM5('6 tuổi', '7 tuổi', '9 tuổi', '8 tuổi', '12 tuổi'), ans: 'D',
      why: 'Tuổi hiện nay: 10 − 2 = 8 (tuổi).' },
    { sec: FA, name: 'Câu 6', pts: 0.6, img: FM + 'f13q6.svg',
      text: 'Dựa vào cuộc trò chuyện, hỏi mẹ năm nay bao nhiêu tuổi?',
      opts: FM5('35 tuổi', '19 tuổi', '27 tuổi', '32 tuổi', '38 tuổi'), ans: 'A',
      why: 'Con 8 tuổi, mẹ hơn con 27 tuổi nên tuổi mẹ: 8 + 27 = 35 (tuổi).' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Năm ngoái bạn Lan 7 tuổi. Hỏi năm nay Lan bao nhiêu tuổi?',
      opts: FM5('6 tuổi', '7 tuổi', '9 tuổi', '8 tuổi', '14 tuổi'), ans: 'D',
      why: 'Mỗi năm thêm 1 tuổi nên năm nay Lan: 7 + 1 = 8 (tuổi).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Ông 70 tuổi, cháu 10 tuổi. Hỏi tuổi ông gấp mấy lần tuổi cháu?',
      opts: FM5('5 lần', '6 lần', '7 lần', '8 lần', '60 lần'), ans: 'C',
      why: 'Muốn biết gấp mấy lần ta lấy số lớn chia số bé: 70 : 10 = 7 (lần).' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: 'Tổng số tuổi của hai anh em là 20 tuổi, anh hơn em 4 tuổi. Hỏi anh bao nhiêu tuổi?',
      opts: FM5('8 tuổi', '12 tuổi', '10 tuổi', '14 tuổi', '16 tuổi'), ans: 'B',
      why: 'Tuổi anh = (20 + 4) : 2 = 24 : 2 = 12 (tuổi). Tuổi em là 8; thử lại 12 + 8 = 20 và 12 − 8 = 4.' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: 'Năm nay chị 14 tuổi, em 8 tuổi. Hỏi <b>3 năm nữa</b> chị hơn em bao nhiêu tuổi?',
      opts: FM5('3 tuổi', '9 tuổi', '12 tuổi', '22 tuổi', '6 tuổi'), ans: 'E',
      why: 'Mỗi năm cả hai chị em đều thêm 1 tuổi nên hiệu số tuổi không bao giờ thay đổi. Chị vẫn hơn em: 14 − 8 = 6 (tuổi).' },

    { sec: FB, name: 'Câu 11', pts: 0.8, img: FM + 'f13q11.svg',
      text: 'Dựa vào cuộc trò chuyện, hỏi em năm nay bao nhiêu tuổi?',
      opts: FM5('4 tuổi', '6 tuổi', '8 tuổi', '10 tuổi', '12 tuổi'), ans: 'B',
      why: 'Hai năm nữa anh tròn 12 tuổi nên năm nay anh: 12 − 2 = 10 (tuổi). Em kém anh 4 tuổi nên em: 10 − 4 = 6 (tuổi).' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Mẹ 30 tuổi, con 6 tuổi. Hỏi tuổi mẹ gấp mấy lần tuổi con?',
      opts: FM5('3 lần', '4 lần', '6 lần', '5 lần', '24 lần'), ans: 'D',
      why: 'Ta lấy: 30 : 6 = 5 (lần).' },
    { sec: FB, name: 'Câu 13', pts: 0.8,
      text: 'Bố hơn con 30 tuổi và tuổi bố gấp 4 lần tuổi con. Hỏi con bao nhiêu tuổi?',
      opts: FM5('10 tuổi', '6 tuổi', '8 tuổi', '12 tuổi', '15 tuổi'), ans: 'A',
      why: 'Coi tuổi con là 1 phần thì tuổi bố là 4 phần, hiệu là 3 phần ứng với 30 tuổi. Tuổi con: 30 : 3 = 10 (tuổi), tuổi bố 40 tuổi.' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Năm nay anh 14 tuổi, em 6 tuổi. Hỏi sau bao nhiêu năm nữa thì tuổi anh gấp đôi tuổi em?',
      opts: FM5('1 năm', '3 năm', '2 năm', '4 năm', '6 năm'), ans: 'C',
      why: 'Anh luôn hơn em 14 − 6 = 8 (tuổi). Khi tuổi anh gấp đôi tuổi em thì phần hơn 8 tuổi đúng bằng tuổi em, nên lúc đó em 8 tuổi. Vậy sau 8 − 6 = 2 (năm).' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: 'Tổng số tuổi của hai chị em là 24 tuổi, tuổi chị gấp đôi tuổi em. Hỏi chị bao nhiêu tuổi?',
      opts: FM5('8 tuổi', '12 tuổi', '14 tuổi', '18 tuổi', '16 tuổi'), ans: 'E',
      why: 'Coi tuổi em là 1 phần thì tuổi chị là 2 phần, tổng là 3 phần. Tuổi em: 24 : 3 = 8 (tuổi); tuổi chị: 8 × 2 = 16 (tuổi).' },
  ],
},

/* ═══════════ ĐỀ 14 — SO SÁNH VÀ THAY THẾ ═══════════ */
{
  id: 1014, title: 'CĐ 14 · So sánh và thay thế', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6, img: FM + 'f14q1.svg',
      text: 'Cân thăng bằng cho biết 1 con gà mái nặng bằng 3 con gà con. Hỏi 2 con gà mái nặng bằng mấy con gà con?',
      opts: FM5('3 con', '4 con', '5 con', '6 con', '9 con'), ans: 'D',
      why: 'Mỗi con gà mái đổi được 3 con gà con nên 2 con gà mái đổi được: 3 × 2 = 6 (con gà con).' },
    { sec: FA, name: 'Câu 2', pts: 0.6,
      text: '1 quả dưa nặng bằng 4 quả cam. Hỏi 3 quả dưa nặng bằng mấy quả cam?',
      opts: FM5('7 quả', '12 quả', '8 quả', '10 quả', '16 quả'), ans: 'B',
      why: 'Số cam: 4 × 3 = 12 (quả).' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: '2 cây bút đổi được 1 quyển vở. Hỏi 8 cây bút đổi được mấy quyển vở?',
      opts: FM5('2 quyển', '3 quyển', '6 quyển', '16 quyển', '4 quyển'), ans: 'E',
      why: 'Số vở đổi được: 8 : 2 = 4 (quyển).' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: '<b>3 kg = … g</b>. Số thích hợp điền vào chỗ chấm là:',
      opts: FM5('3 000', '30', '300', '30 000', '3'), ans: 'A',
      why: '1 kg = 1 000 g nên 3 kg = 1 000 × 3 = 3 000 (g).' },
    { sec: FA, name: 'Câu 5', pts: 0.6, img: FM + 'f14q5.svg',
      text: 'Hai cân đều thăng bằng. Hỏi 1 quyển sách đỏ 📕 nặng bằng mấy quyển sách xanh lá 📗?',
      opts: FM5('2 quyển', '3 quyển', '4 quyển', '6 quyển', '8 quyển'), ans: 'C',
      why: 'Cân thứ nhất: 1 sách đỏ = 2 sách xanh dương. Cân thứ hai: 1 sách xanh dương = 2 sách xanh lá. Vậy 1 sách đỏ = 2 × 2 = 4 (quyển sách xanh lá).' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: 'Một hộp có 6 gói, mỗi gói có 5 cái kẹo. Hỏi một hộp có bao nhiêu cái kẹo?',
      opts: FM5('11 cái', '20 cái', '30 cái', '25 cái', '36 cái'), ans: 'C',
      why: 'Số kẹo trong hộp: 5 × 6 = 30 (cái).' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: '1 thùng hàng gồm 2 túi, mỗi túi nặng 5 kg. Hỏi 3 thùng nặng bao nhiêu ki-lô-gam?',
      opts: FM5('30 kg', '10 kg', '15 kg', '20 kg', '45 kg'), ans: 'A',
      why: 'Mỗi thùng nặng: 5 × 2 = 10 (kg). Ba thùng nặng: 10 × 3 = 30 (kg).' },
    { sec: FA, name: 'Câu 8', pts: 0.6,
      text: 'Cứ 5 cái bánh xếp được 1 hộp. Hỏi 20 cái bánh xếp được mấy hộp?',
      opts: FM5('2 hộp', '3 hộp', '5 hộp', '10 hộp', '4 hộp'), ans: 'E',
      why: 'Số hộp: 20 : 5 = 4 (hộp).' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: 'Một con bò ăn hết lượng cỏ bằng 4 con dê. Hỏi 2 con bò ăn hết lượng cỏ bằng mấy con dê?',
      opts: FM5('2 con', '8 con', '4 con', '6 con', '10 con'), ans: 'B',
      why: 'Số dê tương ứng: 4 × 2 = 8 (con).' },
    { sec: FA, name: 'Câu 10', pts: 0.6, img: FM + 'f14q10.svg',
      text: 'Cân thăng bằng cho biết 4 hình tam giác nặng bằng 2 hình vuông. Hỏi 1 hình vuông nặng bằng mấy hình tam giác?',
      opts: FM5('1 hình', '3 hình', '4 hình', '2 hình', '8 hình'), ans: 'D',
      why: '2 hình vuông nặng bằng 4 tam giác nên 1 hình vuông nặng bằng: 4 : 2 = 2 (hình tam giác).' },

    { sec: FB, name: 'Câu 11', pts: 0.8,
      text: '3 cây bút chì đổi được 1 quyển vở; 2 quyển vở đổi được 1 hộp màu. Hỏi cần bao nhiêu cây bút chì để đổi được 1 hộp màu?',
      opts: FM5('6 cây', '3 cây', '5 cây', '8 cây', '9 cây'), ans: 'A',
      why: '1 hộp màu đổi được 2 quyển vở, mà mỗi quyển vở cần 3 cây bút chì. Vậy cần: 3 × 2 = 6 (cây bút chì).' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: '1 quả dưa nặng bằng 3 quả cam, 1 quả cam nặng bằng 2 quả quýt. Hỏi 1 quả dưa nặng bằng mấy quả quýt?',
      opts: FM5('4 quả', '5 quả', '8 quả', '6 quả', '9 quả'), ans: 'D',
      why: '1 quả dưa = 3 quả cam, mà mỗi quả cam = 2 quả quýt. Vậy 1 quả dưa = 2 × 3 = 6 (quả quýt).' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f14q14.svg',
      text: 'Hai cân đều thăng bằng. Hỏi mỗi hình tròn nặng bao nhiêu ki-lô-gam?',
      opts: FM5('2 kg', '3 kg', '4 kg', '6 kg', '8 kg'), ans: 'C',
      why: 'Cân thứ nhất: 3 hình vuông nặng 24 kg nên mỗi hình vuông nặng 24 : 3 = 8 (kg). Cân thứ hai: 1 hình vuông = 2 hình tròn nên mỗi hình tròn nặng: 8 : 2 = 4 (kg).' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Cứ 4 gói kẹo xếp được 1 hộp. Biết 3 hộp có tất cả 48 cái kẹo. Hỏi mỗi gói có bao nhiêu cái kẹo?',
      opts: FM5('3 cái', '4 cái', '6 cái', '8 cái', '12 cái'), ans: 'B',
      why: 'Số gói trong 3 hộp: 4 × 3 = 12 (gói). Mỗi gói có: 48 : 12 = 4 (cái kẹo).' },
    { sec: FB, name: 'Câu 15', pts: 0.8,
      text: '2 con vịt nặng bằng 3 con gà. Hỏi 6 con vịt nặng bằng mấy con gà?',
      opts: FM5('4 con', '6 con', '8 con', '12 con', '9 con'), ans: 'E',
      why: '6 con vịt gấp 3 lần 2 con vịt nên số gà cũng gấp 3 lần: 3 × 3 = 9 (con gà).' },
  ],
},

/* ═══════════ ĐỀ 15 — TỔNG ÔN ═══════════ */
{
  id: 1015, title: 'CĐ 15 · Tổng ôn – thử sức', time: 40,
  questions: [
    { sec: FA, name: 'Câu 1', pts: 0.6,
      text: 'Tính nhanh: <b>25 + 37 + 75</b>',
      opts: FM5('127', '137', '132', '147', '157'), ans: 'B',
      why: 'Ghép 25 + 75 = 100 cho tròn trăm trước, rồi 100 + 37 = 137.' },
    { sec: FA, name: 'Câu 2', pts: 0.6, img: FM + 'f15q2.svg',
      text: 'Tìm số thích hợp thay cho dấu hỏi chấm.',
      opts: FM5('21', '24', '30', '25', '35'), ans: 'D',
      why: 'Mỗi số hơn số liền trước 5 đơn vị: 5; 10; 15; 20. Số tiếp theo là 20 + 5 = 25.' },
    { sec: FA, name: 'Câu 3', pts: 0.6,
      text: 'Hôm nay là thứ Năm. Hỏi 3 ngày nữa là thứ mấy?',
      opts: FM5('Chủ nhật', 'Thứ Sáu', 'Thứ Bảy', 'Thứ Hai', 'Thứ Ba'), ans: 'A',
      why: 'Đếm tiếp từ thứ Năm: Sáu (1), Bảy (2), Chủ nhật (3).' },
    { sec: FA, name: 'Câu 4', pts: 0.6,
      text: 'Bác thợ cưa một khúc gỗ thành 6 đoạn, mỗi lần cưa hết 4 phút. Hỏi bác cưa xong hết bao nhiêu phút?',
      opts: FM5('16 phút', '24 phút', '20 phút', '28 phút', '30 phút'), ans: 'C',
      why: 'Muốn được 6 đoạn chỉ cần cưa 6 − 1 = 5 (lần). Thời gian: 4 × 5 = 20 (phút).' },
    { sec: FA, name: 'Câu 5', pts: 0.6, img: FM + 'f15q5.svg',
      text: 'Dựa vào biểu đồ, màu bóng nào có nhiều quả nhất?',
      opts: FM5('Màu xanh', 'Màu vàng', 'Xanh và đỏ bằng nhau', 'Không xác định được', 'Màu đỏ'), ans: 'E',
      why: 'Cột màu đỏ cao nhất — 20 quả, nhiều hơn màu xanh (12 quả) và màu vàng (8 quả).' },
    { sec: FA, name: 'Câu 6', pts: 0.6,
      text: 'Ba bạn gặp nhau, mỗi bạn bắt tay với hai bạn còn lại đúng một lần. Hỏi có bao nhiêu cái bắt tay?',
      opts: FM5('2 cái', '4 cái', '6 cái', '3 cái', '9 cái'), ans: 'D',
      why: 'Bạn thứ nhất bắt tay 2 bạn, bạn thứ hai bắt thêm 1 cái mới. Tổng: 2 + 1 = 3 (cái bắt tay).' },
    { sec: FA, name: 'Câu 7', pts: 0.6,
      text: 'Số lớn nhất có ba chữ số là:',
      opts: FM5('100', '999', '900', '987', '1 000'), ans: 'B',
      why: 'Muốn lớn nhất thì cả ba chữ số đều là 9, được số 999 (1 000 đã có bốn chữ số).' },
    { sec: FA, name: 'Câu 8', pts: 0.6, img: FM + 'f15q8.svg',
      text: 'Hình bên được xếp từ các khối lập phương nhỏ bằng nhau. Hỏi có tất cả bao nhiêu khối?',
      opts: FM5('3 khối', '4 khối', '6 khối', '8 khối', '5 khối'), ans: 'E',
      why: 'Có 4 vị trí ở tầng dưới, trong đó một vị trí được chồng thêm 1 khối nữa. Tất cả: 4 + 1 = 5 (khối).' },
    { sec: FA, name: 'Câu 9', pts: 0.6,
      text: 'Bạn Nam đứng thứ 3 từ bên trái và thứ 5 từ bên phải trong một hàng. Hỏi hàng đó có bao nhiêu bạn?',
      opts: FM5('7 bạn', '6 bạn', '8 bạn', '9 bạn', '15 bạn'), ans: 'A',
      why: 'Số bạn trong hàng: 3 + 5 − 1 = 7 (bạn).' },
    { sec: FA, name: 'Câu 10', pts: 0.6,
      text: '<b>1 giờ 15 phút = … phút</b>. Số thích hợp điền vào chỗ chấm là:',
      opts: FM5('65', '70', '75', '80', '115'), ans: 'C',
      why: '1 giờ = 60 phút nên 1 giờ 15 phút = 60 + 15 = 75 (phút).' },

    { sec: FB, name: 'Câu 11', pts: 0.8, img: FM + 'f15q11.svg',
      text: 'Đồng hồ bên đang chỉ giờ hiện tại. Hỏi sau 45 phút nữa là mấy giờ?',
      opts: FM5('7 giờ', '7 giờ 30 phút', '7 giờ 15 phút', '7 giờ 45 phút', '6 giờ 75 phút'), ans: 'C',
      why: 'Đồng hồ chỉ 6 giờ 30 phút. Thêm 30 phút được 7 giờ, còn dư 15 phút nữa nên là 7 giờ 15 phút.' },
    { sec: FB, name: 'Câu 12', pts: 0.8,
      text: 'Trong sân có 8 con vừa gà vừa thỏ, đếm được tất cả 22 cái chân. Hỏi có bao nhiêu con thỏ?',
      opts: FM5('3 con', '2 con', '4 con', '5 con', '6 con'), ans: 'A',
      why: 'Giả sử cả 8 con đều là gà thì có 2 × 8 = 16 (chân), thiếu 22 − 16 = 6 (chân). Số thỏ: 6 : 2 = 3 (con).' },
    { sec: FB, name: 'Câu 13', pts: 0.8, img: FM + 'f15q13.svg',
      text: 'Cân thăng bằng cho biết 3 hình tròn nặng bằng 6 hình tam giác. Hỏi 1 hình tròn nặng bằng mấy hình tam giác?',
      opts: FM5('1 hình', '3 hình', '6 hình', '9 hình', '2 hình'), ans: 'E',
      why: '3 hình tròn nặng bằng 6 tam giác nên mỗi hình tròn nặng bằng: 6 : 3 = 2 (hình tam giác).' },
    { sec: FB, name: 'Câu 14', pts: 0.8,
      text: 'Một số cộng thêm 9 rồi bớt đi 4 thì được 20. Hỏi số đó là số nào?',
      opts: FM5('7', '15', '13', '16', '25'), ans: 'B',
      why: 'Tính ngược từ cuối: 20 + 4 = 24; 24 − 9 = 15. Thử lại: 15 + 9 = 24; 24 − 4 = 20, đúng.' },
    { sec: FB, name: 'Câu 15', pts: 0.8, img: FM + 'f15q15.svg',
      text: 'Hỏi trên hình có tất cả bao nhiêu <b>hình vuông</b>?',
      opts: FM5('2 hình', '4 hình', '8 hình', '5 hình', '9 hình'), ans: 'D',
      why: 'Hình vuông nhỏ (cỡ 1 ô): 4 hình. Hình vuông lớn (cỡ 2 × 2 ô): 1 hình. Tổng: 4 + 1 = 5 (hình vuông).' },
  ],
},

];

// Chèn ngay sau môn "Tư duy ASMO/AMO" để các môn tư duy nằm cạnh nhau
{
  const i = SUBJECTS.findIndex(s => s.id === 'amo2');
  SUBJECTS.splice(i < 0 ? SUBJECTS.length : i + 1, 0, {
    id: 'fmo2', name: 'FMO – Toán tư duy', short: 'FMO 2', icon: '🧩', grade: 2,
    exams: FMO2_EXAMS, ready: true,
    heroTitle: 'FMO / Toán tư duy lớp 2 — bản hạ độ khó',
    heroMeta: '📚 15 chuyên đề &nbsp;•&nbsp; 225 câu &nbsp;•&nbsp; ⏱ 40 phút mỗi đề &nbsp;•&nbsp; hình minh hoạ · lời giải chi tiết',
  });
}
