// ĐẠO ĐỨC — LỚP 5 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// 8 chủ đề chính của chương trình Đạo đức lớp 5:
//   - Em yêu Tổ quốc Việt Nam
//   - Tôn trọng sự đa dạng của các dân tộc và các nền văn hoá
//   - Vượt qua khó khăn
//   - Bảo vệ cái đúng, cái tốt
//   - Lập kế hoạch cá nhân
//   - Phòng, tránh xâm hại (an toàn cho bản thân)
//   - Sử dụng tiền hợp lí
//   - Có trách nhiệm với việc làm của mình
//
// Mỗi câu là một tình huống / hành vi đúng - sai; đáp án đúng là ứng xử chuẩn mực.
// Chủ đề phòng tránh xâm hại được viết tế nhị, phù hợp lứa tuổi lớp 5.

const DAODUC5_EXAMS = [

/* ═══════════ ĐỀ 1 — EM YÊU TỔ QUỐC VIỆT NAM ═══════════ */
{
  id: 9221, title: 'Đề 1 · Em yêu Tổ quốc Việt Nam', time: 20,
  questions: [
    { sec: 'Yêu Tổ quốc', name: 'Câu 1', pts: 1,
      text: 'Quốc kì của nước Việt Nam có đặc điểm nào?',
      opts: o4('Nền xanh, ngôi sao trắng', 'Nền đỏ, ngôi sao vàng năm cánh ở giữa', 'Nền vàng, ngôi sao đỏ', 'Ba sọc ngang xanh trắng đỏ'), ans: 'B',
      why: 'Quốc kì Việt Nam là lá cờ nền đỏ, ở giữa có ngôi sao vàng năm cánh.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 2', pts: 1,
      text: 'Khi chào cờ và hát Quốc ca, em cần có thái độ thế nào?',
      opts: o4('Đứng nghiêm trang, hát to, rõ ràng', 'Vừa hát vừa đùa nghịch', 'Ngồi nói chuyện riêng', 'Quay ngang quay ngửa'), ans: 'A',
      why: 'Chào cờ, hát Quốc ca phải đứng nghiêm trang, hát rõ ràng để thể hiện lòng tôn kính Tổ quốc.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 3', pts: 1,
      text: 'Việc làm nào thể hiện tình yêu quê hương, đất nước của học sinh?',
      opts: o4('Vẽ bậy lên di tích', 'Xả rác nơi công cộng', 'Chê bai quê hương mình', 'Chăm học, giữ gìn cảnh quan, tìm hiểu lịch sử nước nhà'), ans: 'D',
      why: 'Chăm học, giữ gìn cảnh quan và tìm hiểu lịch sử là cách học sinh thể hiện tình yêu đất nước.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 4', pts: 1,
      text: 'Vua Hùng được nhân dân ta ghi nhớ công ơn vì điều gì?',
      opts: o4('Buôn bán giỏi', 'Xây nhiều nhà cao tầng', 'Có công dựng nước', 'Sáng chế máy móc'), ans: 'C',
      why: 'Các Vua Hùng có công dựng nước, nên hằng năm nhân dân ta tổ chức Giỗ Tổ để tưởng nhớ.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 5', pts: 1,
      text: 'Khi thấy khách nước ngoài hỏi đường ở khu di tích, em nên làm gì?',
      opts: o4('Bỏ đi vì ngại', 'Chỉ dẫn lịch sự, thân thiện trong khả năng của mình', 'Giả vờ không nghe thấy', 'Nói xấu du khách'), ans: 'B',
      why: 'Chỉ dẫn lịch sự, thân thiện giúp bạn bè quốc tế có ấn tượng đẹp về con người Việt Nam.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 6', pts: 1,
      text: 'Hành động nào KHÔNG thể hiện lòng tự hào dân tộc?',
      opts: o4('Chê tiếng Việt là quê mùa, thích nói chê bai nước mình', 'Giới thiệu món ăn, danh lam của quê hương', 'Mặc áo dài trong ngày lễ', 'Kể chuyện anh hùng dân tộc cho bạn nghe'), ans: 'A',
      why: 'Chê bai tiếng nói, đất nước mình là thái độ sai, không có lòng tự hào dân tộc.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 7', pts: 1,
      text: 'Ngày 2 tháng 9 hằng năm là ngày gì của nước ta?',
      opts: o4('Ngày Nhà giáo Việt Nam', 'Ngày Quốc tế Thiếu nhi', 'Ngày Thầy thuốc', 'Ngày Quốc khánh'), ans: 'D',
      why: 'Ngày 2/9 là ngày Quốc khánh, kỉ niệm Bác Hồ đọc Tuyên ngôn Độc lập khai sinh nước ta.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 8', pts: 1,
      text: 'Đối với các chú bộ đội, thương binh, gia đình liệt sĩ, em cần có thái độ nào?',
      opts: o4('Coi thường', 'Không quan tâm', 'Biết ơn, kính trọng, giúp đỡ khi có thể', 'Trêu chọc'), ans: 'C',
      why: 'Các thế hệ cha anh đã hi sinh để bảo vệ Tổ quốc, ta cần biết ơn, kính trọng và giúp đỡ.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 9', pts: 1,
      text: 'Bạn Nam định viết tên mình lên bức tường của một khu di tích. Em nên làm gì?',
      opts: o4('Cùng viết cho vui', 'Khuyên bạn không nên vì làm hỏng di tích chung', 'Cổ vũ bạn viết', 'Mặc kệ bạn'), ans: 'B',
      why: 'Di tích là tài sản chung của đất nước; cần khuyên bạn không viết vẽ, phá hoại.' },
    { sec: 'Yêu Tổ quốc', name: 'Câu 10', pts: 1,
      text: 'Câu nào nói đúng về Tổ quốc Việt Nam?',
      opts: o4('Là quê hương, đất nước mà em có trách nhiệm yêu quý, dựng xây', 'Là nơi khác, không liên quan đến em', 'Chỉ là nơi để đi du lịch', 'Không cần bảo vệ'), ans: 'A',
      why: 'Tổ quốc là quê hương, đất nước; mỗi người dân, kể cả học sinh, đều có trách nhiệm yêu quý và góp phần xây dựng.' },
  ],
},

/* ═══════════ ĐỀ 2 — TÔN TRỌNG SỰ ĐA DẠNG CỦA CÁC DÂN TỘC ═══════════ */
{
  id: 9222, title: 'Đề 2 · Tôn trọng sự đa dạng của các dân tộc', time: 20,
  questions: [
    { sec: 'Đa dạng dân tộc', name: 'Câu 1', pts: 1,
      text: 'Nước Việt Nam ta có bao nhiêu dân tộc anh em cùng chung sống?',
      opts: o4('54 dân tộc', '3 dân tộc', '10 dân tộc', 'Chỉ có 1 dân tộc'), ans: 'A',
      why: 'Việt Nam là quốc gia có 54 dân tộc anh em cùng chung sống, đoàn kết một nhà.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 2', pts: 1,
      text: 'Bạn học cùng lớp là người dân tộc thiểu số, nói tiếng phổ thông chưa sõi. Em nên làm gì?',
      opts: o4('Chế giễu cách nói của bạn', 'Không chơi với bạn', 'Bắt chước để trêu bạn', 'Kiên nhẫn, thân thiện, giúp bạn hoà nhập'), ans: 'D',
      why: 'Cần tôn trọng, thân thiện và giúp bạn hoà nhập, không được chế giễu sự khác biệt.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 3', pts: 1,
      text: 'Trang phục, tiếng nói, lễ hội riêng của mỗi dân tộc thể hiện điều gì?',
      opts: o4('Sự lạc hậu', 'Điều đáng chê cười', 'Nét văn hoá riêng đáng quý cần được tôn trọng', 'Sự chia rẽ'), ans: 'C',
      why: 'Mỗi dân tộc có nét văn hoá riêng; đó là vốn quý của đất nước, cần được tôn trọng, giữ gìn.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 4', pts: 1,
      text: 'Thái độ nào là đúng khi tìm hiểu về phong tục của một dân tộc khác với mình?',
      opts: o4('Cho rằng phong tục của mình mới đúng, của người khác là sai', 'Cởi mở, học hỏi và tôn trọng sự khác biệt', 'Cười nhạo phong tục lạ', 'Không thèm tìm hiểu'), ans: 'B',
      why: 'Cần cởi mở học hỏi và tôn trọng, không áp đặt hay coi thường phong tục của dân tộc khác.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 5', pts: 1,
      text: 'Vì sao các dân tộc trên đất nước ta cần đoàn kết?',
      opts: o4('Để cùng xây dựng và bảo vệ đất nước', 'Để tranh giành với nhau', 'Vì bị bắt buộc', 'Không cần đoàn kết'), ans: 'A',
      why: 'Đoàn kết giữa các dân tộc giúp cùng nhau xây dựng, bảo vệ và phát triển đất nước.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 6', pts: 1,
      text: 'Khi xem một điệu múa của dân tộc bạn chưa từng biết, em nên?',
      opts: o4('Bỏ ra ngoài chê chán', 'Cười cợt trang phục của họ', 'Nói to gây mất trật tự', 'Chăm chú xem, vỗ tay tán thưởng'), ans: 'D',
      why: 'Chăm chú thưởng thức và cổ vũ là cách thể hiện sự tôn trọng nét đẹp văn hoá của dân tộc khác.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 7', pts: 1,
      text: 'Người ở các quốc gia khác cũng có ngôn ngữ, phong tục khác ta. Em nên nghĩ thế nào?',
      opts: o4('Chỉ văn hoá nước ta là hay', 'Văn hoá nước khác đều xấu', 'Mỗi nước có nét văn hoá riêng, đều đáng được tôn trọng', 'Không cần biết đến'), ans: 'C',
      why: 'Mỗi quốc gia, dân tộc có bản sắc riêng; ta nên tôn trọng sự đa dạng của các nền văn hoá.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 8', pts: 1,
      text: 'Hành vi nào thể hiện sự KHÔNG tôn trọng dân tộc khác?',
      opts: o4('Học vài câu chào bằng tiếng của bạn dân tộc thiểu số', 'Gọi bạn bằng biệt danh trêu chọc dựa vào dân tộc của bạn', 'Mời bạn kể về lễ hội quê bạn', 'Cùng bạn mặc thử trang phục dân tộc'), ans: 'B',
      why: 'Đặt biệt danh trêu chọc dựa vào dân tộc là hành vi thiếu tôn trọng, gây tổn thương bạn.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 9', pts: 1,
      text: 'Câu tục ngữ nào nói về tinh thần đoàn kết các dân tộc anh em?',
      opts: o4('Bầu ơi thương lấy bí cùng', 'Ăn quả nhớ kẻ trồng cây', 'Có công mài sắt có ngày nên kim', 'Đi một ngày đàng học một sàng khôn'), ans: 'A',
      why: '"Bầu ơi thương lấy bí cùng" nhắc mọi người trong một nhà, một nước phải thương yêu, đùm bọc nhau.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 10', pts: 1,
      text: 'Trong lớp có nhiều bạn đến từ các vùng miền khác nhau. Em nên?',
      opts: o4('Chỉ chơi với bạn cùng quê', 'Chia bè phái theo vùng miền', 'Chê giọng nói vùng khác', 'Hoà đồng, chơi thân với tất cả các bạn'), ans: 'D',
      why: 'Hoà đồng, thân thiện với mọi bạn dù khác vùng miền thể hiện sự tôn trọng và đoàn kết.' },
  ],
},

/* ═══════════ ĐỀ 3 — VƯỢT QUA KHÓ KHĂN ═══════════ */
{
  id: 9223, title: 'Đề 3 · Vượt qua khó khăn', time: 20,
  questions: [
    { sec: 'Vượt khó', name: 'Câu 1', pts: 1,
      text: 'Gặp bài toán khó, em nên làm gì?',
      opts: o4('Bỏ luôn không làm', 'Chép bài của bạn', 'Xé vở đi', 'Bình tĩnh suy nghĩ, thử nhiều cách, hỏi khi thật cần'), ans: 'D',
      why: 'Bình tĩnh suy nghĩ và kiên trì thử nhiều cách là biểu hiện của tinh thần vượt khó.' },
    { sec: 'Vượt khó', name: 'Câu 2', pts: 1,
      text: 'Câu tục ngữ "Có công mài sắt, có ngày nên kim" khuyên ta điều gì?',
      opts: o4('Làm việc gì cũng nên bỏ giữa chừng', 'Chỉ cần may mắn', 'Kiên trì, bền bỉ sẽ thành công', 'Không cần cố gắng'), ans: 'C',
      why: 'Câu tục ngữ khuyên ta phải kiên trì, bền bỉ thì việc khó mấy cũng làm được.' },
    { sec: 'Vượt khó', name: 'Câu 3', pts: 1,
      text: 'Bạn Lan nhà nghèo nhưng vẫn cố gắng học giỏi. Thái độ đúng của em là?',
      opts: o4('Coi thường vì bạn nghèo', 'Khâm phục, học tập tinh thần vượt khó của bạn', 'Xa lánh bạn', 'Chế giễu bạn'), ans: 'B',
      why: 'Bạn vượt khó vươn lên rất đáng khâm phục; ta nên quý mến và học tập tinh thần đó.' },
    { sec: 'Vượt khó', name: 'Câu 4', pts: 1,
      text: 'Khi tập một môn thể thao mãi chưa được, em nên?',
      opts: o4('Kiên trì luyện tập thêm, rút kinh nghiệm', 'Nản chí bỏ cuộc ngay', 'Đổ lỗi cho dụng cụ', 'Ghen tị với người giỏi hơn'), ans: 'A',
      why: 'Kiên trì luyện tập và rút kinh nghiệm sẽ giúp em tiến bộ, đó là cách vượt qua khó khăn.' },
    { sec: 'Vượt khó', name: 'Câu 5', pts: 1,
      text: 'Đâu là biểu hiện của người biết vượt khó trong học tập?',
      opts: o4('Nhờ người khác làm hộ hết', 'Chờ đến khi giỏi rồi mới học', 'Chỉ học môn mình thích', 'Tự giác ôn bài, cố gắng làm hết bài dù mệt'), ans: 'D',
      why: 'Tự giác, cố gắng hoàn thành nhiệm vụ dù khó khăn, mệt mỏi là biểu hiện của người vượt khó.' },
    { sec: 'Vượt khó', name: 'Câu 6', pts: 1,
      text: 'Khi gặp khó khăn quá sức mình, cách xử lí khôn ngoan là?',
      opts: o4('Giấu kín, tự chịu đựng đến kiệt sức', 'Trốn tránh mọi việc', 'Mạnh dạn chia sẻ, nhờ thầy cô, người thân giúp đỡ', 'Trách móc bản thân suốt ngày'), ans: 'C',
      why: 'Biết chia sẻ và nhờ người tin cậy giúp đỡ đúng lúc cũng là một cách vượt qua khó khăn.' },
    { sec: 'Vượt khó', name: 'Câu 7', pts: 1,
      text: 'Hôm nay trời mưa to, đường ngập, nhưng em vẫn cố đến lớp đúng giờ. Việc đó cho thấy em là người?',
      opts: o4('Dại dột', 'Có ý chí, chăm chỉ, biết vượt khó', 'Thích khoe khoang', 'Không biết giữ sức khoẻ'), ans: 'B',
      why: 'Vượt qua trở ngại để hoàn thành nhiệm vụ học tập thể hiện ý chí và tinh thần vượt khó.' },
    { sec: 'Vượt khó', name: 'Câu 8', pts: 1,
      text: 'Điều gì giúp em có thêm động lực để vượt qua khó khăn?',
      opts: o4('Đặt mục tiêu rõ ràng và tin vào bản thân', 'So sánh rồi tự ti', 'Luôn nghĩ mình sẽ thất bại', 'Chờ người khác làm giúp'), ans: 'A',
      why: 'Đặt mục tiêu và tin vào khả năng của mình tạo động lực giúp ta kiên trì vượt khó.' },
    { sec: 'Vượt khó', name: 'Câu 9', pts: 1,
      text: 'Thấy bạn định bỏ cuộc khi luyện chữ chưa đẹp, em nên nói gì?',
      opts: o4('"Chữ cậu xấu lắm, bỏ đi"', '"Đằng nào cũng không được đâu"', '"Kệ cậu"', '"Cứ kiên trì luyện thêm, nhất định sẽ đẹp hơn"'), ans: 'D',
      why: 'Động viên bạn kiên trì là cách giúp bạn có thêm nghị lực vượt qua khó khăn.' },
    { sec: 'Vượt khó', name: 'Câu 10', pts: 1,
      text: 'Người có nghị lực vượt khó thường có kết quả thế nào trong cuộc sống?',
      opts: o4('Dễ dàng bỏ cuộc', 'Luôn thất bại', 'Đạt được điều mình mong muốn, được mọi người quý trọng', 'Không ai để ý đến'), ans: 'C',
      why: 'Người kiên trì vượt khó thường đạt kết quả tốt và được mọi người yêu quý, nể trọng.' },
  ],
},

/* ═══════════ ĐỀ 4 — BẢO VỆ CÁI ĐÚNG, CÁI TỐT ═══════════ */
{
  id: 9224, title: 'Đề 4 · Bảo vệ cái đúng, cái tốt', time: 20,
  questions: [
    { sec: 'Bảo vệ cái đúng', name: 'Câu 1', pts: 1,
      text: 'Thấy bạn nhặt được của rơi và tìm cách trả lại người mất, em nên?',
      opts: o4('Chê bạn dại', 'Xui bạn giữ lại', 'Khen ngợi và ủng hộ việc làm của bạn', 'Làm ngơ'), ans: 'C',
      why: 'Trả lại của rơi là việc tốt; ta nên khen ngợi, ủng hộ và học tập bạn.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 2', pts: 1,
      text: 'Trong giờ kiểm tra, bạn bên cạnh giở tài liệu chép bài. Em nên?',
      opts: o4('Chép cùng cho công bằng', 'Khuyên bạn không nên và trung thực làm bài của mình', 'Cổ vũ bạn', 'Giấu giúp bạn'), ans: 'B',
      why: 'Trung thực trong thi cử là cái đúng; em cần giữ đúng và khuyên bạn không gian lận.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 3', pts: 1,
      text: 'Cả nhóm định đổ lỗi làm vỡ cửa kính cho một bạn không có mặt hôm đó. Em nên?',
      opts: o4('Nói rõ sự thật để bảo vệ bạn bị oan', 'Đồng ý cho xong chuyện', 'Im lặng cho an toàn', 'Hùa theo cả nhóm'), ans: 'A',
      why: 'Bảo vệ cái đúng là dám nói sự thật để người vô tội không bị oan, dù số đông làm sai.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 4', pts: 1,
      text: 'Vì sao đôi khi bảo vệ cái đúng lại khó khăn?',
      opts: o4('Vì cái đúng không quan trọng', 'Vì không ai làm việc tốt', 'Vì làm sai dễ hơn', 'Vì có thể bị số đông phản đối, bị trêu chọc'), ans: 'D',
      why: 'Bảo vệ cái đúng đôi khi phải chịu áp lực, bị số đông phản đối, nên cần dũng cảm.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 5', pts: 1,
      text: 'Khi chứng kiến một bạn bắt nạt em nhỏ hơn, em nên làm gì?',
      opts: o4('Quay clip đăng lên mạng cho vui', 'Cổ vũ bạn lớn', 'Can ngăn nếu an toàn và báo ngay thầy cô, người lớn', 'Bỏ đi coi như không thấy'), ans: 'C',
      why: 'Can ngăn khi an toàn và báo người lớn là cách bảo vệ bạn yếu thế và bảo vệ điều đúng.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 6', pts: 1,
      text: 'Bạn thân rủ em cùng nói dối cô giáo để trốn trực nhật. Em nên?',
      opts: o4('Đồng ý vì là bạn thân', 'Từ chối và khuyên bạn nên trung thực, làm đúng phận sự', 'Nói dối giúp bạn', 'Giận bạn rồi mách lại để trả thù'), ans: 'B',
      why: 'Bảo vệ cái đúng nghĩa là không a dua làm điều sai, kể cả khi bạn thân rủ rê.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 7', pts: 1,
      text: 'Người dám bảo vệ lẽ phải thường được mọi người nhìn nhận thế nào?',
      opts: o4('Được tin tưởng, quý trọng', 'Bị mọi người xa lánh mãi mãi', 'Bị coi là kẻ xấu', 'Không ai quan tâm'), ans: 'A',
      why: 'Người trung thực, dám bảo vệ lẽ phải lâu dài sẽ được mọi người tin tưởng và quý trọng.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 8', pts: 1,
      text: 'Đâu là việc làm bảo vệ cái tốt trong lớp học?',
      opts: o4('Nói xấu bạn học giỏi vì ghen tị', 'Cười nhạo bạn hay giúp đỡ người khác', 'Rủ bạn cùng lười biếng', 'Bênh vực, cổ vũ những bạn làm việc tốt, học tập tấm gương tốt'), ans: 'D',
      why: 'Cổ vũ, bênh vực và noi theo những việc tốt chính là bảo vệ cái tốt trong tập thể.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 9', pts: 1,
      text: 'Khi em làm đúng mà bị hiểu lầm là sai, em nên?',
      opts: o4('Cãi nhau to tiếng', 'Khóc và bỏ chạy', 'Bình tĩnh giải thích, đưa ra bằng chứng cho việc đúng của mình', 'Nhận đại là mình sai'), ans: 'C',
      why: 'Bình tĩnh giải thích, chứng minh việc mình làm đúng là cách bảo vệ cái đúng một cách văn minh.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 10', pts: 1,
      text: 'Câu nào thể hiện đúng tinh thần bảo vệ lẽ phải?',
      opts: o4('"Ai làm gì mặc kệ"', '"Thấy đúng phải bảo vệ, thấy sai phải góp ý"', '"Cứ theo số đông cho lành"', '"Im lặng là vàng trong mọi trường hợp"'), ans: 'B',
      why: 'Thấy đúng biết bảo vệ, thấy sai dám góp ý chính là tinh thần bảo vệ cái đúng, cái tốt.' },
  ],
},

/* ═══════════ ĐỀ 5 — LẬP KẾ HOẠCH CÁ NHÂN ═══════════ */
{
  id: 9225, title: 'Đề 5 · Lập kế hoạch cá nhân', time: 20,
  questions: [
    { sec: 'Kế hoạch cá nhân', name: 'Câu 1', pts: 1,
      text: 'Lập kế hoạch cá nhân giúp em điều gì?',
      opts: o4('Làm việc lộn xộn hơn', 'Sắp xếp công việc hợp lí, không bỏ sót và đỡ mất thời gian', 'Quên hết việc cần làm', 'Chỉ để cho đẹp'), ans: 'B',
      why: 'Có kế hoạch giúp em sắp xếp công việc hợp lí, làm đủ việc và tiết kiệm thời gian.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 2', pts: 1,
      text: 'Bước đầu tiên khi lập kế hoạch cho một tuần học là gì?',
      opts: o4('Xác định những việc cần làm và mục tiêu', 'Đi chơi trước đã', 'Chờ bố mẹ nhắc', 'Bỏ qua, làm đến đâu hay đến đó'), ans: 'A',
      why: 'Trước hết cần xác định rõ những việc cần làm và mục tiêu, rồi mới sắp xếp thời gian.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 3', pts: 1,
      text: 'Một thời gian biểu hợp lí cần có những phần nào?',
      opts: o4('Chỉ có thời gian chơi', 'Chỉ có thời gian học', 'Chỉ có thời gian ngủ', 'Cân đối giữa học tập, nghỉ ngơi, giúp việc nhà và vui chơi'), ans: 'D',
      why: 'Thời gian biểu tốt phải cân đối học tập, nghỉ ngơi, giúp việc nhà và vui chơi.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 4', pts: 1,
      text: 'Khi đã lập kế hoạch, muốn có kết quả thì em cần?',
      opts: o4('Chỉ lập ra rồi để đấy', 'Thay đổi liên tục cho vui', 'Thực hiện nghiêm túc và kiên trì theo kế hoạch', 'Làm ngược lại kế hoạch'), ans: 'C',
      why: 'Kế hoạch chỉ có ích khi em thực hiện nghiêm túc, kiên trì theo đúng những gì đã đặt ra.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 5', pts: 1,
      text: 'Nếu hôm nay có việc đột xuất, kế hoạch bị lỡ một phần, em nên?',
      opts: o4('Bỏ luôn cả kế hoạch', 'Bình tĩnh điều chỉnh, sắp xếp lại cho phù hợp', 'Cáu gắt bỏ cuộc', 'Trách người khác'), ans: 'B',
      why: 'Kế hoạch có thể linh hoạt điều chỉnh khi có việc phát sinh, không nên bỏ hẳn.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 6', pts: 1,
      text: 'Việc nào nên được ưu tiên làm trước trong ngày đi học?',
      opts: o4('Học bài, làm bài tập và chuẩn bị cho ngày mai', 'Chơi điện tử', 'Xem hết một bộ phim dài', 'Ngủ cả buổi chiều'), ans: 'A',
      why: 'Việc quan trọng như học bài, làm bài, chuẩn bị đồ dùng cần được ưu tiên trước.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 7', pts: 1,
      text: 'Bạn An lập kế hoạch mỗi tối đọc sách 20 phút. Việc này thể hiện điều gì?',
      opts: o4('Sự lãng phí thời gian', 'Sự lười biếng', 'Thích khoe khoang', 'Biết đặt mục tiêu và rèn thói quen tốt'), ans: 'D',
      why: 'Đặt mục tiêu nhỏ, đều đặn mỗi ngày là cách lập kế hoạch để rèn thói quen tốt.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 8', pts: 1,
      text: 'Cuối tuần, em nên nhìn lại kế hoạch của mình để làm gì?',
      opts: o4('Để tự trách mình cả ngày', 'Để so bì với bạn', 'Xem việc nào đã làm được, việc nào chưa để rút kinh nghiệm', 'Không cần nhìn lại'), ans: 'C',
      why: 'Nhìn lại kế hoạch giúp em biết mình đã làm được gì, còn thiếu gì để điều chỉnh tốt hơn.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 9', pts: 1,
      text: 'Người không có kế hoạch làm việc thường gặp tình trạng nào?',
      opts: o4('Làm việc gọn gàng, đúng hạn', 'Vội vàng, quên việc, làm không kịp', 'Luôn dư dả thời gian', 'Rất thảnh thơi'), ans: 'B',
      why: 'Thiếu kế hoạch dễ dẫn đến vội vàng, quên việc và làm không kịp thời hạn.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 10', pts: 1,
      text: 'Một kế hoạch tốt cần đặt mục tiêu như thế nào?',
      opts: o4('Rõ ràng, vừa sức và phù hợp với bản thân', 'Thật xa vời, không thể đạt được', 'Mơ hồ, chung chung', 'Bắt chước y hệt của bạn'), ans: 'A',
      why: 'Mục tiêu cần rõ ràng, vừa sức và phù hợp với bản thân thì mới thực hiện được.' },
  ],
},

/* ═══════════ ĐỀ 6 — PHÒNG, TRÁNH XÂM HẠI — AN TOÀN BẢN THÂN ═══════════ */
{
  id: 9226, title: 'Đề 6 · Phòng, tránh xâm hại — an toàn bản thân', time: 20,
  questions: [
    { sec: 'An toàn bản thân', name: 'Câu 1', pts: 1,
      text: 'Những vùng riêng tư trên cơ thể được quần áo lót che kín. Ai được phép nhìn, chạm vào một cách tuỳ tiện?',
      opts: o4('Không ai được tuỳ tiện; đó là vùng riêng tư của em', 'Bất kì ai cũng được', 'Người lạ cho quà', 'Bạn cùng lớp'), ans: 'A',
      why: 'Các vùng riêng tư là của riêng em; không ai được tuỳ tiện nhìn hay chạm vào.' },
    { sec: 'An toàn bản thân', name: 'Câu 2', pts: 1,
      text: 'Khi có người khiến em cảm thấy sợ hãi, khó chịu bằng lời nói hoặc hành động đụng chạm, em nên?',
      opts: o4('Im lặng chịu đựng', 'Giữ bí mật vì xấu hổ', 'Tự trách mình', 'Nói "Không", tránh xa và kể ngay với bố mẹ, thầy cô'), ans: 'D',
      why: 'Em có quyền nói "Không", rời khỏi đó và kể ngay với người lớn tin cậy để được bảo vệ.' },
    { sec: 'An toàn bản thân', name: 'Câu 3', pts: 1,
      text: 'Một người lạ rủ em đi theo, hứa cho quà và dặn "đừng nói với ai". Em nên?',
      opts: o4('Đi theo vì có quà', 'Giữ bí mật như lời họ dặn', 'Từ chối, không đi và kể ngay cho bố mẹ, thầy cô biết', 'Nhận quà rồi mới đi'), ans: 'C',
      why: 'Người tốt sẽ không bắt em giấu bố mẹ; cần từ chối và báo ngay cho người lớn tin cậy.' },
    { sec: 'An toàn bản thân', name: 'Câu 4', pts: 1,
      text: 'Ai là những người em có thể tin tưởng để chia sẻ khi thấy không an toàn?',
      opts: o4('Người lạ trên mạng', 'Bố mẹ, thầy cô, người thân tin cậy', 'Người vừa quen ngoài đường', 'Không nói với ai cả'), ans: 'B',
      why: 'Bố mẹ, thầy cô và người thân tin cậy là những người em nên tìm đến khi cần được giúp đỡ, bảo vệ.' },
    { sec: 'An toàn bản thân', name: 'Câu 5', pts: 1,
      text: 'Trên mạng, người lạ xin ảnh riêng tư và số điện thoại, địa chỉ nhà của em. Em nên?',
      opts: o4('Tuyệt đối không gửi và kể cho bố mẹ biết', 'Gửi ngay cho họ', 'Cho địa chỉ để họ đến chơi', 'Kết bạn thân thiết'), ans: 'A',
      why: 'Không chia sẻ ảnh, thông tin riêng tư cho người lạ trên mạng và cần báo cho bố mẹ biết.' },
    { sec: 'An toàn bản thân', name: 'Câu 6', pts: 1,
      text: 'Nếu chẳng may bị người khác xâm hại hoặc đe doạ, điều quan trọng nhất em cần nhớ là?',
      opts: o4('Đó là lỗi của em nên phải giấu', 'Phải giữ bí mật mãi mãi', 'Tự chịu một mình', 'Đó KHÔNG phải lỗi của em; hãy kể ngay để được giúp đỡ'), ans: 'D',
      why: 'Bị xâm hại không bao giờ là lỗi của em; hãy dũng cảm kể với người tin cậy để được bảo vệ.' },
    { sec: 'An toàn bản thân', name: 'Câu 7', pts: 1,
      text: 'Số điện thoại nào là Tổng đài quốc gia bảo vệ trẻ em ở nước ta?',
      opts: o4('112', '119', '111', '100'), ans: 'C',
      why: 'Tổng đài 111 là Tổng đài quốc gia bảo vệ trẻ em, em có thể gọi khi cần giúp đỡ.' },
    { sec: 'An toàn bản thân', name: 'Câu 8', pts: 1,
      text: 'Khi ở nhà một mình, có người lạ gõ cửa đòi vào, em nên?',
      opts: o4('Mở cửa cho vào ngay', 'Không mở cửa, gọi điện cho bố mẹ hoặc người thân', 'Mời họ vào chơi', 'Ra ngoài đi theo họ'), ans: 'B',
      why: 'Không tự ý mở cửa cho người lạ; nên gọi cho bố mẹ, người thân để được hướng dẫn.' },
    { sec: 'An toàn bản thân', name: 'Câu 9', pts: 1,
      text: 'Bạn của em kể bị một người họ hàng đụng chạm khiến bạn sợ, nhưng dặn em giữ bí mật. Em nên?',
      opts: o4('Khuyên bạn kể với người lớn tin cậy và cùng bạn nói với thầy cô', 'Giữ bí mật cho bạn', 'Cười cho là bạn nói dối', 'Mặc kệ bạn'), ans: 'A',
      why: 'Đây là bí mật cần được nói ra; hãy giúp bạn tìm người lớn tin cậy để bạn được bảo vệ.' },
    { sec: 'An toàn bản thân', name: 'Câu 10', pts: 1,
      text: 'Quy tắc an toàn nào dưới đây là đúng?',
      opts: o4('Người lớn muốn gì em cũng phải nghe theo', 'Phải giữ mọi bí mật người lạ dặn', 'Không được kể với ai chuyện của mình', 'Cơ thể của em là của riêng em, em có quyền bảo vệ và nói "Không"'), ans: 'D',
      why: 'Cơ thể là của riêng em; em có quyền bảo vệ, được nói "Không" và tìm sự giúp đỡ khi cần.' },
  ],
},

/* ═══════════ ĐỀ 7 — SỬ DỤNG TIỀN HỢP LÍ ═══════════ */
{
  id: 9227, title: 'Đề 7 · Sử dụng tiền hợp lí', time: 20,
  questions: [
    { sec: 'Dùng tiền hợp lí', name: 'Câu 1', pts: 1,
      text: 'Được cho một khoản tiền tiêu vặt, cách dùng hợp lí là?',
      opts: o4('Tiêu hết ngay vào đồ chơi, quà vặt', 'Cho hết bạn để được khen', 'Mua thật nhiều bánh kẹo', 'Chi tiêu cần thiết, để dành một phần tiết kiệm'), ans: 'D',
      why: 'Dùng tiền hợp lí là chỉ chi cho việc cần thiết và biết để dành tiết kiệm một phần.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 2', pts: 1,
      text: 'Trước khi mua một món đồ, em nên tự hỏi điều gì?',
      opts: o4('"Bạn có thì mình cũng phải có"', '"Càng đắt càng tốt"', '"Món này mình có thật sự cần không?"', '"Cứ mua đã rồi tính"'), ans: 'C',
      why: 'Nên cân nhắc mình có thật sự cần món đồ đó không trước khi quyết định mua.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 3', pts: 1,
      text: 'Việc để dành tiền vào lợn đất, sổ tiết kiệm thể hiện điều gì?',
      opts: o4('Sự keo kiệt', 'Thói quen tiết kiệm, biết lo xa', 'Sự lãng phí', 'Sự khoe khoang'), ans: 'B',
      why: 'Tiết kiệm để dành cho việc cần sau này là thói quen tốt, biết lo xa, không phải keo kiệt.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 4', pts: 1,
      text: 'Phân biệt "cái mình cần" và "cái mình muốn" giúp em điều gì?',
      opts: o4('Ưu tiên chi cho thứ cần thiết, tránh lãng phí', 'Tiêu tiền lộn xộn hơn', 'Mua được nhiều đồ chơi hơn', 'Không có ích gì'), ans: 'A',
      why: 'Biết phân biệt cần và muốn giúp em ưu tiên chi tiêu đúng chỗ và tránh lãng phí.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 5', pts: 1,
      text: 'Bạn rủ em góp tiền tiết kiệm để mua quà tặng một bạn có hoàn cảnh khó khăn trong lớp. Em nên?',
      opts: o4('Từ chối vì tiếc tiền', 'Chê bạn kia nghèo', 'Giữ tiền cho riêng mình', 'Vui vẻ tham gia trong khả năng của mình'), ans: 'D',
      why: 'Dùng một phần tiền để giúp bạn khó khăn là cách chi tiêu ý nghĩa, thể hiện lòng nhân ái.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 6', pts: 1,
      text: 'Đồng tiền có được là nhờ đâu?',
      opts: o4('Tự nhiên mà có', 'Nhặt được ngoài đường', 'Do công sức lao động của bố mẹ, mọi người làm ra', 'Không cần làm gì cũng có'), ans: 'C',
      why: 'Tiền là thành quả lao động vất vả của bố mẹ và mọi người, nên phải biết trân trọng.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 7', pts: 1,
      text: 'Hành vi nào là lãng phí tiền bạc?',
      opts: o4('Mua đồ dùng học tập cần thiết', 'Đòi mua món đồ chơi giống hệt cái đang có chỉ vì bạn có', 'Để dành tiền mừng tuổi', 'Mua sách để đọc'), ans: 'B',
      why: 'Mua thứ đã có, không thật sự cần chỉ vì đua đòi là lãng phí tiền bạc.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 8', pts: 1,
      text: 'Ghi lại các khoản đã tiêu trong tuần giúp em điều gì?',
      opts: o4('Biết mình đã tiêu vào việc gì để chi tiêu hợp lí hơn', 'Mất thời gian vô ích', 'Tiêu nhiều hơn', 'Không có tác dụng'), ans: 'A',
      why: 'Ghi chép chi tiêu giúp em quản lí tiền tốt hơn và điều chỉnh cho hợp lí.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 9', pts: 1,
      text: 'Khi được lì xì ngày Tết, cách xử lí hợp lí là?',
      opts: o4('Tiêu sạch trong vài ngày', 'Đem đi cá cược', 'Khoe khoang với bạn bè', 'Nhờ bố mẹ giữ giúp hoặc để dành cho việc cần thiết'), ans: 'D',
      why: 'Nên để dành hoặc nhờ bố mẹ giữ giúp, dùng vào việc cần thiết thay vì tiêu hết ngay.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 10', pts: 1,
      text: 'Câu tục ngữ, thành ngữ nào khuyên ta biết tiết kiệm?',
      opts: o4('Chân cứng đá mềm', 'Nước chảy đá mòn', 'Năng nhặt chặt bị', 'Gần mực thì đen'), ans: 'C',
      why: '"Năng nhặt chặt bị" khuyên ta chăm góp nhặt, tiết kiệm từng chút thì sẽ có nhiều.' },
  ],
},

/* ═══════════ ĐỀ 8 — CÓ TRÁCH NHIỆM VỚI VIỆC LÀM CỦA MÌNH ═══════════ */
{
  id: 9228, title: 'Đề 8 · Có trách nhiệm với việc làm của mình', time: 20,
  questions: [
    { sec: 'Trách nhiệm', name: 'Câu 1', pts: 1,
      text: 'Em lỡ làm vỡ chiếc bình hoa của nhà. Việc làm có trách nhiệm là?',
      opts: o4('Giấu đi, đổ lỗi cho em bé', 'Vờ như không biết', 'Nhận lỗi, xin lỗi và dọn dẹp, tìm cách khắc phục', 'Đổ cho con mèo'), ans: 'C',
      why: 'Người có trách nhiệm dám nhận lỗi, xin lỗi và cố gắng khắc phục hậu quả việc mình gây ra.' },
    { sec: 'Trách nhiệm', name: 'Câu 2', pts: 1,
      text: 'Được phân công trực nhật nhưng em quên. Em nên?',
      opts: o4('Đổ cho bạn cùng ca', 'Nhận thiếu sót, xin lỗi và làm bù, lần sau ghi nhớ', 'Cãi rằng không phải phiên mình', 'Trốn về sớm'), ans: 'B',
      why: 'Có trách nhiệm là thừa nhận thiếu sót, làm bù và rút kinh nghiệm cho lần sau.' },
    { sec: 'Trách nhiệm', name: 'Câu 3', pts: 1,
      text: 'Trước khi làm một việc, người có trách nhiệm thường?',
      opts: o4('Suy nghĩ về hậu quả và cân nhắc rồi mới làm', 'Làm bừa rồi tính sau', 'Chờ người khác làm hộ', 'Làm cho xong để đối phó'), ans: 'A',
      why: 'Người có trách nhiệm biết suy nghĩ trước, cân nhắc hậu quả rồi mới quyết định làm.' },
    { sec: 'Trách nhiệm', name: 'Câu 4', pts: 1,
      text: 'Em hứa với bạn sẽ mang truyện cho bạn mượn nhưng lại quên. Em nên?',
      opts: o4('Lờ đi coi như không hứa', 'Trách bạn sao không nhắc', 'Nói dối là để quên ở nhà mãi', 'Xin lỗi bạn và mang cho bạn vào hôm sau'), ans: 'D',
      why: 'Giữ lời hứa là biểu hiện của trách nhiệm; lỡ quên thì phải xin lỗi và thực hiện cho bằng được.' },
    { sec: 'Trách nhiệm', name: 'Câu 5', pts: 1,
      text: 'Việc học tập là trách nhiệm của ai?',
      opts: o4('Chỉ của thầy cô', 'Của bố mẹ', 'Của chính bản thân mỗi học sinh', 'Không của ai cả'), ans: 'C',
      why: 'Học tập trước hết là trách nhiệm của chính mỗi học sinh với bản thân và tương lai của mình.' },
    { sec: 'Trách nhiệm', name: 'Câu 6', pts: 1,
      text: 'Khi được giao chăm sóc góc cây của lớp, em nên?',
      opts: o4('Bỏ mặc cho cây héo', 'Tưới cây đều đặn, nhổ cỏ, chăm sóc chu đáo', 'Đợi cô nhắc mới làm', 'Nhờ hết bạn khác'), ans: 'B',
      why: 'Hoàn thành tốt nhiệm vụ được giao, chăm sóc chu đáo là thể hiện tinh thần trách nhiệm.' },
    { sec: 'Trách nhiệm', name: 'Câu 7', pts: 1,
      text: 'Người biết nhận trách nhiệm về việc làm của mình sẽ?',
      opts: o4('Ngày càng tiến bộ và được mọi người tin cậy', 'Bị mọi người ghét bỏ', 'Luôn thất bại', 'Không ai chơi cùng'), ans: 'A',
      why: 'Dám nhận và sửa sai giúp em tiến bộ và được mọi người tin tưởng, quý mến.' },
    { sec: 'Trách nhiệm', name: 'Câu 8', pts: 1,
      text: 'Trong nhóm làm bài chung, bạn nào cũng ỷ lại người khác thì kết quả sẽ?',
      opts: o4('Rất tốt', 'Nhanh hơn', 'Không ảnh hưởng gì', 'Kém, vì không ai chịu trách nhiệm phần việc của mình'), ans: 'D',
      why: 'Nếu ai cũng ỷ lại, không làm tròn phần việc của mình thì kết quả chung sẽ kém.' },
    { sec: 'Trách nhiệm', name: 'Câu 9', pts: 1,
      text: 'Khi mắc lỗi, câu nói nào thể hiện tinh thần trách nhiệm?',
      opts: o4('"Không phải lỗi của con"', '"Tại bạn ấy cả"', '"Con xin lỗi, con sẽ sửa và làm lại cho đúng"', '"Con không biết gì hết"'), ans: 'C',
      why: 'Nhận lỗi và hứa sửa chữa, làm lại cho đúng là lời nói của người có trách nhiệm.' },
    { sec: 'Trách nhiệm', name: 'Câu 10', pts: 1,
      text: 'Ở nhà, việc làm nào thể hiện em có trách nhiệm?',
      opts: o4('Bày bừa rồi bỏ đấy', 'Tự giác học bài, giúp bố mẹ việc nhà vừa sức', 'Chờ nhắc mãi mới làm', 'Đùn hết việc cho anh chị'), ans: 'B',
      why: 'Tự giác học và giúp việc nhà vừa sức là cách em thể hiện trách nhiệm với bản thân và gia đình.' },
  ],
},

/* ═══════════ ĐỀ 9 — ÔN TẬP TỔNG HỢP (1) ═══════════ */
{
  id: 9229, title: 'Đề 9 · Ôn tập tổng hợp (1)', time: 20,
  questions: [
    { sec: 'Yêu Tổ quốc', name: 'Câu 1', pts: 1,
      text: 'Hành động nào thể hiện lòng yêu nước của học sinh lớp 5?',
      opts: o4('Xả rác ở khu di tích', 'Chăm học, giữ gìn tiếng Việt, bảo vệ môi trường quê hương', 'Chê bai đất nước mình', 'Phá hoại của công'), ans: 'B',
      why: 'Chăm học, giữ gìn tiếng Việt và bảo vệ môi trường là những việc yêu nước thiết thực.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 2', pts: 1,
      text: 'Với bạn đến từ dân tộc khác, vùng miền khác, em nên?',
      opts: o4('Tôn trọng, hoà đồng và học hỏi nét hay của bạn', 'Chế giễu giọng nói của bạn', 'Xa lánh bạn', 'Chia bè phái'), ans: 'A',
      why: 'Tôn trọng sự đa dạng, hoà đồng và học hỏi lẫn nhau là ứng xử đúng đắn.' },
    { sec: 'Vượt khó', name: 'Câu 3', pts: 1,
      text: 'Gặp khó khăn trong học tập, thái độ đúng là?',
      opts: o4('Bỏ cuộc ngay', 'Đổ lỗi hoàn cảnh', 'Trông chờ may mắn', 'Kiên trì cố gắng, tìm cách giải quyết'), ans: 'D',
      why: 'Kiên trì, chủ động tìm cách giải quyết là biểu hiện của tinh thần vượt khó.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 4', pts: 1,
      text: 'Thấy bạn bị đổ oan, em nên?',
      opts: o4('Im lặng cho an toàn', 'Hùa theo số đông', 'Dũng cảm nói ra sự thật để bảo vệ bạn', 'Cười nhạo bạn'), ans: 'C',
      why: 'Dám nói sự thật để bảo vệ người bị oan là biểu hiện của việc bảo vệ cái đúng.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 5', pts: 1,
      text: 'Lợi ích của việc lập thời gian biểu là gì?',
      opts: o4('Làm việc lộn xộn', 'Cân đối học và chơi, không bỏ sót việc', 'Quên nhiều việc hơn', 'Mất thời gian vô ích'), ans: 'B',
      why: 'Thời gian biểu giúp cân đối học tập, nghỉ ngơi và không bỏ sót việc cần làm.' },
    { sec: 'An toàn bản thân', name: 'Câu 6', pts: 1,
      text: 'Khi bị người khác đụng chạm khiến em thấy sợ, khó chịu, em cần?',
      opts: o4('Nói "Không", tránh xa và kể ngay với người lớn tin cậy', 'Im lặng chịu đựng', 'Giữ bí mật', 'Tự trách mình'), ans: 'A',
      why: 'Em có quyền nói "Không", rời đi và kể ngay với người lớn tin cậy để được bảo vệ.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 7', pts: 1,
      text: 'Cách sử dụng tiền tiêu vặt hợp lí là?',
      opts: o4('Tiêu hết vào quà vặt', 'Đua đòi mua sắm theo bạn', 'Mua thật nhiều đồ chơi', 'Chi cho việc cần thiết và để dành một phần'), ans: 'D',
      why: 'Chi cho việc cần thiết và biết tiết kiệm một phần là cách dùng tiền hợp lí.' },
    { sec: 'Trách nhiệm', name: 'Câu 8', pts: 1,
      text: 'Khi mắc lỗi, người có trách nhiệm sẽ?',
      opts: o4('Đổ lỗi cho người khác', 'Giấu giếm', 'Nhận lỗi và tìm cách sửa chữa', 'Bỏ mặc hậu quả'), ans: 'C',
      why: 'Nhận lỗi và sửa chữa là biểu hiện của người có trách nhiệm với việc làm của mình.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 9', pts: 1,
      text: 'Bạn rủ em cùng nói dối cô để trốn việc. Em nên?',
      opts: o4('Đồng ý vì nể bạn', 'Từ chối và khuyên bạn nên trung thực', 'Nói dối giúp bạn', 'Mách cô để trả thù bạn'), ans: 'B',
      why: 'Không a dua làm điều sai và biết khuyên bạn trung thực là bảo vệ cái đúng.' },
    { sec: 'Vượt khó', name: 'Câu 10', pts: 1,
      text: 'Bạn nhà khó khăn nhưng vẫn học giỏi. Em nên?',
      opts: o4('Khâm phục và học tập tinh thần của bạn', 'Coi thường bạn', 'Xa lánh bạn', 'Ghen tị với bạn'), ans: 'A',
      why: 'Tinh thần vượt khó vươn lên của bạn rất đáng khâm phục và học tập.' },
  ],
},

/* ═══════════ ĐỀ 10 — ÔN TẬP TỔNG HỢP (2) ═══════════ */
{
  id: 9230, title: 'Đề 10 · Ôn tập tổng hợp (2)', time: 20,
  questions: [
    { sec: 'Yêu Tổ quốc', name: 'Câu 1', pts: 1,
      text: 'Khi chào cờ đầu tuần, em cần?',
      opts: o4('Đứng nghiêm trang, hát Quốc ca to, rõ', 'Đùa nghịch với bạn', 'Nói chuyện riêng', 'Đứng ngả nghiêng'), ans: 'A',
      why: 'Chào cờ nghiêm trang, hát Quốc ca rõ ràng thể hiện lòng tôn kính Tổ quốc.' },
    { sec: 'Trách nhiệm', name: 'Câu 2', pts: 1,
      text: 'Được giao chăm sóc góc cây của lớp, em nên?',
      opts: o4('Bỏ mặc cho cây héo', 'Đợi nhắc mới làm', 'Nhờ hết bạn khác', 'Tưới nước, chăm sóc đều đặn'), ans: 'D',
      why: 'Hoàn thành tốt nhiệm vụ được giao là biểu hiện của tinh thần trách nhiệm.' },
    { sec: 'An toàn bản thân', name: 'Câu 3', pts: 1,
      text: 'Người lạ trên mạng xin ảnh riêng tư và địa chỉ nhà em. Em nên?',
      opts: o4('Gửi ngay', 'Cho địa chỉ để họ đến chơi', 'Không gửi và kể cho bố mẹ biết', 'Kết bạn thân'), ans: 'C',
      why: 'Tuyệt đối không chia sẻ ảnh, thông tin riêng tư cho người lạ và cần báo bố mẹ.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 4', pts: 1,
      text: 'Trước khi mua món đồ, em nên tự hỏi?',
      opts: o4('"Bạn có thì mình phải có"', '"Mình có thật sự cần không?"', '"Càng đắt càng tốt"', '"Cứ mua đã rồi tính"'), ans: 'B',
      why: 'Cân nhắc mình có thật sự cần hay không giúp tránh mua sắm lãng phí.' },
    { sec: 'Đa dạng dân tộc', name: 'Câu 5', pts: 1,
      text: 'Nước ta có bao nhiêu dân tộc anh em?',
      opts: o4('54 dân tộc', '5 dân tộc', '20 dân tộc', '1 dân tộc'), ans: 'A',
      why: 'Việt Nam có 54 dân tộc anh em cùng chung sống, đoàn kết.' },
    { sec: 'Kế hoạch cá nhân', name: 'Câu 6', pts: 1,
      text: 'Sau khi lập kế hoạch tuần, muốn có kết quả em cần?',
      opts: o4('Để đấy không làm', 'Thay đổi liên tục', 'Làm ngược lại', 'Thực hiện nghiêm túc và kiên trì'), ans: 'D',
      why: 'Kế hoạch chỉ có ích khi được thực hiện nghiêm túc và kiên trì.' },
    { sec: 'Vượt khó', name: 'Câu 7', pts: 1,
      text: 'Câu "Có công mài sắt, có ngày nên kim" khuyên ta điều gì?',
      opts: o4('Nên bỏ giữa chừng', 'Chỉ cần may mắn', 'Kiên trì, bền bỉ sẽ thành công', 'Không cần cố gắng'), ans: 'C',
      why: 'Kiên trì, bền bỉ thì việc khó mấy cũng làm được.' },
    { sec: 'Bảo vệ cái đúng', name: 'Câu 8', pts: 1,
      text: 'Thấy bạn lớn bắt nạt em nhỏ, em nên?',
      opts: o4('Cổ vũ bạn lớn', 'Can ngăn nếu an toàn và báo thầy cô, người lớn', 'Quay clip cho vui', 'Bỏ đi coi như không thấy'), ans: 'B',
      why: 'Can ngăn khi an toàn và báo người lớn là cách bảo vệ bạn yếu và bảo vệ điều đúng.' },
    { sec: 'Trách nhiệm', name: 'Câu 9', pts: 1,
      text: 'Em lỡ làm vỡ đồ trong nhà. Việc làm đúng là?',
      opts: o4('Nhận lỗi, xin lỗi và dọn dẹp', 'Giấu đi và đổ lỗi cho em bé', 'Vờ như không biết', 'Đổ cho con mèo'), ans: 'A',
      why: 'Dám nhận lỗi, xin lỗi và khắc phục là biểu hiện của người có trách nhiệm.' },
    { sec: 'Dùng tiền hợp lí', name: 'Câu 10', pts: 1,
      text: 'Được lì xì ngày Tết, cách xử lí hợp lí là?',
      opts: o4('Tiêu sạch trong vài ngày', 'Đem đi cá cược', 'Khoe khoang với bạn', 'Để dành hoặc nhờ bố mẹ giữ giúp cho việc cần thiết'), ans: 'D',
      why: 'Để dành, nhờ bố mẹ giữ giúp và dùng cho việc cần thiết là cách dùng tiền hợp lí.' },
  ],
},

];

SUBJECTS.push({ id:'daoduc5', name:'Đạo đức', short:'Đạo đức 5', icon:'❤️', grade:5, exams:DAODUC5_EXAMS, ready:true, heroTitle:'Đạo đức lớp 5 — yêu Tổ quốc, tôn trọng sự đa dạng dân tộc, vượt khó và bảo vệ cái đúng', heroMeta:'📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018' });
