// TOÁN HỌC TƯ DUY LOGIC — LỚP 2 (chuẩn ASMO / AMO, mức "vừa vừa")
// 6 chuyên đề × 15 câu = 90 câu. Mỗi đề: Phần A 10 câu × 0,6đ = 6đ · Phần B 5 câu × 0,8đ = 4đ.
// Thang 10 — 40 phút mỗi đề — 5 lựa chọn A–E theo đúng thể lệ ASMO/AMO.
//
// SÁU CHUYÊN ĐỀ (theo khung ôn luyện ASMO / AMO bậc tiểu học):
//   1. Logic & Khả năng suy luận      — Logic & Reasoning
//   2. Số học thực chiến               — Arithmetic & Number Theory
//   3. Hình học không gian             — Geometry & Spatial Ability
//   4. Mô hình toán học                — Word Problems & Modeling
//   5. Tổ hợp và Xác suất              — Combinatorics & Counting
//   6. Tiếng Anh chuyên ngành          — Mathematical English vocabulary
//
// ĐỘ KHÓ: cố ý giữ ở mức VỪA PHẢI — dùng để làm quen dạng bài ASMO/AMO, KHÔNG phải đề thi thật
// vòng chung kết. Mọi số liệu nằm trong phạm vi chương trình lớp 2: số đến 1000, bảng nhân chia
// từ 2 đến 9, chu vi hình đơn giản, khối hộp – khối lập phương – khối cầu, đo lường, thời gian.
// Riêng phép × 2 và : 2 được phép vượt ra ngoài phạm vi bảng (ví dụ 2 × 150; 480 : 2).
// Đề thật các năm 2014 · 2015 · 2017 · 2018 nằm ở môn "ASMO" riêng.
//
// Toàn bộ câu hỏi biên soạn lại, có lời giải chi tiết bằng tiếng Việt.

const AMO5 = (a, b, c, d, e) => [{ k: 'A', t: a }, { k: 'B', t: b }, { k: 'C', t: c }, { k: 'D', t: d }, { k: 'E', t: e }];

const AMO2_EXAMS = [

/* ═══════════ CHUYÊN ĐỀ 1 — LOGIC & KHẢ NĂNG SUY LUẬN ═══════════ */
{
  id: 901, title: 'CĐ 1 · Logic & Khả năng suy luận', time: 40,
  questions: [
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 1', pts: 0.6,
      text: 'Ba bạn An, Bình, Cường mỗi bạn nuôi một con vật: mèo, chó hoặc thỏ. Biết An <b>không</b> nuôi mèo và <b>không</b> nuôi chó; Bình <b>không</b> nuôi mèo. Hỏi Cường nuôi con gì?',
      opts: AMO5('Con chó', 'Con thỏ', 'Con mèo', 'Con mèo hoặc con thỏ', 'Không xác định được'), ans: 'C',
      why: 'An không nuôi mèo, không nuôi chó nên An nuôi thỏ. Bình không nuôi mèo, cũng không thể nuôi thỏ (An nuôi rồi) nên Bình nuôi chó. Vậy Cường nuôi mèo.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 2', pts: 0.6,
      text: 'Trong hộp có 4 viên bi đỏ và 3 viên bi xanh. Không nhìn vào hộp, phải lấy ra <b>ít nhất</b> bao nhiêu viên để chắc chắn có 2 viên <b>cùng màu</b>?',
      opts: AMO5('3 viên', '2 viên', '4 viên', '5 viên', '7 viên'), ans: 'A',
      why: 'Lấy 2 viên vẫn có thể được 1 đỏ 1 xanh. Nhưng lấy 3 viên mà chỉ có 2 màu thì chắc chắn phải có 2 viên trùng màu. Vậy ít nhất 3 viên.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 3', pts: 0.6,
      text: 'Bạn Nam đứng thứ 5 tính từ bên trái và thứ 4 tính từ bên phải trong một hàng. Hỏi hàng đó có bao nhiêu bạn?',
      opts: AMO5('7 bạn', '9 bạn', '10 bạn', '11 bạn', '8 bạn'), ans: 'E',
      why: 'Nếu cộng 5 + 4 = 9 thì bạn Nam bị đếm hai lần. Số bạn trong hàng: 5 + 4 − 1 = 8 (bạn).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 4', pts: 0.6,
      text: 'Bác thợ cưa một thanh gỗ thành 8 khúc, mỗi lần cưa hết 7 phút. Hỏi bác cưa xong hết bao nhiêu phút?',
      opts: AMO5('56 phút', '49 phút', '42 phút', '63 phút', '35 phút'), ans: 'B',
      why: 'Muốn được 8 khúc chỉ cần cưa 8 − 1 = 7 (lần). Thời gian: 7 × 7 = 49 (phút).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 5', pts: 0.6,
      text: 'Hôm nay là thứ Hai. Hỏi <b>10 ngày</b> nữa là thứ mấy?',
      opts: AMO5('Thứ Ba', 'Thứ Tư', 'Thứ Sáu', 'Thứ Năm', 'Thứ Bảy'), ans: 'D',
      why: 'Cứ 7 ngày lại lặp lại thứ cũ. Ta có 10 : 7 = 1 (dư 3), nghĩa là sau 7 ngày vẫn là thứ Hai, thêm 3 ngày nữa là thứ Năm.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 6', pts: 0.6,
      text: 'Có 5 bạn gặp nhau, mỗi bạn bắt tay với tất cả các bạn còn lại đúng một lần. Hỏi có bao nhiêu cái bắt tay?',
      opts: AMO5('10 cái', '5 cái', '8 cái', '20 cái', '25 cái'), ans: 'A',
      why: 'Bạn thứ nhất bắt tay 4 bạn, bạn thứ hai bắt thêm 3 cái mới, rồi 2 và 1. Tổng: 4 + 3 + 2 + 1 = 10 (cái bắt tay).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 7', pts: 0.6,
      text: 'Mai nói: “Số của tớ <b>lớn hơn 5</b>, <b>bé hơn 8</b> và là <b>số chẵn</b>.” Số của Mai là:',
      opts: AMO5('5', '7', '8', '6', 'Không có số nào'), ans: 'D',
      why: 'Số lớn hơn 5 và bé hơn 8 chỉ có thể là 6 hoặc 7. Trong hai số đó chỉ có 6 là số chẵn.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 8', pts: 0.6,
      text: 'An hơn Bình 2 tuổi, Bình hơn Cường 3 tuổi. Hỏi An hơn Cường bao nhiêu tuổi?',
      opts: AMO5('1 tuổi', '2 tuổi', '5 tuổi', '3 tuổi', '6 tuổi'), ans: 'C',
      why: 'An hơn Bình 2 tuổi, Bình lại hơn Cường 3 tuổi nên An hơn Cường: 2 + 3 = 5 (tuổi).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 9', pts: 0.6,
      text: 'Từ tầng 1 lên tầng 7 của một toà nhà có 108 bậc thang, mỗi tầng có số bậc như nhau. Hỏi từ tầng 1 lên tầng 2 có bao nhiêu bậc?',
      opts: AMO5('15 bậc', '18 bậc', '21 bậc', '12 bậc', '16 bậc'), ans: 'B',
      why: 'Từ tầng 1 lên tầng 7 phải đi qua 6 tầng cầu thang (1→2, 2→3, …, 6→7). Mỗi tầng có: 108 : 6 = 18 (bậc).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 10', pts: 0.6,
      text: 'Trên bàn có 3 quyển sách chồng lên nhau: sách Toán ở trên sách Tiếng Việt, sách Tiếng Việt ở trên sách Mĩ thuật. Hỏi quyển nào ở <b>dưới cùng</b>?',
      opts: AMO5('Sách Toán', 'Sách Tiếng Việt', 'Sách Toán hoặc Mĩ thuật', 'Không xác định được', 'Sách Mĩ thuật'), ans: 'E',
      why: 'Thứ tự từ trên xuống là Toán — Tiếng Việt — Mĩ thuật. Vậy sách Mĩ thuật ở dưới cùng.' },

    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 11', pts: 0.8,
      text: 'Trong sân có 8 con vừa gà vừa thỏ, đếm được tất cả 22 cái chân. Hỏi có bao nhiêu con thỏ?',
      opts: AMO5('2 con', '3 con', '4 con', '5 con', '6 con'), ans: 'B',
      why: 'Giả sử cả 8 con đều là gà thì có 2 × 8 = 16 (chân), thiếu 22 − 16 = 6 (chân). Đổi 1 con gà thành 1 con thỏ thì thêm 2 chân, nên số thỏ là 6 : 2 = 3 (con). Kiểm tra: 5 gà (10 chân) + 3 thỏ (12 chân) = 22 chân.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 12', pts: 0.8,
      text: 'Bốn bạn thi chạy: An về trước Bình; Cường về sau Bình nhưng trước Dũng. Hỏi ai về <b>cuối cùng</b>?',
      opts: AMO5('An', 'Bình', 'Cường', 'Dũng', 'Không xác định được'), ans: 'D',
      why: 'Sắp thứ tự: An — Bình — Cường — Dũng. Vậy Dũng về cuối cùng.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 13', pts: 0.8,
      text: 'Trong túi có 5 cái kẹo dâu và 4 cái kẹo cam. Không nhìn vào túi, phải lấy ra <b>ít nhất</b> bao nhiêu cái để chắc chắn có 1 cái kẹo <b>cam</b>?',
      opts: AMO5('6 cái', '2 cái', '4 cái', '5 cái', '9 cái'), ans: 'A',
      why: 'Trường hợp xấu nhất là lấy phải cả 5 cái kẹo dâu trước. Khi đó cái thứ 6 chắc chắn là kẹo cam. Vậy ít nhất 6 cái.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 14', pts: 0.8,
      text: 'Nếu <b>hôm qua</b> là thứ Tư thì <b>ngày mai</b> là thứ mấy?',
      opts: AMO5('Thứ Năm', 'Thứ Bảy', 'Thứ Sáu', 'Thứ Ba', 'Chủ nhật'), ans: 'C',
      why: 'Hôm qua là thứ Tư nên hôm nay là thứ Năm, ngày mai là thứ Sáu.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 15', pts: 0.8,
      text: 'Ba bạn Lan, Huệ, Cúc mỗi bạn đeo một chiếc nơ màu hồng, tím hoặc vàng. Biết Lan <b>không</b> đeo nơ hồng và Huệ đeo nơ vàng. Hỏi Lan đeo nơ màu gì?',
      opts: AMO5('Màu hồng', 'Màu vàng', 'Màu hồng hoặc tím', 'Không xác định được', 'Màu tím'), ans: 'E',
      why: 'Huệ đeo nơ vàng nên Lan chỉ còn nơ hồng hoặc tím. Mà Lan không đeo nơ hồng nên Lan đeo nơ tím (Cúc đeo nơ hồng).' },
  ],
},

/* ═══════════ CHUYÊN ĐỀ 2 — SỐ HỌC THỰC CHIẾN ═══════════ */
{
  id: 902, title: 'CĐ 2 · Số học thực chiến (Arithmetic & Number Theory)', time: 40,
  questions: [
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 1', pts: 0.6,
      text: 'Tính nhanh: <b>25 + 37 + 75</b>',
      opts: AMO5('127', '147', '132', '137', '157'), ans: 'D',
      why: 'Ghép 25 + 75 = 100 cho tròn trăm trước, rồi 100 + 37 = 137.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 2', pts: 0.6,
      text: 'Số <b>lớn nhất có ba chữ số khác nhau</b> là:',
      opts: AMO5('999', '987', '998', '978', '900'), ans: 'B',
      why: 'Muốn lớn nhất thì hàng trăm lấy 9, hàng chục lấy 8, hàng đơn vị lấy 7 (ba chữ số phải khác nhau). Số đó là 987.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 3', pts: 0.6,
      text: 'Tính nhanh: <b>7 × 5 × 2</b>',
      opts: AMO5('35', '60', '14', '140', '70'), ans: 'E',
      why: 'Nhóm 5 × 2 = 10 trước cho tròn chục, rồi 7 × 10 = 70.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 4', pts: 0.6,
      text: 'Số liền sau của số 199 là:',
      opts: AMO5('200', '198', '201', '299', '190'), ans: 'A',
      why: 'Số liền sau hơn số đã cho 1 đơn vị: 199 + 1 = 200.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 5', pts: 0.6,
      text: 'Tính tổng: <b>1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10</b>',
      opts: AMO5('45', '50', '55', '60', '65'), ans: 'C',
      why: 'Ghép cặp từ hai đầu: (1 + 10); (2 + 9); (3 + 8); (4 + 7); (5 + 6) — được 5 cặp, mỗi cặp bằng 11. Tổng: 11 × 5 = 55.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 6', pts: 0.6,
      text: 'Số dư của phép chia <b>52 : 7</b> là:',
      opts: AMO5('1', '2', '3', '4', '0'), ans: 'C',
      why: '52 : 7 được 7 vì 7 × 7 = 49. Số dư là 52 − 49 = 3 (số dư luôn bé hơn số chia).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 7', pts: 0.6,
      text: 'Từ 1 đến 20 có bao nhiêu <b>số chẵn</b>?',
      opts: AMO5('10 số', '9 số', '11 số', '20 số', '12 số'), ans: 'A',
      why: 'Các số chẵn là 2; 4; 6; …; 20. Số lượng: 20 : 2 = 10 (số).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 8', pts: 0.6,
      text: 'Tìm <b>x</b>, biết: <b>x + 25 = 60</b>',
      opts: AMO5('x = 85', 'x = 45', 'x = 25', 'x = 30', 'x = 35'), ans: 'E',
      why: 'x = 60 − 25 = 35. Thử lại: 35 + 25 = 60.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 9', pts: 0.6,
      text: 'Trong các số <b>34; 41; 54; 65; 70</b>, số nào chia hết cho 9?',
      opts: AMO5('34', '54', '41', '65', '70'), ans: 'B',
      why: 'Lần lượt thử với bảng chia 9: chỉ có 54 : 9 = 6 là phép chia hết. Các số còn lại chia 9 đều còn dư.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 10', pts: 0.6,
      text: 'Số <b>bé nhất có ba chữ số</b> là:',
      opts: AMO5('111', '101', '110', '100', '999'), ans: 'D',
      why: 'Chữ số hàng trăm nhỏ nhất khác 0 là 1, hai hàng còn lại đều là 0. Số đó là 100.' },

    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 11', pts: 0.8,
      text: 'Hai số có tổng bằng 30 và hiệu bằng 6. Số lớn là:',
      opts: AMO5('18', '12', '15', '20', '24'), ans: 'A',
      why: 'Số lớn = (tổng + hiệu) : 2 = (30 + 6) : 2 = 36 : 2 = 18. Số bé là 12; thử lại 18 + 12 = 30 và 18 − 12 = 6.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 12', pts: 0.8,
      text: 'Một số cộng thêm 12 rồi trừ đi 5 thì được 27. Tìm số đó.',
      opts: AMO5('10', '22', '34', '20', '44'), ans: 'D',
      why: 'Tính ngược từ cuối: 27 + 5 = 32; 32 − 12 = 20. Thử lại: 20 + 12 = 32; 32 − 5 = 27.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 13', pts: 0.8,
      text: 'Khi viết các số từ <b>1 đến 30</b>, chữ số <b>1</b> được viết bao nhiêu lần?',
      opts: AMO5('11 lần', '12 lần', '13 lần', '14 lần', '10 lần'), ans: 'C',
      why: 'Chữ số 1 ở hàng đơn vị: 1; 11; 21 — 3 lần. Chữ số 1 ở hàng chục: 10; 11; 12; …; 19 — 10 lần. Tất cả: 3 + 10 = 13 lần.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 14', pts: 0.8,
      text: 'Cho dãy số <b>3; 6; 9; 12; …</b> Số hạng thứ <b>9</b> của dãy là:',
      opts: AMO5('24', '27', '30', '33', '36'), ans: 'B',
      why: 'Dãy gồm các số 3 × 1; 3 × 2; 3 × 3; … nên số hạng thứ 9 là 3 × 9 = 27.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 15', pts: 0.8,
      text: 'Có 63 quả cam xếp đều vào các đĩa, mỗi đĩa 7 quả. Hỏi xếp được bao nhiêu đĩa?',
      opts: AMO5('7 đĩa', '8 đĩa', '10 đĩa', '11 đĩa', '9 đĩa'), ans: 'E',
      why: 'Số đĩa: 63 : 7 = 9 (đĩa).' },
  ],
},

/* ═══════════ CHUYÊN ĐỀ 3 — HÌNH HỌC KHÔNG GIAN ═══════════ */
{
  id: 903, title: 'CĐ 3 · Hình học không gian (Geometry & Spatial Ability)', time: 40,
  questions: [
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 1', pts: 0.6,
      text: 'Khối lập phương có bao nhiêu <b>mặt</b>?',
      opts: AMO5('4 mặt', '6 mặt', '5 mặt', '8 mặt', '12 mặt'), ans: 'B',
      why: 'Khối lập phương có 6 mặt, mỗi mặt đều là một hình vuông bằng nhau (giống hình con xúc xắc).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 2', pts: 0.6,
      text: 'Khối hộp chữ nhật có bao nhiêu <b>đỉnh</b>?',
      opts: AMO5('4 đỉnh', '6 đỉnh', '10 đỉnh', '8 đỉnh', '12 đỉnh'), ans: 'D',
      why: 'Khối hộp chữ nhật có 8 đỉnh: 4 đỉnh ở mặt trên và 4 đỉnh ở mặt dưới.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 3', pts: 0.6,
      text: 'Hình vuông có mấy cạnh bằng nhau?',
      opts: AMO5('4 cạnh', '2 cạnh', '3 cạnh', '5 cạnh', '6 cạnh'), ans: 'A',
      why: 'Hình vuông có 4 cạnh và cả 4 cạnh đều dài bằng nhau.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 4', pts: 0.6,
      text: 'Chu vi hình tam giác có ba cạnh dài 9 cm, 8 cm và 7 cm là:',
      opts: AMO5('22 cm', '23 cm', '24 cm', '25 cm', '504 cm'), ans: 'C',
      why: 'Chu vi hình tam giác là tổng độ dài ba cạnh: 9 + 8 + 7 = 24 (cm).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 5', pts: 0.6,
      text: 'Chu vi hình tứ giác có bốn cạnh đều dài 6 cm là:',
      opts: AMO5('10 cm', '12 cm', '18 cm', '36 cm', '24 cm'), ans: 'E',
      why: 'Chu vi = 6 + 6 + 6 + 6 = 6 × 4 = 24 (cm).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 6', pts: 0.6,
      text: 'Khối lập phương có bao nhiêu <b>cạnh</b>?',
      opts: AMO5('6 cạnh', '8 cạnh', '10 cạnh', '12 cạnh', '16 cạnh'), ans: 'D',
      why: 'Khối lập phương có 12 cạnh: 4 cạnh ở mặt trên, 4 cạnh ở mặt dưới và 4 cạnh đứng nối hai mặt.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 7', pts: 0.6,
      text: 'Chu vi hình vuông có cạnh 7 cm là:',
      opts: AMO5('14 cm', '28 cm', '21 cm', '49 cm', '35 cm'), ans: 'B',
      why: 'Chu vi hình vuông = cạnh × 4 = 7 × 4 = 28 (cm).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 8', pts: 0.6,
      text: 'Xếp 8 khối lập phương nhỏ bằng nhau thành một khối lập phương lớn. Hỏi mỗi cạnh của khối lớn gồm mấy khối nhỏ?',
      opts: AMO5('3 khối', '4 khối', '6 khối', '8 khối', '2 khối'), ans: 'E',
      why: 'Khối lớn gồm 2 tầng, mỗi tầng 2 × 2 = 4 khối, tất cả 8 khối. Vậy mỗi cạnh gồm 2 khối nhỏ.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 9', pts: 0.6,
      text: 'Hình khối nào <b>lăn được</b> theo mọi hướng?',
      opts: AMO5('Khối cầu', 'Khối lập phương', 'Khối hộp chữ nhật', 'Hình vuông', 'Hình tam giác'), ans: 'A',
      why: 'Khối cầu (như quả bóng) có bề mặt cong đều nên lăn được theo mọi hướng. Khối lập phương và khối hộp chữ nhật có mặt phẳng nên chỉ trượt hoặc lật.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 10', pts: 0.6,
      text: 'Gấp đôi một tờ giấy hình vuông theo <b>đường chéo</b> thì được hình gì?',
      opts: AMO5('Hình vuông nhỏ hơn', 'Hình chữ nhật', 'Hình tam giác', 'Hình tròn', 'Hình tứ giác'), ans: 'C',
      why: 'Đường chéo chia hình vuông thành hai hình tam giác bằng nhau, nên gấp đôi theo đường chéo ta được một hình tam giác.' },

    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 11', pts: 0.8,
      text: 'Một khối lập phương lớn được ghép từ <b>27 khối lập phương nhỏ</b> (3 × 3 × 3) rồi sơn đỏ toàn bộ mặt ngoài. Hỏi có bao nhiêu khối nhỏ <b>không được sơn mặt nào</b>?',
      opts: AMO5('0 khối', '3 khối', '1 khối', '6 khối', '8 khối'), ans: 'C',
      why: 'Chỉ có khối nằm chính giữa khối lớn là hoàn toàn bị bao kín, không lộ ra mặt ngoài nào. Vậy có đúng 1 khối không được sơn.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 12', pts: 0.8,
      text: 'Vẫn khối lập phương 3 × 3 × 3 được sơn đỏ mặt ngoài ở trên. Hỏi có bao nhiêu khối nhỏ được sơn <b>đúng 3 mặt</b>?',
      opts: AMO5('8 khối', '4 khối', '6 khối', '12 khối', '9 khối'), ans: 'A',
      why: 'Khối được sơn 3 mặt là các khối nằm ở góc của khối lớn. Một khối lập phương có 8 góc nên có 8 khối như thế.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 13', pts: 0.8,
      text: 'Ghép hai hình vuông có cạnh 3 cm thành một hình chữ nhật. Chu vi hình chữ nhật đó là:',
      opts: AMO5('12 cm', '15 cm', '24 cm', '9 cm', '18 cm'), ans: 'E',
      why: 'Hình chữ nhật ghép được có chiều dài 3 + 3 = 6 (cm) và chiều rộng 3 cm. Chu vi: 6 + 3 + 6 + 3 = 18 (cm).' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 14', pts: 0.8,
      text: 'Vẽ một đoạn thẳng từ đỉnh của một hình tam giác xuống cạnh đối diện. Hỏi trên hình có tất cả bao nhiêu hình tam giác?',
      opts: AMO5('1 hình', '3 hình', '2 hình', '4 hình', '6 hình'), ans: 'B',
      why: 'Có 2 hình tam giác nhỏ do đoạn thẳng chia ra, cộng thêm hình tam giác lớn ban đầu. Tất cả: 2 + 1 = 3 (hình).' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 15', pts: 0.8,
      text: 'Một khối hộp được xếp từ các khối lập phương nhỏ bằng nhau: gồm 2 tầng, mỗi tầng xếp 3 hàng, mỗi hàng 2 khối. Hỏi có tất cả bao nhiêu khối nhỏ?',
      opts: AMO5('6 khối', '8 khối', '10 khối', '12 khối', '18 khối'), ans: 'D',
      why: 'Mỗi tầng có: 3 × 2 = 6 (khối). Hai tầng có: 6 × 2 = 12 (khối nhỏ).' },
  ],
},

/* ═══════════ CHUYÊN ĐỀ 4 — MÔ HÌNH TOÁN HỌC ═══════════ */
{
  id: 904, title: 'CĐ 4 · Mô hình toán học (Word Problems & Modeling)', time: 40,
  questions: [
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 1', pts: 0.6,
      text: 'Lan có 24 cái kẹo, Lan cho bạn 9 cái. Hỏi Lan còn lại bao nhiêu cái kẹo?',
      opts: AMO5('15 cái', '13 cái', '14 cái', '16 cái', '33 cái'), ans: 'A',
      why: 'Số kẹo còn lại: 24 − 9 = 15 (cái).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 2', pts: 0.6,
      text: 'Mỗi hộp có 5 chiếc bút. Hỏi 6 hộp như thế có bao nhiêu chiếc bút?',
      opts: AMO5('11 chiếc', '25 chiếc', '35 chiếc', '30 chiếc', '56 chiếc'), ans: 'D',
      why: 'Số bút: 5 × 6 = 30 (chiếc).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 3', pts: 0.6,
      text: '54 học sinh xếp đều thành 6 hàng. Hỏi mỗi hàng có bao nhiêu học sinh?',
      opts: AMO5('6 bạn', '8 bạn', '9 bạn', '12 bạn', '10 bạn'), ans: 'C',
      why: 'Mỗi hàng có: 54 : 6 = 9 (học sinh).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 4', pts: 0.6,
      text: 'Cửa hàng có 150 kg gạo, đã bán 68 kg. Hỏi cửa hàng còn lại bao nhiêu ki-lô-gam gạo?',
      opts: AMO5('72 kg', '82 kg', '92 kg', '88 kg', '218 kg'), ans: 'B',
      why: 'Số gạo còn lại: 150 − 68 = 82 (kg).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 5', pts: 0.6,
      text: 'Mẹ mua 7 kg thịt, mỗi ki-lô-gam giá 90000 đồng. Hỏi mẹ phải trả bao nhiêu tiền?',
      opts: AMO5('97000 đồng', '540000 đồng', '720000 đồng', '700000 đồng', '630000 đồng'), ans: 'E',
      why: 'Số tiền phải trả: 90000 × 7 = 630000 (đồng).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 6', pts: 0.6,
      text: 'Một bao gạo nặng 486 kg, người ta lấy ra <sup>1</sup>⁄<sub>2</sub> số gạo đó. Hỏi trong bao còn lại bao nhiêu ki-lô-gam?',
      opts: AMO5('234 kg', '243 kg', '223 kg', '253 kg', '484 kg'), ans: 'B',
      why: 'Một nửa của 486 kg là: 486 : 2 = 243 (kg). Lấy ra một nửa thì phần còn lại cũng đúng một nửa, tức 243 kg gạo.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 7', pts: 0.6,
      text: 'Một tuần lễ có 7 ngày. Hỏi 3 tuần lễ có bao nhiêu ngày?',
      opts: AMO5('10 ngày', '14 ngày', '28 ngày', '21 ngày', '30 ngày'), ans: 'D',
      why: 'Số ngày: 7 × 3 = 21 (ngày).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 8', pts: 0.6,
      text: 'An có 45 viên bi, Bình có ít hơn An 12 viên bi. Hỏi Bình có bao nhiêu viên bi?',
      opts: AMO5('33 viên', '23 viên', '43 viên', '57 viên', '30 viên'), ans: 'A',
      why: 'Số bi của Bình: 45 − 12 = 33 (viên).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 9', pts: 0.6,
      text: 'Lớp 2A có 32 bạn, trong đó có 15 bạn nữ. Hỏi lớp có bao nhiêu bạn nam?',
      opts: AMO5('15 bạn', '16 bạn', '17 bạn', '18 bạn', '47 bạn'), ans: 'C',
      why: 'Số bạn nam: 32 − 15 = 17 (bạn).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 10', pts: 0.6,
      text: 'Một cuốn vở giá 8000 đồng. Hỏi mua 7 cuốn vở như thế hết bao nhiêu tiền?',
      opts: AMO5('15000 đồng', '48000 đồng', '63000 đồng', '72000 đồng', '56000 đồng'), ans: 'E',
      why: 'Số tiền: 8000 × 7 = 56000 (đồng).' },

    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 11', pts: 0.8,
      text: 'Có 5 rổ trứng, mỗi rổ 8 quả. Người ta đã bán 17 quả. Hỏi còn lại bao nhiêu quả trứng?',
      opts: AMO5('20 quả', '25 quả', '28 quả', '23 quả', '40 quả'), ans: 'D',
      why: 'Tổng số trứng: 8 × 5 = 40 (quả). Số trứng còn lại: 40 − 17 = 23 (quả).' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 12', pts: 0.8,
      text: 'Nam có 30000 đồng, Nam mua 2 quyển vở giá 9000 đồng một quyển. Hỏi Nam còn lại bao nhiêu tiền?',
      opts: AMO5('9000 đồng', '12000 đồng', '11000 đồng', '18000 đồng', '21000 đồng'), ans: 'B',
      why: 'Tiền mua vở: 9000 × 2 = 18000 (đồng). Số tiền còn lại: 30000 − 18000 = 12000 (đồng).' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 13', pts: 0.8,
      text: 'Anh hái được 56 quả cam, em hái được bằng <sup>1</sup>⁄<sub>7</sub> số cam của anh. Hỏi cả hai anh em hái được bao nhiêu quả cam?',
      opts: AMO5('8 quả', '63 quả', '49 quả', '112 quả', '64 quả'), ans: 'E',
      why: 'Số cam của em: 56 : 7 = 8 (quả). Cả hai anh em: 56 + 8 = 64 (quả cam).' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 14', pts: 0.8,
      text: 'Một sợi dây dài 72 cm được cắt thành các đoạn dài 8 cm. Hỏi cắt được bao nhiêu đoạn?',
      opts: AMO5('9 đoạn', '6 đoạn', '7 đoạn', '10 đoạn', '12 đoạn'), ans: 'A',
      why: 'Số đoạn: 72 : 8 = 9 (đoạn).' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 15', pts: 0.8,
      text: 'Có 126 quyển vở chia đều cho 7 lớp, mỗi lớp lại chia đều cho 6 tổ. Hỏi mỗi tổ nhận được bao nhiêu quyển vở?',
      opts: AMO5('4 quyển', '18 quyển', '3 quyển', '21 quyển', '6 quyển'), ans: 'C',
      why: 'Mỗi lớp nhận: 126 : 7 = 18 (quyển). Mỗi tổ nhận: 18 : 6 = 3 (quyển vở).' },
  ],
},

/* ═══════════ CHUYÊN ĐỀ 5 — TỔ HỢP VÀ XÁC SUẤT ═══════════ */
{
  id: 905, title: 'CĐ 5 · Tổ hợp và Xác suất (Combinatorics & Counting)', time: 40,
  questions: [
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 1', pts: 0.6,
      text: 'Bạn Mai có 4 chiếc áo và 7 chiếc quần khác nhau. Hỏi Mai có bao nhiêu cách chọn một bộ gồm 1 áo và 1 quần?',
      opts: AMO5('11 cách', '21 cách', '28 cách', '32 cách', '14 cách'), ans: 'C',
      why: 'Mỗi chiếc áo ghép được với 7 chiếc quần. Số cách: 4 × 7 = 28 (cách).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 2', pts: 0.6,
      text: 'Từ ba chữ số <b>1; 2; 3</b> viết được bao nhiêu số có hai chữ số <b>khác nhau</b>?',
      opts: AMO5('6 số', '3 số', '4 số', '9 số', '12 số'), ans: 'A',
      why: 'Hàng chục có 3 cách chọn, hàng đơn vị còn 2 cách. Số các số: 3 × 2 = 6 (đó là 12; 13; 21; 23; 31; 32).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 3', pts: 0.6,
      text: 'Tung một đồng xu một lần thì có bao nhiêu kết quả có thể xảy ra?',
      opts: AMO5('1 kết quả', '3 kết quả', '4 kết quả', '6 kết quả', '2 kết quả'), ans: 'E',
      why: 'Đồng xu có hai mặt nên có 2 kết quả: mặt sấp hoặc mặt ngửa.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 4', pts: 0.6,
      text: 'Trong hộp chỉ có 3 viên bi đỏ. Lấy ra một viên bi bất kì. Khẳng định nào <b>đúng</b>?',
      opts: AMO5('Có thể lấy được bi xanh.', 'Chắc chắn lấy được bi đỏ.', 'Không thể lấy được bi đỏ.', 'Chắc chắn lấy được bi xanh.', 'Không xác định được.'), ans: 'B',
      why: 'Trong hộp chỉ có bi đỏ nên lấy viên nào cũng là bi đỏ — đó là sự việc chắc chắn xảy ra.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 5', pts: 0.6,
      text: 'Xếp 2 bạn A và B thành một hàng dọc. Có bao nhiêu cách xếp?',
      opts: AMO5('1 cách', '3 cách', '4 cách', '2 cách', '6 cách'), ans: 'D',
      why: 'Có 2 cách: A đứng trước B, hoặc B đứng trước A.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 6', pts: 0.6,
      text: 'Có 4 bạn, mỗi bạn bắt tay với tất cả các bạn còn lại đúng một lần. Hỏi có bao nhiêu cái bắt tay?',
      opts: AMO5('6 cái', '4 cái', '8 cái', '10 cái', '12 cái'), ans: 'A',
      why: 'Tổng số cái bắt tay: 3 + 2 + 1 = 6 (cái).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 7', pts: 0.6,
      text: 'Từ A đến B có 3 con đường, từ B đến C có 6 con đường. Hỏi có bao nhiêu cách đi từ A đến C (đi qua B)?',
      opts: AMO5('9 cách', '12 cách', '24 cách', '18 cách', '36 cách'), ans: 'D',
      why: 'Mỗi con đường từ A đến B ghép được với 6 con đường từ B đến C. Số cách: 3 × 6 = 18 (cách).' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 8', pts: 0.6,
      text: 'Trong tiệm có 4 loại bánh khác nhau. Hỏi có bao nhiêu cách chọn <b>1 loại</b> bánh?',
      opts: AMO5('1 cách', '2 cách', '4 cách', '3 cách', '8 cách'), ans: 'C',
      why: 'Mỗi loại bánh là một cách chọn, có 4 loại nên có 4 cách.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 9', pts: 0.6,
      text: 'Gieo một con xúc xắc 6 mặt một lần. Sự việc nào <b>không thể</b> xảy ra?',
      opts: AMO5('Được mặt 1 chấm.', 'Được mặt 7 chấm.', 'Được mặt 3 chấm.', 'Được mặt 6 chấm.', 'Được mặt có số chấm chẵn.'), ans: 'B',
      why: 'Con xúc xắc chỉ có các mặt từ 1 đến 6 chấm nên không thể có mặt 7 chấm.' },
    { sec: 'Phần A — Cơ bản (6 điểm)', name: 'Câu 10', pts: 0.6,
      text: 'Xếp 3 bạn A, B, C thành một hàng dọc. Có bao nhiêu cách xếp?',
      opts: AMO5('3 cách', '4 cách', '9 cách', '12 cách', '6 cách'), ans: 'E',
      why: 'Vị trí đầu có 3 cách chọn, vị trí giữa còn 2 cách, vị trí cuối còn 1 cách. Tất cả: 3 × 2 × 1 = 6 (cách).' },

    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 11', pts: 0.8,
      text: 'Từ ba chữ số <b>0; 1; 2</b> viết được bao nhiêu số có hai chữ số <b>khác nhau</b>?',
      opts: AMO5('3 số', '4 số', '6 số', '8 số', '9 số'), ans: 'B',
      why: 'Chữ số hàng chục không được là 0 nên có 2 cách (1 hoặc 2); hàng đơn vị còn 2 cách. Tất cả: 2 × 2 = 4 số, đó là 10; 12; 20; 21.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 12', pts: 0.8,
      text: 'Có 7 màu bút. Tô 2 hình khác nhau, mỗi hình một màu và hai hình phải <b>khác màu</b>. Có bao nhiêu cách tô?',
      opts: AMO5('14 cách', '49 cách', '21 cách', '42 cách', '35 cách'), ans: 'D',
      why: 'Hình thứ nhất có 7 cách chọn màu, hình thứ hai chỉ còn 6 màu khác. Số cách: 7 × 6 = 42 (cách).' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 13', pts: 0.8,
      text: 'Tung một đồng xu <b>hai lần</b> liên tiếp. Có bao nhiêu kết quả có thể xảy ra?',
      opts: AMO5('4 kết quả', '2 kết quả', '3 kết quả', '6 kết quả', '8 kết quả'), ans: 'A',
      why: 'Mỗi lần tung có 2 khả năng nên hai lần tung có 2 × 2 = 4 kết quả: sấp–sấp; sấp–ngửa; ngửa–sấp; ngửa–ngửa.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 14', pts: 0.8,
      text: 'Trong hộp có 3 viên bi đỏ và 2 viên bi xanh. Lấy ra 4 viên bất kì. Hỏi <b>chắc chắn</b> lấy được ít nhất mấy viên bi xanh?',
      opts: AMO5('0 viên', '2 viên', '1 viên', '3 viên', '4 viên'), ans: 'C',
      why: 'Trường hợp xấu nhất là lấy phải cả 3 viên bi đỏ; khi đó viên thứ tư bắt buộc là bi xanh. Vậy chắc chắn có ít nhất 1 viên bi xanh.' },
    { sec: 'Phần B — Nâng cao (4 điểm)', name: 'Câu 15', pts: 0.8,
      text: 'Chọn 2 bạn trong số 4 bạn để đi trực nhật. Có bao nhiêu cách chọn?',
      opts: AMO5('4 cách', '8 cách', '10 cách', '12 cách', '6 cách'), ans: 'E',
      why: 'Số cặp bạn: 3 + 2 + 1 = 6 (cách chọn).' },
  ],
},

/* ═══════════ CHUYÊN ĐỀ 6 — TIẾNG ANH CHUYÊN NGÀNH ═══════════ */
{
  id: 906, title: 'CĐ 6 · Tiếng Anh chuyên ngành (Mathematical English)', time: 40,
  questions: [
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 1', pts: 0.6,
      text: 'Trong tiếng Anh toán học, từ <b>“sum”</b> có nghĩa là:',
      opts: AMO5('Hiệu', 'Tích', 'Thương', 'Tổng', 'Số dư'), ans: 'D',
      why: '“Sum” là <i>tổng</i> — kết quả của phép cộng. Ví dụ: <i>the sum of 3 and 4 is 7</i> (tổng của 3 và 4 là 7).' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 2', pts: 0.6,
      text: 'Từ <b>“difference”</b> có nghĩa là:',
      opts: AMO5('Tổng', 'Hiệu', 'Tích', 'Thương', 'Chu vi'), ans: 'B',
      why: '“Difference” là <i>hiệu</i> — kết quả của phép trừ. Ví dụ: <i>the difference between 9 and 4 is 5</i>.' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 3', pts: 0.6,
      text: 'Từ <b>“product”</b> có nghĩa là:',
      opts: AMO5('Tổng', 'Hiệu', 'Thương', 'Số lẻ', 'Tích'), ans: 'E',
      why: '“Product” là <i>tích</i> — kết quả của phép nhân. Ví dụ: <i>the product of 3 and 5 is 15</i>.' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 4', pts: 0.6,
      text: 'Từ <b>“quotient”</b> có nghĩa là:',
      opts: AMO5('Thương', 'Tổng', 'Hiệu', 'Tích', 'Chu vi'), ans: 'A',
      why: '“Quotient” là <i>thương</i> — kết quả của phép chia. Ví dụ: <i>the quotient of 20 and 4 is 5</i>.' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 5', pts: 0.6,
      text: 'Từ <b>“triangle”</b> có nghĩa là:',
      opts: AMO5('Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình chữ nhật', 'Hình tứ giác'), ans: 'C',
      why: '“Triangle” là <i>hình tam giác</i> (tri- nghĩa là ba, angle là góc — hình có ba góc).' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 6', pts: 0.6,
      text: 'Từ <b>“square”</b> có nghĩa là:',
      opts: AMO5('Hình tròn', 'Hình tam giác', 'Hình vuông', 'Hình chữ nhật', 'Khối cầu'), ans: 'C',
      why: '“Square” là <i>hình vuông</i> — hình có 4 cạnh bằng nhau và 4 góc vuông.' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 7', pts: 0.6,
      text: 'Từ <b>“rectangle”</b> có nghĩa là:',
      opts: AMO5('Hình chữ nhật', 'Hình vuông', 'Hình tam giác', 'Hình tròn', 'Khối lập phương'), ans: 'A',
      why: '“Rectangle” là <i>hình chữ nhật</i> — hình có 4 góc vuông, hai cạnh dài bằng nhau và hai cạnh ngắn bằng nhau.' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 8', pts: 0.6,
      text: 'Cụm từ <b>“odd number”</b> có nghĩa là:',
      opts: AMO5('Số chẵn', 'Số tròn chục', 'Số lớn nhất', 'Số 0', 'Số lẻ'), ans: 'E',
      why: '“Odd number” là <i>số lẻ</i> (1; 3; 5; 7; 9; …). Còn “even number” là số chẵn.' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 9', pts: 0.6,
      text: 'Cụm từ <b>“even number”</b> có nghĩa là:',
      opts: AMO5('Số lẻ', 'Số chẵn', 'Số dư', 'Số tròn trăm', 'Số bé nhất'), ans: 'B',
      why: '“Even number” là <i>số chẵn</i> (0; 2; 4; 6; 8; …) — số chia hết cho 2.' },
    { sec: 'Phần A — Từ vựng (6 điểm)', name: 'Câu 10', pts: 0.6,
      text: 'Từ <b>“perimeter”</b> có nghĩa là:',
      opts: AMO5('Diện tích', 'Chiều dài', 'Chiều rộng', 'Chu vi', 'Cạnh'), ans: 'D',
      why: '“Perimeter” là <i>chu vi</i> — tổng độ dài các cạnh bao quanh một hình.' },

    { sec: 'Phần B — Giải toán bằng tiếng Anh (4 điểm)', name: 'Câu 11', pts: 0.8,
      text: '<b>What is the sum of 25 and 17?</b><br><i>(Tổng của 25 và 17 là bao nhiêu?)</i>',
      opts: AMO5('42', '32', '8', '43', '52'), ans: 'A',
      why: '“Sum” là tổng nên ta làm phép cộng: 25 + 17 = 42.' },
    { sec: 'Phần B — Giải toán bằng tiếng Anh (4 điểm)', name: 'Câu 12', pts: 0.8,
      text: '<b>Find the difference between 50 and 23.</b><br><i>(Tìm hiệu của 50 và 23.)</i>',
      opts: AMO5('73', '33', '37', '27', '23'), ans: 'D',
      why: '“Difference” là hiệu nên ta làm phép trừ: 50 − 23 = 27.' },
    { sec: 'Phần B — Giải toán bằng tiếng Anh (4 điểm)', name: 'Câu 13', pts: 0.8,
      text: '<b>What is the product of 6 and 7?</b><br><i>(Tích của 6 và 7 là bao nhiêu?)</i>',
      opts: AMO5('13', '36', '42', '48', '67'), ans: 'C',
      why: '“Product” là tích nên ta làm phép nhân: 6 × 7 = 42.' },
    { sec: 'Phần B — Giải toán bằng tiếng Anh (4 điểm)', name: 'Câu 14', pts: 0.8,
      text: '<b>A square has a side of 8 cm. What is its perimeter?</b><br><i>(Một hình vuông có cạnh 8 cm. Chu vi của nó là bao nhiêu?)</i>',
      opts: AMO5('16 cm', '32 cm', '24 cm', '64 cm', '40 cm'), ans: 'B',
      why: '“Perimeter” của “square” (hình vuông) bằng cạnh nhân 4: 8 × 4 = 32 (cm).' },
    { sec: 'Phần B — Giải toán bằng tiếng Anh (4 điểm)', name: 'Câu 15', pts: 0.8,
      text: '<b>Which is the smallest odd number greater than 10?</b><br><i>(Số lẻ bé nhất lớn hơn 10 là số nào?)</i>',
      opts: AMO5('10', '12', '13', '15', '11'), ans: 'E',
      why: '“Odd number” là số lẻ. Các số lẻ lớn hơn 10 là 11; 13; 15; … Số bé nhất trong đó là 11.' },
  ],
},

];

// Chèn môn "Tư duy ASMO/AMO" ngay sau môn ASMO (đề thật) của lớp 2
{
  const i = SUBJECTS.findIndex(s => s.id === 'asmo');
  SUBJECTS.splice(i < 0 ? 2 : i + 1, 0, {
    id: 'amo2', name: 'Tư duy ASMO/AMO', short: 'AMO 2', icon: '🧠', grade: 2,
    exams: AMO2_EXAMS, ready: true,
    heroTitle: 'Toán học tư duy logic lớp 2 — chuẩn ASMO / AMO (mức vừa phải)',
    heroMeta: '📚 6 chuyên đề &nbsp;•&nbsp; 90 câu &nbsp;•&nbsp; ⏱ 40 phút mỗi đề &nbsp;•&nbsp; Logic · Số học · Hình không gian · Mô hình · Tổ hợp · Tiếng Anh',
  });
}
