// TOÁN TƯ DUY 12 DẠNG — LỚP 3 · 12 dạng × 20 câu = 240 câu (137 câu có hình, 57%).
// SINH TỰ ĐỘNG bởi tools/gen-tuduy-tt.mjs — sửa nội dung trong script rồi chạy lại:
//     node tools/gen-tuduy-tt.mjs
//
// 12 dạng tư duy: Number Sense · Pattern & Sequence · Missing Number · Logic &
// Deduction · Mental Math · Transformation · Spatial/Visual · Combinatorics ·
// Classification · Data & Graph · Word Problem · Non-routine. Mức độ HSG cấp
// trường / cấp huyện, bám chương trình lớp 3. Hình vẽ bằng code (tools/tt-art.mjs
// + hinh-art.mjs + nc2-art.mjs), đáp án lấy thẳng từ dữ liệu vẽ ra hình.

const TTD3 = [
{
  id: 3301, title: 'Dạng 1 · Cảm nhận số (Number Sense)', time: 25,
  questions: [
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 1', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd3/d1_ns-pv0.svg',
      opts: o4('194', '149', '249', '148'), ans: 'B',
      why: 'Có 1 trăm, 4 chục và 9 đơn vị nên số đó là 149.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 2', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd3/d1_ns-pv1.svg',
      opts: o4('535', '653', '553', '554'), ans: 'C',
      why: 'Có 5 trăm, 5 chục và 3 đơn vị nên số đó là 553.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 3', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd3/d1_ns-pv2.svg',
      opts: o4('293', '239', '339', '238'), ans: 'B',
      why: 'Có 2 trăm, 3 chục và 9 đơn vị nên số đó là 239.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 4', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd3/d1_ns-pv3.svg',
      opts: o4('242', '324', '224', '225'), ans: 'C',
      why: 'Có 2 trăm, 2 chục và 4 đơn vị nên số đó là 224.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 5', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd3/d1_ns-nl0.svg',
      opts: o4('14', '10', '16', '12'), ans: 'D',
      why: 'Các vạch cách đều nhau 2 đơn vị nên vạch có dấu ? là số 12.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 6', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd3/d1_ns-nl1.svg',
      opts: o4('25', '15', '30', '20'), ans: 'D',
      why: 'Các vạch cách đều nhau 5 đơn vị nên vạch có dấu ? là số 20.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 7', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd3/d1_ns-nl2.svg',
      opts: o4('50', '60', '40', '70'), ans: 'A',
      why: 'Các vạch cách đều nhau 10 đơn vị nên vạch có dấu ? là số 50.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 8', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd3/d1_ns-nl3.svg',
      opts: o4('600', '700', '500', '800'), ans: 'A',
      why: 'Các vạch cách đều nhau 100 đơn vị nên vạch có dấu ? là số 600.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 9', pts: 0.5,
      text: 'Trong các số 18917 ; 70524 ; 49889 ; 19217, số <b>lớn nhất</b> là:',
      opts: o4('18917', '49889', '70524', '19217'), ans: 'C',
      why: 'So sánh bốn số, số lớn nhất là 70524.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 10', pts: 0.5,
      text: 'Trong các số 64524 ; 89608 ; 13400 ; 27088, số <b>bé nhất</b> là:',
      opts: o4('64524', '89608', '27088', '13400'), ans: 'D',
      why: 'So sánh bốn số, số bé nhất là 13400.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 11', pts: 0.5,
      text: 'Trong các số 72269 ; 58841 ; 11687 ; 52118, số <b>lớn nhất</b> là:',
      opts: o4('58841', '72269', '11687', '52118'), ans: 'B',
      why: 'So sánh bốn số, số lớn nhất là 72269.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 12', pts: 0.5,
      text: 'Trong các số 65780 ; 12305 ; 25737 ; 17151, số <b>bé nhất</b> là:',
      opts: o4('65780', '25737', '17151', '12305'), ans: 'D',
      why: 'So sánh bốn số, số bé nhất là 12305.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 13', pts: 0.5,
      text: 'Số gồm 3 nghìn, 4 trăm, 2 chục và 5 đơn vị được viết là:',
      opts: o4('3245', '3425', '4425', '3325'), ans: 'B',
      why: '3 nghìn 4 trăm 2 chục 5 đơn vị viết là 3425.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 14', pts: 0.5,
      text: 'Số gồm 6 nghìn, 0 trăm, 3 chục và 1 đơn vị được viết là:',
      opts: o4('6301', '6031', '7031', '5931'), ans: 'B',
      why: '6 nghìn 0 trăm 3 chục 1 đơn vị viết là 6031.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 15', pts: 0.5,
      text: 'Số gồm 3 nghìn, 5 trăm, 6 chục và 8 đơn vị được viết là:',
      opts: o4('3658', '4568', '3468', '3568'), ans: 'D',
      why: '3 nghìn 5 trăm 6 chục 8 đơn vị viết là 3568.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 16', pts: 0.5,
      text: 'Số gồm 6 nghìn, 5 trăm, 8 chục và 6 đơn vị được viết là:',
      opts: o4('6856', '7586', '6586', '6486'), ans: 'C',
      why: '6 nghìn 5 trăm 8 chục 6 đơn vị viết là 6586.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 17', pts: 0.5,
      text: 'Từ ba chữ số 3, 1, 8, hãy lập số có ba chữ số (các chữ số khác nhau) <b>lớn nhất</b>. Số đó là:',
      opts: o4('138', '822', '831', '813'), ans: 'C',
      why: 'Xếp các chữ số từ lớn đến bé: 8 > 3 > 1 → số lớn nhất là 831.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 18', pts: 0.5,
      text: 'Từ ba chữ số 7, 1, 3, hãy lập số có ba chữ số (các chữ số khác nhau) <b>bé nhất</b>. Số đó là:',
      opts: o4('731', '146', '137', '713'), ans: 'C',
      why: 'Chữ số hàng trăm phải khác 0 và nhỏ nhất có thể; số bé nhất là 137.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 19', pts: 0.5,
      text: 'Từ ba chữ số 5, 6, 8, hãy lập số có ba chữ số (các chữ số khác nhau) <b>lớn nhất</b>. Số đó là:',
      opts: o4('568', '856', '865', '866'), ans: 'C',
      why: 'Xếp các chữ số từ lớn đến bé: 8 > 6 > 5 → số lớn nhất là 865.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 20', pts: 0.5,
      text: 'Từ ba chữ số 5, 9, 4, hãy lập số có ba chữ số (các chữ số khác nhau) <b>bé nhất</b>. Số đó là:',
      opts: o4('954', '459', '468', '945'), ans: 'B',
      why: 'Chữ số hàng trăm phải khác 0 và nhỏ nhất có thể; số bé nhất là 459.' },
  ],
},
{
  id: 3302, title: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', time: 25,
  questions: [
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 1', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd3/d2_pt-emo0.svg',
      opts: o4('🔴', '🔵', '🟡', '🟢'), ans: 'A',
      why: 'Dãy lặp lại theo nhóm 🔴 🔵 (chu kì 2). Ô thứ 7 lặp lại 🔴.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 2', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd3/d2_pt-emo1.svg',
      opts: o4('🔴', '🔵', '🟡', '🟢'), ans: 'D',
      why: 'Dãy lặp lại theo nhóm 🟢 ⭐ ❤️ (chu kì 3). Ô thứ 7 lặp lại 🟢.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 3', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd3/d2_pt-emo2.svg',
      opts: o4('🔵', '🟡', '🔴', '🟢'), ans: 'C',
      why: 'Dãy lặp lại theo nhóm 🔺 ⬛ 🔴 🔵 (chu kì 4). Ô thứ 7 lặp lại 🔴.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 4', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd3/d2_pt-emo3.svg',
      opts: o4('🔴', '🔵', '🟡', '🟢'), ans: 'B',
      why: 'Dãy lặp lại theo nhóm 🔵 🟡 (chu kì 2). Ô thứ 7 lặp lại 🔵.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 5', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd3/d2_pt-emo4.svg',
      opts: o4('🔴', '🔵', '🟡', '⭐'), ans: 'D',
      why: 'Dãy lặp lại theo nhóm ⭐ ❤️ 🔺 (chu kì 3). Ô thứ 7 lặp lại ⭐.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 6', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd3/d2_pt-add0.svg',
      opts: o4('17', '19', '15', '18'), ans: 'A',
      why: 'Mỗi số hơn số liền trước 2 đơn vị. Số cần tìm là 15 + 2 = 17.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 7', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd3/d2_pt-add1.svg',
      opts: o4('18', '15', '12', '16'), ans: 'B',
      why: 'Mỗi số hơn số liền trước 3 đơn vị. Số cần tìm là 12 + 3 = 15.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 8', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd3/d2_pt-add2.svg',
      opts: o4('23', '19', '15', '20'), ans: 'B',
      why: 'Mỗi số hơn số liền trước 4 đơn vị. Số cần tìm là 15 + 4 = 19.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 9', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd3/d2_pt-add3.svg',
      opts: o4('31', '26', '21', '27'), ans: 'B',
      why: 'Mỗi số hơn số liền trước 5 đơn vị. Số cần tìm là 21 + 5 = 26.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 10', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd3/d2_pt-add4.svg',
      opts: o4('137', '87', '113', '112'), ans: 'D',
      why: 'Mỗi số hơn số liền trước 25 đơn vị. Số cần tìm là 87 + 25 = 112.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 11', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd3/d2_pt-grow0.svg',
      opts: o4('18', '17', '16', '19'), ans: 'B',
      why: 'Khoảng cách tăng dần 2, 3, 4, 5. Số cuối là 12 + 5 = 17.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 12', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd3/d2_pt-grow1.svg',
      opts: o4('19', '20', '18', '21'), ans: 'A',
      why: 'Khoảng cách tăng dần 3, 4, 5, 6. Số cuối là 13 + 6 = 19.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 13', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd3/d2_pt-grow2.svg',
      opts: o4('13', '11', '12', '14'), ans: 'C',
      why: 'Khoảng cách tăng dần 1, 2, 3, 4. Số cuối là 8 + 4 = 12.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 14', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd3/d2_pt-grow3.svg',
      opts: o4('13', '12', '11', '14'), ans: 'B',
      why: 'Khoảng cách tăng dần 1, 2, 3, 4. Số cuối là 8 + 4 = 12.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 15', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd3/d2_pt-grow4.svg',
      opts: o4('21', '22', '20', '23'), ans: 'A',
      why: 'Khoảng cách tăng dần 3, 4, 5, 6. Số cuối là 15 + 6 = 21.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 16', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd3/d2_pt-mul0.svg',
      opts: o4('10', '8', '6', '9'), ans: 'B',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 4 × 2 = 8.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 17', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd3/d2_pt-mul1.svg',
      opts: o4('16', '18', '14', '12'), ans: 'A',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 8 × 2 = 16.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 18', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd3/d2_pt-mul2.svg',
      opts: o4('26', '22', '18', '24'), ans: 'D',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 12 × 2 = 24.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 19', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd3/d2_pt-mul3.svg',
      opts: o4('10', '8', '6', '9'), ans: 'B',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 4 × 2 = 8.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 20', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd3/d2_pt-mul4.svg',
      opts: o4('18', '14', '12', '16'), ans: 'D',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 8 × 2 = 16.' },
  ],
},
{
  id: 3303, title: 'Dạng 3 · Số còn thiếu (Missing Number)', time: 25,
  questions: [
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 1', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd3/d3_mi-arr0.svg',
      opts: o4('20', '14', '17', '18'), ans: 'C',
      why: 'Mỗi mũi tên là + 3. Số cần tìm là 14 + 3 = 17.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 2', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd3/d3_mi-arr1.svg',
      opts: o4('18', '10', '15', '14'), ans: 'D',
      why: 'Mỗi mũi tên là + 4. Số cần tìm là 10 + 4 = 14.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 3', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd3/d3_mi-arr2.svg',
      opts: o4('12', '18', '6', '13'), ans: 'A',
      why: 'Mỗi mũi tên là + 6. Số cần tìm là 6 + 6 = 12.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 4', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd3/d3_mi-arr3.svg',
      opts: o4('26', '16', '22', '21'), ans: 'D',
      why: 'Mỗi mũi tên là + 5. Số cần tìm là 16 + 5 = 21.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 5', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd3/d3_mi-arr4.svg',
      opts: o4('38', '8', '24', '23'), ans: 'D',
      why: 'Mỗi mũi tên là + 15. Số cần tìm là 8 + 15 = 23.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 6', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? + 137 = 240</b>',
      opts: o4('103', '240', '113', '94'), ans: 'A',
      why: 'Số cần tìm = 240 − 137 = 103.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 7', pts: 0.5,
      text: 'Tìm số thích hợp: <b>142 + ? = 447</b>',
      opts: o4('447', '305', '315', '296'), ans: 'B',
      why: 'Số cần tìm = 447 − 142 = 305.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 8', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? + 62 = 358</b>',
      opts: o4('296', '358', '306', '287'), ans: 'A',
      why: 'Số cần tìm = 358 − 62 = 296.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 9', pts: 0.5,
      text: 'Tìm số thích hợp: <b>22 + ? = 188</b>',
      opts: o4('166', '188', '176', '157'), ans: 'A',
      why: 'Số cần tìm = 188 − 22 = 166.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 10', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? + 269 = 532</b>',
      opts: o4('532', '273', '254', '263'), ans: 'D',
      why: 'Số cần tìm = 532 − 269 = 263.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 11', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd3/d3_mi-seq0.svg',
      opts: o4('14', '16', '12', '15'), ans: 'A',
      why: 'Dãy đếm thêm 2: số ở ô trống là 12 + 2 = 14.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 12', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd3/d3_mi-seq1.svg',
      opts: o4('30', '20', '27', '25'), ans: 'D',
      why: 'Dãy đếm thêm 5: số ở ô trống là 20 + 5 = 25.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 13', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd3/d3_mi-seq2.svg',
      opts: o4('80', '60', '72', '70'), ans: 'D',
      why: 'Dãy đếm thêm 10: số ở ô trống là 60 + 10 = 70.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 14', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd3/d3_mi-seq3.svg',
      opts: o4('24', '18', '21', '23'), ans: 'C',
      why: 'Dãy đếm thêm 3: số ở ô trống là 18 + 3 = 21.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 15', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd3/d3_mi-seq4.svg',
      opts: o4('32', '24', '28', '30'), ans: 'C',
      why: 'Dãy đếm thêm 4: số ở ô trống là 24 + 4 = 28.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 16', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? × 8 = 56</b>',
      opts: o4('56', '7', '8', '6'), ans: 'B',
      why: 'Số cần tìm = 56 : 8 = 7.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 17', pts: 0.5,
      text: 'Tìm số thích hợp: <b>4 × ? = 8</b>',
      opts: o4('2', '8', '4', '1'), ans: 'A',
      why: 'Số cần tìm = 8 : 4 = 2.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 18', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? : 3 = 3</b>',
      opts: o4('3', '9', '12', '10'), ans: 'B',
      why: 'Số bị chia = 3 × 3 = 9.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 19', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? × 6 = 48</b>',
      opts: o4('48', '9', '8', '6'), ans: 'C',
      why: 'Số cần tìm = 48 : 6 = 8.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 20', pts: 0.5,
      text: 'Tìm số thích hợp: <b>4 × ? = 8</b>',
      opts: o4('8', '4', '2', '1'), ans: 'C',
      why: 'Số cần tìm = 8 : 4 = 2.' },
  ],
},
{
  id: 3304, title: 'Dạng 4 · Suy luận (Logic & Deduction)', time: 25,
  questions: [
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 1', pts: 0.5,
      text: 'Cân thăng bằng. Biết 2 quả táo nặng bằng nhau. Hỏi <b>một quả táo</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd3/d4_lg-bal0.svg',
      opts: o4('18 kg', '10 kg', '8 kg', '9 kg'), ans: 'D',
      why: 'Tổng các quả cân là 6 + 6 + 6 = 18 kg cho 2 quả táo. Một quả táo nặng 18 : 2 = 9 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 2', pts: 0.5,
      text: 'Cân thăng bằng. Biết 3 quả cam nặng bằng nhau. Hỏi <b>một quả cam</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd3/d4_lg-bal1.svg',
      opts: o4('27 kg', '10 kg', '9 kg', '8 kg'), ans: 'C',
      why: 'Tổng các quả cân là 9 + 9 + 9 = 27 kg cho 3 quả cam. Một quả cam nặng 27 : 3 = 9 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 3', pts: 0.5,
      text: 'Cân thăng bằng. Biết 2 quả lê nặng bằng nhau. Hỏi <b>một quả lê</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd3/d4_lg-bal2.svg',
      opts: o4('8 kg', '16 kg', '9 kg', '7 kg'), ans: 'A',
      why: 'Tổng các quả cân là 5 + 6 + 5 = 16 kg cho 2 quả lê. Một quả lê nặng 16 : 2 = 8 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 4', pts: 0.5,
      text: 'Cân thăng bằng. Biết 3 quả chanh nặng bằng nhau. Hỏi <b>một quả chanh</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd3/d4_lg-bal3.svg',
      opts: o4('2 kg', '6 kg', '3 kg', '1 kg'), ans: 'A',
      why: 'Tổng các quả cân là 6 = 6 kg cho 3 quả chanh. Một quả chanh nặng 6 : 3 = 2 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 5', pts: 0.5,
      text: 'Cân thăng bằng. Biết 4 quả táo nặng bằng nhau. Hỏi <b>một quả táo</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd3/d4_lg-bal4.svg',
      opts: o4('32 kg', '8 kg', '9 kg', '7 kg'), ans: 'B',
      why: 'Tổng các quả cân là 11 + 11 + 10 = 32 kg cho 4 quả táo. Một quả táo nặng 32 : 4 = 8 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 6', pts: 0.5,
      text: 'Cân thăng bằng. Biết 3 quả cam nặng bằng nhau. Hỏi <b>một quả cam</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd3/d4_lg-bal5.svg',
      opts: o4('9 kg', '4 kg', '2 kg', '3 kg'), ans: 'D',
      why: 'Tổng các quả cân là 5 + 4 = 9 kg cho 3 quả cam. Một quả cam nặng 9 : 3 = 3 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 7', pts: 0.5,
      text: 'An cao hơn Bình, Bình cao hơn Cường. Hỏi bạn nào <b>cao nhất</b>?',
      opts: o4('Cường', 'Bình', 'Không xác định được', 'An'), ans: 'D',
      why: 'Xếp theo chiều cao: An > Bình > Cường. Vậy An cao nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 8', pts: 0.5,
      text: 'Bình cao hơn Cường, Cường cao hơn Dung. Hỏi bạn nào <b>thấp nhất</b>?',
      opts: o4('Bình', 'Cường', 'Dung', 'Không xác định được'), ans: 'C',
      why: 'Xếp theo chiều cao: Bình > Cường > Dung. Vậy Dung thấp nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 9', pts: 0.5,
      text: 'Cường cao hơn Dung, Dung cao hơn Hoa. Hỏi bạn nào <b>cao nhất</b>?',
      opts: o4('Hoa', 'Dung', 'Cường', 'Không xác định được'), ans: 'C',
      why: 'Xếp theo chiều cao: Cường > Dung > Hoa. Vậy Cường cao nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 10', pts: 0.5,
      text: 'Dung cao hơn Hoa, Hoa cao hơn Khôi. Hỏi bạn nào <b>thấp nhất</b>?',
      opts: o4('Dung', 'Hoa', 'Không xác định được', 'Khôi'), ans: 'D',
      why: 'Xếp theo chiều cao: Dung > Hoa > Khôi. Vậy Khôi thấp nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 11', pts: 0.5,
      text: 'Ba bạn An, Bình, Cường xếp thành một hàng. An đứng trước Bình, Cường đứng sau Bình. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('An', 'Bình', 'Cường', 'Không xác định được'), ans: 'B',
      why: 'Thứ tự hàng là An – Bình – Cường, nên Bình đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 12', pts: 0.5,
      text: 'Ba bạn Bình, Cường, Dung xếp thành một hàng. Bình đứng trước Cường, Dung đứng sau Cường. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('Bình', 'Dung', 'Cường', 'Không xác định được'), ans: 'C',
      why: 'Thứ tự hàng là Bình – Cường – Dung, nên Cường đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 13', pts: 0.5,
      text: 'Ba bạn Cường, Dung, Hoa xếp thành một hàng. Cường đứng trước Dung, Hoa đứng sau Dung. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('Cường', 'Hoa', 'Không xác định được', 'Dung'), ans: 'D',
      why: 'Thứ tự hàng là Cường – Dung – Hoa, nên Dung đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 14', pts: 0.5,
      text: 'Ba bạn Dung, Hoa, Khôi xếp thành một hàng. Dung đứng trước Hoa, Khôi đứng sau Hoa. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('Hoa', 'Dung', 'Khôi', 'Không xác định được'), ans: 'A',
      why: 'Thứ tự hàng là Dung – Hoa – Khôi, nên Hoa đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 15', pts: 0.5,
      text: 'An, Cường, Hoa mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. An không nuôi chó cũng không nuôi mèo. Cường nuôi mèo. Hỏi An nuôi con gì?',
      opts: o4('Chó', 'Mèo', 'Cá', 'Không biết'), ans: 'C',
      why: 'An không nuôi chó, không nuôi mèo nên An nuôi cá. (Cường nuôi mèo, còn Hoa nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 16', pts: 0.5,
      text: 'Bình, Dung, Khôi mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. Bình không nuôi chó cũng không nuôi mèo. Dung nuôi mèo. Hỏi Bình nuôi con gì?',
      opts: o4('Chó', 'Cá', 'Mèo', 'Không biết'), ans: 'B',
      why: 'Bình không nuôi chó, không nuôi mèo nên Bình nuôi cá. (Dung nuôi mèo, còn Khôi nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 17', pts: 0.5,
      text: 'Cường, Hoa, Lan mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. Cường không nuôi chó cũng không nuôi mèo. Hoa nuôi mèo. Hỏi Cường nuôi con gì?',
      opts: o4('Cá', 'Chó', 'Mèo', 'Không biết'), ans: 'A',
      why: 'Cường không nuôi chó, không nuôi mèo nên Cường nuôi cá. (Hoa nuôi mèo, còn Lan nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 18', pts: 0.5,
      text: 'Dung, Khôi, Minh mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. Dung không nuôi chó cũng không nuôi mèo. Khôi nuôi mèo. Hỏi Dung nuôi con gì?',
      opts: o4('Cá', 'Chó', 'Mèo', 'Không biết'), ans: 'A',
      why: 'Dung không nuôi chó, không nuôi mèo nên Dung nuôi cá. (Khôi nuôi mèo, còn Minh nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 19', pts: 0.5,
      text: 'Bút đắt hơn Thước, Thước đắt hơn Kẹo. Hỏi trong ba thứ, thứ nào <b>rẻ nhất</b>?',
      opts: o4('Bút', 'Thước', 'Không xác định được', 'Kẹo'), ans: 'D',
      why: 'Xếp theo giá: Bút > Thước > Kẹo. Vậy Kẹo rẻ nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 20', pts: 0.5,
      text: 'Vở đắt hơn Tẩy, Tẩy đắt hơn Bánh. Hỏi trong ba thứ, thứ nào <b>rẻ nhất</b>?',
      opts: o4('Vở', 'Bánh', 'Tẩy', 'Không xác định được'), ans: 'B',
      why: 'Xếp theo giá: Vở > Tẩy > Bánh. Vậy Bánh rẻ nhất.' },
  ],
},
{
  id: 3305, title: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', time: 25,
  questions: [
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 1', pts: 0.5,
      text: 'Tính nhanh: <b>17 + 3 + 31</b>', img: 'assets/ttd3/d5_me-round0.svg',
      opts: o4('51', '61', '41', '52'), ans: 'A',
      why: 'Ghép 17 + 3 = 20 (tròn chục) rồi cộng 31: 20 + 31 = 51.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 2', pts: 0.5,
      text: 'Tính nhanh: <b>13 + 7 + 36</b>', img: 'assets/ttd3/d5_me-round1.svg',
      opts: o4('66', '56', '46', '57'), ans: 'B',
      why: 'Ghép 13 + 7 = 20 (tròn chục) rồi cộng 36: 20 + 36 = 56.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 3', pts: 0.5,
      text: 'Tính nhanh: <b>13 + 7 + 27</b>', img: 'assets/ttd3/d5_me-round2.svg',
      opts: o4('57', '37', '48', '47'), ans: 'D',
      why: 'Ghép 13 + 7 = 20 (tròn chục) rồi cộng 27: 20 + 27 = 47.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 4', pts: 0.5,
      text: 'Tính nhanh: <b>16 + 4 + 23</b>', img: 'assets/ttd3/d5_me-round3.svg',
      opts: o4('43', '53', '33', '44'), ans: 'A',
      why: 'Ghép 16 + 4 = 20 (tròn chục) rồi cộng 23: 20 + 23 = 43.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 5', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>14 + 6 + 38 + 2</b>',
      opts: o4('60', '70', '59', '69'), ans: 'A',
      why: '(14 + 6) + (38 + 2) = 20 + 40 = 60.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 6', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>15 + 5 + 31 + 9</b>',
      opts: o4('70', '59', '69', '60'), ans: 'D',
      why: '(15 + 5) + (31 + 9) = 20 + 40 = 60.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 7', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>20 + 10 + 46 + 4</b>',
      opts: o4('90', '80', '79', '89'), ans: 'B',
      why: '(20 + 10) + (46 + 4) = 30 + 50 = 80.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 8', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>14 + 6 + 37 + 3</b>',
      opts: o4('70', '59', '60', '69'), ans: 'C',
      why: '(14 + 6) + (37 + 3) = 20 + 40 = 60.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 9', pts: 0.5,
      text: 'Tính nhanh: <b>25 × 4</b>',
      opts: o4('100', '110', '90', '102'), ans: 'A',
      why: '25 × 4 = 100 (một phần tư của 400).' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 10', pts: 0.5,
      text: 'Tính nhanh: <b>5 × 8</b>',
      opts: o4('50', '30', '40', '42'), ans: 'C',
      why: '5 × 8 = 40. Mẹo: 5 × số chẵn = (số chẵn : 2) × 10 = 4 × 10 = 40.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 11', pts: 0.5,
      text: 'Tính nhanh: <b>9 × 6</b>',
      opts: o4('64', '44', '56', '54'), ans: 'D',
      why: '9 × 6 = 10 × 6 − 6 = 60 − 6 = 54.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 12', pts: 0.5,
      text: 'Tính nhanh: <b>9 × 8</b>',
      opts: o4('82', '62', '72', '74'), ans: 'C',
      why: '9 × 8 = 10 × 8 − 8 = 80 − 8 = 72.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 13', pts: 0.5,
      text: 'Tính nhanh: <b>50 × 6</b>',
      opts: o4('310', '300', '290', '302'), ans: 'B',
      why: '50 × 6 = 5 × 6 × 10 = 30 × 10 = 300.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 14', pts: 0.5,
      text: 'Tính nhanh: <b>2 × 49</b>',
      opts: o4('108', '88', '98', '100'), ans: 'C',
      why: '2 × 49 = 2 × 50 − 2 = 100 − 2 = 98.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 15', pts: 0.5,
      text: 'Tính nhanh: <b>99 + 38</b>',
      opts: o4('147', '136', '137', '138'), ans: 'C',
      why: 'Xem 99 ≈ 100: (100 + 38) − 1 = 138 − 1 = 137.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 16', pts: 0.5,
      text: 'Tính nhanh: <b>98 + 35</b>',
      opts: o4('133', '143', '132', '134'), ans: 'A',
      why: 'Xem 98 ≈ 99: (99 + 35) − 1 = 134 − 1 = 133.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 17', pts: 0.5,
      text: 'Tính nhanh: <b>199 + 62</b>',
      opts: o4('261', '271', '260', '262'), ans: 'A',
      why: 'Xem 199 ≈ 200: (200 + 62) − 1 = 262 − 1 = 261.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 18', pts: 0.5,
      text: 'Tính nhanh: <b>999 + 59</b>',
      opts: o4('1058', '1068', '1057', '1059'), ans: 'A',
      why: 'Xem 999 ≈ 1000: (1000 + 59) − 1 = 1059 − 1 = 1058.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 19', pts: 0.5,
      text: 'Không cần tính kết quả, hãy so sánh: <b>36 + 20</b> ... <b>36 + 29</b>. Dấu thích hợp là:',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B',
      why: 'Hai tổng cùng có 36, nhưng 29 > 20 nên 36 + 20 < 36 + 29.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 20', pts: 0.5,
      text: 'Không cần tính kết quả, hãy so sánh: <b>44 + 49</b> ... <b>44 + 51</b>. Dấu thích hợp là:',
      opts: o4('>', '=', '<', 'Không so sánh được'), ans: 'C',
      why: 'Hai tổng cùng có 44, nhưng 51 > 49 nên 44 + 49 < 44 + 51.' },
  ],
},
{
  id: 3306, title: 'Dạng 6 · Máy biến đổi (Transformation)', time: 25,
  questions: [
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 1', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd3/d6_tf-add0.svg',
      opts: o4('14', '13', '10', '12'), ans: 'B',
      why: 'Máy luôn cộng thêm 3 (2 → 5, ...). Vậy 10 → 10 + 3 = 13.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 2', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd3/d6_tf-add1.svg',
      opts: o4('16', '11', '15', '14'), ans: 'C',
      why: 'Máy luôn cộng thêm 4 (3 → 7, ...). Vậy 11 → 11 + 4 = 15.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 3', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd3/d6_tf-add2.svg',
      opts: o4('18', '17', '12', '16'), ans: 'B',
      why: 'Máy luôn cộng thêm 5 (4 → 9, ...). Vậy 12 → 12 + 5 = 17.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 4', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd3/d6_tf-add3.svg',
      opts: o4('20', '13', '19', '18'), ans: 'C',
      why: 'Máy luôn cộng thêm 6 (5 → 11, ...). Vậy 13 → 13 + 6 = 19.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 5', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd3/d6_tf-add4.svg',
      opts: o4('27', '14', '25', '26'), ans: 'D',
      why: 'Máy luôn cộng thêm 12 (6 → 18, ...). Vậy 14 → 14 + 12 = 26.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 6', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd3/d6_tf-mul0.svg',
      opts: o4('14', '8', '11', '12'), ans: 'D',
      why: 'Mỗi số ra gấp 2 lần số vào (2 → 4, ...). Vậy 6 → 6 × 2 = 12.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 7', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd3/d6_tf-mul1.svg',
      opts: o4('14', '16', '9', '13'), ans: 'A',
      why: 'Mỗi số ra gấp 2 lần số vào (3 → 6, ...). Vậy 7 → 7 × 2 = 14.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 8', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd3/d6_tf-mul2.svg',
      opts: o4('24', '27', '11', '23'), ans: 'A',
      why: 'Mỗi số ra gấp 3 lần số vào (4 → 12, ...). Vậy 8 → 8 × 3 = 24.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 9', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd3/d6_tf-mul3.svg',
      opts: o4('30', '12', '27', '26'), ans: 'C',
      why: 'Mỗi số ra gấp 3 lần số vào (5 → 15, ...). Vậy 9 → 9 × 3 = 27.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 10', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd3/d6_tf-mul4.svg',
      opts: o4('44', '14', '39', '40'), ans: 'D',
      why: 'Mỗi số ra gấp 4 lần số vào (6 → 24, ...). Vậy 10 → 10 × 4 = 40.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 11', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd3/d6_tf-two0.svg',
      opts: o4('13', '11', '10', '12'), ans: 'B',
      why: 'Máy làm: nhân 2 rồi cộng 1 (1 → 3, ...). Vậy 5 → 5 × 2 + 1 = 11.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 12', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd3/d6_tf-two1.svg',
      opts: o4('16', '12', '15', '14'), ans: 'D',
      why: 'Máy làm: nhân 2 rồi cộng 2 (2 → 6, ...). Vậy 6 → 6 × 2 + 2 = 14.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 13', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd3/d6_tf-two2.svg',
      opts: o4('19', '17', '14', '18'), ans: 'B',
      why: 'Máy làm: nhân 2 rồi cộng 3 (3 → 9, ...). Vậy 7 → 7 × 2 + 3 = 17.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 14', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd3/d6_tf-two3.svg',
      opts: o4('19', '17', '16', '18'), ans: 'B',
      why: 'Máy làm: nhân 2 rồi cộng 1 (4 → 9, ...). Vậy 8 → 8 × 2 + 1 = 17.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 15', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd3/d6_tf-two4.svg',
      opts: o4('22', '18', '21', '20'), ans: 'D',
      why: 'Máy làm: nhân 2 rồi cộng 2 (5 → 12, ...). Vậy 9 → 9 × 2 + 2 = 20.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 16', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>20</b> thì phải đưa vào số nào?', img: 'assets/ttd3/d6_tf-rev0.svg',
      opts: o4('20', '15', '16', '17'), ans: 'C',
      why: 'Máy cộng thêm 4. Để ra 20 thì số vào là 20 − 4 = 16.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 17', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>21</b> thì phải đưa vào số nào?', img: 'assets/ttd3/d6_tf-rev1.svg',
      opts: o4('21', '15', '16', '17'), ans: 'C',
      why: 'Máy cộng thêm 5. Để ra 21 thì số vào là 21 − 5 = 16.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 18', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>22</b> thì phải đưa vào số nào?', img: 'assets/ttd3/d6_tf-rev2.svg',
      opts: o4('22', '15', '16', '17'), ans: 'C',
      why: 'Máy cộng thêm 6. Để ra 22 thì số vào là 22 − 6 = 16.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 19', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>23</b> thì phải đưa vào số nào?', img: 'assets/ttd3/d6_tf-rev3.svg',
      opts: o4('23', '19', '20', '21'), ans: 'C',
      why: 'Máy cộng thêm 3. Để ra 23 thì số vào là 23 − 3 = 20.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 20', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>24</b> thì phải đưa vào số nào?', img: 'assets/ttd3/d6_tf-rev4.svg',
      opts: o4('24', '14', '13', '15'), ans: 'B',
      why: 'Máy cộng thêm 10. Để ra 24 thì số vào là 24 − 10 = 14.' },
  ],
},
{
  id: 3307, title: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', time: 25,
  questions: [
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 1', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd3/d7_sp-grid0.svg',
      opts: o4('20', '25', '16', '9'), ans: 'A',
      why: 'Có 4 hàng, mỗi hàng 5 ô nên có 5 × 4 = 20 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 2', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd3/d7_sp-grid1.svg',
      opts: o4('20', '12', '8', '16'), ans: 'D',
      why: 'Có 4 hàng, mỗi hàng 4 ô nên có 4 × 4 = 16 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 3', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd3/d7_sp-grid2.svg',
      opts: o4('12', '6', '8', '9'), ans: 'C',
      why: 'Có 2 hàng, mỗi hàng 4 ô nên có 4 × 2 = 8 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 4', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd3/d7_sp-grid3.svg',
      opts: o4('12', '8', '6', '9'), ans: 'B',
      why: 'Có 2 hàng, mỗi hàng 4 ô nên có 4 × 2 = 8 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 5', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd3/d7_sp-grid4.svg',
      opts: o4('25', '16', '9', '20'), ans: 'D',
      why: 'Có 4 hàng, mỗi hàng 5 ô nên có 5 × 4 = 20 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 6', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd3/d7_sp-cube0.svg',
      opts: o4('10', '11', '9', '16'), ans: 'A',
      why: 'Đếm theo từng cột: 1 + 4 + 4 + 1 = 10 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 7', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd3/d7_sp-cube1.svg',
      opts: o4('9', '8', '7', '12'), ans: 'B',
      why: 'Đếm theo từng cột: 3 + 1 + 1 + 3 = 8 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 8', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd3/d7_sp-cube2.svg',
      opts: o4('10', '9', '8', '12'), ans: 'B',
      why: 'Đếm theo từng cột: 3 + 2 + 3 + 1 = 9 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 9', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd3/d7_sp-cube3.svg',
      opts: o4('10', '9', '8', '16'), ans: 'B',
      why: 'Đếm theo từng cột: 2 + 2 + 4 + 1 = 9 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 10', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd3/d7_sp-cube4.svg',
      opts: o4('8', '6', '9', '7'), ans: 'D',
      why: 'Đếm theo từng cột: 2 + 2 + 2 + 1 = 7 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 11', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd3/d7_sp-tri0.svg',
      opts: o4('2', '3', '4', '5'), ans: 'B',
      why: 'Có 2 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 2×(2+1):2 = 3 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 12', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd3/d7_sp-tri1.svg',
      opts: o4('3', '2', '4', '5'), ans: 'A',
      why: 'Có 2 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 2×(2+1):2 = 3 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 13', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd3/d7_sp-tri2.svg',
      opts: o4('3', '7', '6', '5'), ans: 'C',
      why: 'Có 3 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 3×(3+1):2 = 6 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 14', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd3/d7_sp-tri3.svg',
      opts: o4('2', '3', '4', '5'), ans: 'B',
      why: 'Có 2 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 2×(2+1):2 = 3 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 15', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd3/d7_sp-tri4.svg',
      opts: o4('6', '3', '7', '5'), ans: 'A',
      why: 'Có 3 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 3×(3+1):2 = 6 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 16', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>tam giác</b>?', img: 'assets/ttd3/d7_sp-mix0.svg',
      opts: o4('3', '2', '4', '1'), ans: 'B',
      why: 'Đếm riêng các tam giác trong hình được 2 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 17', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>hình vuông</b>?', img: 'assets/ttd3/d7_sp-mix1.svg',
      opts: o4('4', '5', '6', '3'), ans: 'A',
      why: 'Đếm riêng các hình vuông trong hình được 4 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 18', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>hình tròn</b>?', img: 'assets/ttd3/d7_sp-mix2.svg',
      opts: o4('4', '5', '2', '3'), ans: 'D',
      why: 'Đếm riêng các hình tròn trong hình được 3 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 19', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>hình chữ nhật</b>?', img: 'assets/ttd3/d7_sp-mix3.svg',
      opts: o4('4', '3', '5', '2'), ans: 'B',
      why: 'Đếm riêng các hình chữ nhật trong hình được 3 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 20', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>tam giác</b>?', img: 'assets/ttd3/d7_sp-mix4.svg',
      opts: o4('4', '5', '2', '3'), ans: 'D',
      why: 'Đếm riêng các tam giác trong hình được 3 hình.' },
  ],
},
{
  id: 3308, title: 'Dạng 8 · Đếm số cách (Combinatorics)', time: 25,
  questions: [
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 1', pts: 0.5,
      text: 'Có 2 chiếc áo và 3 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd3/d8_cb-grid0.svg',
      opts: o4('5', '7', '6', '3'), ans: 'C',
      why: 'Mỗi áo ghép được với 3 quần/váy nên có 2 × 3 = 6 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 2', pts: 0.5,
      text: 'Có 3 chiếc áo và 4 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd3/d8_cb-grid1.svg',
      opts: o4('7', '13', '8', '12'), ans: 'D',
      why: 'Mỗi áo ghép được với 4 quần/váy nên có 3 × 4 = 12 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 3', pts: 0.5,
      text: 'Có 2 chiếc áo và 2 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd3/d8_cb-grid2.svg',
      opts: o4('4', '5', '2', '3'), ans: 'A',
      why: 'Mỗi áo ghép được với 2 quần/váy nên có 2 × 2 = 4 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 4', pts: 0.5,
      text: 'Có 3 chiếc áo và 3 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd3/d8_cb-grid3.svg',
      opts: o4('6', '10', '8', '9'), ans: 'D',
      why: 'Mỗi áo ghép được với 3 quần/váy nên có 3 × 3 = 9 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 5', pts: 0.5,
      text: 'Có 2 chiếc áo và 4 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd3/d8_cb-grid4.svg',
      opts: o4('6', '9', '4', '8'), ans: 'D',
      why: 'Mỗi áo ghép được với 4 quần/váy nên có 2 × 4 = 8 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 6', pts: 0.5,
      text: 'Từ các chữ số 6, 5, 7 lập được bao nhiêu số có <b>hai chữ số</b> mà hai chữ số <b>khác nhau</b>?',
      opts: o4('6', '7', '5', '8'), ans: 'A',
      why: 'Chữ số hàng chục có 3 cách, hàng đơn vị còn 2 cách: 3 × 2 = 6 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 7', pts: 0.5,
      text: 'Từ các chữ số 5, 3, 2 lập được bao nhiêu số có <b>hai chữ số</b> (các chữ số có thể lặp lại)?',
      opts: o4('10', '9', '8', '6'), ans: 'B',
      why: 'Mỗi hàng có 3 cách chọn: 3 × 3 = 9 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 8', pts: 0.5,
      text: 'Từ các chữ số 7, 2, 3 lập được bao nhiêu số có <b>hai chữ số</b> mà hai chữ số <b>khác nhau</b>?',
      opts: o4('6', '7', '5', '8'), ans: 'A',
      why: 'Chữ số hàng chục có 3 cách, hàng đơn vị còn 2 cách: 3 × 2 = 6 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 9', pts: 0.5,
      text: 'Từ các chữ số 9, 4, 8 lập được bao nhiêu số có <b>hai chữ số</b> (các chữ số có thể lặp lại)?',
      opts: o4('9', '10', '8', '6'), ans: 'A',
      why: 'Mỗi hàng có 3 cách chọn: 3 × 3 = 9 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 10', pts: 0.5,
      text: 'Từ các chữ số 4, 6, 5 lập được bao nhiêu số có <b>hai chữ số</b> mà hai chữ số <b>khác nhau</b>?',
      opts: o4('7', '5', '8', '6'), ans: 'D',
      why: 'Chữ số hàng chục có 3 cách, hàng đơn vị còn 2 cách: 3 × 2 = 6 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 11', pts: 0.5,
      text: 'Có 4 bạn gặp nhau, mỗi hai bạn bắt tay nhau đúng <b>một lần</b>. Có tất cả bao nhiêu cái bắt tay?',
      opts: o4('6', '12', '10', '8'), ans: 'A',
      why: 'Mỗi bạn gặp 3 bạn khác, mỗi cặp tính một lần: (4 − 1) + (4 − 2) + … + 1 = 6.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 12', pts: 0.5,
      text: 'Có 5 đội bóng thi đấu vòng tròn, hai đội bất kì đấu với nhau đúng <b>một trận</b>. Có tất cả bao nhiêu trận đấu?',
      opts: o4('20', '15', '11', '10'), ans: 'D',
      why: 'Mỗi đội gặp 4 đội khác, mỗi cặp tính một lần: (5 − 1) + (5 − 2) + … + 1 = 10.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 13', pts: 0.5,
      text: 'Có 6 bạn gặp nhau, mỗi hai bạn bắt tay nhau đúng <b>một lần</b>. Có tất cả bao nhiêu cái bắt tay?',
      opts: o4('30', '21', '12', '15'), ans: 'D',
      why: 'Mỗi bạn gặp 5 bạn khác, mỗi cặp tính một lần: (6 − 1) + (6 − 2) + … + 1 = 15.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 14', pts: 0.5,
      text: 'Có 7 đội bóng thi đấu vòng tròn, hai đội bất kì đấu với nhau đúng <b>một trận</b>. Có tất cả bao nhiêu trận đấu?',
      opts: o4('42', '28', '21', '14'), ans: 'C',
      why: 'Mỗi đội gặp 6 đội khác, mỗi cặp tính một lần: (7 − 1) + (7 − 2) + … + 1 = 21.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 15', pts: 0.5,
      text: 'Có 8 bạn gặp nhau, mỗi hai bạn bắt tay nhau đúng <b>một lần</b>. Có tất cả bao nhiêu cái bắt tay?',
      opts: o4('56', '36', '28', '16'), ans: 'C',
      why: 'Mỗi bạn gặp 7 bạn khác, mỗi cặp tính một lần: (8 − 1) + (8 − 2) + … + 1 = 28.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 16', pts: 0.5,
      text: 'Từ nhà đến trường có 2 con đường, từ trường đến sân bóng có 1 con đường. Có mấy cách đi từ nhà đến sân bóng qua trường?',
      opts: o4('3', '2', '1', '4'), ans: 'B',
      why: '2 con đường đầu × 1 con đường sau = 2 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 17', pts: 0.5,
      text: 'Từ A đến B có 3 con đường, từ B đến C có 1 con đường. Có mấy cách đi từ A đến C qua B?',
      opts: o4('3', '4', '2', '5'), ans: 'A',
      why: '3 × 1 = 3 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 18', pts: 0.5,
      text: 'Từ nhà tới hồ có 3 lối, mỗi lối chỉ đi được một mình nó. Nam muốn đi tới hồ rồi về theo <b>lối khác</b> lúc đi thì có mấy cách chọn lối đi?',
      opts: o4('7', '6', '5', '8'), ans: 'B',
      why: 'Lối đi chọn 1 trong 3 (3 cách), lối về phải khác nên còn 2 cách: 3 × 2 = 6 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 19', pts: 0.5,
      text: 'Có 2 chiếc mũ và 2 đôi giày. Chọn 1 mũ và 1 đôi giày thì có mấy cách?',
      opts: o4('5', '3', '4', '6'), ans: 'C',
      why: '2 mũ × 2 đôi giày = 4 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 20', pts: 0.5,
      text: 'Có 2 loại bánh và 3 loại nước. Chọn 1 bánh và 1 nước thì có mấy cách?',
      opts: o4('7', '5', '6', '8'), ans: 'C',
      why: '2 bánh × 3 nước = 6 cách.' },
  ],
},
{
  id: 3309, title: 'Dạng 9 · Phân loại (Classification)', time: 25,
  questions: [
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 1', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd0.svg',
      opts: o4('B', 'C', 'D', 'A'), ans: 'D',
      why: 'Táo, cam, lê là quả; ô tô là phương tiện — khác nhóm. Vậy chọn A.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 2', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd1.svg',
      opts: o4('A', 'B', 'D', 'C'), ans: 'C',
      why: 'Chó, mèo, thỏ là con vật; cây không phải con vật. Vậy chọn D.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 3', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd2.svg',
      opts: o4('B', 'C', 'D', 'A'), ans: 'A',
      why: 'Ô tô, xe buýt, xe đạp là phương tiện; chuối là quả. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 4', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd3.svg',
      opts: o4('C', 'D', 'A', 'B'), ans: 'A',
      why: 'Bóng đá, bóng rổ, tennis là quả bóng; quyển sách không phải bóng. Vậy chọn C.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 5', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd4.svg',
      opts: o4('C', 'B', 'D', 'A'), ans: 'B',
      why: 'Hoa; cá không phải hoa. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 6', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd5.svg',
      opts: o4('A', 'B', 'C', 'D'), ans: 'D',
      why: 'Bút chì, bút mực, thước là dụng cụ học tập; pizza là món ăn. Vậy chọn D.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 7', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd6.svg',
      opts: o4('C', 'D', 'A', 'B'), ans: 'D',
      why: 'Dâu, nho, đào là quả; xe buýt là phương tiện. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 8', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd3/d9_cl-odd7.svg',
      opts: o4('C', 'D', 'B', 'A'), ans: 'C',
      why: 'Ong, bướm, bọ rùa là côn trùng nhỏ; voi là thú lớn. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 9', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 12 ; 8 ; 2 ; 11?',
      opts: o4('12', '8', '11', '2'), ans: 'C',
      why: 'Ba số kia đều là số chẵn, chỉ có số này là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 10', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 5 ; 10 ; 32 ; 35?',
      opts: o4('5', '10', '35', '32'), ans: 'D',
      why: 'Ba số kia đều chia hết cho 5 (tận cùng 0 hoặc 5), số này thì không.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 11', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 90 ; 30 ; 19 ; 22?',
      opts: o4('90', '19', '30', '22'), ans: 'B',
      why: 'Ba số kia là số tròn chục, số này không tròn chục.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 12', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 10 ; 12 ; 15 ; 18?',
      opts: o4('10', '12', '15', '18'), ans: 'C',
      why: 'Ba số kia đều là số chẵn, chỉ có số này là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 13', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 20 ; 45 ; 48 ; 51?',
      opts: o4('20', '45', '51', '48'), ans: 'D',
      why: 'Ba số kia đều chia hết cho 5 (tận cùng 0 hoặc 5), số này thì không.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 14', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 80 ; 10 ; 90 ; 66?',
      opts: o4('66', '80', '10', '90'), ans: 'A',
      why: 'Ba số kia là số tròn chục, số này không tròn chục.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 15', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 2 ; 16 ; 12 ; 17?',
      opts: o4('2', '16', '17', '12'), ans: 'C',
      why: 'Ba số kia đều là số chẵn, chỉ có số này là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 16', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 30 ; 15 ; 10 ; 39?',
      opts: o4('30', '39', '15', '10'), ans: 'B',
      why: 'Ba số kia đều chia hết cho 5 (tận cùng 0 hoặc 5), số này thì không.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 17', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Hình tròn', 'Hình vuông', 'Hình chữ nhật', 'Hình tam giác'), ans: 'A',
      why: 'Ba hình kia có cạnh thẳng và có góc; hình tròn không có cạnh, không có góc.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 18', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Hình tam giác', 'Hình vuông', 'Hình tròn', 'Hình chữ nhật'), ans: 'A',
      why: 'Vuông, tròn, chữ nhật thường được coi cùng nhóm ở đây vì có 4 cạnh (vuông, chữ nhật) — nhưng tam giác chỉ có 3 cạnh, ít cạnh nhất.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 19', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Số 12', 'Số 20', 'Số 40', 'Số 35'), ans: 'D',
      why: '12, 20, 40 là số chẵn; 35 là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 20', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Con gà', 'Con cá', 'Con vịt', 'Con chim'), ans: 'B',
      why: 'Gà, vịt, chim có cánh (là loài chim/gia cầm); cá sống dưới nước, có vây.' },
  ],
},
{
  id: 3310, title: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', time: 25,
  questions: [
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 1', pts: 0.5,
      text: 'Bạn nào đọc được <b>nhiều sách nhất</b>?', img: 'assets/ttd3/d10_da-bar0.svg',
      opts: o4('Lan', 'Bình', 'An', 'Hoa'), ans: 'A',
      why: 'Cột cao nhất là của Lan (5 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 2', pts: 0.5,
      text: 'Bạn nào đọc được <b>ít sách nhất</b>?', img: 'assets/ttd3/d10_da-bar1.svg',
      opts: o4('Lan', 'An', 'Bình', 'Hoa'), ans: 'B',
      why: 'Cột thấp nhất là của An (2 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 3', pts: 0.5,
      text: 'Cả bốn bạn đọc được <b>tất cả</b> bao nhiêu quyển sách?', img: 'assets/ttd3/d10_da-bar2.svg',
      opts: o4('23', '19', '22', '21'), ans: 'D',
      why: 'Cộng số sách của bốn bạn: 5 + 8 + 3 + 5 = 21 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 4', pts: 0.5,
      text: 'Bạn Lan đọc <b>nhiều hơn</b> (hoặc ít hơn) bạn Bình bao nhiêu quyển?', img: 'assets/ttd3/d10_da-bar3.svg',
      opts: o4('4', '5', '6', '8'), ans: 'A',
      why: 'Chênh lệch là 6 − 2 = 4 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 5', pts: 0.5,
      text: 'Bạn nào đọc được <b>nhiều sách nhất</b>?', img: 'assets/ttd3/d10_da-bar4.svg',
      opts: o4('Bình', 'Lan', 'An', 'Hoa'), ans: 'A',
      why: 'Cột cao nhất là của Bình (10 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 6', pts: 0.5,
      text: 'Bạn nào đọc được <b>ít sách nhất</b>?', img: 'assets/ttd3/d10_da-bar5.svg',
      opts: o4('Lan', 'An', 'Hoa', 'Bình'), ans: 'D',
      why: 'Cột thấp nhất là của Bình (2 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 7', pts: 0.5,
      text: 'Cả bốn bạn đọc được <b>tất cả</b> bao nhiêu quyển sách?', img: 'assets/ttd3/d10_da-bar6.svg',
      opts: o4('22', '20', '18', '21'), ans: 'B',
      why: 'Cộng số sách của bốn bạn: 3 + 3 + 7 + 7 = 20 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 8', pts: 0.5,
      text: 'Bạn Lan đọc <b>nhiều hơn</b> (hoặc ít hơn) bạn Bình bao nhiêu quyển?', img: 'assets/ttd3/d10_da-bar7.svg',
      opts: o4('1', '2', '0', '14'), ans: 'C',
      why: 'Chênh lệch là 7 − 7 = 0 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 9', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 1 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd3/d10_da-pic0.svg',
      opts: o4('3', '4', '2', '5'), ans: 'A',
      why: 'Lớp Lan có 3 ngôi sao, mỗi sao 1 huy chương: 3 × 1 = 3 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 10', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 2 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd3/d10_da-pic1.svg',
      opts: o4('4', '10', '8', '6'), ans: 'C',
      why: 'Lớp Lan có 4 ngôi sao, mỗi sao 2 huy chương: 4 × 2 = 8 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 11', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 5 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd3/d10_da-pic2.svg',
      opts: o4('3', '20', '10', '15'), ans: 'D',
      why: 'Lớp Lan có 3 ngôi sao, mỗi sao 5 huy chương: 3 × 5 = 15 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 12', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 2 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd3/d10_da-pic3.svg',
      opts: o4('2', '6', '4', '5'), ans: 'C',
      why: 'Lớp Lan có 2 ngôi sao, mỗi sao 2 huy chương: 2 × 2 = 4 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 13', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 3 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd3/d10_da-pic4.svg',
      opts: o4('5', '15', '18', '12'), ans: 'B',
      why: 'Lớp Lan có 5 ngôi sao, mỗi sao 3 huy chương: 5 × 3 = 15 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 14', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 10 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd3/d10_da-pic5.svg',
      opts: o4('2', '30', '20', '10'), ans: 'C',
      why: 'Lớp Lan có 2 ngôi sao, mỗi sao 10 huy chương: 2 × 10 = 20 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 15', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. Cả bốn ngày bán được <b>tất cả</b> bao nhiêu cốc?', img: 'assets/ttd3/d10_da-tab0.svg',
      opts: o4('20', '14', '17', '18'), ans: 'C',
      why: 'Cộng số cốc bốn ngày: 5 + 3 + 3 + 6 = 17 cốc.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 16', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. <b>Ngày nào</b> bán được nhiều cốc nhất?', img: 'assets/ttd3/d10_da-tab1.svg',
      opts: o4('T4', 'T2', 'T3', 'T5'), ans: 'A',
      why: 'Số lớn nhất trong bảng là 11 (ngày T4).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 17', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. Cả bốn ngày bán được <b>tất cả</b> bao nhiêu cốc?', img: 'assets/ttd3/d10_da-tab2.svg',
      opts: o4('38', '41', '35', '39'), ans: 'A',
      why: 'Cộng số cốc bốn ngày: 10 + 11 + 5 + 12 = 38 cốc.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 18', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. <b>Ngày nào</b> bán được nhiều cốc nhất?', img: 'assets/ttd3/d10_da-tab3.svg',
      opts: o4('T4', 'T2', 'T3', 'T5'), ans: 'A',
      why: 'Số lớn nhất trong bảng là 11 (ngày T4).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 19', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. Cả bốn ngày bán được <b>tất cả</b> bao nhiêu cốc?', img: 'assets/ttd3/d10_da-tab4.svg',
      opts: o4('35', '32', '29', '33'), ans: 'B',
      why: 'Cộng số cốc bốn ngày: 6 + 11 + 7 + 8 = 32 cốc.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 20', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. <b>Ngày nào</b> bán được nhiều cốc nhất?', img: 'assets/ttd3/d10_da-tab5.svg',
      opts: o4('T3', 'T4', 'T2', 'T5'), ans: 'C',
      why: 'Số lớn nhất trong bảng là 7 (ngày T2).' },
  ],
},
{
  id: 3311, title: 'Dạng 11 · Toán có lời văn (Word Problem)', time: 25,
  questions: [
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 1', pts: 0.5,
      text: 'Anh có 22 cái kẹo, em có nhiều hơn anh 16 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd3/d11_wo-more0.svg',
      opts: o4('44', '60', '38', '76'), ans: 'B',
      why: 'Em có 22 + 16 = 38 cái. Cả hai có 22 + 38 = 60 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 2', pts: 0.5,
      text: 'Anh có 27 cái kẹo, em có nhiều hơn anh 20 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd3/d11_wo-more1.svg',
      opts: o4('54', '47', '74', '94'), ans: 'C',
      why: 'Em có 27 + 20 = 47 cái. Cả hai có 27 + 47 = 74 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 3', pts: 0.5,
      text: 'Anh có 61 cái kẹo, em có nhiều hơn anh 12 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd3/d11_wo-more2.svg',
      opts: o4('122', '134', '73', '146'), ans: 'B',
      why: 'Em có 61 + 12 = 73 cái. Cả hai có 61 + 73 = 134 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 4', pts: 0.5,
      text: 'Anh có 69 cái kẹo, em có nhiều hơn anh 12 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd3/d11_wo-more3.svg',
      opts: o4('138', '81', '150', '162'), ans: 'C',
      why: 'Em có 69 + 12 = 81 cái. Cả hai có 69 + 81 = 150 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 5', pts: 0.5,
      text: 'Nhà bạn Lan có 12 con gà, số vịt gấp 2 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd3/d11_wo-times0.svg',
      opts: o4('24', '14', '48', '36'), ans: 'D',
      why: 'Số vịt là 12 × 2 = 24 con. Cả gà và vịt: 12 + 24 = 36 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 6', pts: 0.5,
      text: 'Nhà bạn Lan có 10 con gà, số vịt gấp 3 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd3/d11_wo-times1.svg',
      opts: o4('30', '13', '50', '40'), ans: 'D',
      why: 'Số vịt là 10 × 3 = 30 con. Cả gà và vịt: 10 + 30 = 40 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 7', pts: 0.5,
      text: 'Nhà bạn Lan có 12 con gà, số vịt gấp 4 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd3/d11_wo-times2.svg',
      opts: o4('60', '48', '16', '72'), ans: 'A',
      why: 'Số vịt là 12 × 4 = 48 con. Cả gà và vịt: 12 + 48 = 60 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 8', pts: 0.5,
      text: 'Nhà bạn Lan có 9 con gà, số vịt gấp 4 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd3/d11_wo-times3.svg',
      opts: o4('45', '36', '13', '54'), ans: 'A',
      why: 'Số vịt là 9 × 4 = 36 con. Cả gà và vịt: 9 + 36 = 45 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 9', pts: 0.5,
      text: 'Có 4 hộp bút, mỗi hộp 8 chiếc. Người ta đã bán 19 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('32', '51', '13', '14'), ans: 'C',
      why: 'Tổng số bút: 4 × 8 = 32 chiếc. Còn lại: 32 − 19 = 13 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 10', pts: 0.5,
      text: 'Có 5 hộp bút, mỗi hộp 4 chiếc. Người ta đã bán 7 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('20', '27', '14', '13'), ans: 'D',
      why: 'Tổng số bút: 5 × 4 = 20 chiếc. Còn lại: 20 − 7 = 13 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 11', pts: 0.5,
      text: 'Có 7 hộp bút, mỗi hộp 7 chiếc. Người ta đã bán 16 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('49', '33', '65', '34'), ans: 'B',
      why: 'Tổng số bút: 7 × 7 = 49 chiếc. Còn lại: 49 − 16 = 33 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 12', pts: 0.5,
      text: 'Có 6 hộp bút, mỗi hộp 5 chiếc. Người ta đã bán 25 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('30', '55', '6', '5'), ans: 'D',
      why: 'Tổng số bút: 6 × 5 = 30 chiếc. Còn lại: 30 − 25 = 5 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 13', pts: 0.5,
      text: 'Có 12 chiếc bánh chia đều vào 6 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('3', '2', '6', '1'), ans: 'B',
      why: 'Mỗi đĩa có 12 : 6 = 2 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 14', pts: 0.5,
      text: 'Có 42 chiếc bánh chia đều vào 7 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('7', '6', '35', '5'), ans: 'B',
      why: 'Mỗi đĩa có 42 : 7 = 6 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 15', pts: 0.5,
      text: 'Có 54 chiếc bánh chia đều vào 6 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('10', '6', '48', '9'), ans: 'D',
      why: 'Mỗi đĩa có 54 : 6 = 9 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 16', pts: 0.5,
      text: 'Có 21 chiếc bánh chia đều vào 7 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('4', '7', '3', '14'), ans: 'C',
      why: 'Mỗi đĩa có 21 : 7 = 3 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 17', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 11 rồi bớt đi 15 thì được 9. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('9', '24', '13', '2'), ans: 'C',
      why: 'Tính ngược: 9 + 15 − 11 = 24 − 11 = 13.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 18', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 20 rồi bớt đi 8 thì được 26. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('26', '34', '14', '6'), ans: 'C',
      why: 'Tính ngược: 26 + 8 − 20 = 34 − 20 = 14.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 19', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 19 rồi bớt đi 4 thì được 52. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('52', '56', '37', '33'), ans: 'C',
      why: 'Tính ngược: 52 + 4 − 19 = 56 − 19 = 37.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 20', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 18 rồi bớt đi 3 thì được 25. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('25', '10', '28', '7'), ans: 'B',
      why: 'Tính ngược: 25 + 3 − 18 = 28 − 18 = 10.' },
  ],
},
{
  id: 3312, title: 'Dạng 12 · Bài toán khó (Non-routine)', time: 25,
  questions: [
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 1', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd3/d12_nr-magic0.svg',
      opts: o4('13', '14', '12', '33'), ans: 'A',
      why: 'Tổng mỗi hàng là 33. Lấy 33 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 13.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 2', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd3/d12_nr-magic1.svg',
      opts: o4('29', '27', '72', '28'), ans: 'D',
      why: 'Tổng mỗi hàng là 72. Lấy 72 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 28.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 3', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd3/d12_nr-magic2.svg',
      opts: o4('23', '19', '21', '45'), ans: 'C',
      why: 'Tổng mỗi hàng là 45. Lấy 45 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 21.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 4', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd3/d12_nr-magic3.svg',
      opts: o4('16', '15', '14', '39'), ans: 'B',
      why: 'Tổng mỗi hàng là 39. Lấy 39 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 15.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 5', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd3/d12_nr-dice0.svg',
      opts: o4('14', '12', '15', '13'), ans: 'D',
      why: 'Cộng số chấm: 6 + 1 + 6 = 13 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 6', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd3/d12_nr-dice1.svg',
      opts: o4('11', '12', '10', '13'), ans: 'A',
      why: 'Cộng số chấm: 4 + 1 + 6 = 11 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 7', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd3/d12_nr-dice2.svg',
      opts: o4('5', '4', '3', '6'), ans: 'B',
      why: 'Cộng số chấm: 1 + 1 + 2 = 4 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 8', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd3/d12_nr-dice3.svg',
      opts: o4('10', '9', '8', '11'), ans: 'B',
      why: 'Cộng số chấm: 3 + 5 + 1 = 9 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 9', pts: 0.5,
      text: 'Trong sân có 5 con gà và 4 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('9', '26', '28', '27'), ans: 'B',
      why: 'Gà 2 chân: 5 × 2 = 10. Chó 4 chân: 4 × 4 = 16. Tất cả: 10 + 16 = 26 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 10', pts: 0.5,
      text: 'Trong sân có 3 con gà và 3 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('6', '20', '19', '18'), ans: 'D',
      why: 'Gà 2 chân: 3 × 2 = 6. Chó 4 chân: 3 × 4 = 12. Tất cả: 6 + 12 = 18 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 11', pts: 0.5,
      text: 'Trong sân có 5 con gà và 3 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('8', '22', '24', '26'), ans: 'B',
      why: 'Gà 2 chân: 5 × 2 = 10. Chó 4 chân: 3 × 4 = 12. Tất cả: 10 + 12 = 22 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 12', pts: 0.5,
      text: 'Trong sân có 5 con gà và 4 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('26', '9', '28', '27'), ans: 'A',
      why: 'Gà 2 chân: 5 × 2 = 10. Chó 4 chân: 4 × 4 = 16. Tất cả: 10 + 16 = 26 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 13', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 12 m, hai cây liền nhau cách nhau 2 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('6', '8', '7', '9'), ans: 'C',
      why: 'Số khoảng cách là 12 : 2 = 6. Trồng cả hai đầu nên số cây = số khoảng + 1 = 7 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 14', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 15 m, hai cây liền nhau cách nhau 3 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('5', '6', '7', '8'), ans: 'B',
      why: 'Số khoảng cách là 15 : 3 = 5. Trồng cả hai đầu nên số cây = số khoảng + 1 = 6 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 15', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 15 m, hai cây liền nhau cách nhau 5 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('4', '3', '5', '6'), ans: 'A',
      why: 'Số khoảng cách là 15 : 5 = 3. Trồng cả hai đầu nên số cây = số khoảng + 1 = 4 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 16', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 12 m, hai cây liền nhau cách nhau 4 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('3', '4', '5', '6'), ans: 'B',
      why: 'Số khoảng cách là 12 : 4 = 3. Trồng cả hai đầu nên số cây = số khoảng + 1 = 4 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 17', pts: 0.5,
      text: 'Năm nay con 6 tuổi, bố hơn con 25 tuổi. Hỏi <b>bố</b> năm nay bao nhiêu tuổi?',
      opts: o4('31', '12', '25', '33'), ans: 'A',
      why: 'Tuổi bố = 6 + 25 = 31 tuổi.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 18', pts: 0.5,
      text: 'Năm nay con 7 tuổi. Hỏi <b>sau 6 năm nữa</b> con bao nhiêu tuổi?',
      opts: o4('7', '6', '14', '13'), ans: 'D',
      why: 'Sau 6 năm, tuổi con là 7 + 6 = 13 tuổi.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 19', pts: 0.5,
      text: 'Năm nay con 6 tuổi, bố hơn con 25 tuổi. Hỏi <b>bố</b> năm nay bao nhiêu tuổi?',
      opts: o4('12', '31', '25', '33'), ans: 'B',
      why: 'Tuổi bố = 6 + 25 = 31 tuổi.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 20', pts: 0.5,
      text: 'Năm nay con 9 tuổi. Hỏi <b>sau 6 năm nữa</b> con bao nhiêu tuổi?',
      opts: o4('9', '6', '16', '15'), ans: 'D',
      why: 'Sau 6 năm, tuổi con là 9 + 6 = 15 tuổi.' },
  ],
},
];

// Chèn môn "Toán tư duy 12 dạng" cho lớp 3
SUBJECTS.push({
  id: 'ttd3', name: 'Tư duy 12 dạng', short: 'Tư duy 3', icon: '💡', grade: 3,
  exams: TTD3, ready: true,
  heroTitle: 'Toán tư duy 12 dạng — lớp 3',
  heroMeta: '📚 12 dạng &nbsp;•&nbsp; 240 câu &nbsp;•&nbsp; ⏱ 25 phút mỗi đề &nbsp;•&nbsp; 137 câu có hình (57%) &nbsp;•&nbsp; lời giải chi tiết',
});
