// TỰ NHIÊN VÀ XÃ HỘI — LỚP 1 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 15 phút mỗi đề.
//
// Bám 6 chủ đề của chương trình TNXH lớp 1:
//   1. Gia đình            2. Trường học
//   3. Cộng đồng địa phương 4. Thực vật và động vật
//   5. Con người và sức khoẻ 6. Trái Đất và bầu trời
//
// Mức độ: nhận biết – hiểu, phù hợp học sinh 6 tuổi; câu hỏi ngắn, gần gũi đời sống.
// Trường `why` giải thích ngắn để phụ huynh/bé cùng đọc lại sau khi làm.

const TNXH1_EXAMS = [

/* ═══════════ ĐỀ 1 — GIA ĐÌNH CỦA EM ═══════════ */
{
  id: 5101, title: 'Đề 1 · Gia đình của em', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Gia đình thường có những ai?',
      opts: o4('Chỉ có mình em', 'Ông bà, bố mẹ, anh chị em', 'Chỉ có các bạn cùng lớp', 'Chỉ có cô giáo'), ans: 'B',
      why: 'Gia đình là những người thân sống cùng nhau: ông bà, bố mẹ, anh chị em.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Người sinh ra bố của em, em gọi là gì?',
      opts: o4('Ông bà ngoại', 'Cô, dì', 'Ông bà nội', 'Bác hàng xóm'), ans: 'C',
      why: 'Bố mẹ của bố là ông nội, bà nội.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Người sinh ra mẹ của em, em gọi là gì?',
      opts: o4('Ông bà nội', 'Ông bà ngoại', 'Chú, thím', 'Anh, chị'), ans: 'B',
      why: 'Bố mẹ của mẹ là ông ngoại, bà ngoại.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Em gái của mẹ em, em gọi là gì?',
      opts: o4('Dì', 'Bác trai', 'Ông', 'Anh'), ans: 'A',
      why: 'Em gái của mẹ được gọi là dì.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Ngày nghỉ, gia đình em thường làm gì cùng nhau?',
      opts: o4('Mỗi người đi một nơi, không gặp nhau', 'Cùng ăn cơm, trò chuyện, đi chơi', 'Không ai nói với ai', 'Cãi nhau cả ngày'), ans: 'B',
      why: 'Ngày nghỉ là dịp cả nhà quây quần: cùng ăn cơm, trò chuyện, đi chơi.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Việc nào cho thấy em biết yêu thương ông bà?',
      opts: o4('Lấy nước, bóp vai cho ông bà', 'Không chào hỏi ông bà', 'Giành đồ ăn của ông bà', 'Cãi lời ông bà'), ans: 'A',
      why: 'Rót nước, bóp vai, hỏi han là những việc nhỏ thể hiện lòng yêu thương ông bà.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Khi ông (bà) bị ốm, em nên làm gì?',
      opts: o4('Chạy đi chơi thật xa', 'Hỏi thăm và chăm sóc ông bà', 'La hét thật to', 'Mặc kệ ông bà'), ans: 'B',
      why: 'Người thân ốm thì em nên hỏi thăm, chăm sóc, giữ yên lặng cho ông bà nghỉ.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Anh, chị, em trong nhà nên đối xử với nhau thế nào?',
      opts: o4('Tranh giành đồ chơi', 'Đánh nhau mỗi ngày', 'Nhường nhịn, thương yêu nhau', 'Không chơi cùng nhau'), ans: 'C',
      why: 'Anh chị em một nhà thì phải nhường nhịn, thương yêu nhau.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Việc nhà nào một bạn lớp 1 có thể giúp bố mẹ?',
      opts: o4('Nấu một nồi canh to', 'Sửa xe máy', 'Gấp quần áo, cất dép gọn gàng', 'Lái ô tô'), ans: 'C',
      why: 'Bé có thể làm việc vừa sức: gấp quần áo, cất dép, quét nhà cùng bố mẹ.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Nhà là nơi để làm gì?',
      opts: o4('Chỉ để chứa đồ', 'Để cả nhà cùng ở, nghỉ ngơi và yêu thương nhau', 'Để không ai vào', 'Để nuôi thú dữ'), ans: 'B',
      why: 'Ngôi nhà là nơi các thành viên cùng chung sống, nghỉ ngơi và yêu thương nhau.' },
  ],
},

/* ═══════════ ĐỀ 2 — NGÔI NHÀ, ĐỒ DÙNG VÀ AN TOÀN Ở NHÀ ═══════════ */
{
  id: 5102, title: 'Đề 2 · Ngôi nhà và an toàn khi ở nhà', time: 15,
  questions: [
    { sec: 'Nhà ở', name: 'Câu 1', pts: 1,
      text: 'Phòng dùng để nấu ăn trong nhà gọi là gì?',
      opts: o4('Phòng ngủ', 'Phòng bếp', 'Phòng khách', 'Nhà tắm'), ans: 'B',
      why: 'Nơi có bếp, nồi, xoong để nấu ăn là phòng bếp.' },
    { sec: 'Nhà ở', name: 'Câu 2', pts: 1,
      text: 'Đồ dùng nào dùng để quét nhà?',
      opts: o4('Cái chổi', 'Cái nồi', 'Cái quạt', 'Cái ti vi'), ans: 'A',
      why: 'Chổi dùng để quét cho nhà sạch sẽ.' },
    { sec: 'Nhà ở', name: 'Câu 3', pts: 1,
      text: 'Đồ dùng nào giúp làm mát vào ngày nóng?',
      opts: o4('Cái chăn bông', 'Cái quạt', 'Đôi giày', 'Quyển vở'), ans: 'B',
      why: 'Quạt (hoặc điều hoà) giúp làm mát khi trời nóng.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Vật nào nguy hiểm, trẻ em không được lấy ra chơi?',
      opts: o4('Con gấu bông', 'Quả bóng nhựa', 'Bao diêm, bật lửa', 'Bút màu'), ans: 'C',
      why: 'Diêm và bật lửa có thể gây bỏng, cháy nên trẻ em không được nghịch.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Vì sao không được cho tay hay que vào ổ cắm điện?',
      opts: o4('Vì sẽ bị điện giật rất nguy hiểm', 'Vì ổ điện bẩn', 'Vì làm hỏng tay áo', 'Vì ổ điện kêu to'), ans: 'A',
      why: 'Chọc vào ổ điện có thể bị điện giật, rất nguy hiểm đến tính mạng.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Thấy phích nước sôi (nước nóng) trên bàn, em nên làm gì?',
      opts: o4('Sờ thử xem nóng không', 'Tránh xa, không nghịch', 'Đổ ra sàn chơi', 'Mang đi giấu'), ans: 'B',
      why: 'Nước sôi gây bỏng nặng, em phải tránh xa và không tự rót.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Đồ vật nào dưới đây sắc nhọn, dễ gây đứt tay?',
      opts: o4('Cái gối', 'Con dao', 'Cái khăn mặt', 'Quả bóng'), ans: 'B',
      why: 'Dao, kéo là vật sắc nhọn; khi dùng phải có người lớn và cầm cẩn thận.' },
    { sec: 'Nhà ở', name: 'Câu 8', pts: 1,
      text: 'Chơi xong, em nên làm gì với đồ chơi?',
      opts: o4('Vứt khắp nhà', 'Cất gọn vào đúng chỗ', 'Ném ra ngoài sân', 'Giấu đi cho bẩn'), ans: 'B',
      why: 'Chơi xong phải cất đồ gọn gàng để nhà sạch và khỏi vấp ngã.' },
    { sec: 'Nhà ở', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp giữ nhà cửa sạch sẽ?',
      opts: o4('Vẽ bẩn lên tường', 'Quét nhà, lau bàn, đổ rác đúng chỗ', 'Để rác khắp nơi', 'Không bao giờ dọn'), ans: 'B',
      why: 'Quét nhà, lau bàn, đổ rác đúng nơi giúp nhà luôn sạch.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Khi ở nhà một mình có người lạ gõ cửa, em nên làm gì?',
      opts: o4('Mở cửa cho người lạ vào ngay', 'Không mở cửa và gọi điện cho bố mẹ', 'Đi theo người lạ', 'Cho người lạ tiền'), ans: 'B',
      why: 'Không tự mở cửa cho người lạ; nên gọi báo bố mẹ hoặc người thân.' },
  ],
},

/* ═══════════ ĐỀ 3 — TRƯỜNG HỌC CỦA EM ═══════════ */
{
  id: 5103, title: 'Đề 3 · Trường học của em', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Ở trường, người dạy em học chữ, học toán là ai?',
      opts: o4('Bác bảo vệ', 'Thầy, cô giáo', 'Bạn cùng lớp', 'Chú lái xe'), ans: 'B',
      why: 'Thầy giáo, cô giáo là người dạy dỗ em ở trường.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Những bạn học cùng lớp với em gọi là gì?',
      opts: o4('Bạn cùng lớp', 'Người lạ', 'Hàng xóm', 'Khách'), ans: 'A',
      why: 'Các bạn học chung một lớp là bạn cùng lớp của em.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Đồ dùng nào là đồ dùng học tập?',
      opts: o4('Nồi cơm điện', 'Bút, sách, vở', 'Cái chổi', 'Con dao'), ans: 'B',
      why: 'Bút, sách, vở, cặp là đồ dùng học tập của em.' },
    { sec: 'Trường học', name: 'Câu 4', pts: 1,
      text: 'Nơi các bạn chạy nhảy, vui chơi trong giờ ra chơi là ở đâu?',
      opts: o4('Sân trường', 'Trên mái nhà', 'Ngoài đường lớn', 'Trong nhà bếp'), ans: 'A',
      why: 'Giờ ra chơi, học sinh chơi ở sân trường cho an toàn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Trò chơi nào an toàn khi chơi ở sân trường?',
      opts: o4('Leo lên tường cao', 'Ném đá vào bạn', 'Nhảy dây, chơi ô ăn quan', 'Xô đẩy nhau ở cầu thang'), ans: 'C',
      why: 'Nhảy dây, ô ăn quan là trò an toàn; leo cao, ném đá, xô đẩy dễ gây tai nạn.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Khi lên xuống cầu thang, em nên đi thế nào?',
      opts: o4('Chạy thật nhanh', 'Xô đẩy bạn', 'Đi từ tốn, bám tay vịn, đi bên phải', 'Nhảy hai bậc một'), ans: 'C',
      why: 'Đi chậm, bám tay vịn và đi bên phải để không bị ngã.' },
    { sec: 'Trường học', name: 'Câu 7', pts: 1,
      text: 'Thấy bạn bị ngã ở sân trường, em nên làm gì?',
      opts: o4('Cười chê bạn', 'Đỡ bạn dậy và báo cho thầy cô', 'Bỏ đi chỗ khác', 'Đẩy thêm cho bạn ngã'), ans: 'B',
      why: 'Em nên giúp đỡ bạn dậy và báo thầy cô nếu bạn bị đau.' },
    { sec: 'Trường học', name: 'Câu 8', pts: 1,
      text: 'Để giữ lớp học sạch sẽ, em nên làm gì?',
      opts: o4('Vứt rác ra sàn lớp', 'Bỏ rác vào thùng rác', 'Vẽ bậy lên bàn', 'Bôi bẩn lên tường'), ans: 'B',
      why: 'Bỏ rác đúng thùng, không vẽ bậy giúp lớp luôn sạch đẹp.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Khi cô giáo đang giảng bài, em nên làm gì?',
      opts: o4('Nói chuyện riêng thật to', 'Chú ý lắng nghe', 'Ngủ gật', 'Chạy ra khỏi lớp'), ans: 'B',
      why: 'Chú ý lắng nghe cô giảng thì em mới hiểu bài.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Bác bảo vệ ở trường làm công việc gì?',
      opts: o4('Dạy em học hát', 'Nấu ăn cho cả lớp', 'Trông coi, giữ an toàn cho trường', 'Bán quần áo'), ans: 'C',
      why: 'Bác bảo vệ trông coi trường, giữ an toàn cho học sinh.' },
  ],
},

/* ═══════════ ĐỀ 4 — CỘNG ĐỒNG VÀ AN TOÀN GIAO THÔNG ═══════════ */
{
  id: 5104, title: 'Đề 4 · Nơi em sống và an toàn giao thông', time: 15,
  questions: [
    { sec: 'Cộng đồng', name: 'Câu 1', pts: 1,
      text: 'Nơi mọi người đến mua bán rau, thịt, cá, đồ dùng gọi là gì?',
      opts: o4('Bệnh viện', 'Chợ (hoặc siêu thị)', 'Trường học', 'Bưu điện'), ans: 'B',
      why: 'Chợ và siêu thị là nơi mua bán hàng hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 2', pts: 1,
      text: 'Khi bị ốm, em được đưa đến đâu để khám bệnh?',
      opts: o4('Bệnh viện hoặc trạm y tế', 'Rạp chiếu phim', 'Sân bóng', 'Cửa hàng bánh'), ans: 'A',
      why: 'Bệnh viện, trạm y tế là nơi khám và chữa bệnh.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Người khám và chữa bệnh cho em gọi là gì?',
      opts: o4('Chú công an', 'Bác nông dân', 'Bác sĩ', 'Cô bán hàng'), ans: 'C',
      why: 'Bác sĩ là người khám bệnh, chữa bệnh cho mọi người.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Đèn giao thông màu ĐỎ báo hiệu điều gì?',
      opts: o4('Được đi tiếp', 'Dừng lại', 'Đi thật nhanh', 'Rẽ phải'), ans: 'B',
      why: 'Đèn đỏ nghĩa là dừng lại.' },
    { sec: 'Giao thông', name: 'Câu 5', pts: 1,
      text: 'Đèn giao thông màu XANH báo hiệu điều gì?',
      opts: o4('Dừng lại', 'Được đi', 'Lùi lại', 'Đứng im mãi mãi'), ans: 'B',
      why: 'Đèn xanh nghĩa là được phép đi.' },
    { sec: 'Giao thông', name: 'Câu 6', pts: 1,
      text: 'Người đi bộ nên đi ở phần đường nào?',
      opts: o4('Giữa lòng đường', 'Trên vỉa hè (lề đường)', 'Chỗ nào cũng được', 'Ngay trước đầu ô tô'), ans: 'B',
      why: 'Người đi bộ đi trên vỉa hè; nơi không có vỉa hè thì đi sát lề bên phải.' },
    { sec: 'Giao thông', name: 'Câu 7', pts: 1,
      text: 'Khi muốn qua đường, em nên làm gì?',
      opts: o4('Chạy nhanh qua giữa dòng xe', 'Đi theo vạch kẻ, nắm tay người lớn, nhìn hai phía', 'Nhắm mắt băng qua', 'Qua đường lúc đèn đỏ dành cho người đi bộ'), ans: 'B',
      why: 'Qua đường phải đi đúng vạch, quan sát hai bên và nắm tay người lớn.' },
    { sec: 'Giao thông', name: 'Câu 8', pts: 1,
      text: 'Khi ngồi trên xe máy, em phải làm gì để an toàn?',
      opts: o4('Đội mũ bảo hiểm', 'Đứng lên xe', 'Thả hai tay', 'Quay ngang quay ngửa'), ans: 'A',
      why: 'Ngồi xe máy phải đội mũ bảo hiểm và ngồi yên, bám chắc.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Chú công an giao thông làm nhiệm vụ gì?',
      opts: o4('Trồng lúa', 'Điều khiển, giữ trật tự giao thông', 'Dạy học', 'Bán vé xem phim'), ans: 'B',
      why: 'Công an giao thông điều khiển và giữ trật tự cho đường phố an toàn.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp làng xóm, phố phường sạch đẹp?',
      opts: o4('Vứt rác xuống ao hồ', 'Bỏ rác đúng nơi, trồng và chăm cây', 'Bẻ cành hái hoa nơi công cộng', 'Vẽ bậy lên tường'), ans: 'B',
      why: 'Bỏ rác đúng chỗ và trồng cây làm nơi mình sống sạch, đẹp.' },
  ],
},

/* ═══════════ ĐỀ 5 — THỰC VẬT QUANH EM ═══════════ */
{
  id: 5105, title: 'Đề 5 · Cây cối quanh em', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Một cây thường có các bộ phận nào?',
      opts: o4('Chỉ có lá', 'Rễ, thân, lá (nhiều cây có hoa, quả)', 'Chỉ có hoa', 'Chỉ có rễ'), ans: 'B',
      why: 'Cây thường gồm rễ, thân, lá; nhiều cây còn có hoa và quả.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Bộ phận nào của cây nằm dưới đất, hút nước và chất nuôi cây?',
      opts: o4('Lá', 'Hoa', 'Rễ', 'Quả'), ans: 'C',
      why: 'Rễ cây cắm xuống đất để hút nước và chất dinh dưỡng nuôi cây.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Cây nào sau đây cho ta quả để ăn?',
      opts: o4('Cây cam', 'Cây cột điện', 'Cỏ dại', 'Cây nhựa trang trí'), ans: 'A',
      why: 'Cây cam là cây ăn quả, cho quả cam để ăn.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Rau muống, rau cải là loại cây gì?',
      opts: o4('Cây lấy gỗ', 'Cây rau (làm thức ăn)', 'Cây hoa', 'Cây bóng mát'), ans: 'B',
      why: 'Rau muống, rau cải là cây rau, dùng làm thức ăn hằng ngày.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Muốn cây sống và lớn lên, ta cần làm gì?',
      opts: o4('Tưới nước, cho cây có ánh sáng', 'Đổ dầu ăn lên cây', 'Nhổ hết rễ đi', 'Để cây trong bóng tối kín'), ans: 'A',
      why: 'Cây cần nước, ánh sáng và không khí mới sống và lớn được.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Cây xanh mang lại lợi ích nào cho con người?',
      opts: o4('Làm không khí bẩn hơn', 'Cho bóng mát, quả, gỗ và không khí trong lành', 'Không có ích gì', 'Làm nắng nóng hơn'), ans: 'B',
      why: 'Cây cho bóng mát, quả, gỗ và giúp không khí trong lành.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Việc nào là chăm sóc, bảo vệ cây?',
      opts: o4('Bẻ cành, ngắt lá cho vui', 'Tưới nước, nhổ cỏ, không giẫm lên cây', 'Chặt phá cây bừa bãi', 'Vặt trụi hết hoa'), ans: 'B',
      why: 'Tưới nước, nhổ cỏ, không bẻ cành là cách chăm sóc và bảo vệ cây.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Hành động nào làm hại cây?',
      opts: o4('Tưới nước cho cây', 'Bón phân cho cây', 'Bẻ cành, khắc tên lên thân cây', 'Nhặt lá khô cho gốc sạch'), ans: 'C',
      why: 'Bẻ cành, khắc lên thân làm cây bị thương, dễ chết.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Hoa của cây thường dùng để làm gì?',
      opts: o4('Trang trí cho đẹp, một số kết thành quả', 'Để đun bếp', 'Để lau nhà', 'Để làm giày dép'), ans: 'A',
      why: 'Hoa làm cảnh cho đẹp; nhiều loài hoa sau đó kết thành quả.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Cây lúa cho ta sản phẩm chính là gì?',
      opts: o4('Hạt gạo (để nấu cơm)', 'Quả táo', 'Củ khoai', 'Bắp ngô'), ans: 'A',
      why: 'Cây lúa cho hạt thóc, xay ra gạo để nấu cơm ăn.' },
  ],
},

/* ═══════════ ĐỀ 6 — ĐỘNG VẬT QUANH EM ═══════════ */
{
  id: 5106, title: 'Đề 6 · Các con vật quanh em', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào thường được nuôi để trông nhà?',
      opts: o4('Con chó', 'Con cá', 'Con bướm', 'Con ong'), ans: 'A',
      why: 'Chó được nuôi để trông nhà, giữ nhà.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào thường bắt chuột?',
      opts: o4('Con mèo', 'Con gà', 'Con vịt', 'Con trâu'), ans: 'A',
      why: 'Mèo bắt chuột giúp bảo vệ thóc gạo.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con vật nào cho ta trứng?',
      opts: o4('Con gà', 'Con chó', 'Con mèo', 'Con voi'), ans: 'A',
      why: 'Gà (và vịt) đẻ trứng cho ta ăn.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con vật nào cho ta sữa để uống?',
      opts: o4('Con bò', 'Con gà', 'Con cá', 'Con chim'), ans: 'A',
      why: 'Bò (và dê) cho sữa để uống và làm sữa chua, pho mát.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào sống dưới nước, dùng vây để bơi?',
      opts: o4('Con cá', 'Con gà', 'Con mèo', 'Con chó'), ans: 'A',
      why: 'Cá sống dưới nước, bơi bằng vây và đuôi, thở bằng mang.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con vật nào có cánh và biết bay?',
      opts: o4('Con chim', 'Con trâu', 'Con lợn', 'Con rùa'), ans: 'A',
      why: 'Chim có cánh và biết bay.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con gà có mấy chân?',
      opts: o4('2 chân', '4 chân', '6 chân', '8 chân'), ans: 'A',
      why: 'Gà, vịt, chim đều có 2 chân.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con trâu, con bò thường giúp nhà nông làm gì?',
      opts: o4('Kéo cày, kéo xe', 'Trông nhà', 'Bắt chuột', 'Gáy báo sáng'), ans: 'A',
      why: 'Trâu, bò khoẻ, giúp nhà nông kéo cày, kéo xe.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Muốn vật nuôi khoẻ mạnh, em nên làm gì?',
      opts: o4('Cho ăn, cho uống, giữ sạch chỗ ở', 'Bỏ đói vật nuôi', 'Đánh đập vật nuôi', 'Nhốt trong chỗ bẩn thỉu'), ans: 'A',
      why: 'Chăm sóc vật nuôi là cho ăn uống đầy đủ và giữ chỗ ở sạch sẽ.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Việc nào KHÔNG nên làm với các con vật?',
      opts: o4('Cho con vật ăn', 'Ném đá, đánh đập con vật', 'Vuốt ve nhẹ nhàng', 'Dọn chuồng sạch sẽ'), ans: 'B',
      why: 'Không được ném đá, đánh đập; phải đối xử nhẹ nhàng với con vật.' },
  ],
},

/* ═══════════ ĐỀ 7 — CƠ THỂ VÀ CÁC GIÁC QUAN ═══════════ */
{
  id: 5107, title: 'Đề 7 · Cơ thể em và năm giác quan', time: 15,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Em dùng bộ phận nào để nhìn?',
      opts: o4('Mắt', 'Tai', 'Mũi', 'Chân'), ans: 'A',
      why: 'Mắt là cơ quan để nhìn (thị giác).' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Em dùng bộ phận nào để nghe?',
      opts: o4('Mắt', 'Tai', 'Lưỡi', 'Tay'), ans: 'B',
      why: 'Tai là cơ quan để nghe (thính giác).' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Em dùng bộ phận nào để ngửi mùi?',
      opts: o4('Mũi', 'Tai', 'Chân', 'Mắt'), ans: 'A',
      why: 'Mũi dùng để ngửi (khứu giác) và để thở.' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Em dùng bộ phận nào để nếm biết vị ngọt, mặn?',
      opts: o4('Lưỡi', 'Tai', 'Mắt', 'Tay'), ans: 'A',
      why: 'Lưỡi giúp nếm và nhận biết vị (vị giác).' },
    { sec: 'Cơ thể', name: 'Câu 5', pts: 1,
      text: 'Em dùng bộ phận nào để cầm, nắm đồ vật?',
      opts: o4('Chân', 'Tay', 'Tai', 'Mũi'), ans: 'B',
      why: 'Tay dùng để cầm, nắm, viết, xúc cơm...' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Em dùng bộ phận nào để đi lại, chạy nhảy?',
      opts: o4('Tay', 'Chân', 'Mắt', 'Lưỡi'), ans: 'B',
      why: 'Chân dùng để đứng, đi, chạy và nhảy.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Bình thường một người có mấy bàn tay?',
      opts: o4('1 bàn tay', '2 bàn tay', '3 bàn tay', '4 bàn tay'), ans: 'B',
      why: 'Cơ thể có 2 tay và 2 chân.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Khi chạm tay vào nước, em biết nước nóng hay lạnh là nhờ đâu?',
      opts: o4('Nhờ da (làn da)', 'Nhờ tóc', 'Nhờ móng tay', 'Nhờ răng'), ans: 'A',
      why: 'Da giúp cảm nhận nóng, lạnh, đau (xúc giác).' },
    { sec: 'Cơ thể', name: 'Câu 9', pts: 1,
      text: 'Răng của em dùng để làm gì?',
      opts: o4('Để nghe', 'Để nhìn', 'Để cắn và nhai thức ăn', 'Để đi lại'), ans: 'C',
      why: 'Răng dùng để cắn, nhai nhỏ thức ăn.' },
    { sec: 'Cơ thể', name: 'Câu 10', pts: 1,
      text: 'Con người có mấy giác quan chính (nhìn, nghe, ngửi, nếm, sờ)?',
      opts: o4('3', '4', '5', '6'), ans: 'C',
      why: 'Có 5 giác quan: thị giác, thính giác, khứu giác, vị giác và xúc giác.' },
  ],
},

/* ═══════════ ĐỀ 8 — GIỮ GÌN SỨC KHOẺ ═══════════ */
{
  id: 5108, title: 'Đề 8 · Ăn uống, vệ sinh và nghỉ ngơi', time: 15,
  questions: [
    { sec: 'Sức khoẻ', name: 'Câu 1', pts: 1,
      text: 'Trước khi ăn cơm và sau khi đi vệ sinh, em cần làm gì?',
      opts: o4('Rửa tay sạch', 'Chạy đi chơi', 'Xem ti vi', 'Đi ngủ'), ans: 'A',
      why: 'Rửa tay bằng xà phòng giúp em không bị đau bụng, mắc bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 2', pts: 1,
      text: 'Mỗi ngày em nên đánh răng mấy lần?',
      opts: o4('Không cần đánh răng', 'Ít nhất 2 lần (sáng và tối)', 'Một tuần một lần', 'Một tháng một lần'), ans: 'B',
      why: 'Đánh răng buổi sáng và trước khi đi ngủ giúp răng chắc khoẻ, không sâu.' },
    { sec: 'Sức khoẻ', name: 'Câu 3', pts: 1,
      text: 'Để bảo vệ mắt khi xem ti vi, em nên làm gì?',
      opts: o4('Ngồi thật gần màn hình', 'Ngồi cách xa vừa đủ, đủ ánh sáng', 'Xem trong bóng tối', 'Xem suốt cả ngày'), ans: 'B',
      why: 'Ngồi xa vừa phải, đủ ánh sáng và không xem quá lâu để mắt không bị mỏi, cận.' },
    { sec: 'Sức khoẻ', name: 'Câu 4', pts: 1,
      text: 'Ăn uống đủ chất (cơm, thịt, cá, rau, quả) giúp em thế nào?',
      opts: o4('Khoẻ mạnh, mau lớn', 'Hay bị ốm', 'Không lớn được', 'Buồn ngủ cả ngày'), ans: 'A',
      why: 'Ăn đủ chất giúp cơ thể khoẻ mạnh và lớn nhanh.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Buổi tối, để hôm sau tỉnh táo học tập, em nên làm gì?',
      opts: o4('Thức khuya xem điện thoại', 'Đi ngủ đúng giờ, ngủ đủ giấc', 'Chơi suốt đêm', 'Ăn thật nhiều bánh kẹo'), ans: 'B',
      why: 'Ngủ đủ và đúng giờ giúp cơ thể khoẻ và tỉnh táo.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Nước nào uống vào là an toàn nhất?',
      opts: o4('Nước ao, nước mương', 'Nước đun sôi để nguội (nước sạch)', 'Nước cống', 'Nước mưa hứng dưới đất'), ans: 'B',
      why: 'Nên uống nước sạch, nước đun sôi để nguội để không bị bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Ăn nhiều bánh kẹo ngọt mà lười đánh răng dễ bị gì?',
      opts: o4('Sâu răng, đau răng', 'Cao lớn hơn', 'Mắt sáng hơn', 'Chạy nhanh hơn'), ans: 'A',
      why: 'Đồ ngọt bám vào răng, không đánh răng sẽ gây sâu răng.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Móng tay dài và bẩn thì em nên làm gì?',
      opts: o4('Để cho thật dài', 'Cắt ngắn và rửa tay sạch', 'Dùng để cào bạn', 'Không cần quan tâm'), ans: 'B',
      why: 'Móng tay bẩn chứa vi trùng; cần cắt ngắn và rửa tay sạch.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp cơ thể sạch sẽ, thơm tho?',
      opts: o4('Tắm gội, thay quần áo sạch', 'Mặc mãi một bộ đồ bẩn', 'Không bao giờ tắm', 'Lăn lê dưới đất bẩn'), ans: 'A',
      why: 'Tắm gội và mặc quần áo sạch giúp cơ thể sạch và khoẻ.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Để cơ thể khoẻ mạnh, ngoài ăn ngủ tốt em còn nên làm gì?',
      opts: o4('Tập thể dục, vận động', 'Ngồi im cả ngày', 'Nhịn ăn để gầy', 'Thức khuya thật nhiều'), ans: 'A',
      why: 'Tập thể dục và vận động giúp cơ thể dẻo dai, khoẻ mạnh.' },
  ],
},

/* ═══════════ ĐỀ 9 — TRÁI ĐẤT VÀ BẦU TRỜI ═══════════ */
{
  id: 5109, title: 'Đề 9 · Bầu trời và thời tiết', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Ban ngày, trên bầu trời ta thường thấy gì toả sáng?',
      opts: o4('Mặt Trời', 'Mặt Trăng', 'Ngôi sao', 'Bóng đèn'), ans: 'A',
      why: 'Ban ngày Mặt Trời chiếu sáng khắp nơi.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Ban đêm, trên bầu trời ta thường thấy gì?',
      opts: o4('Mặt Trời chói chang', 'Mặt Trăng và các ngôi sao', 'Cầu vồng', 'Bông hoa'), ans: 'B',
      why: 'Ban đêm ta nhìn thấy Mặt Trăng và các ngôi sao.' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Mặt Trời đem lại cho Trái Đất điều gì?',
      opts: o4('Ánh sáng và hơi ấm', 'Bóng tối và giá lạnh', 'Mưa đá', 'Tiếng ồn'), ans: 'A',
      why: 'Mặt Trời cho ánh sáng và hơi ấm để cây cối, con người sống được.' },
    { sec: 'Thời tiết', name: 'Câu 4', pts: 1,
      text: 'Khi trời mưa, ra ngoài em cần mang theo gì?',
      opts: o4('Áo mưa hoặc ô (dù)', 'Cái quạt', 'Kính râm', 'Đôi dép lê'), ans: 'A',
      why: 'Trời mưa cần áo mưa hoặc ô để khỏi bị ướt, cảm lạnh.' },
    { sec: 'Thời tiết', name: 'Câu 5', pts: 1,
      text: 'Trời nắng to, ra đường em nên làm gì?',
      opts: o4('Đội mũ (nón), che nắng', 'Cởi hết áo ra', 'Nhìn thẳng vào Mặt Trời', 'Không cần che gì'), ans: 'A',
      why: 'Nắng to nên đội mũ, che nắng và không nhìn thẳng vào Mặt Trời.' },
    { sec: 'Thời tiết', name: 'Câu 6', pts: 1,
      text: 'Trời lạnh (mùa đông), em nên ăn mặc thế nào?',
      opts: o4('Mặc áo mỏng manh', 'Mặc áo ấm, quàng khăn', 'Cởi trần', 'Đi chân đất ngoài trời rét'), ans: 'B',
      why: 'Trời lạnh phải mặc ấm để không bị cảm.' },
    { sec: 'Thời tiết', name: 'Câu 7', pts: 1,
      text: 'Bầu trời nhiều mây đen, gió mạnh thường báo hiệu điều gì sắp tới?',
      opts: o4('Sắp có mưa (hoặc bão)', 'Trời sắp nắng đẹp', 'Sắp có cầu vồng', 'Không có gì thay đổi'), ans: 'A',
      why: 'Mây đen kéo đến, gió mạnh thường là dấu hiệu sắp mưa hoặc bão.' },
    { sec: 'Thời tiết', name: 'Câu 8', pts: 1,
      text: 'Cầu vồng nhiều màu thường xuất hiện khi nào?',
      opts: o4('Vào lúc nửa đêm', 'Sau cơn mưa, khi có nắng', 'Khi trời tối đen', 'Khi có tuyết rơi'), ans: 'B',
      why: 'Cầu vồng thường hiện ra sau cơn mưa, khi Mặt Trời chiếu qua các hạt nước.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Buổi sáng, Mặt Trời mọc lên ở hướng nào?',
      opts: o4('Hướng đông', 'Hướng tây', 'Ngay trên đỉnh đầu', 'Dưới lòng đất'), ans: 'A',
      why: 'Mặt Trời mọc ở hướng đông vào buổi sáng và lặn ở hướng tây vào buổi chiều.' },
    { sec: 'Thời tiết', name: 'Câu 10', pts: 1,
      text: 'Cách nào giúp em biết hôm nay thời tiết thế nào để chuẩn bị?',
      opts: o4('Nhắm mắt đoán bừa', 'Xem, nghe bản tin dự báo thời tiết', 'Hỏi con mèo', 'Không cần biết'), ans: 'B',
      why: 'Nghe, xem dự báo thời tiết giúp em biết nắng, mưa mà chuẩn bị áo mưa, mũ...' },
  ],
},

/* ═══════════ ĐỀ 10 — ÔN TẬP TỔNG HỢP ═══════════ */
{
  id: 5110, title: 'Đề 10 · Ôn tập tổng hợp', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Bố mẹ của mẹ em, em gọi là gì?',
      opts: o4('Ông bà nội', 'Ông bà ngoại', 'Cô chú', 'Bạn bè'), ans: 'B',
      why: 'Bố mẹ của mẹ là ông ngoại, bà ngoại.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Vật nào trẻ em tuyệt đối không được lấy chơi?',
      opts: o4('Gấu bông', 'Bút màu', 'Diêm, bật lửa, dao', 'Quả bóng'), ans: 'C',
      why: 'Diêm, bật lửa, dao gây bỏng và đứt tay nên không được nghịch.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Gặp đèn giao thông màu đỏ, người và xe phải làm gì?',
      opts: o4('Dừng lại', 'Đi tiếp', 'Chạy nhanh hơn', 'Rẽ trái'), ans: 'A',
      why: 'Đèn đỏ phải dừng lại để đảm bảo an toàn.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Bộ phận nào của cây hút nước từ đất lên nuôi cây?',
      opts: o4('Lá', 'Hoa', 'Quả', 'Rễ'), ans: 'D',
      why: 'Rễ cây hút nước và chất dinh dưỡng từ đất.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào cho ta trứng để ăn?',
      opts: o4('Con gà', 'Con chó', 'Con mèo', 'Con voi'), ans: 'A',
      why: 'Gà, vịt đẻ trứng cho ta ăn.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Em nghe được tiếng nói nhờ bộ phận nào?',
      opts: o4('Mắt', 'Tai', 'Mũi', 'Chân'), ans: 'B',
      why: 'Tai là cơ quan để nghe.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Việc nào nên làm trước khi ăn cơm?',
      opts: o4('Rửa tay sạch', 'Chơi đất cát', 'Vuốt ve con mèo', 'Không làm gì'), ans: 'A',
      why: 'Rửa tay trước khi ăn để tránh vi trùng gây bệnh.' },
    { sec: 'Bầu trời', name: 'Câu 8', pts: 1,
      text: 'Ban đêm, trên trời ta nhìn thấy gì?',
      opts: o4('Mặt Trời', 'Mặt Trăng và các vì sao', 'Cầu vồng', 'Máy bay giấy'), ans: 'B',
      why: 'Ban đêm ta thấy Mặt Trăng và các ngôi sao.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Ở trường, ai là người dạy dỗ em?',
      opts: o4('Thầy, cô giáo', 'Người lạ ngoài đường', 'Chú tài xế', 'Bác nông dân'), ans: 'A',
      why: 'Thầy cô giáo là người dạy dỗ em ở trường.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Để giữ nơi mình sống sạch đẹp, em nên làm gì?',
      opts: o4('Bỏ rác đúng nơi quy định', 'Vứt rác xuống ao hồ', 'Bẻ cây nơi công cộng', 'Vẽ bậy lên tường'), ans: 'A',
      why: 'Bỏ rác đúng chỗ giúp làng xóm, phố phường luôn sạch đẹp.' },
  ],
},

];

SUBJECTS.push({
  id: 'tnxh1', name: 'Tự nhiên & Xã hội', short: 'TN&XH 1', icon: '🌍', grade: 1,
  exams: TNXH1_EXAMS, ready: true,
  heroTitle: 'Tự nhiên và Xã hội lớp 1 — gia đình, trường học, cây cối, con vật, cơ thể và bầu trời',
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 15 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
