// TỰ NHIÊN VÀ XÃ HỘI — LỚP 1 (GDPT 2018)
// 30 đề × 10 câu = 300 câu. Mỗi câu 1 điểm — thang 10 — 15 phút mỗi đề.
//
// Bám 6 chủ đề của chương trình TNXH lớp 1:
//   1. Gia đình            2. Trường học
//   3. Cộng đồng địa phương 4. Thực vật và động vật
//   5. Con người và sức khoẻ 6. Trái Đất và bầu trời
//
// Mức độ: nhận biết – hiểu, phù hợp học sinh 6 tuổi; câu hỏi ngắn, gần gũi đời sống.
// Trường `why` giải thích ngắn để phụ huynh/bé cùng đọc lại sau khi làm.

const TNXH1_EXAMS = [

/* ═══════════ ĐỀ 1 — GIA ĐÌNH CỦA EM ═══════════ */
{
  id: 5101, title: 'Đề 1 · Gia đình của em', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Gia đình thường có những ai?',
      opts: o4('Chỉ có mình em', 'Ông bà, bố mẹ, anh chị em', 'Chỉ có các bạn cùng lớp', 'Chỉ có cô giáo'), ans: 'B',
      why: 'Gia đình là những người thân sống cùng nhau: ông bà, bố mẹ, anh chị em.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Người sinh ra bố của em, em gọi là gì?',
      opts: o4('Ông bà ngoại', 'Cô, dì', 'Ông bà nội', 'Bác hàng xóm'), ans: 'C',
      why: 'Bố mẹ của bố là ông nội, bà nội.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Người sinh ra mẹ của em, em gọi là gì?',
      opts: o4('Ông bà nội', 'Ông bà ngoại', 'Chú, thím', 'Anh, chị'), ans: 'B',
      why: 'Bố mẹ của mẹ là ông ngoại, bà ngoại.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Em gái của mẹ em, em gọi là gì?',
      opts: o4('Dì', 'Bác trai', 'Ông', 'Anh'), ans: 'A',
      why: 'Em gái của mẹ được gọi là dì.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Ngày nghỉ, gia đình em thường làm gì cùng nhau?',
      opts: o4('Mỗi người đi một nơi, không gặp nhau', 'Cùng ăn cơm, trò chuyện, đi chơi', 'Không ai nói với ai', 'Cãi nhau cả ngày'), ans: 'B',
      why: 'Ngày nghỉ là dịp cả nhà quây quần: cùng ăn cơm, trò chuyện, đi chơi.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Việc nào cho thấy em biết yêu thương ông bà?',
      opts: o4('Lấy nước, bóp vai cho ông bà', 'Không chào hỏi ông bà', 'Giành đồ ăn của ông bà', 'Cãi lời ông bà'), ans: 'A',
      why: 'Rót nước, bóp vai, hỏi han là những việc nhỏ thể hiện lòng yêu thương ông bà.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Khi ông (bà) bị ốm, em nên làm gì?',
      opts: o4('Chạy đi chơi thật xa', 'Hỏi thăm và chăm sóc ông bà', 'La hét thật to', 'Mặc kệ ông bà'), ans: 'B',
      why: 'Người thân ốm thì em nên hỏi thăm, chăm sóc, giữ yên lặng cho ông bà nghỉ.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Anh, chị, em trong nhà nên đối xử với nhau thế nào?',
      opts: o4('Tranh giành đồ chơi', 'Đánh nhau mỗi ngày', 'Nhường nhịn, thương yêu nhau', 'Không chơi cùng nhau'), ans: 'C',
      why: 'Anh chị em một nhà thì phải nhường nhịn, thương yêu nhau.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Việc nhà nào một bạn lớp 1 có thể giúp bố mẹ?',
      opts: o4('Nấu một nồi canh to', 'Sửa xe máy', 'Gấp quần áo, cất dép gọn gàng', 'Lái ô tô'), ans: 'C',
      why: 'Bé có thể làm việc vừa sức: gấp quần áo, cất dép, quét nhà cùng bố mẹ.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Nhà là nơi để làm gì?',
      opts: o4('Chỉ để chứa đồ', 'Để cả nhà cùng ở, nghỉ ngơi và yêu thương nhau', 'Để không ai vào', 'Để nuôi thú dữ'), ans: 'B',
      why: 'Ngôi nhà là nơi các thành viên cùng chung sống, nghỉ ngơi và yêu thương nhau.' },
  ],
},

/* ═══════════ ĐỀ 2 — NGÔI NHÀ, ĐỒ DÙNG VÀ AN TOÀN Ở NHÀ ═══════════ */
{
  id: 5102, title: 'Đề 2 · Ngôi nhà và an toàn khi ở nhà', time: 15,
  questions: [
    { sec: 'Nhà ở', name: 'Câu 1', pts: 1,
      text: 'Phòng dùng để nấu ăn trong nhà gọi là gì?',
      opts: o4('Phòng ngủ', 'Phòng bếp', 'Phòng khách', 'Nhà tắm'), ans: 'B',
      why: 'Nơi có bếp, nồi, xoong để nấu ăn là phòng bếp.' },
    { sec: 'Nhà ở', name: 'Câu 2', pts: 1,
      text: 'Đồ dùng nào dùng để quét nhà?',
      opts: o4('Cái chổi', 'Cái nồi', 'Cái quạt', 'Cái ti vi'), ans: 'A',
      why: 'Chổi dùng để quét cho nhà sạch sẽ.' },
    { sec: 'Nhà ở', name: 'Câu 3', pts: 1,
      text: 'Đồ dùng nào giúp làm mát vào ngày nóng?',
      opts: o4('Cái chăn bông', 'Cái quạt', 'Đôi giày', 'Quyển vở'), ans: 'B',
      why: 'Quạt (hoặc điều hoà) giúp làm mát khi trời nóng.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Vật nào nguy hiểm, trẻ em không được lấy ra chơi?',
      opts: o4('Con gấu bông', 'Quả bóng nhựa', 'Bao diêm, bật lửa', 'Bút màu'), ans: 'C',
      why: 'Diêm và bật lửa có thể gây bỏng, cháy nên trẻ em không được nghịch.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Vì sao không được cho tay hay que vào ổ cắm điện?',
      opts: o4('Vì sẽ bị điện giật rất nguy hiểm', 'Vì ổ điện bẩn', 'Vì làm hỏng tay áo', 'Vì ổ điện kêu to'), ans: 'A',
      why: 'Chọc vào ổ điện có thể bị điện giật, rất nguy hiểm đến tính mạng.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Thấy phích nước sôi (nước nóng) trên bàn, em nên làm gì?',
      opts: o4('Sờ thử xem nóng không', 'Tránh xa, không nghịch', 'Đổ ra sàn chơi', 'Mang đi giấu'), ans: 'B',
      why: 'Nước sôi gây bỏng nặng, em phải tránh xa và không tự rót.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Đồ vật nào dưới đây sắc nhọn, dễ gây đứt tay?',
      opts: o4('Cái gối', 'Con dao', 'Cái khăn mặt', 'Quả bóng'), ans: 'B',
      why: 'Dao, kéo là vật sắc nhọn; khi dùng phải có người lớn và cầm cẩn thận.' },
    { sec: 'Nhà ở', name: 'Câu 8', pts: 1,
      text: 'Chơi xong, em nên làm gì với đồ chơi?',
      opts: o4('Vứt khắp nhà', 'Cất gọn vào đúng chỗ', 'Ném ra ngoài sân', 'Giấu đi cho bẩn'), ans: 'B',
      why: 'Chơi xong phải cất đồ gọn gàng để nhà sạch và khỏi vấp ngã.' },
    { sec: 'Nhà ở', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp giữ nhà cửa sạch sẽ?',
      opts: o4('Vẽ bẩn lên tường', 'Quét nhà, lau bàn, đổ rác đúng chỗ', 'Để rác khắp nơi', 'Không bao giờ dọn'), ans: 'B',
      why: 'Quét nhà, lau bàn, đổ rác đúng nơi giúp nhà luôn sạch.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Khi ở nhà một mình có người lạ gõ cửa, em nên làm gì?',
      opts: o4('Mở cửa cho người lạ vào ngay', 'Không mở cửa và gọi điện cho bố mẹ', 'Đi theo người lạ', 'Cho người lạ tiền'), ans: 'B',
      why: 'Không tự mở cửa cho người lạ; nên gọi báo bố mẹ hoặc người thân.' },
  ],
},

/* ═══════════ ĐỀ 3 — TRƯỜNG HỌC CỦA EM ═══════════ */
{
  id: 5103, title: 'Đề 3 · Trường học của em', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Ở trường, người dạy em học chữ, học toán là ai?',
      opts: o4('Bác bảo vệ', 'Thầy, cô giáo', 'Bạn cùng lớp', 'Chú lái xe'), ans: 'B',
      why: 'Thầy giáo, cô giáo là người dạy dỗ em ở trường.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Những bạn học cùng lớp với em gọi là gì?',
      opts: o4('Bạn cùng lớp', 'Người lạ', 'Hàng xóm', 'Khách'), ans: 'A',
      why: 'Các bạn học chung một lớp là bạn cùng lớp của em.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Đồ dùng nào là đồ dùng học tập?',
      opts: o4('Nồi cơm điện', 'Bút, sách, vở', 'Cái chổi', 'Con dao'), ans: 'B',
      why: 'Bút, sách, vở, cặp là đồ dùng học tập của em.' },
    { sec: 'Trường học', name: 'Câu 4', pts: 1,
      text: 'Nơi các bạn chạy nhảy, vui chơi trong giờ ra chơi là ở đâu?',
      opts: o4('Sân trường', 'Trên mái nhà', 'Ngoài đường lớn', 'Trong nhà bếp'), ans: 'A',
      why: 'Giờ ra chơi, học sinh chơi ở sân trường cho an toàn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Trò chơi nào an toàn khi chơi ở sân trường?',
      opts: o4('Leo lên tường cao', 'Ném đá vào bạn', 'Nhảy dây, chơi ô ăn quan', 'Xô đẩy nhau ở cầu thang'), ans: 'C',
      why: 'Nhảy dây, ô ăn quan là trò an toàn; leo cao, ném đá, xô đẩy dễ gây tai nạn.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Khi lên xuống cầu thang, em nên đi thế nào?',
      opts: o4('Chạy thật nhanh', 'Xô đẩy bạn', 'Đi từ tốn, bám tay vịn, đi bên phải', 'Nhảy hai bậc một'), ans: 'C',
      why: 'Đi chậm, bám tay vịn và đi bên phải để không bị ngã.' },
    { sec: 'Trường học', name: 'Câu 7', pts: 1,
      text: 'Thấy bạn bị ngã ở sân trường, em nên làm gì?',
      opts: o4('Cười chê bạn', 'Đỡ bạn dậy và báo cho thầy cô', 'Bỏ đi chỗ khác', 'Đẩy thêm cho bạn ngã'), ans: 'B',
      why: 'Em nên giúp đỡ bạn dậy và báo thầy cô nếu bạn bị đau.' },
    { sec: 'Trường học', name: 'Câu 8', pts: 1,
      text: 'Để giữ lớp học sạch sẽ, em nên làm gì?',
      opts: o4('Vứt rác ra sàn lớp', 'Bỏ rác vào thùng rác', 'Vẽ bậy lên bàn', 'Bôi bẩn lên tường'), ans: 'B',
      why: 'Bỏ rác đúng thùng, không vẽ bậy giúp lớp luôn sạch đẹp.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Khi cô giáo đang giảng bài, em nên làm gì?',
      opts: o4('Nói chuyện riêng thật to', 'Chú ý lắng nghe', 'Ngủ gật', 'Chạy ra khỏi lớp'), ans: 'B',
      why: 'Chú ý lắng nghe cô giảng thì em mới hiểu bài.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Bác bảo vệ ở trường làm công việc gì?',
      opts: o4('Dạy em học hát', 'Nấu ăn cho cả lớp', 'Trông coi, giữ an toàn cho trường', 'Bán quần áo'), ans: 'C',
      why: 'Bác bảo vệ trông coi trường, giữ an toàn cho học sinh.' },
  ],
},

/* ═══════════ ĐỀ 4 — CỘNG ĐỒNG VÀ AN TOÀN GIAO THÔNG ═══════════ */
{
  id: 5104, title: 'Đề 4 · Nơi em sống và an toàn giao thông', time: 15,
  questions: [
    { sec: 'Cộng đồng', name: 'Câu 1', pts: 1,
      text: 'Nơi mọi người đến mua bán rau, thịt, cá, đồ dùng gọi là gì?',
      opts: o4('Bệnh viện', 'Chợ (hoặc siêu thị)', 'Trường học', 'Bưu điện'), ans: 'B',
      why: 'Chợ và siêu thị là nơi mua bán hàng hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 2', pts: 1,
      text: 'Khi bị ốm, em được đưa đến đâu để khám bệnh?',
      opts: o4('Bệnh viện hoặc trạm y tế', 'Rạp chiếu phim', 'Sân bóng', 'Cửa hàng bánh'), ans: 'A',
      why: 'Bệnh viện, trạm y tế là nơi khám và chữa bệnh.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Người khám và chữa bệnh cho em gọi là gì?',
      opts: o4('Chú công an', 'Bác nông dân', 'Bác sĩ', 'Cô bán hàng'), ans: 'C',
      why: 'Bác sĩ là người khám bệnh, chữa bệnh cho mọi người.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Đèn giao thông màu ĐỎ báo hiệu điều gì?',
      opts: o4('Được đi tiếp', 'Dừng lại', 'Đi thật nhanh', 'Rẽ phải'), ans: 'B',
      why: 'Đèn đỏ nghĩa là dừng lại.' },
    { sec: 'Giao thông', name: 'Câu 5', pts: 1,
      text: 'Đèn giao thông màu XANH báo hiệu điều gì?',
      opts: o4('Dừng lại', 'Được đi', 'Lùi lại', 'Đứng im mãi mãi'), ans: 'B',
      why: 'Đèn xanh nghĩa là được phép đi.' },
    { sec: 'Giao thông', name: 'Câu 6', pts: 1,
      text: 'Người đi bộ nên đi ở phần đường nào?',
      opts: o4('Giữa lòng đường', 'Trên vỉa hè (lề đường)', 'Chỗ nào cũng được', 'Ngay trước đầu ô tô'), ans: 'B',
      why: 'Người đi bộ đi trên vỉa hè; nơi không có vỉa hè thì đi sát lề bên phải.' },
    { sec: 'Giao thông', name: 'Câu 7', pts: 1,
      text: 'Khi muốn qua đường, em nên làm gì?',
      opts: o4('Chạy nhanh qua giữa dòng xe', 'Đi theo vạch kẻ, nắm tay người lớn, nhìn hai phía', 'Nhắm mắt băng qua', 'Qua đường lúc đèn đỏ dành cho người đi bộ'), ans: 'B',
      why: 'Qua đường phải đi đúng vạch, quan sát hai bên và nắm tay người lớn.' },
    { sec: 'Giao thông', name: 'Câu 8', pts: 1,
      text: 'Khi ngồi trên xe máy, em phải làm gì để an toàn?',
      opts: o4('Đội mũ bảo hiểm', 'Đứng lên xe', 'Thả hai tay', 'Quay ngang quay ngửa'), ans: 'A',
      why: 'Ngồi xe máy phải đội mũ bảo hiểm và ngồi yên, bám chắc.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Chú công an giao thông làm nhiệm vụ gì?',
      opts: o4('Trồng lúa', 'Điều khiển, giữ trật tự giao thông', 'Dạy học', 'Bán vé xem phim'), ans: 'B',
      why: 'Công an giao thông điều khiển và giữ trật tự cho đường phố an toàn.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp làng xóm, phố phường sạch đẹp?',
      opts: o4('Vứt rác xuống ao hồ', 'Bỏ rác đúng nơi, trồng và chăm cây', 'Bẻ cành hái hoa nơi công cộng', 'Vẽ bậy lên tường'), ans: 'B',
      why: 'Bỏ rác đúng chỗ và trồng cây làm nơi mình sống sạch, đẹp.' },
  ],
},

/* ═══════════ ĐỀ 5 — THỰC VẬT QUANH EM ═══════════ */
{
  id: 5105, title: 'Đề 5 · Cây cối quanh em', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Một cây thường có các bộ phận nào?',
      opts: o4('Chỉ có lá', 'Rễ, thân, lá (nhiều cây có hoa, quả)', 'Chỉ có hoa', 'Chỉ có rễ'), ans: 'B',
      why: 'Cây thường gồm rễ, thân, lá; nhiều cây còn có hoa và quả.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Bộ phận nào của cây nằm dưới đất, hút nước và chất nuôi cây?',
      opts: o4('Lá', 'Hoa', 'Rễ', 'Quả'), ans: 'C',
      why: 'Rễ cây cắm xuống đất để hút nước và chất dinh dưỡng nuôi cây.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Cây nào sau đây cho ta quả để ăn?',
      opts: o4('Cây cam', 'Cây cột điện', 'Cỏ dại', 'Cây nhựa trang trí'), ans: 'A',
      why: 'Cây cam là cây ăn quả, cho quả cam để ăn.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Rau muống, rau cải là loại cây gì?',
      opts: o4('Cây lấy gỗ', 'Cây rau (làm thức ăn)', 'Cây hoa', 'Cây bóng mát'), ans: 'B',
      why: 'Rau muống, rau cải là cây rau, dùng làm thức ăn hằng ngày.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Muốn cây sống và lớn lên, ta cần làm gì?',
      opts: o4('Tưới nước, cho cây có ánh sáng', 'Đổ dầu ăn lên cây', 'Nhổ hết rễ đi', 'Để cây trong bóng tối kín'), ans: 'A',
      why: 'Cây cần nước, ánh sáng và không khí mới sống và lớn được.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Cây xanh mang lại lợi ích nào cho con người?',
      opts: o4('Làm không khí bẩn hơn', 'Cho bóng mát, quả, gỗ và không khí trong lành', 'Không có ích gì', 'Làm nắng nóng hơn'), ans: 'B',
      why: 'Cây cho bóng mát, quả, gỗ và giúp không khí trong lành.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Việc nào là chăm sóc, bảo vệ cây?',
      opts: o4('Bẻ cành, ngắt lá cho vui', 'Tưới nước, nhổ cỏ, không giẫm lên cây', 'Chặt phá cây bừa bãi', 'Vặt trụi hết hoa'), ans: 'B',
      why: 'Tưới nước, nhổ cỏ, không bẻ cành là cách chăm sóc và bảo vệ cây.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Hành động nào làm hại cây?',
      opts: o4('Tưới nước cho cây', 'Bón phân cho cây', 'Bẻ cành, khắc tên lên thân cây', 'Nhặt lá khô cho gốc sạch'), ans: 'C',
      why: 'Bẻ cành, khắc lên thân làm cây bị thương, dễ chết.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Hoa của cây thường dùng để làm gì?',
      opts: o4('Trang trí cho đẹp, một số kết thành quả', 'Để đun bếp', 'Để lau nhà', 'Để làm giày dép'), ans: 'A',
      why: 'Hoa làm cảnh cho đẹp; nhiều loài hoa sau đó kết thành quả.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Cây lúa cho ta sản phẩm chính là gì?',
      opts: o4('Hạt gạo (để nấu cơm)', 'Quả táo', 'Củ khoai', 'Bắp ngô'), ans: 'A',
      why: 'Cây lúa cho hạt thóc, xay ra gạo để nấu cơm ăn.' },
  ],
},

/* ═══════════ ĐỀ 6 — ĐỘNG VẬT QUANH EM ═══════════ */
{
  id: 5106, title: 'Đề 6 · Các con vật quanh em', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào thường được nuôi để trông nhà?',
      opts: o4('Con chó', 'Con cá', 'Con bướm', 'Con ong'), ans: 'A',
      why: 'Chó được nuôi để trông nhà, giữ nhà.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào thường bắt chuột?',
      opts: o4('Con mèo', 'Con gà', 'Con vịt', 'Con trâu'), ans: 'A',
      why: 'Mèo bắt chuột giúp bảo vệ thóc gạo.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con vật nào cho ta trứng?',
      opts: o4('Con gà', 'Con chó', 'Con mèo', 'Con voi'), ans: 'A',
      why: 'Gà (và vịt) đẻ trứng cho ta ăn.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con vật nào cho ta sữa để uống?',
      opts: o4('Con bò', 'Con gà', 'Con cá', 'Con chim'), ans: 'A',
      why: 'Bò (và dê) cho sữa để uống và làm sữa chua, pho mát.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào sống dưới nước, dùng vây để bơi?',
      opts: o4('Con cá', 'Con gà', 'Con mèo', 'Con chó'), ans: 'A',
      why: 'Cá sống dưới nước, bơi bằng vây và đuôi, thở bằng mang.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con vật nào có cánh và biết bay?',
      opts: o4('Con chim', 'Con trâu', 'Con lợn', 'Con rùa'), ans: 'A',
      why: 'Chim có cánh và biết bay.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con gà có mấy chân?',
      opts: o4('2 chân', '4 chân', '6 chân', '8 chân'), ans: 'A',
      why: 'Gà, vịt, chim đều có 2 chân.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con trâu, con bò thường giúp nhà nông làm gì?',
      opts: o4('Kéo cày, kéo xe', 'Trông nhà', 'Bắt chuột', 'Gáy báo sáng'), ans: 'A',
      why: 'Trâu, bò khoẻ, giúp nhà nông kéo cày, kéo xe.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Muốn vật nuôi khoẻ mạnh, em nên làm gì?',
      opts: o4('Cho ăn, cho uống, giữ sạch chỗ ở', 'Bỏ đói vật nuôi', 'Đánh đập vật nuôi', 'Nhốt trong chỗ bẩn thỉu'), ans: 'A',
      why: 'Chăm sóc vật nuôi là cho ăn uống đầy đủ và giữ chỗ ở sạch sẽ.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Việc nào KHÔNG nên làm với các con vật?',
      opts: o4('Cho con vật ăn', 'Ném đá, đánh đập con vật', 'Vuốt ve nhẹ nhàng', 'Dọn chuồng sạch sẽ'), ans: 'B',
      why: 'Không được ném đá, đánh đập; phải đối xử nhẹ nhàng với con vật.' },
  ],
},

/* ═══════════ ĐỀ 7 — CƠ THỂ VÀ CÁC GIÁC QUAN ═══════════ */
{
  id: 5107, title: 'Đề 7 · Cơ thể em và năm giác quan', time: 15,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Em dùng bộ phận nào để nhìn?',
      opts: o4('Mắt', 'Tai', 'Mũi', 'Chân'), ans: 'A',
      why: 'Mắt là cơ quan để nhìn (thị giác).' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Em dùng bộ phận nào để nghe?',
      opts: o4('Mắt', 'Tai', 'Lưỡi', 'Tay'), ans: 'B',
      why: 'Tai là cơ quan để nghe (thính giác).' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Em dùng bộ phận nào để ngửi mùi?',
      opts: o4('Mũi', 'Tai', 'Chân', 'Mắt'), ans: 'A',
      why: 'Mũi dùng để ngửi (khứu giác) và để thở.' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Em dùng bộ phận nào để nếm biết vị ngọt, mặn?',
      opts: o4('Lưỡi', 'Tai', 'Mắt', 'Tay'), ans: 'A',
      why: 'Lưỡi giúp nếm và nhận biết vị (vị giác).' },
    { sec: 'Cơ thể', name: 'Câu 5', pts: 1,
      text: 'Em dùng bộ phận nào để cầm, nắm đồ vật?',
      opts: o4('Chân', 'Tay', 'Tai', 'Mũi'), ans: 'B',
      why: 'Tay dùng để cầm, nắm, viết, xúc cơm...' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Em dùng bộ phận nào để đi lại, chạy nhảy?',
      opts: o4('Tay', 'Chân', 'Mắt', 'Lưỡi'), ans: 'B',
      why: 'Chân dùng để đứng, đi, chạy và nhảy.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Bình thường một người có mấy bàn tay?',
      opts: o4('1 bàn tay', '2 bàn tay', '3 bàn tay', '4 bàn tay'), ans: 'B',
      why: 'Cơ thể có 2 tay và 2 chân.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Khi chạm tay vào nước, em biết nước nóng hay lạnh là nhờ đâu?',
      opts: o4('Nhờ da (làn da)', 'Nhờ tóc', 'Nhờ móng tay', 'Nhờ răng'), ans: 'A',
      why: 'Da giúp cảm nhận nóng, lạnh, đau (xúc giác).' },
    { sec: 'Cơ thể', name: 'Câu 9', pts: 1,
      text: 'Răng của em dùng để làm gì?',
      opts: o4('Để nghe', 'Để nhìn', 'Để cắn và nhai thức ăn', 'Để đi lại'), ans: 'C',
      why: 'Răng dùng để cắn, nhai nhỏ thức ăn.' },
    { sec: 'Cơ thể', name: 'Câu 10', pts: 1,
      text: 'Con người có mấy giác quan chính (nhìn, nghe, ngửi, nếm, sờ)?',
      opts: o4('3', '4', '5', '6'), ans: 'C',
      why: 'Có 5 giác quan: thị giác, thính giác, khứu giác, vị giác và xúc giác.' },
  ],
},

/* ═══════════ ĐỀ 8 — GIỮ GÌN SỨC KHOẺ ═══════════ */
{
  id: 5108, title: 'Đề 8 · Ăn uống, vệ sinh và nghỉ ngơi', time: 15,
  questions: [
    { sec: 'Sức khoẻ', name: 'Câu 1', pts: 1,
      text: 'Trước khi ăn cơm và sau khi đi vệ sinh, em cần làm gì?',
      opts: o4('Rửa tay sạch', 'Chạy đi chơi', 'Xem ti vi', 'Đi ngủ'), ans: 'A',
      why: 'Rửa tay bằng xà phòng giúp em không bị đau bụng, mắc bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 2', pts: 1,
      text: 'Mỗi ngày em nên đánh răng mấy lần?',
      opts: o4('Không cần đánh răng', 'Ít nhất 2 lần (sáng và tối)', 'Một tuần một lần', 'Một tháng một lần'), ans: 'B',
      why: 'Đánh răng buổi sáng và trước khi đi ngủ giúp răng chắc khoẻ, không sâu.' },
    { sec: 'Sức khoẻ', name: 'Câu 3', pts: 1,
      text: 'Để bảo vệ mắt khi xem ti vi, em nên làm gì?',
      opts: o4('Ngồi thật gần màn hình', 'Ngồi cách xa vừa đủ, đủ ánh sáng', 'Xem trong bóng tối', 'Xem suốt cả ngày'), ans: 'B',
      why: 'Ngồi xa vừa phải, đủ ánh sáng và không xem quá lâu để mắt không bị mỏi, cận.' },
    { sec: 'Sức khoẻ', name: 'Câu 4', pts: 1,
      text: 'Ăn uống đủ chất (cơm, thịt, cá, rau, quả) giúp em thế nào?',
      opts: o4('Khoẻ mạnh, mau lớn', 'Hay bị ốm', 'Không lớn được', 'Buồn ngủ cả ngày'), ans: 'A',
      why: 'Ăn đủ chất giúp cơ thể khoẻ mạnh và lớn nhanh.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Buổi tối, để hôm sau tỉnh táo học tập, em nên làm gì?',
      opts: o4('Thức khuya xem điện thoại', 'Đi ngủ đúng giờ, ngủ đủ giấc', 'Chơi suốt đêm', 'Ăn thật nhiều bánh kẹo'), ans: 'B',
      why: 'Ngủ đủ và đúng giờ giúp cơ thể khoẻ và tỉnh táo.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Nước nào uống vào là an toàn nhất?',
      opts: o4('Nước ao, nước mương', 'Nước đun sôi để nguội (nước sạch)', 'Nước cống', 'Nước mưa hứng dưới đất'), ans: 'B',
      why: 'Nên uống nước sạch, nước đun sôi để nguội để không bị bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Ăn nhiều bánh kẹo ngọt mà lười đánh răng dễ bị gì?',
      opts: o4('Sâu răng, đau răng', 'Cao lớn hơn', 'Mắt sáng hơn', 'Chạy nhanh hơn'), ans: 'A',
      why: 'Đồ ngọt bám vào răng, không đánh răng sẽ gây sâu răng.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Móng tay dài và bẩn thì em nên làm gì?',
      opts: o4('Để cho thật dài', 'Cắt ngắn và rửa tay sạch', 'Dùng để cào bạn', 'Không cần quan tâm'), ans: 'B',
      why: 'Móng tay bẩn chứa vi trùng; cần cắt ngắn và rửa tay sạch.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp cơ thể sạch sẽ, thơm tho?',
      opts: o4('Tắm gội, thay quần áo sạch', 'Mặc mãi một bộ đồ bẩn', 'Không bao giờ tắm', 'Lăn lê dưới đất bẩn'), ans: 'A',
      why: 'Tắm gội và mặc quần áo sạch giúp cơ thể sạch và khoẻ.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Để cơ thể khoẻ mạnh, ngoài ăn ngủ tốt em còn nên làm gì?',
      opts: o4('Tập thể dục, vận động', 'Ngồi im cả ngày', 'Nhịn ăn để gầy', 'Thức khuya thật nhiều'), ans: 'A',
      why: 'Tập thể dục và vận động giúp cơ thể dẻo dai, khoẻ mạnh.' },
  ],
},

/* ═══════════ ĐỀ 9 — TRÁI ĐẤT VÀ BẦU TRỜI ═══════════ */
{
  id: 5109, title: 'Đề 9 · Bầu trời và thời tiết', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Ban ngày, trên bầu trời ta thường thấy gì toả sáng?',
      opts: o4('Mặt Trời', 'Mặt Trăng', 'Ngôi sao', 'Bóng đèn'), ans: 'A',
      why: 'Ban ngày Mặt Trời chiếu sáng khắp nơi.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Ban đêm, trên bầu trời ta thường thấy gì?',
      opts: o4('Mặt Trời chói chang', 'Mặt Trăng và các ngôi sao', 'Cầu vồng', 'Bông hoa'), ans: 'B',
      why: 'Ban đêm ta nhìn thấy Mặt Trăng và các ngôi sao.' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Mặt Trời đem lại cho Trái Đất điều gì?',
      opts: o4('Ánh sáng và hơi ấm', 'Bóng tối và giá lạnh', 'Mưa đá', 'Tiếng ồn'), ans: 'A',
      why: 'Mặt Trời cho ánh sáng và hơi ấm để cây cối, con người sống được.' },
    { sec: 'Thời tiết', name: 'Câu 4', pts: 1,
      text: 'Khi trời mưa, ra ngoài em cần mang theo gì?',
      opts: o4('Áo mưa hoặc ô (dù)', 'Cái quạt', 'Kính râm', 'Đôi dép lê'), ans: 'A',
      why: 'Trời mưa cần áo mưa hoặc ô để khỏi bị ướt, cảm lạnh.' },
    { sec: 'Thời tiết', name: 'Câu 5', pts: 1,
      text: 'Trời nắng to, ra đường em nên làm gì?',
      opts: o4('Đội mũ (nón), che nắng', 'Cởi hết áo ra', 'Nhìn thẳng vào Mặt Trời', 'Không cần che gì'), ans: 'A',
      why: 'Nắng to nên đội mũ, che nắng và không nhìn thẳng vào Mặt Trời.' },
    { sec: 'Thời tiết', name: 'Câu 6', pts: 1,
      text: 'Trời lạnh (mùa đông), em nên ăn mặc thế nào?',
      opts: o4('Mặc áo mỏng manh', 'Mặc áo ấm, quàng khăn', 'Cởi trần', 'Đi chân đất ngoài trời rét'), ans: 'B',
      why: 'Trời lạnh phải mặc ấm để không bị cảm.' },
    { sec: 'Thời tiết', name: 'Câu 7', pts: 1,
      text: 'Bầu trời nhiều mây đen, gió mạnh thường báo hiệu điều gì sắp tới?',
      opts: o4('Sắp có mưa (hoặc bão)', 'Trời sắp nắng đẹp', 'Sắp có cầu vồng', 'Không có gì thay đổi'), ans: 'A',
      why: 'Mây đen kéo đến, gió mạnh thường là dấu hiệu sắp mưa hoặc bão.' },
    { sec: 'Thời tiết', name: 'Câu 8', pts: 1,
      text: 'Cầu vồng nhiều màu thường xuất hiện khi nào?',
      opts: o4('Vào lúc nửa đêm', 'Sau cơn mưa, khi có nắng', 'Khi trời tối đen', 'Khi có tuyết rơi'), ans: 'B',
      why: 'Cầu vồng thường hiện ra sau cơn mưa, khi Mặt Trời chiếu qua các hạt nước.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Buổi sáng, Mặt Trời mọc lên ở hướng nào?',
      opts: o4('Hướng đông', 'Hướng tây', 'Ngay trên đỉnh đầu', 'Dưới lòng đất'), ans: 'A',
      why: 'Mặt Trời mọc ở hướng đông vào buổi sáng và lặn ở hướng tây vào buổi chiều.' },
    { sec: 'Thời tiết', name: 'Câu 10', pts: 1,
      text: 'Cách nào giúp em biết hôm nay thời tiết thế nào để chuẩn bị?',
      opts: o4('Nhắm mắt đoán bừa', 'Xem, nghe bản tin dự báo thời tiết', 'Hỏi con mèo', 'Không cần biết'), ans: 'B',
      why: 'Nghe, xem dự báo thời tiết giúp em biết nắng, mưa mà chuẩn bị áo mưa, mũ...' },
  ],
},

/* ═══════════ ĐỀ 10 — ÔN TẬP TỔNG HỢP ═══════════ */
{
  id: 5110, title: 'Đề 10 · Ôn tập tổng hợp', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Bố mẹ của mẹ em, em gọi là gì?',
      opts: o4('Ông bà nội', 'Ông bà ngoại', 'Cô chú', 'Bạn bè'), ans: 'B',
      why: 'Bố mẹ của mẹ là ông ngoại, bà ngoại.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Vật nào trẻ em tuyệt đối không được lấy chơi?',
      opts: o4('Gấu bông', 'Bút màu', 'Diêm, bật lửa, dao', 'Quả bóng'), ans: 'C',
      why: 'Diêm, bật lửa, dao gây bỏng và đứt tay nên không được nghịch.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Gặp đèn giao thông màu đỏ, người và xe phải làm gì?',
      opts: o4('Dừng lại', 'Đi tiếp', 'Chạy nhanh hơn', 'Rẽ trái'), ans: 'A',
      why: 'Đèn đỏ phải dừng lại để đảm bảo an toàn.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Bộ phận nào của cây hút nước từ đất lên nuôi cây?',
      opts: o4('Lá', 'Hoa', 'Quả', 'Rễ'), ans: 'D',
      why: 'Rễ cây hút nước và chất dinh dưỡng từ đất.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào cho ta trứng để ăn?',
      opts: o4('Con gà', 'Con chó', 'Con mèo', 'Con voi'), ans: 'A',
      why: 'Gà, vịt đẻ trứng cho ta ăn.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Em nghe được tiếng nói nhờ bộ phận nào?',
      opts: o4('Mắt', 'Tai', 'Mũi', 'Chân'), ans: 'B',
      why: 'Tai là cơ quan để nghe.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Việc nào nên làm trước khi ăn cơm?',
      opts: o4('Rửa tay sạch', 'Chơi đất cát', 'Vuốt ve con mèo', 'Không làm gì'), ans: 'A',
      why: 'Rửa tay trước khi ăn để tránh vi trùng gây bệnh.' },
    { sec: 'Bầu trời', name: 'Câu 8', pts: 1,
      text: 'Ban đêm, trên trời ta nhìn thấy gì?',
      opts: o4('Mặt Trời', 'Mặt Trăng và các vì sao', 'Cầu vồng', 'Máy bay giấy'), ans: 'B',
      why: 'Ban đêm ta thấy Mặt Trăng và các ngôi sao.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Ở trường, ai là người dạy dỗ em?',
      opts: o4('Thầy, cô giáo', 'Người lạ ngoài đường', 'Chú tài xế', 'Bác nông dân'), ans: 'A',
      why: 'Thầy cô giáo là người dạy dỗ em ở trường.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Để giữ nơi mình sống sạch đẹp, em nên làm gì?',
      opts: o4('Bỏ rác đúng nơi quy định', 'Vứt rác xuống ao hồ', 'Bẻ cây nơi công cộng', 'Vẽ bậy lên tường'), ans: 'A',
      why: 'Bỏ rác đúng chỗ giúp làng xóm, phố phường luôn sạch đẹp.' },
  ],
},

/* ═══════════ ĐỀ 11 — GIA ĐÌNH THÂN YÊU ═══════════ */
{
  id: 8781, title: 'Đề 11 · Gia đình thân yêu', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Người sinh ra em và nuôi em lớn là ai?',
      opts: o4('Cô giáo', 'Bố và mẹ', 'Bạn hàng xóm', 'Bác đưa thư'), ans: 'B',
      why: 'Bố và mẹ là người sinh ra và nuôi nấng em.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Anh trai của bố em, em gọi là gì?',
      opts: o4('Dì', 'Ông ngoại', 'Chị gái', 'Bác trai'), ans: 'D',
      why: 'Anh trai của bố được gọi là bác.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Em trai của bố em, em gọi là gì?',
      opts: o4('Dì', 'Chú', 'Bà', 'Anh'), ans: 'B',
      why: 'Em trai của bố được gọi là chú.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Khi được bố mẹ cho quà, em nên nói gì?',
      opts: o4('Không nói gì cả', 'Đưa đây cho con', 'Con cảm ơn ạ', 'Con không thích'), ans: 'C',
      why: 'Khi nhận quà em nên lễ phép nói lời cảm ơn.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Buổi sáng đi học, em nên chào bố mẹ thế nào?',
      opts: o4('Con chào bố mẹ, con đi học ạ', 'Bỏ đi luôn không chào', 'Hét thật to', 'Khóc lóc'), ans: 'A',
      why: 'Đi học em nên chào bố mẹ lễ phép.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Việc nào giúp mẹ được lòng nhất?',
      opts: o4('Bày đồ chơi bừa bãi', 'Tự cất dọn đồ chơi, giúp mẹ việc nhỏ', 'Khóc đòi đồ chơi', 'Vẽ bẩn lên tường'), ans: 'B',
      why: 'Tự dọn đồ chơi và giúp mẹ việc nhỏ là ngoan.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Trong bữa cơm gia đình, em nên làm gì?',
      opts: o4('Mời ông bà, bố mẹ ăn cơm', 'Giành hết thức ăn ngon', 'Vừa ăn vừa chạy nhảy', 'Bốc thức ăn ném đi'), ans: 'A',
      why: 'Trước khi ăn nên mời người lớn, đó là phép lịch sự.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Con của bác (anh của bố), so với em thì là gì?',
      opts: o4('Ông của em', 'Anh (chị) họ của em', 'Bố của em', 'Người lạ'), ans: 'B',
      why: 'Con của bác là anh, chị họ của em.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Khi mẹ mệt, em nên làm gì?',
      opts: o4('Bật nhạc thật to', 'Đòi mẹ chơi ngay', 'Làm ồn ào', 'Rót nước, hỏi thăm và để mẹ nghỉ'), ans: 'D',
      why: 'Mẹ mệt thì em nên yên lặng, hỏi thăm và để mẹ nghỉ.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Những người thân trong gia đình cần đối xử với nhau ra sao?',
      opts: o4('Cãi nhau suốt ngày', 'Không quan tâm nhau', 'Tranh giành đồ đạc', 'Yêu thương, quan tâm nhau'), ans: 'D',
      why: 'Người thân trong nhà cần yêu thương và quan tâm lẫn nhau.' },
  ],
},

/* ═══════════ ĐỀ 12 — NHÀ Ở VÀ ĐỒ DÙNG TRONG NHÀ ═══════════ */
{
  id: 8782, title: 'Đề 12 · Nhà ở và đồ dùng trong nhà', time: 15,
  questions: [
    { sec: 'Nhà ở', name: 'Câu 1', pts: 1,
      text: 'Phòng dùng để tiếp khách, cả nhà ngồi xem ti vi gọi là gì?',
      opts: o4('Nhà tắm', 'Phòng bếp', 'Phòng khách', 'Nhà kho'), ans: 'C',
      why: 'Phòng khách là nơi tiếp khách và cả nhà quây quần.' },
    { sec: 'Nhà ở', name: 'Câu 2', pts: 1,
      text: 'Đồ dùng nào dùng để nấu cơm cho cả nhà?',
      opts: o4('Nồi cơm điện', 'Cái tủ áo', 'Cái gối', 'Quyển sách'), ans: 'A',
      why: 'Nồi cơm điện dùng để nấu cơm.' },
    { sec: 'Nhà ở', name: 'Câu 3', pts: 1,
      text: 'Đồ dùng nào giúp em thấy đường vào buổi tối?',
      opts: o4('Cái chăn', 'Cái ghế', 'Đôi dép', 'Bóng đèn'), ans: 'D',
      why: 'Bóng đèn thắp sáng giúp ta nhìn rõ vào buổi tối.' },
    { sec: 'Nhà ở', name: 'Câu 4', pts: 1,
      text: 'Đồ dùng nào giúp giữ thức ăn được tươi lâu?',
      opts: o4('Cái chổi', 'Cái quạt', 'Tủ lạnh', 'Cái gương'), ans: 'C',
      why: 'Tủ lạnh giữ lạnh giúp thức ăn tươi lâu, không hỏng.' },
    { sec: 'Nhà ở', name: 'Câu 5', pts: 1,
      text: 'Buổi tối em ngủ ở phòng nào?',
      opts: o4('Nhà bếp', 'Phòng ngủ', 'Nhà vệ sinh', 'Ngoài sân'), ans: 'B',
      why: 'Phòng ngủ là nơi để nghỉ ngơi và ngủ.' },
    { sec: 'Nhà ở', name: 'Câu 6', pts: 1,
      text: 'Đồ dùng nào để cất và giữ quần áo?',
      opts: o4('Cái nồi', 'Cái bàn ăn', 'Ti vi', 'Cái tủ áo'), ans: 'D',
      why: 'Tủ áo (tủ quần áo) dùng để cất giữ quần áo gọn gàng.' },
    { sec: 'Nhà ở', name: 'Câu 7', pts: 1,
      text: 'Đồ dùng nào giúp em lau khô người sau khi tắm?',
      opts: o4('Cái nồi', 'Cái bút', 'Cái khăn tắm', 'Cái đĩa'), ans: 'C',
      why: 'Khăn tắm dùng để lau khô người sau khi tắm.' },
    { sec: 'Nhà ở', name: 'Câu 8', pts: 1,
      text: 'Vì sao đồ dùng trong nhà cần sắp xếp gọn gàng?',
      opts: o4('Để nhà bừa bộn hơn', 'Để không ai dùng được', 'Để làm bẩn nhà', 'Để nhà đẹp, dễ tìm và không vấp ngã'), ans: 'D',
      why: 'Sắp xếp gọn giúp nhà đẹp, dễ tìm đồ và tránh vấp ngã.' },
    { sec: 'Nhà ở', name: 'Câu 9', pts: 1,
      text: 'Sau khi dùng cốc uống nước xong, em nên làm gì?',
      opts: o4('Ném xuống đất', 'Rửa sạch và cất vào đúng chỗ', 'Để bẩn trên bàn', 'Giấu đi'), ans: 'B',
      why: 'Dùng xong nên rửa sạch và cất đồ về đúng chỗ.' },
    { sec: 'Nhà ở', name: 'Câu 10', pts: 1,
      text: 'Đồ dùng nào giúp làm sạch sàn nhà cùng với chổi?',
      opts: o4('Cái ti vi', 'Cái ki hốt rác', 'Cái gối', 'Cái mũ'), ans: 'B',
      why: 'Ki hốt rác dùng cùng chổi để hốt rác cho sàn sạch.' },
  ],
},

/* ═══════════ ĐỀ 13 — LỚP HỌC CỦA EM ═══════════ */
{
  id: 8783, title: 'Đề 13 · Lớp học của em', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Đồ dùng nào để viết chữ vào vở?',
      opts: o4('Cái nồi', 'Cái quạt', 'Cái bút', 'Cái chổi'), ans: 'C',
      why: 'Bút dùng để viết chữ.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Đồ dùng nào để đựng sách vở khi đi học?',
      opts: o4('Cái nồi cơm', 'Cái cặp sách', 'Cái gối', 'Cái ô tô'), ans: 'B',
      why: 'Cặp sách dùng để đựng sách vở, đồ dùng học tập.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Cô giáo viết bài giảng lên đâu cho cả lớp nhìn?',
      opts: o4('Lên sàn nhà', 'Lên bảng', 'Lên cửa sổ', 'Lên mái nhà'), ans: 'B',
      why: 'Cô giáo viết lên bảng để cả lớp cùng nhìn.' },
    { sec: 'Trường học', name: 'Câu 4', pts: 1,
      text: 'Đồ dùng nào dùng để tẩy (xoá) chữ viết sai bằng bút chì?',
      opts: o4('Cái thước', 'Cái kéo', 'Lọ hồ dán', 'Cục tẩy'), ans: 'D',
      why: 'Cục tẩy (gôm) dùng để xoá nét bút chì viết sai.' },
    { sec: 'Trường học', name: 'Câu 5', pts: 1,
      text: 'Đồ dùng nào để kẻ đường thẳng cho đẹp?',
      opts: o4('Cái thước kẻ', 'Cục tẩy', 'Cái cặp', 'Bút màu'), ans: 'A',
      why: 'Thước kẻ giúp kẻ đường thẳng, đo độ dài.' },
    { sec: 'Trường học', name: 'Câu 6', pts: 1,
      text: 'Khi muốn phát biểu, em nên làm gì?',
      opts: o4('Nói leo thật to', 'Giơ tay xin phép cô', 'Đứng lên chạy quanh lớp', 'La hét'), ans: 'B',
      why: 'Muốn phát biểu phải giơ tay xin phép cô giáo.' },
    { sec: 'Trường học', name: 'Câu 7', pts: 1,
      text: 'Mượn bút của bạn xong, em nên làm gì?',
      opts: o4('Cảm ơn và trả lại bạn', 'Giữ luôn không trả', 'Làm gãy rồi vứt đi', 'Đưa cho bạn khác'), ans: 'A',
      why: 'Mượn đồ của bạn dùng xong phải cảm ơn và trả lại.' },
    { sec: 'Trường học', name: 'Câu 8', pts: 1,
      text: 'Việc nào giúp giữ bàn học sạch, đẹp?',
      opts: o4('Giữ bàn sạch, không viết bậy', 'Vẽ bậy, khắc lên mặt bàn', 'Đổ nước ra bàn', 'Bôi kẹo dính lên bàn'), ans: 'A',
      why: 'Không viết vẽ bậy giúp bàn học luôn sạch, bền.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Đến lớp muộn, em nên làm gì?',
      opts: o4('Xin phép cô rồi vào lớp', 'Chạy ào vào chỗ', 'Đứng ngoài không vào', 'La hét gọi bạn'), ans: 'A',
      why: 'Đến muộn nên lễ phép xin phép cô rồi mới vào lớp.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Bạn ngồi cạnh quên mang bút, em nên làm gì?',
      opts: o4('Cười chê bạn', 'Giấu bút đi', 'Cho bạn mượn bút', 'Mách cô để phạt bạn'), ans: 'C',
      why: 'Giúp bạn bằng cách cho mượn bút là việc tốt.' },
  ],
},

/* ═══════════ ĐỀ 14 — NGHỀ NGHIỆP QUANH EM ═══════════ */
{
  id: 8784, title: 'Đề 14 · Những nghề quen thuộc', time: 15,
  questions: [
    { sec: 'Cộng đồng', name: 'Câu 1', pts: 1,
      text: 'Người trồng lúa, trồng rau, nuôi gà lợn gọi là gì?',
      opts: o4('Bác nông dân', 'Chú phi công', 'Cô ca sĩ', 'Bác sĩ'), ans: 'A',
      why: 'Nông dân là người làm ruộng, trồng trọt, chăn nuôi.' },
    { sec: 'Cộng đồng', name: 'Câu 2', pts: 1,
      text: 'Người dạy học cho học sinh gọi là gì?',
      opts: o4('Người bán cá', 'Chú thợ xây', 'Thầy, cô giáo', 'Bác tài xế'), ans: 'C',
      why: 'Thầy giáo, cô giáo làm nghề dạy học.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Người lái ô tô, xe khách chở mọi người gọi là gì?',
      opts: o4('Bác nông dân', 'Chú tài xế (lái xe)', 'Cô y tá', 'Chú lính cứu hoả'), ans: 'B',
      why: 'Tài xế là người lái xe chở khách và hàng hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 4', pts: 1,
      text: 'Người chữa cháy, cứu người trong đám cháy gọi là gì?',
      opts: o4('Cô giáo', 'Lính cứu hoả', 'Bác đầu bếp', 'Người bán hoa'), ans: 'B',
      why: 'Lính cứu hoả (phòng cháy chữa cháy) dập lửa và cứu người.' },
    { sec: 'Cộng đồng', name: 'Câu 5', pts: 1,
      text: 'Người nấu các món ăn ở nhà hàng gọi là gì?',
      opts: o4('Bác sĩ', 'Phi công', 'Thợ may', 'Đầu bếp'), ans: 'D',
      why: 'Đầu bếp là người nấu các món ăn.' },
    { sec: 'Cộng đồng', name: 'Câu 6', pts: 1,
      text: 'Người may quần áo cho chúng ta gọi là gì?',
      opts: o4('Bác nông dân', 'Chú công an', 'Thợ may', 'Cô lao công'), ans: 'C',
      why: 'Thợ may cắt vải và may thành quần áo.' },
    { sec: 'Cộng đồng', name: 'Câu 7', pts: 1,
      text: 'Người quét dọn, giữ đường phố sạch sẽ gọi là gì?',
      opts: o4('Cô (chú) lao công', 'Phi công', 'Ca sĩ', 'Thợ điện'), ans: 'A',
      why: 'Lao công quét dọn, giữ đường phố sạch đẹp.' },
    { sec: 'Cộng đồng', name: 'Câu 8', pts: 1,
      text: 'Đối với người lao động, em nên có thái độ thế nào?',
      opts: o4('Coi thường họ', 'Chê bai họ', 'Không quan tâm', 'Tôn trọng và biết ơn'), ans: 'D',
      why: 'Mọi nghề đều có ích, ta cần tôn trọng và biết ơn người lao động.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Người lái máy bay chở khách gọi là gì?',
      opts: o4('Nông dân', 'Ngư dân', 'Thợ mộc', 'Phi công'), ans: 'D',
      why: 'Phi công là người lái máy bay.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Người đánh bắt cá trên biển gọi là gì?',
      opts: o4('Bác sĩ', 'Giáo viên', 'Ngư dân', 'Thợ xây'), ans: 'C',
      why: 'Ngư dân là người đánh bắt cá, tôm trên sông, biển.' },
  ],
},

/* ═══════════ ĐỀ 15 — AN TOÀN TRÊN ĐƯỜNG ═══════════ */
{
  id: 8785, title: 'Đề 15 · An toàn trên đường', time: 15,
  questions: [
    { sec: 'Giao thông', name: 'Câu 1', pts: 1,
      text: 'Đèn giao thông màu vàng báo hiệu điều gì?',
      opts: o4('Được đi thật nhanh', 'Đi chậm lại, chuẩn bị dừng', 'Lùi lại', 'Rẽ trái'), ans: 'B',
      why: 'Đèn vàng báo hiệu đi chậm lại và chuẩn bị dừng.' },
    { sec: 'Giao thông', name: 'Câu 2', pts: 1,
      text: 'Người đi bộ qua đường nên đi ở đâu?',
      opts: o4('Giữa lòng đường', 'Vạch kẻ dành cho người đi bộ', 'Chỗ nào cũng được', 'Sau đuôi ô tô'), ans: 'B',
      why: 'Qua đường phải đi đúng vạch kẻ dành cho người đi bộ.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Khi ngồi sau xe đạp, xe máy, em phải làm gì?',
      opts: o4('Đứng lên nhún nhảy', 'Thả hai tay', 'Ngồi yên, ôm chặt người lái', 'Đùa nghịch'), ans: 'C',
      why: 'Ngồi sau xe phải ngồi yên, bám chắc để không bị ngã.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Em có nên chơi đùa, đá bóng dưới lòng đường không?',
      opts: o4('Không nên, rất nguy hiểm', 'Có, rất vui', 'Chỉ chơi khi có xe', 'Lúc nào cũng được'), ans: 'A',
      why: 'Chơi dưới lòng đường rất nguy hiểm vì xe cộ qua lại.' },
    { sec: 'Giao thông', name: 'Câu 5', pts: 1,
      text: 'Khi đi bộ trên đường không có vỉa hè, em nên đi ở đâu?',
      opts: o4('Giữa đường', 'Sát lề đường bên phải', 'Bên trái sát xe chạy', 'Chạy zic zắc'), ans: 'B',
      why: 'Không có vỉa hè thì đi sát lề bên phải cho an toàn.' },
    { sec: 'Giao thông', name: 'Câu 6', pts: 1,
      text: 'Trẻ em nhỏ khi qua đường nên làm gì?',
      opts: o4('Tự chạy qua một mình', 'Nhắm mắt băng qua', 'Nắm tay người lớn cùng qua', 'Vừa qua vừa chơi'), ans: 'C',
      why: 'Trẻ nhỏ nên nắm tay người lớn khi qua đường.' },
    { sec: 'Giao thông', name: 'Câu 7', pts: 1,
      text: 'Bạn nào ngồi xe máy đúng cách?',
      opts: o4('Bạn đứng trên yên xe', 'Bạn quay ngang quay ngửa', 'Bạn đội mũ bảo hiểm, ngồi yên', 'Bạn thò chân ra ngoài'), ans: 'C',
      why: 'Đội mũ bảo hiểm và ngồi yên là ngồi xe máy đúng cách.' },
    { sec: 'Giao thông', name: 'Câu 8', pts: 1,
      text: 'Trước khi bước xuống lòng đường, em cần làm gì?',
      opts: o4('Vừa đi vừa nhìn điện thoại', 'Nhìn kỹ hai bên đường', 'Chạy thật nhanh', 'Nhắm mắt lại'), ans: 'B',
      why: 'Phải quan sát kỹ hai bên trước khi qua đường.' },
    { sec: 'Giao thông', name: 'Câu 9', pts: 1,
      text: 'Xe nào chở nhiều người, dừng ở bến để đón khách?',
      opts: o4('Xe đạp một người', 'Xe cút kít', 'Xe buýt (xe khách)', 'Xe lăn'), ans: 'C',
      why: 'Xe buýt chở nhiều người và dừng ở bến để đón, trả khách.' },
    { sec: 'Giao thông', name: 'Câu 10', pts: 1,
      text: 'Nghe thấy tiếng còi xe cứu thương, xe cứu hoả, mọi người nên làm gì?',
      opts: o4('Chặn đường lại', 'Chạy theo xe', 'Nhường đường cho xe đi trước', 'Không quan tâm'), ans: 'C',
      why: 'Xe cứu thương, cứu hoả đang làm nhiệm vụ nên phải nhường đường.' },
  ],
},

/* ═══════════ ĐỀ 16 — CÂY CỐI VÀ ÍCH LỢI ═══════════ */
{
  id: 8786, title: 'Đề 16 · Cây cối và ích lợi', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Bộ phận nào của cây thường có màu xanh, mọc trên cành?',
      opts: o4('Rễ', 'Củ', 'Lá', 'Hạt'), ans: 'C',
      why: 'Lá cây thường có màu xanh và mọc trên cành.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Cây nào cho ta bóng mát khi trời nắng?',
      opts: o4('Cây rau muống', 'Cây nấm', 'Cây bàng, cây phượng', 'Cây cỏ nhỏ'), ans: 'C',
      why: 'Cây to như bàng, phượng cho bóng mát rộng.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Củ cà rốt, củ khoai là bộ phận nào của cây mà ta ăn?',
      opts: o4('Hoa', 'Lá', 'Cành', 'Củ (rễ củ)'), ans: 'D',
      why: 'Cà rốt, khoai là phần củ của cây, dùng làm thức ăn.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Cây chuối cho ta ăn phần nào?',
      opts: o4('Rễ cây', 'Thân gỗ', 'Quả chuối', 'Hạt cứng'), ans: 'C',
      why: 'Cây chuối cho quả chuối để ăn.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Loài cây nào cho ta gỗ để làm bàn, ghế?',
      opts: o4('Cây rau cải', 'Cây lấy gỗ (cây xoan, cây lim)', 'Cây hành', 'Cây cỏ'), ans: 'B',
      why: 'Cây lấy gỗ cho gỗ để đóng bàn ghế, làm nhà.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Muốn hạt nảy mầm thành cây con, ta cần gì?',
      opts: o4('Đất, nước và không khí', 'Bóng tối kín mít', 'Dầu ăn', 'Nước ngọt có ga'), ans: 'A',
      why: 'Hạt cần đất ẩm, nước và không khí để nảy mầm.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Trồng nhiều cây xanh giúp ích gì cho môi trường?',
      opts: o4('Làm ô nhiễm hơn', 'Gây nóng bức hơn', 'Làm không khí trong lành hơn', 'Không có ích gì'), ans: 'C',
      why: 'Cây xanh làm sạch không khí, giúp môi trường trong lành.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Việc nào nên làm để bảo vệ cây trong sân trường?',
      opts: o4('Trèo lên cây', 'Bẻ hoa, hái lá', 'Không bẻ cành, không giẫm lên bồn cây', 'Vẽ lên thân cây'), ans: 'C',
      why: 'Không bẻ cành, không giẫm bồn cây là bảo vệ cây.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Cây cần được tưới nước vào lúc nào là tốt?',
      opts: o4('Giữa trưa nắng gắt', 'Không bao giờ tưới', 'Sáng sớm hoặc chiều mát', 'Chỉ tưới bằng nước bẩn'), ans: 'C',
      why: 'Nên tưới cây lúc sáng sớm hoặc chiều mát để cây hút nước tốt.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Cây hoa hồng, hoa cúc thường được trồng để làm gì?',
      opts: o4('Để đun bếp', 'Làm cảnh cho đẹp', 'Để làm giày', 'Để xây nhà'), ans: 'B',
      why: 'Hoa hồng, hoa cúc là cây hoa, trồng để làm cảnh cho đẹp.' },
  ],
},

/* ═══════════ ĐỀ 17 — CON VẬT VÀ ÍCH LỢI ═══════════ */
{
  id: 8787, title: 'Đề 17 · Con vật và ích lợi', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào gáy "ò ó o" báo hiệu trời sáng?',
      opts: o4('Con gà trống', 'Con mèo', 'Con cá', 'Con rùa'), ans: 'A',
      why: 'Gà trống gáy vào sáng sớm báo hiệu trời sáng.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào kêu "meo meo"?',
      opts: o4('Con chó', 'Con vịt', 'Con mèo', 'Con bò'), ans: 'C',
      why: 'Con mèo kêu "meo meo".' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con vật nào bơi giỏi, hay kêu "cạp cạp" và có màng ở chân?',
      opts: o4('Con vịt', 'Con gà', 'Con chó', 'Con mèo'), ans: 'A',
      why: 'Vịt có màng chân, bơi giỏi và kêu "cạp cạp".' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con ong cho ta sản phẩm ngọt nào?',
      opts: o4('Sữa', 'Trứng', 'Mật ong', 'Len'), ans: 'C',
      why: 'Ong hút mật hoa và làm ra mật ong.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào cho ta lông để làm áo len?',
      opts: o4('Con cá', 'Con gà', 'Con ếch', 'Con cừu'), ans: 'D',
      why: 'Lông cừu được dùng để làm sợi len, đan áo ấm.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con vật nào có ích vì bắt sâu bọ hại cây?',
      opts: o4('Con chim sâu, con cóc', 'Con hổ', 'Con cá mập', 'Con sư tử'), ans: 'A',
      why: 'Chim sâu, cóc bắt sâu bọ giúp bảo vệ mùa màng.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con vật nào KHÔNG biết bơi dưới nước?',
      opts: o4('Con gà', 'Con cá', 'Con vịt', 'Con ếch'), ans: 'A',
      why: 'Gà sống trên cạn, không biết bơi như cá, vịt, ếch.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con lợn (heo) được nuôi để làm gì?',
      opts: o4('Để trông nhà', 'Lấy thịt làm thức ăn', 'Để bắt chuột', 'Để kéo cày'), ans: 'B',
      why: 'Lợn được nuôi chủ yếu để lấy thịt.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Khi thấy con vật lạ, dữ (như chó lạ gầm gừ), em nên làm gì?',
      opts: o4('Tránh xa, không trêu chọc', 'Lại gần kéo đuôi', 'Ném đá vào nó', 'Ôm lấy nó'), ans: 'A',
      why: 'Con vật lạ có thể cắn, em nên tránh xa, không trêu chọc.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Con vật nào giúp nhà nông bằng cách kéo cày?',
      opts: o4('Con mèo', 'Con gà', 'Con trâu', 'Con chim'), ans: 'C',
      why: 'Trâu khoẻ, giúp nhà nông kéo cày trên ruộng.' },
  ],
},

/* ═══════════ ĐỀ 18 — CƠ THỂ EM ═══════════ */
{
  id: 8788, title: 'Đề 18 · Các bộ phận cơ thể', time: 15,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Bộ phận nào ở trên cùng của cơ thể, có mắt, mũi, miệng?',
      opts: o4('Bàn chân', 'Bàn tay', 'Cái đầu', 'Đầu gối'), ans: 'C',
      why: 'Đầu ở trên cùng, có mắt, mũi, miệng, tai.' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Ngón tay nằm ở bộ phận nào?',
      opts: o4('Cái tai', 'Bàn tay', 'Cái mũi', 'Bàn chân'), ans: 'B',
      why: 'Mỗi bàn tay có các ngón tay.' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Bình thường mỗi bàn tay có mấy ngón?',
      opts: o4('3 ngón', '7 ngón', '10 ngón', '5 ngón'), ans: 'D',
      why: 'Mỗi bàn tay có 5 ngón.' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Tóc mọc ở bộ phận nào?',
      opts: o4('Ở bàn chân', 'Ở đầu gối', 'Ở bụng', 'Trên đầu'), ans: 'D',
      why: 'Tóc mọc trên đầu.' },
    { sec: 'Cơ thể', name: 'Câu 5', pts: 1,
      text: 'Bộ phận nào giúp em cúi xuống và đứng thẳng lên?',
      opts: o4('Tai', 'Lưng', 'Mũi', 'Móng tay'), ans: 'B',
      why: 'Lưng và cột sống giúp cơ thể cúi, ngồi và đứng thẳng.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Cơ thể người bình thường có mấy chân?',
      opts: o4('4 chân', '2 chân', '3 chân', '6 chân'), ans: 'B',
      why: 'Con người có 2 chân để đi lại.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Em thở bằng bộ phận nào?',
      opts: o4('Tai', 'Mắt', 'Mũi', 'Móng tay'), ans: 'C',
      why: 'Mũi giúp em thở, hít không khí vào cơ thể.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Để cơ thể lớn lên khoẻ mạnh, hằng ngày em cần gì?',
      opts: o4('Nhịn ăn', 'Ngồi im mãi', 'Chỉ ăn kẹo', 'Ăn uống đủ chất và vận động'), ans: 'D',
      why: 'Ăn đủ chất và vận động giúp cơ thể lớn lên khoẻ mạnh.' },
    { sec: 'Cơ thể', name: 'Câu 9', pts: 1,
      text: 'Đầu gối nằm ở đâu?',
      opts: o4('Ở đầu', 'Trên bàn tay', 'Ở chân', 'Trong tai'), ans: 'C',
      why: 'Đầu gối nằm ở giữa chân, giúp gập chân lại.' },
    { sec: 'Cơ thể', name: 'Câu 10', pts: 1,
      text: 'Bộ phận nào giúp em mỉm cười và nói chuyện?',
      opts: o4('Miệng', 'Tai', 'Chân', 'Lưng'), ans: 'A',
      why: 'Miệng giúp em ăn, nói và mỉm cười.' },
  ],
},

/* ═══════════ ĐỀ 19 — GIỮ VỆ SINH VÀ ĂN UỐNG ═══════════ */
{
  id: 8789, title: 'Đề 19 · Giữ vệ sinh và ăn uống', time: 15,
  questions: [
    { sec: 'Sức khoẻ', name: 'Câu 1', pts: 1,
      text: 'Rửa tay đúng cách cần dùng gì?',
      opts: o4('Nước bẩn', 'Nước sạch và xà phòng', 'Cát và bùn', 'Dầu ăn'), ans: 'B',
      why: 'Rửa tay bằng nước sạch và xà phòng mới sạch vi trùng.' },
    { sec: 'Sức khoẻ', name: 'Câu 2', pts: 1,
      text: 'Thức ăn nào tốt cho sức khoẻ hơn?',
      opts: o4('Chỉ ăn bánh kẹo cả ngày', 'Rau, cá, cơm, trái cây', 'Đồ ăn ôi thiu', 'Nước ngọt thay cơm'), ans: 'B',
      why: 'Cơm, rau, cá, trái cây giúp cơ thể khoẻ và đủ chất.' },
    { sec: 'Sức khoẻ', name: 'Câu 3', pts: 1,
      text: 'Trước khi ăn trái cây, em nên làm gì?',
      opts: o4('Ăn ngay khi còn bẩn', 'Rửa sạch trái cây', 'Lăn trái cây dưới đất', 'Không cần rửa'), ans: 'B',
      why: 'Rửa sạch trái cây để loại bỏ bụi bẩn, vi trùng.' },
    { sec: 'Sức khoẻ', name: 'Câu 4', pts: 1,
      text: 'Ăn cơm em nên ăn thế nào?',
      opts: o4('Vừa ăn vừa chạy', 'Nuốt vội thật nhanh', 'Vừa ăn vừa nói cười lớn', 'Nhai kỹ, ăn từ tốn'), ans: 'D',
      why: 'Ăn nhai kỹ, từ tốn giúp tiêu hoá tốt và không bị hóc.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Khi ho hoặc hắt hơi, em nên làm gì?',
      opts: o4('Quay vào mặt bạn', 'Che miệng, mũi lại', 'Không che gì cả', 'Ho thẳng vào thức ăn'), ans: 'B',
      why: 'Che miệng mũi khi ho, hắt hơi để không lây bệnh cho người khác.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Quần áo bị bẩn, ướt mồ hôi thì em nên làm gì?',
      opts: o4('Mặc luôn nhiều ngày', 'Không cần thay', 'Mặc lại đồ bẩn', 'Thay quần áo sạch'), ans: 'D',
      why: 'Thay quần áo sạch giúp cơ thể sạch sẽ, tránh bệnh ngoài da.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Buổi sáng ngủ dậy, em nên làm gì cho răng miệng?',
      opts: o4('Ăn kẹo ngay', 'Không làm gì', 'Đánh răng, rửa mặt', 'Bôi bẩn lên mặt'), ans: 'C',
      why: 'Sáng dậy nên đánh răng, rửa mặt cho sạch sẽ, tỉnh táo.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Vì sao không nên ăn quà bánh bày bán mất vệ sinh, đầy ruồi?',
      opts: o4('Vì rất ngon', 'Vì rẻ tiền', 'Vì đẹp mắt', 'Vì dễ bị đau bụng, mắc bệnh'), ans: 'D',
      why: 'Thức ăn mất vệ sinh chứa vi trùng, dễ gây đau bụng, mắc bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Mỗi ngày em nên uống đủ gì?',
      opts: o4('Nước sạch', 'Chỉ uống nước ngọt có ga', 'Không uống gì', 'Nước ao hồ'), ans: 'A',
      why: 'Cơ thể cần uống đủ nước sạch mỗi ngày để khoẻ mạnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Khi bị bệnh, em cần làm gì?',
      opts: o4('Báo bố mẹ và đi khám bác sĩ', 'Giấu không cho ai biết', 'Chạy đi chơi', 'Ăn thật nhiều kẹo'), ans: 'A',
      why: 'Bị bệnh nên báo bố mẹ, đi khám và uống thuốc theo bác sĩ.' },
  ],
},

/* ═══════════ ĐỀ 20 — NGÀY, ĐÊM VÀ THỜI TIẾT ═══════════ */
{
  id: 8790, title: 'Đề 20 · Ngày, đêm và thời tiết', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Khi nào trời sáng, ta nhìn rõ mọi vật?',
      opts: o4('Ban đêm', 'Nửa đêm', 'Lúc trời tối', 'Ban ngày'), ans: 'D',
      why: 'Ban ngày có Mặt Trời chiếu sáng nên ta nhìn rõ mọi vật.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Khi nào trời tối, mọi người thường đi ngủ?',
      opts: o4('Buổi sáng', 'Ban đêm', 'Buổi trưa', 'Lúc Mặt Trời lên cao'), ans: 'B',
      why: 'Ban đêm trời tối, mọi người nghỉ ngơi và đi ngủ.' },
    { sec: 'Thời tiết', name: 'Câu 3', pts: 1,
      text: 'Trời nắng thì bầu trời thường thế nào?',
      opts: o4('Mưa tầm tã', 'Đầy tuyết rơi', 'Tối đen như mực', 'Trong xanh, có nắng'), ans: 'D',
      why: 'Trời nắng thì bầu trời trong xanh, có ánh nắng.' },
    { sec: 'Thời tiết', name: 'Câu 4', pts: 1,
      text: 'Khi trời mưa, mặt đường và cây cối thế nào?',
      opts: o4('Ướt nước', 'Khô cong', 'Bốc cháy', 'Đầy bụi'), ans: 'A',
      why: 'Trời mưa làm mặt đường, cây cối bị ướt.' },
    { sec: 'Thời tiết', name: 'Câu 5', pts: 1,
      text: 'Mùa nào trong năm thường nóng nhất?',
      opts: o4('Mùa đông', 'Mùa hè (mùa hạ)', 'Không mùa nào', 'Ban đêm'), ans: 'B',
      why: 'Mùa hè trời nắng nhiều nên nóng nhất trong năm.' },
    { sec: 'Thời tiết', name: 'Câu 6', pts: 1,
      text: 'Mùa nào trong năm thường lạnh nhất?',
      opts: o4('Mùa hè', 'Ban ngày', 'Lúc trưa', 'Mùa đông'), ans: 'D',
      why: 'Mùa đông trời rét, lạnh nhất trong năm.' },
    { sec: 'Thời tiết', name: 'Câu 7', pts: 1,
      text: 'Trời nắng gắt, em nên mặc quần áo thế nào?',
      opts: o4('Áo bông thật dày', 'Quần áo mỏng, thoáng mát', 'Nhiều lớp áo len', 'Mặc áo mưa'), ans: 'B',
      why: 'Trời nóng nên mặc đồ mỏng, thoáng cho mát.' },
    { sec: 'Thời tiết', name: 'Câu 8', pts: 1,
      text: 'Khi có gió to, mưa lớn (bão), em nên làm gì?',
      opts: o4('Chạy ra ngoài chơi', 'Ở trong nhà an toàn', 'Đứng dưới gốc cây to', 'Ra bờ sông xem nước'), ans: 'B',
      why: 'Khi có bão, gió lớn nên ở trong nhà cho an toàn.' },
    { sec: 'Thời tiết', name: 'Câu 9', pts: 1,
      text: 'Buổi chiều tối, Mặt Trời lặn ở hướng nào?',
      opts: o4('Hướng tây', 'Hướng đông', 'Ngay trên đầu', 'Dưới đất'), ans: 'A',
      why: 'Mặt Trời mọc ở hướng đông và lặn ở hướng tây.' },
    { sec: 'Thời tiết', name: 'Câu 10', pts: 1,
      text: 'Ra ngoài trời mưa mà không có áo mưa, em dễ bị gì?',
      opts: o4('Cao lớn nhanh hơn', 'Khoẻ mạnh hơn', 'Ướt và có thể bị cảm lạnh', 'Không sao cả'), ans: 'C',
      why: 'Bị ướt mưa dễ nhiễm lạnh, cảm ho nên cần che mưa.' },
  ],
},

/* ═══════════ ĐỀ 21 — TÌNH CẢM GIA ĐÌNH VÀ AN TOÀN Ở NHÀ ═══════════ */
{
  id: 8791, title: 'Đề 21 · Gia đình và an toàn ở nhà', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Chị gái của mẹ em, em gọi là gì?',
      opts: o4('Ông nội', 'Chú', 'Anh trai', 'Bác gái (hoặc dì)'), ans: 'D',
      why: 'Chị của mẹ thường được gọi là bác gái (có nơi gọi là dì).' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Ngày sinh nhật ông bà, em nên làm gì?',
      opts: o4('Quên luôn', 'Đòi quà cho mình', 'Bỏ đi chơi', 'Chúc mừng và tặng ông bà lời yêu thương'), ans: 'D',
      why: 'Sinh nhật ông bà, em nên chúc mừng, thể hiện tình yêu thương.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Ở nhà, em có nên nghịch bếp ga đang cháy lửa không?',
      opts: o4('Có, rất vui', 'Chỉ nghịch một chút', 'Lúc nào cũng được', 'Không, rất nguy hiểm'), ans: 'D',
      why: 'Bếp lửa gây bỏng, cháy; trẻ em không được nghịch.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Sàn nhà tắm ướt trơn, em nên đi thế nào?',
      opts: o4('Chạy thật nhanh', 'Đi chậm, cẩn thận kẻo ngã', 'Nhảy lò cò', 'Trượt cho vui'), ans: 'B',
      why: 'Sàn ướt rất trơn, phải đi chậm để không bị ngã.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Thấy em bé sắp cho hạt nhỏ vào miệng, em nên làm gì?',
      opts: o4('Cho bé nuốt thử', 'Cười và bỏ đi', 'Đưa thêm hạt cho bé', 'Ngăn lại và báo người lớn'), ans: 'D',
      why: 'Hạt nhỏ dễ làm bé bị hóc, nghẹn; phải ngăn và báo người lớn.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Chai nước lạ, thuốc trong nhà, em có được tự ý uống không?',
      opts: o4('Uống thử một ngụm', 'Uống hết luôn', 'Không được tự ý uống', 'Chia cho bạn uống'), ans: 'C',
      why: 'Thuốc, hoá chất lạ rất nguy hiểm; không được tự ý uống.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Khi bố mẹ đi làm về mệt, em nên làm gì?',
      opts: o4('Đòi đi chơi ngay', 'Bật ti vi thật to', 'Chào và mời bố mẹ uống nước', 'Khóc nhè'), ans: 'C',
      why: 'Bố mẹ về mệt, em nên chào hỏi và quan tâm bố mẹ.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Khi ở nhà một mình, nếu có sự cố (cháy, người lạ), em nên gọi ai?',
      opts: o4('Gọi bố mẹ hoặc người thân', 'Không gọi ai', 'Đi ra đường theo người lạ', 'Trốn im lặng mãi'), ans: 'A',
      why: 'Có sự cố phải gọi ngay bố mẹ, người thân hoặc số khẩn cấp.' },
    { sec: 'An toàn', name: 'Câu 9', pts: 1,
      text: 'Đồ chơi bị vỡ, sắc cạnh thì em nên làm gì?',
      opts: o4('Tiếp tục chơi', 'Ngậm vào miệng', 'Ném vào bạn', 'Báo người lớn, không cầm nghịch'), ans: 'D',
      why: 'Đồ vỡ sắc cạnh dễ đứt tay, phải báo người lớn dọn đi.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Ngôi nhà giúp che chở cho gia đình khỏi điều gì?',
      opts: o4('Tình yêu thương', 'Niềm vui', 'Mưa, nắng, gió lạnh', 'Bữa cơm'), ans: 'C',
      why: 'Ngôi nhà che mưa, nắng, gió rét cho các thành viên.' },
  ],
},

/* ═══════════ ĐỀ 22 — HOẠT ĐỘNG Ở TRƯỜNG ═══════════ */
{
  id: 8792, title: 'Đề 22 · Hoạt động ở trường', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Buổi sáng chào cờ, học sinh thường làm gì?',
      opts: o4('Đứng nghiêm, hát Quốc ca', 'Chạy nhảy lung tung', 'Nói chuyện riêng', 'Ngồi bệt xuống đất'), ans: 'A',
      why: 'Chào cờ phải đứng nghiêm trang và hát Quốc ca.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Trong giờ học, việc nào là đúng?',
      opts: o4('Nói chuyện riêng', 'Vẽ bậy ra vở', 'Chú ý nghe giảng, làm bài', 'Trêu chọc bạn'), ans: 'C',
      why: 'Giờ học phải chú ý nghe giảng và làm bài đầy đủ.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Gặp thầy cô giáo trong trường, em nên làm gì?',
      opts: o4('Bỏ chạy', 'Giả vờ không thấy', 'Cười to rồi bỏ đi', 'Lễ phép chào thầy cô'), ans: 'D',
      why: 'Gặp thầy cô phải lễ phép chào hỏi.' },
    { sec: 'Trường học', name: 'Câu 4', pts: 1,
      text: 'Đến giờ ra chơi, em nên chơi ở đâu?',
      opts: o4('Ngoài đường lớn', 'Trên nóc nhà', 'Chỗ có ổ điện', 'Trong khu vực sân trường'), ans: 'D',
      why: 'Ra chơi nên chơi trong sân trường cho an toàn.' },
    { sec: 'Trường học', name: 'Câu 5', pts: 1,
      text: 'Nhặt được đồ của bạn đánh rơi, em nên làm gì?',
      opts: o4('Giữ làm của mình', 'Trả lại bạn hoặc báo thầy cô', 'Vứt đi', 'Giấu vào cặp'), ans: 'B',
      why: 'Nhặt được của rơi phải trả lại người mất hoặc báo thầy cô.' },
    { sec: 'Trường học', name: 'Câu 6', pts: 1,
      text: 'Tới phiên trực nhật, em nên làm gì?',
      opts: o4('Trốn về sớm', 'Quét lớp, lau bảng cho sạch', 'Chỉ ngồi chơi', 'Bảo bạn làm hết'), ans: 'B',
      why: 'Trực nhật là quét lớp, lau bảng giúp lớp sạch sẽ.' },
    { sec: 'Trường học', name: 'Câu 7', pts: 1,
      text: 'Khi xếp hàng vào lớp, em nên thế nào?',
      opts: o4('Chen lấn, xô đẩy', 'Xếp hàng ngay ngắn, trật tự', 'Đứng lộn xộn', 'La hét'), ans: 'B',
      why: 'Xếp hàng phải ngay ngắn, trật tự, không chen lấn.' },
    { sec: 'Trường học', name: 'Câu 8', pts: 1,
      text: 'Ở trường, ngoài học em còn được tham gia gì?',
      opts: o4('Chỉ ngồi im cả ngày', 'Ngủ suốt buổi', 'Múa hát, thể dục, vui chơi', 'Không làm gì'), ans: 'C',
      why: 'Ở trường em còn được học múa hát, thể dục và vui chơi.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Khi bạn buồn, em nên làm gì?',
      opts: o4('Cười chê bạn', 'Bỏ mặc bạn', 'An ủi, động viên bạn', 'Trêu chọc thêm'), ans: 'C',
      why: 'Bạn buồn thì nên an ủi, động viên để bạn vui hơn.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Vì sao em cần đi học đúng giờ?',
      opts: o4('Để không bỏ lỡ bài học', 'Để làm phiền cả lớp', 'Để được về sớm', 'Để không phải học'), ans: 'A',
      why: 'Đi học đúng giờ để theo kịp bài và giữ nề nếp lớp.' },
  ],
},

/* ═══════════ ĐỀ 23 — NƠI EM SỐNG ═══════════ */
{
  id: 8793, title: 'Đề 23 · Nơi em sống', time: 15,
  questions: [
    { sec: 'Cộng đồng', name: 'Câu 1', pts: 1,
      text: 'Nơi em gửi và nhận thư, bưu phẩm gọi là gì?',
      opts: o4('Bưu điện', 'Bệnh viện', 'Trường học', 'Chợ'), ans: 'A',
      why: 'Bưu điện là nơi gửi, nhận thư từ và bưu phẩm.' },
    { sec: 'Cộng đồng', name: 'Câu 2', pts: 1,
      text: 'Nơi mọi người đến đọc và mượn sách gọi là gì?',
      opts: o4('Thư viện', 'Nhà bếp', 'Bến xe', 'Sân bóng'), ans: 'A',
      why: 'Thư viện là nơi đọc và mượn sách.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Nơi giữ gìn an ninh, giúp dân khi gặp chuyện xấu là ai (đơn vị nào)?',
      opts: o4('Công an', 'Người bán rau', 'Ca sĩ', 'Thợ may'), ans: 'A',
      why: 'Công an giữ gìn an ninh, trật tự và giúp đỡ người dân.' },
    { sec: 'Cộng đồng', name: 'Câu 4', pts: 1,
      text: 'Những người sống gần nhà em gọi là gì?',
      opts: o4('Người nước ngoài', 'Người lạ', 'Hàng xóm', 'Khách du lịch'), ans: 'C',
      why: 'Những người sống gần nhà mình là hàng xóm.' },
    { sec: 'Cộng đồng', name: 'Câu 5', pts: 1,
      text: 'Với hàng xóm, em nên cư xử thế nào?',
      opts: o4('Làm ồn ào phá phách', 'Không chào ai', 'Ném rác sang nhà họ', 'Lễ phép chào hỏi, thân thiện'), ans: 'D',
      why: 'Với hàng xóm nên chào hỏi lễ phép, sống thân thiện.' },
    { sec: 'Cộng đồng', name: 'Câu 6', pts: 1,
      text: 'Nơi trẻ em vui chơi có xích đu, cầu trượt gọi là gì?',
      opts: o4('Công viên (khu vui chơi)', 'Nhà kho', 'Bãi rác', 'Bệnh viện'), ans: 'A',
      why: 'Công viên, khu vui chơi có xích đu, cầu trượt cho trẻ em.' },
    { sec: 'Cộng đồng', name: 'Câu 7', pts: 1,
      text: 'Để giữ nơi công cộng sạch đẹp, em nên làm gì?',
      opts: o4('Vứt rác bừa bãi', 'Bẻ cây, hái hoa', 'Bỏ rác vào thùng rác', 'Vẽ bậy lên ghế đá'), ans: 'C',
      why: 'Bỏ rác đúng thùng giúp nơi công cộng sạch đẹp.' },
    { sec: 'Cộng đồng', name: 'Câu 8', pts: 1,
      text: 'Thấy một cụ già muốn qua đường, em nên làm gì?',
      opts: o4('Giúp cụ qua đường an toàn', 'Bỏ đi', 'Cười cụ', 'Xô cụ ngã'), ans: 'A',
      why: 'Giúp đỡ người già qua đường là việc làm tốt.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Đường phố, làng xóm nơi em sống cần được giữ gìn thế nào?',
      opts: o4('Bẩn thỉu, đầy rác', 'Chặt hết cây xanh', 'Vẽ bậy khắp nơi', 'Sạch sẽ, xanh, an toàn'), ans: 'D',
      why: 'Nơi mình sống cần được giữ sạch, xanh và an toàn.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Khi bị lạc ở nơi đông người, em nên làm gì?',
      opts: o4('Chạy lung tung', 'Đứng yên, nhờ chú công an hoặc người lớn đáng tin giúp', 'Đi theo người lạ về nhà họ', 'Khóc rồi bỏ đi thật xa'), ans: 'B',
      why: 'Bị lạc nên đứng yên, nhờ công an hoặc người lớn đáng tin giúp gọi bố mẹ.' },
  ],
},

/* ═══════════ ĐỀ 24 — THIÊN NHIÊN QUANH EM ═══════════ */
{
  id: 8794, title: 'Đề 24 · Cây và con vật quanh em', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Cây nào sống dưới nước, có lá to nổi trên mặt ao?',
      opts: o4('Cây sen (cây súng)', 'Cây bàng', 'Cây xoài', 'Cây thông'), ans: 'A',
      why: 'Cây sen, cây súng sống dưới nước, lá nổi trên mặt ao.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào sống dưới nước và trên cạn, hay kêu "ộp ộp"?',
      opts: o4('Con gà', 'Con chó', 'Con chim', 'Con ếch'), ans: 'D',
      why: 'Ếch sống được cả dưới nước và trên cạn, kêu "ộp ộp".' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Bộ phận nào giúp cây đứng vững và mang cành lá?',
      opts: o4('Thân cây', 'Hoa', 'Quả', 'Hạt'), ans: 'A',
      why: 'Thân cây giúp cây đứng vững và mang cành, lá.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con vật nào chậm chạp, mang mai cứng trên lưng?',
      opts: o4('Con thỏ', 'Con ngựa', 'Con rùa', 'Con chim'), ans: 'C',
      why: 'Rùa bò chậm và có mai cứng che thân.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào có tai dài, thích ăn cà rốt và nhảy nhanh?',
      opts: o4('Con voi', 'Con thỏ', 'Con cá', 'Con rắn'), ans: 'B',
      why: 'Thỏ có tai dài, thích ăn rau, cà rốt và nhảy rất nhanh.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Vào mùa nào cây cối thường ra hoa, đâm chồi nảy lộc?',
      opts: o4('Mùa đông', 'Ban đêm', 'Mùa xuân', 'Không mùa nào'), ans: 'C',
      why: 'Mùa xuân ấm áp, cây cối đâm chồi, nảy lộc và ra hoa.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con vật nào to lớn, có vòi dài và hai ngà?',
      opts: o4('Con mèo', 'Con gà', 'Con cá', 'Con voi'), ans: 'D',
      why: 'Voi rất to, có vòi dài và hai ngà.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Điều gì làm hại cây xanh nơi công cộng?',
      opts: o4('Tưới nước cho cây', 'Nhặt lá khô', 'Bẻ cành, giẫm nát cây', 'Bắt sâu cho cây'), ans: 'C',
      why: 'Bẻ cành, giẫm nát làm cây bị thương và chết.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Con vật nào có ích vì cho ta cả thịt lẫn trứng?',
      opts: o4('Con hổ', 'Con gà', 'Con rắn', 'Con muỗi'), ans: 'B',
      why: 'Gà cho ta cả thịt và trứng để ăn.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Con vật nào KHÔNG có ích, hay hút máu và truyền bệnh?',
      opts: o4('Con bò', 'Con gà', 'Con ong', 'Con muỗi'), ans: 'D',
      why: 'Muỗi hút máu và truyền bệnh, cần phòng tránh, diệt muỗi.' },
  ],
},

/* ═══════════ ĐỀ 25 — GIÁC QUAN VÀ SỨC KHOẺ ═══════════ */
{
  id: 8795, title: 'Đề 25 · Giác quan và sức khoẻ', time: 15,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Để bảo vệ đôi mắt, em KHÔNG nên làm gì?',
      opts: o4('Đọc sách nơi đủ sáng', 'Ngồi xa ti vi', 'Cho mắt nghỉ ngơi', 'Dụi mắt bằng tay bẩn'), ans: 'D',
      why: 'Dụi mắt bằng tay bẩn dễ làm mắt đau, nhiễm bệnh.' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Để bảo vệ đôi tai, em nên tránh điều gì?',
      opts: o4('Nghe âm thanh quá to', 'Giữ tai sạch', 'Nghe nhạc vừa phải', 'Không cho vật lạ vào tai'), ans: 'A',
      why: 'Âm thanh quá to làm hại tai, cần tránh.' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Nhờ giác quan nào em ngửi được mùi thơm của hoa?',
      opts: o4('Tai', 'Lưỡi', 'Chân', 'Mũi'), ans: 'D',
      why: 'Mũi giúp em ngửi mùi (khứu giác).' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Nhờ giác quan nào em biết cốc nước là ngọt?',
      opts: o4('Lưỡi', 'Mắt', 'Tai', 'Da'), ans: 'A',
      why: 'Lưỡi giúp nếm và biết vị ngọt, mặn, chua, cay.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Để giữ đôi tay sạch, em nên làm gì?',
      opts: o4('Không rửa bao giờ', 'Bôi bùn lên tay', 'Rửa tay thường xuyên bằng xà phòng', 'Cắn móng tay'), ans: 'C',
      why: 'Rửa tay thường xuyên giúp tay sạch, tránh vi trùng.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Để răng chắc khoẻ, em nên hạn chế ăn gì?',
      opts: o4('Rau xanh', 'Trái cây tươi', 'Cá, thịt', 'Quá nhiều bánh kẹo ngọt'), ans: 'D',
      why: 'Ăn nhiều đồ ngọt dễ sâu răng, nên hạn chế.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Khi trời lạnh, để không bị ốm em nên làm gì?',
      opts: o4('Cởi bớt áo', 'Mặc ấm, giữ ấm cơ thể', 'Tắm nước lạnh lâu', 'Đi chân đất ngoài trời'), ans: 'B',
      why: 'Trời lạnh phải mặc ấm để không bị cảm, ốm.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Da của em có tác dụng gì?',
      opts: o4('Để nghe', 'Để nhìn', 'Bao bọc, bảo vệ cơ thể và cảm nhận nóng lạnh', 'Để nhai'), ans: 'C',
      why: 'Da bao bọc, bảo vệ cơ thể và giúp cảm nhận nóng, lạnh, đau.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Buổi tối trước khi ngủ, em nên làm gì cho răng?',
      opts: o4('Đánh răng sạch sẽ', 'Ăn thêm kẹo', 'Không làm gì', 'Uống nước ngọt'), ans: 'A',
      why: 'Đánh răng trước khi ngủ giúp răng sạch, không bị sâu.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Vận động, tập thể dục đều đặn giúp cơ thể thế nào?',
      opts: o4('Yếu ớt hơn', 'Hay ốm hơn', 'Chậm chạp hơn', 'Khoẻ mạnh, nhanh nhẹn'), ans: 'D',
      why: 'Tập thể dục đều đặn giúp cơ thể khoẻ mạnh, nhanh nhẹn.' },
  ],
},

/* ═══════════ ĐỀ 26 — MẶT TRỜI, MẶT TRĂNG VÀ SAO ═══════════ */
{
  id: 8796, title: 'Đề 26 · Mặt Trời, Mặt Trăng và sao', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Vật nào trên trời cho ta ánh sáng mạnh nhất vào ban ngày?',
      opts: o4('Mặt Trời', 'Ngôi sao nhỏ', 'Bóng đèn pin', 'Đom đóm'), ans: 'A',
      why: 'Mặt Trời cho ánh sáng mạnh nhất vào ban ngày.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Vào đêm rằm, Mặt Trăng thường có hình gì?',
      opts: o4('Vuông', 'Tròn và sáng', 'Tam giác', 'Hình ngôi sao'), ans: 'B',
      why: 'Đêm rằm, Mặt Trăng tròn và sáng nhất.' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Các đốm sáng nhỏ lấp lánh trên trời đêm gọi là gì?',
      opts: o4('Bông hoa', 'Ngôi sao', 'Hạt mưa', 'Viên bi'), ans: 'B',
      why: 'Những đốm sáng nhỏ lấp lánh ban đêm là các ngôi sao.' },
    { sec: 'Bầu trời', name: 'Câu 4', pts: 1,
      text: 'Vì sao ta không nên nhìn thẳng vào Mặt Trời?',
      opts: o4('Vì Mặt Trời xấu', 'Vì Mặt Trời lạnh', 'Vì rất chói, hại mắt', 'Vì không nhìn thấy gì'), ans: 'C',
      why: 'Ánh Mặt Trời rất chói, nhìn thẳng sẽ hại mắt.' },
    { sec: 'Bầu trời', name: 'Câu 5', pts: 1,
      text: 'Ánh sáng và hơi ấm của Mặt Trời giúp gì cho cây cối?',
      opts: o4('Làm cây héo ngay', 'Giúp cây xanh tốt, lớn lên', 'Không giúp gì', 'Làm cây đổ'), ans: 'B',
      why: 'Cây cối cần ánh sáng Mặt Trời để xanh tốt và lớn lên.' },
    { sec: 'Bầu trời', name: 'Câu 6', pts: 1,
      text: 'Khi nào ta thường nhìn thấy Mặt Trăng rõ nhất?',
      opts: o4('Ban đêm', 'Giữa trưa nắng', 'Lúc mưa to', 'Khi trời sáng chói'), ans: 'A',
      why: 'Mặt Trăng thường nhìn rõ nhất vào ban đêm.' },
    { sec: 'Bầu trời', name: 'Câu 7', pts: 1,
      text: 'Mây trên bầu trời thường có màu gì khi trời đẹp?',
      opts: o4('Màu trắng', 'Màu đỏ tươi', 'Màu tím than', 'Màu đen kịt'), ans: 'A',
      why: 'Trời đẹp, mây thường có màu trắng; mây đen báo hiệu mưa.' },
    { sec: 'Bầu trời', name: 'Câu 8', pts: 1,
      text: 'Buổi sáng khi Mặt Trời mọc thì trời thế nào?',
      opts: o4('Sáng dần lên', 'Tối dần đi', 'Vẫn tối đen', 'Có sao đầy trời'), ans: 'A',
      why: 'Mặt Trời mọc thì trời sáng dần lên, bắt đầu ngày mới.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Buổi chiều khi Mặt Trời lặn thì trời thế nào?',
      opts: o4('Tối dần đi', 'Sáng chói hơn', 'Nắng gắt hơn', 'Không thay đổi'), ans: 'A',
      why: 'Mặt Trời lặn thì trời tối dần, chuyển sang ban đêm.' },
    { sec: 'Bầu trời', name: 'Câu 10', pts: 1,
      text: 'Nhờ có ánh sáng Mặt Trời, ban ngày em có thể làm gì?',
      opts: o4('Không nhìn thấy gì', 'Chỉ ngủ được', 'Nhìn rõ, học tập, vui chơi', 'Bị lạnh cóng'), ans: 'C',
      why: 'Ánh sáng ban ngày giúp em nhìn rõ để học tập, vui chơi.' },
  ],
},

/* ═══════════ ĐỀ 27 — EM BIẾT TỰ BẢO VỆ ═══════════ */
{
  id: 8797, title: 'Đề 27 · Em biết tự bảo vệ', time: 15,
  questions: [
    { sec: 'An toàn', name: 'Câu 1', pts: 1,
      text: 'Người lạ cho em kẹo và rủ đi chơi, em nên làm gì?',
      opts: o4('Đi theo ngay', 'Nhận kẹo rồi đi cùng', 'Từ chối và báo bố mẹ, thầy cô', 'Giấu không nói ai'), ans: 'C',
      why: 'Không đi theo người lạ; phải từ chối và báo người lớn tin cậy.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Khi bị lạc, em nên nhớ điều gì để người lớn giúp?',
      opts: o4('Tên bố mẹ, số điện thoại (nếu nhớ)', 'Tên các con vật', 'Tên món ăn', 'Không cần nhớ gì'), ans: 'A',
      why: 'Nhớ tên bố mẹ và số điện thoại giúp người lớn liên lạc được.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Ao, hồ, sông sâu là nơi thế nào với trẻ em?',
      opts: o4('An toàn để bơi một mình', 'Nơi chơi tốt nhất', 'Nguy hiểm, dễ đuối nước', 'Không sao cả'), ans: 'C',
      why: 'Ao hồ sông sâu dễ gây đuối nước, không được tự ý xuống.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Muốn tắm, bơi ở hồ bơi, em cần có ai?',
      opts: o4('Đi một mình', 'Chỉ đi với bạn nhỏ', 'Người lớn đi cùng trông chừng', 'Không cần ai'), ans: 'C',
      why: 'Bơi phải có người lớn đi cùng để bảo đảm an toàn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Thấy dây điện bị đứt rơi xuống đất, em nên làm gì?',
      opts: o4('Tránh xa và báo người lớn', 'Nhặt lên chơi', 'Dùng tay chạm thử', 'Kéo dây đi'), ans: 'A',
      why: 'Dây điện đứt rất nguy hiểm, phải tránh xa và báo người lớn.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Khi có người lạ chạm vào cơ thể làm em thấy khó chịu, em nên làm gì?',
      opts: o4('Im lặng chịu đựng', 'Giữ bí mật mãi', 'Coi như không có gì', 'Nói "không", tránh xa và kể cho bố mẹ'), ans: 'D',
      why: 'Em có quyền nói "không", tránh xa và kể ngay cho bố mẹ, thầy cô.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Đồ chơi rất nhỏ, em bé dễ nuốt phải thì nên để thế nào?',
      opts: o4('Đưa cho em bé chơi', 'Để trên sàn', 'Trộn vào đồ ăn của bé', 'Để xa tầm tay em bé'), ans: 'D',
      why: 'Đồ nhỏ dễ gây hóc, phải để xa tầm tay em bé.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Khi qua đường cùng người lớn, em nên đi thế nào?',
      opts: o4('Buông tay chạy trước', 'Đi giữa dòng xe', 'Vừa đi vừa nhắm mắt', 'Nắm tay người lớn, đi đúng vạch'), ans: 'D',
      why: 'Qua đường phải nắm tay người lớn và đi đúng vạch kẻ.' },
    { sec: 'An toàn', name: 'Câu 9', pts: 1,
      text: 'Chơi gần bếp lửa, nồi nước sôi có an toàn không?',
      opts: o4('Không an toàn, dễ bị bỏng', 'Rất an toàn', 'Chỉ nóng một chút', 'Không sao'), ans: 'A',
      why: 'Bếp lửa, nước sôi gây bỏng nặng; phải tránh xa.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Số điện thoại nào gọi khi có cháy?',
      opts: o4('100', '114 (cứu hoả)', '200', '999'), ans: 'B',
      why: 'Khi có cháy gọi 114 để lính cứu hoả đến giúp.' },
  ],
},

/* ═══════════ ĐỀ 28 — ÔN TẬP TỔNG HỢP (1) ═══════════ */
{
  id: 8798, title: 'Đề 28 · Ôn tập tổng hợp (1)', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Em trai của bố, em gọi là gì?',
      opts: o4('Chú', 'Ông', 'Bác gái', 'Dì'), ans: 'A',
      why: 'Em trai của bố được gọi là chú.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Đồ dùng nào KHÔNG phải đồ dùng học tập?',
      opts: o4('Nồi cơm điện', 'Cái bút', 'Quyển vở', 'Cục tẩy'), ans: 'A',
      why: 'Nồi cơm điện là đồ dùng trong nhà, không phải đồ học tập.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Đèn giao thông màu xanh nghĩa là gì?',
      opts: o4('Dừng lại', 'Được đi', 'Đi chậm lại', 'Lùi xe'), ans: 'B',
      why: 'Đèn xanh nghĩa là được phép đi.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Cây lúa cho ta hạt gì để nấu cơm?',
      opts: o4('Hạt ngô', 'Hạt đậu', 'Hạt vừng', 'Hạt gạo'), ans: 'D',
      why: 'Cây lúa cho hạt thóc, xay ra gạo để nấu cơm.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào cho ta sữa uống?',
      opts: o4('Con gà', 'Con cá', 'Con vịt', 'Con bò'), ans: 'D',
      why: 'Bò (và dê) cho sữa để uống.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Em nhìn thấy mọi vật nhờ bộ phận nào?',
      opts: o4('Mắt', 'Tai', 'Mũi', 'Lưỡi'), ans: 'A',
      why: 'Mắt giúp em nhìn thấy mọi vật.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Mỗi ngày nên đánh răng ít nhất mấy lần?',
      opts: o4('Không cần', '1 tuần 1 lần', '2 lần', '1 tháng 1 lần'), ans: 'C',
      why: 'Nên đánh răng ít nhất 2 lần: sáng và tối.' },
    { sec: 'Bầu trời', name: 'Câu 8', pts: 1,
      text: 'Ban ngày, trời sáng là nhờ có gì?',
      opts: o4('Mặt Trăng', 'Ngôi sao', 'Bóng đèn', 'Mặt Trời'), ans: 'D',
      why: 'Ban ngày trời sáng nhờ ánh sáng Mặt Trời.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Người khám và chữa bệnh gọi là gì?',
      opts: o4('Nông dân', 'Thợ may', 'Bác sĩ', 'Tài xế'), ans: 'C',
      why: 'Bác sĩ là người khám và chữa bệnh.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Vật nào trẻ em không được nghịch?',
      opts: o4('Gấu bông', 'Bật lửa, diêm', 'Bút màu', 'Quả bóng'), ans: 'B',
      why: 'Bật lửa, diêm gây bỏng, cháy nên không được nghịch.' },
  ],
},

/* ═══════════ ĐỀ 29 — ÔN TẬP TỔNG HỢP (2) ═══════════ */
{
  id: 8799, title: 'Đề 29 · Ôn tập tổng hợp (2)', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Người sinh ra bố em, em gọi là gì?',
      opts: o4('Ông bà nội', 'Ông bà ngoại', 'Cô dì', 'Bạn bố'), ans: 'A',
      why: 'Bố mẹ của bố là ông nội, bà nội.' },
    { sec: 'Nhà ở', name: 'Câu 2', pts: 1,
      text: 'Phòng dùng để nấu ăn gọi là gì?',
      opts: o4('Phòng bếp', 'Phòng ngủ', 'Phòng khách', 'Nhà tắm'), ans: 'A',
      why: 'Nơi nấu ăn là phòng bếp.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Khi cô giáo giảng bài, em nên làm gì?',
      opts: o4('Nói chuyện riêng', 'Chú ý lắng nghe', 'Ngủ gật', 'Chạy ra ngoài'), ans: 'B',
      why: 'Chú ý lắng nghe cô giảng để hiểu bài.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Ngồi trên xe máy, em phải đội gì?',
      opts: o4('Mũ bảo hiểm', 'Mũ len', 'Nón lá', 'Khăn'), ans: 'A',
      why: 'Ngồi xe máy phải đội mũ bảo hiểm để an toàn.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Muốn cây sống và lớn, cần cho cây gì?',
      opts: o4('Dầu ăn', 'Bóng tối', 'Nước ngọt có ga', 'Nước và ánh sáng'), ans: 'D',
      why: 'Cây cần nước, ánh sáng và không khí để sống và lớn.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con vật nào được nuôi để trông nhà?',
      opts: o4('Con cá', 'Con ong', 'Con chó', 'Con bướm'), ans: 'C',
      why: 'Chó được nuôi để trông nhà, giữ nhà.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Con người có mấy giác quan chính?',
      opts: o4('3', '5', '4', '6'), ans: 'B',
      why: 'Có 5 giác quan: nhìn, nghe, ngửi, nếm và sờ.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Nước nào uống vào an toàn?',
      opts: o4('Nước ao', 'Nước đun sôi để nguội', 'Nước cống', 'Nước mương'), ans: 'B',
      why: 'Nên uống nước sạch, nước đun sôi để nguội.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Buổi sáng, Mặt Trời mọc ở hướng nào?',
      opts: o4('Hướng tây', 'Trên đỉnh đầu', 'Dưới đất', 'Hướng đông'), ans: 'D',
      why: 'Mặt Trời mọc ở hướng đông vào buổi sáng.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Chú công an giao thông làm nhiệm vụ gì?',
      opts: o4('Dạy học', 'Điều khiển, giữ trật tự giao thông', 'Trồng lúa', 'Bán hàng'), ans: 'B',
      why: 'Công an giao thông điều khiển và giữ trật tự giao thông.' },
  ],
},

/* ═══════════ ĐỀ 30 — ÔN TẬP TỔNG HỢP (3) ═══════════ */
{
  id: 8800, title: 'Đề 30 · Ôn tập tổng hợp (3)', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Anh chị em trong nhà nên đối xử với nhau thế nào?',
      opts: o4('Tranh giành nhau', 'Đánh nhau', 'Không chơi cùng', 'Nhường nhịn, thương yêu nhau'), ans: 'D',
      why: 'Anh chị em một nhà phải nhường nhịn, thương yêu nhau.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Có người lạ gõ cửa khi em ở nhà một mình, em nên làm gì?',
      opts: o4('Mở cửa cho vào', 'Đi theo họ', 'Cho họ tiền', 'Không mở cửa, gọi báo bố mẹ'), ans: 'D',
      why: 'Không tự mở cửa cho người lạ; gọi báo bố mẹ.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Để giữ lớp sạch, em nên làm gì với rác?',
      opts: o4('Vứt ra sàn', 'Bỏ vào thùng rác', 'Nhét vào ngăn bàn', 'Ném ra cửa sổ'), ans: 'B',
      why: 'Bỏ rác vào thùng giúp lớp luôn sạch đẹp.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Người đi bộ nên đi ở đâu?',
      opts: o4('Giữa lòng đường', 'Trước đầu ô tô', 'Chỗ nào cũng được', 'Trên vỉa hè'), ans: 'D',
      why: 'Người đi bộ đi trên vỉa hè; không có thì đi sát lề phải.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Cây xanh mang lại ích lợi gì?',
      opts: o4('Làm không khí bẩn', 'Cho bóng mát và không khí trong lành', 'Gây nóng hơn', 'Không có ích'), ans: 'B',
      why: 'Cây xanh cho bóng mát, quả, gỗ và không khí trong lành.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Việc nào KHÔNG nên làm với con vật?',
      opts: o4('Ném đá, đánh đập', 'Cho ăn', 'Vuốt ve nhẹ', 'Dọn chuồng sạch'), ans: 'A',
      why: 'Không được ném đá, đánh đập; phải đối xử nhẹ nhàng với con vật.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Em ngửi mùi thơm nhờ bộ phận nào?',
      opts: o4('Mắt', 'Tai', 'Mũi', 'Chân'), ans: 'C',
      why: 'Mũi giúp em ngửi mùi.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Ngoài ăn ngủ tốt, để khoẻ mạnh em nên làm gì?',
      opts: o4('Ngồi im cả ngày', 'Thức khuya', 'Nhịn ăn', 'Tập thể dục, vận động'), ans: 'D',
      why: 'Tập thể dục, vận động giúp cơ thể khoẻ mạnh.' },
    { sec: 'Thời tiết', name: 'Câu 9', pts: 1,
      text: 'Trời mưa, ra ngoài em cần mang gì?',
      opts: o4('Kính râm', 'Cái quạt', 'Đôi dép lê', 'Áo mưa hoặc ô'), ans: 'D',
      why: 'Trời mưa cần áo mưa hoặc ô để khỏi bị ướt.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Để nơi mình sống sạch đẹp, em nên làm gì?',
      opts: o4('Bỏ rác đúng nơi, trồng và chăm cây', 'Vứt rác xuống ao hồ', 'Bẻ cây công cộng', 'Vẽ bậy lên tường'), ans: 'A',
      why: 'Bỏ rác đúng chỗ và chăm cây giúp nơi mình sống sạch đẹp.' },
  ],
},

];

SUBJECTS.push({
  id: 'tnxh1', name: 'Tự nhiên & Xã hội', short: 'TN&XH 1', icon: '🌍', grade: 1,
  exams: TNXH1_EXAMS, ready: true,
  heroTitle: 'Tự nhiên và Xã hội lớp 1 — gia đình, trường học, cây cối, con vật, cơ thể và bầu trời',
  heroMeta: '📚 30 đề &nbsp;•&nbsp; 300 câu &nbsp;•&nbsp; ⏱ 15 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
