// TIN HỌC VÀ CÔNG NGHỆ — LỚP 3 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// Hai mạch nội dung:
//   TIN HỌC (Đề 1–6): các bộ phận máy tính & chức năng; thao tác chuột (nháy, nháy đúp,
//     kéo thả); bàn phím & tư thế ngồi đúng; thông tin & vật mang tin; thư mục và tệp
//     (lưu, mở); làm quen phần mềm đơn giản; dùng máy tính an toàn, đúng giờ, bảo vệ mắt.
//   CÔNG NGHỆ (Đề 7–10): tự nhiên & sản phẩm công nghệ; sản phẩm công nghệ trong gia đình
//     (đèn, quạt điện, nồi cơm điện, tivi) & cách dùng; an toàn khi dùng điện; làm và
//     bảo quản đồ dùng, đồ chơi thủ công đơn giản.

const TINCN3_EXAMS = [

/* ═══════════ ĐỀ 1 — CÁC BỘ PHẬN CỦA MÁY TÍNH ═══════════ */
{
  id: 9301, title: 'Đề 1 · Các bộ phận của máy tính', time: 20,
  questions: [
    { sec: 'Máy tính và em', name: 'Câu 1', pts: 1,
      text: 'Bộ phận nào của máy tính dùng để hiển thị hình ảnh, chữ cho ta nhìn?',
      opts: o4('Màn hình', 'Bàn phím', 'Chuột', 'Loa'), ans: 'A',
      why: 'Màn hình là bộ phận hiển thị hình ảnh và chữ để em nhìn thấy.' },
    { sec: 'Máy tính và em', name: 'Câu 2', pts: 1,
      text: 'Bộ phận nào dùng để gõ chữ và số vào máy tính?',
      opts: o4('Chuột', 'Bàn phím', 'Màn hình', 'Máy in'), ans: 'B',
      why: 'Bàn phím có các phím chữ, số... dùng để nhập thông tin vào máy tính.' },
    { sec: 'Máy tính và em', name: 'Câu 3', pts: 1,
      text: 'Bộ phận nào dùng để di chuyển con trỏ và nháy chọn trên màn hình?',
      opts: o4('Loa', 'Bàn phím', 'Chuột', 'Màn hình'), ans: 'C',
      why: 'Chuột dùng để di chuyển con trỏ và nháy chọn các đối tượng trên màn hình.' },
    { sec: 'Máy tính và em', name: 'Câu 4', pts: 1,
      text: 'Thân máy (khối hệ thống) của máy tính để bàn có vai trò gì?',
      opts: o4('Chỉ để trang trí', 'Xử lí thông tin, là "bộ óc" của máy tính', 'Phát ra âm thanh', 'Chiếu sáng cho phòng'), ans: 'B',
      why: 'Thân máy chứa các bộ phận xử lí, được xem như "bộ óc" điều khiển máy tính.' },
    { sec: 'Máy tính và em', name: 'Câu 5', pts: 1,
      text: 'Máy tính xách tay (laptop) khác máy tính để bàn ở điểm nào?',
      opts: o4('Không có màn hình', 'Không dùng được', 'Gọn nhẹ, gập lại và mang đi được', 'Chỉ chơi được nhạc'), ans: 'C',
      why: 'Máy tính xách tay gọn nhẹ, gập lại và mang đi mọi nơi được.' },
    { sec: 'Máy tính và em', name: 'Câu 6', pts: 1,
      text: 'Bộ phận nào giúp máy tính phát ra âm thanh?',
      opts: o4('Loa', 'Chuột', 'Bàn phím', 'Màn hình'), ans: 'A',
      why: 'Loa là bộ phận phát ra âm thanh của máy tính.' },
    { sec: 'Máy tính và em', name: 'Câu 7', pts: 1,
      text: 'Muốn in bài làm ra giấy, em cần dùng thiết bị nào?',
      opts: o4('Máy in', 'Chuột', 'Loa', 'Màn hình'), ans: 'A',
      why: 'Máy in giúp in nội dung trong máy tính ra giấy.' },
    { sec: 'Máy tính và em', name: 'Câu 8', pts: 1,
      text: 'Để máy tính hoạt động, ta cần cắm nguồn nào?',
      opts: o4('Nguồn nước', 'Nguồn điện', 'Ánh sáng', 'Không cần gì'), ans: 'B',
      why: 'Máy tính là thiết bị điện nên cần nguồn điện để hoạt động.' },
    { sec: 'Máy tính và em', name: 'Câu 9', pts: 1,
      text: 'Máy tính có thể giúp em làm việc gì?',
      opts: o4('Học tập, vẽ tranh, xem phim, nghe nhạc', 'Nấu cơm', 'Giặt quần áo', 'Tưới cây ngoài vườn'), ans: 'A',
      why: 'Máy tính giúp học tập, vẽ, xem phim, nghe nhạc và nhiều việc khác.' },
    { sec: 'Máy tính và em', name: 'Câu 10', pts: 1,
      text: 'Máy tính bảng thường được điều khiển bằng cách nào?',
      opts: o4('Chạm ngón tay lên màn hình cảm ứng', 'Thổi vào màn hình', 'Lắc thật mạnh', 'Nói to vào loa'), ans: 'A',
      why: 'Máy tính bảng dùng màn hình cảm ứng, em chạm ngón tay để điều khiển.' },
  ],
},

/* ═══════════ ĐỀ 2 — THAO TÁC VỚI CHUỘT ═══════════ */
{
  id: 9302, title: 'Đề 2 · Thao tác với chuột máy tính', time: 20,
  questions: [
    { sec: 'Chuột máy tính', name: 'Câu 1', pts: 1,
      text: 'Nhấn nhanh một lần nút trái chuột gọi là thao tác gì?',
      opts: o4('Nháy chuột (nháy đơn)', 'Nháy đúp', 'Kéo thả', 'Cuộn chuột'), ans: 'A',
      why: 'Nhấn nhanh một lần nút trái chuột gọi là nháy chuột (nháy đơn).' },
    { sec: 'Chuột máy tính', name: 'Câu 2', pts: 1,
      text: 'Nhấn nhanh liên tiếp hai lần nút trái chuột gọi là gì?',
      opts: o4('Nháy đơn', 'Nháy đúp (nháy kép)', 'Kéo thả', 'Nháy nút phải'), ans: 'B',
      why: 'Nhấn nhanh hai lần liên tiếp nút trái chuột gọi là nháy đúp.' },
    { sec: 'Chuột máy tính', name: 'Câu 3', pts: 1,
      text: 'Muốn di chuyển một biểu tượng đến chỗ khác, em dùng thao tác nào?',
      opts: o4('Nháy đơn', 'Kéo thả', 'Cuộn chuột', 'Nháy nút phải'), ans: 'B',
      why: 'Kéo thả là giữ nút trái chuột, di chuyển rồi thả ra để chuyển đối tượng đi.' },
    { sec: 'Chuột máy tính', name: 'Câu 4', pts: 1,
      text: 'Vệt nhỏ di chuyển theo chuột trên màn hình gọi là gì?',
      opts: o4('Con trỏ chuột', 'Cửa sổ', 'Biểu tượng', 'Bàn phím'), ans: 'A',
      why: 'Con trỏ chuột là dấu nhỏ di chuyển trên màn hình theo tay em điều khiển.' },
    { sec: 'Chuột máy tính', name: 'Câu 5', pts: 1,
      text: 'Một con chuột thường có mấy nút chính?',
      opts: o4('Một nút', 'Hai nút và một bánh lăn ở giữa', 'Năm nút', 'Không có nút nào'), ans: 'B',
      why: 'Chuột thường có nút trái, nút phải và một bánh lăn (con lăn) ở giữa.' },
    { sec: 'Chuột máy tính', name: 'Câu 6', pts: 1,
      text: 'Bánh lăn (con lăn) ở giữa chuột dùng để làm gì?',
      opts: o4('Cuộn trang lên, xuống', 'Gõ chữ', 'Tắt máy', 'Tăng âm lượng loa'), ans: 'A',
      why: 'Bánh lăn giúp cuộn nội dung trang lên hoặc xuống.' },
    { sec: 'Chuột máy tính', name: 'Câu 7', pts: 1,
      text: 'Muốn mở một thư mục trên màn hình, em thường làm gì?',
      opts: o4('Gõ tên thật to', 'Rút dây điện ra', 'Lắc con chuột', 'Nháy đúp vào thư mục đó'), ans: 'D',
      why: 'Nháy đúp vào biểu tượng thư mục hoặc tệp để mở nó ra.' },
    { sec: 'Chuột máy tính', name: 'Câu 8', pts: 1,
      text: 'Tay đặt lên chuột đúng cách là như thế nào?',
      opts: o4('Đặt nhẹ nhàng, ngón trỏ ở nút trái', 'Nắm thật chặt và bóp mạnh', 'Chỉ dùng một ngón út', 'Cầm chuột lật ngửa lên'), ans: 'A',
      why: 'Bàn tay đặt nhẹ lên chuột, ngón trỏ đặt ở nút trái để nháy cho thoải mái.' },
    { sec: 'Chuột máy tính', name: 'Câu 9', pts: 1,
      text: 'Nút phải chuột thường dùng để làm gì?',
      opts: o4('Tắt màn hình', 'Gõ số', 'Mở bảng chọn (thực đơn) các lệnh', 'Chỉnh độ sáng phòng'), ans: 'C',
      why: 'Nháy nút phải chuột thường mở ra bảng chọn gồm các lệnh có thể thực hiện.' },
    { sec: 'Chuột máy tính', name: 'Câu 10', pts: 1,
      text: 'Khi dùng chuột, mặt bàn nên như thế nào?',
      opts: o4('Bằng phẳng để chuột di chuyển dễ dàng', 'Gồ ghề, nhiều nước', 'Dốc nghiêng', 'Đầy bụi bẩn'), ans: 'A',
      why: 'Mặt bàn phẳng, sạch giúp chuột di chuyển trơn tru, con trỏ đi đúng ý.' },
  ],
},

/* ═══════════ ĐỀ 3 — BÀN PHÍM VÀ TƯ THẾ NGỒI ═══════════ */
{
  id: 9303, title: 'Đề 3 · Bàn phím và tư thế ngồi đúng', time: 20,
  questions: [
    { sec: 'Bàn phím', name: 'Câu 1', pts: 1,
      text: 'Bàn phím máy tính dùng để làm gì?',
      opts: o4('Nhập chữ, số và kí hiệu vào máy tính', 'Nghe nhạc', 'Chiếu hình ảnh', 'In ra giấy'), ans: 'A',
      why: 'Bàn phím dùng để gõ chữ, số và kí hiệu, đưa thông tin vào máy tính.' },
    { sec: 'Bàn phím', name: 'Câu 2', pts: 1,
      text: 'Phím dài nhất ở dưới cùng bàn phím dùng để làm gì?',
      opts: o4('Tắt máy', 'Xoá cả bài', 'Tạo khoảng cách (dấu cách) giữa các chữ', 'Tăng âm lượng'), ans: 'C',
      why: 'Phím cách (Space) là phím dài nhất, dùng để tạo khoảng trống giữa các chữ.' },
    { sec: 'Bàn phím', name: 'Câu 3', pts: 1,
      text: 'Phím Enter thường dùng để làm gì khi gõ văn bản?',
      opts: o4('Xoá hết chữ', 'Xuống dòng mới', 'Tô màu chữ', 'Phóng to màn hình'), ans: 'B',
      why: 'Phím Enter dùng để xuống dòng mới khi đang gõ văn bản.' },
    { sec: 'Bàn phím', name: 'Câu 4', pts: 1,
      text: 'Gõ nhầm một chữ, em dùng phím nào để xoá chữ vừa gõ?',
      opts: o4('Phím cách', 'Phím Backspace (phím xoá lùi)', 'Phím Enter', 'Phím Shift'), ans: 'B',
      why: 'Phím Backspace (xoá lùi) xoá kí tự đứng ngay trước con trỏ.' },
    { sec: 'Bàn phím', name: 'Câu 5', pts: 1,
      text: 'Khi gõ bàn phím, hai tay em nên đặt thế nào?',
      opts: o4('Đặt nhẹ trên bàn phím, các ngón cong tự nhiên', 'Chỉ dùng một ngón chọc mạnh', 'Đấm vào bàn phím', 'Để tay dưới gầm bàn'), ans: 'A',
      why: 'Hai tay đặt nhẹ trên bàn phím, các ngón cong tự nhiên để gõ đỡ mỏi.' },
    { sec: 'Tư thế ngồi', name: 'Câu 6', pts: 1,
      text: 'Tư thế ngồi học máy tính đúng là như thế nào?',
      opts: o4('Nằm ra ghế', 'Cúi sát mặt vào màn hình', 'Vắt chân lên bàn', 'Ngồi thẳng lưng, hai chân đặt trên sàn'), ans: 'D',
      why: 'Ngồi thẳng lưng, hai chân chạm sàn giúp không bị mỏi và vẹo cột sống.' },
    { sec: 'Tư thế ngồi', name: 'Câu 7', pts: 1,
      text: 'Khoảng cách từ mắt đến màn hình nên như thế nào?',
      opts: o4('Vừa phải, khoảng một cánh tay, không sát quá', 'Sát tận màn hình', 'Càng xa càng tốt, nhìn không rõ', 'Nhắm mắt lại'), ans: 'A',
      why: 'Ngồi cách màn hình khoảng một cánh tay để bảo vệ mắt, tránh mỏi mắt.' },
    { sec: 'Tư thế ngồi', name: 'Câu 8', pts: 1,
      text: 'Ánh sáng nơi ngồi học máy tính nên thế nào?',
      opts: o4('Đủ sáng, không quá chói cũng không quá tối', 'Càng tối càng tốt', 'Chiếu đèn thẳng vào mắt', 'Không cần ánh sáng'), ans: 'A',
      why: 'Nơi học cần đủ sáng, không chói cũng không tối để mắt đỡ mỏi.' },
    { sec: 'Tư thế ngồi', name: 'Câu 9', pts: 1,
      text: 'Ngồi máy tính lâu, thỉnh thoảng em nên làm gì để mắt đỡ mỏi?',
      opts: o4('Nhìn màn hình chằm chằm không nghỉ', 'Nhìn ra xa, nghỉ ngơi vài phút', 'Dụi mắt thật mạnh', 'Tắt hết đèn'), ans: 'B',
      why: 'Sau một lúc nên nhìn ra xa và nghỉ vài phút để mắt được thư giãn.' },
    { sec: 'Tư thế ngồi', name: 'Câu 10', pts: 1,
      text: 'Vì sao phải giữ tư thế ngồi đúng khi dùng máy tính?',
      opts: o4('Để không mỏi, không vẹo lưng và bảo vệ mắt', 'Để trông đẹp mắt', 'Để máy chạy nhanh hơn', 'Để tốn ít điện hơn'), ans: 'A',
      why: 'Tư thế đúng giúp cơ thể không mỏi, tránh cong vẹo cột sống và bảo vệ mắt.' },
  ],
},

/* ═══════════ ĐỀ 4 — THÔNG TIN VÀ VẬT MANG TIN ═══════════ */
{
  id: 9304, title: 'Đề 4 · Thông tin và vật mang tin', time: 20,
  questions: [
    { sec: 'Thông tin', name: 'Câu 1', pts: 1,
      text: 'Em biết ngày mai trời mưa nhờ nghe dự báo thời tiết. Đó là gì?',
      opts: o4('Một thông tin', 'Một cái bàn', 'Một loại thức ăn', 'Một trò chơi'), ans: 'A',
      why: 'Điều em biết được (ngày mai trời mưa) chính là một thông tin.' },
    { sec: 'Thông tin', name: 'Câu 2', pts: 1,
      text: 'Em nhận thông tin về màu sắc bông hoa nhờ giác quan nào?',
      opts: o4('Tai (nghe)', 'Mũi (ngửi)', 'Mắt (nhìn)', 'Lưỡi (nếm)'), ans: 'C',
      why: 'Màu sắc được nhận biết bằng mắt qua việc nhìn.' },
    { sec: 'Thông tin', name: 'Câu 3', pts: 1,
      text: 'Nghe tiếng trống trường báo vào lớp, em nhận thông tin bằng giác quan nào?',
      opts: o4('Tai (nghe)', 'Mắt (nhìn)', 'Da (sờ)', 'Mũi (ngửi)'), ans: 'A',
      why: 'Âm thanh tiếng trống được nhận biết bằng tai qua việc nghe.' },
    { sec: 'Vật mang tin', name: 'Câu 4', pts: 1,
      text: 'Quyển sách chứa chữ và hình để em đọc. Sách là gì?',
      opts: o4('Một thiết bị điện', 'Một vật mang tin', 'Một món ăn', 'Một loại cây'), ans: 'B',
      why: 'Sách chứa (mang) thông tin nên gọi là vật mang tin.' },
    { sec: 'Vật mang tin', name: 'Câu 5', pts: 1,
      text: 'Vật nào sau đây là vật mang tin?',
      opts: o4('Tờ báo, tấm biển chỉ đường, đĩa CD', 'Cái ghế', 'Cục tẩy', 'Viên gạch'), ans: 'A',
      why: 'Tờ báo, biển chỉ đường, đĩa CD đều chứa thông tin nên là vật mang tin.' },
    { sec: 'Vật mang tin', name: 'Câu 6', pts: 1,
      text: 'Tấm biển báo "Cấm đi ngược chiều" cho ta biết điều gì?',
      opts: o4('Một món quà', 'Một trò chơi', 'Một bài hát', 'Một thông tin để đi đúng luật'), ans: 'D',
      why: 'Biển báo mang thông tin giúp mọi người tham gia giao thông đúng luật.' },
    { sec: 'Thông tin', name: 'Câu 7', pts: 1,
      text: 'Máy tính giúp em làm gì với thông tin?',
      opts: o4('Nấu chín thông tin', 'Trồng cây thông tin', 'Lưu trữ, tìm kiếm và xử lí thông tin', 'Giặt sạch thông tin'), ans: 'C',
      why: 'Máy tính giúp lưu trữ, tìm kiếm và xử lí thông tin nhanh chóng.' },
    { sec: 'Thông tin', name: 'Câu 8', pts: 1,
      text: 'Ngửi thấy mùi thơm của cơm chín là em nhận thông tin bằng giác quan nào?',
      opts: o4('Mũi (ngửi)', 'Mắt (nhìn)', 'Tai (nghe)', 'Tay (sờ)'), ans: 'A',
      why: 'Mùi được nhận biết bằng mũi qua việc ngửi.' },
    { sec: 'Vật mang tin', name: 'Câu 9', pts: 1,
      text: 'Thẻ nhớ, USB dùng để làm gì?',
      opts: o4('Làm đồ chơi', 'Lưu trữ dữ liệu, mang thông tin đi nơi khác', 'Ăn cho no', 'Tưới cây'), ans: 'B',
      why: 'Thẻ nhớ, USB là vật mang tin dùng để lưu và mang dữ liệu đi nơi khác.' },
    { sec: 'Thông tin', name: 'Câu 10', pts: 1,
      text: 'Vì sao thông tin lại quan trọng với chúng ta?',
      opts: o4('Giúp ta hiểu biết và quyết định đúng', 'Làm ta mệt hơn', 'Không có ích gì', 'Chỉ để trang trí'), ans: 'A',
      why: 'Nhờ có thông tin, ta hiểu biết sự việc và đưa ra quyết định đúng đắn.' },
  ],
},

/* ═══════════ ĐỀ 5 — THƯ MỤC VÀ TỆP ═══════════ */
{
  id: 9305, title: 'Đề 5 · Thư mục, tệp và lưu bài', time: 20,
  questions: [
    { sec: 'Thư mục và tệp', name: 'Câu 1', pts: 1,
      text: 'Nơi chứa các tệp và giúp sắp xếp chúng gọn gàng gọi là gì?',
      opts: o4('Thư mục', 'Con chuột', 'Bàn phím', 'Màn hình'), ans: 'A',
      why: 'Thư mục dùng để chứa và sắp xếp các tệp cho gọn gàng, dễ tìm.' },
    { sec: 'Thư mục và tệp', name: 'Câu 2', pts: 1,
      text: 'Một bài vẽ, một bài văn được lưu trong máy tính thành cái gì?',
      opts: o4('Một cái ghế', 'Một cục tẩy', 'Một tệp (tập tin)', 'Một bóng đèn'), ans: 'C',
      why: 'Mỗi bài làm được lưu trong máy tính thành một tệp (tập tin).' },
    { sec: 'Thư mục và tệp', name: 'Câu 3', pts: 1,
      text: 'Vì sao nên đặt tên cho thư mục và tệp?',
      opts: o4('Để dễ tìm và biết bên trong chứa gì', 'Để tốn nhiều điện hơn', 'Để máy chạy chậm lại', 'Không cần thiết'), ans: 'A',
      why: 'Đặt tên rõ ràng giúp ta dễ tìm và biết thư mục, tệp chứa nội dung gì.' },
    { sec: 'Thư mục và tệp', name: 'Câu 4', pts: 1,
      text: 'Làm xong bài trên máy tính, em nên làm gì để không bị mất?',
      opts: o4('Tắt phụt máy ngay', 'Lưu (save) lại bài', 'Rút điện đột ngột', 'Đóng máy không lưu'), ans: 'B',
      why: 'Phải lưu (save) bài lại thì lần sau mới mở ra dùng tiếp được, khỏi mất công.' },
    { sec: 'Thư mục và tệp', name: 'Câu 5', pts: 1,
      text: 'Muốn xem lại bài đã lưu, em làm gì?',
      opts: o4('Mở tệp bài đó ra', 'Gõ tên thật to', 'Lắc con chuột', 'Vẽ lại từ đầu'), ans: 'A',
      why: 'Em tìm tệp đã lưu và mở nó ra để xem lại hoặc làm tiếp.' },
    { sec: 'Thư mục và tệp', name: 'Câu 6', pts: 1,
      text: 'Trong một thư mục có thể chứa những gì?',
      opts: o4('Chỉ chứa được một tệp', 'Không chứa được gì', 'Chỉ chứa nước', 'Nhiều tệp và cả các thư mục con khác'), ans: 'D',
      why: 'Một thư mục có thể chứa nhiều tệp và cả các thư mục con bên trong.' },
    { sec: 'Thư mục và tệp', name: 'Câu 7', pts: 1,
      text: 'Sắp xếp bài vẽ vào thư mục "Tranh vẽ", bài văn vào thư mục "Bài văn" giúp gì?',
      opts: o4('Tìm bài nhanh và gọn gàng hơn', 'Làm mất bài', 'Máy hỏng nhanh', 'Không giúp gì'), ans: 'A',
      why: 'Phân loại tệp vào đúng thư mục giúp gọn gàng và tìm lại nhanh hơn.' },
    { sec: 'Thư mục và tệp', name: 'Câu 8', pts: 1,
      text: 'Biểu tượng nhỏ hình cặp giấy màu vàng trên màn hình thường là gì?',
      opts: o4('Một con chuột', 'Một thư mục', 'Một cái loa', 'Một máy in'), ans: 'B',
      why: 'Biểu tượng hình cặp (bìa) màu vàng thường là một thư mục.' },
    { sec: 'Thư mục và tệp', name: 'Câu 9', pts: 1,
      text: 'Khi không cần một tệp nữa, em có thể làm gì?',
      opts: o4('Xoá tệp đó đi cho gọn', 'Đập vỡ màn hình', 'Rút dây điện', 'Đổ nước vào máy'), ans: 'A',
      why: 'Tệp không dùng nữa có thể xoá đi để máy tính gọn gàng hơn.' },
    { sec: 'Thư mục và tệp', name: 'Câu 10', pts: 1,
      text: 'Đặt tên tệp thế nào là hợp lí?',
      opts: o4('Tên thật dài và khó hiểu', 'Toàn kí hiệu lạ', 'Tên ngắn gọn, nói đúng nội dung bài', 'Không đặt tên gì'), ans: 'C',
      why: 'Tên tệp nên ngắn gọn, đúng nội dung để sau này dễ nhận ra và tìm lại.' },
  ],
},

/* ═══════════ ĐỀ 6 — PHẦN MỀM VÀ SỬ DỤNG MÁY TÍNH AN TOÀN ═══════════ */
{
  id: 9306, title: 'Đề 6 · Phần mềm và dùng máy tính an toàn', time: 20,
  questions: [
    { sec: 'Phần mềm', name: 'Câu 1', pts: 1,
      text: 'Chương trình giúp em vẽ tranh trên máy tính gọi là gì?',
      opts: o4('Phần mềm (chương trình) vẽ', 'Con chuột', 'Vật mang tin', 'Ổ điện'), ans: 'A',
      why: 'Phần mềm vẽ là chương trình giúp em vẽ tranh trên máy tính.' },
    { sec: 'Phần mềm', name: 'Câu 2', pts: 1,
      text: 'Muốn khởi động một phần mềm, em thường làm gì?',
      opts: o4('Rút dây điện', 'Nháy đúp vào biểu tượng của phần mềm', 'Gõ Enter liên tục', 'Lắc màn hình'), ans: 'B',
      why: 'Thường nháy đúp vào biểu tượng của phần mềm để khởi động (mở) nó.' },
    { sec: 'Phần mềm', name: 'Câu 3', pts: 1,
      text: 'Trong phần mềm vẽ, muốn tô màu ta thường dùng công cụ nào?',
      opts: o4('Công cụ tô màu (thùng sơn)', 'Cái kéo cắt giấy', 'Cục tẩy bảng', 'Phím Enter'), ans: 'A',
      why: 'Phần mềm vẽ có công cụ tô màu (thùng sơn) để đổ màu cho vùng đã chọn.' },
    { sec: 'Phần mềm', name: 'Câu 4', pts: 1,
      text: 'Phần mềm trò chơi học tập giúp em điều gì?',
      opts: o4('Làm hỏng máy tính', 'Không có ích gì', 'Vừa chơi vừa học, luyện tư duy', 'Chỉ tốn điện'), ans: 'C',
      why: 'Phần mềm trò chơi học tập giúp em vừa chơi vừa học, rèn luyện tư duy.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Mỗi ngày nên dùng máy tính trong bao lâu là hợp lí với học sinh lớp 3?',
      opts: o4('Suốt cả ngày không nghỉ', 'Thức khuya chơi máy', 'Càng lâu càng tốt', 'Một thời gian vừa phải, có nghỉ giải lao'), ans: 'D',
      why: 'Chỉ nên dùng máy tính vừa phải và có nghỉ giải lao để bảo vệ mắt và sức khoẻ.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Việc nào KHÔNG an toàn khi dùng máy tính?',
      opts: o4('Cắm, rút điện bằng tay ướt', 'Ngồi thẳng lưng', 'Lưu bài trước khi tắt máy', 'Nghỉ ngơi cho đỡ mỏi mắt'), ans: 'A',
      why: 'Dùng tay ướt cắm, rút điện rất nguy hiểm, dễ bị điện giật.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Khi dùng máy tính có nối mạng, em nên làm gì?',
      opts: o4('Hỏi ý kiến người lớn, không nói tên, địa chỉ cho người lạ', 'Cho người lạ số điện thoại nhà', 'Hẹn gặp người lạ', 'Bấm vào mọi đường liên kết'), ans: 'A',
      why: 'Trên mạng cần hỏi người lớn và không tiết lộ thông tin cá nhân cho người lạ.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Khi máy tính bị trục trặc, em nên làm gì?',
      opts: o4('Tự tháo tung máy ra', 'Báo thầy cô hoặc người lớn', 'Đập vào máy', 'Đổ nước cho mát'), ans: 'B',
      why: 'Máy hỏng thì báo thầy cô, người lớn; không tự ý tháo hay đập máy.' },
    { sec: 'An toàn', name: 'Câu 9', pts: 1,
      text: 'Tắt máy tính đúng cách là như thế nào?',
      opts: o4('Rút phích điện đột ngột', 'Ấn giữ nút liên tục cho nóng máy', 'Chọn lệnh tắt máy (Shut down) rồi mới ngắt điện', 'Đóng nắp và bỏ đi'), ans: 'C',
      why: 'Nên chọn lệnh tắt máy (Shut down) để máy tắt an toàn, không hỏng dữ liệu.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Để bảo vệ mắt khi dùng máy tính, em nên tránh điều gì?',
      opts: o4('Nhìn màn hình quá gần và quá lâu', 'Ngồi cách màn hình một cánh tay', 'Nghỉ ngơi nhìn ra xa', 'Bật đủ ánh sáng'), ans: 'A',
      why: 'Nhìn màn hình quá gần và quá lâu khiến mắt mỏi, hại mắt; cần tránh.' },
  ],
},

/* ═══════════ ĐỀ 7 — TỰ NHIÊN VÀ SẢN PHẨM CÔNG NGHỆ ═══════════ */
{
  id: 9307, title: 'Đề 7 · Tự nhiên và sản phẩm công nghệ', time: 20,
  questions: [
    { sec: 'Công nghệ quanh em', name: 'Câu 1', pts: 1,
      text: 'Vật nào sau đây là sản phẩm do con người làm ra (sản phẩm công nghệ)?',
      opts: o4('Cái quạt điện', 'Con sông', 'Đám mây', 'Ngọn núi'), ans: 'A',
      why: 'Quạt điện do con người chế tạo nên là sản phẩm công nghệ.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 2', pts: 1,
      text: 'Vật nào sau đây có sẵn trong tự nhiên?',
      opts: o4('Cái bàn', 'Hòn đá, cây cối, dòng sông', 'Chiếc tivi', 'Bóng đèn'), ans: 'B',
      why: 'Hòn đá, cây cối, dòng sông có sẵn trong tự nhiên, không do con người tạo ra.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 3', pts: 1,
      text: 'Nhóm nào dưới đây đều là sản phẩm công nghệ?',
      opts: o4('Cây xanh, con chim, đám mây', 'Bàn ghế, xe đạp, đèn điện', 'Núi, sông, biển', 'Mưa, nắng, gió'), ans: 'B',
      why: 'Bàn ghế, xe đạp, đèn điện đều do con người làm ra, là sản phẩm công nghệ.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 4', pts: 1,
      text: 'Sản phẩm công nghệ ra đời nhằm mục đích gì?',
      opts: o4('Làm hại con người', 'Không có tác dụng gì', 'Phục vụ đời sống con người tiện lợi hơn', 'Chỉ để nhìn cho đẹp'), ans: 'C',
      why: 'Con người tạo ra sản phẩm công nghệ để cuộc sống tiện lợi, dễ dàng hơn.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 5', pts: 1,
      text: 'Vật nào giúp chúng ta đi lại nhanh hơn?',
      opts: o4('Hòn đá', 'Đám mây', 'Cây cỏ', 'Xe đạp, xe máy, ô tô'), ans: 'D',
      why: 'Xe đạp, xe máy, ô tô là sản phẩm công nghệ giúp ta đi lại nhanh hơn.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 6', pts: 1,
      text: 'Cái nào dưới đây KHÔNG phải sản phẩm công nghệ?',
      opts: o4('Ánh nắng Mặt Trời', 'Chiếc điện thoại', 'Cái nồi cơm điện', 'Bóng đèn'), ans: 'A',
      why: 'Ánh nắng Mặt Trời có trong tự nhiên, không do con người tạo ra.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 7', pts: 1,
      text: 'Trước khi có đèn điện, ban đêm người ta thường thắp gì để sáng?',
      opts: o4('Đèn dầu, nến', 'Tivi', 'Máy tính', 'Tủ lạnh'), ans: 'A',
      why: 'Xưa kia người ta thắp đèn dầu, nến; nay có đèn điện tiện và sáng hơn.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 8', pts: 1,
      text: 'Chiếc đồng hồ giúp em biết điều gì?',
      opts: o4('Biết nấu cơm', 'Biết giờ, xem thời gian', 'Biết bay lên trời', 'Biết bơi'), ans: 'B',
      why: 'Đồng hồ là sản phẩm công nghệ giúp ta xem giờ, biết thời gian.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 9', pts: 1,
      text: 'Đồ dùng công nghệ nào giúp giữ thức ăn tươi lâu trong gia đình?',
      opts: o4('Tủ lạnh', 'Cái chổi', 'Cái thớt', 'Cái rổ'), ans: 'A',
      why: 'Tủ lạnh làm lạnh, giúp thức ăn tươi lâu, không bị ôi thiu nhanh.' },
    { sec: 'Công nghệ quanh em', name: 'Câu 10', pts: 1,
      text: 'Sản phẩm công nghệ nào giúp em học tập và giải trí?',
      opts: o4('Hòn sỏi', 'Vũng nước', 'Máy tính, tivi, sách điện tử', 'Đống lá khô'), ans: 'C',
      why: 'Máy tính, tivi, sách điện tử giúp em học tập và giải trí.' },
  ],
},

/* ═══════════ ĐỀ 8 — ĐỒ DÙNG ĐIỆN TRONG GIA ĐÌNH ═══════════ */
{
  id: 9308, title: 'Đề 8 · Đồ dùng điện trong gia đình', time: 20,
  questions: [
    { sec: 'Đồ dùng gia đình', name: 'Câu 1', pts: 1,
      text: 'Đèn điện trong nhà dùng để làm gì?',
      opts: o4('Chiếu sáng', 'Nấu cơm', 'Làm mát', 'Giặt quần áo'), ans: 'A',
      why: 'Đèn điện dùng để chiếu sáng cho ngôi nhà.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 2', pts: 1,
      text: 'Quạt điện dùng để làm gì?',
      opts: o4('Chiếu sáng', 'Tạo gió, làm mát', 'Nấu cơm', 'Xem phim'), ans: 'B',
      why: 'Quạt điện quay tạo gió, giúp làm mát khi trời nóng.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 3', pts: 1,
      text: 'Nồi cơm điện dùng để làm gì?',
      opts: o4('Nấu chín cơm', 'Làm mát phòng', 'Chiếu sáng', 'Xem tivi'), ans: 'A',
      why: 'Nồi cơm điện dùng để nấu và giữ ấm cơm.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 4', pts: 1,
      text: 'Tivi trong gia đình dùng để làm gì?',
      opts: o4('Nấu ăn', 'Quét nhà', 'Xem chương trình, phim, tin tức', 'Tưới cây'), ans: 'C',
      why: 'Tivi giúp cả nhà xem phim, tin tức và các chương trình giải trí.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 5', pts: 1,
      text: 'Trước khi dùng một đồ dùng điện mới, em nên làm gì?',
      opts: o4('Đọc hướng dẫn hoặc hỏi người lớn', 'Tự ý bật lung tung', 'Tháo tung ra xem', 'Cho vào nước'), ans: 'A',
      why: 'Nên đọc hướng dẫn hoặc hỏi người lớn để dùng đúng cách và an toàn.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 6', pts: 1,
      text: 'Dùng xong quạt điện, em nên làm gì để tiết kiệm điện?',
      opts: o4('Để quạt chạy suốt', 'Bật thêm nhiều quạt', 'Mở cửa cho gió bay', 'Tắt quạt khi không dùng'), ans: 'D',
      why: 'Tắt quạt (và các đồ điện) khi không dùng giúp tiết kiệm điện.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 7', pts: 1,
      text: 'Bóng đèn nào dưới đây tiết kiệm điện hơn?',
      opts: o4('Đèn để cháy cả ngày lẫn đêm', 'Đèn LED (đèn tiết kiệm điện)', 'Đèn bật khi trời đang sáng', 'Bật tất cả các đèn cùng lúc'), ans: 'B',
      why: 'Đèn LED chiếu sáng tốt mà tốn ít điện hơn nhiều loại đèn cũ.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 8', pts: 1,
      text: 'Ban ngày trời sáng, để tiết kiệm điện ta nên làm gì?',
      opts: o4('Tắt bớt đèn, tận dụng ánh sáng tự nhiên', 'Bật hết đèn trong nhà', 'Kéo kín rèm rồi bật đèn', 'Bật cả đèn ngoài sân'), ans: 'A',
      why: 'Ban ngày nên mở cửa lấy ánh sáng tự nhiên và tắt bớt đèn cho đỡ tốn điện.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 9', pts: 1,
      text: 'Khi nồi cơm điện đang nấu, phần nào của nồi rất nóng, không nên sờ?',
      opts: o4('Sàn nhà', 'Cái bàn bên cạnh', 'Nắp thoát hơi và thân nồi', 'Cái ghế'), ans: 'C',
      why: 'Khi nấu, hơi và thân nồi rất nóng, sờ vào dễ bị bỏng.' },
    { sec: 'Đồ dùng gia đình', name: 'Câu 10', pts: 1,
      text: 'Đồ dùng điện giúp ích gì cho gia đình?',
      opts: o4('Làm việc nhà nhanh, tiện lợi hơn', 'Làm nhà bừa bộn hơn', 'Không có ích gì', 'Chỉ để bày cho đẹp'), ans: 'A',
      why: 'Đồ dùng điện giúp việc nhà nhanh, nhẹ nhàng và tiện lợi hơn.' },
  ],
},

/* ═══════════ ĐỀ 9 — AN TOÀN KHI DÙNG ĐIỆN ═══════════ */
{
  id: 9309, title: 'Đề 9 · An toàn khi dùng điện trong nhà', time: 20,
  questions: [
    { sec: 'An toàn điện', name: 'Câu 1', pts: 1,
      text: 'Vì sao không được dùng tay ướt cắm hoặc rút phích điện?',
      opts: o4('Vì rất dễ bị điện giật', 'Vì tốn điện', 'Vì làm bẩn tay', 'Vì mất thời gian'), ans: 'A',
      why: 'Tay ướt dẫn điện, cắm rút phích khi tay ướt rất dễ bị điện giật, nguy hiểm.' },
    { sec: 'An toàn điện', name: 'Câu 2', pts: 1,
      text: 'Em có nên chọc que hay ngón tay vào ổ cắm điện không?',
      opts: o4('Có, cho vui', 'Có, nếu que bằng sắt', 'Có, khi buồn chán', 'Không, vì rất nguy hiểm, dễ bị điện giật'), ans: 'D',
      why: 'Tuyệt đối không chọc vật gì vào ổ điện vì dễ bị điện giật, rất nguy hiểm.' },
    { sec: 'An toàn điện', name: 'Câu 3', pts: 1,
      text: 'Thấy dây điện bị đứt hoặc hở, em nên làm gì?',
      opts: o4('Tránh xa và báo người lớn', 'Lấy tay nối lại', 'Dùng chân đá vào', 'Đổ nước lên'), ans: 'A',
      why: 'Dây điện hở rất nguy hiểm; phải tránh xa và báo ngay cho người lớn.' },
    { sec: 'An toàn điện', name: 'Câu 4', pts: 1,
      text: 'Rút phích cắm điện ra khỏi ổ, em nên cầm vào đâu?',
      opts: o4('Nắm dây kéo mạnh', 'Cầm vào thân phích cắm', 'Cầm vào chỗ dây bị hở', 'Dùng kéo cắt dây'), ans: 'B',
      why: 'Phải cầm thân phích để rút; kéo dây dễ làm đứt dây, gây nguy hiểm.' },
    { sec: 'An toàn điện', name: 'Câu 5', pts: 1,
      text: 'Có nên để đồ dùng điện gần nước không?',
      opts: o4('Không, vì nước dẫn điện, dễ gây nguy hiểm', 'Có, cho mát máy', 'Có, để rửa cho sạch', 'Có, nếu là mùa hè'), ans: 'A',
      why: 'Nước dẫn điện; để đồ điện gần nước dễ gây chập, điện giật nên phải tránh.' },
    { sec: 'An toàn điện', name: 'Câu 6', pts: 1,
      text: 'Thấy em bé định nghịch ổ cắm điện, em nên làm gì?',
      opts: o4('Cùng nghịch cho vui', 'Đưa thêm đồ chơi để chọc vào', 'Ngăn lại và báo người lớn', 'Làm ngơ bỏ đi'), ans: 'C',
      why: 'Cần ngăn em bé và báo người lớn để tránh tai nạn điện giật.' },
    { sec: 'An toàn điện', name: 'Câu 7', pts: 1,
      text: 'Khi trời mưa có sấm sét, em KHÔNG nên làm gì?',
      opts: o4('Trú dưới gốc cây to giữa trời, nghịch đồ điện', 'Vào trong nhà', 'Tắt bớt thiết bị điện', 'Tránh xa cửa sổ'), ans: 'A',
      why: 'Trời sấm sét không nên đứng dưới cây to hay nghịch đồ điện vì dễ gặp nguy hiểm.' },
    { sec: 'An toàn điện', name: 'Câu 8', pts: 1,
      text: 'Dùng đồ điện đúng cách mang lại điều gì?',
      opts: o4('Nhiều tai nạn hơn', 'An toàn cho bản thân và mọi người', 'Tốn điện hơn', 'Đồ mau hỏng hơn'), ans: 'B',
      why: 'Dùng đồ điện đúng cách giúp an toàn cho em và mọi người trong nhà.' },
    { sec: 'An toàn điện', name: 'Câu 9', pts: 1,
      text: 'Có nên tự trèo lên sửa dây điện, bóng đèn trên cao không?',
      opts: o4('Không, phải nhờ người lớn', 'Có, một mình cũng được', 'Có, nếu đứng trên ghế nhựa', 'Có, cho nhanh'), ans: 'A',
      why: 'Trẻ em không được tự sửa điện trên cao; việc đó phải để người lớn làm.' },
    { sec: 'An toàn điện', name: 'Câu 10', pts: 1,
      text: 'Khi ra khỏi phòng lâu, để an toàn và tiết kiệm điện em nên làm gì?',
      opts: o4('Bật hết mọi thiết bị', 'Để nguyên tất cả', 'Mở thêm cửa sổ', 'Tắt đèn, quạt và các đồ điện không dùng'), ans: 'D',
      why: 'Tắt các đồ điện khi không dùng vừa an toàn vừa tiết kiệm điện.' },
  ],
},

/* ═══════════ ĐỀ 10 — LÀM VÀ BẢO QUẢN ĐỒ THỦ CÔNG ═══════════ */
{
  id: 9310, title: 'Đề 10 · Đồ thủ công và bảo quản đồ dùng', time: 20,
  questions: [
    { sec: 'Đồ thủ công', name: 'Câu 1', pts: 1,
      text: 'Để gấp một chiếc thuyền giấy, em cần vật liệu chính nào?',
      opts: o4('Tờ giấy', 'Cái nồi', 'Bóng đèn', 'Con chuột máy tính'), ans: 'A',
      why: 'Gấp thuyền, máy bay giấy... chỉ cần một tờ giấy là làm được.' },
    { sec: 'Đồ thủ công', name: 'Câu 2', pts: 1,
      text: 'Khi dùng kéo để cắt giấy làm đồ chơi, em cần chú ý gì?',
      opts: o4('Vừa chạy vừa cắt', 'Cẩn thận, không chĩa mũi kéo vào người', 'Cầm ngược lưỡi kéo', 'Đưa kéo cho bạn bằng mũi nhọn'), ans: 'B',
      why: 'Dùng kéo phải cẩn thận, không chĩa mũi nhọn vào người để tránh bị thương.' },
    { sec: 'Đồ thủ công', name: 'Câu 3', pts: 1,
      text: 'Muốn dán hai mảnh giấy lại với nhau, em dùng gì?',
      opts: o4('Hồ dán (keo dán)', 'Nước lã', 'Cục tẩy', 'Cái thước'), ans: 'A',
      why: 'Hồ dán (keo) giúp dán hai mảnh giấy dính chặt vào nhau.' },
    { sec: 'Đồ thủ công', name: 'Câu 4', pts: 1,
      text: 'Làm đồ chơi từ vỏ hộp sữa, chai nhựa cũ có lợi ích gì?',
      opts: o4('Làm bẩn nhà cửa', 'Tốn nhiều tiền hơn', 'Tiết kiệm và bảo vệ môi trường', 'Không có lợi gì'), ans: 'C',
      why: 'Tận dụng đồ cũ làm đồ chơi giúp tiết kiệm và giảm rác, bảo vệ môi trường.' },
    { sec: 'Đồ thủ công', name: 'Câu 5', pts: 1,
      text: 'Trước khi làm đồ thủ công, em nên chuẩn bị điều gì?',
      opts: o4('Vật liệu, dụng cụ và chỗ ngồi gọn gàng', 'Chỉ ngồi chờ', 'Bày bừa khắp nhà', 'Không cần gì cả'), ans: 'A',
      why: 'Chuẩn bị đủ vật liệu, dụng cụ và chỗ gọn gàng giúp làm nhanh và sạch sẽ.' },
    { sec: 'Đồ thủ công', name: 'Câu 6', pts: 1,
      text: 'Làm xong đồ thủ công, em nên làm gì với chỗ ngồi?',
      opts: o4('Để bừa bộn đó', 'Vứt rác ra sàn', 'Bỏ đi chơi ngay', 'Dọn dẹp giấy vụn, cất dụng cụ gọn gàng'), ans: 'D',
      why: 'Làm xong cần dọn giấy vụn và cất dụng cụ để nơi làm sạch, gọn.' },
    { sec: 'Bảo quản đồ dùng', name: 'Câu 7', pts: 1,
      text: 'Để đồ dùng bền lâu, em nên làm gì?',
      opts: o4('Dùng cẩn thận, cất đúng chỗ sau khi dùng', 'Ném vứt lung tung', 'Bỏ mặc ngoài mưa nắng', 'Dùng xong để bừa'), ans: 'A',
      why: 'Dùng cẩn thận và cất đúng chỗ giúp đồ dùng bền, dùng được lâu.' },
    { sec: 'Bảo quản đồ dùng', name: 'Câu 8', pts: 1,
      text: 'Sách vở, đồ dùng học tập nên được cất ở đâu?',
      opts: o4('Dưới gầm giường ẩm ướt', 'Nơi khô ráo, sạch sẽ, đúng ngăn', 'Ngoài sân mưa', 'Trong bồn rửa'), ans: 'B',
      why: 'Cất sách vở, đồ dùng nơi khô ráo, sạch và đúng chỗ để giữ bền, dễ tìm.' },
    { sec: 'Bảo quản đồ dùng', name: 'Câu 9', pts: 1,
      text: 'Vì sao phải giữ gìn, bảo quản đồ dùng?',
      opts: o4('Để đồ bền, tiết kiệm và luôn sẵn sàng dùng', 'Để mau hỏng', 'Để tốn tiền mua mới', 'Không vì lí do gì'), ans: 'A',
      why: 'Giữ gìn đồ dùng giúp chúng bền, tiết kiệm tiền và lúc cần là có ngay để dùng.' },
    { sec: 'Bảo quản đồ dùng', name: 'Câu 10', pts: 1,
      text: 'Đồ chơi bị hỏng nhẹ, em nên làm gì trước tiên?',
      opts: o4('Vứt bỏ ngay', 'Đập cho hỏng hẳn', 'Nhờ người lớn sửa lại nếu được', 'Ném vào bạn'), ans: 'C',
      why: 'Đồ hỏng nhẹ có thể nhờ người lớn sửa lại để dùng tiếp, đỡ lãng phí.' },
  ],
},

];

SUBJECTS.push({ id:'tincn3', name:'Tin học & Công nghệ', short:'Tin-CN 3', icon:'💻', grade:3, exams:TINCN3_EXAMS, ready:true, heroTitle:'Tin học & Công nghệ lớp 3 — máy tính và em, chuột & bàn phím, sản phẩm công nghệ và an toàn', heroMeta:'📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018' });
