// TOÁN TƯ DUY 12 DẠNG — LỚP 2 · 12 dạng × 20 câu = 240 câu (137 câu có hình, 57%).
// SINH TỰ ĐỘNG bởi tools/gen-tuduy-tt.mjs — sửa nội dung trong script rồi chạy lại:
//     node tools/gen-tuduy-tt.mjs
//
// 12 dạng tư duy: Number Sense · Pattern & Sequence · Missing Number · Logic &
// Deduction · Mental Math · Transformation · Spatial/Visual · Combinatorics ·
// Classification · Data & Graph · Word Problem · Non-routine. Mức độ HSG cấp
// trường / cấp huyện, bám chương trình lớp 2. Hình vẽ bằng code (tools/tt-art.mjs
// + hinh-art.mjs + nc2-art.mjs), đáp án lấy thẳng từ dữ liệu vẽ ra hình.

const TTD2 = [
{
  id: 3201, title: 'Dạng 1 · Cảm nhận số (Number Sense)', time: 25,
  questions: [
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 1', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd2/d1_ns-pv0.svg',
      opts: o4('416', '561', '462', '461'), ans: 'D',
      why: 'Có 4 trăm, 6 chục và 1 đơn vị nên số đó là 461.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 2', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd2/d1_ns-pv1.svg',
      opts: o4('548', '684', '584', '585'), ans: 'C',
      why: 'Có 5 trăm, 8 chục và 4 đơn vị nên số đó là 584.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 3', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd2/d1_ns-pv2.svg',
      opts: o4('113', '131', '213', '114'), ans: 'A',
      why: 'Có 1 trăm, 1 chục và 3 đơn vị nên số đó là 113.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 4', pts: 0.5,
      text: 'Các khối trong hình biểu diễn số nào? (mỗi tấm = 1 trăm, mỗi thanh = 1 chục, mỗi ô nhỏ = 1 đơn vị)', img: 'assets/ttd2/d1_ns-pv3.svg',
      opts: o4('348', '384', '448', '349'), ans: 'A',
      why: 'Có 3 trăm, 4 chục và 8 đơn vị nên số đó là 348.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 5', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd2/d1_ns-nl0.svg',
      opts: o4('8', '6', '4', '10'), ans: 'B',
      why: 'Các vạch cách đều nhau 2 đơn vị nên vạch có dấu ? là số 6.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 6', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd2/d1_ns-nl1.svg',
      opts: o4('35', '25', '40', '30'), ans: 'D',
      why: 'Các vạch cách đều nhau 5 đơn vị nên vạch có dấu ? là số 30.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 7', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd2/d1_ns-nl2.svg',
      opts: o4('40', '20', '50', '30'), ans: 'D',
      why: 'Các vạch cách đều nhau 10 đơn vị nên vạch có dấu ? là số 30.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 8', pts: 0.5,
      text: 'Trên tia số, vạch có dấu <b>?</b> ứng với số nào?', img: 'assets/ttd2/d1_ns-nl3.svg',
      opts: o4('500', '300', '400', '600'), ans: 'C',
      why: 'Các vạch cách đều nhau 100 đơn vị nên vạch có dấu ? là số 400.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 9', pts: 0.5,
      text: 'Trong các số 832 ; 766 ; 300 ; 770, số <b>lớn nhất</b> là:',
      opts: o4('766', '300', '832', '770'), ans: 'C',
      why: 'So sánh bốn số, số lớn nhất là 832.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 10', pts: 0.5,
      text: 'Trong các số 524 ; 819 ; 577 ; 741, số <b>bé nhất</b> là:',
      opts: o4('819', '577', '741', '524'), ans: 'D',
      why: 'So sánh bốn số, số bé nhất là 524.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 11', pts: 0.5,
      text: 'Trong các số 255 ; 800 ; 413 ; 370, số <b>lớn nhất</b> là:',
      opts: o4('255', '800', '413', '370'), ans: 'B',
      why: 'So sánh bốn số, số lớn nhất là 800.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 12', pts: 0.5,
      text: 'Trong các số 875 ; 191 ; 349 ; 683, số <b>bé nhất</b> là:',
      opts: o4('875', '349', '191', '683'), ans: 'C',
      why: 'So sánh bốn số, số bé nhất là 191.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 13', pts: 0.5,
      text: 'Số gồm 1 trăm, 1 chục và 9 đơn vị được viết là:',
      opts: o4('191', '219', '11', '119'), ans: 'D',
      why: '1 trăm 1 chục 9 đơn vị viết là 119.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 14', pts: 0.5,
      text: 'Số gồm 2 trăm, 7 chục và 8 đơn vị được viết là:',
      opts: o4('278', '287', '378', '27'), ans: 'A',
      why: '2 trăm 7 chục 8 đơn vị viết là 278.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 15', pts: 0.5,
      text: 'Số gồm 3 trăm, 9 chục và 1 đơn vị được viết là:',
      opts: o4('319', '491', '391', '39'), ans: 'C',
      why: '3 trăm 9 chục 1 đơn vị viết là 391.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 16', pts: 0.5,
      text: 'Số gồm 1 trăm, 8 chục và 1 đơn vị được viết là:',
      opts: o4('118', '181', '281', '18'), ans: 'B',
      why: '1 trăm 8 chục 1 đơn vị viết là 181.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 17', pts: 0.5,
      text: 'Từ ba chữ số 8, 9, 0, hãy lập số có ba chữ số (các chữ số khác nhau) <b>lớn nhất</b>. Số đó là:',
      opts: o4('980', '809', '971', '908'), ans: 'A',
      why: 'Xếp các chữ số từ lớn đến bé: 9 > 8 > 0 → số lớn nhất là 980.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 18', pts: 0.5,
      text: 'Từ ba chữ số 7, 1, 8, hãy lập số có ba chữ số (các chữ số khác nhau) <b>bé nhất</b>. Số đó là:',
      opts: o4('178', '871', '187', '817'), ans: 'A',
      why: 'Chữ số hàng trăm phải khác 0 và nhỏ nhất có thể; số bé nhất là 178.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 19', pts: 0.5,
      text: 'Từ ba chữ số 2, 5, 1, hãy lập số có ba chữ số (các chữ số khác nhau) <b>lớn nhất</b>. Số đó là:',
      opts: o4('125', '512', '522', '521'), ans: 'D',
      why: 'Xếp các chữ số từ lớn đến bé: 5 > 2 > 1 → số lớn nhất là 521.' },
    { sec: 'Dạng 1 · Cảm nhận số (Number Sense)', name: 'Câu 20', pts: 0.5,
      text: 'Từ ba chữ số 5, 4, 0, hãy lập số có ba chữ số (các chữ số khác nhau) <b>bé nhất</b>. Số đó là:',
      opts: o4('540', '405', '414', '504'), ans: 'B',
      why: 'Chữ số hàng trăm phải khác 0 và nhỏ nhất có thể; số bé nhất là 405.' },
  ],
},
{
  id: 3202, title: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', time: 25,
  questions: [
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 1', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd2/d2_pt-emo0.svg',
      opts: o4('🔴', '🔵', '🟡', '🟢'), ans: 'A',
      why: 'Dãy lặp lại theo nhóm 🔴 🔵 (chu kì 2). Ô thứ 7 lặp lại 🔴.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 2', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd2/d2_pt-emo1.svg',
      opts: o4('🔴', '🟢', '🔵', '🟡'), ans: 'B',
      why: 'Dãy lặp lại theo nhóm 🟢 ⭐ ❤️ (chu kì 3). Ô thứ 7 lặp lại 🟢.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 3', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd2/d2_pt-emo2.svg',
      opts: o4('🔵', '🟡', '🟢', '🔴'), ans: 'D',
      why: 'Dãy lặp lại theo nhóm 🔺 ⬛ 🔴 🔵 (chu kì 4). Ô thứ 7 lặp lại 🔴.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 4', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd2/d2_pt-emo3.svg',
      opts: o4('🔵', '🔴', '🟡', '🟢'), ans: 'A',
      why: 'Dãy lặp lại theo nhóm 🔵 🟡 (chu kì 2). Ô thứ 7 lặp lại 🔵.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 5', pts: 0.5,
      text: 'Hình nào thích hợp điền vào ô có dấu <b>?</b> để tiếp tục quy luật?', img: 'assets/ttd2/d2_pt-emo4.svg',
      opts: o4('⭐', '🔴', '🔵', '🟡'), ans: 'A',
      why: 'Dãy lặp lại theo nhóm ⭐ ❤️ 🔺 (chu kì 3). Ô thứ 7 lặp lại ⭐.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 6', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd2/d2_pt-add0.svg',
      opts: o4('16', '12', '15', '14'), ans: 'D',
      why: 'Mỗi số hơn số liền trước 2 đơn vị. Số cần tìm là 12 + 2 = 14.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 7', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd2/d2_pt-add1.svg',
      opts: o4('20', '17', '14', '18'), ans: 'B',
      why: 'Mỗi số hơn số liền trước 3 đơn vị. Số cần tìm là 14 + 3 = 17.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 8', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd2/d2_pt-add2.svg',
      opts: o4('26', '18', '22', '23'), ans: 'C',
      why: 'Mỗi số hơn số liền trước 4 đơn vị. Số cần tìm là 18 + 4 = 22.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 9', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd2/d2_pt-add3.svg',
      opts: o4('25', '30', '20', '26'), ans: 'A',
      why: 'Mỗi số hơn số liền trước 5 đơn vị. Số cần tìm là 20 + 5 = 25.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 10', pts: 0.5,
      text: 'Số nào thích hợp điền vào ô có dấu <b>?</b>?', img: 'assets/ttd2/d2_pt-add4.svg',
      opts: o4('52', '32', '42', '43'), ans: 'C',
      why: 'Mỗi số hơn số liền trước 10 đơn vị. Số cần tìm là 32 + 10 = 42.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 11', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd2/d2_pt-grow0.svg',
      opts: o4('12', '10', '13', '11'), ans: 'D',
      why: 'Khoảng cách tăng dần 1, 2, 3, 4. Số cuối là 7 + 4 = 11.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 12', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd2/d2_pt-grow1.svg',
      opts: o4('23', '21', '22', '24'), ans: 'C',
      why: 'Khoảng cách tăng dần 3, 4, 5, 6. Số cuối là 16 + 6 = 22.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 13', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd2/d2_pt-grow2.svg',
      opts: o4('19', '18', '17', '20'), ans: 'B',
      why: 'Khoảng cách tăng dần 2, 3, 4, 5. Số cuối là 13 + 5 = 18.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 14', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd2/d2_pt-grow3.svg',
      opts: o4('17', '15', '16', '18'), ans: 'C',
      why: 'Khoảng cách tăng dần 2, 3, 4, 5. Số cuối là 11 + 5 = 16.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 15', pts: 0.5,
      text: 'Quan sát khoảng cách giữa các số rồi tìm số điền vào ô <b>?</b>.', img: 'assets/ttd2/d2_pt-grow4.svg',
      opts: o4('23', '21', '22', '24'), ans: 'C',
      why: 'Khoảng cách tăng dần 3, 4, 5, 6. Số cuối là 16 + 6 = 22.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 16', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd2/d2_pt-mul0.svg',
      opts: o4('8', '10', '6', '9'), ans: 'A',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 4 × 2 = 8.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 17', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd2/d2_pt-mul1.svg',
      opts: o4('16', '18', '14', '12'), ans: 'A',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 8 × 2 = 16.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 18', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd2/d2_pt-mul2.svg',
      opts: o4('24', '26', '22', '18'), ans: 'A',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 12 × 2 = 24.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 19', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd2/d2_pt-mul3.svg',
      opts: o4('10', '8', '6', '9'), ans: 'B',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 4 × 2 = 8.' },
    { sec: 'Dạng 2 · Tìm quy luật (Pattern & Sequence)', name: 'Câu 20', pts: 0.5,
      text: 'Mỗi số được tạo ra từ số liền trước theo một quy luật. Tìm số ở ô <b>?</b>.', img: 'assets/ttd2/d2_pt-mul4.svg',
      opts: o4('18', '14', '16', '12'), ans: 'C',
      why: 'Mỗi số gấp đôi số liền trước. Số cần tìm là 8 × 2 = 16.' },
  ],
},
{
  id: 3203, title: 'Dạng 3 · Số còn thiếu (Missing Number)', time: 25,
  questions: [
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 1', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd2/d3_mi-arr0.svg',
      opts: o4('15', '12', '9', '13'), ans: 'B',
      why: 'Mỗi mũi tên là + 3. Số cần tìm là 9 + 3 = 12.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 2', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd2/d3_mi-arr1.svg',
      opts: o4('17', '9', '13', '14'), ans: 'C',
      why: 'Mỗi mũi tên là + 4. Số cần tìm là 9 + 4 = 13.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 3', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd2/d3_mi-arr2.svg',
      opts: o4('17', '11', '5', '12'), ans: 'B',
      why: 'Mỗi mũi tên là + 6. Số cần tìm là 5 + 6 = 11.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 4', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd2/d3_mi-arr3.svg',
      opts: o4('13', '3', '8', '9'), ans: 'C',
      why: 'Mỗi mũi tên là + 5. Số cần tìm là 3 + 5 = 8.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 5', pts: 0.5,
      text: 'Tìm số còn thiếu ở ô <b>?</b> trong dãy.', img: 'assets/ttd2/d3_mi-arr4.svg',
      opts: o4('18', '4', '12', '11'), ans: 'D',
      why: 'Mỗi mũi tên là + 7. Số cần tìm là 4 + 7 = 11.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 6', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? + 34 = 69</b>',
      opts: o4('69', '45', '26', '35'), ans: 'D',
      why: 'Số cần tìm = 69 − 34 = 35.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 7', pts: 0.5,
      text: 'Tìm số thích hợp: <b>48 + ? = 96</b>',
      opts: o4('48', '96', '58', '39'), ans: 'A',
      why: 'Số cần tìm = 96 − 48 = 48.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 8', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? + 60 = 87</b>',
      opts: o4('27', '87', '37', '18'), ans: 'A',
      why: 'Số cần tìm = 87 − 60 = 27.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 9', pts: 0.5,
      text: 'Tìm số thích hợp: <b>32 + ? = 71</b>',
      opts: o4('71', '49', '39', '30'), ans: 'C',
      why: 'Số cần tìm = 71 − 32 = 39.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 10', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? + 60 = 120</b>',
      opts: o4('120', '70', '51', '60'), ans: 'D',
      why: 'Số cần tìm = 120 − 60 = 60.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 11', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd2/d3_mi-seq0.svg',
      opts: o4('10', '8', '6', '9'), ans: 'B',
      why: 'Dãy đếm thêm 2: số ở ô trống là 6 + 2 = 8.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 12', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd2/d3_mi-seq1.svg',
      opts: o4('30', '20', '27', '25'), ans: 'D',
      why: 'Dãy đếm thêm 5: số ở ô trống là 20 + 5 = 25.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 13', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd2/d3_mi-seq2.svg',
      opts: o4('70', '60', '50', '62'), ans: 'B',
      why: 'Dãy đếm thêm 10: số ở ô trống là 50 + 10 = 60.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 14', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd2/d3_mi-seq3.svg',
      opts: o4('12', '9', '6', '11'), ans: 'B',
      why: 'Dãy đếm thêm 3: số ở ô trống là 6 + 3 = 9.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 15', pts: 0.5,
      text: 'Điền số còn thiếu vào ô <b>?</b>.', img: 'assets/ttd2/d3_mi-seq4.svg',
      opts: o4('28', '20', '26', '24'), ans: 'D',
      why: 'Dãy đếm thêm 4: số ở ô trống là 20 + 4 = 24.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 16', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? × 8 = 32</b>',
      opts: o4('32', '5', '4', '8'), ans: 'C',
      why: 'Số cần tìm = 32 : 8 = 4.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 17', pts: 0.5,
      text: 'Tìm số thích hợp: <b>2 × ? = 16</b>',
      opts: o4('16', '10', '8', '7'), ans: 'C',
      why: 'Số cần tìm = 16 : 2 = 8.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 18', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? : 4 = 7</b>',
      opts: o4('7', '4', '28', '32'), ans: 'C',
      why: 'Số bị chia = 7 × 4 = 28.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 19', pts: 0.5,
      text: 'Tìm số thích hợp: <b>? × 9 = 81</b>',
      opts: o4('81', '10', '9', '8'), ans: 'C',
      why: 'Số cần tìm = 81 : 9 = 9.' },
    { sec: 'Dạng 3 · Số còn thiếu (Missing Number)', name: 'Câu 20', pts: 0.5,
      text: 'Tìm số thích hợp: <b>7 × ? = 63</b>',
      opts: o4('63', '9', '11', '8'), ans: 'B',
      why: 'Số cần tìm = 63 : 7 = 9.' },
  ],
},
{
  id: 3204, title: 'Dạng 4 · Suy luận (Logic & Deduction)', time: 25,
  questions: [
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 1', pts: 0.5,
      text: 'Cân thăng bằng. Biết 2 quả táo nặng bằng nhau. Hỏi <b>một quả táo</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd2/d4_lg-bal0.svg',
      opts: o4('3 kg', '6 kg', '4 kg', '2 kg'), ans: 'A',
      why: 'Tổng các quả cân là 6 = 6 kg cho 2 quả táo. Một quả táo nặng 6 : 2 = 3 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 2', pts: 0.5,
      text: 'Cân thăng bằng. Biết 3 quả cam nặng bằng nhau. Hỏi <b>một quả cam</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd2/d4_lg-bal1.svg',
      opts: o4('18 kg', '7 kg', '5 kg', '6 kg'), ans: 'D',
      why: 'Tổng các quả cân là 6 + 6 + 6 = 18 kg cho 3 quả cam. Một quả cam nặng 18 : 3 = 6 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 3', pts: 0.5,
      text: 'Cân thăng bằng. Biết 2 quả lê nặng bằng nhau. Hỏi <b>một quả lê</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd2/d4_lg-bal2.svg',
      opts: o4('4 kg', '3 kg', '2 kg', '1 kg'), ans: 'C',
      why: 'Tổng các quả cân là 4 = 4 kg cho 2 quả lê. Một quả lê nặng 4 : 2 = 2 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 4', pts: 0.5,
      text: 'Cân thăng bằng. Biết 3 quả chanh nặng bằng nhau. Hỏi <b>một quả chanh</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd2/d4_lg-bal3.svg',
      opts: o4('6 kg', '2 kg', '3 kg', '1 kg'), ans: 'B',
      why: 'Tổng các quả cân là 6 = 6 kg cho 3 quả chanh. Một quả chanh nặng 6 : 3 = 2 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 5', pts: 0.5,
      text: 'Cân thăng bằng. Biết 4 quả táo nặng bằng nhau. Hỏi <b>một quả táo</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd2/d4_lg-bal4.svg',
      opts: o4('8 kg', '3 kg', '1 kg', '2 kg'), ans: 'D',
      why: 'Tổng các quả cân là 4 + 4 = 8 kg cho 4 quả táo. Một quả táo nặng 8 : 4 = 2 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 6', pts: 0.5,
      text: 'Cân thăng bằng. Biết 3 quả cam nặng bằng nhau. Hỏi <b>một quả cam</b> nặng bao nhiêu ki-lô-gam?', img: 'assets/ttd2/d4_lg-bal5.svg',
      opts: o4('2 kg', '6 kg', '3 kg', '1 kg'), ans: 'A',
      why: 'Tổng các quả cân là 6 = 6 kg cho 3 quả cam. Một quả cam nặng 6 : 3 = 2 kg.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 7', pts: 0.5,
      text: 'An cao hơn Bình, Bình cao hơn Cường. Hỏi bạn nào <b>cao nhất</b>?',
      opts: o4('Cường', 'An', 'Bình', 'Không xác định được'), ans: 'B',
      why: 'Xếp theo chiều cao: An > Bình > Cường. Vậy An cao nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 8', pts: 0.5,
      text: 'Bình cao hơn Cường, Cường cao hơn Dung. Hỏi bạn nào <b>thấp nhất</b>?',
      opts: o4('Bình', 'Dung', 'Cường', 'Không xác định được'), ans: 'B',
      why: 'Xếp theo chiều cao: Bình > Cường > Dung. Vậy Dung thấp nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 9', pts: 0.5,
      text: 'Cường cao hơn Dung, Dung cao hơn Hoa. Hỏi bạn nào <b>cao nhất</b>?',
      opts: o4('Hoa', 'Cường', 'Dung', 'Không xác định được'), ans: 'B',
      why: 'Xếp theo chiều cao: Cường > Dung > Hoa. Vậy Cường cao nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 10', pts: 0.5,
      text: 'Dung cao hơn Hoa, Hoa cao hơn Khôi. Hỏi bạn nào <b>thấp nhất</b>?',
      opts: o4('Dung', 'Hoa', 'Không xác định được', 'Khôi'), ans: 'D',
      why: 'Xếp theo chiều cao: Dung > Hoa > Khôi. Vậy Khôi thấp nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 11', pts: 0.5,
      text: 'Ba bạn An, Bình, Cường xếp thành một hàng. An đứng trước Bình, Cường đứng sau Bình. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('An', 'Bình', 'Cường', 'Không xác định được'), ans: 'B',
      why: 'Thứ tự hàng là An – Bình – Cường, nên Bình đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 12', pts: 0.5,
      text: 'Ba bạn Bình, Cường, Dung xếp thành một hàng. Bình đứng trước Cường, Dung đứng sau Cường. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('Cường', 'Bình', 'Dung', 'Không xác định được'), ans: 'A',
      why: 'Thứ tự hàng là Bình – Cường – Dung, nên Cường đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 13', pts: 0.5,
      text: 'Ba bạn Cường, Dung, Hoa xếp thành một hàng. Cường đứng trước Dung, Hoa đứng sau Dung. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('Cường', 'Hoa', 'Dung', 'Không xác định được'), ans: 'C',
      why: 'Thứ tự hàng là Cường – Dung – Hoa, nên Dung đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 14', pts: 0.5,
      text: 'Ba bạn Dung, Hoa, Khôi xếp thành một hàng. Dung đứng trước Hoa, Khôi đứng sau Hoa. Hỏi bạn nào đứng <b>giữa</b>?',
      opts: o4('Dung', 'Hoa', 'Khôi', 'Không xác định được'), ans: 'B',
      why: 'Thứ tự hàng là Dung – Hoa – Khôi, nên Hoa đứng giữa.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 15', pts: 0.5,
      text: 'An, Cường, Hoa mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. An không nuôi chó cũng không nuôi mèo. Cường nuôi mèo. Hỏi An nuôi con gì?',
      opts: o4('Cá', 'Chó', 'Mèo', 'Không biết'), ans: 'A',
      why: 'An không nuôi chó, không nuôi mèo nên An nuôi cá. (Cường nuôi mèo, còn Hoa nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 16', pts: 0.5,
      text: 'Bình, Dung, Khôi mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. Bình không nuôi chó cũng không nuôi mèo. Dung nuôi mèo. Hỏi Bình nuôi con gì?',
      opts: o4('Chó', 'Cá', 'Mèo', 'Không biết'), ans: 'B',
      why: 'Bình không nuôi chó, không nuôi mèo nên Bình nuôi cá. (Dung nuôi mèo, còn Khôi nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 17', pts: 0.5,
      text: 'Cường, Hoa, Lan mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. Cường không nuôi chó cũng không nuôi mèo. Hoa nuôi mèo. Hỏi Cường nuôi con gì?',
      opts: o4('Cá', 'Chó', 'Mèo', 'Không biết'), ans: 'A',
      why: 'Cường không nuôi chó, không nuôi mèo nên Cường nuôi cá. (Hoa nuôi mèo, còn Lan nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 18', pts: 0.5,
      text: 'Dung, Khôi, Minh mỗi bạn nuôi một con vật khác nhau: chó, mèo, cá. Dung không nuôi chó cũng không nuôi mèo. Khôi nuôi mèo. Hỏi Dung nuôi con gì?',
      opts: o4('Chó', 'Mèo', 'Không biết', 'Cá'), ans: 'D',
      why: 'Dung không nuôi chó, không nuôi mèo nên Dung nuôi cá. (Khôi nuôi mèo, còn Minh nuôi chó.)' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 19', pts: 0.5,
      text: 'Bút đắt hơn Thước, Thước đắt hơn Kẹo. Hỏi trong ba thứ, thứ nào <b>rẻ nhất</b>?',
      opts: o4('Bút', 'Kẹo', 'Thước', 'Không xác định được'), ans: 'B',
      why: 'Xếp theo giá: Bút > Thước > Kẹo. Vậy Kẹo rẻ nhất.' },
    { sec: 'Dạng 4 · Suy luận (Logic & Deduction)', name: 'Câu 20', pts: 0.5,
      text: 'Vở đắt hơn Tẩy, Tẩy đắt hơn Bánh. Hỏi trong ba thứ, thứ nào <b>rẻ nhất</b>?',
      opts: o4('Vở', 'Tẩy', 'Không xác định được', 'Bánh'), ans: 'D',
      why: 'Xếp theo giá: Vở > Tẩy > Bánh. Vậy Bánh rẻ nhất.' },
  ],
},
{
  id: 3205, title: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', time: 25,
  questions: [
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 1', pts: 0.5,
      text: 'Tính nhanh: <b>13 + 7 + 23</b>', img: 'assets/ttd2/d5_me-round0.svg',
      opts: o4('53', '33', '43', '44'), ans: 'C',
      why: 'Ghép 13 + 7 = 20 (tròn chục) rồi cộng 23: 20 + 23 = 43.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 2', pts: 0.5,
      text: 'Tính nhanh: <b>12 + 8 + 24</b>', img: 'assets/ttd2/d5_me-round1.svg',
      opts: o4('54', '34', '45', '44'), ans: 'D',
      why: 'Ghép 12 + 8 = 20 (tròn chục) rồi cộng 24: 20 + 24 = 44.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 3', pts: 0.5,
      text: 'Tính nhanh: <b>19 + 1 + 39</b>', img: 'assets/ttd2/d5_me-round2.svg',
      opts: o4('59', '69', '49', '60'), ans: 'A',
      why: 'Ghép 19 + 1 = 20 (tròn chục) rồi cộng 39: 20 + 39 = 59.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 4', pts: 0.5,
      text: 'Tính nhanh: <b>18 + 2 + 29</b>', img: 'assets/ttd2/d5_me-round3.svg',
      opts: o4('59', '39', '50', '49'), ans: 'D',
      why: 'Ghép 18 + 2 = 20 (tròn chục) rồi cộng 29: 20 + 29 = 49.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 5', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>20 + 10 + 32 + 8</b>',
      opts: o4('80', '69', '79', '70'), ans: 'D',
      why: '(20 + 10) + (32 + 8) = 30 + 40 = 70.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 6', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>16 + 4 + 46 + 4</b>',
      opts: o4('70', '80', '69', '79'), ans: 'A',
      why: '(16 + 4) + (46 + 4) = 20 + 50 = 70.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 7', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>13 + 7 + 40 + 10</b>',
      opts: o4('80', '70', '69', '79'), ans: 'B',
      why: '(13 + 7) + (40 + 10) = 20 + 50 = 70.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 8', pts: 0.5,
      text: 'Tính nhanh bằng cách ghép cho tròn chục: <b>22 + 8 + 42 + 8</b>',
      opts: o4('80', '90', '79', '89'), ans: 'A',
      why: '(22 + 8) + (42 + 8) = 30 + 50 = 80.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 9', pts: 0.5,
      text: 'Tính nhanh: <b>25 × 4</b>',
      opts: o4('100', '110', '90', '102'), ans: 'A',
      why: '25 × 4 = 100 (một phần tư của 400).' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 10', pts: 0.5,
      text: 'Tính nhanh: <b>5 × 8</b>',
      opts: o4('50', '30', '42', '40'), ans: 'D',
      why: '5 × 8 = 40. Mẹo: 5 × số chẵn = (số chẵn : 2) × 10 = 4 × 10 = 40.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 11', pts: 0.5,
      text: 'Tính nhanh: <b>9 × 6</b>',
      opts: o4('54', '64', '44', '56'), ans: 'A',
      why: '9 × 6 = 10 × 6 − 6 = 60 − 6 = 54.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 12', pts: 0.5,
      text: 'Tính nhanh: <b>9 × 8</b>',
      opts: o4('82', '62', '74', '72'), ans: 'D',
      why: '9 × 8 = 10 × 8 − 8 = 80 − 8 = 72.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 13', pts: 0.5,
      text: 'Tính nhanh: <b>50 × 6</b>',
      opts: o4('310', '290', '302', '300'), ans: 'D',
      why: '50 × 6 = 5 × 6 × 10 = 30 × 10 = 300.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 14', pts: 0.5,
      text: 'Tính nhanh: <b>2 × 49</b>',
      opts: o4('108', '88', '98', '100'), ans: 'C',
      why: '2 × 49 = 2 × 50 − 2 = 100 − 2 = 98.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 15', pts: 0.5,
      text: 'Tính nhanh: <b>99 + 44</b>',
      opts: o4('153', '142', '143', '144'), ans: 'C',
      why: 'Xem 99 ≈ 100: (100 + 44) − 1 = 144 − 1 = 143.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 16', pts: 0.5,
      text: 'Tính nhanh: <b>98 + 46</b>',
      opts: o4('154', '144', '143', '145'), ans: 'B',
      why: 'Xem 98 ≈ 99: (99 + 46) − 1 = 145 − 1 = 144.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 17', pts: 0.5,
      text: 'Tính nhanh: <b>199 + 48</b>',
      opts: o4('247', '257', '246', '248'), ans: 'A',
      why: 'Xem 199 ≈ 200: (200 + 48) − 1 = 248 − 1 = 247.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 18', pts: 0.5,
      text: 'Tính nhanh: <b>98 + 65</b>',
      opts: o4('173', '163', '162', '164'), ans: 'B',
      why: 'Xem 98 ≈ 99: (99 + 65) − 1 = 164 − 1 = 163.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 19', pts: 0.5,
      text: 'Không cần tính kết quả, hãy so sánh: <b>46 + 46</b> ... <b>46 + 51</b>. Dấu thích hợp là:',
      opts: o4('>', '=', '<', 'Không so sánh được'), ans: 'C',
      why: 'Hai tổng cùng có 46, nhưng 51 > 46 nên 46 + 46 < 46 + 51.' },
    { sec: 'Dạng 5 · Tính nhanh thông minh (Mental Math)', name: 'Câu 20', pts: 0.5,
      text: 'Không cần tính kết quả, hãy so sánh: <b>29 + 39</b> ... <b>29 + 41</b>. Dấu thích hợp là:',
      opts: o4('>', '=', '<', 'Không so sánh được'), ans: 'C',
      why: 'Hai tổng cùng có 29, nhưng 41 > 39 nên 29 + 39 < 29 + 41.' },
  ],
},
{
  id: 3206, title: 'Dạng 6 · Máy biến đổi (Transformation)', time: 25,
  questions: [
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 1', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd2/d6_tf-add0.svg',
      opts: o4('14', '10', '12', '13'), ans: 'D',
      why: 'Máy luôn cộng thêm 3 (2 → 5, ...). Vậy 10 → 10 + 3 = 13.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 2', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd2/d6_tf-add1.svg',
      opts: o4('16', '11', '15', '14'), ans: 'C',
      why: 'Máy luôn cộng thêm 4 (3 → 7, ...). Vậy 11 → 11 + 4 = 15.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 3', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd2/d6_tf-add2.svg',
      opts: o4('17', '18', '12', '16'), ans: 'A',
      why: 'Máy luôn cộng thêm 5 (4 → 9, ...). Vậy 12 → 12 + 5 = 17.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 4', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd2/d6_tf-add3.svg',
      opts: o4('19', '20', '13', '18'), ans: 'A',
      why: 'Máy luôn cộng thêm 6 (5 → 11, ...). Vậy 13 → 13 + 6 = 19.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 5', pts: 0.5,
      text: 'Quan sát máy biến đổi số. Nếu đưa vào số cuối cùng thì máy cho ra số nào?', img: 'assets/ttd2/d6_tf-add4.svg',
      opts: o4('22', '21', '14', '20'), ans: 'B',
      why: 'Máy luôn cộng thêm 7 (6 → 13, ...). Vậy 14 → 14 + 7 = 21.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 6', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd2/d6_tf-mul0.svg',
      opts: o4('14', '8', '11', '12'), ans: 'D',
      why: 'Mỗi số ra gấp 2 lần số vào (2 → 4, ...). Vậy 6 → 6 × 2 = 12.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 7', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd2/d6_tf-mul1.svg',
      opts: o4('16', '9', '13', '14'), ans: 'D',
      why: 'Mỗi số ra gấp 2 lần số vào (3 → 6, ...). Vậy 7 → 7 × 2 = 14.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 8', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd2/d6_tf-mul2.svg',
      opts: o4('27', '11', '24', '23'), ans: 'C',
      why: 'Mỗi số ra gấp 3 lần số vào (4 → 12, ...). Vậy 8 → 8 × 3 = 24.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 9', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd2/d6_tf-mul3.svg',
      opts: o4('30', '12', '27', '26'), ans: 'C',
      why: 'Mỗi số ra gấp 3 lần số vào (5 → 15, ...). Vậy 9 → 9 × 3 = 27.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 10', pts: 0.5,
      text: 'Máy biến đổi mỗi số vào thành số ra. Số cuối cùng cho ra kết quả nào?', img: 'assets/ttd2/d6_tf-mul4.svg',
      opts: o4('22', '12', '19', '20'), ans: 'D',
      why: 'Mỗi số ra gấp 2 lần số vào (6 → 12, ...). Vậy 10 → 10 × 2 = 20.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 11', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd2/d6_tf-two0.svg',
      opts: o4('13', '11', '10', '12'), ans: 'B',
      why: 'Máy làm: nhân 2 rồi cộng 1 (1 → 3, ...). Vậy 5 → 5 × 2 + 1 = 11.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 12', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd2/d6_tf-two1.svg',
      opts: o4('16', '12', '14', '15'), ans: 'C',
      why: 'Máy làm: nhân 2 rồi cộng 2 (2 → 6, ...). Vậy 6 → 6 × 2 + 2 = 14.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 13', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd2/d6_tf-two2.svg',
      opts: o4('19', '14', '18', '17'), ans: 'D',
      why: 'Máy làm: nhân 2 rồi cộng 3 (3 → 9, ...). Vậy 7 → 7 × 2 + 3 = 17.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 14', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd2/d6_tf-two3.svg',
      opts: o4('17', '19', '16', '18'), ans: 'A',
      why: 'Máy làm: nhân 2 rồi cộng 1 (4 → 9, ...). Vậy 8 → 8 × 2 + 1 = 17.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 15', pts: 0.5,
      text: 'Tìm quy luật của máy rồi cho biết số ra ứng với số vào cuối cùng.', img: 'assets/ttd2/d6_tf-two4.svg',
      opts: o4('22', '18', '20', '21'), ans: 'C',
      why: 'Máy làm: nhân 2 rồi cộng 2 (5 → 12, ...). Vậy 9 → 9 × 2 + 2 = 20.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 16', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>20</b> thì phải đưa vào số nào?', img: 'assets/ttd2/d6_tf-rev0.svg',
      opts: o4('20', '16', '15', '17'), ans: 'B',
      why: 'Máy cộng thêm 4. Để ra 20 thì số vào là 20 − 4 = 16.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 17', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>21</b> thì phải đưa vào số nào?', img: 'assets/ttd2/d6_tf-rev1.svg',
      opts: o4('16', '21', '15', '17'), ans: 'A',
      why: 'Máy cộng thêm 5. Để ra 21 thì số vào là 21 − 5 = 16.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 18', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>22</b> thì phải đưa vào số nào?', img: 'assets/ttd2/d6_tf-rev2.svg',
      opts: o4('16', '22', '15', '17'), ans: 'A',
      why: 'Máy cộng thêm 6. Để ra 22 thì số vào là 22 − 6 = 16.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 19', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>23</b> thì phải đưa vào số nào?', img: 'assets/ttd2/d6_tf-rev3.svg',
      opts: o4('23', '19', '21', '20'), ans: 'D',
      why: 'Máy cộng thêm 3. Để ra 23 thì số vào là 23 − 3 = 20.' },
    { sec: 'Dạng 6 · Máy biến đổi (Transformation)', name: 'Câu 20', pts: 0.5,
      text: 'Máy hoạt động theo quy luật như các ví dụ. Muốn máy cho ra số <b>24</b> thì phải đưa vào số nào?', img: 'assets/ttd2/d6_tf-rev4.svg',
      opts: o4('24', '16', '15', '17'), ans: 'B',
      why: 'Máy cộng thêm 8. Để ra 24 thì số vào là 24 − 8 = 16.' },
  ],
},
{
  id: 3207, title: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', time: 25,
  questions: [
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 1', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd2/d7_sp-grid0.svg',
      opts: o4('10', '15', '8', '7'), ans: 'A',
      why: 'Có 2 hàng, mỗi hàng 5 ô nên có 5 × 2 = 10 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 2', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd2/d7_sp-grid1.svg',
      opts: o4('9', '6', '4', '5'), ans: 'B',
      why: 'Có 2 hàng, mỗi hàng 3 ô nên có 3 × 2 = 6 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 3', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd2/d7_sp-grid2.svg',
      opts: o4('15', '8', '7', '10'), ans: 'D',
      why: 'Có 2 hàng, mỗi hàng 5 ô nên có 5 × 2 = 10 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 4', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd2/d7_sp-grid3.svg',
      opts: o4('8', '12', '6', '9'), ans: 'A',
      why: 'Có 2 hàng, mỗi hàng 4 ô nên có 4 × 2 = 8 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 5', pts: 0.5,
      text: 'Hình chữ nhật lớn được chia thành các ô vuông nhỏ bằng nhau. Có tất cả bao nhiêu <b>ô vuông nhỏ</b>?', img: 'assets/ttd2/d7_sp-grid4.svg',
      opts: o4('8', '12', '6', '9'), ans: 'A',
      why: 'Có 2 hàng, mỗi hàng 4 ô nên có 4 × 2 = 8 ô vuông nhỏ.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 6', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd2/d7_sp-cube0.svg',
      opts: o4('9', '7', '12', '8'), ans: 'D',
      why: 'Đếm theo từng cột: 2 + 1 + 2 + 3 = 8 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 7', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd2/d7_sp-cube1.svg',
      opts: o4('11', '10', '9', '16'), ans: 'B',
      why: 'Đếm theo từng cột: 2 + 4 + 2 + 2 = 10 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 8', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd2/d7_sp-cube2.svg',
      opts: o4('7', '5', '6', '8'), ans: 'C',
      why: 'Đếm theo từng cột: 1 + 2 + 1 + 2 = 6 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 9', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd2/d7_sp-cube3.svg',
      opts: o4('10', '11', '9', '16'), ans: 'A',
      why: 'Đếm theo từng cột: 2 + 3 + 4 + 1 = 10 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 10', pts: 0.5,
      text: 'Các khối lập phương giống nhau được xếp thành những cột như hình. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttd2/d7_sp-cube4.svg',
      opts: o4('10', '8', '9', '12'), ans: 'C',
      why: 'Đếm theo từng cột: 3 + 3 + 1 + 2 = 9 khối.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 11', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd2/d7_sp-tri0.svg',
      opts: o4('3', '7', '5', '6'), ans: 'D',
      why: 'Có 3 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 3×(3+1):2 = 6 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 12', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd2/d7_sp-tri1.svg',
      opts: o4('3', '7', '6', '5'), ans: 'C',
      why: 'Có 3 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 3×(3+1):2 = 6 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 13', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd2/d7_sp-tri2.svg',
      opts: o4('4', '10', '11', '9'), ans: 'B',
      why: 'Có 4 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 4×(4+1):2 = 10 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 14', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd2/d7_sp-tri3.svg',
      opts: o4('4', '11', '10', '9'), ans: 'C',
      why: 'Có 4 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 4×(4+1):2 = 10 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 15', pts: 0.5,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttd2/d7_sp-tri4.svg',
      opts: o4('2', '4', '3', '5'), ans: 'C',
      why: 'Có 2 tam giác nhỏ và các tam giác lớn ghép lại; tổng cộng 2×(2+1):2 = 3 tam giác.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 16', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>tam giác</b>?', img: 'assets/ttd2/d7_sp-mix0.svg',
      opts: o4('4', '5', '6', '3'), ans: 'A',
      why: 'Đếm riêng các tam giác trong hình được 4 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 17', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>hình vuông</b>?', img: 'assets/ttd2/d7_sp-mix1.svg',
      opts: o4('3', '4', '5', '2'), ans: 'A',
      why: 'Đếm riêng các hình vuông trong hình được 3 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 18', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>hình tròn</b>?', img: 'assets/ttd2/d7_sp-mix2.svg',
      opts: o4('3', '4', '5', '2'), ans: 'A',
      why: 'Đếm riêng các hình tròn trong hình được 3 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 19', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>hình chữ nhật</b>?', img: 'assets/ttd2/d7_sp-mix3.svg',
      opts: o4('5', '4', '6', '3'), ans: 'B',
      why: 'Đếm riêng các hình chữ nhật trong hình được 4 hình.' },
    { sec: 'Dạng 7 · Tư duy không gian (Spatial / Visual)', name: 'Câu 20', pts: 0.5,
      text: 'Trong hình có tất cả bao nhiêu <b>tam giác</b>?', img: 'assets/ttd2/d7_sp-mix4.svg',
      opts: o4('4', '5', '3', '2'), ans: 'C',
      why: 'Đếm riêng các tam giác trong hình được 3 hình.' },
  ],
},
{
  id: 3208, title: 'Dạng 8 · Đếm số cách (Combinatorics)', time: 25,
  questions: [
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 1', pts: 0.5,
      text: 'Có 2 chiếc áo và 3 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd2/d8_cb-grid0.svg',
      opts: o4('5', '6', '7', '3'), ans: 'B',
      why: 'Mỗi áo ghép được với 3 quần/váy nên có 2 × 3 = 6 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 2', pts: 0.5,
      text: 'Có 3 chiếc áo và 4 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd2/d8_cb-grid1.svg',
      opts: o4('7', '13', '12', '8'), ans: 'C',
      why: 'Mỗi áo ghép được với 4 quần/váy nên có 3 × 4 = 12 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 3', pts: 0.5,
      text: 'Có 2 chiếc áo và 2 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd2/d8_cb-grid2.svg',
      opts: o4('5', '4', '2', '3'), ans: 'B',
      why: 'Mỗi áo ghép được với 2 quần/váy nên có 2 × 2 = 4 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 4', pts: 0.5,
      text: 'Có 3 chiếc áo và 3 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd2/d8_cb-grid3.svg',
      opts: o4('6', '10', '9', '8'), ans: 'C',
      why: 'Mỗi áo ghép được với 3 quần/váy nên có 3 × 3 = 9 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 5', pts: 0.5,
      text: 'Có 2 chiếc áo và 4 chiếc quần/váy khác nhau. Mỗi bộ gồm 1 áo và 1 quần/váy. Có bao nhiêu <b>bộ khác nhau</b>?', img: 'assets/ttd2/d8_cb-grid4.svg',
      opts: o4('6', '9', '4', '8'), ans: 'D',
      why: 'Mỗi áo ghép được với 4 quần/váy nên có 2 × 4 = 8 bộ.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 6', pts: 0.5,
      text: 'Từ các chữ số 9, 7, 2 lập được bao nhiêu số có <b>hai chữ số</b> mà hai chữ số <b>khác nhau</b>?',
      opts: o4('7', '5', '8', '6'), ans: 'D',
      why: 'Chữ số hàng chục có 3 cách, hàng đơn vị còn 2 cách: 3 × 2 = 6 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 7', pts: 0.5,
      text: 'Từ các chữ số 1, 6, 2 lập được bao nhiêu số có <b>hai chữ số</b> (các chữ số có thể lặp lại)?',
      opts: o4('9', '10', '8', '6'), ans: 'A',
      why: 'Mỗi hàng có 3 cách chọn: 3 × 3 = 9 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 8', pts: 0.5,
      text: 'Từ các chữ số 6, 4, 5 lập được bao nhiêu số có <b>hai chữ số</b> mà hai chữ số <b>khác nhau</b>?',
      opts: o4('6', '7', '5', '8'), ans: 'A',
      why: 'Chữ số hàng chục có 3 cách, hàng đơn vị còn 2 cách: 3 × 2 = 6 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 9', pts: 0.5,
      text: 'Từ các chữ số 8, 2, 7 lập được bao nhiêu số có <b>hai chữ số</b> (các chữ số có thể lặp lại)?',
      opts: o4('10', '8', '9', '6'), ans: 'C',
      why: 'Mỗi hàng có 3 cách chọn: 3 × 3 = 9 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 10', pts: 0.5,
      text: 'Từ các chữ số 3, 9, 5 lập được bao nhiêu số có <b>hai chữ số</b> mà hai chữ số <b>khác nhau</b>?',
      opts: o4('7', '5', '8', '6'), ans: 'D',
      why: 'Chữ số hàng chục có 3 cách, hàng đơn vị còn 2 cách: 3 × 2 = 6 số.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 11', pts: 0.5,
      text: 'Có 4 bạn gặp nhau, mỗi hai bạn bắt tay nhau đúng <b>một lần</b>. Có tất cả bao nhiêu cái bắt tay?',
      opts: o4('12', '6', '10', '8'), ans: 'B',
      why: 'Mỗi bạn gặp 3 bạn khác, mỗi cặp tính một lần: (4 − 1) + (4 − 2) + … + 1 = 6.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 12', pts: 0.5,
      text: 'Có 5 đội bóng thi đấu vòng tròn, hai đội bất kì đấu với nhau đúng <b>một trận</b>. Có tất cả bao nhiêu trận đấu?',
      opts: o4('20', '15', '11', '10'), ans: 'D',
      why: 'Mỗi đội gặp 4 đội khác, mỗi cặp tính một lần: (5 − 1) + (5 − 2) + … + 1 = 10.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 13', pts: 0.5,
      text: 'Có 6 bạn gặp nhau, mỗi hai bạn bắt tay nhau đúng <b>một lần</b>. Có tất cả bao nhiêu cái bắt tay?',
      opts: o4('30', '15', '21', '12'), ans: 'B',
      why: 'Mỗi bạn gặp 5 bạn khác, mỗi cặp tính một lần: (6 − 1) + (6 − 2) + … + 1 = 15.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 14', pts: 0.5,
      text: 'Có 7 đội bóng thi đấu vòng tròn, hai đội bất kì đấu với nhau đúng <b>một trận</b>. Có tất cả bao nhiêu trận đấu?',
      opts: o4('42', '21', '28', '14'), ans: 'B',
      why: 'Mỗi đội gặp 6 đội khác, mỗi cặp tính một lần: (7 − 1) + (7 − 2) + … + 1 = 21.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 15', pts: 0.5,
      text: 'Có 8 bạn gặp nhau, mỗi hai bạn bắt tay nhau đúng <b>một lần</b>. Có tất cả bao nhiêu cái bắt tay?',
      opts: o4('56', '36', '16', '28'), ans: 'D',
      why: 'Mỗi bạn gặp 7 bạn khác, mỗi cặp tính một lần: (8 − 1) + (8 − 2) + … + 1 = 28.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 16', pts: 0.5,
      text: 'Từ nhà đến trường có 2 con đường, từ trường đến sân bóng có 1 con đường. Có mấy cách đi từ nhà đến sân bóng qua trường?',
      opts: o4('3', '1', '2', '4'), ans: 'C',
      why: '2 con đường đầu × 1 con đường sau = 2 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 17', pts: 0.5,
      text: 'Từ A đến B có 3 con đường, từ B đến C có 1 con đường. Có mấy cách đi từ A đến C qua B?',
      opts: o4('4', '2', '3', '5'), ans: 'C',
      why: '3 × 1 = 3 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 18', pts: 0.5,
      text: 'Từ nhà tới hồ có 3 lối, mỗi lối chỉ đi được một mình nó. Nam muốn đi tới hồ rồi về theo <b>lối khác</b> lúc đi thì có mấy cách chọn lối đi?',
      opts: o4('7', '5', '6', '8'), ans: 'C',
      why: 'Lối đi chọn 1 trong 3 (3 cách), lối về phải khác nên còn 2 cách: 3 × 2 = 6 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 19', pts: 0.5,
      text: 'Có 2 chiếc mũ và 2 đôi giày. Chọn 1 mũ và 1 đôi giày thì có mấy cách?',
      opts: o4('5', '3', '4', '6'), ans: 'C',
      why: '2 mũ × 2 đôi giày = 4 cách.' },
    { sec: 'Dạng 8 · Đếm số cách (Combinatorics)', name: 'Câu 20', pts: 0.5,
      text: 'Có 2 loại bánh và 3 loại nước. Chọn 1 bánh và 1 nước thì có mấy cách?',
      opts: o4('7', '6', '5', '8'), ans: 'B',
      why: '2 bánh × 3 nước = 6 cách.' },
  ],
},
{
  id: 3209, title: 'Dạng 9 · Phân loại (Classification)', time: 25,
  questions: [
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 1', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd0.svg',
      opts: o4('A', 'B', 'C', 'D'), ans: 'A',
      why: 'Táo, cam, lê là quả; ô tô là phương tiện — khác nhóm. Vậy chọn A.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 2', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd1.svg',
      opts: o4('A', 'B', 'C', 'D'), ans: 'D',
      why: 'Chó, mèo, thỏ là con vật; cây không phải con vật. Vậy chọn D.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 3', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd2.svg',
      opts: o4('C', 'D', 'B', 'A'), ans: 'C',
      why: 'Ô tô, xe buýt, xe đạp là phương tiện; chuối là quả. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 4', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd3.svg',
      opts: o4('D', 'C', 'A', 'B'), ans: 'B',
      why: 'Bóng đá, bóng rổ, tennis là quả bóng; quyển sách không phải bóng. Vậy chọn C.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 5', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd4.svg',
      opts: o4('C', 'D', 'A', 'B'), ans: 'D',
      why: 'Hoa; cá không phải hoa. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 6', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd5.svg',
      opts: o4('D', 'A', 'B', 'C'), ans: 'A',
      why: 'Bút chì, bút mực, thước là dụng cụ học tập; pizza là món ăn. Vậy chọn D.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 7', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd6.svg',
      opts: o4('C', 'B', 'D', 'A'), ans: 'B',
      why: 'Dâu, nho, đào là quả; xe buýt là phương tiện. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 8', pts: 0.5,
      text: 'Vật nào <b>khác nhóm</b> với ba vật còn lại?', img: 'assets/ttd2/d9_cl-odd7.svg',
      opts: o4('C', 'B', 'D', 'A'), ans: 'B',
      why: 'Ong, bướm, bọ rùa là côn trùng nhỏ; voi là thú lớn. Vậy chọn B.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 9', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 14 ; 12 ; 3 ; 6?',
      opts: o4('14', '3', '12', '6'), ans: 'B',
      why: 'Ba số kia đều là số chẵn, chỉ có số này là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 10', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 5 ; 15 ; 36 ; 39?',
      opts: o4('5', '15', '39', '36'), ans: 'D',
      why: 'Ba số kia đều chia hết cho 5 (tận cùng 0 hoặc 5), số này thì không.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 11', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 20 ; 60 ; 77 ; 80?',
      opts: o4('20', '77', '60', '80'), ans: 'B',
      why: 'Ba số kia là số tròn chục, số này không tròn chục.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 12', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 18 ; 8 ; 6 ; 19?',
      opts: o4('19', '18', '8', '6'), ans: 'A',
      why: 'Ba số kia đều là số chẵn, chỉ có số này là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 13', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 40 ; 15 ; 45 ; 34?',
      opts: o4('40', '15', '34', '45'), ans: 'C',
      why: 'Ba số kia đều chia hết cho 5 (tận cùng 0 hoặc 5), số này thì không.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 14', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 50 ; 20 ; 80 ; 86?',
      opts: o4('50', '86', '20', '80'), ans: 'B',
      why: 'Ba số kia là số tròn chục, số này không tròn chục.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 15', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 10 ; 14 ; 2 ; 15?',
      opts: o4('15', '10', '14', '2'), ans: 'A',
      why: 'Ba số kia đều là số chẵn, chỉ có số này là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 16', pts: 0.5,
      text: 'Số nào <b>khác nhóm</b> với ba số còn lại: 20 ; 30 ; 45 ; 47?',
      opts: o4('20', '47', '30', '45'), ans: 'B',
      why: 'Ba số kia đều chia hết cho 5 (tận cùng 0 hoặc 5), số này thì không.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 17', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Hình tròn', 'Hình vuông', 'Hình chữ nhật', 'Hình tam giác'), ans: 'A',
      why: 'Ba hình kia có cạnh thẳng và có góc; hình tròn không có cạnh, không có góc.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 18', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Hình vuông', 'Hình tròn', 'Hình chữ nhật', 'Hình tam giác'), ans: 'D',
      why: 'Vuông, tròn, chữ nhật thường được coi cùng nhóm ở đây vì có 4 cạnh (vuông, chữ nhật) — nhưng tam giác chỉ có 3 cạnh, ít cạnh nhất.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 19', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Số 12', 'Số 35', 'Số 20', 'Số 40'), ans: 'B',
      why: '12, 20, 40 là số chẵn; 35 là số lẻ.' },
    { sec: 'Dạng 9 · Phân loại (Classification)', name: 'Câu 20', pts: 0.5,
      text: 'Vật (hoặc hình) nào <b>khác nhóm</b> với ba lựa chọn còn lại?',
      opts: o4('Con gà', 'Con vịt', 'Con chim', 'Con cá'), ans: 'D',
      why: 'Gà, vịt, chim có cánh (là loài chim/gia cầm); cá sống dưới nước, có vây.' },
  ],
},
{
  id: 3210, title: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', time: 25,
  questions: [
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 1', pts: 0.5,
      text: 'Bạn nào đọc được <b>nhiều sách nhất</b>?', img: 'assets/ttd2/d10_da-bar0.svg',
      opts: o4('Bình', 'An', 'Lan', 'Hoa'), ans: 'C',
      why: 'Cột cao nhất là của Lan (10 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 2', pts: 0.5,
      text: 'Bạn nào đọc được <b>ít sách nhất</b>?', img: 'assets/ttd2/d10_da-bar1.svg',
      opts: o4('Lan', 'Bình', 'Hoa', 'An'), ans: 'D',
      why: 'Cột thấp nhất là của An (2 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 3', pts: 0.5,
      text: 'Cả bốn bạn đọc được <b>tất cả</b> bao nhiêu quyển sách?', img: 'assets/ttd2/d10_da-bar2.svg',
      opts: o4('29', '31', '27', '30'), ans: 'A',
      why: 'Cộng số sách của bốn bạn: 10 + 9 + 6 + 4 = 29 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 4', pts: 0.5,
      text: 'Bạn Lan đọc <b>nhiều hơn</b> (hoặc ít hơn) bạn Bình bao nhiêu quyển?', img: 'assets/ttd2/d10_da-bar3.svg',
      opts: o4('3', '4', '18', '2'), ans: 'D',
      why: 'Chênh lệch là 10 − 8 = 2 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 5', pts: 0.5,
      text: 'Bạn nào đọc được <b>nhiều sách nhất</b>?', img: 'assets/ttd2/d10_da-bar4.svg',
      opts: o4('Lan', 'Bình', 'Hoa', 'An'), ans: 'D',
      why: 'Cột cao nhất là của An (10 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 6', pts: 0.5,
      text: 'Bạn nào đọc được <b>ít sách nhất</b>?', img: 'assets/ttd2/d10_da-bar5.svg',
      opts: o4('Lan', 'Bình', 'An', 'Hoa'), ans: 'A',
      why: 'Cột thấp nhất là của Lan (3 quyển).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 7', pts: 0.5,
      text: 'Cả bốn bạn đọc được <b>tất cả</b> bao nhiêu quyển sách?', img: 'assets/ttd2/d10_da-bar6.svg',
      opts: o4('16', '14', '12', '15'), ans: 'B',
      why: 'Cộng số sách của bốn bạn: 5 + 2 + 3 + 4 = 14 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 8', pts: 0.5,
      text: 'Bạn Lan đọc <b>nhiều hơn</b> (hoặc ít hơn) bạn Bình bao nhiêu quyển?', img: 'assets/ttd2/d10_da-bar7.svg',
      opts: o4('7', '8', '9', '13'), ans: 'A',
      why: 'Chênh lệch là 10 − 3 = 7 quyển.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 9', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 1 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd2/d10_da-pic0.svg',
      opts: o4('6', '7', '5', '8'), ans: 'A',
      why: 'Lớp Lan có 6 ngôi sao, mỗi sao 1 huy chương: 6 × 1 = 6 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 10', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 2 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd2/d10_da-pic1.svg',
      opts: o4('3', '8', '4', '6'), ans: 'D',
      why: 'Lớp Lan có 3 ngôi sao, mỗi sao 2 huy chương: 3 × 2 = 6 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 11', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 5 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd2/d10_da-pic2.svg',
      opts: o4('30', '6', '35', '25'), ans: 'A',
      why: 'Lớp Lan có 6 ngôi sao, mỗi sao 5 huy chương: 6 × 5 = 30 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 12', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 2 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd2/d10_da-pic3.svg',
      opts: o4('3', '8', '4', '6'), ans: 'D',
      why: 'Lớp Lan có 3 ngôi sao, mỗi sao 2 huy chương: 3 × 2 = 6 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 13', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 3 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd2/d10_da-pic4.svg',
      opts: o4('2', '9', '3', '6'), ans: 'D',
      why: 'Lớp Lan có 2 ngôi sao, mỗi sao 3 huy chương: 2 × 3 = 6 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 14', pts: 0.5,
      text: 'Mỗi ⭐ ứng với 10 huy chương. Lớp <b>Lan</b> có bao nhiêu huy chương?', img: 'assets/ttd2/d10_da-pic5.svg',
      opts: o4('6', '70', '60', '50'), ans: 'C',
      why: 'Lớp Lan có 6 ngôi sao, mỗi sao 10 huy chương: 6 × 10 = 60 huy chương.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 15', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. Cả bốn ngày bán được <b>tất cả</b> bao nhiêu cốc?', img: 'assets/ttd2/d10_da-tab0.svg',
      opts: o4('31', '25', '28', '29'), ans: 'C',
      why: 'Cộng số cốc bốn ngày: 6 + 11 + 4 + 7 = 28 cốc.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 16', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. <b>Ngày nào</b> bán được nhiều cốc nhất?', img: 'assets/ttd2/d10_da-tab1.svg',
      opts: o4('T2', 'T4', 'T3', 'T5'), ans: 'B',
      why: 'Số lớn nhất trong bảng là 8 (ngày T4).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 17', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. Cả bốn ngày bán được <b>tất cả</b> bao nhiêu cốc?', img: 'assets/ttd2/d10_da-tab2.svg',
      opts: o4('31', '34', '28', '32'), ans: 'A',
      why: 'Cộng số cốc bốn ngày: 10 + 4 + 11 + 6 = 31 cốc.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 18', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. <b>Ngày nào</b> bán được nhiều cốc nhất?', img: 'assets/ttd2/d10_da-tab3.svg',
      opts: o4('T2', 'T4', 'T3', 'T5'), ans: 'B',
      why: 'Số lớn nhất trong bảng là 11 (ngày T4).' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 19', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. Cả bốn ngày bán được <b>tất cả</b> bao nhiêu cốc?', img: 'assets/ttd2/d10_da-tab4.svg',
      opts: o4('30', '24', '27', '28'), ans: 'C',
      why: 'Cộng số cốc bốn ngày: 10 + 6 + 8 + 3 = 27 cốc.' },
    { sec: 'Dạng 10 · Đọc bảng, biểu đồ (Data & Graph)', name: 'Câu 20', pts: 0.5,
      text: 'Bảng ghi số cốc nước bán được mỗi ngày. <b>Ngày nào</b> bán được nhiều cốc nhất?', img: 'assets/ttd2/d10_da-tab5.svg',
      opts: o4('T2', 'T3', 'T5', 'T4'), ans: 'C',
      why: 'Số lớn nhất trong bảng là 12 (ngày T5).' },
  ],
},
{
  id: 3211, title: 'Dạng 11 · Toán có lời văn (Word Problem)', time: 25,
  questions: [
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 1', pts: 0.5,
      text: 'Anh có 39 cái kẹo, em có nhiều hơn anh 11 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd2/d11_wo-more0.svg',
      opts: o4('78', '50', '100', '89'), ans: 'D',
      why: 'Em có 39 + 11 = 50 cái. Cả hai có 39 + 50 = 89 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 2', pts: 0.5,
      text: 'Anh có 26 cái kẹo, em có nhiều hơn anh 5 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd2/d11_wo-more1.svg',
      opts: o4('52', '31', '57', '62'), ans: 'C',
      why: 'Em có 26 + 5 = 31 cái. Cả hai có 26 + 31 = 57 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 3', pts: 0.5,
      text: 'Anh có 17 cái kẹo, em có nhiều hơn anh 9 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd2/d11_wo-more2.svg',
      opts: o4('43', '34', '26', '52'), ans: 'A',
      why: 'Em có 17 + 9 = 26 cái. Cả hai có 17 + 26 = 43 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 4', pts: 0.5,
      text: 'Anh có 21 cái kẹo, em có nhiều hơn anh 17 cái. Hỏi <b>cả hai anh em</b> có bao nhiêu cái kẹo?', img: 'assets/ttd2/d11_wo-more3.svg',
      opts: o4('59', '42', '38', '76'), ans: 'A',
      why: 'Em có 21 + 17 = 38 cái. Cả hai có 21 + 38 = 59 cái kẹo.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 5', pts: 0.5,
      text: 'Nhà bạn Lan có 5 con gà, số vịt gấp 4 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd2/d11_wo-times0.svg',
      opts: o4('20', '25', '9', '30'), ans: 'B',
      why: 'Số vịt là 5 × 4 = 20 con. Cả gà và vịt: 5 + 20 = 25 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 6', pts: 0.5,
      text: 'Nhà bạn Lan có 5 con gà, số vịt gấp 2 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd2/d11_wo-times1.svg',
      opts: o4('10', '7', '20', '15'), ans: 'D',
      why: 'Số vịt là 5 × 2 = 10 con. Cả gà và vịt: 5 + 10 = 15 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 7', pts: 0.5,
      text: 'Nhà bạn Lan có 4 con gà, số vịt gấp 3 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd2/d11_wo-times2.svg',
      opts: o4('12', '7', '20', '16'), ans: 'D',
      why: 'Số vịt là 4 × 3 = 12 con. Cả gà và vịt: 4 + 12 = 16 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 8', pts: 0.5,
      text: 'Nhà bạn Lan có 4 con gà, số vịt gấp 3 lần số gà. Hỏi nhà Lan có <b>tất cả</b> bao nhiêu con gà và vịt?', img: 'assets/ttd2/d11_wo-times3.svg',
      opts: o4('12', '7', '16', '20'), ans: 'C',
      why: 'Số vịt là 4 × 3 = 12 con. Cả gà và vịt: 4 + 12 = 16 con.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 9', pts: 0.5,
      text: 'Có 6 hộp bút, mỗi hộp 7 chiếc. Người ta đã bán 28 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('42', '70', '14', '15'), ans: 'C',
      why: 'Tổng số bút: 6 × 7 = 42 chiếc. Còn lại: 42 − 28 = 14 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 10', pts: 0.5,
      text: 'Có 8 hộp bút, mỗi hộp 9 chiếc. Người ta đã bán 17 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('72', '89', '56', '55'), ans: 'D',
      why: 'Tổng số bút: 8 × 9 = 72 chiếc. Còn lại: 72 − 17 = 55 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 11', pts: 0.5,
      text: 'Có 3 hộp bút, mỗi hộp 8 chiếc. Người ta đã bán 3 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('24', '21', '27', '22'), ans: 'B',
      why: 'Tổng số bút: 3 × 8 = 24 chiếc. Còn lại: 24 − 3 = 21 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 12', pts: 0.5,
      text: 'Có 9 hộp bút, mỗi hộp 9 chiếc. Người ta đã bán 25 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('81', '106', '56', '57'), ans: 'C',
      why: 'Tổng số bút: 9 × 9 = 81 chiếc. Còn lại: 81 − 25 = 56 chiếc.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 13', pts: 0.5,
      text: 'Có 36 chiếc bánh chia đều vào 4 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('10', '4', '32', '9'), ans: 'D',
      why: 'Mỗi đĩa có 36 : 4 = 9 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 14', pts: 0.5,
      text: 'Có 16 chiếc bánh chia đều vào 4 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('4', '5', '12', '3'), ans: 'A',
      why: 'Mỗi đĩa có 16 : 4 = 4 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 15', pts: 0.5,
      text: 'Có 6 chiếc bánh chia đều vào 2 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('4', '2', '3', '5'), ans: 'C',
      why: 'Mỗi đĩa có 6 : 2 = 3 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 16', pts: 0.5,
      text: 'Có 16 chiếc bánh chia đều vào 8 đĩa. Hỏi <b>mỗi đĩa</b> có bao nhiêu chiếc bánh?',
      opts: o4('3', '2', '8', '1'), ans: 'B',
      why: 'Mỗi đĩa có 16 : 8 = 2 chiếc bánh.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 17', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 18 rồi bớt đi 4 thì được 27. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('13', '27', '31', '9'), ans: 'A',
      why: 'Tính ngược: 27 + 4 − 18 = 31 − 18 = 13.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 18', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 8 rồi bớt đi 8 thì được 37. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('37', '45', '29', '38'), ans: 'A',
      why: 'Tính ngược: 37 + 8 − 8 = 45 − 8 = 37.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 19', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 12 rồi bớt đi 9 thì được 42. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('42', '51', '30', '39'), ans: 'D',
      why: 'Tính ngược: 42 + 9 − 12 = 51 − 12 = 39.' },
    { sec: 'Dạng 11 · Toán có lời văn (Word Problem)', name: 'Câu 20', pts: 0.5,
      text: 'Một bạn nghĩ ra một số, cộng thêm 19 rồi bớt đi 9 thì được 39. Hỏi bạn đã nghĩ ra số nào?',
      opts: o4('39', '29', '48', '20'), ans: 'B',
      why: 'Tính ngược: 39 + 9 − 19 = 48 − 19 = 29.' },
  ],
},
{
  id: 3212, title: 'Dạng 12 · Bài toán khó (Non-routine)', time: 25,
  questions: [
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 1', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd2/d12_nr-magic0.svg',
      opts: o4('11', '12', '10', '27'), ans: 'A',
      why: 'Tổng mỗi hàng là 27. Lấy 27 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 11.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 2', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd2/d12_nr-magic1.svg',
      opts: o4('14', '13', '12', '27'), ans: 'B',
      why: 'Tổng mỗi hàng là 27. Lấy 27 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 13.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 3', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd2/d12_nr-magic2.svg',
      opts: o4('10', '8', '18', '9'), ans: 'D',
      why: 'Tổng mỗi hàng là 18. Lấy 18 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 9.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 4', pts: 0.5,
      text: 'Trong bảng, tổng ba số ở mỗi hàng, mỗi cột đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttd2/d12_nr-magic3.svg',
      opts: o4('12', '13', '11', '30'), ans: 'A',
      why: 'Tổng mỗi hàng là 30. Lấy 30 trừ hai số đã biết cùng hàng/cột để tìm ô còn thiếu: 12.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 5', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd2/d12_nr-dice0.svg',
      opts: o4('10', '11', '9', '12'), ans: 'A',
      why: 'Cộng số chấm: 6 + 2 + 2 = 10 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 6', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd2/d12_nr-dice1.svg',
      opts: o4('14', '12', '15', '13'), ans: 'D',
      why: 'Cộng số chấm: 1 + 6 + 6 = 13 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 7', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd2/d12_nr-dice2.svg',
      opts: o4('15', '14', '13', '16'), ans: 'B',
      why: 'Cộng số chấm: 4 + 5 + 5 = 14 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 8', pts: 0.5,
      text: 'Đếm tổng số chấm trên các mặt xúc xắc.', img: 'assets/ttd2/d12_nr-dice3.svg',
      opts: o4('14', '12', '13', '15'), ans: 'C',
      why: 'Cộng số chấm: 4 + 6 + 3 = 13 chấm.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 9', pts: 0.5,
      text: 'Trong sân có 2 con gà và 4 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('20', '6', '22', '16'), ans: 'A',
      why: 'Gà 2 chân: 2 × 2 = 4. Chó 4 chân: 4 × 4 = 16. Tất cả: 4 + 16 = 20 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 10', pts: 0.5,
      text: 'Trong sân có 5 con gà và 6 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('11', '36', '34', '32'), ans: 'C',
      why: 'Gà 2 chân: 5 × 2 = 10. Chó 4 chân: 6 × 4 = 24. Tất cả: 10 + 24 = 34 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 11', pts: 0.5,
      text: 'Trong sân có 6 con gà và 3 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('9', '26', '30', '24'), ans: 'D',
      why: 'Gà 2 chân: 6 × 2 = 12. Chó 4 chân: 3 × 4 = 12. Tất cả: 12 + 12 = 24 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 12', pts: 0.5,
      text: 'Trong sân có 6 con gà và 5 con chó. Hỏi tất cả có bao nhiêu <b>cái chân</b>?',
      opts: o4('11', '34', '32', '33'), ans: 'C',
      why: 'Gà 2 chân: 6 × 2 = 12. Chó 4 chân: 5 × 4 = 20. Tất cả: 12 + 20 = 32 chân.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 13', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 8 m, hai cây liền nhau cách nhau 2 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('4', '5', '6', '7'), ans: 'B',
      why: 'Số khoảng cách là 8 : 2 = 4. Trồng cả hai đầu nên số cây = số khoảng + 1 = 5 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 14', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 9 m, hai cây liền nhau cách nhau 3 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('3', '5', '4', '6'), ans: 'C',
      why: 'Số khoảng cách là 9 : 3 = 3. Trồng cả hai đầu nên số cây = số khoảng + 1 = 4 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 15', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 25 m, hai cây liền nhau cách nhau 5 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('5', '7', '6', '8'), ans: 'C',
      why: 'Số khoảng cách là 25 : 5 = 5. Trồng cả hai đầu nên số cây = số khoảng + 1 = 6 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 16', pts: 0.5,
      text: 'Người ta trồng cây dọc một đoạn đường dài 12 m, hai cây liền nhau cách nhau 4 m, trồng cả ở <b>hai đầu</b> đường. Hỏi cần bao nhiêu cây?',
      opts: o4('4', '3', '5', '6'), ans: 'A',
      why: 'Số khoảng cách là 12 : 4 = 3. Trồng cả hai đầu nên số cây = số khoảng + 1 = 4 cây.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 17', pts: 0.5,
      text: 'Năm nay con 7 tuổi, bố hơn con 24 tuổi. Hỏi <b>bố</b> năm nay bao nhiêu tuổi?',
      opts: o4('31', '14', '24', '33'), ans: 'A',
      why: 'Tuổi bố = 7 + 24 = 31 tuổi.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 18', pts: 0.5,
      text: 'Năm nay con 7 tuổi. Hỏi <b>sau 3 năm nữa</b> con bao nhiêu tuổi?',
      opts: o4('10', '7', '3', '11'), ans: 'A',
      why: 'Sau 3 năm, tuổi con là 7 + 3 = 10 tuổi.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 19', pts: 0.5,
      text: 'Năm nay con 10 tuổi, bố hơn con 25 tuổi. Hỏi <b>bố</b> năm nay bao nhiêu tuổi?',
      opts: o4('20', '35', '25', '37'), ans: 'B',
      why: 'Tuổi bố = 10 + 25 = 35 tuổi.' },
    { sec: 'Dạng 12 · Bài toán khó (Non-routine)', name: 'Câu 20', pts: 0.5,
      text: 'Năm nay con 6 tuổi. Hỏi <b>sau 6 năm nữa</b> con bao nhiêu tuổi?',
      opts: o4('6', '13', '12', '11'), ans: 'C',
      why: 'Sau 6 năm, tuổi con là 6 + 6 = 12 tuổi.' },
  ],
},
];

// Chèn môn "Toán tư duy 12 dạng" cho lớp 2
SUBJECTS.push({
  id: 'ttd2', name: 'Tư duy 12 dạng', short: 'Tư duy 2', icon: '💡', grade: 2,
  exams: TTD2, ready: true,
  heroTitle: 'Toán tư duy 12 dạng — lớp 2',
  heroMeta: '📚 12 dạng &nbsp;•&nbsp; 240 câu &nbsp;•&nbsp; ⏱ 25 phút mỗi đề &nbsp;•&nbsp; 137 câu có hình (57%) &nbsp;•&nbsp; lời giải chi tiết',
});
