// TOÁN LỚP 2 QUA HÌNH — BÀI HỌC · 10 đề × 10 câu = 100 câu, 100% câu có hình SVG.
// SINH TỰ ĐỘNG bởi tools/gen-hinh-baihoc.mjs (module tools/hinhb-q2.mjs) — sửa trong script rồi chạy lại:
//     node tools/gen-hinh-baihoc.mjs
// Bài 26 · 46 · 15 · 16 · 55 · 37–44 · 51 · 64 · 66 · 56 · 30 (SGK Kết nối tri thức)
// Hình vẽ bằng code (assets/hinhb2/), đáp án lấy thẳng từ dữ liệu vẽ hình nên không bao giờ lệch.

const HINHB2_EXAMS = [
{
  id: 9501, title: "Đề 1 · Đường gấp khúc — độ dài", time: 25,
  questions: [
    { sec: "Đường gấp khúc", name: "Câu 1", pts: 1, text: "Đường gấp khúc ABCDE có độ dài các đoạn thẳng ghi trên hình. Độ dài đường gấp khúc ABCDE là bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c1.svg", opts: o4("35 cm", "33 cm", "25 cm", "34 cm"), ans: "D", why: "Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng: 6 + 6 + 13 + 9 = 34 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 2", pts: 1, text: "Đường gấp khúc ABCDE có độ dài các đoạn thẳng ghi trên hình. Độ dài đường gấp khúc ABCDE là bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c2.svg", opts: o4("18 cm", "16 cm", "15 cm", "17 cm"), ans: "D", why: "Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng: 5 + 3 + 7 + 2 = 17 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 3", pts: 1, text: "Đường gấp khúc ABCDE dài 36 cm. Độ dài các đoạn thẳng còn lại ghi trên hình. Đoạn thẳng DE dài bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c3.svg", opts: o4("12 cm", "13 cm", "11 cm", "24 cm"), ans: "A", why: "DE = 36 − (7 + 9 + 8) = 36 − 24 = 12 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 4", pts: 1, text: "Đường gấp khúc ABCD có độ dài các đoạn thẳng ghi trên hình. Độ dài đường gấp khúc ABCD là bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c4.svg", opts: o4("27 cm", "25 cm", "26 cm", "19 cm"), ans: "C", why: "Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng: 8 + 11 + 7 = 26 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 5", pts: 1, text: "Đường gấp khúc ABCD dài 22 cm. Độ dài các đoạn thẳng còn lại ghi trên hình. Đoạn thẳng BC dài bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c5.svg", opts: o4("4 cm", "2 cm", "3 cm", "19 cm"), ans: "C", why: "BC = 22 − (15 + 4) = 22 − 19 = 3 (cm)." },
    { sec: "So sánh độ dài", name: "Câu 6", pts: 1, text: "Băng giấy B dài hơn băng giấy A bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c6.svg", opts: o4("38 cm", "14 cm", "15 cm", "13 cm"), ans: "B", why: "Băng B dài hơn: 26 − 12 = 14 (cm)." },
    { sec: "So sánh độ dài", name: "Câu 7", pts: 1, text: "Băng giấy A dài hơn băng giấy B bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c7.svg", opts: o4("30 cm", "12 cm", "13 cm", "11 cm"), ans: "B", why: "Băng A dài hơn: 21 − 9 = 12 (cm)." },
    { sec: "So sánh độ dài", name: "Câu 8", pts: 1, text: "Băng giấy A dài hơn băng giấy B bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d1c8.svg", opts: o4("5 cm", "29 cm", "6 cm", "4 cm"), ans: "A", why: "Băng A dài hơn: 17 − 12 = 5 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 9", pts: 1, text: "Đường gấp khúc nào gồm đúng 2 đoạn thẳng?", opts: [{ k: 'A', img: "assets/hinhb2/d1c9a.svg" }, { k: 'B', img: "assets/hinhb2/d1c9b.svg" }, { k: 'C', img: "assets/hinhb2/d1c9c.svg" }, { k: 'D', img: "assets/hinhb2/d1c9d.svg" }], ans: "C", why: "Đếm số đoạn thẳng nối liền nhau: hình đúng có 2 đoạn thẳng (3 điểm). Đường cong không phải đường gấp khúc." },
    { sec: "Đường gấp khúc", name: "Câu 10", pts: 1, text: "Đường gấp khúc nào gồm đúng 3 đoạn thẳng?", opts: [{ k: 'A', img: "assets/hinhb2/d1c10a.svg" }, { k: 'B', img: "assets/hinhb2/d1c10b.svg" }, { k: 'C', img: "assets/hinhb2/d1c10c.svg" }, { k: 'D', img: "assets/hinhb2/d1c10d.svg" }], ans: "A", why: "Đếm số đoạn thẳng nối liền nhau: hình đúng có 3 đoạn thẳng (4 điểm). Đường cong không phải đường gấp khúc." },
  ],
},
{
  id: 9502, title: "Đề 2 · Hình tứ giác — hình tam giác", time: 25,
  questions: [
    { sec: "Hình tứ giác", name: "Câu 1", pts: 1, text: "Trong hình có bao nhiêu hình tứ giác?", img: "assets/hinhb2/d2c1.svg", opts: o4("3", "4", "2", "1"), ans: "A", why: "Hình tứ giác có 4 cạnh, 4 đỉnh. Đó là các hình số 3, 4, 6 → có 3 hình." },
    { sec: "Hình tứ giác", name: "Câu 2", pts: 1, text: "Trong hình có bao nhiêu hình tam giác?", img: "assets/hinhb2/d2c2.svg", opts: o4("2", "0", "1", "3"), ans: "C", why: "Hình tam giác có 3 cạnh, 3 đỉnh. Đó là các hình số 2 → có 1 hình." },
    { sec: "Hình tứ giác", name: "Câu 3", pts: 1, text: "Trong hình có bao nhiêu hình tứ giác?", img: "assets/hinhb2/d2c3.svg", opts: o4("5", "4", "3", "2"), ans: "B", why: "Hình tứ giác có 4 cạnh, 4 đỉnh. Đó là các hình số 1, 3, 6, 8 → có 4 hình." },
    { sec: "Hình tứ giác", name: "Câu 4", pts: 1, text: "Trong hình có bao nhiêu hình tam giác?", img: "assets/hinhb2/d2c4.svg", opts: o4("3", "1", "5", "2"), ans: "D", why: "Hình tam giác có 3 cạnh, 3 đỉnh. Đó là các hình số 2, 4 → có 2 hình." },
    { sec: "Hình tứ giác", name: "Câu 5", pts: 1, text: "Hình nào là hình tứ giác?", opts: [{ k: 'A', img: "assets/hinhb2/d2c5a.svg" }, { k: 'B', img: "assets/hinhb2/d2c5b.svg" }, { k: 'C', img: "assets/hinhb2/d2c5c.svg" }, { k: 'D', img: "assets/hinhb2/d2c5d.svg" }], ans: "D", why: "Hình tứ giác có 4 cạnh và 4 đỉnh. Các hình còn lại có 3 cạnh, 5–6 cạnh hoặc không có cạnh thẳng." },
    { sec: "Hình tứ giác", name: "Câu 6", pts: 1, text: "Hình nào là hình tứ giác?", opts: [{ k: 'A', img: "assets/hinhb2/d2c6a.svg" }, { k: 'B', img: "assets/hinhb2/d2c6b.svg" }, { k: 'C', img: "assets/hinhb2/d2c6c.svg" }, { k: 'D', img: "assets/hinhb2/d2c6d.svg" }], ans: "A", why: "Hình tứ giác có 4 cạnh và 4 đỉnh. Các hình còn lại có 3 cạnh, 5–6 cạnh hoặc không có cạnh thẳng." },
    { sec: "Hình tam giác", name: "Câu 7", pts: 1, text: "Hình nào là hình tam giác?", opts: [{ k: 'A', img: "assets/hinhb2/d2c7a.svg" }, { k: 'B', img: "assets/hinhb2/d2c7b.svg" }, { k: 'C', img: "assets/hinhb2/d2c7c.svg" }, { k: 'D', img: "assets/hinhb2/d2c7d.svg" }], ans: "A", why: "Hình tam giác có đúng 3 cạnh và 3 đỉnh." },
    { sec: "Đường gấp khúc", name: "Câu 8", pts: 1, text: "Đường gấp khúc ABCD có độ dài các đoạn thẳng ghi trên hình. Độ dài đường gấp khúc ABCD là bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d2c8.svg", opts: o4("18 cm", "17 cm", "16 cm", "12 cm"), ans: "B", why: "Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng: 4 + 8 + 5 = 17 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 9", pts: 1, text: "Đường gấp khúc ABCDE có độ dài các đoạn thẳng ghi trên hình. Độ dài đường gấp khúc ABCDE là bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d2c9.svg", opts: o4("31 cm", "29 cm", "30 cm", "18 cm"), ans: "C", why: "Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng: 2 + 8 + 8 + 12 = 30 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 10", pts: 1, text: "Đường gấp khúc ABCDE dài 33 cm. Độ dài các đoạn thẳng còn lại ghi trên hình. Đoạn thẳng BC dài bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d2c10.svg", opts: o4("8 cm", "7 cm", "6 cm", "26 cm"), ans: "B", why: "BC = 33 − (9 + 9 + 8) = 33 − 26 = 7 (cm)." },
  ],
},
{
  id: 9503, title: "Đề 3 · Khối trụ — khối cầu — khối hộp", time: 25,
  questions: [
    { sec: "Hình khối", name: "Câu 1", pts: 1, text: "Trong hình có bao nhiêu khối cầu?", img: "assets/hinhb2/d3c1.svg", opts: o4("1", "2", "0", "5"), ans: "A", why: "Khối cầu là các hình số 1 → có 1 khối." },
    { sec: "Hình khối", name: "Câu 2", pts: 1, text: "Trong hình có bao nhiêu khối cầu?", img: "assets/hinhb2/d3c2.svg", opts: o4("4", "2", "3", "5"), ans: "C", why: "Khối cầu là các hình số 1, 3, 4 → có 3 khối." },
    { sec: "Hình khối", name: "Câu 3", pts: 1, text: "Trong hình có bao nhiêu khối hộp chữ nhật?", img: "assets/hinhb2/d3c3.svg", opts: o4("3", "4", "2", "5"), ans: "A", why: "Khối hộp chữ nhật là các hình số 2, 5, 8 → có 3 khối." },
    { sec: "Hình khối", name: "Câu 4", pts: 1, text: "Trong hình có bao nhiêu khối hộp chữ nhật?", img: "assets/hinhb2/d3c4.svg", opts: o4("3", "1", "6", "2"), ans: "D", why: "Khối hộp chữ nhật là các hình số 3, 8 → có 2 khối." },
    { sec: "Hình khối", name: "Câu 5", pts: 1, text: "Trong hình có bao nhiêu khối hộp chữ nhật?", img: "assets/hinhb2/d3c5.svg", opts: o4("2", "1", "0", "5"), ans: "B", why: "Khối hộp chữ nhật là các hình số 3 → có 1 khối." },
    { sec: "Hình khối", name: "Câu 6", pts: 1, text: "Trong hình có bao nhiêu khối lập phương?", img: "assets/hinhb2/d3c6.svg", opts: o4("2", "0", "1", "7"), ans: "C", why: "Khối lập phương là các hình số 2 → có 1 khối." },
    { sec: "Hình khối", name: "Câu 7", pts: 1, text: "Hình nào là khối trụ?", opts: [{ k: 'A', img: "assets/hinhb2/d3c7a.svg" }, { k: 'B', img: "assets/hinhb2/d3c7b.svg" }, { k: 'C', img: "assets/hinhb2/d3c7c.svg" }, { k: 'D', img: "assets/hinhb2/d3c7d.svg" }], ans: "B", why: "Khối trụ có hai mặt đáy là hình tròn và một mặt cong bao quanh." },
    { sec: "Hình khối", name: "Câu 8", pts: 1, text: "Hình nào là khối cầu?", opts: [{ k: 'A', img: "assets/hinhb2/d3c8a.svg" }, { k: 'B', img: "assets/hinhb2/d3c8b.svg" }, { k: 'C', img: "assets/hinhb2/d3c8c.svg" }, { k: 'D', img: "assets/hinhb2/d3c8d.svg" }], ans: "D", why: "Khối cầu tròn đều mọi phía, không có mặt phẳng." },
    { sec: "Hình khối", name: "Câu 9", pts: 1, text: "Hình nào là khối lập phương?", opts: [{ k: 'A', img: "assets/hinhb2/d3c9a.svg" }, { k: 'B', img: "assets/hinhb2/d3c9b.svg" }, { k: 'C', img: "assets/hinhb2/d3c9c.svg" }, { k: 'D', img: "assets/hinhb2/d3c9d.svg" }], ans: "A", why: "Khối lập phương có 6 mặt đều là hình vuông bằng nhau." },
    { sec: "Hình khối", name: "Câu 10", pts: 1, text: "Hình nào là khối hộp chữ nhật?", opts: [{ k: 'A', img: "assets/hinhb2/d3c10a.svg" }, { k: 'B', img: "assets/hinhb2/d3c10b.svg" }, { k: 'C', img: "assets/hinhb2/d3c10c.svg" }, { k: 'D', img: "assets/hinhb2/d3c10d.svg" }], ans: "C", why: "Khối hộp chữ nhật có 6 mặt là hình chữ nhật." },
  ],
},
{
  id: 9504, title: "Đề 4 · Ki-lô-gam — Lít", time: 25,
  questions: [
    { sec: "Ki-lô-gam", name: "Câu 1", pts: 1, text: "Cân đang thăng bằng như hình. Túi muối nặng bao nhiêu ki-lô-gam?", img: "assets/hinhb2/d4c1.svg", opts: o4("8 kg", "6 kg", "7 kg", "9 kg"), ans: "C", why: "Hai bên nặng bằng nhau nên muối nặng bằng tổng các quả cân: 5 + 2 = 7 (kg)." },
    { sec: "Ki-lô-gam", name: "Câu 2", pts: 1, text: "Cân đang thăng bằng như hình. Túi đường nặng bao nhiêu ki-lô-gam?", img: "assets/hinhb2/d4c2.svg", opts: o4("8 kg", "6 kg", "7 kg", "5 kg"), ans: "B", why: "Hai bên nặng bằng nhau: đường + 2 kg = 5 + 2 + 1 = 8 kg, nên đường nặng 8 − 2 = 6 (kg)." },
    { sec: "Ki-lô-gam", name: "Câu 3", pts: 1, text: "Cân đang thăng bằng như hình. Túi gạo nặng bao nhiêu ki-lô-gam?", img: "assets/hinhb2/d4c3.svg", opts: o4("4 kg", "5 kg", "3 kg", "6 kg"), ans: "A", why: "Hai bên nặng bằng nhau: gạo + 1 kg = 5 = 5 kg, nên gạo nặng 5 − 1 = 4 (kg)." },
    { sec: "Ki-lô-gam", name: "Câu 4", pts: 1, text: "Cân đang thăng bằng như hình. Quả dưa nặng bao nhiêu ki-lô-gam?", img: "assets/hinhb2/d4c4.svg", opts: o4("14 kg", "10 kg", "8 kg", "9 kg"), ans: "D", why: "Hai bên nặng bằng nhau: dưa + 5 kg = 5 + 5 + 2 + 2 = 14 kg, nên dưa nặng 14 − 5 = 9 (kg)." },
    { sec: "Ki-lô-gam", name: "Câu 5", pts: 1, text: "Cân đang thăng bằng như hình. Túi đường nặng bao nhiêu ki-lô-gam?", img: "assets/hinhb2/d4c5.svg", opts: o4("13 kg", "11 kg", "12 kg", "14 kg"), ans: "C", why: "Hai bên nặng bằng nhau nên đường nặng bằng tổng các quả cân: 5 + 5 + 2 = 12 (kg)." },
    { sec: "Lít", name: "Câu 6", pts: 1, text: "Can đựng được 20 l nước, ca đựng được 2 l. Muốn đổ đầy can thì cần đổ bao nhiêu ca nước?", img: "assets/hinhb2/d4c6.svg", opts: o4("11 ca", "10 ca", "9 ca", "18 ca"), ans: "B", why: "Số ca cần đổ: 20 : 2 = 10 (ca)." },
    { sec: "Lít", name: "Câu 7", pts: 1, text: "Can đựng được 6 l nước, ca đựng được 3 l. Muốn đổ đầy can thì cần đổ bao nhiêu ca nước?", img: "assets/hinhb2/d4c7.svg", opts: o4("2 ca", "3 ca", "1 ca", "9 ca"), ans: "A", why: "Số ca cần đổ: 6 : 3 = 2 (ca)." },
    { sec: "Lít", name: "Câu 8", pts: 1, text: "Có 2 can nước, số lít ghi trên mỗi can như hình. Hỏi tất cả có bao nhiêu lít nước?", img: "assets/hinhb2/d4c8.svg", opts: o4("15 l", "16 l", "14 l", "20 l"), ans: "A", why: "Tất cả có: 5 + 10 = 15 (l)." },
    { sec: "Lít", name: "Câu 9", pts: 1, text: "Có 3 xô nước, số lít ghi trên mỗi xô như hình. Hỏi tất cả có bao nhiêu lít nước?", img: "assets/hinhb2/d4c9.svg", opts: o4("31 l", "29 l", "35 l", "30 l"), ans: "D", why: "Tất cả có: 5 + 5 + 20 = 30 (l)." },
    { sec: "Lít", name: "Câu 10", pts: 1, text: "Có 2 bình nước, số lít ghi trên mỗi bình như hình. Hỏi tất cả có bao nhiêu lít nước?", img: "assets/hinhb2/d4c10.svg", opts: o4("26 l", "24 l", "45 l", "25 l"), ans: "D", why: "Tất cả có: 20 + 5 = 25 (l)." },
  ],
},
{
  id: 9505, title: "Đề 5 · Đề-xi-mét — Mét", time: 25,
  questions: [
    { sec: "Đề-xi-mét", name: "Câu 1", pts: 1, text: "Đặt sợi dây dọc theo thước đo có vạch đề-xi-mét như hình. Sợi dây dài bao nhiêu đề-xi-mét?", img: "assets/hinhb2/d5c1.svg", opts: o4("2 dm", "20 dm", "3 dm", "1 dm"), ans: "A", why: "Từ vạch 0 đến vạch 2 là 2 − 0 = 2 (dm)." },
    { sec: "Đề-xi-mét", name: "Câu 2", pts: 1, text: "Đặt sợi dây dọc theo thước đo có vạch đề-xi-mét như hình. Sợi dây dài bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d5c2.svg", opts: o4("7 cm", "80 cm", "70 cm", "60 cm"), ans: "C", why: "Sợi dây kéo dài từ vạch 2 đến vạch 9, dài 9 − 2 = 7 (dm). 1 dm = 10 cm nên 7 dm = 70 cm." },
    { sec: "Đề-xi-mét", name: "Câu 3", pts: 1, text: "Đặt cây thước dọc theo thước đo có vạch đề-xi-mét như hình. Cây thước dài bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d5c3.svg", opts: o4("2 cm", "30 cm", "20 cm", "10 cm"), ans: "C", why: "Cây thước kéo dài từ vạch 4 đến vạch 6, dài 6 − 4 = 2 (dm). 1 dm = 10 cm nên 2 dm = 20 cm." },
    { sec: "Đề-xi-mét", name: "Câu 4", pts: 1, text: "Đặt sợi dây dọc theo thước đo có vạch đề-xi-mét như hình. Sợi dây dài bao nhiêu đề-xi-mét?", img: "assets/hinhb2/d5c4.svg", opts: o4("80 dm", "8 dm", "9 dm", "7 dm"), ans: "B", why: "Từ vạch 0 đến vạch 8 là 8 − 0 = 8 (dm)." },
    { sec: "Đề-xi-mét", name: "Câu 5", pts: 1, text: "Đặt cây thước dọc theo thước đo có vạch đề-xi-mét như hình. Cây thước dài bao nhiêu đề-xi-mét?", img: "assets/hinhb2/d5c5.svg", opts: o4("100 dm", "11 dm", "9 dm", "10 dm"), ans: "D", why: "Từ vạch 0 đến vạch 10 là 10 − 0 = 10 (dm)." },
    { sec: "So sánh độ dài", name: "Câu 6", pts: 1, text: "Băng giấy A dài hơn băng giấy B bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d5c6.svg", opts: o4("37 cm", "9 cm", "10 cm", "8 cm"), ans: "B", why: "Băng A dài hơn: 23 − 14 = 9 (cm)." },
    { sec: "So sánh độ dài", name: "Câu 7", pts: 1, text: "Băng giấy B dài hơn băng giấy A bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d5c7.svg", opts: o4("38 cm", "7 cm", "5 cm", "6 cm"), ans: "D", why: "Băng B dài hơn: 22 − 16 = 6 (cm)." },
    { sec: "So sánh độ dài", name: "Câu 8", pts: 1, text: "Băng giấy A dài hơn băng giấy B bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d5c8.svg", opts: o4("8 cm", "50 cm", "9 cm", "7 cm"), ans: "A", why: "Băng A dài hơn: 29 − 21 = 8 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 9", pts: 1, text: "Đường gấp khúc ABCD dài 22 cm. Độ dài các đoạn thẳng còn lại ghi trên hình. Đoạn thẳng AB dài bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d5c9.svg", opts: o4("9 cm", "7 cm", "14 cm", "8 cm"), ans: "D", why: "AB = 22 − (5 + 9) = 22 − 14 = 8 (cm)." },
    { sec: "Đường gấp khúc", name: "Câu 10", pts: 1, text: "Đường gấp khúc ABCD có độ dài các đoạn thẳng ghi trên hình. Độ dài đường gấp khúc ABCD là bao nhiêu xăng-ti-mét?", img: "assets/hinhb2/d5c10.svg", opts: o4("15 cm", "13 cm", "14 cm", "10 cm"), ans: "C", why: "Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng: 5 + 5 + 4 = 14 (cm)." },
  ],
},
{
  id: 9506, title: "Đề 6 · Phép nhân — phép chia qua hình", time: 25,
  questions: [
    { sec: "Phép nhân", name: "Câu 1", pts: 1, text: "Phép nhân nào phù hợp với hình bên (mỗi hàng là một nhóm bằng nhau)?", img: "assets/hinhb2/d6c1.svg", opts: o4("3 + 5 = 8", "3 × 5 = 15", "3 × 6 = 18", "4 × 5 = 20"), ans: "B", why: "Mỗi hàng có 3 chấm, 3 được lấy 5 lần: 3 × 5 = 15." },
    { sec: "Phép nhân", name: "Câu 2", pts: 1, text: "Phép nhân nào phù hợp với hình bên (mỗi hàng là một nhóm bằng nhau)?", img: "assets/hinhb2/d6c2.svg", opts: o4("5 + 4 = 9", "5 × 5 = 25", "5 × 4 = 20", "6 × 4 = 24"), ans: "C", why: "Mỗi hàng có 5 chấm, 5 được lấy 4 lần: 5 × 4 = 20." },
    { sec: "Phép nhân", name: "Câu 3", pts: 1, text: "Phép nhân nào phù hợp với hình bên (mỗi hàng là một nhóm bằng nhau)?", img: "assets/hinhb2/d6c3.svg", opts: o4("3 + 6 = 9", "3 × 7 = 21", "4 × 6 = 24", "3 × 6 = 18"), ans: "D", why: "Mỗi hàng có 3 chấm, 3 được lấy 6 lần: 3 × 6 = 18." },
    { sec: "Phép nhân", name: "Câu 4", pts: 1, text: "Hình có tất cả bao nhiêu chấm tròn?", img: "assets/hinhb2/d6c4.svg", opts: o4("9", "25", "15", "20"), ans: "D", why: "Mỗi hàng có 5 chấm, có 4 hàng như thế: 5 × 4 = 20 (chấm)." },
    { sec: "Phép nhân", name: "Câu 5", pts: 1, text: "Phép nhân nào phù hợp với hình bên (mỗi hàng là một nhóm bằng nhau)?", img: "assets/hinhb2/d6c5.svg", opts: o4("5 + 4 = 9", "5 × 4 = 20", "5 × 5 = 25", "6 × 4 = 24"), ans: "B", why: "Mỗi hàng có 5 chấm, 5 được lấy 4 lần: 5 × 4 = 20." },
    { sec: "Phép chia", name: "Câu 6", pts: 1, text: "Chia đều 45 cái kẹo trong hình vào 5 cái đĩa. Mỗi đĩa có mấy cái kẹo?", img: "assets/hinhb2/d6c6.svg", opts: o4("9", "10", "8", "40"), ans: "A", why: "45 : 5 = 9. Mỗi đĩa có 9 cái kẹo." },
    { sec: "Phép chia", name: "Câu 7", pts: 1, text: "Có 16 cái bút như hình, xếp vào các túi, mỗi túi 4 cái bút. Xếp được bao nhiêu túi?", img: "assets/hinhb2/d6c7.svg", opts: o4("5", "3", "12", "4"), ans: "D", why: "16 : 4 = 4. Xếp được 4 túi." },
    { sec: "Phép chia", name: "Câu 8", pts: 1, text: "Có 12 cái bánh như hình, xếp vào các túi, mỗi túi 4 cái bánh. Xếp được bao nhiêu túi?", img: "assets/hinhb2/d6c8.svg", opts: o4("4", "2", "3", "8"), ans: "C", why: "12 : 4 = 3. Xếp được 3 túi." },
    { sec: "Phép chia", name: "Câu 9", pts: 1, text: "Có 14 quả dâu như hình, xếp vào các túi, mỗi túi 7 quả dâu. Xếp được bao nhiêu túi?", img: "assets/hinhb2/d6c9.svg", opts: o4("3", "1", "2", "7"), ans: "C", why: "14 : 7 = 2. Xếp được 2 túi." },
    { sec: "Phép chia", name: "Câu 10", pts: 1, text: "Có 40 cái bánh như hình, xếp vào các túi, mỗi túi 8 cái bánh. Xếp được bao nhiêu túi?", img: "assets/hinhb2/d6c10.svg", opts: o4("6", "5", "4", "32"), ans: "B", why: "40 : 8 = 5. Xếp được 5 túi." },
  ],
},
{
  id: 9507, title: "Đề 7 · Số có ba chữ số — tia số", time: 25,
  questions: [
    { sec: "Số có ba chữ số", name: "Câu 1", pts: 1, text: "Hình dưới biểu diễn số nào? (mỗi ô vuông lớn là 100, mỗi thanh là 10, mỗi ô nhỏ là 1)", img: "assets/hinhb2/d7c1.svg", opts: o4("458", "485", "495", "475"), ans: "B", why: "Có 4 trăm, 8 chục và 5 đơn vị: 400 + 80 + 5 = 485." },
    { sec: "Số có ba chữ số", name: "Câu 2", pts: 1, text: "Hình dưới biểu diễn số nào? (mỗi ô vuông lớn là 100, mỗi thanh là 10, mỗi ô nhỏ là 1)", img: "assets/hinhb2/d7c2.svg", opts: o4("682", "628", "692", "672"), ans: "A", why: "Có 6 trăm, 8 chục và 2 đơn vị: 600 + 80 + 2 = 682." },
    { sec: "Số có ba chữ số", name: "Câu 3", pts: 1, text: "Hình dưới biểu diễn số nào? (mỗi ô vuông lớn là 100, mỗi thanh là 10, mỗi ô nhỏ là 1)", img: "assets/hinhb2/d7c3.svg", opts: o4("302", "330", "310", "320"), ans: "D", why: "Có 3 trăm, 2 chục và 0 đơn vị: 300 + 20 = 320." },
    { sec: "Số có ba chữ số", name: "Câu 4", pts: 1, text: "Hình dưới biểu diễn số nào? (mỗi ô vuông lớn là 100, mỗi thanh là 10, mỗi ô nhỏ là 1)", img: "assets/hinhb2/d7c4.svg", opts: o4("469", "496", "506", "486"), ans: "B", why: "Có 4 trăm, 9 chục và 6 đơn vị: 400 + 90 + 6 = 496." },
    { sec: "Số có ba chữ số", name: "Câu 5", pts: 1, text: "Hình dưới biểu diễn số nào? (mỗi ô vuông lớn là 100, mỗi thanh là 10, mỗi ô nhỏ là 1)", img: "assets/hinhb2/d7c5.svg", opts: o4("485", "458", "468", "448"), ans: "B", why: "Có 4 trăm, 5 chục và 8 đơn vị: 400 + 50 + 8 = 458." },
    { sec: "Tia số", name: "Câu 6", pts: 1, text: "Trên tia số, hai số liền nhau cách nhau một khoảng bằng nhau. Số cần điền vào ô có dấu ? là số nào?", img: "assets/hinhb2/d7c6.svg", opts: o4("280", "278", "279", "281"), ans: "C", why: "Các số cách nhau 1 đơn vị (274, 275, …). Vị trí dấu ? là 278 + 1 = 279." },
    { sec: "Tia số", name: "Câu 7", pts: 1, text: "Trên tia số, hai số liền nhau cách nhau một khoảng bằng nhau. Số cần điền vào ô có dấu ? là số nào?", img: "assets/hinhb2/d7c7.svg", opts: o4("35", "25", "30", "31"), ans: "C", why: "Các số cách nhau 5 đơn vị (20, 25, …). Vị trí dấu ? là 25 + 5 = 30." },
    { sec: "Tia số", name: "Câu 8", pts: 1, text: "Trên tia số, hai số liền nhau cách nhau một khoảng bằng nhau. Số cần điền vào ô có dấu ? là số nào?", img: "assets/hinhb2/d7c8.svg", opts: o4("700", "800", "600", "701"), ans: "A", why: "Các số cách nhau 100 đơn vị (0, 100, …). Vị trí dấu ? là 600 + 100 = 700." },
    { sec: "Tia số", name: "Câu 9", pts: 1, text: "Trên tia số, hai số liền nhau cách nhau một khoảng bằng nhau. Số cần điền vào ô có dấu ? là số nào?", img: "assets/hinhb2/d7c9.svg", opts: o4("300", "100", "201", "200"), ans: "D", why: "Các số cách nhau 100 đơn vị (0, 100, …). Vị trí dấu ? là 100 + 100 = 200." },
    { sec: "Tia số", name: "Câu 10", pts: 1, text: "Trên tia số, hai số liền nhau cách nhau một khoảng bằng nhau. Số cần điền vào ô có dấu ? là số nào?", img: "assets/hinhb2/d7c10.svg", opts: o4("55", "45", "51", "50"), ans: "D", why: "Các số cách nhau 5 đơn vị (20, 25, …). Vị trí dấu ? là 45 + 5 = 50." },
  ],
},
{
  id: 9508, title: "Đề 8 · Kiểm đếm số liệu", time: 25,
  questions: [
    { sec: "Kiểm đếm", name: "Câu 1", pts: 1, text: "Bảng vạch đếm ghi lại \"Con vật nuôi của tổ 1\". Loại nhiều nhất hơn loại ít nhất bao nhiêu con?", img: "assets/hinhb2/d8c1.svg", opts: o4("9", "10", "8", "19"), ans: "A", why: "Nhiều nhất 14, ít nhất 5: 14 − 5 = 9 (con)." },
    { sec: "Kiểm đếm", name: "Câu 2", pts: 1, text: "Bảng vạch đếm ghi lại \"Loại quả các bạn lớp 2A thích\". Loại nhiều nhất hơn loại ít nhất bao nhiêu bạn?", img: "assets/hinhb2/d8c2.svg", opts: o4("11", "10", "9", "16"), ans: "B", why: "Nhiều nhất 13, ít nhất 3: 13 − 3 = 10 (bạn)." },
    { sec: "Kiểm đếm", name: "Câu 3", pts: 1, text: "Bảng vạch đếm ghi lại \"Loại quả các bạn lớp 2A thích\". Có tất cả bao nhiêu bạn?", img: "assets/hinhb2/d8c3.svg", opts: o4("27", "28", "26", "32"), ans: "A", why: "Tổng: 9 + 14 + 4 = 27 (bạn)." },
    { sec: "Kiểm đếm", name: "Câu 4", pts: 1, text: "Bảng vạch đếm ghi lại \"Con vật nuôi của tổ 1\". Có tất cả bao nhiêu con?", img: "assets/hinhb2/d8c4.svg", opts: o4("35", "34", "33", "39"), ans: "B", why: "Tổng: 12 + 11 + 8 + 3 = 34 (con)." },
    { sec: "Kiểm đếm", name: "Câu 5", pts: 1, text: "Bảng vạch đếm ghi lại \"Loại quả các bạn lớp 2A thích\". Loại nào có nhiều bạn nhất?", img: "assets/hinhb2/d8c5.svg", opts: o4("Chuối", "Nho", "Táo", "Cam"), ans: "C", why: "Đếm vạch: Táo 10, Chuối 9, Nho 7. Nhiều nhất là Táo (10)." },
    { sec: "Kiểm đếm", name: "Câu 6", pts: 1, text: "Bảng vạch đếm ghi lại \"Con vật nuôi của tổ 1\". Loại nào có nhiều con nhất?", img: "assets/hinhb2/d8c6.svg", opts: o4("Cá", "Thỏ", "Chó", "Mèo"), ans: "C", why: "Đếm vạch: Chó 10, Cá 7, Thỏ 4. Nhiều nhất là Chó (10)." },
    { sec: "Kiểm đếm", name: "Câu 7", pts: 1, text: "Bảng vạch đếm ghi lại \"Loại quả các bạn lớp 2A thích\". Có bao nhiêu bạn ứng với chuối 🍌?", img: "assets/hinhb2/d8c7.svg", opts: o4("8", "6", "12", "7"), ans: "D", why: "Mỗi nhóm 5 vạch (4 vạch đứng và 1 vạch chéo) là 5. Dòng chuối có 1 nhóm 5 và 2 vạch lẻ: 7." },
    { sec: "Khả năng xảy ra", name: "Câu 8", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Nam lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d8c8.svg", opts: o4("Chắc chắn lấy được bóng màu tím", "Có thể lấy được bóng màu xanh", "Không thể lấy được bóng màu xanh", "Có thể lấy được bóng màu tím"), ans: "B", why: "Hộp có bóng màu xanh và màu đỏ nên có thể lấy được một trong hai màu đó, không chắc chắn màu nào; không có bóng màu tím nên không thể lấy được bóng tím." },
    { sec: "Khả năng xảy ra", name: "Câu 9", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Hà lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d8c9.svg", opts: o4("Không thể lấy được bóng màu vàng", "Chắc chắn lấy được bóng màu vàng", "Có thể lấy được bóng màu vàng", "Chắc chắn lấy được bóng màu tím"), ans: "A", why: "Hộp có bóng màu tím và màu xanh nên có thể lấy được một trong hai màu đó, không chắc chắn màu nào; không có bóng màu vàng nên không thể lấy được bóng vàng." },
    { sec: "Khả năng xảy ra", name: "Câu 10", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Mai lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d8c10.svg", opts: o4("Có thể lấy được bóng màu đỏ", "Có thể lấy được bóng màu xanh", "Chắc chắn lấy được bóng màu đỏ", "Không thể lấy được bóng màu đỏ"), ans: "D", why: "Hộp chỉ có bóng màu tím nên chắc chắn lấy được bóng tím, không thể lấy được bóng màu khác." },
  ],
},
{
  id: 9509, title: "Đề 9 · Chắc chắn — có thể — không thể", time: 25,
  questions: [
    { sec: "Khả năng xảy ra", name: "Câu 1", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Nam lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d9c1.svg", opts: o4("Chắc chắn lấy được bóng màu đỏ", "Có thể lấy được bóng màu tím", "Có thể lấy được bóng màu đỏ", "Không thể lấy được bóng màu đỏ"), ans: "D", why: "Hộp chỉ có bóng màu xanh nên chắc chắn lấy được bóng xanh, không thể lấy được bóng màu khác." },
    { sec: "Khả năng xảy ra", name: "Câu 2", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Mai lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d9c2.svg", opts: o4("Có thể lấy được bóng màu tím", "Có thể lấy được bóng màu vàng", "Chắc chắn lấy được bóng màu xanh", "Chắc chắn lấy được bóng màu vàng"), ans: "C", why: "Hộp chỉ có bóng màu xanh nên chắc chắn lấy được bóng xanh, không thể lấy được bóng màu khác." },
    { sec: "Khả năng xảy ra", name: "Câu 3", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Nam lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d9c3.svg", opts: o4("Có thể lấy được bóng màu xanh", "Có thể lấy được bóng màu đỏ", "Chắc chắn lấy được bóng màu vàng", "Chắc chắn lấy được bóng màu xanh"), ans: "A", why: "Hộp có bóng màu xanh và màu vàng nên có thể lấy được một trong hai màu đó, không chắc chắn màu nào; không có bóng màu đỏ nên không thể lấy được bóng đỏ." },
    { sec: "Khả năng xảy ra", name: "Câu 4", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Việt lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d9c4.svg", opts: o4("Có thể lấy được bóng màu đỏ", "Chắc chắn lấy được bóng màu tím", "Có thể lấy được bóng màu tím", "Chắc chắn lấy được bóng màu xanh"), ans: "D", why: "Hộp chỉ có bóng màu xanh nên chắc chắn lấy được bóng xanh, không thể lấy được bóng màu khác." },
    { sec: "Khả năng xảy ra", name: "Câu 5", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Hà lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d9c5.svg", opts: o4("Chắc chắn lấy được bóng màu đỏ", "Chắc chắn lấy được bóng màu xanh", "Có thể lấy được bóng màu đỏ", "Có thể lấy được bóng màu xanh"), ans: "D", why: "Hộp có bóng màu vàng và màu xanh nên có thể lấy được một trong hai màu đó, không chắc chắn màu nào; không có bóng màu đỏ nên không thể lấy được bóng đỏ." },
    { sec: "Khả năng xảy ra", name: "Câu 6", pts: 1, text: "Trong hộp có các quả bóng như hình. Không nhìn vào hộp, Nam lấy ra một quả bóng. Khẳng định nào đúng?", img: "assets/hinhb2/d9c6.svg", opts: o4("Chắc chắn lấy được bóng màu tím", "Không thể lấy được bóng màu vàng", "Chắc chắn lấy được bóng màu vàng", "Không thể lấy được bóng màu tím"), ans: "B", why: "Hộp có bóng màu tím và màu xanh nên có thể lấy được một trong hai màu đó, không chắc chắn màu nào; không có bóng màu vàng nên không thể lấy được bóng vàng." },
    { sec: "Kiểm đếm", name: "Câu 7", pts: 1, text: "Bảng vạch đếm ghi lại \"Con vật nuôi của tổ 1\". Có bao nhiêu con ứng với mèo 🐱?", img: "assets/hinhb2/d9c7.svg", opts: o4("4", "5", "3", "9"), ans: "A", why: "Mỗi nhóm 5 vạch (4 vạch đứng và 1 vạch chéo) là 5. Dòng mèo có 0 nhóm 5 và 4 vạch lẻ: 4." },
    { sec: "Kiểm đếm", name: "Câu 8", pts: 1, text: "Bảng vạch đếm ghi lại \"Con vật nuôi của tổ 1\". Loại nào có nhiều con nhất?", img: "assets/hinhb2/d9c8.svg", opts: o4("Thỏ", "Chó", "Mèo", "Cá"), ans: "C", why: "Đếm vạch: Mèo 13, Thỏ 9, Chó 11. Nhiều nhất là Mèo (13)." },
    { sec: "Kiểm đếm", name: "Câu 9", pts: 1, text: "Bảng vạch đếm ghi lại \"Loại quả các bạn lớp 2A thích\". Loại nào có nhiều bạn nhất?", img: "assets/hinhb2/d9c9.svg", opts: o4("Táo", "Chuối", "Nho", "Cam"), ans: "C", why: "Đếm vạch: Táo 4, Nho 9, Chuối 6, Cam 8. Nhiều nhất là Nho (9)." },
    { sec: "Kiểm đếm", name: "Câu 10", pts: 1, text: "Bảng vạch đếm ghi lại \"Phương tiện đi học của lớp 2B\". Có bao nhiêu bạn ứng với đi bộ 🚶?", img: "assets/hinhb2/d9c10.svg", opts: o4("4", "3", "2", "8"), ans: "B", why: "Mỗi nhóm 5 vạch (4 vạch đứng và 1 vạch chéo) là 5. Dòng đi bộ có 0 nhóm 5 và 3 vạch lẻ: 3." },
  ],
},
{
  id: 9510, title: "Đề 10 · Tiền Việt Nam — xem lịch", time: 25,
  questions: [
    { sec: "Tiền Việt Nam", name: "Câu 1", pts: 1, text: "Bình có các tờ tiền như hình. Bình có tất cả bao nhiêu tiền?", img: "assets/hinhb2/d10c1.svg", opts: o4("1 700 đồng", "1 500 đồng", "2 100 đồng", "1 600 đồng"), ans: "D", why: "100 + 200 + 1 000 + 200 + 100 = 1 600 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 2", pts: 1, text: "Hoa có các tờ tiền như hình. Hoa có tất cả bao nhiêu tiền?", img: "assets/hinhb2/d10c2.svg", opts: o4("1 300 đồng", "1 200 đồng", "1 100 đồng", "1 700 đồng"), ans: "B", why: "200 + 500 + 500 = 1 200 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 3", pts: 1, text: "Lan có các tờ tiền như hình. Lan có tất cả bao nhiêu tiền?", img: "assets/hinhb2/d10c3.svg", opts: o4("2 700 đồng", "2 500 đồng", "2 600 đồng", "3 100 đồng"), ans: "C", why: "500 + 1 000 + 500 + 100 + 500 = 2 600 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 4", pts: 1, text: "Nam có các tờ tiền như hình và mua một chiếc kẹo giá 1 500 đồng. Nam còn lại bao nhiêu tiền?", img: "assets/hinhb2/d10c4.svg", opts: o4("1 000 đồng", "800 đồng", "900 đồng", "2 400 đồng"), ans: "C", why: "Tổng tiền: 200 + 1 000 + 200 + 1 000 = 2 400 đồng. Còn lại: 2 400 − 1 500 = 900 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 5", pts: 1, text: "Hoa có các tờ tiền như hình và mua một chiếc kẹo giá 1 500 đồng. Hoa còn lại bao nhiêu tiền?", img: "assets/hinhb2/d10c5.svg", opts: o4("200 đồng", "300 đồng", "100 đồng", "1 700 đồng"), ans: "A", why: "Tổng tiền: 200 + 1 000 + 500 = 1 700 đồng. Còn lại: 1 700 − 1 500 = 200 (đồng)." },
    { sec: "Ngày – tháng", name: "Câu 6", pts: 1, text: "Xem tờ lịch. Ngày cuối cùng của tháng 11 năm 2025 là ngày nào, thứ mấy?", img: "assets/hinhb2/d10c6.svg", opts: o4("Ngày 30, Thứ Hai", "Ngày 30, Chủ nhật", "Ngày 31, Chủ nhật", "Ngày 31, Thứ Bảy"), ans: "B", why: "Tháng 11 năm 2025 có 30 ngày; ngày 30 rơi vào Chủ nhật." },
    { sec: "Ngày – tháng", name: "Câu 7", pts: 1, text: "Xem tờ lịch tháng 5. Ngày 22 tháng 5 là thứ mấy?", img: "assets/hinhb2/d10c7.svg", opts: o4("Thứ Sáu", "Thứ Bảy", "Thứ Năm", "Thứ Tư"), ans: "A", why: "Ngày 22 (được khoanh) nằm ở cột Thứ Sáu." },
    { sec: "Ngày – tháng", name: "Câu 8", pts: 1, text: "Xem tờ lịch. Ngày cuối cùng của tháng 5 năm 2025 là ngày nào, thứ mấy?", img: "assets/hinhb2/d10c8.svg", opts: o4("Ngày 31, Chủ nhật", "Ngày 31, Thứ Bảy", "Ngày 30, Thứ Bảy", "Ngày 30, Thứ Sáu"), ans: "B", why: "Tháng 5 năm 2025 có 31 ngày; ngày 31 rơi vào Thứ Bảy." },
    { sec: "Ngày – tháng", name: "Câu 9", pts: 1, text: "Xem tờ lịch tháng 7. Ngày 31 tháng 7 là thứ mấy?", img: "assets/hinhb2/d10c9.svg", opts: o4("Thứ Hai", "Thứ Năm", "Thứ Ba", "Thứ Sáu"), ans: "D", why: "Ngày 31 (được khoanh) nằm ở cột Thứ Sáu." },
    { sec: "Ngày – tháng", name: "Câu 10", pts: 1, text: "Xem tờ lịch tháng 2. Ngày 23 tháng 2 là thứ mấy?", img: "assets/hinhb2/d10c10.svg", opts: o4("Thứ Hai", "Thứ Năm", "Thứ Sáu", "Thứ Ba"), ans: "A", why: "Ngày 23 (được khoanh) nằm ở cột Thứ Hai." },
  ],
},
];

SUBJECTS.push({
  id: 'hinhb2', name: 'Toán qua hình — Bài học', short: 'Bài học hình 2', icon: '🧩', grade: 2,
  exams: HINHB2_EXAMS, ready: true,
  heroTitle: "Toán lớp 2 qua hình — bài học: đường gấp khúc, hình khối, kg – lít – dm, nhân chia, kiểm đếm, khả năng, tiền và lịch",
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; 🖼️ 100% câu có hình &nbsp;•&nbsp; ⏱ 25 phút mỗi đề',
});
