// TỰ NHIÊN VÀ XÃ HỘI — LỚP 3 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 15 phút mỗi đề.
//
// 6 chủ đề, nhấn nội dung riêng của lớp 3:
//   - Gia đình: họ nội – họ ngoại, kỉ niệm gia đình, phòng cháy, giữ vệ sinh quanh nhà
//   - Trường học: truyền thống, hoạt động kết nối cộng đồng, giữ an toàn
//   - Cộng đồng: hoạt động sản xuất (nông nghiệp, công nghiệp, thủ công); di tích – cảnh quan
//   - Thực vật và động vật: các bộ phận và chức năng; sử dụng hợp lí
//   - Con người và sức khoẻ: cơ quan tiêu hoá, tuần hoàn, thần kinh và cách bảo vệ
//   - Trái Đất và bầu trời: phương hướng; hình dạng Trái Đất; ngày – đêm; năm – tháng – mùa

const TNXH3_EXAMS = [

/* ═══════════ ĐỀ 1 — HỌ HÀNG NỘI, NGOẠI ═══════════ */
{
  id: 5301, title: 'Đề 1 · Họ nội, họ ngoại', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Ông bà, các bác, cô, chú... bên bố thuộc họ nào?',
      opts: o4('Họ nội', 'Họ ngoại', 'Họ hàng xóm', 'Không thuộc họ nào'), ans: 'A',
      why: 'Những người thân bên bố (ông bà nội, bác, cô, chú) là họ nội.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Ông bà, các bác, cậu, dì... bên mẹ thuộc họ nào?',
      opts: o4('Họ nội', 'Họ ngoại', 'Họ khác', 'Người dưng'), ans: 'B',
      why: 'Những người thân bên mẹ (ông bà ngoại, cậu, dì) là họ ngoại.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Con của cậu, của dì là anh, chị, em họ bên nào của em?',
      opts: o4('Bên ngoại', 'Bên nội', 'Không phải họ hàng', 'Bên hàng xóm'), ans: 'A',
      why: 'Cậu, dì là em/anh chị của mẹ (họ ngoại) nên con của họ là anh chị em họ bên ngoại.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Vợ của chú (em trai bố), em gọi là gì?',
      opts: o4('Thím', 'Mợ', 'Bác gái', 'Dì'), ans: 'A',
      why: 'Vợ của chú được gọi là thím.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Vợ của cậu (em/anh trai mẹ), em gọi là gì?',
      opts: o4('Thím', 'Mợ', 'Cô', 'Bà'), ans: 'B',
      why: 'Vợ của cậu được gọi là mợ.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Ngày giỗ, ngày Tết là dịp để họ hàng làm gì?',
      opts: o4('Sum họp, tưởng nhớ ông bà tổ tiên', 'Xa lánh nhau', 'Tranh chấp tài sản', 'Không quan tâm nhau'), ans: 'A',
      why: 'Giỗ, Tết là dịp con cháu sum họp, tưởng nhớ tổ tiên và gắn bó với nhau.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Kỉ niệm đáng nhớ của gia đình có thể là dịp nào?',
      opts: o4('Sinh nhật, chuyến du lịch, ngày cưới, ngày sum họp', 'Ngày cãi vã', 'Ngày mất đồ', 'Không có dịp nào'), ans: 'A',
      why: 'Sinh nhật, du lịch, cưới hỏi, sum họp là những kỉ niệm đẹp của gia đình.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Sơ đồ vẽ các đời ông bà, cha mẹ, con cháu trong dòng họ gọi là gì?',
      opts: o4('Sơ đồ gia phả (cây gia đình)', 'Thời khoá biểu', 'Bản đồ', 'Sổ liên lạc'), ans: 'A',
      why: 'Gia phả (cây gia đình) ghi lại các thế hệ trong dòng họ.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Với họ hàng, em nên có thái độ thế nào?',
      opts: o4('Kính trọng người trên, thương yêu mọi người', 'Coi thường người nghèo', 'Chỉ chơi với người giàu', 'Không chào hỏi ai'), ans: 'A',
      why: 'Cần kính trọng người lớn tuổi và yêu thương, giúp đỡ mọi người trong họ.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Bố của bố em, em gọi là gì?',
      opts: o4('Ông nội', 'Ông ngoại', 'Bác', 'Cậu'), ans: 'A',
      why: 'Bố của bố là ông nội.' },
  ],
},

/* ═══════════ ĐỀ 2 — PHÒNG CHÁY VÀ GIỮ VỆ SINH QUANH NHÀ ═══════════ */
{
  id: 5302, title: 'Đề 2 · Phòng cháy và vệ sinh quanh nhà', time: 15,
  questions: [
    { sec: 'An toàn', name: 'Câu 1', pts: 1,
      text: 'Vật nào trong nhà dễ gây cháy nếu bất cẩn?',
      opts: o4('Bếp lửa, bếp ga, nến, diêm', 'Cái gối', 'Quyển vở', 'Cái chăn để gấp'), ans: 'A',
      why: 'Bếp lửa, bếp ga, nến, diêm là nguồn lửa dễ gây cháy nếu sơ ý.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Khi nấu ăn xong, cần làm gì với bếp ga?',
      opts: o4('Khoá bếp, tắt lửa cẩn thận', 'Để lửa cháy suốt', 'Bỏ đi chơi ngay', 'Đổ nước lên bình ga'), ans: 'A',
      why: 'Phải tắt và khoá bếp ga sau khi dùng để tránh rò khí, gây cháy nổ.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Vì sao không nên cắm quá nhiều thiết bị điện vào một ổ cắm?',
      opts: o4('Vì dễ quá tải, nóng và gây cháy', 'Vì tốn chỗ', 'Vì xấu', 'Không sao cả'), ans: 'A',
      why: 'Cắm quá nhiều đồ vào một ổ dễ gây quá tải, nóng dây và chập cháy.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Khi phát hiện có cháy trong nhà, em nên làm gì?',
      opts: o4('Báo người lớn, hô hoán và gọi 114', 'Trốn vào gầm giường', 'Chạy vào chỗ có lửa', 'Giấu không nói ai'), ans: 'A',
      why: 'Cần hô hoán, báo người lớn và gọi cứu hoả số 114, rồi thoát ra nơi an toàn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Số điện thoại gọi lực lượng chữa cháy (cứu hoả) là số nào?',
      opts: o4('113', '114', '115', '116'), ans: 'B',
      why: 'Số 114 là số gọi cứu hoả (chữa cháy). (113: công an, 115: cấp cứu.)' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Khi trong nhà có khói, khí độc do cháy, nên di chuyển thế nào?',
      opts: o4('Cúi thấp người, bịt mũi bằng khăn ẩm', 'Đứng thẳng chạy thật nhanh', 'Hít thật sâu khói vào', 'Đứng yên chờ'), ans: 'A',
      why: 'Khói bốc lên cao nên phải cúi thấp, dùng khăn ẩm che mũi miệng để bớt hít khói độc.' },
    { sec: 'Vệ sinh', name: 'Câu 7', pts: 1,
      text: 'Giữ vệ sinh xung quanh nhà giúp phòng tránh điều gì?',
      opts: o4('Ruồi, muỗi và bệnh tật', 'Trời mưa', 'Xe cộ đông', 'Mất điện'), ans: 'A',
      why: 'Nhà cửa, sân vườn sạch sẽ hạn chế ruồi, muỗi và mầm bệnh.' },
    { sec: 'Vệ sinh', name: 'Câu 8', pts: 1,
      text: 'Rác thải trong nhà nên được xử lí thế nào?',
      opts: o4('Phân loại, bỏ đúng nơi quy định', 'Vứt ra đường', 'Đổ xuống cống', 'Chất đống trong nhà'), ans: 'A',
      why: 'Rác cần được phân loại và bỏ đúng nơi để giữ môi trường sạch.' },
    { sec: 'Vệ sinh', name: 'Câu 9', pts: 1,
      text: 'Nước đọng ở lu, chum, chậu quanh nhà là nơi con gì đẻ trứng?',
      opts: o4('Muỗi', 'Chim', 'Cá', 'Gà'), ans: 'A',
      why: 'Muỗi đẻ trứng ở nơi nước đọng; cần đậy kín hoặc đổ hết nước đọng.' },
    { sec: 'Vệ sinh', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp môi trường quanh nhà sạch, đẹp?',
      opts: o4('Quét sân, trồng cây, khơi thông cống rãnh', 'Đổ rác ra vườn nhà hàng xóm', 'Để cỏ dại mọc um tùm', 'Xả nước bẩn ra đường'), ans: 'A',
      why: 'Quét dọn, trồng cây, khơi thông cống rãnh giúp nơi ở sạch đẹp, thoáng mát.' },
  ],
},

/* ═══════════ ĐỀ 3 — TRƯỜNG HỌC: TRUYỀN THỐNG, HOẠT ĐỘNG, AN TOÀN ═══════════ */
{
  id: 5303, title: 'Đề 3 · Truyền thống và hoạt động ở trường', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Truyền thống tốt đẹp của nhà trường có thể là gì?',
      opts: o4('Dạy tốt – học tốt, đoàn kết, giúp đỡ nhau', 'Hay bỏ học', 'Gây gổ đánh nhau', 'Xả rác bừa bãi'), ans: 'A',
      why: 'Dạy tốt – học tốt, đoàn kết, tương thân tương ái là truyền thống đáng quý của trường.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Hoạt động nào giúp nhà trường kết nối với cộng đồng?',
      opts: o4('Quyên góp ủng hộ vùng lũ, dọn vệ sinh khu phố', 'Đóng cửa không giao lưu', 'Chê bai hàng xóm', 'Không tham gia gì'), ans: 'A',
      why: 'Quyên góp giúp đỡ, dọn vệ sinh cộng đồng là hoạt động kết nối trường với xã hội.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Việc làm nào thể hiện lòng biết ơn thầy cô?',
      opts: o4('Chăm học, lễ phép, chúc mừng ngày 20/11', 'Cãi lời thầy cô', 'Trốn học', 'Vẽ bậy lên bàn'), ans: 'A',
      why: 'Chăm học, lễ phép và tri ân dịp 20/11 thể hiện lòng biết ơn thầy cô.' },
    { sec: 'Trường học', name: 'Câu 4', pts: 1,
      text: 'Khi tham gia hoạt động ngoại khoá (tham quan, dã ngoại), em cần làm gì?',
      opts: o4('Đi theo đoàn, nghe hướng dẫn, không tách nhóm', 'Tự ý đi một mình', 'Chạy lung tung', 'Trèo lan can nguy hiểm'), ans: 'A',
      why: 'Đi theo đoàn, nghe hướng dẫn và không tách nhóm để bảo đảm an toàn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Phòng thí nghiệm, phòng có thiết bị điện ở trường, em cần thế nào?',
      opts: o4('Chỉ dùng khi có thầy cô hướng dẫn', 'Tự ý nghịch phá', 'Bật tắt lung tung', 'Mang đồ về nhà'), ans: 'A',
      why: 'Chỉ sử dụng thiết bị khi có thầy cô hướng dẫn để tránh tai nạn.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Việc làm nào giữ an toàn khi vui chơi ở trường?',
      opts: o4('Chơi đúng khu vực, không leo trèo, xô đẩy', 'Trèo lên cửa sổ', 'Ném đồ vào bạn', 'Chạy trên bàn ghế'), ans: 'A',
      why: 'Chơi đúng chỗ, không leo trèo, xô đẩy giúp tránh tai nạn thương tích.' },
    { sec: 'Trường học', name: 'Câu 7', pts: 1,
      text: 'Khi thấy bạn bị bắt nạt ở trường, em nên làm gì?',
      opts: o4('Bênh vực bạn và báo thầy cô', 'Hùa theo trêu chọc', 'Quay clip cười cợt', 'Làm ngơ mặc kệ'), ans: 'A',
      why: 'Em nên giúp bạn và báo thầy cô để ngăn hành vi bắt nạt.' },
    { sec: 'Trường học', name: 'Câu 8', pts: 1,
      text: 'Giữ gìn cơ sở vật chất của trường là việc nào?',
      opts: o4('Không vẽ bậy, không làm hỏng bàn ghế', 'Khắc tên lên bàn', 'Bẻ vòi nước', 'Đập phá cửa sổ'), ans: 'A',
      why: 'Không vẽ bậy, không phá hỏng bàn ghế, thiết bị là giữ gìn tài sản của trường.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Tham gia phong trào "Kế hoạch nhỏ" thu gom giấy vụn có ý nghĩa gì?',
      opts: o4('Tiết kiệm, bảo vệ môi trường, gây quỹ giúp bạn', 'Làm bẩn trường', 'Lãng phí giấy', 'Không có ý nghĩa'), ans: 'A',
      why: 'Thu gom giấy vụn giúp tái chế, bảo vệ môi trường và gây quỹ giúp bạn khó khăn.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Là học sinh, em góp phần giữ truyền thống nhà trường bằng cách nào?',
      opts: o4('Học tốt, ngoan ngoãn, tham gia phong trào', 'Vi phạm nội quy', 'Đi học muộn thường xuyên', 'Không làm bài tập'), ans: 'A',
      why: 'Học tốt, ngoan và tích cực tham gia phong trào là góp phần giữ truyền thống của trường.' },
  ],
},

/* ═══════════ ĐỀ 4 — HOẠT ĐỘNG SẢN XUẤT ═══════════ */
{
  id: 5304, title: 'Đề 4 · Hoạt động sản xuất quanh em', time: 15,
  questions: [
    { sec: 'Sản xuất', name: 'Câu 1', pts: 1,
      text: 'Trồng lúa, trồng rau, nuôi lợn gà thuộc hoạt động sản xuất nào?',
      opts: o4('Nông nghiệp', 'Công nghiệp', 'Thủ công', 'Du lịch'), ans: 'A',
      why: 'Trồng trọt và chăn nuôi thuộc hoạt động sản xuất nông nghiệp.' },
    { sec: 'Sản xuất', name: 'Câu 2', pts: 1,
      text: 'Sản xuất trong nhà máy như dệt vải, lắp ráp máy móc thuộc hoạt động nào?',
      opts: o4('Nông nghiệp', 'Công nghiệp', 'Đánh cá', 'Chăn nuôi'), ans: 'B',
      why: 'Sản xuất bằng máy móc trong nhà máy (dệt, lắp ráp...) là công nghiệp.' },
    { sec: 'Sản xuất', name: 'Câu 3', pts: 1,
      text: 'Làm gốm, đan lát, thêu tay, làm nón... thuộc hoạt động nào?',
      opts: o4('Nghề thủ công', 'Nông nghiệp', 'Công nghiệp nặng', 'Khai thác than'), ans: 'A',
      why: 'Làm gốm, đan lát, thêu, làm nón là các nghề thủ công truyền thống.' },
    { sec: 'Sản xuất', name: 'Câu 4', pts: 1,
      text: 'Sản phẩm nào là của nghề nông?',
      opts: o4('Thóc, gạo, rau, quả', 'Cái ti vi', 'Ô tô', 'Điện thoại'), ans: 'A',
      why: 'Thóc, gạo, rau, quả là nông sản do nghề nông làm ra.' },
    { sec: 'Sản xuất', name: 'Câu 5', pts: 1,
      text: 'Ngư dân đánh bắt và nuôi trồng thuỷ sản làm ra sản phẩm gì?',
      opts: o4('Tôm, cá, cua, mực', 'Vải vóc', 'Xi măng', 'Sách vở'), ans: 'A',
      why: 'Nghề cá cho ta tôm, cá, cua, mực... (thuỷ hải sản).' },
    { sec: 'Sản xuất', name: 'Câu 6', pts: 1,
      text: 'Người thợ mộc làm ra sản phẩm gì?',
      opts: o4('Bàn, ghế, giường, tủ bằng gỗ', 'Bát đĩa sứ', 'Quần áo', 'Bánh kẹo'), ans: 'A',
      why: 'Thợ mộc dùng gỗ làm bàn, ghế, giường, tủ.' },
    { sec: 'Sản xuất', name: 'Câu 7', pts: 1,
      text: 'Vì sao ta cần quý trọng người lao động?',
      opts: o4('Vì họ làm ra của cải, sản phẩm cho xã hội', 'Vì họ giàu có', 'Vì họ nổi tiếng', 'Không cần quý trọng'), ans: 'A',
      why: 'Người lao động làm ra của cải, sản phẩm phục vụ mọi người nên rất đáng quý.' },
    { sec: 'Sản xuất', name: 'Câu 8', pts: 1,
      text: 'Sản phẩm thủ công của làng nghề thường có đặc điểm gì?',
      opts: o4('Làm bằng tay, tinh xảo, mang nét truyền thống', 'Sản xuất hàng loạt bằng máy', 'Không có giá trị', 'Giống hệt hàng công nghiệp'), ans: 'A',
      why: 'Hàng thủ công làm bằng tay, tinh xảo, mang đậm nét văn hoá truyền thống.' },
    { sec: 'Sản xuất', name: 'Câu 9', pts: 1,
      text: 'Để có sản phẩm, người lao động cần điều gì?',
      opts: o4('Bỏ công sức, thời gian và sự khéo léo', 'Chỉ cần ngồi chơi', 'Chờ trời cho sẵn', 'Không cần làm gì'), ans: 'A',
      why: 'Mỗi sản phẩm đều đòi hỏi công sức, thời gian và sự khéo léo của người lao động.' },
    { sec: 'Sản xuất', name: 'Câu 10', pts: 1,
      text: 'Em thể hiện sự trân trọng thành quả lao động bằng cách nào?',
      opts: o4('Tiết kiệm, không phá hoại, giữ gìn sản phẩm', 'Lãng phí đồ ăn', 'Đập phá đồ dùng', 'Vứt bỏ bừa bãi'), ans: 'A',
      why: 'Tiết kiệm và giữ gìn sản phẩm là cách trân trọng công sức người lao động.' },
  ],
},

/* ═══════════ ĐỀ 5 — DI TÍCH LỊCH SỬ, VĂN HOÁ VÀ CẢNH QUAN ═══════════ */
{
  id: 5305, title: 'Đề 5 · Di tích và cảnh quan quê hương', time: 15,
  questions: [
    { sec: 'Cộng đồng', name: 'Câu 1', pts: 1,
      text: 'Đền, chùa, di tích cổ được gọi chung là gì?',
      opts: o4('Di tích lịch sử – văn hoá', 'Khu vui chơi', 'Chợ', 'Bến xe'), ans: 'A',
      why: 'Đền, chùa, thành cổ, lăng tẩm... là di tích lịch sử – văn hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 2', pts: 1,
      text: 'Vịnh Hạ Long, hang động, thác nước đẹp được gọi là gì?',
      opts: o4('Cảnh quan thiên nhiên', 'Nhà máy', 'Bệnh viện', 'Trường học'), ans: 'A',
      why: 'Núi, hang, vịnh, thác đẹp là cảnh quan thiên nhiên.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Khi đến tham quan di tích, đền chùa, em cần làm gì?',
      opts: o4('Giữ trật tự, không xả rác, không viết bậy', 'Khắc tên lên tường', 'Hái hoa bẻ cành', 'Chạy nhảy la hét'), ans: 'A',
      why: 'Ở di tích cần giữ trật tự, sạch sẽ, không viết vẽ bậy hay phá hoại.' },
    { sec: 'Cộng đồng', name: 'Câu 4', pts: 1,
      text: 'Vì sao phải bảo vệ di tích lịch sử – văn hoá?',
      opts: o4('Vì đó là tài sản chung, gắn với lịch sử dân tộc', 'Vì cũ kĩ nên bỏ đi', 'Vì không ai quan tâm', 'Vì để bán lấy tiền'), ans: 'A',
      why: 'Di tích là tài sản chung, gắn với lịch sử, truyền thống, cần được giữ gìn.' },
    { sec: 'Cộng đồng', name: 'Câu 5', pts: 1,
      text: 'Lễ hội truyền thống ở địa phương thường nhằm mục đích gì?',
      opts: o4('Tưởng nhớ công ơn, giữ nét văn hoá', 'Để gây ồn ào', 'Để xả rác', 'Không có ý nghĩa'), ans: 'A',
      why: 'Lễ hội nhằm tưởng nhớ công ơn tổ tiên, anh hùng và giữ gìn nét văn hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 6', pts: 1,
      text: 'Đền Hùng (Phú Thọ) là nơi thờ ai?',
      opts: o4('Các Vua Hùng', 'Ông Táo', 'Thần Sông', 'Nhà vua nước ngoài'), ans: 'A',
      why: 'Đền Hùng thờ các Vua Hùng — những người có công dựng nước.' },
    { sec: 'Cộng đồng', name: 'Câu 7', pts: 1,
      text: 'Việc nào giúp giữ gìn cảnh quan thiên nhiên khi đi tham quan?',
      opts: o4('Không xả rác, không bẻ cây, không khắc vẽ', 'Vứt rác xuống suối', 'Chặt cây làm kỉ niệm', 'Viết tên lên đá'), ans: 'A',
      why: 'Không xả rác, không bẻ cây, không khắc vẽ là cách giữ cảnh quan luôn đẹp.' },
    { sec: 'Cộng đồng', name: 'Câu 8', pts: 1,
      text: 'Cảnh quan thiên nhiên đẹp có lợi ích gì cho địa phương?',
      opts: o4('Thu hút khách du lịch, tạo việc làm', 'Làm nghèo địa phương', 'Không có lợi gì', 'Gây ô nhiễm'), ans: 'A',
      why: 'Cảnh đẹp thu hút du khách, phát triển du lịch và tạo việc làm.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Hành động nào phá hoại di tích, cảnh quan?',
      opts: o4('Khắc tên, xả rác, bẻ cành, sờ nắn hiện vật', 'Chụp ảnh nhẹ nhàng', 'Đi đúng lối tham quan', 'Bỏ rác vào thùng'), ans: 'A',
      why: 'Khắc vẽ, xả rác, bẻ cành, sờ nắn hiện vật đều làm hư hại di tích, cảnh quan.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Em có thể giới thiệu quê hương mình với bạn bè bằng cách nào?',
      opts: o4('Kể về di tích, món ăn, cảnh đẹp của quê', 'Chê bai quê mình', 'Giấu không nói gì', 'Nói sai sự thật'), ans: 'A',
      why: 'Giới thiệu di tích, cảnh đẹp, món ăn giúp bạn bè hiểu và yêu quê hương em.' },
  ],
},

/* ═══════════ ĐỀ 6 — BỘ PHẬN VÀ CHỨC NĂNG CỦA THỰC VẬT ═══════════ */
{
  id: 5306, title: 'Đề 6 · Các bộ phận của cây và chức năng', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Rễ cây có chức năng chính là gì?',
      opts: o4('Hút nước, chất khoáng và giữ cây đứng vững', 'Quang hợp tạo thức ăn', 'Nở hoa', 'Bay trong không khí'), ans: 'A',
      why: 'Rễ hút nước, chất khoáng từ đất và bám giữ cho cây đứng vững.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Thân cây có chức năng gì?',
      opts: o4('Nâng đỡ và vận chuyển nước, chất nuôi cây', 'Chỉ để làm cảnh', 'Hút nước dưới đất', 'Đẻ trứng'), ans: 'A',
      why: 'Thân nâng đỡ cành lá và vận chuyển nước, chất dinh dưỡng đi nuôi cây.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Lá cây nhận ánh sáng để làm gì?',
      opts: o4('Chế tạo thức ăn nuôi cây (quang hợp)', 'Hút nước từ đất', 'Giữ cây đứng vững', 'Kết thành hạt'), ans: 'A',
      why: 'Lá nhận ánh sáng Mặt Trời để quang hợp, tạo thức ăn nuôi cây và nhả khí ô-xi.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Hoa của cây có vai trò gì trong việc sinh sản?',
      opts: o4('Thụ phấn rồi tạo thành quả và hạt', 'Hút nước', 'Nâng đỡ cây', 'Giữ đất'), ans: 'A',
      why: 'Hoa thụ phấn, sau đó phát triển thành quả chứa hạt để sinh ra cây mới.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Quả của cây thường chứa gì bên trong?',
      opts: o4('Hạt (để mọc thành cây mới)', 'Rễ cây', 'Lá non', 'Nước lã'), ans: 'A',
      why: 'Quả bao bọc và bảo vệ hạt; hạt gieo xuống đất sẽ mọc thành cây mới.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Khi quang hợp, lá cây nhả ra khí gì có lợi cho con người?',
      opts: o4('Khí ô-xi', 'Khói bụi', 'Khí độc', 'Hơi nóng'), ans: 'A',
      why: 'Cây quang hợp nhả ra khí ô-xi giúp con người và động vật hô hấp.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Bộ phận nào của cây rau muống ta thường dùng làm thức ăn?',
      opts: o4('Thân và lá', 'Rễ', 'Hạt khô', 'Vỏ cây'), ans: 'A',
      why: 'Với rau muống, ta ăn phần thân và lá.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Cây nào ta dùng phần rễ (củ) để ăn?',
      opts: o4('Củ cà rốt, củ cải', 'Rau cải', 'Cây mía', 'Cây cam'), ans: 'A',
      why: 'Cà rốt, củ cải là phần rễ phình to thành củ, dùng làm thức ăn.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Sử dụng thực vật một cách hợp lí nghĩa là gì?',
      opts: o4('Dùng tiết kiệm, trồng thêm, không phá hoại', 'Chặt phá thoải mái', 'Đốt rừng lấy đất', 'Lãng phí rau quả'), ans: 'A',
      why: 'Dùng tiết kiệm và trồng thêm cây, không chặt phá bừa bãi là sử dụng hợp lí.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Nếu chặt phá rừng bừa bãi sẽ dẫn đến hậu quả gì?',
      opts: o4('Lũ lụt, sạt lở, thiếu ô-xi', 'Không khí sạch hơn', 'Nhiều mưa thuận hoà hơn', 'Không có hậu quả gì'), ans: 'A',
      why: 'Mất rừng gây lũ lụt, sạt lở đất và làm giảm lượng ô-xi, hại môi trường.' },
  ],
},

/* ═══════════ ĐỀ 7 — BỘ PHẬN VÀ CHỨC NĂNG CỦA ĐỘNG VẬT ═══════════ */
{
  id: 5307, title: 'Đề 7 · Các bộ phận của con vật và chức năng', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Hầu hết cơ thể động vật gồm những phần chính nào?',
      opts: o4('Đầu, mình và cơ quan di chuyển', 'Chỉ có đầu', 'Chỉ có đuôi', 'Chỉ có chân'), ans: 'A',
      why: 'Nhiều loài vật có ba phần: đầu, mình và cơ quan di chuyển (chân, cánh, vây...).' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Cá dùng bộ phận nào để bơi?',
      opts: o4('Vây và đuôi', 'Cánh', 'Chân', 'Tai'), ans: 'A',
      why: 'Cá bơi nhờ vây và đuôi.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Cá thở bằng bộ phận nào?',
      opts: o4('Mang', 'Phổi', 'Da', 'Mũi'), ans: 'A',
      why: 'Cá thở bằng mang để lấy khí ô-xi hoà tan trong nước.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Chim dùng bộ phận nào để bay?',
      opts: o4('Đôi cánh', 'Vây', 'Đuôi cá', 'Bốn chân'), ans: 'A',
      why: 'Chim bay được nhờ đôi cánh có lông vũ.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào có 6 chân?',
      opts: o4('Con kiến, con ong (côn trùng)', 'Con chó', 'Con mèo', 'Con voi'), ans: 'A',
      why: 'Côn trùng như kiến, ong có 6 chân.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Bộ phận nào giúp con vật cảm nhận mùi và tìm thức ăn?',
      opts: o4('Mũi (và râu ở một số loài)', 'Đuôi', 'Móng', 'Vảy'), ans: 'A',
      why: 'Mũi (và râu ở một số loài) giúp con vật ngửi mùi để tìm thức ăn, nhận biết nguy hiểm.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con vật nào đẻ con và nuôi con bằng sữa?',
      opts: o4('Con mèo, con chó, con bò', 'Con gà', 'Con cá', 'Con rắn'), ans: 'A',
      why: 'Thú (mèo, chó, bò) đẻ con và nuôi con bằng sữa mẹ.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con vật nào đẻ trứng?',
      opts: o4('Con gà, con vịt, con chim', 'Con trâu', 'Con lợn', 'Con voi'), ans: 'A',
      why: 'Gà, vịt, chim đẻ trứng rồi ấp cho trứng nở thành con.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Con vật cũng cần những gì để sống như con người?',
      opts: o4('Thức ăn, nước uống, không khí và nơi ở', 'Chỉ cần ánh nắng', 'Không cần ăn uống', 'Chỉ cần tiếng nhạc'), ans: 'A',
      why: 'Động vật cần thức ăn, nước, không khí và nơi ở để sống và lớn lên.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Sử dụng động vật hợp lí là làm gì?',
      opts: o4('Nuôi và khai thác có kế hoạch, không săn bắt bừa bãi', 'Săn bắt hết mọi loài', 'Bắt cả con non', 'Phá nơi chúng sống'), ans: 'A',
      why: 'Nuôi, khai thác có kế hoạch và không săn bắt bừa bãi giúp bảo vệ động vật.' },
  ],
},

/* ═══════════ ĐỀ 8 — CƠ QUAN TIÊU HOÁ VÀ TUẦN HOÀN ═══════════ */
{
  id: 5308, title: 'Đề 8 · Cơ quan tiêu hoá và tuần hoàn', time: 15,
  questions: [
    { sec: 'Tiêu hoá', name: 'Câu 1', pts: 1,
      text: 'Cơ quan tiêu hoá có nhiệm vụ gì?',
      opts: o4('Biến thức ăn thành chất nuôi cơ thể', 'Giúp ta nhìn', 'Giúp ta nghe', 'Bơm máu đi khắp người'), ans: 'A',
      why: 'Cơ quan tiêu hoá biến thức ăn thành chất dinh dưỡng nuôi cơ thể.' },
    { sec: 'Tiêu hoá', name: 'Câu 2', pts: 1,
      text: 'Thức ăn được nghiền nhỏ đầu tiên ở đâu?',
      opts: o4('Ở miệng (nhờ răng nhai)', 'Ở dạ dày', 'Ở ruột già', 'Ở phổi'), ans: 'A',
      why: 'Ở miệng, răng nhai nghiền nhỏ thức ăn, nước bọt làm mềm thức ăn.' },
    { sec: 'Tiêu hoá', name: 'Câu 3', pts: 1,
      text: 'Ống dẫn thức ăn từ miệng xuống dạ dày gọi là gì?',
      opts: o4('Thực quản', 'Khí quản', 'Ruột non', 'Mạch máu'), ans: 'A',
      why: 'Thực quản là ống dẫn thức ăn từ miệng xuống dạ dày.' },
    { sec: 'Tiêu hoá', name: 'Câu 4', pts: 1,
      text: 'Nơi thức ăn được nhào trộn, tiêu hoá phần lớn là cơ quan nào?',
      opts: o4('Dạ dày và ruột non', 'Hai lá phổi', 'Quả tim', 'Đôi mắt'), ans: 'A',
      why: 'Dạ dày nhào trộn thức ăn; ruột non tiêu hoá và hấp thụ phần lớn chất dinh dưỡng.' },
    { sec: 'Tiêu hoá', name: 'Câu 5', pts: 1,
      text: 'Để bảo vệ cơ quan tiêu hoá, em nên làm gì?',
      opts: o4('Ăn chín uống sôi, nhai kĩ, ăn đúng giờ', 'Ăn đồ ôi thiu', 'Ăn thật nhanh, không nhai', 'Bỏ bữa thường xuyên'), ans: 'A',
      why: 'Ăn chín uống sôi, nhai kĩ và ăn đúng giờ giúp tiêu hoá tốt, tránh đau bụng.' },
    { sec: 'Tuần hoàn', name: 'Câu 6', pts: 1,
      text: 'Cơ quan tuần hoàn gồm những bộ phận chính nào?',
      opts: o4('Tim và các mạch máu', 'Dạ dày và ruột', 'Mắt và tai', 'Xương và cơ'), ans: 'A',
      why: 'Cơ quan tuần hoàn gồm tim và các mạch máu.' },
    { sec: 'Tuần hoàn', name: 'Câu 7', pts: 1,
      text: 'Tim có nhiệm vụ gì?',
      opts: o4('Co bóp, bơm máu đi khắp cơ thể', 'Tiêu hoá thức ăn', 'Giúp ta thở', 'Giúp ta nhìn'), ans: 'A',
      why: 'Tim co bóp liên tục để bơm máu mang chất dinh dưỡng, ô-xi đi nuôi cơ thể.' },
    { sec: 'Tuần hoàn', name: 'Câu 8', pts: 1,
      text: 'Máu đi trong cơ thể theo đường nào?',
      opts: o4('Theo các mạch máu', 'Theo ống thực quản', 'Theo khí quản', 'Theo dây thần kinh'), ans: 'A',
      why: 'Máu chảy trong các mạch máu, đi khắp cơ thể rồi trở về tim.' },
    { sec: 'Tuần hoàn', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp tim mạch khoẻ mạnh?',
      opts: o4('Tập thể dục, ăn uống điều độ, ngủ đủ', 'Ăn quá nhiều mỡ, đồ mặn', 'Lười vận động', 'Thức khuya thường xuyên'), ans: 'A',
      why: 'Tập thể dục, ăn uống điều độ và ngủ đủ giúp tim mạch khoẻ.' },
    { sec: 'Tuần hoàn', name: 'Câu 10', pts: 1,
      text: 'Khi chạy nhảy nhiều, tim của em thường thế nào?',
      opts: o4('Đập nhanh hơn', 'Ngừng đập', 'Đập chậm lại rồi dừng', 'Không thay đổi gì'), ans: 'A',
      why: 'Khi vận động mạnh, cơ thể cần nhiều ô-xi hơn nên tim đập nhanh hơn.' },
  ],
},

/* ═══════════ ĐỀ 9 — CƠ QUAN THẦN KINH VÀ CHĂM SÓC SỨC KHOẺ ═══════════ */
{
  id: 5309, title: 'Đề 9 · Cơ quan thần kinh và sức khoẻ', time: 15,
  questions: [
    { sec: 'Thần kinh', name: 'Câu 1', pts: 1,
      text: 'Cơ quan thần kinh gồm những bộ phận chính nào?',
      opts: o4('Não, tuỷ sống và các dây thần kinh', 'Tim và mạch máu', 'Dạ dày và ruột', 'Xương và cơ'), ans: 'A',
      why: 'Cơ quan thần kinh gồm não, tuỷ sống và các dây thần kinh.' },
    { sec: 'Thần kinh', name: 'Câu 2', pts: 1,
      text: 'Não nằm được bảo vệ trong bộ phận nào?',
      opts: o4('Hộp sọ', 'Lồng ngực', 'Bàn tay', 'Bàn chân'), ans: 'A',
      why: 'Não nằm trong hộp sọ cứng để được bảo vệ.' },
    { sec: 'Thần kinh', name: 'Câu 3', pts: 1,
      text: 'Cơ quan thần kinh có vai trò gì?',
      opts: o4('Điều khiển mọi hoạt động của cơ thể', 'Chỉ để trang trí', 'Tiêu hoá thức ăn', 'Bơm máu'), ans: 'A',
      why: 'Não và các dây thần kinh điều khiển, phối hợp mọi hoạt động: suy nghĩ, cử động, cảm nhận.' },
    { sec: 'Thần kinh', name: 'Câu 4', pts: 1,
      text: 'Nhờ đâu em suy nghĩ, ghi nhớ và học bài được?',
      opts: o4('Nhờ bộ não', 'Nhờ dạ dày', 'Nhờ bàn chân', 'Nhờ lá phổi'), ans: 'A',
      why: 'Bộ não giúp ta suy nghĩ, ghi nhớ, học tập và điều khiển hành động.' },
    { sec: 'Thần kinh', name: 'Câu 5', pts: 1,
      text: 'Để cơ quan thần kinh khoẻ, em cần làm gì?',
      opts: o4('Ngủ đủ giấc, học và nghỉ hợp lí', 'Thức khuya học dồn', 'Xem điện thoại suốt ngày', 'Lo lắng, căng thẳng liên tục'), ans: 'A',
      why: 'Ngủ đủ, học tập và nghỉ ngơi hợp lí giúp thần kinh khoẻ mạnh, tỉnh táo.' },
    { sec: 'Thần kinh', name: 'Câu 6', pts: 1,
      text: 'Giấc ngủ có vai trò gì với cơ quan thần kinh?',
      opts: o4('Giúp não và cơ thể được nghỉ ngơi, phục hồi', 'Làm não yếu đi', 'Không có tác dụng', 'Khiến ta quên hết'), ans: 'A',
      why: 'Ngủ giúp não và cơ thể nghỉ ngơi, phục hồi để hôm sau minh mẫn.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Trạng thái nào có hại cho cơ quan thần kinh?',
      opts: o4('Lo sợ, tức giận, căng thẳng kéo dài', 'Vui vẻ, thoải mái', 'Ngủ đủ giấc', 'Học tập điều độ'), ans: 'A',
      why: 'Lo sợ, tức giận, căng thẳng lâu ngày làm hại thần kinh, dễ mệt mỏi, mất ngủ.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Để đầu óc thư giãn sau giờ học, em nên làm gì?',
      opts: o4('Chơi thể thao, nghe nhạc, trò chuyện vui', 'Học liên tục không nghỉ', 'Cãi nhau với bạn', 'Lo lắng chuyện chưa xảy ra'), ans: 'A',
      why: 'Vận động nhẹ, nghe nhạc, vui chơi lành mạnh giúp thần kinh được nghỉ ngơi.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Chất nào rất có hại cho cơ quan thần kinh, trẻ em tuyệt đối tránh?',
      opts: o4('Rượu, bia, thuốc lá, ma tuý', 'Nước lọc', 'Sữa tươi', 'Rau xanh'), ans: 'A',
      why: 'Rượu, bia, thuốc lá, ma tuý gây hại nặng cho thần kinh và sức khoẻ; phải tránh xa.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Thời gian biểu học tập, nghỉ ngơi hợp lí giúp em điều gì?',
      opts: o4('Khoẻ mạnh, học tốt, không bị quá tải', 'Mệt mỏi hơn', 'Học kém đi', 'Không có ích gì'), ans: 'A',
      why: 'Sắp xếp thời gian hợp lí giúp cơ thể và thần kinh không quá tải, học hiệu quả.' },
  ],
},

/* ═══════════ ĐỀ 10 — PHƯƠNG HƯỚNG, TRÁI ĐẤT, NGÀY ĐÊM VÀ CÁC MÙA ═══════════ */
{
  id: 5310, title: 'Đề 10 · Trái Đất, phương hướng và các mùa', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Có mấy phương hướng chính?',
      opts: o4('Hai (đông, tây)', 'Ba', 'Bốn (đông, tây, nam, bắc)', 'Sáu'), ans: 'C',
      why: 'Có bốn hướng chính: đông, tây, nam, bắc.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Buổi sáng, Mặt Trời mọc ở hướng nào?',
      opts: o4('Hướng đông', 'Hướng tây', 'Hướng nam', 'Hướng bắc'), ans: 'A',
      why: 'Mặt Trời mọc ở hướng đông vào buổi sáng.' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Buổi chiều, Mặt Trời lặn ở hướng nào?',
      opts: o4('Hướng đông', 'Hướng tây', 'Hướng nam', 'Hướng bắc'), ans: 'B',
      why: 'Mặt Trời lặn ở hướng tây vào buổi chiều.' },
    { sec: 'Bầu trời', name: 'Câu 4', pts: 1,
      text: 'Trái Đất có hình dạng như thế nào?',
      opts: o4('Hình khối cầu (tròn như quả bóng)', 'Hình vuông', 'Hình phẳng dẹt', 'Hình tam giác'), ans: 'A',
      why: 'Trái Đất có dạng hình cầu, tròn như quả bóng.' },
    { sec: 'Bầu trời', name: 'Câu 5', pts: 1,
      text: 'Trái Đất chuyển động quanh thiên thể nào?',
      opts: o4('Mặt Trời', 'Mặt Trăng', 'Ngôi sao Bắc Đẩu', 'Sao chổi'), ans: 'A',
      why: 'Trái Đất chuyển động quanh Mặt Trời.' },
    { sec: 'Bầu trời', name: 'Câu 6', pts: 1,
      text: 'Vì sao trên Trái Đất có ngày và đêm?',
      opts: o4('Do Trái Đất tự quay quanh mình nó', 'Do Mặt Trời tắt đi', 'Do có mây che', 'Do đèn điện'), ans: 'A',
      why: 'Trái Đất tự quay: nửa hướng về Mặt Trời là ngày, nửa khuất là đêm.' },
    { sec: 'Bầu trời', name: 'Câu 7', pts: 1,
      text: 'Một năm có mấy tháng?',
      opts: o4('10 tháng', '11 tháng', '12 tháng', '15 tháng'), ans: 'C',
      why: 'Một năm có 12 tháng.' },
    { sec: 'Các mùa', name: 'Câu 8', pts: 1,
      text: 'Miền Bắc nước ta có bốn mùa theo thứ tự nào?',
      opts: o4('Xuân – hạ – thu – đông', 'Đông – thu – hạ – xuân', 'Hạ – đông – xuân – thu', 'Thu – xuân – đông – hạ'), ans: 'A',
      why: 'Bốn mùa nối tiếp: xuân, hạ, thu, đông.' },
    { sec: 'Các mùa', name: 'Câu 9', pts: 1,
      text: 'Vào ban ngày trời sáng là nhờ đâu?',
      opts: o4('Ánh sáng Mặt Trời chiếu tới', 'Ánh sáng Mặt Trăng', 'Ánh đèn đường', 'Ánh sáng các vì sao'), ans: 'A',
      why: 'Ban ngày, nơi đó hướng về Mặt Trời nên nhận được ánh sáng và trở nên sáng.' },
    { sec: 'Bầu trời', name: 'Câu 10', pts: 1,
      text: 'Dụng cụ nào giúp ta xác định phương hướng?',
      opts: o4('La bàn', 'Cái cân', 'Cái thước kẻ', 'Đồng hồ báo thức'), ans: 'A',
      why: 'La bàn có kim luôn chỉ hướng bắc – nam, giúp xác định phương hướng.' },
  ],
},

];

SUBJECTS.push({
  id: 'tnxh3', name: 'Tự nhiên & Xã hội', short: 'TN&XH 3', icon: '🌍', grade: 3,
  exams: TNXH3_EXAMS, ready: true,
  heroTitle: 'Tự nhiên và Xã hội lớp 3 — họ hàng, sản xuất, cơ thể người, thực vật, động vật và Trái Đất',
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 15 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
