// TOÁN TƯ DUY TỔNG HỢP LỚP 3 — 15 phiếu × 8 câu = 120 câu (42 câu có hình, 35%).
// SINH TỰ ĐỘNG bởi tools/gen-tuduy3-plus.mjs — sửa nội dung trong script rồi chạy lại:
//     node tools/gen-tuduy3-plus.mjs
//
// BIÊN SOẠN THEO PHONG CÁCH MathX + các dạng toán tư duy nước ngoài đã hạ độ khó
// về mức HSG cấp trường/huyện lớp 3 Việt Nam (KHÔNG chép nguyên văn phiếu mathx.vn):
//   • Trung Quốc (奥数): số trận đồ · tính nhanh · tìm quy luật · gà–thỏ · trồng
//     cây/cưa gỗ · tuổi · suy ngược · nguyên lý ngăn kéo · tổng–hiệu · quy về đơn vị.
//   • Nga (Кенгуру): suy luận xếp hạng · bài toán mẹo.
//   • Úc (APSMO / Kangaroo): mua bán non-routine · đổi tiền ít đồng nhất · đếm
//     hình – đếm khối · phép tính ẩn bằng hình · cân so sánh biểu tượng.
// Hình vẽ bằng code (tools/tt-art.mjs + nc2-art.mjs + hinh-art.mjs + vio-art.mjs).

const TTW3 = [
{
  id: 3401, title: 'Phiếu 01', time: 20,
  questions: [
    { sec: 'Tính nhanh', name: 'Câu 1', pts: 1.25,
      text: 'Tính nhanh: <b>2 + 4 + 6 + 8 + 10 + 12 + 14</b>',
      opts: o4('58', '54', '60', '56'), ans: 'D',
      why: 'Ghép cặp hai đầu, mỗi cặp bằng 16: kết quả = 56.' },
    { sec: 'Gà và thỏ', name: 'Câu 2', pts: 1.25,
      text: 'Bãi xe có 8 chiếc xe gồm xe đạp (2 bánh) và xe ba bánh (3 bánh), đếm được tất cả 19 bánh xe. Hỏi có bao nhiêu <b>xe đạp</b>?',
      opts: o4('3', '6', '5', '4'), ans: 'C',
      why: 'Giả sử tất cả là xe đạp: 8 × 2 = 16 bánh, thiếu 3 bánh. Mỗi xe ba bánh hơn 1 bánh nên số xe ba bánh = 3, số xe đạp = 5. Vậy xe đạp có 5 chiếc.' },
    { sec: 'Trồng cây', name: 'Câu 3', pts: 1.25,
      text: 'Đóng cọc quanh một cái ao hình tròn có chu vi 20 m, hai cọc cạnh nhau cách 4 m. Cần bao nhiêu cọc?',
      opts: o4('6', '4', '5', '20'), ans: 'C',
      why: 'Vì trồng theo <b>vòng khép kín</b> nên số cọc = số khoảng = 20 : 4 = 5 cọc.' },
    { sec: 'Bài toán tuổi', name: 'Câu 4', pts: 1.25,
      text: 'Mẹ hơn con 24 tuổi. Năm nay tuổi mẹ gấp 5 lần tuổi con. Hỏi <b>con</b> năm nay bao nhiêu tuổi?',
      opts: o4('30', '24', '6', '8'), ans: 'C',
      why: 'Tuổi mẹ gấp 5 lần tuổi con nên hiệu 24 tuổi ứng với 5 − 1 = 4 lần tuổi con. Tuổi con = 24 : 4 = 6, tuổi mẹ = 6 × 5 = 30.' },
    { sec: 'Suy ngược', name: 'Câu 5', pts: 1.25,
      text: 'Một bạn nghĩ ra một số, <b>cộng 9</b>, rồi <b>nhân 2</b>, rồi <b>bớt 4</b> thì được 32. Hỏi bạn đã nghĩ ra số nào?', img: 'assets/ttw3/q1.svg',
      opts: o4('32', '18', '9', '10'), ans: 'C',
      why: 'Đi lùi từ kết quả: (32 + 4) : 2 − 9 = 36 : 2 − 9 = 18 − 9 = 9.' },
    { sec: 'Nguyên lý ngăn kéo', name: 'Câu 6', pts: 1.25,
      text: 'Trong một chiếc hộp kín có rất nhiều viên bi thuộc 2 màu (đỏ, xanh). Không nhìn vào hộp, phải lấy ra ít nhất bao nhiêu viên để <b>chắc chắn</b> có 2 viên cùng màu?',
      opts: o4('2', '3', '4', '5'), ans: 'B',
      why: 'Xấu nhất mỗi màu lấy được 1 viên (2 viên khác màu). Lấy thêm 1 viên nữa thì chắc chắn trùng màu: 2 + 1 = 3 viên.' },
    { sec: 'Tổng và hiệu', name: 'Câu 7', pts: 1.25,
      text: 'Hai số có tổng bằng 91 và hiệu bằng 9. Tìm <b>số lớn</b>.',
      opts: o4('50', '41', '59', '91'), ans: 'A',
      why: 'Số lớn = (tổng + hiệu) : 2 = (91 + 9) : 2 = 50. Số bé = 41.' },
    { sec: 'Quy về đơn vị', name: 'Câu 8', pts: 1.25,
      text: 'Mua 3 quyển vở giống nhau hết 24 nghìn đồng. Hỏi mua 6 quyển vở như thế hết bao nhiêu nghìn đồng?',
      opts: o4('56', '40', '30', '48'), ans: 'D',
      why: 'Giá một quyển: 24 : 3 = 8 nghìn. Mua 6 quyển hết: 8 × 6 = 48 nghìn đồng.' },
  ],
},
{
  id: 3402, title: 'Phiếu 02', time: 20,
  questions: [
    { sec: 'Tìm quy luật', name: 'Câu 1', pts: 1.25,
      text: 'Tìm số thích hợp điền vào ô có dấu <b>?</b>.', img: 'assets/ttw3/q2.svg',
      opts: o4('29', '21', '25', '26'), ans: 'C',
      why: 'Mỗi số hơn số trước 4 đơn vị nên số cần tìm = 21 + 4 = 25.' },
    { sec: 'Số trận đồ', name: 'Câu 2', pts: 1.25,
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng nhau. Tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q3.svg',
      opts: o4('14', '13', '12', '45'), ans: 'B',
      why: 'Tổng mỗi hàng là 45. Lấy 45 trừ hai số đã biết cùng hàng (hoặc cùng cột) với ô trống được 13.' },
    { sec: 'Số trận đồ', name: 'Câu 3', pts: 1.25,
      text: 'Tổng ba số trên <b>mỗi cạnh</b> của tam giác đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttw3/q4.svg',
      opts: o4('5', '3', '18', '4'), ans: 'D',
      why: 'Tổng mỗi cạnh là 18. Ở cạnh chứa ô trống, lấy 18 trừ hai số đã biết được 4.' },
    { sec: 'Cân so sánh', name: 'Câu 4', pts: 1.25,
      text: 'Biết 1 quả táo 🍎 nặng bằng 3 quả mận 🟣, và 1 quả mận 🟣 nặng bằng 2 hạt dẻ 🌰. Hỏi 1 quả táo 🍎 nặng bằng bao nhiêu <b>hạt dẻ</b>?',
      opts: o4('6', '5', '7', '8'), ans: 'A',
      why: '1 táo = 3 mận, mỗi mận = 2 hạt dẻ nên 1 táo = 3 × 2 = 6 hạt dẻ.' },
    { sec: 'Phép tính ẩn', name: 'Câu 5', pts: 1.25,
      text: 'Biết: 🍎 + 🍎 = 6 và 🍎 + 🍌 = 7. Hỏi <b>🍌</b> bằng bao nhiêu?',
      opts: o4('3', '4', '7', '5'), ans: 'B',
      why: 'Từ 🍎 + 🍎 = 6 suy ra 🍎 = 3. Thay vào 🍎 + 🍌 = 7: 🍌 = 7 − 3 = 4.' },
    { sec: 'Đếm hình', name: 'Câu 6', pts: 1.25,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttw3/q5.svg',
      opts: o4('2', '3', '4', '5'), ans: 'B',
      why: 'Có 2 tam giác nhỏ, cộng thêm các tam giác lớn ghép lại; tổng cộng 2 × (2 + 1) : 2 = 3 tam giác.' },
    { sec: 'Đếm khối', name: 'Câu 7', pts: 1.25,
      text: 'Các khối lập phương giống nhau xếp thành hình bậc thang. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttw3/q6.svg',
      opts: o4('11', '10', '9', '16'), ans: 'B',
      why: 'Đếm theo từng cột: 1 + 2 + 3 + 4 = 10 khối.' },
    { sec: 'Non-routine', name: 'Câu 8', pts: 1.25,
      text: 'Một cửa hàng bán bút 6 nghìn đồng một chiếc, có khuyến mãi <b>mua 3 tặng 1</b>. Bạn Nam có 24 nghìn đồng. Nam mua được <b>nhiều nhất</b> bao nhiêu chiếc bút?',
      opts: o4('4', '6', '7', '5'), ans: 'D',
      why: 'Với 24 nghìn mua được 4 chiếc (4 × 6 = 24). Cứ mua 3 tặng 1 nên được tặng thêm 1 chiếc. Tổng: 4 + 1 = 5 chiếc.' },
  ],
},
{
  id: 3403, title: 'Phiếu 03', time: 20,
  questions: [
    { sec: 'Non-routine', name: 'Câu 1', pts: 1.25,
      text: 'Cần trả đúng 12 nghìn đồng bằng các tờ tiền loại 1 nghìn, 2 nghìn và 5 nghìn. Dùng <b>ít tờ tiền nhất</b> thì cần bao nhiêu tờ?',
      opts: o4('4', '3', '5', '12'), ans: 'B',
      why: 'Ưu tiên tờ lớn: 2 tờ 5 nghìn, 1 tờ 2 nghìn = 12 nghìn, dùng 3 tờ.' },
    { sec: 'Bài toán mẹo', name: 'Câu 2', pts: 1.25,
      text: 'Trên cành cây có 9 con chim. Có 4 con bay đi nơi khác. Hỏi trên cành còn lại mấy con chim?',
      opts: o4('5', '9', '4', '13'), ans: 'A',
      why: 'Còn lại = 9 − 4 = 5 con chim.' },
    { sec: 'Suy luận', name: 'Câu 3', pts: 1.25,
      text: 'Trong một cuộc thi chạy: Lan về trước Mai, Mai về trước Hoa. Hỏi bạn nào về <b>đích đầu tiên</b>?',
      opts: o4('Hoa', 'Mai', 'Lan', 'Không xác định được'), ans: 'C',
      why: 'Thứ tự về đích: Lan → Mai → Hoa. Vậy Lan về đầu tiên.' },
    { sec: 'Thời gian', name: 'Câu 4', pts: 1.25,
      text: 'Đồng hồ đang chỉ 6 giờ đúng. Hỏi <b>sau 4 giờ nữa</b> đồng hồ chỉ mấy giờ?', img: 'assets/ttw3/q7.svg',
      opts: o4('11 giờ', '10 giờ', '4 giờ', '6 giờ'), ans: 'B',
      why: 'Sau 4 giờ nữa là 6 + 4 = 10 giờ, tức 10 giờ.' },
    { sec: 'Hình học', name: 'Câu 5', pts: 1.25,
      text: 'Một hình chữ nhật có chiều dài 6 cm, chiều rộng 4 cm. Tính <b>chu vi</b> hình chữ nhật đó.',
      opts: o4('20 cm', '10 cm', '24 cm', '22 cm'), ans: 'A',
      why: 'Chu vi = (dài + rộng) × 2 = (6 + 4) × 2 = 20 cm.' },
    { sec: 'Tính nhanh', name: 'Câu 6', pts: 1.25,
      text: 'Tính nhanh: <b>2 + 4 + 6 + 8 + 10 + 12</b>',
      opts: o4('44', '42', '40', '46'), ans: 'B',
      why: 'Ghép cặp hai đầu, mỗi cặp bằng 14: kết quả = 42.' },
    { sec: 'Gà và thỏ', name: 'Câu 7', pts: 1.25,
      text: 'Bãi xe có 5 chiếc xe gồm xe đạp (2 bánh) và xe ba bánh (3 bánh), đếm được tất cả 12 bánh xe. Hỏi có bao nhiêu <b>xe ba bánh</b>?',
      opts: o4('2', '3', '1', '5'), ans: 'A',
      why: 'Giả sử tất cả là xe đạp: 5 × 2 = 10 bánh, thiếu 2 bánh. Mỗi xe ba bánh hơn 1 bánh nên số xe ba bánh = 2, số xe đạp = 3. Vậy xe ba bánh có 2 chiếc.' },
    { sec: 'Trồng cây', name: 'Câu 8', pts: 1.25,
      text: 'Một bác thợ cưa một khúc gỗ dài thành 8 đoạn bằng nhau. Bác phải cưa bao nhiêu <b>nhát</b>?',
      opts: o4('8', '9', '6', '7'), ans: 'D',
      why: 'Cưa thành 8 đoạn thì chỉ cần 8 − 1 = 7 nhát (nhát cuối đã tách đủ đoạn).' },
  ],
},
{
  id: 3404, title: 'Phiếu 04', time: 20,
  questions: [
    { sec: 'Bài toán tuổi', name: 'Câu 1', pts: 1.25,
      text: 'Mẹ hơn con 21 tuổi. Năm nay tuổi mẹ gấp 4 lần tuổi con. Hỏi <b>mẹ</b> năm nay bao nhiêu tuổi?',
      opts: o4('7', '28', '21', '30'), ans: 'B',
      why: 'Tuổi mẹ gấp 4 lần tuổi con nên hiệu 21 tuổi ứng với 4 − 1 = 3 lần tuổi con. Tuổi con = 21 : 3 = 7, tuổi mẹ = 7 × 4 = 28.' },
    { sec: 'Suy ngược', name: 'Câu 2', pts: 1.25,
      text: 'Một bạn nghĩ ra một số, <b>cộng 7</b>, rồi <b>nhân 2</b>, rồi <b>bớt 6</b> thì được 22. Hỏi bạn đã nghĩ ra số nào?', img: 'assets/ttw3/q8.svg',
      opts: o4('22', '14', '8', '7'), ans: 'D',
      why: 'Đi lùi từ kết quả: (22 + 6) : 2 − 7 = 28 : 2 − 7 = 14 − 7 = 7.' },
    { sec: 'Nguyên lý ngăn kéo', name: 'Câu 3', pts: 1.25,
      text: 'Trong một chiếc hộp kín có rất nhiều viên bi thuộc 3 màu (đỏ, xanh, vàng). Không nhìn vào hộp, phải lấy ra ít nhất bao nhiêu viên để <b>chắc chắn</b> có 2 viên cùng màu?',
      opts: o4('3', '5', '4', '6'), ans: 'C',
      why: 'Xấu nhất mỗi màu lấy được 1 viên (3 viên khác màu). Lấy thêm 1 viên nữa thì chắc chắn trùng màu: 3 + 1 = 4 viên.' },
    { sec: 'Tổng và hiệu', name: 'Câu 4', pts: 1.25,
      text: 'Hai số có tổng bằng 40 và hiệu bằng 22. Tìm <b>số bé</b>.',
      opts: o4('31', '40', '10', '9'), ans: 'D',
      why: 'Số lớn = (tổng + hiệu) : 2 = (40 + 22) : 2 = 31. Số bé = 9.' },
    { sec: 'Quy về đơn vị', name: 'Câu 5', pts: 1.25,
      text: 'Mua 2 quyển vở giống nhau hết 14 nghìn đồng. Hỏi mua 9 quyển vở như thế hết bao nhiêu nghìn đồng?',
      opts: o4('63', '70', '56', '23'), ans: 'A',
      why: 'Giá một quyển: 14 : 2 = 7 nghìn. Mua 9 quyển hết: 7 × 9 = 63 nghìn đồng.' },
    { sec: 'Tìm quy luật', name: 'Câu 6', pts: 1.25,
      text: 'Tìm số thích hợp điền vào ô có dấu <b>?</b>.', img: 'assets/ttw3/q9.svg',
      opts: o4('47', '29', '39', '38'), ans: 'D',
      why: 'Mỗi số hơn số trước 9 đơn vị nên số cần tìm = 29 + 9 = 38.' },
    { sec: 'Số trận đồ', name: 'Câu 7', pts: 1.25,
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng nhau. Tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q10.svg',
      opts: o4('19', '17', '54', '18'), ans: 'D',
      why: 'Tổng mỗi hàng là 54. Lấy 54 trừ hai số đã biết cùng hàng (hoặc cùng cột) với ô trống được 18.' },
    { sec: 'Số trận đồ', name: 'Câu 8', pts: 1.25,
      text: 'Tổng ba số trên <b>mỗi cạnh</b> của tam giác đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttw3/q11.svg',
      opts: o4('5', '6', '4', '9'), ans: 'A',
      why: 'Tổng mỗi cạnh là 9. Ở cạnh chứa ô trống, lấy 9 trừ hai số đã biết được 5.' },
  ],
},
{
  id: 3405, title: 'Phiếu 05', time: 20,
  questions: [
    { sec: 'Cân so sánh', name: 'Câu 1', pts: 1.25,
      text: 'Biết 1 quả táo 🍎 nặng bằng 3 quả mận 🟣, và 1 quả mận 🟣 nặng bằng 3 hạt dẻ 🌰. Hỏi 1 quả táo 🍎 nặng bằng bao nhiêu <b>hạt dẻ</b>?',
      opts: o4('6', '9', '10', '8'), ans: 'B',
      why: '1 táo = 3 mận, mỗi mận = 3 hạt dẻ nên 1 táo = 3 × 3 = 9 hạt dẻ.' },
    { sec: 'Phép tính ẩn', name: 'Câu 2', pts: 1.25,
      text: 'Biết: 🍎 + 🍎 = 16 và 🍎 + 🍌 = 14. Hỏi <b>🍌</b> bằng bao nhiêu?',
      opts: o4('6', '8', '14', '7'), ans: 'A',
      why: 'Từ 🍎 + 🍎 = 16 suy ra 🍎 = 8. Thay vào 🍎 + 🍌 = 14: 🍌 = 14 − 8 = 6.' },
    { sec: 'Đếm hình', name: 'Câu 3', pts: 1.25,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttw3/q12.svg',
      opts: o4('6', '3', '7', '5'), ans: 'A',
      why: 'Có 3 tam giác nhỏ, cộng thêm các tam giác lớn ghép lại; tổng cộng 3 × (3 + 1) : 2 = 6 tam giác.' },
    { sec: 'Đếm khối', name: 'Câu 4', pts: 1.25,
      text: 'Các khối lập phương giống nhau xếp thành hình bậc thang. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttw3/q13.svg',
      opts: o4('11', '9', '16', '10'), ans: 'D',
      why: 'Đếm theo từng cột: 1 + 2 + 3 + 4 = 10 khối.' },
    { sec: 'Non-routine', name: 'Câu 5', pts: 1.25,
      text: 'Một cửa hàng bán bút 4 nghìn đồng một chiếc, có khuyến mãi <b>mua 3 tặng 1</b>. Bạn Nam có 28 nghìn đồng. Nam mua được <b>nhiều nhất</b> bao nhiêu chiếc bút?',
      opts: o4('9', '7', '10', '8'), ans: 'A',
      why: 'Với 28 nghìn mua được 7 chiếc (7 × 4 = 28). Cứ mua 3 tặng 1 nên được tặng thêm 2 chiếc. Tổng: 7 + 2 = 9 chiếc.' },
    { sec: 'Non-routine', name: 'Câu 6', pts: 1.25,
      text: 'Cần trả đúng 9 nghìn đồng bằng các tờ tiền loại 1 nghìn, 2 nghìn và 5 nghìn. Dùng <b>ít tờ tiền nhất</b> thì cần bao nhiêu tờ?',
      opts: o4('4', '5', '9', '3'), ans: 'D',
      why: 'Ưu tiên tờ lớn: 1 tờ 5 nghìn, 2 tờ 2 nghìn = 9 nghìn, dùng 3 tờ.' },
    { sec: 'Bài toán mẹo', name: 'Câu 7', pts: 1.25,
      text: 'Trên cành cây có 6 con chim. Có 4 con bay đi nơi khác. Hỏi trên cành còn lại mấy con chim?',
      opts: o4('6', '4', '10', '2'), ans: 'D',
      why: 'Còn lại = 6 − 4 = 2 con chim.' },
    { sec: 'Suy luận', name: 'Câu 8', pts: 1.25,
      text: 'Trong một cuộc thi chạy: Mai về trước Hoa, Hoa về trước Tú. Hỏi bạn nào về <b>đích đầu tiên</b>?',
      opts: o4('Tú', 'Hoa', 'Mai', 'Không xác định được'), ans: 'C',
      why: 'Thứ tự về đích: Mai → Hoa → Tú. Vậy Mai về đầu tiên.' },
  ],
},
{
  id: 3406, title: 'Phiếu 06', time: 20,
  questions: [
    { sec: 'Thời gian', name: 'Câu 1', pts: 1.25,
      text: 'Đồng hồ đang chỉ 2 giờ đúng. Hỏi <b>sau 4 giờ nữa</b> đồng hồ chỉ mấy giờ?', img: 'assets/ttw3/q14.svg',
      opts: o4('7 giờ', '4 giờ', '6 giờ', '2 giờ'), ans: 'C',
      why: 'Sau 4 giờ nữa là 2 + 4 = 6 giờ, tức 6 giờ.' },
    { sec: 'Hình học', name: 'Câu 2', pts: 1.25,
      text: 'Một hình chữ nhật có chiều dài 8 cm, chiều rộng 3 cm. Tính <b>chu vi</b> hình chữ nhật đó.',
      opts: o4('11 cm', '22 cm', '24 cm', '20 cm'), ans: 'B',
      why: 'Chu vi = (dài + rộng) × 2 = (8 + 3) × 2 = 22 cm.' },
    { sec: 'Tính nhanh', name: 'Câu 3', pts: 1.25,
      text: 'Tính nhanh: <b>200 − 4 − 5 − 6 − 7</b>',
      opts: o4('178', '174', '182', '196'), ans: 'A',
      why: 'Trừ liên tiếp = trừ tổng: 200 − (4 + 5 + 6 + 7) = 200 − 22 = 178.' },
    { sec: 'Gà và thỏ', name: 'Câu 4', pts: 1.25,
      text: 'Vừa gà vừa thỏ có tất cả 8 con, đếm được 22 chân. Hỏi có bao nhiêu con <b>thỏ</b>?',
      opts: o4('5', '3', '4', '2'), ans: 'B',
      why: 'Giả sử tất cả là gà: 8 × 2 = 16 chân, thiếu 6 chân. Mỗi con thỏ hơn gà 2 chân nên số thỏ = 6 : 2 = 3, số gà = 5. Vậy có 3 con thỏ.' },
    { sec: 'Trồng cây', name: 'Câu 5', pts: 1.25,
      text: 'Trồng cây dọc một đoạn đường dài 12 m, hai cây cạnh nhau cách 3 m, trồng cả ở <b>hai đầu</b> đường. Cần bao nhiêu cây?', img: 'assets/ttw3/q15.svg',
      opts: o4('4', '6', '5', '3'), ans: 'C',
      why: 'Số khoảng = 12 : 3 = 4. Trồng cả hai đầu nên số cây = số khoảng + 1 = 5 cây.' },
    { sec: 'Bài toán tuổi', name: 'Câu 6', pts: 1.25,
      text: 'Mẹ hơn con 15 tuổi. Năm nay tuổi mẹ gấp 4 lần tuổi con. Hỏi <b>mẹ</b> năm nay bao nhiêu tuổi?',
      opts: o4('5', '15', '20', '22'), ans: 'C',
      why: 'Tuổi mẹ gấp 4 lần tuổi con nên hiệu 15 tuổi ứng với 4 − 1 = 3 lần tuổi con. Tuổi con = 15 : 3 = 5, tuổi mẹ = 5 × 4 = 20.' },
    { sec: 'Suy ngược', name: 'Câu 7', pts: 1.25,
      text: 'Một bạn nghĩ ra một số, <b>cộng 9</b>, rồi <b>nhân 3</b>, rồi <b>bớt 2</b> thì được 55. Hỏi bạn đã nghĩ ra số nào?', img: 'assets/ttw3/q16.svg',
      opts: o4('55', '19', '11', '10'), ans: 'D',
      why: 'Đi lùi từ kết quả: (55 + 2) : 3 − 9 = 57 : 3 − 9 = 19 − 9 = 10.' },
    { sec: 'Nguyên lý ngăn kéo', name: 'Câu 8', pts: 1.25,
      text: 'Trong một chiếc hộp kín có rất nhiều viên bi thuộc 2 màu (đỏ, xanh). Không nhìn vào hộp, phải lấy ra ít nhất bao nhiêu viên để <b>chắc chắn</b> có 2 viên cùng màu?',
      opts: o4('2', '4', '3', '5'), ans: 'C',
      why: 'Xấu nhất mỗi màu lấy được 1 viên (2 viên khác màu). Lấy thêm 1 viên nữa thì chắc chắn trùng màu: 2 + 1 = 3 viên.' },
  ],
},
{
  id: 3407, title: 'Phiếu 07', time: 20,
  questions: [
    { sec: 'Tổng và hiệu', name: 'Câu 1', pts: 1.25,
      text: 'Hai số có tổng bằng 71 và hiệu bằng 47. Tìm <b>số lớn</b>.',
      opts: o4('59', '12', '106', '71'), ans: 'A',
      why: 'Số lớn = (tổng + hiệu) : 2 = (71 + 47) : 2 = 59. Số bé = 12.' },
    { sec: 'Quy về đơn vị', name: 'Câu 2', pts: 1.25,
      text: 'Mua 5 quyển vở giống nhau hết 25 nghìn đồng. Hỏi mua 6 quyển vở như thế hết bao nhiêu nghìn đồng?',
      opts: o4('30', '35', '25', '31'), ans: 'A',
      why: 'Giá một quyển: 25 : 5 = 5 nghìn. Mua 6 quyển hết: 5 × 6 = 30 nghìn đồng.' },
    { sec: 'Tìm quy luật', name: 'Câu 3', pts: 1.25,
      text: 'Tìm số thích hợp điền vào ô có dấu <b>?</b>.', img: 'assets/ttw3/q17.svg',
      opts: o4('25', '21', '17', '22'), ans: 'B',
      why: 'Mỗi số hơn số trước 4 đơn vị nên số cần tìm = 17 + 4 = 21.' },
    { sec: 'Số trận đồ', name: 'Câu 4', pts: 1.25,
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng nhau. Tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q18.svg',
      opts: o4('12', '10', '36', '11'), ans: 'D',
      why: 'Tổng mỗi hàng là 36. Lấy 36 trừ hai số đã biết cùng hàng (hoặc cùng cột) với ô trống được 11.' },
    { sec: 'Số trận đồ', name: 'Câu 5', pts: 1.25,
      text: 'Tổng ba số trên <b>mỗi cạnh</b> của tam giác đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttw3/q19.svg',
      opts: o4('10', '8', '33', '9'), ans: 'D',
      why: 'Tổng mỗi cạnh là 33. Ở cạnh chứa ô trống, lấy 33 trừ hai số đã biết được 9.' },
    { sec: 'Cân so sánh', name: 'Câu 6', pts: 1.25,
      text: 'Biết 1 quả táo 🍎 nặng bằng 2 quả mận 🟣, và 1 quả mận 🟣 nặng bằng 4 hạt dẻ 🌰. Hỏi 1 quả táo 🍎 nặng bằng bao nhiêu <b>hạt dẻ</b>?',
      opts: o4('6', '9', '8', '7'), ans: 'C',
      why: '1 táo = 2 mận, mỗi mận = 4 hạt dẻ nên 1 táo = 2 × 4 = 8 hạt dẻ.' },
    { sec: 'Phép tính ẩn', name: 'Câu 7', pts: 1.25,
      text: 'Biết: 🍎 + 🍎 = 6 và 🍎 + 🍌 = 12. Hỏi <b>🍌</b> bằng bao nhiêu?',
      opts: o4('3', '12', '9', '10'), ans: 'C',
      why: 'Từ 🍎 + 🍎 = 6 suy ra 🍎 = 3. Thay vào 🍎 + 🍌 = 12: 🍌 = 12 − 3 = 9.' },
    { sec: 'Đếm hình', name: 'Câu 8', pts: 1.25,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttw3/q20.svg',
      opts: o4('4', '11', '9', '10'), ans: 'D',
      why: 'Có 4 tam giác nhỏ, cộng thêm các tam giác lớn ghép lại; tổng cộng 4 × (4 + 1) : 2 = 10 tam giác.' },
  ],
},
{
  id: 3408, title: 'Phiếu 08', time: 20,
  questions: [
    { sec: 'Đếm khối', name: 'Câu 1', pts: 1.25,
      text: 'Các khối lập phương giống nhau xếp thành hình bậc thang. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttw3/q21.svg',
      opts: o4('16', '15', '14', '25'), ans: 'B',
      why: 'Đếm theo từng cột: 1 + 2 + 3 + 4 + 5 = 15 khối.' },
    { sec: 'Non-routine', name: 'Câu 2', pts: 1.25,
      text: 'Một cửa hàng bán bút 4 nghìn đồng một chiếc, có khuyến mãi <b>mua 3 tặng 1</b>. Bạn Nam có 28 nghìn đồng. Nam mua được <b>nhiều nhất</b> bao nhiêu chiếc bút?',
      opts: o4('7', '10', '9', '8'), ans: 'C',
      why: 'Với 28 nghìn mua được 7 chiếc (7 × 4 = 28). Cứ mua 3 tặng 1 nên được tặng thêm 2 chiếc. Tổng: 7 + 2 = 9 chiếc.' },
    { sec: 'Non-routine', name: 'Câu 3', pts: 1.25,
      text: 'Cần trả đúng 16 nghìn đồng bằng các tờ tiền loại 1 nghìn, 2 nghìn và 5 nghìn. Dùng <b>ít tờ tiền nhất</b> thì cần bao nhiêu tờ?',
      opts: o4('5', '6', '16', '4'), ans: 'D',
      why: 'Ưu tiên tờ lớn: 3 tờ 5 nghìn, 1 tờ 1 nghìn = 16 nghìn, dùng 4 tờ.' },
    { sec: 'Bài toán mẹo', name: 'Câu 4', pts: 1.25,
      text: 'Trên cành cây có 7 con chim. Có 3 con bay đi nơi khác. Hỏi trên cành còn lại mấy con chim?',
      opts: o4('4', '7', '3', '10'), ans: 'A',
      why: 'Còn lại = 7 − 3 = 4 con chim.' },
    { sec: 'Suy luận', name: 'Câu 5', pts: 1.25,
      text: 'Trong một cuộc thi chạy: Hoa về trước Tú, Tú về trước An. Hỏi bạn nào về <b>đích đầu tiên</b>?',
      opts: o4('An', 'Tú', 'Hoa', 'Không xác định được'), ans: 'C',
      why: 'Thứ tự về đích: Hoa → Tú → An. Vậy Hoa về đầu tiên.' },
    { sec: 'Thời gian', name: 'Câu 6', pts: 1.25,
      text: 'Đồng hồ đang chỉ 8 giờ đúng. Hỏi <b>sau 4 giờ nữa</b> đồng hồ chỉ mấy giờ?', img: 'assets/ttw3/q22.svg',
      opts: o4('1 giờ', '12 giờ', '4 giờ', '8 giờ'), ans: 'B',
      why: 'Sau 4 giờ nữa là 8 + 4 = 12 giờ, tức 12 giờ.' },
    { sec: 'Hình học', name: 'Câu 7', pts: 1.25,
      text: 'Một hình chữ nhật có chiều dài 5 cm, chiều rộng 3 cm. Tính <b>chu vi</b> hình chữ nhật đó.',
      opts: o4('16 cm', '8 cm', '15 cm', '18 cm'), ans: 'A',
      why: 'Chu vi = (dài + rộng) × 2 = (5 + 3) × 2 = 16 cm.' },
    { sec: 'Tính nhanh', name: 'Câu 8', pts: 1.25,
      text: 'Tính nhanh: <b>100 − 2 − 3 − 4 − 5</b>',
      opts: o4('86', '82', '90', '98'), ans: 'A',
      why: 'Trừ liên tiếp = trừ tổng: 100 − (2 + 3 + 4 + 5) = 100 − 14 = 86.' },
  ],
},
{
  id: 3409, title: 'Phiếu 09', time: 20,
  questions: [
    { sec: 'Gà và thỏ', name: 'Câu 1', pts: 1.25,
      text: 'Bãi xe có 11 chiếc xe gồm xe đạp (2 bánh) và xe ba bánh (3 bánh), đếm được tất cả 25 bánh xe. Hỏi có bao nhiêu <b>xe đạp</b>?',
      opts: o4('3', '9', '7', '8'), ans: 'D',
      why: 'Giả sử tất cả là xe đạp: 11 × 2 = 22 bánh, thiếu 3 bánh. Mỗi xe ba bánh hơn 1 bánh nên số xe ba bánh = 3, số xe đạp = 8. Vậy xe đạp có 8 chiếc.' },
    { sec: 'Trồng cây', name: 'Câu 2', pts: 1.25,
      text: 'Đóng cọc quanh một cái ao hình tròn có chu vi 20 m, hai cọc cạnh nhau cách 5 m. Cần bao nhiêu cọc?',
      opts: o4('5', '4', '3', '20'), ans: 'B',
      why: 'Vì trồng theo <b>vòng khép kín</b> nên số cọc = số khoảng = 20 : 5 = 4 cọc.' },
    { sec: 'Bài toán tuổi', name: 'Câu 3', pts: 1.25,
      text: 'Mẹ hơn con 6 tuổi. Năm nay tuổi mẹ gấp 2 lần tuổi con. Hỏi <b>con</b> năm nay bao nhiêu tuổi?',
      opts: o4('6', '12', '8', '7'), ans: 'A',
      why: 'Tuổi mẹ gấp 2 lần tuổi con nên hiệu 6 tuổi ứng với 2 − 1 = 1 lần tuổi con. Tuổi con = 6 : 1 = 6, tuổi mẹ = 6 × 2 = 12.' },
    { sec: 'Suy ngược', name: 'Câu 4', pts: 1.25,
      text: 'Một bạn nghĩ ra một số, <b>cộng 9</b>, rồi <b>nhân 2</b>, rồi <b>bớt 5</b> thì được 25. Hỏi bạn đã nghĩ ra số nào?', img: 'assets/ttw3/q23.svg',
      opts: o4('25', '6', '15', '7'), ans: 'B',
      why: 'Đi lùi từ kết quả: (25 + 5) : 2 − 9 = 30 : 2 − 9 = 15 − 9 = 6.' },
    { sec: 'Nguyên lý ngăn kéo', name: 'Câu 5', pts: 1.25,
      text: 'Trong một chiếc hộp kín có rất nhiều viên bi thuộc 2 màu (đỏ, xanh). Không nhìn vào hộp, phải lấy ra ít nhất bao nhiêu viên để <b>chắc chắn</b> có 2 viên cùng màu?',
      opts: o4('2', '4', '5', '3'), ans: 'D',
      why: 'Xấu nhất mỗi màu lấy được 1 viên (2 viên khác màu). Lấy thêm 1 viên nữa thì chắc chắn trùng màu: 2 + 1 = 3 viên.' },
    { sec: 'Tổng và hiệu', name: 'Câu 6', pts: 1.25,
      text: 'Hai số có tổng bằng 65 và hiệu bằng 39. Tìm <b>số bé</b>.',
      opts: o4('13', '52', '65', '14'), ans: 'A',
      why: 'Số lớn = (tổng + hiệu) : 2 = (65 + 39) : 2 = 52. Số bé = 13.' },
    { sec: 'Quy về đơn vị', name: 'Câu 7', pts: 1.25,
      text: 'Mua 4 quyển vở giống nhau hết 32 nghìn đồng. Hỏi mua 5 quyển vở như thế hết bao nhiêu nghìn đồng?',
      opts: o4('40', '48', '32', '37'), ans: 'A',
      why: 'Giá một quyển: 32 : 4 = 8 nghìn. Mua 5 quyển hết: 8 × 5 = 40 nghìn đồng.' },
    { sec: 'Tìm quy luật', name: 'Câu 8', pts: 1.25,
      text: 'Quan sát khoảng cách tăng dần rồi tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q24.svg',
      opts: o4('17', '15', '18', '16'), ans: 'D',
      why: 'Khoảng cách tăng dần 2, 3, 4, 5. Số cuối = 11 + 5 = 16.' },
  ],
},
{
  id: 3410, title: 'Phiếu 10', time: 20,
  questions: [
    { sec: 'Số trận đồ', name: 'Câu 1', pts: 1.25,
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng nhau. Tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q25.svg',
      opts: o4('19', '18', '17', '48'), ans: 'B',
      why: 'Tổng mỗi hàng là 48. Lấy 48 trừ hai số đã biết cùng hàng (hoặc cùng cột) với ô trống được 18.' },
    { sec: 'Số trận đồ', name: 'Câu 2', pts: 1.25,
      text: 'Tổng ba số trên <b>mỗi cạnh</b> của tam giác đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttw3/q26.svg',
      opts: o4('9', '7', '8', '27'), ans: 'C',
      why: 'Tổng mỗi cạnh là 27. Ở cạnh chứa ô trống, lấy 27 trừ hai số đã biết được 8.' },
    { sec: 'Cân so sánh', name: 'Câu 3', pts: 1.25,
      text: 'Biết 1 quả táo 🍎 nặng bằng 3 quả mận 🟣, và 1 quả mận 🟣 nặng bằng 4 hạt dẻ 🌰. Hỏi 1 quả táo 🍎 nặng bằng bao nhiêu <b>hạt dẻ</b>?',
      opts: o4('12', '7', '13', '11'), ans: 'A',
      why: '1 táo = 3 mận, mỗi mận = 4 hạt dẻ nên 1 táo = 3 × 4 = 12 hạt dẻ.' },
    { sec: 'Phép tính ẩn', name: 'Câu 4', pts: 1.25,
      text: 'Biết: 🍎 + 🍎 = 10 và 🍎 + 🍌 = 9. Hỏi <b>🍌</b> bằng bao nhiêu?',
      opts: o4('5', '9', '4', '3'), ans: 'C',
      why: 'Từ 🍎 + 🍎 = 10 suy ra 🍎 = 5. Thay vào 🍎 + 🍌 = 9: 🍌 = 9 − 5 = 4.' },
    { sec: 'Đếm hình', name: 'Câu 5', pts: 1.25,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttw3/q27.svg',
      opts: o4('4', '11', '9', '10'), ans: 'D',
      why: 'Có 4 tam giác nhỏ, cộng thêm các tam giác lớn ghép lại; tổng cộng 4 × (4 + 1) : 2 = 10 tam giác.' },
    { sec: 'Đếm khối', name: 'Câu 6', pts: 1.25,
      text: 'Các khối lập phương giống nhau xếp thành hình bậc thang. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttw3/q28.svg',
      opts: o4('16', '14', '15', '25'), ans: 'C',
      why: 'Đếm theo từng cột: 1 + 2 + 3 + 4 + 5 = 15 khối.' },
    { sec: 'Non-routine', name: 'Câu 7', pts: 1.25,
      text: 'Một cửa hàng bán bút 5 nghìn đồng một chiếc, có khuyến mãi <b>mua 3 tặng 1</b>. Bạn Nam có 20 nghìn đồng. Nam mua được <b>nhiều nhất</b> bao nhiêu chiếc bút?',
      opts: o4('4', '5', '6', '7'), ans: 'B',
      why: 'Với 20 nghìn mua được 4 chiếc (4 × 5 = 20). Cứ mua 3 tặng 1 nên được tặng thêm 1 chiếc. Tổng: 4 + 1 = 5 chiếc.' },
    { sec: 'Non-routine', name: 'Câu 8', pts: 1.25,
      text: 'Cần trả đúng 15 nghìn đồng bằng các tờ tiền loại 1 nghìn, 2 nghìn và 5 nghìn. Dùng <b>ít tờ tiền nhất</b> thì cần bao nhiêu tờ?',
      opts: o4('4', '5', '3', '15'), ans: 'C',
      why: 'Ưu tiên tờ lớn: 3 tờ 5 nghìn = 15 nghìn, dùng 3 tờ.' },
  ],
},
{
  id: 3411, title: 'Phiếu 11', time: 20,
  questions: [
    { sec: 'Bài toán mẹo', name: 'Câu 1', pts: 1.25,
      text: 'Trên cành cây có 8 con chim. Có 2 con bay đi nơi khác. Hỏi trên cành còn lại mấy con chim?',
      opts: o4('8', '2', '6', '10'), ans: 'C',
      why: 'Còn lại = 8 − 2 = 6 con chim.' },
    { sec: 'Suy luận', name: 'Câu 2', pts: 1.25,
      text: 'Trong một cuộc thi chạy: Lan về trước Mai, Mai về trước Hoa. Hỏi bạn nào về <b>đích đầu tiên</b>?',
      opts: o4('Lan', 'Hoa', 'Mai', 'Không xác định được'), ans: 'A',
      why: 'Thứ tự về đích: Lan → Mai → Hoa. Vậy Lan về đầu tiên.' },
    { sec: 'Thời gian', name: 'Câu 3', pts: 1.25,
      text: 'Đồng hồ đang chỉ 2 giờ đúng. Hỏi <b>sau 4 giờ nữa</b> đồng hồ chỉ mấy giờ?', img: 'assets/ttw3/q29.svg',
      opts: o4('6 giờ', '7 giờ', '4 giờ', '2 giờ'), ans: 'A',
      why: 'Sau 4 giờ nữa là 2 + 4 = 6 giờ, tức 6 giờ.' },
    { sec: 'Hình học', name: 'Câu 4', pts: 1.25,
      text: 'Một hình chữ nhật có chiều dài 14 cm, chiều rộng 6 cm. Tính <b>chu vi</b> hình chữ nhật đó.',
      opts: o4('40 cm', '20 cm', '84 cm', '42 cm'), ans: 'A',
      why: 'Chu vi = (dài + rộng) × 2 = (14 + 6) × 2 = 40 cm.' },
    { sec: 'Tính nhanh', name: 'Câu 5', pts: 1.25,
      text: 'Tính nhanh: <b>1 + 2 + 3 + … + 15</b> (cộng các số tự nhiên liên tiếp từ 1 đến 15).',
      opts: o4('135', '120', '105', '225'), ans: 'B',
      why: 'Ghép cặp hai đầu: mỗi cặp có tổng 16, có 7 cặp và số giữa. Kết quả = 15 × 16 : 2 = 120.' },
    { sec: 'Gà và thỏ', name: 'Câu 6', pts: 1.25,
      text: 'Bãi xe có 11 chiếc xe gồm xe đạp (2 bánh) và xe ba bánh (3 bánh), đếm được tất cả 27 bánh xe. Hỏi có bao nhiêu <b>xe đạp</b>?',
      opts: o4('5', '7', '6', '11'), ans: 'C',
      why: 'Giả sử tất cả là xe đạp: 11 × 2 = 22 bánh, thiếu 5 bánh. Mỗi xe ba bánh hơn 1 bánh nên số xe ba bánh = 5, số xe đạp = 6. Vậy xe đạp có 6 chiếc.' },
    { sec: 'Trồng cây', name: 'Câu 7', pts: 1.25,
      text: 'Đóng cọc quanh một cái ao hình tròn có chu vi 32 m, hai cọc cạnh nhau cách 4 m. Cần bao nhiêu cọc?',
      opts: o4('9', '8', '7', '32'), ans: 'B',
      why: 'Vì trồng theo <b>vòng khép kín</b> nên số cọc = số khoảng = 32 : 4 = 8 cọc.' },
    { sec: 'Bài toán tuổi', name: 'Câu 8', pts: 1.25,
      text: 'Mẹ hơn con 20 tuổi. Năm nay tuổi mẹ gấp 3 lần tuổi con. Hỏi <b>con</b> năm nay bao nhiêu tuổi?',
      opts: o4('30', '20', '10', '12'), ans: 'C',
      why: 'Tuổi mẹ gấp 3 lần tuổi con nên hiệu 20 tuổi ứng với 3 − 1 = 2 lần tuổi con. Tuổi con = 20 : 2 = 10, tuổi mẹ = 10 × 3 = 30.' },
  ],
},
{
  id: 3412, title: 'Phiếu 12', time: 20,
  questions: [
    { sec: 'Suy ngược', name: 'Câu 1', pts: 1.25,
      text: 'Một bạn nghĩ ra một số, <b>cộng 8</b>, rồi <b>nhân 3</b>, rồi <b>bớt 4</b> thì được 44. Hỏi bạn đã nghĩ ra số nào?', img: 'assets/ttw3/q30.svg',
      opts: o4('44', '8', '16', '9'), ans: 'B',
      why: 'Đi lùi từ kết quả: (44 + 4) : 3 − 8 = 48 : 3 − 8 = 16 − 8 = 8.' },
    { sec: 'Nguyên lý ngăn kéo', name: 'Câu 2', pts: 1.25,
      text: 'Trong một chiếc hộp kín có rất nhiều viên bi thuộc 2 màu (đỏ, xanh). Không nhìn vào hộp, phải lấy ra ít nhất bao nhiêu viên để <b>chắc chắn</b> có 2 viên cùng màu?',
      opts: o4('2', '4', '3', '5'), ans: 'C',
      why: 'Xấu nhất mỗi màu lấy được 1 viên (2 viên khác màu). Lấy thêm 1 viên nữa thì chắc chắn trùng màu: 2 + 1 = 3 viên.' },
    { sec: 'Tổng và hiệu', name: 'Câu 3', pts: 1.25,
      text: 'Hai số có tổng bằng 40 và hiệu bằng 12. Tìm <b>số lớn</b>.',
      opts: o4('14', '38', '40', '26'), ans: 'D',
      why: 'Số lớn = (tổng + hiệu) : 2 = (40 + 12) : 2 = 26. Số bé = 14.' },
    { sec: 'Quy về đơn vị', name: 'Câu 4', pts: 1.25,
      text: 'Mua 5 quyển vở giống nhau hết 35 nghìn đồng. Hỏi mua 8 quyển vở như thế hết bao nhiêu nghìn đồng?',
      opts: o4('63', '49', '43', '56'), ans: 'D',
      why: 'Giá một quyển: 35 : 5 = 7 nghìn. Mua 8 quyển hết: 7 × 8 = 56 nghìn đồng.' },
    { sec: 'Tìm quy luật', name: 'Câu 5', pts: 1.25,
      text: 'Tìm số thích hợp điền vào ô có dấu <b>?</b>.', img: 'assets/ttw3/q31.svg',
      opts: o4('25', '29', '21', '26'), ans: 'A',
      why: 'Mỗi số hơn số trước 4 đơn vị nên số cần tìm = 21 + 4 = 25.' },
    { sec: 'Số trận đồ', name: 'Câu 6', pts: 1.25,
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng nhau. Tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q32.svg',
      opts: o4('3', '4', '2', '18'), ans: 'A',
      why: 'Tổng mỗi hàng là 18. Lấy 18 trừ hai số đã biết cùng hàng (hoặc cùng cột) với ô trống được 3.' },
    { sec: 'Số trận đồ', name: 'Câu 7', pts: 1.25,
      text: 'Tổng ba số trên <b>mỗi cạnh</b> của tam giác đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttw3/q33.svg',
      opts: o4('5', '3', '4', '12'), ans: 'C',
      why: 'Tổng mỗi cạnh là 12. Ở cạnh chứa ô trống, lấy 12 trừ hai số đã biết được 4.' },
    { sec: 'Cân so sánh', name: 'Câu 8', pts: 1.25,
      text: 'Biết 1 quả táo 🍎 nặng bằng 3 quả mận 🟣, và 1 quả mận 🟣 nặng bằng 4 hạt dẻ 🌰. Hỏi 1 quả táo 🍎 nặng bằng bao nhiêu <b>hạt dẻ</b>?',
      opts: o4('7', '13', '11', '12'), ans: 'D',
      why: '1 táo = 3 mận, mỗi mận = 4 hạt dẻ nên 1 táo = 3 × 4 = 12 hạt dẻ.' },
  ],
},
{
  id: 3413, title: 'Phiếu 13', time: 20,
  questions: [
    { sec: 'Phép tính ẩn', name: 'Câu 1', pts: 1.25,
      text: 'Biết: 🍎 + 🍎 = 8 và 🍎 + 🍌 = 7. Hỏi <b>🍌</b> bằng bao nhiêu?',
      opts: o4('4', '3', '7', '2'), ans: 'B',
      why: 'Từ 🍎 + 🍎 = 8 suy ra 🍎 = 4. Thay vào 🍎 + 🍌 = 7: 🍌 = 7 − 4 = 3.' },
    { sec: 'Đếm hình', name: 'Câu 2', pts: 1.25,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttw3/q34.svg',
      opts: o4('3', '7', '5', '6'), ans: 'D',
      why: 'Có 3 tam giác nhỏ, cộng thêm các tam giác lớn ghép lại; tổng cộng 3 × (3 + 1) : 2 = 6 tam giác.' },
    { sec: 'Đếm khối', name: 'Câu 3', pts: 1.25,
      text: 'Các khối lập phương giống nhau xếp thành hình bậc thang. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttw3/q35.svg',
      opts: o4('16', '15', '14', '25'), ans: 'B',
      why: 'Đếm theo từng cột: 1 + 2 + 3 + 4 + 5 = 15 khối.' },
    { sec: 'Non-routine', name: 'Câu 4', pts: 1.25,
      text: 'Một cửa hàng bán bút 6 nghìn đồng một chiếc, có khuyến mãi <b>mua 3 tặng 1</b>. Bạn Nam có 42 nghìn đồng. Nam mua được <b>nhiều nhất</b> bao nhiêu chiếc bút?',
      opts: o4('7', '9', '10', '8'), ans: 'B',
      why: 'Với 42 nghìn mua được 7 chiếc (7 × 6 = 42). Cứ mua 3 tặng 1 nên được tặng thêm 2 chiếc. Tổng: 7 + 2 = 9 chiếc.' },
    { sec: 'Non-routine', name: 'Câu 5', pts: 1.25,
      text: 'Cần trả đúng 7 nghìn đồng bằng các tờ tiền loại 1 nghìn, 2 nghìn và 5 nghìn. Dùng <b>ít tờ tiền nhất</b> thì cần bao nhiêu tờ?',
      opts: o4('3', '4', '7', '2'), ans: 'D',
      why: 'Ưu tiên tờ lớn: 1 tờ 5 nghìn, 1 tờ 2 nghìn = 7 nghìn, dùng 2 tờ.' },
    { sec: 'Bài toán mẹo', name: 'Câu 6', pts: 1.25,
      text: 'Trên cành cây có 6 con chim. Có 3 con bay đi nơi khác. Hỏi trên cành còn lại mấy con chim?',
      opts: o4('6', '9', '3', '4'), ans: 'C',
      why: 'Còn lại = 6 − 3 = 3 con chim.' },
    { sec: 'Suy luận', name: 'Câu 7', pts: 1.25,
      text: 'Trong một cuộc thi chạy: Mai về trước Hoa, Hoa về trước Tú. Hỏi bạn nào về <b>đích đầu tiên</b>?',
      opts: o4('Tú', 'Hoa', 'Mai', 'Không xác định được'), ans: 'C',
      why: 'Thứ tự về đích: Mai → Hoa → Tú. Vậy Mai về đầu tiên.' },
    { sec: 'Thời gian', name: 'Câu 8', pts: 1.25,
      text: 'Đồng hồ đang chỉ 6 giờ đúng. Hỏi <b>sau 2 giờ nữa</b> đồng hồ chỉ mấy giờ?', img: 'assets/ttw3/q36.svg',
      opts: o4('9 giờ', '2 giờ', '8 giờ', '6 giờ'), ans: 'C',
      why: 'Sau 2 giờ nữa là 6 + 2 = 8 giờ, tức 8 giờ.' },
  ],
},
{
  id: 3414, title: 'Phiếu 14', time: 20,
  questions: [
    { sec: 'Hình học', name: 'Câu 1', pts: 1.25,
      text: 'Một hình chữ nhật có chiều dài 15 cm, chiều rộng 6 cm. Tính <b>chu vi</b> hình chữ nhật đó.',
      opts: o4('21 cm', '90 cm', '42 cm', '44 cm'), ans: 'C',
      why: 'Chu vi = (dài + rộng) × 2 = (15 + 6) × 2 = 42 cm.' },
    { sec: 'Tính nhanh', name: 'Câu 2', pts: 1.25,
      text: 'Tính nhanh: <b>1 + 2 + 3 + … + 20</b> (cộng các số tự nhiên liên tiếp từ 1 đến 20).',
      opts: o4('230', '210', '190', '400'), ans: 'B',
      why: 'Ghép cặp hai đầu: mỗi cặp có tổng 21, có 10 cặp. Kết quả = 20 × 21 : 2 = 210.' },
    { sec: 'Gà và thỏ', name: 'Câu 3', pts: 1.25,
      text: 'Vừa gà vừa thỏ có tất cả 11 con, đếm được 28 chân. Hỏi có bao nhiêu con <b>thỏ</b>?',
      opts: o4('3', '8', '4', '2'), ans: 'A',
      why: 'Giả sử tất cả là gà: 11 × 2 = 22 chân, thiếu 6 chân. Mỗi con thỏ hơn gà 2 chân nên số thỏ = 6 : 2 = 3, số gà = 8. Vậy có 3 con thỏ.' },
    { sec: 'Trồng cây', name: 'Câu 4', pts: 1.25,
      text: 'Đóng cọc quanh một cái ao hình tròn có chu vi 30 m, hai cọc cạnh nhau cách 5 m. Cần bao nhiêu cọc?',
      opts: o4('7', '5', '30', '6'), ans: 'D',
      why: 'Vì trồng theo <b>vòng khép kín</b> nên số cọc = số khoảng = 30 : 5 = 6 cọc.' },
    { sec: 'Bài toán tuổi', name: 'Câu 5', pts: 1.25,
      text: 'Mẹ hơn con 30 tuổi. Năm nay tuổi mẹ gấp 4 lần tuổi con. Hỏi <b>con</b> năm nay bao nhiêu tuổi?',
      opts: o4('40', '30', '10', '12'), ans: 'C',
      why: 'Tuổi mẹ gấp 4 lần tuổi con nên hiệu 30 tuổi ứng với 4 − 1 = 3 lần tuổi con. Tuổi con = 30 : 3 = 10, tuổi mẹ = 10 × 4 = 40.' },
    { sec: 'Suy ngược', name: 'Câu 6', pts: 1.25,
      text: 'Một bạn nghĩ ra một số, <b>cộng 6</b>, rồi <b>nhân 3</b>, rồi <b>bớt 7</b> thì được 35. Hỏi bạn đã nghĩ ra số nào?', img: 'assets/ttw3/q37.svg',
      opts: o4('35', '8', '14', '9'), ans: 'B',
      why: 'Đi lùi từ kết quả: (35 + 7) : 3 − 6 = 42 : 3 − 6 = 14 − 6 = 8.' },
    { sec: 'Nguyên lý ngăn kéo', name: 'Câu 7', pts: 1.25,
      text: 'Trong một chiếc hộp kín có rất nhiều viên bi thuộc 3 màu (đỏ, xanh, vàng). Không nhìn vào hộp, phải lấy ra ít nhất bao nhiêu viên để <b>chắc chắn</b> có 2 viên cùng màu?',
      opts: o4('3', '5', '6', '4'), ans: 'D',
      why: 'Xấu nhất mỗi màu lấy được 1 viên (3 viên khác màu). Lấy thêm 1 viên nữa thì chắc chắn trùng màu: 3 + 1 = 4 viên.' },
    { sec: 'Tổng và hiệu', name: 'Câu 8', pts: 1.25,
      text: 'Hai số có tổng bằng 82 và hiệu bằng 12. Tìm <b>số lớn</b>.',
      opts: o4('47', '35', '59', '82'), ans: 'A',
      why: 'Số lớn = (tổng + hiệu) : 2 = (82 + 12) : 2 = 47. Số bé = 35.' },
  ],
},
{
  id: 3415, title: 'Phiếu 15', time: 20,
  questions: [
    { sec: 'Quy về đơn vị', name: 'Câu 1', pts: 1.25,
      text: 'Mua 4 quyển vở giống nhau hết 20 nghìn đồng. Hỏi mua 9 quyển vở như thế hết bao nhiêu nghìn đồng?',
      opts: o4('50', '45', '40', '29'), ans: 'B',
      why: 'Giá một quyển: 20 : 4 = 5 nghìn. Mua 9 quyển hết: 5 × 9 = 45 nghìn đồng.' },
    { sec: 'Tìm quy luật', name: 'Câu 2', pts: 1.25,
      text: 'Quan sát khoảng cách tăng dần rồi tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q38.svg',
      opts: o4('17', '16', '15', '18'), ans: 'B',
      why: 'Khoảng cách tăng dần 2, 3, 4, 5. Số cuối = 11 + 5 = 16.' },
    { sec: 'Số trận đồ', name: 'Câu 3', pts: 1.25,
      text: 'Trong bảng, tổng ba số ở mỗi hàng và mỗi cột đều bằng nhau. Tìm số ở ô <b>?</b>.', img: 'assets/ttw3/q39.svg',
      opts: o4('12', '11', '10', '33'), ans: 'B',
      why: 'Tổng mỗi hàng là 33. Lấy 33 trừ hai số đã biết cùng hàng (hoặc cùng cột) với ô trống được 11.' },
    { sec: 'Số trận đồ', name: 'Câu 4', pts: 1.25,
      text: 'Tổng ba số trên <b>mỗi cạnh</b> của tam giác đều bằng nhau. Tìm số ở ô có dấu <b>?</b>.', img: 'assets/ttw3/q40.svg',
      opts: o4('10', '8', '21', '9'), ans: 'D',
      why: 'Tổng mỗi cạnh là 21. Ở cạnh chứa ô trống, lấy 21 trừ hai số đã biết được 9.' },
    { sec: 'Cân so sánh', name: 'Câu 5', pts: 1.25,
      text: 'Biết 1 quả táo 🍎 nặng bằng 3 quả mận 🟣, và 1 quả mận 🟣 nặng bằng 4 hạt dẻ 🌰. Hỏi 1 quả táo 🍎 nặng bằng bao nhiêu <b>hạt dẻ</b>?',
      opts: o4('7', '12', '13', '11'), ans: 'B',
      why: '1 táo = 3 mận, mỗi mận = 4 hạt dẻ nên 1 táo = 3 × 4 = 12 hạt dẻ.' },
    { sec: 'Phép tính ẩn', name: 'Câu 6', pts: 1.25,
      text: 'Biết: 🍎 + 🍎 = 16 và 🍎 + 🍌 = 11. Hỏi <b>🍌</b> bằng bao nhiêu?',
      opts: o4('3', '8', '11', '4'), ans: 'A',
      why: 'Từ 🍎 + 🍎 = 16 suy ra 🍎 = 8. Thay vào 🍎 + 🍌 = 11: 🍌 = 11 − 8 = 3.' },
    { sec: 'Đếm hình', name: 'Câu 7', pts: 1.25,
      text: 'Đếm xem trong hình có tất cả bao nhiêu <b>hình tam giác</b> (kể cả tam giác lớn ghép từ nhiều tam giác nhỏ).', img: 'assets/ttw3/q41.svg',
      opts: o4('2', '4', '3', '5'), ans: 'C',
      why: 'Có 2 tam giác nhỏ, cộng thêm các tam giác lớn ghép lại; tổng cộng 2 × (2 + 1) : 2 = 3 tam giác.' },
    { sec: 'Đếm khối', name: 'Câu 8', pts: 1.25,
      text: 'Các khối lập phương giống nhau xếp thành hình bậc thang. Có tất cả bao nhiêu <b>khối</b>?', img: 'assets/ttw3/q42.svg',
      opts: o4('11', '10', '9', '16'), ans: 'B',
      why: 'Đếm theo từng cột: 1 + 2 + 3 + 4 = 10 khối.' },
  ],
},
];

// Chèn môn "Tư duy tổng hợp lớp 3"
SUBJECTS.push({
  id: 'ttw3', name: 'Tư duy tổng hợp', short: 'Tư duy tuần 3', icon: '🌟', grade: 3,
  exams: TTW3, ready: true,
  heroTitle: 'Toán tư duy tổng hợp lớp 3 — 15 phiếu hàng tuần',
  heroMeta: '📚 15 phiếu &nbsp;•&nbsp; 120 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi phiếu &nbsp;•&nbsp; 42 câu có hình (35%) &nbsp;•&nbsp; dạng Trung Quốc · Nga · Úc, lời giải chi tiết',
});
