// KHOA HỌC TỰ NHIÊN — LỚP 6 (THCS, GDPT 2018)
// Mục tiêu bank: 50 đề × 30 câu = 1 500 câu — 60 phút mỗi đề.
// Ma trận mỗi đề: 9 Nhận biết · 9 Thông hiểu · 3 Vận dụng · 9 Nâng cao.
//
// Khung 50 đề (xem de-thi/thcs/MA-TRAN-PHU-CHUONG-TRINH.md):
//   đề 1–30  : theo từng chủ đề — Mở đầu, Chất, Vật liệu, Hỗn hợp, Tế bào,
//              Đa dạng thế giới sống, Lực, Năng lượng, Trái Đất và bầu trời
//   đề 31–40 : giữa kì I, cuối kì I, giữa kì II, cuối kì II
//   đề 41–50 : tổng hợp cuối năm, ôn tập, chuyên đề, nâng cao/HSG

const KHTN6_EXAMS = [

/* ═══════════ ĐỀ 1 — GIỚI THIỆU VỀ KHTN. AN TOÀN TRONG PHÒNG THỰC HÀNH ═══════════ */
{
  id: 10651, title: 'Đề 1 · Giới thiệu về KHTN. An toàn trong phòng thực hành', time: 60,
  questions: [
    { sec: 'Khái niệm KHTN', lvl: 'NB', name: 'Câu 1', pts: 1, text: 'Khoa học tự nhiên là ngành khoa học nghiên cứu về:', opts: o4('các hiện tượng xã hội và đời sống con người', 'lịch sử hình thành và phát triển của loài người', 'các sự vật, hiện tượng và quy luật của thế giới tự nhiên', 'cách thức tổ chức sản xuất và kinh doanh hàng hóa'), ans: 'C', why: 'Khoa học tự nhiên nghiên cứu các sự vật, hiện tượng, quy luật tự nhiên và ảnh hưởng của chúng tới cuộc sống con người.' },
    { sec: 'Khái niệm KHTN', lvl: 'TH', name: 'Câu 2', pts: 1, text: 'Hoạt động nào sau đây KHÔNG được coi là nghiên cứu khoa học tự nhiên?', opts: o4('Nghiên cứu quá trình quang hợp của cây xanh', 'Tìm hiểu về sự nở vì nhiệt của chất rắn', 'Nghiên cứu sự biến đổi của các chất khi đun nóng', 'Nghiên cứu phong tục tập quán của một vùng miền'), ans: 'D', why: 'Phong tục tập quán là đối tượng của khoa học xã hội, không phải khoa học tự nhiên. Ba hoạt động còn lại lần lượt thuộc Sinh học, Vật lí và Hóa học.' },
    { sec: 'Phương pháp tìm hiểu tự nhiên', lvl: 'NC', name: 'Câu 3', pts: 1, text: 'Một bạn trồng hai chậu đậu giống hệt nhau, tưới nước như nhau; một chậu để ngoài sáng, một chậu để trong tối. Thí nghiệm này nhằm tìm hiểu ảnh hưởng của yếu tố nào?', opts: o4('Nước', 'Ánh sáng', 'Nhiệt độ', 'Loại đất trồng'), ans: 'B', why: 'Trong thí nghiệm có đối chứng, chỉ được thay đổi MỘT yếu tố, các yếu tố khác giữ như nhau. Ở đây hai chậu chỉ khác nhau về ánh sáng nên yếu tố đang được khảo sát là ánh sáng.' },
    { sec: 'An toàn thực hành', lvl: 'VD', name: 'Câu 4', pts: 1, text: 'Trong phòng thực hành, khi làm vỡ nhiệt kế thủy ngân, em cần làm gì đầu tiên?', opts: o4('Báo ngay cho giáo viên và không tự ý thu dọn', 'Dùng tay nhặt các hạt thủy ngân cho vào thùng rác', 'Dùng chổi quét thật nhanh rồi đổ xuống cống thoát nước', 'Mở quạt thổi thật mạnh cho thủy ngân bay đi hết'), ans: 'A', why: 'Thủy ngân rất độc và dễ bay hơi. Tuyệt đối không tự xử lí, càng không dùng tay không hay chổi quét; phải báo giáo viên để xử lí đúng quy trình.' },
    { sec: 'Kí hiệu cảnh báo', lvl: 'NB', name: 'Câu 5', pts: 1, text: 'Kí hiệu cảnh báo hình tam giác viền đen, nền vàng dùng để:', opts: o4('chỉ dẫn cách thực hiện thao tác', 'cấm thực hiện một việc nào đó', 'chỉ lối thoát hiểm khi có sự cố', 'cảnh báo về một nguy hiểm'), ans: 'D', why: 'Quy ước: hình tam giác nền vàng — cảnh báo nguy hiểm; hình tròn viền đỏ gạch chéo — cấm; hình vuông/chữ nhật nền xanh — chỉ dẫn hoặc lối thoát.' },
    { sec: 'An toàn thực hành', lvl: 'NC', name: 'Câu 6', pts: 1, text: 'Vì sao trong phòng thực hành KHÔNG được nếm thử hoặc ngửi trực tiếp hóa chất?', opts: o4('Vì nhiều hóa chất độc, có thể gây ngộ độc hoặc bỏng đường hô hấp', 'Vì làm như vậy sẽ khiến hóa chất bị bẩn, không dùng lại được nữa', 'Vì mùi và vị của hóa chất không giúp nhận biết được chất đó', 'Vì hóa chất trong phòng thực hành thường rất đắt tiền và khó mua'), ans: 'A', why: 'Rất nhiều hóa chất có tính độc, ăn mòn hoặc bay hơi mạnh. Nếm hay ngửi trực tiếp có thể gây ngộ độc, bỏng niêm mạc mũi và đường hô hấp. Khi cần ngửi phải dùng tay phẩy nhẹ hơi về phía mũi.' },
    { sec: 'Dụng cụ quan sát', lvl: 'TH', name: 'Câu 7', pts: 1, text: 'Dụng cụ nào sau đây dùng để quan sát các vật có kích thước rất nhỏ như tế bào?', opts: o4('Kính lúp', 'Ống nhòm', 'Kính hiển vi', 'Kính râm'), ans: 'C', why: 'Kính hiển vi có độ phóng đại lớn (hàng trăm đến hàng nghìn lần) nên quan sát được tế bào. Kính lúp chỉ phóng đại vài lần, dùng cho vật nhỏ nhưng mắt vẫn nhìn thấy được.' },
    { sec: 'Dụng cụ quan sát', lvl: 'NC', name: 'Câu 8', pts: 1, text: 'Một kính lúp ghi số bội giác 5x. Điều đó có nghĩa là:', opts: o4('kính lúp có đường kính 5 cm', 'ảnh nhìn qua kính lớn gấp 5 lần so với khi nhìn bằng mắt thường', 'kính lúp có khối lượng 5 gam', 'phải đặt vật cách kính đúng 5 cm mới nhìn rõ'), ans: 'B', why: 'Số bội giác cho biết ảnh quan sát qua kính lớn gấp bao nhiêu lần so với khi nhìn trực tiếp bằng mắt. Số bội giác càng lớn thì ảnh càng to.' },
    { sec: 'Lĩnh vực của KHTN', lvl: 'NB', name: 'Câu 9', pts: 1, text: 'Lĩnh vực nào sau đây KHÔNG thuộc khoa học tự nhiên?', opts: o4('Lịch sử', 'Vật lí', 'Hóa học', 'Sinh học'), ans: 'A', why: 'Lịch sử thuộc nhóm khoa học xã hội. Khoa học tự nhiên gồm Vật lí, Hóa học, Sinh học, Khoa học Trái Đất và Thiên văn học.' },
    { sec: 'An toàn thực hành', lvl: 'TH', name: 'Câu 10', pts: 1, text: 'Khi vào phòng thực hành, việc đầu tiên học sinh cần làm là:', opts: o4('lấy ngay hóa chất ra để bắt đầu làm thí nghiệm', 'bật tất cả các thiết bị điện trong phòng lên', 'đọc kĩ nội quy và hướng dẫn an toàn của phòng', 'tự ý pha trộn các hóa chất có sẵn trên bàn'), ans: 'C', why: 'Nội quy và hướng dẫn an toàn giúp phòng tránh tai nạn. Chỉ được thao tác khi đã hiểu rõ quy định và được giáo viên cho phép.' },
    { sec: 'Phương pháp tìm hiểu tự nhiên', lvl: 'NC', name: 'Câu 11', pts: 1, text: 'Một nhóm học sinh muốn kiểm tra giả thuyết "nước muối làm hạt đậu nảy mầm kém hơn nước thường". Cách bố trí thí nghiệm đúng là:', opts: o4('Ngâm 10 hạt đậu trong nước muối, không cần so sánh với gì khác', 'Ngâm 10 hạt đậu trong nước muối và 5 hạt đậu trong nước thường', 'Ngâm 10 hạt trong nước muối để chỗ tối, 10 hạt trong nước thường để chỗ sáng', 'Ngâm 10 hạt đậu trong nước muối và 10 hạt trong nước thường, các điều kiện khác như nhau'), ans: 'D', why: 'Thí nghiệm phải có nhóm đối chứng, số lượng hạt bằng nhau và chỉ khác nhau đúng một yếu tố (loại nước). Phương án B sai vì số hạt khác nhau; phương án C sai vì thay đổi thêm yếu tố ánh sáng nên không kết luận được nguyên nhân.' },
    { sec: 'Vật thể và chất', lvl: 'TH', name: 'Câu 12', pts: 1, text: 'Vật thể nào sau đây là vật thể tự nhiên?', opts: o4('Cái bàn', 'Cây tre', 'Chiếc xe đạp', 'Quyển vở'), ans: 'B', why: 'Cây tre có sẵn trong tự nhiên, không do con người tạo ra. Bàn, xe đạp, quyển vở đều là vật thể nhân tạo.' },
    { sec: 'Vai trò của KHTN', lvl: 'NB', name: 'Câu 13', pts: 1, text: 'Vai trò của khoa học tự nhiên trong đời sống là:', opts: o4('cung cấp hiểu biết để phát triển công nghệ, bảo vệ sức khỏe và môi trường', 'ghi chép lại các sự kiện quan trọng đã xảy ra trong quá khứ', 'quy định cách ứng xử giữa người với người trong xã hội', 'sáng tác các tác phẩm văn học và nghệ thuật cho cộng đồng'), ans: 'A', why: 'Khoa học tự nhiên là nền tảng để phát triển công nghệ, chăm sóc sức khỏe, bảo vệ môi trường và ứng phó với thiên tai.' },
    { sec: 'An toàn thực hành', lvl: 'VD', name: 'Câu 14', pts: 1, text: 'Khi đun nóng hóa chất trong ống nghiệm, cần hướng miệng ống nghiệm:', opts: o4('về phía mình để quan sát cho rõ', 'về phía bạn ngồi bên cạnh', 'thẳng đứng lên phía trên', 'về phía không có người'), ans: 'D', why: 'Khi đun, chất lỏng có thể sôi bắn ra ngoài. Hướng miệng ống về phía không có người để tránh gây bỏng cho mình và cho người khác.' },
    { sec: 'Phép đo', lvl: 'NC', name: 'Câu 15', pts: 1, text: 'Một bạn đo chiều dài chiếc bút ba lần, được 15,2 cm; 15,3 cm; 15,2 cm. Kết quả phép đo nên ghi là:', opts: o4('15,3 cm', '45,7 cm', '15,2 cm', '15,23 cm'), ans: 'C', why: 'Kết quả lấy giá trị trung bình: (15,2 + 15,3 + 15,2) : 3 = 45,7 : 3 ≈ 15,23 cm. Nhưng thước chỉ đo tới 0,1 cm nên phải làm tròn đúng mức đó ⇒ ghi 15,2 cm. Phương án D ghi thừa chữ số, vượt quá độ chính xác của dụng cụ.' },
    { sec: 'Vật thể và chất', lvl: 'NB', name: 'Câu 16', pts: 1, text: 'Vật thể nào sau đây là vật thể nhân tạo?', opts: o4('Con mèo', 'Chiếc cốc thủy tinh', 'Hòn đá', 'Dòng sông'), ans: 'B', why: 'Chiếc cốc thủy tinh do con người chế tạo nên là vật thể nhân tạo; ba vật còn lại có sẵn trong tự nhiên.' },
    { sec: 'Phương pháp tìm hiểu tự nhiên', lvl: 'NC', name: 'Câu 17', pts: 1, text: 'Thứ tự đúng của các bước trong tiến trình tìm hiểu tự nhiên là:', opts: o4('làm thí nghiệm → quan sát đặt câu hỏi → rút ra kết luận → xây dựng giả thuyết', 'xây dựng giả thuyết → quan sát đặt câu hỏi → rút ra kết luận → làm thí nghiệm', 'rút ra kết luận → xây dựng giả thuyết → làm thí nghiệm → quan sát đặt câu hỏi', 'quan sát đặt câu hỏi → xây dựng giả thuyết → làm thí nghiệm → rút ra kết luận'), ans: 'D', why: 'Tiến trình tìm hiểu tự nhiên bắt đầu từ quan sát và đặt câu hỏi, sau đó dự đoán (giả thuyết), rồi làm thí nghiệm để kiểm tra, cuối cùng mới rút ra kết luận. Kết luận không bao giờ đứng trước thí nghiệm.' },
    { sec: 'Vật thể và chất', lvl: 'TH', name: 'Câu 18', pts: 1, text: 'Chất nào sau đây tạo nên vật thể "chiếc lốp xe"?', opts: o4('Cao su', 'Thủy tinh', 'Nước', 'Sắt'), ans: 'A', why: 'Lốp xe được làm chủ yếu từ cao su vì cao su có tính đàn hồi và bám đường tốt.' },
    { sec: 'An toàn thực hành', lvl: 'NC', name: 'Câu 19', pts: 1, text: 'Vì sao không được dùng tay ướt để cắm hoặc rút phích cắm điện?', opts: o4('Vì tay ướt làm phích cắm nhanh bị hỏng hơn', 'Vì nước làm giảm độ sáng của bóng đèn trong phòng', 'Vì nước dẫn điện nên rất dễ gây điện giật nguy hiểm', 'Vì tay ướt làm ổ cắm bị bẩn và nhanh han gỉ'), ans: 'C', why: 'Nước (nhất là nước có hòa tan muối khoáng trên da) dẫn điện. Tay ướt làm điện trở của cơ thể giảm mạnh, dòng điện dễ truyền qua người gây điện giật.' },
    { sec: 'Kí hiệu cảnh báo', lvl: 'TH', name: 'Câu 20', pts: 1, text: 'Kí hiệu nào sau đây cảnh báo chất dễ cháy?', opts: o4('Hình bàn tay bị ăn mòn', 'Hình ngọn lửa', 'Hình đầu lâu và hai xương chéo', 'Hình cây bị chết và cá chết'), ans: 'B', why: 'Hình ngọn lửa cảnh báo chất dễ cháy. Bàn tay bị ăn mòn — chất ăn mòn; đầu lâu xương chéo — chất độc; cây và cá chết — chất nguy hại cho môi trường.' },
    { sec: 'Dụng cụ đo', lvl: 'NB', name: 'Câu 21', pts: 1, text: 'Dụng cụ dùng để đo khối lượng là:', opts: o4('Cân', 'Thước', 'Nhiệt kế', 'Đồng hồ'), ans: 'A', why: 'Cân đo khối lượng; thước đo chiều dài; nhiệt kế đo nhiệt độ; đồng hồ đo thời gian.' },
    { sec: 'Dụng cụ quan sát', lvl: 'VD', name: 'Câu 22', pts: 1, text: 'Để quan sát gân của một chiếc lá cây, dụng cụ phù hợp nhất là:', opts: o4('Kính hiển vi quang học', 'Ống nhòm', 'Kính râm', 'Kính lúp'), ans: 'D', why: 'Gân lá đủ lớn để mắt thường nhìn thấy nhưng cần phóng to để thấy rõ chi tiết ⇒ dùng kính lúp là phù hợp. Kính hiển vi chỉ dùng cho vật rất nhỏ như tế bào và cần làm tiêu bản.' },
    { sec: 'An toàn thực hành', lvl: 'TH', name: 'Câu 23', pts: 1, text: 'Khi làm thí nghiệm, học sinh KHÔNG được:', opts: o4('đeo kính bảo hộ khi cần thiết', 'rửa tay thật sạch sau khi làm thí nghiệm', 'tự ý trộn lẫn các hóa chất với nhau', 'đọc kĩ nhãn hóa chất trước khi sử dụng'), ans: 'C', why: 'Tự ý trộn hóa chất có thể gây phản ứng mạnh, sinh khí độc, cháy nổ. Chỉ được làm theo đúng hướng dẫn của giáo viên.' },
    { sec: 'Lĩnh vực của KHTN', lvl: 'NB', name: 'Câu 24', pts: 1, text: 'Khoa học tự nhiên gồm các lĩnh vực chủ yếu nào?', opts: o4('Vật lí, Hóa học, Lịch sử, Địa lí', 'Vật lí, Hóa học, Sinh học, Khoa học Trái Đất và Thiên văn học', 'Toán học, Vật lí, Hóa học, Tin học', 'Sinh học, Địa lí, Văn học, Nghệ thuật'), ans: 'B', why: 'Bốn lĩnh vực chủ yếu của khoa học tự nhiên là Vật lí, Hóa học, Sinh học và Khoa học Trái Đất — Thiên văn học.' },
    { sec: 'Vật thể và chất', lvl: 'NC', name: 'Câu 25', pts: 1, text: 'Một bạn nói: "Mọi vật thể đều được tạo nên từ chất." Nhận định này:', opts: o4('đúng, vì bất kì vật thể nào cũng do một hoặc nhiều chất tạo thành', 'sai, vì vật thể tự nhiên không được tạo nên từ chất', 'sai, vì chỉ vật thể nhân tạo mới được tạo nên từ chất', 'sai, vì chất và vật thể là hai thứ hoàn toàn tách rời nhau'), ans: 'A', why: 'Chất là thứ tạo nên vật thể. Cây tre (tự nhiên) tạo nên từ cellulose, nước…; chiếc cốc (nhân tạo) tạo nên từ thủy tinh. Một vật thể có thể do nhiều chất tạo thành, ví dụ chiếc xe đạp gồm sắt, cao su, nhựa.' },
    { sec: 'Dụng cụ đo', lvl: 'TH', name: 'Câu 26', pts: 1, text: 'Nhiệt kế y tế dùng để đo:', opts: o4('khối lượng cơ thể', 'chiều cao cơ thể', 'nhiệt độ cơ thể', 'huyết áp của cơ thể'), ans: 'C', why: 'Nhiệt kế y tế có thang đo khoảng 35 – 42 °C, đúng khoảng nhiệt độ của cơ thể người.' },
    { sec: 'An toàn thực hành', lvl: 'NB', name: 'Câu 27', pts: 1, text: 'Khi sử dụng đèn cồn, muốn tắt đèn ta phải:', opts: o4('thổi thật mạnh vào ngọn lửa', 'đổ nước vào trong đèn cồn', 'để yên cho đèn tự tắt dần', 'đậy nắp đèn lại'), ans: 'D', why: 'Đậy nắp làm ngọn lửa tắt do thiếu oxygen. Thổi có thể làm cồn bắn ra gây cháy lan; đổ nước làm hỏng đèn.' },
    { sec: 'Phương pháp tìm hiểu tự nhiên', lvl: 'NC', name: 'Câu 28', pts: 1, text: 'Bạn Nam đặt hai đĩa nước giống hệt nhau, một đĩa ngoài nắng, một đĩa trong bóng râm. Sau 2 giờ, đĩa ngoài nắng cạn nhiều hơn. Kết luận đúng là:', opts: o4('Nước chỉ bay hơi khi có ánh nắng mặt trời chiếu vào', 'Nhiệt độ càng cao thì nước bay hơi càng nhanh', 'Ánh sáng đã làm nước biến đổi thành một chất khác', 'Diện tích mặt thoáng là yếu tố quyết định tốc độ bay hơi'), ans: 'B', why: 'Hai đĩa chỉ khác nhau ở chỗ nắng — râm, tức khác nhau về nhiệt độ. Đĩa nóng hơn cạn nhanh hơn ⇒ nhiệt độ càng cao, bay hơi càng nhanh. A sai vì đĩa trong râm vẫn cạn bớt; D sai vì hai đĩa có mặt thoáng như nhau nên không kết luận được về yếu tố này.' },
    { sec: 'Khái niệm KHTN', lvl: 'NB', name: 'Câu 29', pts: 1, text: 'Hoạt động nào sau đây là hoạt động nghiên cứu khoa học?', opts: o4('Tìm hiểu vì sao lá cây có màu xanh', 'Trồng hoa để trang trí lớp học', 'Vẽ tranh về phong cảnh quê hương', 'Tập hát một bài hát mới'), ans: 'A', why: 'Nghiên cứu khoa học là hoạt động tìm hiểu, khám phá để trả lời một câu hỏi về thế giới tự nhiên. Ba hoạt động còn lại là lao động và nghệ thuật.' },
    { sec: 'Dụng cụ đo', lvl: 'TH', name: 'Câu 30', pts: 1, text: 'Trong các dụng cụ sau, dụng cụ nào dùng để đo thời gian?', opts: o4('Cân đồng hồ', 'Thước dây', 'Đồng hồ bấm giây', 'Nhiệt kế rượu'), ans: 'C', why: 'Đồng hồ bấm giây đo khoảng thời gian diễn ra một hiện tượng. Lưu ý "cân đồng hồ" là loại cân, dùng đo khối lượng chứ không đo thời gian.' },
  ],
},

/* ═══════════ ĐỀ 2 — DỤNG CỤ ĐO. ĐO CHIỀU DÀI, KHỐI LƯỢNG, THỜI GIAN ═══════════ */
{
  id: 10652, title: 'Đề 2 · Dụng cụ đo. Đo chiều dài, khối lượng, thời gian', time: 60,
  questions: [
    { sec: 'Đơn vị đo', lvl: 'TH', name: 'Câu 1', pts: 1, text: 'Đơn vị đo chiều dài hợp pháp của nước ta là:', opts: o4('mét (m)', 'inch', 'dặm', 'gam'), ans: 'A', why: 'Mét là đơn vị đo chiều dài trong hệ đơn vị đo lường hợp pháp của Việt Nam (hệ SI). Inch và dặm là đơn vị của Anh, Mĩ; gam là đơn vị khối lượng.' },
    { sec: 'Ghi kết quả đo', lvl: 'VD', name: 'Câu 2', pts: 1, text: 'Một thước có giới hạn đo 30 cm và độ chia nhỏ nhất 1 mm. Kết quả đo nào sau đây được ghi ĐÚNG?', opts: o4('12 cm', '12,25 cm', '12,5 cm', '12,50 cm'), ans: 'C', why: 'ĐCNN 1 mm = 0,1 cm nên kết quả phải ghi tới một chữ số thập phân (theo cm): 12,5 cm. Phương án A thiếu chữ số; B và D ghi tới 0,01 cm, vượt quá khả năng của thước.' },
    { sec: 'Dụng cụ đo', lvl: 'NB', name: 'Câu 3', pts: 1, text: 'Dụng cụ nào sau đây dùng để đo thời gian?', opts: o4('Cân đồng hồ', 'Thước cuộn', 'Bình chia độ', 'Đồng hồ bấm giây'), ans: 'D', why: 'Đồng hồ bấm giây đo thời gian. Cân đồng hồ đo khối lượng, thước cuộn đo chiều dài, bình chia độ đo thể tích.' },
    { sec: 'Đo thể tích vật rắn', lvl: 'NC', name: 'Câu 4', pts: 1, text: 'Bình chia độ chứa 40 mL nước. Thả chìm một viên sỏi vào thì mực nước lên 47 mL. Nếu thả thêm một viên sỏi giống hệt nữa thì mực nước sẽ là:', opts: o4('47 mL', '54 mL', '87 mL', '14 mL'), ans: 'B', why: 'Thể tích mỗi viên sỏi = 47 − 40 = 7 (mL). Thả thêm một viên giống hệt thì mực nước dâng thêm 7 mL nữa: 47 + 7 = 54 (mL).' },
    { sec: 'Giới hạn đo', lvl: 'TH', name: 'Câu 5', pts: 1, text: 'Giới hạn đo (GHĐ) của một thước là:', opts: o4('độ dài giữa hai vạch chia liên tiếp trên thước', 'độ dài nhỏ nhất mà thước có thể đo được', 'độ dài lớn nhất ghi trên thước', 'số vạch chia có trên toàn bộ thước'), ans: 'C', why: 'GHĐ là độ dài lớn nhất ghi trên thước — tức giá trị lớn nhất mà thước đo được trong một lần. Phương án A là định nghĩa của ĐCNN.' },
    { sec: 'Đơn vị đo', lvl: 'NB', name: 'Câu 6', pts: 1, text: 'Đơn vị đo khối lượng hợp pháp của nước ta là:', opts: o4('lít', 'kilôgam', 'mét', 'giây'), ans: 'B', why: 'Kilôgam (kg) là đơn vị đo khối lượng trong hệ SI. Lít đo thể tích, mét đo chiều dài, giây đo thời gian.' },
    { sec: 'Cách đo chiều dài', lvl: 'NC', name: 'Câu 7', pts: 1, text: 'Khi đọc kết quả đo chiều dài một vật, phải đặt mắt nhìn:', opts: o4('theo hướng vuông góc với cạnh thước tại đầu kia của vật', 'theo hướng xiên từ phía bên trái của vật cần đo', 'theo hướng xiên từ phía bên phải của vật cần đo', 'theo hướng song song với mặt thước đang sử dụng'), ans: 'A', why: 'Nhìn xiên sẽ gây sai số do hiện tượng thị sai: vạch chia và đầu vật không trùng nhau trong tầm nhìn. Phải nhìn vuông góc với mặt thước tại vị trí đầu vật.' },
    { sec: 'Đổi đơn vị', lvl: 'TH', name: 'Câu 8', pts: 1, text: 'Đổi 2,5 kg ra gam ta được:', opts: o4('25 g', '250 g', '25 000 g', '2 500 g'), ans: 'D', why: '1 kg = 1 000 g nên 2,5 kg = 2,5 × 1 000 = 2 500 (g).' },
    { sec: 'Ghi kết quả đo', lvl: 'NC', name: 'Câu 9', pts: 1, text: 'Một bạn dùng cân có ĐCNN 0,1 g để cân một vật và ghi kết quả 15,25 g. Kết quả này:', opts: o4('đúng, vì đã ghi tới hai chữ số sau dấu phẩy', 'đúng, vì chiếc cân đó rất chính xác', 'sai, vì phải ghi tới 0,1 g, tức 15,2 g hoặc 15,3 g', 'sai, vì khối lượng bắt buộc phải là một số nguyên'), ans: 'C', why: 'Kết quả đo không được ghi chính xác hơn ĐCNN của dụng cụ. Cân chỉ đọc được tới 0,1 g nên chữ số hàng phần trăm là vô nghĩa.' },
    { sec: 'Dụng cụ đo', lvl: 'NB', name: 'Câu 10', pts: 1, text: 'Để đo thể tích của chất lỏng, ta dùng:', opts: o4('bình chia độ', 'thước kẻ', 'lực kế', 'nhiệt kế'), ans: 'A', why: 'Bình chia độ (hoặc ống đong, cốc chia độ) có vạch chia thể tích nên dùng để đo thể tích chất lỏng.' },
    { sec: 'Chọn dụng cụ đo', lvl: 'NC', name: 'Câu 11', pts: 1, text: 'Muốn đo chiều dài một sân bóng khoảng 100 m, nên chọn dụng cụ nào?', opts: o4('Thước kẻ 20 cm, đo nhiều lần rồi cộng lại', 'Thước cuộn có giới hạn đo 50 m', 'Thước dây may mặc dài 1,5 m', 'Thước thẳng học sinh dài 30 cm'), ans: 'B', why: 'Phải chọn dụng cụ có GHĐ phù hợp để số lần đo ít, sai số nhỏ. Thước cuộn 50 m chỉ cần đo 2 lần; dùng thước 20 cm hay 30 cm phải đo hàng trăm lần, sai số cộng dồn rất lớn.' },
    { sec: 'Độ chia nhỏ nhất', lvl: 'TH', name: 'Câu 12', pts: 1, text: 'Độ chia nhỏ nhất (ĐCNN) của thước là:', opts: o4('độ dài lớn nhất ghi trên thước', 'chiều dài của toàn bộ chiếc thước', 'số vạch chia có trên thước', 'độ dài giữa hai vạch chia liên tiếp'), ans: 'D', why: 'ĐCNN là khoảng cách giữa hai vạch chia liên tiếp — nó quyết định mức độ chính xác khi ghi kết quả đo.' },
    { sec: 'Đổi đơn vị', lvl: 'VD', name: 'Câu 13', pts: 1, text: 'Một bạn cân một túi gạo được 5 kg 200 g. Khối lượng túi gạo tính theo kilôgam là:', opts: o4('52 kg', '5,02 kg', '5,2 kg', '5 200 kg'), ans: 'C', why: '200 g = 0,2 kg nên 5 kg 200 g = 5 + 0,2 = 5,2 (kg).' },
    { sec: 'Đổi đơn vị', lvl: 'NB', name: 'Câu 14', pts: 1, text: '1 giờ bằng bao nhiêu giây?', opts: o4('3 600 s', '60 s', '100 s', '600 s'), ans: 'A', why: '1 giờ = 60 phút, mỗi phút = 60 giây nên 1 giờ = 60 × 60 = 3 600 (s).' },
    { sec: 'Đo thể tích vật rắn', lvl: 'NC', name: 'Câu 15', pts: 1, text: 'Để đo thể tích của một hòn đá to không bỏ lọt bình chia độ, ta cần dùng thêm:', opts: o4('một chiếc cân đồng hồ', 'bình tràn', 'một chiếc thước dây', 'một chiếc nhiệt kế'), ans: 'B', why: 'Thả hòn đá vào bình tràn đã đầy nước, hứng lấy phần nước tràn ra rồi đo bằng bình chia độ. Thể tích nước tràn ra chính bằng thể tích hòn đá.' },
    { sec: 'Đổi đơn vị', lvl: 'TH', name: 'Câu 16', pts: 1, text: 'Đổi 1,5 giờ ra phút ta được:', opts: o4('15 phút', '105 phút', '150 phút', '90 phút'), ans: 'D', why: '1,5 giờ = 1 giờ + 0,5 giờ = 60 + 30 = 90 (phút).' },
    { sec: 'Dụng cụ đo', lvl: 'NB', name: 'Câu 17', pts: 1, text: 'Dụng cụ nào sau đây dùng để đo nhiệt độ?', opts: o4('Nhiệt kế', 'Cân', 'Thước', 'Bình chia độ'), ans: 'A', why: 'Nhiệt kế là dụng cụ đo nhiệt độ, hoạt động dựa trên sự dãn nở vì nhiệt.' },
    { sec: 'Đo khối lượng', lvl: 'NC', name: 'Câu 18', pts: 1, text: 'Dùng cân Rô-bec-van, đặt vật lên đĩa trái và các quả cân lên đĩa phải. Khi đòn cân thăng bằng, khối lượng của vật bằng:', opts: o4('tổng khối lượng các quả cân cộng với khối lượng của đĩa cân', 'hiệu khối lượng các quả cân và khối lượng của đĩa cân', 'tổng khối lượng của các quả cân đặt trên đĩa bên phải', 'một nửa tổng khối lượng của các quả cân đã sử dụng'), ans: 'C', why: 'Hai đĩa cân giống hệt nhau nên khối lượng của chúng tự triệt tiêu. Khi cân thăng bằng, khối lượng vật đúng bằng tổng khối lượng các quả cân.' },
    { sec: 'Cách đo chiều dài', lvl: 'TH', name: 'Câu 19', pts: 1, text: 'Khi đo chiều dài một vật, cần đặt thước:', opts: o4('song song nhưng cách xa vật để nhìn rõ vạch chia', 'dọc theo vật cần đo, một đầu vật ngang bằng vạch số 0', 'vuông góc với vật cần đo để dễ quan sát', 'chéo góc với vật để đo được cả phần cong'), ans: 'B', why: 'Thước phải đặt dọc theo vật và một đầu vật trùng với vạch số 0, khi đó số đọc ở đầu kia chính là chiều dài vật.' },
    { sec: 'Đơn vị đo', lvl: 'NB', name: 'Câu 20', pts: 1, text: 'Đơn vị đo thời gian trong hệ SI là:', opts: o4('giờ', 'phút', 'ngày', 'giây'), ans: 'D', why: 'Giây (s) là đơn vị đo thời gian trong hệ SI. Giờ, phút, ngày là các đơn vị dẫn xuất dùng trong đời sống.' },
    { sec: 'Ghi kết quả đo', lvl: 'NC', name: 'Câu 21', pts: 1, text: 'Một bạn đo chiều dài quyển sách 4 lần được: 20,1 cm; 20,2 cm; 20,1 cm; 20,0 cm. Chiều dài trung bình của quyển sách là:', opts: o4('20,0 cm', '20,2 cm', '20,1 cm', '80,4 cm'), ans: 'C', why: 'Chiều dài trung bình = (20,1 + 20,2 + 20,1 + 20,0) : 4 = 80,4 : 4 = 20,1 (cm). Phương án D là tổng bốn lần đo, chưa chia cho 4.' },
    { sec: 'Đo khối lượng', lvl: 'TH', name: 'Câu 22', pts: 1, text: 'Trước khi đo khối lượng bằng cân đồng hồ, ta cần:', opts: o4('điều chỉnh kim cân về đúng vạch số 0', 'đặt vật lên đĩa cân rồi mới chỉnh kim', 'lắc mạnh cân cho kim dao động qua lại', 'đặt cân ở nơi có gió thổi mạnh'), ans: 'A', why: 'Nếu kim không ở vạch 0 khi chưa cân thì mọi kết quả đều bị lệch đi một lượng cố định. Vì vậy phải hiệu chỉnh kim về 0 trước.' },
    { sec: 'Chọn dụng cụ đo', lvl: 'NB', name: 'Câu 23', pts: 1, text: 'Để đo đường kính trong của một chiếc cốc, dụng cụ phù hợp là:', opts: o4('Cân đồng hồ', 'Nhiệt kế', 'Đồng hồ bấm giây', 'Thước kẻ'), ans: 'D', why: 'Đường kính là một độ dài nên phải dùng dụng cụ đo chiều dài, ở đây là thước kẻ.' },
    { sec: 'Đo thể tích vật rắn', lvl: 'VD', name: 'Câu 24', pts: 1, text: 'Một bình chia độ chứa 55 mL nước. Thả chìm hoàn toàn một vật rắn vào bình thì mực nước dâng lên 78 mL. Thể tích của vật rắn là:', opts: o4('78 cm³', '23 cm³', '133 cm³', '55 cm³'), ans: 'B', why: 'Thể tích vật = thể tích nước dâng thêm = 78 − 55 = 23 (mL). Vì 1 mL = 1 cm³ nên thể tích vật là 23 cm³.' },
    { sec: 'Đo thể tích chất lỏng', lvl: 'NC', name: 'Câu 25', pts: 1, text: 'Khi đọc kết quả đo thể tích chất lỏng trong bình chia độ, mắt phải nhìn:', opts: o4('từ trên xuống mặt thoáng của chất lỏng', 'từ dưới lên mặt thoáng của chất lỏng', 'ngang bằng với mặt thoáng của chất lỏng', 'chếch một góc 45° so với mặt thoáng'), ans: 'C', why: 'Nhìn từ trên xuống hay từ dưới lên đều gây sai số thị sai, khiến đọc thừa hoặc thiếu. Phải đặt mắt ngang bằng với mặt thoáng chất lỏng.' },
    { sec: 'Đổi đơn vị', lvl: 'TH', name: 'Câu 26', pts: 1, text: 'Đổi 750 g ra kilôgam ta được:', opts: o4('0,75 kg', '7,5 kg', '75 kg', '0,075 kg'), ans: 'A', why: '1 000 g = 1 kg nên 750 g = 750 : 1 000 = 0,75 (kg).' },
    { sec: 'Sai số phép đo', lvl: 'NC', name: 'Câu 27', pts: 1, text: 'Vì sao khi đo phải thực hiện phép đo nhiều lần rồi lấy giá trị trung bình?', opts: o4('Để kéo dài thời gian làm thí nghiệm cho kĩ lưỡng', 'Để giảm bớt sai số do người đo và dụng cụ gây ra', 'Để dụng cụ đo lâu bị hỏng hơn khi dùng nhiều', 'Để kết quả cuối cùng luôn là một số nguyên đẹp'), ans: 'B', why: 'Mỗi lần đo đều có sai số ngẫu nhiên, khi thì thừa khi thì thiếu. Lấy trung bình của nhiều lần đo, các sai số này bù trừ nhau nên kết quả gần giá trị thật hơn.' },
    { sec: 'Đổi đơn vị', lvl: 'NB', name: 'Câu 28', pts: 1, text: '1 km bằng bao nhiêu mét?', opts: o4('10 m', '100 m', '10 000 m', '1 000 m'), ans: 'D', why: 'Tiền tố "ki-lô" nghĩa là một nghìn nên 1 km = 1 000 m.' },
    { sec: 'Chọn dụng cụ đo', lvl: 'TH', name: 'Câu 29', pts: 1, text: 'Một thước có GHĐ 20 cm và ĐCNN 1 mm. Thước này KHÔNG thể dùng để đo:', opts: o4('chiều dài chiếc bút chì', 'chiều rộng quyển vở', 'chiều dài chiếc bảng lớp học', 'bề dày của quyển sách'), ans: 'C', why: 'Bảng lớp dài vài mét, vượt xa GHĐ 20 cm của thước. Ba vật còn lại đều có kích thước nhỏ hơn 20 cm nên đo được trong một lần.' },
    { sec: 'Dụng cụ đo', lvl: 'NB', name: 'Câu 30', pts: 1, text: 'Dụng cụ nào sau đây dùng để đo lực?', opts: o4('Lực kế', 'Cân', 'Thước', 'Nhiệt kế'), ans: 'A', why: 'Lực kế đo độ lớn của lực, hoạt động dựa trên độ dãn của lò xo. Cân đo khối lượng, không phải lực.' },
  ],
},

/* ═══════════ ĐỀ 3 — ĐO NHIỆT ĐỘ. THANG NHIỆT ĐỘ ═══════════ */
{
  id: 10653, title: 'Đề 3 · Đo nhiệt độ. Thang nhiệt độ', time: 60,
  questions: [
    { sec: 'Nhiệt độ trong đời sống', lvl: 'VD', name: 'Câu 1', pts: 1, text: 'Nhiệt độ cơ thể của người bình thường vào khoảng:', opts: o4('27 °C', '37 °C', '47 °C', '100 °C'), ans: 'B', why: 'Thân nhiệt người khỏe mạnh vào khoảng 37 °C. Vượt quá 37,5 °C thường được coi là sốt.' },
    { sec: 'Dụng cụ đo nhiệt độ', lvl: 'NB', name: 'Câu 2', pts: 1, text: 'Dụng cụ dùng để đo nhiệt độ là:', opts: o4('nhiệt kế', 'lực kế', 'ampe kế', 'tốc kế'), ans: 'A', why: 'Nhiệt kế đo nhiệt độ. Lực kế đo lực, ampe kế đo cường độ dòng điện, tốc kế đo tốc độ.' },
    { sec: 'Thang nhiệt độ', lvl: 'TH', name: 'Câu 3', pts: 1, text: 'Ở điều kiện thường, nước đá nóng chảy ở nhiệt độ:', opts: o4('100 °C', '−10 °C', '0 °C', '37 °C'), ans: 'C', why: 'Nước đá bắt đầu nóng chảy ở 0 °C. Đây cũng là mốc dưới của thang nhiệt độ Celsius.' },
    { sec: 'Giới hạn đo của nhiệt kế', lvl: 'NC', name: 'Câu 4', pts: 1, text: 'Vì sao không dùng nhiệt kế y tế để đo nhiệt độ của nước đang sôi?', opts: o4('Vì nhiệt kế y tế quá ngắn, không chạm được tới đáy nồi', 'Vì nước sôi làm nhiệt kế y tế bị bẩn, rất khó lau chùi', 'Vì nhiệt kế y tế chỉ dùng được cho cơ thể của sinh vật sống', 'Vì giới hạn đo của nhiệt kế y tế chỉ khoảng 35 – 42 °C, thấp hơn 100 °C'), ans: 'D', why: 'Nước sôi ở 100 °C, vượt xa GHĐ của nhiệt kế y tế. Dùng sai sẽ làm cột thủy ngân dâng quá vạch cuối và làm vỡ nhiệt kế.' },
    { sec: 'Đơn vị nhiệt độ', lvl: 'NB', name: 'Câu 5', pts: 1, text: 'Đơn vị đo nhiệt độ thường dùng ở nước ta là:', opts: o4('độ C (°C)', 'độ F (°F)', 'kelvin (K)', 'niutơn (N)'), ans: 'A', why: 'Việt Nam dùng thang Celsius, đơn vị là độ C. Độ F dùng ở Mĩ, kelvin dùng trong khoa học, niutơn là đơn vị đo lực.' },
    { sec: 'Nguyên tắc hoạt động', lvl: 'TH', name: 'Câu 6', pts: 1, text: 'Nhiệt kế hoạt động dựa trên hiện tượng nào?', opts: o4('sự nở vì nhiệt của chất rắn khi bị nén mạnh', 'sự bay hơi của chất lỏng khi gặp lạnh', 'sự dẫn điện của kim loại khi nóng lên', 'sự dãn nở vì nhiệt của chất lỏng hoặc kim loại'), ans: 'D', why: 'Khi nóng lên, chất lỏng (thủy ngân, rượu) hoặc thanh kim loại trong nhiệt kế dãn nở, làm cột chất lỏng dâng lên hoặc kim quay — nhờ đó chỉ ra nhiệt độ.' },
    { sec: 'Thang nhiệt độ', lvl: 'NB', name: 'Câu 7', pts: 1, text: 'Ở điều kiện thường, nước sôi ở nhiệt độ:', opts: o4('0 °C', '100 °C', '37 °C', '50 °C'), ans: 'B', why: 'Nước sôi ở 100 °C — đây là mốc trên của thang nhiệt độ Celsius.' },
    { sec: 'Giới hạn đo của nhiệt kế', lvl: 'NC', name: 'Câu 8', pts: 1, text: 'Một nhiệt kế có GHĐ từ −20 °C đến 50 °C và ĐCNN 1 °C. Nhiệt kế này dùng được để đo:', opts: o4('nhiệt độ của nước đang sôi trong ấm', 'nhiệt độ bên trong lò nung gạch', 'nhiệt độ không khí ngoài trời', 'nhiệt độ của sắt đang nóng chảy'), ans: 'C', why: 'Nhiệt độ không khí ngoài trời thường nằm trong khoảng −20 °C đến 50 °C nên phù hợp. Nước sôi (100 °C), lò nung và sắt nóng chảy (hàng trăm tới hàng nghìn độ) đều vượt GHĐ.' },
    { sec: 'Cách đo nhiệt độ', lvl: 'TH', name: 'Câu 9', pts: 1, text: 'Trước khi đo nhiệt độ cơ thể bằng nhiệt kế y tế thủy ngân, ta cần:', opts: o4('vẩy mạnh cho thủy ngân tụt xuống dưới vạch 35 °C', 'hơ nhiệt kế qua lửa cho nóng lên trước', 'ngâm nhiệt kế vào nước đá cho thật lạnh', 'lắc nhiệt kế cho cột chất lỏng dâng lên cao'), ans: 'A', why: 'Nhiệt kế y tế có chỗ thắt giữ cột thủy ngân không tụt xuống sau khi đo, nên phải vẩy mạnh đưa thủy ngân về dưới 35 °C trước khi đo lần mới.' },
    { sec: 'Bài toán nhiệt độ', lvl: 'NC', name: 'Câu 10', pts: 1, text: 'Buổi sáng nhiệt độ ngoài trời là 18 °C, đến trưa tăng thêm 12 °C, đến tối lại giảm 9 °C so với buổi trưa. Nhiệt độ buổi tối là:', opts: o4('30 °C', '21 °C', '15 °C', '39 °C'), ans: 'B', why: 'Nhiệt độ buổi trưa: 18 + 12 = 30 (°C). Nhiệt độ buổi tối: 30 − 9 = 21 (°C). Phương án A là dừng lại ở buổi trưa.' },
    { sec: 'Khái niệm nhiệt độ', lvl: 'NB', name: 'Câu 11', pts: 1, text: 'Nhiệt độ cho biết điều gì về một vật?', opts: o4('khối lượng của vật', 'thể tích của vật', 'chiều dài của vật', 'mức độ nóng, lạnh của vật'), ans: 'D', why: 'Nhiệt độ là số đo mức độ nóng hay lạnh của vật. Vật càng nóng thì nhiệt độ càng cao.' },
    { sec: 'Cách đo nhiệt độ', lvl: 'VD', name: 'Câu 12', pts: 1, text: 'Để đo nhiệt độ của nước trong cốc, cần đặt bầu nhiệt kế:', opts: o4('chạm sát vào đáy cốc', 'chỉ chạm vào mặt thoáng của nước', 'ngập trong nước, không chạm đáy và thành cốc', 'treo lơ lửng phía trên mặt nước'), ans: 'C', why: 'Bầu nhiệt kế phải ngập hẳn trong nước để nhận đúng nhiệt độ của nước. Nếu chạm đáy hoặc thành cốc, nhiệt kế sẽ đo lẫn nhiệt độ của cốc chứ không phải của nước.' },
    { sec: 'Thang nhiệt độ', lvl: 'TH', name: 'Câu 13', pts: 1, text: 'Thang nhiệt độ Celsius lấy mốc 0 °C ứng với:', opts: o4('nhiệt độ của nước đá đang tan', 'nhiệt độ của nước đang sôi', 'nhiệt độ của cơ thể người', 'nhiệt độ thấp nhất có thể có'), ans: 'A', why: 'Thang Celsius quy ước 0 °C là nhiệt độ nước đá đang tan và 100 °C là nhiệt độ nước đang sôi (ở áp suất thường), rồi chia đều khoảng giữa thành 100 phần.' },
    { sec: 'Cách đo nhiệt độ', lvl: 'NC', name: 'Câu 14', pts: 1, text: 'Vì sao khi đo nhiệt độ chất lỏng, phải để bầu nhiệt kế trong chất lỏng một lúc rồi mới đọc kết quả?', opts: o4('Để chất lỏng kịp bay hơi bớt đi một phần', 'Để nhiệt độ của nhiệt kế kịp bằng nhiệt độ chất lỏng', 'Để cột chất lỏng trong nhiệt kế kịp lắng xuống', 'Để người đo có thời gian chuẩn bị giấy bút ghi chép'), ans: 'B', why: 'Ban đầu nhiệt kế có nhiệt độ khác chất lỏng. Cần thời gian để nhiệt truyền qua lại cho tới khi hai bên cùng nhiệt độ; đọc quá sớm sẽ cho kết quả sai.' },
    { sec: 'Các loại nhiệt kế', lvl: 'NB', name: 'Câu 15', pts: 1, text: 'Loại nhiệt kế nào thường dùng để đo nhiệt độ cơ thể người?', opts: o4('Nhiệt kế rượu', 'Nhiệt kế kim loại', 'Nhiệt kế y tế', 'Nhiệt kế phòng thí nghiệm'), ans: 'C', why: 'Nhiệt kế y tế có thang đo hẹp (khoảng 35 – 42 °C) và độ chia nhỏ, phù hợp để đo thân nhiệt chính xác.' },
    { sec: 'Sự chuyển thể', lvl: 'NC', name: 'Câu 16', pts: 1, text: 'Ở nhiệt độ nào nước có thể tồn tại đồng thời ở cả thể rắn và thể lỏng?', opts: o4('100 °C', '37 °C', '−10 °C', '0 °C'), ans: 'D', why: 'Tại 0 °C, nước đá đang tan: một phần đã hóa lỏng còn một phần vẫn ở thể rắn. Trong suốt quá trình nóng chảy, nhiệt độ giữ nguyên ở 0 °C.' },
    { sec: 'Nhiệt độ trong đời sống', lvl: 'TH', name: 'Câu 17', pts: 1, text: 'Nhiệt độ của một phòng học thông thường vào khoảng:', opts: o4('5 °C', '25 °C', '50 °C', '80 °C'), ans: 'B', why: 'Nhiệt độ dễ chịu trong phòng ở nước ta vào khoảng 25 °C. 5 °C là rất lạnh, còn 50 °C và 80 °C thì con người không thể sinh hoạt bình thường.' },
    { sec: 'Nguyên tắc hoạt động', lvl: 'NB', name: 'Câu 18', pts: 1, text: 'Khi nhiệt độ tăng, chất lỏng trong nhiệt kế sẽ:', opts: o4('dãn nở ra và dâng lên', 'co lại và tụt xuống', 'bay hơi hết ra ngoài', 'đông đặc lại thành thể rắn'), ans: 'A', why: 'Chất lỏng nở ra khi nóng lên, thể tích tăng nên cột chất lỏng trong ống mao dẫn dâng lên, chỉ mức nhiệt độ cao hơn.' },
    { sec: 'Cách đo nhiệt độ', lvl: 'NC', name: 'Câu 19', pts: 1, text: 'Một bạn đặt nhiệt kế ra giữa trời nắng để đo nhiệt độ không khí, đọc được 45 °C trong khi bản tin thời tiết báo 33 °C. Nguyên nhân của sai lệch là:', opts: o4('Nhiệt kế của bạn đó đã bị hỏng hoàn toàn', 'Bản tin thời tiết hôm đó đã đưa tin sai', 'Không khí ngoài trời lạnh hơn trong bóng râm', 'Nhiệt kế bị Mặt Trời chiếu trực tiếp nên nóng hơn không khí'), ans: 'D', why: 'Khi bị nắng chiếu thẳng, nhiệt kế hấp thụ năng lượng ánh sáng nên nóng hơn không khí xung quanh. Muốn đo đúng nhiệt độ không khí phải đặt nhiệt kế trong bóng râm, nơi thoáng gió.' },
    { sec: 'Các loại nhiệt kế', lvl: 'TH', name: 'Câu 20', pts: 1, text: 'Nhiệt kế rượu thường được dùng để đo nhiệt độ:', opts: o4('của lò nung ở nhiệt độ rất cao', 'của cơ thể người khi bị sốt', 'của khí quyển, kể cả khi trời rất lạnh', 'của kim loại đang nóng chảy'), ans: 'C', why: 'Rượu đông đặc ở nhiệt độ rất thấp (khoảng −117 °C) nên nhiệt kế rượu đo được cả những vùng rất lạnh — điều mà nhiệt kế thủy ngân không làm được.' },
    { sec: 'Bài toán nhiệt độ', lvl: 'NC', name: 'Câu 21', pts: 1, text: 'Nhiệt độ ở Sa Pa buổi sáng là −2 °C, buổi trưa là 9 °C. Nhiệt độ buổi trưa cao hơn buổi sáng bao nhiêu độ?', opts: o4('7 °C', '11 °C', '−11 °C', '18 °C'), ans: 'B', why: 'Chênh lệch = 9 − (−2) = 9 + 2 = 11 (°C). Phương án A là lỗi tính 9 − 2, quên dấu âm.' },
    { sec: 'So sánh nhiệt độ', lvl: 'NB', name: 'Câu 22', pts: 1, text: 'Vật nào sau đây có nhiệt độ cao nhất?', opts: o4('Cốc nước đá', 'Không khí trong phòng lạnh', 'Nước máy chứa trong bể', 'Nước đang sôi trong ấm'), ans: 'D', why: 'Nước đang sôi có nhiệt độ 100 °C — cao hơn hẳn nước đá (0 °C), không khí phòng lạnh và nước máy (khoảng 25 – 30 °C).' },
    { sec: 'Chọn nhiệt kế', lvl: 'VD', name: 'Câu 23', pts: 1, text: 'Muốn đo nhiệt độ của một lò nung khoảng 800 °C, ta cần dùng:', opts: o4('nhiệt kế kim loại có giới hạn đo phù hợp', 'nhiệt kế y tế thủy ngân', 'nhiệt kế rượu thông thường', 'nhiệt kế điện tử đo trán'), ans: 'A', why: 'Nhiệt độ 800 °C vượt xa GHĐ của nhiệt kế y tế, nhiệt kế rượu và nhiệt kế đo trán (rượu còn sôi ở khoảng 78 °C). Phải dùng nhiệt kế kim loại chuyên dụng cho nhiệt độ cao.' },
    { sec: 'Sự chuyển thể', lvl: 'TH', name: 'Câu 24', pts: 1, text: 'Khi nhiệt độ hạ xuống dưới 0 °C thì nước sẽ:', opts: o4('sôi lên', 'bay hơi hết', 'đông đặc', 'nóng chảy'), ans: 'C', why: 'Dưới 0 °C, nước chuyển từ thể lỏng sang thể rắn — đó là sự đông đặc. Nóng chảy là quá trình ngược lại.' },
    { sec: 'Suy luận về nhiệt độ', lvl: 'NC', name: 'Câu 25', pts: 1, text: 'Có hai cốc nước giống nhau, cốc A ở 20 °C và cốc B ở 60 °C. Nếu đổ hai cốc vào chung một bình thì nhiệt độ của nước trong bình sẽ:', opts: o4('bằng đúng 80 °C', 'nằm trong khoảng từ 20 °C đến 60 °C', 'thấp hơn 20 °C', 'cao hơn 60 °C'), ans: 'B', why: 'Nước nóng truyền nhiệt cho nước lạnh cho tới khi cả hai cùng một nhiệt độ. Nhiệt độ chung phải cao hơn cốc lạnh và thấp hơn cốc nóng. Phương án A sai vì nhiệt độ không cộng được như khối lượng.' },
    { sec: 'Giới hạn đo của nhiệt kế', lvl: 'NB', name: 'Câu 26', pts: 1, text: 'Giới hạn đo của nhiệt kế y tế thường là:', opts: o4('từ 35 °C đến 42 °C', 'từ 0 °C đến 100 °C', 'từ −20 °C đến 50 °C', 'từ 0 °C đến 500 °C'), ans: 'A', why: 'Thang đo của nhiệt kế y tế được thiết kế hẹp, bao trọn khoảng thân nhiệt người (kể cả khi sốt cao) để có độ chia nhỏ và đọc chính xác.' },
    { sec: 'Các loại nhiệt kế', lvl: 'TH', name: 'Câu 27', pts: 1, text: 'Vì sao không dùng nhiệt kế thủy ngân để đo nhiệt độ ở vùng cực lạnh dưới −40 °C?', opts: o4('Vì thủy ngân sẽ bay hơi hết ở nhiệt độ đó', 'Vì thủy ngân nở ra quá nhanh khi gặp lạnh', 'Vì thủy ngân đông đặc ở khoảng −39 °C nên không còn dãn nở được', 'Vì nhiệt kế thủy ngân chỉ dùng được cho cơ thể người'), ans: 'C', why: 'Thủy ngân đông đặc ở khoảng −39 °C. Khi đã hóa rắn, nó không còn dãn nở theo nhiệt độ nữa nên nhiệt kế mất tác dụng. Ở vùng rất lạnh phải dùng nhiệt kế rượu.' },
    { sec: 'Đọc bảng số liệu', lvl: 'NC', name: 'Câu 28', pts: 1, text: 'Bảng ghi nhiệt độ một ngày ở Hà Nội: 6 giờ — 22 °C; 12 giờ — 33 °C; 18 giờ — 29 °C; 24 giờ — 24 °C. Chênh lệch giữa nhiệt độ cao nhất và thấp nhất trong ngày là:', opts: o4('5 °C', '9 °C', '7 °C', '11 °C'), ans: 'D', why: 'Nhiệt độ cao nhất là 33 °C (lúc 12 giờ), thấp nhất là 22 °C (lúc 6 giờ). Chênh lệch = 33 − 22 = 11 (°C).' },
    { sec: 'Các loại nhiệt kế', lvl: 'NB', name: 'Câu 29', pts: 1, text: 'Nhiệt kế điện tử có ưu điểm nào sau đây?', opts: o4('Đọc kết quả nhanh và không chứa thủy ngân độc hại', 'Đo được nhiệt độ cao tới hàng nghìn độ', 'Không cần nguồn điện vẫn hoạt động được', 'Giá thành rẻ hơn tất cả các loại nhiệt kế khác'), ans: 'A', why: 'Nhiệt kế điện tử cho kết quả sau vài giây, hiển thị số rõ ràng và an toàn vì không dùng thủy ngân — nhưng vẫn cần pin để hoạt động.' },
    { sec: 'Cách đo nhiệt độ', lvl: 'TH', name: 'Câu 30', pts: 1, text: 'Khi đo nhiệt độ không khí trong phòng, cần đặt nhiệt kế ở đâu?', opts: o4('sát ngay vào bóng đèn đang bật sáng', 'nơi thoáng, tránh ánh nắng và các nguồn nhiệt', 'ngay cạnh cửa sổ có gió lùa thật mạnh', 'áp sát vào bức tường phía ngoài của nhà'), ans: 'B', why: 'Đặt gần bóng đèn, tường bị nắng hay chỗ gió lùa mạnh đều làm nhiệt kế chịu ảnh hưởng riêng, không phản ánh đúng nhiệt độ chung của không khí trong phòng.' },
  ],
},

];

SUBJECTS.push({
  id: 'khtn6', name: 'KHTN', short: 'KHTN 6', icon: '🔬', grade: 6,
  exams: KHTN6_EXAMS, ready: true,
  heroTitle: 'Khoa học tự nhiên lớp 6 — chất, tế bào, thế giới sống, lực và năng lượng',
  heroMeta: '📚 ' + KHTN6_EXAMS.length + '/50 đề &nbsp;•&nbsp; 30 câu mỗi đề &nbsp;•&nbsp; ⏱ 60 phút &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
