// TIN HỌC & CÔNG NGHỆ — LỚP 4 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// Hai mạch nội dung (đặt qua `sec`):
//   TIN HỌC (Đề 1–6):
//     - Phần cứng & phần mềm: phân biệt thiết bị và chương trình
//     - Tổ chức thông tin: thư mục hình cây, đường dẫn, sao chép/di chuyển tệp
//     - Gõ bàn phím đúng, soạn thảo văn bản đơn giản (định dạng chữ)
//     - Thông tin đáng tin cậy trên Internet & kĩ năng tìm kiếm
//     - Sơ đồ hình cây / sơ đồ tư duy
//     - Đạo đức, văn hoá & bản quyền khi dùng máy tính
//   CÔNG NGHỆ (Đề 7–10):
//     - Lợi ích của hoa & cây cảnh, chăm sóc cây
//     - Gieo trồng & chăm sóc cây; vật liệu & dụng cụ
//     - Lắp ghép mô hình kĩ thuật đơn giản
//     - Đồ dùng điện trong gia đình & an toàn điện; ý tưởng, làm sản phẩm thủ công

const TINCN4_EXAMS = [

/* ═══════════ ĐỀ 1 — PHẦN CỨNG VÀ PHẦN MỀM ═══════════ */
{
  id: 9311, title: 'Đề 1 · Phần cứng và phần mềm', time: 20,
  questions: [
    { sec: 'Phần cứng & phần mềm', name: 'Câu 1', pts: 1,
      text: 'Phần cứng của máy tính là gì?',
      opts: o4('Các bộ phận mà ta cầm, sờ được như màn hình, bàn phím', 'Các chương trình chạy trong máy', 'Các trang web trên Internet', 'Các tệp văn bản'), ans: 'A',
      why: 'Phần cứng là những bộ phận vật lí của máy tính mà ta nhìn thấy, sờ được: màn hình, bàn phím, chuột, thân máy.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 2', pts: 1,
      text: 'Phần mềm là gì?',
      opts: o4('Cái bàn kê máy tính', 'Sợi dây điện nối máy', 'Các chương trình giúp máy tính làm việc', 'Cái loa ngoài'), ans: 'C',
      why: 'Phần mềm là các chương trình cài trong máy, điều khiển máy làm việc (ví dụ trình duyệt, phần mềm vẽ, soạn thảo).' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 3', pts: 1,
      text: 'Thiết bị nào dùng để nhập chữ và số vào máy tính?',
      opts: o4('Màn hình', 'Bàn phím', 'Loa', 'Máy in'), ans: 'B',
      why: 'Bàn phím là thiết bị vào, dùng để gõ chữ và số vào máy tính.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 4', pts: 1,
      text: 'Thiết bị nào dùng để hiển thị hình ảnh, văn bản cho ta xem?',
      opts: o4('Bàn phím', 'Chuột', 'Ổ đĩa', 'Màn hình'), ans: 'D',
      why: 'Màn hình là thiết bị ra, hiển thị hình ảnh và văn bản để người dùng nhìn thấy.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 5', pts: 1,
      text: 'Chuột máy tính dùng để làm gì?',
      opts: o4('Gõ một đoạn văn dài', 'In tài liệu ra giấy', 'Trỏ, chọn và nháy vào các đối tượng trên màn hình', 'Phát ra âm thanh'), ans: 'C',
      why: 'Chuột dùng để di chuyển con trỏ, chọn và nháy vào biểu tượng, nút lệnh trên màn hình.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 6', pts: 1,
      text: 'Thiết bị nào là thiết bị đưa thông tin RA (in ra giấy)?',
      opts: o4('Máy in', 'Bàn phím', 'Chuột', 'Micro'), ans: 'A',
      why: 'Máy in là thiết bị ra, đưa văn bản, hình ảnh trong máy ra giấy.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 7', pts: 1,
      text: 'Trong các thứ sau, thứ nào là PHẦN MỀM?',
      opts: o4('Màn hình', 'Con chuột', 'Cái loa', 'Chương trình vẽ tranh trên máy'), ans: 'D',
      why: 'Chương trình vẽ tranh là phần mềm; màn hình, chuột, loa đều là phần cứng.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 8', pts: 1,
      text: 'Loa của máy tính có nhiệm vụ gì?',
      opts: o4('Nhập chữ vào máy', 'Phát ra âm thanh', 'Lưu trữ tệp', 'Trỏ chọn đối tượng'), ans: 'B',
      why: 'Loa là thiết bị ra, giúp máy tính phát ra âm thanh cho ta nghe.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 9', pts: 1,
      text: 'Muốn máy tính làm được nhiều việc (soạn thảo, vẽ, nghe nhạc) thì cần có gì?',
      opts: o4('Chỉ cần phần cứng', 'Cả phần cứng và phần mềm', 'Chỉ cần dây điện', 'Chỉ cần màn hình'), ans: 'B',
      why: 'Máy tính cần cả phần cứng và phần mềm mới hoạt động và làm được nhiều việc khác nhau.' },
    { sec: 'Phần cứng & phần mềm', name: 'Câu 10', pts: 1,
      text: 'Bộ phận nào được ví như "bộ não" xử lí của máy tính?',
      opts: o4('Cái loa', 'Sợi dây nguồn', 'Bàn di chuột', 'Bộ xử lí (nằm trong thân máy)'), ans: 'D',
      why: 'Bộ xử lí bên trong thân máy là nơi xử lí thông tin, được ví như bộ não của máy tính.' },
  ],
},

/* ═══════════ ĐỀ 2 — THƯ MỤC, ĐƯỜNG DẪN VÀ TỆP ═══════════ */
{
  id: 9312, title: 'Đề 2 · Thư mục, đường dẫn và tệp', time: 20,
  questions: [
    { sec: 'Tổ chức thông tin', name: 'Câu 1', pts: 1,
      text: 'Thư mục dùng để làm gì trong máy tính?',
      opts: o4('Để chứa và sắp xếp các tệp, thư mục con', 'Để phát nhạc', 'Để in tài liệu', 'Để lau màn hình'), ans: 'A',
      why: 'Thư mục giống như ngăn tủ, dùng để chứa và sắp xếp các tệp và thư mục con cho gọn gàng.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 2', pts: 1,
      text: 'Các thư mục lồng nhau (thư mục trong thư mục) tạo thành cấu trúc gì?',
      opts: o4('Cấu trúc hình tròn', 'Cấu trúc hình vuông', 'Cấu trúc hình cây', 'Không có cấu trúc'), ans: 'C',
      why: 'Thư mục lồng trong thư mục tạo thành cấu trúc hình cây: một thư mục gốc rồi phân nhánh dần.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 3', pts: 1,
      text: 'Tệp (tập tin) là gì?',
      opts: o4('Nơi lưu một nội dung như bài văn, bức tranh, bài hát', 'Một cái ngăn để chứa thư mục', 'Một bộ phận phần cứng', 'Một loại dây cáp'), ans: 'A',
      why: 'Tệp là nơi lưu một nội dung cụ thể trong máy: một bài văn, bức tranh, bản nhạc...' },
    { sec: 'Tổ chức thông tin', name: 'Câu 4', pts: 1,
      text: 'Đường dẫn của một tệp cho ta biết điều gì?',
      opts: o4('Màu sắc của tệp', 'Giá tiền của tệp', 'Vị trí (nằm trong thư mục nào) của tệp đó', 'Tên người tạo máy'), ans: 'C',
      why: 'Đường dẫn cho biết tệp nằm ở đâu, đi qua những thư mục nào để tới được tệp.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 5', pts: 1,
      text: 'Vì sao nên đặt tên thư mục, tệp rõ ràng, dễ hiểu?',
      opts: o4('Để trang trí cho đẹp', 'Để về sau tìm lại nhanh, không bị lẫn lộn', 'Để máy chạy nhanh hơn', 'Để tốn ít điện'), ans: 'B',
      why: 'Đặt tên rõ ràng giúp ta dễ tìm lại tệp, sắp xếp gọn gàng và không nhầm lẫn.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 6', pts: 1,
      text: 'Muốn giữ tệp ở chỗ cũ mà vẫn có thêm một bản giống hệt ở chỗ khác, em dùng thao tác nào?',
      opts: o4('Xoá', 'Đổi tên', 'Tắt máy', 'Sao chép (copy)'), ans: 'D',
      why: 'Sao chép tạo thêm một bản giống hệt ở nơi mới, còn bản gốc vẫn giữ nguyên chỗ cũ.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 7', pts: 1,
      text: 'Di chuyển (cut) một tệp sang thư mục khác nghĩa là gì?',
      opts: o4('Tệp có ở cả hai nơi', 'Tệp bị xoá hẳn', 'Tệp rời khỏi chỗ cũ, chuyển sang chỗ mới', 'Tệp được in ra giấy'), ans: 'C',
      why: 'Di chuyển đưa tệp từ nơi cũ sang nơi mới; chỗ cũ không còn tệp nữa.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 8', pts: 1,
      text: 'Thư mục nằm trong một thư mục khác được gọi là gì?',
      opts: o4('Thư mục con', 'Thư mục gốc', 'Tệp', 'Ổ đĩa'), ans: 'A',
      why: 'Thư mục nằm bên trong thư mục khác gọi là thư mục con.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 9', pts: 1,
      text: 'Để tổ chức bài học gọn gàng, em nên làm gì?',
      opts: o4('Để tất cả tệp lẫn lộn một chỗ', 'Xoá hết tệp cũ', 'Đặt tên tệp giống hệt nhau', 'Tạo các thư mục theo môn rồi cho tệp vào đúng thư mục'), ans: 'D',
      why: 'Tạo thư mục theo từng môn và cho tệp vào đúng thư mục giúp sắp xếp gọn, dễ tìm.' },
    { sec: 'Tổ chức thông tin', name: 'Câu 10', pts: 1,
      text: 'Khi lỡ xoá nhầm một tệp còn cần dùng, nơi đầu tiên nên tìm lại là đâu?',
      opts: o4('Máy in', 'Thùng rác (Recycle Bin)', 'Cái loa', 'Bàn phím'), ans: 'B',
      why: 'Tệp vừa xoá thường nằm trong Thùng rác; có thể khôi phục lại từ đó.' },
  ],
},

/* ═══════════ ĐỀ 3 — GÕ BÀN PHÍM VÀ SOẠN THẢO VĂN BẢN ═══════════ */
{
  id: 9313, title: 'Đề 3 · Gõ bàn phím và soạn thảo văn bản', time: 20,
  questions: [
    { sec: 'Soạn thảo văn bản', name: 'Câu 1', pts: 1,
      text: 'Khi gõ bàn phím đúng cách, hai tay em đặt thế nào?',
      opts: o4('Chỉ dùng một ngón trỏ', 'Đặt trên hàng phím cơ sở, gõ bằng cả mười ngón', 'Đặt tay lên màn hình', 'Gõ bằng khuỷu tay'), ans: 'B',
      why: 'Gõ đúng là đặt tay trên hàng phím cơ sở và dùng cả mười ngón, giúp gõ nhanh và đỡ mỏi.' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 2', pts: 1,
      text: 'Phím cách (Space) dùng để làm gì?',
      opts: o4('Xoá chữ', 'Viết hoa chữ', 'Lưu tệp', 'Tạo khoảng trống giữa các từ'), ans: 'D',
      why: 'Phím cách tạo khoảng trống để tách các từ trong câu.' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 3', pts: 1,
      text: 'Muốn xoá kí tự đứng ngay trước con trỏ, em dùng phím nào?',
      opts: o4('Backspace (phím xoá lùi)', 'Enter', 'Shift', 'Caps Lock'), ans: 'A',
      why: 'Phím Backspace xoá kí tự đứng ngay bên trái con trỏ soạn thảo.' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 4', pts: 1,
      text: 'Muốn xuống dòng, bắt đầu một dòng mới, em nhấn phím nào?',
      opts: o4('Space', 'Tab', 'Enter', 'Esc'), ans: 'C',
      why: 'Phím Enter dùng để xuống dòng, bắt đầu một dòng (đoạn) mới.' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 5', pts: 1,
      text: 'Giữ phím Shift rồi gõ một chữ cái sẽ được kết quả gì?',
      opts: o4('Chữ in hoa', 'Chữ bị xoá', 'Chữ nhỏ đi', 'Không có gì'), ans: 'A',
      why: 'Giữ Shift rồi gõ một chữ cái sẽ cho chữ in hoa của chữ đó.' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 6', pts: 1,
      text: 'Muốn làm chữ đậm, in nghiêng hay gạch chân, ta gọi đó là gì?',
      opts: o4('Xoá chữ', 'In tài liệu', 'Định dạng chữ', 'Tắt máy'), ans: 'C',
      why: 'Làm chữ đậm, nghiêng, gạch chân, đổi cỡ hay màu chữ được gọi là định dạng chữ (văn bản).' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 7', pts: 1,
      text: 'Trước khi định dạng (làm đậm, đổi màu) một đoạn chữ, em cần làm gì đầu tiên?',
      opts: o4('Tắt máy', 'Chọn (bôi đen) đoạn chữ đó', 'In ra giấy', 'Xoá đoạn chữ'), ans: 'B',
      why: 'Phải chọn (bôi đen) đoạn chữ cần định dạng trước, rồi mới chọn kiểu chữ đậm, nghiêng, màu...' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 8', pts: 1,
      text: 'Soạn xong một bài văn, muốn giữ lại để lần sau mở, em cần làm gì?',
      opts: o4('Tắt máy ngay', 'Rút dây điện', 'Kéo màn hình', 'Lưu (Save) tệp lại'), ans: 'D',
      why: 'Phải lưu (Save) tệp thì nội dung mới được giữ lại để lần sau mở ra dùng tiếp.' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 9', pts: 1,
      text: 'Khi bật đèn phím Caps Lock, em gõ chữ cái sẽ ra kiểu gì?',
      opts: o4('Toàn chữ thường', 'Toàn số', 'Toàn chữ in hoa', 'Không gõ được'), ans: 'C',
      why: 'Bật Caps Lock thì các chữ cái gõ ra đều là chữ in hoa cho tới khi tắt đi.' },
    { sec: 'Soạn thảo văn bản', name: 'Câu 10', pts: 1,
      text: 'Ngồi học và gõ máy đúng tư thế là thế nào?',
      opts: o4('Ngồi thẳng lưng, mắt cách màn hình vừa phải', 'Nằm dài gõ máy', 'Dí sát mắt vào màn hình', 'Ngồi vẹo người sang một bên'), ans: 'A',
      why: 'Ngồi thẳng lưng, giữ khoảng cách mắt tới màn hình hợp lí giúp bảo vệ mắt và cột sống.' },
  ],
},

/* ═══════════ ĐỀ 4 — THÔNG TIN ĐÁNG TIN CẬY VÀ TÌM KIẾM ═══════════ */
{
  id: 9314, title: 'Đề 4 · Thông tin đáng tin cậy và tìm kiếm', time: 20,
  questions: [
    { sec: 'Thông tin trên Internet', name: 'Câu 1', pts: 1,
      text: 'Internet giúp em làm được việc gì?',
      opts: o4('Nấu cơm hộ em', 'Quét nhà thay em', 'Giặt quần áo', 'Tìm kiếm thông tin, xem bài học, liên lạc từ xa'), ans: 'D',
      why: 'Internet giúp tìm kiếm thông tin, học tập, giải trí và liên lạc với người ở xa.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 2', pts: 1,
      text: 'Thông tin "đáng tin cậy" là thông tin thế nào?',
      opts: o4('Do một người lạ tự bịa ra', 'Đúng sự thật, từ nguồn rõ ràng, uy tín', 'Càng giật gân càng đúng', 'Chữ càng to càng đáng tin'), ans: 'B',
      why: 'Thông tin đáng tin cậy là thông tin đúng sự thật, lấy từ nguồn rõ ràng, uy tín.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 3', pts: 1,
      text: 'Khi đọc một tin trên mạng, để biết có nên tin hay không, em nên làm gì?',
      opts: o4('Tin ngay lập tức', 'Kiểm tra nguồn và so với thông tin ở nơi uy tín khác', 'Chia sẻ ngay cho mọi người', 'Chỉ tin nếu có nhiều màu sắc'), ans: 'B',
      why: 'Nên xem thông tin từ đâu và đối chiếu với nguồn uy tín khác trước khi tin hoặc chia sẻ.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 4', pts: 1,
      text: 'Muốn tìm thông tin trên Internet, em thường dùng công cụ gì?',
      opts: o4('Cái loa', 'Máy in', 'Bàn di chuột', 'Máy tìm kiếm (công cụ tìm kiếm)'), ans: 'D',
      why: 'Máy tìm kiếm giúp ta gõ từ khoá để tìm các trang web có thông tin cần tìm.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 5', pts: 1,
      text: 'Để tìm nhanh và đúng, em nên gõ từ khoá thế nào?',
      opts: o4('Gõ từ khoá ngắn gọn, đúng nội dung cần tìm', 'Gõ một câu thật dài, lan man', 'Gõ toàn dấu chấm than', 'Gõ số điện thoại của mình'), ans: 'A',
      why: 'Từ khoá ngắn gọn, đúng trọng tâm giúp máy tìm kiếm trả về kết quả sát với điều cần tìm.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 6', pts: 1,
      text: 'Khi lên mạng, thông tin nào em TUYỆT ĐỐI không nên chia sẻ với người lạ?',
      opts: o4('Một câu chúc mừng', 'Một bức tranh phong cảnh', 'Địa chỉ nhà, số điện thoại, mật khẩu', 'Tên một quyển sách hay'), ans: 'C',
      why: 'Địa chỉ nhà, số điện thoại, mật khẩu là thông tin riêng tư, không được cho người lạ để tránh nguy hiểm.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 7', pts: 1,
      text: 'Gặp thông tin xấu, đáng ngờ hoặc khiến em khó chịu trên mạng, em nên làm gì?',
      opts: o4('Kể cho bố mẹ, thầy cô biết', 'Làm theo ngay', 'Giấu kín không nói ai', 'Chia sẻ cho thật nhiều bạn'), ans: 'A',
      why: 'Khi gặp thông tin xấu hay đáng ngờ, em nên báo với người lớn tin cậy để được giúp đỡ.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 8', pts: 1,
      text: 'Vì sao không nên tin ngay mọi thứ đọc được trên mạng?',
      opts: o4('Vì mạng luôn luôn đúng', 'Vì máy tính biết nói dối', 'Vì trên mạng có cả thông tin sai, bịa đặt', 'Vì thông tin nào cũng vô hại'), ans: 'C',
      why: 'Trên Internet có cả thông tin sai, bịa đặt nên phải chọn lọc, kiểm chứng trước khi tin.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 9', pts: 1,
      text: 'Dùng Internet để học tập hợp lí là thế nào?',
      opts: o4('Chơi game suốt ngày', 'Xem có giờ giấc, ưu tiên tìm kiến thức, nghỉ ngơi mắt', 'Thức khuya lướt mạng', 'Bỏ ăn để lên mạng'), ans: 'B',
      why: 'Dùng Internet có giờ giấc, chọn nội dung học tập bổ ích và cho mắt nghỉ là cách dùng hợp lí.' },
    { sec: 'Thông tin trên Internet', name: 'Câu 10', pts: 1,
      text: 'Kết quả tìm kiếm cho nhiều trang, em nên chọn trang nào để đọc?',
      opts: o4('Trang có nhiều quảng cáo nhấp nháy nhất', 'Trang bất kì ở cuối danh sách', 'Trang có tên lạ nhất', 'Trang có nguồn rõ ràng, nội dung phù hợp điều cần tìm'), ans: 'D',
      why: 'Nên chọn trang có nguồn rõ ràng, nội dung đúng và phù hợp với điều mình cần tìm.' },
  ],
},

/* ═══════════ ĐỀ 5 — SƠ ĐỒ HÌNH CÂY VÀ SƠ ĐỒ TƯ DUY ═══════════ */
{
  id: 9315, title: 'Đề 5 · Sơ đồ hình cây và sơ đồ tư duy', time: 20,
  questions: [
    { sec: 'Sơ đồ', name: 'Câu 1', pts: 1,
      text: 'Sơ đồ hình cây dùng để làm gì?',
      opts: o4('Đo chiều dài cái bàn', 'Phát ra âm thanh', 'Sắp xếp, phân nhóm thông tin theo các nhánh', 'Tính tiền chợ'), ans: 'C',
      why: 'Sơ đồ hình cây giúp sắp xếp, phân loại thông tin thành các nhánh lớn, nhánh nhỏ cho dễ hiểu.' },
    { sec: 'Sơ đồ', name: 'Câu 2', pts: 1,
      text: 'Trong sơ đồ tư duy, ý chính (chủ đề trung tâm) thường được đặt ở đâu?',
      opts: o4('Ở giữa sơ đồ', 'Ở góc dưới cùng', 'Bên ngoài trang giấy', 'Không cần ý chính'), ans: 'A',
      why: 'Ý chính (chủ đề) đặt ở giữa, rồi từ đó toả ra các nhánh ý phụ xung quanh.' },
    { sec: 'Sơ đồ', name: 'Câu 3', pts: 1,
      text: 'Từ ý chính ở giữa, ta vẽ tiếp những gì?',
      opts: o4('Các con số ngẫu nhiên', 'Nhiều dấu chấm hỏi', 'Không vẽ thêm gì', 'Các nhánh chứa ý phụ, ý nhỏ hơn'), ans: 'D',
      why: 'Từ ý chính, ta vẽ các nhánh nối tới ý phụ, rồi ý phụ lại chia thành ý nhỏ hơn.' },
    { sec: 'Sơ đồ', name: 'Câu 4', pts: 1,
      text: 'Sơ đồ tư duy giúp em điều gì khi học bài?',
      opts: o4('Làm bài lâu hơn', 'Nhìn tổng quát và nhớ bài dễ hơn', 'Quên bài nhanh hơn', 'Không giúp gì cả'), ans: 'B',
      why: 'Sơ đồ tư duy tóm tắt bài thành nhánh, giúp nhìn tổng quát và ghi nhớ dễ hơn.' },
    { sec: 'Sơ đồ', name: 'Câu 5', pts: 1,
      text: 'Cấu trúc thư mục trong máy tính có dạng giống sơ đồ nào?',
      opts: o4('Sơ đồ hình tròn khép kín', 'Sơ đồ hình cây', 'Đường thẳng một hàng', 'Không có dạng nào'), ans: 'B',
      why: 'Thư mục lồng trong thư mục tạo thành cấu trúc hình cây, giống sơ đồ hình cây.' },
    { sec: 'Sơ đồ', name: 'Câu 6', pts: 1,
      text: 'Để sơ đồ tư duy dễ nhìn, em nên làm gì?',
      opts: o4('Viết cả đoạn văn dài trên mỗi nhánh', 'Chỉ dùng một màu đen kín trang', 'Viết chữ thật nhỏ, chồng lên nhau', 'Dùng từ khoá ngắn, thêm màu và hình vẽ'), ans: 'D',
      why: 'Dùng từ khoá ngắn, màu sắc và hình vẽ giúp sơ đồ rõ ràng, sinh động và dễ nhớ.' },
    { sec: 'Sơ đồ', name: 'Câu 7', pts: 1,
      text: 'Muốn phân loại con vật thành "vật nuôi" và "thú rừng", dùng sơ đồ nào thuận tiện?',
      opts: o4('Sơ đồ hình cây', 'Bảng nhân', 'Cái thước kẻ', 'Đồng hồ'), ans: 'A',
      why: 'Sơ đồ hình cây chia thành các nhánh nhóm nên rất hợp để phân loại con vật.' },
    { sec: 'Sơ đồ', name: 'Câu 8', pts: 1,
      text: 'Các nhánh trong sơ đồ hình cây nối với nhau bằng gì?',
      opts: o4('Các con ốc vít', 'Sợi dây điện', 'Các đường (nhánh) nối', 'Băng dính'), ans: 'C',
      why: 'Các mục trong sơ đồ hình cây được nối với nhau bằng các đường (nhánh) thể hiện quan hệ.' },
    { sec: 'Sơ đồ', name: 'Câu 9', pts: 1,
      text: 'Khi tóm tắt một bài học nhiều mục, cách nào giúp trình bày gọn, rõ nhất?',
      opts: o4('Vẽ sơ đồ tư duy theo các nhánh ý', 'Chép lại y nguyên cả bài', 'Không ghi gì cả', 'Viết lộn xộn không thứ tự'), ans: 'A',
      why: 'Vẽ sơ đồ tư duy theo nhánh giúp gom ý chính, trình bày gọn và rõ ràng hơn chép cả bài.' },
    { sec: 'Sơ đồ', name: 'Câu 10', pts: 1,
      text: 'Trong sơ đồ hình cây, mục "gốc" (trên cùng) là gì?',
      opts: o4('Mục nhỏ nhất', 'Mục không liên quan gì', 'Mục chung nhất, bao trùm các mục còn lại', 'Một con số bất kì'), ans: 'C',
      why: 'Gốc của sơ đồ hình cây là mục chung nhất, từ đó phân nhánh xuống các mục nhỏ hơn.' },
  ],
},

/* ═══════════ ĐỀ 6 — ĐẠO ĐỨC, VĂN HOÁ VÀ BẢN QUYỀN KHI DÙNG MÁY TÍNH ═══════════ */
{
  id: 9316, title: 'Đề 6 · Đạo đức, văn hoá và bản quyền khi dùng máy tính', time: 20,
  questions: [
    { sec: 'Đạo đức & bản quyền', name: 'Câu 1', pts: 1,
      text: 'Bản quyền của một bài hát, bức tranh, phần mềm là gì?',
      opts: o4('Quyền của bất kì ai muốn lấy', 'Quyền của người đã tạo ra sản phẩm đó', 'Không của ai cả', 'Quyền của máy tính'), ans: 'B',
      why: 'Bản quyền là quyền của người sáng tạo (tác giả) đối với sản phẩm họ làm ra.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 2', pts: 1,
      text: 'Muốn dùng tranh, bài viết của người khác, em nên làm gì?',
      opts: o4('Cứ lấy dùng, coi như của mình', 'Xoá tên tác giả đi', 'Nói dối là mình tự làm', 'Xin phép và ghi rõ tên tác giả (nguồn)'), ans: 'D',
      why: 'Cần xin phép và ghi rõ nguồn, tên tác giả; không được nhận sản phẩm của người khác là của mình.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 3', pts: 1,
      text: 'Việc chép bài của bạn rồi nói là mình làm là hành vi gì?',
      opts: o4('Trung thực', 'Rất đáng khen', 'Không trung thực, vi phạm đạo đức', 'Việc nên làm'), ans: 'C',
      why: 'Chép bài của người khác rồi nhận là của mình là không trung thực, vi phạm đạo đức.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 4', pts: 1,
      text: 'Khi nhắn tin, bình luận trên mạng, em nên cư xử thế nào?',
      opts: o4('Lịch sự, tôn trọng người khác', 'Nói lời thô lỗ', 'Trêu chọc, chê bai bạn', 'Viết những lời xúc phạm'), ans: 'A',
      why: 'Trên mạng cũng cần lịch sự, tôn trọng người khác như khi nói chuyện ngoài đời.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 5', pts: 1,
      text: 'Sao chép trái phép phần mềm, phim, nhạc để dùng hoặc bán là việc thế nào?',
      opts: o4('Được phép thoải mái', 'Rất nên làm', 'Không liên quan tới ai', 'Vi phạm bản quyền, không được làm'), ans: 'D',
      why: 'Sao chép trái phép sản phẩm của người khác là vi phạm bản quyền, không được phép làm.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 6', pts: 1,
      text: 'Bạn đăng ảnh chế giễu một người khác, em nên làm gì?',
      opts: o4('Hùa theo cười cợt', 'Khuyên bạn gỡ xuống và không làm theo', 'Chia sẻ cho nhiều người', 'Khen bạn giỏi'), ans: 'B',
      why: 'Ảnh chế giễu làm tổn thương người khác; em nên khuyên bạn gỡ và không tham gia.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 7', pts: 1,
      text: 'Vì sao phải tôn trọng bản quyền?',
      opts: o4('Để máy chạy nhanh hơn', 'Để tôn trọng công sức của người sáng tạo', 'Vì bắt buộc phải xấu tính', 'Không có lí do gì'), ans: 'B',
      why: 'Tôn trọng bản quyền là tôn trọng công sức, chất xám của người đã tạo ra sản phẩm.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 8', pts: 1,
      text: 'Khi trích một đoạn từ sách trên mạng để làm bài, em nên làm gì?',
      opts: o4('Giấu đi không ai biết', 'Đổi tên tác giả thành tên mình', 'Xoá hết dấu vết', 'Ghi rõ đã lấy từ đâu (nguồn)'), ans: 'D',
      why: 'Khi dùng lại nội dung của người khác, cần ghi rõ nguồn để trung thực và tôn trọng tác giả.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 9', pts: 1,
      text: 'Mật khẩu tài khoản của em, em nên làm gì?',
      opts: o4('Giữ bí mật, chỉ cho người thân tin cậy biết khi cần', 'Dán lên màn hình cho dễ nhớ', 'Cho tất cả bạn bè biết', 'Ghi công khai trên mạng'), ans: 'A',
      why: 'Mật khẩu cần giữ bí mật để bảo vệ tài khoản, không cho người lạ biết.' },
    { sec: 'Đạo đức & bản quyền', name: 'Câu 10', pts: 1,
      text: 'Sử dụng máy tính có văn hoá còn thể hiện ở việc nào?',
      opts: o4('Đập phá máy khi thua game', 'Vẽ bậy lên máy chung', 'Dùng đúng giờ, giữ máy sạch, không phá của công', 'Cãi nhau tranh máy'), ans: 'C',
      why: 'Dùng máy đúng giờ, giữ gìn máy, không phá hoại của công là biểu hiện của văn hoá khi dùng máy tính.' },
  ],
},

/* ═══════════ ĐỀ 7 — HOA, CÂY CẢNH VÀ LỢI ÍCH ═══════════ */
{
  id: 9317, title: 'Đề 7 · Hoa, cây cảnh và lợi ích', time: 20,
  questions: [
    { sec: 'Hoa và cây cảnh', name: 'Câu 1', pts: 1,
      text: 'Trồng hoa và cây cảnh trong nhà, sân trường mang lại lợi ích gì?',
      opts: o4('Làm đẹp, cho bóng mát, không khí trong lành hơn', 'Làm nhà bẩn hơn', 'Gây ồn ào', 'Tốn điện'), ans: 'A',
      why: 'Hoa và cây cảnh làm đẹp không gian, cho bóng mát và giúp không khí trong lành, dễ chịu.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 2', pts: 1,
      text: 'Cây nào sau đây thường được trồng làm cây cảnh?',
      opts: o4('Cây lúa', 'Cây ngô ngoài đồng', 'Cây hoa hồng, cây trầu bà', 'Cây khoai lang'), ans: 'C',
      why: 'Hoa hồng, trầu bà... thường được trồng làm cảnh; còn lúa, ngô, khoai là cây lương thực, hoa màu.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 3', pts: 1,
      text: 'Cây xanh giúp không khí trong lành vì cây nhả ra khí gì?',
      opts: o4('Khói bụi', 'Khí ô-xi', 'Khí độc', 'Hơi nóng'), ans: 'B',
      why: 'Ban ngày cây quang hợp và nhả ra khí ô-xi, giúp không khí trong lành hơn.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 4', pts: 1,
      text: 'Để cây cảnh trong chậu sống tốt, việc nào là cần thiết?',
      opts: o4('Để cây trong bóng tối hoàn toàn', 'Không bao giờ tưới nước', 'Đổ nước sôi vào gốc', 'Tưới nước và cho cây đủ ánh sáng'), ans: 'D',
      why: 'Cây cần được tưới nước và có đủ ánh sáng để sống và phát triển.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 5', pts: 1,
      text: 'Khi lá cây cảnh bị bụi bám nhiều, em nên làm gì?',
      opts: o4('Bẻ hết lá đi', 'Đổ dầu ăn lên lá', 'Nhẹ nhàng lau sạch lá', 'Mặc kệ cho bụi dày thêm'), ans: 'C',
      why: 'Lau sạch bụi trên lá giúp cây quang hợp tốt hơn và trông sạch, đẹp.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 6', pts: 1,
      text: 'Ngoài làm đẹp, một số loài hoa còn dùng để làm gì?',
      opts: o4('Trang trí, làm quà tặng trong ngày lễ', 'Làm dây điện', 'Làm bàn ghế', 'Làm gạch xây nhà'), ans: 'A',
      why: 'Hoa còn được dùng để trang trí, làm quà tặng trong các ngày lễ, dịp vui.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 7', pts: 1,
      text: 'Đặt chậu cây cảnh ưa sáng ở đâu là hợp lí?',
      opts: o4('Trong tủ kín tối', 'Dưới gầm giường', 'Trong hộp đậy nắp', 'Gần cửa sổ có ánh sáng'), ans: 'D',
      why: 'Cây ưa sáng nên đặt gần cửa sổ để nhận đủ ánh sáng, cây mới xanh tốt.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 8', pts: 1,
      text: 'Việc chăm sóc cây cảnh giúp em rèn luyện đức tính gì?',
      opts: o4('Lười biếng', 'Chăm chỉ, kiên nhẫn, yêu thiên nhiên', 'Cẩu thả', 'Vô trách nhiệm'), ans: 'B',
      why: 'Chăm cây đều đặn giúp em rèn tính chăm chỉ, kiên nhẫn và thêm yêu thiên nhiên.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 9', pts: 1,
      text: 'Cây cảnh trồng trong lớp học còn giúp điều gì?',
      opts: o4('Lớp học nóng hơn', 'Lớp học xanh, mát, dễ chịu khi học', 'Học sinh khó thở hơn', 'Không có tác dụng'), ans: 'B',
      why: 'Cây xanh trong lớp giúp không gian mát mẻ, trong lành, tạo cảm giác dễ chịu khi học.' },
    { sec: 'Hoa và cây cảnh', name: 'Câu 10', pts: 1,
      text: 'Khi cây trong chậu bị úng nước (tưới quá nhiều), em nên làm gì?',
      opts: o4('Đổ thêm thật nhiều nước nữa', 'Đậy kín chậu lại', 'Đem chậu ra phơi nắng gắt cả ngày', 'Ngừng tưới, để chậu chỗ thoáng cho ráo bớt nước'), ans: 'D',
      why: 'Cây úng nước cần ngừng tưới và để chậu nơi thoáng cho thoát bớt nước, tránh thối rễ.' },
  ],
},

/* ═══════════ ĐỀ 8 — GIEO TRỒNG, CHĂM SÓC CÂY; VẬT LIỆU VÀ DỤNG CỤ ═══════════ */
{
  id: 9318, title: 'Đề 8 · Gieo trồng, chăm sóc cây; vật liệu và dụng cụ', time: 20,
  questions: [
    { sec: 'Gieo trồng cây', name: 'Câu 1', pts: 1,
      text: 'Muốn gieo hạt để cây mọc lên, trước hết cần có gì?',
      opts: o4('Hạt giống tốt và đất trồng', 'Chỉ cần cái kéo', 'Chỉ cần cái loa', 'Chỉ cần tờ giấy'), ans: 'A',
      why: 'Để gieo trồng cần có hạt giống tốt và đất (hoặc giá thể) để hạt nảy mầm.' },
    { sec: 'Gieo trồng cây', name: 'Câu 2', pts: 1,
      text: 'Hạt gieo xuống đất cần những gì để nảy mầm?',
      opts: o4('Chỉ cần bóng tối tuyệt đối', 'Chỉ cần đá sỏi khô', 'Nước, không khí và nhiệt độ thích hợp', 'Không cần gì cả'), ans: 'C',
      why: 'Hạt cần đủ nước, không khí và nhiệt độ thích hợp mới nảy mầm được.' },
    { sec: 'Gieo trồng cây', name: 'Câu 3', pts: 1,
      text: 'Sau khi gieo hạt, việc chăm sóc hằng ngày quan trọng là gì?',
      opts: o4('Tưới nước, nhổ cỏ, bắt sâu cho cây', 'Bỏ mặc không tưới', 'Giẫm lên luống cây', 'Đổ dầu vào gốc'), ans: 'A',
      why: 'Chăm sóc cây gồm tưới nước, nhổ cỏ dại, bắt sâu để cây lớn khoẻ.' },
    { sec: 'Gieo trồng cây', name: 'Câu 4', pts: 1,
      text: 'Bón phân cho cây nhằm mục đích gì?',
      opts: o4('Làm cây chết nhanh', 'Làm đất cứng lại', 'Cung cấp chất dinh dưỡng để cây lớn tốt', 'Xua đuổi ánh sáng'), ans: 'C',
      why: 'Bón phân bổ sung chất dinh dưỡng cho đất, giúp cây phát triển tốt.' },
    { sec: 'Vật liệu & dụng cụ', name: 'Câu 5', pts: 1,
      text: 'Dụng cụ nào dùng để xới đất, làm tơi đất khi trồng cây?',
      opts: o4('Cái loa', 'Cái cuốc, cái bay làm vườn', 'Bàn phím', 'Cái kéo cắt giấy'), ans: 'B',
      why: 'Cuốc, bay (xẻng nhỏ) làm vườn dùng để xới, làm tơi đất trước khi trồng cây.' },
    { sec: 'Vật liệu & dụng cụ', name: 'Câu 6', pts: 1,
      text: 'Dụng cụ nào dùng để tưới nước cho cây trong chậu?',
      opts: o4('Cái búa', 'Cái kìm', 'Máy tính', 'Bình tưới (ô doa)'), ans: 'D',
      why: 'Bình tưới (ô doa) giúp tưới nước nhẹ nhàng, đều lên cây.' },
    { sec: 'Vật liệu & dụng cụ', name: 'Câu 7', pts: 1,
      text: 'Khi dùng các dụng cụ có cạnh sắc nhọn (kéo, dao làm vườn), em cần thế nào?',
      opts: o4('Vung vẩy tuỳ ý', 'Chĩa vào người khác', 'Cẩn thận, làm theo hướng dẫn của người lớn', 'Vừa dùng vừa chạy'), ans: 'C',
      why: 'Dụng cụ sắc nhọn phải dùng cẩn thận, theo hướng dẫn để tránh bị thương.' },
    { sec: 'Vật liệu & dụng cụ', name: 'Câu 8', pts: 1,
      text: 'Dùng dụng cụ làm vườn xong, em nên làm gì?',
      opts: o4('Lau sạch, cất gọn vào đúng nơi', 'Vứt bừa ngoài sân', 'Bẻ gãy đi', 'Để ngâm trong nước bẩn'), ans: 'A',
      why: 'Sau khi dùng nên lau sạch và cất gọn dụng cụ để giữ bền và an toàn.' },
    { sec: 'Gieo trồng cây', name: 'Câu 9', pts: 1,
      text: 'Vì sao nên nhổ bớt cỏ dại quanh gốc cây trồng?',
      opts: o4('Để cây thêm nhiều cỏ', 'Để đất khô cứng hơn', 'Không có lí do', 'Để cỏ khỏi tranh nước, chất dinh dưỡng của cây'), ans: 'D',
      why: 'Cỏ dại tranh nước và dinh dưỡng của cây trồng, nên cần nhổ bớt để cây lớn tốt.' },
    { sec: 'Gieo trồng cây', name: 'Câu 10', pts: 1,
      text: 'Nên tưới cây vào thời điểm nào trong ngày là hợp lí?',
      opts: o4('Giữa trưa nắng gắt', 'Sáng sớm hoặc chiều mát', 'Nửa đêm mỗi giờ một lần', 'Không bao giờ tưới'), ans: 'B',
      why: 'Tưới vào sáng sớm hoặc chiều mát giúp cây hút nước tốt, tránh bốc hơi nhanh lúc trưa nắng.' },
  ],
},

/* ═══════════ ĐỀ 9 — LẮP GHÉP MÔ HÌNH KĨ THUẬT ĐƠN GIẢN ═══════════ */
{
  id: 9319, title: 'Đề 9 · Lắp ghép mô hình kĩ thuật đơn giản', time: 20,
  questions: [
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 1', pts: 1,
      text: 'Trước khi lắp ghép một mô hình, việc đầu tiên nên làm là gì?',
      opts: o4('Lắp bừa cho nhanh', 'Xem hình mẫu, đọc hướng dẫn và chuẩn bị đủ chi tiết', 'Vứt bỏ bản hướng dẫn', 'Tháo tung mọi thứ ra trước'), ans: 'B',
      why: 'Nên xem mẫu, đọc kĩ hướng dẫn và kiểm tra đủ các chi tiết trước khi bắt tay lắp ghép.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 2', pts: 1,
      text: 'Trong bộ lắp ghép, chi tiết nào dùng để nối và giữ chặt các thanh với nhau?',
      opts: o4('Cục tẩy', 'Viên phấn', 'Tờ giấy', 'Ốc (vít) và đai ốc'), ans: 'D',
      why: 'Ốc vít và đai ốc dùng để nối và siết chặt các chi tiết của mô hình lại với nhau.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 3', pts: 1,
      text: 'Dụng cụ nào dùng để vặn ốc vít khi lắp ghép?',
      opts: o4('Cái tua vít (và cờ lê)', 'Cái bút chì', 'Cái thìa ăn cơm', 'Cái lược'), ans: 'A',
      why: 'Tua vít dùng để vặn ốc vít, cờ lê giữ đai ốc; đó là dụng cụ lắp ghép thông dụng.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 4', pts: 1,
      text: 'Nên lắp ghép mô hình theo thứ tự thế nào?',
      opts: o4('Bỏ qua các bước cho nhanh', 'Lắp ngược từ bước cuối', 'Theo đúng các bước trong hướng dẫn', 'Lắp lung tung không thứ tự'), ans: 'C',
      why: 'Lắp theo đúng thứ tự các bước hướng dẫn giúp mô hình chắc chắn và không bị sai, thiếu.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 5', pts: 1,
      text: 'Khi lắp xong mà mô hình bị lỏng lẻo, em nên làm gì?',
      opts: o4('Vặn chặt lại các ốc vít cho chắc', 'Bỏ luôn không quan tâm', 'Đập cho gãy', 'Tháo hết vít ra rồi để đó'), ans: 'A',
      why: 'Mô hình lỏng cần vặn chặt lại các ốc vít để chắc chắn, dùng được lâu và an toàn.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 6', pts: 1,
      text: 'Lắp xong, thừa hoặc thiếu chi tiết cho thấy điều gì?',
      opts: o4('Chắc chắn mô hình hoàn hảo', 'Không cần để ý', 'Có thể đã lắp sai hoặc bỏ sót bước, cần kiểm tra lại', 'Nên vứt mô hình đi'), ans: 'C',
      why: 'Thừa hay thiếu chi tiết thường do lắp sai hoặc bỏ sót; nên kiểm tra và làm lại cho đúng.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 7', pts: 1,
      text: 'Khi lắp ghép, để an toàn cho tay, em cần chú ý gì?',
      opts: o4('Vung tua vít loạn xạ', 'Cẩn thận với cạnh sắc, mũi vít nhọn', 'Ngậm ốc vít trong miệng', 'Ném chi tiết cho bạn'), ans: 'B',
      why: 'Cần cẩn thận với cạnh sắc và mũi vít nhọn; không ngậm chi tiết nhỏ để tránh nguy hiểm.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 8', pts: 1,
      text: 'Làm xong sản phẩm lắp ghép, em nên làm gì với các chi tiết còn lại?',
      opts: o4('Vứt vương vãi trên sàn', 'Cho vào miệng ngậm', 'Ném ra ngoài cửa sổ', 'Thu gom, cất gọn vào hộp đúng nơi'), ans: 'D',
      why: 'Thu gom, cất gọn chi tiết vào hộp giúp không thất lạc và giữ an toàn, ngăn nắp.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 9', pts: 1,
      text: 'Lắp ghép mô hình kĩ thuật giúp em rèn luyện điều gì?',
      opts: o4('Tính cẩu thả', 'Thói bỏ dở giữa chừng', 'Sự khéo léo, kiên nhẫn và tư duy làm theo trình tự', 'Sự vội vàng, hấp tấp'), ans: 'C',
      why: 'Lắp ghép rèn cho em sự khéo léo, kiên nhẫn và biết làm việc theo trình tự các bước.' },
    { sec: 'Lắp ghép kĩ thuật', name: 'Câu 10', pts: 1,
      text: 'Với mô hình có bánh xe (ví dụ xe đẩy), lắp bánh xe thế nào là đúng?',
      opts: o4('Lắp chắc, để bánh quay được trơn tru', 'Vặn thật chặt tới mức bánh không quay', 'Lắp lỏng để bánh rơi ra', 'Không cần bánh cũng được'), ans: 'A',
      why: 'Bánh xe cần lắp chắc nhưng vẫn quay trơn tru thì xe mới chạy được.' },
  ],
},

/* ═══════════ ĐỀ 10 — ĐỒ DÙNG ĐIỆN, AN TOÀN ĐIỆN VÀ SẢN PHẨM THỦ CÔNG ═══════════ */
{
  id: 9320, title: 'Đề 10 · Đồ dùng điện, an toàn điện và sản phẩm thủ công', time: 20,
  questions: [
    { sec: 'Đồ dùng điện & an toàn', name: 'Câu 1', pts: 1,
      text: 'Đồ dùng nào trong nhà chạy bằng điện?',
      opts: o4('Cái chổi', 'Cái ghế gỗ', 'Quyển sách', 'Quạt điện, tủ lạnh, nồi cơm điện'), ans: 'D',
      why: 'Quạt điện, tủ lạnh, nồi cơm điện là các đồ dùng điện; chổi, ghế gỗ, sách thì không.' },
    { sec: 'Đồ dùng điện & an toàn', name: 'Câu 2', pts: 1,
      text: 'Vì sao không được dùng tay ướt cắm hoặc rút phích điện?',
      opts: o4('Vì làm bẩn ổ cắm', 'Vì tay ướt dễ bị điện giật, rất nguy hiểm', 'Vì tốn điện', 'Vì làm hỏng bàn tay cho đẹp'), ans: 'B',
      why: 'Nước dẫn điện, tay ướt chạm vào điện dễ bị điện giật nguy hiểm, thậm chí nguy hiểm tính mạng.' },
    { sec: 'Đồ dùng điện & an toàn', name: 'Câu 3', pts: 1,
      text: 'Thấy dây điện bị hở, đứt hoặc ổ cắm cháy xém, em nên làm gì?',
      opts: o4('Lấy tay sờ thử', 'Tránh xa và báo ngay người lớn', 'Cắm thêm đồ vào', 'Dội nước lên'), ans: 'B',
      why: 'Dây hở, ổ cắm cháy rất nguy hiểm; phải tránh xa và báo người lớn, không tự ý chạm vào.' },
    { sec: 'Đồ dùng điện & an toàn', name: 'Câu 4', pts: 1,
      text: 'Rút phích cắm điện ra khỏi ổ, em nên cầm vào đâu?',
      opts: o4('Túm dây điện mà giật', 'Dùng kéo cắt dây', 'Dùng răng cắn dây', 'Cầm vào thân phích cắm mà rút'), ans: 'D',
      why: 'Phải cầm vào thân phích để rút; giật dây dễ làm đứt dây, hở điện, gây nguy hiểm.' },
    { sec: 'Đồ dùng điện & an toàn', name: 'Câu 5', pts: 1,
      text: 'Dùng xong quạt, đèn, ti vi, em nên làm gì để tiết kiệm điện?',
      opts: o4('Tắt thiết bị khi không dùng', 'Bật suốt ngày đêm', 'Cắm thật nhiều đồ cùng lúc', 'Mở hết cửa cho gió vào rồi vẫn bật quạt'), ans: 'A',
      why: 'Tắt đồ dùng điện khi không dùng vừa tiết kiệm điện vừa an toàn.' },
    { sec: 'Đồ dùng điện & an toàn', name: 'Câu 6', pts: 1,
      text: 'Vì sao không nên nhét vật kim loại (như đũa, kẹp) vào ổ điện?',
      opts: o4('Vì làm ổ điện đẹp hơn', 'Vì giúp đồ chạy nhanh hơn', 'Vì kim loại dẫn điện, dễ bị điện giật', 'Vì cho vui'), ans: 'C',
      why: 'Kim loại dẫn điện; nhét vào ổ điện sẽ bị điện giật rất nguy hiểm, tuyệt đối không làm.' },
    { sec: 'Sản phẩm thủ công', name: 'Câu 7', pts: 1,
      text: 'Từ giấy màu, em có thể làm sản phẩm thủ công nào?',
      opts: o4('Thiệp chúc mừng, đèn lồng, hoa giấy', 'Cái tủ lạnh', 'Chiếc ô tô thật', 'Cái điện thoại'), ans: 'A',
      why: 'Giấy màu có thể dùng làm thiệp, đèn lồng, hoa giấy... là các sản phẩm thủ công đơn giản.' },
    { sec: 'Sản phẩm thủ công', name: 'Câu 8', pts: 1,
      text: 'Trước khi làm một sản phẩm thủ công, bước đầu nên làm gì?',
      opts: o4('Làm bừa rồi tính sau', 'Không cần chuẩn bị gì', 'Nghĩ ra ý tưởng và chuẩn bị vật liệu, dụng cụ', 'Vứt hết vật liệu đi'), ans: 'C',
      why: 'Nên có ý tưởng về sản phẩm rồi chuẩn bị đủ vật liệu, dụng cụ trước khi bắt tay làm.' },
    { sec: 'Sản phẩm thủ công', name: 'Câu 9', pts: 1,
      text: 'Làm sản phẩm thủ công từ vật liệu tái chế (chai, lọ, hộp cũ) có lợi ích gì?',
      opts: o4('Làm nhà bẩn thêm', 'Tiết kiệm và bảo vệ môi trường', 'Tốn tiền hơn mua mới', 'Không có ích gì'), ans: 'B',
      why: 'Tái chế đồ cũ thành sản phẩm mới giúp tiết kiệm và giảm rác, bảo vệ môi trường.' },
    { sec: 'Sản phẩm thủ công', name: 'Câu 10', pts: 1,
      text: 'Làm thủ công xong, chỗ ngồi bừa bộn giấy vụn, keo dán, em nên làm gì?',
      opts: o4('Để nguyên đó rồi đi chơi', 'Ném rác xuống sàn', 'Bỏ keo dán vào miệng', 'Dọn dẹp, thu gom rác, cất dụng cụ gọn gàng'), ans: 'D',
      why: 'Làm xong cần dọn sạch chỗ ngồi, thu gom rác và cất dụng cụ để giữ vệ sinh, ngăn nắp.' },
  ],
},

];

SUBJECTS.push({ id:'tincn4', name:'Tin học & Công nghệ', short:'Tin-CN 4', icon:'💻', grade:4, exams:TINCN4_EXAMS, ready:true, heroTitle:'Tin học & Công nghệ lớp 4 — phần cứng & phần mềm, soạn thảo, thông tin đáng tin cậy và kĩ thuật', heroMeta:'📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018' });
