// TOÁN LỚP 3 QUA HÌNH — BÀI HỌC · 10 đề × 10 câu = 100 câu, 100% câu có hình SVG.
// SINH TỰ ĐỘNG bởi tools/gen-hinh-baihoc.mjs (module tools/hinhb-q3.mjs) — sửa trong script rồi chạy lại:
//     node tools/gen-hinh-baihoc.mjs
// Bài 16 · 17 · 18 · 21 · 29–33 · 47–52 · 61 · 14 · 39 · 71–72 (SGK Kết nối tri thức)
// Hình vẽ bằng code (assets/hinhb3/), đáp án lấy thẳng từ dữ liệu vẽ hình nên không bao giờ lệch.

const HINHB3_EXAMS = [
{
  id: 9511, title: "Đề 1 · Điểm ở giữa — trung điểm", time: 25,
  questions: [
    { sec: "Trung điểm", name: "Câu 1", pts: 1, text: "Trên hình, các điểm A, B, C, D, E cách đều nhau. Trung điểm của đoạn thẳng AE là điểm nào?", img: "assets/hinhb3/d1c1.svg", opts: o4("A", "E", "B", "C"), ans: "D", why: "C nằm giữa A và E, đồng thời AC = CE nên C là trung điểm của AE." },
    { sec: "Trung điểm", name: "Câu 2", pts: 1, text: "M là trung điểm của đoạn thẳng AB. Độ dài đoạn thẳng AB là bao nhiêu?", img: "assets/hinhb3/d1c2.svg", opts: o4("12 cm", "26 cm", "22 cm", "24 cm"), ans: "D", why: "M là trung điểm nên AB = AM × 2 = 12 × 2 = 24 (cm)." },
    { sec: "Trung điểm", name: "Câu 3", pts: 1, text: "M là trung điểm của đoạn thẳng AB. Độ dài đoạn thẳng AB là bao nhiêu?", img: "assets/hinhb3/d1c3.svg", opts: o4("24 cm", "12 cm", "26 cm", "22 cm"), ans: "A", why: "M là trung điểm nên AB = AM × 2 = 12 × 2 = 24 (cm)." },
    { sec: "Trung điểm", name: "Câu 4", pts: 1, text: "M là trung điểm của đoạn thẳng AB. Độ dài đoạn thẳng MB là bao nhiêu?", img: "assets/hinhb3/d1c4.svg", opts: o4("14 cm", "8 cm", "7 cm", "6 cm"), ans: "C", why: "M là trung điểm nên AM = MB = AB : 2 = 14 : 2 = 7 (cm)." },
    { sec: "Trung điểm", name: "Câu 5", pts: 1, text: "M là trung điểm của đoạn thẳng AB. Độ dài đoạn thẳng AB là bao nhiêu?", img: "assets/hinhb3/d1c5.svg", opts: o4("18 cm", "9 cm", "20 cm", "16 cm"), ans: "A", why: "M là trung điểm nên AB = AM × 2 = 9 × 2 = 18 (cm)." },
    { sec: "Trung điểm", name: "Câu 6", pts: 1, text: "Trên hình, các điểm A, B, C, D, E cách đều nhau. Trung điểm của đoạn thẳng AC là điểm nào?", img: "assets/hinhb3/d1c6.svg", opts: o4("E", "D", "B", "A"), ans: "C", why: "B nằm giữa A và C, đồng thời AB = BC nên B là trung điểm của AC." },
    { sec: "Trung điểm", name: "Câu 7", pts: 1, text: "M là trung điểm của đoạn thẳng AB. Độ dài đoạn thẳng MB là bao nhiêu?", img: "assets/hinhb3/d1c7.svg", opts: o4("24 cm", "12 cm", "13 cm", "11 cm"), ans: "B", why: "M là trung điểm nên AM = MB = AB : 2 = 24 : 2 = 12 (cm)." },
    { sec: "Gấp mấy lần", name: "Câu 8", pts: 1, text: "Sơ đồ cho biết số cam và số quýt. Số cam gấp số quýt mấy lần?", img: "assets/hinhb3/d1c8.svg", opts: o4("4 lần", "2 lần", "3 lần", "1 lần"), ans: "B", why: "Muốn biết số lớn gấp số bé mấy lần, ta lấy số lớn chia cho số bé: 8 : 4 = 2 (lần)." },
    { sec: "Gấp mấy lần", name: "Câu 9", pts: 1, text: "Sơ đồ cho biết số gà và số vịt. Số gà gấp số vịt mấy lần?", img: "assets/hinhb3/d1c9.svg", opts: o4("5 lần", "2 lần", "3 lần", "1 lần"), ans: "B", why: "Muốn biết số lớn gấp số bé mấy lần, ta lấy số lớn chia cho số bé: 10 : 5 = 2 (lần)." },
    { sec: "Gấp mấy lần", name: "Câu 10", pts: 1, text: "Sơ đồ cho biết số cam và số quýt. Số cam gấp số quýt mấy lần?", img: "assets/hinhb3/d1c10.svg", opts: o4("8 lần", "4 lần", "2 lần", "3 lần"), ans: "D", why: "Muốn biết số lớn gấp số bé mấy lần, ta lấy số lớn chia cho số bé: 12 : 4 = 3 (lần)." },
  ],
},
{
  id: 9512, title: "Đề 2 · Hình tròn: tâm — bán kính — đường kính", time: 25,
  questions: [
    { sec: "Hình tròn", name: "Câu 1", pts: 1, text: "Hình tròn tâm O. Trong hình có bao nhiêu bán kính được vẽ?", img: "assets/hinhb3/d2c1.svg", opts: o4("5", "3", "4", "6"), ans: "C", why: "Bán kính là đoạn thẳng nối tâm O với một điểm trên đường tròn: OA, OB, OC, OD → 4 bán kính. Đoạn MN không đi qua tâm nên không phải bán kính hay đường kính." },
    { sec: "Hình tròn", name: "Câu 2", pts: 1, text: "Hình tròn tâm O có đường kính AB dài như ghi trên hình. Bán kính OB dài bao nhiêu?", img: "assets/hinhb3/d2c2.svg", opts: o4("14 cm", "28 cm", "8 cm", "7 cm"), ans: "D", why: "Bán kính bằng nửa đường kính: OB = 14 : 2 = 7 (cm)." },
    { sec: "Hình tròn", name: "Câu 3", pts: 1, text: "Hình tròn tâm O có đường kính AB dài như ghi trên hình. Bán kính OB dài bao nhiêu?", img: "assets/hinhb3/d2c3.svg", opts: o4("16 cm", "32 cm", "9 cm", "8 cm"), ans: "D", why: "Bán kính bằng nửa đường kính: OB = 16 : 2 = 8 (cm)." },
    { sec: "Hình tròn", name: "Câu 4", pts: 1, text: "Hình tròn tâm O có bán kính OA dài như ghi trên hình. Đường kính AB dài bao nhiêu?", img: "assets/hinhb3/d2c4.svg", opts: o4("3 cm", "12 cm", "6 cm", "7 cm"), ans: "C", why: "Đường kính gấp 2 lần bán kính: AB = 3 × 2 = 6 (cm)." },
    { sec: "Hình tròn", name: "Câu 5", pts: 1, text: "Hình tròn tâm O có bán kính OA dài như ghi trên hình. Đường kính AB dài bao nhiêu?", img: "assets/hinhb3/d2c5.svg", opts: o4("6 cm", "24 cm", "12 cm", "13 cm"), ans: "C", why: "Đường kính gấp 2 lần bán kính: AB = 6 × 2 = 12 (cm)." },
    { sec: "Hình tròn", name: "Câu 6", pts: 1, text: "Hình tròn tâm O có bán kính OA dài như ghi trên hình. Đường kính AB dài bao nhiêu?", img: "assets/hinhb3/d2c6.svg", opts: o4("9 cm", "18 cm", "36 cm", "19 cm"), ans: "B", why: "Đường kính gấp 2 lần bán kính: AB = 9 × 2 = 18 (cm)." },
    { sec: "Hình tròn", name: "Câu 7", pts: 1, text: "Hình tròn tâm O. Trong hình có bao nhiêu bán kính được vẽ?", img: "assets/hinhb3/d2c7.svg", opts: o4("3", "4", "2", "5"), ans: "A", why: "Bán kính là đoạn thẳng nối tâm O với một điểm trên đường tròn: OA, OB, OC → 3 bán kính. Đoạn MN không đi qua tâm nên không phải bán kính hay đường kính." },
    { sec: "Hình chữ nhật", name: "Câu 8", pts: 1, text: "Hình nào là hình chữ nhật?", opts: [{ k: 'A', img: "assets/hinhb3/d2c8a.svg" }, { k: 'B', img: "assets/hinhb3/d2c8b.svg" }, { k: 'C', img: "assets/hinhb3/d2c8c.svg" }, { k: 'D', img: "assets/hinhb3/d2c8d.svg" }], ans: "A", why: "Hình chữ nhật có 4 góc vuông, hai cạnh dài bằng nhau và hai cạnh ngắn bằng nhau. Hình bình hành, hình thang, hình thoi không có 4 góc vuông." },
    { sec: "Hình vuông", name: "Câu 9", pts: 1, text: "Hình nào là hình vuông?", opts: [{ k: 'A', img: "assets/hinhb3/d2c9a.svg" }, { k: 'B', img: "assets/hinhb3/d2c9b.svg" }, { k: 'C', img: "assets/hinhb3/d2c9c.svg" }, { k: 'D', img: "assets/hinhb3/d2c9d.svg" }], ans: "D", why: "Hình vuông có 4 góc vuông và 4 cạnh bằng nhau." },
    { sec: "Góc vuông", name: "Câu 10", pts: 1, text: "Góc nào là góc vuông?", opts: [{ k: 'A', img: "assets/hinhb3/d2c10a.svg" }, { k: 'B', img: "assets/hinhb3/d2c10b.svg" }, { k: 'C', img: "assets/hinhb3/d2c10c.svg" }, { k: 'D', img: "assets/hinhb3/d2c10d.svg" }], ans: "B", why: "Góc vuông là góc bằng góc của ê ke (được đánh dấu bằng ô vuông nhỏ ở đỉnh). Các góc còn lại nhỏ hơn hoặc lớn hơn góc vuông." },
  ],
},
{
  id: 9513, title: "Đề 3 · Góc vuông — góc không vuông", time: 25,
  questions: [
    { sec: "Góc vuông", name: "Câu 1", pts: 1, text: "Trong các góc dưới đây (đỉnh ở góc dưới bên trái), có bao nhiêu góc vuông?", img: "assets/hinhb3/d3c1.svg", opts: o4("3", "1", "2", "4"), ans: "C", why: "Dùng ê ke kiểm tra: các góc số 1, 3 là góc vuông (được đánh dấu ô vuông nhỏ) → 2 góc vuông. Các góc còn lại là góc không vuông (nhọn hoặc tù)." },
    { sec: "Góc vuông", name: "Câu 2", pts: 1, text: "Trong các góc dưới đây (đỉnh ở góc dưới bên trái), có bao nhiêu góc vuông?", img: "assets/hinhb3/d3c2.svg", opts: o4("2", "3", "1", "4"), ans: "A", why: "Dùng ê ke kiểm tra: các góc số 1, 3 là góc vuông (được đánh dấu ô vuông nhỏ) → 2 góc vuông. Các góc còn lại là góc không vuông (nhọn hoặc tù)." },
    { sec: "Góc vuông", name: "Câu 3", pts: 1, text: "Trong các góc dưới đây (đỉnh ở góc dưới bên trái), có bao nhiêu góc vuông?", img: "assets/hinhb3/d3c3.svg", opts: o4("2", "0", "1", "4"), ans: "C", why: "Dùng ê ke kiểm tra: các góc số 1 là góc vuông (được đánh dấu ô vuông nhỏ) → 1 góc vuông. Các góc còn lại là góc không vuông (nhọn hoặc tù)." },
    { sec: "Góc vuông", name: "Câu 4", pts: 1, text: "Trong các góc dưới đây (đỉnh ở góc dưới bên trái), có bao nhiêu góc vuông?", img: "assets/hinhb3/d3c4.svg", opts: o4("3", "1", "2", "4"), ans: "C", why: "Dùng ê ke kiểm tra: các góc số 1, 2 là góc vuông (được đánh dấu ô vuông nhỏ) → 2 góc vuông. Các góc còn lại là góc không vuông (nhọn hoặc tù)." },
    { sec: "Góc vuông", name: "Câu 5", pts: 1, text: "Trong các góc dưới đây (đỉnh ở góc dưới bên trái), có bao nhiêu góc vuông?", img: "assets/hinhb3/d3c5.svg", opts: o4("1", "2", "0", "4"), ans: "A", why: "Dùng ê ke kiểm tra: các góc số 1 là góc vuông (được đánh dấu ô vuông nhỏ) → 1 góc vuông. Các góc còn lại là góc không vuông (nhọn hoặc tù)." },
    { sec: "Góc vuông", name: "Câu 6", pts: 1, text: "Hình ABCD bên có bao nhiêu góc vuông?", img: "assets/hinhb3/d3c6.svg", opts: o4("5", "4", "3", "6"), ans: "B", why: "Các góc vuông là góc ở đỉnh A, B, C, D → 4 góc vuông (kiểm tra bằng ê ke)." },
    { sec: "Góc vuông", name: "Câu 7", pts: 1, text: "Hình ABCD bên có bao nhiêu góc vuông?", img: "assets/hinhb3/d3c7.svg", opts: o4("1", "4", "2", "0"), ans: "D", why: "Không có góc nào là góc vuông; các góc đều là góc nhọn hoặc góc tù." },
    { sec: "Góc vuông", name: "Câu 8", pts: 1, text: "Góc nào là góc vuông?", opts: [{ k: 'A', img: "assets/hinhb3/d3c8a.svg" }, { k: 'B', img: "assets/hinhb3/d3c8b.svg" }, { k: 'C', img: "assets/hinhb3/d3c8c.svg" }, { k: 'D', img: "assets/hinhb3/d3c8d.svg" }], ans: "B", why: "Góc vuông là góc bằng góc của ê ke (được đánh dấu bằng ô vuông nhỏ ở đỉnh). Các góc còn lại nhỏ hơn hoặc lớn hơn góc vuông." },
    { sec: "Góc vuông", name: "Câu 9", pts: 1, text: "Góc nào là góc vuông?", opts: [{ k: 'A', img: "assets/hinhb3/d3c9a.svg" }, { k: 'B', img: "assets/hinhb3/d3c9b.svg" }, { k: 'C', img: "assets/hinhb3/d3c9c.svg" }, { k: 'D', img: "assets/hinhb3/d3c9d.svg" }], ans: "B", why: "Góc vuông là góc bằng góc của ê ke (được đánh dấu bằng ô vuông nhỏ ở đỉnh). Các góc còn lại nhỏ hơn hoặc lớn hơn góc vuông." },
    { sec: "Hình chữ nhật", name: "Câu 10", pts: 1, text: "Hình nào là hình chữ nhật?", opts: [{ k: 'A', img: "assets/hinhb3/d3c10a.svg" }, { k: 'B', img: "assets/hinhb3/d3c10b.svg" }, { k: 'C', img: "assets/hinhb3/d3c10c.svg" }, { k: 'D', img: "assets/hinhb3/d3c10d.svg" }], ans: "D", why: "Hình chữ nhật có 4 góc vuông, hai cạnh dài bằng nhau và hai cạnh ngắn bằng nhau. Hình bình hành, hình thang, hình thoi không có 4 góc vuông." },
  ],
},
{
  id: 9514, title: "Đề 4 · Khối lập phương — khối hộp chữ nhật", time: 25,
  questions: [
    { sec: "Khối lập phương", name: "Câu 1", pts: 1, text: "Khối hộp chữ nhật dưới đây được xếp kín bằng các khối lập phương nhỏ bằng nhau (không có chỗ rỗng). Có tất cả bao nhiêu khối lập phương nhỏ?", img: "assets/hinhb3/d4c1.svg", opts: o4("9", "12", "7", "8"), ans: "D", why: "Mỗi lớp có 4 × 1 = 4 khối, xếp 2 lớp: 4 × 2 = 8 (khối)." },
    { sec: "Khối lập phương", name: "Câu 2", pts: 1, text: "Khối hộp chữ nhật dưới đây được xếp kín bằng các khối lập phương nhỏ bằng nhau (không có chỗ rỗng). Có tất cả bao nhiêu khối lập phương nhỏ?", img: "assets/hinhb3/d4c2.svg", opts: o4("15", "36", "12", "40"), ans: "B", why: "Mỗi lớp có 4 × 3 = 12 khối, xếp 3 lớp: 12 × 3 = 36 (khối)." },
    { sec: "Khối lập phương", name: "Câu 3", pts: 1, text: "Khối hộp chữ nhật dưới đây được xếp kín bằng các khối lập phương nhỏ bằng nhau (không có chỗ rỗng). Có tất cả bao nhiêu khối lập phương nhỏ?", img: "assets/hinhb3/d4c3.svg", opts: o4("13", "12", "16", "11"), ans: "B", why: "Mỗi lớp có 4 × 1 = 4 khối, xếp 3 lớp: 4 × 3 = 12 (khối)." },
    { sec: "Khối lập phương", name: "Câu 4", pts: 1, text: "Khối hộp chữ nhật dưới đây được xếp kín bằng các khối lập phương nhỏ bằng nhau (không có chỗ rỗng). Có tất cả bao nhiêu khối lập phương nhỏ?", img: "assets/hinhb3/d4c4.svg", opts: o4("18", "9", "6", "21"), ans: "A", why: "Mỗi lớp có 3 × 3 = 9 khối, xếp 2 lớp: 9 × 2 = 18 (khối)." },
    { sec: "Khối lập phương", name: "Câu 5", pts: 1, text: "Khối hộp chữ nhật dưới đây được xếp kín bằng các khối lập phương nhỏ bằng nhau (không có chỗ rỗng). Có tất cả bao nhiêu khối lập phương nhỏ?", img: "assets/hinhb3/d4c5.svg", opts: o4("9", "6", "18", "20"), ans: "C", why: "Mỗi lớp có 2 × 3 = 6 khối, xếp 3 lớp: 6 × 3 = 18 (khối)." },
    { sec: "Khối lập phương", name: "Câu 6", pts: 1, text: "Khối hộp chữ nhật dưới đây được xếp kín bằng các khối lập phương nhỏ bằng nhau (không có chỗ rỗng). Có tất cả bao nhiêu khối lập phương nhỏ?", img: "assets/hinhb3/d4c6.svg", opts: o4("5", "4", "8", "3"), ans: "B", why: "Mỗi lớp có 4 × 1 = 4 khối, xếp 1 lớp: 4 × 1 = 4 (khối)." },
    { sec: "Hình khối", name: "Câu 7", pts: 1, text: "Hình nào là khối lập phương?", opts: [{ k: 'A', img: "assets/hinhb3/d4c7a.svg" }, { k: 'B', img: "assets/hinhb3/d4c7b.svg" }, { k: 'C', img: "assets/hinhb3/d4c7c.svg" }, { k: 'D', img: "assets/hinhb3/d4c7d.svg" }], ans: "C", why: "Khối lập phương có 6 mặt là hình vuông bằng nhau, 8 đỉnh, 12 cạnh." },
    { sec: "Hình khối", name: "Câu 8", pts: 1, text: "Hình nào là khối hộp chữ nhật?", opts: [{ k: 'A', img: "assets/hinhb3/d4c8a.svg" }, { k: 'B', img: "assets/hinhb3/d4c8b.svg" }, { k: 'C', img: "assets/hinhb3/d4c8c.svg" }, { k: 'D', img: "assets/hinhb3/d4c8d.svg" }], ans: "D", why: "Khối hộp chữ nhật có 6 mặt là hình chữ nhật, 8 đỉnh, 12 cạnh." },
    { sec: "Hình khối", name: "Câu 9", pts: 1, text: "Hình nào là khối trụ?", opts: [{ k: 'A', img: "assets/hinhb3/d4c9a.svg" }, { k: 'B', img: "assets/hinhb3/d4c9b.svg" }, { k: 'C', img: "assets/hinhb3/d4c9c.svg" }, { k: 'D', img: "assets/hinhb3/d4c9d.svg" }], ans: "D", why: "Khối trụ có hai đáy hình tròn." },
    { sec: "Hình khối", name: "Câu 10", pts: 1, text: "Hình nào là khối cầu?", opts: [{ k: 'A', img: "assets/hinhb3/d4c10a.svg" }, { k: 'B', img: "assets/hinhb3/d4c10b.svg" }, { k: 'C', img: "assets/hinhb3/d4c10c.svg" }, { k: 'D', img: "assets/hinhb3/d4c10d.svg" }], ans: "C", why: "Khối cầu tròn đều." },
  ],
},
{
  id: 9515, title: "Đề 5 · Chu vi tam giác — tứ giác — hình vuông", time: 25,
  questions: [
    { sec: "Chu vi", name: "Câu 1", pts: 1, text: "Tính chu vi hình tứ giác ABCD có độ dài các cạnh ghi trên hình.", img: "assets/hinhb3/d5c1.svg", opts: o4("55 cm", "54 cm", "53 cm", "43 cm"), ans: "B", why: "Chu vi bằng tổng độ dài các cạnh: 11 + 14 + 14 + 15 = 54 (cm)." },
    { sec: "Chu vi", name: "Câu 2", pts: 1, text: "Tính chu vi hình tứ giác ABCD có độ dài các cạnh ghi trên hình.", img: "assets/hinhb3/d5c2.svg", opts: o4("36 m", "37 m", "35 m", "23 m"), ans: "A", why: "Chu vi bằng tổng độ dài các cạnh: 13 + 14 + 6 + 3 = 36 (m)." },
    { sec: "Chu vi", name: "Câu 3", pts: 1, text: "Tính chu vi hình tam giác ABC có độ dài các cạnh ghi trên hình.", img: "assets/hinhb3/d5c3.svg", opts: o4("21 cm", "22 cm", "20 cm", "16 cm"), ans: "A", why: "Chu vi bằng tổng độ dài các cạnh: 5 + 5 + 11 = 21 (cm)." },
    { sec: "Chu vi", name: "Câu 4", pts: 1, text: "Tính chu vi hình tứ giác ABCD có độ dài các cạnh ghi trên hình.", img: "assets/hinhb3/d5c4.svg", opts: o4("30 cm", "28 cm", "29 cm", "17 cm"), ans: "C", why: "Chu vi bằng tổng độ dài các cạnh: 12 + 7 + 3 + 7 = 29 (cm)." },
    { sec: "Chu vi", name: "Câu 5", pts: 1, text: "Tính chu vi hình tam giác ABC có độ dài các cạnh ghi trên hình.", img: "assets/hinhb3/d5c5.svg", opts: o4("26 cm", "24 cm", "22 cm", "25 cm"), ans: "D", why: "Chu vi bằng tổng độ dài các cạnh: 3 + 11 + 11 = 25 (cm)." },
    { sec: "Chu vi hình vuông", name: "Câu 6", pts: 1, text: "Hình vuông có chu vi 20 cm. Độ dài cạnh hình vuông là bao nhiêu?", img: "assets/hinhb3/d5c6.svg", opts: o4("10 cm", "20 cm", "5 cm", "6 cm"), ans: "C", why: "Cạnh = chu vi : 4 = 20 : 4 = 5 (cm)." },
    { sec: "Chu vi hình vuông", name: "Câu 7", pts: 1, text: "Tính chu vi hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d5c7.svg", opts: o4("48 cm", "144 cm", "24 cm", "50 cm"), ans: "A", why: "Chu vi hình vuông = cạnh × 4 = 12 × 4 = 48 (cm)." },
    { sec: "Chu vi hình vuông", name: "Câu 8", pts: 1, text: "Tính chu vi hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d5c8.svg", opts: o4("36 cm", "12 cm", "26 cm", "24 cm"), ans: "D", why: "Chu vi hình vuông = cạnh × 4 = 6 × 4 = 24 (cm)." },
    { sec: "Chu vi hình vuông", name: "Câu 9", pts: 1, text: "Tính chu vi hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d5c9.svg", opts: o4("9 cm", "6 cm", "14 cm", "12 cm"), ans: "D", why: "Chu vi hình vuông = cạnh × 4 = 3 × 4 = 12 (cm)." },
    { sec: "Chu vi hình vuông", name: "Câu 10", pts: 1, text: "Tính chu vi hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d5c10.svg", opts: o4("49 cm", "28 cm", "14 cm", "30 cm"), ans: "B", why: "Chu vi hình vuông = cạnh × 4 = 7 × 4 = 28 (cm)." },
  ],
},
{
  id: 9516, title: "Đề 6 · Diện tích theo ô vuông 1 cm²", time: 25,
  questions: [
    { sec: "Diện tích", name: "Câu 1", pts: 1, text: "Hình được tô màu xanh gồm các ô vuông 1 cm². Diện tích hình tô màu là bao nhiêu?", img: "assets/hinhb3/d6c1.svg", opts: o4("14 cm²", "15 cm²", "13 cm²", "1 cm²"), ans: "A", why: "Cả bảng có 5 × 3 = 15 ô, phần trắng bị cắt đi 1 × 1 = 1 ô. Còn lại 15 − 1 = 14 ô → 14 cm²." },
    { sec: "Diện tích", name: "Câu 2", pts: 1, text: "Hình được tô màu xanh gồm các ô vuông 1 cm². Diện tích hình tô màu là bao nhiêu?", img: "assets/hinhb3/d6c2.svg", opts: o4("16 cm²", "15 cm²", "13 cm²", "14 cm²"), ans: "D", why: "Cả bảng có 4 × 4 = 16 ô, phần trắng bị cắt đi 2 × 1 = 2 ô. Còn lại 16 − 2 = 14 ô → 14 cm²." },
    { sec: "Diện tích", name: "Câu 3", pts: 1, text: "Hình được tô màu xanh gồm các ô vuông 1 cm². Diện tích hình tô màu là bao nhiêu?", img: "assets/hinhb3/d6c3.svg", opts: o4("20 cm²", "19 cm²", "18 cm²", "17 cm²"), ans: "C", why: "Cả bảng có 5 × 4 = 20 ô, phần trắng bị cắt đi 1 × 2 = 2 ô. Còn lại 20 − 2 = 18 ô → 18 cm²." },
    { sec: "Diện tích", name: "Câu 4", pts: 1, text: "Hình được tô màu xanh gồm các ô vuông 1 cm². Diện tích hình tô màu là bao nhiêu?", img: "assets/hinhb3/d6c4.svg", opts: o4("26 cm²", "30 cm²", "27 cm²", "25 cm²"), ans: "A", why: "Cả bảng có 6 × 5 = 30 ô, phần trắng bị cắt đi 2 × 2 = 4 ô. Còn lại 30 − 4 = 26 ô → 26 cm²." },
    { sec: "Diện tích", name: "Câu 5", pts: 1, text: "Hình được tô màu xanh gồm các ô vuông 1 cm². Diện tích hình tô màu là bao nhiêu?", img: "assets/hinhb3/d6c5.svg", opts: o4("24 cm²", "23 cm²", "22 cm²", "21 cm²"), ans: "C", why: "Cả bảng có 6 × 4 = 24 ô, phần trắng bị cắt đi 1 × 2 = 2 ô. Còn lại 24 − 2 = 22 ô → 22 cm²." },
    { sec: "Diện tích", name: "Câu 6", pts: 1, text: "Hình được tô màu xanh gồm các ô vuông 1 cm². Diện tích hình tô màu là bao nhiêu?", img: "assets/hinhb3/d6c6.svg", opts: o4("28 cm²", "23 cm²", "21 cm²", "22 cm²"), ans: "D", why: "Cả bảng có 7 × 4 = 28 ô, phần trắng bị cắt đi 2 × 3 = 6 ô. Còn lại 28 − 6 = 22 ô → 22 cm²." },
    { sec: "Chu vi hình vuông", name: "Câu 7", pts: 1, text: "Tính chu vi hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d6c7.svg", opts: o4("9 cm", "12 cm", "6 cm", "14 cm"), ans: "B", why: "Chu vi hình vuông = cạnh × 4 = 3 × 4 = 12 (cm)." },
    { sec: "Chu vi hình vuông", name: "Câu 8", pts: 1, text: "Tính chu vi hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d6c8.svg", opts: o4("121 cm", "22 cm", "46 cm", "44 cm"), ans: "D", why: "Chu vi hình vuông = cạnh × 4 = 11 × 4 = 44 (cm)." },
    { sec: "Diện tích hình vuông", name: "Câu 9", pts: 1, text: "Tính diện tích hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d6c9.svg", opts: o4("4 cm²", "8 cm²", "6 cm²", "2 cm²"), ans: "A", why: "Diện tích hình vuông = cạnh × cạnh = 2 × 2 = 4 (cm²)." },
    { sec: "Chu vi hình vuông", name: "Câu 10", pts: 1, text: "Tính chu vi hình vuông có độ dài cạnh ghi trên hình.", img: "assets/hinhb3/d6c10.svg", opts: o4("9 cm", "6 cm", "12 cm", "14 cm"), ans: "C", why: "Chu vi hình vuông = cạnh × 4 = 3 × 4 = 12 (cm)." },
  ],
},
{
  id: 9517, title: "Đề 7 · Mi-li-mét — Gam", time: 25,
  questions: [
    { sec: "Mi-li-mét", name: "Câu 1", pts: 1, text: "Đặt con kiến (đoạn) dọc theo thước có vạch xăng-ti-mét (mỗi vạch nhỏ là 1 mm). Con kiến (đoạn) dài bao nhiêu mi-li-mét?", img: "assets/hinhb3/d7c1.svg", opts: o4("36 mm", "16 mm", "26 mm", "46 mm"), ans: "C", why: "Vật bắt đầu ở vạch 20 mm và kết thúc ở 46 mm: 46 − 20 = 26 mm. 1 cm = 10 mm nên 2 cm 6 mm = 26 mm." },
    { sec: "Mi-li-mét", name: "Câu 2", pts: 1, text: "Đặt con kiến (đoạn) dọc theo thước có vạch xăng-ti-mét (mỗi vạch nhỏ là 1 mm). Con kiến (đoạn) dài bao nhiêu?", img: "assets/hinhb3/d7c2.svg", opts: o4("4 cm 6 mm", "5 cm 6 mm", "4 cm 4 mm", "6 cm 4 mm"), ans: "A", why: "46 mm = 4 cm 6 mm (vì 1 cm = 10 mm)." },
    { sec: "Mi-li-mét", name: "Câu 3", pts: 1, text: "Đặt chiếc đinh dọc theo thước có vạch xăng-ti-mét (mỗi vạch nhỏ là 1 mm). Chiếc đinh dài bao nhiêu?", img: "assets/hinhb3/d7c3.svg", opts: o4("1 cm 9 mm", "2 cm 9 mm", "1 cm 1 mm", "9 cm 1 mm"), ans: "A", why: "19 mm = 1 cm 9 mm (vì 1 cm = 10 mm)." },
    { sec: "Mi-li-mét", name: "Câu 4", pts: 1, text: "Đặt cây bút chì dọc theo thước có vạch xăng-ti-mét (mỗi vạch nhỏ là 1 mm). Cây bút chì dài bao nhiêu?", img: "assets/hinhb3/d7c4.svg", opts: o4("3 cm 8 mm", "2 cm 8 mm", "2 cm 2 mm", "8 cm 2 mm"), ans: "B", why: "28 mm = 2 cm 8 mm (vì 1 cm = 10 mm)." },
    { sec: "Mi-li-mét", name: "Câu 5", pts: 1, text: "Đặt con kiến (đoạn) dọc theo thước có vạch xăng-ti-mét (mỗi vạch nhỏ là 1 mm). Con kiến (đoạn) dài bao nhiêu?", img: "assets/hinhb3/d7c5.svg", opts: o4("3 cm 4 mm", "4 cm 4 mm", "3 cm 6 mm", "4 cm 3 mm"), ans: "A", why: "34 mm = 3 cm 4 mm (vì 1 cm = 10 mm)." },
    { sec: "Gam", name: "Câu 6", pts: 1, text: "Cân đang thăng bằng như hình. Quả cam nặng bao nhiêu gam?", img: "assets/hinhb3/d7c6.svg", opts: o4("350 g", "150 g", "250 g", "450 g"), ans: "C", why: "quả cam + 100 g = 200 + 100 + 50 = 350 g nên quả cam nặng 350 − 100 = 250 (g)." },
    { sec: "Gam", name: "Câu 7", pts: 1, text: "Cân đang thăng bằng như hình. Túi kẹo nặng bao nhiêu gam?", img: "assets/hinhb3/d7c7.svg", opts: o4("250 g", "150 g", "50 g", "200 g"), ans: "B", why: "túi kẹo nặng bằng tổng các quả cân: 100 + 50 = 150 (g)." },
    { sec: "Gam", name: "Câu 8", pts: 1, text: "Cân đang thăng bằng như hình. Quyển sách nặng bao nhiêu gam?", img: "assets/hinhb3/d7c8.svg", opts: o4("650 g", "450 g", "600 g", "550 g"), ans: "D", why: "quyển sách nặng bằng tổng các quả cân: 500 + 50 = 550 (g)." },
    { sec: "Gam", name: "Câu 9", pts: 1, text: "Cân thăng bằng: bên trái là quả cân 1 kg, bên phải có gói hàng và các quả cân như hình. Gói hàng nặng bao nhiêu gam?", img: "assets/hinhb3/d7c9.svg", opts: o4("1500 g", "500 g", "600 g", "400 g"), ans: "B", why: "1 kg = 1000 g. Gói hàng + 500 = 1000 nên gói hàng nặng 1000 − 500 = 500 (g)." },
    { sec: "Gam", name: "Câu 10", pts: 1, text: "Cân thăng bằng: bên trái là quả cân 1 kg, bên phải có gói hàng và các quả cân như hình. Gói hàng nặng bao nhiêu gam?", img: "assets/hinhb3/d7c10.svg", opts: o4("1500 g", "600 g", "500 g", "400 g"), ans: "C", why: "1 kg = 1000 g. Gói hàng + 500 = 1000 nên gói hàng nặng 1000 − 500 = 500 (g)." },
  ],
},
{
  id: 9518, title: "Đề 8 · Mi-li-lít — Nhiệt độ", time: 25,
  questions: [
    { sec: "Mi-li-lít", name: "Câu 1", pts: 1, text: "Hai ca đong (mỗi vạch nhỏ 50 ml) đựng nước như hình. Đổ cả hai ca vào một bình thì bình có bao nhiêu mi-li-lít nước?", img: "assets/hinhb3/d8c1.svg", opts: o4("600 ml", "500 ml", "250 ml", "550 ml"), ans: "D", why: "Ca 1 có 150 ml, ca 2 có 400 ml: 150 + 400 = 550 (ml)." },
    { sec: "Mi-li-lít", name: "Câu 2", pts: 1, text: "Hai ca đong (mỗi vạch nhỏ 50 ml) đựng nước như hình. Đổ cả hai ca vào một bình thì bình có bao nhiêu mi-li-lít nước?", img: "assets/hinhb3/d8c2.svg", opts: o4("500 ml", "400 ml", "450 ml", "50 ml"), ans: "C", why: "Ca 1 có 250 ml, ca 2 có 200 ml: 250 + 200 = 450 (ml)." },
    { sec: "Mi-li-lít", name: "Câu 3", pts: 1, text: "Ca đựng nước như hình. Rót ra 350 ml. Trong ca còn lại bao nhiêu mi-li-lít?", img: "assets/hinhb3/d8c3.svg", opts: o4("1150 ml", "550 ml", "350 ml", "450 ml"), ans: "D", why: "Ca có 800 ml. Còn lại: 800 − 350 = 450 (ml)." },
    { sec: "Mi-li-lít", name: "Câu 4", pts: 1, text: "Hai ca đong (mỗi vạch nhỏ 50 ml) đựng nước như hình. Đổ cả hai ca vào một bình thì bình có bao nhiêu mi-li-lít nước?", img: "assets/hinhb3/d8c4.svg", opts: o4("600 ml", "550 ml", "500 ml", "50 ml"), ans: "B", why: "Ca 1 có 250 ml, ca 2 có 300 ml: 250 + 300 = 550 (ml)." },
    { sec: "Mi-li-lít", name: "Câu 5", pts: 1, text: "Ca đong có vạch chia, mỗi vạch nhỏ là 100 ml. Trong ca có bao nhiêu mi-li-lít nước?", img: "assets/hinhb3/d8c5.svg", opts: o4("800 ml", "900 ml", "700 ml", "1000 ml"), ans: "A", why: "Mặt nước ở vạch 800 (vạch có ghi số) → 800 ml." },
    { sec: "Nhiệt độ", name: "Câu 6", pts: 1, text: "Nhiệt kế đo nhiệt độ Hà Nội buổi trưa chỉ như hình (mỗi vạch nhỏ là 5 °C). Nhiệt độ đó là bao nhiêu?", img: "assets/hinhb3/d8c6.svg", opts: o4("10 °C", "5 °C", "0 °C", "15 °C"), ans: "B", why: "Cột màu đỏ dừng ở vạch 5 → 5 °C." },
    { sec: "Nhiệt độ", name: "Câu 7", pts: 1, text: "Hai nhiệt kế chỉ nhiệt độ buổi sáng và buổi trưa (mỗi vạch nhỏ 5 °C). Buổi trưa nóng hơn buổi sáng bao nhiêu độ?", img: "assets/hinhb3/d8c7.svg", opts: o4("10 °C", "15 °C", "5 °C", "20 °C"), ans: "A", why: "Sáng 5 °C, trưa 15 °C. Chênh lệch: 15 − 5 = 10 °C." },
    { sec: "Nhiệt độ", name: "Câu 8", pts: 1, text: "Nhiệt kế đo nhiệt độ trong tủ lạnh chỉ như hình (mỗi vạch nhỏ là 5 °C). Nhiệt độ đó là bao nhiêu?", img: "assets/hinhb3/d8c8.svg", opts: o4("0 °C", "5 °C", "10 °C", "1 °C"), ans: "A", why: "Cột màu đỏ dừng ở vạch 0 → 0 °C." },
    { sec: "Nhiệt độ", name: "Câu 9", pts: 1, text: "Nhiệt kế đo nhiệt độ ngoài trời hè chỉ như hình (mỗi vạch nhỏ là 5 °C). Nhiệt độ đó là bao nhiêu?", img: "assets/hinhb3/d8c9.svg", opts: o4("20 °C", "10 °C", "25 °C", "15 °C"), ans: "D", why: "Cột màu đỏ dừng ở vạch 15 → 15 °C." },
    { sec: "Nhiệt độ", name: "Câu 10", pts: 1, text: "Nhiệt kế đo nhiệt độ ngoài trời hè chỉ như hình (mỗi vạch nhỏ là 5 °C). Nhiệt độ đó là bao nhiêu?", img: "assets/hinhb3/d8c10.svg", opts: o4("10 °C", "0 °C", "5 °C", "15 °C"), ans: "C", why: "Cột màu đỏ dừng ở vạch 5 → 5 °C." },
  ],
},
{
  id: 9519, title: "Đề 9 · Tiền Việt Nam — Một phần mấy", time: 25,
  questions: [
    { sec: "Tiền Việt Nam", name: "Câu 1", pts: 1, text: "Long có các tờ tiền như hình. Long có tất cả bao nhiêu tiền?", img: "assets/hinhb3/d9c1.svg", opts: o4("66000 đồng", "65000 đồng", "64000 đồng", "75000 đồng"), ans: "B", why: "50000 + 5000 + 10000 = 65000 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 2", pts: 1, text: "Đức có các tờ tiền như hình và mua một quyển vở giá 8000 đồng. Đức còn lại bao nhiêu tiền?", img: "assets/hinhb3/d9c2.svg", opts: o4("39000 đồng", "37000 đồng", "54000 đồng", "38000 đồng"), ans: "D", why: "Có 46000 đồng, còn lại 46000 − 8000 = 38000 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 3", pts: 1, text: "Long có các tờ tiền như hình. Long có tất cả bao nhiêu tiền?", img: "assets/hinhb3/d9c3.svg", opts: o4("39000 đồng", "37000 đồng", "38000 đồng", "48000 đồng"), ans: "C", why: "10000 + 5000 + 1000 + 20000 + 2000 = 38000 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 4", pts: 1, text: "Mai có các tờ tiền như hình và mua một quyển vở giá 35000 đồng. Mai còn lại bao nhiêu tiền?", img: "assets/hinhb3/d9c4.svg", opts: o4("39000 đồng", "40000 đồng", "38000 đồng", "109000 đồng"), ans: "A", why: "Có 74000 đồng, còn lại 74000 − 35000 = 39000 (đồng)." },
    { sec: "Tiền Việt Nam", name: "Câu 5", pts: 1, text: "Long có các tờ tiền như hình. Long có tất cả bao nhiêu tiền?", img: "assets/hinhb3/d9c5.svg", opts: o4("173000 đồng", "174000 đồng", "172000 đồng", "183000 đồng"), ans: "A", why: "1000 + 50000 + 2000 + 50000 + 50000 + 20000 = 173000 (đồng)." },
    { sec: "Một phần mấy", name: "Câu 6", pts: 1, text: "Đã tô màu một phần mấy của hình?", img: "assets/hinhb3/d9c6.svg", opts: o4("1/4", "1/5", "1/2", "1/3"), ans: "D", why: "Hình được chia thành 3 phần bằng nhau, tô màu 1 phần → đã tô 1/3 hình." },
    { sec: "Một phần mấy", name: "Câu 7", pts: 1, text: "Đã tô màu một phần mấy của hình?", img: "assets/hinhb3/d9c7.svg", opts: o4("1/8", "1/7", "7/8", "1/9"), ans: "A", why: "Hình được chia thành 8 phần bằng nhau, tô màu 1 phần → đã tô 1/8 hình." },
    { sec: "Một phần mấy", name: "Câu 8", pts: 1, text: "Đã tô màu một phần mấy của hình?", img: "assets/hinhb3/d9c8.svg", opts: o4("5/6", "1/5", "1/6", "1/8"), ans: "C", why: "Hình được chia thành 6 phần bằng nhau, tô màu 1 phần → đã tô 1/6 hình." },
    { sec: "Một phần mấy", name: "Câu 9", pts: 1, text: "Đã tô màu một phần mấy của hình?", img: "assets/hinhb3/d9c9.svg", opts: o4("1/7", "1/6", "1/4", "1/5"), ans: "D", why: "Hình được chia thành 5 phần bằng nhau, tô màu 1 phần → đã tô 1/5 hình." },
    { sec: "Một phần mấy", name: "Câu 10", pts: 1, text: "Đã tô màu một phần mấy của hình?", img: "assets/hinhb3/d9c10.svg", opts: o4("1/3", "1/2", "1/1", "1/4"), ans: "B", why: "Hình được chia thành 2 phần bằng nhau, tô màu 1 phần → đã tô 1/2 hình." },
  ],
},
{
  id: 9520, title: "Đề 10 · Bảng số liệu — Khả năng xảy ra", time: 25,
  questions: [
    { sec: "Bảng số liệu", name: "Câu 1", pts: 1, text: "Bảng thống kê \"Số điểm 10 của lớp 3A trong 4 tuần\". Tuần nhiều nhất hơn tuần ít nhất bao nhiêu điểm 10?", img: "assets/hinhb3/d10c1.svg", opts: o4("21", "19", "20", "32"), ans: "C", why: "26 − 6 = 20." },
    { sec: "Bảng số liệu", name: "Câu 2", pts: 1, text: "Bảng thống kê \"Số điểm 10 của lớp 3A trong 4 tuần\". Tổng số điểm 10 của cả bốn tuần là bao nhiêu?", img: "assets/hinhb3/d10c2.svg", opts: o4("92", "102", "82", "93"), ans: "A", why: "28 + 20 + 23 + 21 = 92." },
    { sec: "Bảng số liệu", name: "Câu 3", pts: 1, text: "Bảng thống kê \"Số điểm 10 của lớp 3A trong 4 tuần\". Tuần 4 nhiều hơn Tuần 3 bao nhiêu điểm 10?", img: "assets/hinhb3/d10c3.svg", opts: o4("44", "3", "1", "2"), ans: "D", why: "23 − 21 = 2 (điểm 10)." },
    { sec: "Bảng số liệu", name: "Câu 4", pts: 1, text: "Bảng thống kê \"Số điểm 10 của lớp 3A trong 4 tuần\". Tuần 2 nhiều hơn Tuần 3 bao nhiêu điểm 10?", img: "assets/hinhb3/d10c4.svg", opts: o4("36", "22", "23", "21"), ans: "B", why: "29 − 7 = 22 (điểm 10)." },
    { sec: "Bảng số liệu", name: "Câu 5", pts: 1, text: "Bảng thống kê \"Số điểm 10 của lớp 3A trong 4 tuần\". Tổng số điểm 10 của cả bốn tuần là bao nhiêu?", img: "assets/hinhb3/d10c5.svg", opts: o4("82", "72", "62", "73"), ans: "B", why: "7 + 26 + 23 + 16 = 72." },
    { sec: "Bảng số liệu", name: "Câu 6", pts: 1, text: "Bảng thống kê \"Số điểm 10 của lớp 3A trong 4 tuần\". Tổng số điểm 10 của cả bốn tuần là bao nhiêu?", img: "assets/hinhb3/d10c6.svg", opts: o4("97", "77", "88", "87"), ans: "D", why: "28 + 9 + 24 + 26 = 87." },
    { sec: "Khả năng xảy ra", name: "Câu 7", pts: 1, text: "Quay vòng quay như hình. Kim KHÔNG THỂ dừng ở màu nào?", img: "assets/hinhb3/d10c7.svg", opts: o4("xanh", "vàng", "tím", "đỏ"), ans: "D", why: "Vòng quay chỉ có các màu xanh, vàng, tím; không có phần màu đỏ nên kim không thể dừng ở đó." },
    { sec: "Khả năng xảy ra", name: "Câu 8", pts: 1, text: "Quay vòng quay như hình. Kim KHÔNG THỂ dừng ở màu nào?", img: "assets/hinhb3/d10c8.svg", opts: o4("tím", "xanh", "vàng", "đỏ"), ans: "B", why: "Vòng quay chỉ có các màu tím, vàng, đỏ; không có phần màu xanh nên kim không thể dừng ở đó." },
    { sec: "Khả năng xảy ra", name: "Câu 9", pts: 1, text: "Quay vòng quay như hình (các phần bằng nhau). Kim có khả năng dừng ở màu nào ÍT nhất?", img: "assets/hinhb3/d10c9.svg", opts: o4("tím", "xanh", "vàng", "đỏ"), ans: "C", why: "Số phần mỗi màu: tím 3, xanh 2, vàng 1. Màu chiếm ít phần nhất có khả năng thấp nhất: vàng." },
    { sec: "Khả năng xảy ra", name: "Câu 10", pts: 1, text: "Quay vòng quay như hình. Kim KHÔNG THỂ dừng ở màu nào?", img: "assets/hinhb3/d10c10.svg", opts: o4("đỏ", "tím", "xanh", "vàng"), ans: "C", why: "Vòng quay chỉ có các màu đỏ, tím, vàng; không có phần màu xanh nên kim không thể dừng ở đó." },
  ],
},
];

SUBJECTS.push({
  id: 'hinhb3', name: 'Toán qua hình — Bài học', short: 'Bài học hình 3', icon: '🧩', grade: 3,
  exams: HINHB3_EXAMS, ready: true,
  heroTitle: "Toán lớp 3 qua hình — bài học: trung điểm, hình tròn, góc vuông, khối hộp, chu vi – diện tích, mm – g – ml – °C, tiền, bảng số liệu",
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; 🖼️ 100% câu có hình &nbsp;•&nbsp; ⏱ 25 phút mỗi đề',
});
