// TOÁN — LỚP 1 (GDPT 2018)
// 30 đề × 10 câu = 300 câu. Mỗi câu 1 điểm — thang 10 — 15 phút mỗi đề.
//
// Phạm vi lớp 1: các số đến 100; đếm – đọc – viết – so sánh số; cộng trừ (không nhớ)
// trong phạm vi 100 và cộng trừ trong phạm vi 20; hình phẳng và hình khối; đo độ dài (cm);
// xem giờ đúng; giải toán có lời văn đơn giản (thêm – bớt).

const TOAN1_EXAMS = [

/* ═══════════ ĐỀ 1 — ĐẾM, ĐỌC, VIẾT SỐ ĐẾN 10 ═══════════ */
{
  id: 6101, title: 'Đề 1 · Đếm và so sánh trong phạm vi 10', time: 15,
  questions: [
    { sec: 'Đếm', name: 'Câu 1', pts: 1, text: 'Có mấy quả táo? 🍎🍎🍎🍎🍎',
      opts: o4('3', '4', '5', '6'), ans: 'C', why: 'Đếm lần lượt: 1, 2, 3, 4, 5 — có 5 quả táo.' },
    { sec: 'Số liền sau', name: 'Câu 2', pts: 1, text: 'Số liền sau của số 6 là số nào?',
      opts: o4('5', '7', '6', '8'), ans: 'B', why: 'Số liền sau 6 là 7 (đếm thêm 1).' },
    { sec: 'Số liền trước', name: 'Câu 3', pts: 1, text: 'Số liền trước của số 9 là số nào?',
      opts: o4('10', '9', '8', '7'), ans: 'C', why: 'Số liền trước 9 là 8 (bớt đi 1).' },
    { sec: 'So sánh', name: 'Câu 4', pts: 1, text: 'Số bé nhất trong các số 3, 7, 2, 5 là số nào?',
      opts: o4('2', '3', '5', '7'), ans: 'A', why: 'Trong 3, 7, 2, 5 thì 2 là số bé nhất.' },
    { sec: 'So sánh', name: 'Câu 5', pts: 1, text: 'Số lớn nhất trong các số 8, 4, 9, 6 là số nào?',
      opts: o4('8', '4', '9', '6'), ans: 'C', why: 'Trong 8, 4, 9, 6 thì 9 là số lớn nhất.' },
    { sec: 'Đếm', name: 'Câu 6', pts: 1, text: 'Đếm ngược: 10, 9, 8, ... Số tiếp theo là số nào?',
      opts: o4('7', '11', '6', '9'), ans: 'A', why: 'Đếm ngược (bớt 1): sau 8 là 7.' },
    { sec: 'So sánh', name: 'Câu 7', pts: 1, text: 'Nhóm nào có nhiều cá hơn: 🐟🐟🐟 hay 🐟🐟?',
      opts: o4('Nhóm 🐟🐟🐟', 'Nhóm 🐟🐟', 'Hai nhóm bằng nhau', 'Không đếm được'), ans: 'A',
      why: 'Nhóm đầu có 3 con, nhóm sau có 2 con; 3 nhiều hơn 2.' },
    { sec: 'Số 0', name: 'Câu 8', pts: 1, text: 'Trong đĩa không có quả nào. Ta viết số mấy?',
      opts: o4('1', '0', '10', '2'), ans: 'B', why: 'Không có cái nào thì viết là số 0.' },
    { sec: 'Sắp xếp', name: 'Câu 9', pts: 1, text: 'Sắp xếp 5, 2, 8 theo thứ tự từ bé đến lớn:',
      opts: o4('2, 5, 8', '8, 5, 2', '5, 2, 8', '2, 8, 5'), ans: 'A', why: 'Từ bé đến lớn: 2, 5, 8.' },
    { sec: 'Đếm thêm', name: 'Câu 10', pts: 1, text: 'Có 4 bạn, thêm 1 bạn nữa. Có tất cả mấy bạn?',
      opts: o4('3', '4', '5', '6'), ans: 'C', why: 'Đếm thêm 1: 4 thêm 1 là 5 bạn.' },
  ],
},

/* ═══════════ ĐỀ 2 — CỘNG, TRỪ TRONG PHẠM VI 10 ═══════════ */
{
  id: 6102, title: 'Đề 2 · Cộng, trừ trong phạm vi 10', time: 15,
  questions: [
    { sec: 'Cộng', name: 'Câu 1', pts: 1, text: '2 + 3 = ?', opts: o4('4', '5', '6', '3'), ans: 'B', why: '2 + 3 = 5.' },
    { sec: 'Cộng', name: 'Câu 2', pts: 1, text: '4 + 5 = ?', opts: o4('8', '9', '10', '7'), ans: 'B', why: '4 + 5 = 9.' },
    { sec: 'Trừ', name: 'Câu 3', pts: 1, text: '7 − 2 = ?', opts: o4('4', '5', '6', '9'), ans: 'B', why: '7 − 2 = 5.' },
    { sec: 'Trừ', name: 'Câu 4', pts: 1, text: '10 − 4 = ?', opts: o4('5', '6', '7', '14'), ans: 'B', why: '10 − 4 = 6.' },
    { sec: 'Cộng', name: 'Câu 5', pts: 1, text: '6 + 4 = ?', opts: o4('9', '10', '11', '8'), ans: 'B', why: '6 + 4 = 10.' },
    { sec: 'Trừ', name: 'Câu 6', pts: 1, text: '8 − 3 = ?', opts: o4('4', '5', '6', '11'), ans: 'B', why: '8 − 3 = 5.' },
    { sec: 'Cộng', name: 'Câu 7', pts: 1, text: '3 + 3 = ?', opts: o4('5', '6', '7', '9'), ans: 'B', why: '3 + 3 = 6.' },
    { sec: 'Trừ', name: 'Câu 8', pts: 1, text: '9 − 9 = ?', opts: o4('0', '1', '9', '18'), ans: 'A', why: 'Một số trừ chính nó bằng 0: 9 − 9 = 0.' },
    { sec: 'Cộng với 0', name: 'Câu 9', pts: 1, text: '5 + 0 = ?', opts: o4('0', '5', '50', '6'), ans: 'B', why: 'Cộng với 0 giữ nguyên: 5 + 0 = 5.' },
    { sec: 'Cộng', name: 'Câu 10', pts: 1, text: '2 + 2 + 2 = ?', opts: o4('4', '6', '8', '2'), ans: 'B', why: '2 + 2 = 4, rồi 4 + 2 = 6.' },
  ],
},

/* ═══════════ ĐỀ 3 — CÁC SỐ ĐẾN 100: CHỤC VÀ ĐƠN VỊ ═══════════ */
{
  id: 6103, title: 'Đề 3 · Các số đến 100', time: 15,
  questions: [
    { sec: 'Cấu tạo số', name: 'Câu 1', pts: 1, text: 'Số 35 gồm mấy chục và mấy đơn vị?',
      opts: o4('5 chục 3 đơn vị', '3 chục 5 đơn vị', '35 chục', '3 đơn vị 5 chục'), ans: 'B',
      why: 'Số 35 có chữ số 3 ở hàng chục, chữ số 5 ở hàng đơn vị: 3 chục 5 đơn vị.' },
    { sec: 'Viết số', name: 'Câu 2', pts: 1, text: '4 chục 7 đơn vị viết là số nào?',
      opts: o4('74', '47', '407', '11'), ans: 'B', why: '4 chục và 7 đơn vị viết là 47.' },
    { sec: 'Viết số', name: 'Câu 3', pts: 1, text: 'Số gồm 6 chục và 0 đơn vị là số nào?',
      opts: o4('6', '16', '60', '66'), ans: 'C', why: '6 chục 0 đơn vị là 60.' },
    { sec: 'Số liền sau', name: 'Câu 4', pts: 1, text: 'Số liền sau của 49 là số nào?',
      opts: o4('48', '50', '59', '40'), ans: 'B', why: 'Liền sau 49 là 50.' },
    { sec: 'Số liền trước', name: 'Câu 5', pts: 1, text: 'Số liền trước của 70 là số nào?',
      opts: o4('71', '69', '60', '80'), ans: 'B', why: 'Liền trước 70 là 69.' },
    { sec: 'Đọc viết', name: 'Câu 6', pts: 1, text: '"Hai mươi mốt" viết là số nào?',
      opts: o4('12', '21', '20', '201'), ans: 'B', why: 'Hai mươi mốt viết là 21.' },
    { sec: 'Đọc viết', name: 'Câu 7', pts: 1, text: 'Số 90 đọc là gì?',
      opts: o4('Chín', 'Chín mươi', 'Chín trăm', 'Mười chín'), ans: 'B', why: 'Số 90 đọc là "chín mươi".' },
    { sec: 'Giá trị chữ số', name: 'Câu 8', pts: 1, text: 'Trong số 58, chữ số 5 chỉ mấy chục?',
      opts: o4('5 chục', '8 chục', '5 đơn vị', '50 chục'), ans: 'A', why: 'Chữ số 5 ở hàng chục nên chỉ 5 chục (tức 50).' },
    { sec: 'Số tròn chục', name: 'Câu 9', pts: 1, text: 'Số tròn chục lớn nhất có hai chữ số là số nào?',
      opts: o4('90', '99', '100', '80'), ans: 'A', why: 'Số tròn chục hai chữ số lớn nhất là 90 (100 có ba chữ số).' },
    { sec: 'Đếm thêm', name: 'Câu 10', pts: 1, text: 'Đếm thêm 10: 20, 30, 40, ... Số tiếp theo là?',
      opts: o4('41', '50', '45', '60'), ans: 'B', why: 'Thêm 10 vào 40 được 50.' },
  ],
},

/* ═══════════ ĐỀ 4 — SO SÁNH SỐ ĐẾN 100 ═══════════ */
{
  id: 6104, title: 'Đề 4 · So sánh các số đến 100', time: 15,
  questions: [
    { sec: 'So sánh', name: 'Câu 1', pts: 1, text: 'Điền dấu thích hợp: 34 ... 43',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B', why: '34 có 3 chục, 43 có 4 chục nên 34 < 43.' },
    { sec: 'So sánh', name: 'Câu 2', pts: 1, text: 'Điền dấu thích hợp: 76 ... 67',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'A', why: '76 có 7 chục, 67 có 6 chục nên 76 > 67.' },
    { sec: 'So sánh', name: 'Câu 3', pts: 1, text: 'Điền dấu thích hợp: 50 ... 50',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'C', why: 'Hai số bằng nhau nên 50 = 50.' },
    { sec: 'Lớn nhất', name: 'Câu 4', pts: 1, text: 'Số lớn nhất trong 45, 54, 50 là số nào?',
      opts: o4('45', '54', '50', 'Cả ba bằng nhau'), ans: 'B', why: '54 có 5 chục 4 đơn vị, lớn hơn 50 và 45.' },
    { sec: 'Bé nhất', name: 'Câu 5', pts: 1, text: 'Số bé nhất trong 38, 83, 80 là số nào?',
      opts: o4('38', '83', '80', 'Không có'), ans: 'A', why: '38 có 3 chục, bé hơn 80 và 83.' },
    { sec: 'So sánh', name: 'Câu 6', pts: 1, text: 'Điền dấu thích hợp: 29 ... 30',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B', why: '29 < 30 (29 đứng trước 30).' },
    { sec: 'So sánh', name: 'Câu 7', pts: 1, text: 'Điền dấu thích hợp: 99 ... 100',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B', why: '99 đứng trước 100 nên 99 < 100.' },
    { sec: 'Sắp xếp', name: 'Câu 8', pts: 1, text: 'Sắp xếp 60, 16, 61 từ bé đến lớn:',
      opts: o4('16, 60, 61', '60, 61, 16', '16, 61, 60', '61, 60, 16'), ans: 'A', why: 'Từ bé đến lớn: 16, 60, 61.' },
    { sec: 'Tìm số', name: 'Câu 9', pts: 1, text: 'Số nào lớn hơn 70?',
      opts: o4('68', '70', '72', '69'), ans: 'C', why: '72 lớn hơn 70; các số kia bằng hoặc bé hơn 70.' },
    { sec: 'Tìm số', name: 'Câu 10', pts: 1, text: 'Số nào bé hơn 25?',
      opts: o4('25', '52', '20', '30'), ans: 'C', why: '20 bé hơn 25; các số kia bằng hoặc lớn hơn.' },
  ],
},

/* ═══════════ ĐỀ 5 — CỘNG, TRỪ (KHÔNG NHỚ) TRONG PHẠM VI 100 ═══════════ */
{
  id: 6105, title: 'Đề 5 · Cộng, trừ trong phạm vi 100', time: 15,
  questions: [
    { sec: 'Cộng tròn chục', name: 'Câu 1', pts: 1, text: '30 + 20 = ?', opts: o4('40', '50', '60', '25'), ans: 'B', why: '3 chục cộng 2 chục là 5 chục: 30 + 20 = 50.' },
    { sec: 'Cộng', name: 'Câu 2', pts: 1, text: '45 + 3 = ?', opts: o4('48', '75', '42', '15'), ans: 'A', why: '45 + 3 = 48 (cộng ở hàng đơn vị).' },
    { sec: 'Trừ tròn chục', name: 'Câu 3', pts: 1, text: '60 − 40 = ?', opts: o4('20', '30', '100', '10'), ans: 'A', why: '6 chục trừ 4 chục là 2 chục: 60 − 40 = 20.' },
    { sec: 'Trừ', name: 'Câu 4', pts: 1, text: '57 − 5 = ?', opts: o4('52', '02', '62', '50'), ans: 'A', why: '57 − 5 = 52 (trừ ở hàng đơn vị).' },
    { sec: 'Cộng', name: 'Câu 5', pts: 1, text: '24 + 13 = ?', opts: o4('37', '27', '54', '11'), ans: 'A', why: '24 + 13: 4+3=7, 2+1=3 → 37.' },
    { sec: 'Trừ', name: 'Câu 6', pts: 1, text: '68 − 25 = ?', opts: o4('43', '33', '93', '53'), ans: 'A', why: '68 − 25: 8−5=3, 6−2=4 → 43.' },
    { sec: 'Cộng tròn chục', name: 'Câu 7', pts: 1, text: '40 + 50 = ?', opts: o4('80', '90', '100', '45'), ans: 'B', why: '4 chục cộng 5 chục là 9 chục: 40 + 50 = 90.' },
    { sec: 'Cộng', name: 'Câu 8', pts: 1, text: '33 + 33 = ?', opts: o4('66', '63', '96', '36'), ans: 'A', why: '33 + 33: 3+3=6, 3+3=6 → 66.' },
    { sec: 'Trừ', name: 'Câu 9', pts: 1, text: '99 − 9 = ?', opts: o4('90', '80', '9', '00'), ans: 'A', why: '99 − 9 = 90 (trừ ở hàng đơn vị).' },
    { sec: 'Cộng', name: 'Câu 10', pts: 1, text: '12 + 34 = ?', opts: o4('46', '44', '56', '22'), ans: 'A', why: '12 + 34: 2+4=6, 1+3=4 → 46.' },
  ],
},

/* ═══════════ ĐỀ 6 — CỘNG, TRỪ TRONG PHẠM VI 20 ═══════════ */
{
  id: 6106, title: 'Đề 6 · Cộng, trừ trong phạm vi 20', time: 15,
  questions: [
    { sec: 'Cộng qua 10', name: 'Câu 1', pts: 1, text: '8 + 5 = ?', opts: o4('12', '13', '14', '11'), ans: 'B', why: '8 + 2 = 10, còn 3 nữa là 13.' },
    { sec: 'Cộng qua 10', name: 'Câu 2', pts: 1, text: '9 + 6 = ?', opts: o4('14', '15', '16', '13'), ans: 'B', why: '9 + 1 = 10, còn 5 nữa là 15.' },
    { sec: 'Trừ qua 10', name: 'Câu 3', pts: 1, text: '15 − 7 = ?', opts: o4('7', '8', '9', '6'), ans: 'B', why: '15 − 5 = 10, trừ tiếp 2 còn 8.' },
    { sec: 'Trừ qua 10', name: 'Câu 4', pts: 1, text: '13 − 4 = ?', opts: o4('8', '9', '10', '7'), ans: 'B', why: '13 − 3 = 10, trừ tiếp 1 còn 9.' },
    { sec: 'Cộng', name: 'Câu 5', pts: 1, text: '7 + 7 = ?', opts: o4('13', '14', '15', '12'), ans: 'B', why: '7 + 7 = 14.' },
    { sec: 'Trừ', name: 'Câu 6', pts: 1, text: '16 − 8 = ?', opts: o4('7', '8', '9', '6'), ans: 'B', why: '16 − 8 = 8.' },
    { sec: 'Cộng', name: 'Câu 7', pts: 1, text: '9 + 9 = ?', opts: o4('17', '18', '19', '16'), ans: 'B', why: '9 + 9 = 18.' },
    { sec: 'Trừ', name: 'Câu 8', pts: 1, text: '11 − 3 = ?', opts: o4('7', '8', '9', '14'), ans: 'B', why: '11 − 1 = 10, trừ tiếp 2 còn 8.' },
    { sec: 'Cộng', name: 'Câu 9', pts: 1, text: '6 + 8 = ?', opts: o4('13', '14', '15', '12'), ans: 'B', why: '6 + 4 = 10, còn 4 nữa là 14.' },
    { sec: 'Trừ', name: 'Câu 10', pts: 1, text: '20 − 5 = ?', opts: o4('14', '15', '16', '25'), ans: 'B', why: '20 − 5 = 15.' },
  ],
},

/* ═══════════ ĐỀ 7 — HÌNH PHẲNG VÀ HÌNH KHỐI ═══════════ */
{
  id: 6107, title: 'Đề 7 · Hình phẳng và hình khối', time: 15,
  questions: [
    { sec: 'Hình phẳng', name: 'Câu 1', pts: 1, text: 'Hình có 3 cạnh là hình gì?',
      opts: o4('Hình tròn', 'Hình tam giác', 'Hình vuông', 'Hình chữ nhật'), ans: 'B', why: 'Hình tam giác có 3 cạnh.' },
    { sec: 'Hình phẳng', name: 'Câu 2', pts: 1, text: 'Hình có 4 cạnh bằng nhau và 4 góc vuông là hình gì?',
      opts: o4('Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình bầu dục'), ans: 'A', why: 'Hình vuông có 4 cạnh bằng nhau và 4 góc vuông.' },
    { sec: 'Hình phẳng', name: 'Câu 3', pts: 1, text: 'Mặt quyển sách, mặt bàn thường có dạng hình gì?',
      opts: o4('Hình tròn', 'Hình tam giác', 'Hình chữ nhật', 'Hình cầu'), ans: 'C', why: 'Mặt sách, mặt bàn thường có dạng hình chữ nhật.' },
    { sec: 'Hình phẳng', name: 'Câu 4', pts: 1, text: 'Mặt đồng hồ, bánh xe có dạng hình gì?',
      opts: o4('Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình chữ nhật'), ans: 'B', why: 'Mặt đồng hồ, bánh xe có dạng hình tròn.' },
    { sec: 'Hình khối', name: 'Câu 5', pts: 1, text: 'Quả bóng có dạng khối gì?',
      opts: o4('Khối lập phương', 'Khối hộp chữ nhật', 'Khối cầu', 'Khối trụ'), ans: 'C', why: 'Quả bóng có dạng khối cầu.' },
    { sec: 'Hình khối', name: 'Câu 6', pts: 1, text: 'Viên xúc xắc (6 mặt đều là hình vuông) có dạng khối gì?',
      opts: o4('Khối lập phương', 'Khối cầu', 'Khối trụ', 'Khối hộp chữ nhật'), ans: 'A', why: 'Xúc xắc có 6 mặt hình vuông bằng nhau nên là khối lập phương.' },
    { sec: 'Hình khối', name: 'Câu 7', pts: 1, text: 'Hộp bánh dài, các mặt là hình chữ nhật có dạng khối gì?',
      opts: o4('Khối cầu', 'Khối hộp chữ nhật', 'Khối trụ', 'Khối lập phương'), ans: 'B', why: 'Hộp có các mặt hình chữ nhật là khối hộp chữ nhật.' },
    { sec: 'Hình khối', name: 'Câu 8', pts: 1, text: 'Lon nước ngọt có dạng khối gì?',
      opts: o4('Khối trụ', 'Khối cầu', 'Khối lập phương', 'Khối hộp chữ nhật'), ans: 'A', why: 'Lon nước có dạng khối trụ.' },
    { sec: 'Hình phẳng', name: 'Câu 9', pts: 1, text: 'Hình tam giác có mấy cạnh?',
      opts: o4('2', '3', '4', '5'), ans: 'B', why: 'Hình tam giác có 3 cạnh.' },
    { sec: 'Hình phẳng', name: 'Câu 10', pts: 1, text: 'Hình vuông có mấy đỉnh (góc)?',
      opts: o4('3', '4', '5', '6'), ans: 'B', why: 'Hình vuông có 4 đỉnh và 4 góc.' },
  ],
},

/* ═══════════ ĐỀ 8 — ĐO ĐỘ DÀI VÀ XEM GIỜ ═══════════ */
{
  id: 6108, title: 'Đề 8 · Đo độ dài và xem giờ đúng', time: 15,
  questions: [
    { sec: 'Đo độ dài', name: 'Câu 1', pts: 1, text: 'Đơn vị đo độ dài đã học ở lớp 1 là gì?',
      opts: o4('Ki-lô-gam', 'Xăng-ti-mét (cm)', 'Lít', 'Giờ'), ans: 'B', why: 'Ở lớp 1, đơn vị đo độ dài là xăng-ti-mét, viết tắt là cm.' },
    { sec: 'Đo độ dài', name: 'Câu 2', pts: 1, text: 'Bút chì dài 10 ... . Điền đơn vị thích hợp:',
      opts: o4('cm', 'kg', 'giờ', 'lít'), ans: 'A', why: 'Độ dài bút chì đo bằng cm: bút chì dài 10 cm.' },
    { sec: 'Xem giờ', name: 'Câu 3', pts: 1, text: 'Kim ngắn chỉ số 3, kim dài chỉ số 12. Đồng hồ chỉ mấy giờ?',
      opts: o4('3 giờ', '12 giờ', '9 giờ', '6 giờ'), ans: 'A', why: 'Kim dài chỉ 12, kim ngắn chỉ 3 là 3 giờ đúng.' },
    { sec: 'Xem giờ', name: 'Câu 4', pts: 1, text: 'Đồng hồ chỉ 9 giờ đúng thì kim ngắn chỉ vào số mấy?',
      opts: o4('12', '9', '3', '6'), ans: 'B', why: 'Lúc 9 giờ đúng, kim ngắn chỉ số 9.' },
    { sec: 'So sánh độ dài', name: 'Câu 5', pts: 1, text: 'Đoạn thẳng AB dài 5 cm, đoạn CD dài 8 cm. Đoạn nào dài hơn?',
      opts: o4('Đoạn AB', 'Đoạn CD', 'Hai đoạn bằng nhau', 'Không biết'), ans: 'B', why: '8 cm dài hơn 5 cm nên đoạn CD dài hơn.' },
    { sec: 'Ước lượng', name: 'Câu 6', pts: 1, text: 'Buổi sáng em thường thức dậy đi học lúc khoảng mấy giờ?',
      opts: o4('6 giờ sáng', '12 giờ đêm', '9 giờ tối', '3 giờ đêm'), ans: 'A', why: 'Buổi sáng đi học thường thức dậy khoảng 6 giờ.' },
    { sec: 'Xem giờ', name: 'Câu 7', pts: 1, text: 'Khi đồng hồ chỉ giờ đúng thì kim dài (kim phút) chỉ vào số mấy?',
      opts: o4('12', '6', '3', '9'), ans: 'A', why: 'Giờ đúng thì kim dài luôn chỉ số 12.' },
    { sec: 'Dụng cụ', name: 'Câu 8', pts: 1, text: 'Thước kẻ dùng để làm gì?',
      opts: o4('Đo độ dài và kẻ đường thẳng', 'Đo cân nặng', 'Xem giờ', 'Đong nước'), ans: 'A', why: 'Thước kẻ dùng để đo độ dài và kẻ đường thẳng.' },
    { sec: 'Cộng độ dài', name: 'Câu 9', pts: 1, text: '3 cm + 4 cm = ?',
      opts: o4('7 cm', '1 cm', '34 cm', '7'), ans: 'A', why: '3 cm + 4 cm = 7 cm.' },
    { sec: 'Trừ độ dài', name: 'Câu 10', pts: 1, text: '9 cm − 6 cm = ?',
      opts: o4('3 cm', '15 cm', '2 cm', '96 cm'), ans: 'A', why: '9 cm − 6 cm = 3 cm.' },
  ],
},

/* ═══════════ ĐỀ 9 — TOÁN CÓ LỜI VĂN ═══════════ */
{
  id: 6109, title: 'Đề 9 · Bài toán có lời văn', time: 15,
  questions: [
    { sec: 'Bớt', name: 'Câu 1', pts: 1, text: 'Lan có 5 bông hoa, cho bạn 2 bông. Lan còn lại mấy bông hoa?',
      opts: o4('2', '3', '7', '4'), ans: 'B', why: 'Còn lại: 5 − 2 = 3 (bông hoa).' },
    { sec: 'Thêm', name: 'Câu 2', pts: 1, text: 'Có 4 con gà, mua thêm 3 con. Có tất cả mấy con gà?',
      opts: o4('6', '7', '1', '8'), ans: 'B', why: 'Tất cả: 4 + 3 = 7 (con gà).' },
    { sec: 'Bớt', name: 'Câu 3', pts: 1, text: 'Trên cây có 8 quả, rụng mất 2 quả. Trên cây còn mấy quả?',
      opts: o4('5', '6', '10', '4'), ans: 'B', why: 'Còn lại: 8 − 2 = 6 (quả).' },
    { sec: 'Gộp', name: 'Câu 4', pts: 1, text: 'Hộp có 6 bút xanh và 3 bút đỏ. Hộp có tất cả mấy bút?',
      opts: o4('8', '9', '3', '10'), ans: 'B', why: 'Tất cả: 6 + 3 = 9 (cái bút).' },
    { sec: 'Bớt', name: 'Câu 5', pts: 1, text: 'Có 10 cái kẹo, ăn hết 4 cái. Còn lại mấy cái kẹo?',
      opts: o4('5', '6', '14', '4'), ans: 'B', why: 'Còn lại: 10 − 4 = 6 (cái kẹo).' },
    { sec: 'Gộp', name: 'Câu 6', pts: 1, text: 'Tổ 1 có 5 bạn, tổ 2 có 5 bạn. Cả hai tổ có mấy bạn?',
      opts: o4('9', '10', '11', '5'), ans: 'B', why: 'Cả hai tổ: 5 + 5 = 10 (bạn).' },
    { sec: 'Tìm số', name: 'Câu 7', pts: 1, text: 'Nam có 7 viên bi, nhiều hơn Hùng 2 viên. Hùng có mấy viên bi?',
      opts: o4('9', '5', '2', '7'), ans: 'B', why: 'Hùng có ít hơn: 7 − 2 = 5 (viên bi).' },
    { sec: 'Tìm số', name: 'Câu 8', pts: 1, text: 'Lớp có 9 bạn, trong đó 4 bạn là nữ. Có mấy bạn nam?',
      opts: o4('4', '5', '13', '6'), ans: 'B', why: 'Số bạn nam: 9 − 4 = 5 (bạn).' },
    { sec: 'Chục', name: 'Câu 9', pts: 1, text: 'Mẹ mua 3 chục quả trứng. Mẹ mua mấy quả trứng?',
      opts: o4('3', '13', '30', '33'), ans: 'C', why: '1 chục là 10, nên 3 chục là 30 quả trứng.' },
    { sec: 'Gộp', name: 'Câu 10', pts: 1, text: 'Có 2 đĩa, mỗi đĩa 5 quả cam. Có tất cả mấy quả cam?',
      opts: o4('7', '10', '25', '5'), ans: 'B', why: 'Hai đĩa: 5 + 5 = 10 (quả cam).' },
  ],
},

/* ═══════════ ĐỀ 10 — ÔN TẬP TỔNG HỢP ═══════════ */
{
  id: 6110, title: 'Đề 10 · Ôn tập tổng hợp', time: 15,
  questions: [
    { sec: 'Số', name: 'Câu 1', pts: 1, text: 'Số liền sau của 99 là số nào?', opts: o4('98', '100', '90', '109'), ans: 'B', why: 'Liền sau 99 là 100.' },
    { sec: 'Cộng', name: 'Câu 2', pts: 1, text: '40 + 30 = ?', opts: o4('70', '60', '10', '80'), ans: 'A', why: '4 chục cộng 3 chục là 7 chục: 70.' },
    { sec: 'Trừ', name: 'Câu 3', pts: 1, text: '18 − 9 = ?', opts: o4('8', '9', '10', '27'), ans: 'B', why: '18 − 9 = 9.' },
    { sec: 'Hình', name: 'Câu 4', pts: 1, text: 'Hình có 3 cạnh là hình gì?', opts: o4('Hình vuông', 'Hình tam giác', 'Hình tròn', 'Hình chữ nhật'), ans: 'B', why: 'Hình tam giác có 3 cạnh.' },
    { sec: 'So sánh', name: 'Câu 5', pts: 1, text: 'Điền dấu: 25 ... 52', opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B', why: '25 có 2 chục, 52 có 5 chục nên 25 < 52.' },
    { sec: 'Chục', name: 'Câu 6', pts: 1, text: '6 chục bằng bao nhiêu?', opts: o4('6', '16', '60', '66'), ans: 'C', why: '6 chục là 60.' },
    { sec: 'Cộng', name: 'Câu 7', pts: 1, text: '5 + 4 = ?', opts: o4('8', '9', '10', '1'), ans: 'B', why: '5 + 4 = 9.' },
    { sec: 'Hình khối', name: 'Câu 8', pts: 1, text: 'Quả bóng có dạng khối gì?', opts: o4('Khối lập phương', 'Khối trụ', 'Khối cầu', 'Khối hộp'), ans: 'C', why: 'Quả bóng có dạng khối cầu.' },
    { sec: 'Lời văn', name: 'Câu 9', pts: 1, text: 'Có 7 con vịt, 2 con lên bờ. Dưới ao còn mấy con vịt?', opts: o4('5', '9', '4', '2'), ans: 'A', why: 'Còn lại: 7 − 2 = 5 (con vịt).' },
    { sec: 'Cộng', name: 'Câu 10', pts: 1, text: '3 + 3 + 3 = ?', opts: o4('6', '9', '12', '3'), ans: 'B', why: '3 + 3 = 6, rồi 6 + 3 = 9.' },
  ],
},

/* ═══════════ ĐỀ 11 — ĐẾM VÀ SO SÁNH TRONG PHẠM VI 20 ═══════════ */
{
  id: 8701, title: 'Đề 11 · Đếm và so sánh trong phạm vi 20', time: 15,
  questions: [
    { sec: 'Đếm', name: 'Câu 1', pts: 1, text: 'Có mấy ngôi sao? ⭐⭐⭐⭐⭐⭐⭐',
      opts: o4('6', '7', '8', '5'), ans: 'B', why: 'Đếm lần lượt được 7 ngôi sao.' },
    { sec: 'Số liền sau', name: 'Câu 2', pts: 1, text: 'Số liền sau của 14 là số nào?',
      opts: o4('13', '15', '16', '14'), ans: 'B', why: 'Liền sau 14 là 15 (thêm 1).' },
    { sec: 'Số liền trước', name: 'Câu 3', pts: 1, text: 'Số liền trước của 20 là số nào?',
      opts: o4('21', '18', '19', '10'), ans: 'C', why: 'Liền trước 20 là 19 (bớt 1).' },
    { sec: 'So sánh', name: 'Câu 4', pts: 1, text: 'Số lớn nhất trong 12, 18, 15 là số nào?',
      opts: o4('12', '15', '18', 'Bằng nhau'), ans: 'C', why: '18 lớn hơn 15 và 12.' },
    { sec: 'So sánh', name: 'Câu 5', pts: 1, text: 'Số bé nhất trong 17, 11, 14 là số nào?',
      opts: o4('11', '14', '17', 'Không có'), ans: 'A', why: '11 bé hơn 14 và 17.' },
    { sec: 'So sánh', name: 'Câu 6', pts: 1, text: 'Điền dấu: 13 ... 16',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B', why: '13 bé hơn 16 nên 13 < 16.' },
    { sec: 'Đếm', name: 'Câu 7', pts: 1, text: 'Đếm tiếp: 16, 17, 18, ... Số tiếp theo là?',
      opts: o4('19', '15', '20', '17'), ans: 'A', why: 'Thêm 1 vào 18 được 19.' },
    { sec: 'Sắp xếp', name: 'Câu 8', pts: 1, text: 'Sắp xếp 19, 11, 15 từ bé đến lớn:',
      opts: o4('11, 15, 19', '19, 15, 11', '15, 11, 19', '11, 19, 15'), ans: 'A', why: 'Từ bé đến lớn: 11, 15, 19.' },
    { sec: 'Chục đơn vị', name: 'Câu 9', pts: 1, text: 'Số 13 gồm mấy chục và mấy đơn vị?',
      opts: o4('3 chục 1 đơn vị', '1 chục 3 đơn vị', '13 chục', '1 đơn vị 3 chục'), ans: 'B', why: 'Số 13 có 1 chục và 3 đơn vị.' },
    { sec: 'Đếm', name: 'Câu 10', pts: 1, text: 'Số nào đứng giữa 15 và 17?',
      opts: o4('14', '16', '18', '15'), ans: 'B', why: 'Giữa 15 và 17 là số 16.' },
  ],
},

/* ═══════════ ĐỀ 12 — CẤU TẠO SỐ: CHỤC VÀ ĐƠN VỊ ═══════════ */
{
  id: 8702, title: 'Đề 12 · Cấu tạo số (chục và đơn vị)', time: 15,
  questions: [
    { sec: 'Cấu tạo số', name: 'Câu 1', pts: 1, text: 'Số 42 gồm mấy chục và mấy đơn vị?',
      opts: o4('4 chục 2 đơn vị', '2 chục 4 đơn vị', '42 chục', '4 đơn vị 2 chục'), ans: 'A', why: 'Số 42 có 4 chục và 2 đơn vị.' },
    { sec: 'Viết số', name: 'Câu 2', pts: 1, text: '5 chục 8 đơn vị viết là số nào?',
      opts: o4('85', '58', '508', '13'), ans: 'B', why: '5 chục 8 đơn vị viết là 58.' },
    { sec: 'Viết số', name: 'Câu 3', pts: 1, text: 'Số gồm 7 chục và 0 đơn vị là số nào?',
      opts: o4('7', '17', '77', '70'), ans: 'D', why: '7 chục 0 đơn vị là 70.' },
    { sec: 'Giá trị chữ số', name: 'Câu 4', pts: 1, text: 'Trong số 63, chữ số 3 chỉ mấy đơn vị?',
      opts: o4('3 chục', '3 đơn vị', '6 đơn vị', '30 đơn vị'), ans: 'B', why: 'Chữ số 3 ở hàng đơn vị nên chỉ 3 đơn vị.' },
    { sec: 'Giá trị chữ số', name: 'Câu 5', pts: 1, text: 'Trong số 29, chữ số 2 chỉ mấy chục?',
      opts: o4('9 chục', '2 đơn vị', '2 chục', '20 chục'), ans: 'C', why: 'Chữ số 2 ở hàng chục nên chỉ 2 chục.' },
    { sec: 'Đọc viết', name: 'Câu 6', pts: 1, text: '"Ba mươi tư" viết là số nào?',
      opts: o4('43', '34', '30', '304'), ans: 'B', why: 'Ba mươi tư viết là 34.' },
    { sec: 'Đọc viết', name: 'Câu 7', pts: 1, text: 'Số 80 đọc là gì?',
      opts: o4('Tám', 'Tám mươi', 'Tám trăm', 'Mười tám'), ans: 'B', why: 'Số 80 đọc là "tám mươi".' },
    { sec: 'Số tròn chục', name: 'Câu 8', pts: 1, text: 'Số tròn chục liền sau 50 là số nào?',
      opts: o4('51', '40', '60', '55'), ans: 'C', why: 'Số tròn chục liền sau 50 là 60.' },
    { sec: 'Cấu tạo số', name: 'Câu 9', pts: 1, text: 'Số nào có 9 chục và 9 đơn vị?',
      opts: o4('9', '90', '99', '18'), ans: 'C', why: '9 chục 9 đơn vị là 99.' },
    { sec: 'Chục', name: 'Câu 10', pts: 1, text: '1 chục bằng bao nhiêu đơn vị?',
      opts: o4('1', '10', '100', '11'), ans: 'B', why: '1 chục bằng 10 đơn vị.' },
  ],
},

/* ═══════════ ĐỀ 13 — SỐ LIỀN TRƯỚC, LIỀN SAU, DÃY SỐ ═══════════ */
{
  id: 8703, title: 'Đề 13 · Số liền trước, liền sau và dãy số', time: 15,
  questions: [
    { sec: 'Số liền sau', name: 'Câu 1', pts: 1, text: 'Số liền sau của 39 là số nào?',
      opts: o4('38', '40', '49', '30'), ans: 'B', why: 'Liền sau 39 là 40.' },
    { sec: 'Số liền trước', name: 'Câu 2', pts: 1, text: 'Số liền trước của 50 là số nào?',
      opts: o4('51', '49', '40', '60'), ans: 'B', why: 'Liền trước 50 là 49.' },
    { sec: 'Điền số', name: 'Câu 3', pts: 1, text: 'Điền số còn thiếu: 25, 26, ..., 28',
      opts: o4('27', '29', '24', '30'), ans: 'A', why: 'Dãy đếm thêm 1, sau 26 là 27.' },
    { sec: 'Điền số', name: 'Câu 4', pts: 1, text: 'Điền số còn thiếu: 10, 20, ..., 40',
      opts: o4('25', '30', '35', '45'), ans: 'B', why: 'Dãy đếm thêm 10, sau 20 là 30.' },
    { sec: 'Dãy số', name: 'Câu 5', pts: 1, text: 'Đếm ngược: 15, 14, 13, ... Số tiếp theo là?',
      opts: o4('12', '16', '11', '14'), ans: 'A', why: 'Đếm ngược bớt 1: sau 13 là 12.' },
    { sec: 'Điền số', name: 'Câu 6', pts: 1, text: 'Điền số còn thiếu: 47, 48, 49, ...',
      opts: o4('46', '50', '59', '40'), ans: 'B', why: 'Đếm thêm 1: sau 49 là 50.' },
    { sec: 'Dãy số', name: 'Câu 7', pts: 1, text: 'Số ở giữa 60 và 62 là số nào?',
      opts: o4('59', '61', '63', '60'), ans: 'B', why: 'Giữa 60 và 62 là 61.' },
    { sec: 'Điền số', name: 'Câu 8', pts: 1, text: 'Điền số còn thiếu: 5, 10, 15, ...',
      opts: o4('16', '20', '25', '18'), ans: 'B', why: 'Đếm thêm 5: sau 15 là 20.' },
    { sec: 'Số liền sau', name: 'Câu 9', pts: 1, text: 'Số liền sau số lớn nhất có một chữ số là số nào?',
      opts: o4('8', '9', '10', '11'), ans: 'C', why: 'Số lớn nhất có một chữ số là 9, liền sau là 10.' },
    { sec: 'Số liền trước', name: 'Câu 10', pts: 1, text: 'Số liền trước số bé nhất có hai chữ số là số nào?',
      opts: o4('9', '10', '11', '99'), ans: 'A', why: 'Số bé nhất có hai chữ số là 10, liền trước là 9.' },
  ],
},

/* ═══════════ ĐỀ 14 — CỘNG, TRỪ TRONG PHẠM VI 10 ═══════════ */
{
  id: 8704, title: 'Đề 14 · Cộng, trừ trong phạm vi 10', time: 15,
  questions: [
    { sec: 'Cộng', name: 'Câu 1', pts: 1, text: '3 + 4 = ?', opts: o4('6', '7', '8', '5'), ans: 'B', why: '3 + 4 = 7.' },
    { sec: 'Cộng', name: 'Câu 2', pts: 1, text: '5 + 5 = ?', opts: o4('9', '11', '10', '8'), ans: 'C', why: '5 + 5 = 10.' },
    { sec: 'Trừ', name: 'Câu 3', pts: 1, text: '8 − 5 = ?', opts: o4('2', '4', '3', '13'), ans: 'C', why: '8 − 5 = 3.' },
    { sec: 'Trừ', name: 'Câu 4', pts: 1, text: '10 − 7 = ?', opts: o4('3', '4', '2', '17'), ans: 'A', why: '10 − 7 = 3.' },
    { sec: 'Cộng', name: 'Câu 5', pts: 1, text: '2 + 6 = ?', opts: o4('7', '9', '8', '4'), ans: 'C', why: '2 + 6 = 8.' },
    { sec: 'Trừ', name: 'Câu 6', pts: 1, text: '9 − 4 = ?', opts: o4('5', '6', '4', '13'), ans: 'A', why: '9 − 4 = 5.' },
    { sec: 'Cộng với 0', name: 'Câu 7', pts: 1, text: '0 + 7 = ?', opts: o4('0', '17', '7', '8'), ans: 'C', why: 'Cộng với 0 giữ nguyên: 0 + 7 = 7.' },
    { sec: 'Trừ', name: 'Câu 8', pts: 1, text: '6 − 6 = ?', opts: o4('0', '6', '12', '1'), ans: 'A', why: 'Một số trừ chính nó bằng 0.' },
    { sec: 'Cộng', name: 'Câu 9', pts: 1, text: '4 + 4 = ?', opts: o4('7', '8', '9', '6'), ans: 'B', why: '4 + 4 = 8.' },
    { sec: 'Tìm số', name: 'Câu 10', pts: 1, text: '3 + ... = 9. Số cần điền là?', opts: o4('5', '6', '7', '4'), ans: 'B', why: '9 − 3 = 6 nên điền 6.' },
  ],
},

/* ═══════════ ĐỀ 15 — CỘNG, TRỪ TRONG PHẠM VI 20 ═══════════ */
{
  id: 8705, title: 'Đề 15 · Cộng, trừ trong phạm vi 20', time: 15,
  questions: [
    { sec: 'Cộng qua 10', name: 'Câu 1', pts: 1, text: '7 + 6 = ?', opts: o4('12', '13', '14', '11'), ans: 'B', why: '7 + 3 = 10, còn 3 nữa là 13.' },
    { sec: 'Cộng qua 10', name: 'Câu 2', pts: 1, text: '8 + 8 = ?', opts: o4('15', '16', '17', '14'), ans: 'B', why: '8 + 8 = 16.' },
    { sec: 'Trừ qua 10', name: 'Câu 3', pts: 1, text: '14 − 6 = ?', opts: o4('7', '9', '8', '6'), ans: 'C', why: '14 − 4 = 10, trừ tiếp 2 còn 8.' },
    { sec: 'Trừ qua 10', name: 'Câu 4', pts: 1, text: '17 − 9 = ?', opts: o4('8', '9', '7', '6'), ans: 'A', why: '17 − 7 = 10, trừ tiếp 2 còn 8.' },
    { sec: 'Cộng', name: 'Câu 5', pts: 1, text: '9 + 8 = ?', opts: o4('16', '18', '17', '15'), ans: 'C', why: '9 + 1 = 10, còn 7 nữa là 17.' },
    { sec: 'Trừ', name: 'Câu 6', pts: 1, text: '12 − 5 = ?', opts: o4('6', '7', '8', '17'), ans: 'B', why: '12 − 2 = 10, trừ tiếp 3 còn 7.' },
    { sec: 'Cộng', name: 'Câu 7', pts: 1, text: '6 + 9 = ?', opts: o4('14', '15', '16', '13'), ans: 'B', why: '6 + 4 = 10, còn 5 nữa là 15.' },
    { sec: 'Trừ', name: 'Câu 8', pts: 1, text: '18 − 9 = ?', opts: o4('8', '9', '10', '7'), ans: 'B', why: '18 − 9 = 9.' },
    { sec: 'Cộng', name: 'Câu 9', pts: 1, text: '5 + 7 = ?', opts: o4('11', '12', '13', '10'), ans: 'B', why: '5 + 5 = 10, còn 2 nữa là 12.' },
    { sec: 'Trừ', name: 'Câu 10', pts: 1, text: '20 − 8 = ?', opts: o4('11', '12', '13', '28'), ans: 'B', why: '20 − 8 = 12.' },
  ],
},

/* ═══════════ ĐỀ 16 — CỘNG, TRỪ (KHÔNG NHỚ) TRONG PHẠM VI 100 ═══════════ */
{
  id: 8706, title: 'Đề 16 · Cộng, trừ trong phạm vi 100', time: 15,
  questions: [
    { sec: 'Cộng tròn chục', name: 'Câu 1', pts: 1, text: '50 + 30 = ?', opts: o4('70', '80', '90', '20'), ans: 'B', why: '5 chục cộng 3 chục là 8 chục: 80.' },
    { sec: 'Cộng', name: 'Câu 2', pts: 1, text: '32 + 6 = ?', opts: o4('38', '92', '26', '39'), ans: 'A', why: '32 + 6 = 38 (cộng hàng đơn vị).' },
    { sec: 'Trừ tròn chục', name: 'Câu 3', pts: 1, text: '90 − 50 = ?', opts: o4('30', '40', '140', '20'), ans: 'B', why: '9 chục trừ 5 chục là 4 chục: 40.' },
    { sec: 'Trừ', name: 'Câu 4', pts: 1, text: '76 − 4 = ?', opts: o4('72', '32', '80', '70'), ans: 'A', why: '76 − 4 = 72 (trừ hàng đơn vị).' },
    { sec: 'Cộng', name: 'Câu 5', pts: 1, text: '43 + 25 = ?', opts: o4('68', '18', '78', '58'), ans: 'A', why: '43 + 25: 3+5=8, 4+2=6 → 68.' },
    { sec: 'Trừ', name: 'Câu 6', pts: 1, text: '87 − 34 = ?', opts: o4('53', '43', '63', '51'), ans: 'A', why: '87 − 34: 7−4=3, 8−3=5 → 53.' },
    { sec: 'Cộng tròn chục', name: 'Câu 7', pts: 1, text: '20 + 60 = ?', opts: o4('70', '80', '90', '40'), ans: 'B', why: '2 chục cộng 6 chục là 8 chục: 80.' },
    { sec: 'Cộng', name: 'Câu 8', pts: 1, text: '54 + 45 = ?', opts: o4('99', '89', '91', '09'), ans: 'A', why: '54 + 45: 4+5=9, 5+4=9 → 99.' },
    { sec: 'Trừ', name: 'Câu 9', pts: 1, text: '65 − 30 = ?', opts: o4('25', '35', '95', '45'), ans: 'B', why: '65 − 30: 5−0=5, 6−3=3 → 35.' },
    { sec: 'Trừ', name: 'Câu 10', pts: 1, text: '48 − 22 = ?', opts: o4('26', '20', '66', '36'), ans: 'A', why: '48 − 22: 8−2=6, 4−2=2 → 26.' },
  ],
},

/* ═══════════ ĐỀ 17 — SO SÁNH SỐ ĐẾN 100 ═══════════ */
{
  id: 8707, title: 'Đề 17 · So sánh các số đến 100', time: 15,
  questions: [
    { sec: 'So sánh', name: 'Câu 1', pts: 1, text: 'Điền dấu: 28 ... 82',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B', why: '28 có 2 chục, 82 có 8 chục nên 28 < 82.' },
    { sec: 'So sánh', name: 'Câu 2', pts: 1, text: 'Điền dấu: 65 ... 56',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'A', why: '65 có 6 chục, 56 có 5 chục nên 65 > 56.' },
    { sec: 'So sánh', name: 'Câu 3', pts: 1, text: 'Điền dấu: 44 ... 44',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'C', why: 'Hai số bằng nhau: 44 = 44.' },
    { sec: 'Lớn nhất', name: 'Câu 4', pts: 1, text: 'Số lớn nhất trong 71, 17, 70 là số nào?',
      opts: o4('17', '70', '71', 'Bằng nhau'), ans: 'C', why: '71 lớn hơn 70 và 17.' },
    { sec: 'Bé nhất', name: 'Câu 5', pts: 1, text: 'Số bé nhất trong 40, 4, 44 là số nào?',
      opts: o4('44', '40', '4', 'Không có'), ans: 'C', why: '4 bé hơn 40 và 44.' },
    { sec: 'So sánh', name: 'Câu 6', pts: 1, text: 'Điền dấu: 59 ... 60',
      opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'B', why: '59 đứng trước 60 nên 59 < 60.' },
    { sec: 'Tìm số', name: 'Câu 7', pts: 1, text: 'Số nào lớn hơn 85?',
      opts: o4('83', '85', '88', '80'), ans: 'C', why: '88 lớn hơn 85; các số kia bằng hoặc bé hơn.' },
    { sec: 'Tìm số', name: 'Câu 8', pts: 1, text: 'Số nào bé hơn 30?',
      opts: o4('30', '33', '28', '40'), ans: 'C', why: '28 bé hơn 30; các số kia bằng hoặc lớn hơn.' },
    { sec: 'Sắp xếp', name: 'Câu 9', pts: 1, text: 'Sắp xếp 90, 19, 91 từ bé đến lớn:',
      opts: o4('19, 90, 91', '90, 91, 19', '19, 91, 90', '91, 90, 19'), ans: 'A', why: 'Từ bé đến lớn: 19, 90, 91.' },
    { sec: 'Sắp xếp', name: 'Câu 10', pts: 1, text: 'Sắp xếp 77, 70, 7 từ lớn đến bé:',
      opts: o4('7, 70, 77', '77, 70, 7', '70, 77, 7', '77, 7, 70'), ans: 'B', why: 'Từ lớn đến bé: 77, 70, 7.' },
  ],
},

/* ═══════════ ĐỀ 18 — ĐIỀN SỐ CÒN THIẾU ═══════════ */
{
  id: 8708, title: 'Đề 18 · Điền số còn thiếu', time: 15,
  questions: [
    { sec: 'Điền số', name: 'Câu 1', pts: 1, text: '4 + ... = 10. Số cần điền là?', opts: o4('5', '6', '7', '4'), ans: 'B', why: '10 − 4 = 6 nên điền 6.' },
    { sec: 'Điền số', name: 'Câu 2', pts: 1, text: '... + 5 = 8. Số cần điền là?', opts: o4('2', '4', '3', '13'), ans: 'C', why: '8 − 5 = 3 nên điền 3.' },
    { sec: 'Điền số', name: 'Câu 3', pts: 1, text: '9 − ... = 4. Số cần điền là?', opts: o4('5', '6', '4', '3'), ans: 'A', why: '9 − 4 = 5 nên điền 5.' },
    { sec: 'Điền số', name: 'Câu 4', pts: 1, text: '... − 3 = 6. Số cần điền là?', opts: o4('8', '9', '10', '3'), ans: 'B', why: '6 + 3 = 9 nên điền 9.' },
    { sec: 'Điền số', name: 'Câu 5', pts: 1, text: '7 + ... = 7. Số cần điền là?', opts: o4('0', '7', '1', '14'), ans: 'A', why: 'Cộng với 0 giữ nguyên nên điền 0.' },
    { sec: 'Điền số', name: 'Câu 6', pts: 1, text: '10 + ... = 15. Số cần điền là?', opts: o4('4', '6', '5', '25'), ans: 'C', why: '15 − 10 = 5 nên điền 5.' },
    { sec: 'Điền số', name: 'Câu 7', pts: 1, text: '... + 20 = 50. Số cần điền là?', opts: o4('30', '20', '70', '10'), ans: 'A', why: '50 − 20 = 30 nên điền 30.' },
    { sec: 'Điền số', name: 'Câu 8', pts: 1, text: '13 − ... = 10. Số cần điền là?', opts: o4('2', '4', '3', '23'), ans: 'C', why: '13 − 10 = 3 nên điền 3.' },
    { sec: 'Điền dãy', name: 'Câu 9', pts: 1, text: 'Điền số còn thiếu: 30, 40, ..., 60', opts: o4('45', '50', '55', '70'), ans: 'B', why: 'Đếm thêm 10: sau 40 là 50.' },
    { sec: 'Điền dãy', name: 'Câu 10', pts: 1, text: 'Điền số còn thiếu: 2, 4, 6, ...', opts: o4('7', '8', '9', '10'), ans: 'B', why: 'Đếm thêm 2: sau 6 là 8.' },
  ],
},

/* ═══════════ ĐỀ 19 — NHẬN DẠNG VÀ ĐẾM HÌNH ═══════════ */
{
  id: 8709, title: 'Đề 19 · Nhận dạng và đếm hình', time: 15,
  questions: [
    { sec: 'Nhận dạng', name: 'Câu 1', pts: 1, text: 'Hình có 4 cạnh, hai cạnh dài và hai cạnh ngắn là hình gì?',
      opts: o4('Hình vuông', 'Hình chữ nhật', 'Hình tròn', 'Hình tam giác'), ans: 'B', why: 'Hình chữ nhật có hai cạnh dài và hai cạnh ngắn.' },
    { sec: 'Nhận dạng', name: 'Câu 2', pts: 1, text: 'Hình không có cạnh, không có góc là hình gì?',
      opts: o4('Hình tam giác', 'Hình vuông', 'Hình tròn', 'Hình chữ nhật'), ans: 'C', why: 'Hình tròn không có cạnh, không có góc.' },
    { sec: 'Đếm hình', name: 'Câu 3', pts: 1, text: 'Có mấy hình tam giác? 🔺🔺🔺',
      opts: o4('2', '3', '4', '1'), ans: 'B', why: 'Đếm được 3 hình tam giác.' },
    { sec: 'Đếm hình', name: 'Câu 4', pts: 1, text: 'Có mấy hình tròn? ⚪⚪⚪⚪',
      opts: o4('3', '5', '4', '2'), ans: 'C', why: 'Đếm được 4 hình tròn.' },
    { sec: 'Nhận dạng', name: 'Câu 5', pts: 1, text: 'Hình vuông có mấy cạnh?',
      opts: o4('3', '4', '5', '6'), ans: 'B', why: 'Hình vuông có 4 cạnh bằng nhau.' },
    { sec: 'Nhận dạng', name: 'Câu 6', pts: 1, text: 'Hình tam giác có mấy đỉnh?',
      opts: o4('3', '4', '2', '5'), ans: 'A', why: 'Hình tam giác có 3 đỉnh.' },
    { sec: 'Đếm hình', name: 'Câu 7', pts: 1, text: 'Có 2 hình vuông và 1 hình tròn. Tất cả có mấy hình?',
      opts: o4('2', '4', '3', '1'), ans: 'C', why: '2 + 1 = 3 hình.' },
    { sec: 'Nhận dạng', name: 'Câu 8', pts: 1, text: 'Mặt trăng tròn có dạng hình gì?',
      opts: o4('Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình chữ nhật'), ans: 'B', why: 'Mặt trăng tròn có dạng hình tròn.' },
    { sec: 'Nhận dạng', name: 'Câu 9', pts: 1, text: 'Chiếc khăn mùi xoa có dạng hình gì?',
      opts: o4('Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình cầu'), ans: 'A', why: 'Khăn mùi xoa thường có dạng hình vuông.' },
    { sec: 'Đếm hình', name: 'Câu 10', pts: 1, text: 'Có 3 hình tam giác và 2 hình tam giác nữa. Có tất cả mấy hình tam giác?',
      opts: o4('4', '5', '6', '3'), ans: 'B', why: '3 + 2 = 5 hình tam giác.' },
  ],
},

/* ═══════════ ĐỀ 20 — XEM GIỜ ĐÚNG ═══════════ */
{
  id: 8710, title: 'Đề 20 · Xem giờ đúng', time: 15,
  questions: [
    { sec: 'Xem giờ', name: 'Câu 1', pts: 1, text: 'Kim ngắn chỉ số 7, kim dài chỉ số 12. Đồng hồ chỉ mấy giờ?',
      opts: o4('12 giờ', '7 giờ', '5 giờ', '6 giờ'), ans: 'B', why: 'Kim dài chỉ 12, kim ngắn chỉ 7 là 7 giờ đúng.' },
    { sec: 'Xem giờ', name: 'Câu 2', pts: 1, text: 'Đồng hồ chỉ 5 giờ đúng thì kim ngắn chỉ vào số mấy?',
      opts: o4('12', '3', '5', '6'), ans: 'C', why: 'Lúc 5 giờ đúng, kim ngắn chỉ số 5.' },
    { sec: 'Xem giờ', name: 'Câu 3', pts: 1, text: 'Khi đồng hồ chỉ giờ đúng thì kim dài chỉ vào số mấy?',
      opts: o4('6', '3', '9', '12'), ans: 'D', why: 'Giờ đúng thì kim dài luôn chỉ số 12.' },
    { sec: 'Xem giờ', name: 'Câu 4', pts: 1, text: 'Kim ngắn chỉ số 10, kim dài chỉ số 12. Đồng hồ chỉ mấy giờ?',
      opts: o4('10 giờ', '12 giờ', '2 giờ', '11 giờ'), ans: 'A', why: 'Kim dài chỉ 12, kim ngắn chỉ 10 là 10 giờ đúng.' },
    { sec: 'Ước lượng', name: 'Câu 5', pts: 1, text: 'Buổi trưa em thường ăn cơm lúc khoảng mấy giờ?',
      opts: o4('11 giờ trưa', '6 giờ sáng', '9 giờ tối', '3 giờ đêm'), ans: 'A', why: 'Buổi trưa ăn cơm thường khoảng 11 giờ.' },
    { sec: 'Ước lượng', name: 'Câu 6', pts: 1, text: 'Buổi tối em thường đi ngủ lúc khoảng mấy giờ?',
      opts: o4('6 giờ sáng', '9 giờ tối', '12 giờ trưa', '3 giờ chiều'), ans: 'B', why: 'Buổi tối đi ngủ thường khoảng 9 giờ.' },
    { sec: 'Xem giờ', name: 'Câu 7', pts: 1, text: 'Đồng hồ chỉ 12 giờ đúng thì hai kim cùng chỉ vào số mấy?',
      opts: o4('6', '12', '3', '1'), ans: 'B', why: 'Lúc 12 giờ, cả kim ngắn và kim dài cùng chỉ số 12.' },
    { sec: 'Thứ tự', name: 'Câu 8', pts: 1, text: 'Giờ nào đến sớm hơn trong ngày: 8 giờ sáng hay 10 giờ sáng?',
      opts: o4('8 giờ sáng', '10 giờ sáng', 'Bằng nhau', 'Không biết'), ans: 'A', why: '8 giờ đến trước 10 giờ nên sớm hơn.' },
    { sec: 'Xem giờ', name: 'Câu 9', pts: 1, text: 'Kim ngắn chỉ số 2, kim dài chỉ số 12. Đồng hồ chỉ mấy giờ?',
      opts: o4('12 giờ', '2 giờ', '10 giờ', '6 giờ'), ans: 'B', why: 'Kim dài chỉ 12, kim ngắn chỉ 2 là 2 giờ đúng.' },
    { sec: 'Dụng cụ', name: 'Câu 10', pts: 1, text: 'Đồ vật nào dùng để xem giờ?',
      opts: o4('Cái thước', 'Cái cân', 'Đồng hồ', 'Cái ca'), ans: 'C', why: 'Đồng hồ dùng để xem giờ.' },
  ],
},

/* ═══════════ ĐỀ 21 — DÀI HƠN, NGẮN HƠN, NHIỀU HƠN, ÍT HƠN ═══════════ */
{
  id: 8711, title: 'Đề 21 · Dài hơn, ngắn hơn, nhiều hơn, ít hơn', time: 15,
  questions: [
    { sec: 'So sánh dài ngắn', name: 'Câu 1', pts: 1, text: 'Bút chì dài 12 cm, bút màu dài 9 cm. Cái nào dài hơn?',
      opts: o4('Bút chì', 'Bút màu', 'Bằng nhau', 'Không biết'), ans: 'A', why: '12 cm dài hơn 9 cm nên bút chì dài hơn.' },
    { sec: 'So sánh dài ngắn', name: 'Câu 2', pts: 1, text: 'Băng giấy đỏ dài 7 cm, băng giấy xanh dài 4 cm. Cái nào ngắn hơn?',
      opts: o4('Băng đỏ', 'Băng xanh', 'Bằng nhau', 'Không biết'), ans: 'B', why: '4 cm ngắn hơn 7 cm nên băng xanh ngắn hơn.' },
    { sec: 'Nhiều hơn', name: 'Câu 3', pts: 1, text: 'Rổ A có 8 quả, rổ B có 5 quả. Rổ nào nhiều quả hơn?',
      opts: o4('Rổ A', 'Rổ B', 'Bằng nhau', 'Không biết'), ans: 'A', why: '8 nhiều hơn 5 nên rổ A nhiều hơn.' },
    { sec: 'Ít hơn', name: 'Câu 4', pts: 1, text: 'Nam có 6 viên bi, Bình có 9 viên bi. Ai có ít bi hơn?',
      opts: o4('Bình', 'Nam', 'Bằng nhau', 'Không biết'), ans: 'B', why: '6 ít hơn 9 nên Nam có ít bi hơn.' },
    { sec: 'Nhiều hơn bao nhiêu', name: 'Câu 5', pts: 1, text: 'Có 7 con gà và 3 con vịt. Gà nhiều hơn vịt mấy con?',
      opts: o4('3', '4', '10', '5'), ans: 'B', why: 'Gà nhiều hơn: 7 − 3 = 4 (con).' },
    { sec: 'Ít hơn bao nhiêu', name: 'Câu 6', pts: 1, text: 'Có 5 cái bút và 8 quyển vở. Bút ít hơn vở mấy cái?',
      opts: o4('2', '3', '13', '4'), ans: 'B', why: 'Bút ít hơn: 8 − 5 = 3 (cái).' },
    { sec: 'So sánh cao thấp', name: 'Câu 7', pts: 1, text: 'Cây cao 20 cm, cỏ cao 5 cm. Cái nào cao hơn?',
      opts: o4('Cỏ', 'Cây', 'Bằng nhau', 'Không biết'), ans: 'B', why: '20 cm cao hơn 5 cm nên cây cao hơn.' },
    { sec: 'So sánh', name: 'Câu 8', pts: 1, text: 'Con voi và con kiến, con nào nặng hơn?',
      opts: o4('Con kiến', 'Con voi', 'Bằng nhau', 'Không biết'), ans: 'B', why: 'Con voi to và nặng hơn con kiến rất nhiều.' },
    { sec: 'Nhiều hơn', name: 'Câu 9', pts: 1, text: 'Đĩa A có 10 cái kẹo, đĩa B có 10 cái kẹo. So sánh số kẹo hai đĩa?',
      opts: o4('Đĩa A nhiều hơn', 'Đĩa B nhiều hơn', 'Bằng nhau', 'Không biết'), ans: 'C', why: 'Hai đĩa cùng 10 cái nên bằng nhau.' },
    { sec: 'Ít hơn', name: 'Câu 10', pts: 1, text: 'Đoạn thẳng AB dài 6 cm, đoạn CD dài 6 cm. Hai đoạn thế nào?',
      opts: o4('AB dài hơn', 'CD dài hơn', 'Bằng nhau', 'Không biết'), ans: 'C', why: 'Hai đoạn cùng 6 cm nên dài bằng nhau.' },
  ],
},

/* ═══════════ ĐỀ 22 — BÀI TOÁN CÓ LỜI VĂN ═══════════ */
{
  id: 8712, title: 'Đề 22 · Bài toán có lời văn', time: 15,
  questions: [
    { sec: 'Thêm', name: 'Câu 1', pts: 1, text: 'Trên cành có 6 con chim, bay đến thêm 2 con. Trên cành có mấy con chim?',
      opts: o4('4', '8', '7', '9'), ans: 'B', why: 'Tất cả: 6 + 2 = 8 (con chim).' },
    { sec: 'Bớt', name: 'Câu 2', pts: 1, text: 'Có 9 quả bóng, làm vỡ 3 quả. Còn lại mấy quả bóng?',
      opts: o4('5', '7', '6', '12'), ans: 'C', why: 'Còn lại: 9 − 3 = 6 (quả bóng).' },
    { sec: 'Gộp', name: 'Câu 3', pts: 1, text: 'Hộp có 7 viên kẹo đỏ và 2 viên kẹo vàng. Hộp có tất cả mấy viên kẹo?',
      opts: o4('9', '5', '8', '10'), ans: 'A', why: 'Tất cả: 7 + 2 = 9 (viên kẹo).' },
    { sec: 'Thêm', name: 'Câu 4', pts: 1, text: 'Bến xe có 10 chiếc, đến thêm 5 chiếc. Bến xe có mấy chiếc?',
      opts: o4('14', '5', '15', '16'), ans: 'C', why: 'Tất cả: 10 + 5 = 15 (chiếc xe).' },
    { sec: 'Bớt', name: 'Câu 5', pts: 1, text: 'Có 15 học sinh, 5 bạn về trước. Còn lại mấy bạn?',
      opts: o4('9', '20', '11', '10'), ans: 'D', why: 'Còn lại: 15 − 5 = 10 (bạn).' },
    { sec: 'Tìm số', name: 'Câu 6', pts: 1, text: 'Lan hái 12 bông hoa, cho em 4 bông. Lan còn mấy bông?',
      opts: o4('7', '8', '16', '9'), ans: 'B', why: 'Còn lại: 12 − 4 = 8 (bông hoa).' },
    { sec: 'Nhiều hơn', name: 'Câu 7', pts: 1, text: 'An có 8 quyển vở, Bình có nhiều hơn An 2 quyển. Bình có mấy quyển vở?',
      opts: o4('6', '10', '8', '12'), ans: 'B', why: 'Bình có nhiều hơn: 8 + 2 = 10 (quyển vở).' },
    { sec: 'Ít hơn', name: 'Câu 8', pts: 1, text: 'Mai có 9 cái kẹo, ít hơn Hoa 3 cái. Hoa có mấy cái kẹo?',
      opts: o4('6', '11', '12', '13'), ans: 'C', why: 'Hoa có nhiều hơn Mai: 9 + 3 = 12 (cái kẹo).' },
    { sec: 'Chục', name: 'Câu 9', pts: 1, text: 'Có 2 chục quả cam, ăn hết 5 quả. Còn lại mấy quả cam?',
      opts: o4('15', '25', '5', '10'), ans: 'A', why: '2 chục là 20; còn lại 20 − 5 = 15 (quả cam).' },
    { sec: 'Gộp', name: 'Câu 10', pts: 1, text: 'Tổ 1 có 6 bạn, tổ 2 có 7 bạn. Cả hai tổ có mấy bạn?',
      opts: o4('12', '13', '1', '14'), ans: 'B', why: 'Cả hai tổ: 6 + 7 = 13 (bạn).' },
  ],
},

/* ═══════════ ĐỀ 23 — ĐẾM SỐ TRONG PHẠM VI 100 ═══════════ */
{
  id: 8713, title: 'Đề 23 · Đếm và đọc số trong phạm vi 100', time: 15,
  questions: [
    { sec: 'Đếm chục', name: 'Câu 1', pts: 1, text: 'Có mấy chục que tính trong 40 que?',
      opts: o4('3 chục', '4 chục', '5 chục', '14 chục'), ans: 'B', why: '40 que gồm 4 chục que tính.' },
    { sec: 'Đọc số', name: 'Câu 2', pts: 1, text: 'Số 47 đọc là gì?',
      opts: o4('Bốn mươi bảy', 'Bảy mươi tư', 'Bốn bảy', 'Bốn trăm bảy'), ans: 'A', why: 'Số 47 đọc là "bốn mươi bảy".' },
    { sec: 'Viết số', name: 'Câu 3', pts: 1, text: '"Sáu mươi lăm" viết là số nào?',
      opts: o4('56', '65', '605', '15'), ans: 'B', why: 'Sáu mươi lăm viết là 65.' },
    { sec: 'Đếm', name: 'Câu 4', pts: 1, text: 'Số lớn nhất có hai chữ số là số nào?',
      opts: o4('90', '100', '99', '10'), ans: 'C', why: 'Số lớn nhất có hai chữ số là 99.' },
    { sec: 'Đếm', name: 'Câu 5', pts: 1, text: 'Số bé nhất có hai chữ số là số nào?',
      opts: o4('10', '1', '11', '99'), ans: 'A', why: 'Số bé nhất có hai chữ số là 10.' },
    { sec: 'Đếm thêm', name: 'Câu 6', pts: 1, text: 'Đếm thêm 10: 40, 50, 60, ...',
      opts: o4('61', '70', '65', '80'), ans: 'B', why: 'Thêm 10 vào 60 được 70.' },
    { sec: 'Số tròn chục', name: 'Câu 7', pts: 1, text: 'Số nào là số tròn chục?',
      opts: o4('45', '54', '50', '15'), ans: 'C', why: '50 có 0 ở hàng đơn vị nên là số tròn chục.' },
    { sec: 'Đọc số', name: 'Câu 8', pts: 1, text: 'Số 100 đọc là gì?',
      opts: o4('Mười', 'Một trăm', 'Một nghìn', 'Mười mười'), ans: 'B', why: 'Số 100 đọc là "một trăm".' },
    { sec: 'Đếm', name: 'Câu 9', pts: 1, text: 'Có bao nhiêu số tròn chục từ 10 đến 90?',
      opts: o4('8', '9', '10', '7'), ans: 'B', why: 'Đó là 10, 20, 30, 40, 50, 60, 70, 80, 90 — có 9 số.' },
    { sec: 'Đếm', name: 'Câu 10', pts: 1, text: 'Số 76 có chữ số hàng chục là số nào?',
      opts: o4('6', '7', '76', '67'), ans: 'B', why: 'Trong 76, chữ số hàng chục là 7.' },
  ],
},

/* ═══════════ ĐỀ 24 — CỘNG, TRỪ TRONG PHẠM VI 20 ═══════════ */
{
  id: 8714, title: 'Đề 24 · Cộng, trừ trong phạm vi 20', time: 15,
  questions: [
    { sec: 'Cộng', name: 'Câu 1', pts: 1, text: '11 + 5 = ?', opts: o4('15', '16', '17', '6'), ans: 'B', why: '11 + 5 = 16.' },
    { sec: 'Trừ', name: 'Câu 2', pts: 1, text: '19 − 6 = ?', opts: o4('12', '14', '13', '25'), ans: 'C', why: '19 − 6 = 13.' },
    { sec: 'Cộng qua 10', name: 'Câu 3', pts: 1, text: '8 + 4 = ?', opts: o4('11', '13', '12', '10'), ans: 'C', why: '8 + 2 = 10, còn 2 nữa là 12.' },
    { sec: 'Trừ qua 10', name: 'Câu 4', pts: 1, text: '16 − 7 = ?', opts: o4('9', '8', '10', '7'), ans: 'A', why: '16 − 6 = 10, trừ tiếp 1 còn 9.' },
    { sec: 'Cộng', name: 'Câu 5', pts: 1, text: '13 + 6 = ?', opts: o4('18', '20', '19', '17'), ans: 'C', why: '13 + 6 = 19.' },
    { sec: 'Trừ', name: 'Câu 6', pts: 1, text: '14 − 4 = ?', opts: o4('9', '11', '12', '10'), ans: 'D', why: '14 − 4 = 10.' },
    { sec: 'Cộng ba số', name: 'Câu 7', pts: 1, text: '5 + 5 + 5 = ?', opts: o4('10', '20', '15', '5'), ans: 'C', why: '5 + 5 = 10, rồi 10 + 5 = 15.' },
    { sec: 'Trừ', name: 'Câu 8', pts: 1, text: '17 − 8 = ?', opts: o4('9', '10', '8', '7'), ans: 'A', why: '17 − 7 = 10, trừ tiếp 1 còn 9.' },
    { sec: 'Cộng', name: 'Câu 9', pts: 1, text: '9 + 7 = ?', opts: o4('15', '16', '17', '14'), ans: 'B', why: '9 + 1 = 10, còn 6 nữa là 16.' },
    { sec: 'Tìm số', name: 'Câu 10', pts: 1, text: '8 + ... = 15. Số cần điền là?', opts: o4('6', '8', '7', '9'), ans: 'C', why: '15 − 8 = 7 nên điền 7.' },
  ],
},

/* ═══════════ ĐỀ 25 — CẤU TẠO SỐ VÀ SỐ TRÒN CHỤC ═══════════ */
{
  id: 8715, title: 'Đề 25 · Cấu tạo số và số tròn chục', time: 15,
  questions: [
    { sec: 'Cấu tạo số', name: 'Câu 1', pts: 1, text: 'Số 75 gồm mấy chục và mấy đơn vị?',
      opts: o4('5 chục 7 đơn vị', '7 chục 5 đơn vị', '75 chục', '7 đơn vị 5 chục'), ans: 'B', why: 'Số 75 có 7 chục và 5 đơn vị.' },
    { sec: 'Số tròn chục', name: 'Câu 2', pts: 1, text: 'Số tròn chục liền trước 40 là số nào?',
      opts: o4('39', '30', '41', '50'), ans: 'B', why: 'Số tròn chục liền trước 40 là 30.' },
    { sec: 'Viết số', name: 'Câu 3', pts: 1, text: '9 chục 3 đơn vị viết là số nào?',
      opts: o4('39', '93', '903', '12'), ans: 'B', why: '9 chục 3 đơn vị viết là 93.' },
    { sec: 'Số tròn chục', name: 'Câu 4', pts: 1, text: 'Số nào KHÔNG phải số tròn chục?',
      opts: o4('20', '35', '50', '90'), ans: 'B', why: '35 có 5 ở hàng đơn vị nên không phải số tròn chục.' },
    { sec: 'Chục', name: 'Câu 5', pts: 1, text: '8 chục bằng bao nhiêu?',
      opts: o4('8', '18', '80', '88'), ans: 'C', why: '8 chục là 80.' },
    { sec: 'Cấu tạo số', name: 'Câu 6', pts: 1, text: 'Số nào có chữ số hàng đơn vị là 0?',
      opts: o4('25', '52', '60', '16'), ans: 'C', why: '60 có chữ số 0 ở hàng đơn vị.' },
    { sec: 'Giá trị chữ số', name: 'Câu 7', pts: 1, text: 'Trong số 84, chữ số 8 chỉ mấy chục?',
      opts: o4('4 chục', '8 chục', '8 đơn vị', '80 chục'), ans: 'B', why: 'Chữ số 8 ở hàng chục nên chỉ 8 chục.' },
    { sec: 'Số tròn chục', name: 'Câu 8', pts: 1, text: 'Có bao nhiêu đơn vị trong 3 chục?',
      opts: o4('3', '13', '30', '33'), ans: 'C', why: '3 chục là 30 đơn vị.' },
    { sec: 'Đọc số', name: 'Câu 9', pts: 1, text: 'Số 70 đọc là gì?',
      opts: o4('Bảy', 'Bảy mươi', 'Bảy trăm', 'Mười bảy'), ans: 'B', why: 'Số 70 đọc là "bảy mươi".' },
    { sec: 'Cấu tạo số', name: 'Câu 10', pts: 1, text: 'Số 50 gồm mấy chục và mấy đơn vị?',
      opts: o4('5 chục 0 đơn vị', '0 chục 5 đơn vị', '50 chục', '5 đơn vị 0 chục'), ans: 'A', why: 'Số 50 có 5 chục và 0 đơn vị.' },
  ],
},

/* ═══════════ ĐỀ 26 — CỘNG, TRỪ (KHÔNG NHỚ) TRONG PHẠM VI 100 ═══════════ */
{
  id: 8716, title: 'Đề 26 · Cộng, trừ trong phạm vi 100', time: 15,
  questions: [
    { sec: 'Cộng', name: 'Câu 1', pts: 1, text: '21 + 34 = ?', opts: o4('54', '55', '56', '45'), ans: 'B', why: '21 + 34: 1+4=5, 2+3=5 → 55.' },
    { sec: 'Trừ', name: 'Câu 2', pts: 1, text: '79 − 26 = ?', opts: o4('53', '43', '52', '63'), ans: 'A', why: '79 − 26: 9−6=3, 7−2=5 → 53.' },
    { sec: 'Cộng tròn chục', name: 'Câu 3', pts: 1, text: '30 + 40 = ?', opts: o4('60', '80', '70', '10'), ans: 'C', why: '3 chục cộng 4 chục là 7 chục: 70.' },
    { sec: 'Cộng', name: 'Câu 4', pts: 1, text: '52 + 7 = ?', opts: o4('59', '45', '62', '58'), ans: 'A', why: '52 + 7 = 59 (cộng hàng đơn vị).' },
    { sec: 'Trừ', name: 'Câu 5', pts: 1, text: '96 − 40 = ?', opts: o4('46', '66', '56', '36'), ans: 'C', why: '96 − 40: 6−0=6, 9−4=5 → 56.' },
    { sec: 'Cộng', name: 'Câu 6', pts: 1, text: '35 + 24 = ?', opts: o4('59', '49', '69', '11'), ans: 'A', why: '35 + 24: 5+4=9, 3+2=5 → 59.' },
    { sec: 'Trừ tròn chục', name: 'Câu 7', pts: 1, text: '80 − 30 = ?', opts: o4('40', '50', '110', '60'), ans: 'B', why: '8 chục trừ 3 chục là 5 chục: 50.' },
    { sec: 'Trừ', name: 'Câu 8', pts: 1, text: '58 − 6 = ?', opts: o4('52', '64', '42', '50'), ans: 'A', why: '58 − 6 = 52 (trừ hàng đơn vị).' },
    { sec: 'Cộng', name: 'Câu 9', pts: 1, text: '60 + 25 = ?', opts: o4('75', '85', '95', '35'), ans: 'B', why: '60 + 25: 0+5=5, 6+2=8 → 85.' },
    { sec: 'Trừ', name: 'Câu 10', pts: 1, text: '99 − 33 = ?', opts: o4('56', '66', '76', '63'), ans: 'B', why: '99 − 33: 9−3=6, 9−3=6 → 66.' },
  ],
},

/* ═══════════ ĐỀ 27 — HÌNH PHẲNG VÀ HÌNH KHỐI ═══════════ */
{
  id: 8717, title: 'Đề 27 · Hình phẳng và hình khối', time: 15,
  questions: [
    { sec: 'Hình phẳng', name: 'Câu 1', pts: 1, text: 'Hình nào có 3 cạnh và 3 góc?',
      opts: o4('Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình chữ nhật'), ans: 'C', why: 'Hình tam giác có 3 cạnh và 3 góc.' },
    { sec: 'Hình phẳng', name: 'Câu 2', pts: 1, text: 'Hình vuông và hình chữ nhật đều có mấy cạnh?',
      opts: o4('3', '4', '5', '6'), ans: 'B', why: 'Cả hai hình đều có 4 cạnh.' },
    { sec: 'Hình khối', name: 'Câu 3', pts: 1, text: 'Hộp phấn hình chữ nhật có dạng khối gì?',
      opts: o4('Khối cầu', 'Khối trụ', 'Khối hộp chữ nhật', 'Khối lập phương'), ans: 'C', why: 'Hộp có các mặt hình chữ nhật là khối hộp chữ nhật.' },
    { sec: 'Hình khối', name: 'Câu 4', pts: 1, text: 'Quả bóng bàn có dạng khối gì?',
      opts: o4('Khối cầu', 'Khối trụ', 'Khối lập phương', 'Khối hộp'), ans: 'A', why: 'Quả bóng bàn tròn nên có dạng khối cầu.' },
    { sec: 'Hình khối', name: 'Câu 5', pts: 1, text: 'Cây bút chì (thân dài, tròn) gần giống khối gì?',
      opts: o4('Khối cầu', 'Khối trụ', 'Khối lập phương', 'Khối hộp'), ans: 'B', why: 'Thân bút chì dài và tròn nên gần giống khối trụ.' },
    { sec: 'Hình phẳng', name: 'Câu 6', pts: 1, text: 'Biển báo giao thông hình tam giác có mấy cạnh?',
      opts: o4('2', '3', '4', '5'), ans: 'B', why: 'Hình tam giác có 3 cạnh.' },
    { sec: 'Hình phẳng', name: 'Câu 7', pts: 1, text: 'Đồng xu có dạng hình gì?',
      opts: o4('Hình vuông', 'Hình tam giác', 'Hình tròn', 'Hình chữ nhật'), ans: 'C', why: 'Đồng xu có dạng hình tròn.' },
    { sec: 'Hình khối', name: 'Câu 8', pts: 1, text: 'Con súc sắc 6 mặt đều là hình vuông là khối gì?',
      opts: o4('Khối lập phương', 'Khối cầu', 'Khối trụ', 'Khối hộp chữ nhật'), ans: 'A', why: 'Sáu mặt hình vuông bằng nhau nên là khối lập phương.' },
    { sec: 'Đếm cạnh', name: 'Câu 9', pts: 1, text: 'Hình chữ nhật có mấy góc?',
      opts: o4('3', '4', '5', '6'), ans: 'B', why: 'Hình chữ nhật có 4 góc.' },
    { sec: 'Hình phẳng', name: 'Câu 10', pts: 1, text: 'Hình nào tròn, không có cạnh?',
      opts: o4('Hình tam giác', 'Hình chữ nhật', 'Hình tròn', 'Hình vuông'), ans: 'C', why: 'Hình tròn không có cạnh.' },
  ],
},

/* ═══════════ ĐỀ 28 — BÀI TOÁN CÓ LỜI VĂN ═══════════ */
{
  id: 8718, title: 'Đề 28 · Bài toán có lời văn', time: 15,
  questions: [
    { sec: 'Thêm', name: 'Câu 1', pts: 1, text: 'Trong sân có 5 con thỏ, chạy đến thêm 4 con. Trong sân có mấy con thỏ?',
      opts: o4('8', '9', '1', '10'), ans: 'B', why: 'Tất cả: 5 + 4 = 9 (con thỏ).' },
    { sec: 'Bớt', name: 'Câu 2', pts: 1, text: 'Có 14 quả trứng, dùng hết 4 quả. Còn lại mấy quả trứng?',
      opts: o4('9', '18', '10', '11'), ans: 'C', why: 'Còn lại: 14 − 4 = 10 (quả trứng).' },
    { sec: 'Gộp', name: 'Câu 3', pts: 1, text: 'Giỏ có 8 quả xoài và 6 quả ổi. Giỏ có tất cả mấy quả?',
      opts: o4('13', '14', '2', '15'), ans: 'B', why: 'Tất cả: 8 + 6 = 14 (quả).' },
    { sec: 'Bớt', name: 'Câu 4', pts: 1, text: 'Bãi có 20 chiếc xe, đi mất 10 chiếc. Còn lại mấy chiếc xe?',
      opts: o4('10', '30', '11', '9'), ans: 'A', why: 'Còn lại: 20 − 10 = 10 (chiếc xe).' },
    { sec: 'Thêm', name: 'Câu 5', pts: 1, text: 'Có 30 học sinh, thêm 5 bạn mới. Lớp có mấy học sinh?',
      opts: o4('25', '34', '35', '36'), ans: 'C', why: 'Tất cả: 30 + 5 = 35 (học sinh).' },
    { sec: 'Nhiều hơn', name: 'Câu 6', pts: 1, text: 'Hồng có 7 bông hoa, Cúc có nhiều hơn Hồng 3 bông. Cúc có mấy bông?',
      opts: o4('4', '10', '9', '11'), ans: 'B', why: 'Cúc có nhiều hơn: 7 + 3 = 10 (bông hoa).' },
    { sec: 'Ít hơn', name: 'Câu 7', pts: 1, text: 'Đội A có 13 bạn, đội B ít hơn đội A 3 bạn. Đội B có mấy bạn?',
      opts: o4('16', '10', '9', '11'), ans: 'B', why: 'Đội B ít hơn: 13 − 3 = 10 (bạn).' },
    { sec: 'Tìm số', name: 'Câu 8', pts: 1, text: 'Có 18 viên bi, cho bạn 8 viên. Còn lại mấy viên bi?',
      opts: o4('9', '26', '10', '11'), ans: 'C', why: 'Còn lại: 18 − 8 = 10 (viên bi).' },
    { sec: 'Gộp', name: 'Câu 9', pts: 1, text: 'Buổi sáng bán 40 cái bánh, buổi chiều bán 30 cái. Cả ngày bán mấy cái bánh?',
      opts: o4('60', '70', '10', '80'), ans: 'B', why: 'Cả ngày: 40 + 30 = 70 (cái bánh).' },
    { sec: 'Chục', name: 'Câu 10', pts: 1, text: 'Mẹ mua 4 chục quả cam. Mẹ mua mấy quả cam?',
      opts: o4('4', '14', '40', '44'), ans: 'C', why: '4 chục là 40 quả cam.' },
  ],
},

/* ═══════════ ĐỀ 29 — ĐO ĐỘ DÀI VÀ XEM GIỜ ═══════════ */
{
  id: 8719, title: 'Đề 29 · Đo độ dài và xem giờ đúng', time: 15,
  questions: [
    { sec: 'Đo độ dài', name: 'Câu 1', pts: 1, text: 'Đơn vị đo độ dài đã học ở lớp 1 là gì?',
      opts: o4('Lít', 'Ki-lô-gam', 'Xăng-ti-mét (cm)', 'Giờ'), ans: 'C', why: 'Ở lớp 1, đơn vị đo độ dài là xăng-ti-mét (cm).' },
    { sec: 'Cộng độ dài', name: 'Câu 2', pts: 1, text: '5 cm + 3 cm = ?',
      opts: o4('7 cm', '8 cm', '2 cm', '53 cm'), ans: 'B', why: '5 cm + 3 cm = 8 cm.' },
    { sec: 'Trừ độ dài', name: 'Câu 3', pts: 1, text: '10 cm − 4 cm = ?',
      opts: o4('5 cm', '14 cm', '6 cm', '4 cm'), ans: 'C', why: '10 cm − 4 cm = 6 cm.' },
    { sec: 'Xem giờ', name: 'Câu 4', pts: 1, text: 'Kim ngắn chỉ số 4, kim dài chỉ số 12. Đồng hồ chỉ mấy giờ?',
      opts: o4('12 giờ', '4 giờ', '8 giờ', '6 giờ'), ans: 'B', why: 'Kim dài chỉ 12, kim ngắn chỉ 4 là 4 giờ đúng.' },
    { sec: 'Xem giờ', name: 'Câu 5', pts: 1, text: 'Đồng hồ chỉ 8 giờ đúng thì kim ngắn chỉ vào số mấy?',
      opts: o4('12', '8', '6', '4'), ans: 'B', why: 'Lúc 8 giờ đúng, kim ngắn chỉ số 8.' },
    { sec: 'So sánh độ dài', name: 'Câu 6', pts: 1, text: 'Que tính A dài 9 cm, que B dài 6 cm. Que nào dài hơn?',
      opts: o4('Que A', 'Que B', 'Bằng nhau', 'Không biết'), ans: 'A', why: '9 cm dài hơn 6 cm nên que A dài hơn.' },
    { sec: 'Cộng độ dài', name: 'Câu 7', pts: 1, text: '7 cm + 2 cm = ?',
      opts: o4('9 cm', '5 cm', '72 cm', '10 cm'), ans: 'A', why: '7 cm + 2 cm = 9 cm.' },
    { sec: 'Dụng cụ', name: 'Câu 8', pts: 1, text: 'Muốn đo độ dài quyển vở, em dùng đồ vật nào?',
      opts: o4('Cái cân', 'Cái thước', 'Đồng hồ', 'Cái ca'), ans: 'B', why: 'Dùng cái thước để đo độ dài.' },
    { sec: 'Xem giờ', name: 'Câu 9', pts: 1, text: 'Đồng hồ chỉ 6 giờ đúng thì kim dài chỉ vào số mấy?',
      opts: o4('6', '3', '12', '9'), ans: 'C', why: 'Giờ đúng thì kim dài luôn chỉ số 12.' },
    { sec: 'Trừ độ dài', name: 'Câu 10', pts: 1, text: '8 cm − 5 cm = ?',
      opts: o4('3 cm', '13 cm', '2 cm', '85 cm'), ans: 'A', why: '8 cm − 5 cm = 3 cm.' },
  ],
},

/* ═══════════ ĐỀ 30 — ÔN TẬP TỔNG HỢP ═══════════ */
{
  id: 8720, title: 'Đề 30 · Ôn tập tổng hợp', time: 15,
  questions: [
    { sec: 'Số liền sau', name: 'Câu 1', pts: 1, text: 'Số liền sau của 79 là số nào?', opts: o4('78', '80', '89', '70'), ans: 'B', why: 'Liền sau 79 là 80.' },
    { sec: 'Cộng', name: 'Câu 2', pts: 1, text: '50 + 20 = ?', opts: o4('30', '60', '70', '80'), ans: 'C', why: '5 chục cộng 2 chục là 7 chục: 70.' },
    { sec: 'Trừ', name: 'Câu 3', pts: 1, text: '16 − 9 = ?', opts: o4('6', '8', '7', '25'), ans: 'C', why: '16 − 9 = 7.' },
    { sec: 'Hình', name: 'Câu 4', pts: 1, text: 'Hình có 4 cạnh bằng nhau và 4 góc vuông là hình gì?', opts: o4('Hình tròn', 'Hình tam giác', 'Hình chữ nhật', 'Hình vuông'), ans: 'D', why: 'Hình vuông có 4 cạnh bằng nhau và 4 góc vuông.' },
    { sec: 'So sánh', name: 'Câu 5', pts: 1, text: 'Điền dấu: 48 ... 40', opts: o4('>', '<', '=', 'Không so sánh được'), ans: 'A', why: '48 lớn hơn 40 nên 48 > 40.' },
    { sec: 'Chục đơn vị', name: 'Câu 6', pts: 1, text: 'Số 62 gồm mấy chục và mấy đơn vị?', opts: o4('2 chục 6 đơn vị', '6 chục 2 đơn vị', '62 chục', '6 đơn vị 2 chục'), ans: 'B', why: 'Số 62 có 6 chục và 2 đơn vị.' },
    { sec: 'Cộng', name: 'Câu 7', pts: 1, text: '7 + 8 = ?', opts: o4('14', '15', '16', '13'), ans: 'B', why: '7 + 3 = 10, còn 5 nữa là 15.' },
    { sec: 'Hình khối', name: 'Câu 8', pts: 1, text: 'Lon sữa có dạng khối gì?', opts: o4('Khối cầu', 'Khối lập phương', 'Khối trụ', 'Khối hộp'), ans: 'C', why: 'Lon sữa có dạng khối trụ.' },
    { sec: 'Lời văn', name: 'Câu 9', pts: 1, text: 'Có 12 con cá, bắt đi 2 con. Còn lại mấy con cá?', opts: o4('10', '14', '9', '11'), ans: 'A', why: 'Còn lại: 12 − 2 = 10 (con cá).' },
    { sec: 'Xem giờ', name: 'Câu 10', pts: 1, text: 'Kim ngắn chỉ số 6, kim dài chỉ số 12. Đồng hồ chỉ mấy giờ?', opts: o4('12 giờ', '6 giờ', '3 giờ', '9 giờ'), ans: 'B', why: 'Kim dài chỉ 12, kim ngắn chỉ 6 là 6 giờ đúng.' },
  ],
},

];

SUBJECTS.push({
  id: 'toan1', name: 'Toán', short: 'Toán 1', icon: '🔢', grade: 1,
  exams: TOAN1_EXAMS, ready: true,
  heroTitle: 'Toán lớp 1 — số đến 100, cộng trừ, hình học, đo độ dài và xem giờ',
  heroMeta: '📚 30 đề &nbsp;•&nbsp; 300 câu &nbsp;•&nbsp; ⏱ 15 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
