// LỊCH SỬ VÀ ĐỊA LÍ — LỚP 5 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// Bám các mạch nội dung Lịch sử và Địa lí 5:
//   - Đất nước và con người Việt Nam: vị trí, lãnh thổ, thiên nhiên, biển đảo, dân cư
//   - Những quốc gia đầu tiên: Văn Lang – Âu Lạc, Phù Nam, Chăm-pa
//   - Xây dựng và bảo vệ đất nước: các nhân vật, sự kiện tiêu biểu qua các thời kì
//   - Các nước láng giềng và khu vực Đông Nam Á (ASEAN)
//   - Tìm hiểu thế giới: các châu lục, đại dương, một số nền văn minh, Liên hợp quốc

const LSDL5_EXAMS = [

/* ═══════════ ĐỀ 1 — ĐẤT NƯỚC VIỆT NAM ═══════════ */
{
  id: 5701, title: 'Đề 1 · Đất nước và con người Việt Nam', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Việt Nam nằm ở khu vực nào của châu Á?',
      opts: o4('Đông Nam Á', 'Đông Bắc Á', 'Trung Á', 'Nam Á'), ans: 'A',
      why: 'Việt Nam nằm ở khu vực Đông Nam Á, trên bán đảo Đông Dương.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Phần đất liền của nước ta có hình dạng giống chữ gì?',
      opts: o4('Chữ S', 'Chữ O', 'Chữ U', 'Chữ V'), ans: 'A',
      why: 'Phần đất liền nước ta hẹp ngang, kéo dài, cong hình chữ S.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Nước ta giáp với những quốc gia nào trên đất liền?',
      opts: o4('Trung Quốc, Lào, Cam-pu-chia', 'Thái Lan, Nhật Bản', 'Hàn Quốc, Ấn Độ', 'Nga, Mĩ'), ans: 'A',
      why: 'Trên đất liền, Việt Nam giáp Trung Quốc (bắc), Lào và Cam-pu-chia (tây).' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Phía đông và phía nam nước ta giáp với gì?',
      opts: o4('Biển Đông', 'Sa mạc', 'Dãy núi cao', 'Đồng bằng nước Lào'), ans: 'A',
      why: 'Phía đông và nam nước ta giáp Biển Đông, thuộc Thái Bình Dương.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Địa hình phần đất liền nước ta chủ yếu là gì?',
      opts: o4('Đồi núi (chiếm phần lớn diện tích)', 'Toàn đồng bằng', 'Toàn sa mạc', 'Toàn cao nguyên băng'), ans: 'A',
      why: 'Đồi núi chiếm khoảng ba phần tư diện tích, đồng bằng chỉ chiếm một phần tư.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Nước ta có khí hậu đặc trưng là gì?',
      opts: o4('Nhiệt đới gió mùa, nóng ẩm, mưa nhiều', 'Hàn đới lạnh giá', 'Sa mạc khô hạn', 'Ôn đới có tuyết quanh năm'), ans: 'A',
      why: 'Việt Nam có khí hậu nhiệt đới gió mùa: nóng ẩm và mưa nhiều.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Nước ta có bao nhiêu dân tộc anh em cùng sinh sống?',
      opts: o4('54 dân tộc', '10 dân tộc', '100 dân tộc', '3 dân tộc'), ans: 'A',
      why: 'Việt Nam là quốc gia có 54 dân tộc anh em cùng chung sống.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Dân tộc nào có số dân đông nhất nước ta?',
      opts: o4('Dân tộc Kinh', 'Dân tộc Tày', 'Dân tộc Thái', 'Dân tộc Mông'), ans: 'A',
      why: 'Dân tộc Kinh (Việt) chiếm số dân đông nhất; các dân tộc khác là dân tộc thiểu số.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Dân cư nước ta tập trung đông nhất ở đâu?',
      opts: o4('Vùng đồng bằng và ven biển', 'Trên các đỉnh núi cao', 'Giữa rừng sâu', 'Ngoài khơi xa'), ans: 'A',
      why: 'Dân cư tập trung đông ở đồng bằng, ven biển và các đô thị; thưa thớt ở miền núi.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Thái độ đúng đắn giữa các dân tộc anh em trong nước là gì?',
      opts: o4('Đoàn kết, tôn trọng, giúp đỡ lẫn nhau', 'Kì thị, chia rẽ', 'Coi thường dân tộc khác', 'Tranh giành, xung đột'), ans: 'A',
      why: 'Các dân tộc Việt Nam cần đoàn kết, bình đẳng, tôn trọng và giúp đỡ nhau cùng phát triển.' },
  ],
},

/* ═══════════ ĐỀ 2 — BIỂN, ĐẢO VIỆT NAM ═══════════ */
{
  id: 5702, title: 'Đề 2 · Biển, đảo Việt Nam', time: 20,
  questions: [
    { sec: 'Biển đảo', name: 'Câu 1', pts: 1,
      text: 'Vùng biển nước ta là một phần của biển nào?',
      opts: o4('Biển Đông', 'Biển Đỏ', 'Biển Đen', 'Địa Trung Hải'), ans: 'A',
      why: 'Vùng biển Việt Nam là một bộ phận của Biển Đông.' },
    { sec: 'Biển đảo', name: 'Câu 2', pts: 1,
      text: 'Hai quần đảo lớn thuộc chủ quyền của Việt Nam trên Biển Đông là gì?',
      opts: o4('Quần đảo Hoàng Sa và quần đảo Trường Sa', 'Quần đảo Ba-li', 'Quần đảo Ha-oai', 'Quần đảo Ca-na-ri'), ans: 'A',
      why: 'Hoàng Sa và Trường Sa là hai quần đảo thuộc chủ quyền của Việt Nam.' },
    { sec: 'Biển đảo', name: 'Câu 3', pts: 1,
      text: 'Biển đem lại cho nước ta nguồn lợi nào?',
      opts: o4('Hải sản, dầu khí, muối, du lịch, giao thông', 'Chỉ có sóng và gió', 'Không có lợi ích gì', 'Chỉ để ngắm cảnh'), ans: 'A',
      why: 'Biển cho hải sản, dầu khí, muối, cảnh đẹp du lịch và đường giao thông trên biển.' },
    { sec: 'Biển đảo', name: 'Câu 4', pts: 1,
      text: 'Đảo lớn nhất của nước ta là đảo nào?',
      opts: o4('Đảo Phú Quốc', 'Đảo Cát Bà', 'Đảo Lý Sơn', 'Đảo Cồn Cỏ'), ans: 'A',
      why: 'Phú Quốc (tỉnh Kiên Giang) là hòn đảo lớn nhất của nước ta.' },
    { sec: 'Biển đảo', name: 'Câu 5', pts: 1,
      text: 'Nghề nào gắn liền với vùng biển nước ta?',
      opts: o4('Đánh bắt và nuôi trồng hải sản, làm muối', 'Trồng cà phê', 'Khai thác than trong núi', 'Chăn nuôi trên cao nguyên'), ans: 'A',
      why: 'Người dân ven biển sống bằng nghề cá, nuôi trồng hải sản và làm muối.' },
    { sec: 'Biển đảo', name: 'Câu 6', pts: 1,
      text: 'Di sản thiên nhiên thế giới nổi tiếng trên vùng biển Đông Bắc nước ta là gì?',
      opts: o4('Vịnh Hạ Long', 'Hồ Gươm', 'Động Phong Nha', 'Cao nguyên đá Đồng Văn'), ans: 'A',
      why: 'Vịnh Hạ Long (Quảng Ninh) được UNESCO công nhận là Di sản thiên nhiên thế giới.' },
    { sec: 'Biển đảo', name: 'Câu 7', pts: 1,
      text: 'Những người ngày đêm canh giữ biển, đảo của Tổ quốc là ai?',
      opts: o4('Các chiến sĩ hải quân, cảnh sát biển', 'Khách du lịch', 'Thương nhân', 'Học sinh'), ans: 'A',
      why: 'Các chiến sĩ hải quân, cảnh sát biển và ngư dân góp phần canh giữ, bảo vệ biển đảo.' },
    { sec: 'Biển đảo', name: 'Câu 8', pts: 1,
      text: 'Vì sao phải bảo vệ chủ quyền biển, đảo?',
      opts: o4('Vì biển đảo là phần lãnh thổ thiêng liêng của Tổ quốc', 'Vì biển đảo không quan trọng', 'Vì ở đó có nhiều cá', 'Vì để đi du lịch'), ans: 'A',
      why: 'Biển, đảo là phần lãnh thổ thiêng liêng, không thể tách rời của Tổ quốc, cần được bảo vệ.' },
    { sec: 'Biển đảo', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp bảo vệ môi trường biển?',
      opts: o4('Không xả rác, không đánh bắt bằng chất nổ', 'Vứt rác xuống biển', 'Dùng thuốc nổ đánh cá', 'Xả dầu ra biển'), ans: 'A',
      why: 'Không xả rác, không dùng chất nổ, chất độc đánh cá giúp bảo vệ môi trường và nguồn lợi biển.' },
    { sec: 'Biển đảo', name: 'Câu 10', pts: 1,
      text: 'Là học sinh, em thể hiện tình yêu biển đảo bằng cách nào?',
      opts: o4('Học tốt, tìm hiểu và tuyên truyền về biển đảo quê hương', 'Thờ ơ, không quan tâm', 'Xả rác ra biển', 'Phá hoại san hô'), ans: 'A',
      why: 'Chăm học, tìm hiểu và giữ gìn môi trường biển là cách học sinh thể hiện tình yêu biển đảo.' },
  ],
},

/* ═══════════ ĐỀ 3 — NHỮNG QUỐC GIA ĐẦU TIÊN ═══════════ */
{
  id: 5703, title: 'Đề 3 · Những quốc gia đầu tiên trên đất nước ta', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Nhà nước đầu tiên của người Việt cổ tên là gì?',
      opts: o4('Văn Lang', 'Đại Việt', 'Đại Cồ Việt', 'Âu Lạc'), ans: 'A',
      why: 'Văn Lang do các Vua Hùng lập nên là nhà nước đầu tiên trong lịch sử nước ta.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Đứng đầu nhà nước Văn Lang là ai?',
      opts: o4('Vua Hùng (Hùng Vương)', 'An Dương Vương', 'Ngô Quyền', 'Lê Lợi'), ans: 'A',
      why: 'Các Vua Hùng (Hùng Vương) là người đứng đầu nhà nước Văn Lang.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Sau nước Văn Lang, An Dương Vương lập ra nước nào?',
      opts: o4('Âu Lạc', 'Nam Việt', 'Đại Việt', 'Phù Nam'), ans: 'A',
      why: 'An Dương Vương hợp nhất và lập nên nước Âu Lạc, đóng đô ở Cổ Loa.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Kinh đô của nước Âu Lạc là ở đâu?',
      opts: o4('Cổ Loa', 'Hoa Lư', 'Thăng Long', 'Phú Xuân'), ans: 'A',
      why: 'An Dương Vương xây thành và đóng đô ở Cổ Loa (nay thuộc Hà Nội).' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Cư dân Văn Lang – Âu Lạc chủ yếu làm nghề gì?',
      opts: o4('Trồng lúa nước', 'Chăn nuôi tuần lộc', 'Buôn bán trên biển', 'Khai thác dầu mỏ'), ans: 'A',
      why: 'Người Việt cổ chủ yếu trồng lúa nước, ngoài ra còn săn bắt, đánh cá, làm đồ gốm, đúc đồng.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Hiện vật tiêu biểu thể hiện tài đúc đồng của người Việt cổ là gì?',
      opts: o4('Trống đồng Đông Sơn', 'Kim tự tháp', 'Tượng Nữ thần Tự do', 'Vạn Lí Trường Thành'), ans: 'A',
      why: 'Trống đồng Đông Sơn là hiện vật nổi tiếng, thể hiện trình độ đúc đồng của người Việt cổ.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Vương quốc Chăm-pa (Cham-pa) từng phát triển ở vùng nào của nước ta?',
      opts: o4('Miền Trung', 'Đồng bằng Bắc Bộ', 'Vùng núi Đông Bắc', 'Tây Bắc'), ans: 'A',
      why: 'Vương quốc Chăm-pa hình thành và phát triển ở khu vực miền Trung nước ta.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Công trình kiến trúc nổi tiếng còn lại của người Chăm là gì?',
      opts: o4('Các tháp Chăm (như thánh địa Mỹ Sơn)', 'Chùa Một Cột', 'Văn Miếu', 'Cầu Long Biên'), ans: 'A',
      why: 'Người Chăm để lại nhiều đền tháp bằng gạch, tiêu biểu là thánh địa Mỹ Sơn (Quảng Nam).' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Vương quốc Phù Nam từng tồn tại ở khu vực nào?',
      opts: o4('Vùng Nam Bộ ngày nay', 'Vùng núi Tây Bắc', 'Đồng bằng Bắc Bộ', 'Tây Nguyên'), ans: 'A',
      why: 'Phù Nam là vương quốc cổ ở vùng Nam Bộ, gắn với nền văn hoá Óc Eo.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Các quốc gia cổ trên lãnh thổ nước ta cho thấy điều gì?',
      opts: o4('Nước ta có lịch sử lâu đời và nền văn hoá đa dạng', 'Nước ta không có lịch sử', 'Người Việt mới xuất hiện gần đây', 'Không có gì đáng nói'), ans: 'A',
      why: 'Văn Lang – Âu Lạc, Chăm-pa, Phù Nam cho thấy đất nước ta có lịch sử lâu đời, văn hoá đa dạng.' },
  ],
},

/* ═══════════ ĐỀ 4 — ĐẤU TRANH GIÀNH ĐỘC LẬP ═══════════ */
{
  id: 5704, title: 'Đề 4 · Đấu tranh giành lại độc lập', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Hai Bà Trưng phất cờ khởi nghĩa chống lại ách đô hộ của triều đại nào?',
      opts: o4('Nhà Hán (phương Bắc)', 'Thực dân Pháp', 'Đế quốc Mĩ', 'Nhà Thanh'), ans: 'A',
      why: 'Năm 40, Hai Bà Trưng khởi nghĩa chống ách đô hộ của nhà Hán.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Tên của Hai Bà Trưng là gì?',
      opts: o4('Trưng Trắc và Trưng Nhị', 'Triệu Thị Trinh', 'Ỷ Lan', 'Nguyên phi'), ans: 'A',
      why: 'Hai Bà Trưng là hai chị em Trưng Trắc và Trưng Nhị.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Cuộc khởi nghĩa của Hai Bà Trưng thể hiện điều gì về phụ nữ Việt Nam?',
      opts: o4('Lòng yêu nước và tinh thần bất khuất', 'Sự yếu đuối', 'Sự thờ ơ', 'Không có ý nghĩa'), ans: 'A',
      why: 'Khởi nghĩa Hai Bà Trưng thể hiện lòng yêu nước, ý chí quật cường của phụ nữ Việt Nam.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Ngô Quyền đánh tan quân Nam Hán trên sông Bạch Đằng vào năm nào?',
      opts: o4('Năm 938', 'Năm 40', 'Năm 1288', 'Năm 1789'), ans: 'A',
      why: 'Năm 938, Ngô Quyền đại thắng quân Nam Hán trên sông Bạch Đằng.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Ngô Quyền đã dùng kế sách gì để đánh giặc trên sông Bạch Đằng?',
      opts: o4('Đóng cọc nhọn dưới lòng sông', 'Đào hầm dưới đất', 'Dùng voi chiến', 'Dùng súng thần công'), ans: 'A',
      why: 'Ngô Quyền cho đóng cọc nhọn xuống lòng sông, lợi dụng thuỷ triều để phá thuyền giặc.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Chiến thắng Bạch Đằng năm 938 có ý nghĩa gì?',
      opts: o4('Kết thúc hơn một nghìn năm Bắc thuộc, mở ra độc lập', 'Mở đầu thời Bắc thuộc', 'Không có ý nghĩa gì', 'Chỉ là một trận nhỏ'), ans: 'A',
      why: 'Chiến thắng Bạch Đằng 938 chấm dứt hơn 1000 năm Bắc thuộc, mở ra thời kì độc lập lâu dài.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Người dẹp "loạn 12 sứ quân", thống nhất đất nước và lập ra nước Đại Cồ Việt là ai?',
      opts: o4('Đinh Bộ Lĩnh', 'Lê Lợi', 'Quang Trung', 'Lý Công Uẩn'), ans: 'A',
      why: 'Đinh Bộ Lĩnh dẹp loạn 12 sứ quân, lên ngôi Hoàng đế và lập nước Đại Cồ Việt.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Đinh Bộ Lĩnh đóng đô ở đâu?',
      opts: o4('Hoa Lư (Ninh Bình)', 'Cổ Loa', 'Thăng Long', 'Phú Xuân'), ans: 'A',
      why: 'Đinh Bộ Lĩnh chọn Hoa Lư (Ninh Bình) làm kinh đô của nước Đại Cồ Việt.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Thời niên thiếu, Đinh Bộ Lĩnh nổi tiếng với trò chơi nào cùng lũ trẻ chăn trâu?',
      opts: o4('Cờ lau tập trận', 'Thả diều', 'Đá bóng', 'Bịt mắt bắt dê'), ans: 'A',
      why: 'Tương truyền Đinh Bộ Lĩnh thuở nhỏ lấy cờ lau tập trận, tỏ rõ tài chỉ huy.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Bài học chung từ các cuộc đấu tranh giành độc lập của cha ông là gì?',
      opts: o4('Tinh thần yêu nước, đoàn kết chống ngoại xâm', 'Nên đầu hàng giặc', 'Không cần bảo vệ đất nước', 'Chia rẽ để dễ sống'), ans: 'A',
      why: 'Các cuộc đấu tranh cho thấy truyền thống yêu nước, đoàn kết, kiên cường chống ngoại xâm.' },
  ],
},

/* ═══════════ ĐỀ 5 — CHỐNG NGOẠI XÂM THỜI PHONG KIẾN ═══════════ */
{
  id: 5705, title: 'Đề 5 · Những trang sử chống ngoại xâm', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Vị anh hùng lãnh đạo quân dân nhà Trần ba lần đánh thắng quân Mông – Nguyên là ai?',
      opts: o4('Trần Hưng Đạo (Trần Quốc Tuấn)', 'Lê Lợi', 'Quang Trung', 'Ngô Quyền'), ans: 'A',
      why: 'Trần Hưng Đạo là vị tướng tài lãnh đạo quân dân nhà Trần ba lần đánh bại quân Mông – Nguyên.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Quân dân nhà Trần lại một lần nữa chiến thắng quân Nguyên trên sông Bạch Đằng vào năm nào?',
      opts: o4('Năm 1288', 'Năm 938', 'Năm 1789', 'Năm 1945'), ans: 'A',
      why: 'Năm 1288, quân dân nhà Trần dưới sự chỉ huy của Trần Hưng Đạo thắng lớn trên sông Bạch Đằng.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Hội nghị Diên Hồng thời Trần thể hiện điều gì?',
      opts: o4('Ý chí đoàn kết quyết đánh giặc của toàn dân', 'Việc chia đất cho quan lại', 'Một buổi tiệc lớn', 'Việc buôn bán'), ans: 'A',
      why: 'Hội nghị Diên Hồng hỏi ý các bô lão, thể hiện quyết tâm "đánh" giặc của toàn dân tộc.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Lê Lợi lãnh đạo cuộc khởi nghĩa nào chống quân Minh?',
      opts: o4('Khởi nghĩa Lam Sơn', 'Khởi nghĩa Hai Bà Trưng', 'Khởi nghĩa Tây Sơn', 'Phong trào Cần Vương'), ans: 'A',
      why: 'Lê Lợi lãnh đạo khởi nghĩa Lam Sơn (đầu thế kỉ XV) đánh đuổi quân Minh.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Nhà quân sự, nhà văn hoá lỗi lạc giúp Lê Lợi trong khởi nghĩa Lam Sơn là ai?',
      opts: o4('Nguyễn Trãi', 'Chu Văn An', 'Cao Bá Quát', 'Nguyễn Du'), ans: 'A',
      why: 'Nguyễn Trãi là quân sư tài ba giúp Lê Lợi, sau viết "Bình Ngô đại cáo".' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Người anh hùng áo vải Quang Trung có tên thật là gì?',
      opts: o4('Nguyễn Huệ', 'Nguyễn Ánh', 'Nguyễn Trãi', 'Nguyễn Du'), ans: 'A',
      why: 'Quang Trung tên thật là Nguyễn Huệ, thủ lĩnh nghĩa quân Tây Sơn.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Vua Quang Trung đại phá quân Thanh vào dịp nào?',
      opts: o4('Tết Kỉ Dậu năm 1789', 'Mùa hè năm 1288', 'Mùa thu năm 1945', 'Mùa xuân năm 1975'), ans: 'A',
      why: 'Mùa xuân Kỉ Dậu (1789), Quang Trung thần tốc đánh tan quân Thanh, giải phóng Thăng Long.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Trận đánh nổi tiếng của Quang Trung trong dịp đại phá quân Thanh là trận nào?',
      opts: o4('Ngọc Hồi – Đống Đa', 'Chi Lăng', 'Rạch Gầm – Xoài Mút', 'Đông Bộ Đầu'), ans: 'A',
      why: 'Chiến thắng Ngọc Hồi – Đống Đa quét sạch quân Thanh khỏi Thăng Long.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Điểm chung của Trần Hưng Đạo, Lê Lợi, Quang Trung là gì?',
      opts: o4('Đều là anh hùng lãnh đạo chống ngoại xâm, bảo vệ đất nước', 'Đều là thương nhân', 'Đều làm quan cho giặc', 'Đều sống thời hiện đại'), ans: 'A',
      why: 'Cả ba đều là những vị anh hùng lãnh đạo nhân dân đánh đuổi ngoại xâm, giữ nền độc lập.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Em cần làm gì để ghi nhớ công lao của các anh hùng dân tộc?',
      opts: o4('Học tốt, giữ gìn di tích, biết ơn và noi gương', 'Quên đi lịch sử', 'Phá hoại đền thờ', 'Chê bai cha ông'), ans: 'A',
      why: 'Chăm học, biết ơn, giữ gìn di tích và noi gương cha ông là cách ghi nhớ công lao các anh hùng.' },
  ],
},

/* ═══════════ ĐỀ 6 — CÁCH MẠNG THÁNG TÁM VÀ THỜI KÌ HIỆN ĐẠI ═══════════ */
{
  id: 5706, title: 'Đề 6 · Từ Cách mạng tháng Tám đến ngày thống nhất', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Cách mạng tháng Tám giành chính quyền thành công vào năm nào?',
      opts: o4('Năm 1945', 'Năm 1930', 'Năm 1954', 'Năm 1975'), ans: 'A',
      why: 'Cách mạng tháng Tám năm 1945 giành chính quyền về tay nhân dân.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Ngày 2 – 9 – 1945, tại Quảng trường Ba Đình, Bác Hồ đã làm gì?',
      opts: o4('Đọc bản Tuyên ngôn Độc lập', 'Kí hiệp định thương mại', 'Khánh thành nhà máy', 'Mở lễ hội'), ans: 'A',
      why: 'Ngày 2-9-1945, Chủ tịch Hồ Chí Minh đọc Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hoà.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Người đọc Tuyên ngôn Độc lập, khai sinh ra nước Việt Nam mới là ai?',
      opts: o4('Chủ tịch Hồ Chí Minh', 'Đại tướng Võ Nguyên Giáp', 'Vua Bảo Đại', 'Trần Hưng Đạo'), ans: 'A',
      why: 'Chủ tịch Hồ Chí Minh đọc Tuyên ngôn Độc lập ngày 2-9-1945.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ (7-5-1954) đã kết thúc cuộc kháng chiến chống ai?',
      opts: o4('Thực dân Pháp', 'Đế quốc Mĩ', 'Quân Thanh', 'Phát xít Nhật'), ans: 'A',
      why: 'Chiến thắng Điện Biên Phủ 1954 kết thúc thắng lợi cuộc kháng chiến chống thực dân Pháp.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Miền Nam được hoàn toàn giải phóng, đất nước thống nhất vào ngày nào?',
      opts: o4('30 – 4 – 1975', '2 – 9 – 1945', '7 – 5 – 1954', '10 – 10 – 1954'), ans: 'A',
      why: 'Ngày 30-4-1975, miền Nam được giải phóng, đất nước thống nhất.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Chiến dịch giải phóng Sài Gòn, kết thúc thắng lợi ngày 30-4-1975 mang tên gì?',
      opts: o4('Chiến dịch Hồ Chí Minh', 'Chiến dịch Biên giới', 'Chiến dịch Việt Bắc', 'Chiến dịch Điện Biên Phủ'), ans: 'A',
      why: 'Chiến dịch Hồ Chí Minh giải phóng Sài Gòn, hoàn thành thống nhất đất nước.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Cuộc kháng chiến chống Mĩ, cứu nước của nhân dân ta thể hiện điều gì?',
      opts: o4('Ý chí độc lập, thống nhất và tinh thần chiến đấu kiên cường', 'Sự đầu hàng', 'Sự chia rẽ', 'Không có ý nghĩa'), ans: 'A',
      why: 'Cuộc kháng chiến thể hiện khát vọng độc lập, thống nhất và tinh thần chiến đấu anh dũng của dân tộc.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Công cuộc Đổi mới đất nước bắt đầu từ năm nào?',
      opts: o4('Năm 1986', 'Năm 1945', 'Năm 1954', 'Năm 1975'), ans: 'A',
      why: 'Công cuộc Đổi mới đất nước được khởi xướng từ năm 1986.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Từ khi Đổi mới, đời sống nhân dân ta có sự thay đổi như thế nào?',
      opts: o4('Ngày càng được cải thiện, đất nước phát triển', 'Ngày càng nghèo đi', 'Không thay đổi gì', 'Chiến tranh liên miên'), ans: 'A',
      why: 'Nhờ Đổi mới, kinh tế phát triển, đời sống nhân dân ngày càng được nâng cao.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Là học sinh, em góp phần xây dựng đất nước bằng cách nào?',
      opts: o4('Chăm ngoan, học giỏi, rèn luyện đạo đức', 'Lười học', 'Phá hoại của công', 'Gây gổ đánh nhau'), ans: 'A',
      why: 'Chăm ngoan, học giỏi và rèn luyện đạo đức là cách học sinh góp phần xây dựng đất nước.' },
  ],
},

/* ═══════════ ĐỀ 7 — CÁC NƯỚC LÁNG GIỀNG VÀ ĐÔNG NAM Á ═══════════ */
{
  id: 5707, title: 'Đề 7 · Các nước láng giềng và ASEAN', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Nước láng giềng nằm ở phía bắc nước ta là nước nào?',
      opts: o4('Trung Quốc', 'Lào', 'Cam-pu-chia', 'Thái Lan'), ans: 'A',
      why: 'Trung Quốc là nước láng giềng ở phía bắc Việt Nam.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Trung Quốc là một đất nước như thế nào?',
      opts: o4('Có diện tích rộng lớn và là một trong những nước đông dân nhất thế giới', 'Rất nhỏ và ít dân', 'Không có người ở', 'Nằm ở châu Phi'), ans: 'A',
      why: 'Trung Quốc rộng lớn và là một trong những nước đông dân nhất thế giới.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Công trình cổ nổi tiếng của Trung Quốc là gì?',
      opts: o4('Vạn Lí Trường Thành', 'Tháp Ép-phen', 'Kim tự tháp', 'Nhà hát Ô-pê-ra'), ans: 'A',
      why: 'Vạn Lí Trường Thành là công trình cổ nổi tiếng của Trung Quốc.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Nước láng giềng nào ở phía tây, không giáp biển?',
      opts: o4('Lào', 'Trung Quốc', 'Cam-pu-chia', 'Phi-líp-pin'), ans: 'A',
      why: 'Lào ở phía tây nước ta, là quốc gia không giáp biển (nằm trong lục địa).' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Thủ đô của nước Lào là thành phố nào?',
      opts: o4('Viêng Chăn', 'Phnôm Pênh', 'Băng Cốc', 'Bắc Kinh'), ans: 'A',
      why: 'Viêng Chăn là thủ đô của nước Lào.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Nước láng giềng ở phía tây nam nước ta, có đền Ăng-co Vát nổi tiếng là nước nào?',
      opts: o4('Cam-pu-chia', 'Lào', 'Mi-an-ma', 'Ma-lai-xi-a'), ans: 'A',
      why: 'Cam-pu-chia ở phía tây nam, nổi tiếng với quần thể đền Ăng-co Vát.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Thủ đô của Cam-pu-chia là thành phố nào?',
      opts: o4('Phnôm Pênh', 'Viêng Chăn', 'Gia-các-ta', 'Xin-ga-po'), ans: 'A',
      why: 'Phnôm Pênh là thủ đô của Cam-pu-chia.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'ASEAN là tên viết tắt của tổ chức nào?',
      opts: o4('Hiệp hội các quốc gia Đông Nam Á', 'Liên minh châu Âu', 'Liên hợp quốc', 'Tổ chức Y tế Thế giới'), ans: 'A',
      why: 'ASEAN là Hiệp hội các quốc gia Đông Nam Á.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Việt Nam gia nhập ASEAN vào năm nào?',
      opts: o4('Năm 1995', 'Năm 1945', 'Năm 1975', 'Năm 2007'), ans: 'A',
      why: 'Việt Nam chính thức gia nhập ASEAN năm 1995.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Việt Nam và các nước láng giềng nên có quan hệ như thế nào?',
      opts: o4('Hữu nghị, hợp tác, tôn trọng lẫn nhau', 'Thù địch, gây chiến', 'Không giao thiệp', 'Xâm chiếm lẫn nhau'), ans: 'A',
      why: 'Việt Nam chủ trương quan hệ hữu nghị, hợp tác, hoà bình với các nước láng giềng.' },
  ],
},

/* ═══════════ ĐỀ 8 — CÁC CHÂU LỤC VÀ ĐẠI DƯƠNG ═══════════ */
{
  id: 5708, title: 'Đề 8 · Các châu lục và đại dương', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Trái Đất có mấy châu lục?',
      opts: o4('Sáu châu lục', 'Ba châu lục', 'Mười châu lục', 'Một châu lục'), ans: 'A',
      why: 'Có sáu châu lục: Á, Âu, Phi, Mĩ, Đại Dương và Nam Cực.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Châu lục nào lớn nhất và đông dân nhất?',
      opts: o4('Châu Á', 'Châu Âu', 'Châu Phi', 'Châu Đại Dương'), ans: 'A',
      why: 'Châu Á là châu lục lớn nhất về diện tích và đông dân nhất; Việt Nam thuộc châu Á.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Châu lục nào lạnh nhất, quanh năm phủ băng tuyết và hầu như không có dân cư sinh sống?',
      opts: o4('Châu Nam Cực', 'Châu Phi', 'Châu Á', 'Châu Mĩ'), ans: 'A',
      why: 'Châu Nam Cực lạnh nhất, phủ băng dày, hầu như không có người sinh sống thường xuyên.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Châu lục nào nóng, có hoang mạc Xa-ha-ra rộng lớn?',
      opts: o4('Châu Phi', 'Châu Âu', 'Châu Nam Cực', 'Châu Đại Dương'), ans: 'A',
      why: 'Châu Phi có khí hậu nóng và hoang mạc Xa-ha-ra lớn nhất thế giới.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Trên Trái Đất có mấy đại dương lớn?',
      opts: o4('Bốn đại dương', 'Hai đại dương', 'Sáu đại dương', 'Mười đại dương'), ans: 'A',
      why: 'Có bốn đại dương: Thái Bình Dương, Đại Tây Dương, Ấn Độ Dương và Bắc Băng Dương.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Đại dương nào lớn nhất và sâu nhất?',
      opts: o4('Thái Bình Dương', 'Đại Tây Dương', 'Ấn Độ Dương', 'Bắc Băng Dương'), ans: 'A',
      why: 'Thái Bình Dương là đại dương lớn nhất và sâu nhất; nước ta giáp Thái Bình Dương.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Đại dương nào nhỏ nhất và lạnh giá, nằm ở vùng Bắc Cực?',
      opts: o4('Bắc Băng Dương', 'Thái Bình Dương', 'Ấn Độ Dương', 'Đại Tây Dương'), ans: 'A',
      why: 'Bắc Băng Dương là đại dương nhỏ nhất, nằm quanh vùng cực Bắc, quanh năm băng giá.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Phần lớn bề mặt Trái Đất được bao phủ bởi gì?',
      opts: o4('Nước (biển và đại dương)', 'Đất liền', 'Sa mạc', 'Băng tuyết'), ans: 'A',
      why: 'Khoảng ba phần tư bề mặt Trái Đất là nước (biển và đại dương).' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Việt Nam thuộc châu lục nào?',
      opts: o4('Châu Á', 'Châu Âu', 'Châu Phi', 'Châu Mĩ'), ans: 'A',
      why: 'Việt Nam nằm ở khu vực Đông Nam Á, thuộc châu Á.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Để tìm vị trí một quốc gia, châu lục trên Trái Đất, ta có thể dùng gì?',
      opts: o4('Quả Địa Cầu hoặc bản đồ thế giới', 'Một cái cân', 'Một chiếc đồng hồ', 'Một cây thước'), ans: 'A',
      why: 'Quả Địa Cầu và bản đồ thế giới giúp ta xác định vị trí các châu lục, đại dương, quốc gia.' },
  ],
},

/* ═══════════ ĐỀ 9 — VĂN MINH THẾ GIỚI VÀ LIÊN HỢP QUỐC ═══════════ */
{
  id: 5709, title: 'Đề 9 · Văn minh thế giới và Liên hợp quốc', time: 20,
  questions: [
    { sec: 'Thế giới', name: 'Câu 1', pts: 1,
      text: 'Kim tự tháp là công trình cổ nổi tiếng của nền văn minh nào?',
      opts: o4('Ai Cập cổ đại', 'Hy Lạp cổ đại', 'Trung Quốc', 'Ấn Độ'), ans: 'A',
      why: 'Kim tự tháp là công trình kiến trúc kì vĩ của nền văn minh Ai Cập cổ đại.' },
    { sec: 'Thế giới', name: 'Câu 2', pts: 1,
      text: 'Nền văn minh Ai Cập cổ đại phát triển bên dòng sông lớn nào?',
      opts: o4('Sông Nin', 'Sông Hằng', 'Sông Mê Kông', 'Sông Trường Giang'), ans: 'A',
      why: 'Văn minh Ai Cập cổ đại hình thành và phát triển bên bờ sông Nin.' },
    { sec: 'Thế giới', name: 'Câu 3', pts: 1,
      text: 'Đại hội Thể thao Ô-lim-pic có nguồn gốc từ nền văn minh nào?',
      opts: o4('Hy Lạp cổ đại', 'Ai Cập cổ đại', 'La Mã hiện đại', 'Nhật Bản'), ans: 'A',
      why: 'Thế vận hội Ô-lim-pic bắt nguồn từ Hy Lạp cổ đại.' },
    { sec: 'Thế giới', name: 'Câu 4', pts: 1,
      text: 'Vạn Lí Trường Thành là kì công của nền văn minh nào?',
      opts: o4('Trung Quốc', 'Hy Lạp', 'Ai Cập', 'Ấn Độ'), ans: 'A',
      why: 'Vạn Lí Trường Thành là công trình vĩ đại của văn minh Trung Quốc.' },
    { sec: 'Thế giới', name: 'Câu 5', pts: 1,
      text: 'Những công trình, phát minh của các nền văn minh cổ cho thấy điều gì?',
      opts: o4('Trí tuệ và sự sáng tạo của con người', 'Con người không biết gì', 'Không có giá trị', 'Chỉ là ngẫu nhiên'), ans: 'A',
      why: 'Các công trình, phát minh cổ đại thể hiện trí tuệ và sức sáng tạo tuyệt vời của con người.' },
    { sec: 'Liên hợp quốc', name: 'Câu 6', pts: 1,
      text: 'Liên hợp quốc là tổ chức được lập ra nhằm mục đích chính gì?',
      opts: o4('Giữ gìn hoà bình và hợp tác giữa các nước', 'Gây chiến tranh', 'Chia cắt các nước', 'Buôn bán vũ khí'), ans: 'A',
      why: 'Liên hợp quốc ra đời để gìn giữ hoà bình, an ninh và thúc đẩy hợp tác giữa các quốc gia.' },
    { sec: 'Liên hợp quốc', name: 'Câu 7', pts: 1,
      text: 'Việt Nam trở thành thành viên của Liên hợp quốc vào năm nào?',
      opts: o4('Năm 1977', 'Năm 1945', 'Năm 1995', 'Năm 1954'), ans: 'A',
      why: 'Việt Nam gia nhập Liên hợp quốc năm 1977.' },
    { sec: 'Liên hợp quốc', name: 'Câu 8', pts: 1,
      text: 'Vấn đề nào là thách thức chung mà cả thế giới phải chung tay giải quyết?',
      opts: o4('Ô nhiễm môi trường, biến đổi khí hậu, dịch bệnh', 'Ai học giỏi hơn ai', 'Màu áo của mỗi người', 'Sở thích ăn uống'), ans: 'A',
      why: 'Ô nhiễm, biến đổi khí hậu, dịch bệnh... là những vấn đề toàn cầu cần các nước cùng giải quyết.' },
    { sec: 'Liên hợp quốc', name: 'Câu 9', pts: 1,
      text: 'Để góp phần xây dựng một thế giới tốt đẹp, mỗi người cần làm gì?',
      opts: o4('Sống thân thiện, bảo vệ môi trường, yêu hoà bình', 'Gây gổ, chia rẽ', 'Phá hoại thiên nhiên', 'Thờ ơ với mọi việc'), ans: 'A',
      why: 'Sống thân thiện, bảo vệ môi trường và yêu chuộng hoà bình góp phần xây dựng thế giới tốt đẹp.' },
    { sec: 'Liên hợp quốc', name: 'Câu 10', pts: 1,
      text: 'Chiến tranh gây ra hậu quả gì cho con người?',
      opts: o4('Mất mát, đau thương, phá huỷ và nghèo đói', 'Mang lại hạnh phúc', 'Không ảnh hưởng gì', 'Giúp phát triển'), ans: 'A',
      why: 'Chiến tranh gây chết chóc, tàn phá và đói nghèo — vì vậy cả thế giới đều mong muốn hoà bình.' },
  ],
},

/* ═══════════ ĐỀ 10 — ÔN TẬP TỔNG HỢP ═══════════ */
{
  id: 5710, title: 'Đề 10 · Ôn tập tổng hợp', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Phần đất liền nước ta có hình dạng giống chữ gì?',
      opts: o4('Chữ S', 'Chữ O', 'Chữ U', 'Chữ L'), ans: 'A',
      why: 'Phần đất liền nước ta cong hình chữ S.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Hai quần đảo thuộc chủ quyền Việt Nam trên Biển Đông là:',
      opts: o4('Hoàng Sa và Trường Sa', 'Ha-oai và Ba-li', 'Cô Tô và Cát Bà thôi', 'Không có'), ans: 'A',
      why: 'Hoàng Sa và Trường Sa là hai quần đảo thuộc chủ quyền của Việt Nam.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Ngô Quyền chiến thắng quân Nam Hán trên sông Bạch Đằng năm nào?',
      opts: o4('938', '1288', '1789', '1945'), ans: 'A',
      why: 'Chiến thắng Bạch Đằng năm 938 chấm dứt hơn 1000 năm Bắc thuộc.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Vua Quang Trung (Nguyễn Huệ) nổi tiếng với chiến công nào?',
      opts: o4('Đại phá quân Thanh (1789)', 'Đánh quân Mông – Nguyên', 'Đánh quân Minh', 'Đánh thực dân Pháp'), ans: 'A',
      why: 'Quang Trung đại phá quân Thanh mùa xuân Kỉ Dậu 1789.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Ngày 2-9-1945, Bác Hồ đọc văn kiện lịch sử nào?',
      opts: o4('Tuyên ngôn Độc lập', 'Lời kêu gọi toàn quốc kháng chiến', 'Di chúc', 'Bình Ngô đại cáo'), ans: 'A',
      why: 'Ngày 2-9-1945, Bác Hồ đọc Tuyên ngôn Độc lập khai sinh nước Việt Nam Dân chủ Cộng hoà.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Ngày miền Nam hoàn toàn giải phóng, đất nước thống nhất là:',
      opts: o4('30 – 4 – 1975', '7 – 5 – 1954', '2 – 9 – 1945', '3 – 2 – 1930'), ans: 'A',
      why: 'Ngày 30-4-1975 đất nước ta được thống nhất.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Ba nước láng giềng trên đất liền của Việt Nam là:',
      opts: o4('Trung Quốc, Lào, Cam-pu-chia', 'Nhật, Hàn, Thái', 'Nga, Mĩ, Anh', 'Ấn Độ, Nê-pan, Bu-tan'), ans: 'A',
      why: 'Việt Nam giáp Trung Quốc, Lào và Cam-pu-chia trên đất liền.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Châu lục lớn nhất, đông dân nhất, nơi có Việt Nam là:',
      opts: o4('Châu Á', 'Châu Âu', 'Châu Phi', 'Châu Mĩ'), ans: 'A',
      why: 'Châu Á là châu lục lớn nhất, đông dân nhất; Việt Nam thuộc châu Á.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Đại dương lớn nhất, giáp với nước ta là:',
      opts: o4('Thái Bình Dương', 'Đại Tây Dương', 'Ấn Độ Dương', 'Bắc Băng Dương'), ans: 'A',
      why: 'Thái Bình Dương là đại dương lớn nhất; Biển Đông của ta thông ra Thái Bình Dương.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Điều gì mà cả nhân loại đều mong muốn và cùng gìn giữ?',
      opts: o4('Hoà bình', 'Chiến tranh', 'Ô nhiễm', 'Đói nghèo'), ans: 'A',
      why: 'Hoà bình là điều cả nhân loại mong muốn và cùng nhau gìn giữ.' },
  ],
},

];

SUBJECTS.push({
  id: 'lsdl5', name: 'Lịch sử & Địa lí', short: 'LS-ĐL 5', icon: '🗺️', grade: 5,
  exams: LSDL5_EXAMS, ready: true,
  heroTitle: 'Lịch sử và Địa lí lớp 5 — đất nước, biển đảo, các triều đại dựng nước – giữ nước và thế giới quanh ta',
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
