// TỰ NHIÊN VÀ XÃ HỘI — LỚP 2 (GDPT 2018)
// 30 đề × 10 câu = 300 câu. Mỗi câu 1 điểm — thang 10 — 15-20 phút mỗi đề.
//
// 6 chủ đề, nhấn các nội dung riêng của lớp 2:
//   - Gia đình: các thế hệ, nghề nghiệp, phòng tránh ngộ độc, giữ sạch nhà ở
//   - Trường học: sự kiện ở trường, giữ vệ sinh và an toàn
//   - Cộng đồng: mua bán hàng hoá, phương tiện và an toàn giao thông
//   - Thực vật và động vật: môi trường sống trên cạn / dưới nước, ích lợi – tác hại
//   - Con người và sức khoẻ: cơ quan vận động (xương, cơ, khớp) và cách bảo vệ
//   - Trái Đất và bầu trời: các mùa trong năm

const TNXH2_EXAMS = [

/* ═══════════ ĐỀ 1 — CÁC THẾ HỆ TRONG GIA ĐÌNH ═══════════ */
{
  id: 5201, title: 'Đề 1 · Các thế hệ trong gia đình', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Gia đình gồm ông bà, bố mẹ và các con là gia đình có mấy thế hệ?',
      opts: o4('Một thế hệ', 'Hai thế hệ', 'Ba thế hệ', 'Bốn thế hệ'), ans: 'C',
      why: 'Ông bà — bố mẹ — các con là ba thế hệ cùng chung sống.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Gia đình chỉ có bố mẹ và các con là gia đình có mấy thế hệ?',
      opts: o4('Một thế hệ', 'Hai thế hệ', 'Ba thế hệ', 'Không có thế hệ nào'), ans: 'B',
      why: 'Bố mẹ và các con là hai thế hệ.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Trong gia đình, ai thuộc thế hệ lớn tuổi nhất?',
      opts: o4('Ông bà', 'Bố mẹ', 'Các con', 'Các cháu nhỏ'), ans: 'A',
      why: 'Ông bà là thế hệ lớn tuổi nhất trong nhà.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Anh trai của bố em, em gọi là gì?',
      opts: o4('Bác', 'Dì', 'Cậu', 'Ông'), ans: 'A',
      why: 'Anh (hoặc chị) của bố thường được gọi là bác.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Em trai của mẹ em, em gọi là gì?',
      opts: o4('Chú', 'Cậu', 'Bác', 'Ông'), ans: 'B',
      why: 'Em trai của mẹ được gọi là cậu.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Con của bác, của cô, của cậu... so với em thì gọi chung là gì?',
      opts: o4('Anh, chị, em họ', 'Người lạ', 'Bạn cùng lớp', 'Hàng xóm'), ans: 'A',
      why: 'Con của anh chị em bố mẹ là anh, chị, em họ của em.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Vào ngày giỗ, ngày Tết, họ hàng thường làm gì?',
      opts: o4('Không gặp nhau', 'Sum họp, thăm hỏi nhau', 'Tránh mặt nhau', 'Cãi nhau'), ans: 'B',
      why: 'Giỗ, Tết là dịp họ hàng sum họp, thăm hỏi và gắn bó với nhau.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Việc làm nào thể hiện sự kính trọng ông bà, cha mẹ?',
      opts: o4('Vâng lời, lễ phép, giúp việc nhà', 'Cãi lại người lớn', 'Bỏ đi khi được nhắc nhở', 'Đòi hỏi quà liên tục'), ans: 'A',
      why: 'Lễ phép, vâng lời và giúp đỡ là cách thể hiện lòng kính trọng người lớn.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Chị gái của mẹ, em gọi là gì?',
      opts: o4('Bác gái (già) hoặc dì', 'Chú', 'Cậu', 'Ông ngoại'), ans: 'A',
      why: 'Chị của mẹ nhiều nơi gọi là bác gái, có nơi gọi là dì.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Vì sao cần giữ mối quan hệ tốt với họ hàng?',
      opts: o4('Để mọi người thương yêu, giúp đỡ nhau', 'Để khoe của cải', 'Để tranh giành đồ đạc', 'Không có lí do gì'), ans: 'A',
      why: 'Họ hàng thân thiết thì thương yêu, giúp đỡ nhau khi vui cũng như khi khó khăn.' },
  ],
},

/* ═══════════ ĐỀ 2 — NGHỀ NGHIỆP, GIỮ NHÀ SẠCH VÀ PHÒNG NGỘ ĐỘC ═══════════ */
{
  id: 5202, title: 'Đề 2 · Nghề nghiệp và an toàn trong nhà', time: 15,
  questions: [
    { sec: 'Nghề nghiệp', name: 'Câu 1', pts: 1,
      text: 'Người trồng lúa, trồng rau, nuôi gà lợn làm nghề gì?',
      opts: o4('Bác sĩ', 'Nông dân', 'Giáo viên', 'Thợ may'), ans: 'B',
      why: 'Người làm ruộng, trồng trọt, chăn nuôi là nông dân.' },
    { sec: 'Nghề nghiệp', name: 'Câu 2', pts: 1,
      text: 'Người may quần áo cho mọi người làm nghề gì?',
      opts: o4('Thợ may', 'Đầu bếp', 'Lái xe', 'Ngư dân'), ans: 'A',
      why: 'Người may quần áo là thợ may.' },
    { sec: 'Nghề nghiệp', name: 'Câu 3', pts: 1,
      text: 'Người đánh bắt cá trên biển làm nghề gì?',
      opts: o4('Nông dân', 'Ngư dân', 'Bác sĩ', 'Kĩ sư'), ans: 'B',
      why: 'Người ra biển đánh cá gọi là ngư dân.' },
    { sec: 'Nghề nghiệp', name: 'Câu 4', pts: 1,
      text: 'Mọi nghề nghiệp trong xã hội đều thế nào?',
      opts: o4('Đều đáng quý và có ích cho mọi người', 'Chỉ nghề giàu mới đáng quý', 'Chỉ nghề bác sĩ mới quý', 'Không nghề nào có ích'), ans: 'A',
      why: 'Nghề nào cũng đáng quý vì đều góp ích cho xã hội.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Vì sao không được tự ý uống thuốc khi chưa hỏi người lớn?',
      opts: o4('Vì uống nhầm thuốc có thể bị ngộ độc', 'Vì thuốc đắng', 'Vì thuốc để trang trí', 'Vì thuốc nặng'), ans: 'A',
      why: 'Uống nhầm hoặc uống sai thuốc rất dễ bị ngộ độc, nguy hiểm tính mạng.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Thức ăn có mùi lạ, thiu mốc thì em nên làm gì?',
      opts: o4('Cứ ăn cho hết', 'Không ăn, bỏ đi', 'Cất lại ăn sau', 'Cho bạn ăn thử'), ans: 'B',
      why: 'Thức ăn ôi thiu, mốc gây ngộ độc; tuyệt đối không được ăn.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Chai đựng dầu hoả, thuốc trừ sâu, nước tẩy rửa cần để ở đâu?',
      opts: o4('Trong tủ lạnh cùng đồ ăn', 'Xa tầm tay trẻ em, có dán nhãn rõ', 'Ngay trên bàn ăn', 'Trong cốc uống nước'), ans: 'B',
      why: 'Hoá chất độc phải để riêng, xa tầm với trẻ em và dán nhãn để không nhầm.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Trái cây, rau trước khi ăn cần làm gì để tránh ngộ độc?',
      opts: o4('Rửa sạch (gọt vỏ nếu cần)', 'Ăn ngay khi vừa hái', 'Lăn xuống đất cho sạch', 'Không cần rửa'), ans: 'A',
      why: 'Rửa sạch rau quả giúp loại bỏ bụi bẩn, thuốc sâu, tránh đau bụng.' },
    { sec: 'Nhà ở', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp giữ nhà ở luôn sạch sẽ, gọn gàng?',
      opts: o4('Quét dọn, lau nhà, sắp xếp đồ đạc', 'Để rác trong phòng', 'Vứt đồ bừa bãi', 'Không bao giờ dọn'), ans: 'A',
      why: 'Quét dọn, lau nhà và sắp xếp gọn gàng giúp nhà sạch, đẹp, an toàn.' },
    { sec: 'Nhà ở', name: 'Câu 10', pts: 1,
      text: 'Nhà ở sạch sẽ, thoáng mát đem lại lợi ích gì?',
      opts: o4('Mọi người khoẻ mạnh, ít bệnh tật', 'Dễ bị ốm hơn', 'Nhiều muỗi hơn', 'Không có lợi ích gì'), ans: 'A',
      why: 'Nhà sạch, thoáng ít vi trùng, ruồi muỗi nên mọi người khoẻ mạnh hơn.' },
  ],
},

/* ═══════════ ĐỀ 3 — TRƯỜNG HỌC: SỰ KIỆN, VỆ SINH VÀ AN TOÀN ═══════════ */
{
  id: 5203, title: 'Đề 3 · Hoạt động và an toàn ở trường', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Ngày khai giảng năm học mới thường diễn ra vào tháng nào?',
      opts: o4('Tháng 6', 'Tháng 9', 'Tháng 12', 'Tháng 3'), ans: 'B',
      why: 'Lễ khai giảng năm học mới ở nước ta thường vào đầu tháng 9 (mùng 5-9).' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Hoạt động nào thường được tổ chức ở trường?',
      opts: o4('Lễ khai giảng, ngày hội đọc sách, văn nghệ', 'Họp chợ mua bán', 'Cày ruộng', 'Sửa xe'), ans: 'A',
      why: 'Trường học tổ chức khai giảng, ngày hội đọc sách, văn nghệ, thể thao...' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Ngày Nhà giáo Việt Nam là ngày nào để em tri ân thầy cô?',
      opts: o4('20 tháng 11', '8 tháng 3', '1 tháng 6', '2 tháng 9'), ans: 'A',
      why: 'Ngày 20/11 là Ngày Nhà giáo Việt Nam.' },
    { sec: 'Vệ sinh', name: 'Câu 4', pts: 1,
      text: 'Để giữ lớp học và sân trường sạch sẽ, em nên làm gì?',
      opts: o4('Trực nhật, bỏ rác đúng nơi', 'Vứt rác ra sân', 'Vẽ bẩn lên bàn ghế', 'Khạc nhổ bừa bãi'), ans: 'A',
      why: 'Trực nhật, quét lớp và bỏ rác đúng nơi giúp trường luôn sạch.' },
    { sec: 'Vệ sinh', name: 'Câu 5', pts: 1,
      text: 'Sau khi đi vệ sinh ở trường, em cần làm gì?',
      opts: o4('Rửa tay sạch bằng xà phòng', 'Chạy ngay vào lớp', 'Lau tay vào áo bạn', 'Không cần làm gì'), ans: 'A',
      why: 'Rửa tay bằng xà phòng giúp phòng bệnh lây qua tay.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Việc nào KHÔNG an toàn khi ở trường?',
      opts: o4('Đi bộ trong hành lang', 'Chạy đuổi, xô đẩy ở cầu thang', 'Xếp hàng ngay ngắn', 'Ngồi học nghiêm túc'), ans: 'B',
      why: 'Chạy đuổi, xô đẩy ở cầu thang rất dễ ngã và gây tai nạn.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Khi thấy sàn lớp bị ướt, trơn trượt, em nên làm gì?',
      opts: o4('Chạy nhanh qua cho vui', 'Đi cẩn thận, báo thầy cô lau khô', 'Trượt patin trên đó', 'Đổ thêm nước'), ans: 'B',
      why: 'Sàn trơn dễ ngã; nên đi cẩn thận và báo thầy cô lau khô.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Đồ vật nào ở trường có thể gây nguy hiểm nếu nghịch phá?',
      opts: o4('Ổ điện, quạt điện đang chạy', 'Quyển sách', 'Cái bảng', 'Cây bút chì để viết'), ans: 'A',
      why: 'Ổ điện, quạt đang chạy có thể gây điện giật, thương tích nếu nghịch.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Khi tham gia hoạt động tập thể ở trường, em nên có thái độ thế nào?',
      opts: o4('Vui vẻ, đoàn kết, hợp tác với bạn', 'Tách riêng không tham gia', 'Gây gổ với bạn', 'Phá đám bạn'), ans: 'A',
      why: 'Tham gia tập thể cần vui vẻ, đoàn kết và hợp tác cùng các bạn.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Ngày hội đọc sách ở trường giúp em điều gì?',
      opts: o4('Ham đọc sách, hiểu biết nhiều hơn', 'Lười học hơn', 'Không có ích gì', 'Ghét sách hơn'), ans: 'A',
      why: 'Ngày hội đọc sách khơi dậy niềm ham đọc, giúp em hiểu biết thêm.' },
  ],
},

/* ═══════════ ĐỀ 4 — MUA BÁN HÀNG HOÁ ═══════════ */
{
  id: 5204, title: 'Đề 4 · Hoạt động mua bán hàng hoá', time: 15,
  questions: [
    { sec: 'Mua bán', name: 'Câu 1', pts: 1,
      text: 'Nơi nào dưới đây là nơi mua bán hàng hoá?',
      opts: o4('Chợ, siêu thị, cửa hàng', 'Bệnh viện', 'Trường học', 'Công viên'), ans: 'A',
      why: 'Chợ, siêu thị, cửa hàng là nơi diễn ra việc mua bán hàng hoá.' },
    { sec: 'Mua bán', name: 'Câu 2', pts: 1,
      text: 'Người đem hàng ra để bán gọi là gì?',
      opts: o4('Người mua', 'Người bán', 'Khách qua đường', 'Bác sĩ'), ans: 'B',
      why: 'Người đưa hàng hoá ra trao đổi lấy tiền là người bán.' },
    { sec: 'Mua bán', name: 'Câu 3', pts: 1,
      text: 'Người trả tiền để lấy hàng gọi là gì?',
      opts: o4('Người bán', 'Người mua', 'Người trồng cây', 'Người lái xe'), ans: 'B',
      why: 'Người bỏ tiền ra để có hàng là người mua.' },
    { sec: 'Mua bán', name: 'Câu 4', pts: 1,
      text: 'Ở siêu thị, thực phẩm tươi như thịt, cá thường được bảo quản ở đâu?',
      opts: o4('Ngoài nắng', 'Trong tủ đông, tủ mát', 'Dưới sàn nhà', 'Trên nóc nhà'), ans: 'B',
      why: 'Thịt, cá cần để trong tủ đông/tủ mát cho tươi, không bị hỏng.' },
    { sec: 'Mua bán', name: 'Câu 5', pts: 1,
      text: 'Khi mua đồ ăn đóng gói, em nên xem thông tin gì trên bao bì?',
      opts: o4('Hạn sử dụng', 'Màu của túi bóng', 'Độ nặng của kệ hàng', 'Tên người bán'), ans: 'A',
      why: 'Cần xem hạn sử dụng để không mua phải đồ đã hết hạn, hỏng.' },
    { sec: 'Mua bán', name: 'Câu 6', pts: 1,
      text: 'Đi chợ, siêu thị nên mang theo gì để bảo vệ môi trường?',
      opts: o4('Túi (làn) đựng dùng nhiều lần', 'Thật nhiều túi ni lông', 'Xả rác cho vui', 'Không cần mang gì'), ans: 'A',
      why: 'Mang làn, túi dùng nhiều lần giúp giảm rác túi ni lông, bảo vệ môi trường.' },
    { sec: 'Mua bán', name: 'Câu 7', pts: 1,
      text: 'Khi được bố mẹ nhờ mua hàng, em nên làm gì?',
      opts: o4('Hỏi giá, trả đúng tiền, giữ hàng cẩn thận', 'Cầm hàng bỏ chạy', 'Lấy thêm đồ không trả tiền', 'Mua bừa cho xong'), ans: 'A',
      why: 'Mua bán cần trung thực: hỏi giá, trả đúng tiền và giữ hàng cẩn thận.' },
    { sec: 'Mua bán', name: 'Câu 8', pts: 1,
      text: 'Hành vi nào là KHÔNG trung thực khi mua bán?',
      opts: o4('Trả đủ tiền', 'Lấy hàng mà không trả tiền', 'Xếp hàng chờ tính tiền', 'Cảm ơn người bán'), ans: 'B',
      why: 'Lấy hàng không trả tiền là lấy trộm, không trung thực.' },
    { sec: 'Mua bán', name: 'Câu 9', pts: 1,
      text: 'Hàng hoá được làm ra từ đâu?',
      opts: o4('Từ công sức lao động của con người', 'Tự nhiên có sẵn không ai làm', 'Rơi từ trên trời', 'Mọc lên trong đêm'), ans: 'A',
      why: 'Hàng hoá do con người trồng trọt, chăn nuôi, sản xuất ra.' },
    { sec: 'Mua bán', name: 'Câu 10', pts: 1,
      text: 'Vì sao ta phải trân trọng hàng hoá, không lãng phí?',
      opts: o4('Vì đó là công sức lao động của nhiều người', 'Vì hàng hoá tự nhiên có', 'Vì mua rất rẻ', 'Không cần trân trọng'), ans: 'A',
      why: 'Mỗi món hàng đều chứa công sức lao động nên cần trân trọng, tránh lãng phí.' },
  ],
},

/* ═══════════ ĐỀ 5 — PHƯƠNG TIỆN VÀ AN TOÀN GIAO THÔNG ═══════════ */
{
  id: 5205, title: 'Đề 5 · Phương tiện và an toàn giao thông', time: 15,
  questions: [
    { sec: 'Giao thông', name: 'Câu 1', pts: 1,
      text: 'Phương tiện nào đi trên đường bộ?',
      opts: o4('Ô tô, xe máy, xe đạp', 'Tàu thuỷ', 'Máy bay', 'Ca nô'), ans: 'A',
      why: 'Ô tô, xe máy, xe đạp là phương tiện giao thông đường bộ.' },
    { sec: 'Giao thông', name: 'Câu 2', pts: 1,
      text: 'Phương tiện nào đi trên mặt nước?',
      opts: o4('Tàu hoả', 'Thuyền, tàu thuỷ, ca nô', 'Ô tô', 'Xe đạp'), ans: 'B',
      why: 'Thuyền, tàu thuỷ, ca nô là phương tiện giao thông đường thuỷ.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Phương tiện nào bay trên bầu trời?',
      opts: o4('Máy bay', 'Xe buýt', 'Tàu hoả', 'Xích lô'), ans: 'A',
      why: 'Máy bay là phương tiện giao thông đường hàng không.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Tàu hoả chạy trên loại đường nào?',
      opts: o4('Đường sông', 'Đường sắt (đường ray)', 'Đường hàng không', 'Đường mòn'), ans: 'B',
      why: 'Tàu hoả chạy trên đường sắt (đường ray).' },
    { sec: 'Giao thông', name: 'Câu 5', pts: 1,
      text: 'Khi ngồi trên ô tô, em nên làm gì cho an toàn?',
      opts: o4('Thắt dây an toàn, ngồi yên', 'Thò đầu, thò tay ra ngoài cửa', 'Đứng lên ghế', 'Mở cửa khi xe đang chạy'), ans: 'A',
      why: 'Ngồi ô tô phải thắt dây an toàn, ngồi yên, không thò đầu tay ra ngoài.' },
    { sec: 'Giao thông', name: 'Câu 6', pts: 1,
      text: 'Khi đi thuyền, đi đò qua sông, em phải làm gì?',
      opts: o4('Mặc áo phao, ngồi yên', 'Đứng nghiêng nhoài ra mép thuyền', 'Nghịch nước dưới sông', 'Chạy nhảy trên thuyền'), ans: 'A',
      why: 'Đi thuyền phải mặc áo phao và ngồi yên để không bị ngã xuống nước.' },
    { sec: 'Giao thông', name: 'Câu 7', pts: 1,
      text: 'Khi đi bộ trên đường không có vỉa hè, em nên đi thế nào?',
      opts: o4('Đi sát mép đường bên phải', 'Đi giữa lòng đường', 'Đi hàng ngang chắn đường', 'Vừa đi vừa đùa giỡn'), ans: 'A',
      why: 'Không có vỉa hè thì đi sát lề bên phải, đi hàng một cho an toàn.' },
    { sec: 'Giao thông', name: 'Câu 8', pts: 1,
      text: 'Việc nào là chấp hành đúng luật giao thông?',
      opts: o4('Dừng lại khi đèn đỏ, đi khi đèn xanh', 'Vượt đèn đỏ', 'Đi ngược chiều', 'Đùa nghịch trên đường'), ans: 'A',
      why: 'Chấp hành đèn tín hiệu (đỏ dừng, xanh đi) là đúng luật giao thông.' },
    { sec: 'Giao thông', name: 'Câu 9', pts: 1,
      text: 'Vì sao khi đi xe máy phải đội mũ bảo hiểm?',
      opts: o4('Để bảo vệ đầu khi có va chạm', 'Để làm đẹp', 'Để che mưa nắng cho vui', 'Không có lí do gì'), ans: 'A',
      why: 'Mũ bảo hiểm bảo vệ đầu, giảm chấn thương khi xảy ra tai nạn.' },
    { sec: 'Giao thông', name: 'Câu 10', pts: 1,
      text: 'Phương tiện giao thông giúp con người điều gì?',
      opts: o4('Đi lại và vận chuyển hàng hoá nhanh hơn', 'Làm chậm mọi việc', 'Không có tác dụng gì', 'Chỉ để ngắm cho vui'), ans: 'A',
      why: 'Phương tiện giao thông giúp đi lại và chở hàng nhanh, thuận tiện.' },
  ],
},

/* ═══════════ ĐỀ 6 — THỰC VẬT VÀ MÔI TRƯỜNG SỐNG ═══════════ */
{
  id: 5206, title: 'Đề 6 · Thực vật và nơi sống của chúng', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Cây nào sống ở dưới nước?',
      opts: o4('Cây bàng', 'Cây sen, cây bèo', 'Cây phượng', 'Cây xoài'), ans: 'B',
      why: 'Sen, bèo, súng là những cây sống dưới nước.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Cây nào sống trên cạn?',
      opts: o4('Cây bèo', 'Cây rong', 'Cây mít, cây phượng', 'Cây rau muống nước'), ans: 'C',
      why: 'Mít, phượng, bàng... là những cây sống trên cạn.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Cây xương rồng có thể sống được ở nơi nào?',
      opts: o4('Nơi khô hạn, ít nước như sa mạc', 'Dưới đáy biển sâu', 'Trong tủ lạnh', 'Trên mây'), ans: 'A',
      why: 'Xương rồng chịu hạn tốt, sống được ở vùng khô hạn, ít mưa.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Cây cối cần những gì để sống và lớn lên?',
      opts: o4('Nước, ánh sáng, không khí và chất trong đất', 'Chỉ cần bóng tối', 'Chỉ cần tiếng nhạc', 'Không cần gì cả'), ans: 'A',
      why: 'Cây cần nước, ánh sáng, không khí và chất dinh dưỡng trong đất.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Cây cho gỗ để đóng bàn ghế, làm nhà là loại cây gì?',
      opts: o4('Cây lấy gỗ (lim, xoan...)', 'Cây rau', 'Cây hoa', 'Cây cỏ'), ans: 'A',
      why: 'Cây lấy gỗ như lim, xoan, keo cho gỗ để làm nhà, đóng đồ.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Loại cây nào cho ta thức ăn hằng ngày?',
      opts: o4('Cây lúa, cây rau, cây ăn quả', 'Cây cột điện', 'Cây nhựa giả', 'Cỏ dại độc'), ans: 'A',
      why: 'Lúa, rau, cây ăn quả cho ta lương thực, thực phẩm.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Có loại cây nào gây hại cho con người không?',
      opts: o4('Có, một số cây có nhựa độc, quả độc', 'Không, mọi cây đều ăn được', 'Không có cây nào cả', 'Cây nào cũng độc'), ans: 'A',
      why: 'Một số cây có nhựa hoặc quả độc; không nên tự ý hái ăn cây lạ.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Rừng cây có vai trò gì với môi trường?',
      opts: o4('Giữ đất, giữ nước, cho không khí trong lành', 'Làm ô nhiễm không khí', 'Gây lũ lụt', 'Không có vai trò gì'), ans: 'A',
      why: 'Rừng giữ đất chống xói mòn, giữ nước và làm sạch không khí.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp bảo vệ cây xanh và rừng?',
      opts: o4('Trồng cây, chăm sóc, không chặt phá bừa bãi', 'Chặt cây bừa bãi', 'Đốt rừng', 'Bẻ cành hái lá lung tung'), ans: 'A',
      why: 'Trồng và chăm sóc cây, không chặt phá là cách bảo vệ cây xanh, rừng.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Vì sao chúng ta cần trồng nhiều cây xanh?',
      opts: o4('Cây cho bóng mát, không khí sạch, chống lũ', 'Cây làm bẩn thành phố', 'Cây gây nóng thêm', 'Trồng cây vô ích'), ans: 'A',
      why: 'Cây xanh cho bóng mát, làm sạch không khí và góp phần chống lũ lụt.' },
  ],
},

/* ═══════════ ĐỀ 7 — ĐỘNG VẬT VÀ MÔI TRƯỜNG SỐNG ═══════════ */
{
  id: 5207, title: 'Đề 7 · Động vật và nơi sống của chúng', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào sống dưới nước?',
      opts: o4('Con cá, con tôm, con cua', 'Con gà', 'Con mèo', 'Con chó'), ans: 'A',
      why: 'Cá, tôm, cua sống dưới nước.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào sống trên cạn?',
      opts: o4('Con trâu, con bò, con gà', 'Con cá chép', 'Con mực', 'Con sứa'), ans: 'A',
      why: 'Trâu, bò, gà, chó là những con vật sống trên cạn.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con vật nào vừa sống được ở nước, vừa sống trên cạn?',
      opts: o4('Con ếch', 'Con hổ', 'Con voi', 'Con đại bàng'), ans: 'A',
      why: 'Ếch sống được cả dưới nước và trên cạn (loài lưỡng cư).' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con vật nào biết bay và làm tổ trên cây?',
      opts: o4('Con chim', 'Con cá', 'Con trâu', 'Con rùa'), ans: 'A',
      why: 'Chim có cánh, biết bay và thường làm tổ trên cây.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con ong, con bướm giúp ích gì cho cây?',
      opts: o4('Giúp hoa thụ phấn để tạo quả', 'Ăn hết lá cây', 'Làm cây chết', 'Không có ích gì'), ans: 'A',
      why: 'Ong, bướm hút mật và giúp hoa thụ phấn để kết thành quả.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con vật nào có ích vì bắt sâu bọ hại lúa?',
      opts: o4('Con ếch, con chim sâu', 'Con chuột', 'Con muỗi', 'Con gián'), ans: 'A',
      why: 'Ếch, chim sâu ăn sâu bọ, giúp bảo vệ mùa màng.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con vật nào có hại, hay phá hoại thóc lúa, đồ đạc?',
      opts: o4('Con chuột', 'Con mèo', 'Con bò', 'Con gà'), ans: 'A',
      why: 'Chuột cắn phá thóc lúa, đồ đạc và truyền bệnh.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con muỗi có hại vì điều gì?',
      opts: o4('Đốt người và truyền bệnh (sốt xuất huyết)', 'Cho ta trứng', 'Bắt chuột', 'Kéo cày'), ans: 'A',
      why: 'Muỗi đốt hút máu và truyền bệnh như sốt xuất huyết, sốt rét.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Để phòng muỗi đốt và diệt muỗi, ta nên làm gì?',
      opts: o4('Ngủ màn, dọn nơi nước đọng', 'Nuôi thêm muỗi', 'Để nước đọng khắp nơi', 'Vứt rác bừa bãi'), ans: 'A',
      why: 'Ngủ màn và dọn sạch nơi nước đọng (chỗ muỗi đẻ) giúp phòng và diệt muỗi.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp bảo vệ các con vật có ích?',
      opts: o4('Không săn bắt bừa bãi, giữ sạch môi trường sống', 'Bắt hết chim, ếch', 'Đốt rừng nơi chúng ở', 'Xả rác xuống sông'), ans: 'A',
      why: 'Không săn bắt bừa bãi và giữ sạch môi trường giúp bảo vệ động vật có ích.' },
  ],
},

/* ═══════════ ĐỀ 8 — CƠ QUAN VẬN ĐỘNG: XƯƠNG VÀ CƠ ═══════════ */
{
  id: 5208, title: 'Đề 8 · Cơ quan vận động (xương và cơ)', time: 15,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Cơ quan vận động của cơ thể gồm những gì?',
      opts: o4('Bộ xương và hệ cơ', 'Tim và phổi', 'Dạ dày và ruột', 'Mắt và tai'), ans: 'A',
      why: 'Cơ quan vận động gồm bộ xương và hệ cơ, giúp cơ thể cử động.' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Bộ xương có vai trò gì với cơ thể?',
      opts: o4('Nâng đỡ và bảo vệ cơ thể', 'Giúp nhìn thấy', 'Giúp nghe', 'Giúp tiêu hoá'), ans: 'A',
      why: 'Bộ xương nâng đỡ cơ thể và bảo vệ các cơ quan bên trong (tim, não...).' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Nhờ đâu mà tay, chân... cử động được?',
      opts: o4('Nhờ các cơ bám vào xương co và giãn', 'Nhờ mái tóc', 'Nhờ móng tay', 'Nhờ làn da'), ans: 'A',
      why: 'Cơ bám vào xương, khi cơ co và giãn thì xương cử động theo.' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Nơi hai xương nối với nhau, giúp gập, duỗi được gọi là gì?',
      opts: o4('Khớp xương', 'Sợi tóc', 'Cái răng', 'Móng chân'), ans: 'A',
      why: 'Khớp là chỗ nối hai xương, giúp tay chân co, duỗi, xoay được.' },
    { sec: 'Cơ thể', name: 'Câu 5', pts: 1,
      text: 'Hộp sọ (xương đầu) bảo vệ cơ quan quan trọng nào?',
      opts: o4('Bộ não', 'Bàn chân', 'Ngón tay', 'Lá gan'), ans: 'A',
      why: 'Hộp sọ là xương cứng bao bọc, bảo vệ bộ não.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Lồng ngực (xương sườn) bảo vệ cơ quan nào?',
      opts: o4('Tim và phổi', 'Đôi mắt', 'Bàn tay', 'Lỗ tai'), ans: 'A',
      why: 'Xương sườn tạo thành lồng ngực bảo vệ tim và phổi.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Cột sống (xương sống) chạy dọc theo phần nào của cơ thể?',
      opts: o4('Dọc theo lưng', 'Trong bàn chân', 'Trong ngón tay', 'Trong lỗ mũi'), ans: 'A',
      why: 'Cột sống chạy dọc lưng, giúp cơ thể đứng thẳng.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Khi em co cánh tay lại, bắp tay (cơ) sẽ thế nào?',
      opts: o4('Co lại, cứng và nổi lên', 'Biến mất', 'Chảy nước', 'Không thay đổi gì'), ans: 'A',
      why: 'Khi co tay, cơ bắp tay co lại nên cứng và nổi lên.' },
    { sec: 'Cơ thể', name: 'Câu 9', pts: 1,
      text: 'Cơ thể cử động được (đi, chạy, cầm nắm) là nhờ sự phối hợp của những gì?',
      opts: o4('Xương, cơ và khớp', 'Chỉ có tóc', 'Chỉ có da', 'Chỉ có răng'), ans: 'A',
      why: 'Xương, cơ và khớp phối hợp nhịp nhàng giúp cơ thể vận động.' },
    { sec: 'Cơ thể', name: 'Câu 10', pts: 1,
      text: 'Nếu không vận động, ít tập thể dục thì xương và cơ sẽ thế nào?',
      opts: o4('Yếu và kém dẻo dai', 'Càng khoẻ hơn', 'To ra rất nhanh', 'Không ảnh hưởng gì'), ans: 'A',
      why: 'Lười vận động khiến xương, cơ yếu đi; tập luyện giúp chúng chắc khoẻ.' },
  ],
},

/* ═══════════ ĐỀ 9 — CHĂM SÓC VÀ BẢO VỆ CƠ QUAN VẬN ĐỘNG ═══════════ */
{
  id: 5209, title: 'Đề 9 · Bảo vệ xương và cơ', time: 15,
  questions: [
    { sec: 'Sức khoẻ', name: 'Câu 1', pts: 1,
      text: 'Tư thế ngồi học đúng giúp bảo vệ điều gì?',
      opts: o4('Cột sống (không bị cong vẹo)', 'Đôi tai', 'Cái mũi', 'Móng tay'), ans: 'A',
      why: 'Ngồi học ngay ngắn giúp cột sống thẳng, không bị cong vẹo.' },
    { sec: 'Sức khoẻ', name: 'Câu 2', pts: 1,
      text: 'Nên đeo cặp sách thế nào cho đúng?',
      opts: o4('Đeo đều hai vai, không quá nặng', 'Chỉ đeo lệch một bên vai', 'Nhồi thật nhiều sách cho nặng', 'Kéo lê dưới đất'), ans: 'A',
      why: 'Đeo cặp đều hai vai và không quá nặng giúp xương sống không bị lệch, vẹo.' },
    { sec: 'Sức khoẻ', name: 'Câu 3', pts: 1,
      text: 'Thức ăn nào giúp xương chắc khoẻ?',
      opts: o4('Sữa, tôm, cua, cá nhỏ (giàu canxi)', 'Chỉ ăn kẹo', 'Chỉ uống nước ngọt', 'Nhịn ăn'), ans: 'A',
      why: 'Sữa, tôm, cua, cá nhỏ giàu canxi giúp xương chắc khoẻ.' },
    { sec: 'Sức khoẻ', name: 'Câu 4', pts: 1,
      text: 'Việc nào giúp xương và cơ khoẻ, dẻo dai?',
      opts: o4('Tập thể dục, chơi thể thao đều đặn', 'Ngồi lì xem điện thoại cả ngày', 'Không bao giờ vận động', 'Thức khuya'), ans: 'A',
      why: 'Tập thể dục, chơi thể thao đều đặn giúp xương cơ chắc khoẻ, dẻo dai.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Để tránh gãy xương, khi vui chơi em nên thế nào?',
      opts: o4('Chơi cẩn thận, không leo trèo nơi nguy hiểm', 'Leo lên cao rồi nhảy xuống', 'Xô đẩy nhau', 'Chạy nhảy nơi trơn trượt'), ans: 'A',
      why: 'Chơi cẩn thận, tránh leo trèo, xô đẩy giúp phòng ngã gãy xương.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Bạn mang vác vật quá nặng so với sức mình có thể bị gì?',
      opts: o4('Đau lưng, hại cột sống', 'Cao lớn nhanh hơn', 'Học giỏi hơn', 'Không sao cả'), ans: 'A',
      why: 'Mang vác quá nặng gây đau lưng và có thể làm cong, hại cột sống.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Ngồi học nên chọn nơi có ánh sáng thế nào?',
      opts: o4('Đủ ánh sáng, không quá tối', 'Trong bóng tối', 'Chỉ dùng ánh nến le lói', 'Không cần ánh sáng'), ans: 'A',
      why: 'Ngồi học nơi đủ sáng để giữ tư thế tốt và bảo vệ cả mắt.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Trước khi chơi thể thao (chạy, đá bóng), nên làm gì?',
      opts: o4('Khởi động làm nóng người', 'Ăn thật no rồi chạy ngay', 'Ngồi im rồi chạy đột ngột', 'Không cần chuẩn bị'), ans: 'A',
      why: 'Khởi động giúp cơ, khớp dẻo, tránh bị chuột rút, chấn thương.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Khi bị ngã đau tay, chân, sưng nề, em nên làm gì?',
      opts: o4('Báo người lớn, đến cơ sở y tế nếu cần', 'Tự bẻ nắn thật mạnh', 'Cố chạy nhảy tiếp', 'Giấu không cho ai biết'), ans: 'A',
      why: 'Bị chấn thương nên báo người lớn và đi khám để được xử lí đúng.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Thói quen nào có hại cho cơ quan vận động?',
      opts: o4('Ngồi vẹo, nằm sấp học bài, lười vận động', 'Ngồi thẳng lưng', 'Tập thể dục mỗi ngày', 'Ăn đủ chất'), ans: 'A',
      why: 'Ngồi vẹo, nằm học và lười vận động làm xương cơ yếu, dễ cong vẹo cột sống.' },
  ],
},

/* ═══════════ ĐỀ 10 — CÁC MÙA TRONG NĂM & ÔN TẬP ═══════════ */
{
  id: 5210, title: 'Đề 10 · Các mùa trong năm và ôn tập', time: 15,
  questions: [
    { sec: 'Các mùa', name: 'Câu 1', pts: 1,
      text: 'Miền Bắc nước ta thường có mấy mùa trong năm?',
      opts: o4('Hai mùa', 'Ba mùa', 'Bốn mùa (xuân, hạ, thu, đông)', 'Năm mùa'), ans: 'C',
      why: 'Miền Bắc có bốn mùa rõ rệt: xuân, hạ, thu, đông.' },
    { sec: 'Các mùa', name: 'Câu 2', pts: 1,
      text: 'Miền Nam nước ta thường có mấy mùa?',
      opts: o4('Hai mùa: mùa mưa và mùa khô', 'Bốn mùa', 'Sáu mùa', 'Không có mùa nào'), ans: 'A',
      why: 'Miền Nam có hai mùa: mùa mưa và mùa khô.' },
    { sec: 'Các mùa', name: 'Câu 3', pts: 1,
      text: 'Mùa nào thường nóng nhất trong năm ở miền Bắc?',
      opts: o4('Mùa xuân', 'Mùa hạ (mùa hè)', 'Mùa thu', 'Mùa đông'), ans: 'B',
      why: 'Mùa hạ (mùa hè) là mùa nóng nhất.' },
    { sec: 'Các mùa', name: 'Câu 4', pts: 1,
      text: 'Mùa nào thường lạnh nhất ở miền Bắc?',
      opts: o4('Mùa xuân', 'Mùa hạ', 'Mùa thu', 'Mùa đông'), ans: 'D',
      why: 'Mùa đông là mùa lạnh nhất, cần mặc ấm.' },
    { sec: 'Các mùa', name: 'Câu 5', pts: 1,
      text: 'Mùa xuân thường có đặc điểm gì?',
      opts: o4('Ấm áp, cây cối đâm chồi nảy lộc', 'Rét buốt, cây trụi lá', 'Nóng bức nhất', 'Lá vàng rụng nhiều'), ans: 'A',
      why: 'Mùa xuân ấm áp, cây cối đâm chồi, đơm hoa.' },
    { sec: 'Các mùa', name: 'Câu 6', pts: 1,
      text: 'Vào mùa đông giá lạnh, em nên ăn mặc thế nào?',
      opts: o4('Mặc áo ấm, đội mũ len, đi tất', 'Mặc áo cộc, quần đùi', 'Cởi trần', 'Đi chân đất'), ans: 'A',
      why: 'Mùa đông cần mặc ấm để giữ sức khoẻ, tránh cảm lạnh.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Gia đình có ông bà, bố mẹ và các con là gia đình mấy thế hệ?',
      opts: o4('Một', 'Hai', 'Ba', 'Bốn'), ans: 'C',
      why: 'Ông bà — bố mẹ — các con là ba thế hệ.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Cơ quan vận động của cơ thể gồm những gì?',
      opts: o4('Xương và cơ', 'Tim và gan', 'Mắt và tai', 'Dạ dày và ruột'), ans: 'A',
      why: 'Cơ quan vận động gồm bộ xương và hệ cơ.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Máy bay là phương tiện giao thông đường nào?',
      opts: o4('Đường bộ', 'Đường thuỷ', 'Đường hàng không', 'Đường sắt'), ans: 'C',
      why: 'Máy bay bay trên trời — phương tiện giao thông đường hàng không.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Việc nào KHÔNG nên làm để bảo vệ môi trường?',
      opts: o4('Vứt rác bừa bãi xuống sông', 'Trồng cây xanh', 'Bỏ rác đúng nơi', 'Dùng làn đi chợ'), ans: 'A',
      why: 'Vứt rác xuống sông làm ô nhiễm nguồn nước, hại môi trường.' },
  ],
},

/* ═══════════ ĐỀ 11 — GIA ĐÌNH: CÁC THẾ HỆ ═══════════ */
{
  id: 8801, title: 'Đề 11 · Các thế hệ trong gia đình', time: 20,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Gia đình chỉ có hai vợ chồng, chưa có con là gia đình mấy thế hệ?',
      opts: o4('Một thế hệ', 'Hai thế hệ', 'Ba thế hệ', 'Bốn thế hệ'), ans: 'A',
      why: 'Chỉ có vợ chồng cùng một lứa tuổi nên là gia đình một thế hệ.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Gia đình có bố mẹ và các con là gia đình mấy thế hệ?',
      opts: o4('Một thế hệ', 'Hai thế hệ', 'Ba thế hệ', 'Năm thế hệ'), ans: 'B',
      why: 'Bố mẹ là một thế hệ, các con là một thế hệ, tất cả là hai thế hệ.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Gia đình có ông bà, bố mẹ và các con là gia đình mấy thế hệ?',
      opts: o4('Hai thế hệ', 'Một thế hệ', 'Ba thế hệ', 'Bốn thế hệ'), ans: 'C',
      why: 'Ông bà — bố mẹ — các con là ba thế hệ cùng chung sống.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Người sinh ra bố của em là ai?',
      opts: o4('Cậu của em', 'Dì của em', 'Cô của em', 'Ông bà nội'), ans: 'D',
      why: 'Bố mẹ của bố là ông bà nội của em.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Người sinh ra mẹ của em là ai?',
      opts: o4('Ông bà nội', 'Ông bà ngoại', 'Bác của em', 'Chú của em'), ans: 'B',
      why: 'Bố mẹ của mẹ là ông bà ngoại của em.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Em, anh và chị của em trong nhà thuộc thế hệ nào?',
      opts: o4('Thế hệ ông bà', 'Thế hệ bố mẹ', 'Thế hệ con cháu', 'Không thuộc thế hệ nào'), ans: 'C',
      why: 'Anh, chị, em cùng là con trong nhà nên thuộc thế hệ con cháu.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Ông bà cùng ở chung với bố mẹ và các con thì gọi là gia đình gì?',
      opts: o4('Gia đình một người', 'Gia đình một thế hệ', 'Gia đình nhiều thế hệ', 'Gia đình hàng xóm'), ans: 'C',
      why: 'Có nhiều thế hệ cùng chung sống nên gọi là gia đình nhiều thế hệ.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Với ông bà, cha mẹ, em cần có thái độ thế nào?',
      opts: o4('Kính trọng, yêu thương', 'Xa lánh', 'Vô lễ', 'Trêu chọc'), ans: 'A',
      why: 'Em cần kính trọng, yêu thương và vâng lời ông bà, cha mẹ.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Chị gái và em trai trong cùng một nhà thuộc mấy thế hệ với nhau?',
      opts: o4('Ba thế hệ', 'Hai thế hệ', 'Bốn thế hệ', 'Cùng một thế hệ'), ans: 'D',
      why: 'Anh chị em ruột cùng là con nên cùng một thế hệ.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Việc làm nào giúp các thế hệ trong nhà thêm gắn bó?',
      opts: o4('Cùng ăn cơm, quan tâm nhau', 'Ai cũng ở riêng cả ngày', 'Không nói chuyện với nhau', 'Tranh cãi mỗi ngày'), ans: 'A',
      why: 'Cùng ăn cơm, trò chuyện và quan tâm nhau giúp gia đình gắn bó.' },
  ],
},

/* ═══════════ ĐỀ 12 — GIA ĐÌNH: NGHỀ NGHIỆP NGƯỜI THÂN ═══════════ */
{
  id: 8802, title: 'Đề 12 · Nghề nghiệp của người thân', time: 20,
  questions: [
    { sec: 'Nghề nghiệp', name: 'Câu 1', pts: 1,
      text: 'Bác sĩ làm công việc gì?',
      opts: o4('Khám và chữa bệnh cho mọi người', 'Dạy học', 'Lái xe', 'Cắt tóc'), ans: 'A',
      why: 'Bác sĩ khám bệnh và chữa bệnh giúp mọi người khoẻ mạnh.' },
    { sec: 'Nghề nghiệp', name: 'Câu 2', pts: 1,
      text: 'Thầy, cô giáo làm nghề gì?',
      opts: o4('Lái tàu', 'Dạy học cho học sinh', 'Trồng lúa', 'Bán hàng'), ans: 'B',
      why: 'Thầy cô giáo dạy học, dạy chữ cho học sinh.' },
    { sec: 'Nghề nghiệp', name: 'Câu 3', pts: 1,
      text: 'Người lái xe khách, xe buýt được gọi là gì?',
      opts: o4('Ngư dân', 'Bác sĩ', 'Tài xế (người lái xe)', 'Thợ xây'), ans: 'C',
      why: 'Người điều khiển ô tô để chở khách là tài xế.' },
    { sec: 'Nghề nghiệp', name: 'Câu 4', pts: 1,
      text: 'Chú công an, cảnh sát giao thông làm công việc gì?',
      opts: o4('May quần áo', 'Nấu ăn', 'Trồng rau', 'Giữ gìn trật tự, an toàn'), ans: 'D',
      why: 'Công an giữ gìn trật tự, an toàn cho mọi người.' },
    { sec: 'Nghề nghiệp', name: 'Câu 5', pts: 1,
      text: 'Người xây nhà, xây tường được gọi là gì?',
      opts: o4('Thợ xây', 'Ngư dân', 'Giáo viên', 'Ca sĩ'), ans: 'A',
      why: 'Người xây nhà, xây tường là thợ xây.' },
    { sec: 'Nghề nghiệp', name: 'Câu 6', pts: 1,
      text: 'Đầu bếp làm công việc gì?',
      opts: o4('Chữa bệnh', 'Nấu các món ăn', 'Dạy học', 'Lái máy bay'), ans: 'B',
      why: 'Đầu bếp là người nấu các món ăn.' },
    { sec: 'Nghề nghiệp', name: 'Câu 7', pts: 1,
      text: 'Người chữa cháy, cứu người trong đám cháy được gọi là gì?',
      opts: o4('Thợ may', 'Nông dân', 'Lính cứu hoả', 'Ca sĩ'), ans: 'C',
      why: 'Người dập lửa, cứu người trong đám cháy là lính cứu hoả.' },
    { sec: 'Nghề nghiệp', name: 'Câu 8', pts: 1,
      text: 'Người bán hàng ở chợ, cửa hàng làm việc gì?',
      opts: o4('Cày ruộng', 'Khám bệnh', 'Dập lửa cứu hoả', 'Bán hàng hoá cho người mua'), ans: 'D',
      why: 'Người bán hàng đem hàng hoá bán cho người mua.' },
    { sec: 'Nghề nghiệp', name: 'Câu 9', pts: 1,
      text: 'Mọi nghề nghiệp trong xã hội đều thế nào?',
      opts: o4('Đáng quý và có ích', 'Chỉ nghề giàu mới quý', 'Đều vô ích', 'Chỉ nghề bác sĩ mới quý'), ans: 'A',
      why: 'Nghề nào cũng đáng quý vì đều góp ích cho mọi người.' },
    { sec: 'Nghề nghiệp', name: 'Câu 10', pts: 1,
      text: 'Với công việc của bố mẹ, em nên có thái độ gì?',
      opts: o4('Chê bai', 'Trân trọng, biết ơn', 'Xấu hổ', 'Coi thường'), ans: 'B',
      why: 'Em nên trân trọng, biết ơn và tự hào về công việc của bố mẹ.' },
  ],
},

/* ═══════════ ĐỀ 13 — GIA ĐÌNH: PHÒNG TRÁNH NGỘ ĐỘC KHI Ở NHÀ ═══════════ */
{
  id: 8803, title: 'Đề 13 · Phòng tránh ngộ độc khi ở nhà', time: 20,
  questions: [
    { sec: 'An toàn', name: 'Câu 1', pts: 1,
      text: 'Vì sao không tự ý uống thuốc khi chưa hỏi người lớn?',
      opts: o4('Vì có thể uống nhầm, bị ngộ độc', 'Vì thuốc rất ngọt', 'Vì thuốc để chơi', 'Không có lí do'), ans: 'A',
      why: 'Uống nhầm hoặc sai thuốc rất dễ bị ngộ độc, nguy hiểm.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Thức ăn có mùi lạ, thiu mốc thì em nên làm gì?',
      opts: o4('Ăn cho hết', 'Bỏ đi, không ăn', 'Để dành ăn sau', 'Cho em bé ăn'), ans: 'B',
      why: 'Thức ăn ôi thiu, mốc gây ngộ độc nên phải bỏ đi.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Chai nước tẩy rửa, thuốc trừ sâu cần để ở đâu?',
      opts: o4('Trên bàn ăn', 'Trong cốc nước', 'Xa tầm tay trẻ em, có dán nhãn', 'Cạnh hộp bánh'), ans: 'C',
      why: 'Hoá chất độc phải để riêng, xa trẻ em và dán nhãn để không nhầm.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Thấy chai lạ không nhãn, không rõ đựng gì, em nên làm gì?',
      opts: o4('Uống thử một ngụm', 'Ngửi thật lâu', 'Đổ vào cốc uống', 'Không uống, hỏi người lớn'), ans: 'D',
      why: 'Không rõ là gì thì tuyệt đối không uống, phải hỏi người lớn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Rau và trái cây trước khi ăn cần làm gì?',
      opts: o4('Rửa sạch', 'Ăn ngay khi vừa hái', 'Lăn xuống đất', 'Không cần rửa'), ans: 'A',
      why: 'Rửa sạch giúp loại bỏ bụi bẩn, thuốc sâu, tránh đau bụng.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Ăn phải thức ăn ôi thiu có thể bị gì?',
      opts: o4('Cao lớn nhanh', 'Đau bụng, ngộ độc', 'Khoẻ hơn', 'Học giỏi hơn'), ans: 'B',
      why: 'Thức ăn ôi thiu làm đau bụng, nôn, tiêu chảy — đó là ngộ độc.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Thấy bạn bị đau bụng, nôn sau khi ăn, em nên làm gì?',
      opts: o4('Giấu đi', 'Mặc kệ bạn', 'Báo ngay người lớn', 'Cười chê bạn'), ans: 'C',
      why: 'Bị ngộ độc cần báo ngay người lớn để đưa đi khám kịp thời.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Thức ăn đã nấu chín nên được bảo quản thế nào?',
      opts: o4('Để hở ngoài trời', 'Để cạnh thùng rác', 'Để ruồi bâu vào', 'Đậy kín, cất nơi sạch hoặc tủ lạnh'), ans: 'D',
      why: 'Đậy kín và cất nơi sạch giúp thức ăn không bị nhiễm bẩn, ôi thiu.' },
    { sec: 'An toàn', name: 'Câu 9', pts: 1,
      text: 'Trước khi ăn và sau khi đi vệ sinh em cần làm gì?',
      opts: o4('Rửa tay sạch bằng xà phòng', 'Lau tay vào áo', 'Không cần làm gì', 'Chỉ phủi tay'), ans: 'A',
      why: 'Rửa tay bằng xà phòng giúp phòng vi trùng vào miệng gây bệnh.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Vì sao phải để riêng hoá chất với thức ăn?',
      opts: o4('Cho đẹp', 'Tránh nhầm lẫn gây ngộ độc', 'Cho gọn', 'Không có lí do'), ans: 'B',
      why: 'Để lẫn dễ nhầm hoá chất với đồ ăn, uống nhầm sẽ bị ngộ độc.' },
  ],
},

/* ═══════════ ĐỀ 14 — GIA ĐÌNH: GIỮ NHÀ Ở SẠCH ĐẸP ═══════════ */
{
  id: 8804, title: 'Đề 14 · Giữ nhà ở sạch đẹp', time: 20,
  questions: [
    { sec: 'Nhà ở', name: 'Câu 1', pts: 1,
      text: 'Việc nào giúp nhà ở luôn sạch sẽ?',
      opts: o4('Quét dọn, lau nhà', 'Vứt rác ra sàn', 'Bày đồ bừa bãi', 'Để bụi bám lâu'), ans: 'A',
      why: 'Quét dọn, lau nhà thường xuyên giúp nhà luôn sạch sẽ.' },
    { sec: 'Nhà ở', name: 'Câu 2', pts: 1,
      text: 'Chơi xong đồ chơi, em nên làm gì?',
      opts: o4('Vứt khắp nhà', 'Cất gọn vào chỗ cũ', 'Ném ra sân', 'Để bạn dọn'), ans: 'B',
      why: 'Cất đồ chơi gọn vào chỗ cũ giúp nhà ngăn nắp, dễ tìm.' },
    { sec: 'Nhà ở', name: 'Câu 3', pts: 1,
      text: 'Rác trong nhà nên bỏ vào đâu?',
      opts: o4('Gầm giường', 'Góc phòng', 'Thùng rác', 'Dưới bàn ăn'), ans: 'C',
      why: 'Rác phải bỏ đúng vào thùng rác cho sạch và gọn.' },
    { sec: 'Nhà ở', name: 'Câu 4', pts: 1,
      text: 'Nhà ở sạch sẽ, thoáng mát đem lại lợi ích gì?',
      opts: o4('Nhiều muỗi hơn', 'Dễ ốm hơn', 'Không lợi ích gì', 'Mọi người khoẻ, ít bệnh'), ans: 'D',
      why: 'Nhà sạch, thoáng ít vi trùng, ruồi muỗi nên mọi người khoẻ hơn.' },
    { sec: 'Nhà ở', name: 'Câu 5', pts: 1,
      text: 'Buổi sáng ngủ dậy, em nên làm gì với chăn màn?',
      opts: o4('Gấp gọn chăn màn', 'Để bừa bộn', 'Vứt xuống sàn', 'Nhét dưới gầm giường'), ans: 'A',
      why: 'Gấp gọn chăn màn giúp phòng ngủ gọn gàng, sạch đẹp.' },
    { sec: 'Nhà ở', name: 'Câu 6', pts: 1,
      text: 'Việc nào KHÔNG giúp giữ nhà sạch?',
      opts: o4('Lau bàn ghế', 'Vứt vỏ bánh kẹo ra sàn', 'Quét nhà', 'Đổ rác đúng nơi'), ans: 'B',
      why: 'Vứt vỏ bánh kẹo ra sàn làm nhà bẩn, cần bỏ vào thùng rác.' },
    { sec: 'Nhà ở', name: 'Câu 7', pts: 1,
      text: 'Em nên làm gì để giúp bố mẹ việc nhà?',
      opts: o4('Chỉ ngồi xem tivi', 'Làm việc nhà vừa sức', 'Bày bừa thêm', 'Trốn việc'), ans: 'B',
      why: 'Em nên quét nhà, lau bàn, tưới cây... những việc vừa sức mình.' },
    { sec: 'Nhà ở', name: 'Câu 8', pts: 1,
      text: 'Nhà bếp cần được giữ như thế nào?',
      opts: o4('Bừa bộn, ẩm ướt', 'Đầy rác', 'Sạch sẽ, khô ráo, gọn gàng', 'Để thức ăn thiu'), ans: 'C',
      why: 'Bếp sạch, khô ráo giúp nấu ăn an toàn, tránh vi trùng.' },
    { sec: 'Nhà ở', name: 'Câu 9', pts: 1,
      text: 'Vì sao cần đổ rác hằng ngày?',
      opts: o4('Cho vui', 'Không có lí do', 'Để rác nhiều hơn', 'Tránh hôi thối, ruồi muỗi'), ans: 'D',
      why: 'Rác để lâu bốc mùi, sinh ruồi muỗi và vi trùng gây bệnh.' },
    { sec: 'Nhà ở', name: 'Câu 10', pts: 1,
      text: 'Nhà cửa gọn gàng, ngăn nắp giúp em điều gì?',
      opts: o4('Dễ tìm đồ, an toàn, dễ chịu', 'Khó tìm đồ hơn', 'Dễ vấp ngã hơn', 'Không ích gì'), ans: 'A',
      why: 'Nhà ngăn nắp giúp dễ tìm đồ, đi lại an toàn và dễ chịu.' },
  ],
},

/* ═══════════ ĐỀ 15 — TRƯỜNG HỌC: PHÒNG CHỨC NĂNG VÀ HOẠT ĐỘNG ═══════════ */
{
  id: 8805, title: 'Đề 15 · Các phòng và hoạt động ở trường', time: 20,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Nơi em đến để mượn và đọc sách ở trường là phòng gì?',
      opts: o4('Thư viện', 'Nhà bếp', 'Nhà xe', 'Nhà vệ sinh'), ans: 'A',
      why: 'Thư viện là nơi có nhiều sách để học sinh đọc và mượn.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Khi bị đau, mệt ở trường, em được đưa đến phòng nào?',
      opts: o4('Phòng học', 'Phòng y tế', 'Thư viện', 'Phòng bảo vệ'), ans: 'B',
      why: 'Phòng y tế có cô y tế chăm sóc khi học sinh ốm, đau.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Học sinh học tập hằng ngày chủ yếu ở đâu?',
      opts: o4('Sân trường', 'Nhà xe', 'Phòng học (lớp học)', 'Cổng trường'), ans: 'C',
      why: 'Phòng học (lớp học) là nơi học sinh học tập mỗi ngày.' },
    { sec: 'Trường học', name: 'Câu 4', pts: 1,
      text: 'Nơi cả trường tập trung chào cờ, vui chơi giờ ra chơi là gì?',
      opts: o4('Thư viện', 'Nhà bếp', 'Phòng y tế', 'Sân trường'), ans: 'D',
      why: 'Sân trường là nơi chào cờ, tập thể dục và vui chơi.' },
    { sec: 'Trường học', name: 'Câu 5', pts: 1,
      text: 'Lễ khai giảng năm học mới thường diễn ra vào tháng nào?',
      opts: o4('Tháng 9', 'Tháng 6', 'Tháng 12', 'Tháng 3'), ans: 'A',
      why: 'Lễ khai giảng năm học mới ở nước ta thường vào đầu tháng 9.' },
    { sec: 'Trường học', name: 'Câu 6', pts: 1,
      text: 'Ngày Nhà giáo Việt Nam để em tri ân thầy cô là ngày nào?',
      opts: o4('8 tháng 3', '20 tháng 11', '1 tháng 6', '2 tháng 9'), ans: 'B',
      why: 'Ngày 20/11 là Ngày Nhà giáo Việt Nam.' },
    { sec: 'Trường học', name: 'Câu 7', pts: 1,
      text: 'Hoạt động nào thường được tổ chức ở trường?',
      opts: o4('Họp chợ mua bán', 'Cày ruộng', 'Văn nghệ, ngày hội đọc sách', 'Sửa xe'), ans: 'C',
      why: 'Trường tổ chức văn nghệ, thể thao, ngày hội đọc sách...' },
    { sec: 'Trường học', name: 'Câu 8', pts: 1,
      text: 'Nơi để xe đạp, xe máy trong trường gọi là gì?',
      opts: o4('Thư viện', 'Phòng y tế', 'Phòng học', 'Nhà xe (nhà để xe)'), ans: 'D',
      why: 'Nhà xe là nơi để xe của thầy cô và học sinh.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Khi tham gia hoạt động tập thể ở trường, em nên thế nào?',
      opts: o4('Vui vẻ, đoàn kết, hợp tác', 'Tách riêng không tham gia', 'Gây gổ với bạn', 'Phá đám bạn'), ans: 'A',
      why: 'Hoạt động tập thể cần vui vẻ, đoàn kết và hợp tác cùng bạn.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Ngày hội đọc sách ở trường giúp em điều gì?',
      opts: o4('Lười học hơn', 'Ham đọc sách, hiểu biết nhiều hơn', 'Không có ích', 'Ghét sách hơn'), ans: 'B',
      why: 'Ngày hội đọc sách khơi dậy niềm ham đọc, giúp em hiểu biết thêm.' },
  ],
},

/* ═══════════ ĐỀ 16 — TRƯỜNG HỌC: AN TOÀN, VỆ SINH, GIỮ ĐỒ DÙNG ═══════════ */
{
  id: 8806, title: 'Đề 16 · An toàn và giữ gìn ở trường', time: 20,
  questions: [
    { sec: 'An toàn', name: 'Câu 1', pts: 1,
      text: 'Việc nào KHÔNG an toàn khi ở trường?',
      opts: o4('Đi bộ trong hành lang', 'Xếp hàng ngay ngắn', 'Chạy đuổi, xô đẩy ở cầu thang', 'Ngồi học nghiêm túc'), ans: 'C',
      why: 'Chạy đuổi, xô đẩy ở cầu thang rất dễ ngã và gây tai nạn.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Thấy sàn lớp bị ướt, trơn trượt, em nên làm gì?',
      opts: o4('Đi cẩn thận, báo thầy cô lau khô', 'Chạy nhanh qua cho vui', 'Trượt trên đó', 'Đổ thêm nước'), ans: 'A',
      why: 'Sàn trơn dễ ngã; nên đi cẩn thận và báo thầy cô lau khô.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Đồ vật nào ở trường có thể gây nguy hiểm nếu nghịch phá?',
      opts: o4('Quyển sách', 'Ổ điện, quạt đang chạy', 'Cái bảng', 'Bút chì để viết'), ans: 'B',
      why: 'Ổ điện, quạt đang chạy có thể gây điện giật, thương tích.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Khi lên xuống cầu thang, em nên đi thế nào?',
      opts: o4('Nhảy hai ba bậc một lúc', 'Chen lấn, xô đẩy bạn', 'Đi từng bậc, bám tay vịn, đi bên phải', 'Trượt trên tay vịn'), ans: 'C',
      why: 'Đi từng bậc, bám tay vịn và đi bên phải giúp tránh ngã.' },
    { sec: 'Vệ sinh', name: 'Câu 5', pts: 1,
      text: 'Để giữ lớp học và sân trường sạch sẽ, em nên làm gì?',
      opts: o4('Vứt rác ra sân', 'Vẽ bẩn lên bàn ghế', 'Khạc nhổ bừa bãi', 'Trực nhật, bỏ rác đúng nơi'), ans: 'D',
      why: 'Trực nhật, quét lớp và bỏ rác đúng nơi giúp trường luôn sạch.' },
    { sec: 'Vệ sinh', name: 'Câu 6', pts: 1,
      text: 'Sau khi đi vệ sinh ở trường, em cần làm gì?',
      opts: o4('Rửa tay sạch bằng xà phòng', 'Chạy ngay vào lớp', 'Lau tay vào áo bạn', 'Không cần làm gì'), ans: 'A',
      why: 'Rửa tay bằng xà phòng giúp phòng bệnh lây qua tay.' },
    { sec: 'Đồ dùng', name: 'Câu 7', pts: 1,
      text: 'Với sách vở, bàn ghế trong lớp, em cần làm gì?',
      opts: o4('Vẽ bậy lên bàn', 'Xé sách của bạn', 'Giữ gìn sạch sẽ, cẩn thận', 'Bẻ gãy cho vui'), ans: 'C',
      why: 'Giữ gìn sách vở, bàn ghế cẩn thận để dùng được lâu, bền.' },
    { sec: 'Đồ dùng', name: 'Câu 8', pts: 1,
      text: 'Dùng xong đồ dùng học tập chung của lớp, em nên làm gì?',
      opts: o4('Cất lại đúng chỗ, giữ nguyên vẹn', 'Vứt lung tung', 'Mang về nhà mình', 'Làm hỏng rồi bỏ đi'), ans: 'A',
      why: 'Đồ dùng chung cần cất đúng chỗ, giữ nguyên vẹn cho bạn khác dùng.' },
    { sec: 'Đồ dùng', name: 'Câu 9', pts: 1,
      text: 'Vì sao cần giữ gìn đồ dùng học tập của mình?',
      opts: o4('Để dùng được lâu, đỡ tốn tiền mua mới', 'Để nhanh hỏng hơn', 'Để khoe với bạn', 'Không có lí do'), ans: 'A',
      why: 'Giữ gìn đồ dùng giúp dùng bền, tiết kiệm tiền cho gia đình.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Trong giờ ra chơi, trò chơi nào an toàn?',
      opts: o4('Ném đá, ném đất vào nhau', 'Trèo lên tường rào cao', 'Nhảy dây, đá cầu ở sân', 'Xô đẩy nhau ở cầu thang'), ans: 'C',
      why: 'Nhảy dây, đá cầu ở sân là trò chơi an toàn, vui khoẻ.' },
  ],
},

/* ═══════════ ĐỀ 17 — CỘNG ĐỒNG: NGHỀ VÀ MUA BÁN ═══════════ */
{
  id: 8807, title: 'Đề 17 · Nghề nghiệp và mua bán trong cộng đồng', time: 20,
  questions: [
    { sec: 'Mua bán', name: 'Câu 1', pts: 1,
      text: 'Nơi nào là nơi mua bán hàng hoá?',
      opts: o4('Chợ, siêu thị, cửa hàng', 'Bệnh viện', 'Trường học', 'Công viên'), ans: 'A',
      why: 'Chợ, siêu thị, cửa hàng là nơi diễn ra việc mua bán.' },
    { sec: 'Mua bán', name: 'Câu 2', pts: 1,
      text: 'Người đem hàng ra để bán gọi là gì?',
      opts: o4('Người mua', 'Người bán', 'Khách qua đường', 'Bác sĩ'), ans: 'B',
      why: 'Người đưa hàng hoá ra để lấy tiền là người bán.' },
    { sec: 'Mua bán', name: 'Câu 3', pts: 1,
      text: 'Người trả tiền để lấy hàng gọi là gì?',
      opts: o4('Người trồng cây', 'Người lái xe', 'Người mua', 'Người bán'), ans: 'C',
      why: 'Người bỏ tiền ra để có hàng là người mua.' },
    { sec: 'Nghề nghiệp', name: 'Câu 4', pts: 1,
      text: 'Người trồng lúa, trồng rau, nuôi gà lợn làm nghề gì?',
      opts: o4('Bác sĩ', 'Giáo viên', 'Thợ may', 'Nông dân'), ans: 'D',
      why: 'Người làm ruộng, trồng trọt, chăn nuôi là nông dân.' },
    { sec: 'Nghề nghiệp', name: 'Câu 5', pts: 1,
      text: 'Người đưa thư, đưa hàng đến tận nhà làm nghề gì?',
      opts: o4('Nhân viên bưu điện, giao hàng', 'Ngư dân', 'Đầu bếp', 'Ca sĩ'), ans: 'A',
      why: 'Người chuyển thư, chuyển hàng đến nhà là nhân viên bưu điện, giao hàng.' },
    { sec: 'Mua bán', name: 'Câu 6', pts: 1,
      text: 'Khi mua đồ ăn đóng gói, em nên xem thông tin gì?',
      opts: o4('Màu của túi', 'Hạn sử dụng', 'Độ nặng của kệ', 'Tên người bán'), ans: 'B',
      why: 'Cần xem hạn sử dụng để không mua phải đồ đã hết hạn, hỏng.' },
    { sec: 'Mua bán', name: 'Câu 7', pts: 1,
      text: 'Đi chợ, siêu thị nên mang theo gì để bảo vệ môi trường?',
      opts: o4('Thật nhiều túi ni lông', 'Không mang gì', 'Túi (làn) dùng nhiều lần', 'Xả rác cho vui'), ans: 'C',
      why: 'Mang làn, túi dùng nhiều lần giúp giảm rác túi ni lông.' },
    { sec: 'Mua bán', name: 'Câu 8', pts: 1,
      text: 'Hành vi nào là KHÔNG trung thực khi mua bán?',
      opts: o4('Trả đủ tiền', 'Xếp hàng chờ tính tiền', 'Cảm ơn người bán', 'Lấy hàng mà không trả tiền'), ans: 'D',
      why: 'Lấy hàng không trả tiền là lấy trộm, không trung thực.' },
    { sec: 'Mua bán', name: 'Câu 9', pts: 1,
      text: 'Hàng hoá được làm ra từ đâu?',
      opts: o4('Từ công sức lao động của con người', 'Tự nhiên có sẵn', 'Rơi từ trên trời', 'Mọc lên trong đêm'), ans: 'A',
      why: 'Hàng hoá do con người trồng trọt, chăn nuôi, sản xuất ra.' },
    { sec: 'Mua bán', name: 'Câu 10', pts: 1,
      text: 'Khi tính tiền ở siêu thị, em nên làm gì?',
      opts: o4('Chen ngang lên trước', 'Xô đẩy người khác', 'Xếp hàng chờ đến lượt', 'La hét ầm ĩ'), ans: 'C',
      why: 'Xếp hàng chờ đến lượt là cách ứng xử văn minh nơi công cộng.' },
  ],
},

/* ═══════════ ĐỀ 18 — CỘNG ĐỒNG: PHƯƠNG TIỆN VÀ AN TOÀN GIAO THÔNG ═══════════ */
{
  id: 8808, title: 'Đề 18 · Phương tiện và an toàn giao thông', time: 20,
  questions: [
    { sec: 'Giao thông', name: 'Câu 1', pts: 1,
      text: 'Phương tiện nào đi trên đường bộ?',
      opts: o4('Ô tô, xe máy, xe đạp', 'Tàu thuỷ', 'Máy bay', 'Ca nô'), ans: 'A',
      why: 'Ô tô, xe máy, xe đạp là phương tiện giao thông đường bộ.' },
    { sec: 'Giao thông', name: 'Câu 2', pts: 1,
      text: 'Phương tiện nào đi trên mặt nước?',
      opts: o4('Tàu hoả', 'Thuyền, tàu thuỷ, ca nô', 'Ô tô', 'Xe đạp'), ans: 'B',
      why: 'Thuyền, tàu thuỷ, ca nô là phương tiện giao thông đường thuỷ.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Máy bay là phương tiện giao thông đường nào?',
      opts: o4('Đường bộ', 'Đường thuỷ', 'Đường hàng không', 'Đường sắt'), ans: 'C',
      why: 'Máy bay bay trên trời — phương tiện giao thông đường hàng không.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Tàu hoả chạy trên loại đường nào?',
      opts: o4('Đường sông', 'Đường hàng không', 'Đường mòn', 'Đường sắt (đường ray)'), ans: 'D',
      why: 'Tàu hoả chạy trên đường sắt (đường ray).' },
    { sec: 'Giao thông', name: 'Câu 5', pts: 1,
      text: 'Khi ngồi trên ô tô, em nên làm gì cho an toàn?',
      opts: o4('Thắt dây an toàn, ngồi yên', 'Thò đầu, thò tay ra ngoài', 'Đứng lên ghế', 'Mở cửa khi xe chạy'), ans: 'A',
      why: 'Ngồi ô tô phải thắt dây an toàn, ngồi yên, không thò đầu tay ra ngoài.' },
    { sec: 'Giao thông', name: 'Câu 6', pts: 1,
      text: 'Đèn tín hiệu giao thông màu đỏ có nghĩa là gì?',
      opts: o4('Được đi', 'Dừng lại', 'Chuẩn bị đi', 'Rẽ phải'), ans: 'B',
      why: 'Đèn đỏ nghĩa là phải dừng lại.' },
    { sec: 'Giao thông', name: 'Câu 7', pts: 1,
      text: 'Người đi bộ qua đường cần đi ở đâu?',
      opts: o4('Giữa lòng đường', 'Vạch kẻ dành cho người đi bộ', 'Trèo qua dải phân cách', 'Chỗ nào cũng được'), ans: 'B',
      why: 'Qua đường phải đi đúng vạch kẻ dành cho người đi bộ, quan sát hai bên.' },
    { sec: 'Giao thông', name: 'Câu 8', pts: 1,
      text: 'Khi đi thuyền, đi đò qua sông, em phải làm gì?',
      opts: o4('Đứng nhoài ra mép thuyền', 'Nghịch nước dưới sông', 'Mặc áo phao, ngồi yên', 'Chạy nhảy trên thuyền'), ans: 'C',
      why: 'Đi thuyền phải mặc áo phao và ngồi yên để không bị ngã xuống nước.' },
    { sec: 'Giao thông', name: 'Câu 9', pts: 1,
      text: 'Vì sao khi đi xe máy phải đội mũ bảo hiểm?',
      opts: o4('Để làm đẹp', 'Để che nắng cho vui', 'Không có lí do', 'Để bảo vệ đầu khi va chạm'), ans: 'D',
      why: 'Mũ bảo hiểm bảo vệ đầu, giảm chấn thương khi xảy ra tai nạn.' },
    { sec: 'Giao thông', name: 'Câu 10', pts: 1,
      text: 'Đi bộ trên đường không có vỉa hè, em nên đi thế nào?',
      opts: o4('Đi sát mép đường bên phải', 'Đi giữa lòng đường', 'Đi hàng ngang chắn đường', 'Vừa đi vừa đùa giỡn'), ans: 'A',
      why: 'Không có vỉa hè thì đi sát lề bên phải, đi hàng một cho an toàn.' },
  ],
},

/* ═══════════ ĐỀ 19 — CỘNG ĐỒNG: GIỮ VỆ SINH NƠI CÔNG CỘNG ═══════════ */
{
  id: 8809, title: 'Đề 19 · Giữ vệ sinh nơi công cộng', time: 20,
  questions: [
    { sec: 'Vệ sinh', name: 'Câu 1', pts: 1,
      text: 'Ở công viên, khi có rác em nên làm gì?',
      opts: o4('Bỏ rác vào thùng rác', 'Vứt xuống cỏ', 'Ném xuống hồ', 'Giấu dưới ghế đá'), ans: 'A',
      why: 'Rác phải bỏ vào thùng rác để giữ nơi công cộng sạch đẹp.' },
    { sec: 'Vệ sinh', name: 'Câu 2', pts: 1,
      text: 'Việc nào làm bẩn nơi công cộng?',
      opts: o4('Bỏ rác đúng nơi', 'Vẽ bậy lên tường, khạc nhổ bừa bãi', 'Trồng thêm cây', 'Quét dọn sạch sẽ'), ans: 'B',
      why: 'Vẽ bậy, khạc nhổ bừa bãi làm bẩn và xấu nơi công cộng.' },
    { sec: 'Vệ sinh', name: 'Câu 3', pts: 1,
      text: 'Vì sao cần giữ sạch đường phố, công viên?',
      opts: o4('Để nhiều rác hơn', 'Để có mùi hôi', 'Cho đẹp, thoáng, mọi người khoẻ mạnh', 'Không có lí do'), ans: 'C',
      why: 'Nơi công cộng sạch giúp đẹp, thoáng và mọi người khoẻ mạnh.' },
    { sec: 'Vệ sinh', name: 'Câu 4', pts: 1,
      text: 'Thấy bạn vứt rác ra đường, em nên làm gì?',
      opts: o4('Vứt theo cho vui', 'Cười và khen bạn', 'Mặc kệ', 'Nhắc bạn nhặt bỏ vào thùng rác'), ans: 'D',
      why: 'Nên nhắc bạn nhặt rác bỏ đúng nơi để giữ đường phố sạch.' },
    { sec: 'Vệ sinh', name: 'Câu 5', pts: 1,
      text: 'Khi đi vệ sinh ở nơi công cộng, em nên thế nào?',
      opts: o4('Dội nước, giữ sạch, rửa tay', 'Để bẩn cho người sau', 'Không dội nước', 'Vẽ bậy lên tường'), ans: 'A',
      why: 'Dùng xong dội nước, giữ sạch và rửa tay để giữ vệ sinh chung.' },
    { sec: 'Vệ sinh', name: 'Câu 6', pts: 1,
      text: 'Rác vứt bừa bãi ra sông, hồ gây hậu quả gì?',
      opts: o4('Nước sạch hơn', 'Ô nhiễm nguồn nước, hôi thối', 'Nhiều cá hơn', 'Không sao cả'), ans: 'B',
      why: 'Rác dưới sông hồ làm ô nhiễm nước, bốc mùi và hại sinh vật.' },
    { sec: 'Vệ sinh', name: 'Câu 7', pts: 1,
      text: 'Để nơi công cộng có bóng mát, đẹp hơn, ta nên làm gì?',
      opts: o4('Chặt hết cây', 'Bẻ cành, ngắt hoa', 'Trồng và chăm sóc cây xanh', 'Giẫm lên bãi cỏ'), ans: 'C',
      why: 'Trồng và chăm sóc cây xanh giúp nơi công cộng mát và đẹp.' },
    { sec: 'Vệ sinh', name: 'Câu 8', pts: 1,
      text: 'Hành động nào giữ gìn nơi công cộng?',
      opts: o4('Hái trộm hoa', 'Ngồi lên bồn hoa', 'Vứt rác bừa bãi', 'Không giẫm lên cỏ, không hái hoa'), ans: 'D',
      why: 'Không giẫm cỏ, không hái hoa giúp giữ gìn vẻ đẹp nơi công cộng.' },
    { sec: 'Vệ sinh', name: 'Câu 9', pts: 1,
      text: 'Khi ho, hắt hơi nơi đông người, em nên làm gì?',
      opts: o4('Che miệng, mũi lại', 'Ho thẳng vào người khác', 'Khạc nhổ ra sàn', 'Không cần làm gì'), ans: 'A',
      why: 'Che miệng mũi khi ho, hắt hơi giúp không lây bệnh cho người khác.' },
    { sec: 'Vệ sinh', name: 'Câu 10', pts: 1,
      text: 'Giữ vệ sinh nơi công cộng là trách nhiệm của ai?',
      opts: o4('Chỉ của bác lao công', 'Chỉ của người lớn', 'Của tất cả mọi người', 'Không của ai cả'), ans: 'C',
      why: 'Mỗi người đều có trách nhiệm giữ sạch nơi công cộng.' },
  ],
},

/* ═══════════ ĐỀ 20 — THỰC VẬT: NƠI SỐNG VÀ CÁC BỘ PHẬN ═══════════ */
{
  id: 8810, title: 'Đề 20 · Nơi sống và các bộ phận của cây', time: 20,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Cây nào sống ở dưới nước?',
      opts: o4('Cây sen, cây bèo', 'Cây bàng', 'Cây phượng', 'Cây xoài'), ans: 'A',
      why: 'Sen, bèo, súng là những cây sống dưới nước.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Cây nào sống trên cạn?',
      opts: o4('Cây bèo', 'Cây mít, cây phượng', 'Cây rong', 'Cây rau muống nước'), ans: 'B',
      why: 'Mít, phượng, bàng... là những cây sống trên cạn.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Bộ phận nào của cây hút nước và chất từ đất?',
      opts: o4('Lá', 'Hoa', 'Rễ', 'Quả'), ans: 'C',
      why: 'Rễ cắm xuống đất để hút nước và chất nuôi cây.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Bộ phận nào của cây thường có màu xanh, giúp cây quang hợp?',
      opts: o4('Rễ', 'Thân', 'Hoa', 'Lá'), ans: 'D',
      why: 'Lá cây màu xanh, nhận ánh sáng để chế tạo thức ăn cho cây.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Bộ phận nào nâng đỡ cây và đưa nước từ rễ lên lá?',
      opts: o4('Thân cây', 'Bông hoa', 'Quả', 'Hạt'), ans: 'A',
      why: 'Thân cây nâng đỡ cành lá và dẫn nước từ rễ lên nuôi cây.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Bộ phận nào của cây thường nở đẹp, có hương thơm?',
      opts: o4('Rễ', 'Hoa', 'Thân', 'Rễ phụ'), ans: 'B',
      why: 'Hoa là bộ phận thường có màu đẹp, hương thơm, về sau tạo thành quả.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Cây xương rồng sống được ở nơi nào?',
      opts: o4('Dưới đáy biển', 'Trong tủ lạnh', 'Nơi khô hạn, ít nước như sa mạc', 'Trên mây'), ans: 'C',
      why: 'Xương rồng chịu hạn tốt, sống được ở vùng khô hạn, ít mưa.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Cây cối cần những gì để sống và lớn lên?',
      opts: o4('Chỉ cần bóng tối', 'Chỉ cần tiếng nhạc', 'Không cần gì cả', 'Nước, ánh sáng, không khí, chất trong đất'), ans: 'D',
      why: 'Cây cần nước, ánh sáng, không khí và chất dinh dưỡng trong đất.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Từ đâu mà cây con mọc lên được?',
      opts: o4('Từ hạt (hoặc cành, củ) của cây', 'Từ hòn đá', 'Từ túi ni lông', 'Từ cục sắt'), ans: 'A',
      why: 'Nhiều cây mọc lên từ hạt; có cây mọc từ cành, củ đem trồng.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Cây rau muống, bèo tây thường sống ở đâu?',
      opts: o4('Trên núi đá khô', 'Ở ao, hồ, nơi có nước', 'Trong sa mạc', 'Trên mái nhà khô'), ans: 'B',
      why: 'Rau muống nước, bèo tây là cây sống ở ao hồ, nơi có nhiều nước.' },
  ],
},

/* ═══════════ ĐỀ 21 — THỰC VẬT: ÍCH LỢI VÀ BẢO VỆ ═══════════ */
{
  id: 8811, title: 'Đề 21 · Ích lợi của cây và cách bảo vệ', time: 20,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Loại cây nào cho ta thức ăn hằng ngày?',
      opts: o4('Cây lúa, cây rau, cây ăn quả', 'Cây cột điện', 'Cây nhựa giả', 'Cỏ dại độc'), ans: 'A',
      why: 'Lúa, rau, cây ăn quả cho ta lương thực và thực phẩm.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Cây cho gỗ để đóng bàn ghế, làm nhà là loại cây gì?',
      opts: o4('Cây rau', 'Cây lấy gỗ (lim, xoan...)', 'Cây hoa', 'Cây cỏ'), ans: 'B',
      why: 'Cây lấy gỗ như lim, xoan, keo cho gỗ để làm nhà, đóng đồ.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Cây xanh nhả ra khí gì giúp ta dễ thở?',
      opts: o4('Khí độc', 'Khói bụi', 'Khí ô-xi (khí trong lành)', 'Khói than'), ans: 'C',
      why: 'Cây xanh nhả khí ô-xi, làm không khí trong lành, dễ thở.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Rừng cây có vai trò gì với môi trường?',
      opts: o4('Làm ô nhiễm không khí', 'Gây lũ lụt', 'Không có vai trò gì', 'Giữ đất, giữ nước, cho không khí sạch'), ans: 'D',
      why: 'Rừng giữ đất chống xói mòn, giữ nước và làm sạch không khí.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Có loại cây nào gây hại cho con người không?',
      opts: o4('Có, một số cây có nhựa độc, quả độc', 'Không, cây nào cũng ăn được', 'Không có cây nào cả', 'Cây nào cũng độc'), ans: 'A',
      why: 'Một số cây có nhựa hoặc quả độc; không nên tự ý hái ăn cây lạ.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Việc nào giúp bảo vệ cây xanh và rừng?',
      opts: o4('Chặt cây bừa bãi', 'Trồng cây, chăm sóc, không chặt phá', 'Đốt rừng', 'Bẻ cành hái lá lung tung'), ans: 'B',
      why: 'Trồng, chăm sóc cây và không chặt phá là cách bảo vệ rừng.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Vì sao chúng ta cần trồng nhiều cây xanh?',
      opts: o4('Cây làm bẩn thành phố', 'Cây gây nóng thêm', 'Cây cho bóng mát, không khí sạch', 'Trồng cây vô ích'), ans: 'C',
      why: 'Cây xanh cho bóng mát, làm sạch không khí và góp phần chống lũ.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Để chăm sóc cây trồng, em nên làm gì?',
      opts: o4('Bỏ mặc không tưới', 'Nhổ cây lên chơi', 'Bẻ hết lá', 'Tưới nước, nhổ cỏ, bắt sâu cho cây'), ans: 'D',
      why: 'Tưới nước, nhổ cỏ, bắt sâu giúp cây lớn nhanh, khoẻ mạnh.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Thấy bạn bẻ cành, ngắt hoa nơi công cộng, em nên làm gì?',
      opts: o4('Khuyên bạn không nên làm vậy', 'Bẻ theo cho vui', 'Khen bạn giỏi', 'Ngắt thêm hoa'), ans: 'A',
      why: 'Nên khuyên bạn không bẻ cành, ngắt hoa để giữ cây và cảnh đẹp.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Cây bông, cây đay cho ta nguyên liệu để làm gì?',
      opts: o4('Làm nhà bằng đá', 'Dệt vải, làm sợi', 'Nấu sắt', 'Làm xi măng'), ans: 'B',
      why: 'Cây bông, cây đay cho sợi để dệt vải, may quần áo.' },
  ],
},

/* ═══════════ ĐỀ 22 — ĐỘNG VẬT: NƠI SỐNG VÀ BỘ PHẬN ═══════════ */
{
  id: 8812, title: 'Đề 22 · Nơi sống và bộ phận của con vật', time: 20,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào sống dưới nước?',
      opts: o4('Con cá, con tôm, con cua', 'Con gà', 'Con mèo', 'Con chó'), ans: 'A',
      why: 'Cá, tôm, cua sống dưới nước.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào sống trên cạn?',
      opts: o4('Con cá chép', 'Con trâu, con bò, con gà', 'Con mực', 'Con sứa'), ans: 'B',
      why: 'Trâu, bò, gà, chó là những con vật sống trên cạn.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con vật nào vừa sống được ở nước, vừa sống trên cạn?',
      opts: o4('Con hổ', 'Con voi', 'Con ếch', 'Con đại bàng'), ans: 'C',
      why: 'Ếch sống được cả dưới nước và trên cạn (loài lưỡng cư).' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Cá thở và bơi được dưới nước nhờ bộ phận nào?',
      opts: o4('Đôi cánh', 'Bốn chân', 'Hai tay', 'Mang và vây, đuôi'), ans: 'D',
      why: 'Cá thở bằng mang, bơi nhờ vây và đuôi.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con chim bay được là nhờ bộ phận nào?',
      opts: o4('Đôi cánh', 'Cái vây', 'Cái mang', 'Bốn chân'), ans: 'A',
      why: 'Chim có đôi cánh để bay và thường làm tổ trên cây.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con vật nào có bốn chân, đẻ con và cho sữa nuôi con?',
      opts: o4('Con cá', 'Con trâu, con bò', 'Con ong', 'Con muỗi'), ans: 'B',
      why: 'Trâu, bò có bốn chân, đẻ con và nuôi con bằng sữa.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Gà, vịt, chim đẻ ra gì để sinh con?',
      opts: o4('Đẻ ra sữa', 'Đẻ ra cá', 'Đẻ ra trứng', 'Đẻ ra hạt'), ans: 'C',
      why: 'Gà, vịt, chim đẻ trứng, trứng nở thành con.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con vật nào sống ở rừng?',
      opts: o4('Con cá vàng', 'Con tôm', 'Con cua đồng', 'Con hổ, con khỉ, con voi'), ans: 'D',
      why: 'Hổ, khỉ, voi là những con vật sống trong rừng.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Con vật nào biết bay và làm tổ trên cây?',
      opts: o4('Con chim', 'Con cá', 'Con trâu', 'Con rùa'), ans: 'A',
      why: 'Chim có cánh, biết bay và thường làm tổ trên cây.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Con vịt sống được ở đâu?',
      opts: o4('Chỉ trên núi cao', 'Cả trên cạn và bơi dưới nước', 'Chỉ dưới đáy biển', 'Chỉ trên mây'), ans: 'B',
      why: 'Vịt đi trên cạn và bơi dưới nước nhờ chân có màng.' },
  ],
},

/* ═══════════ ĐỀ 23 — ĐỘNG VẬT: ÍCH LỢI, TÁC HẠI VÀ BẢO VỆ ═══════════ */
{
  id: 8813, title: 'Đề 23 · Ích lợi của con vật và cách bảo vệ', time: 20,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con ong, con bướm giúp ích gì cho cây?',
      opts: o4('Giúp hoa thụ phấn để tạo quả', 'Ăn hết lá cây', 'Làm cây chết', 'Không có ích gì'), ans: 'A',
      why: 'Ong, bướm hút mật và giúp hoa thụ phấn để kết thành quả.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào có ích vì bắt sâu bọ hại lúa?',
      opts: o4('Con chuột', 'Con ếch, con chim sâu', 'Con muỗi', 'Con gián'), ans: 'B',
      why: 'Ếch, chim sâu ăn sâu bọ, giúp bảo vệ mùa màng.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con trâu, con bò giúp ích gì cho nhà nông?',
      opts: o4('Bắt chuột', 'Canh nhà', 'Kéo cày, kéo xe, cho sức lao động', 'Bắt muỗi'), ans: 'C',
      why: 'Trâu, bò kéo cày, kéo xe giúp nhà nông làm ruộng.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con mèo có ích vì việc gì?',
      opts: o4('Cho ta trứng', 'Kéo cày', 'Cho sữa', 'Bắt chuột'), ans: 'D',
      why: 'Mèo bắt chuột, bảo vệ thóc lúa và đồ đạc trong nhà.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào hay phá hoại thóc lúa, đồ đạc?',
      opts: o4('Con chuột', 'Con mèo', 'Con bò', 'Con gà'), ans: 'A',
      why: 'Chuột cắn phá thóc lúa, đồ đạc và truyền bệnh.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con muỗi có hại vì điều gì?',
      opts: o4('Cho ta trứng', 'Đốt người và truyền bệnh', 'Bắt chuột', 'Kéo cày'), ans: 'B',
      why: 'Muỗi đốt hút máu và truyền bệnh như sốt xuất huyết, sốt rét.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Để phòng muỗi đốt và diệt muỗi, ta nên làm gì?',
      opts: o4('Nuôi thêm muỗi', 'Để nước đọng khắp nơi', 'Ngủ màn, dọn nơi nước đọng', 'Vứt rác bừa bãi'), ans: 'C',
      why: 'Ngủ màn và dọn nơi nước đọng (chỗ muỗi đẻ) giúp phòng, diệt muỗi.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Gà, vịt, lợn được nuôi để làm gì?',
      opts: o4('Để phá hoại mùa màng', 'Để cắn người', 'Để truyền bệnh', 'Cho ta thịt, trứng làm thức ăn'), ans: 'D',
      why: 'Gà, vịt, lợn cho ta thịt, trứng — nguồn thức ăn bổ dưỡng.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp bảo vệ các con vật có ích?',
      opts: o4('Không săn bắt bừa bãi, giữ sạch môi trường', 'Bắt hết chim, ếch', 'Đốt rừng nơi chúng ở', 'Xả rác xuống sông'), ans: 'A',
      why: 'Không săn bắt bừa bãi và giữ sạch môi trường giúp bảo vệ động vật.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Với vật nuôi trong nhà (chó, mèo, gà), em nên làm gì?',
      opts: o4('Bỏ đói chúng', 'Cho ăn, chăm sóc, không đánh đập', 'Đánh đập chúng', 'Ném đá vào chúng'), ans: 'B',
      why: 'Cho ăn và chăm sóc vật nuôi tử tế, không đánh đập chúng.' },
  ],
},

/* ═══════════ ĐỀ 24 — CON NGƯỜI: CƠ QUAN VẬN ĐỘNG (XƯƠNG VÀ CƠ) ═══════════ */
{
  id: 8814, title: 'Đề 24 · Cơ quan vận động: xương và cơ', time: 20,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Cơ quan vận động của cơ thể gồm những gì?',
      opts: o4('Bộ xương và hệ cơ', 'Tim và phổi', 'Dạ dày và ruột', 'Mắt và tai'), ans: 'A',
      why: 'Cơ quan vận động gồm bộ xương và hệ cơ, giúp cơ thể cử động.' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Bộ xương có vai trò gì với cơ thể?',
      opts: o4('Giúp nhìn thấy', 'Nâng đỡ và bảo vệ cơ thể', 'Giúp nghe', 'Giúp tiêu hoá'), ans: 'B',
      why: 'Bộ xương nâng đỡ cơ thể và bảo vệ các cơ quan bên trong.' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Nhờ đâu mà tay, chân cử động được?',
      opts: o4('Nhờ mái tóc', 'Nhờ móng tay', 'Nhờ các cơ bám vào xương co và giãn', 'Nhờ làn da'), ans: 'C',
      why: 'Cơ bám vào xương, khi cơ co và giãn thì xương cử động theo.' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Nơi hai xương nối với nhau, giúp gập, duỗi được gọi là gì?',
      opts: o4('Sợi tóc', 'Cái răng', 'Móng chân', 'Khớp xương'), ans: 'D',
      why: 'Khớp là chỗ nối hai xương, giúp tay chân co, duỗi, xoay được.' },
    { sec: 'Cơ thể', name: 'Câu 5', pts: 1,
      text: 'Hộp sọ (xương đầu) bảo vệ cơ quan quan trọng nào?',
      opts: o4('Bộ não', 'Bàn chân', 'Ngón tay', 'Lá gan'), ans: 'A',
      why: 'Hộp sọ là xương cứng bao bọc, bảo vệ bộ não.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Lồng ngực (xương sườn) bảo vệ cơ quan nào?',
      opts: o4('Đôi mắt', 'Tim và phổi', 'Bàn tay', 'Lỗ tai'), ans: 'B',
      why: 'Xương sườn tạo thành lồng ngực bảo vệ tim và phổi.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Cột sống (xương sống) chạy dọc theo phần nào của cơ thể?',
      opts: o4('Trong bàn chân', 'Trong ngón tay', 'Dọc theo lưng', 'Trong lỗ mũi'), ans: 'C',
      why: 'Cột sống chạy dọc lưng, giúp cơ thể đứng thẳng.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Khi em co cánh tay lại, bắp tay (cơ) sẽ thế nào?',
      opts: o4('Biến mất', 'Chảy nước', 'Không thay đổi', 'Co lại, cứng và nổi lên'), ans: 'D',
      why: 'Khi co tay, cơ bắp tay co lại nên cứng và nổi lên.' },
    { sec: 'Cơ thể', name: 'Câu 9', pts: 1,
      text: 'Cơ thể đi, chạy, cầm nắm được là nhờ sự phối hợp của những gì?',
      opts: o4('Xương, cơ và khớp', 'Chỉ có tóc', 'Chỉ có da', 'Chỉ có răng'), ans: 'A',
      why: 'Xương, cơ và khớp phối hợp nhịp nhàng giúp cơ thể vận động.' },
    { sec: 'Cơ thể', name: 'Câu 10', pts: 1,
      text: 'Nếu lười vận động, ít tập thể dục thì xương và cơ sẽ thế nào?',
      opts: o4('Càng khoẻ hơn', 'Yếu và kém dẻo dai', 'To ra rất nhanh', 'Không ảnh hưởng gì'), ans: 'B',
      why: 'Lười vận động khiến xương, cơ yếu đi; tập luyện giúp chắc khoẻ.' },
  ],
},

/* ═══════════ ĐỀ 25 — CON NGƯỜI: CƠ QUAN TIÊU HOÁ ═══════════ */
{
  id: 8815, title: 'Đề 25 · Cơ quan tiêu hoá', time: 20,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Thức ăn được đưa vào cơ thể đầu tiên qua bộ phận nào?',
      opts: o4('Miệng', 'Dạ dày', 'Ruột', 'Gan'), ans: 'A',
      why: 'Miệng là nơi thức ăn được đưa vào, răng nhai nhỏ thức ăn.' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Ở miệng, bộ phận nào cắn và nhai nhỏ thức ăn?',
      opts: o4('Lỗ tai', 'Răng', 'Đôi mắt', 'Ngón tay'), ans: 'B',
      why: 'Răng cắn và nhai nhỏ thức ăn để dễ nuốt và tiêu hoá.' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Ống nối miệng đưa thức ăn xuống dạ dày gọi là gì?',
      opts: o4('Khí quản', 'Mạch máu', 'Thực quản', 'Xương sống'), ans: 'C',
      why: 'Thức ăn đi từ miệng qua thực quản để xuống dạ dày.' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Bộ phận nào co bóp, nhào trộn thức ăn (giống cái túi)?',
      opts: o4('Lá phổi', 'Quả tim', 'Bàn tay', 'Dạ dày'), ans: 'D',
      why: 'Dạ dày như cái túi, co bóp và nhào trộn để nghiền thức ăn.' },
    { sec: 'Cơ thể', name: 'Câu 5', pts: 1,
      text: 'Chất bổ trong thức ăn được thấm vào cơ thể chủ yếu ở đâu?',
      opts: o4('Ở ruột non', 'Ở lỗ mũi', 'Ở đôi mắt', 'Ở bàn chân'), ans: 'A',
      why: 'Ruột non hấp thụ chất bổ từ thức ăn để nuôi cơ thể.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Phần thức ăn không tiêu hoá được sẽ thành gì và thải ra ngoài?',
      opts: o4('Thành máu', 'Thành phân (chất thải)', 'Thành xương', 'Thành tóc'), ans: 'B',
      why: 'Phần bã không tiêu được thành phân, thải ra ngoài qua hậu môn.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Vì sao khi ăn cần nhai kĩ, ăn chậm?',
      opts: o4('Cho lâu hết cơm', 'Để nói chuyện nhiều', 'Giúp dễ tiêu hoá, không đau bụng', 'Không có lí do'), ans: 'C',
      why: 'Nhai kĩ giúp thức ăn nhỏ, dễ tiêu và không bị đau bụng.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Thói quen nào tốt cho cơ quan tiêu hoá?',
      opts: o4('Vừa ăn vừa chạy nhảy', 'Ăn quá no rồi nằm ngay', 'Nhịn ăn cả ngày', 'Ăn đúng bữa, ăn chín uống sôi'), ans: 'D',
      why: 'Ăn đúng bữa, ăn chín uống sôi giúp tiêu hoá tốt, tránh bệnh.' },
    { sec: 'Cơ thể', name: 'Câu 9', pts: 1,
      text: 'Cơ quan tiêu hoá giúp cơ thể điều gì?',
      opts: o4('Biến thức ăn thành chất bổ nuôi cơ thể', 'Giúp ta nhìn thấy', 'Giúp ta nghe', 'Giúp ta bay'), ans: 'A',
      why: 'Cơ quan tiêu hoá biến thức ăn thành chất bổ nuôi cơ thể.' },
    { sec: 'Cơ thể', name: 'Câu 10', pts: 1,
      text: 'Để bảo vệ răng, sau khi ăn em nên làm gì?',
      opts: o4('Ăn thêm kẹo', 'Đánh răng, súc miệng sạch', 'Không làm gì', 'Cắn vật cứng'), ans: 'B',
      why: 'Đánh răng, súc miệng sau khi ăn giúp răng sạch, chắc khoẻ.' },
  ],
},

/* ═══════════ ĐỀ 26 — CON NGƯỜI: ĂN UỐNG SẠCH, PHÒNG BỆNH GIUN ═══════════ */
{
  id: 8816, title: 'Đề 26 · Ăn uống sạch và phòng bệnh giun', time: 20,
  questions: [
    { sec: 'Sức khoẻ', name: 'Câu 1', pts: 1,
      text: 'Để ăn uống sạch, trước khi ăn em cần làm gì?',
      opts: o4('Rửa tay sạch bằng xà phòng', 'Chơi đất rồi ăn ngay', 'Không rửa tay', 'Lau tay vào quần'), ans: 'A',
      why: 'Rửa tay trước khi ăn giúp không đưa vi trùng, trứng giun vào miệng.' },
    { sec: 'Sức khoẻ', name: 'Câu 2', pts: 1,
      text: 'Nên ăn uống thế nào để bảo vệ sức khoẻ?',
      opts: o4('Ăn đồ ôi thiu', 'Ăn chín, uống sôi (nước đun sôi)', 'Uống nước lã', 'Ăn quà vặt bụi bẩn'), ans: 'B',
      why: 'Ăn chín, uống nước đun sôi giúp diệt vi trùng, phòng bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 3', pts: 1,
      text: 'Vì sao không nên uống nước lã (nước chưa đun sôi)?',
      opts: o4('Vì nước lã ngọt', 'Vì nước lã nóng', 'Vì có nhiều vi trùng, dễ đau bụng', 'Không có lí do'), ans: 'C',
      why: 'Nước lã có vi trùng, trứng giun, uống vào dễ đau bụng, nhiễm bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 4', pts: 1,
      text: 'Rau sống, trái cây trước khi ăn cần được làm gì?',
      opts: o4('Ăn ngay không rửa', 'Lăn xuống đất', 'Để ruồi đậu', 'Rửa thật sạch (ngâm nước muối)'), ans: 'D',
      why: 'Rửa sạch rau quả để loại bỏ bụi bẩn, trứng giun và thuốc sâu.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Bệnh giun thường lây vào cơ thể qua đâu?',
      opts: o4('Qua ăn uống bẩn, tay bẩn có trứng giun', 'Qua ánh nắng', 'Qua tiếng ồn', 'Qua gió mát'), ans: 'A',
      why: 'Trứng giun theo tay bẩn, thức ăn bẩn vào miệng rồi vào ruột.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Việc nào giúp phòng tránh bệnh giun?',
      opts: o4('Đi chân đất khắp nơi', 'Cắt móng tay sạch, rửa tay, ăn chín uống sôi', 'Ăn bốc tay bẩn', 'Uống nước lã'), ans: 'B',
      why: 'Giữ tay sạch, cắt móng, ăn chín uống sôi giúp phòng bệnh giun.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Sau khi đi vệ sinh, em cần làm gì để tránh giun, sán?',
      opts: o4('Chạy đi chơi ngay', 'Lau tay vào áo', 'Rửa tay sạch bằng xà phòng', 'Không cần làm gì'), ans: 'C',
      why: 'Rửa tay bằng xà phòng sau khi đi vệ sinh giúp phòng lây trứng giun.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Người bị nhiễm giun thường có biểu hiện gì?',
      opts: o4('Cao lớn nhanh', 'Học giỏi hơn', 'Khoẻ mạnh hơn', 'Gầy yếu, xanh xao, hay đau bụng'), ans: 'D',
      why: 'Giun hút chất bổ khiến người gầy yếu, xanh xao, hay đau bụng.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Để không còn giun trong bụng, thỉnh thoảng cần làm gì?',
      opts: o4('Uống thuốc tẩy giun theo hướng dẫn', 'Ăn thêm kẹo', 'Nhịn ăn', 'Uống nước lã'), ans: 'A',
      why: 'Uống thuốc tẩy giun định kì (theo hướng dẫn) giúp diệt giun.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Thức ăn để ngoài, muốn tránh ruồi đậu vào ta nên làm gì?',
      opts: o4('Để hở cho thoáng', 'Đậy lồng bàn hoặc cất tủ', 'Để ruồi đậu tự nhiên', 'Đặt cạnh thùng rác'), ans: 'B',
      why: 'Đậy lồng bàn, cất tủ giúp ruồi không đậu, thức ăn sạch.' },
  ],
},

/* ═══════════ ĐỀ 27 — CON NGƯỜI: GIỮ VỆ SINH THÂN THỂ ═══════════ */
{
  id: 8817, title: 'Đề 27 · Giữ vệ sinh thân thể', time: 20,
  questions: [
    { sec: 'Sức khoẻ', name: 'Câu 1', pts: 1,
      text: 'Để cơ thể sạch sẽ, mỗi ngày em nên làm gì?',
      opts: o4('Tắm rửa, thay quần áo sạch', 'Không tắm cả tuần', 'Mặc đồ bẩn', 'Bôi bùn lên người'), ans: 'A',
      why: 'Tắm rửa và thay quần áo sạch giúp cơ thể sạch, thơm, khoẻ.' },
    { sec: 'Sức khoẻ', name: 'Câu 2', pts: 1,
      text: 'Mỗi ngày nên đánh răng mấy lần là tốt?',
      opts: o4('Không cần đánh', 'Ít nhất hai lần (sáng và tối)', 'Một tuần một lần', 'Một tháng một lần'), ans: 'B',
      why: 'Đánh răng sáng và tối (ít nhất hai lần) giúp răng sạch, chắc.' },
    { sec: 'Sức khoẻ', name: 'Câu 3', pts: 1,
      text: 'Móng tay dài, bẩn thì em nên làm gì?',
      opts: o4('Để càng dài càng đẹp', 'Nhét đất vào', 'Cắt ngắn, giữ sạch', 'Cắn móng tay'), ans: 'C',
      why: 'Cắt móng tay ngắn và sạch giúp tránh vi trùng, trứng giun.' },
    { sec: 'Sức khoẻ', name: 'Câu 4', pts: 1,
      text: 'Khi nào cần rửa tay bằng xà phòng?',
      opts: o4('Chỉ khi đi ngủ', 'Không bao giờ', 'Chỉ khi tắm', 'Trước khi ăn và sau khi đi vệ sinh'), ans: 'D',
      why: 'Rửa tay trước khi ăn và sau khi đi vệ sinh giúp phòng bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Để bảo vệ đôi mắt, em nên làm gì?',
      opts: o4('Đọc sách nơi đủ ánh sáng, không dụi mắt bẩn', 'Xem điện thoại sát mắt cả ngày', 'Đọc sách trong bóng tối', 'Dụi mắt bằng tay bẩn'), ans: 'A',
      why: 'Đọc sách nơi đủ sáng, không dụi mắt bẩn giúp bảo vệ đôi mắt.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Để giữ đôi tai sạch và nghe tốt, em nên thế nào?',
      opts: o4('Chọc vật nhọn vào tai', 'Giữ tai khô sạch, không chọc vật nhọn vào', 'Nghe nhạc thật to sát tai', 'Để nước bẩn vào tai'), ans: 'B',
      why: 'Giữ tai khô sạch, không chọc vật nhọn giúp bảo vệ tai.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Quần áo mặc bị bẩn, ướt thì em nên làm gì?',
      opts: o4('Mặc tiếp cho bẩn thêm', 'Mặc đồ ướt cả ngày', 'Thay quần áo sạch, khô', 'Không thay bao giờ'), ans: 'C',
      why: 'Thay quần áo sạch, khô giúp cơ thể sạch, tránh cảm và bệnh ngoài da.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Giữ vệ sinh thân thể sạch sẽ giúp em điều gì?',
      opts: o4('Dễ ốm hơn', 'Người hôi hơn', 'Nhiều bệnh hơn', 'Khoẻ mạnh, phòng được nhiều bệnh'), ans: 'D',
      why: 'Cơ thể sạch sẽ giúp em khoẻ mạnh và phòng được nhiều bệnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Khi trời nắng nóng, ra nhiều mồ hôi, em nên làm gì?',
      opts: o4('Tắm rửa, lau khô mồ hôi', 'Để mồ hôi cả ngày', 'Mặc thêm áo dày', 'Không uống nước'), ans: 'A',
      why: 'Tắm rửa, lau mồ hôi giúp cơ thể sạch, tránh rôm sảy, cảm lạnh.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Để tóc sạch, không có chấy (chí), em nên làm gì?',
      opts: o4('Không gội bao giờ', 'Gội đầu, chải tóc thường xuyên', 'Bôi bùn lên tóc', 'Để tóc bết bẩn'), ans: 'B',
      why: 'Gội đầu và chải tóc thường xuyên giúp tóc sạch, không có chấy.' },
  ],
},

/* ═══════════ ĐỀ 28 — TRÁI ĐẤT VÀ BẦU TRỜI: CÁC MÙA ═══════════ */
{
  id: 8818, title: 'Đề 28 · Các mùa trong năm', time: 20,
  questions: [
    { sec: 'Các mùa', name: 'Câu 1', pts: 1,
      text: 'Miền Bắc nước ta thường có mấy mùa trong năm?',
      opts: o4('Bốn mùa: xuân, hạ, thu, đông', 'Hai mùa', 'Ba mùa', 'Năm mùa'), ans: 'A',
      why: 'Miền Bắc có bốn mùa rõ rệt: xuân, hạ, thu, đông.' },
    { sec: 'Các mùa', name: 'Câu 2', pts: 1,
      text: 'Miền Nam nước ta thường có mấy mùa?',
      opts: o4('Bốn mùa', 'Hai mùa: mùa mưa và mùa khô', 'Sáu mùa', 'Không có mùa nào'), ans: 'B',
      why: 'Miền Nam có hai mùa: mùa mưa và mùa khô.' },
    { sec: 'Các mùa', name: 'Câu 3', pts: 1,
      text: 'Mùa nào thường nóng nhất trong năm ở miền Bắc?',
      opts: o4('Mùa xuân', 'Mùa thu', 'Mùa hạ (mùa hè)', 'Mùa đông'), ans: 'C',
      why: 'Mùa hạ (mùa hè) là mùa nóng nhất.' },
    { sec: 'Các mùa', name: 'Câu 4', pts: 1,
      text: 'Mùa nào thường lạnh nhất ở miền Bắc?',
      opts: o4('Mùa xuân', 'Mùa hạ', 'Mùa thu', 'Mùa đông'), ans: 'D',
      why: 'Mùa đông là mùa lạnh nhất, cần mặc ấm.' },
    { sec: 'Các mùa', name: 'Câu 5', pts: 1,
      text: 'Mùa xuân thường có đặc điểm gì?',
      opts: o4('Ấm áp, cây cối đâm chồi nảy lộc', 'Rét buốt, cây trụi lá', 'Nóng bức nhất', 'Lá vàng rụng nhiều'), ans: 'A',
      why: 'Mùa xuân ấm áp, cây cối đâm chồi, đơm hoa.' },
    { sec: 'Các mùa', name: 'Câu 6', pts: 1,
      text: 'Mùa thu ở miền Bắc thường thế nào?',
      opts: o4('Nóng bức nhất', 'Mát mẻ, lá vàng rụng nhiều', 'Rét buốt nhất', 'Mưa dầm suốt ngày'), ans: 'B',
      why: 'Mùa thu mát mẻ, trời trong, lá vàng rụng nhiều.' },
    { sec: 'Các mùa', name: 'Câu 7', pts: 1,
      text: 'Vào mùa đông giá lạnh, em nên ăn mặc thế nào?',
      opts: o4('Mặc áo cộc, quần đùi', 'Cởi trần', 'Mặc áo ấm, đội mũ len, đi tất', 'Đi chân đất'), ans: 'C',
      why: 'Mùa đông cần mặc ấm để giữ sức khoẻ, tránh cảm lạnh.' },
    { sec: 'Các mùa', name: 'Câu 8', pts: 1,
      text: 'Vào mùa hè nắng nóng, khi ra ngoài em nên làm gì?',
      opts: o4('Phơi nắng thật lâu', 'Mặc áo len dày', 'Không uống nước', 'Đội mũ, che nắng, uống đủ nước'), ans: 'D',
      why: 'Mùa hè cần đội mũ, che nắng và uống đủ nước để tránh say nắng.' },
    { sec: 'Các mùa', name: 'Câu 9', pts: 1,
      text: 'Tết Nguyên đán của nước ta thường vào mùa nào?',
      opts: o4('Mùa xuân', 'Mùa hạ', 'Mùa thu', 'Mùa đông'), ans: 'A',
      why: 'Tết Nguyên đán vào đầu năm, đúng dịp mùa xuân.' },
    { sec: 'Các mùa', name: 'Câu 10', pts: 1,
      text: 'Vì sao mỗi mùa em cần ăn mặc phù hợp?',
      opts: o4('Để tốn nhiều quần áo', 'Để giữ sức khoẻ, tránh bị bệnh', 'Cho vui', 'Không có lí do'), ans: 'B',
      why: 'Ăn mặc hợp mùa (ấm khi lạnh, thoáng khi nóng) giúp giữ sức khoẻ.' },
  ],
},

/* ═══════════ ĐỀ 29 — TRÁI ĐẤT VÀ BẦU TRỜI: MẶT TRỜI, MẶT TRĂNG, VÌ SAO ═══════════ */
{
  id: 8819, title: 'Đề 29 · Mặt Trời, Mặt Trăng và các vì sao', time: 20,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Ban ngày, vật nào chiếu sáng và sưởi ấm Trái Đất?',
      opts: o4('Mặt Trời', 'Mặt Trăng', 'Ngôi sao', 'Bóng đèn'), ans: 'A',
      why: 'Mặt Trời chiếu sáng và sưởi ấm cho Trái Đất vào ban ngày.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Ban đêm, vật nào thường sáng nhất trên bầu trời?',
      opts: o4('Mặt Trời', 'Mặt Trăng', 'Đám mây', 'Cầu vồng'), ans: 'B',
      why: 'Ban đêm Mặt Trăng thường sáng nhất trên bầu trời.' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Những chấm nhỏ lấp lánh trên trời đêm là gì?',
      opts: o4('Những bóng đèn', 'Những con đom đóm', 'Các vì sao (ngôi sao)', 'Những hạt mưa'), ans: 'C',
      why: 'Các chấm sáng lấp lánh trên trời đêm là các vì sao.' },
    { sec: 'Bầu trời', name: 'Câu 4', pts: 1,
      text: 'Hình dạng Mặt Trời nhìn thấy trên trời như thế nào?',
      opts: o4('Hình vuông', 'Hình tam giác', 'Hình ngôi sao', 'Hình tròn'), ans: 'D',
      why: 'Mặt Trời nhìn thấy có dạng hình tròn, sáng chói.' },
    { sec: 'Bầu trời', name: 'Câu 5', pts: 1,
      text: 'Vì sao ta không được nhìn thẳng vào Mặt Trời?',
      opts: o4('Vì rất chói, hại mắt', 'Vì Mặt Trời nhỏ', 'Vì Mặt Trời tối', 'Không có lí do'), ans: 'A',
      why: 'Ánh Mặt Trời rất chói, nhìn thẳng vào sẽ hại mắt.' },
    { sec: 'Bầu trời', name: 'Câu 6', pts: 1,
      text: 'Mặt Trăng có lúc tròn, lúc khuyết như lưỡi liềm, đúng hay sai?',
      opts: o4('Sai, luôn hình vuông', 'Đúng, Mặt Trăng có lúc tròn, lúc khuyết', 'Sai, luôn không nhìn thấy', 'Sai, luôn hình tam giác'), ans: 'B',
      why: 'Mặt Trăng thay đổi hình: có đêm tròn, có đêm khuyết như lưỡi liềm.' },
    { sec: 'Bầu trời', name: 'Câu 7', pts: 1,
      text: 'Buổi sáng Mặt Trời mọc ở hướng nào?',
      opts: o4('Hướng tây', 'Hướng bắc', 'Hướng đông', 'Hướng nam'), ans: 'C',
      why: 'Mặt Trời mọc ở hướng đông vào buổi sáng.' },
    { sec: 'Bầu trời', name: 'Câu 8', pts: 1,
      text: 'Buổi chiều Mặt Trời lặn ở hướng nào?',
      opts: o4('Hướng bắc', 'Hướng nam', 'Hướng đông', 'Hướng tây'), ans: 'D',
      why: 'Buổi chiều Mặt Trời lặn ở hướng tây.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Nhờ có Mặt Trời, cây cối và con người mới có được điều gì?',
      opts: o4('Ánh sáng và hơi ấm để sống', 'Bóng tối', 'Giá lạnh', 'Không có gì'), ans: 'A',
      why: 'Mặt Trời cho ánh sáng và hơi ấm để cây, con vật và người sống.' },
    { sec: 'Bầu trời', name: 'Câu 10', pts: 1,
      text: 'Khi trời nắng gắt, muốn ra ngoài em nên làm gì?',
      opts: o4('Nhìn thẳng vào Mặt Trời', 'Đội mũ, che ô, tránh nắng gắt', 'Phơi nắng thật lâu', 'Cởi mũ ra'), ans: 'B',
      why: 'Nắng gắt cần đội mũ, che ô để tránh say nắng và hại da, mắt.' },
  ],
},

/* ═══════════ ĐỀ 30 — ÔN TẬP TỔNG HỢP ═══════════ */
{
  id: 8820, title: 'Đề 30 · Ôn tập tổng hợp', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Gia đình có ông bà, bố mẹ và các con là gia đình mấy thế hệ?',
      opts: o4('Ba thế hệ', 'Một thế hệ', 'Hai thế hệ', 'Bốn thế hệ'), ans: 'A',
      why: 'Ông bà — bố mẹ — các con là ba thế hệ.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Người trồng lúa, nuôi gà lợn làm nghề gì?',
      opts: o4('Bác sĩ', 'Nông dân', 'Thợ may', 'Ca sĩ'), ans: 'B',
      why: 'Người trồng trọt, chăn nuôi là nông dân.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Máy bay là phương tiện giao thông đường nào?',
      opts: o4('Đường bộ', 'Đường thuỷ', 'Đường hàng không', 'Đường sắt'), ans: 'C',
      why: 'Máy bay bay trên trời — phương tiện giao thông đường hàng không.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Con vật nào vừa sống dưới nước, vừa sống trên cạn?',
      opts: o4('Con hổ', 'Con voi', 'Con gà', 'Con ếch'), ans: 'D',
      why: 'Ếch sống được cả dưới nước và trên cạn.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Cơ quan vận động của cơ thể gồm những gì?',
      opts: o4('Bộ xương và hệ cơ', 'Tim và gan', 'Mắt và tai', 'Dạ dày và ruột'), ans: 'A',
      why: 'Cơ quan vận động gồm bộ xương và hệ cơ.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Bộ phận nào của cây hút nước và chất từ đất?',
      opts: o4('Lá', 'Rễ', 'Hoa', 'Quả'), ans: 'B',
      why: 'Rễ cắm xuống đất để hút nước và chất nuôi cây.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Ban ngày, vật nào chiếu sáng và sưởi ấm Trái Đất?',
      opts: o4('Mặt Trăng', 'Ngôi sao', 'Mặt Trời', 'Đám mây'), ans: 'C',
      why: 'Mặt Trời chiếu sáng và sưởi ấm Trái Đất vào ban ngày.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Để phòng bệnh giun, trước khi ăn em cần làm gì?',
      opts: o4('Chơi đất rồi ăn', 'Ăn bốc tay bẩn', 'Uống nước lã', 'Rửa tay sạch bằng xà phòng'), ans: 'D',
      why: 'Rửa tay sạch trước khi ăn giúp phòng bệnh giun và đau bụng.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Miền Bắc nước ta có mấy mùa trong năm?',
      opts: o4('Bốn mùa', 'Hai mùa', 'Ba mùa', 'Một mùa'), ans: 'A',
      why: 'Miền Bắc có bốn mùa: xuân, hạ, thu, đông.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp giữ vệ sinh nơi công cộng?',
      opts: o4('Vẽ bậy lên tường', 'Vứt rác xuống hồ', 'Bỏ rác vào thùng rác', 'Hái hoa, bẻ cành'), ans: 'C',
      why: 'Bỏ rác đúng vào thùng rác giúp nơi công cộng sạch đẹp.' },
  ],
},

];

SUBJECTS.push({
  id: 'tnxh2', name: 'Tự nhiên & Xã hội', short: 'TN&XH 2', icon: '🌍', grade: 2,
  exams: TNXH2_EXAMS, ready: true,
  heroTitle: 'Tự nhiên và Xã hội lớp 2 — gia đình, nghề nghiệp, giao thông, cây con và cơ quan vận động',
  heroMeta: '📚 30 đề &nbsp;•&nbsp; 300 câu &nbsp;•&nbsp; ⏱ 15-20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
