// TIN HỌC & CÔNG NGHỆ — LỚP 5 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// Nội dung bám chương trình GDPT 2018:
//   TIN HỌC (đề 1–6):
//     - Tìm kiếm thông tin trên Internet: từ khoá, chọn nguồn tin cậy
//     - Thư điện tử: gửi/nhận email cơ bản
//     - Phần mềm trình chiếu: tạo trang chiếu, chèn chữ & hình
//     - Thuật toán & sơ đồ khối: tuần tự, lặp, rẽ nhánh
//     - Lập trình trực quan Scratch: khối lệnh, nhân vật, sân khấu
//     - An toàn, đạo đức & bảo mật: mật khẩu, thông tin cá nhân
//   CÔNG NGHỆ (đề 7–10):
//     - Nhà ở: vai trò, các khu vực
//     - Sử dụng điện an toàn & tiết kiệm
//     - Lắp mạch điện đơn giản: nguồn, dây, bóng đèn, công tắc
//     - Thiết kế & làm sản phẩm; nghề nghiệp kĩ thuật – công nghệ

const TINCN5_EXAMS = [

/* ═══════════ ĐỀ 1 — TÌM KIẾM THÔNG TIN TRÊN INTERNET ═══════════ */
{
  id: 9321, title: 'Đề 1 · Tìm kiếm thông tin trên Internet', time: 20,
  questions: [
    { sec: 'Tìm kiếm thông tin', name: 'Câu 1', pts: 1,
      text: 'Để tìm thông tin trên Internet, em thường dùng công cụ nào?',
      opts: o4('Máy tìm kiếm (ví dụ Google)', 'Máy tính bỏ túi', 'Phần mềm vẽ', 'Trình soạn thảo văn bản'), ans: 'A',
      why: 'Máy tìm kiếm giúp tìm các trang web chứa thông tin em cần.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 2', pts: 1,
      text: 'Từ ngắn gọn em gõ vào ô tìm kiếm để máy tìm đúng nội dung gọi là gì?',
      opts: o4('Tên tệp', 'Mật khẩu', 'Từ khoá', 'Địa chỉ email'), ans: 'C',
      why: 'Từ khoá là từ hoặc cụm từ mô tả nội dung em muốn tìm.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 3', pts: 1,
      text: 'Muốn tìm về "vòng đời của con bướm", từ khoá nào là hợp lí nhất?',
      opts: o4('trò chơi điện tử', 'vòng đời con bướm', 'ô tô đồ chơi', 'món ăn ngon'), ans: 'B',
      why: 'Từ khoá cần bám sát đúng nội dung cần tìm.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 4', pts: 1,
      text: 'Kết quả tìm kiếm hiện ra rất nhiều trang. Em nên làm gì?',
      opts: o4('Bỏ qua tất cả', 'Bấm bừa vào trang đầu tiên', 'Chọn trang có nhiều quảng cáo nhất', 'Chọn nguồn tin cậy và đọc nội dung phù hợp'), ans: 'D',
      why: 'Cần chọn nguồn đáng tin cậy, phù hợp với điều em cần tìm.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 5', pts: 1,
      text: 'Trang thông tin nào thường đáng tin cậy hơn?',
      opts: o4('Trang của cơ quan giáo dục, sách báo chính thống', 'Trang không rõ ai viết', 'Bình luận của người lạ', 'Tin đồn trên mạng'), ans: 'A',
      why: 'Nguồn chính thống, rõ tác giả và cơ quan quản lí thì đáng tin hơn.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 6', pts: 1,
      text: 'Vì sao không nên tin ngay mọi thông tin tìm được trên mạng?',
      opts: o4('Vì máy tính không bao giờ sai', 'Vì mạng luôn đúng', 'Vì thông tin nào cũng có ích', 'Vì có thông tin sai, chưa được kiểm chứng'), ans: 'D',
      why: 'Trên mạng có cả thông tin sai lệch, cần kiểm chứng lại.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 7', pts: 1,
      text: 'Khi dùng thông tin, hình ảnh của người khác cho bài học, em nên làm gì?',
      opts: o4('Nói là do em tự làm ra', 'Xoá tên tác giả đi', 'Ghi rõ nguồn, không tự nhận là của mình', 'Bán lại cho bạn'), ans: 'C',
      why: 'Tôn trọng bản quyền: cần ghi nguồn và không nhận vơ của người khác.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 8', pts: 1,
      text: 'Để mở một trang web khi đã biết địa chỉ, em gõ địa chỉ vào đâu?',
      opts: o4('Ô âm lượng loa', 'Thanh địa chỉ của trình duyệt', 'Nút tắt máy', 'Phím cách'), ans: 'B',
      why: 'Địa chỉ web được gõ vào thanh địa chỉ của trình duyệt.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 9', pts: 1,
      text: 'Phần mềm dùng để xem các trang web gọi là gì?',
      opts: o4('Bàn phím', 'Trình chiếu', 'Máy in', 'Trình duyệt web'), ans: 'D',
      why: 'Trình duyệt (ví dụ Chrome, Firefox) dùng để mở và xem trang web.' },
    { sec: 'Tìm kiếm thông tin', name: 'Câu 10', pts: 1,
      text: 'Muốn tìm nhanh, từ khoá nên như thế nào?',
      opts: o4('Toàn dấu chấm than', 'Càng dài dòng càng tốt', 'Ngắn gọn, đúng trọng tâm', 'Viết sai chính tả cho lạ'), ans: 'C',
      why: 'Từ khoá ngắn gọn, đúng trọng tâm giúp máy tìm chính xác hơn.' },
  ],
},

/* ═══════════ ĐỀ 2 — THƯ ĐIỆN TỬ (EMAIL) ═══════════ */
{
  id: 9322, title: 'Đề 2 · Thư điện tử', time: 20,
  questions: [
    { sec: 'Thư điện tử', name: 'Câu 1', pts: 1,
      text: 'Thư điện tử (email) dùng để làm gì?',
      opts: o4('Gửi và nhận thư qua Internet', 'In tài liệu ra giấy', 'Đo nhiệt độ phòng', 'Chơi nhạc'), ans: 'A',
      why: 'Email là cách gửi, nhận thư dưới dạng điện tử qua Internet.' },
    { sec: 'Thư điện tử', name: 'Câu 2', pts: 1,
      text: 'Địa chỉ email nào sau đây đúng định dạng?',
      opts: o4('an nguyen@gmail', 'an.nguyen.gmail.com', 'an.nguyen@gmail.com', 'an@nguyen@gmail.com'), ans: 'C',
      why: 'Địa chỉ email có dạng tên@tên-miền, ví dụ an.nguyen@gmail.com.' },
    { sec: 'Thư điện tử', name: 'Câu 3', pts: 1,
      text: 'Kí tự đặc trưng luôn có trong mọi địa chỉ email là gì?',
      opts: o4('#', '@', '*', '?'), ans: 'B',
      why: 'Mỗi địa chỉ email đều có kí tự @ ngăn giữa tên và tên miền.' },
    { sec: 'Thư điện tử', name: 'Câu 4', pts: 1,
      text: 'Khi soạn thư, ô "Đến / To" dùng để làm gì?',
      opts: o4('Ghi số điện thoại nhà em', 'Ghi màu chữ', 'Ghi ngày sinh', 'Ghi địa chỉ email người nhận'), ans: 'D',
      why: 'Ô "Đến / To" là nơi nhập địa chỉ email của người nhận.' },
    { sec: 'Thư điện tử', name: 'Câu 5', pts: 1,
      text: 'Ô "Chủ đề / Subject" của thư dùng để làm gì?',
      opts: o4('Ghi tóm tắt nội dung chính của thư', 'Ghi mật khẩu', 'Ghi giá tiền', 'Để trống bắt buộc'), ans: 'A',
      why: 'Chủ đề cho người nhận biết ngay thư nói về việc gì.' },
    { sec: 'Thư điện tử', name: 'Câu 6', pts: 1,
      text: 'Muốn gửi kèm một tấm ảnh theo thư, em dùng chức năng nào?',
      opts: o4('Tăng âm lượng', 'Xoá thư', 'Thu nhỏ cửa sổ', 'Đính kèm tệp (Attach)'), ans: 'D',
      why: 'Chức năng đính kèm cho phép gửi thêm tệp, ảnh cùng với thư.' },
    { sec: 'Thư điện tử', name: 'Câu 7', pts: 1,
      text: 'Soạn xong thư, em bấm nút nào để thư đi tới người nhận?',
      opts: o4('Lưu nháp mãi mãi', 'Xoá (Delete)', 'Gửi (Send)', 'Tắt máy'), ans: 'C',
      why: 'Bấm "Gửi / Send" thì thư mới được chuyển đến người nhận.' },
    { sec: 'Thư điện tử', name: 'Câu 8', pts: 1,
      text: 'Nhận được thư lạ có đường liên kết yêu cầu nhập mật khẩu, em nên làm gì?',
      opts: o4('Bấm ngay và nhập mật khẩu', 'Không bấm vào, báo cho người lớn', 'Gửi mật khẩu cho họ', 'Chuyển tiếp cho cả lớp'), ans: 'B',
      why: 'Thư lạ đòi mật khẩu thường là lừa đảo; không bấm và báo người lớn.' },
    { sec: 'Thư điện tử', name: 'Câu 9', pts: 1,
      text: 'Thư rác, thư quảng cáo không mong muốn thường được gọi là gì?',
      opts: o4('Chữ ký', 'Ảnh nền', 'Danh bạ', 'Spam'), ans: 'D',
      why: 'Thư rác gửi hàng loạt, không mong muốn được gọi là spam.' },
    { sec: 'Thư điện tử', name: 'Câu 10', pts: 1,
      text: 'Muốn cùng một thư gửi tới nhiều người một lúc, em làm thế nào?',
      opts: o4('Phải viết lại thư từng lần', 'Chỉ gửi được cho một người', 'Ghi nhiều địa chỉ email vào ô người nhận', 'Không thể gửi cho nhiều người'), ans: 'C',
      why: 'Có thể nhập nhiều địa chỉ ở ô người nhận để gửi cùng lúc.' },
  ],
},

/* ═══════════ ĐỀ 3 — PHẦN MỀM TRÌNH CHIẾU ═══════════ */
{
  id: 9323, title: 'Đề 3 · Phần mềm trình chiếu', time: 20,
  questions: [
    { sec: 'Phần mềm trình chiếu', name: 'Câu 1', pts: 1,
      text: 'Phần mềm trình chiếu dùng để làm gì?',
      opts: o4('Tạo các trang chiếu để trình bày', 'Tính toán số học', 'Nghe nhạc', 'Đo cân nặng'), ans: 'A',
      why: 'Phần mềm trình chiếu giúp tạo các trang chiếu để giới thiệu nội dung.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 2', pts: 1,
      text: 'Mỗi trang trong bài trình chiếu được gọi là gì?',
      opts: o4('Thư mục', 'Bảng tính', 'Trang chiếu (slide)', 'Biểu đồ'), ans: 'C',
      why: 'Từng trang của bài trình chiếu gọi là trang chiếu (slide).' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 3', pts: 1,
      text: 'Muốn thêm chữ vào trang chiếu, em chèn đối tượng nào?',
      opts: o4('Bóng đèn', 'Hộp văn bản', 'Công tắc', 'Loa'), ans: 'B',
      why: 'Chữ trên trang chiếu được nhập trong hộp văn bản.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 4', pts: 1,
      text: 'Muốn minh hoạ bằng tranh, em chèn gì vào trang chiếu?',
      opts: o4('Số trang giấy', 'Mật khẩu', 'Địa chỉ email', 'Hình ảnh'), ans: 'D',
      why: 'Có thể chèn hình ảnh để trang chiếu sinh động, dễ hiểu hơn.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 5', pts: 1,
      text: 'Muốn thêm một trang chiếu mới vào bài, em chọn lệnh nào?',
      opts: o4('Thêm trang chiếu mới', 'Tắt máy tính', 'In ra giấy', 'Xoá cả bài'), ans: 'A',
      why: 'Lệnh thêm trang chiếu mới sẽ tạo thêm một slide trong bài.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 6', pts: 1,
      text: 'Một trang chiếu tốt nên như thế nào?',
      opts: o4('Không có nội dung gì', 'Chữ nhỏ li ti chật kín trang', 'Toàn màu tối, chữ tối khó đọc', 'Chữ ngắn gọn, dễ đọc, có hình minh hoạ'), ans: 'D',
      why: 'Trang chiếu nên ngắn gọn, rõ ràng, có hình minh hoạ giúp người xem dễ theo dõi.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 7', pts: 1,
      text: 'Trang chiếu đầu tiên của bài thường ghi gì?',
      opts: o4('Danh sách thư rác', 'Lời cảm ơn kết thúc', 'Tên chủ đề (tiêu đề) và người thực hiện', 'Mật khẩu wifi'), ans: 'C',
      why: 'Trang đầu (trang tiêu đề) giới thiệu tên chủ đề và người trình bày.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 8', pts: 1,
      text: 'Chế độ nào giúp em xem bài chiếu toàn màn hình như khi trình bày?',
      opts: o4('Xoá trang', 'Trình chiếu (Slide Show)', 'Đổi tên tệp', 'Thu nhỏ cửa sổ'), ans: 'B',
      why: 'Chế độ trình chiếu (Slide Show) hiển thị từng trang toàn màn hình.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 9', pts: 1,
      text: 'Muốn giữ lại bài trình chiếu để dùng sau, em phải làm gì?',
      opts: o4('Đóng phần mềm không lưu', 'Tắt máy ngay', 'Rút điện', 'Lưu tệp lại'), ans: 'D',
      why: 'Cần lưu tệp thì lần sau mới mở lại được bài đã làm.' },
    { sec: 'Phần mềm trình chiếu', name: 'Câu 10', pts: 1,
      text: 'Khi trình bày trước lớp, em nên làm gì?',
      opts: o4('Bấm loạn cho nhanh hết', 'Quay lưng lại và đọc thật nhỏ', 'Nói rõ ràng, chỉ vào nội dung trên trang chiếu', 'Che kín màn hình'), ans: 'C',
      why: 'Trình bày cần rõ ràng, kết hợp lời nói với nội dung trên trang chiếu.' },
  ],
},

/* ═══════════ ĐỀ 4 — THUẬT TOÁN & SƠ ĐỒ KHỐI ═══════════ */
{
  id: 9324, title: 'Đề 4 · Thuật toán & sơ đồ khối', time: 20,
  questions: [
    { sec: 'Thuật toán', name: 'Câu 1', pts: 1,
      text: 'Thuật toán là gì?',
      opts: o4('Các bước được sắp xếp theo thứ tự để giải một công việc', 'Một loại máy in', 'Một trang web', 'Một tấm ảnh'), ans: 'A',
      why: 'Thuật toán là dãy các bước có thứ tự để hoàn thành công việc.' },
    { sec: 'Thuật toán', name: 'Câu 2', pts: 1,
      text: 'Các bước "lấy bột → nhào bột → nướng bánh" là ví dụ về cấu trúc nào?',
      opts: o4('Lặp', 'Rẽ nhánh', 'Tuần tự', 'Ngẫu nhiên'), ans: 'C',
      why: 'Làm lần lượt hết bước này đến bước khác là cấu trúc tuần tự.' },
    { sec: 'Thuật toán', name: 'Câu 3', pts: 1,
      text: '"Nếu trời mưa thì mang ô, nếu không thì đội mũ" là cấu trúc nào?',
      opts: o4('Tuần tự', 'Rẽ nhánh (điều kiện)', 'Lặp', 'Không có cấu trúc'), ans: 'B',
      why: 'Chọn việc làm tuỳ theo điều kiện đúng/sai là cấu trúc rẽ nhánh.' },
    { sec: 'Thuật toán', name: 'Câu 4', pts: 1,
      text: '"Đánh răng lặp lại 20 lần" thể hiện cấu trúc nào?',
      opts: o4('Điều kiện', 'Rẽ nhánh', 'Tuần tự một lần', 'Lặp'), ans: 'D',
      why: 'Làm đi làm lại một việc nhiều lần là cấu trúc lặp.' },
    { sec: 'Thuật toán', name: 'Câu 5', pts: 1,
      text: 'Cách vẽ các hình khối và mũi tên để mô tả thuật toán gọi là gì?',
      opts: o4('Sơ đồ khối', 'Bảng tính', 'Danh bạ', 'Trang chiếu'), ans: 'A',
      why: 'Sơ đồ khối dùng hình khối và mũi tên để mô tả các bước thuật toán.' },
    { sec: 'Thuật toán', name: 'Câu 6', pts: 1,
      text: 'Trong sơ đồ khối, mũi tên dùng để làm gì?',
      opts: o4('Chỉ hướng gió', 'Trang trí cho đẹp', 'Ghi điểm số', 'Chỉ thứ tự thực hiện các bước'), ans: 'D',
      why: 'Mũi tên nối các bước và chỉ thứ tự thực hiện của thuật toán.' },
    { sec: 'Thuật toán', name: 'Câu 7', pts: 1,
      text: 'Trong sơ đồ khối, khối hình thoi thường dùng để làm gì?',
      opts: o4('Kết thúc chương trình', 'Ghi tên người dùng', 'Ghi điều kiện để rẽ nhánh', 'Chèn hình ảnh'), ans: 'C',
      why: 'Khối hình thoi thể hiện một điều kiện đúng/sai để rẽ nhánh.' },
    { sec: 'Thuật toán', name: 'Câu 8', pts: 1,
      text: 'Vì sao các bước trong thuật toán phải đúng thứ tự?',
      opts: o4('Vì cho vui', 'Vì sai thứ tự có thể ra kết quả sai', 'Vì thứ tự không quan trọng', 'Vì để trang trí'), ans: 'B',
      why: 'Đổi thứ tự các bước có thể làm công việc không thực hiện đúng.' },
    { sec: 'Thuật toán', name: 'Câu 9', pts: 1,
      text: 'Mỗi thuật toán đều cần có điều gì?',
      opts: o4('Một tấm ảnh vui', 'Thật nhiều màu sắc', 'Ít nhất 100 bước', 'Điểm bắt đầu và điểm kết thúc rõ ràng'), ans: 'D',
      why: 'Thuật toán luôn có bước bắt đầu và bước kết thúc rõ ràng.' },
    { sec: 'Thuật toán', name: 'Câu 10', pts: 1,
      text: 'Mô tả thuật toán bằng sơ đồ khối có lợi gì?',
      opts: o4('Làm bài chậm hơn', 'Tốn giấy hơn nên hay', 'Dễ nhìn, dễ hiểu các bước và thứ tự', 'Không có ích gì'), ans: 'C',
      why: 'Sơ đồ khối trực quan, giúp hiểu rõ các bước và thứ tự thực hiện.' },
  ],
},

/* ═══════════ ĐỀ 5 — LẬP TRÌNH SCRATCH ═══════════ */
{
  id: 9325, title: 'Đề 5 · Lập trình trực quan Scratch', time: 20,
  questions: [
    { sec: 'Scratch', name: 'Câu 1', pts: 1,
      text: 'Trong Scratch, em lập trình bằng cách nào?',
      opts: o4('Kéo thả và ghép các khối lệnh', 'Gõ toàn bộ mã lệnh khó', 'Vẽ tranh rồi in ra', 'Nói vào micro'), ans: 'A',
      why: 'Scratch là lập trình trực quan: kéo thả và ghép các khối lệnh lại với nhau.' },
    { sec: 'Scratch', name: 'Câu 2', pts: 1,
      text: 'Nhân vật di chuyển, nói chuyện trong Scratch được gọi là gì?',
      opts: o4('Bàn phím', 'Sân khấu', 'Nhân vật (sprite)', 'Chuột'), ans: 'C',
      why: 'Đối tượng thực hiện lệnh (di chuyển, nói...) trong Scratch là nhân vật (sprite).' },
    { sec: 'Scratch', name: 'Câu 3', pts: 1,
      text: 'Vùng nền phía sau, nơi các nhân vật hoạt động gọi là gì?',
      opts: o4('Khối lệnh', 'Sân khấu (stage)', 'Thư mục', 'Thanh địa chỉ'), ans: 'B',
      why: 'Sân khấu (stage) là vùng nền nơi các nhân vật hoạt động.' },
    { sec: 'Scratch', name: 'Câu 4', pts: 1,
      text: 'Khối "khi bấm lá cờ xanh" thường dùng để làm gì?',
      opts: o4('Đổi mật khẩu', 'Kết thúc và tắt máy', 'Xoá nhân vật', 'Bắt đầu chạy chương trình'), ans: 'D',
      why: 'Khối "khi bấm lá cờ xanh" là điểm bắt đầu chạy chương trình.' },
    { sec: 'Scratch', name: 'Câu 5', pts: 1,
      text: 'Muốn nhân vật lặp đi lặp lại một việc, em dùng nhóm khối nào?',
      opts: o4('Khối lặp (lặp lại / lặp mãi)', 'Khối âm thanh', 'Khối vẽ nền', 'Khối tắt máy'), ans: 'A',
      why: 'Khối lặp giúp thực hiện một nhóm lệnh nhiều lần.' },
    { sec: 'Scratch', name: 'Câu 6', pts: 1,
      text: 'Khối "nếu ... thì ..." trong Scratch dùng để làm gì?',
      opts: o4('Đổi màu sân khấu ngẫu nhiên', 'Luôn làm mọi lúc', 'Xoá chương trình', 'Rẽ nhánh: chỉ làm khi điều kiện đúng'), ans: 'D',
      why: 'Khối "nếu ... thì ..." chỉ thực hiện lệnh bên trong khi điều kiện đúng.' },
    { sec: 'Scratch', name: 'Câu 7', pts: 1,
      text: 'Khối "di chuyển 10 bước" làm nhân vật thế nào?',
      opts: o4('Đổi trang phục', 'Biến mất', 'Đi tới một đoạn theo hướng đang quay', 'Phát ra âm thanh'), ans: 'C',
      why: 'Khối "di chuyển 10 bước" đưa nhân vật tiến lên theo hướng nó đang quay.' },
    { sec: 'Scratch', name: 'Câu 8', pts: 1,
      text: 'Muốn nhân vật hiện lời "Xin chào" trên màn hình, em dùng khối nào?',
      opts: o4('Khối "di chuyển ..."', 'Khối "nói ..."', 'Khối "xoay ..."', 'Khối "đợi ..."'), ans: 'B',
      why: 'Khối "nói" hiển thị bong bóng lời thoại của nhân vật.' },
    { sec: 'Scratch', name: 'Câu 9', pts: 1,
      text: 'Các khối lệnh trong Scratch được xếp thành các nhóm màu để làm gì?',
      opts: o4('Không có ý nghĩa', 'Chỉ để cho đẹp', 'Để đánh đố người dùng', 'Giúp dễ tìm theo loại (chuyển động, âm thanh, điều khiển...)'), ans: 'D',
      why: 'Mỗi nhóm màu gom các khối cùng loại, giúp tìm khối nhanh hơn.' },
    { sec: 'Scratch', name: 'Câu 10', pts: 1,
      text: 'Nếu chương trình Scratch chạy sai, em nên làm gì trước tiên?',
      opts: o4('Tắt máy bỏ luôn', 'Đập bàn phím', 'Kiểm tra lại thứ tự và nội dung các khối lệnh', 'Đổ lỗi cho máy tính'), ans: 'C',
      why: 'Chạy sai thường do khối lệnh xếp sai thứ tự hoặc chọn nhầm; cần kiểm tra lại.' },
  ],
},

/* ═══════════ ĐỀ 6 — AN TOÀN, ĐẠO ĐỨC & BẢO MẬT ═══════════ */
{
  id: 9326, title: 'Đề 6 · An toàn, đạo đức và bảo mật', time: 20,
  questions: [
    { sec: 'An toàn & bảo mật', name: 'Câu 1', pts: 1,
      text: 'Mật khẩu mạnh nên như thế nào?',
      opts: o4('Có chữ, số, kí tự và khó đoán', 'Là ngày sinh của em', 'Là dãy 123456', 'Là tên của em'), ans: 'A',
      why: 'Mật khẩu mạnh kết hợp chữ, số, kí tự và không dễ đoán.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 2', pts: 1,
      text: 'Với mật khẩu của mình, em nên làm gì?',
      opts: o4('Kể cho cả lớp', 'Dán lên màn hình', 'Giữ bí mật, không cho người khác biết', 'Đăng lên mạng'), ans: 'C',
      why: 'Mật khẩu phải được giữ bí mật để bảo vệ tài khoản của em.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 3', pts: 1,
      text: 'Người lạ trên mạng hỏi địa chỉ nhà, số điện thoại, em nên làm gì?',
      opts: o4('Trả lời đầy đủ cho họ', 'Không cung cấp và báo người lớn', 'Gửi cả ảnh nhà em', 'Rủ họ đến chơi'), ans: 'B',
      why: 'Không chia sẻ thông tin cá nhân cho người lạ và cần báo người lớn.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 4', pts: 1,
      text: 'Thông tin nào sau đây là thông tin cá nhân cần bảo vệ?',
      opts: o4('Số ngày trong tuần', 'Tên một loài chim', 'Màu sắc cầu vồng', 'Địa chỉ nhà và số điện thoại'), ans: 'D',
      why: 'Địa chỉ, số điện thoại là thông tin cá nhân, không nên lộ cho người lạ.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 5', pts: 1,
      text: 'Khi thấy nội dung xấu, đáng sợ trên mạng, em nên làm gì?',
      opts: o4('Tắt đi và báo cho người lớn', 'Xem thật kĩ', 'Gửi cho bạn bè', 'Bắt chước làm theo'), ans: 'A',
      why: 'Gặp nội dung xấu nên rời khỏi và báo người lớn để được giúp đỡ.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 6', pts: 1,
      text: 'Dùng máy tính, điện thoại lâu liên tục có hại gì?',
      opts: o4('Làm em cao lớn nhanh', 'Giúp mắt sáng hơn', 'Không ảnh hưởng gì', 'Mỏi mắt, hại sức khoẻ nếu không nghỉ hợp lí'), ans: 'D',
      why: 'Dùng thiết bị quá lâu gây mỏi mắt, mệt; cần nghỉ ngơi hợp lí.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 7', pts: 1,
      text: 'Chép nguyên bài của người khác rồi nói là của mình là hành vi gì?',
      opts: o4('Được phép luôn', 'Rất đáng khen', 'Không trung thực, vi phạm đạo đức', 'Cách học tốt'), ans: 'C',
      why: 'Nhận vơ sản phẩm của người khác là không trung thực, cần tránh.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 8', pts: 1,
      text: 'Khi đăng ảnh bạn bè lên mạng, em nên làm gì?',
      opts: o4('Đăng thoải mái không cần hỏi', 'Hỏi ý kiến bạn trước', 'Chỉnh sửa xấu đi cho vui', 'Gắn kèm địa chỉ nhà bạn'), ans: 'B',
      why: 'Cần tôn trọng người khác, xin phép trước khi đăng ảnh của họ.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 9', pts: 1,
      text: 'Vì sao không nên tải phần mềm từ trang web lạ, không rõ nguồn?',
      opts: o4('Vì máy sẽ chạy nhanh hơn', 'Vì tải rất nhanh', 'Vì phần mềm nào cũng an toàn', 'Có thể chứa vi-rút gây hại máy tính'), ans: 'D',
      why: 'Phần mềm từ nguồn lạ có thể chứa vi-rút, mã độc gây hại máy tính.' },
    { sec: 'An toàn & bảo mật', name: 'Câu 10', pts: 1,
      text: 'Khi bị bạn trên mạng nói lời xúc phạm, doạ nạt, em nên làm gì?',
      opts: o4('Im lặng chịu đựng mãi', 'Chửi lại cho bõ tức', 'Không đôi co, lưu bằng chứng và báo người lớn', 'Doạ lại họ'), ans: 'C',
      why: 'Gặp bắt nạt trên mạng, nên giữ bình tĩnh, lưu bằng chứng và báo người lớn tin cậy.' },
  ],
},

/* ═══════════ ĐỀ 7 — NHÀ Ở ═══════════ */
{
  id: 9327, title: 'Đề 7 · Nhà ở', time: 20,
  questions: [
    { sec: 'Nhà ở', name: 'Câu 1', pts: 1,
      text: 'Vai trò chính của nhà ở đối với con người là gì?',
      opts: o4('Nơi trú ngụ, che nắng mưa, sinh hoạt và nghỉ ngơi', 'Chỉ để chụp ảnh', 'Chỉ để chứa xe', 'Không có vai trò gì'), ans: 'A',
      why: 'Nhà ở giúp con người tránh nắng mưa, là nơi sinh hoạt và nghỉ ngơi.' },
    { sec: 'Nhà ở', name: 'Câu 2', pts: 1,
      text: 'Khu vực nào trong nhà dùng để nấu ăn?',
      opts: o4('Phòng khách', 'Phòng ngủ', 'Nhà bếp', 'Nhà tắm'), ans: 'C',
      why: 'Nhà bếp là nơi nấu nướng, chế biến thức ăn.' },
    { sec: 'Nhà ở', name: 'Câu 3', pts: 1,
      text: 'Phòng khách trong nhà thường dùng để làm gì?',
      opts: o4('Nấu ăn', 'Tiếp khách và sinh hoạt chung', 'Tắm giặt', 'Nuôi gà'), ans: 'B',
      why: 'Phòng khách là nơi tiếp khách và cả nhà sinh hoạt chung.' },
    { sec: 'Nhà ở', name: 'Câu 4', pts: 1,
      text: 'Khu vực nào dùng để nghỉ ngơi, ngủ?',
      opts: o4('Nhà kho', 'Nhà bếp', 'Ban công', 'Phòng ngủ'), ans: 'D',
      why: 'Phòng ngủ là nơi để nghỉ ngơi và ngủ.' },
    { sec: 'Nhà ở', name: 'Câu 5', pts: 1,
      text: 'Để nhà ở luôn thoáng mát, sạch sẽ, em nên làm gì?',
      opts: o4('Dọn dẹp, mở cửa cho thoáng, giữ vệ sinh', 'Đóng kín mọi cửa suốt ngày', 'Vứt rác bừa bãi', 'Để đồ đạc lộn xộn'), ans: 'A',
      why: 'Dọn dẹp thường xuyên và thông thoáng giúp nhà sạch, mát, dễ chịu.' },
    { sec: 'Nhà ở', name: 'Câu 6', pts: 1,
      text: 'Kiểu nhà nào thường thấy ở vùng hay ngập lụt, sông nước?',
      opts: o4('Nhà băng tuyết', 'Nhà cao tầng bê tông', 'Nhà kính', 'Nhà sàn'), ans: 'D',
      why: 'Nhà sàn dựng cao trên cọc, phù hợp vùng sông nước, hay ngập.' },
    { sec: 'Nhà ở', name: 'Câu 7', pts: 1,
      text: 'Vật dụng nào giúp sắp xếp, cất giữ quần áo gọn gàng?',
      opts: o4('Quạt trần', 'Bếp gas', 'Tủ quần áo', 'Vòi nước'), ans: 'C',
      why: 'Tủ quần áo dùng để cất giữ, sắp xếp quần áo cho gọn gàng.' },
    { sec: 'Nhà ở', name: 'Câu 8', pts: 1,
      text: 'Để phòng cháy trong nhà bếp, em nên làm gì?',
      opts: o4('Để giẻ, giấy ngay cạnh bếp lửa', 'Tắt bếp khi nấu xong, không để vật dễ cháy gần lửa', 'Bật bếp rồi bỏ đi chơi', 'Chơi diêm gần bếp gas'), ans: 'B',
      why: 'Tắt bếp sau khi dùng và tránh để vật dễ cháy gần lửa giúp phòng cháy.' },
    { sec: 'Nhà ở', name: 'Câu 9', pts: 1,
      text: 'Nhà ở sạch sẽ, ngăn nắp mang lại lợi ích gì?',
      opts: o4('Không có lợi ích gì', 'Làm cả nhà hay ốm', 'Khiến nhà chật hơn', 'Bảo vệ sức khoẻ, sống dễ chịu, tìm đồ nhanh'), ans: 'D',
      why: 'Nhà sạch, gọn giúp giữ sức khoẻ, sống thoải mái và dễ tìm đồ.' },
    { sec: 'Nhà ở', name: 'Câu 10', pts: 1,
      text: 'Là thành viên trong nhà, em nên làm gì để giữ nhà cửa?',
      opts: o4('Bày bừa cho người khác dọn', 'Chỉ ngồi chơi mặc kệ', 'Cùng dọn dẹp, giữ gìn đồ dùng chung', 'Phá đồ đạc trong nhà'), ans: 'C',
      why: 'Mỗi thành viên nên cùng dọn dẹp và giữ gìn đồ dùng chung.' },
  ],
},

/* ═══════════ ĐỀ 8 — SỬ DỤNG ĐIỆN AN TOÀN & TIẾT KIỆM ═══════════ */
{
  id: 9328, title: 'Đề 8 · Sử dụng điện an toàn và tiết kiệm', time: 20,
  questions: [
    { sec: 'An toàn điện', name: 'Câu 1', pts: 1,
      text: 'Việc làm nào sau đây rất nguy hiểm khi dùng điện?',
      opts: o4('Cắm, rút phích điện bằng tay ướt', 'Rút phích khi không dùng', 'Dùng ổ cắm đúng cách', 'Tắt đèn khi ra khỏi phòng'), ans: 'A',
      why: 'Tay ướt dẫn điện tốt nên chạm vào điện rất dễ bị điện giật.' },
    { sec: 'An toàn điện', name: 'Câu 2', pts: 1,
      text: 'Khi thấy dây điện bị đứt, hở lõi đồng, em nên làm gì?',
      opts: o4('Nối lại bằng tay', 'Cầm tay vào xem', 'Tránh xa và báo người lớn', 'Nhúng nước cho mát'), ans: 'C',
      why: 'Dây điện hở rất nguy hiểm; phải tránh xa và báo người lớn xử lí.' },
    { sec: 'An toàn điện', name: 'Câu 3', pts: 1,
      text: 'Không được cho vật gì vào ổ cắm điện?',
      opts: o4('Phích cắm đúng của thiết bị', 'Que sắt, đũa, ngón tay', 'Nắp che ổ điện an toàn', 'Không cho gì cả là đúng nhất'), ans: 'B',
      why: 'Chọc que kim loại hay ngón tay vào ổ điện dễ bị điện giật nguy hiểm.' },
    { sec: 'An toàn điện', name: 'Câu 4', pts: 1,
      text: 'Ra khỏi phòng, để tiết kiệm điện em nên làm gì?',
      opts: o4('Bật quạt suốt đêm', 'Bật hết đèn cho sáng nhà', 'Mở tủ lạnh cả ngày', 'Tắt đèn, quạt nếu không dùng'), ans: 'D',
      why: 'Tắt các thiết bị khi không dùng giúp tiết kiệm điện.' },
    { sec: 'An toàn điện', name: 'Câu 5', pts: 1,
      text: 'Loại bóng đèn nào thường tiết kiệm điện hơn khi chiếu sáng?',
      opts: o4('Bóng đèn LED', 'Bóng đèn sợi đốt nóng', 'Bếp than', 'Nến sáp'), ans: 'A',
      why: 'Đèn LED tiêu thụ ít điện hơn mà vẫn chiếu sáng tốt.' },
    { sec: 'An toàn điện', name: 'Câu 6', pts: 1,
      text: 'Ban ngày trời sáng, để tiết kiệm điện ta nên tận dụng gì?',
      opts: o4('Bật cả đèn lẫn tivi', 'Bật thêm nhiều đèn', 'Đóng kín và bật đèn cả ngày', 'Ánh sáng tự nhiên (mở rèm, cửa sổ)'), ans: 'D',
      why: 'Tận dụng ánh sáng mặt trời ban ngày giúp giảm dùng điện thắp sáng.' },
    { sec: 'An toàn điện', name: 'Câu 7', pts: 1,
      text: 'Chơi thả diều, đá bóng gần đường dây điện cao thế thì sao?',
      opts: o4('Càng gần càng vui', 'Hoàn toàn an toàn', 'Rất nguy hiểm, cần tránh xa', 'Nên leo lên cột điện xem'), ans: 'C',
      why: 'Đường dây cao thế rất nguy hiểm; phải chơi tránh xa các cột và dây điện.' },
    { sec: 'An toàn điện', name: 'Câu 8', pts: 1,
      text: 'Rút phích cắm điện đúng cách là kéo vào đâu?',
      opts: o4('Kéo mạnh vào dây điện', 'Cầm vào thân phích để rút', 'Giật bằng răng', 'Dùng kéo cắt dây'), ans: 'B',
      why: 'Nên cầm thân phích để rút; kéo vào dây dễ làm đứt, hở dây nguy hiểm.' },
    { sec: 'An toàn điện', name: 'Câu 9', pts: 1,
      text: 'Cắm quá nhiều thiết bị vào một ổ điện có thể gây ra điều gì?',
      opts: o4('Không sao cả', 'Tiết kiệm điện hơn', 'Máy chạy nhanh hơn', 'Quá tải, nóng dây, dễ chập cháy'), ans: 'D',
      why: 'Cắm quá nhiều gây quá tải, dây nóng lên và có thể chập cháy.' },
    { sec: 'An toàn điện', name: 'Câu 10', pts: 1,
      text: 'Nếu thấy bạn bị điện giật, việc làm nào đúng?',
      opts: o4('Đứng nhìn không làm gì', 'Lấy tay kéo bạn ra ngay', 'Ngắt nguồn điện rồi gọi người lớn giúp', 'Té nước vào bạn'), ans: 'C',
      why: 'Phải ngắt nguồn điện trước và gọi người lớn; không dùng tay không kéo bạn.' },
  ],
},

/* ═══════════ ĐỀ 9 — LẮP MẠCH ĐIỆN ĐƠN GIẢN ═══════════ */
{
  id: 9329, title: 'Đề 9 · Lắp mạch điện đơn giản', time: 20,
  questions: [
    { sec: 'Mạch điện', name: 'Câu 1', pts: 1,
      text: 'Một mạch điện đơn giản để thắp sáng bóng đèn cần những bộ phận nào?',
      opts: o4('Nguồn điện, dây dẫn, bóng đèn (và công tắc)', 'Chỉ cần một sợi dây', 'Chỉ cần bóng đèn', 'Chỉ cần công tắc'), ans: 'A',
      why: 'Mạch điện đơn giản gồm nguồn điện, dây dẫn, bóng đèn và thường có công tắc.' },
    { sec: 'Mạch điện', name: 'Câu 2', pts: 1,
      text: 'Trong mạch điện đơn giản, pin đóng vai trò gì?',
      opts: o4('Công tắc', 'Dây dẫn điện', 'Nguồn điện cung cấp năng lượng', 'Bóng đèn'), ans: 'C',
      why: 'Pin là nguồn điện, cung cấp năng lượng cho mạch hoạt động.' },
    { sec: 'Mạch điện', name: 'Câu 3', pts: 1,
      text: 'Công tắc trong mạch điện có tác dụng gì?',
      opts: o4('Phát ra ánh sáng', 'Đóng, ngắt dòng điện để bật/tắt đèn', 'Cung cấp điện', 'Làm dây dài hơn'), ans: 'B',
      why: 'Công tắc dùng để đóng hoặc ngắt mạch, giúp bật hay tắt đèn.' },
    { sec: 'Mạch điện', name: 'Câu 4', pts: 1,
      text: 'Khi công tắc ở vị trí "đóng" (bật) thì điều gì xảy ra?',
      opts: o4('Pin biến mất', 'Mạch hở, đèn tắt', 'Đèn nổ tung', 'Mạch kín, có dòng điện, đèn sáng'), ans: 'D',
      why: 'Đóng công tắc làm mạch kín, dòng điện chạy qua nên đèn sáng.' },
    { sec: 'Mạch điện', name: 'Câu 5', pts: 1,
      text: 'Khi công tắc "ngắt" (tắt) thì mạch điện thế nào?',
      opts: o4('Mạch hở, không có dòng điện, đèn tắt', 'Đèn vẫn sáng bình thường', 'Đèn sáng mạnh hơn', 'Pin sạc đầy lại'), ans: 'A',
      why: 'Ngắt công tắc làm mạch hở, dòng điện không chạy nên đèn tắt.' },
    { sec: 'Mạch điện', name: 'Câu 6', pts: 1,
      text: 'Để đèn sáng, mạch điện phải ở trạng thái nào?',
      opts: o4('Hết pin', 'Mạch hở một đoạn', 'Đứt dây', 'Mạch kín (dòng điện chạy được liên tục)'), ans: 'D',
      why: 'Chỉ khi mạch kín, dòng điện mới chạy qua và làm đèn sáng.' },
    { sec: 'Mạch điện', name: 'Câu 7', pts: 1,
      text: 'Vật liệu nào sau đây dẫn điện, dùng làm dây dẫn?',
      opts: o4('Gỗ khô', 'Nhựa', 'Đồng (kim loại)', 'Cao su'), ans: 'C',
      why: 'Kim loại như đồng dẫn điện tốt nên được dùng làm lõi dây dẫn.' },
    { sec: 'Mạch điện', name: 'Câu 8', pts: 1,
      text: 'Lớp vỏ nhựa hoặc cao su bọc ngoài dây điện có tác dụng gì?',
      opts: o4('Dẫn điện nhanh hơn', 'Cách điện, giúp an toàn khi cầm', 'Làm đèn sáng hơn', 'Làm pin lâu hết'), ans: 'B',
      why: 'Nhựa, cao su không dẫn điện nên bọc ngoài để cách điện, dùng an toàn.' },
    { sec: 'Mạch điện', name: 'Câu 9', pts: 1,
      text: 'Lắp mạch xong mà đèn không sáng. Nguyên nhân có thể là gì?',
      opts: o4('Vì dùng dây đồng', 'Vì đèn mới nên không sáng', 'Vì có công tắc', 'Dây lỏng, hết pin hoặc mạch bị hở'), ans: 'D',
      why: 'Đèn không sáng thường do dây tiếp xúc kém, hết pin hoặc mạch hở.' },
    { sec: 'Mạch điện', name: 'Câu 10', pts: 1,
      text: 'Khi làm thí nghiệm mạch điện ở lớp, em nên dùng nguồn điện nào?',
      opts: o4('Dây điện cao thế', 'Ổ điện trong tường 220V', 'Pin nhỏ an toàn', 'Sét trời mưa'), ans: 'C',
      why: 'Chỉ dùng pin nhỏ an toàn; tuyệt đối không thí nghiệm với điện lưới 220V.' },
  ],
},

/* ═══════════ ĐỀ 10 — THIẾT KẾ SẢN PHẨM & NGHỀ NGHIỆP ═══════════ */
{
  id: 9330, title: 'Đề 10 · Thiết kế sản phẩm và nghề nghiệp', time: 20,
  questions: [
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 1', pts: 1,
      text: 'Bước đầu tiên khi thiết kế, làm một sản phẩm là gì?',
      opts: o4('Xác định sản phẩm cần làm và yêu cầu của nó', 'Vứt bỏ vật liệu', 'Đem đi bán ngay', 'Khoe với bạn'), ans: 'A',
      why: 'Trước tiên cần xác định rõ làm sản phẩm gì và yêu cầu đặt ra.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 2', pts: 1,
      text: 'Sau khi có ý tưởng, bước tiếp theo thường là gì?',
      opts: o4('Ăn cơm', 'Nghỉ luôn không làm', 'Vẽ phác thảo và chọn vật liệu', 'Xoá hết ý tưởng'), ans: 'C',
      why: 'Có ý tưởng rồi thì vẽ phác thảo và chuẩn bị, lựa chọn vật liệu.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 3', pts: 1,
      text: 'Sắp xếp đúng thứ tự các bước làm sản phẩm nào sau đây là hợp lí?',
      opts: o4('Làm ra sản phẩm → lên ý tưởng → vứt đi', 'Lên ý tưởng → làm ra sản phẩm → kiểm tra, chỉnh sửa', 'Kiểm tra → vứt đi → lên ý tưởng', 'Bán → làm → nghĩ'), ans: 'B',
      why: 'Quy trình hợp lí: lên ý tưởng, chế tạo, rồi kiểm tra và chỉnh sửa.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 4', pts: 1,
      text: 'Làm xong sản phẩm, em nên làm gì để nó tốt hơn?',
      opts: o4('Đổ lỗi cho dụng cụ', 'Bỏ luôn không xem lại', 'Che giấu lỗi đi', 'Kiểm tra, thử dùng và chỉnh sửa chỗ chưa đạt'), ans: 'D',
      why: 'Cần thử nghiệm, đánh giá và sửa lại những chỗ chưa đạt yêu cầu.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 5', pts: 1,
      text: 'Khi dùng kéo, dao, dụng cụ sắc để làm sản phẩm, em cần làm gì?',
      opts: o4('Cẩn thận, làm đúng cách để an toàn', 'Vung vẩy cho vui', 'Chĩa vào bạn', 'Vừa chạy vừa cầm'), ans: 'A',
      why: 'Dụng cụ sắc nhọn cần dùng cẩn thận, đúng cách để tránh bị thương.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 6', pts: 1,
      text: 'Để bảo vệ môi trường, làm sản phẩm em nên ưu tiên điều gì?',
      opts: o4('Đốt hết vật liệu thừa', 'Dùng thật nhiều rồi vứt', 'Xả rác bừa bãi', 'Tận dụng vật liệu tái chế, tránh lãng phí'), ans: 'D',
      why: 'Tận dụng vật liệu tái chế, tránh lãng phí giúp bảo vệ môi trường.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 7', pts: 1,
      text: 'Người chuyên sửa chữa, lắp đặt hệ thống điện gọi là gì?',
      opts: o4('Giáo viên', 'Bác sĩ', 'Thợ điện', 'Nông dân'), ans: 'C',
      why: 'Thợ điện là người lắp đặt, sửa chữa các thiết bị và hệ thống điện.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 8', pts: 1,
      text: 'Nghề nào dưới đây gắn liền với máy tính và lập trình?',
      opts: o4('Ngư dân', 'Lập trình viên', 'Đầu bếp', 'Thợ may'), ans: 'B',
      why: 'Lập trình viên là người viết chương trình cho máy tính.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 9', pts: 1,
      text: 'Người thiết kế, chế tạo máy móc, thiết bị kĩ thuật gọi là gì?',
      opts: o4('Vận động viên', 'Ca sĩ', 'Hoạ sĩ vẽ tranh', 'Kĩ sư'), ans: 'D',
      why: 'Kĩ sư là người thiết kế, chế tạo máy móc và thiết bị kĩ thuật.' },
    { sec: 'Thiết kế & nghề nghiệp', name: 'Câu 10', pts: 1,
      text: 'Tìm hiểu về các nghề nghiệp từ nhỏ có ích lợi gì?',
      opts: o4('Làm em lười học', 'Không có ích gì', 'Giúp em hiểu công việc và định hướng tương lai', 'Chỉ để cho vui'), ans: 'C',
      why: 'Hiểu biết về nghề nghiệp giúp em quý trọng lao động và định hướng tương lai.' },
  ],
},

];

SUBJECTS.push({ id:'tincn5', name:'Tin học & Công nghệ', short:'Tin-CN 5', icon:'💻', grade:5, exams:TINCN5_EXAMS, ready:true, heroTitle:'Tin học & Công nghệ lớp 5 — tìm kiếm & thư điện tử, trình chiếu, thuật toán Scratch và mạch điện', heroMeta:'📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018' });
