// LỊCH SỬ VÀ ĐỊA LÍ — LỚP 4 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// Chương trình lớp 4 tìm hiểu địa phương và các vùng miền của Việt Nam,
// gắn với một số nhân vật – sự kiện lịch sử tiêu biểu của từng vùng:
//   - Địa phương em và kĩ năng bản đồ, phương hướng
//   - Trung du và miền núi Bắc Bộ (Đền Hùng, Điện Biên Phủ)
//   - Đồng bằng Bắc Bộ (sông Hồng, Thăng Long – Hà Nội, Văn Miếu)
//   - Duyên hải miền Trung (Cố đô Huế, phố cổ Hội An)
//   - Tây Nguyên (đất ba-dan, cà phê, không gian văn hoá cồng chiêng)
//   - Nam Bộ (đồng bằng sông Cửu Long, Thành phố Hồ Chí Minh)

const LSDL4_EXAMS = [

/* ═══════════ ĐỀ 1 — ĐỊA PHƯƠNG EM VÀ BẢN ĐỒ ═══════════ */
{
  id: 5601, title: 'Đề 1 · Địa phương em và bản đồ', time: 20,
  questions: [
    { sec: 'Bản đồ', name: 'Câu 1', pts: 1,
      text: 'Bản đồ là gì?',
      opts: o4('Hình vẽ thu nhỏ một khu vực trên mặt phẳng', 'Một bức ảnh chụp bầu trời', 'Một quyển truyện', 'Một bài hát'), ans: 'A',
      why: 'Bản đồ là hình vẽ thu nhỏ một vùng đất (hoặc toàn bộ Trái Đất) trên mặt phẳng.' },
    { sec: 'Bản đồ', name: 'Câu 2', pts: 1,
      text: 'Trên bản đồ, hướng ở phía trên thường là hướng nào?',
      opts: o4('Hướng bắc', 'Hướng nam', 'Hướng đông', 'Hướng tây'), ans: 'A',
      why: 'Theo quy ước, phía trên bản đồ là hướng bắc, dưới là nam, phải là đông, trái là tây.' },
    { sec: 'Bản đồ', name: 'Câu 3', pts: 1,
      text: 'Trên bản đồ, sông ngòi thường được vẽ bằng màu gì?',
      opts: o4('Màu xanh nước biển', 'Màu đỏ', 'Màu vàng', 'Màu đen'), ans: 'A',
      why: 'Sông, hồ, biển thường được thể hiện bằng màu xanh nước biển.' },
    { sec: 'Bản đồ', name: 'Câu 4', pts: 1,
      text: 'Phần chú giải (bảng chú thích) trên bản đồ dùng để làm gì?',
      opts: o4('Giải thích ý nghĩa các kí hiệu trên bản đồ', 'Trang trí cho đẹp', 'Ghi tên người vẽ', 'Không có tác dụng'), ans: 'A',
      why: 'Chú giải cho biết mỗi kí hiệu, màu sắc trên bản đồ thể hiện điều gì.' },
    { sec: 'Địa phương', name: 'Câu 5', pts: 1,
      text: 'Đơn vị hành chính nào lớn hơn: xã (phường) hay tỉnh (thành phố)?',
      opts: o4('Tỉnh (thành phố) lớn hơn', 'Xã (phường) lớn hơn', 'Bằng nhau', 'Không so sánh được'), ans: 'A',
      why: 'Tỉnh (thành phố) gồm nhiều huyện; huyện gồm nhiều xã, phường — nên tỉnh lớn hơn xã.' },
    { sec: 'Địa phương', name: 'Câu 6', pts: 1,
      text: 'Thủ đô của nước Việt Nam là thành phố nào?',
      opts: o4('Hà Nội', 'Thành phố Hồ Chí Minh', 'Đà Nẵng', 'Huế'), ans: 'A',
      why: 'Hà Nội là thủ đô của nước Cộng hoà xã hội chủ nghĩa Việt Nam.' },
    { sec: 'Địa phương', name: 'Câu 7', pts: 1,
      text: 'Muốn tìm hiểu về quê hương mình, em có thể làm gì?',
      opts: o4('Quan sát, hỏi người lớn, đọc tài liệu, xem bản đồ', 'Chỉ ngồi đoán', 'Không cần tìm hiểu', 'Nghĩ ra một cách tuỳ ý'), ans: 'A',
      why: 'Quan sát thực tế, hỏi người lớn, đọc tài liệu và xem bản đồ giúp hiểu về quê hương.' },
    { sec: 'Địa phương', name: 'Câu 8', pts: 1,
      text: 'Nghề nghiệp của người dân ở một địa phương phụ thuộc nhiều vào điều gì?',
      opts: o4('Điều kiện tự nhiên nơi đó (đồng bằng, ven biển, miền núi)', 'Màu áo họ mặc', 'Tên của họ', 'Sở thích ăn uống'), ans: 'A',
      why: 'Vùng ven biển làm nghề cá, đồng bằng trồng lúa, miền núi trồng rừng... tuỳ điều kiện tự nhiên.' },
    { sec: 'Địa phương', name: 'Câu 9', pts: 1,
      text: 'Việc nào thể hiện tình yêu quê hương?',
      opts: o4('Giữ gìn cảnh quan, học tốt, giới thiệu nét đẹp quê mình', 'Xả rác nơi công cộng', 'Chê bai quê hương', 'Phá hoại di tích'), ans: 'A',
      why: 'Giữ gìn cảnh quan, chăm học và tự hào giới thiệu quê hương thể hiện tình yêu quê.' },
    { sec: 'Địa phương', name: 'Câu 10', pts: 1,
      text: 'Nước Việt Nam nằm ở khu vực nào của thế giới?',
      opts: o4('Khu vực Đông Nam Á', 'Châu Âu', 'Châu Phi', 'Châu Mĩ'), ans: 'A',
      why: 'Việt Nam nằm ở khu vực Đông Nam Á, thuộc châu Á.' },
  ],
},

/* ═══════════ ĐỀ 2 — TRUNG DU VÀ MIỀN NÚI BẮC BỘ: THIÊN NHIÊN, CON NGƯỜI ═══════════ */
{
  id: 5602, title: 'Đề 2 · Trung du và miền núi Bắc Bộ', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Vùng Trung du và miền núi Bắc Bộ có địa hình chủ yếu là gì?',
      opts: o4('Đồi và núi', 'Đồng bằng rộng phẳng', 'Toàn biển', 'Sa mạc cát'), ans: 'A',
      why: 'Đây là vùng nhiều đồi, núi — địa hình cao và hiểm trở.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đỉnh núi cao nhất Việt Nam là đỉnh nào?',
      opts: o4('Phan-xi-păng', 'Bà Đen', 'Ngự Bình', 'Yên Tử'), ans: 'A',
      why: 'Phan-xi-păng (khoảng 3143 m) thuộc dãy Hoàng Liên Sơn, là đỉnh cao nhất nước ta.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Dãy núi cao và đồ sộ nhất ở miền núi Bắc Bộ là dãy nào?',
      opts: o4('Hoàng Liên Sơn', 'Trường Sơn', 'Bạch Mã', 'Tam Đảo'), ans: 'A',
      why: 'Dãy Hoàng Liên Sơn là dãy núi cao, đồ sộ nhất nước ta, có đỉnh Phan-xi-păng.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Người dân vùng núi thường trồng lúa trên loại ruộng nào ở sườn đồi, núi?',
      opts: o4('Ruộng bậc thang', 'Ruộng dưới đáy biển', 'Ruộng trên mái nhà', 'Ruộng trong hang'), ans: 'A',
      why: 'Để trồng lúa ở sườn dốc, người dân làm ruộng bậc thang men theo sườn đồi, núi.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Vùng núi Bắc Bộ là nơi sinh sống của nhiều dân tộc nào?',
      opts: o4('Thái, Mông, Dao, Tày, Nùng...', 'Chỉ có người Kinh', 'Chỉ có người nước ngoài', 'Không có ai sinh sống'), ans: 'A',
      why: 'Vùng này là nơi cư trú của nhiều dân tộc thiểu số như Thái, Mông, Dao, Tày, Nùng...' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Vùng núi Bắc Bộ giàu loại tài nguyên nào?',
      opts: o4('Khoáng sản (than, sắt, a-pa-tit...) và rừng', 'Dầu mỏ ngoài khơi', 'Cát trắng ven biển', 'Muối biển'), ans: 'A',
      why: 'Vùng này giàu khoáng sản (than, sắt, a-pa-tit, thiếc...) và có nhiều rừng.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Sa Pa (Lào Cai) nổi tiếng là nơi có khí hậu như thế nào?',
      opts: o4('Mát mẻ quanh năm, mùa đông có thể có sương muối', 'Nóng như sa mạc', 'Luôn ngập nước', 'Không bao giờ có mây'), ans: 'A',
      why: 'Sa Pa ở vùng núi cao nên khí hậu mát mẻ, mùa đông rất lạnh, đôi khi có sương muối, băng giá.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Chợ phiên vùng cao là nơi để làm gì?',
      opts: o4('Trao đổi, mua bán hàng hoá và giao lưu văn hoá', 'Chỉ để đi dạo', 'Để cày ruộng', 'Không có tác dụng'), ans: 'A',
      why: 'Chợ phiên họp theo ngày nhất định, là nơi mua bán và giao lưu văn hoá của người vùng cao.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Vì sao phải bảo vệ rừng ở vùng núi?',
      opts: o4('Rừng giữ đất, giữ nước, chống lũ và sạt lở', 'Vì rừng vô ích', 'Vì rừng gây hại', 'Không cần bảo vệ'), ans: 'A',
      why: 'Rừng đầu nguồn giữ đất, giữ nước, hạn chế lũ lụt và sạt lở đất ở vùng núi.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Cây công nghiệp lâu năm nào được trồng nhiều ở vùng trung du Bắc Bộ?',
      opts: o4('Cây chè', 'Cây dừa', 'Cây thanh long', 'Cây cà phê'), ans: 'A',
      why: 'Vùng trung du Bắc Bộ (Thái Nguyên, Phú Thọ...) nổi tiếng trồng nhiều chè.' },
  ],
},

/* ═══════════ ĐỀ 3 — LỊCH SỬ GẮN VỚI BẮC BỘ: ĐỀN HÙNG, ĐIỆN BIÊN PHỦ ═══════════ */
{
  id: 5603, title: 'Đề 3 · Đền Hùng và Chiến thắng Điện Biên Phủ', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Đền Hùng (tỉnh Phú Thọ) là nơi thờ ai?',
      opts: o4('Các Vua Hùng — những người có công dựng nước', 'Vua nước ngoài', 'Ông Táo', 'Thần Biển'), ans: 'A',
      why: 'Đền Hùng thờ các Vua Hùng, những người đã có công dựng nên nước Văn Lang.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Giỗ Tổ Hùng Vương được tổ chức vào ngày nào (âm lịch)?',
      opts: o4('Mùng 10 tháng 3', 'Mùng 1 tháng 1', 'Rằm tháng 8', 'Mùng 5 tháng 5'), ans: 'A',
      why: 'Giỗ Tổ Hùng Vương là ngày mùng 10 tháng 3 âm lịch hằng năm.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Nhà nước đầu tiên của người Việt do các Vua Hùng lập ra có tên là gì?',
      opts: o4('Nước Văn Lang', 'Nước Đại Việt', 'Nước Nam Việt', 'Nước Việt Nam'), ans: 'A',
      why: 'Các Vua Hùng lập ra nước Văn Lang — nhà nước đầu tiên trong lịch sử nước ta.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Câu ca dao "Dù ai đi ngược về xuôi / Nhớ ngày Giỗ Tổ mùng mười tháng ba" nhắc nhở điều gì?',
      opts: o4('Nhớ ơn tổ tiên, cội nguồn dân tộc', 'Nhớ đi chợ', 'Nhớ mang áo mưa', 'Nhớ nấu cơm'), ans: 'A',
      why: 'Câu ca dao nhắc con cháu luôn nhớ ơn tổ tiên và cội nguồn dân tộc.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ diễn ra vào năm nào?',
      opts: o4('Năm 1954', 'Năm 1945', 'Năm 1975', 'Năm 1930'), ans: 'A',
      why: 'Chiến thắng Điện Biên Phủ diễn ra ngày 7 tháng 5 năm 1954.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ là chiến thắng chống lại quân xâm lược nào?',
      opts: o4('Thực dân Pháp', 'Quân Nguyên - Mông', 'Quân Thanh', 'Quân Minh'), ans: 'A',
      why: 'Điện Biên Phủ là chiến thắng vang dội của quân dân ta chống thực dân Pháp.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Vị Đại tướng chỉ huy Chiến dịch Điện Biên Phủ là ai?',
      opts: o4('Võ Nguyên Giáp', 'Trần Hưng Đạo', 'Quang Trung', 'Lê Lợi'), ans: 'A',
      why: 'Đại tướng Võ Nguyên Giáp là Tổng chỉ huy Chiến dịch Điện Biên Phủ.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Điện Biên Phủ nằm ở vùng nào của nước ta?',
      opts: o4('Miền núi Tây Bắc (Bắc Bộ)', 'Đồng bằng Nam Bộ', 'Tây Nguyên', 'Duyên hải miền Trung'), ans: 'A',
      why: 'Điện Biên Phủ thuộc tỉnh Điện Biên, ở vùng núi Tây Bắc của Bắc Bộ.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ có ý nghĩa gì?',
      opts: o4('Kết thúc thắng lợi cuộc kháng chiến chống Pháp', 'Mở đầu chiến tranh', 'Không có ý nghĩa', 'Chỉ là một trận nhỏ'), ans: 'A',
      why: 'Chiến thắng Điện Biên Phủ buộc Pháp kí Hiệp định Giơ-ne-vơ, kết thúc kháng chiến chống Pháp.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Kinh đô nước Âu Lạc thời An Dương Vương, nay ở gần Hà Nội, có tên là gì?',
      opts: o4('Cổ Loa', 'Hoa Lư', 'Phú Xuân', 'Thăng Long'), ans: 'A',
      why: 'An Dương Vương lập nước Âu Lạc, đóng đô ở Cổ Loa (nay thuộc Đông Anh, Hà Nội).' },
  ],
},

/* ═══════════ ĐỀ 4 — ĐỒNG BẰNG BẮC BỘ: THIÊN NHIÊN VÀ SẢN XUẤT ═══════════ */
{
  id: 5604, title: 'Đề 4 · Đồng bằng Bắc Bộ', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng Bắc Bộ do những con sông nào bồi đắp nên?',
      opts: o4('Sông Hồng và sông Thái Bình', 'Sông Cửu Long', 'Sông Đồng Nai', 'Sông Hương'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ được sông Hồng và sông Thái Bình bồi đắp phù sa.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đất ở đồng bằng Bắc Bộ có đặc điểm gì?',
      opts: o4('Đất phù sa màu mỡ', 'Đất cát khô cằn', 'Đất đỏ ba-dan', 'Toàn đá sỏi'), ans: 'A',
      why: 'Phù sa sông bồi đắp tạo nên đất màu mỡ, thuận lợi trồng trọt.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Cây lương thực được trồng nhiều nhất ở đồng bằng Bắc Bộ là gì?',
      opts: o4('Cây lúa', 'Cây cà phê', 'Cây cao su', 'Cây thông'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ là vựa lúa lớn thứ hai của cả nước.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Người dân đồng bằng Bắc Bộ đắp đê ven sông để làm gì?',
      opts: o4('Ngăn lũ lụt, bảo vệ mùa màng và làng xóm', 'Để leo trèo', 'Để làm đường tàu', 'Để trang trí'), ans: 'A',
      why: 'Hệ thống đê điều giúp ngăn nước sông dâng cao gây lũ, bảo vệ đồng ruộng, làng mạc.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Mùa nào ở đồng bằng Bắc Bộ thường lạnh, có gió mùa đông bắc?',
      opts: o4('Mùa đông', 'Mùa hạ', 'Mùa mưa quanh năm', 'Không có mùa lạnh'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ có mùa đông lạnh do ảnh hưởng của gió mùa đông bắc.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Ngoài trồng lúa, người dân đồng bằng Bắc Bộ còn phát triển nghề gì?',
      opts: o4('Trồng rau, nuôi lợn gà, làng nghề thủ công', 'Khai thác dầu mỏ', 'Trồng cà phê', 'Nuôi tuần lộc'), ans: 'A',
      why: 'Vùng này còn trồng rau màu, chăn nuôi và có nhiều làng nghề thủ công truyền thống.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Làng nghề gốm Bát Tràng nổi tiếng nằm ở đâu?',
      opts: o4('Hà Nội (đồng bằng Bắc Bộ)', 'Đà Lạt', 'Cần Thơ', 'Buôn Ma Thuột'), ans: 'A',
      why: 'Bát Tràng (Hà Nội) là làng nghề làm gốm sứ nổi tiếng ở đồng bằng Bắc Bộ.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Đồng bằng Bắc Bộ là vùng có mật độ dân số như thế nào?',
      opts: o4('Đông dân, mật độ cao', 'Rất ít người', 'Không có người ở', 'Chỉ có khách du lịch'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ là một trong những vùng đông dân nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Lễ hội truyền thống ở đồng bằng Bắc Bộ thường được tổ chức vào mùa nào?',
      opts: o4('Mùa xuân (sau Tết)', 'Giữa mùa hè nóng nhất', 'Không bao giờ tổ chức', 'Chỉ vào ban đêm mùa đông'), ans: 'A',
      why: 'Nhiều lễ hội (hội Lim, hội Gióng, chùa Hương...) được tổ chức vào mùa xuân.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Sông Hồng có màu nước đặc trưng là gì, do đâu?',
      opts: o4('Màu đỏ nâu do chứa nhiều phù sa', 'Màu xanh trong veo', 'Màu đen', 'Màu trắng như sữa'), ans: 'A',
      why: 'Sông Hồng mang nhiều phù sa nên nước thường có màu đỏ nâu — vì thế gọi là sông Hồng.' },
  ],
},

/* ═══════════ ĐỀ 5 — THĂNG LONG – HÀ NỘI VÀ VĂN MIẾU ═══════════ */
{
  id: 5605, title: 'Đề 5 · Thăng Long – Hà Nội', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Tên gọi xưa của Thủ đô Hà Nội là gì?',
      opts: o4('Thăng Long', 'Gia Định', 'Phú Xuân', 'Hoa Lư'), ans: 'A',
      why: 'Hà Nội xưa có tên là Thăng Long, nghĩa là "rồng bay lên".' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Vị vua nào đã dời đô ra Thăng Long vào năm 1010?',
      opts: o4('Lý Thái Tổ (Lý Công Uẩn)', 'Quang Trung', 'Lê Lợi', 'Trần Hưng Đạo'), ans: 'A',
      why: 'Năm 1010, vua Lý Thái Tổ (Lý Công Uẩn) dời đô từ Hoa Lư ra Thăng Long.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Văn Miếu – Quốc Tử Giám ở Hà Nội được xem là gì?',
      opts: o4('Trường đại học đầu tiên của nước ta', 'Một khu chợ', 'Một bến cảng', 'Một nhà máy'), ans: 'A',
      why: 'Quốc Tử Giám được coi là trường đại học đầu tiên của Việt Nam, nơi đào tạo nhân tài.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Trong Văn Miếu có các tấm bia đá đặt trên lưng con vật nào để khắc tên người đỗ đạt?',
      opts: o4('Con rùa', 'Con rồng', 'Con voi', 'Con ngựa'), ans: 'A',
      why: 'Bia tiến sĩ ở Văn Miếu được đặt trên lưng rùa đá, ghi tên những người thi đỗ.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Hà Nội ngày nay là trung tâm gì của cả nước?',
      opts: o4('Trung tâm chính trị, văn hoá, khoa học', 'Chỉ là một làng nhỏ', 'Một hòn đảo', 'Một khu rừng'), ans: 'A',
      why: 'Hà Nội là thủ đô — trung tâm chính trị, văn hoá, khoa học, giáo dục của cả nước.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Hồ nước nổi tiếng ở trung tâm Hà Nội, gắn với truyền thuyết trả gươm là hồ nào?',
      opts: o4('Hồ Hoàn Kiếm (Hồ Gươm)', 'Hồ Ba Bể', 'Hồ Tây (trả gươm)', 'Biển Hồ'), ans: 'A',
      why: 'Hồ Hoàn Kiếm (Hồ Gươm) gắn với truyền thuyết vua Lê trả gươm cho Rùa Thần.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Truyền thuyết Hồ Gươm gắn với vị anh hùng nào chống quân Minh?',
      opts: o4('Lê Lợi', 'Ngô Quyền', 'Đinh Bộ Lĩnh', 'Lý Thường Kiệt'), ans: 'A',
      why: 'Truyền thuyết kể Lê Lợi được Rùa Thần cho mượn gươm để đánh đuổi giặc Minh.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Khu vực "Ba mươi sáu phố phường" ở Hà Nội xưa là nơi làm gì?',
      opts: o4('Buôn bán, làm nghề thủ công', 'Trồng lúa', 'Đánh cá biển', 'Khai thác than'), ans: 'A',
      why: 'Khu phố cổ "36 phố phường" là nơi tập trung buôn bán và làm nghề thủ công của Thăng Long xưa.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Vì sao vua Lý Thái Tổ chọn Thăng Long làm kinh đô?',
      opts: o4('Vì đây là vùng đất trung tâm, bằng phẳng, thuận lợi phát triển', 'Vì gần biển', 'Vì trên núi cao', 'Vì xa dân cư'), ans: 'A',
      why: 'Thăng Long ở vị trí trung tâm, đất bằng phẳng, thuận lợi cho việc mở mang, phát triển đất nước.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Năm 2010, Hà Nội (Thăng Long) kỉ niệm tròn bao nhiêu năm tuổi?',
      opts: o4('1000 năm', '100 năm', '500 năm', '2000 năm'), ans: 'A',
      why: 'Năm 2010 là dịp Đại lễ 1000 năm Thăng Long – Hà Nội (tính từ năm 1010).' },
  ],
},

/* ═══════════ ĐỀ 6 — DUYÊN HẢI MIỀN TRUNG: THIÊN NHIÊN ═══════════ */
{
  id: 5606, title: 'Đề 6 · Duyên hải miền Trung', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng ở duyên hải miền Trung có đặc điểm gì?',
      opts: o4('Nhỏ hẹp, nằm sát biển', 'Rất rộng lớn, phẳng', 'Nằm sâu trong núi', 'Toàn cao nguyên'), ans: 'A',
      why: 'Do núi ăn ra sát biển nên các đồng bằng ven biển miền Trung nhỏ hẹp.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Miền Trung có nhiều bãi biển đẹp, thuận lợi phát triển ngành gì?',
      opts: o4('Du lịch biển', 'Trồng cà phê', 'Khai thác than', 'Chăn nuôi tuần lộc'), ans: 'A',
      why: 'Bãi biển đẹp (Nha Trang, Đà Nẵng, Lăng Cô...) giúp miền Trung phát triển du lịch biển.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Dãy núi lớn chạy dọc phía tây miền Trung là dãy nào?',
      opts: o4('Dãy Trường Sơn', 'Dãy Hoàng Liên Sơn', 'Dãy Tam Đảo', 'Dãy Con Voi'), ans: 'A',
      why: 'Dãy Trường Sơn chạy dài ở phía tây, ngăn cách miền Trung với Lào và Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Miền Trung thường phải hứng chịu thiên tai nào vào mùa mưa bão?',
      opts: o4('Bão và lũ lụt', 'Tuyết rơi dày', 'Động đất lớn hằng ngày', 'Núi lửa phun'), ans: 'A',
      why: 'Miền Trung là vùng thường xuyên chịu bão và lũ lụt, gây nhiều thiệt hại.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Nghề nào là thế mạnh của người dân ven biển miền Trung?',
      opts: o4('Đánh bắt, nuôi trồng hải sản và làm muối', 'Trồng lúa nước quy mô lớn', 'Khai thác vàng', 'Trồng chè'), ans: 'A',
      why: 'Ven biển miền Trung phát triển đánh bắt, nuôi hải sản và nghề làm muối.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Vì sao nghề làm muối phát triển ở ven biển miền Trung?',
      opts: o4('Vì có nắng nhiều và nước biển mặn', 'Vì trời hay mưa', 'Vì đất đỏ ba-dan', 'Vì có tuyết'), ans: 'A',
      why: 'Nắng nhiều giúp nước biển bốc hơi nhanh, để lại muối — thuận lợi cho nghề làm muối.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Để giảm thiệt hại do bão lũ, người dân miền Trung nên làm gì?',
      opts: o4('Theo dõi dự báo, chằng chống nhà cửa, sơ tán khi cần', 'Ra biển khi có bão', 'Không chuẩn bị gì', 'Chặt hết cây chắn gió'), ans: 'A',
      why: 'Theo dõi dự báo, gia cố nhà cửa và sơ tán kịp thời giúp giảm thiệt hại do bão lũ.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Thành phố biển lớn ở miền Trung, có cầu Rồng nổi tiếng là thành phố nào?',
      opts: o4('Đà Nẵng', 'Hải Phòng', 'Cần Thơ', 'Vũng Tàu'), ans: 'A',
      why: 'Đà Nẵng là thành phố biển lớn ở miền Trung, nổi tiếng với cầu Rồng, bãi biển Mĩ Khê.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Rừng ở dãy Trường Sơn có vai trò gì với miền Trung?',
      opts: o4('Giữ nước, hạn chế lũ quét và sạt lở', 'Gây ra bão', 'Làm biển dâng', 'Không có vai trò'), ans: 'A',
      why: 'Rừng Trường Sơn giữ nước đầu nguồn, hạn chế lũ quét và sạt lở cho vùng đồng bằng ven biển.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Khí hậu miền Trung vào mùa hè thường như thế nào?',
      opts: o4('Nắng nóng, có gió Lào khô nóng', 'Lạnh và có tuyết', 'Mát mẻ quanh năm', 'Mưa suốt ngày'), ans: 'A',
      why: 'Mùa hè miền Trung nắng nóng, chịu ảnh hưởng của gió phơn Tây Nam (gió Lào) khô nóng.' },
  ],
},

/* ═══════════ ĐỀ 7 — CỐ ĐÔ HUẾ VÀ PHỐ CỔ HỘI AN ═══════════ */
{
  id: 5607, title: 'Đề 7 · Cố đô Huế và phố cổ Hội An', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Cố đô Huế từng là kinh đô của triều đại phong kiến nào cuối cùng ở nước ta?',
      opts: o4('Triều Nguyễn', 'Triều Lý', 'Triều Trần', 'Triều Lê'), ans: 'A',
      why: 'Huế (Phú Xuân) là kinh đô của triều Nguyễn — triều đại phong kiến cuối cùng của Việt Nam.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá thế giới', 'Kì quan thiên nhiên', 'Khu bảo tồn biển', 'Công viên giải trí'), ans: 'A',
      why: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là Di sản văn hoá thế giới (năm 1993).' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Con sông thơ mộng chảy qua thành phố Huế tên là gì?',
      opts: o4('Sông Hương', 'Sông Hồng', 'Sông Sài Gòn', 'Sông Đà'), ans: 'A',
      why: 'Sông Hương chảy qua Huế, cùng núi Ngự Bình tạo nên cảnh đẹp nổi tiếng của xứ Huế.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Khu vực các vua Nguyễn ở và làm việc trong Cố đô Huế gọi là gì?',
      opts: o4('Kinh thành (Hoàng thành, Đại Nội)', 'Bến cảng', 'Chợ nổi', 'Nhà máy'), ans: 'A',
      why: 'Kinh thành Huế với Hoàng thành (Đại Nội) là nơi ở và làm việc của các vua Nguyễn.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Phố cổ Hội An thuộc tỉnh nào?',
      opts: o4('Quảng Nam', 'Thừa Thiên Huế', 'Bình Định', 'Khánh Hoà'), ans: 'A',
      why: 'Phố cổ Hội An nằm ở tỉnh Quảng Nam, bên sông Thu Bồn.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Ngày xưa, Hội An nổi tiếng là gì?',
      opts: o4('Một thương cảng sầm uất, buôn bán với nước ngoài', 'Một pháo đài quân sự', 'Một khu rừng nguyên sinh', 'Một mỏ than'), ans: 'A',
      why: 'Hội An từng là thương cảng quốc tế sầm uất, buôn bán với thương nhân nhiều nước.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Công trình nổi tiếng ở Hội An, biểu tượng của phố cổ là gì?',
      opts: o4('Chùa Cầu (cầu Nhật Bản)', 'Tháp Rùa', 'Chợ Bến Thành', 'Nhà thờ Đức Bà'), ans: 'A',
      why: 'Chùa Cầu (cầu Nhật Bản) là công trình cổ, biểu tượng của phố cổ Hội An.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Phố cổ Hội An được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá thế giới', 'Kì quan thiên nhiên mới', 'Khu dự trữ sinh quyển', 'Vườn quốc gia'), ans: 'A',
      why: 'Phố cổ Hội An được UNESCO công nhận là Di sản văn hoá thế giới (năm 1999).' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Khi tham quan Cố đô Huế, Hội An, du khách cần có ý thức gì?',
      opts: o4('Giữ gìn, không phá hoại di tích, không xả rác', 'Khắc tên lên tường cổ', 'Sờ, trèo lên hiện vật', 'Vứt rác bừa bãi'), ans: 'A',
      why: 'Cần giữ gìn, bảo vệ di tích, không viết vẽ, xả rác hay phá hoại cảnh quan.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Vì sao cần bảo tồn Cố đô Huế và phố cổ Hội An?',
      opts: o4('Vì là di sản quý, thể hiện lịch sử – văn hoá dân tộc', 'Vì để bán lấy tiền', 'Vì đã cũ nên phá đi', 'Vì không ai quan tâm'), ans: 'A',
      why: 'Đây là những di sản quý giá phản ánh lịch sử, văn hoá dân tộc, cần được bảo tồn cho đời sau.' },
  ],
},

/* ═══════════ ĐỀ 8 — TÂY NGUYÊN ═══════════ */
{
  id: 5608, title: 'Đề 8 · Tây Nguyên', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Tây Nguyên có địa hình chủ yếu là gì?',
      opts: o4('Các cao nguyên xếp tầng', 'Đồng bằng ven biển', 'Vùng đất ngập nước', 'Đảo và quần đảo'), ans: 'A',
      why: 'Tây Nguyên gồm các cao nguyên rộng lớn, xếp tầng, có độ cao khác nhau.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đất ở Tây Nguyên chủ yếu là loại đất nào, thích hợp trồng cây công nghiệp?',
      opts: o4('Đất đỏ ba-dan', 'Đất phù sa', 'Đất cát', 'Đất sét trắng'), ans: 'A',
      why: 'Tây Nguyên có nhiều đất đỏ ba-dan màu mỡ, thích hợp trồng cây công nghiệp lâu năm.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Cây công nghiệp nào được trồng nhiều nhất và nổi tiếng ở Tây Nguyên?',
      opts: o4('Cây cà phê', 'Cây lúa nước', 'Cây chè', 'Cây táo'), ans: 'A',
      why: 'Tây Nguyên là vùng trồng cà phê lớn nhất cả nước; ngoài ra còn có cao su, hồ tiêu.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Tây Nguyên có khí hậu chia thành mấy mùa rõ rệt?',
      opts: o4('Hai mùa: mùa mưa và mùa khô', 'Bốn mùa như miền Bắc', 'Không có mùa nào', 'Chỉ có mùa đông'), ans: 'A',
      why: 'Tây Nguyên có hai mùa rõ rệt: mùa mưa và mùa khô.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Tây Nguyên là nơi sinh sống của nhiều dân tộc nào?',
      opts: o4('Gia-rai, Ê-đê, Ba-na, Xơ-đăng...', 'Chỉ có người nước ngoài', 'Không có ai', 'Chỉ có một dân tộc'), ans: 'A',
      why: 'Tây Nguyên là địa bàn cư trú lâu đời của nhiều dân tộc như Gia-rai, Ê-đê, Ba-na, Xơ-đăng...' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Ngôi nhà chung để sinh hoạt cộng đồng của một số dân tộc Tây Nguyên gọi là gì?',
      opts: o4('Nhà rông', 'Nhà sàn thấp', 'Nhà ống', 'Nhà chung cư'), ans: 'A',
      why: 'Nhà rông là ngôi nhà chung cao lớn, nơi sinh hoạt cộng đồng của buôn làng Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Loại nhạc cụ đặc trưng trong lễ hội của các dân tộc Tây Nguyên là gì?',
      opts: o4('Cồng, chiêng', 'Đàn bầu', 'Sáo trúc miền Bắc', 'Đàn ghi-ta điện'), ans: 'A',
      why: 'Cồng chiêng là nhạc cụ gắn với lễ hội và đời sống tinh thần của người Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: '"Không gian văn hoá Cồng chiêng Tây Nguyên" được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá phi vật thể của nhân loại', 'Kì quan thiên nhiên', 'Khu công nghiệp', 'Vườn thú'), ans: 'A',
      why: 'Không gian văn hoá Cồng chiêng Tây Nguyên được UNESCO công nhận là Di sản văn hoá phi vật thể.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Thành phố nào ở Tây Nguyên (Lâm Đồng) nổi tiếng khí hậu mát mẻ, nhiều hoa?',
      opts: o4('Đà Lạt', 'Nha Trang', 'Vũng Tàu', 'Hạ Long'), ans: 'A',
      why: 'Đà Lạt (Lâm Đồng) ở cao nguyên, khí hậu mát mẻ quanh năm, nổi tiếng là thành phố ngàn hoa.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Sông ở Tây Nguyên có nhiều thác ghềnh, thuận lợi để làm gì?',
      opts: o4('Xây dựng nhà máy thuỷ điện', 'Làm ruộng muối', 'Nuôi cá voi', 'Trồng lúa nước'), ans: 'A',
      why: 'Sông nhiều thác ghềnh, nước chảy mạnh nên Tây Nguyên có tiềm năng phát triển thuỷ điện.' },
  ],
},

/* ═══════════ ĐỀ 9 — NAM BỘ ═══════════ */
{
  id: 5609, title: 'Đề 9 · Nam Bộ và đồng bằng sông Cửu Long', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng lớn nhất nước ta nằm ở vùng nào?',
      opts: o4('Nam Bộ (đồng bằng sông Cửu Long)', 'Bắc Bộ', 'Tây Nguyên', 'Duyên hải miền Trung'), ans: 'A',
      why: 'Đồng bằng Nam Bộ, trong đó có đồng bằng sông Cửu Long, là đồng bằng lớn nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đồng bằng sông Cửu Long do con sông lớn nào bồi đắp?',
      opts: o4('Sông Cửu Long (sông Mê Kông)', 'Sông Hồng', 'Sông Hương', 'Sông Đà'), ans: 'A',
      why: 'Sông Mê Kông chảy vào nước ta gọi là sông Cửu Long, bồi đắp nên đồng bằng này.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Vì sao gọi là sông "Cửu Long" (chín rồng)?',
      opts: o4('Vì sông đổ ra biển bằng chín cửa sông', 'Vì có chín con rồng thật', 'Vì dài chín ki-lô-mét', 'Vì có chín chiếc cầu'), ans: 'A',
      why: '"Cửu Long" nghĩa là chín rồng — do sông đổ ra biển qua chín cửa (nay một số cửa đã thay đổi).' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Đồng bằng sông Cửu Long là vựa lớn nhất cả nước về sản phẩm nào?',
      opts: o4('Lúa gạo, trái cây và thuỷ sản', 'Than đá', 'Cà phê', 'Chè'), ans: 'A',
      why: 'Đồng bằng sông Cửu Long là vựa lúa, vựa trái cây và thuỷ sản lớn nhất nước ta.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Nét sinh hoạt đặc trưng trên sông nước ở Nam Bộ là gì?',
      opts: o4('Chợ nổi (mua bán trên thuyền, ghe)', 'Chợ phiên trên núi', 'Ruộng bậc thang', 'Săn bắn trong rừng'), ans: 'A',
      why: 'Chợ nổi (Cái Răng, Cái Bè...) — mua bán trên ghe thuyền — là nét đặc trưng của Nam Bộ.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Vùng Nam Bộ có khí hậu như thế nào?',
      opts: o4('Nóng quanh năm, có hai mùa mưa – khô', 'Bốn mùa rõ rệt', 'Rất lạnh, có tuyết', 'Mát mẻ như Đà Lạt'), ans: 'A',
      why: 'Nam Bộ nóng quanh năm, chia thành hai mùa: mùa mưa và mùa khô.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Thành phố lớn nhất, đông dân nhất nước ta là thành phố nào?',
      opts: o4('Thành phố Hồ Chí Minh', 'Hà Nội', 'Cần Thơ', 'Đà Nẵng'), ans: 'A',
      why: 'Thành phố Hồ Chí Minh là thành phố lớn nhất và đông dân nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Thành phố Hồ Chí Minh trước đây có tên gọi là gì?',
      opts: o4('Sài Gòn', 'Gia Định thành cổ xưa nhất', 'Thăng Long', 'Phú Xuân'), ans: 'A',
      why: 'Thành phố Hồ Chí Minh trước đây được gọi là Sài Gòn.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Địa đạo Củ Chi (gần TP. Hồ Chí Minh) là di tích gắn với điều gì?',
      opts: o4('Cuộc kháng chiến chống Mĩ của quân dân ta', 'Một khu chợ cổ', 'Một mỏ vàng', 'Một sân vận động'), ans: 'A',
      why: 'Địa đạo Củ Chi là hệ thống đường hầm, di tích của cuộc kháng chiến chống Mĩ.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Đồng bằng sông Cửu Long đang chịu ảnh hưởng nào cần được ứng phó?',
      opts: o4('Ngập lụt, xâm nhập mặn, sạt lở bờ sông', 'Tuyết rơi dày', 'Động đất mỗi ngày', 'Núi lửa'), ans: 'A',
      why: 'Vùng này chịu ngập lụt mùa nước nổi, xâm nhập mặn mùa khô và sạt lở bờ sông.' },
  ],
},

/* ═══════════ ĐỀ 10 — ÔN TẬP TỔNG HỢP CÁC VÙNG MIỀN ═══════════ */
{
  id: 5610, title: 'Đề 10 · Ôn tập các vùng miền', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Đỉnh núi cao nhất Việt Nam là:',
      opts: o4('Phan-xi-păng', 'Bà Đen', 'Ngự Bình', 'Fansipan giả'), ans: 'A',
      why: 'Phan-xi-păng (Hoàng Liên Sơn) cao khoảng 3143 m, cao nhất nước ta.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Đồng bằng Bắc Bộ do sông nào bồi đắp?',
      opts: o4('Sông Hồng và sông Thái Bình', 'Sông Cửu Long', 'Sông Hương', 'Sông Sài Gòn'), ans: 'A',
      why: 'Sông Hồng và sông Thái Bình bồi đắp nên đồng bằng Bắc Bộ.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Cố đô Huế là kinh đô của triều đại nào?',
      opts: o4('Triều Nguyễn', 'Triều Lý', 'Triều Trần', 'Triều Tây Sơn'), ans: 'A',
      why: 'Huế là kinh đô của triều Nguyễn — triều đại phong kiến cuối cùng của nước ta.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Vùng nào nổi tiếng trồng cà phê và có văn hoá cồng chiêng?',
      opts: o4('Tây Nguyên', 'Đồng bằng Bắc Bộ', 'Duyên hải miền Trung', 'Đồng bằng sông Cửu Long'), ans: 'A',
      why: 'Tây Nguyên trồng nhiều cà phê và có Không gian văn hoá Cồng chiêng nổi tiếng.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Đồng bằng lớn nhất nước ta là:',
      opts: o4('Đồng bằng sông Cửu Long (Nam Bộ)', 'Đồng bằng Bắc Bộ', 'Đồng bằng Thanh - Nghệ', 'Không có đồng bằng nào'), ans: 'A',
      why: 'Đồng bằng sông Cửu Long ở Nam Bộ là đồng bằng lớn nhất cả nước.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ (1954) là chiến thắng chống quân xâm lược nào?',
      opts: o4('Thực dân Pháp', 'Đế quốc Mĩ', 'Quân Thanh', 'Quân Nguyên'), ans: 'A',
      why: 'Điện Biên Phủ 1954 là chiến thắng kết thúc kháng chiến chống thực dân Pháp.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Thủ đô Hà Nội xưa có tên là:',
      opts: o4('Thăng Long', 'Sài Gòn', 'Phú Xuân', 'Hoa Lư'), ans: 'A',
      why: 'Hà Nội xưa tên là Thăng Long, do vua Lý Thái Tổ đặt khi dời đô năm 1010.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Vùng nào của nước ta thường xuyên chịu nhiều bão, lũ nhất?',
      opts: o4('Duyên hải miền Trung', 'Tây Nguyên', 'Đồng bằng Bắc Bộ', 'Trung du Bắc Bộ'), ans: 'A',
      why: 'Duyên hải miền Trung là vùng hứng chịu nhiều bão và lũ lụt.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Phố cổ Hội An và Cố đô Huế đều được UNESCO công nhận là:',
      opts: o4('Di sản văn hoá thế giới', 'Kì quan thiên nhiên', 'Khu công nghiệp', 'Sân bay quốc tế'), ans: 'A',
      why: 'Cả Cố đô Huế và phố cổ Hội An đều là Di sản văn hoá thế giới.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp giữ gìn và phát huy giá trị các vùng miền của đất nước?',
      opts: o4('Bảo vệ di tích, môi trường và tự hào giới thiệu quê hương', 'Phá hoại di tích', 'Xả rác nơi danh thắng', 'Chê bai quê hương'), ans: 'A',
      why: 'Bảo vệ di tích, giữ sạch môi trường và tự hào giới thiệu quê hương giúp phát huy giá trị các vùng miền.' },
  ],
},

];

SUBJECTS.push({
  id: 'lsdl4', name: 'Lịch sử & Địa lí', short: 'LS-ĐL 4', icon: '🗺️', grade: 4,
  exams: LSDL4_EXAMS, ready: true,
  heroTitle: 'Lịch sử và Địa lí lớp 4 — địa phương em và các vùng miền: Bắc Bộ, miền Trung, Tây Nguyên, Nam Bộ',
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
