// TIẾNG VIỆT LỚP 2 — ĐỌC HIỂU · LUYỆN TỪ VÀ CÂU · NỀN TẬP LÀM VĂN
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// VÌ SAO CÓ BỘ NÀY: ngân hàng Tiếng Việt cũ (VioEdu) hỏi đọc hiểu chủ yếu ở mức "nhặt
// chi tiết có sẵn trong câu". Bộ này bổ sung ba mảng còn thiếu, vốn là nền của đề thi
// chuyển cấp về sau:
//   1. Đọc hiểu bậc cao: ý chính, bài học rút ra, nghĩa của từ trong ngữ cảnh, suy luận
//      điều bài đọc không nói thẳng ra.
//   2. Luyện từ và câu gom theo chuyên đề (từ loại · mẫu câu · bộ phận câu · dấu câu ·
//      từ trái nghĩa · mở rộng vốn từ · chính tả phân biệt).
//   3. Nền tập làm văn: sắp xếp câu thành đoạn, chọn câu mở đoạn – kết đoạn, chọn từ
//      gợi tả, nhận ra câu lạc ý.
//
// KHÁC BIỆT KĨ THUẬT: bài đọc để trong trường `read` và LẶP LẠI trên MỌI câu của nhóm
// đọc hiểu, nên bé luôn nhìn thấy bài đọc khi trả lời (app hiện mỗi lần một câu).
//
// MỨC ĐỘ: bám chương trình Tiếng Việt 2 (GDPT 2018) — từ chỉ sự vật / hoạt động / đặc điểm,
// ba mẫu câu Ai là gì? · Ai làm gì? · Ai thế nào?, dấu chấm · chấm hỏi · chấm than · phẩy.
// Dấu hai chấm, dấu ngoặc kép, biện pháp so sánh – nhân hoá để dành cho bộ lớp 3.

/* ── Bài đọc dùng chung cho nhiều câu trong cùng một đề ────────────────────── */
const TV2_R1 = '<b>Kiến con và giọt sương</b><br>Sáng sớm, Kiến con bò ra khỏi tổ đi tìm thức ăn. Trời nắng gắt, Kiến khát khô cả cổ. Đi mãi, Kiến mới thấy một giọt sương còn đọng trên lá cỏ. Kiến mừng quá, ghé miệng uống một hớp nhỏ rồi dừng lại. Kiến nghĩ: “Mình để dành phần cho bạn Sên đi sau.” Đến trưa, Sên bò tới, uống giọt sương mát lạnh và biết ơn Kiến con vô cùng.';

const TV2_R2 = '<b>Cây bàng trước lớp</b><br>Trước cửa lớp em có một cây bàng già. Mùa xuân, bàng bật ra những búp lá non xanh mượt. Mùa hè, tán bàng xoè rộng như một chiếc ô lớn, che nắng cho chúng em chơi. Mùa thu, lá bàng chuyển dần sang màu đỏ tía. Mùa đông, cây trút hết lá, chỉ còn những cành khẳng khiu vươn lên trời.';

const TV2_R3 = '<b>Mẹ</b> <i>(trích — Trần Quốc Minh)</i><br>Lặng rồi cả tiếng con ve<br>Con ve cũng mệt vì hè nắng oi.<br>Nhà em vẫn tiếng ạ ời<br>Kẽo cà tiếng võng mẹ ngồi mẹ ru.<br>Lời ru có gió mùa thu<br>Bàn tay mẹ quạt mẹ đưa gió về.';

const TV2_R4 = '<b>Bạn mới</b><br>Hôm nay lớp 2A có bạn mới. Bạn tên là Hà, vừa chuyển từ quê ra. Hà đứng nép bên cửa lớp, mặt đỏ bừng vì ngượng. Cô giáo dắt Hà tới ngồi cạnh Mai. Giờ ra chơi, Mai rủ Hà ra sân nhảy dây. Chỉ một lát sau, cả nhóm đã cười vang. Hà thấy lớp mới thật gần gũi.';

const TV2_EXAMS = [

/* ═══════════ ĐỀ 1 — ĐỌC HIỂU TRUYỆN: CHI TIẾT, Ý CHÍNH, BÀI HỌC ═══════════ */
{
  id: 1701, title: 'Đề 1 · Đọc hiểu truyện — chi tiết và bài học', time: 20,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV2_R1,
      text: 'Kiến con bò ra khỏi tổ để làm gì?',
      opts: o4('Để đi chơi với bạn Sên', 'Để đi tìm thức ăn', 'Để hái lá cỏ về làm tổ', 'Để tắm giọt sương'), ans: 'B',
      why: 'Câu đầu bài đọc: “Sáng sớm, Kiến con bò ra khỏi tổ đi tìm thức ăn.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 2', pts: 1, read: TV2_R1,
      text: 'Kiến con tìm thấy nước uống ở đâu?',
      opts: o4('Ngay trong tổ của mình', 'Trong một cái ao nhỏ', 'Ở vũng nước bên đường', 'Một giọt sương đọng trên lá cỏ'), ans: 'D',
      why: 'Bài đọc viết: “Kiến mới thấy một giọt sương còn đọng trên lá cỏ.”.' },
    { sec: 'Suy luận', name: 'Câu 3', pts: 1, read: TV2_R1,
      text: 'Vì sao Kiến con chỉ uống <b>một hớp nhỏ</b> rồi dừng lại?',
      opts: o4('Vì Kiến muốn để dành phần cho bạn Sên', 'Vì giọt sương quá lạnh', 'Vì Kiến đã hết khát', 'Vì Kiến sợ bị ướt cánh'), ans: 'A',
      why: 'Kiến đang khát khô cả cổ mà vẫn dừng lại, bởi Kiến nghĩ: “Mình để dành phần cho bạn Sên đi sau.”.' },
    { sec: 'Bài học', name: 'Câu 4', pts: 1, read: TV2_R1,
      text: 'Câu chuyện muốn khuyên em điều gì?',
      opts: o4('Phải dậy thật sớm mới kiếm được ăn', 'Không nên uống nước ngoài đường', 'Đi đâu cũng phải mang theo nước', 'Biết nghĩ đến người khác, có gì cũng nhớ chia phần'), ans: 'D',
      why: 'Cả câu chuyện xoay quanh việc Kiến nhịn khát để dành nước cho bạn — đó là lòng biết nghĩ đến người khác.' },
    { sec: 'Nghĩa của từ', name: 'Câu 5', pts: 1, read: TV2_R1,
      text: 'Từ <b>“mừng quá”</b> cho thấy lúc ấy Kiến con cảm thấy thế nào?',
      opts: o4('Rất buồn', 'Rất sợ', 'Rất mệt', 'Rất vui'), ans: 'D',
      why: 'Đang khát mà tìm được nước nên Kiến “mừng quá”, nghĩa là rất vui.' },
    { sec: 'Từ loại', name: 'Câu 6', pts: 1,
      text: 'Trong câu “Kiến con bò ra khỏi tổ.”, từ nào là <b>từ chỉ hoạt động</b>?',
      opts: o4('con', 'Kiến con', 'tổ', 'bò'), ans: 'D',
      why: '“bò” chỉ việc Kiến đang làm nên là từ chỉ hoạt động; “Kiến con” và “tổ” đều chỉ sự vật.' },
    { sec: 'Mẫu câu', name: 'Câu 7', pts: 1,
      text: 'Câu “Giọt sương rất mát lạnh.” thuộc mẫu câu nào?',
      opts: o4('Ai làm gì?', 'Ở đâu?', 'Ai là gì?', 'Ai thế nào?'), ans: 'D',
      why: 'Câu nêu <i>đặc điểm</i> của giọt sương (mát lạnh) nên thuộc mẫu “Ai thế nào?”.' },
    { sec: 'Nghĩa của từ', name: 'Câu 8', pts: 1,
      text: 'Từ <b>trái nghĩa</b> với “sớm” trong câu “Sáng sớm, Kiến con bò ra khỏi tổ.” là:',
      opts: o4('vội', 'lâu', 'nhanh', 'muộn'), ans: 'D',
      why: 'Sớm – muộn là cặp từ trái nghĩa chỉ thời gian.' },
    { sec: 'Dấu câu', name: 'Câu 9', pts: 1,
      text: 'Cuối câu “Bạn Kiến con có đáng khen không” phải đặt dấu gì?',
      opts: o4('Dấu chấm', 'Dấu chấm than', 'Dấu chấm hỏi', 'Dấu phẩy'), ans: 'C',
      why: 'Câu có từ để hỏi “không” ở cuối nên là câu hỏi, phải kết thúc bằng dấu chấm hỏi.' },
    { sec: 'Dùng từ', name: 'Câu 10', pts: 1,
      text: 'Chọn từ thích hợp điền vào chỗ trống: “Sên rất ______ Kiến con vì đã để dành nước cho mình.”',
      opts: o4('xa lánh', 'ganh tị', 'biết ơn', 'giận dỗi'), ans: 'C',
      why: 'Được bạn nhường phần nước thì phải thấy “biết ơn”; ba từ kia đều mang nghĩa xấu, không hợp.' },
  ],
},

/* ═══════════ ĐỀ 2 — ĐỌC HIỂU BÀI TẢ: THỨ TỰ MIÊU TẢ ═══════════ */
{
  id: 1702, title: 'Đề 2 · Đọc hiểu bài tả — cây bàng bốn mùa', time: 20,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV2_R2,
      text: 'Cây bàng trong bài được trồng ở đâu?',
      opts: o4('Ở góc sân sau trường', 'Trước cửa lớp em', 'Ngoài cổng trường', 'Bên bờ ao'), ans: 'B',
      why: 'Câu mở đầu: “Trước cửa lớp em có một cây bàng già.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 2', pts: 1, read: TV2_R2,
      text: 'Mùa hè, tán bàng được so sánh với vật gì?',
      opts: o4('Một mái nhà', 'Một đám mây', 'Một chiếc quạt', 'Một chiếc ô lớn'), ans: 'D',
      why: '“Tán bàng xoè rộng như một chiếc ô lớn, che nắng cho chúng em chơi.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 3', pts: 1, read: TV2_R2,
      text: 'Sang mùa thu, lá bàng chuyển sang màu gì?',
      opts: o4('Vàng nhạt', 'Đỏ tía', 'Nâu sẫm', 'Xanh mượt'), ans: 'B',
      why: '“Mùa thu, lá bàng chuyển dần sang màu đỏ tía.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 4', pts: 1, read: TV2_R2,
      text: 'Mùa nào cây bàng rụng hết lá?',
      opts: o4('Mùa hè', 'Mùa thu', 'Mùa đông', 'Mùa xuân'), ans: 'C',
      why: '“Mùa đông, cây trút hết lá, chỉ còn những cành khẳng khiu vươn lên trời.”.' },
    { sec: 'Cách tả', name: 'Câu 5', pts: 1, read: TV2_R2,
      text: 'Bài văn tả cây bàng theo thứ tự nào?',
      opts: o4('Từ gốc lên ngọn', 'Từ xa lại gần', 'Từ trên xuống dưới', 'Theo bốn mùa trong năm'), ans: 'D',
      why: 'Bài lần lượt tả mùa xuân → mùa hè → mùa thu → mùa đông, tức là tả theo thứ tự thời gian.' },
    { sec: 'Từ loại', name: 'Câu 6', pts: 1,
      text: 'Trong cụm từ “búp lá non xanh mượt”, từ nào là <b>từ chỉ đặc điểm</b>?',
      opts: o4('xanh mượt', 'bật ra', 'mùa xuân', 'búp lá'), ans: 'A',
      why: '“xanh mượt” tả màu sắc, vẻ ngoài của lá nên là từ chỉ đặc điểm.' },
    { sec: 'Hình ảnh', name: 'Câu 7', pts: 1,
      text: 'Câu “Tán bàng xoè rộng <b>như</b> một chiếc ô lớn.” dùng từ nào để so sánh hai sự vật?',
      opts: o4('xoè', 'như', 'rộng', 'lớn'), ans: 'B',
      why: 'Từ “như” nối sự vật được so sánh (tán bàng) với sự vật dùng để so sánh (chiếc ô lớn).' },
    { sec: 'Nghĩa của từ', name: 'Câu 8', pts: 1,
      text: 'Từ <b>trái nghĩa</b> với “rộng” là:',
      opts: o4('dài', 'ngắn', 'hẹp', 'to'), ans: 'C',
      why: 'Rộng – hẹp là cặp từ trái nghĩa; dài – ngắn là một cặp khác.' },
    { sec: 'Bộ phận câu', name: 'Câu 9', pts: 1,
      text: 'Trong câu “Chúng em chơi dưới gốc bàng.”, bộ phận trả lời câu hỏi <b>Ở đâu?</b> là:',
      opts: o4('gốc', 'Chúng em', 'chơi', 'dưới gốc bàng'), ans: 'D',
      why: 'Hỏi “Chúng em chơi ở đâu?” — trả lời: dưới gốc bàng.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1,
      text: 'Câu nào hợp làm câu <b>mở đầu</b> cho một đoạn văn tả cây bàng?',
      opts: o4('Em rất yêu cây bàng của lớp em.', 'Mùa đông, bàng trút hết lá.', 'Trước cửa lớp em có một cây bàng già.', 'Lá bàng mùa thu đỏ tía.'), ans: 'C',
      why: 'Câu mở đầu giới thiệu chung về cây. Hai câu tả từng mùa là ý chi tiết ở giữa đoạn, còn “Em rất yêu…” hợp làm câu kết.' },
  ],
},

/* ═══════════ ĐỀ 3 — TỪ CHỈ SỰ VẬT · HOẠT ĐỘNG · ĐẶC ĐIỂM ═══════════ */
{
  id: 1703, title: 'Đề 3 · Từ chỉ sự vật — hoạt động — đặc điểm', time: 20,
  questions: [
    { sec: 'Từ loại', name: 'Câu 1', pts: 1, text: 'Từ nào dưới đây là <b>từ chỉ sự vật</b>?',
      opts: o4('ngôi trường', 'chăm chỉ', 'vui vẻ', 'chạy'), ans: 'A',
      why: '“ngôi trường” gọi tên một sự vật; “chạy” chỉ hoạt động, hai từ còn lại chỉ đặc điểm.' },
    { sec: 'Từ loại', name: 'Câu 2', pts: 1, text: 'Từ nào dưới đây là <b>từ chỉ hoạt động</b>?',
      opts: o4('buổi sáng', 'quét nhà', 'cái chổi', 'sạch sẽ'), ans: 'B',
      why: '“quét nhà” là việc con người làm nên là từ chỉ hoạt động.' },
    { sec: 'Từ loại', name: 'Câu 3', pts: 1, text: 'Từ nào dưới đây là <b>từ chỉ đặc điểm</b>?',
      opts: o4('con mèo', 'bắt chuột', 'tinh nghịch', 'cái đuôi'), ans: 'C',
      why: '“tinh nghịch” tả tính nết nên là từ chỉ đặc điểm.' },
    { sec: 'Từ loại', name: 'Câu 4', pts: 1, text: 'Trong câu “Bà em kể chuyện cổ tích.”, từ chỉ hoạt động là:',
      opts: o4('chuyện cổ tích', 'em', 'Bà em', 'kể'), ans: 'D',
      why: '“kể” là việc bà đang làm. “Bà em” và “chuyện cổ tích” đều chỉ sự vật.' },
    { sec: 'Từ gợi tả', name: 'Câu 5', pts: 1, text: 'Trong câu “Dòng suối chảy róc rách.”, từ nào <b>gợi tả âm thanh</b>?',
      opts: o4('róc rách', 'dòng', 'Dòng suối', 'chảy'), ans: 'A',
      why: '“róc rách” mô phỏng tiếng nước chảy, giúp người đọc như nghe thấy tiếng suối.' },
    { sec: 'Nhóm từ', name: 'Câu 6', pts: 1, text: 'Nhóm từ nào <b>chỉ người trong gia đình</b>?',
      opts: o4('ông, bà, cha, mẹ', 'bàn, ghế, tủ, giường', 'đi, chạy, nhảy, bò', 'xanh, đỏ, tím, vàng'), ans: 'A',
      why: 'Nhóm B chỉ đồ dùng, nhóm C chỉ hoạt động, nhóm D chỉ màu sắc.' },
    { sec: 'Nhóm từ', name: 'Câu 7', pts: 1, text: 'Từ nào <b>không cùng nhóm</b> với các từ còn lại?',
      opts: o4('bút chì', 'thước kẻ', 'tẩy', 'nhảy dây'), ans: 'D',
      why: 'Ba từ đầu đều là đồ dùng học tập (chỉ sự vật), riêng “nhảy dây” chỉ hoạt động.' },
    { sec: 'Dùng từ', name: 'Câu 8', pts: 1, text: 'Điền từ <b>chỉ đặc điểm</b> thích hợp: “Những quả cam chín ______.”',
      opts: o4('trên cây', 'vàng mọng', 'hái xuống', 'bóc vỏ'), ans: 'B',
      why: 'Chỗ trống cần một từ tả quả cam. “vàng mọng” tả màu sắc và độ chín; ba phương án kia không phải từ chỉ đặc điểm.' },
    { sec: 'Từ loại', name: 'Câu 9', pts: 1, text: 'Câu nào có <b>hai</b> từ chỉ đặc điểm?',
      opts: o4('Mẹ nấu cơm.', 'Con mèo đang ngủ.', 'Bầu trời cao và xanh.', 'Em đi học.'), ans: 'C',
      why: '“cao” và “xanh” đều tả bầu trời nên đều là từ chỉ đặc điểm. Ba câu kia chỉ có từ chỉ hoạt động.' },
    { sec: 'Đặt câu', name: 'Câu 10', pts: 1, text: 'Sắp xếp các từ sau thành câu đúng: <b>rất / vườn / hoa / đẹp / nhà em</b>',
      opts: o4('Nhà em vườn hoa đẹp rất.', 'Hoa vườn nhà em rất đẹp.', 'Rất đẹp vườn hoa nhà em.', 'Vườn hoa nhà em rất đẹp.'), ans: 'D',
      why: 'Câu đúng theo mẫu “Ai (cái gì) thế nào?”: Vườn hoa nhà em (cái gì) — rất đẹp (thế nào).' },
  ],
},

/* ═══════════ ĐỀ 4 — BA MẪU CÂU ĐÃ HỌC ═══════════ */
{
  id: 1704, title: 'Đề 4 · Ai là gì? — Ai làm gì? — Ai thế nào?', time: 20,
  questions: [
    { sec: 'Mẫu câu', name: 'Câu 1', pts: 1, text: 'Câu “Mẹ em là bác sĩ.” thuộc mẫu câu nào?',
      opts: o4('Ai là gì?', 'Ai thế nào?', 'Ở đâu?', 'Ai làm gì?'), ans: 'A',
      why: 'Câu dùng từ “là” để giới thiệu nghề nghiệp của mẹ nên thuộc mẫu “Ai là gì?”.' },
    { sec: 'Mẫu câu', name: 'Câu 2', pts: 1, text: 'Câu “Đàn gà con chạy lon ton theo mẹ.” thuộc mẫu câu nào?',
      opts: o4('Khi nào?', 'Ai làm gì?', 'Ai là gì?', 'Ai thế nào?'), ans: 'B',
      why: 'Câu kể việc đàn gà đang làm (chạy lon ton theo mẹ) nên thuộc mẫu “Ai làm gì?”.' },
    { sec: 'Mẫu câu', name: 'Câu 3', pts: 1, text: 'Câu “Bạn Lan rất chăm chỉ.” thuộc mẫu câu nào?',
      opts: o4('Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Khi nào?'), ans: 'C',
      why: 'Câu nêu đặc điểm, tính nết của bạn Lan nên thuộc mẫu “Ai thế nào?”.' },
    { sec: 'Mẫu câu', name: 'Câu 4', pts: 1, text: 'Câu nào thuộc mẫu <b>Ai là gì?</b>',
      opts: o4('Ông em trồng rau ngoài vườn.', 'Ông em là bộ đội về hưu.', 'Ông em rất hiền.', 'Ông em ở quê.'), ans: 'B',
      why: 'Chỉ câu B có từ “là” giới thiệu ông là ai. Câu A thuộc mẫu “Ai làm gì?”, câu C thuộc mẫu “Ai thế nào?”.' },
    { sec: 'Bộ phận câu', name: 'Câu 5', pts: 1, text: 'Bộ phận in đậm trong câu “<b>Chúng em</b> quét dọn lớp học.” trả lời cho câu hỏi nào?',
      opts: o4('Làm gì?', 'Thế nào?', 'Ở đâu?', 'Ai?'), ans: 'D',
      why: 'Hỏi “Ai quét dọn lớp học?” — trả lời: Chúng em.' },
    { sec: 'Bộ phận câu', name: 'Câu 6', pts: 1, text: 'Bộ phận trả lời câu hỏi <b>Làm gì?</b> trong câu “Bố em tưới cây ngoài vườn.” là:',
      opts: o4('tưới cây ngoài vườn', 'ngoài vườn', 'cây', 'Bố em'), ans: 'A',
      why: 'Hỏi “Bố em làm gì?” — trả lời trọn ý: tưới cây ngoài vườn.' },
    { sec: 'Đặt câu hỏi', name: 'Câu 7', pts: 1, text: 'Đặt câu hỏi cho bộ phận in đậm: “Cô giáo em <b>rất dịu dàng</b>.”',
      opts: o4('Cô giáo em làm gì?', 'Cô giáo em thế nào?', 'Cô giáo em ở đâu?', 'Cô giáo em là ai?'), ans: 'B',
      why: '“rất dịu dàng” nêu đặc điểm nên câu hỏi tương ứng là “thế nào?”.' },
    { sec: 'Mẫu câu', name: 'Câu 8', pts: 1, text: 'Câu nào đúng mẫu <b>Ai thế nào?</b>',
      opts: o4('Con đường làng quanh co.', 'Con đường làng là lối đi chung.', 'Con đường dẫn ra cánh đồng.', 'Em đi trên đường làng.'), ans: 'A',
      why: '“quanh co” tả đặc điểm con đường. Câu B thuộc mẫu “Ai là gì?”, câu C và D thuộc mẫu “Ai làm gì?”.' },
    { sec: 'Đặt câu', name: 'Câu 9', pts: 1, text: 'Điền tiếp để được câu theo mẫu <b>Ai làm gì?</b>: “Bạn Nam ______.”',
      opts: o4('là học sinh giỏi', 'rất thông minh', 'đang tưới hoa', 'ở gần nhà em'), ans: 'C',
      why: '“đang tưới hoa” cho biết bạn Nam đang <i>làm</i> việc gì. Hai phương án đầu tạo ra mẫu “Ai là gì?” và “Ai thế nào?”.' },
    { sec: 'Bộ phận câu', name: 'Câu 10', pts: 1, text: 'Trong câu “Sáng nay, lớp em đi tham quan.”, bộ phận trả lời câu hỏi <b>Khi nào?</b> là:',
      opts: o4('đi tham quan', 'tham quan', 'Sáng nay', 'lớp em'), ans: 'C',
      why: 'Hỏi “Khi nào lớp em đi tham quan?” — trả lời: Sáng nay.' },
  ],
},

/* ═══════════ ĐỀ 5 — DẤU CÂU VÀ VIẾT HOA ═══════════ */
{
  id: 1705, title: 'Đề 5 · Dấu câu và viết hoa', time: 20,
  questions: [
    { sec: 'Dấu câu', name: 'Câu 1', pts: 1, text: 'Cuối một <b>câu kể</b> ta đặt dấu gì?',
      opts: o4('Dấu chấm than', 'Dấu phẩy', 'Dấu chấm hỏi', 'Dấu chấm'), ans: 'D',
      why: 'Câu kể dùng để kể, tả một sự việc nên kết thúc bằng dấu chấm.' },
    { sec: 'Dấu câu', name: 'Câu 2', pts: 1, text: 'Cuối câu “Ôi, bông hoa đẹp quá” nên đặt dấu gì?',
      opts: o4('Dấu chấm than', 'Dấu phẩy', 'Dấu chấm', 'Dấu chấm hỏi'), ans: 'A',
      why: 'Câu bộc lộ cảm xúc (có “Ôi”, “quá”) nên kết thúc bằng dấu chấm than.' },
    { sec: 'Dấu câu', name: 'Câu 3', pts: 1, text: 'Dấu phẩy trong câu “Trong vườn có cam, quýt, bưởi.” dùng để làm gì?',
      opts: o4('Bộc lộ cảm xúc', 'Ngăn cách các từ cùng chỉ sự vật được kể ra', 'Kết thúc câu', 'Hỏi điều chưa biết'), ans: 'B',
      why: 'Cam – quýt – bưởi là các sự vật được kể liên tiếp, giữa chúng phải có dấu phẩy.' },
    { sec: 'Dấu câu', name: 'Câu 4', pts: 1, text: 'Câu nào đặt dấu phẩy <b>đúng</b>?',
      opts: o4('Em thích học, vẽ hát múa.', 'Em, thích học vẽ và hát.', 'Em thích học vẽ, hát và múa.', 'Em thích, học vẽ hát múa.'), ans: 'C',
      why: 'Dấu phẩy đặt giữa các việc được kể ra (vẽ, hát, múa), không đặt tách rời chủ ngữ với vị ngữ.' },
    { sec: 'Viết hoa', name: 'Câu 5', pts: 1, text: 'Chữ cái đầu câu phải viết thế nào?',
      opts: o4('Viết thường', 'Viết hoa', 'Viết nghiêng', 'Viết to gấp đôi'), ans: 'B',
      why: 'Quy tắc: chữ cái đầu câu và tên riêng đều phải viết hoa.' },
    { sec: 'Viết hoa', name: 'Câu 6', pts: 1, text: 'Câu nào viết hoa <b>đúng</b>?',
      opts: o4('bạn nam học lớp 2A.', 'Bạn nam học lớp 2A.', 'Bạn Nam học lớp 2A.', 'Bạn Nam Học Lớp 2A.'), ans: 'C',
      why: 'Viết hoa chữ đầu câu (“Bạn”) và tên riêng (“Nam”); các chữ còn lại viết thường.' },
    { sec: 'Viết hoa', name: 'Câu 7', pts: 1, text: 'Tên riêng nào viết <b>sai</b>?',
      opts: o4('Nguyễn Thị Mai', 'Hà Nội', 'sông Hồng', 'Trần quốc toản'), ans: 'D',
      why: 'Tên người phải viết hoa tất cả các chữ: <b>Trần Quốc Toản</b>. Trong “sông Hồng”, “sông” là từ chung nên viết thường.' },
    { sec: 'Dấu câu', name: 'Câu 8', pts: 1, text: 'Cuối câu “Bao giờ lớp mình đi tham quan” đặt dấu gì?',
      opts: o4('Dấu chấm hỏi', 'Dấu chấm than', 'Dấu phẩy', 'Dấu chấm'), ans: 'A',
      why: 'Câu có từ để hỏi “Bao giờ” nên là câu hỏi.' },
    { sec: 'Dấu câu', name: 'Câu 9', pts: 1, text: 'Điền dấu câu thích hợp vào chỗ trống: “Trời hôm nay đẹp quá ___”',
      opts: o4('dấu chấm hỏi', 'dấu chấm than', 'dấu phẩy', 'dấu chấm'), ans: 'B',
      why: 'Từ “quá” cho thấy đây là câu bộc lộ cảm xúc nên dùng dấu chấm than.' },
    { sec: 'Dấu câu', name: 'Câu 10', pts: 1, text: 'Câu nào dùng dấu câu <b>đúng</b>?',
      opts: o4('Bạn tên là gì,', 'Bạn tên là gì.', 'Bạn tên là gì?', 'Bạn tên là gì!'), ans: 'C',
      why: 'Có từ để hỏi “gì” nên phải kết thúc bằng dấu chấm hỏi.' },
  ],
},

/* ═══════════ ĐỀ 6 — MỞ RỘNG VỐN TỪ · TỪ TRÁI NGHĨA ═══════════ */
{
  id: 1706, title: 'Đề 6 · Mở rộng vốn từ — từ trái nghĩa, từ cùng nghĩa', time: 20,
  questions: [
    { sec: 'Mở rộng vốn từ', name: 'Câu 1', pts: 1, text: 'Từ nào chỉ <b>tình cảm gia đình</b>?',
      opts: o4('chạy nhảy', 'xanh biếc', 'cặp sách', 'yêu thương'), ans: 'D',
      why: '“yêu thương” nói về tình cảm giữa những người thân trong nhà.' },
    { sec: 'Mở rộng vốn từ', name: 'Câu 2', pts: 1, text: 'Từ nào <b>không</b> chỉ đồ dùng học tập?',
      opts: o4('nồi cơm', 'thước kẻ', 'bút mực', 'vở ô li'), ans: 'A',
      why: '“nồi cơm” là đồ dùng trong bếp, ba từ còn lại đều mang tới lớp để học.' },
    { sec: 'Nghĩa của từ', name: 'Câu 3', pts: 1, text: 'Từ <b>trái nghĩa</b> với “chăm chỉ” là:',
      opts: o4('siêng năng', 'lười biếng', 'cần cù', 'ngoan ngoãn'), ans: 'B',
      why: '“siêng năng”, “cần cù” đều cùng nghĩa với “chăm chỉ”; chỉ “lười biếng” mới trái nghĩa.' },
    { sec: 'Nghĩa của từ', name: 'Câu 4', pts: 1, text: 'Cặp từ nào là <b>cặp từ trái nghĩa</b>?',
      opts: o4('đẹp – xinh', 'vui – mừng', 'cao – thấp', 'to – lớn'), ans: 'C',
      why: 'Ba cặp còn lại đều là hai từ <i>cùng nghĩa</i>, chỉ “cao – thấp” là hai nghĩa ngược nhau.' },
    { sec: 'Nghĩa của từ', name: 'Câu 5', pts: 1, text: 'Từ nào <b>cùng nghĩa</b> với “siêng năng”?',
      opts: o4('chậm chạp', 'buồn bã', 'lười nhác', 'chăm chỉ'), ans: 'D',
      why: 'Siêng năng và chăm chỉ đều khen người hay làm, hay học.' },
    { sec: 'Mở rộng vốn từ', name: 'Câu 6', pts: 1, text: 'Con vật nào <b>sống dưới nước</b>?',
      opts: o4('con cá chép', 'con mèo', 'con chim sẻ', 'con gà'), ans: 'A',
      why: 'Cá chép sống dưới nước; gà, mèo, chim sẻ đều sống trên cạn.' },
    { sec: 'Mở rộng vốn từ', name: 'Câu 7', pts: 1, text: 'Từ nào chỉ <b>nghề nghiệp</b>?',
      opts: o4('thuốc', 'bác sĩ', 'khám bệnh', 'bệnh viện'), ans: 'B',
      why: '“bác sĩ” gọi tên người làm nghề. “bệnh viện”, “thuốc” chỉ sự vật, “khám bệnh” chỉ hoạt động.' },
    { sec: 'Dùng từ', name: 'Câu 8', pts: 1, text: 'Điền cặp từ trái nghĩa thích hợp: “Mùa hè trời rất ______, mùa đông trời rất ______.”',
      opts: o4('mát – mẻ', 'lạnh – rét', 'nóng – lạnh', 'nóng – nực'), ans: 'C',
      why: 'Chỗ trống cần hai từ ngược nghĩa nhau. Ba phương án kia đều là hai từ cùng nghĩa.' },
    { sec: 'Thành ngữ', name: 'Câu 9', pts: 1, text: 'Điền từ còn thiếu: “Chậm như ______.”',
      opts: o4('chớp', 'sóc', 'ngựa', 'rùa'), ans: 'D',
      why: 'Rùa bò rất chậm nên dân gian nói “chậm như rùa”. Sóc, ngựa, chớp đều dùng để ví sự nhanh.' },
    { sec: 'Mở rộng vốn từ', name: 'Câu 10', pts: 1, text: 'Từ nào chỉ <b>đồ dùng trong nhà</b>?',
      opts: o4('bàn ghế', 'học bài', 'chăm ngoan', 'sân trường'), ans: 'A',
      why: '“bàn ghế” là đồ đạc trong nhà; “học bài” chỉ hoạt động, “chăm ngoan” chỉ đặc điểm.' },
  ],
},

/* ═══════════ ĐỀ 7 — ĐỌC HIỂU BÀI THƠ ═══════════ */
{
  id: 1707, title: 'Đề 7 · Đọc hiểu bài thơ — tình cảm của mẹ', time: 20,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV2_R3,
      text: 'Bài thơ nói về ai?',
      opts: o4('Con ve', 'Người mẹ', 'Cơn gió mùa thu', 'Chiếc võng'), ans: 'B',
      why: 'Cả bài đều xoay quanh hình ảnh người mẹ ngồi ru con và quạt cho con.' },
    { sec: 'Đọc hiểu', name: 'Câu 2', pts: 1, read: TV2_R3,
      text: 'Vì sao con ve cũng phải lặng tiếng?',
      opts: o4('Vì trời mưa', 'Vì trời đã tối', 'Vì mệt do hè nắng oi', 'Vì sợ làm con thức giấc'), ans: 'C',
      why: 'Câu thơ: “Con ve cũng mệt vì hè nắng oi.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 3', pts: 1, read: TV2_R3,
      text: 'Mẹ đang làm gì cho con?',
      opts: o4('Nấu cơm trưa', 'Đi làm ngoài đồng', 'Hái quả trong vườn', 'Ngồi ru con và quạt cho con'), ans: 'D',
      why: '“Kẽo cà tiếng võng mẹ ngồi mẹ ru.” và “Bàn tay mẹ quạt mẹ đưa gió về.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 4', pts: 1, read: TV2_R3,
      text: 'Âm thanh nào được nhắc tới trong bài thơ?',
      opts: o4('Tiếng kẽo cà của võng', 'Tiếng trống trường', 'Tiếng mưa rơi', 'Tiếng chim hót'), ans: 'A',
      why: '“Kẽo cà tiếng võng mẹ ngồi mẹ ru.” — kẽo cà là tiếng chiếc võng đưa.' },
    { sec: 'Cảm thụ', name: 'Câu 5', pts: 1, read: TV2_R3,
      text: 'Câu thơ “Bàn tay mẹ quạt mẹ đưa gió về.” nói lên điều gì?',
      opts: o4('Ngoài trời đang có gió to', 'Mẹ thương con, quạt mãi cho con mát', 'Nhà em mới mua quạt điện', 'Mẹ rất khoẻ tay'), ans: 'B',
      why: 'Trời nắng oi mà mẹ vẫn ngồi quạt cho con ngủ — chi tiết ấy cho thấy mẹ rất thương con.' },
    { sec: 'Cảm thụ', name: 'Câu 6', pts: 1, read: TV2_R3,
      text: 'Bài thơ giúp em hiểu tình cảm nào?',
      opts: o4('Tình yêu quê hương', 'Tình thầy trò', 'Tình yêu thương của mẹ dành cho con', 'Tình bạn bè'), ans: 'C',
      why: 'Toàn bài kể việc mẹ chăm con giữa trưa hè, đó là tình mẹ dành cho con.' },
    { sec: 'Nghĩa của từ', name: 'Câu 7', pts: 1,
      text: 'Từ “nắng oi” trong bài chỉ điều gì?',
      opts: o4('Hoạt động của mẹ', 'Tên một sự vật', 'Một loại quả', 'Đặc điểm của thời tiết'), ans: 'D',
      why: '“nắng oi” tả trời nắng nóng, ngột ngạt — đó là đặc điểm của thời tiết.' },
    { sec: 'Nghĩa của từ', name: 'Câu 8', pts: 1,
      text: 'Từ “lặng” trong câu “Lặng rồi cả tiếng con ve” có nghĩa gần với:',
      opts: o4('im, không còn tiếng', 'vang thật to', 'buồn bã', 'nhanh nhẹn'), ans: 'A',
      why: 'Ve “lặng” nghĩa là ve thôi kêu, xung quanh im ắng.' },
    { sec: 'Mẫu câu', name: 'Câu 9', pts: 1,
      text: 'Câu “Mẹ em rất dịu dàng.” thuộc mẫu câu nào?',
      opts: o4('Ai làm gì?', 'Ai thế nào?', 'Ở đâu?', 'Ai là gì?'), ans: 'B',
      why: 'Câu nêu đặc điểm, tính nết của mẹ nên thuộc mẫu “Ai thế nào?”.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1,
      text: 'Câu nào nói lên <b>tình cảm</b> của em với mẹ hay nhất?',
      opts: o4('Mẹ em cao một mét năm mươi tám.', 'Em rất yêu mẹ và luôn cố gắng chăm ngoan để mẹ vui.', 'Mẹ em đi làm bằng xe máy.', 'Mẹ em tên là Lan.'), ans: 'B',
      why: 'Ba câu kia chỉ nêu thông tin bên ngoài. Chỉ câu B bộc lộ tình cảm và việc làm cụ thể của em.' },
  ],
},

/* ═══════════ ĐỀ 8 — NỀN TẬP LÀM VĂN: SẮP XẾP Ý, CHỌN TỪ GỢI TẢ ═══════════ */
{
  id: 1708, title: 'Đề 8 · Luyện viết đoạn — sắp xếp ý, chọn từ gợi tả', time: 20,
  questions: [
    { sec: 'Sắp xếp ý', name: 'Câu 1', pts: 1,
      text: 'Sắp xếp ba câu sau thành đoạn văn kể về buổi sáng của em:<br>(1) Em đánh răng, rửa mặt.<br>(2) Sáu giờ sáng, em thức dậy.<br>(3) Sau đó em ăn sáng rồi tới trường.',
      opts: o4('(2) – (1) – (3)', '(1) – (2) – (3)', '(3) – (2) – (1)', '(2) – (3) – (1)'), ans: 'A',
      why: 'Kể theo thứ tự việc xảy ra: thức dậy trước, rồi vệ sinh cá nhân, cuối cùng mới ăn sáng và đi học.' },
    { sec: 'Mở đoạn', name: 'Câu 2', pts: 1, text: 'Câu nào hợp làm câu <b>mở đầu</b> đoạn văn tả con mèo?',
      opts: o4('Nhà em có một chú mèo tam thể rất đáng yêu.', 'Chú thích nằm sưởi nắng ngoài hiên.', 'Em rất quý chú mèo ấy.', 'Đuôi chú dài và cong.'), ans: 'A',
      why: 'Câu mở đầu giới thiệu chung con vật sẽ tả. Ba câu kia là ý chi tiết hoặc câu kết.' },
    { sec: 'Kết đoạn', name: 'Câu 3', pts: 1, text: 'Câu nào hợp làm câu <b>kết</b> đoạn văn tả con mèo?',
      opts: o4('Nhà em nuôi một chú mèo.', 'Bộ lông chú mượt như nhung.', 'Em rất quý chú mèo và ngày nào cũng cho chú ăn.', 'Chú mèo bắt chuột rất giỏi.'), ans: 'C',
      why: 'Câu kết nêu tình cảm và việc làm của em với con vật vừa tả.' },
    { sec: 'Từ gợi tả', name: 'Câu 4', pts: 1, text: 'Chọn từ <b>gợi tả</b> hay hơn: “Dòng sông ______ chảy qua làng em.”',
      opts: o4('có nước', 'to', 'dài', 'hiền hoà'), ans: 'D',
      why: '“hiền hoà” vừa tả dòng nước êm, vừa làm câu văn có hình ảnh; ba từ kia chỉ nêu thông tin khô khan.' },
    { sec: 'Từ gợi tả', name: 'Câu 5', pts: 1, text: 'Chọn từ gợi tả thích hợp: “Tiếng chim hót ______ trong vòm lá.”',
      opts: o4('líu lo', 'có', 'xong', 'nhiều'), ans: 'A',
      why: '“líu lo” gợi tiếng chim trong trẻo, ríu rít — làm câu văn sinh động hẳn lên.' },
    { sec: 'Hình ảnh', name: 'Câu 6', pts: 1, text: 'Câu nào có <b>hình ảnh so sánh</b>?',
      opts: o4('Mặt trời đỏ như hòn lửa.', 'Mặt trời đã mọc.', 'Mặt trời ở trên cao.', 'Em nhìn mặt trời.'), ans: 'A',
      why: 'Câu A dùng từ “như” để ví mặt trời với hòn lửa nên có hình ảnh so sánh.' },
    { sec: 'Chọn ý', name: 'Câu 7', pts: 1, text: 'Để tả con gà trống, em nên tả những gì?',
      opts: o4('Giá tiền quyển vở', 'Bộ lông, cái mào, tiếng gáy', 'Số điện thoại của bố', 'Đường đi tới trường'), ans: 'B',
      why: 'Tả con vật thì chọn các nét riêng nhìn thấy, nghe thấy được ở chính con vật đó.' },
    { sec: 'Chọn ý', name: 'Câu 8', pts: 1, text: 'Câu nào <b>lạc ý</b> trong đoạn văn tả vườn hoa nhà em?',
      opts: o4('Vườn nhà em trồng nhiều loài hoa.', 'Hoa hồng nở đỏ thắm.', 'Bố em đang đi công tác xa.', 'Ong bướm bay rập rờn trên các luống hoa.'), ans: 'C',
      why: 'Ba câu kia đều nói về vườn hoa; riêng câu C nói chuyện khác nên bị lạc ý, phải bỏ đi.' },
    { sec: 'Trình bày', name: 'Câu 9', pts: 1, text: 'Khi viết một đoạn văn, chữ đầu đoạn phải viết thế nào?',
      opts: o4('Viết lùi vào một ô và viết hoa', 'Viết sát lề và viết thường', 'Viết to gấp đôi', 'Gạch chân'), ans: 'A',
      why: 'Chữ đầu đoạn lùi vào một ô để người đọc nhận ra đoạn mới, và luôn phải viết hoa.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1, text: 'Câu nào vừa <b>đúng</b> vừa <b>hay</b> hơn?',
      opts: o4('Con mèo nhà em nó có lông.', 'Chú mèo nhà em khoác bộ lông vàng mượt.', 'Mèo em lông.', 'Nhà em mèo lông vàng.'), ans: 'B',
      why: 'Câu B đủ ý, dùng từ gợi tả “vàng mượt” và cách nói “khoác bộ lông” rất sinh động. Câu A thừa từ “nó”, hai câu cuối thiếu ý.' },
  ],
},

/* ═══════════ ĐỀ 9 — CHÍNH TẢ PHÂN BIỆT ═══════════ */
{
  id: 1709, title: 'Đề 9 · Chính tả — l/n, ch/tr, s/x, dấu hỏi – dấu ngã', time: 20,
  questions: [
    { sec: 'Chính tả', name: 'Câu 1', pts: 1, text: 'Từ nào viết <b>đúng</b> chính tả?',
      opts: o4('lo lắng', 'no lắng', 'lo nắng', 'no nắng'), ans: 'A',
      why: 'Viết đúng là “lo lắng” — cả hai tiếng đều bắt đầu bằng chữ <b>l</b>.' },
    { sec: 'Chính tả', name: 'Câu 2', pts: 1, text: 'Từ nào viết <b>đúng</b> chính tả?',
      opts: o4('chăm trỉ', 'trăm chỉ', 'chăm chỉ', 'trăm trỉ'), ans: 'C',
      why: 'Viết đúng là “chăm chỉ” — cả hai tiếng đều bắt đầu bằng <b>ch</b>.' },
    { sec: 'Chính tả', name: 'Câu 3', pts: 1, text: 'Từ nào viết <b>đúng</b> chính tả?',
      opts: o4('suất sắc', 'xuất xắc', 'xuất sắc', 'suất xắc'), ans: 'C',
      why: 'Viết đúng là “xuất sắc”: <b>x</b> ở tiếng đầu, <b>s</b> ở tiếng sau.' },
    { sec: 'Chính tả', name: 'Câu 4', pts: 1, text: 'Chọn cách viết đúng: “Bé ______ kĩ rồi mới trả lời.”',
      opts: o4('suy nghỉ', 'suy nghĩ', 'suy ngỉ', 'suy ngĩ'), ans: 'B',
      why: '“nghĩ” mang dấu ngã và viết bằng <b>ngh</b> (đứng trước i, e, ê).' },
    { sec: 'Chính tả', name: 'Câu 5', pts: 1, text: 'Điền chữ thích hợp: “Trăng ___òn vành vạnh.”',
      opts: o4('t', 'c', 'tr', 'ch'), ans: 'C',
      why: 'Viết đúng là “tròn”. Ghi nhớ: trăng <b>tròn</b>, quả <b>tròn</b> đều dùng <b>tr</b>.' },
    { sec: 'Chính tả', name: 'Câu 6', pts: 1, text: 'Từ nào viết <b>đúng</b> chính tả?',
      opts: o4('quả xung', 'quả sung', 'quả xun', 'quả sunh'), ans: 'B',
      why: 'Tên loại quả này viết là “sung”, bắt đầu bằng chữ <b>s</b>.' },
    { sec: 'Chính tả', name: 'Câu 7', pts: 1, text: 'Từ nào viết <b>đúng</b> chính tả?',
      opts: o4('mải mãi', 'mải mải', 'mãi mải', 'mãi mãi'), ans: 'D',
      why: '“mãi mãi” nghĩa là luôn luôn, không bao giờ hết — cả hai tiếng đều mang <b>dấu ngã</b>.' },
    { sec: 'Chính tả', name: 'Câu 8', pts: 1, text: 'Điền <b>s</b> hoặc <b>x</b>: “Con ___âu đang bò trên lá.”',
      opts: o4('s', 'x', 'ch', 'tr'), ans: 'A',
      why: 'Viết đúng là “con sâu”. Phân biệt với “xâu” trong “xâu kim”, “xâu chuỗi”.' },
    { sec: 'Chính tả', name: 'Câu 9', pts: 1, text: 'Điền <b>l</b> hoặc <b>n</b>: “___ước biển trong xanh.”',
      opts: o4('l', 'n', 'đ', 't'), ans: 'B',
      why: 'Viết đúng là “nước biển”. Phân biệt với “lước” — không phải tiếng Việt.' },
    { sec: 'Chính tả', name: 'Câu 10', pts: 1, text: 'Câu nào viết <b>đúng chính tả hoàn toàn</b>?',
      opts: o4('Trời nắng, bé đội mủ ra sân.', 'Trời lắng, bé đội mũ ra sân.', 'Trời nắng, bé đội mũ ra sân.', 'Trời nắng, bé đội mủ ra vân.'), ans: 'C',
      why: 'Đúng là “nắng” (chữ n) và “mũ” (dấu ngã). “mủ” là nhựa cây, “lắng” là lắng nghe — đều sai nghĩa ở đây.' },
  ],
},

/* ═══════════ ĐỀ 10 — TỔNG HỢP ═══════════ */
{
  id: 1710, title: 'Đề 10 · Tổng hợp — đọc hiểu và luyện từ câu', time: 20,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV2_R4,
      text: 'Bạn mới của lớp 2A tên là gì?',
      opts: o4('Lan', 'Nam', 'Mai', 'Hà'), ans: 'D',
      why: '“Bạn tên là Hà, vừa chuyển từ quê ra.”.' },
    { sec: 'Suy luận', name: 'Câu 2', pts: 1, read: TV2_R4,
      text: 'Vì sao lúc mới tới lớp, mặt Hà đỏ bừng?',
      opts: o4('Vì ngượng khi tới lớp mới', 'Vì bị cô giáo mắng', 'Vì vừa chạy nhanh', 'Vì trời nắng'), ans: 'A',
      why: 'Bài đọc nói rõ: “Hà đứng nép bên cửa lớp, mặt đỏ bừng vì ngượng.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 3', pts: 1, read: TV2_R4,
      text: 'Ai đã rủ Hà ra sân chơi?',
      opts: o4('Cô giáo', 'Mai', 'Cả lớp', 'Anh trai của Hà'), ans: 'B',
      why: '“Giờ ra chơi, Mai rủ Hà ra sân nhảy dây.”.' },
    { sec: 'Suy luận', name: 'Câu 4', pts: 1, read: TV2_R4,
      text: 'Nhờ đâu Hà thấy lớp mới thật gần gũi?',
      opts: o4('Nhờ các bạn thân thiện, rủ Hà cùng chơi', 'Nhờ lớp học rộng rãi', 'Nhờ lớp có nhiều đồ chơi', 'Nhờ được ngồi bàn đầu'), ans: 'A',
      why: 'Từ chỗ đứng nép ngượng ngùng, Hà chỉ thấy gần gũi sau khi được Mai rủ chơi và cả nhóm cùng cười vang.' },
    { sec: 'Bài học', name: 'Câu 5', pts: 1, read: TV2_R4,
      text: 'Câu chuyện khuyên em điều gì?',
      opts: o4('Nên giữ vệ sinh lớp học', 'Nên đi học thật sớm', 'Nên làm quen và giúp đỡ bạn mới', 'Nên chăm học bài ở nhà'), ans: 'C',
      why: 'Việc làm của Mai khiến bạn mới hết ngượng — đó là điều câu chuyện muốn nhắn nhủ.' },
    { sec: 'Từ loại', name: 'Câu 6', pts: 1,
      text: 'Trong câu “Mai rủ Hà ra sân nhảy dây.”, từ chỉ hoạt động là:',
      opts: o4('Hà', 'sân', 'Mai', 'rủ'), ans: 'D',
      why: '“rủ” là việc Mai làm; “Mai”, “Hà”, “sân” đều chỉ sự vật.' },
    { sec: 'Mẫu câu', name: 'Câu 7', pts: 1,
      text: 'Câu “Hà là bạn mới của lớp 2A.” thuộc mẫu câu nào?',
      opts: o4('Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'), ans: 'A',
      why: 'Câu dùng từ “là” để giới thiệu Hà là ai.' },
    { sec: 'Bộ phận câu', name: 'Câu 8', pts: 1,
      text: 'Trong câu “Giờ ra chơi, Mai rủ Hà ra sân.”, bộ phận trả lời câu hỏi <b>Khi nào?</b> là:',
      opts: o4('Mai', 'Giờ ra chơi', 'ra sân', 'rủ Hà'), ans: 'B',
      why: 'Hỏi “Khi nào Mai rủ Hà ra sân?” — trả lời: Giờ ra chơi.' },
    { sec: 'Nghĩa của từ', name: 'Câu 9', pts: 1,
      text: 'Từ <b>trái nghĩa</b> với “ngượng ngùng” là:',
      opts: o4('rụt rè', 'e thẹn', 'tự tin', 'xấu hổ'), ans: 'C',
      why: 'Ba từ “rụt rè”, “e thẹn”, “xấu hổ” đều gần nghĩa với “ngượng ngùng”; chỉ “tự tin” mới trái nghĩa.' },
    { sec: 'Dấu câu', name: 'Câu 10', pts: 1,
      text: 'Cuối câu “Bạn Hà học lớp mấy” phải đặt dấu gì?',
      opts: o4('Dấu chấm than', 'Dấu phẩy', 'Dấu chấm', 'Dấu chấm hỏi'), ans: 'D',
      why: 'Câu có từ để hỏi “mấy” nên là câu hỏi, kết thúc bằng dấu chấm hỏi.' },
  ],
},

];

SUBJECTS.push({
  id: 'tviet2', name: 'Tiếng Việt — Đọc hiểu', short: 'Tiếng Việt 2', icon: '📝', grade: 2,
  exams: TV2_EXAMS, ready: true,
  heroTitle: 'Tiếng Việt lớp 2 — đọc hiểu, luyện từ và câu, tập làm văn',
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bài đọc hiện kèm từng câu hỏi',
});
