// ĐẠO ĐỨC — LỚP 4 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// 8 chủ đề bám chương trình Đạo đức lớp 4:
//   - Biết ơn người lao động
//   - Tôn trọng sự khác biệt của người khác
//   - Yêu lao động
//   - Quý trọng đồng tiền (tiết kiệm, chi tiêu hợp lí)
//   - Bảo vệ của công
//   - Thiết lập và duy trì quan hệ bạn bè tốt
//   - Quyền và bổn phận của trẻ em
//   - Trung thực trong học tập
// Mỗi câu là một tình huống / hành vi đúng - sai; đáp án đúng là ứng xử chuẩn mực.

const DAODUC4_EXAMS = [

/* ═══════════ ĐỀ 1 — BIẾT ƠN NGƯỜI LAO ĐỘNG ═══════════ */
{
  id: 9211, title: 'Đề 1 · Biết ơn người lao động', time: 20,
  questions: [
    { sec: 'Biết ơn người lao động', name: 'Câu 1', pts: 1,
      text: 'Ai là người lao động?',
      opts: o4('Bác nông dân, cô công nhân, chú lái xe, thầy cô giáo', 'Chỉ những người làm việc trong nhà máy', 'Chỉ những người có bằng đại học', 'Chỉ những người mặc đồng phục'), ans: 'A',
      why: 'Người lao động là tất cả những ai làm việc để tạo ra của cải vật chất và tinh thần cho xã hội.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 2', pts: 1,
      text: 'Khi được bác bảo vệ mở cổng trường, em nên làm gì?',
      opts: o4('Đi thẳng vào, không nói gì', 'Chê bác mở cổng chậm', 'Coi như không thấy bác', 'Lễ phép chào và cảm ơn bác'), ans: 'D',
      why: 'Lễ phép chào hỏi và cảm ơn là cách thể hiện sự biết ơn với người lao động.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 3', pts: 1,
      text: 'Thấy cô lao công đang quét sân trường, hành động nào là đúng?',
      opts: o4('Vứt rác bừa bãi vì đã có cô quét', 'Trêu chọc cho vui', 'Không xả rác và bỏ rác đúng nơi quy định', 'Giẫm lên chỗ cô vừa quét'), ans: 'C',
      why: 'Giữ vệ sinh, bỏ rác đúng chỗ là cách tôn trọng công sức của cô lao công.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 4', pts: 1,
      text: 'Hạt gạo em ăn hằng ngày là thành quả lao động của ai?',
      opts: o4('Của bác nông dân', 'Tự nhiên mà có', 'Của người bán hàng', 'Của siêu thị'), ans: 'A',
      why: 'Bác nông dân đã một nắng hai sương cấy trồng để làm ra hạt gạo.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 5', pts: 1,
      text: 'Câu tục ngữ nào nói về lòng biết ơn người làm ra hạt gạo?',
      opts: o4('Đi một ngày đàng, học một sàng khôn', 'Ăn quả nhớ kẻ trồng cây', 'Gần mực thì đen, gần đèn thì sáng', 'Có công mài sắt, có ngày nên kim'), ans: 'B',
      why: '"Ăn quả nhớ kẻ trồng cây" nhắc ta biết ơn người đã tạo ra thành quả cho mình hưởng.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 6', pts: 1,
      text: 'Bạn Nam nói: "Nghề quét rác thấp hèn, chẳng đáng tôn trọng." Ý kiến của bạn Nam:',
      opts: o4('Đúng, vì nghề đó bẩn', 'Đúng, vì lương thấp', 'Sai, vì mọi nghề lao động chân chính đều đáng quý', 'Đúng một phần'), ans: 'C',
      why: 'Mọi nghề nghiệp lao động chân chính đều có ích và đáng được tôn trọng như nhau.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 7', pts: 1,
      text: 'Để tỏ lòng biết ơn thầy cô giáo, em nên làm gì?',
      opts: o4('Chăm học, ngoan ngoãn, lễ phép', 'Chỉ tặng quà đắt tiền', 'Nói xấu thầy cô với bạn', 'Không làm bài tập'), ans: 'A',
      why: 'Chăm ngoan, học tốt và lễ phép là món quà ý nghĩa nhất dành cho thầy cô.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 8', pts: 1,
      text: 'Chú thợ xây đang làm việc dưới trời nắng. Em cảm thấy thế nào?',
      opts: o4('Coi thường vì việc nặng nhọc', 'Thấy bình thường, không quan tâm', 'Trân trọng công sức và sự vất vả của chú', 'Chê chú làm chậm'), ans: 'C',
      why: 'Hiểu được sự vất vả của người lao động giúp ta thêm trân trọng thành quả của họ.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 9', pts: 1,
      text: 'Việc làm nào thể hiện sự biết ơn người lao động?',
      opts: o4('Phá hoại đồ vật họ làm ra', 'Ăn uống lãng phí thức ăn', 'Giữ gìn, sử dụng tiết kiệm sản phẩm lao động', 'Chê bai sản phẩm của họ'), ans: 'C',
      why: 'Giữ gìn và dùng tiết kiệm sản phẩm lao động là cách trân trọng công sức người làm ra.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 10', pts: 1,
      text: 'Vì sao chúng ta cần biết ơn người lao động?',
      opts: o4('Vì họ giàu có', 'Vì họ nổi tiếng', 'Vì họ là người quen', 'Vì họ tạo ra của cải, phục vụ cuộc sống của mọi người'), ans: 'D',
      why: 'Nhờ lao động của mọi người mà xã hội có cơm ăn, áo mặc, trường học, đường sá... nên ta phải biết ơn.' },
  ],
},

/* ═══════════ ĐỀ 2 — TÔN TRỌNG SỰ KHÁC BIỆT ═══════════ */
{
  id: 9212, title: 'Đề 2 · Tôn trọng sự khác biệt của người khác', time: 20,
  questions: [
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 1', pts: 1,
      text: 'Trong lớp có bạn nói giọng địa phương khác. Em nên:',
      opts: o4('Chê cười cách bạn nói', 'Tôn trọng và lắng nghe bạn', 'Bắt chước để trêu bạn', 'Không chơi với bạn'), ans: 'B',
      why: 'Mỗi vùng miền có giọng nói riêng; ta cần tôn trọng sự khác biệt đó.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 2', pts: 1,
      text: 'Bạn Hoa là người dân tộc thiểu số, mặc trang phục truyền thống đến lễ hội. Em nên:',
      opts: o4('Trân trọng nét đẹp văn hoá của bạn', 'Chê trang phục lạ', 'Xa lánh bạn', 'Bảo bạn đừng mặc như vậy'), ans: 'A',
      why: 'Trang phục truyền thống của mỗi dân tộc là nét đẹp văn hoá đáng được trân trọng.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 3', pts: 1,
      text: 'Lớp có bạn khuyết tật phải đi xe lăn. Cách ứng xử đúng là:',
      opts: o4('Trêu chọc bạn', 'Không cho bạn tham gia trò chơi', 'Giúp đỡ và chơi cùng bạn bình thường', 'Nhìn bạn với ánh mắt coi thường'), ans: 'C',
      why: 'Bạn khuyết tật cần được cảm thông, giúp đỡ và đối xử bình đẳng như mọi người.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 4', pts: 1,
      text: 'Mỗi người có sở thích, tính cách khác nhau. Điều đó là:',
      opts: o4('Điều bình thường, cần được tôn trọng', 'Điều xấu cần sửa', 'Lí do để chê bai nhau', 'Lí do để xa lánh nhau'), ans: 'A',
      why: 'Sự khác biệt về sở thích, tính cách là điều tự nhiên và đáng được tôn trọng.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 5', pts: 1,
      text: 'Bạn cùng bàn theo tôn giáo khác em. Em nên:',
      opts: o4('Tôn trọng tín ngưỡng của bạn', 'Bắt bạn theo tôn giáo của mình', 'Chế giễu tôn giáo của bạn', 'Không nói chuyện với bạn'), ans: 'A',
      why: 'Mỗi người có quyền tự do tín ngưỡng; ta cần tôn trọng niềm tin của người khác.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 6', pts: 1,
      text: 'Bạn Minh học chậm hơn các bạn. Em nên:',
      opts: o4('Chê bạn dốt', 'Cười nhạo mỗi khi bạn trả lời sai', 'Kiên nhẫn giúp bạn cùng tiến bộ', 'Không cho bạn hỏi bài'), ans: 'C',
      why: 'Mỗi người có tốc độ học khác nhau; giúp đỡ bạn là việc nên làm.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 7', pts: 1,
      text: 'Tôn trọng sự khác biệt của người khác giúp:',
      opts: o4('Mọi người xa cách nhau hơn', 'Gây ra mâu thuẫn', 'Không có ích gì', 'Mọi người sống hoà hợp, thân thiện với nhau'), ans: 'D',
      why: 'Khi biết tôn trọng sự khác biệt, mọi người sẽ hiểu, yêu thương và sống hoà thuận với nhau.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 8', pts: 1,
      text: 'Thấy bạn có ngoại hình khác mình, em không nên:',
      opts: o4('Chơi thân với bạn', 'Đặt biệt danh xấu để chế giễu bạn', 'Khen điểm tốt của bạn', 'Đối xử công bằng với bạn'), ans: 'B',
      why: 'Đặt biệt danh xấu, chế giễu ngoại hình làm bạn tổn thương và là hành vi thiếu tôn trọng.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 9', pts: 1,
      text: 'Bạn nêu ý kiến khác với em trong nhóm. Em nên:',
      opts: o4('Bác bỏ ngay ý kiến của bạn', 'Giận dỗi không hợp tác', 'Lắng nghe và cùng bàn bạc', 'Chê ý kiến bạn là ngớ ngẩn'), ans: 'C',
      why: 'Lắng nghe ý kiến khác biệt giúp cả nhóm tìm được cách giải quyết tốt hơn.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 10', pts: 1,
      text: 'Câu nói nào thể hiện thái độ tôn trọng sự khác biệt?',
      opts: o4('"Bạn khác tớ nên tớ không chơi."', '"Phải giống tớ mới được."', '"Bạn lạ lắm, tránh xa ra."', '"Mỗi người một vẻ, chúng ta cùng học hỏi nhau."'), ans: 'D',
      why: 'Thừa nhận "mỗi người một vẻ" và cùng học hỏi là biểu hiện của sự tôn trọng khác biệt.' },
  ],
},

/* ═══════════ ĐỀ 3 — YÊU LAO ĐỘNG ═══════════ */
{
  id: 9213, title: 'Đề 3 · Yêu lao động', time: 20,
  questions: [
    { sec: 'Yêu lao động', name: 'Câu 1', pts: 1,
      text: 'Việc làm nào thể hiện em yêu lao động?',
      opts: o4('Tự giác quét nhà, giúp bố mẹ việc vặt', 'Ỷ lại, chờ người khác làm hộ', 'Trốn tránh mọi việc nhà', 'Chỉ chơi, không làm gì'), ans: 'A',
      why: 'Tự giác làm việc nhà phù hợp sức mình là biểu hiện của lòng yêu lao động.' },
    { sec: 'Yêu lao động', name: 'Câu 2', pts: 1,
      text: 'Đến phiên trực nhật lớp, em nên:',
      opts: o4('Nhờ bạn làm hộ', 'Làm qua loa cho xong', 'Hoàn thành nhiệm vụ sạch sẽ, cẩn thận', 'Bỏ về sớm'), ans: 'C',
      why: 'Làm tốt việc trực nhật là hoàn thành trách nhiệm và thể hiện tinh thần lao động.' },
    { sec: 'Yêu lao động', name: 'Câu 3', pts: 1,
      text: 'Câu tục ngữ nào ca ngợi lao động?',
      opts: o4('Có làm thì mới có ăn', 'Chân cứng đá mềm', 'Lá lành đùm lá rách', 'Một cây làm chẳng nên non'), ans: 'A',
      why: '"Có làm thì mới có ăn" khẳng định giá trị và sự cần thiết của lao động.' },
    { sec: 'Yêu lao động', name: 'Câu 4', pts: 1,
      text: 'Bạn Lan lười làm bài, hay chép bài bạn. Việc đó thể hiện:',
      opts: o4('Chăm chỉ lao động học tập', 'Lười lao động, ỷ lại', 'Yêu lao động', 'Trung thực'), ans: 'B',
      why: 'Chép bài, lười học là biểu hiện của sự lười lao động và ỷ lại vào người khác.' },
    { sec: 'Yêu lao động', name: 'Câu 5', pts: 1,
      text: 'Ở nhà, việc phù hợp với học sinh lớp 4 là:',
      opts: o4('Xây nhà', 'Lái máy cày', 'Gấp quần áo, tưới cây, rửa bát', 'Đi làm kiếm tiền cả ngày'), ans: 'C',
      why: 'Gấp quần áo, tưới cây, rửa bát là việc vừa sức, giúp đỡ gia đình.' },
    { sec: 'Yêu lao động', name: 'Câu 6', pts: 1,
      text: 'Vì sao chúng ta cần yêu lao động?',
      opts: o4('Vì lao động tạo ra của cải và giúp ta trưởng thành', 'Vì lao động là việc bắt buộc và khổ sở', 'Vì để được khen', 'Vì sợ bị phạt'), ans: 'A',
      why: 'Lao động tạo ra của cải, rèn tính chăm chỉ và giúp mỗi người trưởng thành hơn.' },
    { sec: 'Yêu lao động', name: 'Câu 7', pts: 1,
      text: 'Trong giờ lao động tập thể, em thấy bạn mệt. Em nên:',
      opts: o4('Mặc kệ bạn', 'Chê bạn yếu', 'Giúp bạn một tay để cùng hoàn thành', 'Bỏ đi chơi'), ans: 'C',
      why: 'Giúp đỡ bạn trong lao động thể hiện tinh thần đoàn kết và yêu lao động.' },
    { sec: 'Yêu lao động', name: 'Câu 8', pts: 1,
      text: 'Thái độ đúng khi làm việc là:',
      opts: o4('Làm cho có, cẩu thả', 'Vừa làm vừa than vãn rồi bỏ dở', 'Đùn đẩy cho người khác', 'Chăm chỉ, cố gắng làm đến nơi đến chốn'), ans: 'D',
      why: 'Chăm chỉ, làm việc đến nơi đến chốn là thái độ lao động đúng đắn.' },
    { sec: 'Yêu lao động', name: 'Câu 9', pts: 1,
      text: 'Bạn nói: "Còn nhỏ chỉ cần chơi, không phải làm gì cả." Ý kiến đó:',
      opts: o4('Đúng hoàn toàn', 'Sai, vì trẻ em cũng nên làm việc vừa sức', 'Đúng vì làm việc là của người lớn', 'Đúng vì trẻ em không làm được gì'), ans: 'B',
      why: 'Trẻ em cần tham gia lao động vừa sức để rèn luyện tính tự lập và chăm chỉ.' },
    { sec: 'Yêu lao động', name: 'Câu 10', pts: 1,
      text: 'Kết quả của việc chăm chỉ lao động, học tập là:',
      opts: o4('Bị mọi người chê', 'Mất thời gian vô ích', 'Không có gì thay đổi', 'Đạt kết quả tốt và được mọi người quý mến'), ans: 'D',
      why: 'Chăm chỉ lao động, học tập giúp ta đạt kết quả tốt và được mọi người yêu quý.' },
  ],
},

/* ═══════════ ĐỀ 4 — QUÝ TRỌNG ĐỒNG TIỀN ═══════════ */
{
  id: 9214, title: 'Đề 4 · Quý trọng đồng tiền', time: 20,
  questions: [
    { sec: 'Quý trọng đồng tiền', name: 'Câu 1', pts: 1,
      text: 'Đồng tiền có được là nhờ đâu?',
      opts: o4('Tự nhiên mà có', 'Do lao động vất vả của con người', 'Nhặt được ngoài đường', 'Ai cũng in được'), ans: 'B',
      why: 'Tiền là thành quả lao động vất vả, vì vậy cần được quý trọng.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 2', pts: 1,
      text: 'Được bố mẹ cho tiền tiêu vặt, em nên:',
      opts: o4('Tiêu hết ngay vào quà bánh', 'Mua đồ chơi đắt tiền không cần thiết', 'Chi tiêu hợp lí và để dành một phần', 'Cho hết bạn bè để lấy oai'), ans: 'C',
      why: 'Chi tiêu hợp lí và tiết kiệm một phần là cách quý trọng đồng tiền.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 3', pts: 1,
      text: 'Việc làm nào thể hiện tiết kiệm?',
      opts: o4('Bỏ heo đất số tiền chưa dùng đến', 'Xé tiền chơi', 'Vứt tiền lẻ đi', 'Mua nhiều đồ rồi bỏ phí'), ans: 'A',
      why: 'Nuôi heo đất, để dành tiền chưa cần dùng là biểu hiện của tiết kiệm.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 4', pts: 1,
      text: 'Trước khi mua một món đồ, em nên tự hỏi:',
      opts: o4('"Món này có thật sự cần thiết không?"', '"Làm sao tiêu hết tiền nhanh nhất?"', '"Bạn nào cũng có nên mình phải có."', '"Mua cho bằng bạn bằng bè."'), ans: 'A',
      why: 'Cân nhắc món đồ có cần thiết không giúp em chi tiêu hợp lí, tránh lãng phí.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 5', pts: 1,
      text: 'Bạn Tú đòi bố mẹ mua điện thoại đắt tiền dù nhà còn khó khăn. Việc đó:',
      opts: o4('Nên làm để bằng bạn bè', 'Bình thường', 'Là quyền của trẻ em', 'Không nên, vì đó là đòi hỏi lãng phí, không thương bố mẹ'), ans: 'D',
      why: 'Đòi hỏi những thứ đắt tiền không cần thiết là lãng phí và không thương công sức bố mẹ.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 6', pts: 1,
      text: 'Cách sử dụng điện, nước tiết kiệm là:',
      opts: o4('Bật đèn cả ngày lẫn đêm', 'Để vòi nước chảy tràn', 'Tắt đèn, khoá vòi nước khi không dùng', 'Mở điều hoà rồi mở cửa sổ'), ans: 'C',
      why: 'Tắt điện, khoá nước khi không dùng là cách tiết kiệm, cũng là quý trọng tiền của.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 7', pts: 1,
      text: 'Nhặt được tiền rơi ở trường, em nên:',
      opts: o4('Giữ làm của riêng', 'Chia cho bạn thân', 'Nộp cho thầy cô để trả người mất', 'Giấu đi không cho ai biết'), ans: 'C',
      why: 'Nộp lại tiền nhặt được để trả người đánh mất là hành động trung thực và đúng đắn.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 8', pts: 1,
      text: 'Tiết kiệm tiền để dành có ích lợi gì?',
      opts: o4('Không có ích gì', 'Có thể dùng khi cần thiết hoặc giúp đỡ người khác', 'Làm ta keo kiệt', 'Khiến ta nghèo đi'), ans: 'B',
      why: 'Tiền tiết kiệm giúp ta chủ động khi cần và có thể giúp đỡ người khó khăn.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 9', pts: 1,
      text: 'Bạn khoe tiêu hết sạch tiền lì xì vào game trong một ngày. Em khuyên bạn:',
      opts: o4('Nên chi tiêu hợp lí, để dành cho việc cần thiết', 'Giỏi lắm, tiêu tiếp đi', 'Vay thêm để tiêu', 'Mặc kệ bạn'), ans: 'A',
      why: 'Khuyên bạn chi tiêu hợp lí, để dành là giúp bạn biết quý trọng đồng tiền.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 10', pts: 1,
      text: 'Quý trọng đồng tiền KHÔNG có nghĩa là:',
      opts: o4('Chi tiêu hợp lí', 'Tiết kiệm, không lãng phí', 'Keo kiệt, không dám giúp ai lúc cần', 'Giữ gìn tiền cẩn thận'), ans: 'C',
      why: 'Quý trọng tiền là dùng đúng lúc, đúng chỗ, không phải keo kiệt bủn xỉn.' },
  ],
},

/* ═══════════ ĐỀ 5 — BẢO VỆ CỦA CÔNG ═══════════ */
{
  id: 9215, title: 'Đề 5 · Bảo vệ của công', time: 20,
  questions: [
    { sec: 'Bảo vệ của công', name: 'Câu 1', pts: 1,
      text: 'Của công là gì?',
      opts: o4('Tài sản riêng của một người', 'Đồ vật bỏ đi', 'Đồ của nhà em', 'Tài sản chung của tập thể, nhà nước, mọi người'), ans: 'D',
      why: 'Của công là tài sản chung như bàn ghế lớp học, cây xanh, công viên... của mọi người.' },
    { sec: 'Bảo vệ của công', name: 'Câu 2', pts: 1,
      text: 'Việc làm nào bảo vệ của công?',
      opts: o4('Vẽ bậy lên tường lớp học', 'Giữ gìn bàn ghế, đồ dùng chung sạch sẽ', 'Bẻ cành cây trong công viên', 'Làm hỏng vòi nước công cộng'), ans: 'B',
      why: 'Giữ gìn, dùng cẩn thận đồ dùng chung là hành động bảo vệ của công.' },
    { sec: 'Bảo vệ của công', name: 'Câu 3', pts: 1,
      text: 'Thấy bạn khắc tên lên bàn học của lớp, em nên:',
      opts: o4('Khắc theo cho vui', 'Cổ vũ bạn', 'Khuyên bạn dừng lại vì đó là của chung', 'Kệ bạn'), ans: 'C',
      why: 'Khuyên bạn không phá hoại đồ dùng chung là góp phần bảo vệ của công.' },
    { sec: 'Bảo vệ của công', name: 'Câu 4', pts: 1,
      text: 'Ra khỏi lớp giờ ra chơi, em nên:',
      opts: o4('Để đèn, quạt chạy suốt', 'Mở thêm tất cả đèn', 'Bật điều hoà rồi đi ra', 'Tắt đèn, quạt để tiết kiệm điện của trường'), ans: 'D',
      why: 'Tắt điện, quạt khi không dùng là tiết kiệm điện và bảo vệ tài sản chung của trường.' },
    { sec: 'Bảo vệ của công', name: 'Câu 5', pts: 1,
      text: 'Hành vi nào làm hại của công?',
      opts: o4('Tưới cây trong sân trường', 'Ngắt hoa, giẫm lên bồn cỏ nơi công cộng', 'Lau bàn ghế lớp học', 'Nhắc bạn giữ vệ sinh'), ans: 'B',
      why: 'Ngắt hoa, giẫm cỏ nơi công cộng là phá hoại của công, cần tránh.' },
    { sec: 'Bảo vệ của công', name: 'Câu 6', pts: 1,
      text: 'Ở công viên, em nên:',
      opts: o4('Vứt rác xuống hồ', 'Bẻ cây làm gậy chơi', 'Viết vẽ lên tượng đài', 'Bỏ rác vào thùng, giữ gìn ghế đá, cây xanh'), ans: 'D',
      why: 'Bỏ rác đúng nơi, giữ gìn ghế đá, cây xanh là bảo vệ của công nơi công cộng.' },
    { sec: 'Bảo vệ của công', name: 'Câu 7', pts: 1,
      text: 'Vì sao phải bảo vệ của công?',
      opts: o4('Vì của công phục vụ lợi ích chung của mọi người', 'Vì sợ bị phạt', 'Vì đó là của người khác không liên quan đến mình', 'Vì để được khen'), ans: 'A',
      why: 'Của công phục vụ lợi ích chung nên mỗi người đều có trách nhiệm giữ gìn.' },
    { sec: 'Bảo vệ của công', name: 'Câu 8', pts: 1,
      text: 'Thấy vòi nước công cộng bị hỏng chảy tràn, em nên:',
      opts: o4('Mặc kệ vì không phải của mình', 'Báo cho người lớn hoặc bảo vệ để sửa', 'Mở to thêm cho vui', 'Đứng nhìn rồi bỏ đi'), ans: 'B',
      why: 'Báo người lớn sửa chữa kịp thời giúp tránh lãng phí và bảo vệ của công.' },
    { sec: 'Bảo vệ của công', name: 'Câu 9', pts: 1,
      text: 'Sách vở, thiết bị trong thư viện trường là:',
      opts: o4('Của riêng thủ thư', 'Đồ bỏ đi', 'Của riêng em khi mượn', 'Của công, cần dùng cẩn thận và giữ gìn'), ans: 'D',
      why: 'Sách, thiết bị thư viện là của công; cần dùng cẩn thận và trả lại nguyên vẹn.' },
    { sec: 'Bảo vệ của công', name: 'Câu 10', pts: 1,
      text: 'Câu nào thể hiện ý thức bảo vệ của công?',
      opts: o4('"Của chung nên chẳng cần giữ."', '"Giữ gìn của công như giữ của nhà mình."', '"Ai làm hỏng cũng được, không sao."', '"Không phải việc của mình."'), ans: 'B',
      why: 'Coi của công quý như của nhà mình là ý thức đúng đắn cần có.' },
  ],
},

/* ═══════════ ĐỀ 6 — QUAN HỆ BẠN BÈ TỐT ═══════════ */
{
  id: 9216, title: 'Đề 6 · Thiết lập và duy trì quan hệ bạn bè', time: 20,
  questions: [
    { sec: 'Quan hệ bạn bè', name: 'Câu 1', pts: 1,
      text: 'Có bạn mới chuyển đến lớp, em nên:',
      opts: o4('Làm quen, chỉ dẫn và giúp bạn hoà nhập', 'Lờ bạn đi', 'Chê bạn là người lạ', 'Không cho bạn chơi cùng'), ans: 'A',
      why: 'Chủ động làm quen, giúp đỡ bạn mới là cách thiết lập quan hệ bạn bè tốt.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 2', pts: 1,
      text: 'Để giữ tình bạn lâu bền, em cần:',
      opts: o4('Chân thành, tôn trọng và giúp đỡ nhau', 'Hơn thua, ganh ghét nhau', 'Chỉ chơi khi bạn có lợi cho mình', 'Nói xấu sau lưng bạn'), ans: 'A',
      why: 'Chân thành, tôn trọng và giúp đỡ nhau giúp tình bạn bền lâu.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 3', pts: 1,
      text: 'Khi bạn buồn vì bị điểm kém, em nên:',
      opts: o4('Cười nhạo bạn', 'Khoe điểm cao của mình', 'Động viên và giúp bạn học tốt hơn', 'Kể cho cả lớp biết'), ans: 'C',
      why: 'Động viên, giúp đỡ bạn lúc khó khăn thể hiện tình bạn chân thành.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 4', pts: 1,
      text: 'Hai bạn thân giận nhau vì hiểu lầm. Cách tốt nhất là:',
      opts: o4('Nghỉ chơi luôn', 'Nói xấu nhau với người khác', 'Bình tĩnh nói chuyện để hiểu và làm hoà', 'Chờ bạn xin lỗi trước rồi mới nói'), ans: 'C',
      why: 'Trò chuyện thẳng thắn để hiểu nhau và làm hoà giúp giữ gìn tình bạn.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 5', pts: 1,
      text: 'Bạn rủ em cùng trốn học đi chơi. Em nên:',
      opts: o4('Đồng ý ngay cho vui', 'Đi cùng rồi giấu bố mẹ', 'Rủ thêm bạn khác', 'Từ chối và khuyên bạn không nên làm vậy'), ans: 'D',
      why: 'Bạn tốt là biết từ chối việc sai và khuyên nhau làm điều đúng.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 6', pts: 1,
      text: 'Khi bạn mắc lỗi với em nhưng đã xin lỗi, em nên:',
      opts: o4('Ghi thù mãi', 'Tha thứ và tiếp tục làm bạn', 'Trả đũa lại bạn', 'Kể lỗi của bạn cho mọi người'), ans: 'B',
      why: 'Biết tha thứ khi bạn đã nhận lỗi giúp tình bạn bền chặt hơn.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 7', pts: 1,
      text: 'Việc làm nào KHÔNG giúp duy trì tình bạn?',
      opts: o4('Chia sẻ, giúp đỡ nhau', 'Lắng nghe nhau', 'Nói dối và lợi dụng bạn', 'Cùng nhau học tập, vui chơi'), ans: 'C',
      why: 'Nói dối, lợi dụng bạn làm mất lòng tin và phá vỡ tình bạn.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 8', pts: 1,
      text: 'Thấy bạn bị các bạn khác bắt nạt, em nên:',
      opts: o4('Hùa theo bắt nạt', 'Đứng nhìn cho vui', 'Bảo vệ bạn và báo thầy cô', 'Bỏ mặc bạn'), ans: 'C',
      why: 'Bảo vệ bạn và báo thầy cô là hành động dũng cảm, đúng đắn của người bạn tốt.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 9', pts: 1,
      text: 'Bạn đạt giải trong cuộc thi. Em nên:',
      opts: o4('Chúc mừng và vui cùng bạn', 'Ghen tị với bạn', 'Cho rằng bạn may mắn', 'Không quan tâm'), ans: 'A',
      why: 'Chúc mừng thành công của bạn thể hiện tình bạn chân thành, không ganh tị.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 10', pts: 1,
      text: 'Một tình bạn tốt được xây dựng trên cơ sở:',
      opts: o4('Sự chân thành, tin tưởng và tôn trọng lẫn nhau', 'Sự hơn thua', 'Lợi ích cá nhân', 'Việc a dua theo bạn'), ans: 'A',
      why: 'Tình bạn đẹp dựa trên sự chân thành, tin tưởng và tôn trọng lẫn nhau.' },
  ],
},

/* ═══════════ ĐỀ 7 — QUYỀN VÀ BỔN PHẬN CỦA TRẺ EM ═══════════ */
{
  id: 9217, title: 'Đề 7 · Quyền và bổn phận của trẻ em', time: 20,
  questions: [
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 1', pts: 1,
      text: 'Trẻ em có quyền nào sau đây?',
      opts: o4('Quyền được học tập', 'Quyền không phải học', 'Quyền bỏ nhà đi', 'Quyền làm mọi việc mình muốn'), ans: 'A',
      why: 'Được học tập là một trong những quyền cơ bản của trẻ em.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 2', pts: 1,
      text: 'Bổn phận của trẻ em đối với gia đình là:',
      opts: o4('Chỉ đòi hỏi bố mẹ chiều', 'Không làm gì cả', 'Cãi lời người lớn', 'Kính trọng, vâng lời, giúp đỡ ông bà cha mẹ'), ans: 'D',
      why: 'Trẻ em có bổn phận kính trọng, vâng lời và giúp đỡ ông bà, cha mẹ.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 3', pts: 1,
      text: 'Quyền được vui chơi, giải trí của trẻ em nghĩa là:',
      opts: o4('Chơi cả ngày, không cần học', 'Được vui chơi lành mạnh, phù hợp lứa tuổi', 'Chơi những trò nguy hiểm', 'Bỏ học đi chơi'), ans: 'B',
      why: 'Trẻ em có quyền vui chơi, giải trí lành mạnh, phù hợp với lứa tuổi.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 4', pts: 1,
      text: 'Bổn phận của trẻ em ở trường là:',
      opts: o4('Chăm học, lễ phép với thầy cô, đoàn kết với bạn', 'Trốn học, đánh nhau', 'Không nghe lời thầy cô', 'Phá phách lớp học'), ans: 'A',
      why: 'Chăm học, lễ phép và đoàn kết với bạn là bổn phận của học sinh ở trường.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 5', pts: 1,
      text: 'Trẻ em có quyền được:',
      opts: o4('Bị bỏ rơi', 'Lao động nặng nhọc kiếm tiền', 'Chăm sóc sức khoẻ và bảo vệ', 'Bị bắt nghỉ học'), ans: 'C',
      why: 'Trẻ em có quyền được chăm sóc sức khoẻ, được bảo vệ khỏi nguy hại.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 6', pts: 1,
      text: 'Việc làm nào là thực hiện tốt bổn phận của trẻ em?',
      opts: o4('Bỏ bê học hành', 'Nói dối bố mẹ', 'Bắt nạt em nhỏ', 'Tự giác học bài và giúp việc nhà'), ans: 'D',
      why: 'Tự giác học bài, giúp việc nhà là làm tròn bổn phận của trẻ em.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 7', pts: 1,
      text: 'Bạn Hùng bị bắt nghỉ học để đi làm thuê. Điều này:',
      opts: o4('Là bình thường', 'Vi phạm quyền được học tập của trẻ em', 'Là điều nên làm', 'Không liên quan đến quyền trẻ em'), ans: 'B',
      why: 'Bắt trẻ nghỉ học đi làm là vi phạm quyền được học tập của trẻ em.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 8', pts: 1,
      text: 'Khi bị người lớn đối xử không đúng, trẻ em nên:',
      opts: o4('Im lặng chịu đựng', 'Trả đũa lại', 'Bỏ nhà đi', 'Nói với người tin cậy như bố mẹ, thầy cô'), ans: 'D',
      why: 'Trẻ em nên chia sẻ với người lớn tin cậy để được bảo vệ và giúp đỡ.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 9', pts: 1,
      text: 'Quyền và bổn phận của trẻ em có mối quan hệ:',
      opts: o4('Chỉ có quyền, không có bổn phận', 'Đi liền với nhau: hưởng quyền và làm tròn bổn phận', 'Chỉ có bổn phận, không có quyền', 'Không liên quan gì'), ans: 'B',
      why: 'Trẻ em được hưởng quyền, đồng thời phải thực hiện tốt bổn phận của mình.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 10', pts: 1,
      text: 'Đối với em nhỏ trong nhà, em nên:',
      opts: o4('Bắt nạt, doạ nạt em', 'Tranh đồ chơi với em', 'Mách bố mẹ mọi lỗi của em', 'Yêu thương, nhường nhịn và chăm sóc em'), ans: 'D',
      why: 'Yêu thương, nhường nhịn em nhỏ là bổn phận của anh chị trong gia đình.' },
  ],
},

/* ═══════════ ĐỀ 8 — TRUNG THỰC TRONG HỌC TẬP ═══════════ */
{
  id: 9218, title: 'Đề 8 · Trung thực trong học tập', time: 20,
  questions: [
    { sec: 'Trung thực trong học tập', name: 'Câu 1', pts: 1,
      text: 'Trong giờ kiểm tra, em không làm được bài. Em nên:',
      opts: o4('Chép bài của bạn', 'Giở tài liệu', 'Tự cố gắng làm hết sức mình', 'Nhìn bài bạn bên cạnh'), ans: 'C',
      why: 'Tự làm bài bằng khả năng của mình là biểu hiện của tính trung thực.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 2', pts: 1,
      text: 'Em quên làm bài tập về nhà. Khi cô hỏi, em nên:',
      opts: o4('Nói dối là để quên vở ở nhà', 'Thành thật nhận lỗi và hứa sẽ làm bù', 'Đổ lỗi cho em trai', 'Nói là bị mất vở'), ans: 'B',
      why: 'Thành thật nhận lỗi và sửa chữa là hành động trung thực, đáng khen.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 3', pts: 1,
      text: 'Bạn rủ em cho chép bài trong giờ kiểm tra. Em nên:',
      opts: o4('Cho bạn chép để giữ tình bạn', 'Chép chung với bạn', 'Từ chối và khuyên bạn tự làm', 'Đưa bài cho bạn xem'), ans: 'C',
      why: 'Từ chối cho chép bài và khuyên bạn tự làm mới là giúp bạn thật sự.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 4', pts: 1,
      text: 'Trung thực trong học tập giúp em:',
      opts: o4('Bị điểm kém mãi', 'Bị bạn bè xa lánh', 'Không học được gì', 'Biết đúng năng lực để cố gắng tiến bộ'), ans: 'D',
      why: 'Trung thực giúp em biết đúng sức mình, từ đó cố gắng học tập tiến bộ.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 5', pts: 1,
      text: 'Được điểm cao nhờ chép bài, em cảm thấy:',
      opts: o4('Vui và tự hào', 'Áy náy vì đó không phải sức mình', 'Muốn chép tiếp lần sau', 'Bình thường'), ans: 'B',
      why: 'Điểm cao không thực chất chỉ khiến ta áy náy; trung thực mới đáng tự hào.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 6', pts: 1,
      text: 'Thấy bạn quay cóp trong giờ kiểm tra, em nên:',
      opts: o4('Khuyên bạn dừng lại hoặc báo thầy cô', 'Bắt chước theo', 'Cổ vũ bạn', 'Che cho bạn'), ans: 'A',
      why: 'Khuyên bạn hoặc báo thầy cô giúp bạn sửa sai và giữ sự công bằng.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 7', pts: 1,
      text: 'Cô chấm nhầm cho em điểm cao hơn bài làm. Em nên:',
      opts: o4('Im lặng giữ điểm cao', 'Mừng thầm', 'Khoe với các bạn', 'Báo cô để chấm lại cho đúng'), ans: 'D',
      why: 'Báo cô chấm lại cho đúng là hành động trung thực, dù em bị hạ điểm.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 8', pts: 1,
      text: 'Câu tục ngữ nào nói về tính trung thực?',
      opts: o4('Cây ngay không sợ chết đứng', 'Đi một ngày đàng học một sàng khôn', 'Kiến tha lâu đầy tổ', 'Chậm mà chắc'), ans: 'A',
      why: '"Cây ngay không sợ chết đứng" ca ngợi người trung thực, ngay thẳng.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 9', pts: 1,
      text: 'Người trung thực trong học tập là người:',
      opts: o4('Hay nói dối để được điểm cao', 'Không gian lận, dám nhận lỗi và sửa lỗi', 'Chép bài bạn khéo léo', 'Giấu dốt'), ans: 'B',
      why: 'Người trung thực không gian lận, dám nhận và sửa lỗi của mình.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 10', pts: 1,
      text: 'Vì sao cần trung thực trong học tập?',
      opts: o4('Để được điểm cao bằng mọi giá', 'Để khỏi bị phạt', 'Để tiến bộ thật sự và được mọi người tin yêu', 'Vì bị bắt buộc'), ans: 'C',
      why: 'Trung thực giúp ta học tập tiến bộ thật sự và được thầy cô, bạn bè tin yêu.' },
  ],
},

/* ═══════════ ĐỀ 9 — TỔNG HỢP ═══════════ */
{
  id: 9219, title: 'Đề 9 · Tổng hợp', time: 20,
  questions: [
    { sec: 'Biết ơn người lao động', name: 'Câu 1', pts: 1,
      text: 'Gặp bác đưa thư đến nhà, em nên:',
      opts: o4('Lễ phép chào và cảm ơn bác', 'Không nói gì', 'Chê bác đến muộn', 'Đóng cửa lại'), ans: 'A',
      why: 'Chào hỏi, cảm ơn người lao động thể hiện sự lễ phép và lòng biết ơn.' },
    { sec: 'Yêu lao động', name: 'Câu 2', pts: 1,
      text: 'Sáng chủ nhật, mẹ nhờ em dọn nhà. Em nên:',
      opts: o4('Viện cớ mệt để trốn', 'Nhờ em làm hết', 'Làm qua loa rồi đi chơi', 'Vui vẻ giúp mẹ dọn dẹp'), ans: 'D',
      why: 'Vui vẻ giúp việc nhà là biểu hiện của lòng yêu lao động và thương bố mẹ.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 3', pts: 1,
      text: 'Cách chi tiêu hợp lí là:',
      opts: o4('Mua thứ cần trước, thứ muốn sau và để dành một phần', 'Thấy gì thích là mua', 'Tiêu hết ngay khi có tiền', 'Vay tiền để mua đồ chơi'), ans: 'A',
      why: 'Ưu tiên thứ cần thiết và biết để dành là cách chi tiêu hợp lí.' },
    { sec: 'Bảo vệ của công', name: 'Câu 4', pts: 1,
      text: 'Trên xe buýt, em thấy bạn rạch ghế. Em nên:',
      opts: o4('Làm theo', 'Khuyên bạn dừng vì đó là của công', 'Cười cổ vũ', 'Im lặng bỏ qua'), ans: 'B',
      why: 'Ghế xe buýt là của công; khuyên bạn giữ gìn là việc nên làm.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 5', pts: 1,
      text: 'Bạn mới có sở thích ăn món lạ vùng bạn. Em nên:',
      opts: o4('Chê món ăn của bạn', 'Bảo bạn đừng ăn nữa', 'Xa lánh bạn', 'Tôn trọng và tìm hiểu nét văn hoá của bạn'), ans: 'D',
      why: 'Món ăn vùng miền là nét văn hoá riêng, cần được tôn trọng và tìm hiểu.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 6', pts: 1,
      text: 'Bạn thân bị ốm nghỉ học nhiều ngày. Em nên:',
      opts: o4('Quên luôn bạn', 'Hỏi thăm và chép bài giúp bạn', 'Vui vì bớt đối thủ', 'Không quan tâm'), ans: 'B',
      why: 'Hỏi thăm, chép bài giúp bạn lúc ốm đau là tình bạn chân thành.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 7', pts: 1,
      text: 'Việc nào là bổn phận của em ở nhà?',
      opts: o4('Chỉ chơi và xem tivi', 'Đòi hỏi bố mẹ mua đồ', 'Cãi lời người lớn', 'Vâng lời và giúp đỡ ông bà, cha mẹ'), ans: 'D',
      why: 'Vâng lời, giúp đỡ ông bà cha mẹ là bổn phận của trẻ em trong gia đình.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 8', pts: 1,
      text: 'Làm sai một câu trong bài, em nên:',
      opts: o4('Sửa lại cho đúng và rút kinh nghiệm', 'Giấu đi không cho ai biết', 'Đổ lỗi cho đề khó', 'Xé bài đi'), ans: 'A',
      why: 'Nhận ra và sửa lỗi để tiến bộ là biểu hiện của trung thực và cầu tiến.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 9', pts: 1,
      text: 'Ăn cơm, em nên:',
      opts: o4('Bỏ mứa thức ăn thoải mái', 'Ăn hết suất, không lãng phí để quý công người làm ra', 'Chê cơm không ngon rồi bỏ', 'Vứt thức ăn thừa đi'), ans: 'B',
      why: 'Ăn hết suất, không lãng phí là cách trân trọng công sức người làm ra hạt gạo.' },
    { sec: 'Bảo vệ của công', name: 'Câu 10', pts: 1,
      text: 'Sau giờ học, thấy quạt lớp vẫn quay, em nên:',
      opts: o4('Kệ, có bác lao công tắt', 'Bật thêm cho mát', 'Chủ động tắt quạt để tiết kiệm điện của trường', 'Bỏ ra về'), ans: 'C',
      why: 'Chủ động tắt quạt khi không dùng là tiết kiệm điện, bảo vệ của công.' },
  ],
},

/* ═══════════ ĐỀ 10 — TỔNG HỢP ═══════════ */
{
  id: 9220, title: 'Đề 10 · Tổng hợp', time: 20,
  questions: [
    { sec: 'Trung thực trong học tập', name: 'Câu 1', pts: 1,
      text: 'Nhặt được chiếc bút đẹp của bạn đánh rơi, em nên:',
      opts: o4('Giữ làm của mình', 'Đổi lấy bút cũ của mình', 'Giấu đi', 'Trả lại cho bạn'), ans: 'D',
      why: 'Trả lại đồ nhặt được cho người mất là hành động trung thực, thật thà.' },
    { sec: 'Yêu lao động', name: 'Câu 2', pts: 1,
      text: 'Trong buổi lao động trồng cây ở trường, em nên:',
      opts: o4('Đứng xem bạn làm', 'Tích cực tham gia cùng các bạn', 'Trốn về sớm', 'Chỉ tay sai bạn'), ans: 'B',
      why: 'Tích cực tham gia lao động tập thể thể hiện tinh thần yêu lao động, đoàn kết.' },
    { sec: 'Tôn trọng sự khác biệt', name: 'Câu 3', pts: 1,
      text: 'Bạn trong lớp nói lắp, khó diễn đạt. Em nên:',
      opts: o4('Kiên nhẫn lắng nghe và tôn trọng bạn', 'Cười nhạo bạn', 'Nói thay để bạn im', 'Bắt chước bạn'), ans: 'A',
      why: 'Kiên nhẫn lắng nghe, không chê cười là tôn trọng sự khác biệt của bạn.' },
    { sec: 'Quý trọng đồng tiền', name: 'Câu 4', pts: 1,
      text: 'Bạn khoe mua đồ dùng học tập mới liên tục dù đồ cũ còn tốt. Em nghĩ:',
      opts: o4('Nên bắt chước bạn', 'Càng nhiều đồ mới càng giỏi', 'Không liên quan đến tiết kiệm', 'Đó là lãng phí, nên dùng hết đồ cũ trước'), ans: 'D',
      why: 'Mua đồ mới khi đồ cũ còn dùng tốt là lãng phí, không quý trọng tiền của.' },
    { sec: 'Biết ơn người lao động', name: 'Câu 5', pts: 1,
      text: 'Ngày 20-11, em thể hiện lòng biết ơn thầy cô bằng cách:',
      opts: o4('Chỉ cần nghỉ học ở nhà', 'Gửi lời chúc, chăm học và ngoan ngoãn', 'Đòi thầy cô cho điểm cao', 'Không làm gì'), ans: 'B',
      why: 'Lời chúc chân thành cùng sự chăm ngoan là cách tri ân thầy cô ý nghĩa nhất.' },
    { sec: 'Quan hệ bạn bè', name: 'Câu 6', pts: 1,
      text: 'Em và bạn cùng thích một vai trong buổi diễn văn nghệ. Cách xử lí hay là:',
      opts: o4('Giành cho bằng được', 'Giận bạn', 'Cùng bàn bạc, nhường nhịn hoặc bốc thăm công bằng', 'Bỏ không tham gia nữa'), ans: 'C',
      why: 'Bàn bạc, nhường nhịn công bằng giúp giữ hoà khí và tình bạn tốt đẹp.' },
    { sec: 'Bảo vệ của công', name: 'Câu 7', pts: 1,
      text: 'Ở lớp, sách giáo khoa dùng chung của thư viện, em nên:',
      opts: o4('Vẽ bậy, gấp mép sách', 'Xé trang mình cần', 'Cho mượn lung tung rồi mất', 'Giữ sạch sẽ, bọc cẩn thận và trả đúng hạn'), ans: 'D',
      why: 'Giữ gìn và trả sách dùng chung đúng hạn là bảo vệ của công.' },
    { sec: 'Quyền và bổn phận trẻ em', name: 'Câu 8', pts: 1,
      text: 'Trẻ em có quyền được bày tỏ ý kiến. Điều đó nghĩa là:',
      opts: o4('Nói gì, làm gì cũng được', 'Được nêu suy nghĩ của mình một cách lễ phép', 'Cãi lại người lớn', 'Không cần nghe ai'), ans: 'B',
      why: 'Trẻ em được bày tỏ ý kiến một cách lễ phép, phù hợp, không phải cãi lại người lớn.' },
    { sec: 'Yêu lao động', name: 'Câu 9', pts: 1,
      text: 'Người lười lao động thường:',
      opts: o4('Được mọi người quý mến', 'Học giỏi, làm giỏi', 'Sống tự lập', 'Ỷ lại người khác và khó thành công'), ans: 'D',
      why: 'Lười lao động khiến người ta ỷ lại, không tự lập và khó đạt thành công.' },
    { sec: 'Trung thực trong học tập', name: 'Câu 10', pts: 1,
      text: 'Điều quý giá nhất mà tính trung thực mang lại là:',
      opts: o4('Điểm số cao', 'Sự tin yêu, quý trọng của mọi người', 'Nhiều tiền', 'Được nổi tiếng'), ans: 'B',
      why: 'Người trung thực luôn được mọi người tin yêu và quý trọng — điều quý giá nhất.' },
  ],
},

];

SUBJECTS.push({ id:'daoduc4', name:'Đạo đức', short:'Đạo đức 4', icon:'❤️', grade:4, exams:DAODUC4_EXAMS, ready:true, heroTitle:'Đạo đức lớp 4 — biết ơn người lao động, tôn trọng sự khác biệt, yêu lao động và quý trọng đồng tiền', heroMeta:'📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018' });
