// TỰ NHIÊN VÀ XÃ HỘI — LỚP 2 (GDPT 2018)
// 10 đề × 10 câu = 100 câu. Mỗi câu 1 điểm — thang 10 — 15 phút mỗi đề.
//
// 6 chủ đề, nhấn các nội dung riêng của lớp 2:
//   - Gia đình: các thế hệ, nghề nghiệp, phòng tránh ngộ độc, giữ sạch nhà ở
//   - Trường học: sự kiện ở trường, giữ vệ sinh và an toàn
//   - Cộng đồng: mua bán hàng hoá, phương tiện và an toàn giao thông
//   - Thực vật và động vật: môi trường sống trên cạn / dưới nước, ích lợi – tác hại
//   - Con người và sức khoẻ: cơ quan vận động (xương, cơ, khớp) và cách bảo vệ
//   - Trái Đất và bầu trời: các mùa trong năm

const TNXH2_EXAMS = [

/* ═══════════ ĐỀ 1 — CÁC THẾ HỆ TRONG GIA ĐÌNH ═══════════ */
{
  id: 5201, title: 'Đề 1 · Các thế hệ trong gia đình', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Gia đình gồm ông bà, bố mẹ và các con là gia đình có mấy thế hệ?',
      opts: o4('Một thế hệ', 'Hai thế hệ', 'Ba thế hệ', 'Bốn thế hệ'), ans: 'C',
      why: 'Ông bà — bố mẹ — các con là ba thế hệ cùng chung sống.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Gia đình chỉ có bố mẹ và các con là gia đình có mấy thế hệ?',
      opts: o4('Một thế hệ', 'Hai thế hệ', 'Ba thế hệ', 'Không có thế hệ nào'), ans: 'B',
      why: 'Bố mẹ và các con là hai thế hệ.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Trong gia đình, ai thuộc thế hệ lớn tuổi nhất?',
      opts: o4('Ông bà', 'Bố mẹ', 'Các con', 'Các cháu nhỏ'), ans: 'A',
      why: 'Ông bà là thế hệ lớn tuổi nhất trong nhà.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Anh trai của bố em, em gọi là gì?',
      opts: o4('Bác', 'Dì', 'Cậu', 'Ông'), ans: 'A',
      why: 'Anh (hoặc chị) của bố thường được gọi là bác.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Em trai của mẹ em, em gọi là gì?',
      opts: o4('Chú', 'Cậu', 'Bác', 'Ông'), ans: 'B',
      why: 'Em trai của mẹ được gọi là cậu.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Con của bác, của cô, của cậu... so với em thì gọi chung là gì?',
      opts: o4('Anh, chị, em họ', 'Người lạ', 'Bạn cùng lớp', 'Hàng xóm'), ans: 'A',
      why: 'Con của anh chị em bố mẹ là anh, chị, em họ của em.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Vào ngày giỗ, ngày Tết, họ hàng thường làm gì?',
      opts: o4('Không gặp nhau', 'Sum họp, thăm hỏi nhau', 'Tránh mặt nhau', 'Cãi nhau'), ans: 'B',
      why: 'Giỗ, Tết là dịp họ hàng sum họp, thăm hỏi và gắn bó với nhau.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Việc làm nào thể hiện sự kính trọng ông bà, cha mẹ?',
      opts: o4('Vâng lời, lễ phép, giúp việc nhà', 'Cãi lại người lớn', 'Bỏ đi khi được nhắc nhở', 'Đòi hỏi quà liên tục'), ans: 'A',
      why: 'Lễ phép, vâng lời và giúp đỡ là cách thể hiện lòng kính trọng người lớn.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Chị gái của mẹ, em gọi là gì?',
      opts: o4('Bác gái (già) hoặc dì', 'Chú', 'Cậu', 'Ông ngoại'), ans: 'A',
      why: 'Chị của mẹ nhiều nơi gọi là bác gái, có nơi gọi là dì.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Vì sao cần giữ mối quan hệ tốt với họ hàng?',
      opts: o4('Để mọi người thương yêu, giúp đỡ nhau', 'Để khoe của cải', 'Để tranh giành đồ đạc', 'Không có lí do gì'), ans: 'A',
      why: 'Họ hàng thân thiết thì thương yêu, giúp đỡ nhau khi vui cũng như khi khó khăn.' },
  ],
},

/* ═══════════ ĐỀ 2 — NGHỀ NGHIỆP, GIỮ NHÀ SẠCH VÀ PHÒNG NGỘ ĐỘC ═══════════ */
{
  id: 5202, title: 'Đề 2 · Nghề nghiệp và an toàn trong nhà', time: 15,
  questions: [
    { sec: 'Nghề nghiệp', name: 'Câu 1', pts: 1,
      text: 'Người trồng lúa, trồng rau, nuôi gà lợn làm nghề gì?',
      opts: o4('Bác sĩ', 'Nông dân', 'Giáo viên', 'Thợ may'), ans: 'B',
      why: 'Người làm ruộng, trồng trọt, chăn nuôi là nông dân.' },
    { sec: 'Nghề nghiệp', name: 'Câu 2', pts: 1,
      text: 'Người may quần áo cho mọi người làm nghề gì?',
      opts: o4('Thợ may', 'Đầu bếp', 'Lái xe', 'Ngư dân'), ans: 'A',
      why: 'Người may quần áo là thợ may.' },
    { sec: 'Nghề nghiệp', name: 'Câu 3', pts: 1,
      text: 'Người đánh bắt cá trên biển làm nghề gì?',
      opts: o4('Nông dân', 'Ngư dân', 'Bác sĩ', 'Kĩ sư'), ans: 'B',
      why: 'Người ra biển đánh cá gọi là ngư dân.' },
    { sec: 'Nghề nghiệp', name: 'Câu 4', pts: 1,
      text: 'Mọi nghề nghiệp trong xã hội đều thế nào?',
      opts: o4('Đều đáng quý và có ích cho mọi người', 'Chỉ nghề giàu mới đáng quý', 'Chỉ nghề bác sĩ mới quý', 'Không nghề nào có ích'), ans: 'A',
      why: 'Nghề nào cũng đáng quý vì đều góp ích cho xã hội.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Vì sao không được tự ý uống thuốc khi chưa hỏi người lớn?',
      opts: o4('Vì uống nhầm thuốc có thể bị ngộ độc', 'Vì thuốc đắng', 'Vì thuốc để trang trí', 'Vì thuốc nặng'), ans: 'A',
      why: 'Uống nhầm hoặc uống sai thuốc rất dễ bị ngộ độc, nguy hiểm tính mạng.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Thức ăn có mùi lạ, thiu mốc thì em nên làm gì?',
      opts: o4('Cứ ăn cho hết', 'Không ăn, bỏ đi', 'Cất lại ăn sau', 'Cho bạn ăn thử'), ans: 'B',
      why: 'Thức ăn ôi thiu, mốc gây ngộ độc; tuyệt đối không được ăn.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Chai đựng dầu hoả, thuốc trừ sâu, nước tẩy rửa cần để ở đâu?',
      opts: o4('Trong tủ lạnh cùng đồ ăn', 'Xa tầm tay trẻ em, có dán nhãn rõ', 'Ngay trên bàn ăn', 'Trong cốc uống nước'), ans: 'B',
      why: 'Hoá chất độc phải để riêng, xa tầm với trẻ em và dán nhãn để không nhầm.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Trái cây, rau trước khi ăn cần làm gì để tránh ngộ độc?',
      opts: o4('Rửa sạch (gọt vỏ nếu cần)', 'Ăn ngay khi vừa hái', 'Lăn xuống đất cho sạch', 'Không cần rửa'), ans: 'A',
      why: 'Rửa sạch rau quả giúp loại bỏ bụi bẩn, thuốc sâu, tránh đau bụng.' },
    { sec: 'Nhà ở', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp giữ nhà ở luôn sạch sẽ, gọn gàng?',
      opts: o4('Quét dọn, lau nhà, sắp xếp đồ đạc', 'Để rác trong phòng', 'Vứt đồ bừa bãi', 'Không bao giờ dọn'), ans: 'A',
      why: 'Quét dọn, lau nhà và sắp xếp gọn gàng giúp nhà sạch, đẹp, an toàn.' },
    { sec: 'Nhà ở', name: 'Câu 10', pts: 1,
      text: 'Nhà ở sạch sẽ, thoáng mát đem lại lợi ích gì?',
      opts: o4('Mọi người khoẻ mạnh, ít bệnh tật', 'Dễ bị ốm hơn', 'Nhiều muỗi hơn', 'Không có lợi ích gì'), ans: 'A',
      why: 'Nhà sạch, thoáng ít vi trùng, ruồi muỗi nên mọi người khoẻ mạnh hơn.' },
  ],
},

/* ═══════════ ĐỀ 3 — TRƯỜNG HỌC: SỰ KIỆN, VỆ SINH VÀ AN TOÀN ═══════════ */
{
  id: 5203, title: 'Đề 3 · Hoạt động và an toàn ở trường', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Ngày khai giảng năm học mới thường diễn ra vào tháng nào?',
      opts: o4('Tháng 6', 'Tháng 9', 'Tháng 12', 'Tháng 3'), ans: 'B',
      why: 'Lễ khai giảng năm học mới ở nước ta thường vào đầu tháng 9 (mùng 5-9).' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Hoạt động nào thường được tổ chức ở trường?',
      opts: o4('Lễ khai giảng, ngày hội đọc sách, văn nghệ', 'Họp chợ mua bán', 'Cày ruộng', 'Sửa xe'), ans: 'A',
      why: 'Trường học tổ chức khai giảng, ngày hội đọc sách, văn nghệ, thể thao...' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Ngày Nhà giáo Việt Nam là ngày nào để em tri ân thầy cô?',
      opts: o4('20 tháng 11', '8 tháng 3', '1 tháng 6', '2 tháng 9'), ans: 'A',
      why: 'Ngày 20/11 là Ngày Nhà giáo Việt Nam.' },
    { sec: 'Vệ sinh', name: 'Câu 4', pts: 1,
      text: 'Để giữ lớp học và sân trường sạch sẽ, em nên làm gì?',
      opts: o4('Trực nhật, bỏ rác đúng nơi', 'Vứt rác ra sân', 'Vẽ bẩn lên bàn ghế', 'Khạc nhổ bừa bãi'), ans: 'A',
      why: 'Trực nhật, quét lớp và bỏ rác đúng nơi giúp trường luôn sạch.' },
    { sec: 'Vệ sinh', name: 'Câu 5', pts: 1,
      text: 'Sau khi đi vệ sinh ở trường, em cần làm gì?',
      opts: o4('Rửa tay sạch bằng xà phòng', 'Chạy ngay vào lớp', 'Lau tay vào áo bạn', 'Không cần làm gì'), ans: 'A',
      why: 'Rửa tay bằng xà phòng giúp phòng bệnh lây qua tay.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Việc nào KHÔNG an toàn khi ở trường?',
      opts: o4('Đi bộ trong hành lang', 'Chạy đuổi, xô đẩy ở cầu thang', 'Xếp hàng ngay ngắn', 'Ngồi học nghiêm túc'), ans: 'B',
      why: 'Chạy đuổi, xô đẩy ở cầu thang rất dễ ngã và gây tai nạn.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Khi thấy sàn lớp bị ướt, trơn trượt, em nên làm gì?',
      opts: o4('Chạy nhanh qua cho vui', 'Đi cẩn thận, báo thầy cô lau khô', 'Trượt patin trên đó', 'Đổ thêm nước'), ans: 'B',
      why: 'Sàn trơn dễ ngã; nên đi cẩn thận và báo thầy cô lau khô.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Đồ vật nào ở trường có thể gây nguy hiểm nếu nghịch phá?',
      opts: o4('Ổ điện, quạt điện đang chạy', 'Quyển sách', 'Cái bảng', 'Cây bút chì để viết'), ans: 'A',
      why: 'Ổ điện, quạt đang chạy có thể gây điện giật, thương tích nếu nghịch.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Khi tham gia hoạt động tập thể ở trường, em nên có thái độ thế nào?',
      opts: o4('Vui vẻ, đoàn kết, hợp tác với bạn', 'Tách riêng không tham gia', 'Gây gổ với bạn', 'Phá đám bạn'), ans: 'A',
      why: 'Tham gia tập thể cần vui vẻ, đoàn kết và hợp tác cùng các bạn.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Ngày hội đọc sách ở trường giúp em điều gì?',
      opts: o4('Ham đọc sách, hiểu biết nhiều hơn', 'Lười học hơn', 'Không có ích gì', 'Ghét sách hơn'), ans: 'A',
      why: 'Ngày hội đọc sách khơi dậy niềm ham đọc, giúp em hiểu biết thêm.' },
  ],
},

/* ═══════════ ĐỀ 4 — MUA BÁN HÀNG HOÁ ═══════════ */
{
  id: 5204, title: 'Đề 4 · Hoạt động mua bán hàng hoá', time: 15,
  questions: [
    { sec: 'Mua bán', name: 'Câu 1', pts: 1,
      text: 'Nơi nào dưới đây là nơi mua bán hàng hoá?',
      opts: o4('Chợ, siêu thị, cửa hàng', 'Bệnh viện', 'Trường học', 'Công viên'), ans: 'A',
      why: 'Chợ, siêu thị, cửa hàng là nơi diễn ra việc mua bán hàng hoá.' },
    { sec: 'Mua bán', name: 'Câu 2', pts: 1,
      text: 'Người đem hàng ra để bán gọi là gì?',
      opts: o4('Người mua', 'Người bán', 'Khách qua đường', 'Bác sĩ'), ans: 'B',
      why: 'Người đưa hàng hoá ra trao đổi lấy tiền là người bán.' },
    { sec: 'Mua bán', name: 'Câu 3', pts: 1,
      text: 'Người trả tiền để lấy hàng gọi là gì?',
      opts: o4('Người bán', 'Người mua', 'Người trồng cây', 'Người lái xe'), ans: 'B',
      why: 'Người bỏ tiền ra để có hàng là người mua.' },
    { sec: 'Mua bán', name: 'Câu 4', pts: 1,
      text: 'Ở siêu thị, thực phẩm tươi như thịt, cá thường được bảo quản ở đâu?',
      opts: o4('Ngoài nắng', 'Trong tủ đông, tủ mát', 'Dưới sàn nhà', 'Trên nóc nhà'), ans: 'B',
      why: 'Thịt, cá cần để trong tủ đông/tủ mát cho tươi, không bị hỏng.' },
    { sec: 'Mua bán', name: 'Câu 5', pts: 1,
      text: 'Khi mua đồ ăn đóng gói, em nên xem thông tin gì trên bao bì?',
      opts: o4('Hạn sử dụng', 'Màu của túi bóng', 'Độ nặng của kệ hàng', 'Tên người bán'), ans: 'A',
      why: 'Cần xem hạn sử dụng để không mua phải đồ đã hết hạn, hỏng.' },
    { sec: 'Mua bán', name: 'Câu 6', pts: 1,
      text: 'Đi chợ, siêu thị nên mang theo gì để bảo vệ môi trường?',
      opts: o4('Túi (làn) đựng dùng nhiều lần', 'Thật nhiều túi ni lông', 'Xả rác cho vui', 'Không cần mang gì'), ans: 'A',
      why: 'Mang làn, túi dùng nhiều lần giúp giảm rác túi ni lông, bảo vệ môi trường.' },
    { sec: 'Mua bán', name: 'Câu 7', pts: 1,
      text: 'Khi được bố mẹ nhờ mua hàng, em nên làm gì?',
      opts: o4('Hỏi giá, trả đúng tiền, giữ hàng cẩn thận', 'Cầm hàng bỏ chạy', 'Lấy thêm đồ không trả tiền', 'Mua bừa cho xong'), ans: 'A',
      why: 'Mua bán cần trung thực: hỏi giá, trả đúng tiền và giữ hàng cẩn thận.' },
    { sec: 'Mua bán', name: 'Câu 8', pts: 1,
      text: 'Hành vi nào là KHÔNG trung thực khi mua bán?',
      opts: o4('Trả đủ tiền', 'Lấy hàng mà không trả tiền', 'Xếp hàng chờ tính tiền', 'Cảm ơn người bán'), ans: 'B',
      why: 'Lấy hàng không trả tiền là lấy trộm, không trung thực.' },
    { sec: 'Mua bán', name: 'Câu 9', pts: 1,
      text: 'Hàng hoá được làm ra từ đâu?',
      opts: o4('Từ công sức lao động của con người', 'Tự nhiên có sẵn không ai làm', 'Rơi từ trên trời', 'Mọc lên trong đêm'), ans: 'A',
      why: 'Hàng hoá do con người trồng trọt, chăn nuôi, sản xuất ra.' },
    { sec: 'Mua bán', name: 'Câu 10', pts: 1,
      text: 'Vì sao ta phải trân trọng hàng hoá, không lãng phí?',
      opts: o4('Vì đó là công sức lao động của nhiều người', 'Vì hàng hoá tự nhiên có', 'Vì mua rất rẻ', 'Không cần trân trọng'), ans: 'A',
      why: 'Mỗi món hàng đều chứa công sức lao động nên cần trân trọng, tránh lãng phí.' },
  ],
},

/* ═══════════ ĐỀ 5 — PHƯƠNG TIỆN VÀ AN TOÀN GIAO THÔNG ═══════════ */
{
  id: 5205, title: 'Đề 5 · Phương tiện và an toàn giao thông', time: 15,
  questions: [
    { sec: 'Giao thông', name: 'Câu 1', pts: 1,
      text: 'Phương tiện nào đi trên đường bộ?',
      opts: o4('Ô tô, xe máy, xe đạp', 'Tàu thuỷ', 'Máy bay', 'Ca nô'), ans: 'A',
      why: 'Ô tô, xe máy, xe đạp là phương tiện giao thông đường bộ.' },
    { sec: 'Giao thông', name: 'Câu 2', pts: 1,
      text: 'Phương tiện nào đi trên mặt nước?',
      opts: o4('Tàu hoả', 'Thuyền, tàu thuỷ, ca nô', 'Ô tô', 'Xe đạp'), ans: 'B',
      why: 'Thuyền, tàu thuỷ, ca nô là phương tiện giao thông đường thuỷ.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Phương tiện nào bay trên bầu trời?',
      opts: o4('Máy bay', 'Xe buýt', 'Tàu hoả', 'Xích lô'), ans: 'A',
      why: 'Máy bay là phương tiện giao thông đường hàng không.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Tàu hoả chạy trên loại đường nào?',
      opts: o4('Đường sông', 'Đường sắt (đường ray)', 'Đường hàng không', 'Đường mòn'), ans: 'B',
      why: 'Tàu hoả chạy trên đường sắt (đường ray).' },
    { sec: 'Giao thông', name: 'Câu 5', pts: 1,
      text: 'Khi ngồi trên ô tô, em nên làm gì cho an toàn?',
      opts: o4('Thắt dây an toàn, ngồi yên', 'Thò đầu, thò tay ra ngoài cửa', 'Đứng lên ghế', 'Mở cửa khi xe đang chạy'), ans: 'A',
      why: 'Ngồi ô tô phải thắt dây an toàn, ngồi yên, không thò đầu tay ra ngoài.' },
    { sec: 'Giao thông', name: 'Câu 6', pts: 1,
      text: 'Khi đi thuyền, đi đò qua sông, em phải làm gì?',
      opts: o4('Mặc áo phao, ngồi yên', 'Đứng nghiêng nhoài ra mép thuyền', 'Nghịch nước dưới sông', 'Chạy nhảy trên thuyền'), ans: 'A',
      why: 'Đi thuyền phải mặc áo phao và ngồi yên để không bị ngã xuống nước.' },
    { sec: 'Giao thông', name: 'Câu 7', pts: 1,
      text: 'Khi đi bộ trên đường không có vỉa hè, em nên đi thế nào?',
      opts: o4('Đi sát mép đường bên phải', 'Đi giữa lòng đường', 'Đi hàng ngang chắn đường', 'Vừa đi vừa đùa giỡn'), ans: 'A',
      why: 'Không có vỉa hè thì đi sát lề bên phải, đi hàng một cho an toàn.' },
    { sec: 'Giao thông', name: 'Câu 8', pts: 1,
      text: 'Việc nào là chấp hành đúng luật giao thông?',
      opts: o4('Dừng lại khi đèn đỏ, đi khi đèn xanh', 'Vượt đèn đỏ', 'Đi ngược chiều', 'Đùa nghịch trên đường'), ans: 'A',
      why: 'Chấp hành đèn tín hiệu (đỏ dừng, xanh đi) là đúng luật giao thông.' },
    { sec: 'Giao thông', name: 'Câu 9', pts: 1,
      text: 'Vì sao khi đi xe máy phải đội mũ bảo hiểm?',
      opts: o4('Để bảo vệ đầu khi có va chạm', 'Để làm đẹp', 'Để che mưa nắng cho vui', 'Không có lí do gì'), ans: 'A',
      why: 'Mũ bảo hiểm bảo vệ đầu, giảm chấn thương khi xảy ra tai nạn.' },
    { sec: 'Giao thông', name: 'Câu 10', pts: 1,
      text: 'Phương tiện giao thông giúp con người điều gì?',
      opts: o4('Đi lại và vận chuyển hàng hoá nhanh hơn', 'Làm chậm mọi việc', 'Không có tác dụng gì', 'Chỉ để ngắm cho vui'), ans: 'A',
      why: 'Phương tiện giao thông giúp đi lại và chở hàng nhanh, thuận tiện.' },
  ],
},

/* ═══════════ ĐỀ 6 — THỰC VẬT VÀ MÔI TRƯỜNG SỐNG ═══════════ */
{
  id: 5206, title: 'Đề 6 · Thực vật và nơi sống của chúng', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Cây nào sống ở dưới nước?',
      opts: o4('Cây bàng', 'Cây sen, cây bèo', 'Cây phượng', 'Cây xoài'), ans: 'B',
      why: 'Sen, bèo, súng là những cây sống dưới nước.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Cây nào sống trên cạn?',
      opts: o4('Cây bèo', 'Cây rong', 'Cây mít, cây phượng', 'Cây rau muống nước'), ans: 'C',
      why: 'Mít, phượng, bàng... là những cây sống trên cạn.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Cây xương rồng có thể sống được ở nơi nào?',
      opts: o4('Nơi khô hạn, ít nước như sa mạc', 'Dưới đáy biển sâu', 'Trong tủ lạnh', 'Trên mây'), ans: 'A',
      why: 'Xương rồng chịu hạn tốt, sống được ở vùng khô hạn, ít mưa.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Cây cối cần những gì để sống và lớn lên?',
      opts: o4('Nước, ánh sáng, không khí và chất trong đất', 'Chỉ cần bóng tối', 'Chỉ cần tiếng nhạc', 'Không cần gì cả'), ans: 'A',
      why: 'Cây cần nước, ánh sáng, không khí và chất dinh dưỡng trong đất.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Cây cho gỗ để đóng bàn ghế, làm nhà là loại cây gì?',
      opts: o4('Cây lấy gỗ (lim, xoan...)', 'Cây rau', 'Cây hoa', 'Cây cỏ'), ans: 'A',
      why: 'Cây lấy gỗ như lim, xoan, keo cho gỗ để làm nhà, đóng đồ.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Loại cây nào cho ta thức ăn hằng ngày?',
      opts: o4('Cây lúa, cây rau, cây ăn quả', 'Cây cột điện', 'Cây nhựa giả', 'Cỏ dại độc'), ans: 'A',
      why: 'Lúa, rau, cây ăn quả cho ta lương thực, thực phẩm.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Có loại cây nào gây hại cho con người không?',
      opts: o4('Có, một số cây có nhựa độc, quả độc', 'Không, mọi cây đều ăn được', 'Không có cây nào cả', 'Cây nào cũng độc'), ans: 'A',
      why: 'Một số cây có nhựa hoặc quả độc; không nên tự ý hái ăn cây lạ.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Rừng cây có vai trò gì với môi trường?',
      opts: o4('Giữ đất, giữ nước, cho không khí trong lành', 'Làm ô nhiễm không khí', 'Gây lũ lụt', 'Không có vai trò gì'), ans: 'A',
      why: 'Rừng giữ đất chống xói mòn, giữ nước và làm sạch không khí.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp bảo vệ cây xanh và rừng?',
      opts: o4('Trồng cây, chăm sóc, không chặt phá bừa bãi', 'Chặt cây bừa bãi', 'Đốt rừng', 'Bẻ cành hái lá lung tung'), ans: 'A',
      why: 'Trồng và chăm sóc cây, không chặt phá là cách bảo vệ cây xanh, rừng.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Vì sao chúng ta cần trồng nhiều cây xanh?',
      opts: o4('Cây cho bóng mát, không khí sạch, chống lũ', 'Cây làm bẩn thành phố', 'Cây gây nóng thêm', 'Trồng cây vô ích'), ans: 'A',
      why: 'Cây xanh cho bóng mát, làm sạch không khí và góp phần chống lũ lụt.' },
  ],
},

/* ═══════════ ĐỀ 7 — ĐỘNG VẬT VÀ MÔI TRƯỜNG SỐNG ═══════════ */
{
  id: 5207, title: 'Đề 7 · Động vật và nơi sống của chúng', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào sống dưới nước?',
      opts: o4('Con cá, con tôm, con cua', 'Con gà', 'Con mèo', 'Con chó'), ans: 'A',
      why: 'Cá, tôm, cua sống dưới nước.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con vật nào sống trên cạn?',
      opts: o4('Con trâu, con bò, con gà', 'Con cá chép', 'Con mực', 'Con sứa'), ans: 'A',
      why: 'Trâu, bò, gà, chó là những con vật sống trên cạn.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con vật nào vừa sống được ở nước, vừa sống trên cạn?',
      opts: o4('Con ếch', 'Con hổ', 'Con voi', 'Con đại bàng'), ans: 'A',
      why: 'Ếch sống được cả dưới nước và trên cạn (loài lưỡng cư).' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con vật nào biết bay và làm tổ trên cây?',
      opts: o4('Con chim', 'Con cá', 'Con trâu', 'Con rùa'), ans: 'A',
      why: 'Chim có cánh, biết bay và thường làm tổ trên cây.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con ong, con bướm giúp ích gì cho cây?',
      opts: o4('Giúp hoa thụ phấn để tạo quả', 'Ăn hết lá cây', 'Làm cây chết', 'Không có ích gì'), ans: 'A',
      why: 'Ong, bướm hút mật và giúp hoa thụ phấn để kết thành quả.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Con vật nào có ích vì bắt sâu bọ hại lúa?',
      opts: o4('Con ếch, con chim sâu', 'Con chuột', 'Con muỗi', 'Con gián'), ans: 'A',
      why: 'Ếch, chim sâu ăn sâu bọ, giúp bảo vệ mùa màng.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con vật nào có hại, hay phá hoại thóc lúa, đồ đạc?',
      opts: o4('Con chuột', 'Con mèo', 'Con bò', 'Con gà'), ans: 'A',
      why: 'Chuột cắn phá thóc lúa, đồ đạc và truyền bệnh.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con muỗi có hại vì điều gì?',
      opts: o4('Đốt người và truyền bệnh (sốt xuất huyết)', 'Cho ta trứng', 'Bắt chuột', 'Kéo cày'), ans: 'A',
      why: 'Muỗi đốt hút máu và truyền bệnh như sốt xuất huyết, sốt rét.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Để phòng muỗi đốt và diệt muỗi, ta nên làm gì?',
      opts: o4('Ngủ màn, dọn nơi nước đọng', 'Nuôi thêm muỗi', 'Để nước đọng khắp nơi', 'Vứt rác bừa bãi'), ans: 'A',
      why: 'Ngủ màn và dọn sạch nơi nước đọng (chỗ muỗi đẻ) giúp phòng và diệt muỗi.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp bảo vệ các con vật có ích?',
      opts: o4('Không săn bắt bừa bãi, giữ sạch môi trường sống', 'Bắt hết chim, ếch', 'Đốt rừng nơi chúng ở', 'Xả rác xuống sông'), ans: 'A',
      why: 'Không săn bắt bừa bãi và giữ sạch môi trường giúp bảo vệ động vật có ích.' },
  ],
},

/* ═══════════ ĐỀ 8 — CƠ QUAN VẬN ĐỘNG: XƯƠNG VÀ CƠ ═══════════ */
{
  id: 5208, title: 'Đề 8 · Cơ quan vận động (xương và cơ)', time: 15,
  questions: [
    { sec: 'Cơ thể', name: 'Câu 1', pts: 1,
      text: 'Cơ quan vận động của cơ thể gồm những gì?',
      opts: o4('Bộ xương và hệ cơ', 'Tim và phổi', 'Dạ dày và ruột', 'Mắt và tai'), ans: 'A',
      why: 'Cơ quan vận động gồm bộ xương và hệ cơ, giúp cơ thể cử động.' },
    { sec: 'Cơ thể', name: 'Câu 2', pts: 1,
      text: 'Bộ xương có vai trò gì với cơ thể?',
      opts: o4('Nâng đỡ và bảo vệ cơ thể', 'Giúp nhìn thấy', 'Giúp nghe', 'Giúp tiêu hoá'), ans: 'A',
      why: 'Bộ xương nâng đỡ cơ thể và bảo vệ các cơ quan bên trong (tim, não...).' },
    { sec: 'Cơ thể', name: 'Câu 3', pts: 1,
      text: 'Nhờ đâu mà tay, chân... cử động được?',
      opts: o4('Nhờ các cơ bám vào xương co và giãn', 'Nhờ mái tóc', 'Nhờ móng tay', 'Nhờ làn da'), ans: 'A',
      why: 'Cơ bám vào xương, khi cơ co và giãn thì xương cử động theo.' },
    { sec: 'Cơ thể', name: 'Câu 4', pts: 1,
      text: 'Nơi hai xương nối với nhau, giúp gập, duỗi được gọi là gì?',
      opts: o4('Khớp xương', 'Sợi tóc', 'Cái răng', 'Móng chân'), ans: 'A',
      why: 'Khớp là chỗ nối hai xương, giúp tay chân co, duỗi, xoay được.' },
    { sec: 'Cơ thể', name: 'Câu 5', pts: 1,
      text: 'Hộp sọ (xương đầu) bảo vệ cơ quan quan trọng nào?',
      opts: o4('Bộ não', 'Bàn chân', 'Ngón tay', 'Lá gan'), ans: 'A',
      why: 'Hộp sọ là xương cứng bao bọc, bảo vệ bộ não.' },
    { sec: 'Cơ thể', name: 'Câu 6', pts: 1,
      text: 'Lồng ngực (xương sườn) bảo vệ cơ quan nào?',
      opts: o4('Tim và phổi', 'Đôi mắt', 'Bàn tay', 'Lỗ tai'), ans: 'A',
      why: 'Xương sườn tạo thành lồng ngực bảo vệ tim và phổi.' },
    { sec: 'Cơ thể', name: 'Câu 7', pts: 1,
      text: 'Cột sống (xương sống) chạy dọc theo phần nào của cơ thể?',
      opts: o4('Dọc theo lưng', 'Trong bàn chân', 'Trong ngón tay', 'Trong lỗ mũi'), ans: 'A',
      why: 'Cột sống chạy dọc lưng, giúp cơ thể đứng thẳng.' },
    { sec: 'Cơ thể', name: 'Câu 8', pts: 1,
      text: 'Khi em co cánh tay lại, bắp tay (cơ) sẽ thế nào?',
      opts: o4('Co lại, cứng và nổi lên', 'Biến mất', 'Chảy nước', 'Không thay đổi gì'), ans: 'A',
      why: 'Khi co tay, cơ bắp tay co lại nên cứng và nổi lên.' },
    { sec: 'Cơ thể', name: 'Câu 9', pts: 1,
      text: 'Cơ thể cử động được (đi, chạy, cầm nắm) là nhờ sự phối hợp của những gì?',
      opts: o4('Xương, cơ và khớp', 'Chỉ có tóc', 'Chỉ có da', 'Chỉ có răng'), ans: 'A',
      why: 'Xương, cơ và khớp phối hợp nhịp nhàng giúp cơ thể vận động.' },
    { sec: 'Cơ thể', name: 'Câu 10', pts: 1,
      text: 'Nếu không vận động, ít tập thể dục thì xương và cơ sẽ thế nào?',
      opts: o4('Yếu và kém dẻo dai', 'Càng khoẻ hơn', 'To ra rất nhanh', 'Không ảnh hưởng gì'), ans: 'A',
      why: 'Lười vận động khiến xương, cơ yếu đi; tập luyện giúp chúng chắc khoẻ.' },
  ],
},

/* ═══════════ ĐỀ 9 — CHĂM SÓC VÀ BẢO VỆ CƠ QUAN VẬN ĐỘNG ═══════════ */
{
  id: 5209, title: 'Đề 9 · Bảo vệ xương và cơ', time: 15,
  questions: [
    { sec: 'Sức khoẻ', name: 'Câu 1', pts: 1,
      text: 'Tư thế ngồi học đúng giúp bảo vệ điều gì?',
      opts: o4('Cột sống (không bị cong vẹo)', 'Đôi tai', 'Cái mũi', 'Móng tay'), ans: 'A',
      why: 'Ngồi học ngay ngắn giúp cột sống thẳng, không bị cong vẹo.' },
    { sec: 'Sức khoẻ', name: 'Câu 2', pts: 1,
      text: 'Nên đeo cặp sách thế nào cho đúng?',
      opts: o4('Đeo đều hai vai, không quá nặng', 'Chỉ đeo lệch một bên vai', 'Nhồi thật nhiều sách cho nặng', 'Kéo lê dưới đất'), ans: 'A',
      why: 'Đeo cặp đều hai vai và không quá nặng giúp xương sống không bị lệch, vẹo.' },
    { sec: 'Sức khoẻ', name: 'Câu 3', pts: 1,
      text: 'Thức ăn nào giúp xương chắc khoẻ?',
      opts: o4('Sữa, tôm, cua, cá nhỏ (giàu canxi)', 'Chỉ ăn kẹo', 'Chỉ uống nước ngọt', 'Nhịn ăn'), ans: 'A',
      why: 'Sữa, tôm, cua, cá nhỏ giàu canxi giúp xương chắc khoẻ.' },
    { sec: 'Sức khoẻ', name: 'Câu 4', pts: 1,
      text: 'Việc nào giúp xương và cơ khoẻ, dẻo dai?',
      opts: o4('Tập thể dục, chơi thể thao đều đặn', 'Ngồi lì xem điện thoại cả ngày', 'Không bao giờ vận động', 'Thức khuya'), ans: 'A',
      why: 'Tập thể dục, chơi thể thao đều đặn giúp xương cơ chắc khoẻ, dẻo dai.' },
    { sec: 'Sức khoẻ', name: 'Câu 5', pts: 1,
      text: 'Để tránh gãy xương, khi vui chơi em nên thế nào?',
      opts: o4('Chơi cẩn thận, không leo trèo nơi nguy hiểm', 'Leo lên cao rồi nhảy xuống', 'Xô đẩy nhau', 'Chạy nhảy nơi trơn trượt'), ans: 'A',
      why: 'Chơi cẩn thận, tránh leo trèo, xô đẩy giúp phòng ngã gãy xương.' },
    { sec: 'Sức khoẻ', name: 'Câu 6', pts: 1,
      text: 'Bạn mang vác vật quá nặng so với sức mình có thể bị gì?',
      opts: o4('Đau lưng, hại cột sống', 'Cao lớn nhanh hơn', 'Học giỏi hơn', 'Không sao cả'), ans: 'A',
      why: 'Mang vác quá nặng gây đau lưng và có thể làm cong, hại cột sống.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Ngồi học nên chọn nơi có ánh sáng thế nào?',
      opts: o4('Đủ ánh sáng, không quá tối', 'Trong bóng tối', 'Chỉ dùng ánh nến le lói', 'Không cần ánh sáng'), ans: 'A',
      why: 'Ngồi học nơi đủ sáng để giữ tư thế tốt và bảo vệ cả mắt.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Trước khi chơi thể thao (chạy, đá bóng), nên làm gì?',
      opts: o4('Khởi động làm nóng người', 'Ăn thật no rồi chạy ngay', 'Ngồi im rồi chạy đột ngột', 'Không cần chuẩn bị'), ans: 'A',
      why: 'Khởi động giúp cơ, khớp dẻo, tránh bị chuột rút, chấn thương.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Khi bị ngã đau tay, chân, sưng nề, em nên làm gì?',
      opts: o4('Báo người lớn, đến cơ sở y tế nếu cần', 'Tự bẻ nắn thật mạnh', 'Cố chạy nhảy tiếp', 'Giấu không cho ai biết'), ans: 'A',
      why: 'Bị chấn thương nên báo người lớn và đi khám để được xử lí đúng.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Thói quen nào có hại cho cơ quan vận động?',
      opts: o4('Ngồi vẹo, nằm sấp học bài, lười vận động', 'Ngồi thẳng lưng', 'Tập thể dục mỗi ngày', 'Ăn đủ chất'), ans: 'A',
      why: 'Ngồi vẹo, nằm học và lười vận động làm xương cơ yếu, dễ cong vẹo cột sống.' },
  ],
},

/* ═══════════ ĐỀ 10 — CÁC MÙA TRONG NĂM & ÔN TẬP ═══════════ */
{
  id: 5210, title: 'Đề 10 · Các mùa trong năm và ôn tập', time: 15,
  questions: [
    { sec: 'Các mùa', name: 'Câu 1', pts: 1,
      text: 'Miền Bắc nước ta thường có mấy mùa trong năm?',
      opts: o4('Hai mùa', 'Ba mùa', 'Bốn mùa (xuân, hạ, thu, đông)', 'Năm mùa'), ans: 'C',
      why: 'Miền Bắc có bốn mùa rõ rệt: xuân, hạ, thu, đông.' },
    { sec: 'Các mùa', name: 'Câu 2', pts: 1,
      text: 'Miền Nam nước ta thường có mấy mùa?',
      opts: o4('Hai mùa: mùa mưa và mùa khô', 'Bốn mùa', 'Sáu mùa', 'Không có mùa nào'), ans: 'A',
      why: 'Miền Nam có hai mùa: mùa mưa và mùa khô.' },
    { sec: 'Các mùa', name: 'Câu 3', pts: 1,
      text: 'Mùa nào thường nóng nhất trong năm ở miền Bắc?',
      opts: o4('Mùa xuân', 'Mùa hạ (mùa hè)', 'Mùa thu', 'Mùa đông'), ans: 'B',
      why: 'Mùa hạ (mùa hè) là mùa nóng nhất.' },
    { sec: 'Các mùa', name: 'Câu 4', pts: 1,
      text: 'Mùa nào thường lạnh nhất ở miền Bắc?',
      opts: o4('Mùa xuân', 'Mùa hạ', 'Mùa thu', 'Mùa đông'), ans: 'D',
      why: 'Mùa đông là mùa lạnh nhất, cần mặc ấm.' },
    { sec: 'Các mùa', name: 'Câu 5', pts: 1,
      text: 'Mùa xuân thường có đặc điểm gì?',
      opts: o4('Ấm áp, cây cối đâm chồi nảy lộc', 'Rét buốt, cây trụi lá', 'Nóng bức nhất', 'Lá vàng rụng nhiều'), ans: 'A',
      why: 'Mùa xuân ấm áp, cây cối đâm chồi, đơm hoa.' },
    { sec: 'Các mùa', name: 'Câu 6', pts: 1,
      text: 'Vào mùa đông giá lạnh, em nên ăn mặc thế nào?',
      opts: o4('Mặc áo ấm, đội mũ len, đi tất', 'Mặc áo cộc, quần đùi', 'Cởi trần', 'Đi chân đất'), ans: 'A',
      why: 'Mùa đông cần mặc ấm để giữ sức khoẻ, tránh cảm lạnh.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Gia đình có ông bà, bố mẹ và các con là gia đình mấy thế hệ?',
      opts: o4('Một', 'Hai', 'Ba', 'Bốn'), ans: 'C',
      why: 'Ông bà — bố mẹ — các con là ba thế hệ.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Cơ quan vận động của cơ thể gồm những gì?',
      opts: o4('Xương và cơ', 'Tim và gan', 'Mắt và tai', 'Dạ dày và ruột'), ans: 'A',
      why: 'Cơ quan vận động gồm bộ xương và hệ cơ.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Máy bay là phương tiện giao thông đường nào?',
      opts: o4('Đường bộ', 'Đường thuỷ', 'Đường hàng không', 'Đường sắt'), ans: 'C',
      why: 'Máy bay bay trên trời — phương tiện giao thông đường hàng không.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Việc nào KHÔNG nên làm để bảo vệ môi trường?',
      opts: o4('Vứt rác bừa bãi xuống sông', 'Trồng cây xanh', 'Bỏ rác đúng nơi', 'Dùng làn đi chợ'), ans: 'A',
      why: 'Vứt rác xuống sông làm ô nhiễm nguồn nước, hại môi trường.' },
  ],
},

];

SUBJECTS.push({
  id: 'tnxh2', name: 'Tự nhiên & Xã hội', short: 'TN&XH 2', icon: '🌍', grade: 2,
  exams: TNXH2_EXAMS, ready: true,
  heroTitle: 'Tự nhiên và Xã hội lớp 2 — gia đình, nghề nghiệp, giao thông, cây con và cơ quan vận động',
  heroMeta: '📚 10 đề &nbsp;•&nbsp; 100 câu &nbsp;•&nbsp; ⏱ 15 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
