// Dữ liệu bộ đề — trích nguyên văn từ "BO_DE_Toan_CK2__Lop_2" (Toán 2 — Cuối học kì 2)
// Mỗi câu: sec (phần), name, pts (điểm), text, img/imgs, opts, ans, why (giải thích)

const A = 'assets/';
const DS = [{ k: 'A', t: 'Đúng' }, { k: 'B', t: 'Sai' }];
const KN = [{ k: 'A', t: 'Chắc chắn' }, { k: 'B', t: 'Có thể' }, { k: 'C', t: 'Không thể' }];
const o4 = (a, b, c, d) => [{ k: 'A', t: a }, { k: 'B', t: b }, { k: 'C', t: c }, { k: 'D', t: d }];
const o3 = (a, b, c) => [{ k: 'A', t: a }, { k: 'B', t: b }, { k: 'C', t: c }];

const CAL_T5 = `<table class="cal"><tr><th colspan="7">Tháng 5</th></tr>
<tr><td class="h">Thứ hai</td><td class="h">Thứ ba</td><td class="h">Thứ tư</td><td class="h">Thứ năm</td><td class="h">Thứ sáu</td><td class="h">Thứ bảy</td><td class="h">Chủ nhật</td></tr>
<tr><td></td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td></tr>
<tr><td>7</td><td>8</td><td>9</td><td>10</td><td>11</td><td>12</td><td>13</td></tr>
<tr><td>14</td><td class="q">15</td><td>16</td><td>17</td><td>18</td><td>19</td><td>20</td></tr>
<tr><td>?</td><td class="q">?</td><td>23</td><td>24</td><td>25</td><td>26</td><td>27</td></tr>
<tr><td>28</td><td>?</td><td>?</td><td></td><td></td><td></td><td></td></tr></table>`;

const EXAMS = [
/* ================================================== ĐỀ 1 ================================================== */
{
  id: 1, title: 'Đề 1', time: 35,
  questions: [
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 1', pts: 0.5,
      text: 'Số gồm 9 trăm, 7 chục được viết là:',
      opts: o4('970', '97', '907', '790'), ans: 'A',
      why: '9 trăm và 7 chục viết là 970.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 2', pts: 0.5,
      text: 'Các số: 672 ; 805 ; 599 ; 689 được sắp xếp theo thứ tự từ lớn đến bé là:',
      opts: o4('805 ; 689 ; 599 ; 672', '805 ; 599 ; 689 ; 672', '805 ; 689 ; 672 ; 599', '599 ; 672 ; 682 ; 805'), ans: 'C',
      why: 'So sánh: 805 > 689 > 672 > 599.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 3', pts: 0.5,
      text: 'Tổng của 255 và 204 là:',
      opts: o4('459', '671', '771', '883'), ans: 'A',
      why: '255 + 204 = 459.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 4', pts: 0.5,
      text: 'Số thích hợp điền vào chỗ trống là:', img: A + 'd1c4.svg',
      opts: o4('8 và 41', '15 và 50', '15 và 40', '8 và 42'), ans: 'B',
      why: '5 × 3 = 15; 15 thêm 35 được 15 + 35 = 50.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 5', pts: 0.5,
      text: 'Kết quả của phép tính: 2 × 7 = ?',
      opts: o4('3', '25', '11', '14'), ans: 'D',
      why: '2 × 7 = 14.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 6', pts: 0.5,
      text: 'Cầu Vĩnh Tuy dài khoảng:', img: A + 'd1c6.png',
      opts: o4('3cm', '3dm', '3m', '3km'), ans: 'D',
      why: 'Cây cầu rất dài nên dùng đơn vị ki-lô-mét: khoảng 3km.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 7', pts: 0.5,
      text: 'Ở đằng xa chúng ta nhìn thấy đường viền của một tòa lâu đài. Hình nào dưới đây KHÔNG thể là một phần của tòa lâu đài?', img: A + 'd1c7.svg',
      opts: [{ k: 'A', img: A + 'd1c7a.svg' }, { k: 'B', img: A + 'd1c7b.svg' }, { k: 'C', img: A + 'd1c7c.svg' }, { k: 'D', img: A + 'd1c7d.svg' }], ans: 'C',
      why: 'Trên đường viền lâu đài, các vòm tròn luôn nối liền nhau tại một điểm lõm; hình C lại có hai vòm tròn cách nhau bởi một đoạn thẳng nằm ngang (khe chữ nhật) nên không thể là một phần của tòa lâu đài.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 8', pts: 0.5,
      text: 'Bố chở anh em Minh đi chơi ở trung tâm thương mại Times City. Ba bố con bắt đầu đi lúc 18 giờ 15 phút và đến Times City lúc 18 giờ 45 phút. Vậy thời gian ba bố con đi từ nhà đến trung tâm thương mại là:', img: A + 'd1c8.png',
      opts: o4('15 phút', '45 phút', '30 phút', '60 phút'), ans: 'C',
      why: 'Từ 18 giờ 15 phút đến 18 giờ 45 phút là 45 − 15 = 30 phút.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1a', pts: 0.25,
      text: 'Đặt tính rồi tính: 727 − 135 = ?',
      opts: o4('592', '612', '582', '692'), ans: 'A', why: '727 − 135 = 592.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1b', pts: 0.25,
      text: 'Đặt tính rồi tính: 25 + 281 = ?',
      opts: o4('306', '316', '206', '531'), ans: 'A', why: '25 + 281 = 306.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1c', pts: 0.25,
      text: 'Đặt tính rồi tính: 173 + 764 = ?',
      opts: o4('937', '837', '947', '927'), ans: 'A', why: '173 + 764 = 937.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1d', pts: 0.25,
      text: 'Đặt tính rồi tính: 255 − 94 = ?',
      opts: o4('161', '151', '171', '349'), ans: 'A', why: '255 − 94 = 161.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2', pts: 1,
      text: 'Có 15 chiếc kẹo, chia đều cho ba bạn. Ta có phép chia:', img: A + 'd1b2.png',
      opts: o4('15 : 3 = 5', '15 : 5 = 3', '12 : 3 = 4', '15 − 3 = 12'), ans: 'A',
      why: '15 chiếc kẹo chia đều cho 3 bạn: 15 : 3 = 5 (mỗi bạn 5 chiếc).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3a', pts: 0.33,
      text: 'Quan sát biểu đồ tranh. Bạn Trường câu được bao nhiêu con cá?', img: A + 'd1b3.png',
      opts: o4('2 con cá', '1 con cá', '3 con cá', '4 con cá'), ans: 'A',
      why: 'Hàng của bạn Trường có 2 con cá.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3b', pts: 0.33,
      text: 'Bạn nào câu được nhiều cá nhất? Bạn nào câu được ít cá nhất?', img: A + 'd1b3.png',
      opts: o4('Phương nhiều nhất – Tùng ít nhất', 'Trường nhiều nhất – Tùng ít nhất', 'Phương nhiều nhất – Trường ít nhất', 'Tùng nhiều nhất – Phương ít nhất'), ans: 'A',
      why: 'Phương câu được 3 con (nhiều nhất), Tùng câu được 1 con (ít nhất).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3c', pts: 0.34,
      text: 'Ba bạn câu được tất cả bao nhiêu con cá?', img: A + 'd1b3.png',
      opts: o4('6 con cá', '5 con cá', '7 con cá', '8 con cá'), ans: 'A',
      why: '2 + 1 + 3 = 6 con cá.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4', pts: 2,
      text: 'Nhân dịp 30/4 – 1/5, cửa hàng Thế giới di động tổ chức chương trình siêu khuyến mãi. Hai mặt hàng bán chạy nhất đó là điều hòa và tủ lạnh. Biết cửa hàng bán được 180 chiếc tủ lạnh và số điều hòa bán được nhiều hơn số tủ lạnh là 120 chiếc. Hỏi cửa hàng bán được bao nhiêu chiếc điều hòa?', img: A + 'd1b4.png',
      opts: o4('300 chiếc', '60 chiếc', '280 chiếc', '320 chiếc'), ans: 'A',
      why: 'Số điều hòa: 180 + 120 = 300 (chiếc).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5a', pts: 0.5,
      text: 'Điền số thích hợp vào chỗ trống (dấu ? ở dòng cuối):', img: A + 'd1b5a.png',
      opts: o4('19', '17', '18', '16'), ans: 'A',
      why: 'Cá vàng = 9 : 3 = 3; cá chép = 13 − 3 = 10; cá xanh = 10 − 4 = 6. Vậy 6 + 3 + 10 = 19.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5b', pts: 0.5,
      text: 'Hình bên có bao nhiêu khối trụ, khối cầu, khối hộp chữ nhật?', img: A + 'd1b5b.png',
      opts: o4('3 khối trụ, 3 khối cầu, 2 khối hộp chữ nhật', '2 khối trụ, 3 khối cầu, 3 khối hộp chữ nhật', '3 khối trụ, 2 khối cầu, 3 khối hộp chữ nhật', '2 khối trụ, 2 khối cầu, 3 khối hộp chữ nhật'), ans: 'A',
      why: '3 khối trụ màu đỏ, 3 khối cầu màu xanh, 2 khối hộp chữ nhật màu xanh lá.' },
  ],
},
/* ================================================== ĐỀ 2 ================================================== */
{
  id: 2, title: 'Đề 2', time: 35,
  questions: [
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 1', pts: 0.5,
      text: 'Số gồm 5 trăm, 4 chục, 3 đơn vị được viết là:',
      opts: o4('345', '543', '534', '453'), ans: 'B', why: '5 trăm, 4 chục, 3 đơn vị viết là 543.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 2', pts: 0.5,
      text: 'Thừa số trong phép nhân 5 × 3 = 15 là:',
      opts: o4('5', '3', '15', '5 và 3'), ans: 'D', why: 'Trong phép nhân 5 × 3 = 15, cả 5 và 3 đều là thừa số.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 3', pts: 0.5,
      text: 'Số lớn nhất trong các số 605; 125; 202; 520 là:',
      opts: o4('605', '125', '202', '520'), ans: 'A', why: '605 > 520 > 202 > 125.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 4', pts: 0.5,
      text: 'Kết quả của phép tính 2 × 9 là:',
      opts: o4('18', '17', '29', '19'), ans: 'A', why: '2 × 9 = 18.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 5', pts: 0.5,
      text: 'Xem lịch và cho biết, nếu thứ ba tuần này của tháng 5 là ngày 15 thì thứ ba tuần sau của tháng 5 sẽ là ngày:', html: CAL_T5,
      opts: o4('1', '8', '21', '22'), ans: 'D', why: 'Một tuần có 7 ngày: 15 + 7 = 22.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 6', pts: 0.5,
      text: 'Bạn Minh đi đá bóng lúc 16 giờ 10 phút và về nhà lúc 16 giờ 45 phút. Vậy thời gian bạn Minh đi đá bóng là:', img: A + 'd2c6.png',
      opts: o4('30 phút', '35 phút', '45 phút', '55 phút'), ans: 'B',
      why: '45 − 10 = 35 phút.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 7', pts: 0.5,
      text: '1km …… 300m + 600m. Dấu thích hợp điền vào chỗ chấm là:',
      opts: o4('>', '=', '<', 'Không điền được dấu'), ans: 'A',
      why: '300m + 600m = 900m; 1km = 1000m > 900m.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 8', pts: 0.5,
      text: 'Một hình vuông bị cắt ra dọc theo các đường kẻ. Hỏi hình nào dưới đây KHÔNG thể có được bằng cách cắt trên?', img: A + 'd2c8sq.svg',
      opts: [{ k: 'A', img: A + 'd2c8a.svg' }, { k: 'B', img: A + 'd2c8b.svg' }, { k: 'C', img: A + 'd2c8c.svg' }, { k: 'D', img: A + 'd2c8d.svg' }], ans: 'C',
      why: 'Trong hình vuông đã cắt không có mảnh nào hình chữ U như hình C.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1a', pts: 0.25,
      text: 'Đặt tính rồi tính: 80 + 132 = ?',
      opts: o4('212', '202', '222', '132'), ans: 'A', why: '80 + 132 = 212.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1b', pts: 0.25,
      text: 'Đặt tính rồi tính: 225 + 156 = ?',
      opts: o4('381', '371', '391', '369'), ans: 'A', why: '225 + 156 = 381.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1c', pts: 0.25,
      text: 'Đặt tính rồi tính: 191 − 77 = ?',
      opts: o4('114', '124', '104', '268'), ans: 'A', why: '191 − 77 = 114.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1d', pts: 0.25,
      text: 'Đặt tính rồi tính: 738 − 291 = ?',
      opts: o4('447', '457', '437', '529'), ans: 'A', why: '738 − 291 = 447.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2a', pts: 0.5,
      text: 'Tính: 5 × 6 = ?',
      opts: o4('30', '25', '35', '11'), ans: 'A', why: '5 × 6 = 30.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2b', pts: 0.5,
      text: 'Tính: 14m : 2 = ?',
      opts: o4('7m', '7', '6m', '12m'), ans: 'A', why: '14m : 2 = 7m (nhớ kèm đơn vị mét).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3a', pts: 0.33,
      text: 'Quan sát biểu đồ tranh. Môn thể thao được nhiều bạn yêu thích nhất là:', img: A + 'd2b3.png',
      opts: o4('Bóng đá', 'Bóng rổ', 'Bơi lội', 'Đá cầu'), ans: 'A',
      why: 'Bóng đá có 8 bạn thích — nhiều nhất.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3b', pts: 0.33,
      text: 'Môn bơi lội được bao nhiêu bạn yêu thích?', img: A + 'd2b3.png',
      opts: o4('4 bạn', '5 bạn', '3 bạn', '6 bạn'), ans: 'A',
      why: 'Hàng bơi lội có 4 mặt cười.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3c', pts: 0.34,
      text: 'Môn bóng rổ có số lượng bạn yêu thích nhiều hơn môn đá cầu là bao nhiêu bạn?', img: A + 'd2b3.png',
      opts: o4('5 bạn', '6 bạn', '4 bạn', '3 bạn'), ans: 'A',
      why: 'Bóng rổ 7 bạn, đá cầu 2 bạn: 7 − 2 = 5 bạn.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4', pts: 2,
      text: 'Để chuẩn bị cho buổi tiệc ngày 8/3, nhà hàng Nam Sơn cắm các bình hoa hồng và bình hoa tulip trang trí. Biết số bình hoa tulip là 240 bình và số bình hoa hồng nhiều hơn số bình hoa tulip là 180 bình. Hỏi nhà hàng đã cắm bao nhiêu bình hoa hồng?', img: A + 'd2b4.png',
      opts: o4('420 bình', '60 bình', '400 bình', '240 bình'), ans: 'A',
      why: 'Số bình hoa hồng: 240 + 180 = 420 (bình).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5a', pts: 0.5,
      text: 'Điền số thích hợp vào chỗ trống (dấu ? ở dòng cuối):', img: A + 'd2b5a.png',
      opts: o4('19', '17', '18', '16'), ans: 'A',
      why: 'Chuối = 9 : 3 = 3; dâu = 13 − 3 = 10; lê = 10 − 4 = 6. Vậy 6 + 3 + 10 = 19.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5b', pts: 0.5,
      text: 'Tích của 2 số ghi trên khối lập phương và khối hộp chữ nhật là bao nhiêu? Thương của số ghi trên khối cầu và số ghi trên khối trụ là bao nhiêu?', img: A + 'd2b5b.png',
      opts: o4('Tích là 45 ; thương là 9', 'Tích là 45 ; thương là 36', 'Tích là 14 ; thương là 9', 'Tích là 40 ; thương là 9'), ans: 'A',
      why: 'Khối lập phương ghi 5, khối hộp chữ nhật ghi 9: 5 × 9 = 45. Khối cầu ghi 18, khối trụ ghi 2: 18 : 2 = 9.' },
  ],
},
/* ================================================== ĐỀ 3 ================================================== */
{
  id: 3, title: 'Đề 3', time: 35,
  questions: [
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 1', pts: 0.5,
      text: 'Số gồm 5 trăm, 1 chục được viết là:',
      opts: o4('510', '501', '150', '105'), ans: 'A', why: '5 trăm và 1 chục viết là 510.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 2', pts: 0.5,
      text: 'Trong phép tính 21 + 37, số 21 đứng ở vị trí:',
      opts: o4('Tổng', 'Số hạng', 'Thừa số', 'Tích'), ans: 'B',
      why: 'Trong phép cộng, các số đem cộng gọi là số hạng.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 3', pts: 0.5,
      text: 'Điền số thích hợp vào chỗ trống:', img: A + 'd3c3.svg',
      opts: o4('650 ; 670 ; 680 ; 691', '650 ; 660 ; 670 ; 680', '650 ; 670 ; 680 ; 690', '650 ; 670 ; 680 ; 700'), ans: 'D',
      why: 'Dãy số tròn chục đếm thêm 10: 630, 640, 650, 660, 670, 680, 690, 700.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 4', pts: 0.5,
      text: 'Hãy giúp chú mèo tìm đường về nhà bằng cách thực hiện phép tính dưới đây (số điền vào ô cuối):', img: A + 'd3c4.png',
      opts: o4('23', '8', '4', '10'), ans: 'C',
      why: '15 bớt 7 còn 8; 8 chia 2 được 4.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 5', pts: 0.5,
      text: 'Trong một cuộc thi chạy ziczac, các chú chuột túi Mary, Norbert và Oscar nhảy như trong hình vẽ. Giả sử chúng nhảy với cùng tốc độ. Câu nào dưới đây là đúng?', img: A + 'd3c5.png',
      opts: o4('Mary và Oscar đến đích cùng lúc', 'Norbert về sớm nhất', 'Oscar về cuối cùng', 'Mary và Norbert đến đích cùng lúc'), ans: 'B',
      why: 'Đường của Norbert ngắn nhất nên Norbert về đích sớm nhất.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 6', pts: 0.5,
      text: 'Mỗi can đựng được 5l dầu ô liu. Hỏi 6 can như thế đựng được bao nhiêu lít dầu?',
      opts: o4('5l', '11l', '30l', '1l'), ans: 'C', why: '5 × 6 = 30 (lít).' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 7', pts: 0.5,
      text: 'Chiếc điện thoại thông minh iPhone 13 Pro Max dài khoảng:', img: A + 'd3c7.png',
      opts: o4('16cm', '16dm', '16m', '16km'), ans: 'A',
      why: 'Chiếc điện thoại dài khoảng 16 xăng-ti-mét.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 8', pts: 0.5,
      text: 'Trường của Anh Thư vào lớp lúc 8 giờ. Hôm nay Anh Thư vào lớp lúc 7 giờ 45 phút. Như vậy hôm nay:', img: A + 'd3c8.png',
      opts: o4('Thư vào lớp muộn 15 phút', 'Thư vào lớp sớm 15 phút', 'Thư vào lớp đúng giờ', 'Thư không vào lớp'), ans: 'B',
      why: '7 giờ 45 phút sớm hơn 8 giờ là 15 phút.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1a', pts: 0.25,
      text: 'Đặt tính rồi tính: 138 + 49 = ?',
      opts: o4('187', '177', '197', '89'), ans: 'A', why: '138 + 49 = 187.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1b', pts: 0.25,
      text: 'Đặt tính rồi tính: 431 + 282 = ?',
      opts: o4('713', '703', '723', '613'), ans: 'A', why: '431 + 282 = 713.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1c', pts: 0.25,
      text: 'Đặt tính rồi tính: 866 − 596 = ?',
      opts: o4('270', '370', '280', '260'), ans: 'A', why: '866 − 596 = 270.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1d', pts: 0.25,
      text: 'Đặt tính rồi tính: 555 − 238 = ?',
      opts: o4('317', '327', '307', '217'), ans: 'A', why: '555 − 238 = 317.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2', pts: 1,
      text: 'Quan sát tranh, viết số thích hợp vào chỗ chấm: Chuyến tàu hỏa đã chuyển được …….. kg hàng.', img: A + 'd3b2.png',
      opts: o4('662 kg', '652 kg', '562 kg', '672 kg'), ans: 'A',
      why: '200 + 355 + 107 = 662 (kg).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3a', pts: 0.25,
      text: 'Bạn Hùng lấy ra trong thùng đồ chơi một món đồ. Câu sau đúng hay sai: “Hùng chắc chắn lấy ra được chú gấu bông.”', img: A + 'd3b3.png',
      opts: DS, ans: 'B',
      why: 'Sai — trong thùng có nhiều loại đồ chơi nên không chắc chắn lấy được gấu bông.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3b', pts: 0.25,
      text: 'Câu sau đúng hay sai: “Hùng có thể lấy ra được quả bóng.”', img: A + 'd3b3.png',
      opts: DS, ans: 'A',
      why: 'Đúng — trong thùng có quả bóng nên có thể lấy được.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3c', pts: 0.25,
      text: 'Câu sau đúng hay sai: “Hùng có thể lấy ra được chú khủng long xanh.”', img: A + 'd3b3.png',
      opts: DS, ans: 'A',
      why: 'Đúng — trong thùng có chú khủng long màu xanh.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3d', pts: 0.25,
      text: 'Câu sau đúng hay sai: “Hùng không thể lấy ra được cái đàn.”', img: A + 'd3b3.png',
      opts: DS, ans: 'B',
      why: 'Sai — trong thùng có cây đàn (phía sau gấu bông) nên vẫn có thể lấy được.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4', pts: 2,
      text: 'Cửa hàng bánh ngọt Fresh Garden trong một tuần bán được 230 chiếc bánh sừng bò. Số bánh sừng bò cửa hàng bán được nhiều hơn số bánh nho là 29 chiếc. Hỏi cửa hàng bánh ngọt bán được bao nhiêu chiếc bánh nho trong tuần?', img: A + 'd3b4.png',
      opts: o4('201 chiếc', '259 chiếc', '211 chiếc', '229 chiếc'), ans: 'A',
      why: 'Số bánh nho: 230 − 29 = 201 (chiếc).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5a', pts: 0.5,
      text: 'Điền số thích hợp vào chỗ trống (dấu ? ở dòng cuối):', img: A + 'd3b5a.png',
      opts: o4('17', '19', '16', '15'), ans: 'A',
      why: 'Cốc nước = 30 : 3 = 10; bánh burger = (20 − 10) : 2 = 5; khoai tây = (9 − 5) : 2 = 2. Vậy 5 + 2 + 10 = 17.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5b', pts: 0.5,
      text: 'Hình bên có bao nhiêu khối trụ và khối cầu?', img: A + 'd3b5b.png',
      opts: o4('2 khối trụ và 2 khối cầu', '3 khối trụ và 2 khối cầu', '2 khối trụ và 3 khối cầu', '3 khối trụ và 3 khối cầu'), ans: 'A',
      why: '2 khối trụ (màu đỏ và màu xanh) và 2 khối cầu màu xanh.' },
  ],
},
/* ================================================== ĐỀ 4 ================================================== */
{
  id: 4, title: 'Đề 4', time: 35,
  questions: [
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 1', pts: 0.5,
      text: 'Cô nhân viên thư viện xếp các cuốn sách lên giá, em hãy giúp cô đánh tiếp số thứ tự vào các cuốn sách còn lại trong hình nhé:', img: A + 'd4c1.png',
      opts: o4('228; 229; 230; 231; 233; 234', '227; 228; 230; 231; 233; 234', '2225; 228; 230; 231; 233; 234', '226; 228; 230; 231; 233; 234'), ans: 'D',
      why: 'Các sách đã ghi 225, 227, 229, 232, 235. Các số còn thiếu theo thứ tự: 226; 228; 230; 231; 233; 234.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 2', pts: 0.5,
      text: 'Điền dấu thích hợp: 862 ….. 953',
      opts: o4('<', '=', '>', 'Không điền được dấu'), ans: 'A', why: '862 < 953.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 3', pts: 0.5,
      text: 'Các số: 191 ; 957 ; 599 ; 518 được sắp xếp theo thứ tự từ lớn đến bé là:',
      opts: o4('191 ; 518 ; 599 ; 957', '957 ; 599 ; 518 ; 191', '599 ; 518 ; 957 ; 191', '957 ; 518 ; 599 ; 191'), ans: 'B',
      why: '957 > 599 > 518 > 191.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 4', pts: 0.5,
      text: 'Quan sát quy luật bên dưới. Hỏi hàng 5 có bao nhiêu Minions?', img: A + 'd4c4.png',
      opts: o4('8', '10', '12', '5'), ans: 'B',
      why: 'Hàng 1 có 2, hàng 2 có 4, hàng 3 có 6 — mỗi hàng thêm 2. Hàng 5 có 10 Minions.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 5', pts: 0.5,
      text: 'Để đo chiều dài một cuốn sách, người ta thường sử dụng đơn vị:',
      opts: o4('km', 'm', 'cm', 'kg'), ans: 'C', why: 'Cuốn sách ngắn nên đo bằng xăng-ti-mét (cm).' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 6', pts: 0.5,
      text: 'Mỗi xe đạp có 2 bánh xe. Hỏi 6 xe đạp như thế có tất cả bao nhiêu bánh xe?', img: A + 'd4c6.png',
      opts: o4('10 bánh xe', '12 bánh xe', '16 bánh xe', '18 bánh xe'), ans: 'B',
      why: '2 × 6 = 12 (bánh xe).' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 7', pts: 0.5,
      text: 'Buổi tối, em đọc sách khoảng:',
      opts: o4('20 giây', '20 phút', '20 giờ', '20cm'), ans: 'B', why: 'Thời gian đọc sách buổi tối hợp lý là khoảng 20 phút.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 8', pts: 0.5,
      text: 'Tổng của số nhỏ nhất có ba chữ số, số liền trước 350 và số lớn nhất có hai chữ số là:',
      opts: o4('549', '199', '548', '450'), ans: 'C',
      why: '100 + 349 + 99 = 548.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1a', pts: 0.25,
      text: 'Đặt tính rồi tính: 105 + 125 = ?',
      opts: o4('230', '220', '240', '125'), ans: 'A', why: '105 + 125 = 230.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1b', pts: 0.25,
      text: 'Đặt tính rồi tính: 21 + 191 = ?',
      opts: o4('212', '202', '222', '170'), ans: 'A', why: '21 + 191 = 212.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1c', pts: 0.25,
      text: 'Đặt tính rồi tính: 260 − 37 = ?',
      opts: o4('223', '233', '213', '297'), ans: 'A', why: '260 − 37 = 223.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1d', pts: 0.25,
      text: 'Đặt tính rồi tính: 592 − 243 = ?',
      opts: o4('349', '359', '339', '449'), ans: 'A', why: '592 − 243 = 349.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2', pts: 1,
      text: 'Hãy tô màu vào các tờ giấy bạc để được số tiền ở bên phải (800 đồng). Em chọn các tờ tiền nào?', img: A + 'd4b2.png',
      opts: o4('100 đồng, 200 đồng và 500 đồng', '200 đồng và 100 đồng', '500 đồng và 100 đồng', '200 đồng, 200 đồng và 100 đồng'), ans: 'A',
      why: '100 + 200 + 500 = 800 (đồng).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3', pts: 2,
      text: 'Cô giáo có 40 quyển vở. Cô chia đều số vở đó cho 5 bạn. Hỏi mỗi bạn được nhận mấy quyển vở?', img: A + 'd4b3.png',
      opts: o4('8 quyển vở', '7 quyển vở', '9 quyển vở', '6 quyển vở'), ans: 'A',
      why: '40 : 5 = 8 (quyển vở).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4a', pts: 0.25,
      text: 'Kiểm đếm số lượng rồi ghi lại kết quả: Có bao nhiêu quả cam?', img: A + 'd4b4.png',
      opts: o4('6', '5', '7', '8'), ans: 'A', why: 'Đếm được 6 quả cam.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4b', pts: 0.25,
      text: 'Có bao nhiêu chùm nho?', img: A + 'd4b4.png',
      opts: o4('7', '6', '8', '5'), ans: 'A', why: 'Đếm được 7 chùm nho.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4c', pts: 0.25,
      text: 'Có bao nhiêu miếng dưa hấu?', img: A + 'd4b4.png',
      opts: o4('8', '7', '6', '9'), ans: 'A', why: 'Đếm được 8 miếng dưa hấu.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4d', pts: 0.25,
      text: 'Có bao nhiêu quả kiwi?', img: A + 'd4b4.png',
      opts: o4('4', '5', '3', '6'), ans: 'A', why: 'Đếm được 4 quả kiwi.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5a', pts: 0.5,
      text: 'Quan sát sơ đồ và cho biết quãng đường từ nhà Ngọc đến địa điểm nào dài 220m?', img: A + 'd4b5a.png',
      opts: o4('Bến xe bus (đi qua bưu điện)', 'Trường học', 'Rạp xiếc', 'Bệnh viện'), ans: 'A',
      why: 'Nhà Ngọc → Bưu điện (100m) → Bến xe bus (120m): 100 + 120 = 220m.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5b-1', pts: 0.125,
      text: 'Quan sát tranh: Có bao nhiêu đồ vật có hình khối hộp chữ nhật?', img: A + 'd4b5b.png',
      opts: o4('2', '1', '3', '4'), ans: 'A', why: 'Tủ gỗ và hộp quà — 2 đồ vật.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5b-2', pts: 0.125,
      text: 'Có bao nhiêu đồ vật có hình khối cầu?', img: A + 'd4b5b.png',
      opts: o4('4', '3', '5', '2'), ans: 'A', why: 'Quả cam, quả địa cầu, quả bóng, quả bí ngô — 4 đồ vật.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5b-3', pts: 0.125,
      text: 'Có bao nhiêu đồ vật có hình khối trụ?', img: A + 'd4b5b.png',
      opts: o4('4', '3', '5', '2'), ans: 'A', why: 'Cốc nước cam, bể bơi, kính vạn hoa, lon nước — 4 đồ vật.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5b-4', pts: 0.125,
      text: 'Có bao nhiêu đồ vật có hình khối lập phương?', img: A + 'd4b5b.png',
      opts: o4('3', '4', '2', '5'), ans: 'A', why: 'Khối rubik, khối chữ M, khối chữ A — 3 đồ vật.' },
  ],
},
/* ================================================== ĐỀ 5 ================================================== */
{
  id: 5, title: 'Đề 5', time: 35,
  questions: [
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 1', pts: 0.5,
      text: 'Số “Sáu trăm bảy mươi lăm” được viết là:',
      opts: o4('670', '655', '675', '576'), ans: 'C', why: 'Sáu trăm bảy mươi lăm viết là 675.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 2', pts: 0.5,
      text: 'Tổng của 121 và 338 là:',
      opts: o4('119', '671', '459', '883'), ans: 'C', why: '121 + 338 = 459.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 3', pts: 0.5,
      text: 'Số nhỏ nhất trong các số: 157 ; 552 ; 202 ; 190 là:',
      opts: o4('157', '552', '202', '190'), ans: 'A', why: '157 < 190 < 202 < 552.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 4', pts: 0.5,
      text: 'Buổi sáng, em vệ sinh cá nhân khoảng:',
      opts: o4('10 giây', '10 phút', '10 giờ', '10 cm'), ans: 'B', why: 'Vệ sinh cá nhân buổi sáng mất khoảng 10 phút.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 5', pts: 0.5,
      text: '2dm 9cm = … cm. Số thích hợp điền vào chỗ chấm là:',
      opts: o4('209', '29', '219', '290'), ans: 'B', why: '2dm = 20cm; 20 + 9 = 29cm.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 6', pts: 0.5,
      text: 'Một đội công nhân sửa đường trong vòng 5 ngày liên tục, bắt đầu từ ngày 16 tháng 4. Hỏi ngày kết thúc là ngày nào?', img: A + 'd5c6.png',
      opts: o4('11 tháng 4', '21 tháng 4', '20 tháng 4', '19 tháng 4'), ans: 'C',
      why: '5 ngày liên tục: 16, 17, 18, 19, 20 — kết thúc ngày 20 tháng 4.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 7', pts: 0.5,
      text: 'Thùng cam cân nặng 155kg, thùng dưa hấu cân nặng 154kg. Hỏi cả hai thùng cân nặng bao nhiêu?', img: A + 'd5c7.png',
      opts: o4('309', '309kg', '209kg', '109kg'), ans: 'B',
      why: '155 + 154 = 309 (kg) — nhớ kèm đơn vị kg.' },
    { sec: 'Phần I: Trắc nghiệm (4 điểm)', name: 'Câu 8', pts: 0.5,
      text: 'Biết 45□ < 451, số thích hợp điền vào ô trống là:',
      opts: o4('0', '1', '2', '3'), ans: 'A', why: '450 < 451 nên điền số 0.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1a', pts: 0.25,
      text: 'Đặt tính rồi tính: 128 + 49 = ?',
      opts: o4('177', '167', '187', '79'), ans: 'A', why: '128 + 49 = 177.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1b', pts: 0.25,
      text: 'Đặt tính rồi tính: 451 + 262 = ?',
      opts: o4('713', '703', '723', '189'), ans: 'A', why: '451 + 262 = 713.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1c', pts: 0.25,
      text: 'Đặt tính rồi tính: 866 − 596 = ?',
      opts: o4('270', '260', '280', '370'), ans: 'A', why: '866 − 596 = 270.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 1d', pts: 0.25,
      text: 'Đặt tính rồi tính: 955 − 238 = ?',
      opts: o4('717', '707', '727', '617'), ans: 'A', why: '955 − 238 = 717.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2a', pts: 0.17,
      text: 'Gieo một viên xúc xắc. Khả năng “Xuất hiện mặt 1 chấm” là:', img: A + 'd5b2.svg',
      opts: KN, ans: 'B', why: 'Xúc xắc có các mặt 1–6 chấm nên mặt 1 chấm CÓ THỂ xuất hiện.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2b', pts: 0.17,
      text: 'Khả năng “Xuất hiện mặt 6 chấm” là:', img: A + 'd5b2.svg',
      opts: KN, ans: 'B', why: 'Mặt 6 chấm CÓ THỂ xuất hiện.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2c', pts: 0.17,
      text: 'Khả năng “Xuất hiện mặt 8 chấm” là:', img: A + 'd5b2.svg',
      opts: KN, ans: 'C', why: 'Xúc xắc không có mặt 8 chấm — KHÔNG THỂ.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2d', pts: 0.17,
      text: 'Khả năng “Xuất hiện mặt có số chấm lớn hơn 3” là:', img: A + 'd5b2.svg',
      opts: KN, ans: 'B', why: 'Các mặt 4, 5, 6 chấm lớn hơn 3 — CÓ THỂ xuất hiện.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2e', pts: 0.16,
      text: 'Khả năng “Xuất hiện mặt có số chấm nhỏ hơn 7” là:', img: A + 'd5b2.svg',
      opts: KN, ans: 'A', why: 'Mọi mặt xúc xắc đều từ 1 đến 6 chấm (nhỏ hơn 7) — CHẮC CHẮN.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 2f', pts: 0.16,
      text: 'Khả năng “Xuất hiện mặt có số chấm lớn hơn 7” là:', img: A + 'd5b2.svg',
      opts: KN, ans: 'C', why: 'Không có mặt nào lớn hơn 6 chấm — KHÔNG THỂ.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3a', pts: 0.33,
      text: 'Quan sát biểu đồ tranh. Vị kem được yêu thích nhất là:', img: A + 'd5b3.png',
      opts: o4('Kem vani', 'Kem sô-cô-la', 'Kem dâu', 'Kem bạc hà'), ans: 'A',
      why: 'Kem vani có 10 người thích — nhiều nhất.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3b', pts: 0.33,
      text: 'Có bao nhiêu người yêu thích kem bạc hà?', img: A + 'd5b3.png',
      opts: o4('4 người', '5 người', '9 người', '10 người'), ans: 'A',
      why: 'Hàng kem bạc hà có 4 cây kem.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 3c', pts: 0.34,
      text: 'Khu chung cư có tất cả bao nhiêu người tham gia khảo sát vị kem yêu thích của mình?', img: A + 'd5b3.png',
      opts: o4('28 người', '27 người', '29 người', '24 người'), ans: 'A',
      why: '10 + 9 + 5 + 4 = 28 người.' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4a', pts: 1,
      text: 'Trong tuần đầu tháng 4/2022, cửa hàng gà rán KFC bán được 580 chiếc đùi gà. Biết số cánh gà cửa hàng bán được ít hơn số đùi gà là 246 chiếc. Hỏi cửa hàng gà rán KFC bán được bao nhiêu chiếc cánh gà?', img: A + 'd5b4.png',
      opts: o4('334 chiếc', '826 chiếc', '344 chiếc', '324 chiếc'), ans: 'A',
      why: 'Số cánh gà: 580 − 246 = 334 (chiếc).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 4b', pts: 1,
      text: 'Hỏi cửa hàng bán được tất cả bao nhiêu chiếc đùi gà và cánh gà?', img: A + 'd5b4.png',
      opts: o4('914 chiếc', '826 chiếc', '904 chiếc', '924 chiếc'), ans: 'A',
      why: '580 + 334 = 914 (chiếc).' },
    { sec: 'Phần II: Tự luận (6 điểm)', name: 'Bài 5', pts: 1,
      text: 'Trong vòng 5 phút, bạn Thỏ nhặt được 45 hạt dẻ. Trong vòng 2 phút, bạn Sóc nhặt được 20 hạt dẻ. Theo em, bạn nào nhặt hạt dẻ nhanh hơn, vì sao?', img: A + 'd5b5.png',
      opts: o4('Bạn Sóc, vì mỗi phút Sóc nhặt được 20 : 2 = 10 hạt, nhiều hơn Thỏ (45 : 5 = 9 hạt)', 'Bạn Thỏ, vì 45 hạt nhiều hơn 20 hạt', 'Hai bạn nhanh như nhau', 'Bạn Thỏ, vì mỗi phút Thỏ nhặt được 10 hạt'), ans: 'A',
      why: 'Mỗi phút: Thỏ nhặt 45 : 5 = 9 hạt; Sóc nhặt 20 : 2 = 10 hạt. 10 > 9 nên Sóc nhanh hơn.' },
  ],
},
/* ================================================== ĐỀ 6 ================================================== */
{
  id: 6, title: 'Đề 6', time: 35,
  questions: [
    { sec: 'Trắc nghiệm', name: 'Câu 1a', pts: 0.5,
      text: 'Các số 652; 562; 625 viết theo thứ tự từ bé đến lớn là:',
      opts: o4('562; 652; 625', '652; 562; 625', '562; 625; 652', '625; 562; 652'), ans: 'C',
      why: '562 < 625 < 652.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1b', pts: 0.5,
      text: 'Chiều dài của cái bàn khoảng 15……. Tên đơn vị cần điền vào chỗ chấm là:',
      opts: o4('cm', 'km', 'dm', 'm'), ans: 'C',
      why: 'Cái bàn dài khoảng 15dm (tức 1,5m) — hợp lý nhất.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1c', pts: 0.5,
      text: 'Số liền trước số 342 là:',
      opts: o4('343', '341', '340', '344'), ans: 'B', why: 'Số liền trước 342 là 342 − 1 = 341.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1d', pts: 0.5,
      text: 'Giá trị của chữ số 8 trong 287 là:',
      opts: o4('800', '8', '80', '87'), ans: 'C', why: 'Chữ số 8 ở hàng chục nên có giá trị 80.' },
    { sec: 'Trắc nghiệm', name: 'Câu 2a', pts: 0.125,
      text: 'Nối số với cách đọc: “Tám trăm bảy mươi lăm” là số:',
      opts: o4('875', '857', '578', '785'), ans: 'A', why: 'Tám trăm bảy mươi lăm = 875.' },
    { sec: 'Trắc nghiệm', name: 'Câu 2b', pts: 0.125,
      text: '“Năm trăm bảy mươi tám” là số:',
      opts: o4('578', '587', '875', '785'), ans: 'A', why: 'Năm trăm bảy mươi tám = 578.' },
    { sec: 'Trắc nghiệm', name: 'Câu 2c', pts: 0.125,
      text: '“Bốn trăm linh bốn” là số:',
      opts: o4('404', '440', '400', '414'), ans: 'A', why: 'Bốn trăm linh bốn = 404.' },
    { sec: 'Trắc nghiệm', name: 'Câu 2d', pts: 0.125,
      text: '“Bốn trăm” là số:',
      opts: o4('400', '404', '440', '410'), ans: 'A', why: 'Bốn trăm = 400.' },
    { sec: 'Trắc nghiệm', name: 'Câu 3', pts: 1,
      text: 'Số? Điền lần lượt các số vào ô vuông, tam giác, chữ nhật và hình thoi:', img: A + 'd6c3.svg',
      opts: o4('13 ; 5 ; 20 ; 10', '13 ; 5 ; 20 ; 40', '12 ; 4 ; 16 ; 8', '13 ; 6 ; 24 ; 12'), ans: 'A',
      why: '7 + 6 = 13; 13 − 8 = 5; 5 × 4 = 20; 20 : 2 = 10.' },
    { sec: 'Tự luận', name: 'Câu 4a', pts: 0.5,
      text: 'Đặt tính rồi tính: 535 + 245 = ?',
      opts: o4('780', '770', '790', '290'), ans: 'A', why: '535 + 245 = 780.' },
    { sec: 'Tự luận', name: 'Câu 4b', pts: 0.5,
      text: 'Đặt tính rồi tính: 381 + 546 = ?',
      opts: o4('927', '917', '937', '835'), ans: 'A', why: '381 + 546 = 927.' },
    { sec: 'Tự luận', name: 'Câu 4c', pts: 0.5,
      text: 'Đặt tính rồi tính: 972 − 49 = ?',
      opts: o4('923', '933', '913', '1021'), ans: 'A', why: '972 − 49 = 923.' },
    { sec: 'Tự luận', name: 'Câu 4d', pts: 0.5,
      text: 'Đặt tính rồi tính: 569 − 285 = ?',
      opts: o4('284', '294', '274', '854'), ans: 'A', why: '569 − 285 = 284.' },
    { sec: 'Tự luận', name: 'Câu 5', pts: 1,
      text: 'Một chuồng có 5 con gà. Hỏi 4 chuồng như thế có bao nhiêu con gà?', img: A + 'd6c5.png',
      opts: o4('20 con gà', '9 con gà', '25 con gà', '15 con gà'), ans: 'A',
      why: '5 × 4 = 20 (con gà).' },
    { sec: 'Tự luận', name: 'Câu 6a-1', pts: 0.17,
      text: 'Quan sát biểu đồ. Có bao nhiêu con chim?', img: A + 'd6c6.png',
      opts: o4('5', '6', '7', '4'), ans: 'A', why: 'Hàng con chim có 5 con.' },
    { sec: 'Tự luận', name: 'Câu 6a-2', pts: 0.17,
      text: 'Có bao nhiêu con bướm?', img: A + 'd6c6.png',
      opts: o4('7', '6', '5', '8'), ans: 'A', why: 'Hàng con bướm có 7 con.' },
    { sec: 'Tự luận', name: 'Câu 6a-3', pts: 0.16,
      text: 'Có bao nhiêu con ong?', img: A + 'd6c6.png',
      opts: o4('6', '5', '7', '4'), ans: 'A', why: 'Hàng con ong có 6 con.' },
    { sec: 'Tự luận', name: 'Câu 6b', pts: 0.5,
      text: 'Con vật nào nhiều nhất? Con vật nào ít nhất?', img: A + 'd6c6.png',
      opts: o4('Bướm nhiều nhất, chim ít nhất', 'Ong nhiều nhất, chim ít nhất', 'Bướm nhiều nhất, ong ít nhất', 'Chim nhiều nhất, ong ít nhất'), ans: 'A',
      why: 'Bướm 7 con (nhiều nhất); chim 5 con (ít nhất).' },
    { sec: 'Tự luận', name: 'Câu 6c-1', pts: 0.25,
      text: 'Con bướm nhiều hơn con chim …… con.', img: A + 'd6c6.png',
      opts: o4('2', '1', '3', '4'), ans: 'A', why: '7 − 5 = 2 (con).' },
    { sec: 'Tự luận', name: 'Câu 6c-2', pts: 0.25,
      text: 'Con chim ít hơn con ong …… con.', img: A + 'd6c6.png',
      opts: o4('1', '2', '3', '0'), ans: 'A', why: '6 − 5 = 1 (con).' },
    { sec: 'Tự luận', name: 'Câu 7a', pts: 0.5,
      text: 'Số hình tứ giác có trong hình vẽ là:', img: A + 'd6c7a.svg',
      opts: o4('4 hình', '3 hình', '2 hình', '1 hình'), ans: 'A',
      why: 'Hình ở giữa; hình giữa + tam giác trái; hình giữa + tam giác phải; và cả hình lớn — tất cả 4 hình tứ giác.' },
    { sec: 'Tự luận', name: 'Câu 7b', pts: 0.5,
      text: 'Hình nào là hình khối trụ? (đếm từ trái sang phải)', img: A + 'd6c7b.svg',
      opts: o4('Hình 2, hình 3 và hình 5', 'Hình 2 và hình 3', 'Hình 3 và hình 5', 'Hình 1, hình 2 và hình 3'), ans: 'A',
      why: 'Khối trụ nằm ngang (hình 2), khối trụ đứng (hình 3) và khối trụ dẹt (hình 5).' },
    { sec: 'Tự luận', name: 'Câu 7c', pts: 0.5,
      text: 'Hãy tính đoạn đường từ nhà Lan đến trường dựa vào hình vẽ dưới đây:', img: A + 'd6c7c.png',
      opts: o4('990m', '980m', '890m', '1000m'), ans: 'A',
      why: '375 + 254 + 361 = 990 (m).' },
    { sec: 'Tự luận', name: 'Câu 8a', pts: 0.125,
      text: 'Quan sát đường đi của những con vật và chọn từ phù hợp: Cô bướm …… đến chỗ bông hoa màu hồng.', img: A + 'd6c8.png',
      opts: KN, ans: 'A', why: 'Lần theo dây: đường của cô bướm dẫn đến bông hoa màu hồng — chắc chắn.' },
    { sec: 'Tự luận', name: 'Câu 8b', pts: 0.125,
      text: 'Chú ong …… đến chỗ bông hoa màu vàng.', img: A + 'd6c8.png',
      opts: KN, ans: 'A', why: 'Đường của chú ong nối thẳng đến bông hoa màu vàng — chắc chắn.' },
    { sec: 'Tự luận', name: 'Câu 8c', pts: 0.125,
      text: 'Bác Kiến …… đến chỗ chiếc bánh.', img: A + 'd6c8.png',
      opts: KN, ans: 'A', why: 'Đường của bác kiến dẫn đến chiếc bánh — chắc chắn.' },
    { sec: 'Tự luận', name: 'Câu 8d', pts: 0.125,
      text: 'Cậu ốc sên …… đến chỗ quả táo đỏ.', img: A + 'd6c8.png',
      opts: KN, ans: 'A', why: 'Đường của ốc sên dẫn đến quả táo đỏ — chắc chắn.' },
  ],
},
/* ================================================== ĐỀ 7 ================================================== */
{
  id: 7, title: 'Đề 7', time: 35,
  questions: [
    { sec: 'Trắc nghiệm', name: 'Câu 1a', pts: 0.5,
      text: 'Số bé nhất có 3 chữ số khác nhau là:',
      opts: o4('100', '101', '102', '111'), ans: 'C',
      why: '100 và 101 có chữ số lặp lại; số bé nhất có 3 chữ số khác nhau là 102.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1b', pts: 0.5,
      text: 'Cho dãy số: 7; 11; 15; 19; …. Số tiếp theo điền vào chỗ chấm là:',
      opts: o4('22', '23', '33', '34'), ans: 'B',
      why: 'Dãy số đếm thêm 4: 19 + 4 = 23.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1c', pts: 0.5,
      text: 'Nếu thứ 6 tuần này là 26. Thì thứ 5 tuần trước là:',
      opts: o4('17', '18', '19', '20'), ans: 'B',
      why: 'Thứ 6 tuần trước: 26 − 7 = 19; thứ 5 tuần trước: 19 − 1 = 18.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1d', pts: 0.5,
      text: 'Số liền sau của số lớn nhất có hai chữ số là:',
      opts: o4('98', '99', '100', '101'), ans: 'C',
      why: 'Số lớn nhất có hai chữ số là 99; liền sau là 100.' },
    { sec: 'Tự luận', name: 'Câu 2a', pts: 0.25,
      text: 'Viết theo mẫu (398 = 300 + 90 + 8): 83 = ?',
      opts: o4('80 + 3', '8 + 3', '80 + 30', '800 + 3'), ans: 'A', why: '83 = 80 + 3.' },
    { sec: 'Tự luận', name: 'Câu 2b', pts: 0.25,
      text: 'Viết theo mẫu: 670 = ?',
      opts: o4('600 + 70', '600 + 7', '60 + 70', '600 + 70 + 0,5'), ans: 'A', why: '670 = 600 + 70.' },
    { sec: 'Tự luận', name: 'Câu 2c', pts: 0.25,
      text: 'Viết theo mẫu: 103 = ?',
      opts: o4('100 + 3', '100 + 30', '10 + 3', '100 + 0 + 30'), ans: 'A', why: '103 = 100 + 3.' },
    { sec: 'Tự luận', name: 'Câu 2d', pts: 0.25,
      text: 'Viết theo mẫu: 754 = ?',
      opts: o4('700 + 50 + 4', '700 + 5 + 4', '70 + 50 + 4', '700 + 40 + 5'), ans: 'A', why: '754 = 700 + 50 + 4.' },
    { sec: 'Tự luận', name: 'Câu 3a', pts: 0.33,
      text: 'Cho các số 427; 242; 369; 898. Viết theo thứ tự từ bé đến lớn:', img: A + 'd7c3.png',
      opts: o4('242; 369; 427; 898', '898; 427; 369; 242', '242; 427; 369; 898', '369; 242; 427; 898'), ans: 'A',
      why: '242 < 369 < 427 < 898.' },
    { sec: 'Tự luận', name: 'Câu 3b', pts: 0.33,
      text: 'Viết theo thứ tự từ lớn đến bé:', img: A + 'd7c3.png',
      opts: o4('898; 427; 369; 242', '242; 369; 427; 898', '898; 369; 427; 242', '427; 898; 369; 242'), ans: 'A',
      why: '898 > 427 > 369 > 242.' },
    { sec: 'Tự luận', name: 'Câu 3c', pts: 0.34,
      text: 'Hiệu của số lớn nhất và số bé nhất bằng:',
      opts: o4('656', '646', '666', '1140'), ans: 'A',
      why: '898 − 242 = 656.' },
    { sec: 'Tự luận', name: 'Câu 4a', pts: 0.25,
      text: 'Đặt tính rồi tính: 880 − 426 = ?',
      opts: o4('454', '464', '444', '1306'), ans: 'A', why: '880 − 426 = 454.' },
    { sec: 'Tự luận', name: 'Câu 4b', pts: 0.25,
      text: 'Đặt tính rồi tính: 167 + 62 = ?',
      opts: o4('229', '219', '239', '105'), ans: 'A', why: '167 + 62 = 229.' },
    { sec: 'Tự luận', name: 'Câu 4c', pts: 0.25,
      text: 'Đặt tính rồi tính: 346 − 64 = ?',
      opts: o4('282', '292', '272', '410'), ans: 'A', why: '346 − 64 = 282.' },
    { sec: 'Tự luận', name: 'Câu 4d', pts: 0.25,
      text: 'Đặt tính rồi tính: 756 − 291 = ?',
      opts: o4('465', '475', '455', '1047'), ans: 'A', why: '756 − 291 = 465.' },
    { sec: 'Tự luận', name: 'Câu 5a', pts: 0.33,
      text: 'Tính: 837 + 39 − 92 = ?',
      opts: o4('784', '774', '794', '876'), ans: 'A', why: '837 + 39 = 876; 876 − 92 = 784.' },
    { sec: 'Tự luận', name: 'Câu 5b', pts: 0.33,
      text: 'Tính: 792 − 564 + 80 = ?',
      opts: o4('308', '318', '298', '228'), ans: 'A', why: '792 − 564 = 228; 228 + 80 = 308.' },
    { sec: 'Tự luận', name: 'Câu 5c', pts: 0.34,
      text: 'Tính: 455 − 126 − 151 = ?',
      opts: o4('178', '168', '188', '329'), ans: 'A', why: '455 − 126 = 329; 329 − 151 = 178.' },
    { sec: 'Tự luận', name: 'Câu 6', pts: 1,
      text: 'Một cửa hàng buổi sáng bán được 350kg gạo, buổi chiều bán được 374kg gạo. Hỏi cả hai buổi cửa hàng đó bán được bao nhiêu ki-lô-gam gạo?',
      opts: o4('724 kg', '624 kg', '714 kg', '734 kg'), ans: 'A',
      why: '350 + 374 = 724 (kg).' },
    { sec: 'Tự luận', name: 'Câu 7a', pts: 0.5,
      text: 'Độ dài đường gấp khúc MNPQKH là (viết phép tính nhân):', img: A + 'd7c7a.svg',
      opts: o4('5 × 5 = 25cm', '5 × 4 = 20cm', '5 + 5 = 10cm', '5 × 6 = 30cm'), ans: 'A',
      why: 'Đường gấp khúc gồm 5 đoạn, mỗi đoạn 5cm: 5 × 5 = 25cm.' },
    { sec: 'Tự luận', name: 'Câu 7b', pts: 0.5,
      text: 'Trong hình bên có bao nhiêu hình tam giác và bao nhiêu đoạn thẳng?', img: A + 'd7c7b.svg',
      opts: o4('6 hình tam giác, 11 đoạn thẳng', '4 hình tam giác, 7 đoạn thẳng', '6 hình tam giác, 7 đoạn thẳng', '4 hình tam giác, 11 đoạn thẳng'), ans: 'A',
      why: '4 tam giác nhỏ + 2 tam giác ghép = 6. Đoạn thẳng: 3 cạnh nguyên + 2 cạnh bị chia (mỗi cạnh đếm 3 đoạn) + 2 đoạn trong hình = 11.' },
    { sec: 'Tự luận', name: 'Câu 7c-1', pts: 0.125,
      text: 'Mỗi đồ vật sau thuộc hình khối gì? — Khối lập phương là:', img: A + 'd7c7c.png',
      opts: o4('Thùng gỗ', 'Hộp sữa', 'Lon sữa', 'Quả bóng đá'), ans: 'A',
      why: 'Thùng gỗ có các mặt vuông bằng nhau — khối lập phương.' },
    { sec: 'Tự luận', name: 'Câu 7c-2', pts: 0.125,
      text: 'Khối trụ là:', img: A + 'd7c7c.png',
      opts: o4('Lon sữa, cục pin và bể cá', 'Lon sữa và hộp sữa', 'Cục pin và quả bóng', 'Bể cá và thùng gỗ'), ans: 'A',
      why: 'Lon sữa, cục pin và bể cá đều có dạng khối trụ.' },
    { sec: 'Tự luận', name: 'Câu 7c-3', pts: 0.125,
      text: 'Khối cầu là:', img: A + 'd7c7c.png',
      opts: o4('Quả bóng chuyền và quả bóng đá', 'Quả bóng và lon sữa', 'Bể cá', 'Thùng gỗ và hộp sữa'), ans: 'A',
      why: 'Hai quả bóng có dạng khối cầu.' },
    { sec: 'Tự luận', name: 'Câu 7c-4', pts: 0.125,
      text: 'Khối hộp chữ nhật là:', img: A + 'd7c7c.png',
      opts: o4('Hộp sữa', 'Thùng gỗ', 'Bể cá', 'Cục pin'), ans: 'A',
      why: 'Hộp sữa có dạng khối hộp chữ nhật.' },
    { sec: 'Tự luận', name: 'Câu 8a', pts: 0.125,
      text: 'Nam và Mai chơi trò bịt mắt hái hoa, chỉ được đi thẳng. Chọn từ phù hợp: Mai hái được bông hoa màu vàng.', img: A + 'd7c8.png',
      opts: KN, ans: 'A', why: 'Vườn phía Mai toàn hoa vàng — chắc chắn hái được hoa vàng.' },
    { sec: 'Tự luận', name: 'Câu 8b', pts: 0.125,
      text: 'Nam hái được bông hoa màu đỏ.', img: A + 'd7c8.png',
      opts: KN, ans: 'B', why: 'Vườn phía Nam có nhiều màu hoa (đỏ, tím, vàng, xanh) — có thể.' },
    { sec: 'Tự luận', name: 'Câu 8c', pts: 0.125,
      text: 'Mai hái được bông hoa màu tím.', img: A + 'd7c8.png',
      opts: KN, ans: 'C', why: 'Vườn phía Mai không có hoa tím — không thể.' },
    { sec: 'Tự luận', name: 'Câu 8d', pts: 0.125,
      text: 'Nam hái được bông hoa màu xanh.', img: A + 'd7c8.png',
      opts: KN, ans: 'B', why: 'Vườn phía Nam có hoa xanh — có thể.' },
    { sec: 'Tự luận', name: 'Câu 9a', pts: 0.25,
      text: 'Điền dấu (>, <, =) thích hợp: 12 : 2 …… 5 × 3',
      opts: o3('>', '<', '='), ans: 'B', why: '12 : 2 = 6; 5 × 3 = 15; 6 < 15.' },
    { sec: 'Tự luận', name: 'Câu 9b', pts: 0.25,
      text: 'Điền dấu: 45 : 5 …… 18 : 2',
      opts: o3('>', '<', '='), ans: 'C', why: '45 : 5 = 9; 18 : 2 = 9; 9 = 9.' },
    { sec: 'Tự luận', name: 'Câu 9c', pts: 0.25,
      text: 'Điền dấu: 5 × 2 …… 2 × 5',
      opts: o3('>', '<', '='), ans: 'C', why: '5 × 2 = 2 × 5 = 10.' },
    { sec: 'Tự luận', name: 'Câu 9d', pts: 0.25,
      text: 'Điền dấu: 7 × 2 …… 35 : 5',
      opts: o3('>', '<', '='), ans: 'A', why: '7 × 2 = 14; 35 : 5 = 7; 14 > 7.' },
  ],
},
/* ================================================== ĐỀ 8 ================================================== */
{
  id: 8, title: 'Đề 8', time: 35,
  questions: [
    { sec: 'Trắc nghiệm', name: 'Câu 1a', pts: 0.5,
      text: 'Số “Năm trăm linh bảy” viết là:',
      opts: o4('570', '507', '705', '750'), ans: 'B', why: 'Năm trăm linh bảy = 507.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1b', pts: 0.5,
      text: 'Số 575 đọc là:',
      opts: o4('Năm trăm bảy mươi lăm', 'Năm trăm bảy mươi năm', 'Lăm trăm bảy mươi lăm', 'Năm bảy năm'), ans: 'A',
      why: '575 đọc là “Năm trăm bảy mươi lăm”.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1c', pts: 0.5,
      text: 'Số bé nhất trong các số 414; 441; 144; 444 là:',
      opts: o4('414', '441', '144', '444'), ans: 'C', why: '144 < 414 < 441 < 444.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1d', pts: 1,
      text: 'Bao gạo thứ nhất nặng 115kg. Bao gạo thứ nhất nhẹ hơn bao gạo thứ hai 85kg. Nếu đặt bao thứ hai lên cân đồng hồ thì kim đồng hồ chỉ số bao nhiêu?',
      opts: o4('190kg', '30kg', '20kg', '200kg'), ans: 'D',
      why: 'Bao thứ hai nặng: 115 + 85 = 200 (kg).' },
    { sec: 'Trắc nghiệm', name: 'Câu 2a', pts: 0.25,
      text: 'Viết cm, dm, m vào chỗ chấm thích hợp: Chiếc bút bi dài khoảng 15…', img: A + 'd8c2.png',
      opts: o3('cm', 'dm', 'm'), ans: 'A', why: 'Bút bi dài khoảng 15cm.' },
    { sec: 'Trắc nghiệm', name: 'Câu 2b', pts: 0.25,
      text: 'Một ngôi nhà nhiều tầng cao khoảng 15…', img: A + 'd8c2.png',
      opts: o3('cm', 'dm', 'm'), ans: 'C', why: 'Ngôi nhà nhiều tầng cao khoảng 15m.' },
    { sec: 'Trắc nghiệm', name: 'Câu 2c', pts: 0.25,
      text: 'Bề dày hộp bút khoảng 2…', img: A + 'd8c2.png',
      opts: o3('cm', 'dm', 'm'), ans: 'A', why: 'Bề dày hộp bút khoảng 2cm.' },
    { sec: 'Trắc nghiệm', name: 'Câu 2d', pts: 0.25,
      text: 'Một gang tay dài khoảng 2…', img: A + 'd8c2.png',
      opts: o3('cm', 'dm', 'm'), ans: 'B', why: 'Một gang tay dài khoảng 2dm (20cm).' },
    { sec: 'Tự luận', name: 'Câu 3a-1', pts: 0.25,
      text: 'Viết số thích hợp vào ô trống: Ngũ giác thứ nhất −290m ra ngũ giác giữa, +300m ra 800m. Hai số cần điền là:', img: A + 'd8c3a.svg',
      opts: o4('790 và 500', '500 và 790', '510 và 810', '790 và 1090'), ans: 'A',
      why: 'Ô giữa: 800 − 300 = 500; ô đầu: 500 + 290 = 790.' },
    { sec: 'Tự luận', name: 'Câu 3a-2', pts: 0.25,
      text: 'Ngôi sao thứ nhất +180l ra ngôi sao giữa, −125l ra 460l. Hai số cần điền là:', img: A + 'd8c3a.svg',
      opts: o4('405 và 585', '585 và 405', '415 và 595', '400 và 580'), ans: 'A',
      why: 'Ô giữa: 460 + 125 = 585; ô đầu: 585 − 180 = 405.' },
    { sec: 'Tự luận', name: 'Câu 3b-1', pts: 0.125,
      text: 'Điền dấu phù hợp (>, <, =): 2×3 …… 2+3',
      opts: o3('>', '<', '='), ans: 'A', why: '6 > 5.' },
    { sec: 'Tự luận', name: 'Câu 3b-2', pts: 0.125,
      text: 'Điền dấu: 14+28−10 …… 5×7',
      opts: o3('>', '<', '='), ans: 'B', why: '32 < 35.' },
    { sec: 'Tự luận', name: 'Câu 3b-3', pts: 0.125,
      text: 'Điền dấu: 20:2 …… 30:5',
      opts: o3('>', '<', '='), ans: 'A', why: '10 > 6.' },
    { sec: 'Tự luận', name: 'Câu 3b-4', pts: 0.125,
      text: 'Điền dấu: 2:2 …… 5:5',
      opts: o3('>', '<', '='), ans: 'C', why: '1 = 1.' },
    { sec: 'Tự luận', name: 'Câu 4a', pts: 0.25,
      text: 'Đặt tính rồi tính: 734 + 173 = ?',
      opts: o4('907', '897', '917', '561'), ans: 'A', why: '734 + 173 = 907.' },
    { sec: 'Tự luận', name: 'Câu 4b', pts: 0.25,
      text: 'Đặt tính rồi tính: 297 − 248 = ?',
      opts: o4('49', '59', '39', '149'), ans: 'A', why: '297 − 248 = 49.' },
    { sec: 'Tự luận', name: 'Câu 4c', pts: 0.25,
      text: 'Đặt tính rồi tính: 528 − 134 = ?',
      opts: o4('394', '404', '384', '494'), ans: 'A', why: '528 − 134 = 394.' },
    { sec: 'Tự luận', name: 'Câu 4d', pts: 0.25,
      text: 'Đặt tính rồi tính: 378 + 612 = ?',
      opts: o4('990', '980', '1000', '234'), ans: 'A', why: '378 + 612 = 990.' },
    { sec: 'Tự luận', name: 'Câu 5', pts: 1,
      text: 'An có một số hộp bi, mỗi hộp 5 viên. An mua thêm 30 bi nữa. Hỏi An có thêm được bao nhiêu hộp bi?',
      opts: o4('6 hộp bi', '5 hộp bi', '7 hộp bi', '35 hộp bi'), ans: 'A',
      why: '30 : 5 = 6 (hộp bi).' },
    { sec: 'Tự luận', name: 'Câu 6a', pts: 0.5,
      text: 'Hình bên có:', img: A + 'd8c6a.svg',
      opts: o3('2 hình tam giác và 2 hình tứ giác', '2 hình tam giác và 3 hình tứ giác', '2 hình tam giác và 4 hình tứ giác'), ans: 'C',
      why: 'Tứ giác gồm: hình chữ nhật giữa, cả hình thang lớn, và 2 hình thang ghép (trái + giữa, giữa + phải) — 4 hình tứ giác; cùng 2 hình tam giác.' },
    { sec: 'Tự luận', name: 'Câu 6b-1', pts: 0.25,
      text: 'Đường gấp khúc ABCD có độ dài là 18cm. Đoạn BC là 8cm, đoạn CD ngắn hơn đoạn BC là 2cm. Đoạn CD dài:', img: A + 'd8c6b.svg',
      opts: o4('6cm', '2cm', '8cm', '10cm'), ans: 'A',
      why: 'CD = 8 − 2 = 6 (cm).' },
    { sec: 'Tự luận', name: 'Câu 6b-2', pts: 0.25,
      text: 'Đoạn AB dài:', img: A + 'd8c6b.svg',
      opts: o4('4cm', '6cm', '2cm', '8cm'), ans: 'A',
      why: 'AB = 18 − 8 − 6 = 4 (cm).' },
    { sec: 'Tự luận', name: 'Câu 6c', pts: 0.5,
      text: 'Quan sát tranh và khoanh vào hình có dạng khối cầu:', img: A + 'd8c6c.png',
      opts: o4('Các hành tinh (Trái Đất, Mặt Trăng, sao Thổ, …)', 'Tên lửa', 'Đĩa bay', 'Ngôi sao'), ans: 'A',
      why: 'Các hành tinh trong tranh có dạng khối cầu.' },
    { sec: 'Tự luận', name: 'Câu 7a', pts: 0.5,
      text: 'Tính kết quả của 5 chú ong: (1) 965−217+107; (2) 712+19−120; (3) 309+129−29; (4) 700−200; (5) 300+400+27. Những chú ong có kết quả lớn hơn 500 và bé hơn 800 là:', img: A + 'd8c7.png',
      opts: o4('Ong số 2 và ong số 5', 'Ong số 1 và ong số 5', 'Ong số 2 và ong số 4', 'Ong số 3 và ong số 5'), ans: 'A',
      why: 'Kết quả: (1) 855; (2) 611; (3) 409; (4) 500; (5) 727. Lớn hơn 500 và bé hơn 800: 611 (ong 2) và 727 (ong 5).' },
    { sec: 'Tự luận', name: 'Câu 7b', pts: 0.5,
      text: 'Các chú ong có kết quả được sắp xếp theo thứ tự từ lớn đến bé là:', img: A + 'd8c7.png',
      opts: o4('Ong 1 (855), ong 5 (727), ong 2 (611), ong 4 (500), ong 3 (409)', 'Ong 3, ong 4, ong 2, ong 5, ong 1', 'Ong 1, ong 2, ong 5, ong 4, ong 3', 'Ong 5, ong 1, ong 2, ong 4, ong 3'), ans: 'A',
      why: '855 > 727 > 611 > 500 > 409.' },
    { sec: 'Tự luận', name: 'Câu 8a', pts: 0.125,
      text: 'Trên kệ có 5 bút chì, 6 bút mực, 4 quyển vở. Chọn từ phù hợp: Minh mua 2 cái bút chì, 2 cái bút mực.', img: A + 'd8c8.png',
      opts: KN, ans: 'A', why: 'Hàng còn đủ (5 chì, 6 mực) — chắc chắn mua được.' },
    { sec: 'Tự luận', name: 'Câu 8b', pts: 0.125,
      text: 'Hải mua 1 cái bút chì, 3 quyển vở, 1 cái bút mực.', img: A + 'd8c8.png',
      opts: KN, ans: 'A', why: 'Hàng còn đủ (5 chì, 4 vở, 6 mực) — chắc chắn mua được.' },
    { sec: 'Tự luận', name: 'Câu 8c', pts: 0.125,
      text: 'Minh mua 3 bút chì, 2 bút mực, 3 quyển vở; Hải mua 1 bút chì, 3 bút mực, 2 quyển vở.', img: A + 'd8c8.png',
      opts: KN, ans: 'C', why: 'Cần 3 + 2 = 5 quyển vở nhưng kệ chỉ có 4 — không thể.' },
    { sec: 'Tự luận', name: 'Câu 8d', pts: 0.125,
      text: 'Cả 2 bạn mua tổng cộng 4 bút chì, 4 bút mực, 2 quyển vở.', img: A + 'd8c8.png',
      opts: KN, ans: 'B', why: 'Kệ còn đủ số lượng đó nên có thể xảy ra.' },
    { sec: 'Tự luận', name: 'Câu 9', pts: 0.5,
      text: 'Mẹ Lan đem 90 nghìn đồng đi chợ, mẹ Lan mua thịt hết 32 nghìn đồng, mua cá hết 14 nghìn đồng, mua rau hết 2 nghìn đồng. Hỏi mẹ Lan còn lại bao nhiêu tiền?',
      opts: o4('42 nghìn đồng', '44 nghìn đồng', '32 nghìn đồng', '52 nghìn đồng'), ans: 'A',
      why: '90 − 32 − 14 − 2 = 42 (nghìn đồng).' },
  ],
},
/* ================================================== ĐỀ 9 ================================================== */
{
  id: 9, title: 'Đề 9', time: 35,
  questions: [
    { sec: 'Trắc nghiệm', name: 'Câu 1a', pts: 0.5,
      text: 'Kết quả của phép tính 5 × 5 =',
      opts: o4('9', '20', '25', '15'), ans: 'C', why: '5 × 5 = 25.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1b', pts: 0.5,
      text: '5 × … = 10 : 2. Số thích hợp điền vào chỗ chấm là:',
      opts: o4('1', '2', '3', '4'), ans: 'A', why: '10 : 2 = 5, mà 5 × 1 = 5.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1c', pts: 0.5,
      text: 'Một cái xe đạp có 2 bánh. Hỏi 8 cái xe đạp có mấy bánh?',
      opts: o4('8', '16', '10', '14'), ans: 'B', why: '2 × 8 = 16 (bánh xe).' },
    { sec: 'Trắc nghiệm', name: 'Câu 1d', pts: 0.5,
      text: 'Số 203 đọc là:',
      opts: o4('Hai không ba', 'Hai mươi ba', 'Hai trăm ninh ba', 'Hai trăm linh ba'), ans: 'D',
      why: '203 đọc là “Hai trăm linh ba”.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1e', pts: 0.5,
      text: 'Số? 1m = …..cm',
      opts: o4('10', '100', '20', '1000'), ans: 'B', why: '1m = 100cm.' },
    { sec: 'Tự luận', name: 'Câu 2a', pts: 0.17,
      text: 'Điền số thích hợp: 3m 6cm = ……cm',
      opts: o4('306', '36', '360', '63'), ans: 'A', why: '3m = 300cm; 300 + 6 = 306cm.' },
    { sec: 'Tự luận', name: 'Câu 2b', pts: 0.17,
      text: '5dm 6cm = ……cm',
      opts: o4('56', '506', '65', '560'), ans: 'A', why: '5dm = 50cm; 50 + 6 = 56cm.' },
    { sec: 'Tự luận', name: 'Câu 2c', pts: 0.17,
      text: '200cm = ……m',
      opts: o4('2', '20', '200', '4'), ans: 'A', why: '200cm = 2m.' },
    { sec: 'Tự luận', name: 'Câu 2d', pts: 0.17,
      text: '5000m = ……km',
      opts: o4('5', '50', '500', '2'), ans: 'A', why: '5000m = 5km.' },
    { sec: 'Tự luận', name: 'Câu 2e', pts: 0.16,
      text: '5m 2cm = ……cm',
      opts: o4('502', '52', '520', '250'), ans: 'A', why: '5m = 500cm; 500 + 2 = 502cm.' },
    { sec: 'Tự luận', name: 'Câu 2f', pts: 0.16,
      text: '50dm + 5m = ……m',
      opts: o4('10', '55', '505', '100'), ans: 'A', why: '50dm = 5m; 5 + 5 = 10m.' },
    { sec: 'Tự luận', name: 'Câu 3a', pts: 0.25,
      text: 'Giúp các bạn chọn hộp quà có kết quả đúng: 5000 − 3000 − 2000 + 4 = ?', img: A + 'd9c3.png',
      opts: o4('4', '40', '27', '8'), ans: 'A', why: '5000 − 3000 = 2000; 2000 − 2000 = 0; 0 + 4 = 4.' },
    { sec: 'Tự luận', name: 'Câu 3b', pts: 0.25,
      text: '“5 nhân 9 rồi bớt 18” bằng:', img: A + 'd9c3.png',
      opts: o4('27', '45', '40', '8'), ans: 'A', why: '5 × 9 = 45; 45 − 18 = 27.' },
    { sec: 'Tự luận', name: 'Câu 3c', pts: 0.25,
      text: '“26 cộng 14 rồi chia cho 5” bằng:', img: A + 'd9c3.png',
      opts: o4('8', '40', '27', '4'), ans: 'A', why: '26 + 14 = 40; 40 : 5 = 8.' },
    { sec: 'Tự luận', name: 'Câu 3d', pts: 0.25,
      text: '“5 nhân với tích của 2 và 4” bằng:', img: A + 'd9c3.png',
      opts: o4('40', '13', '8', '27'), ans: 'A', why: 'Tích của 2 và 4 là 8; 5 × 8 = 40.' },
    { sec: 'Tự luận', name: 'Câu 4a', pts: 0.5,
      text: 'Đặt tính rồi tính: 257 + 124 = ?',
      opts: o4('381', '371', '391', '133'), ans: 'A', why: '257 + 124 = 381.' },
    { sec: 'Tự luận', name: 'Câu 4b', pts: 0.5,
      text: 'Đặt tính rồi tính: 553 + 356 = ?',
      opts: o4('909', '899', '919', '197'), ans: 'A', why: '553 + 356 = 909.' },
    { sec: 'Tự luận', name: 'Câu 4c', pts: 0.5,
      text: 'Đặt tính rồi tính: 446 − 217 = ?',
      opts: o4('229', '239', '219', '663'), ans: 'A', why: '446 − 217 = 229.' },
    { sec: 'Tự luận', name: 'Câu 4d', pts: 0.5,
      text: 'Đặt tính rồi tính: 967 − 85 = ?',
      opts: o4('882', '892', '872', '1052'), ans: 'A', why: '967 − 85 = 882.' },
    { sec: 'Tự luận', name: 'Câu 5', pts: 1,
      text: 'Nam có 20 chiếc kẹo. Nam đem chia đều cho mọi người trong nhà. Nhà Nam gồm có bố, mẹ, chị, Nam và em của Nam. Hỏi mỗi người được mấy cái kẹo?',
      opts: o4('4 cái kẹo', '5 cái kẹo', '15 cái kẹo', '25 cái kẹo'), ans: 'A',
      why: 'Nhà Nam có 5 người: 20 : 5 = 4 (cái kẹo).' },
    { sec: 'Tự luận', name: 'Câu 6a', pts: 0.5,
      text: 'Hãy vẽ thêm một đoạn thẳng trong hình vẽ để được 3 hình tam giác và 3 hình tứ giác. Cách vẽ đúng là:', img: A + 'd9c6a.svg',
      opts: o4('Vẽ 1 đoạn thẳng trong tam giác bên phải, từ đỉnh trên xuống cạnh đáy', 'Vẽ 1 đoạn thẳng song song với đáy hình', 'Vẽ đường chéo trong tứ giác bên trái', 'Không thể vẽ được'), ans: 'A',
      why: 'Chia tam giác phải thành 2 tam giác nhỏ → có 2 tam giác nhỏ + 1 tam giác gốc = 3 tam giác; tứ giác trái + (tứ giác trái ghép tam giác kề) + cả hình = 3 tứ giác.' },
    { sec: 'Tự luận', name: 'Câu 6b', pts: 0.5,
      text: 'Cho đường gấp khúc ABCDE. Đoạn thẳng AB = 12cm, đoạn thẳng BC = 6cm, đoạn thẳng CD = DE = 8cm. Một con kiến vàng bò từ A đến E. Hỏi con kiến đã bò được đoạn đường dài bao nhiêu xăng-ti-mét?', img: A + 'd9c6b.svg',
      opts: o4('34cm', '26cm', '28cm', '36cm'), ans: 'A',
      why: '12 + 6 + 8 + 8 = 34 (cm).' },
    { sec: 'Tự luận', name: 'Câu 6c-1', pts: 0.125,
      text: 'Hình phù hợp điền vào dấu hỏi là hình gì?', imgs: [A + 'd9pat1.svg', A + 'd9pat1o.svg'],
      opts: o3('Hình A (khối trụ xanh lá)', 'Hình B (khối cầu đỏ)', 'Hình C (khối cầu xanh)'), ans: 'A',
      why: 'Quy luật lặp lại: trụ, trụ, cầu. Sau 2 nhóm và 1 khối trụ, hình tiếp theo là khối trụ.' },
    { sec: 'Tự luận', name: 'Câu 6c-2', pts: 0.125,
      text: 'Hình phù hợp điền vào dấu hỏi là hình gì?', imgs: [A + 'd9pat2.svg', A + 'd9pat2o.svg'],
      opts: o3('Hình A (khối trụ xanh dương)', 'Hình B (khối cầu vàng)', 'Hình C (khối cầu xanh lá)'), ans: 'C',
      why: 'Quy luật lặp lại nhóm 4: cầu xanh lá, cầu xanh dương, cầu vàng, khối trụ. Sau 2 nhóm, hình tiếp theo là khối cầu xanh lá.' },
    { sec: 'Tự luận', name: 'Câu 7a-1', pts: 0.125,
      text: 'Quan sát bể cá: Có bao nhiêu con cá màu cam?', img: A + 'd9aqua.png',
      opts: o4('6', '5', '7', '4'), ans: 'A', why: 'Đếm được 6 con cá màu cam (4 bên trái, 2 bên phải).' },
    { sec: 'Tự luận', name: 'Câu 7a-2', pts: 0.125,
      text: 'Có bao nhiêu con cá màu vàng?', img: A + 'd9aqua.png',
      opts: o4('6', '5', '7', '4'), ans: 'A', why: 'Đếm được 6 con cá màu vàng (5 con bơi theo đàn + 1 con cạnh hòn đá).' },
    { sec: 'Tự luận', name: 'Câu 7b', pts: 0.25,
      text: 'Có tất cả bao nhiêu con cá?', img: A + 'd9aqua.png',
      opts: o4('12', '11', '13', '10'), ans: 'A', why: '6 + 6 = 12 (con cá).' },
    { sec: 'Tự luận', name: 'Câu 7c', pts: 0.25,
      text: 'Hãy so sánh số cá màu vàng và số cá màu cam:', img: A + 'd9aqua.png',
      opts: o4('Số cá màu vàng bằng số cá màu cam', 'Cá vàng nhiều hơn cá cam', 'Cá cam nhiều hơn cá vàng', 'Không so sánh được'), ans: 'A',
      why: 'Cả hai loại đều có 6 con: 6 = 6.' },
    { sec: 'Tự luận', name: 'Câu 8', pts: 0.5,
      text: 'Một số nhân với 2 rồi cộng thêm 17 thì được 29. Tìm số ban đầu.',
      opts: o4('6', '12', '23', '8'), ans: 'A',
      why: '29 − 17 = 12; 12 : 2 = 6. Số ban đầu là 6.' },
  ],
},
/* ================================================== ĐỀ 10 ================================================== */
{
  id: 10, title: 'Đề 10', time: 35,
  questions: [
    { sec: 'Trắc nghiệm', name: 'Câu 1a', pts: 0.5,
      text: 'Số cần điền vào chỗ chấm 5 × 7 = …… là:',
      opts: o4('20', '35', '25', '11'), ans: 'B', why: '5 × 7 = 35.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1b', pts: 0.5,
      text: 'Lớp em có 40 bạn, xếp đều thành 5 hàng. Hỏi mỗi hàng có bao nhiêu bạn?',
      opts: o4('10 bạn', '9 bạn', '8 bạn', '7 bạn'), ans: 'C', why: '40 : 5 = 8 (bạn).' },
    { sec: 'Trắc nghiệm', name: 'Câu 1c', pts: 0.25,
      text: 'Số cần điền vào dấu ? trong phép tính: ? : 2 = 9 là:',
      opts: o4('12', '5', '36', '18'), ans: 'D', why: '9 × 2 = 18.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1d', pts: 0.25,
      text: 'Các số tròn chục nằm giữa 254 và 320 là:',
      opts: o4('260; 270; 280; 290; 300; 310', '260; 270; 280; 290', '250; 260; 270; 280; 290; 300', '260; 280; 300; 320'), ans: 'A',
      why: 'Các số tròn chục lớn hơn 254 và bé hơn 320: 260, 270, 280, 290, 300, 310.' },
    { sec: 'Trắc nghiệm', name: 'Câu 1e', pts: 0.25,
      text: 'Hiệu của số lớn nhất có ba chữ số và số bé nhất có ba chữ số là:',
      opts: o4('899', '888', '800', '999'), ans: 'A', why: '999 − 100 = 899.' },
    { sec: 'Tự luận', name: 'Câu 2a', pts: 0.125,
      text: 'Đúng ghi Đ, sai ghi S: “Bạn Lâm cao khoảng 120cm.”',
      opts: DS, ans: 'A', why: 'Đúng — học sinh lớp 2 cao khoảng 120cm.' },
    { sec: 'Tự luận', name: 'Câu 2b', pts: 0.125,
      text: '“28m + 17m = 35m”',
      opts: DS, ans: 'B', why: 'Sai — 28 + 17 = 45m.' },
    { sec: 'Tự luận', name: 'Câu 2c', pts: 0.125,
      text: '“Một bước chân của em dài khoảng 3m.”',
      opts: DS, ans: 'B', why: 'Sai — một bước chân chỉ dài khoảng 3dm.' },
    { sec: 'Tự luận', name: 'Câu 2d', pts: 0.125,
      text: '“1000 m = 1km”',
      opts: DS, ans: 'A', why: 'Đúng — 1km = 1000m.' },
    { sec: 'Tự luận', name: 'Câu 2e', pts: 0.125,
      text: 'Một cửa hàng trong một tuần bán được 645m vải hoa. Số mét vải hoa đã bán nhiều hơn vải trắng là 243m. Vậy cửa hàng đó đã bán được: “888m vải trắng”',
      opts: DS, ans: 'B', why: 'Sai — vải trắng: 645 − 243 = 402m.' },
    { sec: 'Tự luận', name: 'Câu 2f', pts: 0.125,
      text: 'Cửa hàng đó đã bán được: “402m vải trắng”',
      opts: DS, ans: 'A', why: 'Đúng — 645 − 243 = 402 (m).' },
    { sec: 'Tự luận', name: 'Câu 3a', pts: 0.5,
      text: 'Tính: 900 − 600 − 30 = ?',
      opts: o4('270', '300', '330', '260'), ans: 'A', why: '900 − 600 = 300; 300 − 30 = 270.' },
    { sec: 'Tự luận', name: 'Câu 3b', pts: 0.5,
      text: 'Tính: 994 − 378 + 135 = ?',
      opts: o4('751', '741', '761', '481'), ans: 'A', why: '994 − 378 = 616; 616 + 135 = 751.' },
    { sec: 'Tự luận', name: 'Câu 3c', pts: 0.5,
      text: 'Tính: 304 + 27 − 171 = ?',
      opts: o4('160', '150', '170', '210'), ans: 'A', why: '304 + 27 = 331; 331 − 171 = 160.' },
    { sec: 'Tự luận', name: 'Câu 4a', pts: 0.5,
      text: 'Đặt tính rồi tính: 453 + 38 = ?',
      opts: o4('491', '481', '501', '415'), ans: 'A', why: '453 + 38 = 491.' },
    { sec: 'Tự luận', name: 'Câu 4b', pts: 0.5,
      text: 'Đặt tính rồi tính: 246 + 460 = ?',
      opts: o4('706', '696', '716', '214'), ans: 'A', why: '246 + 460 = 706.' },
    { sec: 'Tự luận', name: 'Câu 4c', pts: 0.5,
      text: 'Đặt tính rồi tính: 744 − 54 = ?',
      opts: o4('690', '700', '680', '750'), ans: 'A', why: '744 − 54 = 690.' },
    { sec: 'Tự luận', name: 'Câu 4d', pts: 0.5,
      text: 'Đặt tính rồi tính: 675 − 594 = ?',
      opts: o4('81', '91', '71', '181'), ans: 'A', why: '675 − 594 = 81.' },
    { sec: 'Tự luận', name: 'Câu 5', pts: 1,
      text: 'Bao cà phê cân nặng 50kg, 5 bao hạt tiêu cân nặng bằng một bao cà phê. Hỏi bao hạt tiêu cân nặng bao nhiêu ki-lô-gam?',
      opts: o4('10kg', '45kg', '55kg', '250kg'), ans: 'A',
      why: '50 : 5 = 10 (kg).' },
    { sec: 'Tự luận', name: 'Câu 6a-1', pts: 0.25,
      text: 'Hình bên có bao nhiêu hình tứ giác?', img: A + 'd10c6a.svg',
      opts: o4('2', '3', '4', '1'), ans: 'A',
      why: 'Cả hình lớn và hình ghép (tứ giác trái + tam giác giữa) — 2 hình tứ giác.' },
    { sec: 'Tự luận', name: 'Câu 6a-2', pts: 0.25,
      text: 'Hình bên có bao nhiêu hình tam giác?', img: A + 'd10c6a.svg',
      opts: o4('4', '3', '5', '6'), ans: 'A',
      why: '3 tam giác đơn + 1 tam giác ghép (2 tam giác bên phải) = 4 hình tam giác.' },
    { sec: 'Tự luận', name: 'Câu 6b', pts: 0.5,
      text: 'Quan sát hình vẽ và nối hình ở cột A với số thích hợp ở cột B (khối cầu, khối trụ, khối lập phương, khối hộp chữ nhật — các số: 2, 3, 10, 14):', img: A + 'd10c6b.png',
      opts: o4('Cầu–2, Trụ–3, Lập phương–14, Hộp chữ nhật–10', 'Cầu–3, Trụ–2, Lập phương–10, Hộp chữ nhật–14', 'Cầu–2, Trụ–3, Lập phương–10, Hộp chữ nhật–14', 'Cầu–2, Trụ–10, Lập phương–3, Hộp chữ nhật–14'), ans: 'A',
      why: 'Có 2 khối cầu (bóng đỏ), 3 khối trụ (cột vàng), 14 khối lập phương và 10 khối hộp chữ nhật.' },
    { sec: 'Tự luận', name: 'Câu 7-1', pts: 0.125,
      text: 'Đếm và khoanh vào số phù hợp: Có bao nhiêu con cá?', img: A + 'd10c7.png',
      opts: o4('4', '5', '6', '7'), ans: 'B', why: 'Đếm được 5 con cá (2 + 3).' },
    { sec: 'Tự luận', name: 'Câu 7-2', pts: 0.125,
      text: 'Có bao nhiêu cái cốc?', img: A + 'd10c7.png',
      opts: o4('6', '7', '8', '9'), ans: 'C', why: 'Đếm được 8 cái cốc (4 + 4).' },
    { sec: 'Tự luận', name: 'Câu 7-3', pts: 0.125,
      text: 'Có bao nhiêu cái cây?', img: A + 'd10c7.png',
      opts: o4('1', '2', '3', '4'), ans: 'C', why: 'Đếm được 3 cái cây.' },
    { sec: 'Tự luận', name: 'Câu 7-4', pts: 0.125,
      text: 'Có bao nhiêu mặt trời?', img: A + 'd10c7.png',
      opts: o4('5', '6', '7', '8'), ans: 'B', why: 'Đếm được 6 mặt trời (3 + 3).' },
    { sec: 'Tự luận', name: 'Câu 7a', pts: 0.5,
      text: 'Vật có số lượng nhiều nhất và vật có số lượng ít nhất là:', img: A + 'd10c7.png',
      opts: o4('Cái cốc nhiều nhất, cái cây ít nhất', 'Mặt trời nhiều nhất, con cá ít nhất', 'Cái cốc nhiều nhất, con cá ít nhất', 'Con cá nhiều nhất, cái cây ít nhất'), ans: 'A',
      why: 'Cốc 8 cái (nhiều nhất); cây 3 cái (ít nhất).' },
    { sec: 'Tự luận', name: 'Câu 7b', pts: 0.5,
      text: 'Số mặt trời nhiều hơn số cây là:', img: A + 'd10c7.png',
      opts: o4('3', '2', '4', '6'), ans: 'A', why: '6 − 3 = 3.' },
    { sec: 'Tự luận', name: 'Câu 8a', pts: 0.17,
      text: 'Chọn từ chắc chắn, có thể hoặc không thể: “Nếu em không ôn bài kĩ …… em sẽ không đạt điểm cao trong kì thi sắp tới.”',
      opts: KN, ans: 'A', why: 'Không ôn bài kĩ thì chắc chắn không đạt điểm cao.' },
    { sec: 'Tự luận', name: 'Câu 8b', pts: 0.17,
      text: '“Bầu trời âm u, …… trời sắp mưa.”',
      opts: KN, ans: 'B', why: 'Trời âm u thì có thể sắp mưa (không chắc chắn).' },
    { sec: 'Tự luận', name: 'Câu 8c', pts: 0.16,
      text: '“Em bé …… lấy quyển truyện trên giá sách cao.”',
      opts: KN, ans: 'C', why: 'Em bé thấp nên không thể với tới giá sách cao.' },
  ],
},
];

const SUBJECTS = [
  { id: 'toan', name: 'Toán', short: 'Toán 2 CK2', icon: '∑', grade: 2, sem: 2, exams: EXAMS, ready: true,
    heroTitle: 'Đề kiểm tra chất lượng cuối học kì 2',
    heroMeta: '📚 10 đề &nbsp;•&nbsp; ⏱ 35 phút mỗi đề &nbsp;•&nbsp; đề gốc chuyển thể trắc nghiệm' },
  // 'tuduy' được chèn vào vị trí thứ 2 bởi data-tuduy.js
  { id: 'tviet', name: 'Tiếng Việt', icon: '✎', ready: false },
  { id: 'tanh', name: 'Tiếng Anh', icon: 'A', ready: false },
  { id: 'tnxh', name: 'TN&XH', icon: '❀', ready: false },
];
