// Bồi dưỡng học sinh giỏi Toán lớp 2 — 15 đề chuyên đề × 8 câu = 120 câu.
// Mức độ: HSG cấp trường / cấp huyện (nâng cao vừa phải, bám chương trình lớp 2 — phạm vi 1000,
// bảng nhân chia 2–9, đo lường, thời gian, hình học phẳng cơ bản; riêng × 2 và : 2 được
// phép vượt ra ngoài phạm vi bảng).
// Nguồn tham khảo dạng bài: "80 bài Toán ôn luyện HSG lớp 2" (VnDoc), tuyển tập đề thi HSG Toán 2
// (ThuVienDeThi), 25 đề Toán nâng cao lớp 2 (HocTot), chuyên đề Toán nâng cao lớp 2 (Monkey);
// một số dạng suy luận tham khảo đề Kangaroo Pre-Ecolier & SASMO Primary 2 nhưng đã hạ độ khó
// và Việt hoá cho phù hợp học sinh lớp 2 Việt Nam.
// Toàn bộ câu hỏi được biên soạn lại, có lời giải chi tiết. Hình vẽ lại bằng SVG trong assets/hsg2/.

const HS = 'assets/hsg2/';

const HSG2_EXAMS = [

/* ============ ĐỀ 1 — SỐ VÀ CẤU TẠO SỐ ============ */
{
  id: 601, title: 'Đề 1 · Số và cấu tạo số', time: 30,
  questions: [
    { sec: 'Cấu tạo số', name: 'Câu 1', pts: 1.25,
      text: 'Số lớn nhất có hai chữ số mà <b>tổng hai chữ số của nó bằng 8</b> là số nào?',
      opts: o4('71', '80', '62', '44'), ans: 'B',
      why: 'Muốn số lớn nhất thì chữ số hàng chục phải lớn nhất. Chữ số hàng chục lớn nhất có thể lấy là 8 (vì 8 + 0 = 8). Vậy số cần tìm là 80.' },
    { sec: 'Cấu tạo số', name: 'Câu 2', pts: 1.25,
      text: 'Có bao nhiêu số có hai chữ số mà <b>chữ số hàng chục trừ chữ số hàng đơn vị bằng 7</b>?',
      opts: o4('3 số', '5 số', '4 số', '2 số'), ans: 'A',
      why: 'Ta có 7 − 0 = 7; 8 − 1 = 7; 9 − 2 = 7. Các số đó là 70; 81; 92. Vậy có 3 số.' },
    { sec: 'Lập số', name: 'Câu 3', pts: 1.25,
      text: 'Từ ba chữ số <b>0; 3; 5</b> viết được bao nhiêu số có hai chữ số <b>khác nhau</b>?',
      opts: o4('6 số', '3 số', '4 số', '5 số'), ans: 'C',
      why: 'Chữ số 0 không được đứng ở hàng chục. Các số viết được là: 30; 35; 50; 53. Vậy có 4 số.' },
    { sec: 'Tìm số', name: 'Câu 4', pts: 1.25,
      text: 'Một số có hai chữ số. Tổng hai chữ số bằng 9, chữ số hàng chục hơn chữ số hàng đơn vị 3 đơn vị. Tìm số đó.',
      opts: o4('36', '54', '72', '63'), ans: 'D',
      why: 'Chữ số hàng chục là: (9 + 3) : 2 = 6. Chữ số hàng đơn vị là: 9 − 6 = 3. Vậy số cần tìm là 63.' },
    { sec: 'Đếm chữ số', name: 'Câu 5', pts: 1.25,
      text: 'Khi viết các số từ 1 đến 20, chữ số <b>1</b> được viết bao nhiêu lần?',
      opts: o4('12 lần', '11 lần', '13 lần', '10 lần'), ans: 'A',
      why: 'Ở hàng đơn vị có số 1 và số 11 → 2 lần. Ở hàng chục, mười số 10; 11; 12; …; 19 đều có chữ số 1 → 10 lần. Tất cả: 2 + 10 = 12 lần.' },
    { sec: 'So sánh', name: 'Câu 6', pts: 1.25,
      text: 'Tổng của <b>số lớn nhất có hai chữ số</b> và <b>số bé nhất có hai chữ số</b> bằng bao nhiêu?',
      opts: o4('108', '110', '109', '99'), ans: 'C',
      why: 'Số lớn nhất có hai chữ số là 99, số bé nhất có hai chữ số là 10. Tổng là: 99 + 10 = 109.' },
    { sec: 'Điền chữ số', name: 'Câu 7', pts: 1.25,
      text: 'Thay dấu <b>*</b> bằng chữ số thích hợp để <b>32 &lt; 3* &lt; 35</b>. Có mấy cách thay?',
      opts: o4('3 cách', '2 cách', '4 cách', '1 cách'), ans: 'B',
      why: 'Số phải lớn hơn 32 và bé hơn 35 nên chỉ có thể là 33 hoặc 34. Vậy có 2 cách thay: * = 3 hoặc * = 4.' },
    { sec: 'Cấu tạo số', name: 'Câu 8', pts: 1.25,
      text: 'Số <b>78</b> thay đổi thế nào nếu ta đổi chỗ hai chữ số của nó?',
      opts: o4('Giảm 9 đơn vị', 'Tăng 19 đơn vị', 'Không thay đổi', 'Tăng 9 đơn vị'), ans: 'D',
      why: 'Đổi chỗ hai chữ số ta được số 87. Ta có 87 − 78 = 9, nên số đó tăng thêm 9 đơn vị.' },
  ],
},

/* ============ ĐỀ 2 — DÃY SỐ VÀ QUY LUẬT ============ */
{
  id: 602, title: 'Đề 2 · Dãy số và quy luật', time: 30,
  questions: [
    { sec: 'Điền số', name: 'Câu 1', pts: 1.25,
      text: 'Điền số thích hợp vào chỗ chấm: <b>1; 4; 7; 10; …; 16</b>',
      opts: o4('12', '14', '13', '11'), ans: 'C',
      why: 'Mỗi số hơn số liền trước 3 đơn vị (1 + 3 = 4; 4 + 3 = 7; …). Vậy số cần điền là 10 + 3 = 13 (và 13 + 3 = 16, đúng).' },
    { sec: 'Quy luật', name: 'Câu 2', pts: 1.25,
      text: 'Cho dãy số: <b>1; 2; 4; 7; 11; …</b> Số tiếp theo của dãy là số nào?',
      opts: o4('15', '16', '17', '14'), ans: 'B',
      why: 'Khoảng cách giữa các số tăng dần: +1; +2; +3; +4. Vậy số tiếp theo hơn 11 là 5 đơn vị: 11 + 5 = 16.' },
    { sec: 'Quy luật', name: 'Câu 3', pts: 1.25,
      text: 'Cho dãy số: <b>1; 2; 4; 8; 16; …</b> Số tiếp theo của dãy là số nào?',
      opts: o4('24', '30', '20', '32'), ans: 'D',
      why: 'Mỗi số bằng số liền trước gấp đôi lên (1 × 2 = 2; 2 × 2 = 4; …). Vậy số tiếp theo là 16 × 2 = 32.' },
    { sec: 'Số hạng thứ n', name: 'Câu 4', pts: 1.25,
      text: 'Cho dãy các số lẻ: <b>1; 3; 5; 7; …</b> Số hạng thứ <b>10</b> của dãy là số nào?',
      opts: o4('19', '21', '17', '20'), ans: 'A',
      why: 'Từ số hạng thứ nhất đến số hạng thứ 10 phải cộng thêm 9 lần, mỗi lần 2 đơn vị: 1 + 9 × 2 = 1 + 18 = 19.' },
    { sec: 'Vị trí số hạng', name: 'Câu 5', pts: 1.25,
      text: 'Cho dãy số: <b>5; 10; 15; 20; …</b> Số <b>45</b> là số hạng thứ mấy của dãy?',
      opts: o4('Thứ 8', 'Thứ 9', 'Thứ 10', 'Thứ 7'), ans: 'B',
      why: 'Dãy gồm các số 5 × 1; 5 × 2; 5 × 3; … Vì 45 = 5 × 9 nên 45 là số hạng thứ 9.' },
    { sec: 'Đếm số hạng', name: 'Câu 6', pts: 1.25,
      text: 'Dãy số <b>90; 80; 70; …; 20; 10</b> có bao nhiêu số hạng?',
      opts: o4('9 số', '8 số', '10 số', '11 số'), ans: 'A',
      why: 'Các số hạng là 90; 80; 70; 60; 50; 40; 30; 20; 10. Đếm được 9 số hạng.' },
    { sec: 'Quy luật hình', name: 'Câu 7', pts: 1.25,
      text: 'Các hình được xếp theo quy luật:<br><b>🔴 🔵 🔵 🔴 🔵 🔵 🔴 🔵 🔵 …</b><br>Hình thứ <b>10</b> là hình nào?',
      opts: o4('Hình tròn xanh 🔵', 'Không xác định được', 'Hình tròn đỏ 🔴', 'Hình tròn vàng 🟡'), ans: 'C',
      why: 'Cứ 3 hình lại lặp lại một lần: đỏ – xanh – xanh. Ta có 10 = 3 + 3 + 3 + 1, tức hình thứ 10 là hình đầu tiên của nhóm thứ tư. Vậy đó là hình tròn đỏ 🔴.' },
    { sec: 'Quy luật', name: 'Câu 8', pts: 1.25,
      text: 'Trong dãy sau, mỗi số (kể từ số thứ ba) bằng tổng hai số đứng ngay trước nó:<br><b>1; 1; 2; 3; 5; 8; ❓</b><br>Số cần điền vào ô ❓ là số nào?',
      opts: o4('11', '12', '14', '13'), ans: 'D',
      why: 'Kiểm tra quy luật: 1 + 1 = 2; 1 + 2 = 3; 2 + 3 = 5; 3 + 5 = 8. Vậy số cần điền là 5 + 8 = 13.' },
  ],
},

/* ============ ĐỀ 3 — TÍNH NHANH, TÍNH NHẨM ============ */
{
  id: 603, title: 'Đề 3 · Tính nhanh — tính nhẩm', time: 30,
  questions: [
    { sec: 'Tính nhanh', name: 'Câu 1', pts: 1.25,
      text: 'Tính nhanh: <b>1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9</b>',
      opts: o4('45', '40', '50', '44'), ans: 'A',
      why: 'Ghép cặp: (1 + 9) + (2 + 8) + (3 + 7) + (4 + 6) + 5 = 10 + 10 + 10 + 10 + 5 = 45.' },
    { sec: 'Tính nhanh', name: 'Câu 2', pts: 1.25,
      text: 'Tính nhanh: <b>2 + 4 + 6 + 8 + 10 + 12 + 14 + 16 + 18</b>',
      opts: o4('80', '100', '90', '72'), ans: 'C',
      why: 'Ghép cặp từ hai đầu: (2 + 18); (4 + 16); (6 + 14); (8 + 12) — mỗi cặp bằng 20, còn lẻ số 10 ở giữa. Tổng: 20 × 4 + 10 = 80 + 10 = 90.' },
    { sec: 'Tính nhanh', name: 'Câu 3', pts: 1.25,
      text: 'Tính nhanh: <b>11 + 12 + 13 + 14 + 15 + 16 + 17 + 18 + 19</b>',
      opts: o4('130', '135', '145', '125'), ans: 'B',
      why: 'Ghép cặp hai đầu: (11 + 19) + (12 + 18) + (13 + 17) + (14 + 16) + 15 = 30 + 30 + 30 + 30 + 15 = 135.' },
    { sec: 'Tính nhanh', name: 'Câu 4', pts: 1.25,
      text: 'Tính nhanh: <b>47 + 25 + 53</b>',
      opts: o4('115', '120', '135', '125'), ans: 'D',
      why: 'Ghép hai số tròn trăm trước: (47 + 53) + 25 = 100 + 25 = 125.' },
    { sec: 'Tính nhanh', name: 'Câu 5', pts: 1.25,
      text: 'Tính nhanh: <b>100 − 1 − 2 − 3 − 4</b>',
      opts: o4('92', '88', '90', '94'), ans: 'C',
      why: 'Trừ liên tiếp cũng là trừ đi tổng: 1 + 2 + 3 + 4 = 10. Vậy kết quả là 100 − 10 = 90.' },
    { sec: 'Tính nhanh', name: 'Câu 6', pts: 1.25,
      text: 'Tính nhanh: <b>25 + 37 + 75 + 63</b>',
      opts: o4('190', '200', '210', '180'), ans: 'B',
      why: 'Ghép cặp cho tròn trăm: (25 + 75) + (37 + 63) = 100 + 100 = 200.' },
    { sec: 'Tính nhanh', name: 'Câu 7', pts: 1.25,
      text: 'Tính nhanh: <b>5 × 4 + 5 × 6</b>',
      opts: o4('40', '45', '55', '50'), ans: 'D',
      why: 'Cả hai tích đều có thừa số 5 nên: 5 × 4 + 5 × 6 = 5 × (4 + 6) = 5 × 10 = 50.' },
    { sec: 'Tính khéo', name: 'Câu 8', pts: 1.25,
      text: 'Biết <b>36 + 24 = 60</b>. Không cần đặt tính, hãy cho biết <b>36 + 25</b> bằng bao nhiêu?',
      opts: o4('61', '60', '62', '59'), ans: 'A',
      why: 'Số hạng thứ hai tăng thêm 1 đơn vị (từ 24 lên 25) nên tổng cũng tăng thêm 1 đơn vị: 60 + 1 = 61.' },
  ],
},

/* ============ ĐỀ 4 — TÌM X · TÍNH NGƯỢC TỪ CUỐI ============ */
{
  id: 604, title: 'Đề 4 · Tìm x — tính ngược từ cuối', time: 30,
  questions: [
    { sec: 'Tìm x', name: 'Câu 1', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>x + 27 = 45 + 15</b>',
      opts: o4('28', '33', '38', '23'), ans: 'B',
      why: 'Trước hết tính vế phải: 45 + 15 = 60. Ta có x + 27 = 60 nên x = 60 − 27 = 33.' },
    { sec: 'Tìm x', name: 'Câu 2', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>72 − x = 18 + 24</b>',
      opts: o4('30', '28', '32', '34'), ans: 'A',
      why: 'Vế phải: 18 + 24 = 42. Ta có 72 − x = 42 nên x = 72 − 42 = 30.' },
    { sec: 'Tìm x', name: 'Câu 3', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>x × 7 = 63</b>',
      opts: o4('7', '8', '9', '56'), ans: 'C',
      why: 'Muốn tìm thừa số chưa biết ta lấy tích chia cho thừa số đã biết: x = 63 : 7 = 9. Thử lại: 9 × 7 = 63.' },
    { sec: 'Tìm x', name: 'Câu 4', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>x : 5 = 6</b>',
      opts: o4('11', '25', '35', '30'), ans: 'D',
      why: 'Muốn tìm số bị chia ta lấy thương nhân với số chia: x = 6 × 5 = 30.' },
    { sec: 'Tính ngược', name: 'Câu 5', pts: 1.25,
      text: 'Em nghĩ ra một số, đem cộng số đó với 15 rồi trừ đi 8 thì được 20. Hỏi số em nghĩ là số nào?',
      opts: o4('13', '27', '12', '23'), ans: 'A',
      why: 'Làm ngược lại từ cuối: trước khi trừ 8 thì được 20 + 8 = 28. Trước khi cộng 15 thì số đó là 28 − 15 = 13.' },
    { sec: 'Tính ngược', name: 'Câu 6', pts: 1.25,
      text: 'Một số đem nhân với 7 rồi cộng thêm 6 thì được 62. Hỏi số đó là số nào?',
      opts: o4('6', '7', '8', '9'), ans: 'C',
      why: 'Tính ngược từ cuối: 62 − 6 = 56; 56 : 7 = 8. Thử lại: 8 × 7 = 56; 56 + 6 = 62.' },
    { sec: 'Tìm x', name: 'Câu 7', pts: 1.25,
      text: 'Tìm số tự nhiên <b>x lớn nhất</b> sao cho <b>x + 36 &lt; 80</b>.',
      opts: o4('44', '43', '42', '45'), ans: 'B',
      why: 'Ta có 44 + 36 = 80 (không bé hơn 80 nên loại). Với x = 43 thì 43 + 36 = 79 < 80, thoả mãn. Vậy x lớn nhất là 43.' },
    { sec: 'Tính ngược', name: 'Câu 8', pts: 1.25,
      text: 'Mẹ cho Lan một số cái kẹo 🍬. Lan ăn 4 cái rồi cho em 5 cái thì còn lại 9 cái. Hỏi lúc đầu mẹ cho Lan mấy cái kẹo?',
      opts: o4('16 cái', '20 cái', '19 cái', '18 cái'), ans: 'D',
      why: 'Tính ngược từ cuối: trước khi cho em 5 cái, Lan có 9 + 5 = 14 (cái). Trước khi ăn 4 cái, Lan có 14 + 4 = 18 (cái kẹo).' },
  ],
},

/* ============ ĐỀ 5 — TỔNG – HIỆU · NHIỀU HƠN – ÍT HƠN ============ */
{
  id: 605, title: 'Đề 5 · Tổng – hiệu, nhiều hơn – ít hơn', time: 30,
  questions: [
    { sec: 'Toán có lời văn', name: 'Câu 1', pts: 1.25,
      text: 'Hai thùng có tất cả 46 lít dầu. Thùng thứ nhất có 28 lít dầu. Hỏi thùng thứ hai có bao nhiêu lít dầu?',
      opts: o4('22 l', '20 l', '18 l', '16 l'), ans: 'C',
      why: 'Số dầu ở thùng thứ hai là: 46 − 28 = 18 (l).' },
    { sec: 'Nhiều hơn', name: 'Câu 2', pts: 1.25,
      text: 'An có 12 quyển vở, Bình có nhiều hơn An 5 quyển vở. Hỏi cả hai bạn có tất cả bao nhiêu quyển vở?',
      opts: o4('27 quyển', '29 quyển', '24 quyển', '30 quyển'), ans: 'B',
      why: 'Số vở của Bình là: 12 + 5 = 17 (quyển). Cả hai bạn có: 12 + 17 = 29 (quyển vở).' },
    { sec: 'Ít hơn', name: 'Câu 3', pts: 1.25,
      text: 'Lớp 2A có 32 học sinh, ít hơn lớp 2B 4 học sinh. Hỏi cả hai lớp có bao nhiêu học sinh?',
      opts: o4('60 học sinh', '64 học sinh', '72 học sinh', '68 học sinh'), ans: 'D',
      why: 'Lớp 2B có: 32 + 4 = 36 (học sinh). Cả hai lớp có: 32 + 36 = 68 (học sinh).' },
    { sec: 'Tổng không đổi', name: 'Câu 4', pts: 1.25,
      text: 'Hai số có tổng bằng 30. Nếu thêm vào số thứ nhất 5 đơn vị và bớt ở số thứ hai 5 đơn vị thì tổng mới bằng bao nhiêu?',
      opts: o4('30', '35', '25', '40'), ans: 'A',
      why: 'Một số được thêm đúng bằng số kia bị bớt (đều là 5 đơn vị) nên tổng không thay đổi, vẫn bằng 30.' },
    { sec: 'Nhiều hơn', name: 'Câu 5', pts: 1.25,
      text: 'Bao gạo thứ nhất nặng 35 kg, nhiều hơn bao gạo thứ hai 8 kg. Hỏi cả hai bao nặng bao nhiêu ki-lô-gam?',
      opts: o4('70 kg', '62 kg', '58 kg', '60 kg'), ans: 'B',
      why: 'Bao thứ hai nặng: 35 − 8 = 27 (kg). Cả hai bao nặng: 35 + 27 = 62 (kg).' },
    { sec: 'Chia đôi phần hơn', name: 'Câu 6', pts: 1.25,
      text: 'Hùng có nhiều hơn Dũng 8 viên bi. Hỏi Hùng phải cho Dũng mấy viên bi để hai bạn có số bi bằng nhau?',
      opts: o4('4 viên', '8 viên', '2 viên', '6 viên'), ans: 'A',
      why: 'Hùng cho đi bao nhiêu thì Dũng nhận thêm đúng bấy nhiêu, nên phần hơn giảm gấp đôi số bi cho. Hùng chỉ cần cho một nửa phần hơn: 8 : 2 = 4 (viên bi).' },
    { sec: 'Tổng – hiệu', name: 'Câu 7', pts: 1.25,
      text: 'Hai số có tổng bằng 20, số lớn hơn số bé 4 đơn vị. Tìm số lớn.',
      opts: o4('14', '16', '12', '10'), ans: 'C',
      why: 'Số lớn là: (20 + 4) : 2 = 12. (Thử lại: số bé là 20 − 12 = 8, và 12 − 8 = 4, đúng.)' },
    { sec: 'Ít hơn', name: 'Câu 8', pts: 1.25,
      text: 'Mảnh vải xanh dài 24 dm, mảnh vải đỏ ngắn hơn mảnh vải xanh 7 dm. Hỏi cả hai mảnh vải dài bao nhiêu đề-xi-mét?',
      opts: o4('31 dm', '48 dm', '38 dm', '41 dm'), ans: 'D',
      why: 'Mảnh vải đỏ dài: 24 − 7 = 17 (dm). Cả hai mảnh dài: 24 + 17 = 41 (dm).' },
  ],
},

/* ============ ĐỀ 6 — BÀI TOÁN VỀ TUỔI ============ */
{
  id: 606, title: 'Đề 6 · Bài toán về tuổi', time: 30,
  questions: [
    { sec: 'Hiệu số tuổi', name: 'Câu 1', pts: 1.25,
      text: 'Năm nay mẹ 32 tuổi, con 8 tuổi. Hỏi mẹ hơn con bao nhiêu tuổi?',
      opts: o4('24 tuổi', '26 tuổi', '22 tuổi', '40 tuổi'), ans: 'A',
      why: 'Mẹ hơn con số tuổi là: 32 − 8 = 24 (tuổi).' },
    { sec: 'Tuổi sau này', name: 'Câu 2', pts: 1.25,
      text: 'Anh 12 tuổi, em kém anh 4 tuổi. Hỏi 3 năm nữa em bao nhiêu tuổi?',
      opts: o4('9 tuổi', '12 tuổi', '11 tuổi', '15 tuổi'), ans: 'C',
      why: 'Năm nay em: 12 − 4 = 8 (tuổi). Ba năm nữa em: 8 + 3 = 11 (tuổi).' },
    { sec: 'Hiệu không đổi', name: 'Câu 3', pts: 1.25,
      text: 'Năm nay bố 35 tuổi, con 7 tuổi. Hỏi <b>trước đây 3 năm</b> bố hơn con bao nhiêu tuổi?',
      opts: o4('25 tuổi', '28 tuổi', '31 tuổi', '22 tuổi'), ans: 'B',
      why: 'Mỗi năm bố và con đều tăng thêm 1 tuổi nên hiệu số tuổi luôn không đổi. Bố luôn hơn con: 35 − 7 = 28 (tuổi).' },
    { sec: 'Tổng – hiệu tuổi', name: 'Câu 4', pts: 1.25,
      text: 'Tổng số tuổi của hai anh em là 20 tuổi. Anh hơn em 4 tuổi. Hỏi anh bao nhiêu tuổi?',
      opts: o4('14 tuổi', '10 tuổi', '16 tuổi', '12 tuổi'), ans: 'D',
      why: 'Tuổi anh là: (20 + 4) : 2 = 12 (tuổi). Thử lại: tuổi em là 20 − 12 = 8 và 12 − 8 = 4, đúng.' },
    { sec: 'Hiệu không đổi', name: 'Câu 5', pts: 1.25,
      text: 'Năm nay Lan 8 tuổi, chị hơn Lan 5 tuổi. Hỏi khi Lan 12 tuổi thì chị bao nhiêu tuổi?',
      opts: o4('16 tuổi', '18 tuổi', '17 tuổi', '15 tuổi'), ans: 'C',
      why: 'Chị luôn hơn Lan 5 tuổi (hiệu số tuổi không đổi). Khi Lan 12 tuổi thì chị: 12 + 5 = 17 (tuổi).' },
    { sec: 'Tổng ba tuổi', name: 'Câu 6', pts: 1.25,
      text: 'Tổng số tuổi của ông, bố và cháu là 100 tuổi. Tổng số tuổi của ông và bố là 91 tuổi. Hỏi cháu bao nhiêu tuổi?',
      opts: o4('8 tuổi', '9 tuổi', '10 tuổi', '11 tuổi'), ans: 'B',
      why: 'Tuổi cháu bằng tổng tuổi cả ba người trừ đi tổng tuổi ông và bố: 100 − 91 = 9 (tuổi).' },
    { sec: 'Tuổi trước đây', name: 'Câu 7', pts: 1.25,
      text: 'Cách đây 2 năm anh 9 tuổi, em 5 tuổi. Hỏi <b>năm nay</b> tổng số tuổi của hai anh em là bao nhiêu?',
      opts: o4('14 tuổi', '16 tuổi', '20 tuổi', '18 tuổi'), ans: 'D',
      why: 'Năm nay anh: 9 + 2 = 11 (tuổi); em: 5 + 2 = 7 (tuổi). Tổng số tuổi hai anh em: 11 + 7 = 18 (tuổi).' },
    { sec: 'Tuổi', name: 'Câu 8', pts: 1.25,
      text: 'Tuổi con bằng số bé nhất có hai chữ số. Mẹ hơn con 26 tuổi. Hỏi mẹ bao nhiêu tuổi?',
      opts: o4('36 tuổi', '35 tuổi', '38 tuổi', '34 tuổi'), ans: 'A',
      why: 'Số bé nhất có hai chữ số là 10, vậy con 10 tuổi. Tuổi mẹ là: 10 + 26 = 36 (tuổi).' },
  ],
},

/* ============ ĐỀ 7 — NHÂN, CHIA · CHIA ĐỀU VÀ CHIA CÓ DƯ ============ */
{
  id: 607, title: 'Đề 7 · Nhân, chia — chia đều và chia có dư', time: 30,
  questions: [
    { sec: 'Phép nhân', name: 'Câu 1', pts: 1.25,
      text: 'Tổng <b>4 + 4 + 4 + 4 + 4 + 4</b> bằng bao nhiêu?',
      opts: o4('20', '24', '28', '16'), ans: 'B',
      why: 'Có 6 số 4 nên tổng viết được thành tích: 4 × 6 = 24.' },
    { sec: 'Chia đều', name: 'Câu 2', pts: 1.25,
      text: 'Có 48 cái kẹo 🍬 chia đều cho 6 bạn. Hỏi mỗi bạn được mấy cái kẹo?',
      opts: o4('8 cái', '6 cái', '7 cái', '9 cái'), ans: 'A',
      why: 'Mỗi bạn được: 48 : 6 = 8 (cái kẹo).' },
    { sec: 'Phép nhân', name: 'Câu 3', pts: 1.25,
      text: 'Mỗi bàn học có 2 học sinh ngồi. Hỏi 9 cái bàn như thế có bao nhiêu học sinh?',
      opts: o4('16 học sinh', '20 học sinh', '18 học sinh', '11 học sinh'), ans: 'C',
      why: 'Số học sinh là: 2 × 9 = 18 (học sinh).' },
    { sec: 'Chia đều', name: 'Câu 4', pts: 1.25,
      text: 'Có 56 quả cam 🍊 xếp vào các đĩa, mỗi đĩa 7 quả. Hỏi cần bao nhiêu cái đĩa?',
      opts: o4('6 đĩa', '7 đĩa', '9 đĩa', '8 đĩa'), ans: 'D',
      why: 'Số đĩa cần dùng: 56 : 7 = 8 (đĩa).' },
    { sec: 'Chia có dư', name: 'Câu 5', pts: 1.25,
      text: 'Có 60 quyển vở chia đều cho 7 bạn. Hỏi mỗi bạn được nhiều nhất mấy quyển và còn thừa mấy quyển?',
      opts: o4('Mỗi bạn 8 quyển, thừa 4 quyển', 'Mỗi bạn 8 quyển, thừa 3 quyển', 'Mỗi bạn 9 quyển, thừa 3 quyển', 'Mỗi bạn 7 quyển, thừa 11 quyển'), ans: 'A',
      why: 'Thực hiện phép chia có dư: 60 : 7 được 8, vì 7 × 8 = 56. Số vở còn thừa: 60 − 56 = 4 (quyển). Số dư 4 bé hơn số chia 7 nên không chia thêm được nữa.' },
    { sec: 'Tìm thừa số', name: 'Câu 6', pts: 1.25,
      text: 'Số nào nhân với 5 thì được 45?',
      opts: o4('7', '8', '9', '6'), ans: 'C',
      why: 'Ta lấy tích chia cho thừa số đã biết: 45 : 5 = 9. Thử lại: 9 × 5 = 45, đúng.' },
    { sec: 'Phép nhân', name: 'Câu 7', pts: 1.25,
      text: 'Một tuần lễ có 7 ngày. Hỏi 4 tuần lễ có bao nhiêu ngày?',
      opts: o4('21 ngày', '28 ngày', '30 ngày', '24 ngày'), ans: 'B',
      why: 'Số ngày của 4 tuần lễ là: 7 × 4 = 28 (ngày).' },
    { sec: 'Nhân rồi trừ', name: 'Câu 8', pts: 1.25,
      text: 'Có 6 hộp bút, mỗi hộp đựng 8 chiếc bút. Người ta lấy ra 9 chiếc. Hỏi còn lại bao nhiêu chiếc bút?',
      opts: o4('29 chiếc', '48 chiếc', '41 chiếc', '39 chiếc'), ans: 'D',
      why: 'Tổng số bút: 8 × 6 = 48 (chiếc). Số bút còn lại: 48 − 9 = 39 (chiếc).' },
  ],
},

/* ============ ĐỀ 8 — ĐẾM HÌNH ============ */
{
  id: 608, title: 'Đề 8 · Đếm hình', time: 30,
  questions: [
    { sec: 'Đếm hình chữ nhật', name: 'Câu 1', pts: 1.25,
      text: 'Hình bên có bao nhiêu hình chữ nhật?', img: HS + 'hsg08q1.svg',
      opts: o4('3 hình', '4 hình', '6 hình', '5 hình'), ans: 'C',
      why: 'Có 3 hình chữ nhật nhỏ (mỗi ô một hình). Ghép 2 ô liền nhau được 2 hình nữa. Ghép cả 3 ô được 1 hình lớn. Tất cả: 3 + 2 + 1 = 6 hình chữ nhật.' },
    { sec: 'Đếm hình tam giác', name: 'Câu 2', pts: 1.25,
      text: 'Hình bên có bao nhiêu hình tam giác?', img: HS + 'hsg08q2.svg',
      opts: o4('5 hình', '6 hình', '4 hình', '3 hình'), ans: 'B',
      why: 'Có 3 tam giác nhỏ. Ghép 2 tam giác nhỏ liền nhau được 2 tam giác nữa. Cả hình lớn là 1 tam giác. Tất cả: 3 + 2 + 1 = 6 hình tam giác.' },
    { sec: 'Đếm hình vuông', name: 'Câu 3', pts: 1.25,
      text: 'Hình bên có bao nhiêu hình vuông?', img: HS + 'hsg08q3.svg',
      opts: o4('4 hình', '6 hình', '8 hình', '5 hình'), ans: 'D',
      why: 'Có 4 hình vuông nhỏ và 1 hình vuông lớn bao ngoài. Tất cả: 4 + 1 = 5 hình vuông.' },
    { sec: 'Đếm đoạn thẳng', name: 'Câu 4', pts: 1.25,
      text: 'Trên hình bên có bao nhiêu đoạn thẳng?', img: HS + 'hsg08q4.svg',
      opts: o4('6 đoạn', '4 đoạn', '3 đoạn', '5 đoạn'), ans: 'A',
      why: 'Kể từ A có 3 đoạn: AC, AD, AB. Từ C có 2 đoạn mới: CD, CB. Từ D có 1 đoạn mới: DB. Tất cả: 3 + 2 + 1 = 6 đoạn thẳng.' },
    { sec: 'Đếm hình chữ nhật', name: 'Câu 5', pts: 1.25,
      text: 'Hình bên có bao nhiêu hình chữ nhật?', img: HS + 'hsg08q5.svg',
      opts: o4('4 hình', '9 hình', '6 hình', '8 hình'), ans: 'B',
      why: 'Có 4 ô nhỏ. Ghép 2 ô cùng hàng được 2 hình, ghép 2 ô cùng cột được 2 hình, ghép nửa trên và nửa dưới được 2 hình. Cuối cùng cả hình lớn là 1 hình. Tất cả: 4 + 2 + 2 + 1 = 9 hình chữ nhật.' },
    { sec: 'Đếm hình tam giác', name: 'Câu 6', pts: 1.25,
      text: 'Hình bên có bao nhiêu hình tam giác?', img: HS + 'hsg08q6.svg',
      opts: o4('8 hình', '6 hình', '4 hình', '10 hình'), ans: 'A',
      why: 'Hai đường chéo chia hình vuông thành 4 tam giác nhỏ. Ghép 2 tam giác nhỏ liền nhau (tức là một nửa hình vuông) được thêm 4 tam giác lớn. Tất cả: 4 + 4 = 8 hình tam giác.' },
    { sec: 'Đếm đoạn thẳng', name: 'Câu 7', pts: 1.25,
      text: 'Trên một đường thẳng, người ta lấy 5 điểm. Hỏi có bao nhiêu đoạn thẳng được tạo thành?',
      opts: o4('8 đoạn', '9 đoạn', '10 đoạn', '12 đoạn'), ans: 'C',
      why: 'Điểm thứ nhất nối với 4 điểm còn lại được 4 đoạn; điểm thứ hai nối thêm được 3 đoạn mới; rồi 2 đoạn; rồi 1 đoạn. Tất cả: 4 + 3 + 2 + 1 = 10 đoạn thẳng.' },
    { sec: 'Đếm hình vuông', name: 'Câu 8', pts: 1.25,
      text: 'Hình bên gồm các ô vuông nhỏ bằng nhau xếp thành 2 hàng, mỗi hàng 3 ô. Hỏi có tất cả bao nhiêu hình vuông?', img: HS + 'hsg08q8.svg',
      opts: o4('7 hình', '6 hình', '9 hình', '8 hình'), ans: 'D',
      why: 'Hình vuông nhỏ (1 ô): có 6 hình. Hình vuông to gồm 4 ô (2 hàng × 2 cột): đặt được 2 vị trí. Tất cả: 6 + 2 = 8 hình vuông.' },
  ],
},

/* ============ ĐỀ 9 — ĐƯỜNG GẤP KHÚC · CHU VI · ĐỘ DÀI ============ */
{
  id: 609, title: 'Đề 9 · Đường gấp khúc — chu vi — độ dài', time: 30,
  questions: [
    { sec: 'Đường gấp khúc', name: 'Câu 1', pts: 1.25,
      text: 'Tính độ dài đường gấp khúc ABCD dưới đây.', img: HS + 'hsg09q1.svg',
      opts: o4('12 cm', '11 cm', '13 cm', '10 cm'), ans: 'A',
      why: 'Độ dài đường gấp khúc bằng tổng độ dài các đoạn thẳng: 3 + 4 + 5 = 12 (cm).' },
    { sec: 'Chu vi tam giác', name: 'Câu 2', pts: 1.25,
      text: 'Tính chu vi hình tam giác ABC dưới đây.', img: HS + 'hsg09q2.svg',
      opts: o4('14 cm', '16 cm', '15 cm', '13 cm'), ans: 'C',
      why: 'Chu vi hình tam giác bằng tổng độ dài ba cạnh: 4 + 5 + 6 = 15 (cm).' },
    { sec: 'Chu vi tứ giác', name: 'Câu 3', pts: 1.25,
      text: 'Tính chu vi hình tứ giác MNPQ dưới đây.', img: HS + 'hsg09q3.svg',
      opts: o4('17 cm', '18 cm', '19 cm', '16 cm'), ans: 'B',
      why: 'Chu vi hình tứ giác bằng tổng độ dài bốn cạnh: 3 + 4 + 5 + 6 = 18 (cm).' },
    { sec: 'Chu vi tam giác', name: 'Câu 4', pts: 1.25,
      text: 'Một hình tam giác có ba cạnh bằng nhau, mỗi cạnh dài 9 cm. Chu vi hình tam giác đó là bao nhiêu?',
      opts: o4('18 cm', '24 cm', '81 cm', '27 cm'), ans: 'D',
      why: 'Chu vi hình tam giác là tổng độ dài ba cạnh: 9 + 9 + 9 = 9 × 3 = 27 (cm).' },
    { sec: 'Chu vi hình vuông', name: 'Câu 5', pts: 1.25,
      text: 'Tính chu vi hình vuông dưới đây.', img: HS + 'hsg09q5.svg',
      opts: o4('12 cm', '8 cm', '16 cm', '20 cm'), ans: 'C',
      why: 'Hình vuông có 4 cạnh bằng nhau nên chu vi là: 4 + 4 + 4 + 4 = 16 (cm), hay 4 × 4 = 16 (cm).' },
    { sec: 'Đường gấp khúc', name: 'Câu 6', pts: 1.25,
      text: 'Một đường gấp khúc gồm 6 đoạn thẳng bằng nhau và dài tất cả 54 cm. Hỏi mỗi đoạn thẳng dài bao nhiêu xăng-ti-mét?',
      opts: o4('7 cm', '9 cm', '8 cm', '12 cm'), ans: 'B',
      why: 'Sáu đoạn dài bằng nhau nên mỗi đoạn dài: 54 : 6 = 9 (cm).' },
    { sec: 'Ghép hình', name: 'Câu 7', pts: 1.25,
      text: 'Ghép hai hình vuông cạnh 3 cm lại với nhau được một hình chữ nhật như hình bên. Tính chu vi hình chữ nhật đó.', img: HS + 'hsg09q7.svg',
      opts: o4('12 cm', '24 cm', '15 cm', '18 cm'), ans: 'D',
      why: 'Chiều dài hình chữ nhật là 3 + 3 = 6 (cm), chiều rộng là 3 cm. Chu vi là: 6 + 3 + 6 + 3 = 18 (cm).' },
    { sec: 'Đơn vị đo độ dài', name: 'Câu 8', pts: 1.25,
      text: 'Một sợi dây dài 1 m, người ta cắt đi 35 cm. Hỏi sợi dây còn lại dài bao nhiêu xăng-ti-mét?',
      opts: o4('65 cm', '75 cm', '55 cm', '60 cm'), ans: 'A',
      why: 'Đổi 1 m = 100 cm. Sợi dây còn lại dài: 100 − 35 = 65 (cm).' },
  ],
},

/* ============ ĐỀ 10 — ĐO LƯỜNG VÀ TIỀN VIỆT NAM ============ */
{
  id: 610, title: 'Đề 10 · Đo lường và tiền Việt Nam', time: 30,
  questions: [
    { sec: 'Đổi đơn vị', name: 'Câu 1', pts: 1.25,
      text: 'Điền số thích hợp: <b>5 dm = … cm</b>',
      opts: o4('5 cm', '50 cm', '500 cm', '15 cm'), ans: 'B',
      why: 'Vì 1 dm = 10 cm nên 5 dm = 10 × 5 = 50 (cm).' },
    { sec: 'Lít', name: 'Câu 2', pts: 1.25,
      text: 'Can thứ nhất đựng 12 l dầu, can thứ hai đựng ít hơn can thứ nhất 5 l. Hỏi cả hai can đựng bao nhiêu lít dầu?',
      opts: o4('19 l', '17 l', '21 l', '14 l'), ans: 'A',
      why: 'Can thứ hai đựng: 12 − 5 = 7 (l). Cả hai can đựng: 12 + 7 = 19 (l).' },
    { sec: 'Ki-lô-gam', name: 'Câu 3', pts: 1.25,
      text: 'Một quả dưa 🍉 nặng bằng 3 quả cam 🍊. Biết 2 quả dưa nặng 12 kg. Hỏi một quả cam nặng mấy ki-lô-gam?',
      opts: o4('3 kg', '4 kg', '2 kg', '6 kg'), ans: 'C',
      why: 'Một quả dưa nặng: 12 : 2 = 6 (kg). Vì 1 quả dưa nặng bằng 3 quả cam nên một quả cam nặng: 6 : 3 = 2 (kg).' },
    { sec: 'Tiền Việt Nam', name: 'Câu 4', pts: 1.25,
      text: 'Lan có 7 tờ giấy bạc loại 5 000 đồng và 2 tờ giấy bạc loại 2 000 đồng. Hỏi Lan có tất cả bao nhiêu tiền?',
      opts: o4('35 000 đồng', '37 000 đồng', '45 000 đồng', '39 000 đồng'), ans: 'D',
      why: 'Tiền loại 5 000 đồng: 5 000 × 7 = 35 000 (đồng). Tiền loại 2 000 đồng: 2 000 × 2 = 4 000 (đồng). Tất cả: 35 000 + 4 000 = 39 000 (đồng).' },
    { sec: 'Tiền Việt Nam', name: 'Câu 5', pts: 1.25,
      text: 'Một quyển vở giá 6 000 đồng. Hỏi mua 4 quyển vở như thế hết bao nhiêu tiền?',
      opts: o4('24 000 đồng', '20 000 đồng', '18 000 đồng', '30 000 đồng'), ans: 'A',
      why: 'Số tiền mua 4 quyển vở là: 6 000 × 4 = 24 000 (đồng).' },
    { sec: 'Tiền Việt Nam', name: 'Câu 6', pts: 1.25,
      text: 'Nam có 20 000 đồng. Nam mua 2 chiếc bút, mỗi chiếc giá 7 000 đồng. Hỏi Nam còn lại bao nhiêu tiền?',
      opts: o4('8 000 đồng', '13 000 đồng', '6 000 đồng', '5 000 đồng'), ans: 'C',
      why: 'Tiền mua 2 chiếc bút là: 7 000 × 2 = 14 000 (đồng). Nam còn lại: 20 000 − 14 000 = 6 000 (đồng).' },
    { sec: 'Đổi đơn vị', name: 'Câu 7', pts: 1.25,
      text: 'Điền số thích hợp: <b>1 m 20 cm = … cm</b>',
      opts: o4('102 cm', '120 cm', '12 cm', '1 020 cm'), ans: 'B',
      why: 'Đổi 1 m = 100 cm. Vậy 1 m 20 cm = 100 + 20 = 120 (cm).' },
    { sec: 'So sánh số đo', name: 'Câu 8', pts: 1.25,
      text: 'Hùng cao 1 m 15 cm, Dũng cao 108 cm. Hỏi bạn nào cao hơn và cao hơn bao nhiêu xăng-ti-mét?',
      opts: o4('Dũng cao hơn 7 cm', 'Hùng cao hơn 5 cm', 'Hai bạn cao bằng nhau', 'Hùng cao hơn 7 cm'), ans: 'D',
      why: 'Đổi chiều cao của Hùng: 1 m 15 cm = 115 cm. Vì 115 > 108 nên Hùng cao hơn và cao hơn: 115 − 108 = 7 (cm).' },
  ],
},

/* ============ ĐỀ 11 — THỜI GIAN: ĐỒNG HỒ, NGÀY THÁNG ============ */
{
  id: 611, title: 'Đề 11 · Đồng hồ — ngày, tháng', time: 30,
  questions: [
    { sec: 'Ngày trong tuần', name: 'Câu 1', pts: 1.25,
      text: 'Một tuần lễ có 7 ngày. Hôm nay là thứ Ba. Hỏi <b>7 ngày nữa</b> là thứ mấy?',
      opts: o4('Thứ Tư', 'Thứ Hai', 'Thứ Ba', 'Chủ nhật'), ans: 'C',
      why: 'Cứ sau đúng 7 ngày (một tuần lễ) thì lại trở về đúng thứ đó. Vậy 7 ngày nữa vẫn là thứ Ba.' },
    { sec: 'Xem lịch', name: 'Câu 2', pts: 1.25,
      text: 'Hôm nay là thứ Năm ngày 8. Hỏi thứ Năm tuần sau là ngày bao nhiêu?',
      opts: o4('Ngày 14', 'Ngày 15', 'Ngày 16', 'Ngày 13'), ans: 'B',
      why: 'Thứ Năm tuần sau cách hôm nay đúng 7 ngày, nên là ngày: 8 + 7 = 15.' },
    { sec: 'Xem lịch', name: 'Câu 3', pts: 1.25,
      text: 'Ngày 1 tháng 2 là thứ Hai. Hỏi ngày 15 tháng 2 là thứ mấy?',
      opts: o4('Thứ Ba', 'Chủ nhật', 'Thứ Tư', 'Thứ Hai'), ans: 'D',
      why: 'Từ ngày 1 đến ngày 15 cách nhau: 15 − 1 = 14 (ngày), tức đúng 2 tuần lễ. Vậy ngày 15 tháng 2 cũng là thứ Hai.' },
    { sec: 'Tính giờ', name: 'Câu 4', pts: 1.25,
      text: 'Em đến trường lúc 7 giờ và tan học lúc 11 giờ. Hỏi em ở trường bao nhiêu giờ?',
      opts: o4('4 giờ', '3 giờ', '5 giờ', '6 giờ'), ans: 'A',
      why: 'Thời gian em ở trường là: 11 − 7 = 4 (giờ).' },
    { sec: 'Đồng hồ', name: 'Câu 5', pts: 1.25,
      text: 'Đồng hồ ⏰ đang chỉ 8 giờ 30 phút. Hỏi sau 2 giờ nữa đồng hồ chỉ mấy giờ?',
      opts: o4('11 giờ', '10 giờ 30 phút', '9 giờ 30 phút', '10 giờ'), ans: 'B',
      why: 'Số phút giữ nguyên, số giờ tăng thêm 2: 8 giờ + 2 giờ = 10 giờ. Vậy đồng hồ chỉ 10 giờ 30 phút.' },
    { sec: 'Giờ trong ngày', name: 'Câu 6', pts: 1.25,
      text: 'Một ngày có 24 giờ. Hỏi <b>15 giờ</b> còn được gọi là mấy giờ chiều?',
      opts: o4('3 giờ chiều', '4 giờ chiều', '5 giờ chiều', '2 giờ chiều'), ans: 'A',
      why: 'Từ 12 giờ trưa trở đi ta lấy số giờ trừ đi 12: 15 − 12 = 3. Vậy 15 giờ là 3 giờ chiều.' },
    { sec: 'Xem lịch', name: 'Câu 7', pts: 1.25,
      text: 'Tháng 4 có 30 ngày. Nếu ngày 30 tháng 4 là Chủ nhật thì ngày 1 tháng 5 là thứ mấy?',
      opts: o4('Thứ Ba', 'Chủ nhật', 'Thứ Hai', 'Thứ Bảy'), ans: 'C',
      why: 'Ngày 1 tháng 5 là ngày ngay sau ngày 30 tháng 4. Ngày sau Chủ nhật là thứ Hai.' },
    { sec: 'Số ngày trong tháng', name: 'Câu 8', pts: 1.25,
      text: 'Các tháng 1, tháng 3 và tháng 5 đều có 31 ngày. Hỏi cả ba tháng đó có tất cả bao nhiêu ngày?',
      opts: o4('92 ngày', '90 ngày', '91 ngày', '93 ngày'), ans: 'D',
      why: 'Cả ba tháng có số ngày là: 31 × 3 = 93 (ngày).' },
  ],
},

/* ============ ĐỀ 12 — TRỒNG CÂY, XẾP HÀNG, THỨ TỰ ============ */
{
  id: 612, title: 'Đề 12 · Trồng cây — xếp hàng — thứ tự', time: 30,
  questions: [
    { sec: 'Trồng cây', name: 'Câu 1', pts: 1.25,
      text: 'Có 10 cây 🌳 trồng thẳng hàng, hai cây liền nhau cách nhau 2 m. Hỏi cây đầu tiên cách cây cuối cùng bao nhiêu mét?',
      opts: o4('18 m', '20 m', '16 m', '22 m'), ans: 'A',
      why: 'Có 10 cây thì chỉ có 9 khoảng cách giữa hai cây liền nhau. Khoảng cách từ cây đầu đến cây cuối là: 2 × 9 = 18 (m).' },
    { sec: 'Xếp hàng', name: 'Câu 2', pts: 1.25,
      text: 'Một hàng có 12 bạn. Nam đứng thứ 5 tính từ đầu hàng. Hỏi Nam đứng thứ mấy tính từ cuối hàng?',
      opts: o4('Thứ 7', 'Thứ 9', 'Thứ 8', 'Thứ 6'), ans: 'C',
      why: 'Đứng trước Nam có 4 bạn. Kể cả Nam, số bạn tính từ Nam đến cuối hàng là: 12 − 4 = 8. Vậy Nam đứng thứ 8 từ cuối hàng.' },
    { sec: 'Cưa gỗ', name: 'Câu 3', pts: 1.25,
      text: 'Người ta cưa một khúc gỗ thành 5 đoạn bằng nhau. Hỏi phải cưa bao nhiêu lần?',
      opts: o4('5 lần', '4 lần', '3 lần', '6 lần'), ans: 'B',
      why: 'Mỗi lần cưa làm tăng thêm 1 đoạn. Từ 1 đoạn muốn thành 5 đoạn phải cưa: 5 − 1 = 4 (lần).' },
    { sec: 'Trồng cây', name: 'Câu 4', pts: 1.25,
      text: 'Người ta trồng cây 🌳 ở <b>cả hai bên</b> một đoạn đường dài 48 m, cứ 6 m trồng một cây, trồng cả ở hai đầu đường. Hỏi trồng được tất cả bao nhiêu cây?',
      opts: o4('16 cây', '20 cây', '9 cây', '18 cây'), ans: 'D',
      why: 'Mỗi bên có số khoảng cách là: 48 : 6 = 8 (khoảng), nên số cây mỗi bên là 8 + 1 = 9 (cây). Cả hai bên trồng: 9 × 2 = 18 (cây).' },
    { sec: 'Xếp hàng', name: 'Câu 5', pts: 1.25,
      text: 'Trong một hàng, Lan đứng thứ 4 tính từ bên trái và thứ 6 tính từ bên phải. Hỏi hàng đó có bao nhiêu bạn?',
      opts: o4('10 bạn', '11 bạn', '9 bạn', '8 bạn'), ans: 'C',
      why: 'Nếu cộng 4 + 6 = 10 thì bạn Lan bị đếm hai lần. Vậy số bạn trong hàng là: 4 + 6 − 1 = 9 (bạn).' },
    { sec: 'Bậc thang', name: 'Câu 6', pts: 1.25,
      text: 'Từ tầng 1 lên tầng 4 phải đi qua 54 bậc thang. Biết số bậc giữa hai tầng liên tiếp đều bằng nhau. Hỏi từ tầng 1 lên tầng 7 phải đi qua bao nhiêu bậc thang?',
      opts: o4('81 bậc', '108 bậc', '90 bậc', '126 bậc'), ans: 'B',
      why: 'Từ tầng 1 lên tầng 4 phải đi 3 tầng cầu thang nên mỗi tầng có: 54 : 3 = 18 (bậc). Từ tầng 1 lên tầng 7 phải đi 6 tầng cầu thang: 18 × 6 = 108 (bậc).' },
    { sec: 'Đóng cọc', name: 'Câu 7', pts: 1.25,
      text: 'Người ta đóng cọc rào quanh một mảnh vườn hình vuông, mỗi cạnh đóng 8 cọc (kể cả 4 cọc ở bốn góc). Hỏi cần tất cả bao nhiêu cái cọc?',
      opts: o4('24 cọc', '32 cọc', '36 cọc', '28 cọc'), ans: 'D',
      why: 'Nếu đếm 8 cọc cho mỗi cạnh thì được 8 × 4 = 32 cọc, nhưng 4 cọc ở bốn góc đã bị đếm hai lần. Số cọc thật sự cần: 32 − 4 = 28 (cọc).' },
    { sec: 'Thứ tự', name: 'Câu 8', pts: 1.25,
      text: 'Trong một cuộc thi chạy có 9 bạn tham gia. Hùng về đích <b>trước 5 bạn</b>. Hỏi Hùng về đích thứ mấy?',
      opts: o4('Thứ 4', 'Thứ 5', 'Thứ 3', 'Thứ 6'), ans: 'A',
      why: 'Có 5 bạn về sau Hùng, nên số bạn tính từ đầu đến Hùng là: 9 − 5 = 4. Vậy Hùng về đích thứ 4.' },
  ],
},

/* ============ ĐỀ 13 — SUY LUẬN LOGIC ============ */
{
  id: 613, title: 'Đề 13 · Suy luận logic', time: 30,
  questions: [
    { sec: 'So sánh bắc cầu', name: 'Câu 1', pts: 1.25,
      text: 'An cao hơn Bình, Bình cao hơn Cường. Hỏi bạn nào thấp nhất?',
      opts: o4('Bạn An', 'Bạn Cường', 'Bạn Bình', 'Không biết được'), ans: 'B',
      why: 'An cao hơn Bình, Bình lại cao hơn Cường nên thứ tự từ cao xuống thấp là An – Bình – Cường. Vậy Cường thấp nhất.' },
    { sec: 'Suy luận', name: 'Câu 2', pts: 1.25,
      text: 'Ba bạn Mai, Lan, Huệ mặc ba chiếc áo màu đỏ, vàng, xanh (không theo thứ tự). Biết Mai <b>không</b> mặc áo đỏ, còn Lan mặc áo xanh. Hỏi Mai mặc áo màu gì?',
      opts: o4('Màu vàng', 'Màu đỏ', 'Màu xanh', 'Chưa xác định được'), ans: 'A',
      why: 'Lan mặc áo xanh nên Mai không mặc áo xanh. Mai cũng không mặc áo đỏ. Vậy Mai mặc áo màu vàng.' },
    { sec: 'Suy luận', name: 'Câu 3', pts: 1.25,
      text: 'Trong một rổ có 12 quả gồm táo 🍎 và cam 🍊. Số cam nhiều hơn số táo 2 quả. Hỏi trong rổ có bao nhiêu quả cam?',
      opts: o4('5 quả', '6 quả', '7 quả', '8 quả'), ans: 'C',
      why: 'Số cam là: (12 + 2) : 2 = 7 (quả). Thử lại: số táo là 12 − 7 = 5 (quả), và 7 − 5 = 2, đúng.' },
    { sec: 'Thứ tự về đích', name: 'Câu 4', pts: 1.25,
      text: 'Ba bạn Nam, Bắc, Đông thi chạy. Nam về sau Bắc, Đông về trước Bắc. Hỏi bạn nào về nhất?',
      opts: o4('Bạn Nam', 'Bạn Bắc', 'Không biết được', 'Bạn Đông'), ans: 'D',
      why: 'Đông về trước Bắc, Bắc lại về trước Nam. Vậy thứ tự về đích là Đông – Bắc – Nam, bạn Đông về nhất.' },
    { sec: 'Chắc chắn', name: 'Câu 5', pts: 1.25,
      text: 'Trong một chiếc túi có 3 viên bi đỏ 🔴 và 4 viên bi xanh 🔵. Không nhìn vào túi, phải lấy ra ít nhất bao nhiêu viên bi để <b>chắc chắn</b> có được 1 viên bi đỏ?',
      opts: o4('5 viên', '4 viên', '3 viên', '2 viên'), ans: 'A',
      why: 'Trường hợp không may nhất là lấy phải cả 4 viên bi xanh trước. Khi đó viên thứ 5 chắc chắn là bi đỏ. Vậy phải lấy ít nhất 5 viên bi.' },
    { sec: 'So sánh bắc cầu', name: 'Câu 6', pts: 1.25,
      text: 'An nhiều tuổi hơn Bình. Cúc ít tuổi hơn Bình. Dung nhiều tuổi hơn An. Hỏi bạn nào nhiều tuổi nhất?',
      opts: o4('Bạn An', 'Bạn Cúc', 'Bạn Dung', 'Bạn Bình'), ans: 'C',
      why: 'Sắp xếp từ nhiều tuổi đến ít tuổi: Dung – An – Bình – Cúc. Vậy Dung nhiều tuổi nhất.' },
    { sec: 'Ngày trong tuần', name: 'Câu 7', pts: 1.25,
      text: 'Hôm kia là thứ Hai. Hỏi <b>ngày mai</b> là thứ mấy?',
      opts: o4('Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Ba'), ans: 'B',
      why: 'Hôm kia là thứ Hai thì hôm qua là thứ Ba và hôm nay là thứ Tư. Vậy ngày mai là thứ Năm.' },
    { sec: 'Bắt tay', name: 'Câu 8', pts: 1.25,
      text: 'Có 5 bạn gặp nhau, mỗi bạn đều bắt tay 🤝 với tất cả các bạn còn lại đúng một lần. Hỏi có tất cả bao nhiêu cái bắt tay?',
      opts: o4('20 cái', '15 cái', '5 cái', '10 cái'), ans: 'D',
      why: 'Bạn thứ nhất bắt tay 4 bạn còn lại. Bạn thứ hai bắt tay thêm 3 bạn mới, bạn thứ ba thêm 2 bạn, bạn thứ tư thêm 1 bạn. Tất cả: 4 + 3 + 2 + 1 = 10 (cái bắt tay).' },
  ],
},

/* ============ ĐỀ 14 — CÂN THĂNG BẰNG · ĐIỀN SỐ · XẾP QUE ============ */
{
  id: 614, title: 'Đề 14 · Cân thăng bằng — điền số — xếp que', time: 30,
  questions: [
    { sec: 'Cân thăng bằng', name: 'Câu 1', pts: 1.25,
      text: 'Cân ở hình bên đang thăng bằng: một quả dưa nặng bằng ba quả cam. Biết mỗi quả cam nặng 2 kg, hỏi quả dưa nặng bao nhiêu ki-lô-gam?', img: HS + 'hsg14q1.svg',
      opts: o4('5 kg', '8 kg', '6 kg', '3 kg'), ans: 'C',
      why: 'Quả dưa nặng bằng ba quả cam nên quả dưa nặng: 2 × 3 = 6 (kg).' },
    { sec: 'Điền số', name: 'Câu 2', pts: 1.25,
      text: 'Cho biết:<br><b>🔺 + 🔺 = 10</b><br><b>🔺 + ⬛ = 12</b><br>Hỏi ⬛ bằng bao nhiêu?',
      opts: o4('6', '7', '8', '5'), ans: 'B',
      why: 'Từ dòng thứ nhất: 🔺 = 10 : 2 = 5. Thay vào dòng thứ hai: ⬛ = 12 − 5 = 7.' },
    { sec: 'Ô vuông kì diệu', name: 'Câu 3', pts: 1.25,
      text: 'Hãy điền số vào ô ❓ sao cho tổng ba số ở mỗi hàng ngang, mỗi cột dọc đều bằng nhau.', img: HS + 'hsg14q3.svg',
      opts: o4('4', '6', '7', '5'), ans: 'D',
      why: 'Hàng trên có tổng: 8 + 1 + 6 = 15. Hàng giữa là 3 + ❓ + 7 = 15 nên ❓ = 15 − 3 − 7 = 5. (Kiểm tra cột giữa: 1 + 5 + 9 = 15, đúng.)' },
    { sec: 'Điền dấu', name: 'Câu 4', pts: 1.25,
      text: 'Điền dấu <b>+</b> hoặc <b>−</b> thích hợp vào hai ô trống: <b>8 ❓ 3 ❓ 5 = 10</b>',
      opts: o4('dấu − rồi dấu +', 'dấu + rồi dấu −', 'dấu + rồi dấu +', 'dấu − rồi dấu −'), ans: 'A',
      why: 'Thử lần lượt: 8 + 3 + 5 = 16; 8 + 3 − 5 = 6; 8 − 3 + 5 = 10 (đúng); 8 − 3 − 5 = 0. Vậy điền dấu − rồi dấu +.' },
    { sec: 'Cân thăng bằng', name: 'Câu 5', pts: 1.25,
      text: 'Cân ở hình bên đang thăng bằng. Hai chiếc hộp giống hệt nhau và một quả cân 5 kg cân bằng với quả cân 11 kg. Hỏi mỗi chiếc hộp nặng bao nhiêu ki-lô-gam?', img: HS + 'hsg14q5.svg',
      opts: o4('2 kg', '3 kg', '4 kg', '5 kg'), ans: 'B',
      why: 'Hai chiếc hộp nặng: 11 − 5 = 6 (kg). Vì hai hộp giống nhau nên mỗi hộp nặng: 6 : 2 = 3 (kg).' },
    { sec: 'Tìm hai số', name: 'Câu 6', pts: 1.25,
      text: 'Tìm hai số, biết tổng của chúng bằng 27 và số lớn gấp đôi số bé.',
      opts: o4('9 và 18', '8 và 19', '10 và 17', '7 và 20'), ans: 'A',
      why: 'Coi số bé là 1 phần thì số lớn là 2 phần, tổng gồm 1 + 2 = 3 phần. Số bé: 27 : 3 = 9; số lớn: 9 × 2 = 18. Thử lại: 9 + 18 = 27.' },
    { sec: 'Xếp que', name: 'Câu 7', pts: 1.25,
      text: 'Bạn Minh dùng các que tính bằng nhau xếp thành 3 hình vuông nhỏ liền nhau như hình bên. Hỏi Minh đã dùng bao nhiêu que tính?', img: HS + 'hsg14q7.svg',
      opts: o4('12 que', '9 que', '10 que', '8 que'), ans: 'C',
      why: 'Ba hình vuông xếp liền nhau cần 3 que nằm ngang ở trên và 3 que nằm ngang ở dưới (6 que), cùng với 4 que dựng đứng. Tất cả: 6 + 4 = 10 (que tính).' },
    { sec: 'Tính chất phép cộng', name: 'Câu 8', pts: 1.25,
      text: 'Trong một phép cộng, nếu tăng số hạng thứ nhất thêm 8 đơn vị và giữ nguyên số hạng thứ hai thì tổng thay đổi thế nào?',
      opts: o4('Giảm 8 đơn vị', 'Không thay đổi', 'Tăng 16 đơn vị', 'Tăng 8 đơn vị'), ans: 'D',
      why: 'Chỉ một số hạng tăng thêm 8 đơn vị nên tổng cũng tăng thêm đúng 8 đơn vị. Ví dụ: 12 + 5 = 17 và 20 + 5 = 25, quả thật 25 − 17 = 8.' },
  ],
},

/* ============ ĐỀ 15 — ĐỀ TỔNG HỢP LUYỆN THI HSG ============ */
{
  id: 615, title: 'Đề 15 · Tổng hợp luyện thi HSG', time: 30,
  questions: [
    { sec: 'Tính nhanh', name: 'Câu 1', pts: 1.25,
      text: 'Tính nhanh: <b>15 + 25 + 35 + 45</b>',
      opts: o4('120', '110', '130', '100'), ans: 'A',
      why: 'Ghép cặp cho tròn chục: (15 + 45) + (25 + 35) = 60 + 60 = 120.' },
    { sec: 'Tìm x', name: 'Câu 2', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>x − 18 = 27 + 15</b>',
      opts: o4('54', '66', '60', '45'), ans: 'C',
      why: 'Vế phải: 27 + 15 = 42. Ta có x − 18 = 42 nên x = 42 + 18 = 60.' },
    { sec: 'Cấu tạo số', name: 'Câu 3', pts: 1.25,
      text: 'Số lớn nhất có hai chữ số mà <b>chữ số hàng chục gấp đôi chữ số hàng đơn vị</b> là số nào?',
      opts: o4('63', '84', '42', '21'), ans: 'B',
      why: 'Các số thoả mãn là 21; 42; 63; 84 (vì 2 = 1 × 2; 4 = 2 × 2; 6 = 3 × 2; 8 = 4 × 2). Số lớn nhất trong đó là 84.' },
    { sec: 'Toán có lời văn', name: 'Câu 4', pts: 1.25,
      text: 'Một cửa hàng buổi sáng bán được 45 kg gạo, buổi chiều bán được ít hơn buổi sáng 12 kg. Hỏi cả ngày cửa hàng bán được bao nhiêu ki-lô-gam gạo?',
      opts: o4('57 kg', '33 kg', '80 kg', '78 kg'), ans: 'D',
      why: 'Buổi chiều bán được: 45 − 12 = 33 (kg). Cả ngày bán được: 45 + 33 = 78 (kg gạo).' },
    { sec: 'Chia đều', name: 'Câu 5', pts: 1.25,
      text: 'Có 56 học sinh xếp thành 7 hàng đều nhau. Hỏi mỗi hàng có bao nhiêu học sinh?',
      opts: o4('6 học sinh', '7 học sinh', '8 học sinh', '9 học sinh'), ans: 'C',
      why: 'Mỗi hàng có: 56 : 7 = 8 (học sinh).' },
    { sec: 'Toán có lời văn', name: 'Câu 6', pts: 1.25,
      text: 'Nam có 35 viên bi. Nam cho bạn 8 viên rồi được mẹ cho thêm 12 viên. Hỏi lúc này Nam có bao nhiêu viên bi?',
      opts: o4('43 viên', '39 viên', '31 viên', '35 viên'), ans: 'B',
      why: 'Sau khi cho bạn, Nam còn: 35 − 8 = 27 (viên). Được mẹ cho thêm, Nam có: 27 + 12 = 39 (viên bi).' },
    { sec: 'Dãy số', name: 'Câu 7', pts: 1.25,
      text: 'Cho dãy số: <b>4; 8; 12; 16; …</b> Số hạng thứ <b>8</b> của dãy là số nào?',
      opts: o4('28', '36', '30', '32'), ans: 'D',
      why: 'Dãy gồm các số 4 × 1; 4 × 2; 4 × 3; … nên số hạng thứ 8 là: 4 × 8 = 32.' },
    { sec: 'Tổng – hiệu', name: 'Câu 8', pts: 1.25,
      text: 'Anh hơn em 5 tuổi. Tổng số tuổi của hai anh em là 25 tuổi. Hỏi anh bao nhiêu tuổi?',
      opts: o4('15 tuổi', '10 tuổi', '12 tuổi', '13 tuổi'), ans: 'A',
      why: 'Tuổi anh là: (25 + 5) : 2 = 15 (tuổi). Thử lại: tuổi em là 25 − 15 = 10 và 15 − 10 = 5, đúng.' },
  ],
},

];

// Chèn môn "HSG Toán 2" ngay sau môn Toán tư duy trong danh sách môn học
{
  const i = SUBJECTS.findIndex(s => s.id === 'tuduy');
  SUBJECTS.splice(i < 0 ? 1 : i + 1, 0, {
    id: 'hsg2', name: 'HSG Toán', short: 'HSG Toán 2', icon: '🎓', grade: 2,
    exams: HSG2_EXAMS, ready: true,
    heroTitle: 'Bồi dưỡng học sinh giỏi Toán lớp 2 — 15 chuyên đề',
    heroMeta: '📚 15 đề &nbsp;•&nbsp; 120 câu &nbsp;•&nbsp; ⏱ 30 phút mỗi đề &nbsp;•&nbsp; đủ các dạng, lời giải chi tiết',
  });
}
