// LỊCH SỬ VÀ ĐỊA LÍ — LỚP 4 (GDPT 2018)
// 30 đề × 10 câu = 300 câu. Mỗi câu 1 điểm — thang 10 — 20 phút mỗi đề.
//
// Chương trình lớp 4 tìm hiểu địa phương và các vùng miền của Việt Nam,
// gắn với một số nhân vật – sự kiện lịch sử tiêu biểu của từng vùng:
//   - Địa phương em và kĩ năng bản đồ, phương hướng
//   - Trung du và miền núi Bắc Bộ (Đền Hùng, Điện Biên Phủ)
//   - Đồng bằng Bắc Bộ (sông Hồng, Thăng Long – Hà Nội, Văn Miếu)
//   - Duyên hải miền Trung (Cố đô Huế, phố cổ Hội An)
//   - Tây Nguyên (đất ba-dan, cà phê, không gian văn hoá cồng chiêng)
//   - Nam Bộ (đồng bằng sông Cửu Long, Thành phố Hồ Chí Minh)

const LSDL4_EXAMS = [

/* ═══════════ ĐỀ 1 — ĐỊA PHƯƠNG EM VÀ BẢN ĐỒ ═══════════ */
{
  id: 5601, title: 'Đề 1 · Địa phương em và bản đồ', time: 20,
  questions: [
    { sec: 'Bản đồ', name: 'Câu 1', pts: 1,
      text: 'Bản đồ là gì?',
      opts: o4('Hình vẽ thu nhỏ một khu vực trên mặt phẳng', 'Một bức ảnh chụp bầu trời', 'Một quyển truyện', 'Một bài hát'), ans: 'A',
      why: 'Bản đồ là hình vẽ thu nhỏ một vùng đất (hoặc toàn bộ Trái Đất) trên mặt phẳng.' },
    { sec: 'Bản đồ', name: 'Câu 2', pts: 1,
      text: 'Trên bản đồ, hướng ở phía trên thường là hướng nào?',
      opts: o4('Hướng bắc', 'Hướng nam', 'Hướng đông', 'Hướng tây'), ans: 'A',
      why: 'Theo quy ước, phía trên bản đồ là hướng bắc, dưới là nam, phải là đông, trái là tây.' },
    { sec: 'Bản đồ', name: 'Câu 3', pts: 1,
      text: 'Trên bản đồ, sông ngòi thường được vẽ bằng màu gì?',
      opts: o4('Màu xanh nước biển', 'Màu đỏ', 'Màu vàng', 'Màu đen'), ans: 'A',
      why: 'Sông, hồ, biển thường được thể hiện bằng màu xanh nước biển.' },
    { sec: 'Bản đồ', name: 'Câu 4', pts: 1,
      text: 'Phần chú giải (bảng chú thích) trên bản đồ dùng để làm gì?',
      opts: o4('Giải thích ý nghĩa các kí hiệu trên bản đồ', 'Trang trí cho đẹp', 'Ghi tên người vẽ', 'Không có tác dụng'), ans: 'A',
      why: 'Chú giải cho biết mỗi kí hiệu, màu sắc trên bản đồ thể hiện điều gì.' },
    { sec: 'Địa phương', name: 'Câu 5', pts: 1,
      text: 'Đơn vị hành chính nào lớn hơn: xã (phường) hay tỉnh (thành phố)?',
      opts: o4('Tỉnh (thành phố) lớn hơn', 'Xã (phường) lớn hơn', 'Bằng nhau', 'Không so sánh được'), ans: 'A',
      why: 'Tỉnh (thành phố) gồm nhiều huyện; huyện gồm nhiều xã, phường — nên tỉnh lớn hơn xã.' },
    { sec: 'Địa phương', name: 'Câu 6', pts: 1,
      text: 'Thủ đô của nước Việt Nam là thành phố nào?',
      opts: o4('Hà Nội', 'Thành phố Hồ Chí Minh', 'Đà Nẵng', 'Huế'), ans: 'A',
      why: 'Hà Nội là thủ đô của nước Cộng hoà xã hội chủ nghĩa Việt Nam.' },
    { sec: 'Địa phương', name: 'Câu 7', pts: 1,
      text: 'Muốn tìm hiểu về quê hương mình, em có thể làm gì?',
      opts: o4('Quan sát, hỏi người lớn, đọc tài liệu, xem bản đồ', 'Chỉ ngồi đoán', 'Không cần tìm hiểu', 'Nghĩ ra một cách tuỳ ý'), ans: 'A',
      why: 'Quan sát thực tế, hỏi người lớn, đọc tài liệu và xem bản đồ giúp hiểu về quê hương.' },
    { sec: 'Địa phương', name: 'Câu 8', pts: 1,
      text: 'Nghề nghiệp của người dân ở một địa phương phụ thuộc nhiều vào điều gì?',
      opts: o4('Điều kiện tự nhiên nơi đó (đồng bằng, ven biển, miền núi)', 'Màu áo họ mặc', 'Tên của họ', 'Sở thích ăn uống'), ans: 'A',
      why: 'Vùng ven biển làm nghề cá, đồng bằng trồng lúa, miền núi trồng rừng... tuỳ điều kiện tự nhiên.' },
    { sec: 'Địa phương', name: 'Câu 9', pts: 1,
      text: 'Việc nào thể hiện tình yêu quê hương?',
      opts: o4('Giữ gìn cảnh quan, học tốt, giới thiệu nét đẹp quê mình', 'Xả rác nơi công cộng', 'Chê bai quê hương', 'Phá hoại di tích'), ans: 'A',
      why: 'Giữ gìn cảnh quan, chăm học và tự hào giới thiệu quê hương thể hiện tình yêu quê.' },
    { sec: 'Địa phương', name: 'Câu 10', pts: 1,
      text: 'Nước Việt Nam nằm ở khu vực nào của thế giới?',
      opts: o4('Khu vực Đông Nam Á', 'Châu Âu', 'Châu Phi', 'Châu Mĩ'), ans: 'A',
      why: 'Việt Nam nằm ở khu vực Đông Nam Á, thuộc châu Á.' },
  ],
},

/* ═══════════ ĐỀ 2 — TRUNG DU VÀ MIỀN NÚI BẮC BỘ: THIÊN NHIÊN, CON NGƯỜI ═══════════ */
{
  id: 5602, title: 'Đề 2 · Trung du và miền núi Bắc Bộ', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Vùng Trung du và miền núi Bắc Bộ có địa hình chủ yếu là gì?',
      opts: o4('Đồi và núi', 'Đồng bằng rộng phẳng', 'Toàn biển', 'Sa mạc cát'), ans: 'A',
      why: 'Đây là vùng nhiều đồi, núi — địa hình cao và hiểm trở.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đỉnh núi cao nhất Việt Nam là đỉnh nào?',
      opts: o4('Phan-xi-păng', 'Bà Đen', 'Ngự Bình', 'Yên Tử'), ans: 'A',
      why: 'Phan-xi-păng (khoảng 3143 m) thuộc dãy Hoàng Liên Sơn, là đỉnh cao nhất nước ta.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Dãy núi cao và đồ sộ nhất ở miền núi Bắc Bộ là dãy nào?',
      opts: o4('Hoàng Liên Sơn', 'Trường Sơn', 'Bạch Mã', 'Tam Đảo'), ans: 'A',
      why: 'Dãy Hoàng Liên Sơn là dãy núi cao, đồ sộ nhất nước ta, có đỉnh Phan-xi-păng.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Người dân vùng núi thường trồng lúa trên loại ruộng nào ở sườn đồi, núi?',
      opts: o4('Ruộng bậc thang', 'Ruộng dưới đáy biển', 'Ruộng trên mái nhà', 'Ruộng trong hang'), ans: 'A',
      why: 'Để trồng lúa ở sườn dốc, người dân làm ruộng bậc thang men theo sườn đồi, núi.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Vùng núi Bắc Bộ là nơi sinh sống của nhiều dân tộc nào?',
      opts: o4('Thái, Mông, Dao, Tày, Nùng...', 'Chỉ có người Kinh', 'Chỉ có người nước ngoài', 'Không có ai sinh sống'), ans: 'A',
      why: 'Vùng này là nơi cư trú của nhiều dân tộc thiểu số như Thái, Mông, Dao, Tày, Nùng...' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Vùng núi Bắc Bộ giàu loại tài nguyên nào?',
      opts: o4('Khoáng sản (than, sắt, a-pa-tit...) và rừng', 'Dầu mỏ ngoài khơi', 'Cát trắng ven biển', 'Muối biển'), ans: 'A',
      why: 'Vùng này giàu khoáng sản (than, sắt, a-pa-tit, thiếc...) và có nhiều rừng.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Sa Pa (Lào Cai) nổi tiếng là nơi có khí hậu như thế nào?',
      opts: o4('Mát mẻ quanh năm, mùa đông có thể có sương muối', 'Nóng như sa mạc', 'Luôn ngập nước', 'Không bao giờ có mây'), ans: 'A',
      why: 'Sa Pa ở vùng núi cao nên khí hậu mát mẻ, mùa đông rất lạnh, đôi khi có sương muối, băng giá.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Chợ phiên vùng cao là nơi để làm gì?',
      opts: o4('Trao đổi, mua bán hàng hoá và giao lưu văn hoá', 'Chỉ để đi dạo', 'Để cày ruộng', 'Không có tác dụng'), ans: 'A',
      why: 'Chợ phiên họp theo ngày nhất định, là nơi mua bán và giao lưu văn hoá của người vùng cao.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Vì sao phải bảo vệ rừng ở vùng núi?',
      opts: o4('Rừng giữ đất, giữ nước, chống lũ và sạt lở', 'Vì rừng vô ích', 'Vì rừng gây hại', 'Không cần bảo vệ'), ans: 'A',
      why: 'Rừng đầu nguồn giữ đất, giữ nước, hạn chế lũ lụt và sạt lở đất ở vùng núi.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Cây công nghiệp lâu năm nào được trồng nhiều ở vùng trung du Bắc Bộ?',
      opts: o4('Cây chè', 'Cây dừa', 'Cây thanh long', 'Cây cà phê'), ans: 'A',
      why: 'Vùng trung du Bắc Bộ (Thái Nguyên, Phú Thọ...) nổi tiếng trồng nhiều chè.' },
  ],
},

/* ═══════════ ĐỀ 3 — LỊCH SỬ GẮN VỚI BẮC BỘ: ĐỀN HÙNG, ĐIỆN BIÊN PHỦ ═══════════ */
{
  id: 5603, title: 'Đề 3 · Đền Hùng và Chiến thắng Điện Biên Phủ', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Đền Hùng (tỉnh Phú Thọ) là nơi thờ ai?',
      opts: o4('Các Vua Hùng — những người có công dựng nước', 'Vua nước ngoài', 'Ông Táo', 'Thần Biển'), ans: 'A',
      why: 'Đền Hùng thờ các Vua Hùng, những người đã có công dựng nên nước Văn Lang.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Giỗ Tổ Hùng Vương được tổ chức vào ngày nào (âm lịch)?',
      opts: o4('Mùng 10 tháng 3', 'Mùng 1 tháng 1', 'Rằm tháng 8', 'Mùng 5 tháng 5'), ans: 'A',
      why: 'Giỗ Tổ Hùng Vương là ngày mùng 10 tháng 3 âm lịch hằng năm.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Nhà nước đầu tiên của người Việt do các Vua Hùng lập ra có tên là gì?',
      opts: o4('Nước Văn Lang', 'Nước Đại Việt', 'Nước Nam Việt', 'Nước Việt Nam'), ans: 'A',
      why: 'Các Vua Hùng lập ra nước Văn Lang — nhà nước đầu tiên trong lịch sử nước ta.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Câu ca dao "Dù ai đi ngược về xuôi / Nhớ ngày Giỗ Tổ mùng mười tháng ba" nhắc nhở điều gì?',
      opts: o4('Nhớ ơn tổ tiên, cội nguồn dân tộc', 'Nhớ đi chợ', 'Nhớ mang áo mưa', 'Nhớ nấu cơm'), ans: 'A',
      why: 'Câu ca dao nhắc con cháu luôn nhớ ơn tổ tiên và cội nguồn dân tộc.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ diễn ra vào năm nào?',
      opts: o4('Năm 1954', 'Năm 1945', 'Năm 1975', 'Năm 1930'), ans: 'A',
      why: 'Chiến thắng Điện Biên Phủ diễn ra ngày 7 tháng 5 năm 1954.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ là chiến thắng chống lại quân xâm lược nào?',
      opts: o4('Thực dân Pháp', 'Quân Nguyên - Mông', 'Quân Thanh', 'Quân Minh'), ans: 'A',
      why: 'Điện Biên Phủ là chiến thắng vang dội của quân dân ta chống thực dân Pháp.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Vị Đại tướng chỉ huy Chiến dịch Điện Biên Phủ là ai?',
      opts: o4('Võ Nguyên Giáp', 'Trần Hưng Đạo', 'Quang Trung', 'Lê Lợi'), ans: 'A',
      why: 'Đại tướng Võ Nguyên Giáp là Tổng chỉ huy Chiến dịch Điện Biên Phủ.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Điện Biên Phủ nằm ở vùng nào của nước ta?',
      opts: o4('Miền núi Tây Bắc (Bắc Bộ)', 'Đồng bằng Nam Bộ', 'Tây Nguyên', 'Duyên hải miền Trung'), ans: 'A',
      why: 'Điện Biên Phủ thuộc tỉnh Điện Biên, ở vùng núi Tây Bắc của Bắc Bộ.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ có ý nghĩa gì?',
      opts: o4('Kết thúc thắng lợi cuộc kháng chiến chống Pháp', 'Mở đầu chiến tranh', 'Không có ý nghĩa', 'Chỉ là một trận nhỏ'), ans: 'A',
      why: 'Chiến thắng Điện Biên Phủ buộc Pháp kí Hiệp định Giơ-ne-vơ, kết thúc kháng chiến chống Pháp.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Kinh đô nước Âu Lạc thời An Dương Vương, nay ở gần Hà Nội, có tên là gì?',
      opts: o4('Cổ Loa', 'Hoa Lư', 'Phú Xuân', 'Thăng Long'), ans: 'A',
      why: 'An Dương Vương lập nước Âu Lạc, đóng đô ở Cổ Loa (nay thuộc Đông Anh, Hà Nội).' },
  ],
},

/* ═══════════ ĐỀ 4 — ĐỒNG BẰNG BẮC BỘ: THIÊN NHIÊN VÀ SẢN XUẤT ═══════════ */
{
  id: 5604, title: 'Đề 4 · Đồng bằng Bắc Bộ', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng Bắc Bộ do những con sông nào bồi đắp nên?',
      opts: o4('Sông Hồng và sông Thái Bình', 'Sông Cửu Long', 'Sông Đồng Nai', 'Sông Hương'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ được sông Hồng và sông Thái Bình bồi đắp phù sa.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đất ở đồng bằng Bắc Bộ có đặc điểm gì?',
      opts: o4('Đất phù sa màu mỡ', 'Đất cát khô cằn', 'Đất đỏ ba-dan', 'Toàn đá sỏi'), ans: 'A',
      why: 'Phù sa sông bồi đắp tạo nên đất màu mỡ, thuận lợi trồng trọt.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Cây lương thực được trồng nhiều nhất ở đồng bằng Bắc Bộ là gì?',
      opts: o4('Cây lúa', 'Cây cà phê', 'Cây cao su', 'Cây thông'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ là vựa lúa lớn thứ hai của cả nước.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Người dân đồng bằng Bắc Bộ đắp đê ven sông để làm gì?',
      opts: o4('Ngăn lũ lụt, bảo vệ mùa màng và làng xóm', 'Để leo trèo', 'Để làm đường tàu', 'Để trang trí'), ans: 'A',
      why: 'Hệ thống đê điều giúp ngăn nước sông dâng cao gây lũ, bảo vệ đồng ruộng, làng mạc.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Mùa nào ở đồng bằng Bắc Bộ thường lạnh, có gió mùa đông bắc?',
      opts: o4('Mùa đông', 'Mùa hạ', 'Mùa mưa quanh năm', 'Không có mùa lạnh'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ có mùa đông lạnh do ảnh hưởng của gió mùa đông bắc.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Ngoài trồng lúa, người dân đồng bằng Bắc Bộ còn phát triển nghề gì?',
      opts: o4('Trồng rau, nuôi lợn gà, làng nghề thủ công', 'Khai thác dầu mỏ', 'Trồng cà phê', 'Nuôi tuần lộc'), ans: 'A',
      why: 'Vùng này còn trồng rau màu, chăn nuôi và có nhiều làng nghề thủ công truyền thống.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Làng nghề gốm Bát Tràng nổi tiếng nằm ở đâu?',
      opts: o4('Hà Nội (đồng bằng Bắc Bộ)', 'Đà Lạt', 'Cần Thơ', 'Buôn Ma Thuột'), ans: 'A',
      why: 'Bát Tràng (Hà Nội) là làng nghề làm gốm sứ nổi tiếng ở đồng bằng Bắc Bộ.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Đồng bằng Bắc Bộ là vùng có mật độ dân số như thế nào?',
      opts: o4('Đông dân, mật độ cao', 'Rất ít người', 'Không có người ở', 'Chỉ có khách du lịch'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ là một trong những vùng đông dân nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Lễ hội truyền thống ở đồng bằng Bắc Bộ thường được tổ chức vào mùa nào?',
      opts: o4('Mùa xuân (sau Tết)', 'Giữa mùa hè nóng nhất', 'Không bao giờ tổ chức', 'Chỉ vào ban đêm mùa đông'), ans: 'A',
      why: 'Nhiều lễ hội (hội Lim, hội Gióng, chùa Hương...) được tổ chức vào mùa xuân.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Sông Hồng có màu nước đặc trưng là gì, do đâu?',
      opts: o4('Màu đỏ nâu do chứa nhiều phù sa', 'Màu xanh trong veo', 'Màu đen', 'Màu trắng như sữa'), ans: 'A',
      why: 'Sông Hồng mang nhiều phù sa nên nước thường có màu đỏ nâu — vì thế gọi là sông Hồng.' },
  ],
},

/* ═══════════ ĐỀ 5 — THĂNG LONG – HÀ NỘI VÀ VĂN MIẾU ═══════════ */
{
  id: 5605, title: 'Đề 5 · Thăng Long – Hà Nội', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Tên gọi xưa của Thủ đô Hà Nội là gì?',
      opts: o4('Thăng Long', 'Gia Định', 'Phú Xuân', 'Hoa Lư'), ans: 'A',
      why: 'Hà Nội xưa có tên là Thăng Long, nghĩa là "rồng bay lên".' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Vị vua nào đã dời đô ra Thăng Long vào năm 1010?',
      opts: o4('Lý Thái Tổ (Lý Công Uẩn)', 'Quang Trung', 'Lê Lợi', 'Trần Hưng Đạo'), ans: 'A',
      why: 'Năm 1010, vua Lý Thái Tổ (Lý Công Uẩn) dời đô từ Hoa Lư ra Thăng Long.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Văn Miếu – Quốc Tử Giám ở Hà Nội được xem là gì?',
      opts: o4('Trường đại học đầu tiên của nước ta', 'Một khu chợ', 'Một bến cảng', 'Một nhà máy'), ans: 'A',
      why: 'Quốc Tử Giám được coi là trường đại học đầu tiên của Việt Nam, nơi đào tạo nhân tài.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Trong Văn Miếu có các tấm bia đá đặt trên lưng con vật nào để khắc tên người đỗ đạt?',
      opts: o4('Con rùa', 'Con rồng', 'Con voi', 'Con ngựa'), ans: 'A',
      why: 'Bia tiến sĩ ở Văn Miếu được đặt trên lưng rùa đá, ghi tên những người thi đỗ.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Hà Nội ngày nay là trung tâm gì của cả nước?',
      opts: o4('Trung tâm chính trị, văn hoá, khoa học', 'Chỉ là một làng nhỏ', 'Một hòn đảo', 'Một khu rừng'), ans: 'A',
      why: 'Hà Nội là thủ đô — trung tâm chính trị, văn hoá, khoa học, giáo dục của cả nước.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Hồ nước nổi tiếng ở trung tâm Hà Nội, gắn với truyền thuyết trả gươm là hồ nào?',
      opts: o4('Hồ Hoàn Kiếm (Hồ Gươm)', 'Hồ Ba Bể', 'Hồ Tây (trả gươm)', 'Biển Hồ'), ans: 'A',
      why: 'Hồ Hoàn Kiếm (Hồ Gươm) gắn với truyền thuyết vua Lê trả gươm cho Rùa Thần.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Truyền thuyết Hồ Gươm gắn với vị anh hùng nào chống quân Minh?',
      opts: o4('Lê Lợi', 'Ngô Quyền', 'Đinh Bộ Lĩnh', 'Lý Thường Kiệt'), ans: 'A',
      why: 'Truyền thuyết kể Lê Lợi được Rùa Thần cho mượn gươm để đánh đuổi giặc Minh.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Khu vực "Ba mươi sáu phố phường" ở Hà Nội xưa là nơi làm gì?',
      opts: o4('Buôn bán, làm nghề thủ công', 'Trồng lúa', 'Đánh cá biển', 'Khai thác than'), ans: 'A',
      why: 'Khu phố cổ "36 phố phường" là nơi tập trung buôn bán và làm nghề thủ công của Thăng Long xưa.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Vì sao vua Lý Thái Tổ chọn Thăng Long làm kinh đô?',
      opts: o4('Vì đây là vùng đất trung tâm, bằng phẳng, thuận lợi phát triển', 'Vì gần biển', 'Vì trên núi cao', 'Vì xa dân cư'), ans: 'A',
      why: 'Thăng Long ở vị trí trung tâm, đất bằng phẳng, thuận lợi cho việc mở mang, phát triển đất nước.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Năm 2010, Hà Nội (Thăng Long) kỉ niệm tròn bao nhiêu năm tuổi?',
      opts: o4('1000 năm', '100 năm', '500 năm', '2000 năm'), ans: 'A',
      why: 'Năm 2010 là dịp Đại lễ 1000 năm Thăng Long – Hà Nội (tính từ năm 1010).' },
  ],
},

/* ═══════════ ĐỀ 6 — DUYÊN HẢI MIỀN TRUNG: THIÊN NHIÊN ═══════════ */
{
  id: 5606, title: 'Đề 6 · Duyên hải miền Trung', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng ở duyên hải miền Trung có đặc điểm gì?',
      opts: o4('Nhỏ hẹp, nằm sát biển', 'Rất rộng lớn, phẳng', 'Nằm sâu trong núi', 'Toàn cao nguyên'), ans: 'A',
      why: 'Do núi ăn ra sát biển nên các đồng bằng ven biển miền Trung nhỏ hẹp.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Miền Trung có nhiều bãi biển đẹp, thuận lợi phát triển ngành gì?',
      opts: o4('Du lịch biển', 'Trồng cà phê', 'Khai thác than', 'Chăn nuôi tuần lộc'), ans: 'A',
      why: 'Bãi biển đẹp (Nha Trang, Đà Nẵng, Lăng Cô...) giúp miền Trung phát triển du lịch biển.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Dãy núi lớn chạy dọc phía tây miền Trung là dãy nào?',
      opts: o4('Dãy Trường Sơn', 'Dãy Hoàng Liên Sơn', 'Dãy Tam Đảo', 'Dãy Con Voi'), ans: 'A',
      why: 'Dãy Trường Sơn chạy dài ở phía tây, ngăn cách miền Trung với Lào và Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Miền Trung thường phải hứng chịu thiên tai nào vào mùa mưa bão?',
      opts: o4('Bão và lũ lụt', 'Tuyết rơi dày', 'Động đất lớn hằng ngày', 'Núi lửa phun'), ans: 'A',
      why: 'Miền Trung là vùng thường xuyên chịu bão và lũ lụt, gây nhiều thiệt hại.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Nghề nào là thế mạnh của người dân ven biển miền Trung?',
      opts: o4('Đánh bắt, nuôi trồng hải sản và làm muối', 'Trồng lúa nước quy mô lớn', 'Khai thác vàng', 'Trồng chè'), ans: 'A',
      why: 'Ven biển miền Trung phát triển đánh bắt, nuôi hải sản và nghề làm muối.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Vì sao nghề làm muối phát triển ở ven biển miền Trung?',
      opts: o4('Vì có nắng nhiều và nước biển mặn', 'Vì trời hay mưa', 'Vì đất đỏ ba-dan', 'Vì có tuyết'), ans: 'A',
      why: 'Nắng nhiều giúp nước biển bốc hơi nhanh, để lại muối — thuận lợi cho nghề làm muối.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Để giảm thiệt hại do bão lũ, người dân miền Trung nên làm gì?',
      opts: o4('Theo dõi dự báo, chằng chống nhà cửa, sơ tán khi cần', 'Ra biển khi có bão', 'Không chuẩn bị gì', 'Chặt hết cây chắn gió'), ans: 'A',
      why: 'Theo dõi dự báo, gia cố nhà cửa và sơ tán kịp thời giúp giảm thiệt hại do bão lũ.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Thành phố biển lớn ở miền Trung, có cầu Rồng nổi tiếng là thành phố nào?',
      opts: o4('Đà Nẵng', 'Hải Phòng', 'Cần Thơ', 'Vũng Tàu'), ans: 'A',
      why: 'Đà Nẵng là thành phố biển lớn ở miền Trung, nổi tiếng với cầu Rồng, bãi biển Mĩ Khê.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Rừng ở dãy Trường Sơn có vai trò gì với miền Trung?',
      opts: o4('Giữ nước, hạn chế lũ quét và sạt lở', 'Gây ra bão', 'Làm biển dâng', 'Không có vai trò'), ans: 'A',
      why: 'Rừng Trường Sơn giữ nước đầu nguồn, hạn chế lũ quét và sạt lở cho vùng đồng bằng ven biển.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Khí hậu miền Trung vào mùa hè thường như thế nào?',
      opts: o4('Nắng nóng, có gió Lào khô nóng', 'Lạnh và có tuyết', 'Mát mẻ quanh năm', 'Mưa suốt ngày'), ans: 'A',
      why: 'Mùa hè miền Trung nắng nóng, chịu ảnh hưởng của gió phơn Tây Nam (gió Lào) khô nóng.' },
  ],
},

/* ═══════════ ĐỀ 7 — CỐ ĐÔ HUẾ VÀ PHỐ CỔ HỘI AN ═══════════ */
{
  id: 5607, title: 'Đề 7 · Cố đô Huế và phố cổ Hội An', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Cố đô Huế từng là kinh đô của triều đại phong kiến nào cuối cùng ở nước ta?',
      opts: o4('Triều Nguyễn', 'Triều Lý', 'Triều Trần', 'Triều Lê'), ans: 'A',
      why: 'Huế (Phú Xuân) là kinh đô của triều Nguyễn — triều đại phong kiến cuối cùng của Việt Nam.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá thế giới', 'Kì quan thiên nhiên', 'Khu bảo tồn biển', 'Công viên giải trí'), ans: 'A',
      why: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là Di sản văn hoá thế giới (năm 1993).' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Con sông thơ mộng chảy qua thành phố Huế tên là gì?',
      opts: o4('Sông Hương', 'Sông Hồng', 'Sông Sài Gòn', 'Sông Đà'), ans: 'A',
      why: 'Sông Hương chảy qua Huế, cùng núi Ngự Bình tạo nên cảnh đẹp nổi tiếng của xứ Huế.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Khu vực các vua Nguyễn ở và làm việc trong Cố đô Huế gọi là gì?',
      opts: o4('Kinh thành (Hoàng thành, Đại Nội)', 'Bến cảng', 'Chợ nổi', 'Nhà máy'), ans: 'A',
      why: 'Kinh thành Huế với Hoàng thành (Đại Nội) là nơi ở và làm việc của các vua Nguyễn.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Phố cổ Hội An thuộc tỉnh nào?',
      opts: o4('Quảng Nam', 'Thừa Thiên Huế', 'Bình Định', 'Khánh Hoà'), ans: 'A',
      why: 'Phố cổ Hội An nằm ở tỉnh Quảng Nam, bên sông Thu Bồn.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Ngày xưa, Hội An nổi tiếng là gì?',
      opts: o4('Một thương cảng sầm uất, buôn bán với nước ngoài', 'Một pháo đài quân sự', 'Một khu rừng nguyên sinh', 'Một mỏ than'), ans: 'A',
      why: 'Hội An từng là thương cảng quốc tế sầm uất, buôn bán với thương nhân nhiều nước.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Công trình nổi tiếng ở Hội An, biểu tượng của phố cổ là gì?',
      opts: o4('Chùa Cầu (cầu Nhật Bản)', 'Tháp Rùa', 'Chợ Bến Thành', 'Nhà thờ Đức Bà'), ans: 'A',
      why: 'Chùa Cầu (cầu Nhật Bản) là công trình cổ, biểu tượng của phố cổ Hội An.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Phố cổ Hội An được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá thế giới', 'Kì quan thiên nhiên mới', 'Khu dự trữ sinh quyển', 'Vườn quốc gia'), ans: 'A',
      why: 'Phố cổ Hội An được UNESCO công nhận là Di sản văn hoá thế giới (năm 1999).' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Khi tham quan Cố đô Huế, Hội An, du khách cần có ý thức gì?',
      opts: o4('Giữ gìn, không phá hoại di tích, không xả rác', 'Khắc tên lên tường cổ', 'Sờ, trèo lên hiện vật', 'Vứt rác bừa bãi'), ans: 'A',
      why: 'Cần giữ gìn, bảo vệ di tích, không viết vẽ, xả rác hay phá hoại cảnh quan.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Vì sao cần bảo tồn Cố đô Huế và phố cổ Hội An?',
      opts: o4('Vì là di sản quý, thể hiện lịch sử – văn hoá dân tộc', 'Vì để bán lấy tiền', 'Vì đã cũ nên phá đi', 'Vì không ai quan tâm'), ans: 'A',
      why: 'Đây là những di sản quý giá phản ánh lịch sử, văn hoá dân tộc, cần được bảo tồn cho đời sau.' },
  ],
},

/* ═══════════ ĐỀ 8 — TÂY NGUYÊN ═══════════ */
{
  id: 5608, title: 'Đề 8 · Tây Nguyên', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Tây Nguyên có địa hình chủ yếu là gì?',
      opts: o4('Các cao nguyên xếp tầng', 'Đồng bằng ven biển', 'Vùng đất ngập nước', 'Đảo và quần đảo'), ans: 'A',
      why: 'Tây Nguyên gồm các cao nguyên rộng lớn, xếp tầng, có độ cao khác nhau.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đất ở Tây Nguyên chủ yếu là loại đất nào, thích hợp trồng cây công nghiệp?',
      opts: o4('Đất đỏ ba-dan', 'Đất phù sa', 'Đất cát', 'Đất sét trắng'), ans: 'A',
      why: 'Tây Nguyên có nhiều đất đỏ ba-dan màu mỡ, thích hợp trồng cây công nghiệp lâu năm.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Cây công nghiệp nào được trồng nhiều nhất và nổi tiếng ở Tây Nguyên?',
      opts: o4('Cây cà phê', 'Cây lúa nước', 'Cây chè', 'Cây táo'), ans: 'A',
      why: 'Tây Nguyên là vùng trồng cà phê lớn nhất cả nước; ngoài ra còn có cao su, hồ tiêu.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Tây Nguyên có khí hậu chia thành mấy mùa rõ rệt?',
      opts: o4('Hai mùa: mùa mưa và mùa khô', 'Bốn mùa như miền Bắc', 'Không có mùa nào', 'Chỉ có mùa đông'), ans: 'A',
      why: 'Tây Nguyên có hai mùa rõ rệt: mùa mưa và mùa khô.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Tây Nguyên là nơi sinh sống của nhiều dân tộc nào?',
      opts: o4('Gia-rai, Ê-đê, Ba-na, Xơ-đăng...', 'Chỉ có người nước ngoài', 'Không có ai', 'Chỉ có một dân tộc'), ans: 'A',
      why: 'Tây Nguyên là địa bàn cư trú lâu đời của nhiều dân tộc như Gia-rai, Ê-đê, Ba-na, Xơ-đăng...' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Ngôi nhà chung để sinh hoạt cộng đồng của một số dân tộc Tây Nguyên gọi là gì?',
      opts: o4('Nhà rông', 'Nhà sàn thấp', 'Nhà ống', 'Nhà chung cư'), ans: 'A',
      why: 'Nhà rông là ngôi nhà chung cao lớn, nơi sinh hoạt cộng đồng của buôn làng Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Loại nhạc cụ đặc trưng trong lễ hội của các dân tộc Tây Nguyên là gì?',
      opts: o4('Cồng, chiêng', 'Đàn bầu', 'Sáo trúc miền Bắc', 'Đàn ghi-ta điện'), ans: 'A',
      why: 'Cồng chiêng là nhạc cụ gắn với lễ hội và đời sống tinh thần của người Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: '"Không gian văn hoá Cồng chiêng Tây Nguyên" được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá phi vật thể của nhân loại', 'Kì quan thiên nhiên', 'Khu công nghiệp', 'Vườn thú'), ans: 'A',
      why: 'Không gian văn hoá Cồng chiêng Tây Nguyên được UNESCO công nhận là Di sản văn hoá phi vật thể.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Thành phố nào ở Tây Nguyên (Lâm Đồng) nổi tiếng khí hậu mát mẻ, nhiều hoa?',
      opts: o4('Đà Lạt', 'Nha Trang', 'Vũng Tàu', 'Hạ Long'), ans: 'A',
      why: 'Đà Lạt (Lâm Đồng) ở cao nguyên, khí hậu mát mẻ quanh năm, nổi tiếng là thành phố ngàn hoa.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Sông ở Tây Nguyên có nhiều thác ghềnh, thuận lợi để làm gì?',
      opts: o4('Xây dựng nhà máy thuỷ điện', 'Làm ruộng muối', 'Nuôi cá voi', 'Trồng lúa nước'), ans: 'A',
      why: 'Sông nhiều thác ghềnh, nước chảy mạnh nên Tây Nguyên có tiềm năng phát triển thuỷ điện.' },
  ],
},

/* ═══════════ ĐỀ 9 — NAM BỘ ═══════════ */
{
  id: 5609, title: 'Đề 9 · Nam Bộ và đồng bằng sông Cửu Long', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng lớn nhất nước ta nằm ở vùng nào?',
      opts: o4('Nam Bộ (đồng bằng sông Cửu Long)', 'Bắc Bộ', 'Tây Nguyên', 'Duyên hải miền Trung'), ans: 'A',
      why: 'Đồng bằng Nam Bộ, trong đó có đồng bằng sông Cửu Long, là đồng bằng lớn nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đồng bằng sông Cửu Long do con sông lớn nào bồi đắp?',
      opts: o4('Sông Cửu Long (sông Mê Kông)', 'Sông Hồng', 'Sông Hương', 'Sông Đà'), ans: 'A',
      why: 'Sông Mê Kông chảy vào nước ta gọi là sông Cửu Long, bồi đắp nên đồng bằng này.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Vì sao gọi là sông "Cửu Long" (chín rồng)?',
      opts: o4('Vì sông đổ ra biển bằng chín cửa sông', 'Vì có chín con rồng thật', 'Vì dài chín ki-lô-mét', 'Vì có chín chiếc cầu'), ans: 'A',
      why: '"Cửu Long" nghĩa là chín rồng — do sông đổ ra biển qua chín cửa (nay một số cửa đã thay đổi).' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Đồng bằng sông Cửu Long là vựa lớn nhất cả nước về sản phẩm nào?',
      opts: o4('Lúa gạo, trái cây và thuỷ sản', 'Than đá', 'Cà phê', 'Chè'), ans: 'A',
      why: 'Đồng bằng sông Cửu Long là vựa lúa, vựa trái cây và thuỷ sản lớn nhất nước ta.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Nét sinh hoạt đặc trưng trên sông nước ở Nam Bộ là gì?',
      opts: o4('Chợ nổi (mua bán trên thuyền, ghe)', 'Chợ phiên trên núi', 'Ruộng bậc thang', 'Săn bắn trong rừng'), ans: 'A',
      why: 'Chợ nổi (Cái Răng, Cái Bè...) — mua bán trên ghe thuyền — là nét đặc trưng của Nam Bộ.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Vùng Nam Bộ có khí hậu như thế nào?',
      opts: o4('Nóng quanh năm, có hai mùa mưa – khô', 'Bốn mùa rõ rệt', 'Rất lạnh, có tuyết', 'Mát mẻ như Đà Lạt'), ans: 'A',
      why: 'Nam Bộ nóng quanh năm, chia thành hai mùa: mùa mưa và mùa khô.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Thành phố lớn nhất, đông dân nhất nước ta là thành phố nào?',
      opts: o4('Thành phố Hồ Chí Minh', 'Hà Nội', 'Cần Thơ', 'Đà Nẵng'), ans: 'A',
      why: 'Thành phố Hồ Chí Minh là thành phố lớn nhất và đông dân nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Thành phố Hồ Chí Minh trước đây có tên gọi là gì?',
      opts: o4('Sài Gòn', 'Gia Định thành cổ xưa nhất', 'Thăng Long', 'Phú Xuân'), ans: 'A',
      why: 'Thành phố Hồ Chí Minh trước đây được gọi là Sài Gòn.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Địa đạo Củ Chi (gần TP. Hồ Chí Minh) là di tích gắn với điều gì?',
      opts: o4('Cuộc kháng chiến chống Mĩ của quân dân ta', 'Một khu chợ cổ', 'Một mỏ vàng', 'Một sân vận động'), ans: 'A',
      why: 'Địa đạo Củ Chi là hệ thống đường hầm, di tích của cuộc kháng chiến chống Mĩ.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Đồng bằng sông Cửu Long đang chịu ảnh hưởng nào cần được ứng phó?',
      opts: o4('Ngập lụt, xâm nhập mặn, sạt lở bờ sông', 'Tuyết rơi dày', 'Động đất mỗi ngày', 'Núi lửa'), ans: 'A',
      why: 'Vùng này chịu ngập lụt mùa nước nổi, xâm nhập mặn mùa khô và sạt lở bờ sông.' },
  ],
},

/* ═══════════ ĐỀ 10 — ÔN TẬP TỔNG HỢP CÁC VÙNG MIỀN ═══════════ */
{
  id: 5610, title: 'Đề 10 · Ôn tập các vùng miền', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Đỉnh núi cao nhất Việt Nam là:',
      opts: o4('Phan-xi-păng', 'Bà Đen', 'Ngự Bình', 'Fansipan giả'), ans: 'A',
      why: 'Phan-xi-păng (Hoàng Liên Sơn) cao khoảng 3143 m, cao nhất nước ta.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Đồng bằng Bắc Bộ do sông nào bồi đắp?',
      opts: o4('Sông Hồng và sông Thái Bình', 'Sông Cửu Long', 'Sông Hương', 'Sông Sài Gòn'), ans: 'A',
      why: 'Sông Hồng và sông Thái Bình bồi đắp nên đồng bằng Bắc Bộ.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Cố đô Huế là kinh đô của triều đại nào?',
      opts: o4('Triều Nguyễn', 'Triều Lý', 'Triều Trần', 'Triều Tây Sơn'), ans: 'A',
      why: 'Huế là kinh đô của triều Nguyễn — triều đại phong kiến cuối cùng của nước ta.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Vùng nào nổi tiếng trồng cà phê và có văn hoá cồng chiêng?',
      opts: o4('Tây Nguyên', 'Đồng bằng Bắc Bộ', 'Duyên hải miền Trung', 'Đồng bằng sông Cửu Long'), ans: 'A',
      why: 'Tây Nguyên trồng nhiều cà phê và có Không gian văn hoá Cồng chiêng nổi tiếng.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Đồng bằng lớn nhất nước ta là:',
      opts: o4('Đồng bằng sông Cửu Long (Nam Bộ)', 'Đồng bằng Bắc Bộ', 'Đồng bằng Thanh - Nghệ', 'Không có đồng bằng nào'), ans: 'A',
      why: 'Đồng bằng sông Cửu Long ở Nam Bộ là đồng bằng lớn nhất cả nước.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ (1954) là chiến thắng chống quân xâm lược nào?',
      opts: o4('Thực dân Pháp', 'Đế quốc Mĩ', 'Quân Thanh', 'Quân Nguyên'), ans: 'A',
      why: 'Điện Biên Phủ 1954 là chiến thắng kết thúc kháng chiến chống thực dân Pháp.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Thủ đô Hà Nội xưa có tên là:',
      opts: o4('Thăng Long', 'Sài Gòn', 'Phú Xuân', 'Hoa Lư'), ans: 'A',
      why: 'Hà Nội xưa tên là Thăng Long, do vua Lý Thái Tổ đặt khi dời đô năm 1010.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Vùng nào của nước ta thường xuyên chịu nhiều bão, lũ nhất?',
      opts: o4('Duyên hải miền Trung', 'Tây Nguyên', 'Đồng bằng Bắc Bộ', 'Trung du Bắc Bộ'), ans: 'A',
      why: 'Duyên hải miền Trung là vùng hứng chịu nhiều bão và lũ lụt.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Phố cổ Hội An và Cố đô Huế đều được UNESCO công nhận là:',
      opts: o4('Di sản văn hoá thế giới', 'Kì quan thiên nhiên', 'Khu công nghiệp', 'Sân bay quốc tế'), ans: 'A',
      why: 'Cả Cố đô Huế và phố cổ Hội An đều là Di sản văn hoá thế giới.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp giữ gìn và phát huy giá trị các vùng miền của đất nước?',
      opts: o4('Bảo vệ di tích, môi trường và tự hào giới thiệu quê hương', 'Phá hoại di tích', 'Xả rác nơi danh thắng', 'Chê bai quê hương'), ans: 'A',
      why: 'Bảo vệ di tích, giữ sạch môi trường và tự hào giới thiệu quê hương giúp phát huy giá trị các vùng miền.' },
  ],
},

/* ═══════════ ĐỀ 11 — ĐỊA PHƯƠNG EM VÀ KĨ NĂNG BẢN ĐỒ ═══════════ */
{
  id: 7901, title: 'Đề 11 · Địa phương em và bản đồ', time: 20,
  questions: [
    { sec: 'Bản đồ', name: 'Câu 1', pts: 1,
      text: 'Trên bản đồ, hướng nằm ở phía dưới thường là hướng nào?',
      opts: o4('Hướng đông', 'Hướng nam', 'Hướng tây', 'Hướng bắc'), ans: 'B',
      why: 'Theo quy ước: trên là bắc, dưới là nam, phải là đông, trái là tây.' },
    { sec: 'Bản đồ', name: 'Câu 2', pts: 1,
      text: 'Để biết một kí hiệu trên bản đồ có ý nghĩa gì, em cần xem phần nào?',
      opts: o4('Bảng chú giải', 'Tên tác giả', 'Số trang', 'Bìa sách'), ans: 'A',
      why: 'Bảng chú giải giải thích ý nghĩa của các kí hiệu, màu sắc trên bản đồ.' },
    { sec: 'Bản đồ', name: 'Câu 3', pts: 1,
      text: 'Trên bản đồ, vùng đồng bằng thường được tô bằng màu gì?',
      opts: o4('Màu nâu đậm', 'Màu tím', 'Màu xanh lá cây', 'Màu hồng'), ans: 'C',
      why: 'Đồng bằng thấp thường tô màu xanh lá cây; càng lên cao màu càng ngả vàng, cam, nâu.' },
    { sec: 'Bản đồ', name: 'Câu 4', pts: 1,
      text: 'Bốn hướng chính trên bản đồ và trên thực địa là gì?',
      opts: o4('Trên, dưới, trái, phải', 'Xa, gần, cao, thấp', 'Trước, sau, ngang, dọc', 'Đông, tây, nam, bắc'), ans: 'D',
      why: 'Bốn hướng chính là đông, tây, nam, bắc.' },
    { sec: 'Địa phương', name: 'Câu 5', pts: 1,
      text: 'Sắp xếp các đơn vị hành chính từ lớn đến nhỏ, cách nào đúng?',
      opts: o4('Tỉnh – huyện – xã', 'Xã – huyện – tỉnh', 'Huyện – tỉnh – xã', 'Tỉnh – xã – huyện'), ans: 'A',
      why: 'Tỉnh (thành phố) gồm nhiều huyện; huyện gồm nhiều xã, phường.' },
    { sec: 'Địa phương', name: 'Câu 6', pts: 1,
      text: 'Muốn xác định phương hướng ngoài thực địa vào ban ngày, em có thể dựa vào đâu?',
      opts: o4('Màu của mây', 'Tiếng chim hót', 'Hướng gió thổi luôn cố định', 'Vị trí Mặt Trời mọc và lặn'), ans: 'D',
      why: 'Mặt Trời mọc ở hướng đông, lặn ở hướng tây, giúp xác định phương hướng.' },
    { sec: 'Địa phương', name: 'Câu 7', pts: 1,
      text: 'Nước Việt Nam nằm ở châu lục nào?',
      opts: o4('Châu Âu', 'Châu Á', 'Châu Phi', 'Châu Đại Dương'), ans: 'B',
      why: 'Việt Nam thuộc khu vực Đông Nam Á, nằm ở châu Á.' },
    { sec: 'Địa phương', name: 'Câu 8', pts: 1,
      text: 'Phần đất liền nước ta có hình dáng giống chữ gì?',
      opts: o4('Chữ O', 'Chữ U', 'Chữ S', 'Chữ V'), ans: 'C',
      why: 'Phần đất liền nước ta cong cong, thường được ví như hình chữ S.' },
    { sec: 'Địa phương', name: 'Câu 9', pts: 1,
      text: 'Nước ta tiếp giáp với biển nào ở phía đông?',
      opts: o4('Biển Đỏ', 'Biển Đen', 'Địa Trung Hải', 'Biển Đông'), ans: 'D',
      why: 'Phía đông và nam nước ta giáp Biển Đông.' },
    { sec: 'Địa phương', name: 'Câu 10', pts: 1,
      text: 'Việc làm nào giúp em tìm hiểu tốt về địa phương mình?',
      opts: o4('Quan sát, hỏi người lớn và tra cứu tài liệu', 'Chỉ ngồi tưởng tượng', 'Bỏ qua không quan tâm', 'Chép của bạn cho nhanh'), ans: 'A',
      why: 'Quan sát thực tế, hỏi người lớn và tra cứu tài liệu giúp hiểu rõ về địa phương.' },
  ],
},

/* ═══════════ ĐỀ 12 — TRUNG DU VÀ MIỀN NÚI BẮC BỘ: THIÊN NHIÊN ═══════════ */
{
  id: 7902, title: 'Đề 12 · Trung du và miền núi Bắc Bộ (thiên nhiên)', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Vùng Trung du và miền núi Bắc Bộ nằm ở phía nào của nước ta?',
      opts: o4('Phía nam', 'Phía bắc', 'Ở giữa', 'Ngoài khơi'), ans: 'B',
      why: 'Trung du và miền núi Bắc Bộ là vùng nằm ở phía bắc nước ta.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đỉnh Phan-xi-păng cao khoảng bao nhiêu mét?',
      opts: o4('Khoảng 3143 m', 'Khoảng 1000 m', 'Khoảng 2000 m', 'Khoảng 5000 m'), ans: 'A',
      why: 'Phan-xi-păng cao khoảng 3143 m, là đỉnh cao nhất Việt Nam.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Phan-xi-păng được mệnh danh là gì?',
      opts: o4('"Vựa lúa miền Bắc"', '"Thành phố ngàn hoa"', '"Nóc nhà của Đông Dương"', '"Hòn ngọc Viễn Đông"'), ans: 'C',
      why: 'Là đỉnh cao nhất bán đảo Đông Dương nên Phan-xi-păng được gọi là "Nóc nhà của Đông Dương".' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Vùng trung du Bắc Bộ có địa hình chủ yếu là gì?',
      opts: o4('Núi cao hiểm trở', 'Đồng bằng phẳng lặng', 'Bãi cát ven biển', 'Đồi thấp có đỉnh tròn, sườn thoải'), ans: 'D',
      why: 'Trung du là vùng chuyển tiếp, có nhiều đồi thấp đỉnh tròn, sườn thoải.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Khí hậu vùng núi cao Bắc Bộ vào mùa đông như thế nào?',
      opts: o4('Rất lạnh, có nơi có băng tuyết', 'Nóng bức', 'Không thay đổi', 'Luôn oi ả'), ans: 'A',
      why: 'Vùng núi cao mùa đông rất lạnh, một số nơi (Sa Pa, Mẫu Sơn) có sương muối, băng tuyết.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Hồ nước ngọt tự nhiên nổi tiếng ở tỉnh Bắc Kạn là hồ nào?',
      opts: o4('Hồ Gươm', 'Hồ Tây', 'Hồ Xuân Hương', 'Hồ Ba Bể'), ans: 'D',
      why: 'Hồ Ba Bể (Bắc Kạn) là hồ nước ngọt tự nhiên lớn, cảnh đẹp nổi tiếng miền núi Bắc Bộ.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Vì sao vùng núi Bắc Bộ có nhiều thác nước, sông chảy xiết?',
      opts: o4('Vì gần biển', 'Vì địa hình cao, dốc', 'Vì đất bằng phẳng', 'Vì ít mưa'), ans: 'B',
      why: 'Địa hình cao và dốc khiến sông suối chảy xiết, tạo nhiều thác ghềnh.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Ruộng bậc thang được làm nhằm mục đích gì?',
      opts: o4('Để leo núi cho dễ', 'Để làm nơi vui chơi', 'Để trồng lúa, hoa màu trên sườn dốc', 'Để nuôi cá'), ans: 'C',
      why: 'Người dân xẻ sườn đồi núi thành bậc để giữ nước, trồng lúa và hoa màu.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Ruộng bậc thang ở Mù Cang Chải nổi tiếng thuộc tỉnh nào?',
      opts: o4('Hà Nội', 'Nghệ An', 'Cà Mau', 'Yên Bái'), ans: 'D',
      why: 'Ruộng bậc thang Mù Cang Chải thuộc tỉnh Yên Bái, là danh thắng nổi tiếng.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Việc phá rừng làm nương rẫy bừa bãi ở vùng núi có thể gây ra hậu quả gì?',
      opts: o4('Xói mòn đất, lũ quét, sạt lở', 'Đất thêm màu mỡ', 'Không ảnh hưởng gì', 'Làm mưa nhiều hơn có lợi'), ans: 'A',
      why: 'Mất rừng làm đất bị xói mòn, dễ xảy ra lũ quét và sạt lở đất.' },
  ],
},

/* ═══════════ ĐỀ 13 — MIỀN NÚI BẮC BỘ: DÂN TỘC, VĂN HOÁ, KHOÁNG SẢN ═══════════ */
{
  id: 7903, title: 'Đề 13 · Miền núi Bắc Bộ: dân tộc và khoáng sản', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Trang phục truyền thống của các dân tộc vùng cao Bắc Bộ có đặc điểm gì?',
      opts: o4('Đơn điệu một màu', 'Sặc sỡ, nhiều hoa văn thêu', 'Giống hệt nhau ở mọi dân tộc', 'Chỉ có màu đen'), ans: 'B',
      why: 'Mỗi dân tộc có trang phục riêng, thường sặc sỡ với nhiều hoa văn thêu tinh xảo.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Chợ phiên vùng cao thường họp như thế nào?',
      opts: o4('Họp vào những ngày nhất định', 'Họp hằng ngày cả ngày', 'Không bao giờ họp', 'Chỉ họp ban đêm'), ans: 'A',
      why: 'Chợ phiên họp theo phiên, vào những ngày nhất định trong tuần hoặc tháng.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Nhà ở phổ biến của nhiều dân tộc vùng núi Bắc Bộ là loại nhà gì?',
      opts: o4('Nhà nổi trên sông', 'Nhà chung cư', 'Nhà sàn', 'Lều tuyết'), ans: 'C',
      why: 'Nhiều dân tộc vùng núi ở nhà sàn để tránh ẩm thấp và thú dữ.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Vùng Quảng Ninh nổi tiếng khai thác khoáng sản nào?',
      opts: o4('Dầu mỏ', 'Vàng', 'Kim cương', 'Than đá'), ans: 'D',
      why: 'Quảng Ninh là vùng khai thác than đá lớn nhất nước ta.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'A-pa-tit — nguyên liệu làm phân bón — được khai thác nhiều ở tỉnh nào?',
      opts: o4('Lào Cai', 'Cà Mau', 'Bến Tre', 'Tiền Giang'), ans: 'A',
      why: 'Mỏ a-pa-tit ở Lào Cai cung cấp nguyên liệu sản xuất phân bón.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Khai thác khoáng sản cần chú ý điều gì để phát triển bền vững?',
      opts: o4('Khai thác thật nhiều bằng mọi giá', 'Bỏ mặc không quản lí', 'Vứt chất thải ra sông suối', 'Khai thác hợp lí và bảo vệ môi trường'), ans: 'D',
      why: 'Khoáng sản có hạn nên cần khai thác hợp lí, tiết kiệm và bảo vệ môi trường.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Vùng trung du Thái Nguyên, Phú Thọ nổi tiếng với cây trồng nào?',
      opts: o4('Cây dừa', 'Cây chè', 'Cây điều', 'Cây thanh long'), ans: 'B',
      why: 'Đồi trung du thoát nước tốt, thích hợp trồng chè; Thái Nguyên nổi tiếng chè ngon.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Lễ hội Lồng Tồng (xuống đồng) là lễ hội truyền thống của dân tộc nào?',
      opts: o4('Dân tộc Kinh ở đồng bằng', 'Dân tộc Chăm', 'Dân tộc Tày, Nùng', 'Dân tộc Khơ-me'), ans: 'C',
      why: 'Lễ hội Lồng Tồng (xuống đồng) là lễ hội cầu mùa của người Tày, Nùng vùng núi phía Bắc.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Cao nguyên đá Đồng Văn — công viên địa chất toàn cầu — thuộc tỉnh nào?',
      opts: o4('Quảng Ninh', 'Điện Biên', 'Hoà Bình', 'Hà Giang'), ans: 'D',
      why: 'Cao nguyên đá Đồng Văn (Hà Giang) được UNESCO công nhận là công viên địa chất toàn cầu.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Việc nhiều dân tộc cùng chung sống ở vùng núi Bắc Bộ tạo nên điều gì?',
      opts: o4('Nền văn hoá đa dạng, phong phú', 'Sự nghèo nàn văn hoá', 'Sự chia rẽ, xa cách', 'Không có gì đặc biệt'), ans: 'A',
      why: 'Nhiều dân tộc cùng sinh sống tạo nên bản sắc văn hoá đa dạng, phong phú của vùng.' },
  ],
},

/* ═══════════ ĐỀ 14 — ĐỒNG BẰNG BẮC BỘ: THIÊN NHIÊN VÀ SẢN XUẤT ═══════════ */
{
  id: 7904, title: 'Đề 14 · Đồng bằng Bắc Bộ (thiên nhiên, sản xuất)', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng Bắc Bộ có dạng địa hình như thế nào?',
      opts: o4('Đồi núi trập trùng', 'Tương đối bằng phẳng, thấp dần ra biển', 'Cao nguyên xếp tầng', 'Toàn đầm lầy'), ans: 'B',
      why: 'Đồng bằng Bắc Bộ khá bằng phẳng, địa hình thấp dần từ tây bắc xuống đông nam, ra biển.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Sông Hồng bắt nguồn từ đâu?',
      opts: o4('Từ Trung Quốc chảy vào nước ta', 'Từ biển chảy lên', 'Từ Tây Nguyên', 'Từ đồng bằng Nam Bộ'), ans: 'A',
      why: 'Sông Hồng bắt nguồn từ Trung Quốc, chảy qua nước ta rồi đổ ra Biển Đông.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Hệ thống đê ở đồng bằng Bắc Bộ chủ yếu dùng để làm gì?',
      opts: o4('Làm đường đua xe', 'Nuôi tôm cá', 'Ngăn lũ, bảo vệ mùa màng và làng mạc', 'Trồng cây cảnh'), ans: 'C',
      why: 'Đê ngăn nước sông dâng cao gây lũ, bảo vệ đồng ruộng và làng xóm.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Nhờ đâu đồng bằng Bắc Bộ trở thành vựa lúa lớn của cả nước?',
      opts: o4('Đất cát khô cằn', 'Khí hậu quá lạnh', 'Không có sông ngòi', 'Đất phù sa màu mỡ, nguồn nước dồi dào'), ans: 'D',
      why: 'Đất phù sa màu mỡ và nguồn nước từ sông giúp trồng lúa năng suất cao.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Một năm người dân đồng bằng Bắc Bộ thường cấy được mấy vụ lúa chính?',
      opts: o4('Hai vụ chính (chiêm và mùa)', 'Một vụ', 'Bốn vụ', 'Không có vụ nào'), ans: 'A',
      why: 'Người dân thường trồng hai vụ lúa chính là vụ chiêm và vụ mùa.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Vào mùa đông lạnh, đồng bằng Bắc Bộ thuận lợi trồng loại cây nào?',
      opts: o4('Cây cà phê', 'Cây cao su', 'Cây dừa', 'Rau xứ lạnh (su hào, bắp cải, cà chua...)'), ans: 'D',
      why: 'Mùa đông lạnh là điều kiện tốt để trồng nhiều loại rau xứ lạnh như su hào, bắp cải, cà chua.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Ngoài trồng lúa và rau, người dân đồng bằng Bắc Bộ còn chăn nuôi con gì phổ biến?',
      opts: o4('Voi và tê giác', 'Lợn, gà, vịt', 'Lạc đà', 'Tuần lộc'), ans: 'B',
      why: 'Chăn nuôi lợn, gia cầm (gà, vịt) rất phát triển ở đồng bằng Bắc Bộ.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Vì sao đồng bằng Bắc Bộ có mùa đông lạnh?',
      opts: o4('Do gần cực Bắc', 'Do ở trên núi cao', 'Do ảnh hưởng của gió mùa đông bắc', 'Do có tuyết rơi'), ans: 'C',
      why: 'Gió mùa đông bắc tràn về mang không khí lạnh, tạo nên mùa đông lạnh ở Bắc Bộ.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Thành phố cảng lớn ở đồng bằng Bắc Bộ, cửa ngõ ra biển của miền Bắc là thành phố nào?',
      opts: o4('Đà Lạt', 'Buôn Ma Thuột', 'Pleiku', 'Hải Phòng'), ans: 'D',
      why: 'Hải Phòng là thành phố cảng lớn, cửa ngõ ra biển quan trọng của miền Bắc.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Đồng bằng Bắc Bộ là đồng bằng lớn thứ mấy của nước ta?',
      opts: o4('Lớn thứ hai (sau đồng bằng sông Cửu Long)', 'Lớn nhất', 'Nhỏ nhất', 'Không có thứ hạng'), ans: 'A',
      why: 'Đồng bằng Bắc Bộ là đồng bằng lớn thứ hai, sau đồng bằng sông Cửu Long.' },
  ],
},

/* ═══════════ ĐỀ 15 — ĐỒNG BẰNG BẮC BỘ: LÀNG NGHỀ VÀ LỄ HỘI ═══════════ */
{
  id: 7905, title: 'Đề 15 · Đồng bằng Bắc Bộ (làng nghề, lễ hội)', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Làng nghề là nơi như thế nào?',
      opts: o4('Nơi chỉ để ở', 'Nơi nhiều gia đình cùng làm một nghề thủ công truyền thống', 'Nơi khai thác than', 'Nơi nuôi cá biển'), ans: 'B',
      why: 'Làng nghề là làng mà nhiều gia đình cùng làm một nghề thủ công truyền thống lâu đời.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Làng Bát Tràng (Hà Nội) nổi tiếng với nghề gì?',
      opts: o4('Làm gốm sứ', 'Dệt lụa', 'Đúc đồng', 'Làm nón'), ans: 'A',
      why: 'Bát Tràng là làng nghề làm gốm sứ nổi tiếng của đồng bằng Bắc Bộ.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Làng lụa Vạn Phúc (Hà Nội) nổi tiếng với sản phẩm nào?',
      opts: o4('Đồ gốm', 'Tranh sơn mài', 'Lụa tơ tằm', 'Đồ sắt'), ans: 'C',
      why: 'Vạn Phúc là làng nghề dệt lụa tơ tằm truyền thống nổi tiếng.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Sản phẩm của các làng nghề thường được làm bằng cách nào?',
      opts: o4('Hoàn toàn tự động không cần người', 'Không cần kĩ thuật gì', 'Đào từ dưới đất lên', 'Chủ yếu bằng tay, khéo léo, tỉ mỉ'), ans: 'D',
      why: 'Sản phẩm làng nghề chủ yếu làm thủ công bằng bàn tay khéo léo, tỉ mỉ của người thợ.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Hội Lim — hát quan họ — là lễ hội nổi tiếng của tỉnh nào?',
      opts: o4('Bắc Ninh', 'Hà Giang', 'Nghệ An', 'Quảng Nam'), ans: 'A',
      why: 'Hội Lim ở Bắc Ninh nổi tiếng với những làn điệu dân ca quan họ.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Dân ca quan họ Bắc Ninh được UNESCO công nhận là gì?',
      opts: o4('Kì quan thiên nhiên', 'Di sản thiên nhiên', 'Khu bảo tồn biển', 'Di sản văn hoá phi vật thể của nhân loại'), ans: 'D',
      why: 'Dân ca quan họ Bắc Ninh được UNESCO ghi danh là Di sản văn hoá phi vật thể của nhân loại.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Hội Gióng (Sóc Sơn, Phù Đổng) tưởng nhớ nhân vật nào?',
      opts: o4('Hai Bà Trưng', 'Thánh Gióng đánh giặc Ân', 'Ngô Quyền', 'Lê Lợi'), ans: 'B',
      why: 'Hội Gióng tưởng nhớ Thánh Gióng — người anh hùng đánh giặc Ân trong truyền thuyết.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Lễ hội chùa Hương (Hà Nội) thường diễn ra vào mùa nào?',
      opts: o4('Mùa hè', 'Mùa thu', 'Mùa xuân', 'Mùa đông'), ans: 'C',
      why: 'Lễ hội chùa Hương kéo dài trong mùa xuân, thu hút đông đảo du khách trẩy hội.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Vì sao cần giữ gìn các làng nghề truyền thống?',
      opts: o4('Vì làng nghề cũ kĩ nên bỏ đi', 'Vì không có ích gì', 'Vì làm ô nhiễm nên phải xoá bỏ', 'Vì đó là nét văn hoá quý và tạo việc làm'), ans: 'D',
      why: 'Làng nghề lưu giữ nét văn hoá truyền thống và tạo việc làm, thu nhập cho người dân.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Lễ hội truyền thống thường được tổ chức để làm gì?',
      opts: o4('Tưởng nhớ công ơn tổ tiên, anh hùng và cầu mong tốt lành', 'Chỉ để mua bán', 'Không có mục đích', 'Để phá bỏ phong tục'), ans: 'A',
      why: 'Lễ hội thể hiện lòng biết ơn tổ tiên, các vị anh hùng và ước mong cuộc sống tốt lành.' },
  ],
},

/* ═══════════ ĐỀ 16 — THĂNG LONG – HÀ NỘI VÀ VĂN MIẾU ═══════════ */
{
  id: 7906, title: 'Đề 16 · Thăng Long – Hà Nội và Văn Miếu', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Vua Lý Thái Tổ dời đô từ Hoa Lư ra Thăng Long vào năm nào?',
      opts: o4('Năm 938', 'Năm 1010', 'Năm 1288', 'Năm 1789'), ans: 'B',
      why: 'Năm 1010, vua Lý Thái Tổ (Lý Công Uẩn) dời đô ra Thăng Long.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Trước khi dời đô ra Thăng Long, kinh đô của nước ta đặt ở đâu?',
      opts: o4('Hoa Lư (Ninh Bình)', 'Phú Xuân (Huế)', 'Gia Định', 'Cổ Loa'), ans: 'A',
      why: 'Trước đó kinh đô đặt ở Hoa Lư (Ninh Bình), thời Đinh và Tiền Lê.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Tên "Thăng Long" có nghĩa là gì?',
      opts: o4('Rồng vàng', 'Rồng cuộn', 'Rồng bay lên', 'Rồng ngủ'), ans: 'C',
      why: 'Tương truyền khi dời đô, vua thấy rồng bay lên nên đặt tên là Thăng Long — "rồng bay lên".' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Văn Miếu được xây dựng để thờ ai?',
      opts: o4('Các Vua Hùng', 'Thần Sông', 'Thánh Gióng', 'Khổng Tử và các bậc hiền tài'), ans: 'D',
      why: 'Văn Miếu thờ Khổng Tử và tôn vinh các bậc hiền tài, người học rộng tài cao.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Quốc Tử Giám được coi là gì của nước ta?',
      opts: o4('Trường đại học đầu tiên', 'Chợ đầu tiên', 'Bến cảng đầu tiên', 'Nhà máy đầu tiên'), ans: 'A',
      why: 'Quốc Tử Giám được xem là trường đại học đầu tiên của Việt Nam.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Bia tiến sĩ trong Văn Miếu ghi lại điều gì?',
      opts: o4('Giá cả hàng hoá', 'Bản đồ đất nước', 'Công thức nấu ăn', 'Tên tuổi những người thi đỗ tiến sĩ'), ans: 'D',
      why: 'Bia tiến sĩ khắc tên những người đỗ đạt qua các khoa thi, nhằm khuyến khích việc học.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Truyền thuyết Hồ Gươm kể vua Lê Lợi trả gươm cho ai?',
      opts: o4('Chim Lạc', 'Rùa Thần', 'Rồng Vàng', 'Cá Chép'), ans: 'B',
      why: 'Truyền thuyết kể Lê Lợi hoàn trả gươm báu cho Rùa Thần ở hồ Hoàn Kiếm.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: '"Hoàn Kiếm" trong tên Hồ Hoàn Kiếm có nghĩa là gì?',
      opts: o4('Hồ lớn', 'Nước trong', 'Trả lại gươm', 'Cây xanh'), ans: 'C',
      why: '"Hoàn Kiếm" nghĩa là "trả lại gươm", gắn với truyền thuyết vua Lê trả gươm.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Ngày nay, Hà Nội giữ vai trò gì đối với cả nước?',
      opts: o4('Chỉ là một huyện nhỏ', 'Là một hòn đảo', 'Là vùng biển', 'Là thủ đô, trung tâm chính trị – văn hoá'), ans: 'D',
      why: 'Hà Nội là thủ đô — trung tâm chính trị, văn hoá, khoa học, giáo dục của cả nước.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Khu di tích Hoàng thành Thăng Long ở Hà Nội được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá thế giới', 'Kì quan thiên nhiên', 'Khu dự trữ sinh quyển', 'Vườn quốc gia'), ans: 'A',
      why: 'Khu trung tâm Hoàng thành Thăng Long được UNESCO công nhận là Di sản văn hoá thế giới (năm 2010).' },
  ],
},

/* ═══════════ ĐỀ 17 — DUYÊN HẢI MIỀN TRUNG: BIỂN VÀ THIÊN NHIÊN ═══════════ */
{
  id: 7907, title: 'Đề 17 · Duyên hải miền Trung (biển, thiên nhiên)', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Vì sao đồng bằng ở duyên hải miền Trung nhỏ hẹp?',
      opts: o4('Vì có quá nhiều sông lớn', 'Vì núi ăn lan ra sát biển', 'Vì đất bị ngập mặn hết', 'Vì toàn là cao nguyên'), ans: 'B',
      why: 'Dãy Trường Sơn và các nhánh núi ăn lan ra sát biển nên đồng bằng ven biển bị chia cắt, nhỏ hẹp.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Miền Trung là vùng có đường bờ biển như thế nào?',
      opts: o4('Dài, nhiều bãi biển đẹp', 'Ngắn nhất nước', 'Không giáp biển', 'Toàn đầm lầy'), ans: 'A',
      why: 'Duyên hải miền Trung có bờ biển dài với nhiều bãi biển đẹp, vũng, vịnh.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Vùng biển miền Trung thuận lợi phát triển những ngành nào?',
      opts: o4('Trồng cà phê, cao su', 'Khai thác than đá', 'Đánh bắt hải sản, làm muối, du lịch biển', 'Trồng lúa nước quy mô lớn'), ans: 'C',
      why: 'Biển miền Trung thuận lợi cho đánh bắt hải sản, làm muối và phát triển du lịch biển.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Đầm phá nước lợ lớn nhất Đông Nam Á ở Thừa Thiên Huế tên là gì?',
      opts: o4('Hồ Ba Bể', 'Biển Hồ', 'Vịnh Hạ Long', 'Phá Tam Giang'), ans: 'D',
      why: 'Phá Tam Giang – Cầu Hai (Thừa Thiên Huế) là hệ đầm phá nước lợ lớn nhất khu vực.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Vì sao miền Trung thường xuyên có bão vào mùa mưa?',
      opts: o4('Vì nằm ven Biển Đông, nơi nhiều bão đổ bộ', 'Vì ở trên núi cao', 'Vì quá xa biển', 'Vì có tuyết'), ans: 'A',
      why: 'Miền Trung nằm ven Biển Đông nên hứng chịu nhiều cơn bão đổ bộ vào mùa mưa bão.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Gió Lào (gió phơn Tây Nam) thổi vào miền Trung mùa hè có đặc điểm gì?',
      opts: o4('Ẩm và mát', 'Lạnh buốt', 'Kèm theo tuyết', 'Khô và nóng'), ans: 'D',
      why: 'Gió Lào thổi qua dãy Trường Sơn trở nên khô và nóng, gây oi bức cho miền Trung.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Vịnh biển nào ở Quảng Ninh (giáp Bắc Bộ) là Di sản thiên nhiên thế giới nổi tiếng?',
      opts: o4('Vịnh Cam Ranh', 'Vịnh Hạ Long', 'Vịnh Vân Phong', 'Vịnh Xuân Đài'), ans: 'B',
      why: 'Vịnh Hạ Long được UNESCO công nhận là Di sản thiên nhiên thế giới với hàng nghìn hòn đảo đá.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Để giảm thiệt hại do bão lũ, người dân miền Trung nên làm gì trước khi bão đến?',
      opts: o4('Ra khơi đánh cá', 'Chặt hết cây quanh nhà', 'Chằng chống nhà cửa, dự trữ lương thực, theo dõi dự báo', 'Không làm gì cả'), ans: 'C',
      why: 'Cần chằng chống nhà cửa, dự trữ lương thực, theo dõi dự báo và sẵn sàng sơ tán.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Trồng rừng phòng hộ ven biển miền Trung có tác dụng gì?',
      opts: o4('Gây ra bão', 'Làm biển dâng cao', 'Không có tác dụng', 'Chắn gió, chắn cát bay và giữ đất'), ans: 'D',
      why: 'Rừng phi lao, rừng ngập mặn ven biển giúp chắn gió, chắn cát và chống xói lở bờ biển.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Thành phố Đà Nẵng nổi tiếng với cây cầu nào bắc qua sông Hàn?',
      opts: o4('Cầu Rồng', 'Cầu Long Biên', 'Cầu Tràng Tiền', 'Cầu Mỹ Thuận'), ans: 'A',
      why: 'Cầu Rồng bắc qua sông Hàn là biểu tượng nổi tiếng của thành phố Đà Nẵng.' },
  ],
},

/* ═══════════ ĐỀ 18 — CỐ ĐÔ HUẾ VÀ PHỐ CỔ HỘI AN ═══════════ */
{
  id: 7908, title: 'Đề 18 · Cố đô Huế và phố cổ Hội An', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Huế từng là kinh đô của triều đại nào?',
      opts: o4('Triều Lý', 'Triều Nguyễn', 'Triều Trần', 'Triều Lê'), ans: 'B',
      why: 'Huế (Phú Xuân) là kinh đô của triều Nguyễn — triều đại phong kiến cuối cùng của nước ta.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Núi nào cùng với sông Hương tạo nên cảnh đẹp nổi tiếng của Huế?',
      opts: o4('Núi Ngự Bình', 'Núi Bà Đen', 'Núi Yên Tử', 'Núi Fansipan'), ans: 'A',
      why: 'Sông Hương và núi Ngự Bình là biểu tượng thiên nhiên của xứ Huế.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Nhã nhạc — âm nhạc cung đình Huế — được UNESCO công nhận là gì?',
      opts: o4('Kì quan thiên nhiên', 'Di sản thiên nhiên', 'Di sản văn hoá phi vật thể của nhân loại', 'Khu bảo tồn biển'), ans: 'C',
      why: 'Nhã nhạc cung đình Huế được UNESCO ghi danh là Di sản văn hoá phi vật thể của nhân loại.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Trong Kinh thành Huế, nơi ở và làm việc của vua gọi là gì?',
      opts: o4('Chợ Đông Ba', 'Bến Ninh Kiều', 'Nhà Rông', 'Đại Nội (Hoàng thành)'), ans: 'D',
      why: 'Đại Nội (Hoàng thành) là khu vực ở và làm việc của vua và triều đình nhà Nguyễn.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Phố cổ Hội An nằm bên bờ con sông nào?',
      opts: o4('Sông Thu Bồn', 'Sông Hồng', 'Sông Đồng Nai', 'Sông Đà'), ans: 'A',
      why: 'Phố cổ Hội An (Quảng Nam) nằm bên hạ lưu sông Thu Bồn.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Vì sao Hội An xưa trở thành thương cảng sầm uất?',
      opts: o4('Vì có mỏ vàng', 'Vì nằm trên núi cao', 'Vì có nhiều nhà máy', 'Vì ở vị trí thuận lợi, thuyền buôn nước ngoài hay ghé'), ans: 'D',
      why: 'Vị trí ven sông gần biển thuận lợi khiến thương nhân nhiều nước đến Hội An buôn bán.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Biểu tượng của phố cổ Hội An là công trình nào?',
      opts: o4('Tháp Rùa', 'Chùa Cầu', 'Cầu Rồng', 'Chợ Bến Thành'), ans: 'B',
      why: 'Chùa Cầu (còn gọi cầu Nhật Bản) là công trình cổ, biểu tượng của Hội An.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Ngôi nhà cổ ở Hội An thường có đặc điểm gì?',
      opts: o4('Nhà cao tầng bằng kính', 'Nhà sàn gỗ trên núi', 'Mái ngói, tường vàng, kiến trúc cổ hàng trăm năm', 'Nhà nổi trên sông'), ans: 'C',
      why: 'Hội An giữ được nhiều ngôi nhà cổ mái ngói, tường vàng, kiến trúc lâu đời độc đáo.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Cả Cố đô Huế và phố cổ Hội An đều được UNESCO công nhận là gì?',
      opts: o4('Kì quan thiên nhiên mới', 'Khu công nghiệp', 'Cảng biển quốc tế', 'Di sản văn hoá thế giới'), ans: 'D',
      why: 'Quần thể di tích Cố đô Huế và phố cổ Hội An đều là Di sản văn hoá thế giới.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Khi tham quan di tích, hành động nào là đúng?',
      opts: o4('Giữ trật tự, không xả rác, không phá hoại', 'Viết, vẽ lên tường', 'Trèo lên hiện vật', 'Bẻ cây, ngắt hoa'), ans: 'A',
      why: 'Cần giữ gìn di tích: không xả rác, không viết vẽ, không phá hoại cảnh quan và hiện vật.' },
  ],
},

/* ═══════════ ĐỀ 19 — TÂY NGUYÊN: THIÊN NHIÊN VÀ CÀ PHÊ ═══════════ */
{
  id: 7909, title: 'Đề 19 · Tây Nguyên (thiên nhiên, cà phê)', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Tây Nguyên nằm ở phía nào của dãy Trường Sơn?',
      opts: o4('Ngoài biển', 'Phía tây (Trường Sơn Nam)', 'Ở đồng bằng Bắc Bộ', 'Ở Nam Bộ ven biển'), ans: 'B',
      why: 'Tây Nguyên là vùng cao nguyên rộng lớn nằm ở phía tây dãy Trường Sơn Nam.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Đặc điểm nổi bật của đất ba-dan ở Tây Nguyên là gì?',
      opts: o4('Màu đỏ, tơi xốp, màu mỡ', 'Trắng và mặn', 'Toàn sỏi đá', 'Ngập nước quanh năm'), ans: 'A',
      why: 'Đất đỏ ba-dan tơi xốp, màu mỡ, rất thích hợp trồng cây công nghiệp lâu năm.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Cây công nghiệp nào là thế mạnh số một của Tây Nguyên?',
      opts: o4('Cây lúa nước', 'Cây chè', 'Cây cà phê', 'Cây vải'), ans: 'C',
      why: 'Tây Nguyên là vùng trồng cà phê lớn nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Ngoài cà phê, Tây Nguyên còn trồng nhiều cây công nghiệp nào?',
      opts: o4('Lúa mì, ngô ngọt xuất khẩu', 'Dừa và cói', 'Táo và lê', 'Cao su, hồ tiêu, chè'), ans: 'D',
      why: 'Tây Nguyên còn trồng nhiều cao su, hồ tiêu, chè trên đất ba-dan.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Thành phố nào được xem là "thủ phủ cà phê" của Tây Nguyên?',
      opts: o4('Buôn Ma Thuột (Đắk Lắk)', 'Nha Trang', 'Vũng Tàu', 'Hải Phòng'), ans: 'A',
      why: 'Buôn Ma Thuột (Đắk Lắk) nổi tiếng là thủ phủ cà phê của Tây Nguyên và cả nước.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Tây Nguyên có mấy mùa rõ rệt?',
      opts: o4('Bốn mùa', 'Chỉ có mùa đông', 'Không có mùa nào', 'Hai mùa: mùa mưa và mùa khô'), ans: 'D',
      why: 'Tây Nguyên có hai mùa rõ rệt: mùa mưa và mùa khô.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Vào mùa khô kéo dài, Tây Nguyên thường gặp khó khăn gì cho sản xuất?',
      opts: o4('Ngập lụt kéo dài', 'Thiếu nước tưới', 'Rét đậm, rét hại', 'Sóng thần'), ans: 'B',
      why: 'Mùa khô kéo dài gây thiếu nước tưới cho cây trồng, nhất là cà phê.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Sông ở Tây Nguyên nhiều thác ghềnh nên thuận lợi phát triển ngành nào?',
      opts: o4('Làm muối', 'Nuôi trồng thuỷ sản biển', 'Thuỷ điện', 'Đóng tàu biển'), ans: 'C',
      why: 'Sông dốc, nhiều thác ghềnh giúp Tây Nguyên phát triển thuỷ điện (Y-a-ly, Đrây H\'linh...).' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Thành phố Đà Lạt (Lâm Đồng) có khí hậu như thế nào?',
      opts: o4('Nóng như sa mạc', 'Rét buốt có tuyết dày', 'Ngập nước quanh năm', 'Mát mẻ quanh năm'), ans: 'D',
      why: 'Đà Lạt ở trên cao nguyên nên khí hậu mát mẻ quanh năm, thích hợp trồng hoa, rau xứ lạnh.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Để trồng cà phê bền vững ở Tây Nguyên, cần làm gì?',
      opts: o4('Bảo vệ rừng, dùng nước tưới hợp lí', 'Chặt hết rừng để lấy đất', 'Bỏ mặc không chăm sóc', 'Chỉ trồng vào mùa khô'), ans: 'A',
      why: 'Cần bảo vệ rừng, sử dụng nguồn nước hợp lí để giữ đất và phát triển cà phê bền vững.' },
  ],
},

/* ═══════════ ĐỀ 20 — TÂY NGUYÊN: DÂN TỘC, CỒNG CHIÊNG, VOI ═══════════ */
{
  id: 7910, title: 'Đề 20 · Tây Nguyên (dân tộc, cồng chiêng)', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Buôn (làng) là gì đối với các dân tộc Tây Nguyên?',
      opts: o4('Một loại nhạc cụ', 'Đơn vị dân cư — nơi cùng chung sống', 'Một loại cây trồng', 'Một dòng sông'), ans: 'B',
      why: 'Buôn (hoặc bon, plei) là đơn vị dân cư, nơi cộng đồng người Tây Nguyên cùng sinh sống.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Ngôi nhà chung cao lớn, nơi sinh hoạt cộng đồng của buôn làng gọi là gì?',
      opts: o4('Nhà rông', 'Nhà tầng', 'Nhà nổi', 'Nhà chòi canh'), ans: 'A',
      why: 'Nhà rông là ngôi nhà chung, cao lớn, nơi hội họp, sinh hoạt cộng đồng của buôn làng Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Dân tộc nào KHÔNG phải là dân tộc sinh sống lâu đời ở Tây Nguyên?',
      opts: o4('Gia-rai', 'Ê-đê', 'Tày', 'Ba-na'), ans: 'C',
      why: 'Tày là dân tộc ở vùng núi phía Bắc; Gia-rai, Ê-đê, Ba-na mới là dân tộc bản địa Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Cồng, chiêng của người Tây Nguyên thường được làm bằng chất liệu gì?',
      opts: o4('Gỗ', 'Nhựa', 'Đá', 'Đồng'), ans: 'D',
      why: 'Cồng chiêng được đúc bằng đồng, gõ lên tạo âm thanh vang trong các lễ hội.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: '"Không gian văn hoá Cồng chiêng Tây Nguyên" được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá phi vật thể của nhân loại', 'Kì quan thiên nhiên', 'Di sản thiên nhiên', 'Công viên địa chất'), ans: 'A',
      why: 'Không gian văn hoá Cồng chiêng Tây Nguyên được UNESCO ghi danh là Di sản văn hoá phi vật thể.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Cồng chiêng thường được sử dụng trong dịp nào?',
      opts: o4('Đi học hằng ngày', 'Ra khơi đánh cá', 'Họp chợ mua bán', 'Lễ hội, cúng tế, mừng mùa'), ans: 'D',
      why: 'Cồng chiêng gắn với các lễ hội, nghi lễ cúng tế, mừng lúa mới của người Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Con vật nào được người Tây Nguyên thuần dưỡng, gắn với lễ hội đua ở Bản Đôn?',
      opts: o4('Con lạc đà', 'Con voi', 'Con ngựa vằn', 'Con hươu cao cổ'), ans: 'B',
      why: 'Voi được người Tây Nguyên thuần dưỡng; lễ hội đua voi ở Bản Đôn (Đắk Lắk) rất nổi tiếng.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Trường ca "Đăm Săn" là di sản văn hoá của dân tộc nào ở Tây Nguyên?',
      opts: o4('Dân tộc Kinh', 'Dân tộc Chăm', 'Dân tộc Ê-đê', 'Dân tộc Thái'), ans: 'C',
      why: 'Sử thi (trường ca) "Đăm Săn" là tác phẩm nổi tiếng của người Ê-đê ở Tây Nguyên.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Lễ hội "mừng lúa mới" của người Tây Nguyên thể hiện điều gì?',
      opts: o4('Việc mua bán hàng hoá', 'Việc đi đánh cá', 'Việc khai thác than', 'Niềm vui được mùa và lòng biết ơn thần linh, đất trời'), ans: 'D',
      why: 'Lễ mừng lúa mới thể hiện niềm vui được mùa và lòng biết ơn trời đất, thần linh.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Chúng ta cần làm gì để giữ gìn văn hoá cồng chiêng Tây Nguyên?',
      opts: o4('Trân trọng, học hỏi và bảo tồn', 'Coi thường, bỏ quên', 'Bán hết cồng chiêng đi', 'Không quan tâm'), ans: 'A',
      why: 'Cần trân trọng, gìn giữ và truyền dạy để bảo tồn di sản cồng chiêng cho đời sau.' },
  ],
},

/* ═══════════ ĐỀ 21 — NAM BỘ: ĐỒNG BẰNG SÔNG CỬU LONG ═══════════ */
{
  id: 7911, title: 'Đề 21 · Nam Bộ và đồng bằng sông Cửu Long', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng sông Cửu Long còn được gọi là gì?',
      opts: o4('Miền Đông Bắc', 'Miền Tây Nam Bộ', 'Tây Nguyên', 'Trung du Bắc Bộ'), ans: 'B',
      why: 'Đồng bằng sông Cửu Long thường được gọi là miền Tây Nam Bộ.' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Sông Cửu Long là tên gọi ở nước ta của con sông nào?',
      opts: o4('Sông Mê Kông', 'Sông Hồng', 'Sông Đà', 'Sông Mã'), ans: 'A',
      why: 'Sông Mê Kông khi chảy vào nước ta chia thành nhiều nhánh, gọi là sông Cửu Long.' },
    { sec: 'Địa lí', name: 'Câu 3', pts: 1,
      text: 'Hai nhánh sông lớn của sông Cửu Long ở nước ta là gì?',
      opts: o4('Sông Hồng và sông Đà', 'Sông Hương và sông Bồ', 'Sông Tiền và sông Hậu', 'Sông Cầu và sông Thương'), ans: 'C',
      why: 'Sông Cửu Long ở nước ta gồm hai nhánh chính là sông Tiền và sông Hậu.' },
    { sec: 'Địa lí', name: 'Câu 4', pts: 1,
      text: 'Đồng bằng sông Cửu Long có nhiều gì chằng chịt, thuận lợi đi lại bằng thuyền?',
      opts: o4('Đồi núi', 'Sa mạc', 'Hang động', 'Sông ngòi, kênh rạch'), ans: 'D',
      why: 'Vùng này có mạng lưới sông ngòi, kênh rạch chằng chịt, đi lại nhiều bằng ghe, thuyền.' },
    { sec: 'Địa lí', name: 'Câu 5', pts: 1,
      text: 'Đồng bằng sông Cửu Long dẫn đầu cả nước về sản phẩm nào?',
      opts: o4('Lúa gạo và thuỷ sản', 'Than đá', 'Cà phê', 'Chè'), ans: 'A',
      why: 'Đây là vựa lúa, vựa trái cây và vựa thuỷ sản lớn nhất cả nước.' },
    { sec: 'Địa lí', name: 'Câu 6', pts: 1,
      text: 'Chợ nổi là nét sinh hoạt độc đáo của vùng nào?',
      opts: o4('Miền núi Bắc Bộ', 'Tây Nguyên', 'Duyên hải miền Trung', 'Đồng bằng sông Cửu Long'), ans: 'D',
      why: 'Chợ nổi — mua bán trên ghe thuyền — là nét đặc trưng của đồng bằng sông Cửu Long.' },
    { sec: 'Địa lí', name: 'Câu 7', pts: 1,
      text: 'Chợ nổi Cái Răng nổi tiếng thuộc thành phố nào?',
      opts: o4('Hà Nội', 'Cần Thơ', 'Đà Nẵng', 'Huế'), ans: 'B',
      why: 'Chợ nổi Cái Răng là chợ nổi nổi tiếng ở thành phố Cần Thơ.' },
    { sec: 'Địa lí', name: 'Câu 8', pts: 1,
      text: 'Loại nhà nào phổ biến ở vùng sông nước, hay ngập lụt của Nam Bộ?',
      opts: o4('Nhà băng tuyết', 'Nhà hang đá', 'Nhà sàn, nhà nổi ven sông', 'Lều du mục'), ans: 'C',
      why: 'Người dân làm nhà sàn, nhà nổi ven sông để thích nghi với vùng sông nước, ngập lụt.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Mũi đất cực nam của nước ta trên đất liền thuộc tỉnh nào?',
      opts: o4('Kiên Giang', 'An Giang', 'Long An', 'Cà Mau'), ans: 'D',
      why: 'Mũi Cà Mau (tỉnh Cà Mau) là điểm cực nam trên đất liền của nước ta.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Vào mùa khô, đồng bằng sông Cửu Long thường gặp khó khăn gì?',
      opts: o4('Xâm nhập mặn, thiếu nước ngọt', 'Rét đậm rét hại', 'Bão tuyết', 'Động đất'), ans: 'A',
      why: 'Mùa khô, nước biển lấn sâu vào đất liền gây xâm nhập mặn, thiếu nước ngọt cho sản xuất.' },
  ],
},

/* ═══════════ ĐỀ 22 — THÀNH PHỐ HỒ CHÍ MINH VÀ ĐỊA ĐẠO CỦ CHI ═══════════ */
{
  id: 7912, title: 'Đề 22 · Thành phố Hồ Chí Minh và Củ Chi', time: 20,
  questions: [
    { sec: 'Địa lí', name: 'Câu 1', pts: 1,
      text: 'Thành phố Hồ Chí Minh nằm ở vùng nào của nước ta?',
      opts: o4('Đồng bằng Bắc Bộ', 'Đông Nam Bộ', 'Tây Nguyên', 'Trung du Bắc Bộ'), ans: 'B',
      why: 'Thành phố Hồ Chí Minh thuộc vùng Đông Nam Bộ (Nam Bộ).' },
    { sec: 'Địa lí', name: 'Câu 2', pts: 1,
      text: 'Thành phố Hồ Chí Minh có đặc điểm gì về dân số và kinh tế?',
      opts: o4('Đông dân nhất, trung tâm kinh tế lớn nhất nước', 'Ít dân, kinh tế nhỏ', 'Không có công nghiệp', 'Chỉ làm nông nghiệp'), ans: 'A',
      why: 'Đây là thành phố đông dân nhất và là trung tâm kinh tế lớn nhất của cả nước.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Trước năm 1976, Thành phố Hồ Chí Minh có tên là gì?',
      opts: o4('Thăng Long', 'Phú Xuân', 'Sài Gòn', 'Đông Đô'), ans: 'C',
      why: 'Thành phố mang tên Sài Gòn; năm 1976 được đổi tên thành Thành phố Hồ Chí Minh.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Chợ nào là biểu tượng nổi tiếng của Thành phố Hồ Chí Minh?',
      opts: o4('Chợ Đồng Xuân', 'Chợ Đông Ba', 'Chợ Cái Răng', 'Chợ Bến Thành'), ans: 'D',
      why: 'Chợ Bến Thành là khu chợ lâu đời, biểu tượng quen thuộc của Thành phố Hồ Chí Minh.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Bến cảng nơi Bác Hồ ra đi tìm đường cứu nước (1911) ở Sài Gòn tên là gì?',
      opts: o4('Bến Nhà Rồng', 'Bến Ninh Kiều', 'Bến Bạch Đằng cổ', 'Bến Vân Đồn'), ans: 'A',
      why: 'Năm 1911, tại Bến Nhà Rồng, người thanh niên Nguyễn Tất Thành ra đi tìm đường cứu nước.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Địa đạo Củ Chi là hệ thống gì dưới lòng đất?',
      opts: o4('Mỏ than', 'Hồ chứa nước', 'Đường tàu điện ngầm', 'Đường hầm dài, có nhiều tầng'), ans: 'D',
      why: 'Địa đạo Củ Chi là hệ thống đường hầm nhiều tầng đào sâu trong lòng đất.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Địa đạo Củ Chi gắn với cuộc kháng chiến nào của dân tộc ta?',
      opts: o4('Chống quân Nguyên - Mông', 'Kháng chiến chống Mĩ', 'Chống quân Thanh', 'Chống quân Minh'), ans: 'B',
      why: 'Địa đạo Củ Chi là căn cứ của quân dân ta trong cuộc kháng chiến chống Mĩ.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Địa đạo Củ Chi thể hiện điều gì của quân dân ta?',
      opts: o4('Sự lười biếng', 'Sự sợ hãi', 'Tinh thần kiên cường, thông minh, sáng tạo', 'Không có ý nghĩa'), ans: 'C',
      why: 'Địa đạo cho thấy tinh thần kiên cường, mưu trí, sáng tạo của quân dân ta trong kháng chiến.' },
    { sec: 'Địa lí', name: 'Câu 9', pts: 1,
      text: 'Con sông lớn chảy qua Thành phố Hồ Chí Minh tên là gì?',
      opts: o4('Sông Hồng', 'Sông Hương', 'Sông Lam', 'Sông Sài Gòn'), ans: 'D',
      why: 'Sông Sài Gòn chảy qua thành phố, thuận lợi cho giao thông và phát triển đô thị.' },
    { sec: 'Địa lí', name: 'Câu 10', pts: 1,
      text: 'Thành phố Hồ Chí Minh được mệnh danh là gì?',
      opts: o4('Thành phố mang tên Bác, đầu tàu kinh tế', 'Thành phố ngàn hoa', 'Thành phố sương mù', 'Thành phố cảng than'), ans: 'A',
      why: 'Đây là thành phố mang tên Bác Hồ và là đầu tàu kinh tế năng động của cả nước.' },
  ],
},

/* ═══════════ ĐỀ 23 — NHÂN VẬT VÀ SỰ KIỆN LỊCH SỬ CÁC VÙNG ═══════════ */
{
  id: 7913, title: 'Đề 23 · Nhân vật và sự kiện lịch sử', time: 20,
  questions: [
    { sec: 'Lịch sử', name: 'Câu 1', pts: 1,
      text: 'Ai là người có công đánh tan quân Nam Hán trên sông Bạch Đằng năm 938?',
      opts: o4('Lê Lợi', 'Ngô Quyền', 'Quang Trung', 'Lý Thái Tổ'), ans: 'B',
      why: 'Năm 938, Ngô Quyền đánh tan quân Nam Hán trên sông Bạch Đằng, mở nền độc lập.' },
    { sec: 'Lịch sử', name: 'Câu 2', pts: 1,
      text: 'Hai Bà Trưng nổi dậy khởi nghĩa chống lại ách đô hộ của quân nào?',
      opts: o4('Nhà Hán (phong kiến phương Bắc)', 'Thực dân Pháp', 'Đế quốc Mĩ', 'Quân Xiêm'), ans: 'A',
      why: 'Hai Bà Trưng khởi nghĩa năm 40 chống ách đô hộ của nhà Hán, giành lại độc lập tạm thời.' },
    { sec: 'Lịch sử', name: 'Câu 3', pts: 1,
      text: 'Vị anh hùng nào ba lần lãnh đạo quân dân đánh thắng quân Nguyên - Mông?',
      opts: o4('Đinh Bộ Lĩnh', 'Mai Hắc Đế', 'Trần Hưng Đạo', 'Lý Bí'), ans: 'C',
      why: 'Trần Hưng Đạo (Trần Quốc Tuấn) lãnh đạo quân dân nhà Trần ba lần đánh thắng quân Nguyên - Mông.' },
    { sec: 'Lịch sử', name: 'Câu 4', pts: 1,
      text: 'Người dẹp loạn 12 sứ quân, lập ra nước Đại Cồ Việt, đóng đô ở Hoa Lư là ai?',
      opts: o4('Lê Lợi', 'Quang Trung', 'Ngô Quyền', 'Đinh Bộ Lĩnh (Đinh Tiên Hoàng)'), ans: 'D',
      why: 'Đinh Bộ Lĩnh dẹp loạn 12 sứ quân, lên ngôi Hoàng đế, đặt tên nước là Đại Cồ Việt, đóng đô ở Hoa Lư.' },
    { sec: 'Lịch sử', name: 'Câu 5', pts: 1,
      text: 'Vua Quang Trung (Nguyễn Huệ) nổi tiếng với chiến thắng nào đầu xuân Kỉ Dậu 1789?',
      opts: o4('Đại phá quân Thanh (Ngọc Hồi – Đống Đa)', 'Chiến thắng Điện Biên Phủ', 'Chiến thắng Bạch Đằng', 'Chiến thắng Chi Lăng'), ans: 'A',
      why: 'Đầu xuân 1789, Quang Trung đại phá 29 vạn quân Thanh trong trận Ngọc Hồi – Đống Đa.' },
    { sec: 'Lịch sử', name: 'Câu 6', pts: 1,
      text: 'Lê Lợi lãnh đạo cuộc khởi nghĩa Lam Sơn chống lại quân xâm lược nào?',
      opts: o4('Quân Thanh', 'Thực dân Pháp', 'Quân Nguyên', 'Quân Minh'), ans: 'D',
      why: 'Lê Lợi lãnh đạo khởi nghĩa Lam Sơn (đầu thế kỉ XV) đánh đuổi quân Minh, lập nên nhà Lê.' },
    { sec: 'Lịch sử', name: 'Câu 7', pts: 1,
      text: 'Ngày 2 tháng 9 năm 1945, tại Quảng trường Ba Đình (Hà Nội) diễn ra sự kiện gì?',
      opts: o4('Chiến thắng Điện Biên Phủ', 'Bác Hồ đọc Tuyên ngôn Độc lập', 'Vua Lý dời đô', 'Khởi nghĩa Hai Bà Trưng'), ans: 'B',
      why: 'Ngày 2-9-1945, Chủ tịch Hồ Chí Minh đọc Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hoà.' },
    { sec: 'Lịch sử', name: 'Câu 8', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ (1954) do vị Đại tướng nào chỉ huy?',
      opts: o4('Trần Hưng Đạo', 'Lê Lợi', 'Võ Nguyên Giáp', 'Ngô Quyền'), ans: 'C',
      why: 'Đại tướng Võ Nguyên Giáp là Tổng chỉ huy chiến dịch Điện Biên Phủ năm 1954.' },
    { sec: 'Lịch sử', name: 'Câu 9', pts: 1,
      text: 'Chiến dịch Hồ Chí Minh (30-4-1975) đã đem lại kết quả gì?',
      opts: o4('Bắt đầu chống Pháp', 'Dời đô ra Thăng Long', 'Lập nước Văn Lang', 'Giải phóng miền Nam, thống nhất đất nước'), ans: 'D',
      why: 'Ngày 30-4-1975, chiến dịch Hồ Chí Minh toàn thắng, giải phóng miền Nam, thống nhất đất nước.' },
    { sec: 'Lịch sử', name: 'Câu 10', pts: 1,
      text: 'Nữ tướng nào cưỡi voi ra trận với câu nói khảng khái "Tôi muốn cưỡi cơn gió mạnh..."?',
      opts: o4('Bà Triệu (Triệu Thị Trinh)', 'Bà Trưng Nhị', 'Nguyên phi Ỷ Lan', 'Công chúa Huyền Trân'), ans: 'A',
      why: 'Bà Triệu (Triệu Thị Trinh) là nữ anh hùng cưỡi voi đánh giặc Ngô ở thế kỉ III.' },
  ],
},

/* ═══════════ ĐỀ 24 — ÔN TẬP CÁC VÙNG MIỀN (1) ═══════════ */
{
  id: 7914, title: 'Đề 24 · Ôn tập các vùng miền (1)', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Dãy núi cao và đồ sộ nhất nước ta là dãy nào?',
      opts: o4('Trường Sơn', 'Hoàng Liên Sơn', 'Bạch Mã', 'Tam Đảo'), ans: 'B',
      why: 'Dãy Hoàng Liên Sơn cao và đồ sộ nhất nước ta, có đỉnh Phan-xi-păng.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Ruộng bậc thang là cách canh tác đặc trưng của vùng nào?',
      opts: o4('Trung du và miền núi Bắc Bộ', 'Đồng bằng Nam Bộ', 'Duyên hải miền Trung', 'Đồng bằng Bắc Bộ'), ans: 'A',
      why: 'Ruộng bậc thang men theo sườn núi là cách canh tác của người dân miền núi Bắc Bộ.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Đền Hùng — nơi thờ các Vua Hùng — nằm ở tỉnh nào?',
      opts: o4('Ninh Bình', 'Thanh Hoá', 'Phú Thọ', 'Quảng Ninh'), ans: 'C',
      why: 'Đền Hùng nằm ở tỉnh Phú Thọ, là nơi thờ các Vua Hùng có công dựng nước.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Đất đỏ ba-dan màu mỡ là đặc trưng của vùng nào?',
      opts: o4('Đồng bằng Bắc Bộ', 'Duyên hải miền Trung', 'Miền núi Bắc Bộ', 'Tây Nguyên'), ans: 'D',
      why: 'Tây Nguyên nổi tiếng với đất đỏ ba-dan, thích hợp trồng cà phê, cao su.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Chợ nổi trên sông là nét văn hoá của vùng nào?',
      opts: o4('Đồng bằng sông Cửu Long', 'Tây Nguyên', 'Miền núi Bắc Bộ', 'Đồng bằng Bắc Bộ'), ans: 'A',
      why: 'Chợ nổi là nét sinh hoạt độc đáo của vùng sông nước đồng bằng sông Cửu Long.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Sông Hương và núi Ngự Bình là biểu tượng của thành phố nào?',
      opts: o4('Đà Nẵng', 'Hà Nội', 'Cần Thơ', 'Huế'), ans: 'D',
      why: 'Sông Hương và núi Ngự Bình là biểu tượng thiên nhiên của thành phố Huế.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Không gian văn hoá Cồng chiêng là di sản của vùng nào?',
      opts: o4('Đồng bằng Bắc Bộ', 'Tây Nguyên', 'Nam Bộ', 'Duyên hải miền Trung'), ans: 'B',
      why: 'Không gian văn hoá Cồng chiêng Tây Nguyên là Di sản văn hoá phi vật thể của nhân loại.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Vùng nào là vựa lúa lớn nhất cả nước?',
      opts: o4('Đồng bằng Bắc Bộ', 'Tây Nguyên', 'Đồng bằng sông Cửu Long', 'Trung du Bắc Bộ'), ans: 'C',
      why: 'Đồng bằng sông Cửu Long là vựa lúa lớn nhất cả nước.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Địa đạo Củ Chi thuộc vùng nào của nước ta?',
      opts: o4('Bắc Bộ', 'Tây Nguyên', 'Miền núi Bắc Bộ', 'Nam Bộ'), ans: 'D',
      why: 'Địa đạo Củ Chi thuộc Thành phố Hồ Chí Minh, ở vùng Đông Nam Bộ.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Vùng nào của nước ta thường xuyên chịu nhiều bão, lũ nhất?',
      opts: o4('Duyên hải miền Trung', 'Tây Nguyên', 'Đồng bằng Bắc Bộ', 'Nam Bộ'), ans: 'A',
      why: 'Duyên hải miền Trung là vùng hứng chịu nhiều bão và lũ lụt nhất.' },
  ],
},

/* ═══════════ ĐỀ 25 — ĐỊA PHƯƠNG EM VÀ HÀNH CHÍNH ═══════════ */
{
  id: 7915, title: 'Đề 25 · Địa phương em và hành chính', time: 20,
  questions: [
    { sec: 'Địa phương', name: 'Câu 1', pts: 1,
      text: 'Nước ta được chia thành nhiều đơn vị hành chính cấp tỉnh gồm những gì?',
      opts: o4('Chỉ có các huyện', 'Các tỉnh và thành phố trực thuộc trung ương', 'Chỉ có các xã', 'Chỉ có các làng'), ans: 'B',
      why: 'Cấp tỉnh gồm các tỉnh và thành phố trực thuộc trung ương.' },
    { sec: 'Địa phương', name: 'Câu 2', pts: 1,
      text: 'Cơ quan quản lí hành chính ở xã, phường thường gọi là gì?',
      opts: o4('Uỷ ban nhân dân xã (phường)', 'Nhà máy', 'Bến xe', 'Chợ'), ans: 'A',
      why: 'Uỷ ban nhân dân xã (phường) là cơ quan quản lí hành chính ở địa phương cấp cơ sở.' },
    { sec: 'Địa phương', name: 'Câu 3', pts: 1,
      text: 'Muốn biết quê mình có những di tích, danh lam nào, em nên làm gì?',
      opts: o4('Chỉ ngồi đoán', 'Không cần biết', 'Tìm hiểu qua sách báo, người lớn, tham quan thực tế', 'Chờ người khác kể'), ans: 'C',
      why: 'Tìm hiểu qua sách báo, hỏi người lớn và tham quan thực tế giúp biết về di tích, danh lam quê mình.' },
    { sec: 'Địa phương', name: 'Câu 4', pts: 1,
      text: 'Nghề truyền thống của một địa phương thường gắn với điều gì?',
      opts: o4('Ý thích nhất thời', 'Màu sắc quần áo', 'Tên của người dân', 'Điều kiện tự nhiên và tập quán lâu đời'), ans: 'D',
      why: 'Nghề truyền thống hình thành dựa trên điều kiện tự nhiên và tập quán lâu đời của người dân.' },
    { sec: 'Địa phương', name: 'Câu 5', pts: 1,
      text: 'Việc làm nào góp phần bảo vệ môi trường ở địa phương?',
      opts: o4('Trồng cây, dọn vệ sinh, bỏ rác đúng nơi', 'Vứt rác xuống sông', 'Đốt rác bừa bãi', 'Chặt phá cây xanh'), ans: 'A',
      why: 'Trồng cây, giữ vệ sinh và bỏ rác đúng nơi quy định giúp bảo vệ môi trường địa phương.' },
    { sec: 'Địa phương', name: 'Câu 6', pts: 1,
      text: 'Quần đảo Hoàng Sa và Trường Sa là bộ phận của lãnh thổ nước nào?',
      opts: o4('Trung Quốc', 'Thái Lan', 'Phi-líp-pin', 'Việt Nam'), ans: 'D',
      why: 'Hoàng Sa và Trường Sa là hai quần đảo thuộc chủ quyền của Việt Nam.' },
    { sec: 'Địa phương', name: 'Câu 7', pts: 1,
      text: 'Việt Nam giáp với những nước nào trên đất liền?',
      opts: o4('Nhật Bản, Hàn Quốc', 'Trung Quốc, Lào, Cam-pu-chia', 'Ấn Độ, Nê-pan', 'Nga, Mông Cổ'), ans: 'B',
      why: 'Trên đất liền, nước ta giáp Trung Quốc ở phía bắc, giáp Lào và Cam-pu-chia ở phía tây.' },
    { sec: 'Địa phương', name: 'Câu 8', pts: 1,
      text: 'Lá cờ Tổ quốc Việt Nam có đặc điểm gì?',
      opts: o4('Nền xanh, ngôi sao trắng', 'Nền vàng, ngôi sao đỏ', 'Nền đỏ, ngôi sao vàng năm cánh ở giữa', 'Ba sọc ngang'), ans: 'C',
      why: 'Quốc kì Việt Nam có nền đỏ và ngôi sao vàng năm cánh ở chính giữa.' },
    { sec: 'Địa phương', name: 'Câu 9', pts: 1,
      text: 'Vì sao mỗi người cần tự hào và yêu quý quê hương mình?',
      opts: o4('Vì để khoe khoang', 'Vì bắt buộc phải nói', 'Không cần yêu quê hương', 'Vì quê hương là nơi gắn bó, nuôi dưỡng ta khôn lớn'), ans: 'D',
      why: 'Quê hương là nơi ta sinh ra, gắn bó và trưởng thành nên cần yêu quý, tự hào.' },
    { sec: 'Địa phương', name: 'Câu 10', pts: 1,
      text: 'Khi giới thiệu về quê hương cho bạn bè, em nên nói về điều gì?',
      opts: o4('Cảnh đẹp, món ăn, nghề truyền thống và con người quê mình', 'Chỉ toàn điều xấu', 'Bịa ra cho hay', 'Không nói gì cả'), ans: 'A',
      why: 'Nên giới thiệu cảnh đẹp, đặc sản, nghề truyền thống và con người quê hương một cách chân thực, tự hào.' },
  ],
},

/* ═══════════ ĐỀ 26 — BẮC BỘ TỔNG HỢP ═══════════ */
{
  id: 7916, title: 'Đề 26 · Bắc Bộ tổng hợp', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Đền Hùng thờ các Vua Hùng — những người có công gì?',
      opts: o4('Có công đắp đê', 'Có công dựng nước Văn Lang', 'Có công làm gốm', 'Có công dệt lụa'), ans: 'B',
      why: 'Các Vua Hùng có công dựng nên nước Văn Lang — nhà nước đầu tiên của người Việt.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Giỗ Tổ Hùng Vương là ngày nào âm lịch?',
      opts: o4('Mùng 10 tháng 3', 'Mùng 3 tháng 3', 'Rằm tháng 7', 'Mùng 5 tháng 5'), ans: 'A',
      why: 'Giỗ Tổ Hùng Vương là ngày mùng 10 tháng 3 âm lịch hằng năm.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Kinh đô nước Âu Lạc thời An Dương Vương ở đâu?',
      opts: o4('Hoa Lư', 'Phú Xuân', 'Cổ Loa (Đông Anh, Hà Nội)', 'Gia Định'), ans: 'C',
      why: 'An Dương Vương lập nước Âu Lạc, đóng đô ở Cổ Loa (nay thuộc Đông Anh, Hà Nội).' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Vua nào dời đô ra Thăng Long năm 1010?',
      opts: o4('Lê Lợi', 'Quang Trung', 'Ngô Quyền', 'Lý Thái Tổ'), ans: 'D',
      why: 'Năm 1010, vua Lý Thái Tổ dời đô từ Hoa Lư ra Thăng Long.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Đồng bằng Bắc Bộ do những sông nào bồi đắp?',
      opts: o4('Sông Hồng và sông Thái Bình', 'Sông Cửu Long', 'Sông Đồng Nai', 'Sông Ba'), ans: 'A',
      why: 'Sông Hồng và sông Thái Bình bồi đắp phù sa tạo nên đồng bằng Bắc Bộ.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Làng gốm Bát Tràng thuộc thành phố nào?',
      opts: o4('Hải Phòng', 'Bắc Ninh', 'Nam Định', 'Hà Nội'), ans: 'D',
      why: 'Làng gốm Bát Tràng thuộc thành phố Hà Nội.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Chiến thắng Điện Biên Phủ diễn ra năm nào, ở vùng nào?',
      opts: o4('Năm 1945, Nam Bộ', 'Năm 1954, miền núi Tây Bắc', 'Năm 1975, Tây Nguyên', 'Năm 1930, miền Trung'), ans: 'B',
      why: 'Chiến thắng Điện Biên Phủ năm 1954, ở vùng núi Tây Bắc (Bắc Bộ).' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Vì sao đồng bằng Bắc Bộ phải đắp đê?',
      opts: o4('Để trồng chè', 'Để làm sân bay', 'Để ngăn lũ, bảo vệ mùa màng và làng xóm', 'Để nuôi voi'), ans: 'C',
      why: 'Hệ thống đê ngăn nước sông dâng cao gây lũ, bảo vệ đồng ruộng và làng xóm.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Dân ca quan họ là di sản văn hoá gắn với tỉnh nào ở Bắc Bộ?',
      opts: o4('Lào Cai', 'Điện Biên', 'Quảng Ninh', 'Bắc Ninh'), ans: 'D',
      why: 'Dân ca quan họ Bắc Ninh là Di sản văn hoá phi vật thể của nhân loại.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Cây công nghiệp nào được trồng nhiều ở trung du Bắc Bộ?',
      opts: o4('Cây chè', 'Cây cà phê', 'Cây cao su', 'Cây dừa'), ans: 'A',
      why: 'Vùng trung du Bắc Bộ (Thái Nguyên, Phú Thọ...) trồng nhiều chè.' },
  ],
},

/* ═══════════ ĐỀ 27 — MIỀN TRUNG TỔNG HỢP ═══════════ */
{
  id: 7917, title: 'Đề 27 · Miền Trung tổng hợp', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Đồng bằng duyên hải miền Trung có đặc điểm gì?',
      opts: o4('Rộng lớn, bằng phẳng', 'Nhỏ hẹp, bị chia cắt', 'Là cao nguyên', 'Toàn đầm lầy'), ans: 'B',
      why: 'Do núi ăn ra sát biển nên đồng bằng miền Trung nhỏ hẹp, bị chia cắt.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Dãy núi lớn chạy dọc phía tây miền Trung là dãy nào?',
      opts: o4('Trường Sơn', 'Hoàng Liên Sơn', 'Tam Đảo', 'Con Voi'), ans: 'A',
      why: 'Dãy Trường Sơn chạy dài ở phía tây miền Trung.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Cố đô Huế là kinh đô của triều đại nào?',
      opts: o4('Triều Lý', 'Triều Trần', 'Triều Nguyễn', 'Triều Lê'), ans: 'C',
      why: 'Huế là kinh đô của triều Nguyễn — triều đại phong kiến cuối cùng của nước ta.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Phố cổ Hội An thuộc tỉnh nào?',
      opts: o4('Khánh Hoà', 'Bình Định', 'Quảng Ngãi', 'Quảng Nam'), ans: 'D',
      why: 'Phố cổ Hội An nằm ở tỉnh Quảng Nam, bên sông Thu Bồn.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Vì sao nghề làm muối phát triển ở ven biển miền Trung?',
      opts: o4('Vì nhiều nắng và nước biển mặn', 'Vì hay mưa', 'Vì có đất ba-dan', 'Vì có tuyết'), ans: 'A',
      why: 'Nắng nhiều làm nước biển bốc hơi nhanh, để lại muối — thuận lợi cho nghề làm muối.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Thành phố biển lớn ở miền Trung có cầu Rồng là thành phố nào?',
      opts: o4('Hải Phòng', 'Vũng Tàu', 'Cần Thơ', 'Đà Nẵng'), ans: 'D',
      why: 'Đà Nẵng là thành phố biển lớn ở miền Trung, nổi tiếng với cầu Rồng.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Miền Trung thường chịu thiên tai nào vào mùa mưa bão?',
      opts: o4('Tuyết dày', 'Bão và lũ lụt', 'Động đất hằng ngày', 'Núi lửa'), ans: 'B',
      why: 'Miền Trung là vùng thường xuyên chịu bão và lũ lụt.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là gì?',
      opts: o4('Kì quan thiên nhiên', 'Khu bảo tồn biển', 'Di sản văn hoá thế giới', 'Vườn quốc gia'), ans: 'C',
      why: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là Di sản văn hoá thế giới năm 1993.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Con sông chảy qua thành phố Huế tên là gì?',
      opts: o4('Sông Hàn', 'Sông Thu Bồn', 'Sông Cả', 'Sông Hương'), ans: 'D',
      why: 'Sông Hương chảy qua thành phố Huế, tạo nên cảnh đẹp nổi tiếng.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Biểu tượng của phố cổ Hội An là công trình nào?',
      opts: o4('Chùa Cầu', 'Tháp Chàm', 'Cầu Tràng Tiền', 'Tháp Rùa'), ans: 'A',
      why: 'Chùa Cầu (cầu Nhật Bản) là công trình cổ, biểu tượng của phố cổ Hội An.' },
  ],
},

/* ═══════════ ĐỀ 28 — TÂY NGUYÊN VÀ NAM BỘ TỔNG HỢP ═══════════ */
{
  id: 7918, title: 'Đề 28 · Tây Nguyên và Nam Bộ tổng hợp', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Địa hình chủ yếu của Tây Nguyên là gì?',
      opts: o4('Đồng bằng ven biển', 'Các cao nguyên xếp tầng', 'Núi đá vôi', 'Đầm lầy'), ans: 'B',
      why: 'Tây Nguyên gồm các cao nguyên rộng lớn, xếp tầng, có độ cao khác nhau.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Cây công nghiệp nổi tiếng nhất của Tây Nguyên là gì?',
      opts: o4('Cà phê', 'Lúa nước', 'Chè', 'Vải thiều'), ans: 'A',
      why: 'Tây Nguyên là vùng trồng cà phê lớn nhất cả nước.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Nhà rông là kiểu nhà chung của các dân tộc vùng nào?',
      opts: o4('Đồng bằng Bắc Bộ', 'Nam Bộ', 'Tây Nguyên', 'Miền Trung ven biển'), ans: 'C',
      why: 'Nhà rông là ngôi nhà chung, sinh hoạt cộng đồng của buôn làng Tây Nguyên.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Thành phố ngàn hoa, khí hậu mát mẻ ở Tây Nguyên là thành phố nào?',
      opts: o4('Buôn Ma Thuột', 'Pleiku', 'Kon Tum', 'Đà Lạt'), ans: 'D',
      why: 'Đà Lạt (Lâm Đồng) khí hậu mát mẻ quanh năm, nổi tiếng là thành phố ngàn hoa.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Đồng bằng lớn nhất nước ta là đồng bằng nào?',
      opts: o4('Đồng bằng sông Cửu Long', 'Đồng bằng Bắc Bộ', 'Đồng bằng Thanh Hoá', 'Đồng bằng Tuy Hoà'), ans: 'A',
      why: 'Đồng bằng sông Cửu Long (Nam Bộ) là đồng bằng lớn nhất cả nước.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Sông Cửu Long là tên gọi ở nước ta của con sông lớn nào?',
      opts: o4('Sông Hồng', 'Sông Đồng Nai', 'Sông Sê San', 'Sông Mê Kông'), ans: 'D',
      why: 'Sông Mê Kông chảy vào nước ta được gọi là sông Cửu Long.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Thành phố lớn nhất, đông dân nhất nước ta là thành phố nào?',
      opts: o4('Hà Nội', 'Thành phố Hồ Chí Minh', 'Cần Thơ', 'Đà Nẵng'), ans: 'B',
      why: 'Thành phố Hồ Chí Minh là thành phố lớn nhất và đông dân nhất cả nước.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Địa đạo Củ Chi gắn với cuộc kháng chiến nào?',
      opts: o4('Chống Pháp', 'Chống quân Thanh', 'Chống Mĩ', 'Chống quân Nguyên'), ans: 'C',
      why: 'Địa đạo Củ Chi là di tích của cuộc kháng chiến chống Mĩ.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Đồng bằng sông Cửu Long vào mùa khô gặp khó khăn gì?',
      opts: o4('Rét đậm', 'Bão tuyết', 'Sương muối', 'Xâm nhập mặn'), ans: 'D',
      why: 'Mùa khô, nước biển lấn sâu vào gây xâm nhập mặn, thiếu nước ngọt.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Cồng chiêng Tây Nguyên và chợ nổi Nam Bộ đều là gì của đất nước?',
      opts: o4('Nét văn hoá đặc sắc cần giữ gìn', 'Điều nên xoá bỏ', 'Chuyện không quan trọng', 'Sản phẩm công nghiệp'), ans: 'A',
      why: 'Cả hai đều là nét văn hoá đặc sắc của các vùng miền, cần được trân trọng, giữ gìn.' },
  ],
},

/* ═══════════ ĐỀ 29 — DI SẢN VĂN HOÁ VIỆT NAM ═══════════ */
{
  id: 7919, title: 'Đề 29 · Di sản văn hoá Việt Nam', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Vịnh Hạ Long (Quảng Ninh) được UNESCO công nhận là gì?',
      opts: o4('Di sản văn hoá phi vật thể', 'Di sản thiên nhiên thế giới', 'Khu công nghiệp', 'Cảng biển quốc tế'), ans: 'B',
      why: 'Vịnh Hạ Long được UNESCO công nhận là Di sản thiên nhiên thế giới.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Không gian văn hoá Cồng chiêng thuộc vùng nào?',
      opts: o4('Tây Nguyên', 'Bắc Bộ', 'Nam Bộ', 'Miền Trung'), ans: 'A',
      why: 'Không gian văn hoá Cồng chiêng Tây Nguyên là Di sản văn hoá phi vật thể của nhân loại.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Nhã nhạc cung đình là di sản văn hoá gắn với vùng đất nào?',
      opts: o4('Hà Nội', 'Hội An', 'Huế', 'Cần Thơ'), ans: 'C',
      why: 'Nhã nhạc cung đình Huế là Di sản văn hoá phi vật thể của nhân loại.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Dân ca quan họ là di sản của tỉnh nào?',
      opts: o4('Nghệ An', 'Thừa Thiên Huế', 'Lâm Đồng', 'Bắc Ninh'), ans: 'D',
      why: 'Dân ca quan họ Bắc Ninh được UNESCO ghi danh là Di sản văn hoá phi vật thể.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Phố cổ Hội An và Cố đô Huế cùng là loại di sản nào?',
      opts: o4('Di sản văn hoá thế giới', 'Di sản thiên nhiên', 'Kì quan mới', 'Vườn quốc gia'), ans: 'A',
      why: 'Cả hai đều được UNESCO công nhận là Di sản văn hoá thế giới.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Khu di tích Hoàng thành Thăng Long nằm ở thành phố nào?',
      opts: o4('Huế', 'Đà Nẵng', 'Hải Phòng', 'Hà Nội'), ans: 'D',
      why: 'Hoàng thành Thăng Long ở Hà Nội, là Di sản văn hoá thế giới.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Cao nguyên đá Đồng Văn (Hà Giang) được công nhận là gì?',
      opts: o4('Cảng biển', 'Công viên địa chất toàn cầu', 'Khu công nghiệp', 'Sân bay'), ans: 'B',
      why: 'Cao nguyên đá Đồng Văn được UNESCO công nhận là công viên địa chất toàn cầu.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Di sản văn hoá phi vật thể là những giá trị như thế nào?',
      opts: o4('Chỉ là công trình xây dựng', 'Chỉ là khoáng sản', 'Không cầm nắm được như âm nhạc, lễ hội, tiếng nói', 'Chỉ là máy móc'), ans: 'C',
      why: 'Di sản phi vật thể là những giá trị tinh thần như âm nhạc, lễ hội, tiếng nói, phong tục...' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Vì sao chúng ta cần bảo vệ các di sản văn hoá?',
      opts: o4('Vì để bán lấy tiền', 'Vì đã cũ nên bỏ đi', 'Vì không có ích gì', 'Vì là tài sản quý của dân tộc và nhân loại'), ans: 'D',
      why: 'Di sản văn hoá là tài sản quý của dân tộc và nhân loại, cần giữ gìn cho đời sau.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Là học sinh, em có thể làm gì để góp phần bảo vệ di sản?',
      opts: o4('Tìm hiểu, giữ gìn, tuyên truyền và không phá hoại', 'Viết vẽ bậy lên di tích', 'Xả rác ở khu di sản', 'Lấy hiện vật về nhà'), ans: 'A',
      why: 'Học sinh nên tìm hiểu, giữ gìn, giới thiệu và không phá hoại các di sản văn hoá.' },
  ],
},

/* ═══════════ ĐỀ 30 — ÔN TẬP CUỐI: TỪ BẮC VÀO NAM ═══════════ */
{
  id: 7920, title: 'Đề 30 · Ôn tập cuối — từ Bắc vào Nam', time: 20,
  questions: [
    { sec: 'Ôn tập', name: 'Câu 1', pts: 1,
      text: 'Thứ tự các vùng từ bắc vào nam nào sau đây là đúng?',
      opts: o4('Nam Bộ – Bắc Bộ – miền Trung', 'Bắc Bộ – miền Trung – Tây Nguyên/Nam Bộ', 'Tây Nguyên – Bắc Bộ – Nam Bộ', 'Miền Trung – Nam Bộ – Bắc Bộ'), ans: 'B',
      why: 'Đi từ bắc vào nam: Bắc Bộ, đến duyên hải miền Trung, rồi Tây Nguyên và Nam Bộ.' },
    { sec: 'Ôn tập', name: 'Câu 2', pts: 1,
      text: 'Thủ đô của nước ta là thành phố nào?',
      opts: o4('Hà Nội', 'Thành phố Hồ Chí Minh', 'Huế', 'Đà Nẵng'), ans: 'A',
      why: 'Hà Nội là thủ đô của nước Cộng hoà xã hội chủ nghĩa Việt Nam.' },
    { sec: 'Ôn tập', name: 'Câu 3', pts: 1,
      text: 'Đỉnh núi cao nhất Việt Nam là đỉnh nào?',
      opts: o4('Bà Đen', 'Ngự Bình', 'Phan-xi-păng', 'Yên Tử'), ans: 'C',
      why: 'Phan-xi-păng (Hoàng Liên Sơn) cao khoảng 3143 m, cao nhất nước ta.' },
    { sec: 'Ôn tập', name: 'Câu 4', pts: 1,
      text: 'Hai đồng bằng lớn của nước ta là gì?',
      opts: o4('Đồng bằng Huế và đồng bằng Đà Nẵng', 'Đồng bằng Tây Nguyên và Bắc Bộ', 'Đồng bằng Sa Pa và Đà Lạt', 'Đồng bằng Bắc Bộ và đồng bằng sông Cửu Long'), ans: 'D',
      why: 'Hai đồng bằng lớn nhất là đồng bằng Bắc Bộ và đồng bằng sông Cửu Long.' },
    { sec: 'Ôn tập', name: 'Câu 5', pts: 1,
      text: 'Vùng nào nổi tiếng với đất đỏ ba-dan và cây cà phê?',
      opts: o4('Tây Nguyên', 'Đồng bằng Bắc Bộ', 'Duyên hải miền Trung', 'Miền núi Bắc Bộ'), ans: 'A',
      why: 'Tây Nguyên có đất đỏ ba-dan màu mỡ, là vùng trồng cà phê lớn nhất nước.' },
    { sec: 'Ôn tập', name: 'Câu 6', pts: 1,
      text: 'Vua Lý Thái Tổ dời đô ra Thăng Long, còn Bác Hồ đọc Tuyên ngôn Độc lập ở đâu?',
      opts: o4('Bến Nhà Rồng', 'Cố đô Huế', 'Hội An', 'Quảng trường Ba Đình, Hà Nội'), ans: 'D',
      why: 'Ngày 2-9-1945, Bác Hồ đọc Tuyên ngôn Độc lập tại Quảng trường Ba Đình, Hà Nội.' },
    { sec: 'Ôn tập', name: 'Câu 7', pts: 1,
      text: 'Chiến thắng nào (1954) kết thúc cuộc kháng chiến chống Pháp?',
      opts: o4('Bạch Đằng', 'Điện Biên Phủ', 'Chi Lăng', 'Ngọc Hồi – Đống Đa'), ans: 'B',
      why: 'Chiến thắng Điện Biên Phủ năm 1954 kết thúc thắng lợi cuộc kháng chiến chống thực dân Pháp.' },
    { sec: 'Ôn tập', name: 'Câu 8', pts: 1,
      text: 'Ngày 30-4-1975 đánh dấu sự kiện gì?',
      opts: o4('Bắt đầu kháng chiến chống Pháp', 'Vua Lý dời đô', 'Giải phóng miền Nam, thống nhất đất nước', 'Khởi nghĩa Lam Sơn'), ans: 'C',
      why: 'Ngày 30-4-1975, chiến dịch Hồ Chí Minh toàn thắng, giải phóng miền Nam, thống nhất đất nước.' },
    { sec: 'Ôn tập', name: 'Câu 9', pts: 1,
      text: 'Vùng nào là vựa lúa lớn nhất, có nhiều chợ nổi?',
      opts: o4('Đồng bằng Bắc Bộ', 'Tây Nguyên', 'Miền núi Bắc Bộ', 'Đồng bằng sông Cửu Long'), ans: 'D',
      why: 'Đồng bằng sông Cửu Long là vựa lúa lớn nhất và nổi tiếng với các chợ nổi.' },
    { sec: 'Ôn tập', name: 'Câu 10', pts: 1,
      text: 'Điều gì thể hiện tình yêu và trách nhiệm với đất nước, các vùng miền?',
      opts: o4('Học tốt, giữ gìn di sản, bảo vệ môi trường và tự hào về quê hương', 'Phá hoại di tích', 'Xả rác nơi danh thắng', 'Chê bai đất nước'), ans: 'A',
      why: 'Chăm học, giữ gìn di sản, bảo vệ môi trường và tự hào về quê hương thể hiện tình yêu đất nước.' },
  ],
},

];

SUBJECTS.push({
  id: 'lsdl4', name: 'Lịch sử & Địa lí', short: 'LS-ĐL 4', icon: '🗺️', grade: 4,
  exams: LSDL4_EXAMS, ready: true,
  heroTitle: 'Lịch sử và Địa lí lớp 4 — địa phương em và các vùng miền: Bắc Bộ, miền Trung, Tây Nguyên, Nam Bộ',
  heroMeta: '📚 30 đề &nbsp;•&nbsp; 300 câu &nbsp;•&nbsp; ⏱ 20 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
