// ASMO Toán quốc tế — Lớp 2: 4 đề thi thật (2014, 2015, 2017, 2018), mỗi đề 20 câu.
// Nguồn: đề gốc ASMO (Asian Science & Maths Olympiad) Division P Year 2, dịch sang tiếng Việt.
// Mỗi câu 5 lựa chọn A–E như đề gốc, 0.5 điểm/câu (thang 10). Hình vẽ lại bằng SVG trong assets/asmo/.

const AS = 'assets/asmo/';
const o5 = (a, b, c, d, e) => [{ k: 'A', t: a }, { k: 'B', t: b }, { k: 'C', t: c }, { k: 'D', t: d }, { k: 'E', t: e }];

const ASMO_EXAMS = [
/* ================= ASMO 2014 ================= */
{
  id: 201, title: 'ASMO 2014', time: 45,
  questions: [
    { sec: 'Tư duy đại số', name: 'Câu 1', pts: 0.5,
      text: 'Cho biết:<br><b>🌙 + ☀️ = 12</b><br><b>🌙 + 🌙 + ☀️ + ☀️ + ☀️ = 31</b><br>Hỏi 🌙 và ☀️ lần lượt là số nào?',
      opts: o5('5 và 6', '4 và 8', '6 và 6', '9 và 3', 'Không có đáp án nào đúng'), ans: 'E',
      why: 'Vì 🌙 + ☀️ = 12 nên 2🌙 + 2☀️ = 24. So với 2🌙 + 3☀️ = 31, thừa ra đúng 1 ☀️ = 31 − 24 = 7. Suy ra 🌙 = 12 − 7 = 5. Cặp (5, 7) không có trong các lựa chọn nên chọn E.' },
    { sec: 'Tính ngược', name: 'Câu 2', pts: 0.5,
      text: 'Một số cộng 2, rồi trừ 3, rồi nhân 4, rồi chia 5 thì được kết quả 12. Tìm số đó.',
      opts: o5('19', '18', '17', '16', 'Không có đáp án nào đúng'), ans: 'D',
      why: 'Tính ngược từ cuối: 12 × 5 = 60; 60 ÷ 4 = 15; 15 + 3 = 18; 18 − 2 = 16.' },
    { sec: 'Toán đố', name: 'Câu 3', pts: 0.5,
      text: 'Aaron hái một nửa số xoài trên cây. Trước khi về nhà, bạn hái thêm 2 quả nữa. Khi quay lại, bạn hái nốt 7 quả còn lại trên cây. Hỏi Aaron đã hái tất cả bao nhiêu quả xoài?',
      opts: o5('20', '19', '18', '17', 'Không có đáp án nào đúng'), ans: 'C',
      why: 'Sau khi hái nửa cây, phần còn lại cũng là nửa cây và bằng 2 + 7 = 9 quả. Vậy cả cây có 9 × 2 = 18 quả, và Aaron đã hái hết cả 18 quả.' },
    { sec: 'Tư duy vị trí', name: 'Câu 4', pts: 0.5,
      text: 'Jason tham gia đội diễu hành. Trong đội hình, bạn đứng thứ 7 tính từ trái, thứ 2 tính từ phải; thứ 3 tính từ trước và thứ 4 tính từ sau. Hỏi đội của Jason có bao nhiêu người?',
      opts: o5('10', '34', '36', '42', 'Không có đáp án nào đúng'), ans: 'E',
      why: 'Mỗi hàng ngang có 7 + 2 − 1 = 8 người. Số hàng dọc là 3 + 4 − 1 = 6 hàng. Cả đội có 8 × 6 = 48 người — không có trong các lựa chọn nên chọn E.' },
    { sec: 'Hình khối', name: 'Câu 5', pts: 0.5,
      text: 'Một khối hộp lớn được sơn đỏ toàn bộ mặt ngoài, rồi cắt thành 18 khối nhỏ bằng nhau như hình. Hỏi có bao nhiêu khối nhỏ được sơn đúng 2 mặt?', img: AS + 'a14q5.svg',
      opts: o5('3', '5', '7', '8', '9'), ans: 'D',
      why: 'Khối hộp gồm 2 tầng, mỗi tầng 3×3 = 9 khối. Ở mỗi tầng: 4 khối góc được sơn 3 mặt (2 mặt bên + mặt trên/dưới), 4 khối ở giữa cạnh sơn đúng 2 mặt (1 mặt bên + mặt trên/dưới), khối chính giữa sơn 1 mặt. Vậy có 4 × 2 = 8 khối sơn đúng 2 mặt.' },
    { sec: 'Tổng – hiệu', name: 'Câu 6', pts: 0.5,
      text: 'Alvin và John nặng tổng cộng 150 kg. Alvin nặng hơn John 8 kg. Hỏi cân nặng của Alvin và John lần lượt là bao nhiêu (kg)?',
      opts: o5('80, 70', '79, 71', '78, 72', '77, 73', 'Không có đáp án nào đúng'), ans: 'B',
      why: 'Alvin nặng (150 + 8) ÷ 2 = 79 kg, John nặng 150 − 79 = 71 kg.' },
    { sec: 'Quy luật số', name: 'Câu 7', pts: 0.5,
      text: 'Cho dãy các nhóm số: <b>12345, 23451, 34512, 45123, …</b><br>Hỏi nhóm thứ 10 của dãy là nhóm nào?',
      opts: o5('34512', '45123', '51234', '23451', '12345'), ans: 'C',
      why: 'Mỗi lần, chữ số đầu chuyển xuống cuối: 12345 → 23451 → 34512 → 45123 → 51234 → 12345 → … Chu kỳ gồm 5 nhóm. Nhóm thứ 10 trùng nhóm thứ 5, là 51234.' },
    { sec: 'Tuổi', name: 'Câu 8', pts: 0.5,
      text: 'Alvin 10 tuổi, bố của Alvin 40 tuổi. Hỏi khi Alvin bao nhiêu tuổi thì tuổi bố gấp đúng 2 lần tuổi Alvin?',
      opts: o5('20', '25', '30', '35', '40'), ans: 'C',
      why: 'Bố luôn hơn Alvin 40 − 10 = 30 tuổi. Khi tuổi bố gấp 2 lần tuổi Alvin thì phần hơn 30 tuổi đúng bằng tuổi Alvin. Vậy Alvin 30 tuổi (khi đó bố 60 tuổi).' },
    { sec: 'Logic', name: 'Câu 9', pts: 0.5,
      text: 'Một đề thi có 30 câu. Mỗi câu đúng được 2 điểm, mỗi câu sai bị trừ 1 điểm, câu bỏ trống 0 điểm. Alvin làm đúng 20 câu, sai 6 câu, bỏ 4 câu. John làm đúng 21 câu và được số điểm bằng Alvin. Hỏi John bỏ trống mấy câu?',
      opts: o5('0', '1', '8', '9', 'Không có đáp án nào đúng'), ans: 'B',
      why: 'Alvin được 20 × 2 − 6 = 34 điểm. John đúng 21 câu được 42 điểm, muốn còn 34 điểm thì phải sai 8 câu (bị trừ 8). Số câu bỏ trống của John: 30 − 21 − 8 = 1 câu.' },
    { sec: 'Tư duy đại số', name: 'Câu 10', pts: 0.5,
      text: 'Cho biết:<br><b>⬜ ⬜ ⬜ ⬜ ⬜ ⬜ + ⭐ ⭐ ⭐ ⭐ = 50</b><br><b>⬜ + ⭐ = 11</b><br>Hỏi ⬜ có giá trị bằng bao nhiêu?',
      opts: o5('3', '4', '5', '6', '8'), ans: 'A',
      why: 'Tách 6⬜ + 4⭐ thành 4 cặp (⬜ + ⭐) và 2⬜: 4 × 11 = 44, còn lại 2⬜ = 50 − 44 = 6. Vậy ⬜ = 3.' },
    { sec: 'Toán đố', name: 'Câu 11', pts: 0.5,
      text: 'Một chiếc thước dài giá 7 nghìn đồng, một hộp bút giá 11 nghìn đồng. Cô giáo mua thước và hộp bút hết đúng 101 nghìn đồng. Hỏi cô đã mua bao nhiêu thước và bao nhiêu hộp bút?',
      opts: o5('4 thước, 7 hộp bút', '4 thước, 6 hộp bút', '5 thước, 7 hộp bút', '5 thước, 6 hộp bút', 'Không có đáp án nào đúng'), ans: 'D',
      why: 'Thử: 5 × 7 + 6 × 11 = 35 + 66 = 101 ✓. Vậy cô mua 5 thước và 6 hộp bút.' },
    { sec: 'Ma phương', name: 'Câu 12', pts: 0.5,
      text: 'Ở mỗi bảng dưới đây, hãy dùng lại 3 số đã cho (mỗi số dùng đúng 3 lần trong bảng của nó) điền vào các ô trống sao cho mỗi hàng, mỗi cột và mỗi đường chéo đều có tổng bằng nhau. Tìm <b>tích của 2 số ở 2 ô tô đậm (dấu ?)</b>.'
        + '<table class="cal" style="max-width:190px"><tr><td></td><td></td><td>8</td></tr><tr><td></td><td>6</td><td></td></tr><tr><td>4</td><td></td><td class="q">?</td></tr></table>'
        + '<table class="cal" style="max-width:190px"><tr><td>3</td><td>7</td><td></td></tr><tr><td></td><td>5</td><td></td></tr><tr><td class="q">?</td><td></td><td></td></tr></table>',
      opts: o5('20', '30', '40', '56', 'Không có đáp án nào đúng'), ans: 'B',
      why: 'Bảng 1 dùng các số 4, 6, 8, tổng mỗi hàng là 4 + 6 + 8 = 18: mỗi hàng, cột đều gồm đủ ba số 4, 6, 8 → ô ? ở góc dưới phải là 6. Bảng 2 dùng các số 3, 5, 7, tổng 15 → ô ? ở góc dưới trái là 5. Tích: 6 × 5 = 30.' },
    { sec: 'Tư duy', name: 'Câu 13', pts: 0.5,
      text: 'Trong vườn hồng, ngày thứ nhất nở 1 bông, ngày thứ hai nở 2 bông, ngày thứ ba nở 4 bông… (mỗi ngày số hoa phủ vườn gấp đôi ngày trước). Đến ngày thứ 30 thì hoa phủ kín cả vườn. Hỏi đến ngày thứ mấy hoa phủ kín <b>một nửa</b> vườn?',
      opts: o5('15', '18', '25', '28', '29'), ans: 'E',
      why: 'Mỗi ngày diện tích phủ hoa gấp đôi ngày trước. Vậy ngay trước ngày phủ kín cả vườn, hoa phủ đúng một nửa vườn: đó là ngày thứ 29.' },
    { sec: 'Tư duy', name: 'Câu 14', pts: 0.5,
      text: 'Cứ 3 vỏ chai nước trái cây đổi được 1 chai mới. Alvin và bạn mua 5 chai, uống xong lại lấy vỏ đi đổi tiếp. Hỏi cả nhóm uống được tối đa bao nhiêu chai nước?',
      opts: o5('5', '6', '7', '8', '9'), ans: 'C',
      why: 'Uống 5 chai → có 5 vỏ. Đổi 3 vỏ lấy 1 chai (còn 2 vỏ), uống xong có 3 vỏ. Đổi tiếp lấy 1 chai, uống xong còn 1 vỏ — không đổi được nữa. Tổng cộng: 5 + 1 + 1 = 7 chai.' },
    { sec: 'Đếm nhóm số', name: 'Câu 15', pts: 0.5,
      text: 'Có bao nhiêu nhóm gồm 3 số tự nhiên <b>khác nhau</b> có tổng bằng 10? (Ví dụ: 2 + 3 + 5 = 10)',
      opts: o5('5', '6', '7', '8', '9'), ans: 'D',
      why: 'Kể cả số 0: (0,1,9), (0,2,8), (0,3,7), (0,4,6), (1,2,7), (1,3,6), (1,4,5), (2,3,5) — tất cả 8 nhóm.' },
    { sec: 'Toán đố', name: 'Câu 16', pts: 0.5,
      text: 'Christy mang 19 nghìn đồng đi mua đồ, vừa đủ để mua 6 bút chì và 11 cục tẩy. Biết 3 bút chì giá 4 nghìn đồng. Hỏi 1 cục tẩy giá bao nhiêu?',
      opts: o5('1 nghìn đồng', '2 nghìn đồng', '3 nghìn đồng', '4 nghìn đồng', '5 nghìn đồng'), ans: 'A',
      why: '6 bút chì = 2 lần (3 bút chì) giá 2 × 4 = 8 nghìn. Vậy 11 cục tẩy giá 19 − 8 = 11 nghìn → mỗi cục tẩy 1 nghìn đồng.' },
    { sec: 'Toán đố', name: 'Câu 17', pts: 0.5,
      text: 'Jazz, Adrian và Andrew đi câu cá, được tổng cộng 90 con. Số cá của Jazz gấp 3 lần của Andrew. Số cá của Andrew gấp 2 lần của Adrian. Hỏi Adrian câu được bao nhiêu con?',
      opts: o5('10', '20', '40', '60', '50'), ans: 'A',
      why: 'Gọi số cá của Adrian là 1 phần thì Andrew 2 phần, Jazz 6 phần. Tổng 9 phần = 90 con → 1 phần = 10 con. Adrian câu được 10 con.' },
    { sec: 'Đếm chữ số', name: 'Câu 18', pts: 0.5,
      text: 'John phát 100 tấm thẻ đánh số từ 1 đến 100 cho các bạn nhỏ. Bạn nào cầm thẻ có chứa chữ số 3 sẽ trúng thưởng. Hỏi có bao nhiêu bạn trúng thưởng?',
      opts: o5('9', '19', '29', '39', '49'), ans: 'B',
      why: 'Số có chữ số 3 ở hàng đơn vị: 3, 13, 23, …, 93 — 10 số. Số có chữ số 3 ở hàng chục: 30–39 — 10 số. Số 33 bị đếm 2 lần. Vậy có 10 + 10 − 1 = 19 bạn.' },
    { sec: 'Đếm cách chọn', name: 'Câu 19', pts: 0.5,
      text: 'Wendy được nghỉ 1 tuần (từ thứ Hai đến Chủ nhật). Bạn muốn đi bơi 2 buổi trong tuần nhưng mẹ không cho đi 2 ngày liền nhau. Hỏi Wendy có bao nhiêu cách chọn 2 ngày đi bơi?',
      opts: o5('5', '10', '15', '20', '25'), ans: 'C',
      why: 'Chọn 2 ngày bất kỳ trong 7 ngày có 21 cách. Trong đó có 6 cặp ngày liền nhau (T2-T3, T3-T4, …, T7-CN) không được chọn. Vậy còn 21 − 6 = 15 cách.' },
    { sec: 'Chuyển động', name: 'Câu 20', pts: 0.5,
      text: 'Một máy bay bay được 108 km trong 4 giờ. Hỏi cần tổng cộng bao nhiêu giờ nếu máy bay tiếp tục bay thêm 270 km nữa với cùng vận tốc?',
      opts: o5('14', '15', '16', '17', 'Không có đáp án nào đúng'), ans: 'A',
      why: 'Vận tốc: 108 ÷ 4 = 27 km/giờ. Bay 270 km cần 270 ÷ 27 = 10 giờ. Tổng thời gian: 4 + 10 = 14 giờ.' },
  ],
},
/* ================= ASMO 2015 ================= */
{
  id: 202, title: 'ASMO 2015', time: 45,
  questions: [
    { sec: 'Số học', name: 'Câu 1', pts: 0.5,
      text: 'Số nào nằm ở <b>chính giữa</b> số 21 và số 47?',
      opts: o5('31', '32', '34', '33', '35'), ans: 'C',
      why: 'Số chính giữa cách đều hai đầu: (21 + 47) ÷ 2 = 68 ÷ 2 = 34.' },
    { sec: 'Điền chữ số', name: 'Câu 2', pts: 0.5,
      text: 'Trong phép cộng dưới đây, C và D lần lượt là chữ số nào?<br><b style="font-family:monospace;font-size:22px;line-height:1.3">&nbsp;&nbsp;1&nbsp;7<br>+&nbsp;C&nbsp;D<br>────<br>&nbsp;&nbsp;8&nbsp;2</b>',
      opts: o5('7 và 5', '6 và 5', '5 và 6', '7 và 4', '6 và 6'), ans: 'B',
      why: 'C̄D̄ = 82 − 17 = 65. Vậy C = 6 và D = 5. (Thử lại: 17 + 65 = 82 ✓)' },
    { sec: 'Thời gian', name: 'Câu 3', pts: 0.5,
      text: 'Sandra đến trường sớm 16 phút. Trường vào học lúc 7 giờ 25 phút sáng. Hỏi Sandra đến trường lúc mấy giờ?',
      opts: o5('7:11 sáng', '7:41 sáng', '7:10 sáng', '7:09 sáng', '7:12 sáng'), ans: 'D',
      why: '7 giờ 25 phút bớt đi 16 phút: 25 − 16 = 9. Sandra đến lúc 7 giờ 09 phút.' },
    { sec: 'Hình khối', name: 'Câu 4', pts: 0.5,
      text: 'Có bao nhiêu khối lập phương trong hình dưới đây (kể cả những khối bị che khuất)?', img: AS + 'a15q4.svg',
      opts: o5('17', '19', '16', '18', '13'), ans: 'A',
      why: 'Đếm theo tầng, nhớ cả các khối bị che: tầng 1 có 10 khối, tầng 2 có 4 khối, tầng 3 có 2 khối, tầng 4 có 1 khối. Tổng: 10 + 4 + 2 + 1 = 17 khối.' },
    { sec: 'Số học', name: 'Câu 5', pts: 0.5,
      text: 'Hiệu giữa số có ba chữ số <b>nhỏ nhất</b> và số có hai chữ số <b>lớn nhất</b> là bao nhiêu?',
      opts: o5('1', '199', '90', '9', '10'), ans: 'A',
      why: 'Số có ba chữ số nhỏ nhất là 100, số có hai chữ số lớn nhất là 99. Hiệu: 100 − 99 = 1.' },
    { sec: 'Quy luật hình', name: 'Câu 6', pts: 0.5,
      text: 'Tìm 2 hình còn thiếu (ở 2 ô có dấu ?) trong dãy hình sau:', img: AS + 'a15q6.svg',
      opts: o5('Bầu dục và tam giác', 'Chữ nhật và tam giác', 'Chữ nhật và bầu dục', 'Chữ nhật và chữ nhật', 'Tam giác và bầu dục'), ans: 'C',
      why: 'Dãy lặp lại theo nhóm 5 hình: chữ nhật – tam giác – bầu dục – bầu dục – tam giác. Ô thứ 6 bắt đầu nhóm mới nên là <b>chữ nhật</b>; ô thứ 9 là hình thứ tư của nhóm nên là <b>bầu dục</b>.' },
    { sec: 'Số học', name: 'Câu 7', pts: 0.5,
      text: '( &nbsp; ) + 26 = 95 − 39.<br>Số cần điền vào chỗ trống là số nào?',
      opts: o5('69', '56', '30', '29', '40'), ans: 'C',
      why: '95 − 39 = 56. Số cần tìm: 56 − 26 = 30.' },
    { sec: 'Quy luật số', name: 'Câu 8', pts: 0.5,
      text: 'Tìm số còn thiếu:<br><b>2, 6, 14, ___, 62, 126</b>',
      opts: o5('32', '28', '30', '40', '36'), ans: 'C',
      why: 'Quy luật: mỗi số bằng số trước nhân 2 rồi cộng 2. Ta có 14 × 2 + 2 = 30 (kiểm tra: 30 × 2 + 2 = 62 ✓).' },
    { sec: 'Thời gian', name: 'Câu 9', pts: 0.5,
      text: 'Hai ngày rưỡi có bao nhiêu giờ?',
      opts: o5('3', '12', '48', '24', '60'), ans: 'E',
      why: 'Mỗi ngày 24 giờ. Hai ngày rưỡi: 24 + 24 + 12 = 60 giờ.' },
    { sec: 'So sánh', name: 'Câu 10', pts: 0.5,
      text: 'Số <b>lớn nhất</b> có thể điền vào chỗ trống là số nào?<br><b>8 + ______ &lt; 64</b>',
      opts: o5('48', '39', '56', '55', '60'), ans: 'D',
      why: 'Cần 8 + số đó bé hơn 64, tức số đó bé hơn 56. Số lớn nhất thỏa mãn là 55 (8 + 55 = 63 < 64 ✓).' },
    { sec: 'Số học', name: 'Câu 11', pts: 0.5,
      text: 'Tôi là số 39. Lấy chữ số lớn trừ đi chữ số bé của tôi thì được bao nhiêu?',
      opts: o5('6', '8', '12', '7', '5'), ans: 'A',
      why: 'Hai chữ số của 39 là 3 và 9. Hiệu: 9 − 3 = 6.' },
    { sec: 'Phép nhân', name: 'Câu 12', pts: 0.5,
      text: 'Một quyển sách có 12 trang. Hỏi 7 quyển sách như vậy có bao nhiêu trang?',
      opts: o5('12', '84', '70', '19', '80'), ans: 'B',
      why: '12 × 7 = 84 trang.' },
    { sec: 'Toán đố', name: 'Câu 13', pts: 0.5,
      text: 'Sammy nuôi 2 con rùa, 1 con nhện, 2 con mèo và 3 con vẹt. Hỏi tổng số chân của các con vật là bao nhiêu? (Rùa 4 chân, nhện 8 chân, mèo 4 chân, vẹt 2 chân)',
      opts: o5('28', '30', '32', '25', '26'), ans: 'B',
      why: 'Rùa: 2 × 4 = 8; nhện: 8; mèo: 2 × 4 = 8; vẹt: 3 × 2 = 6. Tổng: 8 + 8 + 8 + 6 = 30 chân.' },
    { sec: 'Biểu đồ', name: 'Câu 14', pts: 0.5,
      text: 'Biểu đồ dưới đây cho biết số bóng bay mỗi màu trong cửa hàng. Alice mua hết toàn bộ bóng <b>đỏ</b> và bóng <b>đen</b>. Hỏi Alice mua bao nhiêu quả bóng?', img: AS + 'a15q14.svg',
      opts: o5('18', '33', '27', '30', '32'), ans: 'B',
      why: 'Nhìn biểu đồ: bóng đỏ 18 quả, bóng đen 15 quả. Alice mua 18 + 15 = 33 quả.' },
    { sec: 'Logic', name: 'Câu 15', pts: 0.5,
      text: 'Abdullah nặng hơn Samuel. Elliot nặng hơn Samuel nhưng nhẹ hơn Abdullah. Bryan nặng hơn cả Elliot và Abdullah nhưng nhẹ hơn Faymen. Hỏi ai nặng nhất?',
      opts: o5('Faymen', 'Bryan', 'Abdullah', 'Elliot', 'Samuel'), ans: 'A',
      why: 'Xếp từ nhẹ đến nặng: Samuel < Elliot < Abdullah < Bryan < Faymen. Vậy Faymen nặng nhất.' },
    { sec: 'Tính ngược', name: 'Câu 16', pts: 0.5,
      text: 'Cho sơ đồ tính:<br><b>? &nbsp;→&nbsp; CỘNG 10 &nbsp;→&nbsp; TRỪ 8 &nbsp;→&nbsp; NHÂN 3 &nbsp;→&nbsp; KẾT QUẢ: 33</b><br>Hỏi phải điền số nào vào ô dấu ? để được kết quả 33?',
      opts: o5('8', '12', '10', '9', '11'), ans: 'D',
      why: 'Tính ngược: 33 ÷ 3 = 11; 11 + 8 = 19; 19 − 10 = 9. Vậy số cần điền là 9.' },
    { sec: 'Thời gian', name: 'Câu 17', pts: 0.5,
      text: 'Bây giờ là 10 giờ đêm. Hỏi sau 21 giờ nữa, đồng hồ chỉ mấy giờ?',
      opts: o5('7 giờ sáng', '6 giờ chiều', '7 giờ tối', '8 giờ tối', '6 giờ sáng'), ans: 'C',
      why: 'Sau 24 giờ sẽ lại là 10 giờ đêm hôm sau. 21 giờ ít hơn 24 giờ đúng 3 giờ, nên lùi lại 3 giờ: 10 giờ đêm − 3 giờ = 7 giờ tối.' },
    { sec: 'Tuổi', name: 'Câu 18', pts: 0.5,
      text: 'Muhamad sinh năm 2002 và kém mẹ 20 tuổi. Hỏi năm nay (năm thi 2015) mẹ của Muhamad bao nhiêu tuổi?',
      opts: o5('33', '20', '13', '15', '30'), ans: 'A',
      why: 'Năm 2015, Muhamad 2015 − 2002 = 13 tuổi. Mẹ hơn 20 tuổi: 13 + 20 = 33 tuổi.' },
    { sec: 'Cân bằng', name: 'Câu 19', pts: 0.5,
      text: '10 quả táo nặng bằng 1 quả dưa hấu và 2 quả lê. 1 quả lê nặng bằng 2 quả táo. Hỏi 1 quả dưa hấu nặng bằng bao nhiêu quả táo?',
      opts: o5('6', '4', '8', '5', '2'), ans: 'A',
      why: '2 quả lê nặng bằng 4 quả táo. Vậy dưa hấu = 10 táo − 4 táo = 6 quả táo.' },
    { sec: 'Số học', name: 'Câu 20', pts: 0.5,
      text: 'Tôi đang đọc sách. Tích của hai số trang ở hai trang đang mở là 110. Hỏi tổng của hai số trang đó là bao nhiêu?',
      opts: o5('10', '21', '11', '27', '20'), ans: 'B',
      why: 'Hai trang mở ra là hai số liền nhau. Vì 10 × 11 = 110 nên đó là trang 10 và 11. Tổng: 10 + 11 = 21.' },
  ],
},
/* ================= ASMO 2017 ================= */
{
  id: 203, title: 'ASMO 2017', time: 45,
  questions: [
    { sec: 'Số học', name: 'Câu 1', pts: 0.5,
      text: 'Tính: <b>18 + 14 − 13 = 32 − ( &nbsp; )</b><br>Số cần điền vào chỗ trống là số nào?',
      opts: o5('13', '14', '18', '32', '19'), ans: 'A',
      why: 'Vế trái: 18 + 14 − 13 = 19. Để 32 − ( ) = 19 thì ( ) = 32 − 19 = 13.' },
    { sec: 'Đếm hình', name: 'Câu 2', pts: 0.5,
      text: 'Đếm xem có bao nhiêu hình tam giác trong hình dưới đây?', img: AS + 'a17q2.svg',
      opts: o5('8', '9', '7', '6', '10'), ans: 'B',
      why: 'Hình có 2 vạch ngang chia tam giác lớn thành 3 mức, cùng 1 đường thẳng đứng chia đôi. Ở mỗi mức (đỉnh tới vạch 1, đỉnh tới vạch 2, đỉnh tới đáy) có 3 tam giác: nửa trái, nửa phải và cả hình. Tổng: 3 × 3 = 9 tam giác.' },
    { sec: 'Toán đố', name: 'Câu 3', pts: 0.5,
      text: 'Mẹ cho Sammy 10 nghìn đồng. Sammy mua 2 quyển vở giá 1500 đồng mỗi quyển và 1 hộp bút giá 5 nghìn đồng. Hỏi Sammy còn lại bao nhiêu tiền?',
      opts: o5('7 nghìn đồng', '10 nghìn đồng', '2 nghìn đồng', '5 nghìn đồng', '3 nghìn đồng'), ans: 'C',
      why: 'Tiền vở: 2 × 1500 = 3000 đồng. Tổng tiền mua: 3000 + 5000 = 8000 đồng. Còn lại: 10000 − 8000 = 2000 đồng.' },
    { sec: 'Đếm chữ số', name: 'Câu 4', pts: 0.5,
      text: 'Alice đánh số các hộp quà Giáng sinh từ 1 đến 56. Hỏi bạn phải viết chữ số 5 bao nhiêu lần?',
      opts: o5('15', '14', '11', '13', '12'), ans: 'D',
      why: 'Chữ số 5 ở hàng đơn vị: 5, 15, 25, 35, 45, 55 — 6 lần. Ở hàng chục: 50, 51, …, 56 — 7 lần. Tổng: 6 + 7 = 13 lần (số 55 có 2 chữ số 5, được tính ở cả hai nhóm).' },
    { sec: 'Xem đồng hồ', name: 'Câu 5', pts: 0.5,
      text: 'Giờ vào học của trường được thể hiện trên đồng hồ dưới đây. Kym đến muộn 38 phút. Hỏi Kym đến trường lúc mấy giờ?', img: AS + 'a17q5.svg',
      opts: o5('7:40 sáng', '8:00 sáng', '8:15 sáng', '7:02 sáng', '8:18 sáng'), ans: 'E',
      why: 'Đồng hồ chỉ 7 giờ 40 phút. Muộn 38 phút: 7:40 + 20 phút = 8:00, thêm 18 phút nữa là 8 giờ 18 phút.' },
    { sec: 'Điền chữ số', name: 'Câu 6', pts: 0.5,
      text: 'Trong phép trừ dưới đây, giá trị của <b>P + Q</b> là bao nhiêu?<br><b style="font-family:monospace;font-size:22px;line-height:1.3">&nbsp;&nbsp;8&nbsp;P&nbsp;1<br>−&nbsp;Q&nbsp;2&nbsp;P<br>─────<br>&nbsp;&nbsp;5&nbsp;Q&nbsp;5</b>',
      opts: o5('10', '9', '8', '3', '7'), ans: 'B',
      why: 'Hàng đơn vị: 1 − P tận cùng là 5 nên phải mượn: 11 − P = 5 → P = 6. Hàng trăm: 8 − Q = 5 → Q = 3. (Kiểm tra hàng chục: 6 − 1 − 2 = 3 = Q ✓, tức 861 − 326 = 535.) Vậy P + Q = 6 + 3 = 9.' },
    { sec: 'Quy luật hình', name: 'Câu 7', pts: 0.5,
      text: 'Hình thứ 29 của dãy sau là hình gì?<br><span style="font-size:26px">🤍🤍➕🤍🔺✳️ 🤍🤍🤍➕🤍🔺✳️ 🤍🤍🤍🤍…</span>',
      opts: o5('Trái tim 🤍', 'Ngôi sao ✳️', 'Chữ thập ➕', 'Tam giác 🔺', 'Không xác định được'), ans: 'D',
      why: 'Dãy gồm các nhóm: (2 tim)➕(1 tim)🔺✳️ dài 6 hình, rồi (3 tim)➕(1 tim)🔺✳️ dài 7 hình, rồi nhóm 8 hình, 9 hình… Cộng dồn: 6, 13, 21, 30. Hình thứ 29 nằm trong nhóm thứ tư (từ hình 22 đến 30): 5 tim (22–26), ➕ (27), tim (28), 🔺 (29), ✳️ (30). Vậy hình thứ 29 là tam giác 🔺.' },
    { sec: 'Diện tích', name: 'Câu 8', pts: 0.5,
      text: 'Hình nào có phần tô đậm với diện tích <b>nhỏ nhất</b>?', img: AS + 'a17q8.svg',
      opts: o5('Hình A', 'Hình B', 'Hình C', 'Hình D', 'Hình E'), ans: 'E',
      why: 'Đếm theo ô vuông: A là hình thoi có 2 đường chéo 4 ô → 4 × 4 ÷ 2 = 8 ô; B = 12 − 2 = 10 ô; C = 2 × 4 = 8 ô; D = 2 + 4 = 6 ô; E là tam giác nửa hình vuông 3×3 → 4,5 ô. Nhỏ nhất là hình E.' },
    { sec: 'Toán đố', name: 'Câu 9', pts: 0.5,
      text: 'Sau khi Regene tặng Mia 8 bông hồng và tặng Jon 9 bông hồng, số hồng còn lại của Regene gấp đôi số hồng của Jon. Hỏi lúc đầu Regene có bao nhiêu bông hồng? (Lúc đầu Jon chưa có bông nào)',
      opts: o5('26', '17', '35', '36', '27'), ans: 'C',
      why: 'Jon được tặng 9 bông. Regene còn lại gấp đôi: 9 × 2 = 18 bông. Lúc đầu Regene có 18 + 8 + 9 = 35 bông.' },
    { sec: 'Tuổi', name: 'Câu 10', pts: 0.5,
      text: 'Thỏ nói: "Khi tôi sinh ra, Rùa 2 tuổi." Bây giờ tổng số tuổi của hai bạn là 10. Hỏi Rùa hiện nay mấy tuổi?',
      opts: o5('6', '7', '3', '4', '5'), ans: 'A',
      why: 'Rùa luôn hơn Thỏ 2 tuổi. Tổng 10, hiệu 2 → Rùa = (10 + 2) ÷ 2 = 6 tuổi (Thỏ 4 tuổi).' },
    { sec: 'Quy luật số', name: 'Câu 11', pts: 0.5,
      text: 'Tìm các số còn thiếu:<br><b>7, 8, 11, 16, ___, 32, ___, 56</b>',
      opts: o5('26 và 43', '27 và 44', '23 và 39', '23 và 43', '25 và 36'), ans: 'D',
      why: 'Khoảng cách giữa các số lần lượt là 1, 3, 5, 7, 9, 11, 13. Vậy 16 + 7 = 23 (kiểm tra 23 + 9 = 32 ✓) và 32 + 11 = 43 (43 + 13 = 56 ✓).' },
    { sec: 'Đếm số', name: 'Câu 12', pts: 0.5,
      text: 'Dùng các chữ số 3, 4, 8, 6 (mỗi chữ số dùng 1 lần trong mỗi số) để lập số có 3 chữ số. Hỏi lập được bao nhiêu số <b>lẻ</b>?',
      opts: o5('6', '4', '8', '5', '10'), ans: 'A',
      why: 'Số lẻ phải tận cùng bằng 3 (các chữ số 4, 8, 6 đều chẵn). Hai vị trí còn lại chọn từ 3 chữ số 4, 8, 6: có 3 × 2 = 6 cách. Vậy lập được 6 số lẻ.' },
    { sec: 'Tư duy đại số', name: 'Câu 13', pts: 0.5,
      text: 'Cho biết:<br><b>△ + △ + △ = 15</b><br><b>□ + △ = 8</b><br><b>○ + □ = 11</b><br>Hỏi ○ có giá trị bằng bao nhiêu?',
      opts: o5('3', '5', '8', '6', '4'), ans: 'C',
      why: '△ = 15 ÷ 3 = 5. □ = 8 − 5 = 3. ○ = 11 − 3 = 8.' },
    { sec: 'Tư duy', name: 'Câu 14', pts: 0.5,
      text: 'Đường nào <b>ngắn nhất</b> để đi từ Trường đến Thư viện?', img: AS + 'a17q14.svg',
      opts: [{ k: 'A', t: 'Đường (A)' }, { k: 'B', t: 'Đường (B)' }, { k: 'C', t: 'Đường (C)' }, { k: 'D', t: 'Đường (D)' }], ans: 'C',
      why: 'Trường và Thư viện nằm trên cùng một hàng ngang. Đường C đi thẳng, không phải vòng lên hay vòng xuống nên ngắn nhất.' },
    { sec: 'Đo lường', name: 'Câu 15', pts: 0.5,
      text: 'Biết 1 km = 1000 m và 1 m = 100 cm.<br><b>1 km 20 m = ( &nbsp; ) cm?</b>',
      opts: o5('1200', '1020', '12000', '102000', '10200'), ans: 'D',
      why: '1 km 20 m = 1000 + 20 = 1020 m. Đổi ra xăng-ti-mét: 1020 × 100 = 102000 cm.' },
    { sec: 'Cân bằng', name: 'Câu 16', pts: 0.5,
      text: 'Ba chiếc cân hiển thị như hình. Hỏi quả chuối nặng bao nhiêu gam?', img: AS + 'a17q16.svg',
      opts: o5('25 g', '100 g', '125 g', '200 g', '105 g'), ans: 'E',
      why: '2 táo = 400 g → 1 táo = 200 g. Cân 2: 3 dâu + 1 táo = 260 g → 3 dâu = 60 g → 1 dâu = 20 g. Cân 3: dâu + chuối + táo = 325 g → chuối = 325 − 20 − 200 = 105 g.' },
    { sec: 'Logic', name: 'Câu 17', pts: 0.5,
      text: '5 bạn xếp hàng: Siti đứng giữa Yumy và Iman. Iman đứng ngay trước Edward. Yumy đứng ngay sau Rachel. Hỏi ai đứng <b>thứ 2</b> trong hàng?',
      opts: o5('Iman', 'Rachel', 'Yumy', 'Siti', 'Edward'), ans: 'C',
      why: 'Thứ tự từ đầu hàng: Rachel → Yumy → Siti → Iman → Edward. Người đứng thứ 2 là Yumy.' },
    { sec: 'Số học', name: 'Câu 18', pts: 0.5,
      text: 'A nói: "Tôi là bội của 3, lớn hơn 4 và nhỏ hơn 8."<br>B nói: "Tôi là số chẵn lớn hơn 5, nhỏ hơn 10 và chia hết cho 4."<br>Hỏi tích A × B bằng bao nhiêu?',
      opts: o5('48', '8', '6', '14', '2'), ans: 'A',
      why: 'A là bội của 3 trong khoảng (4; 8) → A = 6. B chẵn, trong khoảng (5; 10), chia hết cho 4 → B = 8. Tích: 6 × 8 = 48.' },
    { sec: 'Hình khối', name: 'Câu 19', pts: 0.5,
      text: 'Có bao nhiêu khối lập phương trong hình dưới đây (kể cả những khối bị che khuất)?', img: AS + 'a17q19.svg',
      opts: o5('15', '13', '16', '18', '19'), ans: 'B',
      why: 'Đếm theo tầng: tầng 1 có 9 khối (kể cả 3 khối bị che dưới các chồng cao), tầng 2 có 3 khối, tầng 3 có 1 khối. Tổng: 9 + 3 + 1 = 13 khối.' },
    { sec: 'Quy luật số', name: 'Câu 20', pts: 0.5,
      text: 'Cindy sưu tầm tem: thứ Hai được 1 con tem, thứ Ba được 2 con, thứ Tư được 3 con… cứ thế tăng dần. Hỏi sau 1 tuần (7 ngày) Cindy có bao nhiêu con tem?',
      opts: o5('24', '25', '6', '30', '28'), ans: 'E',
      why: 'Tổng: 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28 con tem.' },
  ],
},
/* ================= ASMO 2018 ================= */
{
  id: 204, title: 'ASMO 2018', time: 45,
  questions: [
    { sec: 'So sánh', name: 'Câu 1', pts: 0.5,
      text: 'Số <b>lớn nhất</b> có thể điền vào ô trống là số nào?<br><b>42 − ⬜ &gt; 27</b>',
      opts: o5('15', '14', '16', '2', '21'), ans: 'B',
      why: 'Cần 42 − ⬜ lớn hơn 27, tức ⬜ bé hơn 42 − 27 = 15. Số lớn nhất thỏa mãn là 14 (42 − 14 = 28 > 27 ✓).' },
    { sec: 'Điền chữ số', name: 'Câu 2', pts: 0.5,
      text: 'Tìm giá trị của A và B trong phép cộng:<br><b style="font-family:monospace;font-size:22px;line-height:1.3">&nbsp;&nbsp;&nbsp;5&nbsp;7<br>+&nbsp;&nbsp;A&nbsp;B<br>─────<br>&nbsp;1&nbsp;2&nbsp;1</b>',
      opts: o5('A = 1, B = 4', 'A = 2, B = 5', 'A = 3, B = 6', 'A = 6, B = 4', 'A = 4, B = 6'), ans: 'D',
      why: 'ĀB̄ = 121 − 57 = 64. Vậy A = 6, B = 4. (Thử lại: 57 + 64 = 121 ✓)' },
    { sec: 'Đếm số', name: 'Câu 3', pts: 0.5,
      text: 'Từ 31 đến 64 có bao nhiêu số <b>lẻ</b>?',
      opts: o5('5', '10', '16', '17', '18'), ans: 'D',
      why: 'Các số lẻ: 31, 33, 35, …, 63. Số lượng: (63 − 31) ÷ 2 + 1 = 17 số.' },
    { sec: 'Quy luật số', name: 'Câu 4', pts: 0.5,
      text: 'Dãy số nào có quy luật <b>khác</b> với ba dãy còn lại?',
      opts: o5('22, 24, 27, 29, 32', '45, 47, 50, 52, 55', '52, 54, 58, 60, 64', '60, 62, 65, 67, 70', '28, 30, 33, 35, 38'), ans: 'C',
      why: 'Các dãy A, B, D, E đều tăng xen kẽ +2, +3, +2, +3. Riêng dãy C tăng +2, +4, +2, +4 nên khác quy luật.' },
    { sec: 'Hình khối', name: 'Câu 5', pts: 0.5,
      text: 'Mô hình dưới đây được xếp từ bao nhiêu khối lập phương (kể cả những khối bị che khuất)?', img: AS + 'a18q5.svg',
      opts: o5('12', '15', '26', '27', '25'), ans: 'C',
      why: 'Đếm theo tầng: tầng dưới cùng 4 × 4 = 16 khối, tầng giữa 3 × 3 = 9 khối, tầng trên cùng 1 khối. Tổng: 16 + 9 + 1 = 26 khối.' },
    { sec: 'Đếm hình', name: 'Câu 6', pts: 0.5,
      text: 'Có bao nhiêu hình tam giác trong hình dưới đây?', img: AS + 'a18q6.svg',
      opts: o5('5', '7', '9', '10', '8'), ans: 'C',
      why: 'Nửa trên có 2 tam giác nhỏ (hai "cánh bướm"). Nửa dưới có 2 tam giác nhỏ và 1 tam giác to úp xuống đáy. Thêm 2 tam giác cao cả hình ở bên trái và bên phải, cùng 2 tam giác lớn dùng cả đường chéo và cạnh bên. Tổng: 2 + 3 + 2 + 2 = 9 tam giác.' },
    { sec: 'Tính nhanh', name: 'Câu 7', pts: 0.5,
      text: 'Tính tổng:<br><b>39 + 38 + 37 + 36 + 35 + 34 + 33 + 32 + 31 = ?</b>',
      opts: o5('280', '300', '245', '315', '316'), ans: 'D',
      why: 'Có 9 số liên tiếp, số ở chính giữa là 35. Tổng = 35 × 9 = 315.' },
    { sec: 'Tư duy đại số', name: 'Câu 8', pts: 0.5,
      text: 'Cho biết:<br><b>⚪ + ⚪ + ⭐ + ⭐ + ⭐ = 18</b><br><b>⭐ + ⭐ + ⭐ + ⭐ = 8</b><br>Hỏi ⚪ có giá trị bằng bao nhiêu?',
      opts: o5('10', '9', '8', '7', '6'), ans: 'E',
      why: '4⭐ = 8 → ⭐ = 2. Suy ra 2⚪ = 18 − 3 × 2 = 12 → ⚪ = 6.' },
    { sec: 'Quy luật số', name: 'Câu 9', pts: 0.5,
      text: 'Tìm hai số cần điền vào hai ô trống:<br><b>12, 13, 15, 18, 22, ⬜, 33, ⬜</b>',
      opts: o5('28 và 40', '27 và 40', '30 và 35', '26 và 37', '25 và 39'), ans: 'B',
      why: 'Khoảng cách tăng dần 1, 2, 3, 4, 5, 6, 7: sau 22 là 22 + 5 = 27 (27 + 6 = 33 ✓), sau 33 là 33 + 7 = 40.' },
    { sec: 'Tính nhanh', name: 'Câu 10', pts: 0.5,
      text: '<b>11 + 12 + 13 + 14 + 15 + 16 + 17 + 18 + 19 = ⬜ × ⬜</b><br>Cặp số nào phù hợp để điền vào hai ô trống?',
      opts: o5('16 và 10', '15 và 9', '14 và 8', '135 và 0', '20 và 21'), ans: 'B',
      why: 'Tổng 9 số liên tiếp với số giữa là 15: tổng = 15 × 9 = 135. Vậy điền 15 và 9.' },
    { sec: 'Lịch', name: 'Câu 11', pts: 0.5,
      text: 'Ngày 21 tháng 1 năm 2008 là thứ Hai. Hỏi ngày 29 tháng 2 năm 2008 là thứ mấy?',
      opts: o5('Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu'), ans: 'E',
      why: 'Từ 21/1 đến 29/2 là 10 + 29 = 39 ngày. 39 = 7 × 5 + 4, tức 5 tuần và 4 ngày. Thứ Hai + 4 ngày = thứ Sáu.' },
    { sec: 'Tính nhanh', name: 'Câu 12', pts: 0.5,
      text: 'Tính:<br><b>70 − 69 + 68 − 67 + 66 − 65 + … + 4 − 3 + 2 − 1 = ?</b>',
      opts: o5('1', '25', '35', '75', '2485'), ans: 'C',
      why: 'Ghép từng cặp: (70 − 69) + (68 − 67) + … + (2 − 1). Từ 1 đến 70 có 70 số, tạo thành 35 cặp, mỗi cặp bằng 1. Tổng = 35.' },
    { sec: 'Chia hết', name: 'Câu 13', pts: 0.5,
      text: 'Mùa sầu riêng, bác Bob hái được hơn 50 quả trong vườn. Bác chia đều cho 3 người con trai thì còn dư 3 quả. Hỏi lúc đầu bác Bob hái được bao nhiêu quả?',
      opts: o5('56', '52', '53', '54', '55'), ans: 'D',
      why: 'Số quả trừ đi 3 phải chia hết cho 3. Thử các đáp án: 54 − 3 = 51 = 3 × 17 ✓. Các số còn lại (56, 52, 53, 55) trừ 3 đều không chia hết cho 3.' },
    { sec: 'Quy luật số', name: 'Câu 14', pts: 0.5,
      text: 'Dãy số được xếp theo quy luật: <b>21, 22, 23, 21, 22, 23, 21, 22, 23, …</b><br>Tìm tổng của số thứ 30 và số thứ 40 trong dãy.',
      opts: o5('23', '21', '43', '44', '55'), ans: 'D',
      why: 'Nhóm "21, 22, 23" lặp lại. 30 = 3 × 10 nên số thứ 30 là số cuối nhóm: 23. 40 = 3 × 13 + 1 nên số thứ 40 là số đầu nhóm: 21. Tổng: 23 + 21 = 44.' },
    { sec: 'Toán đố', name: 'Câu 15', pts: 0.5,
      text: 'Hai bác Joel mang về rất nhiều trái cây: có 60 quả chuối; số chôm chôm gấp 3 lần số chuối; số măng cụt bằng một nửa số chôm chôm. Hỏi có bao nhiêu quả măng cụt?',
      opts: o5('300', '200', '90', '63', '180'), ans: 'C',
      why: 'Chôm chôm: 60 × 3 = 180 quả. Măng cụt: 180 ÷ 2 = 90 quả.' },
    { sec: 'Tư duy', name: 'Câu 16', pts: 0.5,
      text: 'Một ô tô đi từ Kota Kinabalu đến Kudat hết 2 giờ. Hỏi nếu 9 ô tô cùng xuất phát đi từ Kota Kinabalu đến Kudat thì mỗi xe đi hết bao nhiêu giờ?',
      opts: o5('18', '11', '7', '4', '2'), ans: 'E',
      why: 'Các xe đi cùng quãng đường với cùng thời gian — dù có bao nhiêu xe thì mỗi xe vẫn đi hết 2 giờ.' },
    { sec: 'Xem đồng hồ', name: 'Câu 17', pts: 0.5,
      text: 'Các đồng hồ thay đổi theo quy luật. Hỏi đồng hồ thứ 4 chỉ mấy giờ?', img: AS + 'a18q17.svg',
      opts: o5('3 giờ', '6 giờ', '9 giờ', '12 giờ', '6 giờ 30 phút'), ans: 'D',
      why: 'Ba đồng hồ đầu chỉ 3 giờ, 6 giờ, 9 giờ — mỗi lần tăng thêm 3 giờ. Vậy đồng hồ thứ 4 chỉ 9 + 3 = 12 giờ.' },
    { sec: 'Lập số', name: 'Câu 18', pts: 0.5,
      text: 'Cho 5 chữ số: <b>7, 2, 5, 8, 3</b>. Tìm hiệu giữa số có 5 chữ số <b>lớn nhất</b> và số có 5 chữ số <b>nhỏ nhất</b> ghép được từ 5 chữ số này (mỗi chữ số dùng 1 lần).',
      opts: o5('111110', '72583', '38527', '63954', '63955'), ans: 'D',
      why: 'Số lớn nhất: xếp giảm dần 87532. Số nhỏ nhất: xếp tăng dần 23578. Hiệu: 87532 − 23578 = 63954.' },
    { sec: 'Toán đố', name: 'Câu 19', pts: 0.5,
      text: 'Mẹ mua 30 quả cam. Ngày thứ nhất cả nhà ăn 8 quả. Ngày thứ hai cả nhà ăn bằng một nửa ngày thứ nhất. Hỏi trong hai ngày cả nhà đã ăn bao nhiêu quả cam?',
      opts: o5('16', '20', '12', '4', '40'), ans: 'C',
      why: 'Ngày 2 ăn 8 ÷ 2 = 4 quả. Hai ngày ăn 8 + 4 = 12 quả.' },
    { sec: 'Tư duy', name: 'Câu 20', pts: 0.5,
      text: 'Adam cưa một tấm ván dài thành 10 khúc để làm nhà cho chú chó. Mỗi lần cưa mất 4 phút. Hỏi Adam cưa tất cả hết bao nhiêu phút?',
      opts: o5('42', '40', '35', '36', '14'), ans: 'D',
      why: 'Để được 10 khúc chỉ cần cưa 9 lần. Thời gian: 9 × 4 = 36 phút.' },
  ],
},
];

// Chèn môn "ASMO" vào sau Toán tư duy trong danh sách môn học
SUBJECTS.splice(2, 0, {
  id: 'asmo', name: 'ASMO', short: 'ASMO 2', icon: '🏅', grade: 2,
  exams: ASMO_EXAMS, ready: true,
  heroTitle: 'ASMO Toán quốc tế — Lớp 2 (đề thật các năm)',
  heroMeta: '📚 4 đề &nbsp;•&nbsp; ⏱ 45 phút mỗi đề &nbsp;•&nbsp; 2014 · 2015 · 2017 · 2018 &nbsp;•&nbsp; lời giải chi tiết',
});
