// TOÁN NÂNG CAO – BỒI DƯỠNG HỌC SINH GIỎI TOÁN LỚP 3
// 15 đề chuyên đề × 8 câu = 120 câu. Mỗi câu 1,25 điểm — thang 10 — 35 phút mỗi đề.
//
// MỨC ĐỘ: HSG cấp trường / cấp quận – huyện (nâng cao vừa phải, KHÔNG lấy nguyên đề quốc gia
// hay olympic quốc tế). Bám sát chương trình lớp 3: phạm vi 100 000, bảng nhân chia,
// chu vi – diện tích, đo lường, thời gian, thống kê.
//
// NGUỒN THAM KHẢO DẠNG BÀI:
//  - Việt Nam: "13 đề thi HSG Toán lớp 3 có đáp án" và "Đề thi chọn HSG cấp trường môn Toán 3"
//    (VnDoc), "43 đề thi HSG Toán lớp 3" (VnStorage), "12 đề ôn thi HSG Toán 3" (Ôn thi 123),
//    chuyên đề Toán 3 nâng cao (PoMath, HOCMAI, Giáo viên Việt Nam).
//  - Nước ngoài (đã Việt hoá và HẠ ĐỘ KHÓ về mức cấp quận/huyện): Math Kangaroo bậc Écolier
//    (lớp 3–4), SASMO Grade 3 (Singapore & Asian Schools Math Olympiad), IMSO, HKIMO Primary 3.
//    Chỉ mượn Ý TƯỞNG dạng bài (đếm, suy luận, quy luật), số liệu được viết lại cho vừa sức.
//
// Toàn bộ câu hỏi biên soạn lại, tự kiểm tra phép tính, có lời giải chi tiết từng bước.

const HSG3_EXAMS = [

/* ═══════════ ĐỀ 1 — SỐ VÀ CẤU TẠO SỐ (đến 100 000) ═══════════ */
{
  id: 801, title: 'Đề 1 · Số và cấu tạo số', time: 35,
  questions: [
    { sec: 'Cấu tạo số', name: 'Câu 1', pts: 1.25,
      text: 'Số <b>lớn nhất có năm chữ số</b> mà tổng các chữ số của nó bằng 5 là số nào?',
      opts: o4('41 000', '50 000', '32 000', '11 111'), ans: 'B',
      why: 'Muốn số lớn nhất thì chữ số ở hàng cao nhất phải lớn nhất. Dồn cả 5 đơn vị vào hàng chục nghìn, các hàng còn lại là 0, ta được 50 000.' },
    { sec: 'Đếm số', name: 'Câu 2', pts: 1.25,
      text: 'Có bao nhiêu số có ba chữ số mà <b>chữ số hàng trăm là 4</b>?',
      opts: o4('100 số', '99 số', '90 số', '10 số'), ans: 'A',
      why: 'Đó là các số từ 400 đến 499. Số lượng: 499 − 400 + 1 = 100 (số).' },
    { sec: 'Lập số', name: 'Câu 3', pts: 1.25,
      text: 'Từ bốn chữ số <b>0; 1; 2; 3</b> viết được bao nhiêu số có ba chữ số <b>khác nhau</b>?',
      opts: o4('24 số', '12 số', '18 số', '9 số'), ans: 'C',
      why: 'Chữ số hàng trăm khác 0 nên có 3 cách chọn. Hàng chục còn 3 cách (kể cả 0), hàng đơn vị còn 2 cách. Tất cả: 3 × 3 × 2 = 18 (số).' },
    { sec: 'So sánh', name: 'Câu 4', pts: 1.25,
      text: 'Tổng của <b>số lớn nhất có bốn chữ số</b> và <b>số bé nhất có bốn chữ số</b> là:',
      opts: o4('11 000', '10 099', '19 999', '10 999'), ans: 'D',
      why: 'Số lớn nhất có bốn chữ số là 9 999; số bé nhất có bốn chữ số là 1 000. Tổng: 9 999 + 1 000 = 10 999.' },
    { sec: 'Đếm chữ số', name: 'Câu 5', pts: 1.25,
      text: 'Khi viết các số từ <b>1 đến 100</b>, chữ số <b>0</b> được viết bao nhiêu lần?',
      opts: o4('11 lần', '10 lần', '9 lần', '20 lần'), ans: 'A',
      why: 'Từ 1 đến 9 không có chữ số 0. Từ 10 đến 99, chữ số 0 chỉ xuất hiện ở hàng đơn vị của 10; 20; …; 90 — được 9 lần. Riêng số 100 có 2 chữ số 0. Tất cả: 9 + 2 = 11 lần.' },
    { sec: 'Cấu tạo số', name: 'Câu 6', pts: 1.25,
      text: 'Số <b>2 013</b> thay đổi thế nào nếu ta <b>xoá bỏ chữ số 0</b> của nó?',
      opts: o4('Giảm 1 000 đơn vị', 'Giảm 180 đơn vị', 'Giảm 1 800 đơn vị', 'Tăng 1 800 đơn vị'), ans: 'C',
      why: 'Xoá chữ số 0 ta được số 213. Ta có 2 013 − 213 = 1 800, nên số đó giảm đi 1 800 đơn vị.' },
    { sec: 'Tìm số', name: 'Câu 7', pts: 1.25,
      text: 'Một số có hai chữ số. Nếu viết thêm chữ số <b>0</b> vào bên phải số đó thì số mới hơn số cũ 261 đơn vị. Tìm số đó.',
      opts: o4('26', '29', '27', '31'), ans: 'B',
      why: 'Viết thêm 0 vào bên phải tức là số đó gấp lên 10 lần. Số mới hơn số cũ 10 − 1 = 9 lần chính nó. Vậy số cần tìm là 261 : 9 = 29. Thử lại: 290 − 29 = 261.' },
    { sec: 'Đếm số', name: 'Câu 8', pts: 1.25,
      text: 'Có bao nhiêu số có ba chữ số mà <b>tổng các chữ số bằng 3</b>?',
      opts: o4('5 số', '7 số', '10 số', '6 số'), ans: 'D',
      why: 'Chữ số hàng trăm có thể là 1; 2 hoặc 3. Nếu là 1 thì hai chữ số sau có tổng 2: 102; 111; 120 (3 số). Nếu là 2 thì tổng còn 1: 201; 210 (2 số). Nếu là 3 thì hai chữ số sau đều 0: 300 (1 số). Tất cả 3 + 2 + 1 = 6 số.' },
  ],
},

/* ═══════════ ĐỀ 2 — DÃY SỐ VÀ QUY LUẬT ═══════════ */
{
  id: 802, title: 'Đề 2 · Dãy số và quy luật', time: 35,
  questions: [
    { sec: 'Dãy số', name: 'Câu 1', pts: 1.25,
      text: 'Cho dãy số: <b>2; 5; 8; 11; …</b> Số hạng thứ <b>20</b> của dãy là:',
      opts: o4('62', '58', '59', '60'), ans: 'C',
      why: 'Mỗi số hơn số liền trước 3 đơn vị. Từ số hạng thứ nhất đến số hạng thứ 20 phải cộng thêm 19 lần số 3. Vậy số hạng thứ 20 là: 2 + 3 × 19 = 2 + 57 = 59.' },
    { sec: 'Quy luật', name: 'Câu 2', pts: 1.25,
      text: 'Số thích hợp điền tiếp vào dãy: <b>1; 4; 9; 16; 25; …</b>',
      opts: o4('30', '36', '35', '49'), ans: 'B',
      why: 'Các số trong dãy lần lượt là 1 × 1; 2 × 2; 3 × 3; 4 × 4; 5 × 5. Số tiếp theo là 6 × 6 = 36.' },
    { sec: 'Tính tổng', name: 'Câu 3', pts: 1.25,
      text: 'Tính tổng: <b>1 + 2 + 3 + … + 19 + 20</b>',
      opts: o4('200', '190', '220', '210'), ans: 'D',
      why: 'Ghép cặp từ hai đầu: (1 + 20); (2 + 19); (3 + 18); … Mỗi cặp bằng 21 và có 20 : 2 = 10 cặp. Tổng: 21 × 10 = 210.' },
    { sec: 'Đếm số hạng', name: 'Câu 4', pts: 1.25,
      text: 'Dãy số <b>5; 10; 15; …; 100</b> có bao nhiêu số hạng?',
      opts: o4('20 số', '19 số', '21 số', '25 số'), ans: 'A',
      why: 'Hai số liền nhau cách nhau 5 đơn vị. Số số hạng là: (100 − 5) : 5 + 1 = 19 + 1 = 20 (số).' },
    { sec: 'Tính tổng', name: 'Câu 5', pts: 1.25,
      text: 'Tính tổng: <b>2 + 4 + 6 + … + 38 + 40</b>',
      opts: o4('400', '420', '410', '440'), ans: 'B',
      why: 'Dãy có (40 − 2) : 2 + 1 = 20 số hạng. Ghép cặp hai đầu: (2 + 40) = 42, có 10 cặp. Tổng: 42 × 10 = 420.' },
    { sec: 'Quy luật nhân', name: 'Câu 6', pts: 1.25,
      text: 'Cho dãy: <b>1; 2; 4; 8; 16; …</b> Số hạng thứ <b>8</b> của dãy là:',
      opts: o4('128', '64', '256', '96'), ans: 'A',
      why: 'Mỗi số gấp đôi số liền trước: 1; 2; 4; 8; 16; 32; 64; 128. Số hạng thứ 8 là 128.' },
    { sec: 'Quy luật nhân', name: 'Câu 7', pts: 1.25,
      text: 'Cho dãy: <b>3; 6; 12; 24; …</b> Số hạng thứ <b>6</b> của dãy là:',
      opts: o4('48', '72', '96', '120'), ans: 'C',
      why: 'Mỗi số gấp đôi số liền trước: 3; 6; 12; 24; 48; 96. Số hạng thứ 6 là 96.' },
    { sec: 'Dãy số', name: 'Câu 8', pts: 1.25,
      text: 'Cho dãy: <b>1; 3; 6; 10; 15; …</b> Số hạng thứ <b>8</b> của dãy là:',
      opts: o4('28', '32', '45', '36'), ans: 'D',
      why: 'Khoảng cách giữa các số tăng dần: +2; +3; +4; +5; … Viết tiếp: 15 + 6 = 21; 21 + 7 = 28; 28 + 8 = 36. Số hạng thứ 8 là 36.' },
  ],
},

/* ═══════════ ĐỀ 3 — TÍNH NHANH, GIÁ TRỊ BIỂU THỨC ═══════════ */
{
  id: 803, title: 'Đề 3 · Tính nhanh – giá trị biểu thức', time: 35,
  questions: [
    { sec: 'Tính nhanh', name: 'Câu 1', pts: 1.25,
      text: 'Tính nhanh: <b>25 × 4 × 7</b>',
      opts: o4('700', '175', '350', '1 400'), ans: 'A',
      why: 'Nhóm 25 × 4 = 100 trước cho tròn trăm, rồi 100 × 7 = 700.' },
    { sec: 'Tính nhanh', name: 'Câu 2', pts: 1.25,
      text: 'Tính nhanh: <b>125 + 375 + 625 + 875</b>',
      opts: o4('1 900', '2 100', '2 000', '1 800'), ans: 'C',
      why: 'Ghép các cặp cho tròn nghìn: (125 + 875) + (375 + 625) = 1 000 + 1 000 = 2 000.' },
    { sec: 'Tính nhanh', name: 'Câu 3', pts: 1.25,
      text: 'Tính nhanh: <b>24 × 7 + 24 × 3</b>',
      opts: o4('234', '240', '480', '168'), ans: 'B',
      why: 'Cả hai tích đều có thừa số 24 nên đặt 24 ra ngoài: 24 × (7 + 3) = 24 × 10 = 240.' },
    { sec: 'Tính nhanh', name: 'Câu 4', pts: 1.25,
      text: 'Tính nhanh: <b>100 − 99 + 98 − 97 + … + 2 − 1</b>',
      opts: o4('100', '0', '55', '50'), ans: 'D',
      why: 'Ghép từng cặp: (100 − 99) = 1; (98 − 97) = 1; …; (2 − 1) = 1. Có 100 số nên được 50 cặp, mỗi cặp bằng 1. Tổng: 1 × 50 = 50.' },
    { sec: 'Tính nhanh', name: 'Câu 5', pts: 1.25,
      text: 'Tính nhanh: <b>12 × 25</b>',
      opts: o4('250', '360', '300', '275'), ans: 'C',
      why: 'Tách 12 = 3 × 4 rồi nhóm: 3 × (4 × 25) = 3 × 100 = 300.' },
    { sec: 'Tính nhanh', name: 'Câu 6', pts: 1.25,
      text: 'Tính nhanh: <b>45 × 11</b>',
      opts: o4('450', '495', '485', '540'), ans: 'B',
      why: 'Tách 11 = 10 + 1: 45 × 10 + 45 × 1 = 450 + 45 = 495.' },
    { sec: 'Biểu thức', name: 'Câu 7', pts: 1.25,
      text: 'Tính giá trị của biểu thức: <b>(72 − 8 × 9) × 2 026</b>',
      opts: o4('2 026', '1', '64 832', '0'), ans: 'D',
      why: 'Trong ngoặc làm nhân trước: 8 × 9 = 72, rồi 72 − 72 = 0. Số 0 nhân với số nào cũng bằng 0, nên kết quả là 0.' },
    { sec: 'Biểu thức', name: 'Câu 8', pts: 1.25,
      text: 'Tính giá trị của biểu thức: <b>1 000 : 8 : 5</b>',
      opts: o4('25', '40', '125', '625'), ans: 'A',
      why: 'Chỉ có phép chia nên làm từ trái sang phải: 1 000 : 8 = 125; 125 : 5 = 25. (Cũng có thể nhẩm 1 000 : (8 × 5) = 1 000 : 40 = 25.)' },
  ],
},

/* ═══════════ ĐỀ 4 — TÌM THÀNH PHẦN CHƯA BIẾT & TÍNH NGƯỢC ═══════════ */
{
  id: 804, title: 'Đề 4 · Tìm x – tính ngược từ cuối', time: 35,
  questions: [
    { sec: 'Tìm x', name: 'Câu 1', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>x × 8 − 120 = 200</b>',
      opts: o4('x = 10', 'x = 40', 'x = 25', 'x = 400'), ans: 'B',
      why: 'Trước hết x × 8 = 200 + 120 = 320. Sau đó x = 320 : 8 = 40.' },
    { sec: 'Tìm x', name: 'Câu 2', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>(x + 15) : 5 = 12</b>',
      opts: o4('x = 45', 'x = 60', 'x = 75', 'x = 51'), ans: 'A',
      why: 'Ta có x + 15 = 12 × 5 = 60. Vậy x = 60 − 15 = 45.' },
    { sec: 'Tính ngược', name: 'Câu 3', pts: 1.25,
      text: 'Một số nhân với 4 rồi trừ đi 12 thì được 60. Tìm số đó.',
      opts: o4('12', '20', '18', '15'), ans: 'C',
      why: 'Tính ngược từ cuối: 60 + 12 = 72; 72 : 4 = 18. Thử lại: 18 × 4 = 72; 72 − 12 = 60.' },
    { sec: 'Chia có dư', name: 'Câu 4', pts: 1.25,
      text: 'Một số chia cho 6 được thương là 8 và dư 5. Số đó là:',
      opts: o4('48', '58', '43', '53'), ans: 'D',
      why: 'Số bị chia = thương × số chia + số dư = 8 × 6 + 5 = 48 + 5 = 53.' },
    { sec: 'Tính ngược', name: 'Câu 5', pts: 1.25,
      text: 'Tôi nghĩ ra một số, gấp số đó lên 3 lần rồi cộng thêm 15 thì được 60. Hỏi tôi đã nghĩ ra số nào?',
      opts: o4('15', '25', '20', '45'), ans: 'A',
      why: 'Tính ngược: 60 − 15 = 45; 45 : 3 = 15. Thử lại: 15 × 3 = 45; 45 + 15 = 60.' },
    { sec: 'Chia có dư', name: 'Câu 6', pts: 1.25,
      text: 'Tìm <b>x</b>, biết <b>x : 7 = 8 (dư 4)</b>.',
      opts: o4('x = 56', 'x = 64', 'x = 60', 'x = 59'), ans: 'C',
      why: 'x = 8 × 7 + 4 = 56 + 4 = 60. Kiểm tra: 60 : 7 = 8 dư 4 (số dư 4 bé hơn số chia 7).' },
    { sec: 'Tìm x', name: 'Câu 7', pts: 1.25,
      text: 'Tìm <b>x</b>, biết: <b>5 × x + 3 × x = 96</b>',
      opts: o4('x = 8', 'x = 12', 'x = 16', 'x = 24'), ans: 'B',
      why: 'Cả hai số hạng đều có x nên gộp lại: (5 + 3) × x = 8 × x = 96. Vậy x = 96 : 8 = 12.' },
    { sec: 'Suy luận số', name: 'Câu 8', pts: 1.25,
      text: 'Trong một phép chia, số bị chia là 81 và <b>số chia bằng thương</b>. Số chia là:',
      opts: o4('3', '27', '81', '9'), ans: 'D',
      why: 'Gọi số chia là a thì thương cũng là a, nên a × a = 81. Vì 9 × 9 = 81 nên số chia là 9.' },
  ],
},

/* ═══════════ ĐỀ 5 — TOÁN TỔNG – HIỆU ═══════════ */
{
  id: 805, title: 'Đề 5 · Toán tổng – hiệu', time: 35,
  questions: [
    { sec: 'Tổng – hiệu', name: 'Câu 1', pts: 1.25,
      text: 'Hai số có tổng bằng 84 và hiệu bằng 12. Số lớn là:',
      opts: o4('36', '46', '48', '42'), ans: 'C',
      why: 'Số lớn = (tổng + hiệu) : 2 = (84 + 12) : 2 = 96 : 2 = 48. (Số bé là 84 − 48 = 36.)' },
    { sec: 'Tổng – tỉ', name: 'Câu 2', pts: 1.25,
      text: 'Tổng hai số là 100, số lớn gấp 4 lần số bé. Số bé là:',
      opts: o4('25', '20', '80', '30'), ans: 'B',
      why: 'Coi số bé là 1 phần thì số lớn là 4 phần, tổng có 1 + 4 = 5 phần. Số bé: 100 : 5 = 20 (số lớn là 80).' },
    { sec: 'Tổng – hiệu', name: 'Câu 3', pts: 1.25,
      text: 'Hai thùng chứa tất cả 96 l dầu, thùng thứ nhất nhiều hơn thùng thứ hai 16 l. Thùng thứ hai chứa:',
      opts: o4('56 l', '48 l', '32 l', '40 l'), ans: 'D',
      why: 'Thùng thứ hai (số bé) = (96 − 16) : 2 = 80 : 2 = 40 (l). Thùng thứ nhất: 40 + 16 = 56 l; thử lại 40 + 56 = 96 l.' },
    { sec: 'Tuổi', name: 'Câu 4', pts: 1.25,
      text: 'Anh hơn em 6 tuổi, tổng số tuổi của hai anh em là 26 tuổi. Em bao nhiêu tuổi?',
      opts: o4('10 tuổi', '16 tuổi', '13 tuổi', '12 tuổi'), ans: 'A',
      why: 'Tuổi em = (26 − 6) : 2 = 20 : 2 = 10 (tuổi). Tuổi anh: 10 + 6 = 16; thử lại 10 + 16 = 26.' },
    { sec: 'Hình học', name: 'Câu 5', pts: 1.25,
      text: 'Một hình chữ nhật có <b>nửa chu vi</b> 30 cm và chiều dài hơn chiều rộng 8 cm. Diện tích hình chữ nhật đó là:',
      opts: o4('221 cm²', '209 cm²', '200 cm²', '190 cm²'), ans: 'B',
      why: 'Nửa chu vi là tổng chiều dài và chiều rộng. Chiều dài: (30 + 8) : 2 = 19 (cm); chiều rộng: 30 − 19 = 11 (cm). Diện tích: 19 × 11 = 209 (cm²).' },
    { sec: 'Tổng – hiệu', name: 'Câu 6', pts: 1.25,
      text: 'Hai lớp trồng được 120 cây, lớp 3A trồng ít hơn lớp 3B 20 cây. Lớp 3A trồng được:',
      opts: o4('50 cây', '70 cây', '60 cây', '40 cây'), ans: 'A',
      why: 'Lớp 3A (số bé) = (120 − 20) : 2 = 100 : 2 = 50 (cây). Lớp 3B: 50 + 20 = 70 cây.' },
    { sec: 'Suy luận', name: 'Câu 7', pts: 1.25,
      text: 'Tổng hai số là 45. Nếu <b>giảm số lớn đi 5 đơn vị</b> thì hai số bằng nhau. Số lớn là:',
      opts: o4('20', '30', '25', '22'), ans: 'C',
      why: 'Giảm số lớn 5 đơn vị thì bằng số bé, nghĩa là hiệu hai số bằng 5. Số lớn: (45 + 5) : 2 = 25 (số bé là 20).' },
    { sec: 'Hiệu – tỉ', name: 'Câu 8', pts: 1.25,
      text: 'Hiệu hai số bằng 24, số lớn gấp 3 lần số bé. Số bé là:',
      opts: o4('8', '36', '6', '12'), ans: 'D',
      why: 'Coi số bé là 1 phần thì số lớn là 3 phần, hiệu là 3 − 1 = 2 phần. Số bé: 24 : 2 = 12 (số lớn là 36; thử lại 36 − 12 = 24).' },
  ],
},

/* ═══════════ ĐỀ 6 — RÚT VỀ ĐƠN VỊ, GẤP – GIẢM SỐ LẦN ═══════════ */
{
  id: 806, title: 'Đề 6 · Rút về đơn vị – gấp, giảm số lần', time: 35,
  questions: [
    { sec: 'Rút về đơn vị', name: 'Câu 1', pts: 1.25,
      text: '5 hộp bánh như nhau có 40 cái bánh. Hỏi 9 hộp như thế có bao nhiêu cái bánh?',
      opts: o4('72 cái', '80 cái', '45 cái', '64 cái'), ans: 'A',
      why: 'Mỗi hộp có: 40 : 5 = 8 (cái). 9 hộp có: 8 × 9 = 72 (cái bánh).' },
    { sec: 'Rút về đơn vị', name: 'Câu 2', pts: 1.25,
      text: 'Mua 4 quyển vở hết 28 000 đồng. Hỏi mua 7 quyển vở như thế hết bao nhiêu tiền?',
      opts: o4('56 000 đồng', '42 000 đồng', '49 000 đồng', '35 000 đồng'), ans: 'C',
      why: 'Giá một quyển vở: 28 000 : 4 = 7 000 (đồng). Mua 7 quyển hết: 7 000 × 7 = 49 000 (đồng).' },
    { sec: 'Rút về đơn vị', name: 'Câu 3', pts: 1.25,
      text: 'Chia đều 24 kg gạo vào 6 túi. Hỏi 5 túi như thế đựng bao nhiêu ki-lô-gam gạo?',
      opts: o4('24 kg', '20 kg', '18 kg', '30 kg'), ans: 'B',
      why: 'Mỗi túi đựng: 24 : 6 = 4 (kg). 5 túi đựng: 4 × 5 = 20 (kg gạo).' },
    { sec: 'Rút về đơn vị', name: 'Câu 4', pts: 1.25,
      text: 'Có 35 l dầu đựng đều trong 7 can. Hỏi 60 l dầu thì cần bao nhiêu can như thế?',
      opts: o4('10 can', '14 can', '15 can', '12 can'), ans: 'D',
      why: 'Mỗi can đựng: 35 : 7 = 5 (l). Số can cần dùng: 60 : 5 = 12 (can).' },
    { sec: 'Gấp – giảm', name: 'Câu 5', pts: 1.25,
      text: 'Số bé là 8, số lớn gấp 6 lần số bé. Hỏi số lớn hơn số bé bao nhiêu đơn vị?',
      opts: o4('48', '6', '40', '56'), ans: 'C',
      why: 'Số lớn: 8 × 6 = 48. Số lớn hơn số bé: 48 − 8 = 40 (đơn vị).' },
    { sec: 'Gấp – giảm', name: 'Câu 6', pts: 1.25,
      text: 'Giảm số 72 đi 8 lần rồi gấp kết quả lên 5 lần thì được số nào?',
      opts: o4('40', '45', '9', '360'), ans: 'B',
      why: 'Giảm 8 lần là chia cho 8: 72 : 8 = 9. Gấp 5 lần là nhân 5: 9 × 5 = 45.' },
    { sec: 'Toán đố', name: 'Câu 7', pts: 1.25,
      text: 'Một cửa hàng có 3 tấm vải, mỗi tấm dài 45 m. Cửa hàng đã bán <sup>1</sup>⁄<sub>5</sub> tổng số vải đó. Hỏi còn lại bao nhiêu mét vải?',
      opts: o4('27 m', '120 m', '90 m', '108 m'), ans: 'D',
      why: 'Tổng số vải: 45 × 3 = 135 (m). Số vải đã bán: 135 : 5 = 27 (m). Số vải còn lại: 135 − 27 = 108 (m).' },
    { sec: 'Rút về đơn vị', name: 'Câu 8', pts: 1.25,
      text: '9 xe ô tô chở được 63 tấn hàng. Hỏi 15 xe như thế chở được bao nhiêu tấn hàng?',
      opts: o4('105 tấn', '95 tấn', '135 tấn', '120 tấn'), ans: 'A',
      why: 'Mỗi xe chở: 63 : 9 = 7 (tấn). 15 xe chở: 7 × 15 = 105 (tấn hàng).' },
  ],
},

/* ═══════════ ĐỀ 7 — CHIA HẾT VÀ CHIA CÓ DƯ ═══════════ */
{
  id: 807, title: 'Đề 7 · Chia hết và chia có dư', time: 35,
  questions: [
    { sec: 'Chia hết', name: 'Câu 1', pts: 1.25,
      text: 'Số <b>nhỏ nhất có ba chữ số</b> chia hết cho 5 là:',
      opts: o4('105', '100', '110', '115'), ans: 'B',
      why: 'Số nhỏ nhất có ba chữ số là 100, mà 100 : 5 = 20 nên 100 chia hết cho 5.' },
    { sec: 'Chia hết', name: 'Câu 2', pts: 1.25,
      text: 'Trong các số <b>45; 52; 70; 38</b>, số nào chia hết cho 9?',
      opts: o4('45', '52', '70', '38'), ans: 'A',
      why: '45 : 9 = 5 nên 45 chia hết cho 9. Các số còn lại chia cho 9 đều còn dư (52 : 9 dư 7; 70 : 9 dư 7; 38 : 9 dư 2).' },
    { sec: 'Chia có dư', name: 'Câu 3', pts: 1.25,
      text: 'Trong một phép chia cho 7, số dư <b>lớn nhất</b> có thể là:',
      opts: o4('7', '5', '6', '1'), ans: 'C',
      why: 'Số dư luôn bé hơn số chia. Số bé hơn 7 và lớn nhất là 6.' },
    { sec: 'Đếm số', name: 'Câu 4', pts: 1.25,
      text: 'Có bao nhiêu số có <b>hai chữ số</b> chia hết cho 6?',
      opts: o4('16 số', '14 số', '12 số', '15 số'), ans: 'D',
      why: 'Số bé nhất là 12, lớn nhất là 96. Các số cách nhau 6 đơn vị nên có (96 − 12) : 6 + 1 = 14 + 1 = 15 (số).' },
    { sec: 'Suy luận', name: 'Câu 5', pts: 1.25,
      text: 'Hôm nay là thứ Ba. Hỏi <b>100 ngày</b> nữa là thứ mấy?',
      opts: o4('Thứ Năm', 'Thứ Tư', 'Thứ Sáu', 'Thứ Ba'), ans: 'A',
      why: 'Cứ 7 ngày lại lặp lại thứ cũ. Ta có 100 : 7 = 14 (dư 2), nghĩa là sau 98 ngày vẫn là thứ Ba, rồi thêm 2 ngày nữa là thứ Năm.' },
    { sec: 'Chia có dư', name: 'Câu 6', pts: 1.25,
      text: 'Số <b>nhỏ nhất có hai chữ số</b> mà chia cho 5 dư 3 và chia cho 2 dư 1 là:',
      opts: o4('23', '18', '13', '33'), ans: 'C',
      why: 'Chia 5 dư 3 nên số đó tận cùng là 3 hoặc 8. Chia 2 dư 1 nên số đó lẻ, vậy tận cùng là 3. Số nhỏ nhất có hai chữ số như thế là 13 (13 : 5 = 2 dư 3; 13 : 2 = 6 dư 1).' },
    { sec: 'Điền chữ số', name: 'Câu 7', pts: 1.25,
      text: 'Thay dấu <b>*</b> bằng chữ số thích hợp để số <b>201*</b> chia hết cho <b>cả 2 và 5</b>:',
      opts: o4('* = 5', '* = 0', '* = 2', '* = 4'), ans: 'B',
      why: 'Số chia hết cho 2 phải tận cùng là chữ số chẵn; chia hết cho 5 phải tận cùng là 0 hoặc 5. Vừa chẵn vừa là 0 hoặc 5 thì chỉ có 0. Số đó là 2 010.' },
    { sec: 'Toán đố', name: 'Câu 8', pts: 1.25,
      text: 'Có 100 quả trứng xếp vào các khay, mỗi khay 6 quả. Hỏi cần ít nhất bao nhiêu khay để xếp hết số trứng đó?',
      opts: o4('16 khay', '18 khay', '15 khay', '17 khay'), ans: 'D',
      why: '100 : 6 = 16 (dư 4). Xếp đầy 16 khay thì còn 4 quả, phải dùng thêm 1 khay nữa. Vậy cần ít nhất 16 + 1 = 17 khay.' },
  ],
},

/* ═══════════ ĐỀ 8 — TOÁN TRỒNG CÂY, ĐẾM ĐOẠN, ĐẾM CHỮ SỐ ═══════════ */
{
  id: 808, title: 'Đề 8 · Trồng cây – đếm đoạn – đếm chữ số', time: 35,
  questions: [
    { sec: 'Trồng cây', name: 'Câu 1', pts: 1.25,
      text: 'Người ta trồng cây dọc một con đường dài 100 m, cứ cách 5 m trồng một cây và trồng ở <b>cả hai đầu đường</b>. Hỏi trồng được bao nhiêu cây?',
      opts: o4('20 cây', '19 cây', '21 cây', '22 cây'), ans: 'C',
      why: 'Số khoảng cách: 100 : 5 = 20 (khoảng). Vì trồng ở cả hai đầu nên số cây nhiều hơn số khoảng 1: 20 + 1 = 21 (cây).' },
    { sec: 'Cưa gỗ', name: 'Câu 2', pts: 1.25,
      text: 'Bác thợ cưa một khúc gỗ thành 8 đoạn, mỗi lần cưa hết 5 phút. Hỏi bác cưa xong khúc gỗ đó hết bao nhiêu phút?',
      opts: o4('40 phút', '35 phút', '45 phút', '30 phút'), ans: 'B',
      why: 'Muốn được 8 đoạn thì chỉ cần cưa 8 − 1 = 7 (lần). Thời gian: 5 × 7 = 35 (phút).' },
    { sec: 'Trồng cây', name: 'Câu 3', pts: 1.25,
      text: 'Trồng cây xung quanh một cái ao hình tròn có chu vi 60 m, cứ cách 4 m trồng một cây. Hỏi trồng được bao nhiêu cây?',
      opts: o4('16 cây', '14 cây', '17 cây', '15 cây'), ans: 'D',
      why: 'Vì đường khép kín (đi vòng quanh ao) nên số cây đúng bằng số khoảng: 60 : 4 = 15 (cây).' },
    { sec: 'Đếm đoạn thẳng', name: 'Câu 4', pts: 1.25,
      text: 'Trên một đường thẳng lấy 5 điểm phân biệt. Hỏi có tất cả bao nhiêu đoạn thẳng?',
      opts: o4('10 đoạn', '5 đoạn', '4 đoạn', '20 đoạn'), ans: 'A',
      why: 'Từ điểm thứ nhất nối được 4 đoạn, điểm thứ hai nối thêm 3 đoạn mới, tiếp theo là 2 và 1. Tổng: 4 + 3 + 2 + 1 = 10 (đoạn thẳng).' },
    { sec: 'Trồng cây', name: 'Câu 5', pts: 1.25,
      text: 'Đóng cọc rào một đoạn thẳng dài 24 m, cứ cách 3 m đóng một cọc và đóng cả ở hai đầu. Hỏi cần bao nhiêu cọc?',
      opts: o4('8 cọc', '9 cọc', '10 cọc', '7 cọc'), ans: 'B',
      why: 'Số khoảng: 24 : 3 = 8. Đóng cả hai đầu nên số cọc là 8 + 1 = 9 (cọc).' },
    { sec: 'Suy luận', name: 'Câu 6', pts: 1.25,
      text: 'Từ tầng 1 lên tầng 3 của một toà nhà, bạn Nam đi hết 30 giây. Hỏi bạn Nam đi từ tầng 1 lên tầng 6 hết bao nhiêu giây (đi đều)?',
      opts: o4('75 giây', '90 giây', '60 giây', '100 giây'), ans: 'A',
      why: 'Từ tầng 1 lên tầng 3 phải đi qua 2 tầng cầu thang, nên mỗi tầng hết 30 : 2 = 15 (giây). Từ tầng 1 lên tầng 6 phải đi 5 tầng cầu thang: 15 × 5 = 75 (giây).' },
    { sec: 'Đếm chữ số', name: 'Câu 7', pts: 1.25,
      text: 'Một quyển sách được đánh số trang từ 1 đến 60. Hỏi phải dùng tất cả bao nhiêu <b>chữ số</b>?',
      opts: o4('120 chữ số', '102 chữ số', '111 chữ số', '60 chữ số'), ans: 'C',
      why: 'Từ trang 1 đến 9 có 9 trang, mỗi trang 1 chữ số: 9 chữ số. Từ trang 10 đến 60 có 51 trang, mỗi trang 2 chữ số: 51 × 2 = 102 chữ số. Tổng: 9 + 102 = 111 (chữ số).' },
    { sec: 'Đếm cách chọn', name: 'Câu 8', pts: 1.25,
      text: 'Trong một buổi gặp mặt có 10 người, mỗi người đều bắt tay với tất cả những người còn lại đúng một lần. Hỏi có bao nhiêu cái bắt tay?',
      opts: o4('90 cái', '100 cái', '50 cái', '45 cái'), ans: 'D',
      why: 'Người thứ nhất bắt tay 9 người, người thứ hai bắt thêm 8 cái mới, … lần lượt 7; 6; …; 1. Tổng: 9 + 8 + 7 + … + 1 = 45 (cái bắt tay).' },
  ],
},

/* ═══════════ ĐỀ 9 — CHU VI VÀ DIỆN TÍCH ═══════════ */
{
  id: 809, title: 'Đề 9 · Chu vi và diện tích', time: 35,
  questions: [
    { sec: 'Hình học', name: 'Câu 1', pts: 1.25,
      text: 'Một hình chữ nhật có chu vi 36 cm và chiều dài gấp 2 lần chiều rộng. Diện tích hình chữ nhật đó là:',
      opts: o4('72 cm²', '36 cm²', '81 cm²', '48 cm²'), ans: 'A',
      why: 'Nửa chu vi: 36 : 2 = 18 (cm) — là tổng chiều dài và chiều rộng. Coi chiều rộng 1 phần thì chiều dài 2 phần, tổng 3 phần. Chiều rộng: 18 : 3 = 6 (cm); chiều dài 12 cm. Diện tích: 12 × 6 = 72 (cm²).' },
    { sec: 'Hình học', name: 'Câu 2', pts: 1.25,
      text: 'Một hình vuông có diện tích 64 cm². Chu vi hình vuông đó là:',
      opts: o4('16 cm', '64 cm', '32 cm', '256 cm'), ans: 'C',
      why: 'Vì 8 × 8 = 64 nên cạnh hình vuông là 8 cm. Chu vi: 8 × 4 = 32 (cm).' },
    { sec: 'Hình học', name: 'Câu 3', pts: 1.25,
      text: 'Một mảnh đất hình chữ nhật dài 30 m, rộng 20 m. Người ta mở rộng thêm chiều rộng 5 m (giữ nguyên chiều dài). Hỏi diện tích mảnh đất <b>tăng thêm</b> bao nhiêu mét vuông?',
      opts: o4('100 m²', '150 m²', '750 m²', '50 m²'), ans: 'B',
      why: 'Phần đất tăng thêm là một hình chữ nhật có chiều dài 30 m và chiều rộng 5 m. Diện tích tăng thêm: 30 × 5 = 150 (m²).' },
    { sec: 'Ghép hình', name: 'Câu 4', pts: 1.25,
      text: 'Ghép hai hình vuông có cạnh 5 cm lại thành một hình chữ nhật. Chu vi hình chữ nhật đó là:',
      opts: o4('40 cm', '20 cm', '50 cm', '30 cm'), ans: 'D',
      why: 'Hình chữ nhật ghép được có chiều dài 5 + 5 = 10 (cm) và chiều rộng 5 cm. Chu vi: (10 + 5) × 2 = 30 (cm).' },
    { sec: 'Hình học', name: 'Câu 5', pts: 1.25,
      text: 'Một hình chữ nhật có diện tích 60 cm² và chiều rộng 5 cm. Chu vi hình chữ nhật đó là:',
      opts: o4('30 cm', '17 cm', '34 cm', '24 cm'), ans: 'C',
      why: 'Chiều dài: 60 : 5 = 12 (cm). Chu vi: (12 + 5) × 2 = 34 (cm).' },
    { sec: 'Hình học', name: 'Câu 6', pts: 1.25,
      text: 'Một hình vuông có chu vi bằng chu vi của hình chữ nhật dài 10 cm và rộng 6 cm. Diện tích hình vuông đó là:',
      opts: o4('60 cm²', '64 cm²', '32 cm²', '100 cm²'), ans: 'B',
      why: 'Chu vi hình chữ nhật: (10 + 6) × 2 = 32 (cm). Cạnh hình vuông: 32 : 4 = 8 (cm). Diện tích: 8 × 8 = 64 (cm²).' },
    { sec: 'Suy luận hình', name: 'Câu 7', pts: 1.25,
      text: 'Nếu <b>gấp chiều dài lên 2 lần</b> và giữ nguyên chiều rộng thì diện tích hình chữ nhật thay đổi thế nào?',
      opts: o4('Gấp lên 4 lần', 'Không đổi', 'Giảm đi 2 lần', 'Gấp lên 2 lần'), ans: 'D',
      why: 'Diện tích = dài × rộng. Chiều dài gấp 2 lần, chiều rộng giữ nguyên nên tích cũng gấp 2 lần.' },
    { sec: 'Cắt hình', name: 'Câu 8', pts: 1.25,
      text: 'Cắt một miếng bìa hình chữ nhật dài 12 cm, rộng 8 cm thành các hình vuông cạnh 4 cm. Hỏi cắt được bao nhiêu hình vuông?',
      opts: o4('6 hình', '8 hình', '4 hình', '12 hình'), ans: 'A',
      why: 'Theo chiều dài cắt được 12 : 4 = 3 (hàng ô), theo chiều rộng cắt được 8 : 4 = 2 (cột ô). Tất cả: 3 × 2 = 6 (hình vuông). Kiểm tra bằng diện tích: 96 : 16 = 6.' },
  ],
},

/* ═══════════ ĐỀ 10 — ĐẾM HÌNH VÀ CẮT GHÉP HÌNH ═══════════ */
{
  id: 810, title: 'Đề 10 · Đếm hình – cắt ghép hình', time: 35,
  questions: [
    { sec: 'Đếm hình', name: 'Câu 1', pts: 1.25,
      text: 'Từ đỉnh A của tam giác ABC, người ta kẻ <b>2 đoạn thẳng</b> xuống cạnh BC, chia tam giác thành 3 tam giác nhỏ. Hỏi trên hình có tất cả bao nhiêu hình tam giác?',
      opts: o4('3 hình', '6 hình', '4 hình', '5 hình'), ans: 'B',
      why: 'Có 3 tam giác nhỏ; ghép 2 tam giác nhỏ liền nhau được 2 tam giác; ghép cả 3 được tam giác lớn ABC. Tất cả: 3 + 2 + 1 = 6 (hình tam giác).' },
    { sec: 'Đếm hình', name: 'Câu 2', pts: 1.25,
      text: 'Một hình chữ nhật được chia bởi <b>2 đoạn thẳng thẳng đứng</b> thành 3 phần. Hỏi trên hình có bao nhiêu hình chữ nhật?',
      opts: o4('6 hình', '3 hình', '4 hình', '9 hình'), ans: 'A',
      why: 'Có 3 hình chữ nhật nhỏ; ghép 2 hình liền nhau được 2 hình; ghép cả 3 được 1 hình lớn. Tất cả: 3 + 2 + 1 = 6 (hình chữ nhật).' },
    { sec: 'Đếm hình', name: 'Câu 3', pts: 1.25,
      text: 'Một hình chữ nhật được chia bởi 1 đoạn thẳng dọc và 1 đoạn thẳng ngang thành 4 ô. Hỏi có tất cả bao nhiêu hình chữ nhật?',
      opts: o4('4 hình', '6 hình', '9 hình', '8 hình'), ans: 'C',
      why: 'Theo chiều ngang có 3 cách chọn khoảng (2 ô nhỏ và 1 ô ghép), theo chiều dọc cũng có 3 cách. Tất cả: 3 × 3 = 9 (hình chữ nhật).' },
    { sec: 'Đếm đoạn thẳng', name: 'Câu 4', pts: 1.25,
      text: 'Trên một đường thẳng lấy 6 điểm phân biệt. Có tất cả bao nhiêu đoạn thẳng?',
      opts: o4('12 đoạn', '10 đoạn', '20 đoạn', '15 đoạn'), ans: 'D',
      why: 'Tổng số đoạn: 5 + 4 + 3 + 2 + 1 = 15 (đoạn thẳng).' },
    { sec: 'Đếm hình', name: 'Câu 5', pts: 1.25,
      text: 'Một hình vuông lớn được chia thành lưới <b>3 × 3</b> ô vuông nhỏ bằng nhau. Hỏi có tất cả bao nhiêu hình vuông trên hình?',
      opts: o4('14 hình', '9 hình', '10 hình', '13 hình'), ans: 'A',
      why: 'Hình vuông cỡ 1 ô: 9 hình. Cỡ 2 × 2 ô: 4 hình. Cỡ 3 × 3 ô (cả hình lớn): 1 hình. Tất cả: 9 + 4 + 1 = 14 (hình vuông).' },
    { sec: 'Đếm hình', name: 'Câu 6', pts: 1.25,
      text: 'Một hình vuông lớn được chia thành lưới <b>4 × 4</b> ô vuông nhỏ bằng nhau. Hỏi có tất cả bao nhiêu hình vuông?',
      opts: o4('16 hình', '25 hình', '30 hình', '20 hình'), ans: 'C',
      why: 'Cỡ 1 ô: 16 hình; cỡ 2 × 2: 9 hình; cỡ 3 × 3: 4 hình; cỡ 4 × 4: 1 hình. Tất cả: 16 + 9 + 4 + 1 = 30 (hình vuông).' },
    { sec: 'Đếm hình', name: 'Câu 7', pts: 1.25,
      text: 'Một hình chữ nhật được chia thành lưới <b>2 hàng × 3 cột</b> ô vuông nhỏ. Hỏi có tất cả bao nhiêu hình chữ nhật (kể cả hình vuông)?',
      opts: o4('12 hình', '18 hình', '9 hình', '6 hình'), ans: 'B',
      why: 'Theo chiều ngang (3 cột) có 3 + 2 + 1 = 6 cách chọn; theo chiều dọc (2 hàng) có 2 + 1 = 3 cách chọn. Tất cả: 6 × 3 = 18 (hình chữ nhật).' },
    { sec: 'Xếp que diêm', name: 'Câu 8', pts: 1.25,
      text: 'Cần ít nhất bao nhiêu que diêm bằng nhau để xếp thành một hình vuông lớn được chia thành <b>4 ô vuông nhỏ</b> (lưới 2 × 2)?',
      opts: o4('16 que', '10 que', '8 que', '12 que'), ans: 'D',
      why: 'Lưới 2 × 2 gồm 3 đường ngang và 3 đường dọc, mỗi đường dài 2 que. Số que: (3 + 3) × 2 = 12 (que). Xếp riêng 4 hình vuông thì mất 16 que, dùng chung cạnh nên tiết kiệm được 4 que.' },
  ],
},

/* ═══════════ ĐỀ 11 — THỜI GIAN VÀ LỊCH ═══════════ */
{
  id: 811, title: 'Đề 11 · Thời gian và lịch', time: 35,
  questions: [
    { sec: 'Thời gian', name: 'Câu 1', pts: 1.25,
      text: 'Từ 7 giờ 45 phút đến 10 giờ 20 phút là bao lâu?',
      opts: o4('3 giờ 25 phút', '2 giờ 25 phút', '2 giờ 35 phút', '3 giờ 35 phút'), ans: 'C',
      why: 'Từ 7 giờ 45 phút đến 10 giờ 45 phút là 3 giờ, nhưng ta chỉ tính đến 10 giờ 20 phút, tức là sớm hơn 25 phút. Vậy thời gian là 3 giờ − 25 phút = 2 giờ 35 phút.' },
    { sec: 'Lịch', name: 'Câu 2', pts: 1.25,
      text: 'Ngày 1 tháng 3 là thứ Tư. Hỏi ngày 29 tháng 3 là thứ mấy?',
      opts: o4('Thứ Năm', 'Thứ Tư', 'Thứ Ba', 'Thứ Hai'), ans: 'B',
      why: 'Từ ngày 1 đến ngày 29 cách nhau 28 ngày, đúng bằng 4 tuần lễ. Vì vậy ngày 29 tháng 3 cũng là thứ Tư.' },
    { sec: 'Lịch', name: 'Câu 3', pts: 1.25,
      text: 'Tháng 3 có 31 ngày. Nếu ngày 1 tháng 3 là Chủ nhật thì tháng đó có bao nhiêu ngày Chủ nhật?',
      opts: o4('4 ngày', '6 ngày', '3 ngày', '5 ngày'), ans: 'D',
      why: 'Các ngày Chủ nhật là 1; 8; 15; 22; 29 (cách nhau 7 ngày, đều không quá 31). Vậy tháng đó có 5 ngày Chủ nhật.' },
    { sec: 'Lịch', name: 'Câu 4', pts: 1.25,
      text: 'Một năm không nhuận có 365 ngày. Năm đó gồm bao nhiêu tuần lễ và mấy ngày lẻ?',
      opts: o4('52 tuần và 1 ngày', '52 tuần và 2 ngày', '53 tuần', '51 tuần và 6 ngày'), ans: 'A',
      why: 'Ta có 365 : 7 = 52 (dư 1). Vậy một năm không nhuận có 52 tuần lễ và 1 ngày.' },
    { sec: 'Thời gian', name: 'Câu 5', pts: 1.25,
      text: 'Từ 10 giờ 30 phút đêm hôm trước đến 6 giờ sáng hôm sau là bao lâu?',
      opts: o4('8 giờ 30 phút', '7 giờ 30 phút', '6 giờ 30 phút', '4 giờ 30 phút'), ans: 'B',
      why: 'Từ 10 giờ 30 phút đêm đến 12 giờ đêm là 1 giờ 30 phút; từ 12 giờ đêm đến 6 giờ sáng là 6 giờ. Tổng: 1 giờ 30 phút + 6 giờ = 7 giờ 30 phút.' },
    { sec: 'Đồng hồ', name: 'Câu 6', pts: 1.25,
      text: 'Kim phút quay đúng <b>một vòng</b> trên mặt đồng hồ thì hết bao lâu?',
      opts: o4('60 phút', '12 giờ', '30 phút', '24 giờ'), ans: 'A',
      why: 'Kim phút quay hết một vòng là 60 phút, tức 1 giờ. (Kim giờ quay hết một vòng mới mất 12 giờ.)' },
    { sec: 'Lịch', name: 'Câu 7', pts: 1.25,
      text: 'Ngày 28 tháng 2 (năm không nhuận) là thứ Sáu. Hỏi ngày 8 tháng 3 là thứ mấy?',
      opts: o4('Chủ nhật', 'Thứ Sáu', 'Thứ Bảy', 'Thứ Hai'), ans: 'C',
      why: 'Năm không nhuận, tháng 2 có 28 ngày nên ngày 1 tháng 3 là thứ Bảy. Từ ngày 1 đến ngày 8 cách nhau 7 ngày, đúng 1 tuần, nên ngày 8 tháng 3 cũng là thứ Bảy.' },
    { sec: 'Thời gian', name: 'Câu 8', pts: 1.25,
      text: 'Một chương trình ca nhạc bắt đầu lúc 20 giờ 15 phút và kết thúc lúc 21 giờ 50 phút. Chương trình kéo dài bao lâu?',
      opts: o4('1 giờ 45 phút', '2 giờ 5 phút', '1 giờ 25 phút', '1 giờ 35 phút'), ans: 'D',
      why: 'Từ 20 giờ 15 phút đến 21 giờ 15 phút là 1 giờ; từ 21 giờ 15 phút đến 21 giờ 50 phút là 35 phút. Tổng: 1 giờ 35 phút.' },
  ],
},

/* ═══════════ ĐỀ 12 — SUY LUẬN LOGIC ═══════════ */
{
  id: 812, title: 'Đề 12 · Suy luận logic', time: 35,
  questions: [
    { sec: 'Suy luận', name: 'Câu 1', pts: 1.25,
      text: 'Ba bạn An, Bình, Cường mỗi bạn cầm một quả bóng màu đỏ, xanh hoặc vàng (không trùng nhau). Biết An <b>không</b> cầm bóng đỏ và <b>không</b> cầm bóng xanh; Bình <b>không</b> cầm bóng xanh. Hỏi Cường cầm bóng màu gì?',
      opts: o4('Màu xanh', 'Màu đỏ', 'Màu vàng', 'Không xác định được'), ans: 'A',
      why: 'An không cầm đỏ, không cầm xanh nên An cầm bóng vàng. Bình không cầm xanh, cũng không thể cầm vàng (An cầm rồi) nên Bình cầm bóng đỏ. Còn lại, Cường cầm bóng xanh.' },
    { sec: 'Sắp thứ tự', name: 'Câu 2', pts: 1.25,
      text: 'Bốn bạn xếp thành một hàng dọc. Nam đứng trước Bắc, Bắc đứng trước Đông, Đông đứng trước Tây. Hỏi ai đứng <b>cuối hàng</b>?',
      opts: o4('Nam', 'Đông', 'Tây', 'Bắc'), ans: 'C',
      why: 'Thứ tự từ đầu đến cuối là Nam — Bắc — Đông — Tây. Vậy bạn Tây đứng cuối hàng.' },
    { sec: 'Nguyên lí ngăn kéo', name: 'Câu 3', pts: 1.25,
      text: 'Trong hộp có 5 viên bi đỏ và 4 viên bi xanh. Không nhìn vào hộp, phải lấy ra <b>ít nhất</b> bao nhiêu viên để chắc chắn có 2 viên <b>cùng màu</b>?',
      opts: o4('2 viên', '3 viên', '5 viên', '6 viên'), ans: 'B',
      why: 'Nếu lấy 2 viên có thể được 1 đỏ và 1 xanh (khác màu). Nhưng lấy 3 viên thì chỉ có 2 màu nên bắt buộc có ít nhất 2 viên cùng màu. Vậy ít nhất 3 viên.' },
    { sec: 'Nguyên lí ngăn kéo', name: 'Câu 4', pts: 1.25,
      text: 'Vẫn hộp có 5 viên bi đỏ và 4 viên bi xanh. Phải lấy ra <b>ít nhất</b> bao nhiêu viên để chắc chắn có 1 viên bi <b>xanh</b>?',
      opts: o4('5 viên', '2 viên', '9 viên', '6 viên'), ans: 'D',
      why: 'Trường hợp xấu nhất là lấy phải cả 5 viên bi đỏ trước. Khi đó viên thứ 6 chắc chắn là bi xanh. Vậy ít nhất 6 viên.' },
    { sec: 'Cân bằng', name: 'Câu 5', pts: 1.25,
      text: 'Trên một cân thăng bằng: <b>3 quả táo</b> nặng bằng <b>2 quả cam</b>. Biết mỗi quả cam nặng 300 g. Hỏi mỗi quả táo nặng bao nhiêu gam?',
      opts: o4('450 g', '150 g', '200 g', '100 g'), ans: 'C',
      why: '2 quả cam nặng: 300 × 2 = 600 (g), cũng chính là cân nặng của 3 quả táo. Mỗi quả táo nặng: 600 : 3 = 200 (g).' },
    { sec: 'Suy luận', name: 'Câu 6', pts: 1.25,
      text: 'Ba bạn Nam, Bắc, Trung thi chạy, không có ai bằng nhau. Biết Nam <b>không</b> về nhất và <b>không</b> về cuối; Bắc <b>không</b> về nhất. Hỏi ai về nhất?',
      opts: o4('Bắc', 'Trung', 'Nam', 'Không xác định được'), ans: 'B',
      why: 'Nam không nhất, Bắc không nhất, nên người về nhất chỉ có thể là Trung. (Khi đó Nam về nhì và Bắc về cuối.)' },
    { sec: 'Suy luận', name: 'Câu 7', pts: 1.25,
      text: 'Mai có nhiều hơn Lan 3 cái kẹo. Nếu Mai cho Lan 2 cái kẹo thì lúc đó ai nhiều kẹo hơn và nhiều hơn mấy cái?',
      opts: o4('Mai nhiều hơn Lan 1 cái', 'Hai bạn bằng nhau', 'Mai nhiều hơn Lan 5 cái', 'Lan nhiều hơn Mai 1 cái'), ans: 'D',
      why: 'Mai cho đi 2 cái nên Mai bớt 2, Lan thêm 2 — khoảng cách giữa hai bạn giảm đi 2 + 2 = 4 (cái). Ban đầu Mai hơn Lan 3 cái, mà khoảng cách giảm tới 4 cái, nên bây giờ Lan lại nhiều hơn Mai 4 − 3 = 1 (cái). Ví dụ: Mai 10, Lan 7 → sau khi cho: Mai 8, Lan 9.' },
    { sec: 'Giả thiết tạm', name: 'Câu 8', pts: 1.25,
      text: 'Trong sân có tất cả 10 con vừa gà vừa chó, đếm được 28 cái chân. Hỏi có bao nhiêu con gà?',
      opts: o4('6 con', '4 con', '5 con', '7 con'), ans: 'A',
      why: 'Giả sử cả 10 con đều là gà thì có 2 × 10 = 20 (chân), thiếu 28 − 20 = 8 (chân). Mỗi lần đổi 1 con gà thành 1 con chó thì số chân tăng 2, nên số chó là 8 : 2 = 4 (con). Số gà: 10 − 4 = 6 (con).' },
  ],
},

/* ═══════════ ĐỀ 13 — TỔ HỢP VÀ ĐẾM CÁCH CHỌN ═══════════ */
{
  id: 813, title: 'Đề 13 · Tổ hợp – đếm cách chọn', time: 35,
  questions: [
    { sec: 'Đếm cách chọn', name: 'Câu 1', pts: 1.25,
      text: 'Bạn Lan có 3 chiếc áo và 4 chiếc quần khác nhau. Hỏi Lan có bao nhiêu cách chọn một bộ gồm 1 áo và 1 quần?',
      opts: o4('7 cách', '12 cách', '9 cách', '16 cách'), ans: 'B',
      why: 'Mỗi chiếc áo đều ghép được với 4 chiếc quần. Số cách: 3 × 4 = 12 (cách).' },
    { sec: 'Lập số', name: 'Câu 2', pts: 1.25,
      text: 'Từ ba chữ số <b>1; 2; 3</b> viết được bao nhiêu số có hai chữ số <b>khác nhau</b>?',
      opts: o4('6 số', '9 số', '3 số', '12 số'), ans: 'A',
      why: 'Chữ số hàng chục có 3 cách chọn, hàng đơn vị còn 2 cách. Số các số: 3 × 2 = 6 (đó là 12; 13; 21; 23; 31; 32).' },
    { sec: 'Đếm cách chọn', name: 'Câu 3', pts: 1.25,
      text: 'Lớp có 5 bạn, cần chọn 2 bạn đi trực nhật. Hỏi có bao nhiêu cách chọn?',
      opts: o4('20 cách', '25 cách', '10 cách', '7 cách'), ans: 'C',
      why: 'Bạn thứ nhất ghép được với 4 bạn còn lại, bạn thứ hai ghép thêm 3 cặp mới, tiếp theo 2 và 1. Tổng: 4 + 3 + 2 + 1 = 10 (cách).' },
    { sec: 'Đếm đường đi', name: 'Câu 4', pts: 1.25,
      text: 'Từ A đến B có 3 con đường, từ B đến C có 2 con đường. Hỏi có bao nhiêu cách đi từ A đến C (phải đi qua B)?',
      opts: o4('5 cách', '3 cách', '8 cách', '6 cách'), ans: 'D',
      why: 'Mỗi con đường từ A đến B đều ghép được với 2 con đường từ B đến C. Số cách: 3 × 2 = 6 (cách).' },
    { sec: 'Đếm cách tô', name: 'Câu 5', pts: 1.25,
      text: 'Có 4 màu bút. Tô 2 hình khác nhau, mỗi hình một màu và hai hình <b>khác màu</b> nhau. Có bao nhiêu cách tô?',
      opts: o4('12 cách', '16 cách', '8 cách', '6 cách'), ans: 'A',
      why: 'Hình thứ nhất có 4 cách chọn màu, hình thứ hai chỉ còn 3 màu khác. Số cách: 4 × 3 = 12 (cách).' },
    { sec: 'Khả năng xảy ra', name: 'Câu 6', pts: 1.25,
      text: 'Tung một đồng xu hai lần liên tiếp. Có bao nhiêu kết quả có thể xảy ra?',
      opts: o4('2 kết quả', '3 kết quả', '4 kết quả', '6 kết quả'), ans: 'C',
      why: 'Mỗi lần tung có 2 khả năng (sấp hoặc ngửa). Hai lần tung có: 2 × 2 = 4 (kết quả) là SS; SN; NS; NN.' },
    { sec: 'Xếp thứ tự', name: 'Câu 7', pts: 1.25,
      text: 'Xếp ba bạn A, B, C thành một hàng dọc. Có bao nhiêu cách xếp?',
      opts: o4('3 cách', '6 cách', '9 cách', '12 cách'), ans: 'B',
      why: 'Vị trí đầu có 3 cách chọn, vị trí giữa còn 2 cách, vị trí cuối còn 1 cách. Tất cả: 3 × 2 × 1 = 6 (cách).' },
    { sec: 'Lập số', name: 'Câu 8', pts: 1.25,
      text: 'Từ ba chữ số <b>0; 1; 2</b> viết được bao nhiêu số có ba chữ số <b>khác nhau</b>?',
      opts: o4('6 số', '3 số', '9 số', '4 số'), ans: 'D',
      why: 'Chữ số hàng trăm không được là 0 nên chỉ có 2 cách (1 hoặc 2); hai hàng còn lại có 2 × 1 = 2 cách. Tất cả: 2 × 2 = 4 số, đó là 102; 120; 201; 210.' },
  ],
},

/* ═══════════ ĐỀ 14 — TOÁN TUỔI VÀ TOÁN THỰC TẾ ═══════════ */
{
  id: 814, title: 'Đề 14 · Toán tuổi – toán thực tế', time: 35,
  questions: [
    { sec: 'Tuổi', name: 'Câu 1', pts: 1.25,
      text: 'Năm nay mẹ 32 tuổi, con 8 tuổi. Hỏi sau bao nhiêu năm nữa thì tuổi mẹ gấp 3 lần tuổi con?',
      opts: o4('2 năm', '6 năm', '4 năm', '8 năm'), ans: 'C',
      why: 'Mẹ luôn hơn con 32 − 8 = 24 (tuổi). Khi tuổi mẹ gấp 3 lần tuổi con thì phần hơn 24 tuổi ứng với 3 − 1 = 2 lần tuổi con, nên lúc đó con 24 : 2 = 12 (tuổi). Vậy sau 12 − 8 = 4 (năm).' },
    { sec: 'Tuổi', name: 'Câu 2', pts: 1.25,
      text: 'Bố hơn con 30 tuổi và tuổi bố gấp 4 lần tuổi con. Hỏi con bao nhiêu tuổi?',
      opts: o4('8 tuổi', '10 tuổi', '12 tuổi', '15 tuổi'), ans: 'B',
      why: 'Coi tuổi con là 1 phần thì tuổi bố là 4 phần, hiệu là 3 phần ứng với 30 tuổi. Tuổi con: 30 : 3 = 10 (tuổi); tuổi bố 40 tuổi.' },
    { sec: 'Tuổi', name: 'Câu 3', pts: 1.25,
      text: 'Hiện nay anh 15 tuổi, em 9 tuổi. Hỏi cách đây mấy năm tuổi anh gấp 3 lần tuổi em?',
      opts: o4('3 năm', '4 năm', '5 năm', '6 năm'), ans: 'D',
      why: 'Anh luôn hơn em 15 − 9 = 6 (tuổi). Khi tuổi anh gấp 3 lần tuổi em thì hiệu 6 tuổi ứng với 3 − 1 = 2 lần tuổi em, nên lúc đó em 6 : 2 = 3 (tuổi). Vậy cách đây 9 − 3 = 6 (năm).' },
    { sec: 'Tuổi', name: 'Câu 4', pts: 1.25,
      text: 'Tổng số tuổi của hai chị em là 30 tuổi, chị hơn em 4 tuổi. Chị bao nhiêu tuổi?',
      opts: o4('17 tuổi', '13 tuổi', '16 tuổi', '18 tuổi'), ans: 'A',
      why: 'Tuổi chị = (30 + 4) : 2 = 34 : 2 = 17 (tuổi). Tuổi em: 30 − 17 = 13 tuổi.' },
    { sec: 'Tuổi', name: 'Câu 5', pts: 1.25,
      text: 'Năm nay Lan 9 tuổi, mẹ 33 tuổi. Hỏi trước đây mấy năm tuổi mẹ gấp 5 lần tuổi Lan?',
      opts: o4('4 năm', '3 năm', '6 năm', '2 năm'), ans: 'B',
      why: 'Mẹ luôn hơn Lan 33 − 9 = 24 (tuổi). Khi tuổi mẹ gấp 5 lần thì hiệu 24 tuổi ứng với 5 − 1 = 4 lần tuổi Lan, nên lúc đó Lan 24 : 4 = 6 (tuổi). Vậy trước đây 9 − 6 = 3 (năm).' },
    { sec: 'Thực tế', name: 'Câu 6', pts: 1.25,
      text: 'Một quyển sách dày 200 trang. Mỗi ngày bạn Minh đọc 15 trang và đã đọc trong 12 ngày. Hỏi còn lại bao nhiêu trang chưa đọc?',
      opts: o4('20 trang', '30 trang', '180 trang', '25 trang'), ans: 'A',
      why: 'Số trang đã đọc: 15 × 12 = 180 (trang). Số trang còn lại: 200 − 180 = 20 (trang).' },
    { sec: 'Tính ngược', name: 'Câu 7', pts: 1.25,
      text: 'Một người bán <sup>1</sup>⁄<sub>3</sub> số cam, sau đó bán tiếp 20 quả nữa thì còn lại 40 quả. Hỏi lúc đầu người đó có bao nhiêu quả cam?',
      opts: o4('80 quả', '100 quả', '90 quả', '75 quả'), ans: 'C',
      why: 'Trước khi bán 20 quả sau, người đó còn 40 + 20 = 60 (quả). Số cam này chính là phần còn lại sau khi bán một phần ba, tức 2 phần trong 3 phần. Mỗi phần: 60 : 2 = 30 (quả). Lúc đầu có 30 × 3 = 90 (quả cam).' },
    { sec: 'Thực tế', name: 'Câu 8', pts: 1.25,
      text: 'Ba bạn góp tiền mua một món quà giá 90 000 đồng. An góp <sup>1</sup>⁄<sub>3</sub> giá món quà, Bình góp 25 000 đồng. Hỏi Cường phải góp bao nhiêu tiền?',
      opts: o4('30 000 đồng', '40 000 đồng', '25 000 đồng', '35 000 đồng'), ans: 'D',
      why: 'An góp: 90 000 : 3 = 30 000 (đồng). An và Bình góp: 30 000 + 25 000 = 55 000 (đồng). Cường góp: 90 000 − 55 000 = 35 000 (đồng).' },
  ],
},

/* ═══════════ ĐỀ 15 — TOÁN VUI QUỐC TẾ (Việt hoá, hạ độ khó) ═══════════ */
{
  id: 815, title: 'Đề 15 · Toán vui quốc tế (Việt hoá)', time: 35,
  questions: [
    { sec: 'Đếm số', name: 'Câu 1', pts: 1.25,
      text: '<i>(Ý tưởng Math Kangaroo Écolier)</i> Bạn Mai viết các số từ <b>1 đến 30</b>. Hỏi có bao nhiêu số <b>chứa chữ số 2</b>?',
      opts: o4('12 số', '11 số', '13 số', '10 số'), ans: 'A',
      why: 'Các số có chữ số 2 ở hàng đơn vị: 2; 12; 22 — 3 số. Các số có chữ số 2 ở hàng chục: 20; 21; 22; …; 29 — 10 số. Số 22 bị đếm hai lần nên tổng: 3 + 10 − 1 = 12 (số).' },
    { sec: 'Dãy số', name: 'Câu 2', pts: 1.25,
      text: '<i>(Ý tưởng SASMO Grade 3)</i> Tổng của <b>5 số tự nhiên liên tiếp</b> bằng 100. Số bé nhất trong 5 số đó là:',
      opts: o4('19', '20', '18', '16'), ans: 'C',
      why: 'Ghép cặp thì số ở giữa chính là 100 : 5 = 20. Năm số liên tiếp đó là 18; 19; 20; 21; 22. Số bé nhất là 18. Thử lại: 18 + 19 + 20 + 21 + 22 = 100.' },
    { sec: 'Suy luận', name: 'Câu 3', pts: 1.25,
      text: '<i>(Ý tưởng Math Kangaroo)</i> Một con ốc sên bò lên miệng giếng sâu 10 m. Ban ngày nó bò lên được 3 m, ban đêm lại tụt xuống 2 m. Hỏi sau bao nhiêu ngày ốc sên bò tới miệng giếng?',
      opts: o4('10 ngày', '8 ngày', '9 ngày', '7 ngày'), ans: 'B',
      why: 'Mỗi ngày đêm ốc sên chỉ lên được thực sự 3 − 2 = 1 (m). Sau 7 ngày đêm nó ở độ cao 7 m. Sang ngày thứ 8, nó bò thêm 3 m là đúng 7 + 3 = 10 m — tới miệng giếng và không tụt xuống nữa. Vậy cần 8 ngày.' },
    { sec: 'Toán đố', name: 'Câu 4', pts: 1.25,
      text: '<i>(Ý tưởng SASMO)</i> Hộp thứ nhất có 5 viên kẹo. Hộp thứ hai có số kẹo gấp đôi hộp thứ nhất. Hộp thứ ba có số kẹo ít hơn hộp thứ hai 4 viên. Hỏi cả ba hộp có bao nhiêu viên kẹo?',
      opts: o4('20 viên', '25 viên', '19 viên', '21 viên'), ans: 'D',
      why: 'Hộp thứ hai: 5 × 2 = 10 (viên). Hộp thứ ba: 10 − 4 = 6 (viên). Cả ba hộp: 5 + 10 + 6 = 21 (viên kẹo).' },
    { sec: 'Số học', name: 'Câu 5', pts: 1.25,
      text: '<i>(Ý tưởng IMSO)</i> Một số nhân với chính nó thì được 144. Số đó là:',
      opts: o4('14', '11', '12', '24'), ans: 'C',
      why: 'Thử lần lượt: 11 × 11 = 121; 12 × 12 = 144. Vậy số cần tìm là 12.' },
    { sec: 'Đếm ô', name: 'Câu 6', pts: 1.25,
      text: '<i>(Ý tưởng Math Kangaroo)</i> Một bảng ô vuông <b>4 × 4</b> được tô đen tất cả các ô nằm trên hai đường chéo. Hỏi còn lại bao nhiêu ô <b>không</b> được tô đen?',
      opts: o4('9 ô', '8 ô', '10 ô', '7 ô'), ans: 'B',
      why: 'Bảng có 4 × 4 = 16 ô. Mỗi đường chéo đi qua 4 ô, hai đường chéo của bảng cỡ chẵn không có ô chung nên tô đen 4 + 4 = 8 ô. Số ô còn lại: 16 − 8 = 8 (ô).' },
    { sec: 'Số học', name: 'Câu 7', pts: 1.25,
      text: '<i>(Ý tưởng HKIMO Primary 3)</i> Tính tích của <b>bảy</b> số 2: <b>2 × 2 × 2 × 2 × 2 × 2 × 2</b>. Chữ số tận cùng của kết quả là:',
      opts: o4('2', '4', '6', '8'), ans: 'D',
      why: 'Nhân dần: 2; 4; 8; 16; 32; 64; 128. Kết quả là 128 nên chữ số tận cùng là 8.' },
    { sec: 'Suy luận', name: 'Câu 8', pts: 1.25,
      text: '<i>(Ý tưởng SASMO)</i> Ba bạn ăn hết 9 cái bánh trong 3 phút. Hỏi 9 bạn (ăn nhanh như nhau) ăn hết 27 cái bánh trong bao lâu?',
      opts: o4('3 phút', '9 phút', '1 phút', '27 phút'), ans: 'A',
      why: 'Mỗi bạn ăn 9 : 3 = 3 (cái bánh) trong 3 phút. Với 9 bạn thì mỗi bạn cũng chỉ phải ăn 27 : 9 = 3 (cái bánh), nên vẫn hết đúng 3 phút.' },
  ],
},

];

SUBJECTS.push({
  id: 'hsg3', name: 'Toán nâng cao', short: 'Nâng cao 3', icon: '🎓', grade: 3,
  exams: HSG3_EXAMS, ready: true,
  heroTitle: 'Toán nâng cao lớp 3 — bồi dưỡng HSG cấp trường / quận – huyện',
  heroMeta: '📚 15 chuyên đề &nbsp;•&nbsp; 120 câu &nbsp;•&nbsp; ⏱ 35 phút mỗi đề &nbsp;•&nbsp; lời giải chi tiết',
});
