// TỰ NHIÊN VÀ XÃ HỘI — LỚP 3 (GDPT 2018)
// 30 đề × 10 câu = 300 câu. Mỗi câu 1 điểm — thang 10 — 15 phút mỗi đề.
//
// 6 chủ đề, nhấn nội dung riêng của lớp 3:
//   - Gia đình: họ nội – họ ngoại, kỉ niệm gia đình, phòng cháy, giữ vệ sinh quanh nhà
//   - Trường học: truyền thống, hoạt động kết nối cộng đồng, giữ an toàn
//   - Cộng đồng: hoạt động sản xuất (nông nghiệp, công nghiệp, thủ công); di tích – cảnh quan
//   - Thực vật và động vật: các bộ phận và chức năng; sử dụng hợp lí
//   - Con người và sức khoẻ: cơ quan tiêu hoá, tuần hoàn, thần kinh và cách bảo vệ
//   - Trái Đất và bầu trời: phương hướng; hình dạng Trái Đất; ngày – đêm; năm – tháng – mùa

const TNXH3_EXAMS = [

/* ═══════════ ĐỀ 1 — HỌ HÀNG NỘI, NGOẠI ═══════════ */
{
  id: 5301, title: 'Đề 1 · Họ nội, họ ngoại', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Ông bà, các bác, cô, chú... bên bố thuộc họ nào?',
      opts: o4('Họ nội', 'Họ ngoại', 'Họ hàng xóm', 'Không thuộc họ nào'), ans: 'A',
      why: 'Những người thân bên bố (ông bà nội, bác, cô, chú) là họ nội.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Ông bà, các bác, cậu, dì... bên mẹ thuộc họ nào?',
      opts: o4('Họ nội', 'Họ ngoại', 'Họ khác', 'Người dưng'), ans: 'B',
      why: 'Những người thân bên mẹ (ông bà ngoại, cậu, dì) là họ ngoại.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Con của cậu, của dì là anh, chị, em họ bên nào của em?',
      opts: o4('Bên ngoại', 'Bên nội', 'Không phải họ hàng', 'Bên hàng xóm'), ans: 'A',
      why: 'Cậu, dì là em/anh chị của mẹ (họ ngoại) nên con của họ là anh chị em họ bên ngoại.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Vợ của chú (em trai bố), em gọi là gì?',
      opts: o4('Thím', 'Mợ', 'Bác gái', 'Dì'), ans: 'A',
      why: 'Vợ của chú được gọi là thím.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Vợ của cậu (em/anh trai mẹ), em gọi là gì?',
      opts: o4('Thím', 'Mợ', 'Cô', 'Bà'), ans: 'B',
      why: 'Vợ của cậu được gọi là mợ.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Ngày giỗ, ngày Tết là dịp để họ hàng làm gì?',
      opts: o4('Sum họp, tưởng nhớ ông bà tổ tiên', 'Xa lánh nhau', 'Tranh chấp tài sản', 'Không quan tâm nhau'), ans: 'A',
      why: 'Giỗ, Tết là dịp con cháu sum họp, tưởng nhớ tổ tiên và gắn bó với nhau.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Kỉ niệm đáng nhớ của gia đình có thể là dịp nào?',
      opts: o4('Sinh nhật, chuyến du lịch, ngày cưới, ngày sum họp', 'Ngày cãi vã', 'Ngày mất đồ', 'Không có dịp nào'), ans: 'A',
      why: 'Sinh nhật, du lịch, cưới hỏi, sum họp là những kỉ niệm đẹp của gia đình.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Sơ đồ vẽ các đời ông bà, cha mẹ, con cháu trong dòng họ gọi là gì?',
      opts: o4('Sơ đồ gia phả (cây gia đình)', 'Thời khoá biểu', 'Bản đồ', 'Sổ liên lạc'), ans: 'A',
      why: 'Gia phả (cây gia đình) ghi lại các thế hệ trong dòng họ.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Với họ hàng, em nên có thái độ thế nào?',
      opts: o4('Kính trọng người trên, thương yêu mọi người', 'Coi thường người nghèo', 'Chỉ chơi với người giàu', 'Không chào hỏi ai'), ans: 'A',
      why: 'Cần kính trọng người lớn tuổi và yêu thương, giúp đỡ mọi người trong họ.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Bố của bố em, em gọi là gì?',
      opts: o4('Ông nội', 'Ông ngoại', 'Bác', 'Cậu'), ans: 'A',
      why: 'Bố của bố là ông nội.' },
  ],
},

/* ═══════════ ĐỀ 2 — PHÒNG CHÁY VÀ GIỮ VỆ SINH QUANH NHÀ ═══════════ */
{
  id: 5302, title: 'Đề 2 · Phòng cháy và vệ sinh quanh nhà', time: 15,
  questions: [
    { sec: 'An toàn', name: 'Câu 1', pts: 1,
      text: 'Vật nào trong nhà dễ gây cháy nếu bất cẩn?',
      opts: o4('Bếp lửa, bếp ga, nến, diêm', 'Cái gối', 'Quyển vở', 'Cái chăn để gấp'), ans: 'A',
      why: 'Bếp lửa, bếp ga, nến, diêm là nguồn lửa dễ gây cháy nếu sơ ý.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Khi nấu ăn xong, cần làm gì với bếp ga?',
      opts: o4('Khoá bếp, tắt lửa cẩn thận', 'Để lửa cháy suốt', 'Bỏ đi chơi ngay', 'Đổ nước lên bình ga'), ans: 'A',
      why: 'Phải tắt và khoá bếp ga sau khi dùng để tránh rò khí, gây cháy nổ.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Vì sao không nên cắm quá nhiều thiết bị điện vào một ổ cắm?',
      opts: o4('Vì dễ quá tải, nóng và gây cháy', 'Vì tốn chỗ', 'Vì xấu', 'Không sao cả'), ans: 'A',
      why: 'Cắm quá nhiều đồ vào một ổ dễ gây quá tải, nóng dây và chập cháy.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Khi phát hiện có cháy trong nhà, em nên làm gì?',
      opts: o4('Báo người lớn, hô hoán và gọi 114', 'Trốn vào gầm giường', 'Chạy vào chỗ có lửa', 'Giấu không nói ai'), ans: 'A',
      why: 'Cần hô hoán, báo người lớn và gọi cứu hoả số 114, rồi thoát ra nơi an toàn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Số điện thoại gọi lực lượng chữa cháy (cứu hoả) là số nào?',
      opts: o4('113', '114', '115', '116'), ans: 'B',
      why: 'Số 114 là số gọi cứu hoả (chữa cháy). (113: công an, 115: cấp cứu.)' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Khi trong nhà có khói, khí độc do cháy, nên di chuyển thế nào?',
      opts: o4('Cúi thấp người, bịt mũi bằng khăn ẩm', 'Đứng thẳng chạy thật nhanh', 'Hít thật sâu khói vào', 'Đứng yên chờ'), ans: 'A',
      why: 'Khói bốc lên cao nên phải cúi thấp, dùng khăn ẩm che mũi miệng để bớt hít khói độc.' },
    { sec: 'Vệ sinh', name: 'Câu 7', pts: 1,
      text: 'Giữ vệ sinh xung quanh nhà giúp phòng tránh điều gì?',
      opts: o4('Ruồi, muỗi và bệnh tật', 'Trời mưa', 'Xe cộ đông', 'Mất điện'), ans: 'A',
      why: 'Nhà cửa, sân vườn sạch sẽ hạn chế ruồi, muỗi và mầm bệnh.' },
    { sec: 'Vệ sinh', name: 'Câu 8', pts: 1,
      text: 'Rác thải trong nhà nên được xử lí thế nào?',
      opts: o4('Phân loại, bỏ đúng nơi quy định', 'Vứt ra đường', 'Đổ xuống cống', 'Chất đống trong nhà'), ans: 'A',
      why: 'Rác cần được phân loại và bỏ đúng nơi để giữ môi trường sạch.' },
    { sec: 'Vệ sinh', name: 'Câu 9', pts: 1,
      text: 'Nước đọng ở lu, chum, chậu quanh nhà là nơi con gì đẻ trứng?',
      opts: o4('Muỗi', 'Chim', 'Cá', 'Gà'), ans: 'A',
      why: 'Muỗi đẻ trứng ở nơi nước đọng; cần đậy kín hoặc đổ hết nước đọng.' },
    { sec: 'Vệ sinh', name: 'Câu 10', pts: 1,
      text: 'Việc nào giúp môi trường quanh nhà sạch, đẹp?',
      opts: o4('Quét sân, trồng cây, khơi thông cống rãnh', 'Đổ rác ra vườn nhà hàng xóm', 'Để cỏ dại mọc um tùm', 'Xả nước bẩn ra đường'), ans: 'A',
      why: 'Quét dọn, trồng cây, khơi thông cống rãnh giúp nơi ở sạch đẹp, thoáng mát.' },
  ],
},

/* ═══════════ ĐỀ 3 — TRƯỜNG HỌC: TRUYỀN THỐNG, HOẠT ĐỘNG, AN TOÀN ═══════════ */
{
  id: 5303, title: 'Đề 3 · Truyền thống và hoạt động ở trường', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Truyền thống tốt đẹp của nhà trường có thể là gì?',
      opts: o4('Dạy tốt – học tốt, đoàn kết, giúp đỡ nhau', 'Hay bỏ học', 'Gây gổ đánh nhau', 'Xả rác bừa bãi'), ans: 'A',
      why: 'Dạy tốt – học tốt, đoàn kết, tương thân tương ái là truyền thống đáng quý của trường.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Hoạt động nào giúp nhà trường kết nối với cộng đồng?',
      opts: o4('Quyên góp ủng hộ vùng lũ, dọn vệ sinh khu phố', 'Đóng cửa không giao lưu', 'Chê bai hàng xóm', 'Không tham gia gì'), ans: 'A',
      why: 'Quyên góp giúp đỡ, dọn vệ sinh cộng đồng là hoạt động kết nối trường với xã hội.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Việc làm nào thể hiện lòng biết ơn thầy cô?',
      opts: o4('Chăm học, lễ phép, chúc mừng ngày 20/11', 'Cãi lời thầy cô', 'Trốn học', 'Vẽ bậy lên bàn'), ans: 'A',
      why: 'Chăm học, lễ phép và tri ân dịp 20/11 thể hiện lòng biết ơn thầy cô.' },
    { sec: 'Trường học', name: 'Câu 4', pts: 1,
      text: 'Khi tham gia hoạt động ngoại khoá (tham quan, dã ngoại), em cần làm gì?',
      opts: o4('Đi theo đoàn, nghe hướng dẫn, không tách nhóm', 'Tự ý đi một mình', 'Chạy lung tung', 'Trèo lan can nguy hiểm'), ans: 'A',
      why: 'Đi theo đoàn, nghe hướng dẫn và không tách nhóm để bảo đảm an toàn.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Phòng thí nghiệm, phòng có thiết bị điện ở trường, em cần thế nào?',
      opts: o4('Chỉ dùng khi có thầy cô hướng dẫn', 'Tự ý nghịch phá', 'Bật tắt lung tung', 'Mang đồ về nhà'), ans: 'A',
      why: 'Chỉ sử dụng thiết bị khi có thầy cô hướng dẫn để tránh tai nạn.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Việc làm nào giữ an toàn khi vui chơi ở trường?',
      opts: o4('Chơi đúng khu vực, không leo trèo, xô đẩy', 'Trèo lên cửa sổ', 'Ném đồ vào bạn', 'Chạy trên bàn ghế'), ans: 'A',
      why: 'Chơi đúng chỗ, không leo trèo, xô đẩy giúp tránh tai nạn thương tích.' },
    { sec: 'Trường học', name: 'Câu 7', pts: 1,
      text: 'Khi thấy bạn bị bắt nạt ở trường, em nên làm gì?',
      opts: o4('Bênh vực bạn và báo thầy cô', 'Hùa theo trêu chọc', 'Quay clip cười cợt', 'Làm ngơ mặc kệ'), ans: 'A',
      why: 'Em nên giúp bạn và báo thầy cô để ngăn hành vi bắt nạt.' },
    { sec: 'Trường học', name: 'Câu 8', pts: 1,
      text: 'Giữ gìn cơ sở vật chất của trường là việc nào?',
      opts: o4('Không vẽ bậy, không làm hỏng bàn ghế', 'Khắc tên lên bàn', 'Bẻ vòi nước', 'Đập phá cửa sổ'), ans: 'A',
      why: 'Không vẽ bậy, không phá hỏng bàn ghế, thiết bị là giữ gìn tài sản của trường.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Tham gia phong trào "Kế hoạch nhỏ" thu gom giấy vụn có ý nghĩa gì?',
      opts: o4('Tiết kiệm, bảo vệ môi trường, gây quỹ giúp bạn', 'Làm bẩn trường', 'Lãng phí giấy', 'Không có ý nghĩa'), ans: 'A',
      why: 'Thu gom giấy vụn giúp tái chế, bảo vệ môi trường và gây quỹ giúp bạn khó khăn.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Là học sinh, em góp phần giữ truyền thống nhà trường bằng cách nào?',
      opts: o4('Học tốt, ngoan ngoãn, tham gia phong trào', 'Vi phạm nội quy', 'Đi học muộn thường xuyên', 'Không làm bài tập'), ans: 'A',
      why: 'Học tốt, ngoan và tích cực tham gia phong trào là góp phần giữ truyền thống của trường.' },
  ],
},

/* ═══════════ ĐỀ 4 — HOẠT ĐỘNG SẢN XUẤT ═══════════ */
{
  id: 5304, title: 'Đề 4 · Hoạt động sản xuất quanh em', time: 15,
  questions: [
    { sec: 'Sản xuất', name: 'Câu 1', pts: 1,
      text: 'Trồng lúa, trồng rau, nuôi lợn gà thuộc hoạt động sản xuất nào?',
      opts: o4('Nông nghiệp', 'Công nghiệp', 'Thủ công', 'Du lịch'), ans: 'A',
      why: 'Trồng trọt và chăn nuôi thuộc hoạt động sản xuất nông nghiệp.' },
    { sec: 'Sản xuất', name: 'Câu 2', pts: 1,
      text: 'Sản xuất trong nhà máy như dệt vải, lắp ráp máy móc thuộc hoạt động nào?',
      opts: o4('Nông nghiệp', 'Công nghiệp', 'Đánh cá', 'Chăn nuôi'), ans: 'B',
      why: 'Sản xuất bằng máy móc trong nhà máy (dệt, lắp ráp...) là công nghiệp.' },
    { sec: 'Sản xuất', name: 'Câu 3', pts: 1,
      text: 'Làm gốm, đan lát, thêu tay, làm nón... thuộc hoạt động nào?',
      opts: o4('Nghề thủ công', 'Nông nghiệp', 'Công nghiệp nặng', 'Khai thác than'), ans: 'A',
      why: 'Làm gốm, đan lát, thêu, làm nón là các nghề thủ công truyền thống.' },
    { sec: 'Sản xuất', name: 'Câu 4', pts: 1,
      text: 'Sản phẩm nào là của nghề nông?',
      opts: o4('Thóc, gạo, rau, quả', 'Cái ti vi', 'Ô tô', 'Điện thoại'), ans: 'A',
      why: 'Thóc, gạo, rau, quả là nông sản do nghề nông làm ra.' },
    { sec: 'Sản xuất', name: 'Câu 5', pts: 1,
      text: 'Ngư dân đánh bắt và nuôi trồng thuỷ sản làm ra sản phẩm gì?',
      opts: o4('Tôm, cá, cua, mực', 'Vải vóc', 'Xi măng', 'Sách vở'), ans: 'A',
      why: 'Nghề cá cho ta tôm, cá, cua, mực... (thuỷ hải sản).' },
    { sec: 'Sản xuất', name: 'Câu 6', pts: 1,
      text: 'Người thợ mộc làm ra sản phẩm gì?',
      opts: o4('Bàn, ghế, giường, tủ bằng gỗ', 'Bát đĩa sứ', 'Quần áo', 'Bánh kẹo'), ans: 'A',
      why: 'Thợ mộc dùng gỗ làm bàn, ghế, giường, tủ.' },
    { sec: 'Sản xuất', name: 'Câu 7', pts: 1,
      text: 'Vì sao ta cần quý trọng người lao động?',
      opts: o4('Vì họ làm ra của cải, sản phẩm cho xã hội', 'Vì họ giàu có', 'Vì họ nổi tiếng', 'Không cần quý trọng'), ans: 'A',
      why: 'Người lao động làm ra của cải, sản phẩm phục vụ mọi người nên rất đáng quý.' },
    { sec: 'Sản xuất', name: 'Câu 8', pts: 1,
      text: 'Sản phẩm thủ công của làng nghề thường có đặc điểm gì?',
      opts: o4('Làm bằng tay, tinh xảo, mang nét truyền thống', 'Sản xuất hàng loạt bằng máy', 'Không có giá trị', 'Giống hệt hàng công nghiệp'), ans: 'A',
      why: 'Hàng thủ công làm bằng tay, tinh xảo, mang đậm nét văn hoá truyền thống.' },
    { sec: 'Sản xuất', name: 'Câu 9', pts: 1,
      text: 'Để có sản phẩm, người lao động cần điều gì?',
      opts: o4('Bỏ công sức, thời gian và sự khéo léo', 'Chỉ cần ngồi chơi', 'Chờ trời cho sẵn', 'Không cần làm gì'), ans: 'A',
      why: 'Mỗi sản phẩm đều đòi hỏi công sức, thời gian và sự khéo léo của người lao động.' },
    { sec: 'Sản xuất', name: 'Câu 10', pts: 1,
      text: 'Em thể hiện sự trân trọng thành quả lao động bằng cách nào?',
      opts: o4('Tiết kiệm, không phá hoại, giữ gìn sản phẩm', 'Lãng phí đồ ăn', 'Đập phá đồ dùng', 'Vứt bỏ bừa bãi'), ans: 'A',
      why: 'Tiết kiệm và giữ gìn sản phẩm là cách trân trọng công sức người lao động.' },
  ],
},

/* ═══════════ ĐỀ 5 — DI TÍCH LỊCH SỬ, VĂN HOÁ VÀ CẢNH QUAN ═══════════ */
{
  id: 5305, title: 'Đề 5 · Di tích và cảnh quan quê hương', time: 15,
  questions: [
    { sec: 'Cộng đồng', name: 'Câu 1', pts: 1,
      text: 'Đền, chùa, di tích cổ được gọi chung là gì?',
      opts: o4('Di tích lịch sử – văn hoá', 'Khu vui chơi', 'Chợ', 'Bến xe'), ans: 'A',
      why: 'Đền, chùa, thành cổ, lăng tẩm... là di tích lịch sử – văn hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 2', pts: 1,
      text: 'Vịnh Hạ Long, hang động, thác nước đẹp được gọi là gì?',
      opts: o4('Cảnh quan thiên nhiên', 'Nhà máy', 'Bệnh viện', 'Trường học'), ans: 'A',
      why: 'Núi, hang, vịnh, thác đẹp là cảnh quan thiên nhiên.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Khi đến tham quan di tích, đền chùa, em cần làm gì?',
      opts: o4('Giữ trật tự, không xả rác, không viết bậy', 'Khắc tên lên tường', 'Hái hoa bẻ cành', 'Chạy nhảy la hét'), ans: 'A',
      why: 'Ở di tích cần giữ trật tự, sạch sẽ, không viết vẽ bậy hay phá hoại.' },
    { sec: 'Cộng đồng', name: 'Câu 4', pts: 1,
      text: 'Vì sao phải bảo vệ di tích lịch sử – văn hoá?',
      opts: o4('Vì đó là tài sản chung, gắn với lịch sử dân tộc', 'Vì cũ kĩ nên bỏ đi', 'Vì không ai quan tâm', 'Vì để bán lấy tiền'), ans: 'A',
      why: 'Di tích là tài sản chung, gắn với lịch sử, truyền thống, cần được giữ gìn.' },
    { sec: 'Cộng đồng', name: 'Câu 5', pts: 1,
      text: 'Lễ hội truyền thống ở địa phương thường nhằm mục đích gì?',
      opts: o4('Tưởng nhớ công ơn, giữ nét văn hoá', 'Để gây ồn ào', 'Để xả rác', 'Không có ý nghĩa'), ans: 'A',
      why: 'Lễ hội nhằm tưởng nhớ công ơn tổ tiên, anh hùng và giữ gìn nét văn hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 6', pts: 1,
      text: 'Đền Hùng (Phú Thọ) là nơi thờ ai?',
      opts: o4('Các Vua Hùng', 'Ông Táo', 'Thần Sông', 'Nhà vua nước ngoài'), ans: 'A',
      why: 'Đền Hùng thờ các Vua Hùng — những người có công dựng nước.' },
    { sec: 'Cộng đồng', name: 'Câu 7', pts: 1,
      text: 'Việc nào giúp giữ gìn cảnh quan thiên nhiên khi đi tham quan?',
      opts: o4('Không xả rác, không bẻ cây, không khắc vẽ', 'Vứt rác xuống suối', 'Chặt cây làm kỉ niệm', 'Viết tên lên đá'), ans: 'A',
      why: 'Không xả rác, không bẻ cây, không khắc vẽ là cách giữ cảnh quan luôn đẹp.' },
    { sec: 'Cộng đồng', name: 'Câu 8', pts: 1,
      text: 'Cảnh quan thiên nhiên đẹp có lợi ích gì cho địa phương?',
      opts: o4('Thu hút khách du lịch, tạo việc làm', 'Làm nghèo địa phương', 'Không có lợi gì', 'Gây ô nhiễm'), ans: 'A',
      why: 'Cảnh đẹp thu hút du khách, phát triển du lịch và tạo việc làm.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Hành động nào phá hoại di tích, cảnh quan?',
      opts: o4('Khắc tên, xả rác, bẻ cành, sờ nắn hiện vật', 'Chụp ảnh nhẹ nhàng', 'Đi đúng lối tham quan', 'Bỏ rác vào thùng'), ans: 'A',
      why: 'Khắc vẽ, xả rác, bẻ cành, sờ nắn hiện vật đều làm hư hại di tích, cảnh quan.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Em có thể giới thiệu quê hương mình với bạn bè bằng cách nào?',
      opts: o4('Kể về di tích, món ăn, cảnh đẹp của quê', 'Chê bai quê mình', 'Giấu không nói gì', 'Nói sai sự thật'), ans: 'A',
      why: 'Giới thiệu di tích, cảnh đẹp, món ăn giúp bạn bè hiểu và yêu quê hương em.' },
  ],
},

/* ═══════════ ĐỀ 6 — BỘ PHẬN VÀ CHỨC NĂNG CỦA THỰC VẬT ═══════════ */
{
  id: 5306, title: 'Đề 6 · Các bộ phận của cây và chức năng', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Rễ cây có chức năng chính là gì?',
      opts: o4('Hút nước, chất khoáng và giữ cây đứng vững', 'Quang hợp tạo thức ăn', 'Nở hoa', 'Bay trong không khí'), ans: 'A',
      why: 'Rễ hút nước, chất khoáng từ đất và bám giữ cho cây đứng vững.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Thân cây có chức năng gì?',
      opts: o4('Nâng đỡ và vận chuyển nước, chất nuôi cây', 'Chỉ để làm cảnh', 'Hút nước dưới đất', 'Đẻ trứng'), ans: 'A',
      why: 'Thân nâng đỡ cành lá và vận chuyển nước, chất dinh dưỡng đi nuôi cây.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Lá cây nhận ánh sáng để làm gì?',
      opts: o4('Chế tạo thức ăn nuôi cây (quang hợp)', 'Hút nước từ đất', 'Giữ cây đứng vững', 'Kết thành hạt'), ans: 'A',
      why: 'Lá nhận ánh sáng Mặt Trời để quang hợp, tạo thức ăn nuôi cây và nhả khí ô-xi.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Hoa của cây có vai trò gì trong việc sinh sản?',
      opts: o4('Thụ phấn rồi tạo thành quả và hạt', 'Hút nước', 'Nâng đỡ cây', 'Giữ đất'), ans: 'A',
      why: 'Hoa thụ phấn, sau đó phát triển thành quả chứa hạt để sinh ra cây mới.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Quả của cây thường chứa gì bên trong?',
      opts: o4('Hạt (để mọc thành cây mới)', 'Rễ cây', 'Lá non', 'Nước lã'), ans: 'A',
      why: 'Quả bao bọc và bảo vệ hạt; hạt gieo xuống đất sẽ mọc thành cây mới.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Khi quang hợp, lá cây nhả ra khí gì có lợi cho con người?',
      opts: o4('Khí ô-xi', 'Khói bụi', 'Khí độc', 'Hơi nóng'), ans: 'A',
      why: 'Cây quang hợp nhả ra khí ô-xi giúp con người và động vật hô hấp.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Bộ phận nào của cây rau muống ta thường dùng làm thức ăn?',
      opts: o4('Thân và lá', 'Rễ', 'Hạt khô', 'Vỏ cây'), ans: 'A',
      why: 'Với rau muống, ta ăn phần thân và lá.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Cây nào ta dùng phần rễ (củ) để ăn?',
      opts: o4('Củ cà rốt, củ cải', 'Rau cải', 'Cây mía', 'Cây cam'), ans: 'A',
      why: 'Cà rốt, củ cải là phần rễ phình to thành củ, dùng làm thức ăn.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Sử dụng thực vật một cách hợp lí nghĩa là gì?',
      opts: o4('Dùng tiết kiệm, trồng thêm, không phá hoại', 'Chặt phá thoải mái', 'Đốt rừng lấy đất', 'Lãng phí rau quả'), ans: 'A',
      why: 'Dùng tiết kiệm và trồng thêm cây, không chặt phá bừa bãi là sử dụng hợp lí.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Nếu chặt phá rừng bừa bãi sẽ dẫn đến hậu quả gì?',
      opts: o4('Lũ lụt, sạt lở, thiếu ô-xi', 'Không khí sạch hơn', 'Nhiều mưa thuận hoà hơn', 'Không có hậu quả gì'), ans: 'A',
      why: 'Mất rừng gây lũ lụt, sạt lở đất và làm giảm lượng ô-xi, hại môi trường.' },
  ],
},

/* ═══════════ ĐỀ 7 — BỘ PHẬN VÀ CHỨC NĂNG CỦA ĐỘNG VẬT ═══════════ */
{
  id: 5307, title: 'Đề 7 · Các bộ phận của con vật và chức năng', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Hầu hết cơ thể động vật gồm những phần chính nào?',
      opts: o4('Đầu, mình và cơ quan di chuyển', 'Chỉ có đầu', 'Chỉ có đuôi', 'Chỉ có chân'), ans: 'A',
      why: 'Nhiều loài vật có ba phần: đầu, mình và cơ quan di chuyển (chân, cánh, vây...).' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Cá dùng bộ phận nào để bơi?',
      opts: o4('Vây và đuôi', 'Cánh', 'Chân', 'Tai'), ans: 'A',
      why: 'Cá bơi nhờ vây và đuôi.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Cá thở bằng bộ phận nào?',
      opts: o4('Mang', 'Phổi', 'Da', 'Mũi'), ans: 'A',
      why: 'Cá thở bằng mang để lấy khí ô-xi hoà tan trong nước.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Chim dùng bộ phận nào để bay?',
      opts: o4('Đôi cánh', 'Vây', 'Đuôi cá', 'Bốn chân'), ans: 'A',
      why: 'Chim bay được nhờ đôi cánh có lông vũ.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào có 6 chân?',
      opts: o4('Con kiến, con ong (côn trùng)', 'Con chó', 'Con mèo', 'Con voi'), ans: 'A',
      why: 'Côn trùng như kiến, ong có 6 chân.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Bộ phận nào giúp con vật cảm nhận mùi và tìm thức ăn?',
      opts: o4('Mũi (và râu ở một số loài)', 'Đuôi', 'Móng', 'Vảy'), ans: 'A',
      why: 'Mũi (và râu ở một số loài) giúp con vật ngửi mùi để tìm thức ăn, nhận biết nguy hiểm.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Con vật nào đẻ con và nuôi con bằng sữa?',
      opts: o4('Con mèo, con chó, con bò', 'Con gà', 'Con cá', 'Con rắn'), ans: 'A',
      why: 'Thú (mèo, chó, bò) đẻ con và nuôi con bằng sữa mẹ.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con vật nào đẻ trứng?',
      opts: o4('Con gà, con vịt, con chim', 'Con trâu', 'Con lợn', 'Con voi'), ans: 'A',
      why: 'Gà, vịt, chim đẻ trứng rồi ấp cho trứng nở thành con.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Con vật cũng cần những gì để sống như con người?',
      opts: o4('Thức ăn, nước uống, không khí và nơi ở', 'Chỉ cần ánh nắng', 'Không cần ăn uống', 'Chỉ cần tiếng nhạc'), ans: 'A',
      why: 'Động vật cần thức ăn, nước, không khí và nơi ở để sống và lớn lên.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Sử dụng động vật hợp lí là làm gì?',
      opts: o4('Nuôi và khai thác có kế hoạch, không săn bắt bừa bãi', 'Săn bắt hết mọi loài', 'Bắt cả con non', 'Phá nơi chúng sống'), ans: 'A',
      why: 'Nuôi, khai thác có kế hoạch và không săn bắt bừa bãi giúp bảo vệ động vật.' },
  ],
},

/* ═══════════ ĐỀ 8 — CƠ QUAN TIÊU HOÁ VÀ TUẦN HOÀN ═══════════ */
{
  id: 5308, title: 'Đề 8 · Cơ quan tiêu hoá và tuần hoàn', time: 15,
  questions: [
    { sec: 'Tiêu hoá', name: 'Câu 1', pts: 1,
      text: 'Cơ quan tiêu hoá có nhiệm vụ gì?',
      opts: o4('Biến thức ăn thành chất nuôi cơ thể', 'Giúp ta nhìn', 'Giúp ta nghe', 'Bơm máu đi khắp người'), ans: 'A',
      why: 'Cơ quan tiêu hoá biến thức ăn thành chất dinh dưỡng nuôi cơ thể.' },
    { sec: 'Tiêu hoá', name: 'Câu 2', pts: 1,
      text: 'Thức ăn được nghiền nhỏ đầu tiên ở đâu?',
      opts: o4('Ở miệng (nhờ răng nhai)', 'Ở dạ dày', 'Ở ruột già', 'Ở phổi'), ans: 'A',
      why: 'Ở miệng, răng nhai nghiền nhỏ thức ăn, nước bọt làm mềm thức ăn.' },
    { sec: 'Tiêu hoá', name: 'Câu 3', pts: 1,
      text: 'Ống dẫn thức ăn từ miệng xuống dạ dày gọi là gì?',
      opts: o4('Thực quản', 'Khí quản', 'Ruột non', 'Mạch máu'), ans: 'A',
      why: 'Thực quản là ống dẫn thức ăn từ miệng xuống dạ dày.' },
    { sec: 'Tiêu hoá', name: 'Câu 4', pts: 1,
      text: 'Nơi thức ăn được nhào trộn, tiêu hoá phần lớn là cơ quan nào?',
      opts: o4('Dạ dày và ruột non', 'Hai lá phổi', 'Quả tim', 'Đôi mắt'), ans: 'A',
      why: 'Dạ dày nhào trộn thức ăn; ruột non tiêu hoá và hấp thụ phần lớn chất dinh dưỡng.' },
    { sec: 'Tiêu hoá', name: 'Câu 5', pts: 1,
      text: 'Để bảo vệ cơ quan tiêu hoá, em nên làm gì?',
      opts: o4('Ăn chín uống sôi, nhai kĩ, ăn đúng giờ', 'Ăn đồ ôi thiu', 'Ăn thật nhanh, không nhai', 'Bỏ bữa thường xuyên'), ans: 'A',
      why: 'Ăn chín uống sôi, nhai kĩ và ăn đúng giờ giúp tiêu hoá tốt, tránh đau bụng.' },
    { sec: 'Tuần hoàn', name: 'Câu 6', pts: 1,
      text: 'Cơ quan tuần hoàn gồm những bộ phận chính nào?',
      opts: o4('Tim và các mạch máu', 'Dạ dày và ruột', 'Mắt và tai', 'Xương và cơ'), ans: 'A',
      why: 'Cơ quan tuần hoàn gồm tim và các mạch máu.' },
    { sec: 'Tuần hoàn', name: 'Câu 7', pts: 1,
      text: 'Tim có nhiệm vụ gì?',
      opts: o4('Co bóp, bơm máu đi khắp cơ thể', 'Tiêu hoá thức ăn', 'Giúp ta thở', 'Giúp ta nhìn'), ans: 'A',
      why: 'Tim co bóp liên tục để bơm máu mang chất dinh dưỡng, ô-xi đi nuôi cơ thể.' },
    { sec: 'Tuần hoàn', name: 'Câu 8', pts: 1,
      text: 'Máu đi trong cơ thể theo đường nào?',
      opts: o4('Theo các mạch máu', 'Theo ống thực quản', 'Theo khí quản', 'Theo dây thần kinh'), ans: 'A',
      why: 'Máu chảy trong các mạch máu, đi khắp cơ thể rồi trở về tim.' },
    { sec: 'Tuần hoàn', name: 'Câu 9', pts: 1,
      text: 'Việc nào giúp tim mạch khoẻ mạnh?',
      opts: o4('Tập thể dục, ăn uống điều độ, ngủ đủ', 'Ăn quá nhiều mỡ, đồ mặn', 'Lười vận động', 'Thức khuya thường xuyên'), ans: 'A',
      why: 'Tập thể dục, ăn uống điều độ và ngủ đủ giúp tim mạch khoẻ.' },
    { sec: 'Tuần hoàn', name: 'Câu 10', pts: 1,
      text: 'Khi chạy nhảy nhiều, tim của em thường thế nào?',
      opts: o4('Đập nhanh hơn', 'Ngừng đập', 'Đập chậm lại rồi dừng', 'Không thay đổi gì'), ans: 'A',
      why: 'Khi vận động mạnh, cơ thể cần nhiều ô-xi hơn nên tim đập nhanh hơn.' },
  ],
},

/* ═══════════ ĐỀ 9 — CƠ QUAN THẦN KINH VÀ CHĂM SÓC SỨC KHOẺ ═══════════ */
{
  id: 5309, title: 'Đề 9 · Cơ quan thần kinh và sức khoẻ', time: 15,
  questions: [
    { sec: 'Thần kinh', name: 'Câu 1', pts: 1,
      text: 'Cơ quan thần kinh gồm những bộ phận chính nào?',
      opts: o4('Não, tuỷ sống và các dây thần kinh', 'Tim và mạch máu', 'Dạ dày và ruột', 'Xương và cơ'), ans: 'A',
      why: 'Cơ quan thần kinh gồm não, tuỷ sống và các dây thần kinh.' },
    { sec: 'Thần kinh', name: 'Câu 2', pts: 1,
      text: 'Não nằm được bảo vệ trong bộ phận nào?',
      opts: o4('Hộp sọ', 'Lồng ngực', 'Bàn tay', 'Bàn chân'), ans: 'A',
      why: 'Não nằm trong hộp sọ cứng để được bảo vệ.' },
    { sec: 'Thần kinh', name: 'Câu 3', pts: 1,
      text: 'Cơ quan thần kinh có vai trò gì?',
      opts: o4('Điều khiển mọi hoạt động của cơ thể', 'Chỉ để trang trí', 'Tiêu hoá thức ăn', 'Bơm máu'), ans: 'A',
      why: 'Não và các dây thần kinh điều khiển, phối hợp mọi hoạt động: suy nghĩ, cử động, cảm nhận.' },
    { sec: 'Thần kinh', name: 'Câu 4', pts: 1,
      text: 'Nhờ đâu em suy nghĩ, ghi nhớ và học bài được?',
      opts: o4('Nhờ bộ não', 'Nhờ dạ dày', 'Nhờ bàn chân', 'Nhờ lá phổi'), ans: 'A',
      why: 'Bộ não giúp ta suy nghĩ, ghi nhớ, học tập và điều khiển hành động.' },
    { sec: 'Thần kinh', name: 'Câu 5', pts: 1,
      text: 'Để cơ quan thần kinh khoẻ, em cần làm gì?',
      opts: o4('Ngủ đủ giấc, học và nghỉ hợp lí', 'Thức khuya học dồn', 'Xem điện thoại suốt ngày', 'Lo lắng, căng thẳng liên tục'), ans: 'A',
      why: 'Ngủ đủ, học tập và nghỉ ngơi hợp lí giúp thần kinh khoẻ mạnh, tỉnh táo.' },
    { sec: 'Thần kinh', name: 'Câu 6', pts: 1,
      text: 'Giấc ngủ có vai trò gì với cơ quan thần kinh?',
      opts: o4('Giúp não và cơ thể được nghỉ ngơi, phục hồi', 'Làm não yếu đi', 'Không có tác dụng', 'Khiến ta quên hết'), ans: 'A',
      why: 'Ngủ giúp não và cơ thể nghỉ ngơi, phục hồi để hôm sau minh mẫn.' },
    { sec: 'Sức khoẻ', name: 'Câu 7', pts: 1,
      text: 'Trạng thái nào có hại cho cơ quan thần kinh?',
      opts: o4('Lo sợ, tức giận, căng thẳng kéo dài', 'Vui vẻ, thoải mái', 'Ngủ đủ giấc', 'Học tập điều độ'), ans: 'A',
      why: 'Lo sợ, tức giận, căng thẳng lâu ngày làm hại thần kinh, dễ mệt mỏi, mất ngủ.' },
    { sec: 'Sức khoẻ', name: 'Câu 8', pts: 1,
      text: 'Để đầu óc thư giãn sau giờ học, em nên làm gì?',
      opts: o4('Chơi thể thao, nghe nhạc, trò chuyện vui', 'Học liên tục không nghỉ', 'Cãi nhau với bạn', 'Lo lắng chuyện chưa xảy ra'), ans: 'A',
      why: 'Vận động nhẹ, nghe nhạc, vui chơi lành mạnh giúp thần kinh được nghỉ ngơi.' },
    { sec: 'Sức khoẻ', name: 'Câu 9', pts: 1,
      text: 'Chất nào rất có hại cho cơ quan thần kinh, trẻ em tuyệt đối tránh?',
      opts: o4('Rượu, bia, thuốc lá, ma tuý', 'Nước lọc', 'Sữa tươi', 'Rau xanh'), ans: 'A',
      why: 'Rượu, bia, thuốc lá, ma tuý gây hại nặng cho thần kinh và sức khoẻ; phải tránh xa.' },
    { sec: 'Sức khoẻ', name: 'Câu 10', pts: 1,
      text: 'Thời gian biểu học tập, nghỉ ngơi hợp lí giúp em điều gì?',
      opts: o4('Khoẻ mạnh, học tốt, không bị quá tải', 'Mệt mỏi hơn', 'Học kém đi', 'Không có ích gì'), ans: 'A',
      why: 'Sắp xếp thời gian hợp lí giúp cơ thể và thần kinh không quá tải, học hiệu quả.' },
  ],
},

/* ═══════════ ĐỀ 10 — PHƯƠNG HƯỚNG, TRÁI ĐẤT, NGÀY ĐÊM VÀ CÁC MÙA ═══════════ */
{
  id: 5310, title: 'Đề 10 · Trái Đất, phương hướng và các mùa', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Có mấy phương hướng chính?',
      opts: o4('Hai (đông, tây)', 'Ba', 'Bốn (đông, tây, nam, bắc)', 'Sáu'), ans: 'C',
      why: 'Có bốn hướng chính: đông, tây, nam, bắc.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Buổi sáng, Mặt Trời mọc ở hướng nào?',
      opts: o4('Hướng đông', 'Hướng tây', 'Hướng nam', 'Hướng bắc'), ans: 'A',
      why: 'Mặt Trời mọc ở hướng đông vào buổi sáng.' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Buổi chiều, Mặt Trời lặn ở hướng nào?',
      opts: o4('Hướng đông', 'Hướng tây', 'Hướng nam', 'Hướng bắc'), ans: 'B',
      why: 'Mặt Trời lặn ở hướng tây vào buổi chiều.' },
    { sec: 'Bầu trời', name: 'Câu 4', pts: 1,
      text: 'Trái Đất có hình dạng như thế nào?',
      opts: o4('Hình khối cầu (tròn như quả bóng)', 'Hình vuông', 'Hình phẳng dẹt', 'Hình tam giác'), ans: 'A',
      why: 'Trái Đất có dạng hình cầu, tròn như quả bóng.' },
    { sec: 'Bầu trời', name: 'Câu 5', pts: 1,
      text: 'Trái Đất chuyển động quanh thiên thể nào?',
      opts: o4('Mặt Trời', 'Mặt Trăng', 'Ngôi sao Bắc Đẩu', 'Sao chổi'), ans: 'A',
      why: 'Trái Đất chuyển động quanh Mặt Trời.' },
    { sec: 'Bầu trời', name: 'Câu 6', pts: 1,
      text: 'Vì sao trên Trái Đất có ngày và đêm?',
      opts: o4('Do Trái Đất tự quay quanh mình nó', 'Do Mặt Trời tắt đi', 'Do có mây che', 'Do đèn điện'), ans: 'A',
      why: 'Trái Đất tự quay: nửa hướng về Mặt Trời là ngày, nửa khuất là đêm.' },
    { sec: 'Bầu trời', name: 'Câu 7', pts: 1,
      text: 'Một năm có mấy tháng?',
      opts: o4('10 tháng', '11 tháng', '12 tháng', '15 tháng'), ans: 'C',
      why: 'Một năm có 12 tháng.' },
    { sec: 'Các mùa', name: 'Câu 8', pts: 1,
      text: 'Miền Bắc nước ta có bốn mùa theo thứ tự nào?',
      opts: o4('Xuân – hạ – thu – đông', 'Đông – thu – hạ – xuân', 'Hạ – đông – xuân – thu', 'Thu – xuân – đông – hạ'), ans: 'A',
      why: 'Bốn mùa nối tiếp: xuân, hạ, thu, đông.' },
    { sec: 'Các mùa', name: 'Câu 9', pts: 1,
      text: 'Vào ban ngày trời sáng là nhờ đâu?',
      opts: o4('Ánh sáng Mặt Trời chiếu tới', 'Ánh sáng Mặt Trăng', 'Ánh đèn đường', 'Ánh sáng các vì sao'), ans: 'A',
      why: 'Ban ngày, nơi đó hướng về Mặt Trời nên nhận được ánh sáng và trở nên sáng.' },
    { sec: 'Bầu trời', name: 'Câu 10', pts: 1,
      text: 'Dụng cụ nào giúp ta xác định phương hướng?',
      opts: o4('La bàn', 'Cái cân', 'Cái thước kẻ', 'Đồng hồ báo thức'), ans: 'A',
      why: 'La bàn có kim luôn chỉ hướng bắc – nam, giúp xác định phương hướng.' },
  ],
},

/* ═══════════ ĐỀ 11 — GIA ĐÌNH: HỌ HÀNG NỘI, NGOẠI (NÂNG CAO) ═══════════ */
{
  id: 8601, title: 'Đề 11 · Họ hàng nội ngoại và nếp nhà', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Chị gái của mẹ, em gọi là gì?',
      opts: o4('Thím', 'Bác gái (hoặc dì)', 'Mợ', 'Cô'), ans: 'B',
      why: 'Chị của mẹ thường được gọi là bác gái, có nơi gọi là dì; đều là họ ngoại.' },
    { sec: 'Gia đình', name: 'Câu 2', pts: 1,
      text: 'Em gái của bố, em gọi là gì?',
      opts: o4('Cô', 'Dì', 'Mợ', 'Bác'), ans: 'A',
      why: 'Em gái của bố được gọi là cô, thuộc họ nội.' },
    { sec: 'Gia đình', name: 'Câu 3', pts: 1,
      text: 'Mẹ của mẹ em, em gọi là gì?',
      opts: o4('Bà nội', 'Cô', 'Bà ngoại', 'Bác gái'), ans: 'C',
      why: 'Mẹ của mẹ là bà ngoại.' },
    { sec: 'Gia đình', name: 'Câu 4', pts: 1,
      text: 'Anh trai của bố, em gọi là gì?',
      opts: o4('Cậu', 'Chú', 'Dượng', 'Bác (bác trai)'), ans: 'D',
      why: 'Anh trai của bố được gọi là bác (bác trai), thuộc họ nội.' },
    { sec: 'Gia đình', name: 'Câu 5', pts: 1,
      text: 'Con của bác, của cô, của chú là gì của em?',
      opts: o4('Anh, chị, em họ bên nội', 'Anh, chị, em họ bên ngoại', 'Người dưng', 'Hàng xóm'), ans: 'A',
      why: 'Bác, cô, chú là họ nội nên con của họ là anh chị em họ bên nội.' },
    { sec: 'Gia đình', name: 'Câu 6', pts: 1,
      text: 'Vì sao gia đình thường lưu giữ ảnh, kỉ vật cũ?',
      opts: o4('Để bán lấy tiền', 'Để làm rác', 'Để nhớ về kỉ niệm và người thân', 'Không có lí do gì'), ans: 'C',
      why: 'Ảnh và kỉ vật giúp lưu giữ kỉ niệm, gắn kết các thế hệ trong gia đình.' },
    { sec: 'Gia đình', name: 'Câu 7', pts: 1,
      text: 'Ngày nào là dịp cả họ tưởng nhớ người đã khuất?',
      opts: o4('Ngày sinh nhật của em', 'Ngày giỗ', 'Ngày khai giảng', 'Ngày Quốc tế Thiếu nhi'), ans: 'B',
      why: 'Ngày giỗ là dịp con cháu tưởng nhớ ông bà, tổ tiên đã mất.' },
    { sec: 'Gia đình', name: 'Câu 8', pts: 1,
      text: 'Khi ông bà ốm, em nên làm gì?',
      opts: o4('Bỏ mặc đi chơi', 'Trách ông bà', 'Làm ồn cho ông bà bực', 'Hỏi han, chăm sóc, lấy nước cho ông bà'), ans: 'D',
      why: 'Hỏi han, chăm sóc ông bà lúc ốm thể hiện tình yêu thương và sự hiếu thảo.' },
    { sec: 'Gia đình', name: 'Câu 9', pts: 1,
      text: 'Trong họ hàng, người nhiều tuổi nhất thường là ai?',
      opts: o4('Các em nhỏ', 'Các anh chị', 'Ông bà, cụ', 'Bố mẹ'), ans: 'C',
      why: 'Ông bà, cụ là các thế hệ đi trước nên nhiều tuổi nhất trong họ.' },
    { sec: 'Gia đình', name: 'Câu 10', pts: 1,
      text: 'Chồng của cô, em thường gọi là gì?',
      opts: o4('Dượng (chú)', 'Cậu', 'Bác gái', 'Thím'), ans: 'A',
      why: 'Chồng của cô thường được gọi là dượng (có nơi gọi là chú).' },
  ],
},

/* ═══════════ ĐỀ 12 — GIA ĐÌNH: PHÒNG CHÁY VÀ VỆ SINH NHÀ Ở ═══════════ */
{
  id: 8602, title: 'Đề 12 · Phòng cháy và giữ vệ sinh nhà ở', time: 15,
  questions: [
    { sec: 'An toàn', name: 'Câu 1', pts: 1,
      text: 'Việc nào KHÔNG an toàn, dễ gây cháy trong nhà?',
      opts: o4('Tắt bếp sau khi nấu', 'Đốt vàng mã gần rèm cửa, chăn màn', 'Cất diêm xa tầm trẻ nhỏ', 'Rút phích cắm khi không dùng'), ans: 'B',
      why: 'Đốt lửa gần rèm, chăn màn rất dễ bén lửa gây cháy.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Khi ngửi thấy mùi khí ga trong bếp, em nên làm gì đầu tiên?',
      opts: o4('Khoá van ga, mở cửa cho thoáng và báo người lớn', 'Bật công tắc điện xem sao', 'Bật bếp thử', 'Đóng kín hết cửa'), ans: 'A',
      why: 'Phải khoá van ga, mở cửa thông thoáng, không bật lửa hay công tắc điện vì dễ phát nổ.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Diêm, bật lửa nên được để ở đâu?',
      opts: o4('Trên sàn nhà', 'Gần bếp lửa', 'Xa tầm với của trẻ nhỏ', 'Trong túi áo trẻ em'), ans: 'C',
      why: 'Diêm, bật lửa phải cất xa tầm với trẻ nhỏ để tránh nghịch lửa gây cháy, bỏng.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Số điện thoại gọi cứu hoả khi có cháy là số nào?',
      opts: o4('113', '115', '111', '114'), ans: 'D',
      why: 'Gọi 114 để báo cháy cho lực lượng cứu hoả.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Nếu quần áo đang mặc bị bén lửa, em nên làm gì?',
      opts: o4('Dừng lại, nằm xuống và lăn tròn để dập lửa', 'Chạy thật nhanh cho lửa tắt', 'Vẫy tay cho lửa to lên', 'Cởi bỏ rồi chạy'), ans: 'A',
      why: 'Nguyên tắc "dừng lại – nằm xuống – lăn tròn" giúp dập lửa trên quần áo; chạy chỉ làm lửa cháy to hơn.' },
    { sec: 'Vệ sinh', name: 'Câu 6', pts: 1,
      text: 'Nhà cửa gọn gàng, sạch sẽ mang lại lợi ích gì?',
      opts: o4('Tốn nhiều tiền hơn', 'Khó ở hơn', 'Thoáng mát, dễ tìm đồ, ít bệnh tật', 'Không có lợi ích gì'), ans: 'C',
      why: 'Nhà sạch, gọn giúp không gian thoáng mát, dễ sinh hoạt và hạn chế mầm bệnh.' },
    { sec: 'Vệ sinh', name: 'Câu 7', pts: 1,
      text: 'Việc nào giúp giữ nhà bếp sạch sẽ?',
      opts: o4('Để thức ăn thừa qua nhiều ngày', 'Rửa bát ngay sau khi ăn, lau bếp', 'Vứt rác dưới gầm bếp', 'Không bao giờ lau dọn'), ans: 'B',
      why: 'Rửa bát, lau bếp thường xuyên giúp bếp sạch, tránh gián, chuột và mùi hôi.' },
    { sec: 'Vệ sinh', name: 'Câu 8', pts: 1,
      text: 'Nhà vệ sinh cần được giữ thế nào?',
      opts: o4('Để ẩm ướt, bẩn', 'Đổ rác vào bồn cầu', 'Không cần dọn', 'Sạch, khô, có nắp đậy và cọ rửa thường xuyên'), ans: 'D',
      why: 'Nhà vệ sinh sạch, khô, được cọ rửa thường xuyên giúp phòng bệnh và khử mùi.' },
    { sec: 'Vệ sinh', name: 'Câu 9', pts: 1,
      text: 'Muốn không cho muỗi sinh sôi quanh nhà, em nên làm gì?',
      opts: o4('Để nước tù đọng lâu ngày', 'Vứt vỏ chai chứa nước ra vườn', 'Đổ nước đọng, đậy kín lu chum', 'Trồng thêm nước đọng'), ans: 'C',
      why: 'Muỗi đẻ trứng ở nước đọng, nên phải đổ nước đọng và đậy kín vật chứa nước.' },
    { sec: 'Vệ sinh', name: 'Câu 10', pts: 1,
      text: 'Là học sinh, em giúp giữ vệ sinh nhà ở bằng cách nào?',
      opts: o4('Quét nhà, gấp chăn màn, cất đồ đúng chỗ', 'Bày bừa đồ chơi khắp nhà', 'Vứt rác ra sàn', 'Để quần áo bẩn khắp nơi'), ans: 'A',
      why: 'Quét dọn, gấp chăn màn và cất đồ gọn gàng là việc vừa sức giúp nhà sạch đẹp.' },
  ],
},

/* ═══════════ ĐỀ 13 — TRƯỜNG HỌC: HOẠT ĐỘNG KẾT NỐI VÀ AN TOÀN ═══════════ */
{
  id: 8603, title: 'Đề 13 · Hoạt động kết nối và an toàn ở trường', time: 15,
  questions: [
    { sec: 'Trường học', name: 'Câu 1', pts: 1,
      text: 'Hoạt động nào giúp học sinh gắn bó với cộng đồng?',
      opts: o4('Trốn học đi chơi', 'Thăm và tặng quà gia đình thương binh, liệt sĩ', 'Vẽ bậy lên tường', 'Chê bai hàng xóm'), ans: 'B',
      why: 'Thăm hỏi, tri ân gia đình chính sách là hoạt động kết nối trường học với cộng đồng.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Buổi sinh hoạt dưới cờ đầu tuần thường nhằm mục đích gì?',
      opts: o4('Nhận xét thi đua, phổ biến kế hoạch tuần', 'Chỉ để nghỉ ngơi', 'Để ăn quà', 'Để ngủ'), ans: 'A',
      why: 'Chào cờ đầu tuần là dịp nhận xét thi đua và phổ biến kế hoạch, nhắc nhở học sinh.' },
    { sec: 'Trường học', name: 'Câu 3', pts: 1,
      text: 'Khi tham gia lao động vệ sinh trường lớp, em nên thế nào?',
      opts: o4('Đứng xem bạn làm', 'Trốn việc', 'Tích cực, cẩn thận, giúp đỡ bạn', 'Làm qua loa'), ans: 'C',
      why: 'Tích cực, cẩn thận và biết giúp bạn giúp công việc chung tốt và an toàn.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Khi lên xuống cầu thang ở trường, em cần làm gì?',
      opts: o4('Chạy nhảy hai bậc một', 'Trượt tay vịn', 'Đùa giỡn, đẩy bạn', 'Đi bên phải, không chen lấn, xô đẩy'), ans: 'D',
      why: 'Đi bên phải, đi từng bậc, không xô đẩy giúp tránh ngã và tai nạn ở cầu thang.' },
    { sec: 'An toàn', name: 'Câu 5', pts: 1,
      text: 'Vật nào ở trường có thể gây nguy hiểm nếu nghịch phá?',
      opts: o4('Ổ điện, quạt trần, cửa kính', 'Quyển sách', 'Cái bút chì màu', 'Cục tẩy'), ans: 'A',
      why: 'Ổ điện, quạt trần, cửa kính có thể gây điện giật, thương tích nếu nghịch phá.' },
    { sec: 'An toàn', name: 'Câu 6', pts: 1,
      text: 'Khi bị đứt tay chảy máu nhẹ ở lớp, em nên làm gì?',
      opts: o4('Giấu đi, không nói ai', 'Bôi bùn đất vào', 'Báo thầy cô và tới phòng y tế', 'Tiếp tục chơi'), ans: 'C',
      why: 'Cần báo thầy cô và tới phòng y tế để được sơ cứu, sát trùng đúng cách.' },
    { sec: 'An toàn', name: 'Câu 7', pts: 1,
      text: 'Sân trường ướt trơn sau mưa, em nên làm gì?',
      opts: o4('Chạy đùa thật nhanh', 'Đi chậm, cẩn thận, tránh chỗ trơn', 'Trượt cho vui', 'Đá bóng ngay'), ans: 'B',
      why: 'Sàn trơn dễ ngã, cần đi chậm và tránh chỗ đọng nước để giữ an toàn.' },
    { sec: 'An toàn', name: 'Câu 8', pts: 1,
      text: 'Trò chơi nào an toàn khi chơi ở sân trường?',
      opts: o4('Leo lên nóc nhà', 'Ném đá vào nhau', 'Trèo cổng trường', 'Nhảy dây, đá cầu ở khu vực cho phép'), ans: 'D',
      why: 'Nhảy dây, đá cầu ở đúng khu vực là trò chơi lành mạnh và an toàn.' },
    { sec: 'Trường học', name: 'Câu 9', pts: 1,
      text: 'Khi có bạn mới chuyển đến lớp, em nên làm gì?',
      opts: o4('Xa lánh bạn', 'Chế giễu bạn', 'Làm quen, giúp bạn hoà nhập', 'Không nói chuyện'), ans: 'C',
      why: 'Làm quen và giúp đỡ bạn mới thể hiện tình đoàn kết, giúp bạn nhanh hoà nhập.' },
    { sec: 'Trường học', name: 'Câu 10', pts: 1,
      text: 'Ngày Nhà giáo Việt Nam là ngày nào?',
      opts: o4('Ngày 20/11', 'Ngày 8/3', 'Ngày 1/6', 'Ngày 2/9'), ans: 'A',
      why: 'Ngày 20/11 là Ngày Nhà giáo Việt Nam, dịp tri ân thầy cô.' },
  ],
},

/* ═══════════ ĐỀ 14 — TRƯỜNG HỌC: PHÒNG TRÁNH TAI NẠN VÀ VỆ SINH ═══════════ */
{
  id: 8604, title: 'Đề 14 · Phòng tránh tai nạn và vệ sinh ở trường', time: 15,
  questions: [
    { sec: 'An toàn', name: 'Câu 1', pts: 1,
      text: 'Vì sao không nên chạy nhảy trong lớp học?',
      opts: o4('Vì tốn sức', 'Dễ va vào bàn ghế, ngã và làm bạn bị thương', 'Vì làm bẩn giày', 'Không sao cả'), ans: 'B',
      why: 'Lớp học chật, chạy nhảy dễ va bàn ghế, ngã và gây thương tích cho mình và bạn.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Khi dùng kéo, dao thủ công trong giờ học, em cần thế nào?',
      opts: o4('Cầm cẩn thận, không chĩa vào bạn', 'Vung vẩy cho vui', 'Ném cho bạn', 'Chạy khi cầm kéo'), ans: 'A',
      why: 'Dùng kéo, dao phải cẩn thận, không chĩa vào người khác và không chạy khi cầm.' },
    { sec: 'An toàn', name: 'Câu 3', pts: 1,
      text: 'Không nên cho vật nhỏ (viên bi, hạt) vào đâu để tránh nguy hiểm?',
      opts: o4('Vào hộp bút', 'Vào cặp sách', 'Vào mũi, tai, miệng', 'Vào ngăn bàn'), ans: 'C',
      why: 'Nhét vật nhỏ vào mũi, tai, miệng rất nguy hiểm, có thể gây hóc, nghẹt thở.' },
    { sec: 'An toàn', name: 'Câu 4', pts: 1,
      text: 'Khi thấy dây điện hở ở lớp, em nên làm gì?',
      opts: o4('Sờ thử xem có điện không', 'Kéo dây ra chơi', 'Cắm thêm đồ vào', 'Tránh xa và báo ngay thầy cô'), ans: 'D',
      why: 'Dây điện hở dễ gây điện giật; phải tránh xa và báo thầy cô để xử lí.' },
    { sec: 'Vệ sinh', name: 'Câu 5', pts: 1,
      text: 'Trước khi ăn và sau khi đi vệ sinh, em cần làm gì?',
      opts: o4('Rửa tay bằng xà phòng', 'Chỉ lau vào áo', 'Không cần rửa', 'Rửa tay bằng nước bẩn'), ans: 'A',
      why: 'Rửa tay bằng xà phòng loại bỏ vi khuẩn, phòng bệnh đường ruột.' },
    { sec: 'Vệ sinh', name: 'Câu 6', pts: 1,
      text: 'Vỏ hộp sữa, giấy vụn sau giờ ăn nên bỏ vào đâu?',
      opts: o4('Ngăn bàn', 'Gầm ghế', 'Thùng rác đúng nơi quy định', 'Ném ra sân'), ans: 'C',
      why: 'Bỏ rác vào thùng đúng nơi quy định giúp lớp học và trường sạch sẽ.' },
    { sec: 'Vệ sinh', name: 'Câu 7', pts: 1,
      text: 'Lớp học sạch, đủ ánh sáng và thoáng khí giúp em điều gì?',
      opts: o4('Buồn ngủ hơn', 'Học tập tốt và bảo vệ mắt, sức khoẻ', 'Mắt kém đi', 'Không ảnh hưởng gì'), ans: 'B',
      why: 'Lớp sạch, sáng, thoáng giúp học tập tập trung và bảo vệ mắt, sức khoẻ.' },
    { sec: 'Vệ sinh', name: 'Câu 8', pts: 1,
      text: 'Việc nào giúp giữ vệ sinh chung ở nhà vệ sinh trường?',
      opts: o4('Vẽ bậy lên tường', 'Vứt giấy bừa bãi', 'Để vòi nước chảy tràn', 'Đi đúng chỗ, dội nước, rửa tay sau đó'), ans: 'D',
      why: 'Đi đúng chỗ, dội nước và rửa tay giúp nhà vệ sinh trường sạch và tiết kiệm nước.' },
    { sec: 'An toàn', name: 'Câu 9', pts: 1,
      text: 'Khi ra chơi thấy trời nắng gắt, em nên chơi ở đâu?',
      opts: o4('Giữa sân nắng gắt', 'Trên mái nhà', 'Nơi có bóng mát, tránh nắng lâu', 'Ngoài cổng trường'), ans: 'C',
      why: 'Chơi ở nơi bóng mát tránh say nắng, bảo vệ sức khoẻ khi trời nắng gắt.' },
    { sec: 'An toàn', name: 'Câu 10', pts: 1,
      text: 'Khi tan học, em nên ra về thế nào cho an toàn?',
      opts: o4('Xếp hàng, đi theo hướng dẫn, không chen lấn', 'Xô đẩy để ra trước', 'Chạy băng qua đường', 'Đùa giỡn ở cổng'), ans: 'A',
      why: 'Xếp hàng trật tự, đi đúng hướng dẫn giúp tan học an toàn, tránh chen lấn té ngã.' },
  ],
},

/* ═══════════ ĐỀ 15 — CỘNG ĐỒNG: HOẠT ĐỘNG SẢN XUẤT ═══════════ */
{
  id: 8605, title: 'Đề 15 · Hoạt động sản xuất ở địa phương', time: 15,
  questions: [
    { sec: 'Sản xuất', name: 'Câu 1', pts: 1,
      text: 'Nghề trồng chè, trồng cà phê thuộc hoạt động sản xuất nào?',
      opts: o4('Công nghiệp', 'Nông nghiệp', 'Thủ công', 'Dịch vụ'), ans: 'B',
      why: 'Trồng chè, cà phê là trồng trọt, thuộc sản xuất nông nghiệp.' },
    { sec: 'Sản xuất', name: 'Câu 2', pts: 1,
      text: 'Nhà máy làm ra xi măng, sắt thép thuộc ngành nào?',
      opts: o4('Công nghiệp', 'Nông nghiệp', 'Thủ công', 'Đánh cá'), ans: 'A',
      why: 'Sản xuất xi măng, sắt thép bằng máy móc trong nhà máy là công nghiệp.' },
    { sec: 'Sản xuất', name: 'Câu 3', pts: 1,
      text: 'Nghề nào tạo ra sản phẩm chủ yếu bằng bàn tay khéo léo?',
      opts: o4('Khai thác dầu mỏ', 'Luyện thép', 'Nghề thủ công (đan lát, làm gốm)', 'Sản xuất ô tô'), ans: 'C',
      why: 'Nghề thủ công như đan lát, làm gốm chủ yếu dùng bàn tay khéo léo của người thợ.' },
    { sec: 'Sản xuất', name: 'Câu 4', pts: 1,
      text: 'Sản phẩm nào KHÔNG phải của nông nghiệp?',
      opts: o4('Lúa gạo', 'Rau xanh', 'Trái cây', 'Máy giặt'), ans: 'D',
      why: 'Máy giặt là sản phẩm công nghiệp; lúa gạo, rau, trái cây là nông sản.' },
    { sec: 'Sản xuất', name: 'Câu 5', pts: 1,
      text: 'Người nông dân cần điều kiện tự nhiên nào để trồng trọt?',
      opts: o4('Đất, nước, ánh nắng', 'Máy tính', 'Nhà cao tầng', 'Ô tô'), ans: 'A',
      why: 'Cây trồng cần đất tốt, nước và ánh nắng để sinh trưởng.' },
    { sec: 'Sản xuất', name: 'Câu 6', pts: 1,
      text: 'Vùng biển nước ta phát triển mạnh nghề gì?',
      opts: o4('Trồng lúa nương', 'Khai thác than', 'Đánh bắt và nuôi trồng thuỷ sản, làm muối', 'Dệt lụa'), ans: 'C',
      why: 'Vùng ven biển thuận lợi cho đánh bắt, nuôi thuỷ sản và làm muối.' },
    { sec: 'Sản xuất', name: 'Câu 7', pts: 1,
      text: 'Làng gốm Bát Tràng nổi tiếng với nghề gì?',
      opts: o4('Dệt vải', 'Làm gốm sứ', 'Đúc đồng', 'Làm nón lá'), ans: 'B',
      why: 'Bát Tràng là làng nghề nổi tiếng về gốm sứ.' },
    { sec: 'Sản xuất', name: 'Câu 8', pts: 1,
      text: 'Vì sao mỗi vùng thường có hoạt động sản xuất khác nhau?',
      opts: o4('Do người dân lười', 'Do không có lí do', 'Do thời tiết giống nhau', 'Do điều kiện tự nhiên và nghề truyền thống khác nhau'), ans: 'D',
      why: 'Mỗi vùng có đất đai, khí hậu, nghề truyền thống riêng nên sản xuất khác nhau.' },
    { sec: 'Sản xuất', name: 'Câu 9', pts: 1,
      text: 'Từ hạt lúa muốn thành cơm cần trải qua công đoạn nào trước?',
      opts: o4('Đem đi may quần áo', 'Nung thành gạch', 'Xay xát thành gạo', 'Đúc thành sắt'), ans: 'C',
      why: 'Lúa được xay xát bỏ vỏ thành gạo, rồi mới nấu thành cơm.' },
    { sec: 'Sản xuất', name: 'Câu 10', pts: 1,
      text: 'Để tỏ lòng biết ơn người làm ra hạt gạo, em nên làm gì?',
      opts: o4('Ăn hết suất, không bỏ phí cơm', 'Đổ cơm thừa đi', 'Nghịch phá thức ăn', 'Chê cơm dở rồi vứt'), ans: 'A',
      why: 'Ăn hết suất, không lãng phí cơm là cách trân trọng công sức người nông dân.' },
  ],
},

/* ═══════════ ĐỀ 16 — CỘNG ĐỒNG: DI TÍCH, CẢNH QUAN VÀ VỆ SINH CÔNG CỘNG ═══════════ */
{
  id: 8606, title: 'Đề 16 · Di tích, cảnh quan và vệ sinh nơi công cộng', time: 15,
  questions: [
    { sec: 'Cộng đồng', name: 'Câu 1', pts: 1,
      text: 'Chùa Một Cột nằm ở thành phố nào?',
      opts: o4('Huế', 'Hà Nội', 'Đà Nẵng', 'Cần Thơ'), ans: 'B',
      why: 'Chùa Một Cột là di tích nổi tiếng ở Thủ đô Hà Nội.' },
    { sec: 'Cộng đồng', name: 'Câu 2', pts: 1,
      text: 'Cố đô Huế từng là kinh đô của triều đại nào?',
      opts: o4('Triều Nguyễn', 'Người ngoài hành tinh', 'Nước ngoài', 'Không của ai'), ans: 'A',
      why: 'Cố đô Huế là kinh đô của triều Nguyễn, nay là di sản văn hoá.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Nơi công cộng như công viên, bến xe cần được giữ thế nào?',
      opts: o4('Xả rác thoải mái', 'Vẽ bậy lên ghế', 'Sạch sẽ, bỏ rác đúng chỗ', 'Bẻ cây, hái hoa'), ans: 'C',
      why: 'Giữ nơi công cộng sạch, bỏ rác đúng chỗ giúp mọi người cùng được hưởng.' },
    { sec: 'Cộng đồng', name: 'Câu 4', pts: 1,
      text: 'Hành động nào làm mất vệ sinh nơi công cộng?',
      opts: o4('Bỏ rác vào thùng', 'Xếp hàng trật tự', 'Đi vệ sinh đúng nơi', 'Nhổ bã kẹo cao su ra đường'), ans: 'D',
      why: 'Nhổ bã kẹo, khạc nhổ, xả rác ra đường làm mất vệ sinh nơi công cộng.' },
    { sec: 'Cộng đồng', name: 'Câu 5', pts: 1,
      text: 'Khi tham quan bảo tàng, em nên làm gì với hiện vật?',
      opts: o4('Không sờ, không lấy, giữ khoảng cách', 'Cầm lên xem kĩ', 'Mang về nhà', 'Vẽ lên hiện vật'), ans: 'A',
      why: 'Hiện vật là tài sản quý, chỉ nên ngắm, không sờ hay lấy để giữ gìn lâu dài.' },
    { sec: 'Cộng đồng', name: 'Câu 6', pts: 1,
      text: 'Vịnh Hạ Long nổi tiếng với cảnh gì?',
      opts: o4('Sa mạc cát', 'Núi lửa', 'Hàng nghìn hòn đảo đá trên biển', 'Đồng cỏ khô'), ans: 'C',
      why: 'Vịnh Hạ Long có hàng nghìn hòn đảo đá vôi trên biển, là kì quan thiên nhiên.' },
    { sec: 'Cộng đồng', name: 'Câu 7', pts: 1,
      text: 'Trồng cây xanh nơi công cộng có lợi ích gì?',
      opts: o4('Gây bụi bẩn', 'Cho bóng mát, làm sạch không khí', 'Làm nóng thêm', 'Không có lợi'), ans: 'B',
      why: 'Cây xanh nơi công cộng cho bóng mát, lọc bụi và làm không khí trong lành.' },
    { sec: 'Cộng đồng', name: 'Câu 8', pts: 1,
      text: 'Vì sao cần bảo vệ cảnh quan thiên nhiên của quê hương?',
      opts: o4('Vì không ai cần', 'Vì để phá bỏ', 'Vì cản trở xây nhà', 'Vì đó là tài sản chung, làm quê thêm đẹp'), ans: 'D',
      why: 'Cảnh quan đẹp là tài sản chung, làm quê hương đẹp và thu hút du khách.' },
    { sec: 'Cộng đồng', name: 'Câu 9', pts: 1,
      text: 'Khi thấy bạn vứt rác bừa bãi ở công viên, em nên làm gì?',
      opts: o4('Vứt thêm cho vui', 'Cười cợt', 'Nhắc bạn nhặt rác bỏ vào thùng', 'Mặc kệ'), ans: 'C',
      why: 'Nên nhắc nhở bạn nhặt rác bỏ đúng chỗ để cùng giữ nơi công cộng sạch đẹp.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Việc nào thể hiện em yêu quê hương?',
      opts: o4('Giữ gìn di tích, cảnh quan và giới thiệu với bạn bè', 'Phá hoại di tích', 'Xả rác bừa bãi', 'Chê bai quê mình'), ans: 'A',
      why: 'Giữ gìn, tự hào và giới thiệu di tích, cảnh quan là biểu hiện yêu quê hương.' },
  ],
},

/* ═══════════ ĐỀ 17 — CỘNG ĐỒNG: AN TOÀN GIAO THÔNG ═══════════ */
{
  id: 8607, title: 'Đề 17 · An toàn giao thông', time: 15,
  questions: [
    { sec: 'Giao thông', name: 'Câu 1', pts: 1,
      text: 'Đèn tín hiệu giao thông màu đỏ có nghĩa là gì?',
      opts: o4('Được đi', 'Dừng lại', 'Đi nhanh lên', 'Chuẩn bị đi'), ans: 'B',
      why: 'Đèn đỏ báo hiệu phải dừng lại.' },
    { sec: 'Giao thông', name: 'Câu 2', pts: 1,
      text: 'Đèn tín hiệu màu xanh có nghĩa là gì?',
      opts: o4('Được phép đi', 'Dừng lại', 'Lùi lại', 'Bấm còi'), ans: 'A',
      why: 'Đèn xanh cho phép các phương tiện và người đi bộ được đi.' },
    { sec: 'Giao thông', name: 'Câu 3', pts: 1,
      text: 'Người đi bộ nên đi ở đâu trên đường?',
      opts: o4('Giữa lòng đường', 'Trên đường ray', 'Trên vỉa hè hoặc sát lề bên phải', 'Chỗ nào cũng được'), ans: 'C',
      why: 'Người đi bộ đi trên vỉa hè; nơi không có vỉa hè thì đi sát lề đường bên phải.' },
    { sec: 'Giao thông', name: 'Câu 4', pts: 1,
      text: 'Muốn sang đường, em nên đi ở đâu?',
      opts: o4('Bất cứ chỗ nào', 'Nơi khuất tầm nhìn', 'Giữa dòng xe', 'Vạch kẻ dành cho người đi bộ'), ans: 'D',
      why: 'Sang đường ở vạch kẻ đường (vạch trắng) và quan sát kĩ hai bên cho an toàn.' },
    { sec: 'Giao thông', name: 'Câu 5', pts: 1,
      text: 'Khi ngồi trên xe máy, em cần làm gì để an toàn?',
      opts: o4('Đội mũ bảo hiểm và ngồi ngay ngắn', 'Đứng trên yên', 'Thò tay chân ra ngoài', 'Không cần đội mũ'), ans: 'A',
      why: 'Đội mũ bảo hiểm và ngồi ngay ngắn giúp bảo vệ đầu, tránh nguy hiểm khi va chạm.' },
    { sec: 'Giao thông', name: 'Câu 6', pts: 1,
      text: 'Khi đi bộ qua đường ở nơi không có đèn, em nên làm gì?',
      opts: o4('Chạy nhanh bất ngờ', 'Vừa đi vừa xem điện thoại', 'Quan sát trái – phải, chờ vắng xe rồi qua', 'Nhắm mắt băng qua'), ans: 'C',
      why: 'Phải nhìn trái – phải, chờ đường vắng và đi thẳng qua, không chạy bất ngờ.' },
    { sec: 'Giao thông', name: 'Câu 7', pts: 1,
      text: 'Đi xe đạp trên đường, em nên đi thế nào?',
      opts: o4('Đi hàng ba, hàng bốn', 'Đi đúng phần đường, sát lề phải', 'Buông cả hai tay', 'Đua xe với bạn'), ans: 'B',
      why: 'Đi xe đạp phải đi sát lề phải, đúng phần đường, không dàn hàng hay buông tay.' },
    { sec: 'Giao thông', name: 'Câu 8', pts: 1,
      text: 'Hành động nào KHÔNG an toàn khi tham gia giao thông?',
      opts: o4('Đội mũ bảo hiểm', 'Đi trên vỉa hè', 'Chờ đèn xanh', 'Chơi đùa, đá bóng dưới lòng đường'), ans: 'D',
      why: 'Chơi đùa, đá bóng dưới lòng đường rất nguy hiểm, dễ bị xe đâm.' },
    { sec: 'Giao thông', name: 'Câu 9', pts: 1,
      text: 'Khi ngồi trong ô tô, em nên làm gì?',
      opts: o4('Mở cửa khi xe chạy', 'Đứng lên ghế', 'Thắt dây an toàn, không thò đầu ra ngoài', 'Thò tay ra ngoài'), ans: 'C',
      why: 'Thắt dây an toàn và ngồi yên trong xe giúp tránh chấn thương khi phanh gấp.' },
    { sec: 'Giao thông', name: 'Câu 10', pts: 1,
      text: 'Vì sao phải tuân theo luật giao thông?',
      opts: o4('Để bảo vệ an toàn cho mình và mọi người', 'Để đi chậm hơn', 'Vì bị bắt buộc vô ích', 'Không cần lí do'), ans: 'A',
      why: 'Tuân theo luật giao thông giúp mọi người đi lại an toàn, tránh tai nạn.' },
  ],
},

/* ═══════════ ĐỀ 18 — THỰC VẬT: BỘ PHẬN VÀ CHỨC NĂNG ═══════════ */
{
  id: 8608, title: 'Đề 18 · Bộ phận của cây và chức năng', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Một cây xanh đầy đủ thường có các bộ phận nào?',
      opts: o4('Chỉ có lá', 'Rễ, thân, lá, hoa, quả', 'Chỉ có rễ', 'Chỉ có hoa'), ans: 'B',
      why: 'Cây đầy đủ gồm rễ, thân, lá, hoa và quả (có hạt).' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Bộ phận nào của cây hút nước từ trong đất?',
      opts: o4('Rễ', 'Lá', 'Hoa', 'Quả'), ans: 'A',
      why: 'Rễ cắm xuống đất, hút nước và chất khoáng nuôi cây.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Cây nào có thân leo?',
      opts: o4('Cây bàng', 'Cây phượng', 'Cây mướp, cây bầu', 'Cây dừa'), ans: 'C',
      why: 'Mướp, bầu là cây thân leo, phải bò lên giàn hoặc bám vào vật khác.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Cây nào có thân gỗ to, cao?',
      opts: o4('Cây rau muống', 'Cây cỏ', 'Cây lúa', 'Cây lim, cây bàng'), ans: 'D',
      why: 'Lim, bàng là cây thân gỗ to, cao và sống lâu năm.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Lá cây thường có màu gì và nhờ đâu quang hợp được?',
      opts: o4('Màu xanh, nhờ chất diệp lục', 'Màu đỏ, nhờ nước', 'Màu trắng, nhờ đất', 'Màu đen, nhờ gió'), ans: 'A',
      why: 'Lá có màu xanh nhờ chất diệp lục, giúp hấp thụ ánh sáng để quang hợp.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Sau khi hoa thụ phấn, bộ phận nào sẽ hình thành?',
      opts: o4('Rễ mới', 'Thân mới', 'Quả và hạt', 'Lá non'), ans: 'C',
      why: 'Hoa được thụ phấn rồi phát triển thành quả chứa hạt.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Cây cần những gì để sống và lớn lên?',
      opts: o4('Chỉ cần bóng tối', 'Ánh sáng, nước, không khí và chất dinh dưỡng', 'Chỉ cần đá', 'Không cần gì'), ans: 'B',
      why: 'Cây cần ánh sáng, nước, không khí và chất dinh dưỡng trong đất để sống.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Cây nào ta ăn phần hoa?',
      opts: o4('Cà rốt', 'Mía', 'Khoai lang', 'Súp lơ (bông cải)'), ans: 'D',
      why: 'Súp lơ (bông cải) là phần cụm hoa của cây được dùng làm thức ăn.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Nếu thiếu ánh sáng lâu ngày, cây xanh sẽ thế nào?',
      opts: o4('Lớn nhanh hơn', 'Xanh tốt hơn', 'Còi cọc, vàng úa và có thể chết', 'Không thay đổi'), ans: 'C',
      why: 'Thiếu ánh sáng, cây không quang hợp đủ nên còi cọc, vàng lá và dễ chết.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Bộ phận nào giúp cây đứng vững và vươn lên đón nắng?',
      opts: o4('Thân cây', 'Quả', 'Hạt', 'Hoa'), ans: 'A',
      why: 'Thân nâng đỡ cây, đưa cành lá vươn lên cao để đón ánh nắng.' },
  ],
},

/* ═══════════ ĐỀ 19 — THỰC VẬT: ÍCH LỢI, CHĂM SÓC VÀ BẢO VỆ ═══════════ */
{
  id: 8609, title: 'Đề 19 · Ích lợi và bảo vệ cây xanh', time: 15,
  questions: [
    { sec: 'Thực vật', name: 'Câu 1', pts: 1,
      text: 'Cây xanh mang lại lợi ích nào cho con người?',
      opts: o4('Gây ô nhiễm', 'Cho bóng mát, gỗ, quả và không khí trong lành', 'Làm nóng thêm', 'Không có lợi ích'), ans: 'B',
      why: 'Cây cho bóng mát, gỗ, hoa quả, thức ăn và nhả ô-xi làm sạch không khí.' },
    { sec: 'Thực vật', name: 'Câu 2', pts: 1,
      text: 'Rừng có vai trò quan trọng nào?',
      opts: o4('Giữ đất, giữ nước, chống lũ và cho nhiều gỗ', 'Gây lũ lụt', 'Làm khô hạn', 'Không có tác dụng'), ans: 'A',
      why: 'Rừng giữ đất chống xói mòn, giữ nước, hạn chế lũ và cung cấp gỗ, dược liệu.' },
    { sec: 'Thực vật', name: 'Câu 3', pts: 1,
      text: 'Để cây trồng phát triển tốt, em cần làm gì?',
      opts: o4('Bỏ mặc không chăm', 'Bẻ hết lá', 'Tưới nước, bón phân, nhổ cỏ, bắt sâu', 'Đổ nước sôi vào gốc'), ans: 'C',
      why: 'Tưới nước, bón phân, nhổ cỏ và bắt sâu giúp cây khoẻ và cho nhiều hoa trái.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Việc làm nào bảo vệ cây xanh?',
      opts: o4('Bẻ cành làm roi', 'Khắc tên lên cây', 'Chặt cây non', 'Không bẻ cành, không khắc lên thân cây'), ans: 'D',
      why: 'Không bẻ cành, không khắc vẽ, không chặt phá là cách bảo vệ cây xanh.' },
    { sec: 'Thực vật', name: 'Câu 5', pts: 1,
      text: 'Có loại cây nào gây hại nếu ăn phải?',
      opts: o4('Một số nấm và quả dại có độc', 'Cây rau cải', 'Cây cà chua', 'Cây chuối'), ans: 'A',
      why: 'Một số nấm lạ, quả dại có chất độc; không được tự ý hái ăn khi chưa biết rõ.' },
    { sec: 'Thực vật', name: 'Câu 6', pts: 1,
      text: 'Vì sao nên trồng nhiều cây xanh ở trường và khu phố?',
      opts: o4('Cho tốn đất', 'Để che khuất tầm nhìn', 'Tạo bóng mát, làm đẹp và trong lành không khí', 'Không vì lí do gì'), ans: 'C',
      why: 'Cây xanh cho bóng mát, làm đẹp cảnh quan và giúp không khí trong lành hơn.' },
    { sec: 'Thực vật', name: 'Câu 7', pts: 1,
      text: 'Hành động nào có hại cho cây xanh và môi trường?',
      opts: o4('Trồng thêm cây', 'Đốt rừng làm rẫy', 'Tưới nước cho cây', 'Nhặt lá khô ủ phân'), ans: 'B',
      why: 'Đốt rừng làm rẫy phá hủy cây, gây cháy, xói mòn đất và mất nơi ở của muông thú.' },
    { sec: 'Thực vật', name: 'Câu 8', pts: 1,
      text: 'Cây thuốc (cây dược liệu) như cây tía tô, bạc hà dùng để làm gì?',
      opts: o4('Làm bàn ghế', 'Làm gạch', 'Làm xăng dầu', 'Làm thuốc, chữa bệnh nhẹ'), ans: 'D',
      why: 'Nhiều cây như tía tô, bạc hà là cây thuốc, giúp chữa một số bệnh thông thường.' },
    { sec: 'Thực vật', name: 'Câu 9', pts: 1,
      text: 'Để có cây mới, người ta thường làm gì?',
      opts: o4('Chờ cây tự bay tới', 'Vẽ cây ra giấy', 'Gieo hạt hoặc giâm, chiết cành', 'Mua khói về'), ans: 'C',
      why: 'Người ta gieo hạt hoặc giâm, chiết cành để trồng và nhân giống cây mới.' },
    { sec: 'Thực vật', name: 'Câu 10', pts: 1,
      text: 'Là học sinh, em góp phần bảo vệ cây xanh bằng cách nào?',
      opts: o4('Chăm sóc cây ở trường, không giẫm lên bồn hoa', 'Ngắt hoa bẻ lá', 'Giẫm lên cỏ non', 'Vứt rác vào gốc cây'), ans: 'A',
      why: 'Chăm sóc cây, không giẫm bồn hoa, không bẻ cành là việc vừa sức bảo vệ cây xanh.' },
  ],
},

/* ═══════════ ĐỀ 20 — ĐỘNG VẬT: BỘ PHẬN VÀ CHỨC NĂNG ═══════════ */
{
  id: 8610, title: 'Đề 20 · Bộ phận của con vật và chức năng', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào có 8 chân?',
      opts: o4('Con gà', 'Con nhện', 'Con bò', 'Con cá'), ans: 'B',
      why: 'Nhện có 8 chân (không phải côn trùng 6 chân).' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Bộ phận nào giúp con voi lấy thức ăn và uống nước?',
      opts: o4('Cái vòi', 'Cái đuôi', 'Cái tai', 'Bốn chân'), ans: 'A',
      why: 'Voi dùng vòi dài để lấy thức ăn, hút nước và ngửi mùi.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Ếch di chuyển trên cạn chủ yếu bằng cách nào?',
      opts: o4('Bay bằng cánh', 'Bơi bằng vây', 'Nhảy bằng hai chân sau', 'Bò bằng bụng'), ans: 'C',
      why: 'Ếch có hai chân sau khoẻ, dài, dùng để nhảy trên cạn.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Con vật nào vừa sống được dưới nước, vừa lên cạn?',
      opts: o4('Con gà', 'Con chim sẻ', 'Con hổ', 'Con ếch'), ans: 'D',
      why: 'Ếch là loài lưỡng cư, sống được cả dưới nước và trên cạn.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Bộ phận nào giúp con chó, con mèo nghe âm thanh?',
      opts: o4('Đôi tai', 'Đuôi', 'Móng vuốt', 'Ria mép'), ans: 'A',
      why: 'Đôi tai giúp con vật nghe được âm thanh xung quanh.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Lông vũ dày giúp chim làm gì?',
      opts: o4('Để bơi dưới bùn', 'Để đào đất', 'Giữ ấm cơ thể và giúp bay', 'Không có tác dụng'), ans: 'C',
      why: 'Lông vũ giúp chim giữ ấm cơ thể và tạo lực nâng khi bay.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Rắn di chuyển bằng cách nào?',
      opts: o4('Nhảy bằng chân', 'Trườn, bò bằng thân mình', 'Bay bằng cánh', 'Bơi bằng vây'), ans: 'B',
      why: 'Rắn không có chân, di chuyển bằng cách trườn, uốn lượn thân mình.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Con vật nào có mai cứng để bảo vệ cơ thể?',
      opts: o4('Con thỏ', 'Con chim', 'Con ngựa', 'Con rùa'), ans: 'D',
      why: 'Rùa có mai cứng bao bọc, giúp bảo vệ cơ thể khỏi kẻ thù.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Bộ phận nào giúp con trâu, con bò nhai lại và ăn cỏ?',
      opts: o4('Cái sừng', 'Cái đuôi', 'Miệng và hàm răng', 'Bốn chân'), ans: 'C',
      why: 'Trâu, bò dùng miệng và hàm răng để gặm, nhai cỏ.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Vì sao mỗi con vật có hình dạng, bộ phận khác nhau?',
      opts: o4('Để phù hợp với nơi sống và cách kiếm ăn', 'Do ngẫu nhiên vô nghĩa', 'Để giống hệt nhau', 'Không vì lí do gì'), ans: 'A',
      why: 'Cấu tạo cơ thể mỗi loài phù hợp với môi trường sống và cách kiếm ăn của chúng.' },
  ],
},

/* ═══════════ ĐỀ 21 — ĐỘNG VẬT: ÍCH LỢI, TÁC HẠI VÀ BẢO VỆ ═══════════ */
{
  id: 8611, title: 'Đề 21 · Ích lợi, tác hại và bảo vệ con vật', time: 15,
  questions: [
    { sec: 'Động vật', name: 'Câu 1', pts: 1,
      text: 'Con vật nào giúp bắt chuột, bảo vệ mùa màng?',
      opts: o4('Con muỗi', 'Con mèo, con rắn, con cú', 'Con gián', 'Con ruồi'), ans: 'B',
      why: 'Mèo, rắn, cú bắt chuột nên giúp bảo vệ mùa màng và đồ ăn.' },
    { sec: 'Động vật', name: 'Câu 2', pts: 1,
      text: 'Con ong mang lại lợi ích gì?',
      opts: o4('Hút mật, thụ phấn cho hoa và cho mật ong', 'Phá hoại mùa màng', 'Truyền bệnh', 'Không có lợi'), ans: 'A',
      why: 'Ong lấy mật, giúp thụ phấn cho hoa kết quả và cho con người mật ong.' },
    { sec: 'Động vật', name: 'Câu 3', pts: 1,
      text: 'Con vật nào có hại vì truyền bệnh cho người?',
      opts: o4('Con bò', 'Con gà', 'Muỗi, ruồi, chuột', 'Con cá'), ans: 'C',
      why: 'Muỗi, ruồi, chuột mang mầm bệnh, có thể truyền bệnh nguy hiểm cho người.' },
    { sec: 'Động vật', name: 'Câu 4', pts: 1,
      text: 'Để phòng bệnh do muỗi truyền, em nên làm gì?',
      opts: o4('Nuôi thêm muỗi', 'Để nước tù đọng', 'Không mắc màn', 'Ngủ màn, diệt lăng quăng, dọn nước đọng'), ans: 'D',
      why: 'Ngủ màn, diệt lăng quăng và dọn nước đọng giúp phòng bệnh sốt xuất huyết.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con trâu, con bò giúp ích gì cho nhà nông?',
      opts: o4('Kéo cày, kéo xe, cho thịt và sữa', 'Phá hoại ruộng', 'Truyền bệnh', 'Không giúp gì'), ans: 'A',
      why: 'Trâu, bò kéo cày, kéo xe, cho thịt, sữa và sức lao động cho nhà nông.' },
    { sec: 'Động vật', name: 'Câu 6', pts: 1,
      text: 'Để vật nuôi khoẻ mạnh, cần làm gì?',
      opts: o4('Bỏ đói', 'Nhốt chuồng bẩn', 'Cho ăn đủ, giữ chuồng sạch, tiêm phòng', 'Đánh đập chúng'), ans: 'C',
      why: 'Cho ăn đủ, giữ chuồng sạch và tiêm phòng giúp vật nuôi khoẻ, ít bệnh.' },
    { sec: 'Động vật', name: 'Câu 7', pts: 1,
      text: 'Vì sao không nên săn bắt thú rừng bừa bãi?',
      opts: o4('Vì tốn công', 'Vì làm nhiều loài giảm số lượng, có nguy cơ tuyệt chủng', 'Vì thú xấu', 'Không vì lí do gì'), ans: 'B',
      why: 'Săn bắt bừa bãi khiến nhiều loài cạn kiệt, mất cân bằng tự nhiên và tuyệt chủng.' },
    { sec: 'Động vật', name: 'Câu 8', pts: 1,
      text: 'Khi gặp con vật lạ, con chó dữ, em nên làm gì?',
      opts: o4('Ném đá trêu', 'Chạy tới ôm', 'Kéo đuôi nó', 'Giữ khoảng cách, không trêu chọc'), ans: 'D',
      why: 'Không trêu chọc, giữ khoảng cách với con vật lạ hoặc dữ để tránh bị cắn, cào.' },
    { sec: 'Động vật', name: 'Câu 9', pts: 1,
      text: 'Nếu bị chó, mèo cắn hoặc cào chảy máu, em cần làm gì?',
      opts: o4('Giấu không nói', 'Tự băng rồi thôi', 'Rửa vết thương và báo người lớn đưa đi khám', 'Bôi đất vào'), ans: 'C',
      why: 'Phải rửa sạch vết thương và báo người lớn đưa đi khám để phòng bệnh dại.' },
    { sec: 'Động vật', name: 'Câu 10', pts: 1,
      text: 'Việc nào thể hiện em biết bảo vệ động vật?',
      opts: o4('Không phá tổ chim, không bắt cá con', 'Bắn chim bằng ná', 'Phá tổ chim', 'Bắt hết cá con'), ans: 'A',
      why: 'Không phá tổ chim, không bắt cá con là cách bảo vệ và duy trì các loài vật.' },
  ],
},

/* ═══════════ ĐỀ 22 — CON NGƯỜI: CƠ QUAN HÔ HẤP ═══════════ */
{
  id: 8612, title: 'Đề 22 · Cơ quan hô hấp', time: 15,
  questions: [
    { sec: 'Hô hấp', name: 'Câu 1', pts: 1,
      text: 'Cơ quan hô hấp gồm những bộ phận chính nào?',
      opts: o4('Tim và mạch máu', 'Mũi, khí quản, phế quản và hai lá phổi', 'Dạ dày và ruột', 'Não và tuỷ sống'), ans: 'B',
      why: 'Cơ quan hô hấp gồm mũi, khí quản, phế quản và hai lá phổi.' },
    { sec: 'Hô hấp', name: 'Câu 2', pts: 1,
      text: 'Cơ quan hô hấp có nhiệm vụ chính là gì?',
      opts: o4('Trao đổi khí: lấy ô-xi, thải khí các-bô-níc', 'Tiêu hoá thức ăn', 'Bơm máu', 'Điều khiển suy nghĩ'), ans: 'A',
      why: 'Hô hấp giúp cơ thể lấy khí ô-xi và thải ra khí các-bô-níc.' },
    { sec: 'Hô hấp', name: 'Câu 3', pts: 1,
      text: 'Khi hít vào, không khí đi vào cơ thể qua đâu trước?',
      opts: o4('Miệng dạ dày', 'Tai', 'Mũi', 'Mắt'), ans: 'C',
      why: 'Không khí thường đi vào qua mũi, được lọc sạch, sưởi ấm trước khi xuống phổi.' },
    { sec: 'Hô hấp', name: 'Câu 4', pts: 1,
      text: 'Vì sao nên thở bằng mũi, không nên thở bằng miệng?',
      opts: o4('Miệng thở nhanh hơn', 'Không có lí do', 'Để nói được', 'Mũi lọc sạch bụi và sưởi ấm không khí'), ans: 'D',
      why: 'Lông và niêm mạc trong mũi lọc bụi, sưởi ấm không khí trước khi vào phổi.' },
    { sec: 'Hô hấp', name: 'Câu 5', pts: 1,
      text: 'Hai lá phổi nằm ở phần nào của cơ thể?',
      opts: o4('Trong lồng ngực', 'Trong bụng', 'Ở tay', 'Ở chân'), ans: 'A',
      why: 'Hai lá phổi nằm trong lồng ngực, được xương sườn bảo vệ.' },
    { sec: 'Hô hấp', name: 'Câu 6', pts: 1,
      text: 'Việc nào giúp bảo vệ cơ quan hô hấp?',
      opts: o4('Hít khói thuốc lá', 'Ở nơi bụi bẩn', 'Đeo khẩu trang nơi nhiều bụi, giữ ấm cổ ngực', 'Không giữ ấm khi lạnh'), ans: 'C',
      why: 'Đeo khẩu trang, tránh khói bụi và giữ ấm giúp bảo vệ mũi, họng và phổi.' },
    { sec: 'Hô hấp', name: 'Câu 7', pts: 1,
      text: 'Khói thuốc lá ảnh hưởng thế nào tới cơ quan hô hấp?',
      opts: o4('Làm phổi khoẻ hơn', 'Gây hại phổi, dễ mắc bệnh đường hô hấp', 'Không ảnh hưởng', 'Giúp thở dễ hơn'), ans: 'B',
      why: 'Khói thuốc lá rất hại cho phổi, gây ho, viêm và nhiều bệnh hô hấp.' },
    { sec: 'Hô hấp', name: 'Câu 8', pts: 1,
      text: 'Khi ho, hắt hơi, em nên làm gì để giữ vệ sinh?',
      opts: o4('Quay vào mặt bạn', 'Không che gì', 'Khạc nhổ ra sàn', 'Che miệng, mũi bằng khuỷu tay hoặc khăn giấy'), ans: 'D',
      why: 'Che miệng mũi khi ho, hắt hơi giúp tránh lây bệnh cho người khác.' },
    { sec: 'Hô hấp', name: 'Câu 9', pts: 1,
      text: 'Bệnh nào là bệnh về đường hô hấp?',
      opts: o4('Đau bụng do ăn bẩn', 'Sâu răng', 'Viêm họng, viêm phổi, cảm cúm', 'Đau mắt'), ans: 'C',
      why: 'Viêm họng, viêm phổi, cảm cúm là các bệnh thường gặp ở đường hô hấp.' },
    { sec: 'Hô hấp', name: 'Câu 10', pts: 1,
      text: 'Để phổi khoẻ, em nên làm gì?',
      opts: o4('Tập thể dục, hít thở không khí trong lành', 'Ở lì trong phòng kín ngột ngạt', 'Hút thuốc', 'Chơi nơi nhiều khói bụi'), ans: 'A',
      why: 'Tập thể dục và hít thở không khí trong lành giúp phổi khoẻ, hô hấp tốt.' },
  ],
},

/* ═══════════ ĐỀ 23 — CON NGƯỜI: CƠ QUAN TUẦN HOÀN ═══════════ */
{
  id: 8613, title: 'Đề 23 · Cơ quan tuần hoàn', time: 15,
  questions: [
    { sec: 'Tuần hoàn', name: 'Câu 1', pts: 1,
      text: 'Cơ quan tuần hoàn gồm những bộ phận chính nào?',
      opts: o4('Mũi và phổi', 'Tim và các mạch máu', 'Dạ dày và ruột', 'Thận và bóng đái'), ans: 'B',
      why: 'Cơ quan tuần hoàn gồm tim và các mạch máu.' },
    { sec: 'Tuần hoàn', name: 'Câu 2', pts: 1,
      text: 'Tim nằm ở đâu và có nhiệm vụ gì?',
      opts: o4('Trong lồng ngực, co bóp bơm máu đi nuôi cơ thể', 'Trong bụng, tiêu hoá thức ăn', 'Ở đầu, để suy nghĩ', 'Ở tay, để cầm nắm'), ans: 'A',
      why: 'Tim nằm trong lồng ngực, hơi lệch trái, co bóp để bơm máu đi khắp cơ thể.' },
    { sec: 'Tuần hoàn', name: 'Câu 3', pts: 1,
      text: 'Máu có vai trò gì trong cơ thể?',
      opts: o4('Chỉ để làm màu đỏ', 'Không có vai trò gì', 'Mang ô-xi và chất dinh dưỡng đi nuôi cơ thể', 'Để tiêu hoá'), ans: 'C',
      why: 'Máu vận chuyển ô-xi, chất dinh dưỡng đến tế bào và mang chất thải đi.' },
    { sec: 'Tuần hoàn', name: 'Câu 4', pts: 1,
      text: 'Em có thể cảm nhận tim đập bằng cách nào?',
      opts: o4('Nhìn vào gương', 'Nghe bằng mắt', 'Ngửi bằng mũi', 'Đặt tay lên ngực trái hoặc bắt mạch ở cổ tay'), ans: 'D',
      why: 'Đặt tay lên ngực trái hoặc cổ tay, ta cảm nhận được nhịp tim (mạch đập).' },
    { sec: 'Tuần hoàn', name: 'Câu 5', pts: 1,
      text: 'Sau khi chạy nhanh, nhịp tim của em thay đổi thế nào?',
      opts: o4('Đập nhanh và mạnh hơn', 'Ngừng đập', 'Chậm hẳn lại', 'Không thay đổi'), ans: 'A',
      why: 'Khi vận động, cơ thể cần nhiều ô-xi nên tim đập nhanh và mạnh hơn.' },
    { sec: 'Tuần hoàn', name: 'Câu 6', pts: 1,
      text: 'Thức ăn nào tốt cho tim mạch?',
      opts: o4('Nhiều mỡ động vật', 'Đồ ăn quá mặn', 'Rau xanh, cá, trái cây', 'Nước ngọt có ga'), ans: 'C',
      why: 'Rau xanh, cá, trái cây tốt cho tim mạch; ăn nhiều mỡ, mặn thì có hại.' },
    { sec: 'Tuần hoàn', name: 'Câu 7', pts: 1,
      text: 'Việc nào giúp tim mạch khoẻ mạnh?',
      opts: o4('Lười vận động', 'Vận động đều đặn, ngủ đủ giấc', 'Thức khuya', 'Ăn quá no rồi nằm'), ans: 'B',
      why: 'Vận động đều đặn và ngủ đủ giúp tim mạch khoẻ, tuần hoàn tốt.' },
    { sec: 'Tuần hoàn', name: 'Câu 8', pts: 1,
      text: 'Vì sao không nên vận động quá sức, gắng sức đột ngột?',
      opts: o4('Vì tốn thời gian', 'Vì làm bẩn quần áo', 'Không sao cả', 'Vì tim phải làm việc quá nhiều, dễ mệt, nguy hiểm'), ans: 'D',
      why: 'Gắng sức đột ngột khiến tim làm việc quá tải, dễ mệt và nguy hiểm.' },
    { sec: 'Tuần hoàn', name: 'Câu 9', pts: 1,
      text: 'Khi bị chảy máu ở tay, ta thấy máu có màu gì?',
      opts: o4('Màu xanh', 'Màu vàng', 'Màu đỏ', 'Màu trắng'), ans: 'C',
      why: 'Máu có màu đỏ; khi ra ngoài không khí máu càng đỏ tươi.' },
    { sec: 'Tuần hoàn', name: 'Câu 10', pts: 1,
      text: 'Chất nào có hại cho tim và mạch máu, cần tránh?',
      opts: o4('Thuốc lá, rượu bia', 'Nước lọc', 'Rau củ', 'Sữa'), ans: 'A',
      why: 'Thuốc lá, rượu bia gây hại cho tim mạch; trẻ em phải tránh xa.' },
  ],
},

/* ═══════════ ĐỀ 24 — CON NGƯỜI: CƠ QUAN BÀI TIẾT NƯỚC TIỂU ═══════════ */
{
  id: 8614, title: 'Đề 24 · Cơ quan bài tiết nước tiểu', time: 15,
  questions: [
    { sec: 'Bài tiết', name: 'Câu 1', pts: 1,
      text: 'Cơ quan bài tiết nước tiểu gồm những bộ phận chính nào?',
      opts: o4('Tim và phổi', 'Hai quả thận, ống dẫn nước tiểu, bóng đái và ống đái', 'Dạ dày và ruột', 'Não và tuỷ sống'), ans: 'B',
      why: 'Cơ quan bài tiết nước tiểu gồm hai quả thận, hai ống dẫn nước tiểu, bóng đái và ống đái.' },
    { sec: 'Bài tiết', name: 'Câu 2', pts: 1,
      text: 'Cơ quan bài tiết nước tiểu có nhiệm vụ gì?',
      opts: o4('Lọc máu, thải chất cặn bã và nước thừa ra ngoài', 'Tiêu hoá thức ăn', 'Giúp ta thở', 'Bơm máu đi nuôi cơ thể'), ans: 'A',
      why: 'Cơ quan này lọc máu, tạo nước tiểu để thải chất cặn bã và nước thừa ra ngoài.' },
    { sec: 'Bài tiết', name: 'Câu 3', pts: 1,
      text: 'Bộ phận nào lọc máu để tạo thành nước tiểu?',
      opts: o4('Bóng đái', 'Ống đái', 'Hai quả thận', 'Dạ dày'), ans: 'C',
      why: 'Hai quả thận lọc máu, giữ lại chất cần thiết và tạo ra nước tiểu.' },
    { sec: 'Bài tiết', name: 'Câu 4', pts: 1,
      text: 'Nước tiểu được chứa tạm ở đâu trước khi thải ra ngoài?',
      opts: o4('Trong phổi', 'Trong tim', 'Trong dạ dày', 'Bóng đái (bàng quang)'), ans: 'D',
      why: 'Nước tiểu theo ống dẫn xuống chứa ở bóng đái, khi đầy sẽ được thải ra ngoài.' },
    { sec: 'Bài tiết', name: 'Câu 5', pts: 1,
      text: 'Vì sao mỗi ngày cần uống đủ nước?',
      opts: o4('Giúp thận lọc máu và thải chất độc tốt hơn', 'Để nặng cân hơn', 'Để khỏi phải ăn', 'Không cần uống nước'), ans: 'A',
      why: 'Uống đủ nước giúp thận lọc máu, thải chất cặn bã và tránh sỏi thận.' },
    { sec: 'Bài tiết', name: 'Câu 6', pts: 1,
      text: 'Khi buồn đi tiểu, em nên làm gì?',
      opts: o4('Cố nhịn thật lâu', 'Nhịn cả ngày', 'Đi ngay, không nên nhịn lâu', 'Không bao giờ đi'), ans: 'C',
      why: 'Không nên nhịn tiểu lâu vì dễ gây hại cho bóng đái và thận.' },
    { sec: 'Bài tiết', name: 'Câu 7', pts: 1,
      text: 'Việc nào giúp giữ cơ quan bài tiết nước tiểu khoẻ?',
      opts: o4('Nhịn tiểu thường xuyên', 'Uống đủ nước, giữ vệ sinh cơ thể sạch sẽ', 'Uống rất ít nước', 'Không tắm rửa'), ans: 'B',
      why: 'Uống đủ nước và giữ vệ sinh sạch sẽ giúp cơ quan bài tiết hoạt động tốt.' },
    { sec: 'Bài tiết', name: 'Câu 8', pts: 1,
      text: 'Bình thường cơ thể một người có mấy quả thận?',
      opts: o4('Một', 'Ba', 'Bốn', 'Hai'), ans: 'D',
      why: 'Bình thường cơ thể có hai quả thận, nằm ở phía sau lưng.' },
    { sec: 'Bài tiết', name: 'Câu 9', pts: 1,
      text: 'Nước tiểu là gì?',
      opts: o4('Thức ăn chưa tiêu', 'Máu sạch', 'Chất lỏng chứa chất cặn bã cơ thể thải ra', 'Không khí'), ans: 'C',
      why: 'Nước tiểu là chất lỏng chứa chất cặn bã và nước thừa được thận lọc ra khỏi máu.' },
    { sec: 'Bài tiết', name: 'Câu 10', pts: 1,
      text: 'Sau khi đi vệ sinh, em cần làm gì?',
      opts: o4('Rửa tay sạch bằng xà phòng', 'Không cần rửa tay', 'Lau tay vào quần áo', 'Đi chơi ngay'), ans: 'A',
      why: 'Rửa tay bằng xà phòng sau khi đi vệ sinh giúp phòng bệnh, giữ vệ sinh.' },
  ],
},

/* ═══════════ ĐỀ 25 — CON NGƯỜI: CƠ QUAN THẦN KINH ═══════════ */
{
  id: 8615, title: 'Đề 25 · Cơ quan thần kinh và giấc ngủ', time: 15,
  questions: [
    { sec: 'Thần kinh', name: 'Câu 1', pts: 1,
      text: 'Bộ phận nào là "trung tâm" điều khiển cơ thể?',
      opts: o4('Bóng đái', 'Bộ não', 'Lá phổi', 'Dạ dày'), ans: 'B',
      why: 'Bộ não là trung tâm điều khiển suy nghĩ, cảm nhận và mọi hoạt động của cơ thể.' },
    { sec: 'Thần kinh', name: 'Câu 2', pts: 1,
      text: 'Tuỷ sống nằm ở đâu?',
      opts: o4('Bên trong cột sống (xương sống)', 'Trong lồng ngực', 'Trong bụng', 'Ở bàn chân'), ans: 'A',
      why: 'Tuỷ sống nằm trong cột sống, nối với não và dẫn truyền tín hiệu thần kinh.' },
    { sec: 'Thần kinh', name: 'Câu 3', pts: 1,
      text: 'Dây thần kinh có nhiệm vụ gì?',
      opts: o4('Tiêu hoá thức ăn', 'Lọc máu', 'Dẫn tín hiệu giữa não, tuỷ sống và các bộ phận', 'Bơm máu'), ans: 'C',
      why: 'Các dây thần kinh dẫn truyền tín hiệu giữa não, tuỷ sống và khắp cơ thể.' },
    { sec: 'Thần kinh', name: 'Câu 4', pts: 1,
      text: 'Khi tay chạm phải vật nóng, em rụt tay lại rất nhanh nhờ đâu?',
      opts: o4('Nhờ dạ dày', 'Nhờ lá phổi', 'Nhờ quả thận', 'Nhờ phản xạ của cơ quan thần kinh'), ans: 'D',
      why: 'Đó là phản xạ do thần kinh điều khiển giúp cơ thể tránh nguy hiểm kịp thời.' },
    { sec: 'Thần kinh', name: 'Câu 5', pts: 1,
      text: 'Học sinh lớp 3 nên ngủ mỗi ngày khoảng bao nhiêu là hợp lí?',
      opts: o4('Khoảng 9 – 10 tiếng', 'Chỉ 2 tiếng', 'Không cần ngủ', '20 tiếng'), ans: 'A',
      why: 'Trẻ em cần ngủ đủ (khoảng 9 – 10 tiếng) để não và cơ thể phục hồi.' },
    { sec: 'Thần kinh', name: 'Câu 6', pts: 1,
      text: 'Thiếu ngủ kéo dài ảnh hưởng thế nào tới em?',
      opts: o4('Học giỏi hơn', 'Khoẻ hơn', 'Mệt mỏi, kém tập trung, hay quên', 'Không sao cả'), ans: 'C',
      why: 'Thiếu ngủ làm não mệt mỏi, kém tập trung, dễ quên và ảnh hưởng sức khoẻ.' },
    { sec: 'Thần kinh', name: 'Câu 7', pts: 1,
      text: 'Việc nào giúp cơ quan thần kinh nghỉ ngơi, thư giãn?',
      opts: o4('Học liên tục không nghỉ', 'Ngủ đủ giấc, vui chơi lành mạnh', 'Xem điện thoại tới khuya', 'Lo lắng thường xuyên'), ans: 'B',
      why: 'Ngủ đủ và vui chơi lành mạnh giúp thần kinh được nghỉ ngơi, phục hồi.' },
    { sec: 'Thần kinh', name: 'Câu 8', pts: 1,
      text: 'Chất nào gây hại nặng cho cơ quan thần kinh?',
      opts: o4('Nước cam', 'Cơm gạo', 'Rau xanh', 'Rượu, bia, ma tuý, thuốc lá'), ans: 'D',
      why: 'Rượu, bia, ma tuý, thuốc lá gây hại nghiêm trọng cho thần kinh, phải tránh xa.' },
    { sec: 'Thần kinh', name: 'Câu 9', pts: 1,
      text: 'Để bảo vệ đầu và bộ não khi đi xe, em cần làm gì?',
      opts: o4('Không đội gì', 'Đội mũ vải', 'Đội mũ bảo hiểm đúng cách', 'Cầm mũ trên tay'), ans: 'C',
      why: 'Đội mũ bảo hiểm đúng cách bảo vệ hộp sọ và bộ não khi có va chạm.' },
    { sec: 'Thần kinh', name: 'Câu 10', pts: 1,
      text: 'Trạng thái tinh thần nào tốt cho thần kinh?',
      opts: o4('Vui vẻ, lạc quan, thoải mái', 'Giận dữ kéo dài', 'Lo sợ liên miên', 'Buồn bã cả ngày'), ans: 'A',
      why: 'Tinh thần vui vẻ, thoải mái giúp thần kinh khoẻ mạnh, học tập và sinh hoạt tốt.' },
  ],
},

/* ═══════════ ĐỀ 26 — TRÁI ĐẤT: PHƯƠNG HƯỚNG VÀ LA BÀN ═══════════ */
{
  id: 8616, title: 'Đề 26 · Phương hướng và cách xác định', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Bốn hướng chính là những hướng nào?',
      opts: o4('Trên, dưới, trái, phải', 'Đông, tây, nam, bắc', 'Trước, sau, xa, gần', 'Cao, thấp, rộng, hẹp'), ans: 'B',
      why: 'Bốn hướng chính là đông, tây, nam, bắc.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Nếu em quay mặt về hướng mặt trời mọc (hướng đông), sau lưng em là hướng nào?',
      opts: o4('Hướng tây', 'Hướng nam', 'Hướng bắc', 'Hướng đông'), ans: 'A',
      why: 'Mặt hướng đông thì sau lưng là hướng tây (hai hướng đối nhau).' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Khi quay mặt về hướng đông, tay phải của em chỉ hướng nào?',
      opts: o4('Hướng bắc', 'Hướng tây', 'Hướng nam', 'Hướng đông'), ans: 'C',
      why: 'Mặt hướng đông thì tay phải chỉ về hướng nam, tay trái chỉ hướng bắc.' },
    { sec: 'Bầu trời', name: 'Câu 4', pts: 1,
      text: 'Dụng cụ nào có kim luôn chỉ hướng bắc – nam?',
      opts: o4('Nhiệt kế', 'Cái cân', 'Kính lúp', 'La bàn'), ans: 'D',
      why: 'La bàn có kim nam châm luôn chỉ hướng bắc – nam, dùng để tìm phương hướng.' },
    { sec: 'Bầu trời', name: 'Câu 5', pts: 1,
      text: 'Ban ngày, có thể dựa vào đâu để đoán phương hướng?',
      opts: o4('Vị trí Mặt Trời', 'Vị trí Mặt Trăng', 'Ánh đèn đường', 'Tiếng chim hót'), ans: 'A',
      why: 'Ban ngày dựa vào Mặt Trời: sáng mọc hướng đông, chiều lặn hướng tây.' },
    { sec: 'Bầu trời', name: 'Câu 6', pts: 1,
      text: 'Buổi trưa, khi đứng quay lưng về Mặt Trời ở nước ta, bóng đổ về phía nào là hướng bắc?',
      opts: o4('Phía Mặt Trời', 'Không xác định được', 'Phía bóng của em đổ tới', 'Phía trên đầu'), ans: 'C',
      why: 'Buổi trưa, bóng người thường đổ về phía bắc, có thể dùng để ước lượng hướng.' },
    { sec: 'Bầu trời', name: 'Câu 7', pts: 1,
      text: 'Trên bản đồ, phía trên thường là hướng nào?',
      opts: o4('Hướng nam', 'Hướng bắc', 'Hướng đông', 'Hướng tây'), ans: 'B',
      why: 'Theo quy ước, phía trên bản đồ là hướng bắc.' },
    { sec: 'Bầu trời', name: 'Câu 8', pts: 1,
      text: 'Hướng nào đối diện với hướng nam?',
      opts: o4('Hướng đông', 'Hướng tây', 'Hướng nam', 'Hướng bắc'), ans: 'D',
      why: 'Hướng bắc đối diện với hướng nam.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Biết phương hướng giúp ích gì cho con người?',
      opts: o4('Nấu ăn ngon hơn', 'Học toán giỏi hơn', 'Đi lại, tìm đường không bị lạc', 'Ngủ ngon hơn'), ans: 'C',
      why: 'Xác định được phương hướng giúp đi lại, tìm đường và không bị lạc.' },
    { sec: 'Bầu trời', name: 'Câu 10', pts: 1,
      text: 'Kim la bàn có sơn màu (thường màu đỏ) luôn chỉ về hướng nào?',
      opts: o4('Hướng bắc', 'Hướng đông', 'Hướng tây', 'Hướng nam'), ans: 'A',
      why: 'Đầu kim nam châm (thường sơn đỏ) của la bàn luôn chỉ về hướng bắc.' },
  ],
},

/* ═══════════ ĐỀ 27 — TRÁI ĐẤT: MẶT TRỜI, NGÀY VÀ ĐÊM ═══════════ */
{
  id: 8617, title: 'Đề 27 · Mặt Trời, ngày và đêm', time: 15,
  questions: [
    { sec: 'Bầu trời', name: 'Câu 1', pts: 1,
      text: 'Mặt Trời cung cấp cho Trái Đất những gì?',
      opts: o4('Nước mưa', 'Ánh sáng và sức nóng (nhiệt)', 'Gió bão', 'Bóng tối'), ans: 'B',
      why: 'Mặt Trời cho Trái Đất ánh sáng và sức nóng, giúp mọi vật sống được.' },
    { sec: 'Bầu trời', name: 'Câu 2', pts: 1,
      text: 'Vì sao ban ngày có ánh sáng còn ban đêm thì tối?',
      opts: o4('Do Trái Đất tự quay, lúc hướng về, lúc quay lưng với Mặt Trời', 'Do Mặt Trời tắt đi', 'Do có mây', 'Do người ta tắt điện'), ans: 'A',
      why: 'Trái Đất tự quay: nửa hướng về Mặt Trời là ban ngày, nửa quay lưng là ban đêm.' },
    { sec: 'Bầu trời', name: 'Câu 3', pts: 1,
      text: 'Trái Đất tự quay một vòng quanh mình nó hết khoảng bao lâu?',
      opts: o4('Một tháng', 'Một năm', 'Một ngày một đêm (24 giờ)', 'Một tuần'), ans: 'C',
      why: 'Trái Đất tự quay một vòng hết khoảng 24 giờ, tạo nên một ngày một đêm.' },
    { sec: 'Bầu trời', name: 'Câu 4', pts: 1,
      text: 'Vì sao KHÔNG được nhìn thẳng vào Mặt Trời?',
      opts: o4('Vì Mặt Trời xấu', 'Vì mất lịch sự', 'Không có lí do', 'Vì ánh nắng gắt làm hại, hỏng mắt'), ans: 'D',
      why: 'Nhìn thẳng Mặt Trời, ánh sáng mạnh có thể làm tổn thương và hỏng mắt.' },
    { sec: 'Bầu trời', name: 'Câu 5', pts: 1,
      text: 'Ban đêm, trên bầu trời ta thường nhìn thấy gì?',
      opts: o4('Mặt Trăng và các vì sao', 'Mặt Trời chói chang', 'Cầu vồng bảy sắc', 'Ánh nắng'), ans: 'A',
      why: 'Ban đêm bầu trời thường có Mặt Trăng và các ngôi sao.' },
    { sec: 'Bầu trời', name: 'Câu 6', pts: 1,
      text: 'Ánh sáng Mặt Trời cần cho cây xanh để làm gì?',
      opts: o4('Để cây ngủ', 'Để cây héo', 'Quang hợp, tạo thức ăn nuôi cây', 'Không cần thiết'), ans: 'C',
      why: 'Cây xanh cần ánh sáng Mặt Trời để quang hợp, tạo thức ăn và lớn lên.' },
    { sec: 'Bầu trời', name: 'Câu 7', pts: 1,
      text: 'Vào lúc nào trong ngày Mặt Trời thường lên cao nhất, nắng gắt nhất?',
      opts: o4('Sáng sớm', 'Buổi trưa', 'Chiều tối', 'Nửa đêm'), ans: 'B',
      why: 'Buổi trưa Mặt Trời lên cao nhất nên nắng gắt và nóng nhất trong ngày.' },
    { sec: 'Bầu trời', name: 'Câu 8', pts: 1,
      text: 'Khi ra nắng lâu, để bảo vệ sức khoẻ em nên làm gì?',
      opts: o4('Cởi hết áo phơi nắng', 'Chơi giữa trưa nắng', 'Nhịn uống nước', 'Đội mũ nón, che ô, uống đủ nước'), ans: 'D',
      why: 'Đội mũ, che ô và uống đủ nước giúp tránh say nắng, cảm nắng.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Bóng của một cây cột thay đổi trong ngày là do đâu?',
      opts: o4('Cây cột tự quay', 'Do gió thổi', 'Mặt Trời di chuyển vị trí trên bầu trời', 'Do có người kéo bóng'), ans: 'C',
      why: 'Trong ngày, vị trí Mặt Trời thay đổi nên bóng của vật cũng đổi hướng và độ dài.' },
    { sec: 'Bầu trời', name: 'Câu 10', pts: 1,
      text: 'Nếu không có Mặt Trời, Trái Đất sẽ thế nào?',
      opts: o4('Lạnh giá, tối tăm, không có sự sống', 'Ấm áp hơn', 'Sáng hơn', 'Không thay đổi'), ans: 'A',
      why: 'Không có Mặt Trời, Trái Đất sẽ tối tăm, lạnh giá và không thể có sự sống.' },
  ],
},

/* ═══════════ ĐỀ 28 — TRÁI ĐẤT: CÁC MÙA VÀ THỜI TIẾT ═══════════ */
{
  id: 8618, title: 'Đề 28 · Các mùa và thời tiết', time: 15,
  questions: [
    { sec: 'Các mùa', name: 'Câu 1', pts: 1,
      text: 'Miền Bắc nước ta thường có mấy mùa trong năm?',
      opts: o4('Hai mùa', 'Bốn mùa: xuân, hạ, thu, đông', 'Ba mùa', 'Năm mùa'), ans: 'B',
      why: 'Miền Bắc có bốn mùa rõ rệt: xuân, hạ, thu, đông.' },
    { sec: 'Các mùa', name: 'Câu 2', pts: 1,
      text: 'Miền Nam nước ta chủ yếu có mấy mùa?',
      opts: o4('Hai mùa: mùa mưa và mùa khô', 'Bốn mùa rõ rệt', 'Chỉ mùa đông', 'Năm mùa'), ans: 'A',
      why: 'Miền Nam nóng quanh năm, chỉ có hai mùa: mùa mưa và mùa khô.' },
    { sec: 'Các mùa', name: 'Câu 3', pts: 1,
      text: 'Mùa nào trong năm thường lạnh nhất ở miền Bắc?',
      opts: o4('Mùa hạ', 'Mùa xuân', 'Mùa đông', 'Mùa thu'), ans: 'C',
      why: 'Mùa đông ở miền Bắc trời lạnh nhất, có khi rét đậm.' },
    { sec: 'Các mùa', name: 'Câu 4', pts: 1,
      text: 'Mùa nào thường nóng nhất và hay có mưa rào, bão?',
      opts: o4('Mùa đông', 'Mùa xuân', 'Mùa thu', 'Mùa hạ (mùa hè)'), ans: 'D',
      why: 'Mùa hạ trời nóng nhất, hay có mưa rào và bão.' },
    { sec: 'Thời tiết', name: 'Câu 5', pts: 1,
      text: 'Thời tiết là gì?',
      opts: o4('Trạng thái nắng, mưa, gió, nóng, lạnh... của bầu trời', 'Tên các con vật', 'Món ăn hằng ngày', 'Các loại cây'), ans: 'A',
      why: 'Thời tiết là các hiện tượng nắng, mưa, gió, nóng, lạnh... diễn ra trong ngày.' },
    { sec: 'Thời tiết', name: 'Câu 6', pts: 1,
      text: 'Khi trời sắp mưa to, gió lớn, em nên làm gì?',
      opts: o4('Ra đứng ngoài trời chơi', 'Trú dưới gốc cây to', 'Vào nhà trú, không đứng dưới cây to, cột điện', 'Cầm ô kim loại chạy'), ans: 'C',
      why: 'Mưa dông có sấm sét nên vào nhà trú, tránh đứng dưới cây to hay cột điện.' },
    { sec: 'Thời tiết', name: 'Câu 7', pts: 1,
      text: 'Khi trời trở lạnh, em nên làm gì để giữ sức khoẻ?',
      opts: o4('Mặc áo mỏng', 'Mặc ấm, đội mũ, quàng khăn', 'Tắm nước lạnh lâu', 'Cởi áo ra ngoài'), ans: 'B',
      why: 'Mặc ấm, đội mũ, quàng khăn giúp giữ ấm cơ thể, tránh cảm lạnh khi trời rét.' },
    { sec: 'Thời tiết', name: 'Câu 8', pts: 1,
      text: 'Vì sao cần nghe dự báo thời tiết?',
      opts: o4('Để cho vui', 'Không có ích gì', 'Để đi ngủ sớm', 'Để biết trước nắng mưa mà chuẩn bị'), ans: 'D',
      why: 'Nghe dự báo thời tiết giúp ta chuẩn bị áo mưa, quần áo ấm và phòng tránh bão.' },
    { sec: 'Các mùa', name: 'Câu 9', pts: 1,
      text: 'Mùa xuân thường có đặc điểm gì?',
      opts: o4('Rét buốt nhất năm', 'Nóng nực nhất năm', 'Thời tiết ấm áp, cây cối đâm chồi nảy lộc', 'Lá cây rụng hết'), ans: 'C',
      why: 'Mùa xuân ấm áp, mưa phùn nhẹ, cây cối đâm chồi nảy lộc, muôn hoa đua nở.' },
    { sec: 'Các mùa', name: 'Câu 10', pts: 1,
      text: 'Vào mùa thu, cảnh vật thường thế nào?',
      opts: o4('Trời mát mẻ, lá vàng rụng nhiều', 'Nắng gắt và oi bức', 'Rét buốt, có tuyết', 'Mưa bão liên miên'), ans: 'A',
      why: 'Mùa thu trời mát mẻ, dễ chịu, nhiều loại cây thay lá và lá vàng rụng.' },
  ],
},

/* ═══════════ ĐỀ 29 — TỔNG HỢP (1) ═══════════ */
{
  id: 8619, title: 'Đề 29 · Ôn tập tổng hợp (1)', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Bố của mẹ em, em gọi là gì?',
      opts: o4('Ông nội', 'Ông ngoại', 'Bác', 'Chú'), ans: 'B',
      why: 'Bố của mẹ là ông ngoại.' },
    { sec: 'An toàn', name: 'Câu 2', pts: 1,
      text: 'Gọi cấp cứu y tế khi có người bị nạn là số nào?',
      opts: o4('115', '113', '114', '116'), ans: 'A',
      why: 'Số 115 là số gọi cấp cứu y tế.' },
    { sec: 'Sản xuất', name: 'Câu 3', pts: 1,
      text: 'Nghề nuôi tôm, nuôi cá thuộc hoạt động sản xuất nào?',
      opts: o4('Công nghiệp nặng', 'Khai thác than', 'Nông nghiệp (thuỷ sản)', 'Dệt may'), ans: 'C',
      why: 'Nuôi tôm, cá là nuôi trồng thuỷ sản, thuộc nhóm nông nghiệp.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Bộ phận nào của cây tạo ra thức ăn nhờ ánh sáng?',
      opts: o4('Rễ', 'Quả', 'Hạt', 'Lá'), ans: 'D',
      why: 'Lá quang hợp, dùng ánh sáng để tạo thức ăn nuôi cây.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Con vật nào nuôi con bằng sữa?',
      opts: o4('Con bò', 'Con gà', 'Con vịt', 'Con cá'), ans: 'A',
      why: 'Bò là loài thú, đẻ con và nuôi con bằng sữa mẹ.' },
    { sec: 'Hô hấp', name: 'Câu 6', pts: 1,
      text: 'Khi hít thở, cơ thể lấy vào khí gì?',
      opts: o4('Khí các-bô-níc', 'Khói bụi', 'Khí ô-xi', 'Hơi nước bẩn'), ans: 'C',
      why: 'Cơ thể hít vào khí ô-xi và thở ra khí các-bô-níc.' },
    { sec: 'Tuần hoàn', name: 'Câu 7', pts: 1,
      text: 'Bộ phận nào bơm máu đi khắp cơ thể?',
      opts: o4('Phổi', 'Tim', 'Thận', 'Dạ dày'), ans: 'B',
      why: 'Tim co bóp để bơm máu đi nuôi toàn bộ cơ thể.' },
    { sec: 'Bài tiết', name: 'Câu 8', pts: 1,
      text: 'Bộ phận nào lọc máu, tạo nước tiểu?',
      opts: o4('Tim', 'Phổi', 'Não', 'Thận'), ans: 'D',
      why: 'Thận lọc máu và tạo ra nước tiểu để thải chất cặn bã.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Mặt Trời mọc ở hướng nào?',
      opts: o4('Tây', 'Nam', 'Đông', 'Bắc'), ans: 'C',
      why: 'Buổi sáng Mặt Trời mọc ở hướng đông.' },
    { sec: 'Cộng đồng', name: 'Câu 10', pts: 1,
      text: 'Khi qua đường có đèn tín hiệu, em qua khi đèn nào bật cho người đi bộ?',
      opts: o4('Đèn xanh', 'Đèn đỏ', 'Đèn vàng', 'Lúc nào cũng được'), ans: 'A',
      why: 'Người đi bộ qua đường khi đèn xanh dành cho người đi bộ và quan sát an toàn.' },
  ],
},

/* ═══════════ ĐỀ 30 — TỔNG HỢP (2) ═══════════ */
{
  id: 8620, title: 'Đề 30 · Ôn tập tổng hợp (2)', time: 15,
  questions: [
    { sec: 'Gia đình', name: 'Câu 1', pts: 1,
      text: 'Người thân bên mẹ thuộc họ nào?',
      opts: o4('Họ nội', 'Họ ngoại', 'Hàng xóm', 'Người dưng'), ans: 'B',
      why: 'Ông bà, cậu, dì... bên mẹ thuộc họ ngoại.' },
    { sec: 'Trường học', name: 'Câu 2', pts: 1,
      text: 'Việc nào giữ gìn tài sản của trường?',
      opts: o4('Không viết, vẽ bậy lên bàn ghế, tường', 'Khắc tên lên bàn', 'Bẻ vòi nước', 'Đập cửa kính'), ans: 'A',
      why: 'Không viết vẽ bậy, không phá hỏng bàn ghế là giữ gìn tài sản chung của trường.' },
    { sec: 'Cộng đồng', name: 'Câu 3', pts: 1,
      text: 'Đền Hùng là nơi thờ ai?',
      opts: o4('Thần Mưa', 'Vua nước ngoài', 'Các Vua Hùng', 'Ông Táo'), ans: 'C',
      why: 'Đền Hùng thờ các Vua Hùng có công dựng nước.' },
    { sec: 'Thực vật', name: 'Câu 4', pts: 1,
      text: 'Chức năng chính của rễ cây là gì?',
      opts: o4('Quang hợp', 'Nở hoa', 'Bay lên trời', 'Hút nước, chất khoáng và giữ cây đứng vững'), ans: 'D',
      why: 'Rễ hút nước, chất khoáng và bám giữ cho cây đứng vững.' },
    { sec: 'Động vật', name: 'Câu 5', pts: 1,
      text: 'Cá thở bằng bộ phận nào?',
      opts: o4('Mang', 'Phổi', 'Da', 'Mũi'), ans: 'A',
      why: 'Cá thở bằng mang, lấy ô-xi hoà tan trong nước.' },
    { sec: 'Thần kinh', name: 'Câu 6', pts: 1,
      text: 'Bộ phận nào giúp em suy nghĩ, ghi nhớ và học bài?',
      opts: o4('Lá phổi', 'Quả tim', 'Bộ não', 'Dạ dày'), ans: 'C',
      why: 'Bộ não điều khiển suy nghĩ, ghi nhớ và việc học tập.' },
    { sec: 'Hô hấp', name: 'Câu 7', pts: 1,
      text: 'Để bảo vệ đường hô hấp nơi nhiều khói bụi, em nên làm gì?',
      opts: o4('Hít thật sâu bụi vào', 'Đeo khẩu trang', 'Bỏ khẩu trang ra', 'Chơi lâu chỗ khói'), ans: 'B',
      why: 'Đeo khẩu trang nơi nhiều khói bụi giúp bảo vệ mũi, họng và phổi.' },
    { sec: 'Các mùa', name: 'Câu 8', pts: 1,
      text: 'Một năm có bốn mùa theo thứ tự nào?',
      opts: o4('Đông, xuân, hạ, thu', 'Hạ, thu, xuân, đông', 'Thu, đông, hạ, xuân', 'Xuân, hạ, thu, đông'), ans: 'D',
      why: 'Bốn mùa nối tiếp nhau: xuân, hạ, thu, đông.' },
    { sec: 'Bầu trời', name: 'Câu 9', pts: 1,
      text: 'Trái Đất có hình dạng gì?',
      opts: o4('Hình vuông', 'Hình dẹt phẳng', 'Hình cầu (tròn như quả bóng)', 'Hình tam giác'), ans: 'C',
      why: 'Trái Đất có dạng hình cầu, tròn như quả bóng.' },
    { sec: 'Vệ sinh', name: 'Câu 10', pts: 1,
      text: 'Rác thải nên được xử lí thế nào cho đúng?',
      opts: o4('Phân loại và bỏ đúng nơi quy định', 'Vứt ra đường', 'Đổ xuống sông', 'Đốt bừa trong nhà'), ans: 'A',
      why: 'Phân loại và bỏ rác đúng nơi quy định giúp giữ môi trường sạch, đẹp.' },
  ],
},

];

SUBJECTS.push({
  id: 'tnxh3', name: 'Tự nhiên & Xã hội', short: 'TN&XH 3', icon: '🌍', grade: 3,
  exams: TNXH3_EXAMS, ready: true,
  heroTitle: 'Tự nhiên và Xã hội lớp 3 — họ hàng, sản xuất, cơ thể người, thực vật, động vật và Trái Đất',
  heroMeta: '📚 30 đề &nbsp;•&nbsp; 300 câu &nbsp;•&nbsp; ⏱ 15 phút mỗi đề &nbsp;•&nbsp; bám chương trình GDPT 2018',
});
