// TIẾNG VIỆT LỚP 3 — ĐỌC HIỂU SÂU · CẢM THỤ · LUYỆN TỪ VÀ CÂU
// 12 đề × 10 câu = 120 câu. Mỗi câu 1 điểm — thang 10 — 25 phút mỗi đề.
//
// VÌ SAO CÓ BỘ NÀY: bộ VioEdu Tiếng Việt lớp 3 đã có phần nhận biết so sánh – nhân hoá,
// nhưng dừng ở mức "câu này dùng biện pháp gì". Bộ này đi tiếp hai bước mà đề thi
// chuyển cấp về sau đòi hỏi:
//   1. ĐỌC HIỂU SÂU: ý chính của bài, bài học rút ra, nghĩa của từ trong ngữ cảnh,
//      và suy luận điều bài đọc KHÔNG nói thẳng ra.
//   2. CẢM THỤ: chỉ ra cái hay của một hình ảnh so sánh – nhân hoá, chứ không chỉ gọi tên
//      biện pháp; chọn được câu văn hay hơn và nói được vì sao.
//   3. Nền tập làm văn: bố cục đoạn, câu mở đoạn – kết đoạn, ý lạc đề, từ ngữ gợi tả.
//
// KHÁC BIỆT KĨ THUẬT: bài đọc để trong trường `read` và LẶP LẠI trên MỌI câu của nhóm
// đọc hiểu, nên bé luôn nhìn thấy bài đọc khi trả lời (app hiện mỗi lần một câu).
//
// MỨC ĐỘ: bám chương trình Tiếng Việt 3 (GDPT 2018) — so sánh, nhân hoá, các mẫu câu và
// bộ phận câu trả lời Khi nào? · Ở đâu? · Vì sao? · Bằng gì?, dấu phẩy, dấu hai chấm,
// dấu ngoặc kép, từ cùng nghĩa – trái nghĩa. Không dùng thuật ngữ của lớp trên
// (chủ ngữ – vị ngữ – trạng ngữ, từ đơn – từ phức, điệp từ) vì lớp 3 chưa học.

/* ── Bài đọc dùng chung cho nhiều câu trong cùng một đề ────────────────────── */
const TV3_R1 = '<b>Hạt giống của nhà vua</b> <i>(kể theo truyện dân gian)</i><br>Nhà vua đã già mà chưa có người nối ngôi. Vua phát cho mỗi đứa trẻ trong nước một hạt giống và hẹn: ai trồng được chậu hoa đẹp nhất sẽ được chọn. Suốt cả năm trời, cậu bé Ni chăm bón hết lòng mà chậu đất vẫn trơ trọi. Đến ngày hẹn, các bạn nô nức bưng tới những chậu hoa rực rỡ, riêng Ni bưng một chậu đất không, mặt cúi gằm. Nhà vua nhìn khắp một lượt rồi chỉ vào Ni: “Ta đã luộc chín tất cả hạt giống trước khi phát. Chỉ mình con nói thật.”';

const TV3_R2 = '<b>Chợ phiên vùng cao</b><br>Sáng thứ bảy, sương còn giăng trắng lưng đồi, người các bản đã í ới gọi nhau xuống chợ. Chợ họp trên một bãi đất rộng ven suối. Hàng thổ cẩm bày dài, rực rỡ như một vườn hoa trải trên mặt đất. Bên kia, mấy chú ngựa thồ đứng nhai cỏ, kiên nhẫn chờ chủ mua bán xong. Tiếng cười, tiếng mặc cả, tiếng khèn hoà vào nhau, vang cả một góc núi. Quá trưa, chợ tan, dòng người lại nối nhau leo dốc trở về bản.';

const TV3_R3 = '<b>Mặt trời xanh của tôi</b> <i>(trích — Nguyễn Viết Bình)</i><br>Đã có ai lắng nghe<br>Tiếng mưa trong rừng cọ<br>Như tiếng thác dội về<br>Như ào ào trận gió.<br>…<br>Rừng cọ ơi! Rừng cọ!<br>Lá đẹp, lá ngời ngời<br>Tôi yêu thường vẫn gọi<br>Mặt trời xanh của tôi.';

const TV3_R4 = '<b>Người bạn nhỏ trên sân thượng</b><br>Đầu hè, một đôi chim sẻ tha rơm về làm tổ trong chậu cây trên sân thượng nhà Bống. Bống thích lắm, ngày nào cũng rón rén lên xem. Mẹ dặn: “Con chỉ được đứng xa nhìn thôi, chim mẹ thấy động là bỏ tổ đấy.” Bống nghe lời, chỉ dám nấp sau cánh cửa. Ít lâu sau, ba chú chim non há mỏ kêu chiêm chiếp đòi ăn. Sáng nào Bống cũng dậy sớm chỉ để nghe cái dàn đồng ca bé xíu ấy. Đến ngày lũ chim tập bay rồi rời tổ, Bống buồn mất mấy hôm, nhưng em vẫn để nguyên cái tổ ở đó, hi vọng sang năm chúng lại về.';

const TV3_EXAMS = [

/* ═══════════ ĐỀ 1 — ĐỌC HIỂU TRUYỆN: SUY LUẬN VÀ BÀI HỌC ═══════════ */
{
  id: 1801, title: 'Đề 1 · Đọc hiểu truyện — suy luận và bài học', time: 25,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV3_R1,
      text: 'Nhà vua phát cho mỗi đứa trẻ trong nước thứ gì?',
      opts: o4('Một chậu hoa', 'Một cây con', 'Một túi vàng', 'Một hạt giống'), ans: 'D',
      why: '“Vua phát cho mỗi đứa trẻ trong nước một hạt giống…”.' },
    { sec: 'Đọc hiểu', name: 'Câu 2', pts: 1, read: TV3_R1,
      text: 'Nhà vua hẹn sẽ chọn người nối ngôi theo tiêu chuẩn nào?',
      opts: o4('Ai trồng được chậu hoa đẹp nhất', 'Ai khoẻ mạnh nhất', 'Ai học giỏi nhất', 'Ai giàu có nhất'), ans: 'A',
      why: '“…ai trồng được chậu hoa đẹp nhất sẽ được chọn.”.' },
    { sec: 'Suy luận', name: 'Câu 3', pts: 1, read: TV3_R1,
      text: 'Vì sao chậu đất của Ni không mọc lên cây nào?',
      opts: o4('Vì Ni quên tưới nước', 'Vì đất trong chậu quá xấu', 'Vì hạt giống đã bị luộc chín', 'Vì trời năm ấy quá lạnh'), ans: 'C',
      why: 'Cuối truyện nhà vua nói rõ: “Ta đã luộc chín tất cả hạt giống trước khi phát.” Hạt đã luộc chín thì không thể nảy mầm.' },
    { sec: 'Suy luận', name: 'Câu 4', pts: 1, read: TV3_R1,
      text: 'Vậy vì sao các bạn khác lại bưng tới được những chậu hoa rực rỡ?',
      opts: o4('Vì các bạn được vua cho hạt tốt hơn', 'Vì hoa tự mọc lên trong chậu', 'Vì các bạn chăm bón giỏi hơn Ni', 'Vì các bạn đã thay bằng hạt giống khác'), ans: 'D',
      why: 'Mọi hạt vua phát đều đã luộc chín nên không hạt nào mọc được. Chậu hoa rực rỡ chỉ có thể là do các bạn tự thay hạt khác vào — bài đọc không nói thẳng, em phải suy ra.' },
    { sec: 'Ý chính', name: 'Câu 5', pts: 1, read: TV3_R1,
      text: 'Nhà vua chọn Ni vì điều gì?',
      opts: o4('Vì Ni thật thà, dám bưng chậu đất không tới', 'Vì Ni chăm chỉ nhất nước', 'Vì Ni trồng được hoa đẹp nhất', 'Vì Ni là con nhà nghèo'), ans: 'A',
      why: 'Chậu đất trống là bằng chứng Ni không gian dối. Vua cần người nối ngôi trung thực, không cần người trồng hoa giỏi.' },
    { sec: 'Bài học', name: 'Câu 6', pts: 1, read: TV3_R1,
      text: 'Câu chuyện muốn nói với em điều gì?',
      opts: o4('Phải chăm tưới cây mỗi ngày', 'Muốn làm vua thì phải thật giàu', 'Trồng hoa là việc rất khó', 'Người trung thực mới đáng được tin cậy'), ans: 'D',
      why: 'Toàn bộ câu chuyện là một phép thử lòng trung thực, và người thật thà đã thắng.' },
    { sec: 'Nghĩa của từ', name: 'Câu 7', pts: 1, read: TV3_R1,
      text: 'Từ <b>“trơ trọi”</b> trong câu “chậu đất vẫn trơ trọi” có nghĩa là gì?',
      opts: o4('Trống không, chẳng có gì mọc lên', 'Đầy hoa lá', 'Bị nứt vỡ', 'Khô cằn nhưng vẫn có mầm nhỏ'), ans: 'A',
      why: 'Đặt vào câu: Ni chăm bón cả năm mà chậu vẫn “trơ trọi”, tức là vẫn chỉ có đất, không cây cối gì.' },
    { sec: 'Bộ phận câu', name: 'Câu 8', pts: 1,
      text: 'Trong câu “Suốt cả năm trời, cậu bé Ni chăm bón hết lòng.”, bộ phận trả lời câu hỏi <b>Khi nào?</b> là:',
      opts: o4('chăm bón', 'hết lòng', 'cậu bé Ni', 'Suốt cả năm trời'), ans: 'D',
      why: 'Hỏi “Ni chăm bón hết lòng khi nào?” — trả lời: suốt cả năm trời.' },
    { sec: 'Dấu câu', name: 'Câu 9', pts: 1, read: TV3_R1,
      text: 'Dấu hai chấm và dấu ngoặc kép ở cuối bài dùng để làm gì?',
      opts: o4('Ngăn cách các ý được kể ra', 'Báo hiệu và dẫn lại lời nói của nhà vua', 'Kết thúc câu chuyện', 'Bộc lộ cảm xúc ngạc nhiên'), ans: 'B',
      why: 'Dấu hai chấm báo hiệu phía sau là lời nói, dấu ngoặc kép bao lấy đúng lời nhà vua đã nói.' },
    { sec: 'Cảm thụ', name: 'Câu 10', pts: 1, read: TV3_R1,
      text: 'Câu nào nêu <b>đúng</b> cảm nghĩ của em về cậu bé Ni?',
      opts: o4('Ni đáng khen vì dám nói thật dù biết mình sẽ thua thiệt.', 'Ni may mắn nên mới được chọn.', 'Ni là người trồng hoa giỏi nhất nước.', 'Ni thật dại vì không thay hạt giống khác.'), ans: 'A',
      why: 'Chi tiết “mặt cúi gằm” cho thấy Ni biết mình sẽ thua, vậy mà vẫn bưng chậu đất trống tới — đó mới là điều đáng khen.' },
  ],
},

/* ═══════════ ĐỀ 2 — ĐỌC HIỂU BÀI TẢ CẢNH ═══════════ */
{
  id: 1802, title: 'Đề 2 · Đọc hiểu tả cảnh — chợ phiên vùng cao', time: 25,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV3_R2,
      text: 'Chợ phiên trong bài họp ở đâu?',
      opts: o4('Giữa bản làng', 'Trong sân đình', 'Trên đỉnh đồi', 'Trên một bãi đất rộng ven suối'), ans: 'D',
      why: '“Chợ họp trên một bãi đất rộng ven suối.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 2', pts: 1, read: TV3_R2,
      text: 'Người các bản xuống chợ vào lúc nào?',
      opts: o4('Sáng thứ bảy, khi sương còn giăng trắng lưng đồi', 'Đúng buổi trưa', 'Chiều chủ nhật', 'Đêm khuya'), ans: 'A',
      why: 'Câu mở bài nêu rõ thời gian: “Sáng thứ bảy, sương còn giăng trắng lưng đồi…”.' },
    { sec: 'So sánh', name: 'Câu 3', pts: 1, read: TV3_R2,
      text: 'Hàng thổ cẩm được so sánh với hình ảnh nào?',
      opts: o4('Một tấm chăn ấm', 'Một đám mây ngũ sắc', 'Một dòng suối', 'Một vườn hoa trải trên mặt đất'), ans: 'D',
      why: '“Hàng thổ cẩm bày dài, rực rỡ như một vườn hoa trải trên mặt đất.”.' },
    { sec: 'Suy luận', name: 'Câu 4', pts: 1, read: TV3_R2,
      text: 'Vì sao người vùng cao đi chợ lại dắt theo ngựa thồ?',
      opts: o4('Vì đường về bản phải leo dốc, ngựa chở hàng đỡ người', 'Vì họ mang ngựa ra chợ để bán', 'Vì ngựa đẹp, mang đi cho vui', 'Vì ngựa cũng thích ăn cỏ ở chợ'), ans: 'A',
      why: 'Cuối bài: “dòng người lại nối nhau leo dốc trở về bản”. Đường dốc, không đi xe được nên phải nhờ ngựa thồ hàng — bài không nói thẳng, em phải suy ra.' },
    { sec: 'Suy luận', name: 'Câu 5', pts: 1, read: TV3_R2,
      text: 'Chi tiết nào cho thấy phiên chợ rất <b>đông vui</b>?',
      opts: o4('Sương giăng trắng lưng đồi', 'Ngựa đứng nhai cỏ', 'Chợ họp ven suối', 'Tiếng cười, tiếng mặc cả, tiếng khèn vang cả một góc núi'), ans: 'D',
      why: 'Ba loại âm thanh hoà vào nhau và vang xa cả một góc núi thì chợ phải rất đông người.' },
    { sec: 'Nghĩa của từ', name: 'Câu 6', pts: 1, read: TV3_R2,
      text: 'Từ <b>“í ới”</b> trong bài gợi tả điều gì?',
      opts: o4('Tiếng gọi nhau vọng lại từ xa, lúc to lúc nhỏ', 'Tiếng chân người bước', 'Tiếng suối chảy', 'Tiếng ngựa hí'), ans: 'A',
      why: '“í ới gọi nhau” là tiếng người ở các bản gọi với nhau qua sườn đồi, nghe lúc rõ lúc xa.' },
    { sec: 'So sánh', name: 'Câu 7', pts: 1,
      text: 'Trong câu “Hàng thổ cẩm rực rỡ <b>như</b> một vườn hoa.”, đâu là sự vật <b>được</b> so sánh?',
      opts: o4('vườn hoa', 'hàng thổ cẩm', 'mặt đất', 'màu rực rỡ'), ans: 'B',
      why: 'Sự vật được so sánh đứng trước từ “như”; sự vật dùng để so sánh (vườn hoa) đứng sau.' },
    { sec: 'Bộ phận câu', name: 'Câu 8', pts: 1,
      text: 'Trong câu “Quá trưa, chợ tan.”, bộ phận trả lời câu hỏi <b>Khi nào?</b> là:',
      opts: o4('chợ tan', 'chợ', 'tan', 'Quá trưa'), ans: 'D',
      why: 'Hỏi “Khi nào chợ tan?” — trả lời: quá trưa.' },
    { sec: 'Cảm thụ', name: 'Câu 9', pts: 1, read: TV3_R2,
      text: 'Hình ảnh “sương còn giăng trắng lưng đồi” gợi cho em cảnh gì?',
      opts: o4('Buổi sớm tinh mơ, mờ sương, yên ả nơi vùng cao', 'Trời rét đậm, đóng băng', 'Khói bếp bay lên từ các nhà', 'Trời sắp mưa to'), ans: 'A',
      why: 'Sương chỉ giăng vào lúc sáng sớm; “trắng lưng đồi” vẽ ra một buổi sớm mờ ảo, tĩnh lặng của miền núi.' },
    { sec: 'Ý chính', name: 'Câu 10', pts: 1, read: TV3_R2,
      text: 'Bài văn tả về điều gì?',
      opts: o4('Cách nuôi ngựa thồ', 'Cách dệt vải thổ cẩm', 'Một chuyến đi leo núi', 'Một buổi chợ phiên đông vui, đậm nét riêng của vùng cao'), ans: 'D',
      why: 'Cả bài đi theo một phiên chợ, từ lúc người xuống chợ tới lúc chợ tan.' },
  ],
},

/* ═══════════ ĐỀ 3 — ĐỌC HIỂU THƠ VÀ CẢM THỤ HÌNH ẢNH ═══════════ */
{
  id: 1803, title: 'Đề 3 · Đọc hiểu thơ — cảm thụ hình ảnh đẹp', time: 25,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV3_R3,
      text: 'Bài thơ viết về loài cây nào?',
      opts: o4('Cây cọ', 'Cây bàng', 'Cây dừa', 'Cây tre'), ans: 'A',
      why: 'Bài nhắc đi nhắc lại “rừng cọ”, “lá cọ”.' },
    { sec: 'So sánh', name: 'Câu 2', pts: 1, read: TV3_R3,
      text: 'Tiếng mưa trong rừng cọ được so sánh với những âm thanh nào?',
      opts: o4('Tiếng trống và tiếng khèn', 'Tiếng chim và tiếng ve', 'Tiếng thác dội về và tiếng gió ào ào', 'Tiếng hát và tiếng cười'), ans: 'C',
      why: '“Như tiếng thác dội về / Như ào ào trận gió.” — hai hình ảnh so sánh liền nhau.' },
    { sec: 'Cảm thụ', name: 'Câu 3', pts: 1, read: TV3_R3,
      text: 'Hai câu thơ so sánh ấy giúp em hình dung tiếng mưa trong rừng cọ thế nào?',
      opts: o4('Buồn bã, não nề', 'Đều đều, ru ngủ', 'Nhỏ nhẹ, thưa thớt', 'Rất to, dồn dập, ào ạt'), ans: 'D',
      why: 'Thác dội và gió ào ào đều là âm thanh mạnh, dồn dập — nhờ đó ta “nghe” được cơn mưa rất lớn trên tán cọ.' },
    { sec: 'Cảm thụ', name: 'Câu 4', pts: 1, read: TV3_R3,
      text: 'Vì sao tác giả gọi lá cọ là <b>“mặt trời xanh”</b>?',
      opts: o4('Vì lá cọ xoè tròn, gân lá toả ra như những tia nắng, mà lại màu xanh', 'Vì lá cọ chỉ xanh khi có nắng', 'Vì lá cọ nóng như mặt trời', 'Vì lá cọ mọc quay về hướng mặt trời'), ans: 'A',
      why: 'Cái hay của hình ảnh nằm ở chỗ lá cọ giống hệt mặt trời về <i>hình dáng</i> (tròn, toả tia) nhưng khác về <i>màu sắc</i> (xanh chứ không đỏ).' },
    { sec: 'Nhân hoá', name: 'Câu 5', pts: 1, read: TV3_R3,
      text: 'Cách gọi “Rừng cọ ơi! Rừng cọ!” cho thấy điều gì?',
      opts: o4('Tác giả muốn chặt cây cọ', 'Tác giả sợ rừng cọ', 'Tác giả gọi rừng cọ thân thiết như gọi một người bạn', 'Tác giả đang bị lạc trong rừng'), ans: 'C',
      why: 'Gọi sự vật bằng từ dùng để gọi người (“ơi”) là một cách nhân hoá, thể hiện tình cảm gắn bó.' },
    { sec: 'Nghĩa của từ', name: 'Câu 6', pts: 1, read: TV3_R3,
      text: 'Từ <b>“ngời ngời”</b> trong “Lá đẹp, lá ngời ngời” gợi tả điều gì?',
      opts: o4('Lá đang rụng', 'Lá rất nhiều', 'Lá rất to', 'Lá sáng bóng, rực lên dưới nắng'), ans: 'D',
      why: '“ngời ngời” tả ánh sáng phát ra, rực rỡ — làm câu thơ sáng bừng lên.' },
    { sec: 'Cảm thụ', name: 'Câu 7', pts: 1, read: TV3_R3,
      text: 'Bài thơ nói lên tình cảm gì của tác giả?',
      opts: o4('Yêu rừng cọ, yêu quê hương mình', 'Nhớ bạn bè cũ', 'Thương những ngày mưa gió', 'Mong được đi xa'), ans: 'A',
      why: 'Cách gọi tha thiết “Rừng cọ ơi!” và cách nhận “mặt trời xanh <i>của tôi</i>” đều là tiếng nói của tình yêu quê.' },
    { sec: 'Từ loại', name: 'Câu 8', pts: 1,
      text: 'Trong cụm từ “mặt trời xanh”, từ “xanh” là từ chỉ gì?',
      opts: o4('Sự vật', 'Hoạt động', 'Đặc điểm', 'Thời gian'), ans: 'C',
      why: '“xanh” tả màu sắc nên là từ chỉ đặc điểm.' },
    { sec: 'So sánh', name: 'Câu 9', pts: 1,
      text: 'Câu thơ “Như tiếng thác dội về” dùng biện pháp nghệ thuật nào?',
      opts: o4('Không dùng biện pháp nào', 'Vừa so sánh vừa nhân hoá', 'Nhân hoá', 'So sánh'), ans: 'D',
      why: 'Có từ “như” nối hai âm thanh với nhau nên đây là biện pháp so sánh.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1, read: TV3_R3,
      text: 'Câu nào nêu cảm nghĩ về bài thơ một cách <b>hay</b> nhất?',
      opts: o4('Bài thơ có bốn khổ và nhiều chữ.', 'Em thích bài thơ vì tác giả đã gọi lá cọ là mặt trời xanh, một cách gọi vừa lạ vừa đẹp.', 'Bài thơ nói về cây cọ.', 'Em đã đọc bài thơ này hai lần.'), ans: 'B',
      why: 'Câu B nêu được <i>thích chỗ nào</i> và <i>vì sao thích</i>. Ba câu kia chỉ kể thông tin bên ngoài, chưa phải cảm nghĩ.' },
  ],
},

/* ═══════════ ĐỀ 4 — BIỆN PHÁP SO SÁNH ═══════════ */
{
  id: 1804, title: 'Đề 4 · Biện pháp so sánh — nhận biết và cái hay', time: 25,
  questions: [
    { sec: 'So sánh', name: 'Câu 1', pts: 1,
      text: 'Trong câu “Mặt biển sáng trong như một tấm thảm khổng lồ.”, sự vật nào <b>được</b> so sánh?',
      opts: o4('Tấm thảm', 'Mặt biển', 'Ánh sáng', 'Bầu trời'), ans: 'B',
      why: 'Sự vật được so sánh đứng trước từ “như”; “tấm thảm khổng lồ” là sự vật dùng để so sánh.' },
    { sec: 'So sánh', name: 'Câu 2', pts: 1,
      text: 'Từ so sánh trong câu “Trẻ em như búp trên cành.” là từ nào?',
      opts: o4('như', 'cành', 'Trẻ em', 'búp trên cành'), ans: 'A',
      why: 'Từ “như” là từ dùng để nối hai sự vật được đem ra so sánh.' },
    { sec: 'So sánh', name: 'Câu 3', pts: 1,
      text: 'Câu “Cháu khoẻ hơn ông nhiều!” thuộc kiểu so sánh nào?',
      opts: o4('So sánh ngang bằng', 'So sánh hơn kém', 'Nhân hoá', 'Không có so sánh'), ans: 'B',
      why: 'Từ “hơn” cho thấy hai bên <b>không</b> bằng nhau nên đây là so sánh hơn kém.' },
    { sec: 'So sánh', name: 'Câu 4', pts: 1,
      text: 'Câu nào là so sánh <b>ngang bằng</b>?',
      opts: o4('Bé cao hơn chị.', 'Hôm nay nắng hơn hôm qua.', 'Ông là buổi trời chiều.', 'Trăng khuya sáng hơn đèn.'), ans: 'C',
      why: 'Từ “là” nối hai vế và coi chúng như nhau nên là so sánh ngang bằng; ba câu kia đều có từ “hơn”.' },
    { sec: 'Cảm thụ', name: 'Câu 5', pts: 1,
      text: 'Hình ảnh so sánh trong câu “Những chùm hoa phượng như những đốm lửa nhỏ.” hay ở chỗ nào?',
      opts: o4('Cho biết cây phượng rất cao', 'Cho biết hoa phượng có nhiều cánh', 'Cho biết hoa phượng nở vào mùa hè', 'Giúp ta hình dung hoa phượng đỏ rực, cháy lên giữa vòm lá xanh'), ans: 'D',
      why: 'Cái hay của so sánh là làm hiện lên hình ảnh: màu đỏ của hoa được ví với lửa nên vừa rực rỡ vừa như đang cháy.' },
    { sec: 'So sánh', name: 'Câu 6', pts: 1,
      text: 'Trong câu “Tiếng suối trong như tiếng hát xa.”, hai sự vật được đem so sánh với nhau là:',
      opts: o4('Hai âm thanh', 'Hai con vật', 'Hai loài cây', 'Hai màu sắc'), ans: 'A',
      why: 'Tiếng suối và tiếng hát đều là âm thanh — đây là so sánh âm thanh với âm thanh.' },
    { sec: 'So sánh', name: 'Câu 7', pts: 1,
      text: 'Hình ảnh so sánh nào <b>hợp lí</b>?',
      opts: o4('Mắt bé tròn như quyển vở.', 'Mắt bé tròn như hai hòn bi ve.', 'Mắt bé tròn như cái bàn.', 'Mắt bé tròn như con đường.'), ans: 'B',
      why: 'Hai sự vật đem so sánh phải giống nhau ở một nét nào đó. Chỉ hòn bi ve mới vừa tròn vừa nhỏ vừa long lanh như mắt bé.' },
    { sec: 'Dùng từ', name: 'Câu 8', pts: 1,
      text: 'Điền từ so sánh thích hợp: “Cánh diều cong cong ______ vành trăng non.”',
      opts: o4('rồi', 'và', 'như', 'nhưng'), ans: 'C',
      why: 'Chỉ từ “như” mới nối được hai sự vật giống nhau về hình dáng cong cong.' },
    { sec: 'So sánh', name: 'Câu 9', pts: 1,
      text: 'Câu nào <b>không</b> có hình ảnh so sánh?',
      opts: o4('Trăng tròn như cái đĩa.', 'Trăng đã lên cao.', 'Trăng sáng như gương.', 'Trăng tròn như quả bóng.'), ans: 'B',
      why: 'Câu B chỉ kể một việc, không đem trăng ra so với sự vật nào.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1,
      text: 'Chọn cách viết <b>hay hơn</b> khi tả lá cọ:',
      opts: o4('Lá cọ rất to.', 'Lá cọ xoè ra như một bàn tay khổng lồ.', 'Lá cọ có màu xanh.', 'Cây cọ thì có lá.'), ans: 'B',
      why: 'Câu B dùng so sánh nên người đọc hình dung ngay được cả hình dáng lẫn kích thước của lá; ba câu kia chỉ nêu thông tin khô khan.' },
  ],
},

/* ═══════════ ĐỀ 5 — BIỆN PHÁP NHÂN HOÁ ═══════════ */
{
  id: 1805, title: 'Đề 5 · Biện pháp nhân hoá — ba cách và tác dụng', time: 25,
  questions: [
    { sec: 'Nhân hoá', name: 'Câu 1', pts: 1,
      text: 'Câu nào có sự vật được <b>nhân hoá</b>?',
      opts: o4('Mặt trời mọc ở đằng đông.', 'Hôm nay trời nắng to.', 'Mặt trời rất nóng.', 'Ông mặt trời đạp xe qua ngọn núi.'), ans: 'D',
      why: 'Mặt trời được gọi bằng “ông” và được tả bằng việc của người (“đạp xe”) nên đã được nhân hoá.' },
    { sec: 'Nhân hoá', name: 'Câu 2', pts: 1,
      text: 'Trong câu “Chị gió chăm chỉ quét lá sân trường.”, gió được nhân hoá bằng <b>mấy</b> cách?',
      opts: o4('Hai cách: gọi bằng “chị” và tả bằng việc làm của người', 'Không có nhân hoá', 'Ba cách', 'Một cách: chỉ gọi bằng “chị”'), ans: 'A',
      why: 'Vừa <i>gọi</i> sự vật bằng từ dùng để gọi người (chị), vừa <i>tả</i> bằng hoạt động của người (chăm chỉ quét lá).' },
    { sec: 'Nhân hoá', name: 'Câu 3', pts: 1,
      text: 'Câu “Bác kim giờ thận trọng nhích từng li.” nhân hoá kim giờ bằng cách nào?',
      opts: o4('So sánh kim giờ với một bác thợ', 'Gọi kim giờ bằng “bác” và tả bằng tính nết của người', 'Trò chuyện với kim giờ', 'Không nhân hoá'), ans: 'B',
      why: '“bác” là từ gọi người, “thận trọng” là tính nết của người — cả hai được gán cho chiếc kim đồng hồ.' },
    { sec: 'Nhân hoá', name: 'Câu 4', pts: 1,
      text: 'Câu “Trâu ơi, ta bảo trâu này…” nhân hoá con trâu bằng cách nào?',
      opts: o4('Nói chuyện với con vật như nói với một người bạn', 'Gọi trâu bằng “ông”', 'So sánh trâu với người', 'Tả trâu bằng từ chỉ màu sắc'), ans: 'A',
      why: 'Đây là cách nhân hoá thứ ba: <b>trò chuyện, xưng hô</b> với sự vật y như với con người.' },
    { sec: 'Nhân hoá', name: 'Câu 5', pts: 1,
      text: 'Từ nào làm cho cây tre được nhân hoá trong câu “Tre xanh đứng thẳng, hiên ngang giữa trời.”?',
      opts: o4('xanh', 'đứng', 'hiên ngang', 'giữa trời'), ans: 'C',
      why: '“hiên ngang” là phẩm chất của con người, đem gán cho cây tre nên tre thành ra có khí phách.' },
    { sec: 'Cảm thụ', name: 'Câu 6', pts: 1,
      text: 'Biện pháp nhân hoá có tác dụng gì?',
      opts: o4('Giúp đếm được số sự vật', 'Giúp câu văn đúng chính tả', 'Làm câu văn dài hơn', 'Làm sự vật trở nên sinh động, gần gũi như con người'), ans: 'D',
      why: 'Khi sự vật biết gọi, biết làm, biết nghĩ như người thì người đọc thấy chúng có hồn và thân thiết hẳn lên.' },
    { sec: 'Nhân hoá', name: 'Câu 7', pts: 1,
      text: 'Câu nào <b>không</b> dùng nhân hoá?',
      opts: o4('Đàn kiến rủ nhau về tổ.', 'Ông trời nổi giận đùng đùng.', 'Cây bàng cao hơn mái nhà.', 'Chị ong nâu chăm chỉ đi tìm mật.'), ans: 'C',
      why: 'Câu C chỉ so đo chiều cao, không gán cho cây bàng đặc điểm hay hành động nào của con người.' },
    { sec: 'Dùng từ', name: 'Câu 8', pts: 1,
      text: 'Điền từ để câu có <b>nhân hoá</b>: “Ông trời ______ chiếc áo giáp đen ra trận.”',
      opts: o4('mặc', 'có', 'là', 'bay'), ans: 'A',
      why: '“mặc áo giáp ra trận” là việc của con người; gán cho ông trời thì mây đen kéo tới bỗng thành một vị tướng.' },
    { sec: 'Nhân hoá', name: 'Câu 9', pts: 1,
      text: 'Trong câu “Cây gạo già mỗi năm lại trở lại tuổi xuân.”, từ ngữ nào làm cây gạo được nhân hoá?',
      opts: o4('mỗi năm', 'già, trở lại tuổi xuân', 'cây gạo', 'lại'), ans: 'B',
      why: '“già” và “trở lại tuổi xuân” vốn nói về đời người, đem dùng cho cây gạo nên cây như một con người có tuổi tác.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1,
      text: 'Viết lại câu “Mưa rơi.” cho <b>sinh động hơn</b> bằng nhân hoá:',
      opts: o4('Mưa rơi xuống đất.', 'Chị mưa tí tách gõ cửa từng nhà.', 'Mưa rơi rất nhiều.', 'Hôm nay trời mưa to.'), ans: 'B',
      why: 'Chỉ câu B gọi mưa bằng “chị” và cho mưa biết “gõ cửa” như người; ba câu kia chỉ thêm thông tin, không nhân hoá.' },
  ],
},

/* ═══════════ ĐỀ 6 — TỪ CHỈ ĐẶC ĐIỂM VÀ TỪ NGỮ GỢI TẢ ═══════════ */
{
  id: 1806, title: 'Đề 6 · Từ chỉ đặc điểm và từ ngữ gợi tả', time: 25,
  questions: [
    { sec: 'Từ loại', name: 'Câu 1', pts: 1, text: 'Từ nào là <b>từ chỉ đặc điểm</b>?',
      opts: o4('cánh đồng', 'gặt lúa', 'mênh mông', 'buổi chiều'), ans: 'C',
      why: '“mênh mông” tả độ rộng của cánh đồng nên là từ chỉ đặc điểm.' },
    { sec: 'Từ gợi tả', name: 'Câu 2', pts: 1, text: 'Từ nào <b>gợi tả âm thanh</b>?',
      opts: o4('xanh biếc', 'mềm mại', 'lấp lánh', 'ào ào'), ans: 'D',
      why: '“ào ào” mô phỏng tiếng gió, tiếng nước. “lấp lánh” gợi ánh sáng, hai từ kia gợi màu sắc và hình dáng.' },
    { sec: 'Từ gợi tả', name: 'Câu 3', pts: 1, text: 'Từ nào <b>gợi tả ánh sáng</b>?',
      opts: o4('long lanh', 'khúc khích', 'rì rào', 'thoang thoảng'), ans: 'A',
      why: '“long lanh” tả ánh sáng lấp lánh; “khúc khích” và “rì rào” gợi âm thanh, “thoang thoảng” gợi mùi hương.' },
    { sec: 'Dùng từ', name: 'Câu 4', pts: 1, text: 'Chọn từ gợi tả đúng nhất: “Hương lúa ______ bay trong gió chiều.”',
      opts: o4('chan chát', 'thoang thoảng', 'chói chang', 'ào ào'), ans: 'B',
      why: 'Mùi hương thì chỉ hợp với từ tả mùi. “thoang thoảng” là mùi nhẹ, thoảng qua.' },
    { sec: 'Dùng từ', name: 'Câu 5', pts: 1, text: 'Chọn từ gợi tả đúng nhất: “Mặt hồ ______ dưới ánh trăng.”',
      opts: o4('thoăn thoắt', 'khúc khích', 'lấp lánh', 'rì rào'), ans: 'C',
      why: 'Ánh trăng chiếu xuống mặt nước tạo ra những đốm sáng nhấp nháy — đúng là “lấp lánh”.' },
    { sec: 'Từ loại', name: 'Câu 6', pts: 1, text: 'Câu “Bạn Hoa vừa xinh xắn vừa nết na.” có mấy từ chỉ đặc điểm?',
      opts: o4('Ba từ', 'Không có từ nào', 'Một từ', 'Hai từ'), ans: 'D',
      why: 'Hai từ “xinh xắn” và “nết na” đều tả bạn Hoa.' },
    { sec: 'Nhóm từ', name: 'Câu 7', pts: 1, text: 'Từ nào <b>không cùng nhóm</b> với các từ còn lại?',
      opts: o4('đỏ thắm', 'vàng óng', 'xanh biếc', 'thánh thót'), ans: 'D',
      why: 'Ba từ đầu tả màu sắc, riêng “thánh thót” tả âm thanh.' },
    { sec: 'Cảm thụ', name: 'Câu 8', pts: 1, text: 'Vì sao câu “Nắng vàng như mật ong.” hay hơn câu “Nắng có màu vàng.”?',
      opts: o4('Vì hình ảnh so sánh làm nắng vừa có màu vàng, vừa gợi cảm giác ngọt ngào, sóng sánh', 'Vì câu ấy nói về loài ong', 'Vì câu ấy dài hơn', 'Vì câu ấy có nhiều dấu câu hơn'), ans: 'A',
      why: 'So sánh với mật ong mang thêm cả cảm giác về độ sánh và vị ngọt, chứ không chỉ nói về màu.' },
    { sec: 'Dùng từ', name: 'Câu 9', pts: 1, text: 'Câu nào dùng từ <b>chưa hợp</b>?',
      opts: o4('Dòng suối chảy róc rách.', 'Bông hoa nở róc rách.', 'Lá cờ bay phấp phới.', 'Tiếng chim hót líu lo.'), ans: 'B',
      why: '“róc rách” là tiếng nước chảy, không dùng để tả hoa nở được.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1, text: 'Câu nào tả cơn mưa <b>sinh động</b> nhất?',
      opts: o4('Trời mưa.', 'Mưa rơi xuống sân.', 'Mưa rào ào ào đổ xuống, gõ lộp bộp trên mái tôn.', 'Hôm nay có mưa.'), ans: 'C',
      why: 'Câu C có các từ gợi tả âm thanh (“ào ào”, “lộp bộp”) nên người đọc như nghe thấy cơn mưa.' },
  ],
},

/* ═══════════ ĐỀ 7 — CÂU VÀ BỘ PHẬN CÂU ═══════════ */
{
  id: 1807, title: 'Đề 7 · Câu và bộ phận câu — Khi nào? Ở đâu? Vì sao? Bằng gì?', time: 25,
  questions: [
    { sec: 'Mẫu câu', name: 'Câu 1', pts: 1, text: 'Câu “Đàn sếu đang sải cánh trên cao.” thuộc mẫu câu nào?',
      opts: o4('Vì sao?', 'Ai là gì?', 'Ai làm gì?', 'Ai thế nào?'), ans: 'C',
      why: 'Câu kể việc đàn sếu đang làm (sải cánh) nên thuộc mẫu “Ai làm gì?”.' },
    { sec: 'Bộ phận câu', name: 'Câu 2', pts: 1,
      text: 'Trong câu “Vì trời mưa to, chúng em phải nghỉ buổi tập.”, bộ phận trả lời câu hỏi <b>Vì sao?</b> là:',
      opts: o4('phải nghỉ', 'buổi tập', 'chúng em', 'Vì trời mưa to'), ans: 'D',
      why: 'Hỏi “Vì sao chúng em phải nghỉ buổi tập?” — trả lời: vì trời mưa to.' },
    { sec: 'Bộ phận câu', name: 'Câu 3', pts: 1,
      text: 'Trong câu “Bác thợ mộc đóng bàn bằng gỗ xoan.”, bộ phận trả lời câu hỏi <b>Bằng gì?</b> là:',
      opts: o4('bằng gỗ xoan', 'cái bàn', 'Bác thợ mộc', 'đóng bàn'), ans: 'A',
      why: 'Hỏi “Bác thợ mộc đóng bàn bằng gì?” — trả lời: bằng gỗ xoan.' },
    { sec: 'Bộ phận câu', name: 'Câu 4', pts: 1,
      text: 'Trong câu “Trên nương, mọi người đang gặt lúa.”, bộ phận trả lời câu hỏi <b>Ở đâu?</b> là:',
      opts: o4('lúa', 'Trên nương', 'mọi người', 'đang gặt'), ans: 'B',
      why: 'Hỏi “Mọi người gặt lúa ở đâu?” — trả lời: trên nương.' },
    { sec: 'Đặt câu hỏi', name: 'Câu 5', pts: 1,
      text: 'Đặt câu hỏi cho bộ phận in đậm: “Chúng em đến trường <b>bằng xe đạp</b>.”',
      opts: o4('Chúng em đến trường khi nào?', 'Chúng em đến trường ở đâu?', 'Chúng em đến trường bằng gì?', 'Vì sao chúng em đến trường?'), ans: 'C',
      why: '“bằng xe đạp” nói về phương tiện nên câu hỏi tương ứng là “bằng gì?”.' },
    { sec: 'Mẫu câu', name: 'Câu 6', pts: 1, text: 'Câu nào thuộc mẫu <b>Ai thế nào?</b>',
      opts: o4('Dòng sông quê em uốn khúc quanh làng.', 'Dòng sông quê em rất hiền hoà.', 'Dòng sông quê em là nơi bọn trẻ tắm mát.', 'Chiều chiều, em ra bờ sông chơi.'), ans: 'B',
      why: '“rất hiền hoà” nêu đặc điểm của dòng sông. Câu A và D thuộc mẫu “Ai làm gì?”, câu C thuộc mẫu “Ai là gì?”.' },
    { sec: 'Bộ phận câu', name: 'Câu 7', pts: 1,
      text: 'Trong câu “Mùa xuân, cây cối đâm chồi nảy lộc.”, bộ phận trả lời câu hỏi <b>Khi nào?</b> là:',
      opts: o4('cây cối', 'đâm chồi', 'nảy lộc', 'Mùa xuân'), ans: 'D',
      why: 'Hỏi “Khi nào cây cối đâm chồi nảy lộc?” — trả lời: mùa xuân.' },
    { sec: 'Đặt câu hỏi', name: 'Câu 8', pts: 1,
      text: 'Câu trả lời nào hợp với câu hỏi “<b>Vì sao</b> bạn Nam được cô khen?”',
      opts: o4('Bạn Nam được cô khen ở lớp.', 'Bạn Nam được cô khen sáng nay.', 'Vì bạn Nam đã giúp bạn bị ngã đứng dậy.', 'Bạn Nam được cô khen bằng lời nói.'), ans: 'C',
      why: 'Hỏi “vì sao” thì phải trả lời bằng nguyên nhân, thường mở đầu bằng “vì”, “do”, “nhờ”.' },
    { sec: 'Dùng từ', name: 'Câu 9', pts: 1,
      text: 'Điền từ thích hợp: “______ chăm học nên Nam tiến bộ rất nhanh.”',
      opts: o4('Nhờ', 'Tuy', 'Nhưng', 'Rồi'), ans: 'A',
      why: 'Vế sau nêu kết quả tốt nên vế trước phải nêu nguyên nhân bằng từ “Nhờ”. “Tuy”, “Nhưng” dùng khi hai vế trái ngược nhau.' },
    { sec: 'Bộ phận câu', name: 'Câu 10', pts: 1,
      text: 'Câu nào có bộ phận trả lời câu hỏi <b>Để làm gì?</b>',
      opts: o4('Em dậy sớm để ôn lại bài.', 'Em dậy sớm ở nhà bà.', 'Em dậy sớm bằng chuông báo thức.', 'Sáng nay, em dậy sớm.'), ans: 'A',
      why: '“để ôn lại bài” nêu mục đích của việc dậy sớm. Ba câu kia trả lời Khi nào? / Ở đâu? / Bằng gì?.' },
  ],
},

/* ═══════════ ĐỀ 8 — DẤU PHẨY · DẤU HAI CHẤM · DẤU NGOẶC KÉP ═══════════ */
{
  id: 1808, title: 'Đề 8 · Dấu phẩy — dấu hai chấm — dấu ngoặc kép', time: 25,
  questions: [
    { sec: 'Dấu câu', name: 'Câu 1', pts: 1,
      text: 'Dấu phẩy trong câu “Vườn nhà em trồng ổi, na, mít và bưởi.” dùng để làm gì?',
      opts: o4('Đánh dấu tên riêng', 'Ngăn cách các sự vật được kể ra', 'Báo hiệu lời nói', 'Kết thúc câu'), ans: 'B',
      why: 'Các loại cây được kể liên tiếp thì giữa chúng phải có dấu phẩy.' },
    { sec: 'Dấu câu', name: 'Câu 2', pts: 1,
      text: 'Dấu hai chấm trong câu “Mẹ dặn: “Con nhớ mặc áo ấm nhé!”” dùng để làm gì?',
      opts: o4('Kết thúc câu', 'Báo hiệu phía sau là lời nói của mẹ', 'Ngăn cách các ý kể ra', 'Đánh dấu câu hỏi'), ans: 'B',
      why: 'Dấu hai chấm báo trước rằng phần đứng sau là lời nói hoặc lời giải thích.' },
    { sec: 'Dấu câu', name: 'Câu 3', pts: 1,
      text: 'Dấu ngoặc kép trong câu trên dùng để làm gì?',
      opts: o4('Đánh dấu tên riêng', 'Ngăn cách hai vế câu', 'Bao lấy đúng lời mẹ đã nói', 'Thay cho dấu chấm'), ans: 'C',
      why: 'Dấu ngoặc kép dẫn lại nguyên văn lời nói trực tiếp của nhân vật.' },
    { sec: 'Dấu câu', name: 'Câu 4', pts: 1, text: 'Câu nào đặt dấu phẩy <b>đúng</b>?',
      opts: o4('Sáng nay lớp em, đi lao động.', 'Sáng nay, lớp em đi lao động.', 'Sáng, nay lớp em đi lao động.', 'Sáng nay lớp, em đi lao động.'), ans: 'B',
      why: 'Bộ phận trả lời câu hỏi “Khi nào?” đứng đầu câu thì tách khỏi phần còn lại bằng một dấu phẩy.' },
    { sec: 'Dấu câu', name: 'Câu 5', pts: 1, text: 'Câu nào đặt dấu phẩy <b>đúng</b>?',
      opts: o4('Trên cành cao, đôi chim sẻ ríu rít gọi nhau.', 'Trên, cành cao đôi chim sẻ ríu rít gọi nhau.', 'Trên cành cao đôi chim sẻ, ríu rít gọi nhau.', 'Trên cành cao đôi, chim sẻ ríu rít gọi nhau.'), ans: 'A',
      why: 'Bộ phận trả lời câu hỏi “Ở đâu?” đứng đầu câu cũng được tách bằng dấu phẩy.' },
    { sec: 'Dấu câu', name: 'Câu 6', pts: 1,
      text: 'Điền dấu câu thích hợp: “Cô giáo hỏi ___ “Hôm nay lớp mình vắng ai?””',
      opts: o4('dấu phẩy', 'dấu chấm', 'dấu hai chấm', 'dấu chấm than'), ans: 'C',
      why: 'Phía sau là lời cô giáo nói nên phải dùng dấu hai chấm để báo hiệu.' },
    { sec: 'Dấu câu', name: 'Câu 7', pts: 1,
      text: 'Dấu ngoặc kép trong câu “Em rất thích bài thơ “Mặt trời xanh của tôi”.” dùng để:',
      opts: o4('Ngăn cách các ý liệt kê', 'Báo hiệu lời giải thích', 'Dẫn lời nói của nhân vật', 'Đánh dấu tên một bài thơ'), ans: 'D',
      why: 'Ngoài việc dẫn lời nói, dấu ngoặc kép còn dùng để đánh dấu tên bài thơ, bài hát, quyển sách…' },
    { sec: 'Dấu câu', name: 'Câu 8', pts: 1, text: 'Câu nào dùng dấu câu <b>sai</b>?',
      opts: o4('Bà kể: “Ngày xửa ngày xưa…”.', 'Trong vườn có cam, quýt, bưởi.', 'Bạn có đi học không.', 'Ôi, đẹp quá!'), ans: 'C',
      why: 'Câu C là câu hỏi (có “không” ở cuối) nên phải kết thúc bằng dấu chấm hỏi, không phải dấu chấm.' },
    { sec: 'Dấu câu', name: 'Câu 9', pts: 1,
      text: 'Cần thêm mấy dấu phẩy vào câu: “Lớp em có Lan Mai Hùng và Nam đạt học sinh giỏi.”',
      opts: o4('Một dấu', 'Hai dấu', 'Ba dấu', 'Không cần dấu nào'), ans: 'B',
      why: 'Viết đúng là “Lan, Mai, Hùng và Nam” — hai dấu phẩy giữa ba tên đầu, tên cuối đã có từ “và” nối.' },
    { sec: 'Dấu câu', name: 'Câu 10', pts: 1, text: 'Cuối câu “Cảnh vườn quốc gia đẹp biết bao” nên đặt dấu gì?',
      opts: o4('Dấu chấm than', 'Dấu phẩy', 'Dấu chấm', 'Dấu chấm hỏi'), ans: 'A',
      why: 'Cụm “biết bao” bộc lộ cảm xúc nên đây là câu cảm, kết thúc bằng dấu chấm than.' },
  ],
},

/* ═══════════ ĐỀ 9 — TỪ CÙNG NGHĨA · TRÁI NGHĨA · MỘT TỪ NHIỀU NGHĨA ═══════════ */
{
  id: 1809, title: 'Đề 9 · Từ cùng nghĩa — trái nghĩa — một từ nhiều nghĩa', time: 25,
  questions: [
    { sec: 'Nghĩa của từ', name: 'Câu 1', pts: 1, text: 'Từ nào <b>cùng nghĩa</b> với “chăm chỉ”?',
      opts: o4('lười nhác', 'cần cù', 'nhanh nhẹn', 'vui vẻ'), ans: 'B',
      why: '“cần cù” và “chăm chỉ” đều khen người hay làm, hay học.' },
    { sec: 'Nghĩa của từ', name: 'Câu 2', pts: 1, text: 'Từ nào <b>trái nghĩa</b> với “đoàn kết”?',
      opts: o4('giúp đỡ', 'gắn bó', 'chia rẽ', 'thương yêu'), ans: 'C',
      why: 'Ba từ kia đều cùng hướng với “đoàn kết”; chỉ “chia rẽ” là ngược lại.' },
    { sec: 'Nghĩa của từ', name: 'Câu 3', pts: 1, text: 'Cặp từ nào là <b>cặp trái nghĩa</b>?',
      opts: o4('thông minh – sáng dạ', 'siêng năng – cần cù', 'dũng cảm – gan dạ', 'hiền lành – hung dữ'), ans: 'D',
      why: 'Ba cặp còn lại đều là hai từ cùng nghĩa.' },
    { sec: 'Nhiều nghĩa', name: 'Câu 4', pts: 1,
      text: 'Từ “chân” trong “chân bàn” và trong “chân em bị đau” giống nhau ở điểm nào?',
      opts: o4('Là một từ được dùng theo nhiều nghĩa: đều chỉ bộ phận ở phía dưới, dùng để đỡ', 'Đều chỉ bộ phận của cơ thể người', 'Đều chỉ đồ vật trong nhà', 'Là hai từ khác hẳn nhau, chỉ trùng cách viết'), ans: 'A',
      why: 'Chân người đỡ cả cơ thể, chân bàn đỡ mặt bàn — nghĩa gốc và nghĩa mở rộng có chỗ giống nhau.' },
    { sec: 'Nhiều nghĩa', name: 'Câu 5', pts: 1,
      text: 'Từ “ngọt” trong “giọng nói ngọt ngào” có nghĩa là gì?',
      opts: o4('Có vị như đường', 'Dễ nghe, êm tai, làm người khác thấy dễ chịu', 'Rất to', 'Rất nhanh'), ans: 'B',
      why: 'Ở đây “ngọt” không nói về vị mà nói về cảm giác dễ chịu khi nghe.' },
    { sec: 'Nhiều nghĩa', name: 'Câu 6', pts: 1,
      text: 'Từ “chạy” trong câu nào <b>không</b> chỉ việc di chuyển bằng chân?',
      opts: o4('Bé chạy tới ôm mẹ.', 'Em chạy quanh sân trường.', 'Chiếc đồng hồ chạy rất đúng giờ.', 'Đàn ngựa chạy trên thảo nguyên.'), ans: 'C',
      why: '“Đồng hồ chạy” nghĩa là đồng hồ hoạt động, không có chân nào cả.' },
    { sec: 'Nhiều nghĩa', name: 'Câu 7', pts: 1,
      text: 'Từ “lá” trong cụm nào <b>không</b> chỉ lá cây?',
      opts: o4('lá chuối', 'lá bàng', 'lá tre', 'lá cờ'), ans: 'D',
      why: '“lá cờ” mượn nghĩa của lá cây vì tấm vải cờ cũng mỏng và phẳng như một chiếc lá.' },
    { sec: 'Nghĩa của từ', name: 'Câu 8', pts: 1, text: 'Từ nào <b>trái nghĩa</b> với “bắt đầu”?',
      opts: o4('khởi đầu', 'mở màn', 'kết thúc', 'tiếp tục'), ans: 'C',
      why: '“khởi đầu”, “mở màn” đều cùng nghĩa với “bắt đầu”; chỉ “kết thúc” mới ngược lại.' },
    { sec: 'Dùng từ', name: 'Câu 9', pts: 1, text: 'Chọn từ dùng <b>đúng</b>: “Bạn Nam rất ______ khi nhận lỗi trước cả lớp.”',
      opts: o4('dũng cảm', 'dũng sĩ', 'hung dữ', 'liều lĩnh'), ans: 'A',
      why: 'Dám nhận lỗi là “dũng cảm”. “dũng sĩ” chỉ người, “liều lĩnh” và “hung dữ” đều mang nghĩa xấu.' },
    { sec: 'Dùng từ', name: 'Câu 10', pts: 1, text: 'Câu nào dùng từ <b>chưa chính xác</b>?',
      opts: o4('Chú bộ đội gan dạ, không sợ nguy hiểm.', 'Bạn Lan hung dữ, luôn giúp đỡ mọi người.', 'Anh trai em cần cù, chăm chỉ học hành.', 'Bà em hiền hậu, hay kể chuyện cổ tích.'), ans: 'B',
      why: '“hung dữ” là từ chê, không thể đi cùng việc tốt là “luôn giúp đỡ mọi người”; nên thay bằng “hiền lành”, “tốt bụng”.' },
  ],
},

/* ═══════════ ĐỀ 10 — MỞ RỘNG VỐN TỪ · THÀNH NGỮ, TỤC NGỮ ═══════════ */
{
  id: 1810, title: 'Đề 10 · Mở rộng vốn từ — thành ngữ, tục ngữ quen thuộc', time: 25,
  questions: [
    { sec: 'Mở rộng vốn từ', name: 'Câu 1', pts: 1, text: 'Từ nào chỉ việc làm <b>bảo vệ môi trường</b>?',
      opts: o4('săn bắt thú quý', 'chặt phá rừng', 'trồng cây gây rừng', 'xả rác bừa bãi'), ans: 'C',
      why: 'Ba việc kia đều làm hại môi trường.' },
    { sec: 'Mở rộng vốn từ', name: 'Câu 2', pts: 1, text: 'Từ nào chỉ <b>người trong cộng đồng</b>?',
      opts: o4('bàn ghế', 'chăm chỉ', 'quét dọn', 'hàng xóm'), ans: 'D',
      why: '“hàng xóm” là những người sống quanh nhà mình — thuộc chủ điểm cộng đồng.' },
    { sec: 'Thành ngữ', name: 'Câu 3', pts: 1, text: 'Điền từ còn thiếu: “Uống nước nhớ ______.”',
      opts: o4('nguồn', 'nhà', 'mẹ', 'bạn'), ans: 'A',
      why: '“Uống nước nhớ nguồn” nhắc ta biết ơn người đã làm ra thành quả mình đang hưởng.' },
    { sec: 'Tục ngữ', name: 'Câu 4', pts: 1,
      text: 'Điền từ còn thiếu: “Một cây làm chẳng nên non / Ba cây chụm lại nên hòn ______ cao.”',
      opts: o4('rừng', 'núi', 'đồi', 'cây'), ans: 'B',
      why: 'Câu đúng là “Ba cây chụm lại nên <b>hòn núi</b> cao”, khuyên phải đoàn kết mới làm được việc lớn.' },
    { sec: 'Tục ngữ', name: 'Câu 5', pts: 1, text: 'Điền từ còn thiếu: “Lá lành đùm ______.”',
      opts: o4('lá vàng', 'lá khô', 'lá rách', 'lá non'), ans: 'C',
      why: '“Lá lành đùm lá rách” khuyên người khá giả giúp đỡ người khó khăn.' },
    { sec: 'Thành ngữ', name: 'Câu 6', pts: 1, text: 'Câu nào nói về <b>tình bạn</b>?',
      opts: o4('Ăn quả nhớ kẻ trồng cây.', 'Buôn có bạn, bán có phường.', 'Chị ngã em nâng.', 'Học thầy không tày học bạn.'), ans: 'D',
      why: 'Câu D khuyên học hỏi ở bạn bè. Câu A nói lòng biết ơn, câu C nói tình chị em.' },
    { sec: 'Mở rộng vốn từ', name: 'Câu 7', pts: 1, text: 'Từ nào chỉ <b>nghề thủ công truyền thống</b>?',
      opts: o4('lái máy bay', 'lập trình', 'bán hàng online', 'nặn gốm'), ans: 'D',
      why: 'Nặn gốm là nghề thủ công có từ lâu đời ở nước ta (gốm Bát Tràng, gốm Chu Đậu…).' },
    { sec: 'Mở rộng vốn từ', name: 'Câu 8', pts: 1, text: 'Từ nào <b>không</b> thuộc chủ điểm “Trường học”?',
      opts: o4('thư viện', 'bảng đen', 'sân trường', 'chuồng trâu'), ans: 'D',
      why: 'Ba từ đầu đều là nơi hoặc đồ vật trong trường.' },
    { sec: 'Tục ngữ', name: 'Câu 9', pts: 1, text: 'Câu tục ngữ nào khuyên ta phải <b>đoàn kết</b>?',
      opts: o4('Đói cho sạch, rách cho thơm.', 'Một con ngựa đau, cả tàu bỏ cỏ.', 'Có công mài sắt, có ngày nên kim.', 'Ăn vóc học hay.'), ans: 'B',
      why: 'Câu B nói cả đàn cùng lo khi một con gặp nạn — đó là tinh thần gắn bó, đoàn kết.' },
    { sec: 'Thành ngữ', name: 'Câu 10', pts: 1,
      text: 'Câu “Có công mài sắt, có ngày nên kim.” khuyên em điều gì?',
      opts: o4('Kiên trì, chịu khó thì việc khó mấy cũng làm được', 'Nên mua kim thay vì mài sắt', 'Phải giữ gìn đồ dùng', 'Phải biết mài dao kéo'), ans: 'A',
      why: 'Thanh sắt to mà mài mãi cũng thành cây kim — hình ảnh ấy nói về lòng kiên trì.' },
  ],
},

/* ═══════════ ĐỀ 11 — LUYỆN VIẾT ĐOẠN ═══════════ */
{
  id: 1811, title: 'Đề 11 · Luyện viết đoạn — bố cục, ý và câu văn hay', time: 25,
  questions: [
    { sec: 'Sắp xếp ý', name: 'Câu 1', pts: 1,
      text: 'Sắp xếp thành đoạn văn kể lại buổi lao động của lớp:<br>(1) Chỉ một giờ sau, sân trường đã sạch bóng.<br>(2) Sáng thứ sáu, lớp em tổng vệ sinh sân trường.<br>(3) Các bạn nam quét lá, các bạn nữ nhặt rác.',
      opts: o4('(2) – (1) – (3)', '(2) – (3) – (1)', '(1) – (2) – (3)', '(3) – (1) – (2)'), ans: 'B',
      why: 'Kể theo thứ tự: giới thiệu việc → diễn biến → kết quả.' },
    { sec: 'Mở đoạn', name: 'Câu 2', pts: 1, text: 'Câu nào hợp làm câu <b>mở đầu</b> đoạn văn tả cơn mưa rào?',
      opts: o4('Mưa tạnh, bầu trời lại trong veo.', 'Chiều qua, một cơn mưa rào bất chợt đổ xuống làng em.', 'Nước chảy thành dòng trên sân.', 'Em rất thích những cơn mưa mùa hạ.'), ans: 'B',
      why: 'Câu mở đoạn giới thiệu chung: khi nào, ở đâu, chuyện gì. Câu A là ý cuối, câu D hợp làm câu kết.' },
    { sec: 'Kết đoạn', name: 'Câu 3', pts: 1, text: 'Câu nào hợp làm câu <b>kết</b> đoạn văn tả cơn mưa rào?',
      opts: o4('Chiều qua trời đổ mưa.', 'Mưa gõ lộp bộp trên mái tôn.', 'Sau cơn mưa, cây cối như được gột rửa, xanh mướt hẳn lên.', 'Gió thổi mạnh trước khi mưa.'), ans: 'C',
      why: 'Câu kết khép lại đoạn bằng cảnh vật sau cơn mưa và cảm nhận của người viết.' },
    { sec: 'Chọn ý', name: 'Câu 4', pts: 1, text: 'Câu nào <b>lạc ý</b> trong đoạn văn tả ngôi trường của em?',
      opts: o4('Trường em nằm ngay đầu làng.', 'Sân trường rợp bóng cây bàng.', 'Hôm qua em được mẹ mua cho một chiếc cặp mới.', 'Dãy lớp học sơn màu vàng nhạt.'), ans: 'C',
      why: 'Ba câu kia đều tả trường; câu C nói chuyện chiếc cặp nên phải bỏ ra khỏi đoạn.' },
    { sec: 'Bố cục', name: 'Câu 5', pts: 1, text: 'Một bài văn tả cảnh thường có mấy phần?',
      opts: o4('Một phần', 'Hai phần', 'Ba phần: mở bài, thân bài, kết bài', 'Bốn phần'), ans: 'C',
      why: 'Mở bài giới thiệu cảnh, thân bài tả chi tiết, kết bài nêu cảm nghĩ.' },
    { sec: 'Dùng từ', name: 'Câu 6', pts: 1, text: 'Chọn từ nối thích hợp: “Trời đã tối ______ các bác nông dân vẫn miệt mài gặt nốt thửa ruộng.”',
      opts: o4('vì', 'rồi', 'nên', 'nhưng'), ans: 'D',
      why: 'Hai vế trái ngược nhau (trời tối — vẫn làm việc) nên phải nối bằng “nhưng”.' },
    { sec: 'Lỗi diễn đạt', name: 'Câu 7', pts: 1, text: 'Câu nào mắc lỗi <b>lặp từ</b>?',
      opts: o4('Con mèo nhà em có bộ lông mượt, con mèo nhà em rất thích bắt chuột.', 'Chú mèo tam thể có bộ lông mượt như nhung.', 'Chú rất thích nằm sưởi nắng ngoài hiên.', 'Đôi mắt chú tròn xoe, sáng long lanh.'), ans: 'A',
      why: 'Cụm “con mèo nhà em” lặp hai lần trong một câu; nên thay lần thứ hai bằng “chú” hoặc “nó”.' },
    { sec: 'Luyện viết', name: 'Câu 8', pts: 1, text: 'Câu nào tả bà của em <b>hay</b> nhất?',
      opts: o4('Bà em năm nay sáu mươi tuổi.', 'Bà em có tóc.', 'Mái tóc bà bạc trắng như cước, búi gọn sau gáy.', 'Bà em ở cùng nhà em.'), ans: 'C',
      why: 'Câu C vừa tả cụ thể (bạc trắng, búi gọn) vừa có hình ảnh so sánh “như cước”.' },
    { sec: 'Sắp xếp ý', name: 'Câu 9', pts: 1,
      text: 'Khi tả một cây hoa, trình tự nào <b>hợp lí</b> nhất?',
      opts: o4('Giới thiệu cây → thân, lá → nụ và hoa → cảm nghĩ của em', 'Cảm nghĩ của em → giới thiệu cây → hoa', 'Lá → cảm nghĩ → gốc → hoa', 'Hoa → lá → thân → gốc → giới thiệu cây'), ans: 'A',
      why: 'Tả theo trình tự từ bao quát tới chi tiết, kết lại bằng cảm nghĩ — đó là bố cục ba phần quen thuộc.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1,
      text: 'Muốn đoạn văn tả cảnh sinh động hơn, em nên làm gì?',
      opts: o4('Viết thật nhiều câu dài', 'Dùng từ ngữ gợi tả và hình ảnh so sánh, nhân hoá', 'Kể thêm nhiều số liệu', 'Nhắc lại tên cảnh vật nhiều lần'), ans: 'B',
      why: 'Từ gợi tả giúp người đọc thấy – nghe được cảnh vật; so sánh và nhân hoá làm cảnh vật có hồn.' },
  ],
},

/* ═══════════ ĐỀ 12 — TỔNG HỢP ═══════════ */
{
  id: 1812, title: 'Đề 12 · Tổng hợp — đọc hiểu, cảm thụ và luyện từ câu', time: 25,
  questions: [
    { sec: 'Đọc hiểu', name: 'Câu 1', pts: 1, read: TV3_R4,
      text: 'Đôi chim sẻ làm tổ ở đâu?',
      opts: o4('Trong lồng của Bống', 'Trên cành cây trước nhà', 'Trong chậu cây trên sân thượng', 'Dưới mái hiên'), ans: 'C',
      why: '“…tha rơm về làm tổ trong chậu cây trên sân thượng nhà Bống.”.' },
    { sec: 'Đọc hiểu', name: 'Câu 2', pts: 1, read: TV3_R4,
      text: 'Mẹ dặn Bống điều gì?',
      opts: o4('Phải cho chim ăn mỗi ngày', 'Không được lên sân thượng nữa', 'Phải bắt chim non xuống nuôi', 'Chỉ được đứng xa nhìn, vì chim mẹ thấy động là bỏ tổ'), ans: 'D',
      why: 'Lời mẹ được dẫn nguyên văn trong dấu ngoặc kép ở giữa bài.' },
    { sec: 'Suy luận', name: 'Câu 3', pts: 1, read: TV3_R4,
      text: 'Vì sao Bống chỉ dám nấp sau cánh cửa để xem?',
      opts: o4('Vì Bống sợ chim mổ', 'Vì sân thượng quá nắng', 'Vì Bống nghe lời mẹ, sợ chim mẹ thấy động sẽ bỏ tổ', 'Vì cửa bị khoá'), ans: 'C',
      why: 'Bài viết “Bống nghe lời, chỉ dám nấp sau cánh cửa” — nối với lời dặn của mẹ ở câu trước.' },
    { sec: 'Cảm thụ', name: 'Câu 4', pts: 1, read: TV3_R4,
      text: 'Tác giả gọi tiếng chim non là “<b>cái dàn đồng ca bé xíu</b>”. Cách gọi ấy hay ở chỗ nào?',
      opts: o4('Gợi ra tiếng ba chú chim cùng kêu ríu rít, vui tai như một dàn hát nhỏ', 'Cho biết chim non hót rất to', 'Cho biết có đúng ba chú chim', 'Cho biết chim non rất đói'), ans: 'A',
      why: 'Ba chú chim cùng há mỏ kêu được ví với một dàn đồng ca, vừa gợi âm thanh rộn ràng vừa thấy chúng thật đáng yêu.' },
    { sec: 'Suy luận', name: 'Câu 5', pts: 1, read: TV3_R4,
      text: 'Vì sao Bống vẫn để nguyên cái tổ dù lũ chim đã bay đi?',
      opts: o4('Vì Bống lười dọn dẹp', 'Vì Bống mong sang năm đàn chim lại về làm tổ', 'Vì mẹ không cho dọn', 'Vì cái tổ rất đẹp'), ans: 'B',
      why: 'Câu cuối bài nói rõ: “…nhưng em vẫn để nguyên cái tổ ở đó, hi vọng sang năm chúng lại về.”.' },
    { sec: 'Ý chính', name: 'Câu 6', pts: 1, read: TV3_R4,
      text: 'Câu chuyện cho thấy Bống là một cô bé thế nào?',
      opts: o4('Nghịch ngợm, hay trèo cao', 'Biết yêu thương loài vật và biết nghe lời mẹ', 'Chỉ thích chơi một mình', 'Sợ chim chóc'), ans: 'B',
      why: 'Bống kiềm chế sự tò mò để không làm chim sợ, rồi còn giữ tổ chờ chim về — đó là tình yêu loài vật.' },
    { sec: 'Nghĩa của từ', name: 'Câu 7', pts: 1, read: TV3_R4,
      text: 'Từ <b>“rón rén”</b> trong bài gợi tả điều gì?',
      opts: o4('Đi loạng choạng', 'Vừa đi vừa hát', 'Đi thật nhẹ, khẽ khàng vì sợ gây tiếng động', 'Chạy thật nhanh'), ans: 'C',
      why: 'Bống sợ làm chim mẹ hoảng nên bước đi thật nhẹ — đó là “rón rén”.' },
    { sec: 'Bộ phận câu', name: 'Câu 8', pts: 1,
      text: 'Trong câu “Đầu hè, một đôi chim sẻ tha rơm về làm tổ.”, bộ phận trả lời câu hỏi <b>Khi nào?</b> là:',
      opts: o4('một đôi chim sẻ', 'tha rơm', 'Đầu hè', 'làm tổ'), ans: 'C',
      why: 'Hỏi “Khi nào đôi chim sẻ tha rơm về làm tổ?” — trả lời: đầu hè.' },
    { sec: 'Dấu câu', name: 'Câu 9', pts: 1, read: TV3_R4,
      text: 'Dấu ngoặc kép trong câu “Mẹ dặn: “Con chỉ được đứng xa nhìn thôi…”” dùng để làm gì?',
      opts: o4('Ngăn cách các ý kể ra', 'Thay cho dấu chấm than', 'Đánh dấu tên riêng', 'Dẫn lại đúng lời mẹ đã nói'), ans: 'D',
      why: 'Dấu hai chấm báo hiệu lời nói, dấu ngoặc kép bao lấy nguyên văn câu mẹ dặn.' },
    { sec: 'Luyện viết', name: 'Câu 10', pts: 1, read: TV3_R4,
      text: 'Câu nào nêu cảm nghĩ về câu chuyện <b>hay</b> nhất?',
      opts: o4('Câu chuyện có ba con chim non.', 'Em thích chi tiết Bống để nguyên cái tổ chờ chim về, vì nó cho thấy bạn ấy thương loài vật thật lòng.', 'Câu chuyện xảy ra vào mùa hè.', 'Em đã đọc câu chuyện này rồi.'), ans: 'B',
      why: 'Câu B chỉ ra <i>chi tiết mình thích</i> và <i>vì sao thích</i> — đó mới là cảm nghĩ; ba câu kia chỉ kể lại thông tin.' },
  ],
},

];

SUBJECTS.push({
  id: 'tviet3', name: 'Tiếng Việt — Đọc hiểu', short: 'Tiếng Việt 3', icon: '📝', grade: 3,
  exams: TV3_EXAMS, ready: true,
  heroTitle: 'Tiếng Việt lớp 3 — đọc hiểu sâu, cảm thụ, luyện từ và câu',
  heroMeta: '📚 12 đề &nbsp;•&nbsp; 120 câu &nbsp;•&nbsp; ⏱ 25 phút mỗi đề &nbsp;•&nbsp; bài đọc hiện kèm từng câu hỏi',
});
